### ISSUE TITLE
How to get pyright to find third-party libraries?

### ISSUE THREAD

**Issue by srp** [Microsoft/pyright#10]
I'm try to use the VSCode plugin and in my code where I have `import requests` it's giving the error: `Import 'requests' could not be resolved`.

I've created a file _pyrightconfig.json_ with the following:

```
{
  "typeshedPath": "~/git/typeshed",
  "pythonPath": "/usr/bin/python3"
}
```
I've also tried setting pythonPath to:

- /usr/lib/python3.7/site-packages/
- /usr/lib/python3.7/

None of those have seemed to have any impact on it finding the "requests" module.

**Comment by erictraut** [comment]
I think the problem is the path "~/git/typeshed". Pyright doesn't currently resolve "~", which is a shell convention. It supports both absolute and relative paths (i.e. relative to the config file).

**Comment by srp** [comment]
Ah, that makes sense, I should have thought to try that. Seems to be working now. Thanks!
