### ISSUE TITLE
Add a hint for unnecessary lambdas and a command to remove them

### ISSUE THREAD

**Issue by AmjadHD** [microsoft/pyright#1012]
[pylint](https://pylint.readthedocs.io/en/latest/technical_reference/features.html#format-checker-messages) detects unused lambdas

>unnecessary-lambda (W0108):
>--
>Lambda may not be necessary Used when the body of a lambda expression is a function call on the same argument list as the lambda itself; such lambda expressions are in all but a few cases replaceable with the function being called in the body of the lambda.

can you add a hint and the possibility to remove those unused lambdas e.g (`lambda x: f(x)` -> `f`) ?

**Comment by erictraut** [comment]
Pyright's diagnostic rules are focused on detecting bugs or potential bugs in code. I'm struggling to come up with any situation where an unnecessary lambdas would be indicative of a bug in the code. This is more of a style issue. There are many other style-related things that pylint enforces, so I recommend running pylint in conjunction with pyright/pylance to detect these issues.
