### ISSUE TITLE
Non-absolute python.pythonPath breaks imports

### ISSUE THREAD

**Issue by kiwixz** [microsoft/pyright#1014]
This is about vscode settings with pyright 1.1.69.

- `"python.pythonPath": "not-really-valid"` breaks vscode python stuff as expected.
- `"python.pythonPath": "python3"` satisfy vscode (it detects the interpreter version etc) but breaks imports of non-standard python system libraries in Pyright (no real hint on the problem, just `Import "foo" could not be resolved  -  Pyright (reportMissingImports)`.
- `"python.pythonPath": "/usr/lib/python3"` works as expected

---

Btw, why do we need this setting when we have `python.defaultInterpreterPath` ?  This causes duplication:
```
  "python.defaultInterpreterPath": "/usr/bin/python3",
  "python.pythonPath": "/usr/bin/python3",
```

**Comment by erictraut** [comment]
The "python.pythonPath" setting is defined by the Python extension, not by Pyright. Pyright will read it and honor it if it's present.

This setting will impact Pyright's import resolution, so if it's configured incorrectly, imports will not be resolved as expected.

The Python extension has deprecated this setting. It's still supported for backward compatibility, but at some point it will be going away completely. It has been replaced by a setting managed internally by the Python extension. Pyright (and other extensions that previously relied on the "python.pythonPath" setting) are now able to retrieve the path directly from the Python extension at runtime.

I don't know anything about the "python.defaultInterpreterPath" setting. I don't recall hearing about it before, and it's not a setting that Pyright uses. I also don't see it included in the [Python extension documentation](https://code.visualstudio.com/docs/python/settings-reference).

My recommendation is not to use "python.pythonPath" but instead use the Python extension's built-in interpreter selector. When you change your selection, this will update the extension's internal setting, and Pyright will use it.

**Comment by kiwixz** [comment]
I somehow managed to break stuff again... If I don't specify `python.pythonPath`, pyright seems to try using python 2...

The hidden `python.defaultInterpreterPath` does not seems to have any effect here.

### Without the option:
```
[Info  - 7:33:23 PM] Pyright language server 1.1.74 starting
...
[Info  - 7:33:23 PM] Background analysis(1) started
Received pythonPath from Python extension: python
```
Imports of system libraries are broken.

### With it:
```
[Info  - 7:36:06 PM] Pyright language server 1.1.74 starting
...
[Info  - 7:36:06 PM] Background analysis(1) started
Received pythonPath from Python extension: /usr/bin/python3
```
Imports of system libraries work.

**Comment by kiwixz** [comment]
Found something interesting: actually it works when the pyright extension reload the server...

The vscode `Pyright: Restart Server` does nothing for me, but toggling `pyright.disableOrganizeImports` (I just picked a random setting here) does trigger a reload and makes pyright detect the good python path.

**Comment by erictraut** [comment]
Are you using Pyright with VS Code or some other editor?

Like I mentioned above, I'm not familiar with `python.defaultInterpreterPath`. Neither Pyright nor Pylance read this setting, so it's unlikely to have any effect.

For details about how Pyright/Pylance perform import resolution, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/import-resolution.md).

**Comment by jakebailey** [comment]
Both pyright and pylance fetch the active interpreter directly from the Python extension, so we shouldn't have to worry about the default (as the extension should have already recognized nothing was set and provided it). I could be wrong, though.

**Comment by kiwixz** [comment]
I'm using vscode with pyright extension.

Well if I had to guess whats happening here:
- I open a python file
- pyright boots up and ask the python extension for python path, gets the "default" value: `python`
- the python extension somehow finds out that I actually wanted to use interpreter python3.6
- pyright does not get the updated path

**Comment by erictraut** [comment]
Pyright should receive a notification callback from the Python extension when the python path is updated. The last bullet point should read "pyright is informed by the Python extension that the python path has changed". You should see evidence of this in the Pyright logs. If you're not seeing this, please double check that you're running an up-to-date version of the Python extension.

**Comment by kiwixz** [comment]
I do have the latest version, and confirm this is 100% reproducible on another machine running another OS.

```
[Info  - 7:51:17 PM] Pyright language server 1.1.74 starting
[Info  - 7:51:17 PM] Server root directory: c:\Users\u\.vscode\extensions\ms-pyright.pyright-1.1.74\dist
Received pythonPath from Python extension: python
[Error - 7:51:17 PM] stubPath c:\Users\u\Desktop\typings is not a valid directory.
```

**Comment by jakebailey** [comment]
Hm, so one thing that might have also gone wrong here in the recent release is that I fixed the config paths to be relative to the workspace if not absolute (previously they might have been relative to... who knows what). But if the default is just "python" we'll view to be relative and then gets set to `/path/to/workspace/python`.

This doesn't change the fact that Pyright is supposed to be getting told about interpreter updates, though. It was my impression that once Python extension selects an interpreter, it's going to be working with a fully resolved path.

**Comment by erictraut** [comment]
I just double-checked, and I confirmed that Pyright is receiving the callback as expected. When I switch Python environments in the Python extension, the Output log for Pyright shows that it receives the updated python path.

**Comment by kiwixz** [comment]
Okay, if I changed interpreter and put it back on my second machine and it suddenly works now too.  I guess there is some problem in the Python extension if user didn't update the interpreter manually since the switch to a hidden setting...
