### ISSUE TITLE
dataclass_json

### ISSUE THREAD

**Issue by fxdave** [microsoft/pyright#1035]
There's a very helpful package named dataclass_json: https://pypi.org/project/dataclasses-json/

It allows us to serialize and deserialize classes using json
```python
@dataclass_json
@dataclass
class Something:
    param1: float
    param2: float
    param3: float
```

Unfortunately, Pyright doesn't handle it well:

```python

# Argument missing for parameter "cls"Pyright (reportGeneralTypeIssues)
Something(
    # No parameter named "param1"Pyright (reportGeneralTypeIssues)
    param1=123.0,
    # No parameter named "param2"Pyright (reportGeneralTypeIssues)
    param2=123.0,
    # No parameter named "param3"Pyright (reportGeneralTypeIssues)
    param3=123.0
)

# but this works:
Something.from_json(data)
```

And when I move my mouse over the class name, I get:
```python
def wrap(cls)
```

If it's hard to check, it's better to get nothing than getting errors.

**Comment by erictraut** [comment]
This is a bug in the `dataclasses_json` package. It claims to be type-annotated (it contains a `py.typed` marker), but it omits critical type annotations. Notably, it's omitting the type annotation for the `dataclass_json` decorator. Pyright is doing its best to deal with the lack of type information here by using type inference, but it's hitting the limits of what's possible with inference. When a package claims to be type-annotated, it's really important for it to be "type complete", especially where decorators are concerned.

I recommend that you file a bug report for the `dataclasses_json` library or submit a PR to fix this.

I'm working to implement a mode within the CLI version of pyright that will help library authors detect "holes" in their type annotations such as this one. This situation is not uncommon today. That's understandable given the lack of tooling to help enforce type completeness.

**Comment by erictraut** [comment]
Thinking about this a bit more, I've come up with a solution that should help you out here. I've filed a separate issue to track this: https://github.com/microsoft/pyright/issues/1036

**Comment by fxdave** [comment]
Thanks, this #1036 feature will be awesome!
