### ISSUE TITLE
Support for folding-range requests

### ISSUE THREAD

**Issue by leungbk** [microsoft/pyright#1037]
**Is your feature request related to a problem? Please describe.**
The Pyright server does not presently report [folding ranges](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_foldingRange).

**Describe the solution you'd like**
It would be nice if the server reported folding ranges following the LSP spec.

**Comment by erictraut** [comment]
Thanks for the feature request. 

If we were to implement this, it would be done in pylance, not in pyright. I've opened a new feature request in the pylance-release repo so it gets the proper attention there.
