### ISSUE TITLE
False reportUnusedVariable in list comprehension returning class

### ISSUE THREAD

**Issue by leonardon473** [microsoft/pyright#1041]
**Describe the bug**
At create a list comprehension that return _DeliveryIntent: Type[Any]_ pyright don't recognize variable access

**Expected behavior**
"first_intent" is not accessed, "internal_error" is not accessed, "opp" is not accessed must be removed.

**Screenshots or Code**
![Code](https://i.ibb.co/WxnFvXn/Captura-de-Pantalla-2020-09-16-a-la-s-16-54-37.png)
![Code](https://i.ibb.co/Jscy7gw/Captura-de-Pantalla-2020-09-16-a-la-s-16-59-39.png)

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? VS Code extension
Which version?  v1.1.72

**Comment by erictraut** [comment]
I'm not able to repro this problem. I suspect there's additional context I need. 

Could you please do the following:
1. Look in the Output tab for Pyright and see if there are any clues. In particular, is there any indication that the Pyright extension crashed?
2. Can you try to create a minimal, self-contained example that exhibits the problem?

Thanks!

**Comment by erictraut** [comment]
@leonardon473, without additional details, I won't be able to address this problem. I'm going to close it for now, but please feel free to re-open it if you can still repro it and can offer more details. Thanks!
