### ISSUE TITLE
Pyright attempts to read generated stubs from root

### ISSUE THREAD

**Issue by layday** [microsoft/pyright#1052]
**Describe the bug**
Using the default `stubPath` and after generating a stub file, when attempting to navigate to it in VS Code, Pyright throws an I/O error that it is unable to read `/typings/[...].pyi` (note the initial slash).

**To Reproduce**
1. Install an untyped package
2. Use 'Quick fix' in VS Code to generate stubs
3. 'Go to definition' of a symbol in the package (cmd- or ctrl-click on it or select and hit F12)
4. Select the .pyi file from the sidebar

**Expected behavior**
That the stub path would be relative to the project root or `pyrightconfig.json`.

**Screenshots or Code**
<img width="1142" alt="Screenshot 2020-09-22 at 15 18 34" src="https://user-images.githubusercontent.com/31134424/93882296-b22b0f00-fce8-11ea-9bc5-8226dce583db.png">

**VS Code extension or command-line**
Extension, 1.1.73

**Comment by erictraut** [comment]
@jakebailey I think this is related to another bug that was reported against pylance and has to do with a change you made a few weeks ago with the default value of the `stubPath` setting. Have you fixed that already?

**Comment by jakebailey** [comment]
Yes, this is likely microsoft/pylance-release#326. The stubPath setting isn't getting rooted relative to the workspace root when set if it's not absolute; the old default was the empty string that internally defaulted to a correctly rooted path. I have a fix I'm going to submit in a few to Pylance (and sync it back before our release).

**Comment by jakebailey** [comment]
This is fixed in Pylance, so will be fixed here once we sync next (likely tomorrow before our release).

**Comment by erictraut** [comment]
This is now addressed in Pyright 1.1.74, which I just published. It will also be included in the next release of Pylance.
