### ISSUE TITLE
Tagged union-like narrowing

### ISSUE THREAD

**Issue by layday** [microsoft/pyright#1054]
TypeScript supports an idiom on interfaces and type aliases and mypy on `TypedDict`s where they can be narrowed based on the value of a shared key in a union of objects or dictionaries ([mypy example](https://mypy-play.net/?mypy=latest&python=3.8&gist=470d54e1297c81a2f1de679f942df9d4)).  This is useful, in TS in particular where support is substantially more comprehensive, for discriminating unions without explicit typing.  Would you consider supporting something similar in Pyright?

**Comment by erictraut** [comment]
Pyright already supports this for dataclass types. It doesn't support it for typed dicts.

```python
from typing import Literal, TypedDict, Union, cast
from dataclasses import dataclass

@dataclass
class Foo:
    tag: Literal["foo"]
    some_key: str

@dataclass
class Bar:
    tag: Literal["bar"]
    some_key: int

foo_or_perhaps_bar = cast(Union[Foo, Bar], {})
if foo_or_perhaps_bar.tag == "foo":
    reveal_type(foo_or_perhaps_bar)
    foo_or_perhaps_bar.some_key = 1
    foo_or_perhaps_bar.some_key = "1"
```

**Comment by layday** [comment]
Oh, that's great, I hadn't realised it works that way with data classes.  I wonder if this can be applied to classes generically.  Perhaps with the addition of `Annotated` in 3.9.

**Comment by erictraut** [comment]
Actually, it works with any class already. The narrowing applies to all member access expressions.

After thinking about it further, I don't think it would be a good idea to add similar support for TypedDict. We currently don't have any narrowing based on indexed expressions, and adding this would require tracking a bunch of extra information in the code flow graphs, which would measurably increase memory usage and runtime performance of the type analyzer. That's probably not a good tradeoff given that this feature would be used very infrequently.
