### ISSUE TITLE
argument type 'Unknown' in lambda definition

### ISSUE THREAD

**Issue by iqxd** [microsoft/pyright#1095]
**Screenshots or Code**

f :Callable[[int],int]= lambda m : m**2

# vscode tooltip show    (variable)  f : (m: Unknown ) -> int
# using latest pylance plugin

**Comment by erictraut** [comment]
Thanks for reporting the problem. This will be fixed in the next release.

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.79, which I just published. It will be in the next release of pylance as well.
