### ISSUE TITLE
Typehints with classes specified with strings do not work

### ISSUE THREAD

**Issue by PetterS** [Microsoft/pyright#11]
Example code:
```
from typing import Optional

def f() -> Optional["K"]:
    return K()

class K:
    def __init__(self):
        self.x = 1
```

Pyright tells me (under `K()`):

> Expression of type 'K' cannot be assigned to return type 'Optional[str]'

This kind of type hint works with mypy. Is there a workaround?

**Comment by erictraut** [comment]
Yeah, that's a known limitation currently. The approach I initially took makes it difficult to support type hints that are only partly within quotes. I didn't notice until after I had implemented it that PEP 484 specifically allows this mixed case. It's on my list of things to address, but it's relatively low priority. The workaround in the meantime is to enclose the entire type annotation in quotes, which should work with both Mypy and Pyright. 

I'll leave this issue open as a reminder to fix this at some point.

**Comment by erictraut** [comment]
I just implemented this support. It will be in the next release (1.0.12).

**Comment by erictraut** [comment]
Version 1.0.12 is now published.
