### ISSUE TITLE
Type[Iterable[int]]' is incompatible with 'Type[List[int]]

### ISSUE THREAD

**Issue by YorigamiShion** [Microsoft/pyright#110]
**Describe the bug**
I want to make a class decorator for cache the result of those function which input is Iterable[T] and output is Dict[T, Any], but it reports an error.

**Expected behavior**
`issubclass(List, Iterable)` is True and I think List[T] should be subclass of Iterable[T] either.

**Screenshots or Code**
```python
from typing import Any, Callable, Dict, Generic, Iterable, List, TypeVar

T = TypeVar('T')

class MyCache(Generic[T]):
    def __init__(self, func: Callable[[Iterable[T]], Dict[T, Any]]):
        self.func = func

    def __call__(self, arg: Iterable[T]):
        # ... some cache process
        result = self.func(arg)
        # ... other process
        return result

'''
Argument of type '(s: List[int]) -> Dict[str, int]' cannot be assigned to parameter of type '(p0: Iterable[T]) -> Dict[T, Any]'
   Parameter 1 of type '[object Object]' cannot be assigned to type'[object Object]'.
    'Type[Iterable[int]]' is incompatible with 'Type[List[int]]'pyright
'''
@MyCache   # error here
def list_func(s: List[int]) -> Dict[str, int]:
    return {str(i): i for i in s}
```

**VS Code extension or command-line**
VS Code extension of 1.0.23

**Comment by erictraut** [comment]
Although it might be counterintuitive, this is a type violation and pyright is correctly reporting an error. If you're interested in the details, check out [PEP 483](https://www.python.org/dev/peps/pep-0483/). It states:
```
One of the best examples to illustrate (somewhat counterintuitive) contravariant behavior is the callable type. It is covariant in the return type, but contravariant in the arguments.
```

Let me try to explain using your example. The function `list_func` indicates that it requires a parameter of type `List`. The `__call__` method in the `MyCache` class is passing it an `Iterable` argument, which may or may not be a list. It could be a tuple, a set, or any other iterable type. If you were to pass any of these other iterable types to `list_func`, it could crash. If `list_func` is fine accepting a parameter of type `Iterable`, you can change the type annotation on parameter `s`, and that will make the error disappear.

There is a bug in the error message, which I will fix. It should say:
```
Argument of type '(s: List[int]) -> Dict[str, int]' cannot be assigned to parameter of type '(p0: Iterable[T]) -> Dict[T, Any]'
   Parameter 1 of type 'Iterable[int]' cannot be assigned to type 'List[int]'.
    'Type[Iterable[int]]' is incompatible with 'Type[List[int]]'
```

**Comment by erictraut** [comment]
The bug in the error message is now fixed in 1.0.24

**Comment by YorigamiShion** [comment]
> Although it might be counterintuitive, this is a type violation and pyright is correctly reporting an error. If you're interested in the details, check out [PEP 483](https://www.python.org/dev/peps/pep-0483/). It states:
> 
> "
> One of the best examples to illustrate (somewhat counterintuitive) contravariant behavior is the callable type. It is covariant in the return type, but contravariant in the arguments.
> "
> 
> Let me try to explain using your example. The function `list_func` indicates that it requires a parameter of type `List`. The `__call__` method in the `MyCache` class is passing it an `Iterable` argument, which may or may not be a list. It could be a tuple, a set, or any other iterable type. If you were to pass any of these other iterable types to `list_func`, it could crash. If `list_func` is fine accepting a parameter of type `Iterable`, you can change the type annotation on parameter `s`, and that will make the error disappear.
> 
> There is a bug in the error message, which I will fix. It should say:
> 
> ```
> Argument of type '(s: List[int]) -> Dict[str, int]' cannot be assigned to parameter of type '(p0: Iterable[T]) -> Dict[T, Any]'
>    Parameter 1 of type 'Iterable[int]' cannot be assigned to type 'List[int]'.
>     'Type[Iterable[int]]' is incompatible with 'Type[List[int]]'
> ```

Thank you, I understood the actual called argument incorrectly.

Is there any way to assume the argument type in `Callable` and `__call__` is the some subtype of `Iterable[T]`? Just like `U extends Collection<T>` in java.

```java
public class MyCache<K, V, U extends Collection<K>> {
    private Function<U, Map<K, V>> function;
    public MyCache(Function<U, Map<K, V>> function) {
        this.function = function;
    }
    public Map<K, V> call(U arg) {
        // ...
        Map<K, V> result = function.apply(arg);
        // ...
        return result;
    }
}
```

**Comment by erictraut** [comment]
I unfortunately don't see a way to do this using the Python type annotation system. The reason it works in Java (and would likewise work in other languages like Typescript) is because the "extend" operator allows one type variable to refer to other type variables (like "K" in your example above). In Python, the closest equivalent to "extends" is a "bound" type variable (e.g. `T = TypeVar('T', bound=Iterable)`). But a type variable isn't allowed to refer to another type variable in its definition.
