### ISSUE TITLE
inherited class attributes aren't properly resolved in parent constructor

### ISSUE THREAD

**Issue by hiaselhans** [microsoft/pyright#1107]
**Describe the bug**

When a class attribute is used in a constructor, the class attribute should be resolved in the context of the derived class, if that derived class is being constructed.

```
18:27 - error: Cannot access member "attribute2" for type "AConf"
    Member "attribute2" is unknown (reportGeneralTypeIssues)
```

**To Reproduce**

use the codesample and run pyright (command line)

**Expected behavior**

attribute2 should be a member of B.config

**Screenshots or Code**

```python
class AConf:
    attribute1 = 123

class A:
    DefaultConf = AConf
    def __init__(self):
        self.config = self.DefaultConf()

class BConf(AConf):
    attribute2 = 234

class B(A):
    DefaultConf = BConf

    def test(self):
        print(self.config.attribute2)
```

**VS Code extension or command-line**

pyright 1.1.78 (command line)

**Additional context**

---

**Comment by erictraut** [comment]
This is correct behavior. The code is not declaring the types of any variable types, so the types are inferred based on assignments. The `config` variable is assigned the type `AConf`, so that's what its type is inferred to be.

If you want to stick with this pattern, you would need to make `A` a generic class, like this:

```python
class AConf:
    attribute1 = 123

_T = TypeVar("_T", bound=AConf)

class A(Generic[_T]):
    DefaultConf: Type[_T] = AConf

    def __init__(self):
        self.config: _T = self.DefaultConf()

class BConf(AConf):
    attribute2 = 234

class B(A[BConf]):
    DefaultConf = BConf

    def test(self):
        print(self.config.attribute2)
```
