### ISSUE TITLE
Type narrowing for "in" operator when RHS contains literals

### ISSUE THREAD

**Issue by pawelrubin** [microsoft/pyright#1113]
**Is your feature request related to a problem? Please describe.**

Consider this piece of code:
```python
from typing import Literal, Optional


def get_foo(foo: str) -> Optional[Literal["foo", "bar"]]:
    if foo in ("foo", "bar"):
        return foo  # <- Type "str" cannot be assigned to type "Literal['foo', 'bar'] | None"
    return None
```

**Describe the solution you'd like**
It'd be swell if **PyRight** could inference the type from the previous assertion in the `if` statement.

**Comment by erictraut** [comment]
Thanks for submitting the enhancement request.

I changed the title of your request to better reflect what you're asking for. This isn't "type inference". It's a technique called "conditional type narrowing". You are suggesting that the type of `foo` (which is initially `str`) could be "narrowed" to the type `Union[Literal["foo", "bar"]]` based on the conditional check.

There are about a dozen other specific conditions under which pyright performs conditional type narrowing. This particular pattern isn't one of them. I'll need to think about whether this pattern is common enough to justify adding custom logic for it.

**Comment by erictraut** [comment]
After thinking about this, I don't think the added logic and complexity it would add is merited given how infrequent this case is likely to be.
