### ISSUE TITLE
Infer type of empty dict from other ternary operand

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#1121]
**Is your feature request related to a problem? Please describe.**

```python
from typing import Dict, List

def extract_tags(config: Dict[str, Dict[str, str]]) -> List[Dict[str, str]]:
    additional_tags = config["additional_tags"] if config.get("additional_tags", None) else {}
    tags = [{"Key": k, "Value": v} for k, v in additional_tags.items()]
    return tags
```

Errors with:
```
  6:12 - error: Expression of type "List[Dict[str, str | Any]]" cannot be assigned to return type "List[Dict[str, str]]"
    TypeVar "_T" is invariant
      TypeVar "_VT" is invariant
        Type "str | Any" cannot be assigned to type "str" 
```

Because `{}` is inferred as `Dict[Any, Any]` and therefore `additional_tags` is `Dict[str, str] | Dict[Any, Any]`

**Describe the solution you'd like**

The type error can be resolved with type hints:
```
    additional_tags: Dict[str, str] = config["additional_tags"] if config.get("additional_tags", None) else {}
```

Would it be possible to infer the type of an empty dict from the other ternary operand (ie: `Dict[str, str]`) so type hints aren't necessary? This is the case in languages like Scala.

**Additional context**

pyright 1.1.81

**Comment by tekumara** [comment]
Actually, in this particular case, `additional_tags = config.get("additional_tags", {})` is probably the better solution. The type is inferred as `Dict[str, str]`.

**Comment by erictraut** [comment]
This would introduce inconsistencies in the way Pyright infers dictionary types. It would also presumably need to be bidirectional (where the type of the `if` value is influenced by the type of the `else` value and vice versa). This case doesn't arise very often, and there is an easy and straightforward workaround.
