### ISSUE TITLE
Semantic Highlighting - Modifier for Built-In Functions

### ISSUE THREAD

**Issue by raptor494** [microsoft/pyright#1138]
**Is your feature request related to a problem? Please describe.**
Before I installed this extension, I had a theme that automatically colored the Python built-in functions differently than regular functions. With semantic highlighting enabled, the built-in functions look no different than user-defined functions, and there currently isn't a way to disable semantic highlighting on a per-token basis.

**Describe the solution you'd like**
I would like it so that the tokens for the built-in functions (print, dir, vars, open, etc.) get an extra modifier added to them, such as the standard 'defaultLibrary' modifier, so I can adjust my settings to make them colored differently.

**Comment by erictraut** [comment]
The Pyright VS Code extension doesn't implement semantic highlighting support. If you want that functionality, you should install Pylance, which is built using the core pyright static type checker but also adds features like semantic tokens.
