### ISSUE TITLE
github action

### ISSUE THREAD

**Issue by oshriPP** [microsoft/pyright#1141]
There is a GitHub Action for pyright?

**Comment by erictraut** [comment]
Please refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/ci-integration.md) for CI integration instructions.

**Comment by brettcannon** [comment]
Without diving into [Pyright's internals](https://github.com/microsoft/pyright/blob/master/docs/internals.md) to see if there's a direct way to call the analyzer and get the results, I suspect that an Action could be written without too much effort using Pyright's [JSON output](https://github.com/microsoft/pyright/blob/master/docs/command-line.md#json-output) and [GitHub's `@actions/exec`](https://github.com/actions/toolkit/tree/main/packages/exec). Then you can use [workflow commands](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message) via [`@actions/core` and its `issueCommand()` function](https://github.com/actions/toolkit/tree/main/packages/core) to annotate PRs with any warning and errors found.

**Comment by jakebailey** [comment]
I worked on this in my free time and published a prototype action here: https://github.com/marketplace/actions/run-pyright

It's a thin wrapper around running the CLI, with the GHA API calls to also put the messages into commit/PR comments. It appears to work pretty well: https://github.com/jakebailey/pyright-action-test/pull/1/files

(Pretty experimental; I haven't written tests yet... 🙂)
