### ISSUE TITLE
Improve formatting of parameter hints for functions with long signatures

### ISSUE THREAD

**Issue by matangover** [microsoft/pyright#1144]
**Is your feature request related to a problem? Please describe.**
When calling a function with many parameters that have complex types, it's almost impossible to understand what parameters the function accepts, because the list is long and the (long) types are between parameter names, making it visually hard to distinguish the parameter names.

**Describe the solution you'd like**
I can think of several solutions:
1. When a parameter's type is longer than X characters, truncate it somehow.
2. When the signature is long, put each parameter on a separate line.
3. Use colors or formatting (is this possible in VS Code?), e.g. bold for the parameter names

**Additional context**
![image](https://user-images.githubusercontent.com/5028956/98284001-c416f780-1fa0-11eb-8f0b-4512f332d8e6.png)

**Comment by jakebailey** [comment]
Signature help is unfortunately limited to plaintext only by the language server protocol, so we can't actually add any colors to this tooltip (versus hover and completion where we can).

We also don't get any info from the client to know how big the tooltip might be to know how to wrap, but VS Code is actually in its next version adding fully resizable tooltips, which make some of this a bit easier (and potentially render differently even compared to the above).

**Comment by jakebailey** [comment]
Just to clarify, the signature info does have markdown support, but only for the doc. The signature itself is special because it needs to be segmented such that each part can be highlighted when active.
