### ISSUE TITLE
Feature Request: Highlight unnecessary "# type: ignore" or `typing.cast` annotations

### ISSUE THREAD

**Issue by PetrochukM** [microsoft/pyright#1145]
**Is your feature request related to a problem? Please describe.**
`typing` is relatively new to the Python community and in order to get past typing limitations, we've been encouraged to use `type: ignore` for now. As `typing` is matured... we'll find that `type: ignore` becomes less necessary. 

**Describe the solution you'd like**
It'd be nice to know if `type: ignore` isn't ignoring anything, anymore. This will help codebases remove `type: ignore` as `typing` issues are fixed. For example, once `numpy` incorporates typing, I'll need to triple check every `type: ignore` that involved `numpy`.

**Comment by erictraut** [comment]
Yeah, I recommend that you don't ever use `# type: ignore`. There's always a better way to work around type-related issues including adding additional annotations, adding assert statements, and (if no other technique works) using a call to `cast` or an `Any` annotation. I added the `enableTypeIgnoreComments` setting in pyright specifically because I never want to see `# type: ignore` used in my team's code base.

**Comment by PetrochukM** [comment]
Thanks for the feedback, and I'm generally aware of `cast`, `assert`, etc. 

However, in limited cases, I'm still stuck. For example, a number of modules we are working with are not typed. `pandas`, `spacy`, `matplotlib`, and `numpy` are not typed, and it's going to be a couple of months until they are. Our small team doesn't have the bandwidth to create stub files, so we rely on `#type: ignore`, in some scenarios. 

Apart from that... this feature would help us transition away from `mypy` to `pyright`. `mypy` has a number of issues that required us to use `# type: ignore`. For example, `mypy` doesn't support recursive typing or variable-length argument typing. A feature like this would be able to help us remove unessecary `# type: ignore` comments after deprecating `mypy`.

**Comment by SeparateRecords** [comment]
This feature would also be useful for testing type. Things that shouldn't work would produce an error if they do.

**Comment by erictraut** [comment]
Here's a suggestion. You can disable `# type: ignore` by setting `enableTypeIgnoreComments` to `information` or `warning`. This will disable all of the ignores, and errors that were suppress will appear. It will then be clear which `# type: ignore` comment have no corresponding error. Please try that technique and let me know if it meets your needs.

**Comment by erictraut** [comment]
@PetrochukM, I'm inclined to close this feature request. Please let me know if the above suggestion meets your needs.

**Comment by PetrochukM** [comment]
@erictraut Thanks for the ping, and I have been thinking a lot about your suggestion. It's a good suggestion, and it's a good approach. The approach you are suggesting would work well to fix a lot of annotations at the same time. 

Even so, I don't see myself doing that because our coding process is incremental, for the most part. Furthermore, the process of fixing typing bugs is also incremental. For example, PyTorch has a small typing bug with `nn.Sequence`. If it gets fixed, I likely wouldn't notice, and I suspect I'll have a stray annotation, here and there. 

At the end of the day, this isn't a big issue. It's a minor inconvenience to have redundant `typing.cast` or `# type: ignore` annotations. I would be okay with this issue being closed.
