### ISSUE TITLE
Provide better error recovery on fstring segment

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#1146]
**Describe the bug**
When there is a syntax error inside of fstring segment, it is not included in parse tree causing features like completion provider to show wrong information.

**To Reproduce**
```python
msg = "hello"

a = f"{msg. <invoke completion here>}"
```

**Expected behavior**
it shows members of string rather than symbols from corresponding scopes.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/1333179/98293574-6ca66680-1f63-11eb-8172-ca927b354f73.png)

**VS Code extension or command-line**
extension

**Additional context**
looks like [this code](https://github.com/microsoft/pyright/blob/master/packages/pyright-internal/src/parser/parser.ts#L2782) bail out as soon as it encounter syntax error and that cause expression list inside of {} to be empty and that cause [this code](https://github.com/microsoft/pyright/blob/master/packages/pyright-internal/src/parser/parser.ts#L1662) to return empty tuple. so "msg." now removed from parse tree causing completion provider to think the code is f"{}" rather than f"{msg.}" and end up show wrong list.

**Comment by erictraut** [comment]
This will be fixed in the next release.

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.84, which I just published. It will also be included in the next release of Pylance.
