### ISSUE TITLE
Exclusionary typing

### ISSUE THREAD

**Issue by PetrochukM** [microsoft/pyright#1147]
**Is your feature request related to a problem? Please describe.**
I'm at a loss for typing this recursive function...
```python3
import typing

_FlattenReturnType = typing.TypeVar("_FlattenReturnType")
_FlattenInputType = typing.List[typing.Union[_FlattenReturnType, "_FlattenInputType"]]


def flatten(l: _FlattenInputType) -> typing.List[_FlattenReturnType]:
    """Flatten a list of lists into a list."""
    if isinstance(l, list):
        return sum(map(flatten, l), [])
    return [l]


assert flatten([[1, 2, 3], [1, [2, [3]]]]) == [1, 2, 3, 1, 2, 3]
assert flatten([['a', 'b', 'c'], ['a', ['b', ['c']]]]) == ['a', 'b', 'c', 'a', 'b', 'c']
```

The errors are:
```
Argument of type "List[List[int | _FlattenInputType] | List[int | List[int | List[int | _FlattenInputType] | _FlattenInputType] | _FlattenInputType] | _FlattenInputType]" cannot be assigned to parameter "l" of type "_FlattenInputType[_FlattenReturnType]" in function "flatten"
  TypeVar "_T" is invariant
    Type "List[int | _FlattenInputType] | List[int | List[int | List[int | _FlattenInputType] | _FlattenInputType] | _FlattenInputType] | _FlattenInputType" cannot be assigned to type "_FlattenReturnType | _FlattenInputType"
```

```
Argument of type "List[List[str | _FlattenInputType] | List[str | List[str | List[str | _FlattenInputType] | _FlattenInputType] | _FlattenInputType] | _FlattenInputType]" cannot be assigned to parameter "l" of type "_FlattenInputType[_FlattenReturnType]" in function "flatten"
  TypeVar "_T" is invariant
    Type "List[str | _FlattenInputType] | List[str | List[str | List[str | _FlattenInputType] | _FlattenInputType] | _FlattenInputType] | _FlattenInputType" cannot be assigned to type "_FlattenReturnType | _FlattenInputType"Pylance (reportGeneralTypeIssues)
```

**Describe the solution you'd like**
In order to solve something like this, I'd need a type similar to `not isinstance(l, list)` or something like `Not[typing.List]`.

**Comment by erictraut** [comment]
The `List` class uses an invariant TypeVar. If you switch from `typing.List` to `typing.Sequence`, it will work fine.

**Comment by PetrochukM** [comment]
That works, thank you!

**Comment by PetrochukM** [comment]
I'm still struggling with typing this function correctly:

```python
import typing

_FlattenReturnType = typing.TypeVar("_FlattenReturnType")
_FlattenInputType = typing.Union[
    _FlattenReturnType, typing.Sequence[typing.Union[_FlattenReturnType, "_FlattenInputType"]]
]


def flatten(l: _FlattenInputType) -> typing.List[_FlattenReturnType]:
    """Flatten a list of lists into a list."""
    if isinstance(l, list):
        return sum(map(flatten, l), [])
    return [l]


assert flatten([[1, 2, 3], [1, [2, [3]]]]) == [1, 2, 3, 1, 2, 3]
assert flatten([["a", "b", "c"], ["a", ["b", ["c"]]]]) == ["a", "b", "c", "a", "b", "c"]
assert flatten([[[[]]], [], [[]], [[], []]]) == []
```

This error does not make sense either. How did `Unknown` appear in a list of ints? 
```
Argument of type "list[list[int] | list[int | list[Unknown]]]" cannot be assigned to parameter "l" of type "_FlattenInputType[Type[_FlattenReturnType@_FlattenInputType]]" in function "flatten"
  Type "list[list[int] | list[int | list[Unknown]]]" cannot be assigned to type "_FlattenInputType[Type[_FlattenReturnType@_FlattenInputType]]"
    Type "list[list[int] | list[int | list[Unknown]]]" cannot be assigned to type "_FlattenReturnType@_FlattenInputType"
      TypeVar "_T_co@Sequence" is covariant
        Type "list[int] | list[int | list[Unknown]]" cannot be assigned to type "_FlattenReturnType@_FlattenInputType | _FlattenInputType"
          Type "list[int]" cannot be assigned to type "_FlattenReturnType@_FlattenInputType | _FlattenInputType"
          Type "list[int | list[Unknown]]" cannot be assigned to type "_FlattenReturnType@_FlattenInputType | _FlattenInputType" PylancereportGeneralTypeIssues
```

This error doesn't make any sense. `_FlattenReturnType` appears in `_FlattenInputType` multiple times.
```
TypeVar "_FlattenReturnType" appears only once in generic function signature PylancereportInvalidTypeVarUse
```

I don't think I should be getting this error... 
```
Expression of type "list[_FlattenInputType[Type[_FlattenReturnType@_FlattenInputType]]]" cannot be assigned to return type "List[_FlattenReturnType@flatten]"
  TypeVar "_T@list" is invariant
    Type "_FlattenInputType[Type[_FlattenReturnType@_FlattenInputType]]" cannot be assigned to type "_FlattenReturnType@flatten" PylancereportGeneralTypeIssues
```

**Comment by erictraut** [comment]
Your code has a couple of problems:
1. The function `flatten` is using a TypeVar once. It appears only in the return type annotation. A TypeVar used within a generic function should always appear at least twice. If it appears within the return type annotation, it should also appear in one of the input parameter type annotations. The type evaluator will then solve for the TypeVar based on the constraints imposed by the input parameter types, and the solved type will replace the TypeVar within the return type. You should be seeing a warning from Pyright highlighting this problem ("TypeVar "_FlattenReturnType" appears only once in generic function signature").
2. `_FlattenInputType` is a generic type alias that requires one type argument, but you are using it without a type argument in the annotation for the `l` parameter in the `flatten` function. If you enable the `reportMissingTypeArgument` diagnostic rule, Pyright will tell you about this omission.

One more point that I think you may not understand... A TypeVar in Python has meaning only within a given scope. There are three types of scopes that can provide a TypeVar with meaning: a generic class, a generic function, and a generic type alias. You can use the same TypeVar in different scopes, but you should think of each of these as a separate instance of that TypeVar. You have used the `_FlattenReturnType` in two different scopes: the `_FlattenInputType` type alias and the `flatten` function. Those are two completely different instances of the TypeVar, and those instances are not related to each other in any way.
