### ISSUE TITLE
Recursive file watching broken on linux with Node >= 14

### ISSUE THREAD

**Issue by rcarriga** [microsoft/pyright#1159]
**Describe the bug**
Editing a file outside a workspace such as in the user's home directory causes Pyright to crash due to an exception thrown by `fs.watch()` when the recursive option is true. This is only an issue on Linux apparently. Though the exception is only thrown by Node >= 14, it seems that even previous versions do not work but rather just fail silently.

This error is occurring for me using `coc-pyright`. There is already a [related issue](https://github.com/fannheyward/coc-pyright/issues/87)  which was closed with the resolution being to just downgrade node, which is not ideal. 

**To Reproduce**
I can only reproduce by using `coc-pyright`, running `pyright.js` directly doesn't cause the issue. Once installed, editing a python file in the home directory crashes the server with the message `Exception caught when installing fs watcher`

**Expected behavior**
Language server to start successfully

**Screenshots or Code**
Any python file will reproduce issue

**VS Code extension or command-line**
Using latest version of `coc-pyright` with pyright version `1.1.84`

**Additional context**
The issue is from this line https://github.com/microsoft/pyright/blob/7dffbcfb8c173c5d203a535d577a9072c619fb9d/packages/pyright-internal/src/languageServerBase.ts#L386
Passing false for recursive prevents the error.

It seems that `fs-watch` is no longer maintained. Other packages with the same issue have migrated away from using it, replacing with something like `chokidar`. See this issue https://github.com/whitecolor/ts-node-dev/issues/143. There was a temporary solution provided there while the library was being replaced https://github.com/whitecolor/ts-node-dev/pull/149/files which would work here too

**Comment by erictraut** [comment]
We've had a lot of problems with file system watchers. Node and chokidar both have different problems in different circumstances.

I've added a try/catch block that catches the exception in this case and logs an error. You won't get file watching support for directories outside of your workspace, but that's better than crashing the language server.

**Comment by rcarriga** [comment]
Awesome that's definitely better than having to downgrade node for now at least thank you!

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.85, which I just published.
