### ISSUE TITLE
Local import do not handling

### ISSUE THREAD

**Issue by microcoder** [microsoft/pyright#116]
Hello!

I import my python module from local package and get Pyright error:

`Import 'myapp' could not be resolved pyright`

For reproduce:

Create a python package and any * .py file:

```
.
├── myapp
│   ├── common.py
│   └── __init__.py
└── test1.py
```
Then, add `from myapp import *` into file `test1.py` and you get the error message.

It is bug?

P.S. Version of Pyright - 1.0.25 (VSCode extension)

**Comment by erictraut** [comment]
I tried your repro steps, and it's working fine for me. 

I did need to add a minimal pyrightconfig.json file in the root directory. This step won't be necessary in the next version of pyright (1.0.26). I've modified it so it analyzes all python files under the project root if there is no config file specified.

That still leaves the mystery about the error you're seeing. Am I correct in assuming that you have opened the "." directory within VS Code? Pyright will use the root project directory as its starting point for import resolution.

**Comment by microcoder** [comment]
Sorry i don't understand what's going on. Please look up it the screenshot:

![Screenshot_20190509_210545](https://user-images.githubusercontent.com/2853555/57476061-78499c00-729e-11e9-9a28-dfd9ad54d11f.png)

I tried to copy all files `configurate_arch` project again to a new folder `test1` and added it to workspace of VSCode. The error do not reproduced :)

**Comment by microcoder** [comment]
I seeing the error very long ago, from 1.0.0 version. Maybe Piyriht uses some internal cache?

**Comment by erictraut** [comment]
Interesting. Glad to hear that it's gone!

No, pyright doesn't do any caching.

**Comment by microcoder** [comment]
This issue appears in my current workspace, but do not a new workspace! Please see the video:
https://youtu.be/bPNu7s2UDjk

Content of trouble workspace (there is nothing interesting):

```bash
[dv@dv-pc vscode]$ cat python-projects.code-workspace 
{
        "folders": [
                {
                        "path": "/home/dv/projects/python/configrw"
                },
                {
                        "path": "/home/dv/projects/python/db-scheme"
                },
                {
                        "path": "/home/dv/projects/python/lxd-containers"
                },
                {
                        "path": "/home/dv/projects/python/yml-reader"
                },
                {
                        "path": "/home/dv/projects/python/projectname"
                },
                {
                        "path": "/home/dv/Downloads/test_issue_116"
                }
        ],
        "settings": {}
}
```

I don't understand what's going on. VSCode or Pyright are buggy. Any ideas?

**Comment by erictraut** [comment]
Ah, I see from the video that you're using a multi-root workspace. You added a second folder to the workspace. Pyright doesn't currently support that.

I received a recent contribution to add support, but it introduced a regression, so I need to revert it.

**Comment by microcoder** [comment]
Thank you! I will wait for support multi-root workspace.
