### ISSUE TITLE
Embedded runtime environments

### ISSUE THREAD

**Issue by rwols** [microsoft/pyright#1169]
**Is your feature request related to a problem? Please describe.**
A python interpreter may be embedded into a larger application. Examples of this are:

- gdb
- lldb
- blender
- GIMP
- SublimeText
- Cocos2D
- ...

In such an embedded runtime there's usually one or more modules written in C and exposed to the interpreter. For instance, `bpy` in blender.

It's not clear to me what is the best way to go about handling these embedded interpreters in pyright. In the case of SublimeText I have some `.pyi` files which seems to work, but I am wondering if there is a more optimal way to handling this.

**Describe the solution you'd like**
Allow one to define a custom execution environment that one can set in the `executionEnvironments` array of pyrightconfig.json. Such an execution environment could a file or directory with stub files together with a "target" version like python 3.5.

**Comment by erictraut** [comment]
Yes, you should use `.pyi` files to describe the interface to modules that are not implemented in Python. If you place these stubs in the same directory as the binary file, you can use the same import resolution paths as the Python interpreter. Or you can place them in a different location and configure the import resolution paths differently.

**Comment by rwols** [comment]
Okay. Thanks for the clarification.
