### ISSUE TITLE
`--version` argument

### ISSUE THREAD

**Issue by butuzov** [microsoft/pyright#117]
**Is your feature request related to a problem? Please describe.**
I was trying to troubleshoot VSC intellisense issue and found that there is no argument I can provide to a local installation of `pyright` to get the currently installed version. I can make `npm list`,  but as non `ts/npm` guy I discovered it only after made changes that implement described functionality.

**Describe the solution you'd like**
I would like to have implemented `--version` arguments that can display a version of the checker. 

```bash
> pyright --version
Pyright 1.0.25
```

**Comment by erictraut** [comment]
This is implemented in 1.0.26
