### ISSUE TITLE
'symbol' is unknown symbol

### ISSUE THREAD

**Issue by gear4s** [microsoft/pyright#1176]
**Describe the bug**
When using pipenv + custom entry in `python.analysis.extraPaths`, I get the error `'symbol' is unknown symbol`

**To Reproduce**
Install pipenv
Install mongoengine in pipenv
Add pipenv site packages to your `python.analysis.extraPaths` settings directive
In a file within the workspace, just use:
```python
from mongoengine import connect
```

**Expected behavior**
Should recognize symbol

**Screenshots or Code**
```sh
python -c 'import sys; print(sys.path)'
[
  '',
  '/usr/lib/python38.zip',
  '/usr/lib/python3.8',
  '/usr/lib/python3.8/lib-dynload',
  '/home/aaron/.local/share/virtualenvs/Discord_Bot-1OLsgoy9/lib/python3.8/site-packages'
]
```
![image](https://user-images.githubusercontent.com/832900/99227390-d6403380-27f3-11eb-8cb7-136ab2df6f7c.png)

**VS Code extension or command-line**
I'm using Pyright extension, v1.1.85

**Additional context**
I am using pipenv with the system installed python

**Comment by erictraut** [comment]
The `python.analysis.extraPaths` setting is intended additional paths within your workspace. You should not use them for site packages. Rather, you should specify the virtual environment through the Python extension environment picker (which Pyright will honor).

This is a configuration issue, not a bug, so I'm going to close. If you need additional help with configuration, please ask on the [pyright gitter forum](https://gitter.im/microsoft-pyright/community) or file an issue in the [pylance-release repo](https://github.com/microsoft/pylance-release).
