### ISSUE TITLE
Auto-import is not suggesting variables anymore.

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#1186]
Pyright used to be able to auto-import `db` from `base`, but not anymore after recent updates (not sure which version made this change).

We have some flask apps that creates instances in a file and import it from other files. Please see the example:

In base.py
```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy as FlaskSQLAlchemy

app = Flask()
db = FlaskSQLALchemy(app)
```

In api.py
```python
from base import db

db.session.query(XXX)
```

Pyright's auto-import now suggests Classes, functions, upper-snake-cased variables (like `SOME_CONST`), but no lower-snake-cased variables (like `db`). This makes lots of our usecase harder than before.

We tried to put those variables we'd like to import from other files into the `__all__` list, but Pyright seems to ignoring it.

I assume this is an as-designed behaviour because I can image others might say this is the correct behaviour, but it makes us very hard to adapt using our current code base.

So is there a way to make Pyright suggest public variables (not starting with "_")? Maybe through some configuration or simply respect the `__all__` list.

FYI: I'm currently using the VSCode extension version 1.1.86

Thanks!

**Comment by giyyapan** [comment]
Recently I'm trying very hard to make all of my colleague move from PyCharm to VSCode, but the auto-import related behaviours in VSCode are pushing them back to PyCharm.

According to my own experience, PyCharm is actually not doing a very good job about auto-import, but it have a fantastic "manual import" actions, which uses a much aggresive stratege and searches all the possible match through the whole project and you can always find what you want even these action may take longer to complete (3~5s in our project).

I think auto-import is a feature that very hard to tweak, so I strongly suggest pyright provide a "manual import" action that use a slow but "searches everything" stratege like PyCharm, to make sure everyone get what they want to import.

**Comment by erictraut** [comment]
Auto-import isn't a core type checking feature, so it's more of a focus in pylance than in pyright. There has been significant work (and various changes) to improve auto-import in pylance, including the introduction of a lightweight indexer that runs for a few seconds after you open VS Code. This feature is still in preview, so it's not on by default, but you're welcome to enable it and provide feedback. In general, I recommend switching from pyright to pylance if you haven't already done so. 

Please post any additional auto-import improvement suggestions or bug reports to the [pylance-release](https://github.com/microsoft/pylance-release) repo.

**Comment by giyyapan** [comment]
Understood, I'll give Pylance a try. Thanks for you reply!
