### ISSUE TITLE
Turn on just jump to definition and autocompletion

### ISSUE THREAD

**Issue by delfick** [microsoft/pyright#1194]
Hi,

Is there a combination of settings that will let pyright just do autocompletion and jump to definition? In my vim config I use other plugins for linting so that it can use pylama settings.

Also, jump to definition doesn't seem to work in vim, but I get this feeling that's probably a vim plugin issue?

**Comment by erictraut** [comment]
You can set "typeCheckingMode" to "off" if you'd like. This will preserve features like autocompletion and jump to definition but suppress most errors.

**Comment by delfick** [comment]
ok, I've made a `pyrightconfig.json` with `{"typeCheckingMode": false}` and it still seems to have lint errors. Unfortunately I'm still gonna need a linter anyway and my codebase seems too dynamic for pyright to handle and it complains about way too many things, so I'm gonna have to stick with pylama for that. And also, it gets way too confused by not having typings and I'll have to stick with python-language-server for autocompletion.

**Comment by erictraut** [comment]
"typeCheckingMode" accepts one of the following values: "off", "basic" and "strict". If you set it to any other value, it will default to "basic". Check [here](https://github.com/microsoft/pyright/blob/master/docs/settings.md) for documentation.

**Comment by delfick** [comment]
oh it does too, sorry. This is what I get for trying to fix my editor at 7am.
