### ISSUE TITLE
Ignore file/directory support

### ISSUE THREAD

**Issue by TheCleric** [Microsoft/pyright#12]
I would really like a configuration option in the extension to have support for ignoring files/directories like in .gitignore. I presently have a folder of auto-generated python files (via swagger-codegen) that I can't fix (because they'll just get overwritten), so VS Code throws a lot of errors over these files.

**Comment by erictraut** [comment]
Pyright already has support for this. See the `exclude` option in the [configuration](https://github.com/Microsoft/pyright/blob/master/docs/configuration.md) documentation.

**Comment by TheCleric** [comment]
Thanks!

**Comment by TheCleric** [comment]
Actually this still looks problematic for this reason from the docs:

`Note that files in the exclude paths may still be included in the analysis if they are referenced (imported) by source files that are not excluded.`

So I still get errors that I have no control over.

**Comment by erictraut** [comment]
Ah, I see. Yeah, what you're asking for is different.

**Comment by erictraut** [comment]
Good suggestion. I ended up finding a need for this myself. I just added the support, and it's in version 1.0.6 which I just published.
