### ISSUE TITLE
How to get rid of `not a member of the module` for Python lib build with Boost

### ISSUE THREAD

**Issue by hadim** [microsoft/pyright#1202]
The library is called rdkit (`conda install rdkit`), it's a C++ library that has a Python wrapper.

```python
from rdkit import Chem
mol: Chem.Mol = Chem.MolFromSmiles("CCC")
```

Here for both `Mol` and `MolFromSmiles` I have a `is not a known member of module` error using Pylance on VSCode.

What would the best way to fix that?

**Comment by erictraut** [comment]
I'm not able to repro the error you're seeing. Perhaps there's a difference between the version of rdkit that I just installed and the version you're using.

I presume that you've enabled the type checker (i.e. set typeCheckingMode to "basic"). By default, it's "off" in Pylance. If you want to enable type checking, you will need type information for the libraries you consume. For libraries written in C++ like rdlib, you'll need to find a type stub that describes the Python types that comprise its public interface. Unfortunately, I don't think anyone has published type stubs for this library. 

Pylance ships with a few partial type stubs for popular libraries that are written in C++. These stubs were generated by "scraping" the binary. They're very incomplete — not sufficient for type checking, but enough to provide basic type completion support. If you would like to nominate rdkit to be "scraped" and included in a future release of Pylance, please file a feature request in the "pylance-release" github project.

**Comment by hadim** [comment]
Yes, the checker mode is set to "basic". I mostly use one type from this library `Chem.Mol` so I am fine defining it manually in a `py.typed` file for example but I don't know how to do that. Or can I disable only a few members against member checking in pyright/pylance?

Ideally, I would like to keep "basic" because it's quite awesome but get rid of all those rdkit errors.

**Comment by hadim** [comment]
It looks like `Chem.Mol` would correspond to https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/ROMol.h. I will fill a feature request. Thanks!

**Comment by hadim** [comment]
See https://github.com/microsoft/pylance-release/issues/651

**Comment by erictraut** [comment]
You could manually create a type stub (or a set of type stubs) for these modules and define only the symbols you're using. Create a directory in your workspace called `typings` and create a subfolder called `rdkit`, then place the type stub file(s) under that directory. For example, create an `__init__.pyi` and a `Chem.pyi` (or a subdirectory called `Chem` that contains an `__init__.pyi`).
