### ISSUE TITLE
numpy.dtype(item) with item a loop variable errors out

### ISSUE THREAD

**Issue by nschloe** [microsoft/pyright#1227]
Another weirdness with numpy. The following code gives and error:
```python
import numpy

lst = [
    "bool",
    "uint8",
    "int8",
    "uint16",
    "int16",
    "uint32",
    "int32",
    "uint64",
    "int64",
    "float32",
    "float64",
]


for item in lst:
    numpy.dtype(item)  # !
```
```
  18:5 - error: No overloads for "numpy.dtype(item)" match parameters
    Argument types: (str) (reportGeneralTypeIssues)
```
This, however, is fine:
```python
import numpy

numpy.dtype("bool")
numpy.dtype("uint8")
numpy.dtype("int8")
numpy.dtype("uint16")
numpy.dtype("int16")
numpy.dtype("uint32")
numpy.dtype("int32")
numpy.dtype("uint64")
numpy.dtype("int64")
numpy.dtype("float32")
numpy.dtype("float64")
```

**Comment by erictraut** [comment]
Which version of numpy do you have installed? Are you using any type stubs for it? I installed the latest public version from pypi (numpy 1.19.4), and I'm not able to repro the problem. I've tried enabling and disabling "useLibraryCodeForTypes".

**Comment by nschloe** [comment]
Sorry for not specifying. `master`, and yes, it has stubs:
```
python3 -c "import numpy; print(numpy.__version__)"
```
```
1.21.0.dev0+20201201232031_33dc7be
```

**Comment by erictraut** [comment]
Ah, I see. I don't know how to install numpy directly from the repo. Can you tell me how you did that?

If you go to the definition of dtype in the numpy sources (select dtype and hit F12 if you're using VS Code), what file does that take you to? Based on the what you're reporting, I suspect that they have annotated this method such that it accepts only certain string literal values like "bool" and "uint8" but not arbitrary strings. If so, then pyright is doing the right thing here. In any case, this is probably not a bug in pyright. If you believe the numpy type stubs are in error, please file a bug or PR in that project.

**Comment by nschloe** [comment]
>  Can you tell me how you did that?

Check out the repo, then
```
pip install .
```

> I suspect that they have annotated this method such that it accepts only certain string literal values like "bool" and "uint8" but not arbitrary strings.

For sure.

What I still don't understand is why
```python
a = "bool"
numpy.dtype(a)
```
is fine but
```python
a = ["bool"]
numpy.dtype(a[0])
```
gives an error.

**Comment by erictraut** [comment]
Type checkers evaluate types, not values. If you specify a type declaration for a symbol, it will use that type and verify that all expressions assigned to it are of a compatible type. If you don't declare a type for a symbol (e.g. as with `a` above), the type checker will infer its type the best it can. The inferred type of the expression `"bool"` is `Literal["bool"]`. The inferred type of the expression `["bool"]` is `List[str]`. That means the type of the expression `a[0]` is `str`, and there's no overload for the `dtype` function that accepts a `str` as an input parameter.

For more details about pyright's type inference rules, see [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md).

**Comment by nschloe** [comment]
Thanks for the explanation!
