### ISSUE TITLE
Improve isinstance + issubclass type narrowing for 3.10

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pyright#1237]
## Environment data

-   Language Server version: 2020.12.0
-   OS and version: macOS
-   Python version: **3.10.alpha2**

## Expected behaviour

Extend type narrowing behavior for `isinstance` and `issubclass` to include Union types -> [PEP 604](https://www.python.org/dev/peps/pep-0604/#isinstance-and-issubclass).

## Actual behaviour

No type narrowing is performed.

## Code Snippet / Additional information

```python
from typing import Any
x: Any = 1

if isinstance(x, int | str):
    x  # type should be: Type[int] | Type[str]

if issubclass(x, int | str):
    x  # type should be: Type[int] | Type[str]
```

**Comment by erictraut** [comment]
This is now fixed in Pyright 1.1.92, which I just published. It will also be addressed in next week's Pylance release.
