### ISSUE TITLE
Question about type guards

### ISSUE THREAD

**Issue by alex-treebeard** [microsoft/pyright#1242]
Hi there,

I'm curious why pyright 1.1.30 thinks `x` is of type `object` in the else statement? It should know it is a string right?

```python

def x(x: Optional[str]):
    if  isinstance(x, NoneType):
        a: NoneType = x
    else:
        b: str = x
```

```
error: Expression of type "object" cannot be assigned to declared type "str"
```

Pyright is happy with this, but it feels overkill:

```python
def x(x: Optional[str]):
    if  isinstance(x, NoneType):
        a: NoneType = x
    elif isinstance(x, str):
        b: str = x
```

Are there some docs on `object` I am missing?

**Comment by erictraut** [comment]
Pyright has no knowledge of the `NoneType` symbol. It was apparently recently added to the typeshed headers. It's not a real runtime type, so I'm not sure how it is intended to be used. Your code above will generate runtime errors.

The correct way to do this is:
```python
def x(x: Optional[str]):
    if x is None:
        a = x
    else:
        b = x
```

**Comment by erictraut** [comment]
Incidentally, PEP 484 indicates that `None` when used in a type annotation means `NoneType` if a class name is expected. So you should never need to use `NoneType` in any annotation.
