### ISSUE TITLE
We are interested in your feedback about the pyright repo!

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#1243]
Thanks for all of your contributions to this project! We have created a survey that we hope allows us to learn what works and what needs attention. It's a little bit less than 30 questions, many of them multiple-choice questions. If maybe takes 10 minutes to complete and it’s anonymous. Your responses will help us make your experience better in this repo.
 
https://www.surveymonkey.com/r/92RLF7R?Source=Microsoft/pyright

**Comment by danmosemsft** [comment]
@erictraut the survey is closed, please close this issue - thanks!
