### ISSUE TITLE
Recommendations for usage with Tox

### ISSUE THREAD

**Issue by tomasaschan** [microsoft/pyright#1263]
Are there any recommendations for how to set up Pyright to be both installed and run by [`tox`](https://tox.readthedocs.io/en/latest/)?

**Comment by jugmac00** [comment]
Without testing this myself, one possible good way would be to run `pyright` via `pre-commit`  via `tox`.

Although, I am not entirely sure whether `pyright` can be run via `pre-commit`, as #862 was closed.

**Comment by tomasaschan** [comment]
My main concern here is to figure out how to tell `tox` where to find `pyright`. Ideally, I'd like a new developer on the project to be able to `git clone` the project and then run `tox` to verify that everything works, without having to install anything but python and tox itself. Is that reasonable?

**Comment by layday** [comment]
> without having to install anything but python and tox itself

Pyright has a runtime dependency on Node.js.  By adopting Pyright, you're adopting Node.js as a dependency for your project.

**Comment by erictraut** [comment]
BTW, I just enabled a new GitHub feature called "Discussions" that we can use for questions like this.

**Comment by jugmac00** [comment]
@tomasaschan 
This seems to work, but also does not seem to be well maintained - latest pyright version there is 1.1.53

https://github.com/necaris/pre-commit-pyright

**Comment by erictraut** [comment]
I'm going to close this as an issue. If someone has additional suggestions, feel free to add here or start a discussion using the new Discussions feature.
