### ISSUE TITLE
I need slight help with pyrightconfig.json

### ISSUE THREAD

**Issue by kosciej16** [microsoft/pyright#1266]
Hi!

I have that structure in my code:
```
.pyrightconfig.json
.git/
service1/
    app.py
    src/
    tests/
service2/
    app.py
    src/
    tests/
commons/ <--- I want to add this directory
```
and this pyrightconfig.json:
```
{
 "executionEnvironments": [
    {
      "root": "service1",
      "extraPaths": [
          "service1/src"
      ]
    },
    {
      "root": "service2",
      "extraPaths": [
          "service2/src"
      ]
    }
 ]
}
```
Eveything worked great, I could import in both services without service prefix nor src prefix.
Now I want to create commons directory and allow in addition import from both services
```
from commons.som import x
```
I tried every combination of executionEnvironments and include/exclude things but couldn't make it work.

I would be really appreciate if someone could point me the right direction how to solve it.

**Comment by erictraut** [comment]
You can simply add`"."` as an extra path to the `extraPaths` array. Then when the import resolver looks for `commons.som`, it will start searching at the root directory of your project.

**Comment by kosciej16** [comment]
Works like a charm, you are my hero, thanks!
