### ISSUE TITLE
LSP: How pyright handles client-initiated progress is not what I'd expect

### ISSUE THREAD

**Issue by rwols** [microsoft/pyright#1284]
**Describe the bug**
I'm currently implementing client-initiated progress, testing mainly with pyright.

**To Reproduce**
I don't have concrete steps, but here are some raw RPC payloads:

```
:: --> LSP-pyright textDocument/references(109): {'position': {'character': 19, 'line': 269}, 'workDoneProgressToken': 'wdp109', 'textDocument': {'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/code_actions.py'}, 'context': {'includeDeclaration': False}}
:: <-- LSP-pyright window/workDoneProgress/create(4): {'token': 'b350b08a-c9e6-4088-9d51-f61b95f44d2b'}
:: >>> LSP-pyright 4: None
:: <-  LSP-pyright $/progress: {'token': 'b350b08a-c9e6-4088-9d51-f61b95f44d2b', 'value': {'title': 'Finding references', 'cancellable': True, 'kind': 'begin'}}
:: <-  LSP-pyright $/progress: {'token': 'b350b08a-c9e6-4088-9d51-f61b95f44d2b', 'value': {'kind': 'end'}}
:: <<< LSP-pyright 109: [{'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/boot.py', 'range': {'end': {'character': 58, 'line': 31}, 'start': {'character': 37, 'line': 31}}}]
```

As you can see, the following happens:

1. I request textDocument/references with a workDoneProgressToken equal to `wdp109`
2. pyright starts a _server-initiated progress_ with window/workDoneProgress/create with token `b350b08a-c9e6-4088-9d51-f61b95f44d2b`
3. pyright does a few $/progress notifications using the token from the server-initiated progress
4. it sends back the results

**Expected behavior**

I would expect pyright to not call window/workDoneProgress/create, instead using the workDoneProgressToken (`wdp109`) in the initial request for the $/progress notifications. Am I misreading the spec? https://microsoft.github.io/language-server-protocol/specification#clientInitiatedProgress

**Screenshots or Code**
N/A

**VS Code extension or command-line**
N/A

**Additional context**
pyright version is 1.1.95

**Comment by jakebailey** [comment]
If we're doing a big analysis, I'm pretty sure we use the server-initiated progress to put a spinner at the bottom of the screen (a la VS Code) as just a "the analysis is running" indicator, but that's in addition to any work done progress that happens for client-initiated. IIRC the main reason to use the client-initiated progress is not to track progress (which is difficult for us because we are lazy), but to allow for cancellation of the work.

Do you see the server using the token that came from the references request? Or is it just not touched?

**Comment by jakebailey** [comment]
Looking at the code, we should be using the progress reporter from the client if the token's been provided...

https://github.com/microsoft/pyright/blob/6ff4201d89df2a32f4ce670551ff6f03a90cac4a/packages/pyright-internal/src/languageServerBase.ts#L457

https://github.com/microsoft/pyright/blob/6ff4201d89df2a32f4ce670551ff6f03a90cac4a/packages/pyright-internal/src/languageServerBase.ts#L1161

So, I'm a bit surprised, but I haven't had time to test this out (and HeeJae who implemented this would know better, but he's out on vacation 🙂)

**Comment by jakebailey** [comment]
Ah, I think I see. The spec says `workDoneToken`, not `workDoneProgressToken`. I think the client is sending the wrong thing, then when the server library looks, it only sees `undefined`.

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#clientInitiatedProgress

**Comment by rwols** [comment]
> The spec says workDoneToken, not workDoneProgressToken.

Ah, you're totally right :)

I changed it into `workDoneToken`, but even then, pyright starts its own reporter:

```
:: --> LSP-pyright textDocument/references(5): {'position': {'line': 1232, 'character': 19}, 'textDocument': {'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/core/sessions.py'}, 'context': {'includeDeclaration': False}, 'workDoneToken': 'wdp5'}
:: <-- LSP-pyright window/workDoneProgress/create(4): {'token': '77adc776-d868-4dd6-ac67-52d9e907a6e0'}
:: >>> LSP-pyright 4: None
:: <-  LSP-pyright $/progress: {'token': '77adc776-d868-4dd6-ac67-52d9e907a6e0', 'value': {'cancellable': True, 'kind': 'begin', 'title': 'Finding references'}}
:: <-  LSP-pyright $/progress: {'token': '77adc776-d868-4dd6-ac67-52d9e907a6e0', 'value': {'kind': 'end'}}
:: <<< LSP-pyright 5: [{'range': {'start': {'line': 148, 'character': 36}, 'end': {'line': 148, 'character': 54}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/code_actions.py'}, {'range': {'start': {'line': 157, 'character': 32}, 'end': {'line': 157, 'character': 50}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/code_actions.py'}, {'range': {'start': {'line': 334, 'character': 20}, 'end': {'line': 334, 'character': 38}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/documents.py'}, {'range': {'start': {'line': 423, 'character': 20}, 'end': {'line': 423, 'character': 38}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/documents.py'}, {'range': {'start': {'line': 452, 'character': 20}, 'end': {'line': 452, 'character': 38}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/documents.py'}, {'range': {'start': {'line': 488, 'character': 16}, 'end': {'line': 488, 'character': 34}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/documents.py'}, {'range': {'start': {'line': 42, 'character': 16}, 'end': {'line': 42, 'character': 34}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/formatting.py'}, {'range': {'start': {'line': 69, 'character': 20}, 'end': {'line': 69, 'character': 38}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/formatting.py'}, {'range': {'start': {'line': 920, 'character': 13}, 'end': {'line': 920, 'character': 31}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/core/sessions.py'}, {'range': {'start': {'line': 1210, 'character': 13}, 'end': {'line': 1210, 'character': 31}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/core/sessions.py'}, {'range': {'start': {'line': 1258, 'character': 57}, 'end': {'line': 1258, 'character': 75}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/core/sessions.py'}, {'range': {'start': {'line': 1263, 'character': 13}, 'end': {'line': 1263, 'character': 31}}, 'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/core/sessions.py'}]
```

I'll look into the code of pyright to see what's going on...

**Comment by rwols** [comment]
I'll close this since I do think pyright is doing everything correctly here.
