### ISSUE TITLE
Consider special-casing `type` call to return `Type[x]` rather than `type[Unknown]`

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#1288]
Investigate the following.

See issue: https://github.com/microsoft/pylance-release/issues/747

Also, I think one could make a good argument that the type checker should evaluate the type of the expression type(int) to be Type[int] rather than Type[Unknown].

**Comment by erictraut** [comment]
Upon further investigation, I think it would be incorrect to make this change. The expression `type(3)` already evaluates to the type `Type[int]`, which is correct. The expression `type(int)` isn't really a valid expression because the argument passed to the `type` constructor is supposed to be an object.

**Comment by layday** [comment]
If the type of `int` is `type`, shouldn't the type of `type(int)` be `type` or `type[type]`? Currently this produces `Any` which seems wrong.
