### ISSUE TITLE
pyright could have option to consider .gitignore files

### ISSUE THREAD

**Issue by mikest** [microsoft/pyright#129]
**Is your feature request related to a problem? Please describe.**
We often have files excluded in our codebase via .gitignore, this includes intermediary build files and such. It doesn't appear as if pyright considers these filters when doing its scan. This means we have to maintain two instances of the filter list, or a pyright scan will start picking up code files it should not.

**Describe the solution you'd like**
An option to include the .gitignore rules when selecting files. Preferably defaulting to "on"

**Additional context**

**Comment by return42** [comment]
This issue was closed but it is not clear to me if there is an option to include the .gitignore rules when selecting files. The patch 5ec260f that refers this issue number (#129) seems not related to this issue.  Could you please clarify the status of the .gitignore option / thanks a lot!

**Comment by erictraut** [comment]
The ".gitignore" file is specific to git and code management. It has little if any overlap with type checking.

If there are files or directories that you want to exclude from type checking, you can configure that in the "pyrightconfig.json" file. We don't have any plans for pyright to read the ".gitignore" file.

**Comment by return42** [comment]
> We don't have any plans for pyright to read the ".gitignore" file.

Thanks for clarifying.
