### ISSUE TITLE
Support pyrightconfig.json IntelliSense in VSCode

### ISSUE THREAD

**Issue by tamuhey** [Microsoft/pyright#13]
Thanks for this cool tool!!
I'm glad if there is IntelliSense for pyrightconfig.json in VSCode!

**Comment by erictraut** [comment]
Great suggestion. I added this support in 1.0.6, which I just published.

**Comment by tamuhey** [comment]
3ebdb0b9b00da5fe0b4f26849f6fa9a1e0b67bed
