### ISSUE TITLE
Generate a default configuration file

### ISSUE THREAD

**Issue by halhenke** [microsoft/pyright#1305]
**Is your feature request related to a problem? Please describe.**
At present adding configuration for a project means coming to this site to check what configuration options are available, how to specify them etc. It would be much more convenient and would add to the discoverability of these options if there was a way to create a "basic" or generic configuration file (a la `npm init` for a `package.json` file for example)

**Describe the solution you'd like**
A command that generates a `pyrightconfig.json` file with default values where appropriate or pipes the equivalent to stdout

This could involve an interactive prompt etc.

**Comment by erictraut** [comment]
Pyright includes a JSON schema document that defines the full schema for the configuration file. Smart editors like VS Code that honor JSON schemas will provide type completion and contextual help as you're editing the config file.

Also, the defaults for the config file are intentionally designed to be the most common. So if you want to create a minimal configuration file, its contents would simply be "{}".

For these reasons, I don't think another mechanism is necessary.

**Comment by dlech** [comment]
Is https://raw.githubusercontent.com/microsoft/pyright/master/packages/vscode-pyright/schemas/pyrightconfig.schema.json the canonical URL for this schema?

**Comment by erictraut** [comment]
Yes, that's correct.

**Comment by erictraut** [comment]
Actually, I responded too fast. That's the correct schema file, but it's not the "canonical URL".

This file is shipped with the Pyright extension for VS Code, and it's registered with a local file reference [here](https://github.com/microsoft/pyright/blob/ffbe0193585f38b17e2769be6024d18f3264f052/packages/vscode-pyright/package.json#L688).
