### ISSUE TITLE
Narrowing doesn't understand all synonyms of `and` 

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pyright#1314]
```py
class Foo:
    tag: Literal["foo"] = "foo"

class Bar:
    tag: Literal["bar"] = "bar"


def f(x: Union[Foo, Bar], y: Union[Foo, Bar]):
    if x.tag == y.tag == "foo":
        return (x, y)
    raise Exception


def g(x: Union[Foo, Bar], y: Union[Foo, Bar]):
    if x.tag == "foo" and y.tag == "foo":
        return (x, y)
    raise Exception
    
def h(x: Union[Foo, Bar], y: Union[Foo, Bar]):
    if x.tag == y.tag and y.tag == "foo":
        return (x, y)
    raise Exception
```
Inferred return type: of `f` is `tuple[Foo|Bar, Foo|Bar]` , while the return type of `g` is `tuple[Foo, Foo]`.

- `f: tuple[Foo|Bar, Foo|Bar]` 
- `g: tuple[Foo, Foo]` (correct)
- `h: tuple[Foo|Bar, Foo]`

While technically and in general these three may not be true (in which case `==` is not transitive, so the blame is on who implements it), here it always holds

I wouldn't use the `h` way, that's just another example.

**Comment by erictraut** [comment]
The supported idioms for type narrowing are documented [here](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#type-guards). Each additional idiom requires custom logic to handle. I'm not inclined to add any more unless there's good evidence that they are popular idioms and/or there's no practical workaround. I don't think these come close to meeting that bar.
