### ISSUE TITLE
Infer Enum type instead of literals when a function can return all of its variants

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pyright#1319]
```py
def get_pizza(pineapples: bool, name: str):
    if pineapples:
        return True, name + "1"
    else:
        return False, name + "2"
```
This function is inferred to return `tuple[Literal[True], str] | tuple[Literal[False], str]`. That's correct, but maybe `tuple[bool, str]` would be a better type?

In this example with Enums, it gets a little bit noisy:
```py
@final
class Topping(Enum):
    PINEAPPLES = 0
    BASIL = 1
    ORANGES = 2

def get_pizza(n: int):
    if n == 1:
        return Topping.PINEAPPLES, str(n) + "!"
    elif n == 2:
        return Topping.BASIL, str(n) + "!!!"
    else:
        return Topping.ORANGES, str(n)
```
The return type is inferred to be `tuple[Literal[Topping.PINEAPPLES], str] | tuple[Literal[Topping.BASIL], str] | tuple[Literal[Topping.ORANGES], str]`, while `tuple[Topping, str]` would be much more concise

**Comment by erictraut** [comment]
I don't think the added complexity and performance hit is worth it. If you care enough about this, simply add a return type annotation to your function.
