### ISSUE TITLE
Document rule set defaults

### ISSUE THREAD

**Issue by layday** [microsoft/pyright#1320]
I've noticed recently that `reportUnusedCallResult` is not controlled by `typeCheckingMode`; that is, setting the latter to `"strict"` will not set the former to `true`.  I now wonder if this is the only diagnostic-category setting which exhibits this behaviour or if there are other settings which do not follow `typeCheckingMode`.  It might be useful to document the settings' values for each rule set.

**Comment by erictraut** [comment]
I've added a [table to the documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md#diagnostic-rule-defaults).
