### ISSUE TITLE
Pyright: reportUndefinedVariable after globals() and locals() checks

### ISSUE THREAD

**Issue by vodkar** [microsoft/pyright#1323]
Hello!

Pyright can't recognize variable after checking this in locals() or globals();

![изображение](https://user-images.githubusercontent.com/28678409/103221716-1a6f3980-4945-11eb-9d00-7bc475833078.png)

**Comment by erictraut** [comment]
Dynamically manipulating local or global variables isn't supported in a static type checker. This isn't a recommended practice. If you don't want to modify your code to avoid this, you can disable the diagnostic on that line using a `# type: ignore` comment or disable the diagnostic rule throughout that file by using a `# pyright: reportUndefinedVariable=false` comment at the top of the file.
