### ISSUE TITLE
Pylance having trouble recognizing flask as a valid source

### ISSUE THREAD

**Issue by Mparker25** [microsoft/pyright#1328]
**Describe the bug**
pylance doesn't recognize flask as a valid source

**To Reproduce**
import flask and watch it claim that flask could not be resolved as a source

**Expected behavior**
flask is clearly a valid library

**Screenshots or Code**
<img width="1082" alt="Screen Shot 2020-12-29 at 3 07 46 PM" src="https://user-images.githubusercontent.com/4305479/103311276-e567f300-49e7-11eb-9bfc-373a19d8bc0e.png">

VS Code extension: v2020.12.2

**Comment by erictraut** [comment]
This is an indication that either 1) you have not configured pyright to use your python environment, or 2) flask is not installed in the Python environment you have configured.

Please refer to the documentation for how to configure pyright so it knows about your Python environment. If you can't figure out how to correctly configure it, feel free to ask questions in the discussion tab of the repo.
