### ISSUE TITLE
Expand ~ in pyrightconfig.json

### ISSUE THREAD

**Issue by flupke** [microsoft/pyright#1340]
**Is your feature request related to a problem? Please describe.**
`~` is not expanded in `pyrightconfig.json` strings. Expanding it would allow committing `pyrightconfig.json` to the codebase and share it with the team.

**Describe the solution you'd like**
Expand `~` in all path settings of `pyrightconfig.json`

**Comment by erictraut** [comment]
Pyrightconfig.json is meant to be a cross-platform and shell-agnostic config file format that can be checked in to a repo and used across multiple developers who work on different platforms. All paths should be platform-agnostic and shell-agnostic.

**Comment by flupke** [comment]
Are you saying expanding `~` to the current user's home dir would tie the config file to a particular shell or platform? in what way?

And how are we supposed to share `pyrightconfig.json` between multiple developers if the paths are valid for only one of them?

**Comment by erictraut** [comment]
Windows doesn't have any notion of a "home dir", nor does it use `~` in pathnames. These are UNIX concepts. 

Paths in `pyrightconfig.json` are meant to be relative to the project root directory, not absolute. With which config setting do you want to use an absolute path, and why?

**Comment by flupke** [comment]
On Windows, you could expand `~` to `%USERPROFILE%`. To be complete you could expand `~` and environment variables.

The issue that made me come here is I manage my envs with [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/), which stores the virtualenvs in `~/.virtualenvs`, so my `pyrightconfig.json` looks like this:
```json
{
    "venvPath": "/home/flupke/.virtualenvs",
    "executionEnvironments": [
        {
            "root": "foo/",
            "venv": "foo",
            "extraPaths": ["foo/src"]
        },
        {
            "root": "bar/",
            "venv": "bar",
            "extraPaths": ["bar/src"]
        }
    ]
}
```

**Comment by erictraut** [comment]
If your `venvPath` is an absolute value, it should be specified using a per-user setting value (`python.venvPath`) if you're using the language server. If you're using the command-line version, it can be passed using the `--venv-path` switch. Absolute paths shouldn't appear in pyrightconfig.json.

**Comment by flupke** [comment]
It would be nice if we could avoid every developer in the team do the same config. Teams tend to use the same OS and tools. I understand your point, but sometimes practicality beats purity, and I don't see how expanding `~` would harm Windows users. Would you be against a PR implementing this?

**Comment by erictraut** [comment]
This goes against the intended design, so we don't plan to make this change or accept a PR that implements it.

**Comment by ajoino** [comment]
What about packages installed with the `--user` flag? Currently (on Ubuntu) I have to specify the absolute path `/home/<user>/.local/lib/python3.11/site-packages' instead of using `$HOME` or `~`. I tried both and they both failed. Mypy automatically looks into `$HOME/.local/lib/python3.xy`, maybe pyright should too?

**Comment by erictraut** [comment]
@ajoino, are you using the `venv` and `venvPath` mechanism to specify your python environment? This is _not_ the recommended approach with pyright. If you use one of the recommended approaches, you will avoid all of these issues because the import resolution paths will be supplied by selected python interpreter (via the `sys.path` value). For details, refer to [this documentation](https://microsoft.github.io/pyright/#/import-resolution?id=configuring-your-python-environment).

**Comment by ajoino** [comment]
Thanks for the quick reply! I'm very new to pyright so it might be that I didn't understand the docs. I'm trying to use the `executionEnvironments.extraPaths` config option, running pyright like this `python3.11 -m pyright -p <path/to/lib>` directly through the command line. I saw that you can specify the `python.pythonPath` but I couldn't find how to set that in the pyproject.toml, and I would assume, perhaps incorrectly, that running pyright as I do would make it look into packages installed with the `--user` flag.

For completeness sake, here's the output of `python3.11 -c "import sys; print(sys.path)"`:
```
['', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/home/jacob/.local/lib/python3.11/site-packages', ...]
```
showing that the directory is there, so I'm definitely doing something wrong.

**Comment by erictraut** [comment]
By default, pyright will use whatever `python3` interpreter you have configured in the shell. It internally runs `python3 -c "import sys; print(sys.path)"`.

Most Python developers use virtual environments. This prevents you from corrupting your main python environment when you install libraries for a specific project. You can create a virtual environment using the command `python3.11 -m venv .venv`. You can then "activate" that virtual environment using the command `source .venv/bin/activate`. Now, when you run `python3`, you'll get the interpreter associated with your venv. And when you run pyright, it will use this interpreter along with the activated venv.
