### ISSUE TITLE
"Extract method" functionality

### ISSUE THREAD

**Issue by ranyadshalom** [microsoft/pyright#1353]
Since Pyright already does renaming and import organizing, it would be very nice to also be able to "extract method" (similar functionality to the one in [vscode-python](https://github.com/Microsoft/vscode-python)). It's the one refactoring capability I truly miss when using Pyright. Are there any plans to support it?

**Comment by erictraut** [comment]
Pyright implements core type checking and some (limited) language server features such as renaming and basic completion suggestions. More advanced features like refactoring (including "extract method"), AI-guided completions, advanced auto-import, and semantic tokenization are built on top of Pyright in the VS Code extension called Pylance. You can download Pylance from the VS Code marketplace. We have no plans to add additional language server features to Pyright at this time.
