### ISSUE TITLE
How should Pyright consider typing stubs with try-excepted imports?

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pyright#1358]
`immutables` repo: https://github.com/MagicStack/immutables/blob/master/immutables/__init__.py

has this code in `__init__.py`:
```py
try:
    from ._map import Map
except ImportError:
    from .map import Map
```
The project has a `_map.pyi`, but no `map.pyi`. Pyright thinks that only `map` is ever imported, so it doesn't use `_map.pyi`. 

This is fixed by:
```py
try:
    from ._map import Map
except ImportError:
    if TYPE_CHECKING:
        from ._map import Map
    else:
        from .map import Map
```
or:
```py
if TYPE_CHECKING:
    from ._map import Map
else:
    try:
        from ._map import Map
    except ImportError:
        from .map import Map
```
but maybe Pyright should somehow use `_map`'s typing stub in that case? Or would you say that libraries should just use the second variant, or provide typing stubs for `module` instead of `_module`?

**Comment by erictraut** [comment]
Conditional (dynamic) imports are very difficult for a static analyzer. When resolving an import symbol, Pyright uses the last declaration of the symbol in the file regardless of whether the import statement is in an if/else or try/except block. If that order doesn't work for you, you can use a a TYPE_CHECKING conditional to hide declarations that you don't want pyright to consider.

Another option is to create a local stub alias. In your case you could create a `map.pyi` that re-exports all the symbols from `_map.pyi`.

**Comment by decorator-factory** [comment]
That makes sense. Thank you!
