### ISSUE TITLE
Provide an example integrating pyright with tox

### ISSUE THREAD

**Issue by sebastian-philipp** [microsoft/pyright#1364]
pyright is written in type script which makes it non-trivial to integrate it with standard python tools.

I really would like to add pyright as an additional step in our CI. As we're using tox, it would be great to have an example of 
how to integrate pyright into tox.

**Comment by sebastian-philipp** [comment]
looks like this somewhat duplicates #1263 but I hope this is still unresolved.

**Comment by erictraut** [comment]
Please refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/ci-integration.md) on CI.

I don't have any experience with tox, so I'm not going to be able to help you there. If you open a thread in the discussion section, someone from the community may be able to help you out.
