### ISSUE TITLE
Error on type narrowing with isinstance

### ISSUE THREAD

**Issue by K3UL** [microsoft/pyright#1372]
Hello, I am using `isinstance()` to narrow down the type of a variable but get an error on something that does not exist on another type.
I see you have been working on type narrowing recently, but I am still seeing this error on the newest 1.1.101.

I am also a bit surprise that it seems to only consider one type of the union. While getting errors, I was expecting to also get an error on the line that assumes the var is a dict, saying the `pd.Series` type does not have a `popitem()`.

**To Reproduce**
```
from typing import Union

import pandas as pd


def do_something(arg: Union[pd.Series, dict[str, str]]):
    if isinstance(arg, pd.Series):
        print(arg.index)
    elif isinstance(arg, dict):
        print(arg.popitem())

```

**Expected behavior**
No error

**Additional context**
Python 3.9.0
Windows 10 20H2 19042.746
Pyright 1.1.101

**Comment by erictraut** [comment]
What error are you seeing? I'm not able to repro an error with the sample you provided, so I presume there's some other configuration detail I need to know.

the `isinstance` narrowing logic is smart enough to handle both the positive test (`if` clause) and negative test (`else` clause). In your example, you are first testing whether `arg` is a `Series`. In the `elif` clause, the type narrowing logic has already narrowed it to a `dict[str, str]`, so the second `isinstance` check will always succeed and is unnecessary. If you enable `strict` type checking mode, it will even highlight the fact that the second check is unnecessary.

**Comment by K3UL** [comment]
Ha yes sorry I forgot the error. I am surprised you cannot reproduce it. I just created a file with the above code and here is what I get ; as you can see it is stated no particular configuration is used : 

![image](https://user-images.githubusercontent.com/4669258/104626283-00985b00-5696-11eb-9e2b-cbaf2c408fb9.png)

**Comment by erictraut** [comment]
Ah, the problem is that you don't have any type stubs installed for pandas. Because of the absence of type stubs, the type checker is treating `pd.Series` as an "unknown" type. In the absence of an unknown type, the type narrowing logic needs to be very conservative.

There are a couple of sources of type stubs for pandas. The stubs I recommend are the ones we ship with pylance. You can find it here: https://github.com/microsoft/python-type-stubs.

**Comment by erictraut** [comment]
Here's what it looks like if you have stubs installed.

![Screen Shot 2021-01-14 at 9 48 42 AM](https://user-images.githubusercontent.com/7040122/104628927-b12e3c80-564d-11eb-8276-107e7c4e08dd.png)

**Comment by K3UL** [comment]
Ok this explains the `unknown`, I was wondering about that too. But how come none of the rest of my code is failing ? For example this does not fail : 

```python
import pandas as pd


def do_something(arg: pd.Series):
    print(arg.index)
```

**Comment by erictraut** [comment]
When you say "none of the rest of my code is failing", do you mean that you are not seeing runtime errors? Or you are not seeing type checking errors?

You will not necessarily see type checking errors in the absence of type stubs. If a type is "unknown", the type checker is very permissive, effectively saying "I don't know anything about this type, so I won't generate any errors in this case".

Yes, you are likely to see many more errors and warnings once you install the type stubs. Hopefully some of those represent real errors that you can fix within your code! :)

**Comment by K3UL** [comment]
Thank you very much, it is very clear ! And thank you for your recommendation on the stubs, I will definitely use these ones
