### ISSUE TITLE
Using --verifytypes to check a subset of the public interface

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#1382]
**Is your feature request related to a problem? Please describe.**
As you know, I'm trying the `--verifytypes` on `pandas`.  Given the large number of errors so far, it is hard to determine which class might be the root cause of a lot of the problems.  It would also be useful to be able to just test one part of the public interface to see if that part is fixed.

**Describe the solution you'd like**
A couple of ideas:

1. Have a command line option where you can specify the classes/methods in the public interface you want `pyright` to look at.
2. Have some way to know the dependencies of the failures.  For example, it could be that one "root" class (e.g., `pandas.Index`) is causing problems for many other parts of the interface, but it is difficult to determine that.

**Additional context**
I tried changing `__init__.py` to contain `__all__ = [ to_datetime ]`, thinking that would force pyright to only look at that function, but that didn't work.

**Comment by erictraut** [comment]
I've updated the "--verifytypes" command to accept a dot-delimited module path. Only the module at that path (and its submodules) are included in the analysis. For example, if you want to focus only on the submodule "pandas.api.types", you can now use "pyright --verifytypes pandas.api.types".

**Comment by Dr-Irv** [comment]
> I've updated the "--verifytypes" command to accept a dot-delimited module path. Only the module at that path (and its submodules) are included in the analysis. For example, if you want to focus only on the submodule "pandas.api.types", you can now use "pyright --verifytypes pandas.api.types".

Great!

Can you specify more than one module path, or would you have to invoke pyright on each module path one-by-one?

**Comment by erictraut** [comment]
You can specify only one module path, so you'd need to do them one at a time. The assumption is that you will be doing this interactively.

**Comment by erictraut** [comment]
This is now addressed in pyright 1.1.103, which I just published.
