### ISSUE TITLE
Higher-kinded type variable misinferred

### ISSUE THREAD

**Issue by tamuhey** [microsoft/pyright#1384]
I wrote like the below code, and pyright failed to infer the type of `e`

```python
from typing import Dict, OrderedDict, TypeVar

T = TypeVar("T", bound=Dict)
K = TypeVar("K")
V = TypeVar("V")


def insert(k: K, v: V, d: T[K, V]) -> T[K, V]:
    d[k] = v
    return d

d = OrderedDict({1: 2})
d: OrderedDict = insert(2, 3, d) # ERROR
```

Output: 

```
  14:18 - error: Expression of type "Dict[int, int]" cannot be assigned to declared type "OrderedDict[Unknown, Unknown]"
    "Dict[int, int]" is incompatible with "OrderedDict[Unknown, Unknown]" (reportGeneralTypeIssues)
```

Pyright resolves `d: T[K,V]` of `def insert` to `Dict[K,V]`, and it maybe the cause.

Though the "higher kinded typevar" is not officially supported (ref: https://github.com/python/typing/issues/548), I decided to report this bug.

## expected behaviour

no error

## pyright version

1.1.102

**Comment by erictraut** [comment]
This behavior is as expected. Higher-kinded types are not supported in the Python type system currently.

**Comment by erictraut** [comment]
Actually, I can understand why you might have thought this would have worked because there was a missing error check. I've added some additional code that emits an error when a type variable is used in a subscript expression within a type annotation.
