### ISSUE TITLE
Output error for `functools.reduce(a,b, initial=...)`

### ISSUE THREAD

**Issue by tamuhey** [microsoft/pyright#1387]
`functools.reduce` doesn't allow keyword arguments, e.g. the below code raises error:

```python
import functools
from operator import add

y = functools.reduce(add, [1, 2, 3], initial=False)
```

But pyright doesn't output any error. I want pyright output error for this code.

**Comment by erictraut** [comment]
Pyright is doing the correct thing in this case based on the signature of the `reduce` function provided in the `functools.pyi` type stub. If you think the stub is incorrect, please file a bug or a PR in the [typeshed repo](https://github.com/python/typeshed). Pyright consumes the stubs from this repo.
