### ISSUE TITLE
Wrongly accept `x: "List"[int]`

### ISSUE THREAD

**Issue by tamuhey** [microsoft/pyright#1393]
```python
from typing import List

foo: "List"[int] = [1]
```

This code raises Exception, but Pyright accepts it.
Mypy also accepts this code.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.104, which I just published. It will also be included in the next release of pylance.
