### ISSUE TITLE
Raising an exception does not count as variable access

### ISSUE THREAD

**Issue by shamrin** [microsoft/pyright#140]
**Describe the bug**
Raising an exception does not count as variable access.

**To Reproduce**
```python
def foo():
    exception = Exception()
    raise exception
```

**Expected behavior**
Expected not to get an `exception is not accessed` error.

**Screenshots or Code**
<img width="292" alt="image" src="https://user-images.githubusercontent.com/510678/58550595-bfc8a580-8216-11e9-8e49-786230841ce8.png">

**VS Code extension or command-line**
Name: Pyright
Id: ms-pyright.pyright
Description: VS Code static type checking for Python
Version: 1.0.35
Publisher: ms-pyright
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by erictraut** [comment]
This is fixed in version 1.0.36, which I just published.
