### ISSUE TITLE
[Question] Constants from class as type

### ISSUE THREAD

**Issue by ZackTherrien** [microsoft/pyright#1403]
Hello,

I have a few classes that define constants. Example:

```
class ConversionConstants:
    KILLOGRAM_TO_GRAM = 1000
    GRAM_TO_KILLOGRAM = 1000

class OtherConstants:
    ...
```

imported in other files as:
```
from constants import ConversionConstants, OtherConstants
```

When used in my functions I declare the types as:
```
def myfunction(self) -> ConversionConstant:
    return ConversionConstants.KILLOGRAM_TO_GRAM
```

When enabling Pylance, this says it isn't correct (rightly so, `1000` is not an instance of the ConversionConstants class...).

Is there a way to do this properly?

**Comment by erictraut** [comment]
There are a few ways to do this correctly depending on your intent.

The first way is to change the return type annotation for `ConversionConstant` to `int`:
```python
def myfunction(self) -> int:
    return ConversionConstants.KILLOGRAM_TO_GRAM
```

The second way is to define the `ConversionConstants` as an `enum` class:
```python
class ConversionConstants(enum.Enum):
    KILLOGRAM_TO_GRAM = 1000
    GRAM_TO_KILLOGRAM = 1000

def myfunction(self) -> ConversionConstants:
    return ConversionConstants.KILLOGRAM_TO_GRAM
```

**Comment by ZackTherrien** [comment]
Genius! Thank you so much 🎉
