### ISSUE TITLE
pyright --verifytypes on numpy master seems to hang

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#1406]
**Describe the bug**
Creating a dev environment using  numpy master and then doing `pyright --verifytypes numpy` gets no response after at least 45 minutes

**To Reproduce**

Clone the numpy repo, build numpy and install it using pip into the same environment as described here:
https://numpy.org/devdocs/user/building.html#building-from-source

`pyright --verifytypes numpy` then doesn't respond.

**Expected behavior**
Results within a minute or so

**VS Code extension or command-line**
pyright command line version 1.1.104

**Additional context**
reference discussion here: 
https://github.com/pandas-dev/pandas/issues/28142#issuecomment-766156268

**Comment by Dr-Irv** [comment]
Seems to hang even if you just get the `numpy` master and do `pyright --verifytypes numpy`

**Comment by erictraut** [comment]
There were some deeply-nested expressions in numpy that were resulting in highly redundant type evaluations. I've extended the type caching mechanism that was already in place to handle these cases. The most problematic file was "lib/tests/test_format.py". It previously took about 600sec (!) to analyze. Now it analyzes in about 850ms.

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.105, which I just published.

**Comment by Dr-Irv** [comment]
@erictraut If I go back to the original way I wrote this issue, using `pyright --verifytypes` on pandas dev and numpy dev, we're back to the bad performance (takes over 30 minutes and still running).  Should I open a new issue or describe what I had before here?

**Comment by erictraut** [comment]
Yes, please open another issue. 

I haven't been successful in building numpy from scratch. It requires a bunch of tooling that I don't have (Fortran compilers and such). I am able to run full type analysis on all ~700 python files that comprise numpy though. This used to hang indefinitely, and it now takes on the order of 10sec to complete.

I am able to build and install pandas from sources, and `pyright --verifytypes pandas` now takes only 3.8s on my machine.

If you're seeing something different, please file a new bug with repro steps.
