### ISSUE TITLE
More inference with lists and for loop constructs

### ISSUE THREAD

**Issue by sbdchd** [microsoft/pyright#1408]
**Is your feature request related to a problem? Please describe.**

Essentially I have a function that processes some data and returns a `list` at the end.

In its most basic form it can be reduced to:

```python
output = []
for i in range(10):
    output.append(i)

reveal_type(output)
```

```
❯ ./node_modules/.bin/pyright main.py
  5:13 - info: Type of "output" is "list[Any]"
0 errors, 0 warnings, 1 info 
Completed in 0.592sec
```

```
❯ ./.venv/bin/mypy main.py
main.py:5:13: note: Revealed type is 'builtins.list[builtins.int*]'
```

**Describe the solution you'd like**

Ideally `pyright` could determine the type of `output` to be `list[int]` like `mypy`

**Additional context**

Pyright defaulting to `list[any]` is described in [docs/type-inference.md#list-expressions](https://github.com/microsoft/pyright/blob/05cdaf934407b5ed063b71ca688cd1033fa733c9/docs/type-inference.md#list-expressions) and [docs/type-inference.md#bidirectional-type-inference-expected-types](https://github.com/microsoft/pyright/blob/05cdaf934407b5ed063b71ca688cd1033fa733c9/docs/type-inference.md#bidirectional-type-inference-expected-types), so this is working as intended, but I think it would be helpful to extend the inference to work in these cases as well.

```
❯ ./node_modules/.bin/pyright --version
pyright 1.1.104
```

`pyrightconfig.json`

```json
{
  "typeCheckingMode": "strict"
}
```

related: https://github.com/microsoft/pyright/issues/705

**Comment by erictraut** [comment]
Type inferences is an inexact science. Pyright's type inference is based on assignment, not based on call arguments. Mypy's type inference approach has many other problems that pyright avoids. I think that on the whole pyright's approach is better than mypy's, but there will be cases like this that are a counterexample. In any case, I have no plans to change the approach in pyright.

There is a simple workaround in this case. Simply provide a type annotation for `output` as follows: `output: List[int] = []`.
