### ISSUE TITLE
PEP-484 compliance for stub generation

### ISSUE THREAD

**Issue by YodaEmbedding** [microsoft/pyright#1409]
**Describe the bug**
[PEP-484](https://www.python.org/dev/peps/pep-0484/#stub-files) requires:
> - Modules and variables imported into the stub are not considered exported from the stub unless the import uses the `import ... as ...` form or the equivalent `from ... import ... as ...` form. (UPDATE: To clarify, the intention here is that only names imported using the form `X as X` will be exported, i.e. **the name before and after `as` must be the same**.)
> - However, as an exception to the previous bullet, all objects imported into a stub using `from ... import *` are considered exported. (This makes it easier to re-export all objects from a given module that may vary by Python version.)

**To Reproduce**
```bash
pyright --createstub tensorflow
< typings/tensorflow/__init__.pyi tail -n +29 | head -n 4
```

Outputs:
```python
from tensorflow.python.framework.sparse_tensor import SparseTensor, SparseTensorSpec
from tensorflow.python.framework.tensor_conversion_registry import register_tensor_conversion_function
from tensorflow.python.framework.tensor_shape import TensorShape
from tensorflow.python.framework.tensor_spec import TensorSpec
```

Furthermore, the completion menu for "`tf.`" is mostly empty:
```python
estimator
initializers
losses
metrics
optimizers
```

**Expected behavior**

Compare with mypy's output via `stubgen -p tensorflow -o typings`:
```python
from tensorflow.python.framework.sparse_tensor import SparseTensor as SparseTensor, SparseTensorSpec as SparseTensorSpec
from tensorflow.python.framework.tensor_conversion_registry import register_tensor_conversion_function as register_tensor_conversion_function
from tensorflow.python.framework.tensor_shape import TensorShape as TensorShape
from tensorflow.python.framework.tensor_spec import TensorSpec as TensorSpec
```

Using `stubgen`, the completions are also correct, containing all symbols:
```python
...
SparseTensor
SparseTensorSpec
...
TensorShape
TensorSpec
...
register_tensor_conversion_function
...
```

**Screenshots or Code**
N/A

**VS Code extension or command-line**
Pyright 1.1.104

**Additional context**
N/A

**Comment by erictraut** [comment]
The current behavior is intentional. Pyright has no way of knowing whether a package author intends for an imported symbol to be re-exported. It defaults to "not re-exported" because the vast majority of imports are internal implementation details and not intended to be re-exported.
