### ISSUE TITLE
Pyright shows errors inside node_modules for node.js projects

### ISSUE THREAD

**Issue by bfelbo** [microsoft/pyright#141]
**Describe the bug**
I use VSCode for both python and node.js projects. Right now I have to disable pyright whenever I open a node.js project because it will find errors inside the `node_modules` folder (e.g. inside `node_modules/generic_pool/fabfile.py`), which makes for a frustrating developer experience.

**To Reproduce**
Open a node.js project and run `npm install --save generic_pool`.

**Expected behavior**
Pyright only throwing errors inside actual Python projects.

**VS Code extension or command-line**
VS Code extension

**Comment by erictraut** [comment]
Thanks for the suggestion. That's a reasonable request. I think it makes sense for pyright not to analyze all files under the root if it doesn't find a pyrightconfig.json file. It can still analyze ".py" files that you open in the editor but should otherwise ignore them.

**Comment by bfelbo** [comment]
That sounds perfect!

**Comment by erictraut** [comment]
The fix will be in the next version.

**Comment by erictraut** [comment]
This is fixed in version 1.0.36, which I just published.

**Comment by bfelbo** [comment]
Perfect, thanks!
