### ISSUE TITLE
inspect.isclass doesn't narrow the type

### ISSUE THREAD

**Issue by MarkKoz** [microsoft/pyright#1412]
**Describe the bug**
Unlike `isinstance`, `inspect.isclass` does not narrow the type. Therefore, one cannot benefit from the improved readability of `inspect.isclass` and has to resort to always using `isinstance`.

**To Reproduce**
```py
import inspect

def test(o: object) -> bool:
    return inspect.isclass(o) and issubclass(o, int)
```

> Argument of type "object" cannot be assigned to parameter "__cls" of type "type" in function "issubclass" "object" is incompatible with "type"

**Expected behavior**
Pyright should realise that `inspect.isclass` ensures `o` is a `type` and therefore not complain when `o` is passed to `issubclass`.

**VS Code extension or command-line**
VS Code 1.52.1 with Pylance v2021.1.2

**Additional context**
It has no problem understanding that `o` is a `type` when `isinstance` is used directly. Note that `isinstance(o, type)` is literally what `inspect.isclass` does internally.

```py
def test(o: object) -> bool:
    return isinstance(o, type) and issubclass(o, int)
```

**Comment by erictraut** [comment]
I don't think this idiom is common enough to justify custom type narrowing logic. I've never heard of `inspect.isclass`, nor have I seen it ever used in practice. I also confirmed that mypy doesn't have any special-case narrowing logic for this case.

**Comment by MarkKoz** [comment]
Fair enough. More generally, this could be addressed by PEP 647 anyway.
