### ISSUE TITLE
`numpy.asarray` inferred as Type[NoseTester]

### ISSUE THREAD

**Issue by tamuhey** [microsoft/pyright#1417]
Pyright doesn't output any error on the following code:

```python
import numpy as np
from numpy.testing._private.nosetester import NoseTester

a: NoseTester = np.asarray([1])
```

because it infer `np.asarray` as `Type[NoseTester]`. 
I've checked numpy code and found that it is annotated as `Callable[[...], np.ndarray`] (code: https://github.com/numpy/numpy/blob/bfc7e4347f9b999712768ef7ca8bb3cd0e17dc63/numpy/core/_asarray.pyi#L20).

I don't think this is a bug in pyright, since there seems to be many problems in typing of numpy, but I report it here.

**Comment by BvB93** [comment]
Do you have numpy >= 1.20 installed?
When analyzing the test code you provided pyright successfully issue a warning for me:
```
Expression of type "ndarray[Unknown, Unknown]" cannot be assigned to declared type "NoseTester"
  "ndarray[Unknown, Unknown]" is incompatible with "NoseTester"
```

**Comment by tamuhey** [comment]
@BvB93 Thanks!
