### ISSUE TITLE
CLI error "TypeError: s.watch is not a function"

### ISSUE THREAD

**Issue by DVMVCGCG** [microsoft/pyright#1427]
**Describe the bug**
I get this error whenever running pyright from the command line:

```
(node:44604) UnhandledPromiseRejectionWarning: TypeError: s.watch is not a function
    at M (/Users/dvmv/Code/cc2/node_modules/pyright/dist/vendor.js:2:34121)
    at /Users/dvmv/Code/cc2/node_modules/pyright/dist/vendor.js:2:35834
    at e.exports._watchWithFsEvents (/Users/dvmv/Code/cc2/node_modules/pyright/dist/vendor.js:2:36136)
    at e.exports.initWatch (/Users/dvmv/Code/cc2/node_modules/pyright/dist/vendor.js:2:37526)
    at e.exports._addToFsEvents (/Users/dvmv/Code/cc2/node_modules/pyright/dist/vendor.js:2:38745)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:44604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**VS Code extension or command-line**
Command line, version 1.1.106

**Comment by erictraut** [comment]
What version of node do you have installed on your system? (`node --version`)

I'm guessing that it's too old for pyright.

**Comment by DVMVCGCG** [comment]
That was it. I was running `v12.14.1`. After upgrading to `v14.15.4` the error went away.

**Comment by jakebailey** [comment]
It's concerning that 12.14.1 doesn't work, as that's precisely the version we run with under VS Code (and we test with v12 to match). Did a previous version work?

**Comment by DVMVCGCG** [comment]
I've been using Pylance in VSCode for many months without problems. But I just started using the pyright CLI directly and version `1.1.106` is the only version I've tried.

**Comment by jakebailey** [comment]
Certainly confusing. I've checked and that trace comes from chokidar, and the version we use definitely supports Node v12.

**Comment by jakebailey** [comment]
On looking at chokidar's code and your output (your $HOME implies you're on a Mac), this seems like it's coming from chokidar's fsevents code. Our packaging process doesn't include fsevents as npm only installs it correctly on Macs (so builds can't be reproduced), and chokidar is supposed to be handling the missing module gracefully. I'd have expected this to completely crash in VS Code as well, so I don't really know what's going on.

At least upgrading Node worked, though? 🤷

**Comment by DVMVCGCG** [comment]
chokidar is one of those packages that does weird things in my experience. Any package that has system level dependencies really. But upgrading Node worked, and v12 is getting old, so consider this issue resolved from my perspective. Thanks for the quick reply.
