### ISSUE TITLE
SupportsLessThan incompatible with int within class

### ISSUE THREAD

**Issue by emj1991** [microsoft/pyright#1428]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**
When creating a TypeVar with bound=SupportsLessThan to use in a class, int, str, and float are listed as incompatible within the class. It is handled correctly when creating an instance. See screenshot below for clear example.

**To Reproduce**
Screenshot of simple code below.

**Expected behavior**
Built in types like int, support comparisons so this shouldn't be highlighted.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/3459761/106071139-a9917d80-60ba-11eb-8499-2ddd329a7e46.png)
![image](https://user-images.githubusercontent.com/3459761/106071176-b9a95d00-60ba-11eb-861f-b554f501a329.png)

**VS Code extension or command-line**
Running from Pylance 2021.1.3 which is using pyright 1.1.106

**Additional context**

**Comment by erictraut** [comment]
The type of `val` is `T`, which is bound to `SupportsLessThan`, but you're trying to pass it to a method that requires an `int`. Pyright is correctly reporting that `SupportsLessThan` cannot be assigned to an `int`. The converse would work fine — i.e. if you were trying to assign an `int` to a `SupportsLessThan`, there would be no error reported.

**Comment by emj1991** [comment]
Yup that's a very fair point.
