### ISSUE TITLE
Local module are not being resolved

### ISSUE THREAD

**Issue by ruppysuppy** [microsoft/pyright#1429]
**Describe the bug**
Local module are not being resolved when they are imported and the module is present in a sub-folder of the current working directory.

**To Reproduce**
1. Create a local module within a folder of the directory you are working in
2. Import something from the module created in step 1

**Expected behavior**
The required class/function/variable to be imported without the warning

**Screenshots or Code**
![bug](https://user-images.githubusercontent.com/44058757/106088079-47cd2400-614b-11eb-8f8a-8030c0e4d0e1.gif)
The folder structure for the demo above is as follows:
```
    :root (directory opened in VSCode)
        Solutions
            DataStructures (module)
                Trie.py
                ...
            227.py (file importing the class from)
```

**VS Code extension or command-line**
Pyright is being used with Pylance (v2021.1.3) as a VS Code extension

**Comment by erictraut** [comment]
Yes, this is the intended behavior. The Python interpreter will also not look in subdirectories for local imports unless you configure its import search paths accordingly. You can specify these paths in the `python.analysis.extraPaths` setting. Or for more complex multi-app/multi-script workspaces, you can configure individual execution environments each with their own import resolution paths. For more details, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md).
