### ISSUE TITLE
Freezes when used with sympy.diff

### ISSUE THREAD

**Issue by Zeta611** [microsoft/pyright#1439]
**Describe the bug**
Pyright seems to freeze--at least the coc-pyright running nvim freezes--for about a minute when I use `sympy.diff` method.

**To Reproduce**
The following code:
```python
import sympy as sp
a = sp.diff(sp.Symbol("x"))
```
causes Neovim (running coc-nvim) to freeze when I try to show documentation for `diff` using a keymap:
```vim
" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction
```
Moreover, it seems that any code including the above snippet blocks other part of the code to be analyzed.

**Expected behavior**
It should show the doc for the `sympy.diff`. It does work for the following code:
```python
import sympy
sympy.init_printing(use_unicode=True)
```

**Screenshots or Code**
Example code is given above.

**VS Code extension or command-line**
I'm running pyright as a Coc.nvim extension in Neovim.

coc-pyright 1.1.106

**Additional context**
I tried to debug the LS via `:CocCommand workspace.showOutput` with the verbose option to the LS, and found out that requesting `textDocument/hover` took 43520ms:
```
[Trace - 6:09:48 AM] Received response 'textDocument/hover - (1)' in 43520ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```python\n(function) diff: (f: Unknown, *symbols: Unknown, **kwargs: Unknown) -> Unknown | ArrayDerivative | Derivative\n```\nDifferentiate f with respect to symbols.\n\nExplanation\n===========\n\nThis is just a wrapper to unify .diff() and the Derivative class; its\ninterface is similar to that of integrate().  You can use the same\nshortcuts for multiple variables as with Derivative.  For example,\ndiff(f(x), x, x, x) and diff(f(x), x, 3) both return the third derivative\nof f(x).\n\nYou can pass evaluate=False to get an unevaluated Derivative class.  Note\nthat if there are 0 symbols (such as diff(f(x), x, 0), then the result will\nbe the function (the zeroth derivative), even if evaluate=False.\n\nExamples\n========\n\n```\n>>> from sympy import sin, cos, Function, diff\n>>> from sympy.abc import x, y\n>>> f = Function('f')\n```\n\n```\n>>> diff(sin(x), x)\ncos(x)\n>>> diff(f(x), x, x, x)\nDerivative(f(x), (x, 3))\n>>> diff(f(x), x, 3)\nDerivative(f(x), (x, 3))\n>>> diff(sin(x)*cos(y), x, 2, y, 2)\nsin(x)*cos(y)\n```\n\n```\n>>> type(diff(sin(x), x))\ncos\n>>> type(diff(sin(x), x, evaluate=False))\n<class 'sympy.core.function.Derivative'>\n>>> type(diff(sin(x), x, 0))\nsin\n>>> type(diff(sin(x), x, 0, evaluate=False))\nsin\n```\n\n```\n>>> diff(sin(x))\ncos(x)\n>>> diff(sin(x*y))\nTraceback (most recent call last):\n...\nValueError: specify differentiation variables to differentiate sin(x*y)\n```\n\nNote that `diff(sin(x))` syntax is meant only for convenience\nin interactive sessions and should be avoided in library code.\n\nReferences\n==========\n\nhttp://reference.wolfram.com/legacy/v5\\_2/Built-inFunctions/AlgebraicComputation/Calculus/D.html\n\nSee Also\n========\n\nDerivative\nidiff: computes the derivative implicitly"
    },
    "range": {
        "start": {
            "line": 38,
            "character": 19
        },
        "end": {
            "line": 38,
            "character": 23
        }
    }
}
```

Tested using the following minimal init.vim:
```vim
set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
set runtimepath^=~/.config/coc/extensions/node_modules/coc-pyright

let g:python3_host_prog = expand('~/.pyenv/versions/3.8.5/bin/python')

" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction
```

**Comment by erictraut** [comment]
The hang is explained by a combination of the following:
1. Sympy is a large and complex package that has no type annotations or type stubs.
2. I presume that you have enabled the "useLibraryCodeForTypes" feature in pyright. By default, this is disabled, and pyright will not attempt to infer missing type information from source code if type stubs are not present. By enabling this, you're telling pyright that it should infer types. For a library as complex as Sympy, this can be very expensive.
3. Pyright supports async (file-based) cancellation tokens that allow requests to be canceled if they take too long, but coc-pyright doesn't support these tokens. That means every action (e.g. a hover request or completion request) is synchronous and non-cancelable.

Your options here include:
1. Switch to VS Code, which supports file-based cancellation tokens.
2. Disable useLibraryCodeForTypes.
3. Locate (or create) type stubs for Sympy.

Any one of those three will mitigate the issue.

**Comment by Zeta611** [comment]
@erictraut You are right, coc-pyright defaults useLibraryCodeForTypes to true. Disabling it resolved the issue. Thank you for the help!
