### ISSUE TITLE
opencv module autocomplete is not working

### ISSUE THREAD

**Issue by s1n7ax** [microsoft/pyright#1445]
I'm using `pyright` with Neovim built-in lsp. [This](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/pyright.lua) is the default configuration provided from lspconfig.

```lua
  default_config = {
    cmd = {bin_name, "--stdio"};
    filetypes = {"python"};
    root_dir = function(filename)
      return util.root_pattern(unpack(root_files))(filename) or
             util.path.dirname(filename)
    end;
    settings = {
      python = {
        analysis = {
          autoSearchPaths = true;
          useLibraryCodeForTypes = true;
        };
      };
    };
   };
```

I have `opencv-python` and `numpy` modules installed. As far as I can tell, auto completion for `numpy` module is working totally fine.

**numpy completion menu**
![numpy auto completion](https://i.imgur.com/Ly4vfCP.png)

**opencv completion menu**
![opencv autocompletion](https://i.imgur.com/LSpezCe.png)

I have tried `from cv2 import cv2` which some have suggested, that did not work

**Comment by erictraut** [comment]
As Jake said, opencv doesn't include type stubs, and it is not implemented in Python, so there's no Python source code for pyright to analyze. You would need to find (or create) type stubs to get auto-completion functionality.
