### ISSUE TITLE
Feedback on "Typing Guidance for Python Libraries"

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#1446]
You asked for feedback on the "Typing Guidance" documentation page (https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md), so I took a look. Overall it's a great treatment of the topic that should be very helpful to library authors. I do have a few minor comments:
- "But a parameter typed as List[Union[str, int]] is much more restrictive and accepts only a List[Union[str, int]] or Sequence[Union[str, int]]." This seems wrong (although I haven't checked how Pyright behaves here): it's not legal to pass a Sequence to a parameter typed as List.
- "Name-only parameters" are more commonly called "keyword-only"; I haven't seen the term "name-only" before.
- "The NamedTuple form of data classes" is odd wording; I suppose it refers to variable annotations but those aren't restricted to NamedTuples.
- A few constructs that are said to only work in newer versions of Python actually work in older versions through backports like `typing_extensions` and https://pypi.org/project/dataclasses/ (but I haven't checked if pyright supports these backports). This is mentioned later on, but it feels misleading to say that TypedDict was "introduced in Python 3.8" without mentioning that `typing_extensions.TypedDict` works in older versions too: it could mislead readers into thinking they can't use TypedDict in code that needs to support older versions of Python.

**Comment by erictraut** [comment]
Thanks, I appreciate your feedback. I've updated the document to reflect all of the points you've made.
