### ISSUE TITLE
PyCharm support

### ISSUE THREAD

**Issue by dubreuia** [microsoft/pyright#1447]
**Is your feature request related to a problem? Please describe.**
It seems Pyright insn't integrated in PyCharm (see [Installation](https://github.com/microsoft/pyright#installation) section of the documentation), I would like to know if that's something that is being worked on or in the roadmap?

**Describe the solution you'd like**
Pyright integration in PyCharm like in VSCode

**Additional context**
It seems most Pyright integrations are based on LSP, which I understand isn't well supported in PyCharm

**Comment by erictraut** [comment]
No, there's no support planned for PyCharm. Pyright was designed primarily for VS Code. It has been adapted by others for use within other editors that support LSPs. If you are interested in adapting it for PyCharm, you're welcome to do so.
