### ISSUE TITLE
FEATURE: add "python.autoComplete.addBrackets"

### ISSUE THREAD

**Issue by walkert** [microsoft/pyright#1450]
**Is your feature request related to a problem? Please describe.**
As a long-time user of Jedi for completion, one of the things I've come to appreciate with its integration with coc-nvim/coc-python is the auto-insertion of brackets when a function or function/method is suggested and accepted. I'm trying out `coc-pyright` and the thing I miss the most is this feature.

**Describe the solution you'd like**
I would like the flow to look like:

1. Type `requests.ge<hit tab>` and the `get` function is suggested.
2. Hit Enter and `()` will be added to the end of the completion with the cursor inserted between them.

**Comment by erictraut** [comment]
Pyright is primarily a type checker. It has some basic language server features, but most of our work on new, more advanced language server features is being done in Pylance, the VS Code extension built on top of Pyright. Pylance has already implemented the requested feature. It is controlled by the setting `python.analysis.completeFunctionParens`.

We don't have any plans to port this or other new language server features to Pyright.

**Comment by walkert** [comment]
Thanks for the info @erictraut.
