### ISSUE TITLE
Tell Pyright about implicitly defined variables

### ISSUE THREAD

**Issue by lanza** [microsoft/pyright#1454]
It would be nice to be able to tell Pyright about implicitly defined variables. e.g. when a file is used by some other project as a configuration file. An explicit example is when using llvm's lit configuration files. You just assume the existence of an object called `config` and edit it's known properties from the docs.

```
config.test_format = lit.formats.ShTest(True)
```

This `config` variable isn't defined in that file -- that file is imported and ran with the `config` var handed off to it. It would be nice to be able to write

```
# config: lit.TestingConfig.TestingConfig
config.test_format = lit.formats.ShTest(True)
```

where the first line's only purpose is to tell Pyright about the variable.

**Comment by erictraut** [comment]
I think it's an inadvisable pattern to use implicitly defined variables that are injected dynamically into a module's namespace. That goes against the whole notion of static type checking. So my first suggestion is to avoid this design pattern in the first place.

If this design pattern already exists and you cannot change it, here is an existing workaround. You can define the variable and assign it a value locally using a `TYPE_CHECKING` conditional:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    config: lit.TestingConfig.TestingConfig = {}

config.test_format = lit.formats.ShTest(True)
```
