### ISSUE TITLE
Support for $VIRTUAL_ENV

### ISSUE THREAD

**Issue by jzelinskie** [microsoft/pyright#1456]
**Is your feature request related to a problem? Please describe.**

I'm using pyright from neovim. My Python environment is configured in my shell to use a virtualenv (using pyenv, but that _should be_ irrelevant). pyright is throwing `Import <library> could not be resolved`.

**Describe the solution you'd like**

I shouldn't need to write a config file for pyright to execute in a correctly configured Python environment.
Ideally, pyright falls back to reading $VIRTUAL_ENV after trying to find its config file.

It looks like there was a previous discussion to add a fallback to $PYTHONPATH, but $VIRTUAL_ENV is far more common a use case for people developing with a terminal based editor.

**Additional context**

My apologies in advanced if I missed something while searching the repo/issues.

**Comment by erictraut** [comment]
If you configure your python environment before launching your editor, pyright will automatically discover the correct import resolution paths. It does so by executing "python" and running a one-line script that dumps the sys.path variable. This eliminates the need to query shell variables and should give you the same results that you see with the configured python interpreter.

**Comment by jzelinskie** [comment]
Thanks for the quick response. The shell is configured before launching the editor, so method you described should work. I'll have to dig deeper to see whats going on.

**Comment by erictraut** [comment]
You may want to use the "verboseOutput" option in the pyrightconfig.json file. If this is set to true, pyright will emit a bunch of extra logging that may help diagnose import resolution issues like this. For more details, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md#main-pyright-config-options).

**Comment by jzelinskie** [comment]
Thanks again -- setting verbose on pyright and debug log level on neovim's LSP helped me find the real issue.

pyright was successfully calling through the pyenv shim, but the virtualenv was not set. When I manually set $PYENV_VERSION, everything worked fine. This is because I am usually setting the virtualenv using pyenv's local `.python-version` file, and I had installed pyright into a totally different directory. By moving the the install directory into the project itself, pyright is being now executed from a a child directory of where the `.python-version` file is and the pyenv shim successfully activates the virtualenv.

The aforementioned sys.path solution avoids having to muck with all this tooling -- it's the right design choice for sure.

What a rabbithole from unfortunate tooling interactions! 🐰
Well, at least I learned to debug language servers and read a ton of neovim's implementation, haha.

**Comment by alefpereira** [comment]
Hello people, checkout this plugin [pyenv-pyright](https://github.com/alefpereira/pyenv-pyright) I created.
With it you can setup pyright to use pyenv venvs with only one command:

```
pyenv local my-venv
pyenv pyright
```
or

```
pyenv pyright my-venv
```

This will automatically create/update `.pyrightconfig.json` file. Its a convenient way to overcome neovim+pyright+pyenv virtualenvs setup.
https://github.com/alefpereira/pyenv-pyright

**Comment by urayoru113** [comment]
In my case
```python
  pyright = {
    settings = {
      python = {
        pythonPath = (function()
          if vim.fn.executable("pyenv") == 1 then
            return vim.fn.system("echo -n `pyenv which python`")
          else
            return vim.fn.system("echo -n `which python`")
          end
        end)(),
        venvPath = "",
      },
    },
  },
```
This works for me
