### ISSUE TITLE
Is there any way to export python file AST nodes?

### ISSUE THREAD

**Issue by fannheyward** [microsoft/pyright#1458]
**Describe the solution you'd like**

for empale something like `pyright --ast main.py` to print the parsed nodes type of the python file?

**Additional context**

Thanks for your work on Pyright.

**Comment by erictraut** [comment]
While pyright does contain a parser and produce an internal parse tree, this is an internal implementation detail. It's not exposed, and it changes pretty frequently as new features are added. I don't have any plans to expose it.

The Python interpreter itself contains a parser and exposes the AST, so if you want access to a parse tree, I recommend going with that approach.

**Comment by erezsh** [comment]
@erictraut But pyright's AST contains inferred type information, which would be very useful to have, for writing additional tools on top of it.

**Comment by Zzzen** [comment]
you might be interested in https://github.com/Zzzen/pyright-ast-viewer
