### ISSUE TITLE
Incomplete stub files created for cv2 module.

### ISSUE THREAD

**Issue by listout** [microsoft/pyright#1461]
**Describe the bug**
Wrong/Incomplete .pyi files generated when trying to generate stubs for `cv2` module. Am I doing some thing wrong or is this an issue of the `cv2` module ?

**To Reproduce**
`pyright --createstub cv2`

**Expected behavior**
Correct/Complete .pyi files generated.

**Screenshots and Code**

When opencv is installed with my linux distro's package manager, the contents of typings folder are:
```
.
└── cv2
    └── __init__.pyi
```
Contents of the `__init__.pyi` file
```python
"""
This type stub file was generated by pyright.
"""
@ < Expression >
class:
    ...

```
When I install the `opencv-python` through pip, a bit more files are created but still not helpful. Contents of the typings folder this time:
```
.
└── cv2
    ├── cv2.cpython-39-x86_64-linux-gnu.pyi
    ├── data
    │   └── __init__.pyi
    ├── __init__.pyi
    └── version.pyi
```
Contents of the `__init__.pyi` file this time
```python
"""
This type stub file was generated by pyright.
"""

import importlib
import os
import sys
from .cv2 import *
from .data import *

ci_and_not_headless = False
if sys.platform.startswith("linux") and ci_and_not_headless:
    ...
if sys.platform.startswith("linux") and ci_and_not_headless:
    ...
```

**VS Code extension or command-line**
I tried pyright from terminal after installing it through `npm`, same result when using `coc-pyright`'s `pyright.createtypestub` command. 

For now manually creating stubs using mypy's stubgen command seems to create a correct file.

This is what the .pyi file created with stubgen looks like:
```python
...
def BRISK_create(*args, **kwargs) -> Any: ...
def CamShift(*args, **kwargs) -> Any: ...
def Canny(*args, **kwargs) -> Any: ...
def CascadeClassifier_convert(*args, **kwargs) -> Any: ...
def DISOpticalFlow_create(*args, **kwargs) -> Any: ...
def DescriptorMatcher_create(*args, **kwargs) -> Any: ...
def EMD(*args, **kwargs) -> Any: ...
def FarnebackOpticalFlow_create(*args, **kwargs) -> Any: ...
...
```

**Comment by listout** [comment]
Tested on numpy and matplotlib modules, works as intended.

**Comment by erictraut** [comment]
Cv2 is not implemented in Python, so Pyright has no source code from which it can extract type information. It looks like mypy's stub generator may be loading the cv2 library and using reflection to get a list of symbols, but you'll notice that it is getting no type information other than function names (i.e. no input parameter names/types and no return types), so those stubs are pretty close to useless.

You will probably need to hand-generate type stubs in this case. Or better yet, convince the authors of opencv to publish type information with their package.

**Comment by listout** [comment]
Thank you. You are correct about the stubs having no type information.

There is already an open issue about this on opencv's github.

**Comment by jdhao** [comment]
Opencv issue is this one: https://github.com/opencv/opencv/issues/14590
