### ISSUE TITLE
Allowing incompatible method redefinitions

### ISSUE THREAD

**Issue by vberlier** [microsoft/pyright#1469]
Hi! I'd like to be able to tell pyright that it's okay to change the signature of an inherited method because the base class is only meant to be used as a mixin. Kind of a contrived example but hopefully you can see what I mean:

```python
from typing import Protocol

class HasFoo(Protocol):
    """Protocol for detecting a .foo(str) method."""
    def foo(self, message: str):
        ...

class BarMixin(HasFoo):
    """Mixin that implements .bar(int) using the .foo(str) method."""
    def bar(self, number: int):
        self.foo(str(number))

class MyClass(BarMixin):
    """Class that defines a .foo(str) method and wraps the mixin's .bar(int) implementation."""
    def foo(self, message: str):
        print(message)

    def bar(self, num1: int, num2: int):  # Method "bar" overrides class "BarMixin" in an incompatible manner
        super().bar(num1 + num2)
```

Sure, I could easily dismiss the error by adding `# type: ignore` but I'm wondering if there's something that can be done to make pyright understand the pattern. In this example, the redefinition of the "bar" method only breaks covariance, so it would be nice if pyright could allow it and instead show an error if we were to use the mixin class in type annotations, or maybe treat the mixin class like an invariant type variable in type annotations.

**Comment by erictraut** [comment]
This is a dangerous design pattern, the sort that the `reportIncompatibleMethodOverride` was intended to detect and report. If possible, I recommend eliminating overlapping of methods with the same name but with different signatures within a class hierarchy.

If that's not an option, you can disable the `reportIncompatibleMethodOverride` rule for your entire project or on a per-file basis using `# pyright: reportIncompatibleMethodOverride=false`.

**Comment by vberlier** [comment]
I agree and I'm trying to avoid this as much as possible. But I'm also curious. Since the redefinition is technically not an issue until I try to give an instance of "MyClass" to something that expects an instance of "BarMixin", how difficult would it be to report the problem at the call site instead?

```python
# Maybe using a mixin in a type annotation should report an error
def call_bar(obj: BarMixin):  
    obj.bar(42)

# The other option would be detecting that MyClass has incompatible redefinitions and report the error here
call_bar(MyClass())  
```

**Comment by erictraut** [comment]
I think it's correct and appropriate to report it in its current location. If you don't want to address it in your code, you can disable the diagnostic rule.

**Comment by vberlier** [comment]
Fair enough. Thanks for your feedback. Keep up the good work 🙂
