### ISSUE TITLE
about type check: Expression of type "str | None" cannot be assigned to declared type "str"

### ISSUE THREAD

**Issue by Tsyshiu** [microsoft/pyright#1470]
I am using Pylance(v2021.2.0) in VSCode(v1.53.0). 
And it gave me such an error: 
**Expression of type "str | None" cannot be assigned to declared type "str"
  Type "str | None" cannot be assigned to type "str"
    Type "None" cannot be assigned to type "str" PylancereportGeneralTypeIssues)**

with this line: 
![image](https://user-images.githubusercontent.com/38075786/107496269-0bc6a400-6bcc-11eb-9d82-9d31c3336378.png)

As `os.getenv("USERPROFILE")` may return None or a Str(see 👇
![image](https://user-images.githubusercontent.com/38075786/107497569-b8555580-6bcd-11eb-9e73-48a94e57ae9d.png)
), I ensured that the value assigned to `initial_path` to be not None, but Pylance still prompted this error.

This error also occurs when code typed as below: 
![image](https://user-images.githubusercontent.com/38075786/107497451-8fcd5b80-6bcd-11eb-87ba-6b6d92bdf319.png)

I hope it can contribute to improvements of Pylance. 😊

**Comment by erictraut** [comment]
This is by design. Pyright cannot assume that a function call is going to return the same thing multiple times, so it never narrows types of expressions that contain function calls. To make this work as you are hoping, you would need to assign the result of the function call expression to a temporary variable:

```python
path_from_profile = os.getenv("USERPROFILE")
initial_path = path_from_profile if path_from_profile is not None else "C:"
```

**Comment by Tsyshiu** [comment]
Thanks for your feedback! @erictraut
