### ISSUE TITLE
link to nodejs.org on main readme broken 

### ISSUE THREAD

**Issue by martinResearch** [microsoft/pyright#1477]
**Describe the bug**
The nodejs.org link on the readme pages is broken 
it links to  https://github.com/microsoft/pyright/blob/master/nodejs.org
instead of  https://nodejs.org

**To Reproduce**
click on the link in the readme on the github page

**Expected behavior**
Open page https://nodejs.org/ and not https://github.com/microsoft/pyright/blob/master/nodejs.org

**Comment by erictraut** [comment]
Thanks for the bug report. It's now fixed.
