### ISSUE TITLE
Return statement not taken into account when using ExitStack

### ISSUE THREAD

**Issue by vberlier** [microsoft/pyright#1514]
`ExitStack()` somehow hides the return statement and Pyright reports that the function doesn't return a value:

```python
from contextlib import ExitStack

def foo() -> str:  # error
    with ExitStack() as stack:
        return stack.enter_context(open("foo.txt")).read()
```

```
Function with declared type of "str" must return value
  Type "None" cannot be assigned to type "str"
```

With a dummy return statement the error goes away:

```diff
 def foo() -> str:
     with ExitStack() as stack:
         return stack.enter_context(open("foo.txt")).read()
+    return "hello"
```

**Comment by erictraut** [comment]
Pyright is doing the right thing here.

`ExitStack` is a context manager that catches and handles exceptions. You can tell by looking at the declaration for the `ExitStack` class. The `__exit__` method is declared as follows:
```python
        def __exit__(
            self,
            __exc_type: Optional[Type[BaseException]],
            __exc_value: Optional[BaseException],
            __traceback: Optional[TracebackType],
        ) -> bool: ...
```

A context manager whose `__exit__` method has a return type annotated as `bool` is assumed to catch and handle exceptions.

If an exception occurs within the `ExitStack` context manager, the `return` statement will never be completed, and the code will fall through to the bottom of the function, which will return a `None` result.

**Comment by vberlier** [comment]
Good to know. Thanks.
