### ISSUE TITLE
Cannot detect duplicate variable assignments

### ISSUE THREAD

**Issue by lsDrizzle** [microsoft/pyright#1519]
**Describe the bug**
While I have set `reportUnusedVariable: warning` in Pyright's config file, Pyright can still not detect duplicate variable assignments like this:
```Python
a = 1
a = 2

b = a
```

**To Reproduce**
Just type the code in VS Code (using the Pyright extension) or Vim (using coc-pyright) and observe if a warning will appear.

**Expected behavior**
Without `b = a`, Pyright will correctly show `Variable "a" is not accessed`, but after `b = a` is added, it will not show the same warning on `a = 1`. I think this is not expected since `a = 1` is not used at all.

**Screenshots or Code**
Correct (showing warning):
![image](https://user-images.githubusercontent.com/46703360/108623379-c0d54800-7479-11eb-8f4d-b989177d4cf1.png)

Incorrect (not showing warning on `a = 1`):
![image](https://user-images.githubusercontent.com/46703360/108623411-ec583280-7479-11eb-99c8-5735314c28cd.png)

**VS Code extension or command-line**
VS Code extension, version: 1.1.113
Same bug happens on coc-pyright when using vim/neovim.

**Comment by erictraut** [comment]
It is working as intended. Symbol usage is tracked _per symbol_. In your example, the symbol `a`, which corresponds to a local variable, is being used. Tracking whether a _particular assignment_ of a symbol is used would require a different approach. While it would be possible to implement this, it would add additional runtime computation and would (I'd argue) add relatively little value, so I'm not inclined to add that support.

**Comment by lsDrizzle** [comment]
Thank you for the explanation. It's clear and I completely understand. I'll seek an additional tool supporting this feature.
