### ISSUE TITLE
Add command-line parameter for specifying the desired python version

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#1527]
For typeshed validation, it would be useful to allow the caller to invoke the CLI with a specified python version. This could still be overridden with the pyrightconfig.json file.

**Comment by jakebailey** [comment]
Mypy also lets you set the platform, and typeshed uses this in their CI. Allowing that to be set would be useful to get the full spread as well.

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.115, which was just published.
