### ISSUE TITLE
TYPE_CHECKING leading to unreachable code

### ISSUE THREAD

**Issue by adrianimboden** [microsoft/pyright#1531]
**Describe the bug**
I saw that you already check for the TYPE_CHECKING variable and don't mark it as unused code in this issue https://github.com/microsoft/pyright/issues/616.

**Expected behavior**
I think the variable TYPE_CHECKING should be treated as type bool, not literal true.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/2713705/109022254-f36e8300-76bb-11eb-8d6b-c2b5b9b3cbf4.png)

**Comment by erictraut** [comment]
It's very important that `TYPE_CHECKING` is treated as literal true. Treating it otherwise would break most code that makes use of this feature.

**Comment by erictraut** [comment]
Incidentally, I recommend against using `TYPE_CHECKING` wherever possible because it means that the code being type-checked is not the same as the code that the interpreter sees, which can easily lead to bugs that are not reported by the type checker.

**Comment by adrianimboden** [comment]
Ah ok I see another drawback now as i dig deeper into it. The typechecker would have to check everything with both codepaths to be useful with TYPE_CHECKING things in effect. This would of course not be reasonable, as the amount of cases would blow up.

I assume I should should create type stubs in this case.

**Comment by DetachHead** [comment]
obviously the type checker needs to think `TYPE_CHECKING` is always true for it to work, but the unreachable code warning should make an exception for it
