### ISSUE TITLE
logging._FilterType alias in typeshed thinks Filter and LogRecord are Unknown

### ISSUE THREAD

**Issue by jakebailey** [microsoft/pyright#1539]
While working on improving typeshed (with the new pyrightconfig there), I noticed that for some reason `_FilterType` was partially unknown. Pylance semantic highlighting shows this pretty clearly:

![image](https://user-images.githubusercontent.com/5341706/109215304-da231080-7767-11eb-928b-29f5fc6a9d8f.png)

However, the two types are defined the same file below as plain classes. The types are used elsewhere fine, but for this type, the forward use doesn't seem to work for some reason.

These stubs are about to be reworked in a typeshed PR, but this still seems like a bug.

**Comment by erictraut** [comment]
Yes, good catch. This was specific to type alias definitions found within a type stub that referred to a forward-declared class.

**Comment by jakebailey** [comment]
Fails one test in CI, it seems.

**Comment by erictraut** [comment]
CI failure was unrelated to this change. It's now fixed.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.116, which I just published. It will also be in the next release of pylance.
