### ISSUE TITLE
I am getting "is not a known member of module" errors when using pytorch

### ISSUE THREAD

**Issue by joaqo** [microsoft/pyright#1542]
Hi, just started using pyright and I absolutely love the library, thanks a ton for your work!

Everything is working perfectly except for the library having some issues accessing certain pytorch members. I get the error in the title on several (but not all) pytorch lines in my code. Here is a short code snippet to reproduce the bug:

```python
import torch

torch.cuda  # [Pyright reportGeneralTypeIssues] [E] "cuda" is not a known member of module
```
Whats funny is that 'go to definition' works perfectly on `cuda`.

Is there anyway to fix this? And if there is no current way to fix this, is there an easy way to stop pyright from showing error messages so I can ignore this error for the time being?

Thanks a ton!

Edit: Tried setting "python.analysis.useLibraryCodeForTypes": false but the problem persists.

**Comment by jakebailey** [comment]
See: 

- https://github.com/pytorch/pytorch/issues/47027
- https://github.com/pytorch/pytorch/pull/52339

**Comment by erictraut** [comment]
The top-level torch module doesn't appear to export the symbol `cuda` directly. You would need to `import torch.cuda` to load that submodule. If you're able to access `cuda` directly from `torch`, that's only because you're getting lucky and someone else happens to be importing it before you.

So the simple fix is:
```python
import torch.cuda
```

**Comment by joaqo** [comment]
Gotcha, thanks a lot. Short question, is there a way to disable pyright from showing me errors?

Code like the following is extremely common in the projects I'm working with and it would frankly just be easier to not use the error highlighting of pyright (but still use the amazon code completion, go to definition, etc).

```python
import torch

torch.cuda  
```

Thanks!

**Comment by erictraut** [comment]
Yes, pyright is very configurable. If you change the "python.analysis.typeCheckingMode" to "off", most classes of errors will be silenced.

**Comment by joaqo** [comment]
Thanks for the answer @erictraut, regrettably setting that option didn't fix my issue. Isn't there a more global way to just stop pyright from showing any kind of error information?

**Comment by erictraut** [comment]
What error(s) are you still seeing once typeCheckingMode is set to "off"?

**Comment by joaqo** [comment]
The pytorch import errors such as

```python
import torch

torch.cuda
```

This is my CocConfig:

```json
{
  "python.formatting.provider": "black",
  "python.linting.pylintEnabled": true,
  "python.linting.enabled": true,
  "python.jediEnabled": false,
  "python.venvPath": "path/to/venv/dir",
  "python.pythonPath": "path/to/venv/python/bin",
  "diagnostic.checkCurrentLine": true,
  "python.analysis.useLibraryCodeForTypes": false,
  "python.analysis.typeCheckingMode": false
}
```

**Comment by erictraut** [comment]
You are not using the correct value for "typeCheckingMode". It should be:
```
"python.analysis.typeCheckingMode": "off"
```

**Comment by joaqo** [comment]
Oh I'm so sorry, for some I automatically converted `off` to `false` in my mind. Works flawlessly now, thanks!
