### ISSUE TITLE
Pyright incorrectly determines type of `classmethod` return value when it processes `super()` call

### ISSUE THREAD

**Issue by poul1x** [microsoft/pyright#1557]
**Describe the bug**
Pyright incorrectly determines type of `classmethod` return value when it processes `super()` call.

**To Reproduce**

```python
class A:

    a: str

    @classmethod
    async def instance(cls):
        self = cls()
        self.a = 'a'
        return self

class B(A):

    b: str

    @classmethod
    async def instance(cls):
        self = await super(B, cls).instance()
        self.b = 'b' # Error: Shows that type of self is A, however it's B
        return self


b = await B.instance()
```

**Expected behavior**
No error

**Screenshots or Code**

<div align="center">
<img alt="demo" src="https://user-images.githubusercontent.com/31695750/109553095-a5a2b200-7ae3-11eb-9815-2cbacec22187.png" height="400"/>
</div>

<br>

**VS Code extension**: ms-pyright.pyright 1.1.116
**python**: 3.7

**Comment by erictraut** [comment]
Without a return type annotation, the `cls` parameter in `A.instance` has the type `Type[A]`. 

You can provide an explicit annotation as follows:

```python
from typing import Type, TypeVar

_T = TypeVar("_T", bound="A")


class A:
    a: str

    @classmethod
    async def instance(cls: Type[_T]) -> _T:
        self = cls()
        self.a = "a"
        return self
```

**Comment by poul1x** [comment]
Ok, but I don't know how to apply this to code.

```python
self = await super(B, cls).instance()
```

I want Pyright to think that `self` is type of `B` here (actually, it is). 
But Pyright thinks `self` is type of `A`. And shows errors in valid code.

**Comment by erictraut** [comment]
If you make the change I suggest above, then `await super(B, cls).instance()` will be evaluated as type `B`. Give it a try.

**Comment by poul1x** [comment]
Wow! It works
But I still do not understand why it's working.

**Comment by jakebailey** [comment]
Perhaps an overkill idea, but is it possible in the unannotated case to infer `self` and `cls` as `_T` and `Type[_T]` where `_T` is generated to be a TypeVar bound to the current class? If it worked that way, the original code would have type checked without modification.

**Comment by erictraut** [comment]
It would be possible to add special-case logic to handle this, but this particular pattern is rare (and I'll claim, ill-advised), so I don't feel compelled to add and maintain the extra logic.

**Comment by poul1x** [comment]
Maybe I should switch to something like that?
https://github.com/kchmck/pyasyncinit

**Comment by poul1x** [comment]
I don't know how to make python async constructor inheritance. 
And pyasyncinit is solution, but Pyright does not like it too.

**Comment by poul1x** [comment]
I will use this without any hacks:

```python
class A:

    def __init__(self, settings):
        pass

    async def init(self):
        pass

class B(A):

    def __init__(self, settings):
        super().__init__(settings)

    async def init(self):
        await super().init()
```
