### ISSUE TITLE
Add a CLI flag to ignore partially-unknown types imported from external packages

### ISSUE THREAD

**Issue by vemel** [microsoft/pyright#1563]
**Is your feature request related to a problem? Please describe.**

By reading a source code, I found that types verification can be limited only to current package by adding `!` to its name

```bash
pyright --verifytypes my_lib!
```

This is very helpful, but not intuitive at all.

**Describe the solution you'd like**
Add a CLI flag `--ignore-external`: `pyright --verifytypes my_lib --ignore-external`

**Comment by erictraut** [comment]
There is already a somewhat-hidden feature that does this. To invoke it, specify the name of the package you want to analyze and append a "!" character to it. I haven't yet decided whether I want to officially expose this or document it. Please play with the semi-hidden feature and let me know if that solves your needs.

**Comment by erictraut** [comment]
Since you are not the first person to ask for this feature, I think it's reasonable to expose it officially. 

Thanks for submitting the suggestion and the PR. I'm going to modify the command-line option's name because I've been trying to standardize on non-hyphenated option names, but otherwise it looks good.

**Comment by erictraut** [comment]
Please take a look at the tweaks I made in [this change](https://github.com/microsoft/pyright/commit/a192486099503353413e02078c41d0d82bd696e8) and let me know if you see any issues. Thanks again for the contribution.

**Comment by vemel** [comment]
Thank you for a quick review! Yes, everything looks good. As I see, you have removed `package_name!` functionality as well.

**Comment by erictraut** [comment]
This is included in Pyright 1.1.118, which I just published.
