### ISSUE TITLE
Conditionals that confirm a value is neither True nor False don't narrow out the bool type

### ISSUE THREAD

**Issue by gjoseph92** [microsoft/pyright#1573]
**Describe the bug**
When you have a `Union`-typed value, which could be a bool or something else, the type checker still thinks the value could be a bool within an if-statement that confirms the value is neither True nor False (so, not a bool).

**To Reproduce**
```python
from typing import List, Union


def test(bool_or_list: Union[List[str], bool]):
    if bool_or_list is not True and bool_or_list is not False:
        return [x for x in bool_or_list]
        #                  ~~~~~~~~~~~~
        # "bool" is not iterable
        # "__iter__" method not defined
    
    if bool_or_list is True:
        return
    elif bool_or_list is not False:
        return [x for x in bool_or_list]
        #                  ~~~~~~~~~~~~
        # "bool" is not iterable
        # "__iter__" method not defined

    if bool_or_list:
        if bool_or_list is True:
            return
        else:
            return [x for x in bool_or_list]
            #                  ~~~~~~~~~~~~
            # "bool" is not iterable
            # "__iter__" method not defined
```

**Expected behavior**
In all 3 cases, infer that `bool_or_list` is not a bool, and therefore is a `List[str]`, and don't mark it as an error.

**VS Code extension or command-line**
VS Code extension, v1.1.117

**Comment by erictraut** [comment]
These are the type guards that pyright supports: https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#type-guards.

Each new type guard pattern requires additional logic and potentially slows down analysis, so I add them sparingly. I think this case is relatively unusual. I've confirmed that mypy also doesn't narrow in this case.

I'm going to close this, but if it eventually gets enough upvotes, I'll consider reopening.

**Comment by erictraut** [comment]
Pyright (and mypy) supports the `isinstance` call for narrowing, so the following would be a straightforward solution:

```python
    if not isinstance(bool_or_list, bool):
        return [x for x in bool_or_list]
```
