### ISSUE TITLE
Support for callback protocols

### ISSUE THREAD

**Issue by jzvelc** [microsoft/pyright#158]
It seems that [callback protocols](https://www.python.org/dev/peps/pep-0544/#callback-protocols) are currently not supported. It would be great to have this.

**Comment by erictraut** [comment]
Thanks for the request. You're correct — pyright doesn't currently support callback protocols. I didn't know they existed until you mentioned them. :)

**Comment by erictraut** [comment]
Thanks again for the suggestion. I've implemented support for callback protocols, and it will be in the next released version of pyright.

**Comment by erictraut** [comment]
This is now implemented in 1.0.42, which I just published.
