### ISSUE TITLE
Annotations with Generics not passing through a generic annotated function

### ISSUE THREAD

**Issue by deregtd** [microsoft/pyright#159]
**Expected behavior**
In the example below, "new_service" should have its type deduced to be "Service".  Instead it is "Any".

**Screenshots or Code**
```python
_FuncT = TypeVar('_FuncT', bound=Callable[..., Any])
def backoff() -> Callable[[_FuncT], _FuncT]:
  ...

_T = TypeVar('_T')
@backoff()
def until_deadline(self, func: Callable[[], _T]) -> _T:
  ...

def create(self) -> Service:
  ...

new_service = retry.until_deadline(create)
```

**VS Code extension or command-line**
VSCode extension - 1.0.41

**Comment by erictraut** [comment]
This is now implemented in 1.0.42, which I just published.
