### ISSUE TITLE
Pyright VS Code plugin should recognize pipenv

### ISSUE THREAD

**Issue by PetterS** [Microsoft/pyright#16]
When installing the Pyright VS Code plugin with a project that uses Pipenv, lots of imports are marked as missing.

**Comment by erictraut** [comment]
Pipenv doesn't appear to be part of the stdlib, so it won't be part of the typeshed files that are built in to pyright. That means you will need to point pyright at type stubs or the installed module. Can you provide more details about how you've configured pyright?

**Comment by PetterS** [comment]
I just installed it in VS Code. I had a project using Django and after installation, pyright underlined "import django" with a squiggle saying that "django" could not be found.

The regular Python plugin for VS Code correctly finds Django in the virtualenv and offers completions, go to definition etc.

**Comment by lbenka** [comment]
Can you provide some example configuration to this @erictraut ? There isnt any in VScode extension tab for pyright. Hello world app based on pipenv would help a lot.

Thanks

**Comment by erictraut** [comment]
There's a sample config file on [this page](https://github.com/Microsoft/pyright/blob/master/docs/configuration.md).

**Comment by erictraut** [comment]
Pyright 1.0.4, which I just published, now recognizes the VS Code configuration settings for "python.pythonpath", "python.venvPath" and "python.analysis.typeshedPaths". If you've already configured these, it will pick them up. They override the settings in your pyrightconfig.json file.
