### ISSUE TITLE
os.path.join() is always marked as an error when passing it expressions

### ISSUE THREAD

**Issue by thpica** [microsoft/pyright#161]
**Describe the bug**
`os.path.join()` is always marked as an error when passing it expressions (string declaration).

**To Reproduce**
Use `os.path.join()` with an expression.

**Expected behavior**
Should not be marked as an error.

**Screenshots or Code**
```python
import os.path
path: str = os.path.join('foo', 'bar') # No overloads for 'os.path.join(<Expression>, <Expression>, run_id)' match parameters  Argument types: (Literal['..'], Literal['..'], Optional[str])
```

**Comment by erictraut** [comment]
I'm not able to repro the problem. Here are a few additional questions for you.
1. Are you using the builtin type stub files that are included with pyright, or are you overriding them with custom type stub files using the typeshedPath configuration option?
2. Have you configured the pythonVersion configuration option, or are you letting pyright default to the latest stable version of python (3.7)?
3. If you paste the code above into a file on its own, does pyright still report the error?

The reason I asked question 3 is that the output you've pasted here doesn't match the sample code. The error seems to indicate that you're attempting to pass three arguments to os.path.join. The first two arguments are string literals ('..'), and the third argument is either a string or None. The path.pyi type stub library indicates that os.path.join() accepts only two arguments.

**Comment by erictraut** [comment]
Closing the issue since there has been no response, and I don't think it's a pyright bug. If you have additional information, please feel free to reply below or re-open the issue.
