### ISSUE TITLE
Should I version control the "typings" directory or should I git-ignore it?

### ISSUE THREAD

**Issue by danielfalbo** [microsoft/pyright#1610]
I mean the [type-stubs](https://github.com/microsoft/pyright/blob/master/docs/type-stubs.md) dir

**Comment by danielfalbo** [comment]
Sorry, this is not an issue, I'm going to ask this in the Discussions section

**Comment by bgrounds** [comment]
> Sorry, this is not an issue, I'm going to ask this in the Discussions section

Thanks for this comment. I have the same question, but didn't realize the Discussions section existed :)
