### ISSUE TITLE
Follow up on https://github.com/microsoft/pyright/issues/428

### ISSUE THREAD

**Issue by Indiana3714** [microsoft/pyright#1616]
This is the code from "https://github.com/microsoft/pyright/issues/428"

`from typing import overload, Union

@overload
def myfunc(arg: bool = True) -> str:
    ...

@overload
def myfunc(arg: bool = False) -> int:
    ...

def myfunc(arg: bool) -> Union[int, str]:
    if arg:
        return "something"
    else:
        return 0

output = myfunc(False)
print(type(output))`

extended just to show the type hint of the return outputs. Is there a way for pyright to correctly infer that output should be an int if myfunc(False) and that output should be a str if myfunc(True) ? Currently it will always state that output: str regardless if True/False was passed in

![2021-03-11_11h22_20](https://user-images.githubusercontent.com/41246263/110716901-2daf5700-825c-11eb-9644-3e9f15f0e070.png)

**Comment by erictraut** [comment]
Yes, this can be done with a `Literal` type in the overloads, as follows:

```python
from typing import Literal, overload, Union

@overload
def myfunc(arg: Literal[True]) -> str:
    ...

@overload
def myfunc(arg: Literal[False]) -> int:
    ...

def myfunc(arg: bool) -> Union[int, str]:
    if arg:
        return "something"
    else:
        return 0

output = myfunc(False)
print(type(output))
```
