### ISSUE TITLE
Generic function with arg Type[T] not being recognized as callable.

### ISSUE THREAD

**Issue by poiati** [microsoft/pyright#162]
**Describe the bug**
Generic function with arg Type[T] not being recognized as callable.

**To Reproduce**

![image](https://user-images.githubusercontent.com/21452/60684985-0b561b00-9e77-11e9-8384-3d148ef4cf82.png)

**Expected behavior**
There should be no type error.

**Screenshots or Code**

![image](https://user-images.githubusercontent.com/21452/60684985-0b561b00-9e77-11e9-8384-3d148ef4cf82.png)

**VS Code extension or command-line**

- vscode 1.36.0
- pyright 1.0.42

**Additional context**

**Comment by erictraut** [comment]
Thanks for the bug report. This is indeed a bug. I've found the problem, and the fix will be in the next published version of pyright.

**Comment by erictraut** [comment]
This is now fixed in version 1.0.43, which I just published.
