### ISSUE TITLE
Missing properties on instance of decorated class

### ISSUE THREAD

**Issue by mr-bjerre** [microsoft/pyright#1640]
**Describe the bug**

I've made a decorator that decorates classes and returns an extended class. The properties on the decorated class are no longer visible for code-completion

**To Reproduce**

```python
def decorate_cls(*args):
    def wrapper(cls):
        class ExtendedClass(cls):
            def __init__(self, name: str, age: int) -> None:
                super().__init__(name=name)
                self.age = age

        return ExtendedClass

    return wrapper


@decorate_cls()
class SomeClass:
    def __init__(self, name: str) -> None:
        self.name = name


obj = SomeClass(name="John", age=12)
```

**Expected behavior**

`obj` should have both `age` and `name` as properties but only `age` are listed for code-completion.

**Screenshots or Code**

![Screenshot from 2021-03-17 17-17-17](https://user-images.githubusercontent.com/16841792/111501478-51373d80-8745-11eb-80df-368fc08b12f3.png)

**VS Code extension or command-line**

I'm using pylance `v2021.3.1`

**Comment by erictraut** [comment]
Depending on your requirements, a mix-in pattern might work. Or a container pattern where the wrapper class is a container for an instance of the "wrapped" class.
