### ISSUE TITLE
Missing imports

### ISSUE THREAD

**Issue by rajnathsah** [microsoft/pyright#1646]
pylance shows missing import for lot of new library. One such is asyncssh.

**Comment by erictraut** [comment]
This is almost definitely a problem with the way you've configured pyright.

I'll need more information to help you diagnose the problem. The bug report template asks for a bunch of details that you haven't provided here.

Can you provide a self-contained code sample?

What settings are you using? Are you using a pyrightconfig.json file, and if so, what's in it?

Please refer to the pyright documentation for more details about how to configure it.

**Comment by rajnathsah** [comment]
Thanks for pointing out, it was more to do with my settings.
