### ISSUE TITLE
Type "int" cannot be assigned to type "int | str" when used as generic type

### ISSUE THREAD

**Issue by NateScarlet** [microsoft/pyright#1648]
**Describe the bug**
strict typed value can not be assigned to union type

**To Reproduce**
See code below

**Expected behavior**
no error

**Screenshots or Code**
```python
import typing

a: typing.List[typing.Union[int, str]] = []
b: typing.List[int] = []

a = b
```
![image](https://user-images.githubusercontent.com/21083014/111586301-974ed880-87fb-11eb-919e-16dbac5f0e79.png)

**VS Code extension or command-line**
Pylance: 2021.3.2

**Comment by erictraut** [comment]
This is correct behavior. Refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#generic-types) for details.

Lists are mutable containers, and their type parameters are invariant, so you can't assign a `List[int]` to a `List[int | str]`.
