### ISSUE TITLE
Support type comment for `for` and `with` statement

### ISSUE THREAD

**Issue by NateScarlet** [microsoft/pyright#1650]
**Describe the bug**
type comment for `for` and `with` statement not work

<https://www.python.org/dev/peps/pep-0484/#type-comments>
> Type comments should be put on the last line of the statement that contains the variable definition. They can also be placed on with statements and for statements, right after the colon.

**To Reproduce**
See code below

**Expected behavior**
Type comment take effect

**Screenshots or Code**
```python
from some_module import frobnicate, points # type: ignore

with frobnicate() as foo:  # type: int
    # Here foo is an int
    ...

for x, y in points:  # type: float, float
    # Here x and y are floats
    ...

```
![image](https://user-images.githubusercontent.com/21083014/111607098-e6ecce80-8812-11eb-8967-4e20017531d6.png)
![image](https://user-images.githubusercontent.com/21083014/111607073-e05e5700-8812-11eb-8ca9-6d9010336db8.png)

**VS Code extension or command-line**
Pylance: 2021.3.2

**Comment by erictraut** [comment]
We have no plans to add additional support for type comments. They are obsolete and are supported in a minimal manner for backward compatibility with older versions of Python. You should use new-style type annotations instead.

**Comment by NateScarlet** [comment]
Thanks for the clarification.

This is a nice thing to have for write code for older python, but i can use type comment on self assign instead:

```
from some_module import frobnicate, points # type: ignore

with frobnicate() as foo:  
    foo = foo # type: int
    # Here foo is an int
    ...

for x, y in points:
    x = x # type: float
    y = y # type: float
    # Here x and y are floats
    ...
```
