### ISSUE TITLE
Document the six mystery type arguments to pandas.Series

### ISSUE THREAD

**Issue by roblevy** [microsoft/pyright#1665]
**Is your feature request related to a problem? Please describe.**

A [Pandas Series object](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) is a representation of a vector with a constant data type, and an index, whose elements also have a constant data type

Thus, you might try to annotate a Series which has integer values, each with a `datetime` index value as:

```python
pd.Series[int, datetime]
```

But when attempting to assign types to a series Pyright asks for six attributes. I couldn't find any documentation anywhere about what these six attributes represent.

I eventually found a recipe which works, but it's totally mysterious and opaque to me:

```python
DateTimeFloatSeries = pd.Series[List[int], List[datetime], None, None, bool, bool]
```

**Describe the solution you'd like**

Some new documentation somewhere which describes how to successfully annotate the data type and index data type of a Pandas Series.

**Additional context**

See [this SO question](https://stackoverflow.com/q/66710542/2071807) for a complete description of my research into this topic.

**Comment by erictraut** [comment]
Thanks for the suggestion, but pyright doesn't ship with any pandas type stubs. I'm not sure which ones you're using. Pyright is simply interpreting the type information provided to it. There are several sets of pandas stubs in existence. One set ships with pylance. Is that what you're using? The pandas team is also working on adding type information directly to the pandas package.

Documentation for pandas and its types should be the responsibility of the provider of the type information. This is outside the scope of pyright, which is one of several Python type checkers that consume type information.
