### ISSUE TITLE
Any possibility to add more type checking?

### ISSUE THREAD

**Issue by SurushCyrus** [microsoft/pyright#169]
# Python 3.7.4
from typing import List, Union

# As I expected, did not provide any error
stuff: List[Union[int, str, bool]] = ["Surush", "Mary", "Table",
                                      True, False, "Sam",
                                      99, 20, "TV", "Radio"]
print(stuff)

# I like to see error for not providing bool in Union
stuff: List[Union[int, str]] = ["Surush", "Mary", "Table",
                                True, False, "Sam",
                                99, 20, "TV", "Radio"]
print(stuff)

# I like to see error for not providing Union, str, and bool
stuff: List[int] = ["Surush", "Mary", "Table",
                    True, False, "Sam",
                    99, 20, "TV", "Radio"]
print(stuff)

**Comment by erictraut** [comment]
Pyright supports various configuration settings that control the strictness level of type checking. It defaults to less strictness. For the above case, you can enable "strictListInference" to flag this error.

You can also enable "strict" mode, which enables all strict checks. This can be done on a per-file basis (by adding the comment " # pyright: strict" to the top of the file) or for entire subdirectories (by adding an array of directories to a "strict" section in the configuration file).

**Comment by erictraut** [comment]
For a full list of available configuration options, refer to [this documentation page](https://github.com/microsoft/pyright/blob/master/docs/configuration.md).

**Comment by SurushCyrus** [comment]
Fantastic, thank you for the education Eric:). Sorry for the spam. Did as you described and looking great now:)
