### ISSUE TITLE
Feature request: use function return type to infer type of empty list or dictionary

### ISSUE THREAD

**Issue by ipkiss42** [microsoft/pyright#1692]
Since things worked well in #1670, I'm trying my luck again :)

**Is your feature request related to a problem? Please describe.**

It is fairly common to have a function that creates an empty list, populates it with some logic and returns it. Unfortunately, Pyright requires explicit typing of the initial empty list. For example, in the following code Pyright considers that the type of `alist` is `List[Unknown]`.

```python
from typing import List

def foo() -> List[int]:
    alist = []
    for n in (1, 2):
        alist.append(n)
    return alist
```

**Describe the solution you'd like**
I would like Pyright to infer the `List[int]` type from the function return type. It could be seen as the reverse of the [return type inference](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#return-type-inference).

Rationale: a function signature is a strong statement of intent regarding the types. When a list/dict of unknown type is returned, it would be nice not to have to declare the same type explicitly in the function body.

**Comment by erictraut** [comment]
Sorry, this isn't feasible. That's not how type inference works.

This is possible:
```python
def foo() -> list[int]:
    return []
```

But that's because the literal expression `[]` can be evaluated within the context of an expected return type.

**Comment by ipkiss42** [comment]
OK, too bad.

For my education, could you explain what is the fundamental problem that prevents it, please?

**Comment by erictraut** [comment]
I don't know how to answer that question succinctly unless you already have some understanding of how type evaluation, type narrowing and type inference works in type checkers like pyright.

I've documented this in some detail [here](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md) and [here](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md). Please start there and let me know if you have any follow-up questions.

**Comment by ipkiss42** [comment]
These documents describe what Pyright can do, but not what cannot be done.

The first document [says](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#list-expressions): "If the list is empty (`[]`), assume `List[Unknown]` (unless a known list type is assigned to the same variable along another code path).". So the heuristic I am proposing boils down to treating "return the list" in the same way as a regular assignment.

Another way to look at it is to consider that an explicit function return type can be used as expected type for [bidirectional type inference](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#bidirectional-type-inference-expected-types). This is already the case in your snippet above, but I am proposing to back-propagate this when a variable is returned:

```python
def foo() -> list[int]:
    alist = []
    return alist
```

 The scope of this heuristic could be intentionally very limited:
* Only when the function has an explicit return type of `List[Foo]` (and similar for dicts).
* Only when the return statement contains a plain variable (i.e. only support `return x`, not any other expression such as `return x + y`).
* Only when no known type assignment is done for this variable (i.e. only when the returned variable is `List[Unknown]`).

In such a case, Pyright would infer the type of the variable to be the return type.

So my question is: why couldn't the above be done? Is my suggestion fundamentally broken (if so, why)? Would it go against some Pyright design principle? Would it be too difficult to implement? Something else?

**Comment by erictraut** [comment]
I suppose it would be theoretically possible to add special-case handling for the _exact_ conditions that you mention, but that is extremely specific and not generally very useful because those circumstances don't appear often enough in real code. 

Special cases are problematic in any piece of code as complicated as a type checker. They make the code hard to maintain and evolve. Furthermore, they're hard to document and explain to users because they introduce inconsistencies in behavior (Why doesn't this work when there's a second return statement? Why doesn't this work when there's a second assignment? Why doesn't this work when the return type is `Iterable[int]`?) It's best to stick with consistent, documented rules.

Note that mypy also doesn't do what you're suggesting. Nor does the TypeScript compiler. In all cases, you would be expected to provide a type annotation for `alist` in your code sample above.

**Comment by ipkiss42** [comment]
Thanks for the follow-up.

> Note that mypy also doesn't do what you're suggesting.

It's true for that mypy doesn't support this degenerated case:

```python
def foo() -> list[int]:
    alist = []
    return alist
```

However, mypy does support more realistic (and possibly more common?) cases such as the following:

```python
def foo() -> list[int]:
    alist = []
    for var in some_iterable:
        # completed logic here
        alist.append(some_value)
    return alist
```

AFAIK it does not do it in the way I suggested but by leveraging `append()`. But no matter how it is implemented, I find it convenient not to have to repeat the function return type in the function body.

Having said that, I also understand the desire to avoid too many special cases, and I do not have data about how frequent this pattern is (the code  would have to be complex enough that a list/dict comprehension cannot be used instead). So your arguments make sense to me.

Thanks!
