### ISSUE TITLE
Better docs for Type Stubs, how they work, default behavior, etc

### ISSUE THREAD

**Issue by unformatt** [Microsoft/pyright#17]
I'm using pyright from command line. By default, pyright does not recognize any built-ins. I might be configuring it wrong but the docs don't explain. README mentions Typeshed and the configuration docs say "Pyright ships with an internal copy of some typeshed type stubs". Makes me believe that built-ins should work without extra configuration.

Are they enabled by default? I get errors like:
```
'len' is not defined (27, 8)
'dir' is not defined (58, 23)
'getattr' is not defined (59, 13)
```

my config is:

```
{
    "include": ["/Users/xxx/projects/xxx/django"],
    "venvPath": "/Users/xxx/.envs/",
    "venv": "xxx",
    "pythonVersion": "2.7"
}
```

**Comment by erictraut** [comment]
One issue is that you have the python version set to 2.7, and pyright supports only 3.0 and newer, so you're going to run into a bunch of issues there. I should add code that emits a warning or error for unsupported versions.

**Comment by unformatt** [comment]
Ah, yea that might be a bit of a problem! :)
