### ISSUE TITLE
Annotate Pytest Fixtures

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/pyright#1702]
In this example:

```python
import azure.functions as func
import users
import food
import json
import pytest


@pytest.fixture
def mock_request():
    return func.HttpRequest(
        method="GET", url="users/2", body=b"", route_params={"user_id": "2"}
    )


def test_users(mock_request):
    req = mock_request
    result = users.main(req)
    assert result.status_code == 200
    assert json.loads(result.get_body().decode())["user_id"] == "2"

```

Pyright will annotate the `mock_request` parameter to the `test_users()` function as unknown:

<img width="1032" alt="Screen Shot 2021-03-31 at 9 47 20 am" src="https://user-images.githubusercontent.com/1532417/113066334-1a156180-9206-11eb-9e11-ca88f1f04e1d.png">

It would be great for Pyright to annotate Pytest fixtures as the type of the fixture result, when:

1. The fixture is defined in the same file
2. The fixture is defined in a standard extension, like the [Pytest builtin fixtures](https://docs.pytest.org/en/stable/builtin.html)
3. The fixture is defined in a `conftest.py` file within the test project

**Comment by erictraut** [comment]
The input parameter `mock_request` to function `test_users` has no type annotation, so its type is Unknown. Pytest is doing some behind-the-scenes magic at runtime when it searches for functions with names that start with `test_` and then provide arguments based on parameter names. A static type checker like pyright has no knowledge of this behind-the-scenes magic.

Pyright doesn't include any knowledge of third-party libraries beyond what is provided to it in type stubs or type annotations, and we don't have any plans to add hard-coded logic that is library-specific.

**Comment by debonte** [comment]
For what it's worth, Pylance supports the behavior that @tonybaloney originally requested. So if you're using VS Code, consider switching to Pylance, which is based on Pyright.

![image](https://github.com/microsoft/pyright/assets/12820898/e1525a91-9866-4f3a-a3b9-e19fdac14b36)

Pylance doesn't currently support the behavior that @bersbersbers mentioned, but we could consider adding it.

cc: @rchiodo
