### ISSUE TITLE
Overriding __init_subclass__ makes the overriding class definition type check against its own override

### ISSUE THREAD

**Issue by Tomaz-Vieira** [microsoft/pyright#1705]
**Describe the bug**
Overriding `__init_subclass__` seems to cause the overriding class definition to check its arguments against its own version of `__init_subclass__` as opposed to checking against the arguments of its parents.

**To Reproduce**
Run the following code through mypy:

```python
# pyright: strict

class A:
    def __init_subclass__(cls, param_a: int):
        super().__init_subclass__()
        print(f"Registering class {cls} with param {param_a}")

# pyright error: No parameter named 'param_a'. Argument missing for parameter 'param_b'
class B(A, param_a=123): 
    def __init_subclass__(cls, param_b: int):
        super().__init_subclass__(param_a=param_b)
```

**Expected behavior**
No errors on the definition of class B. mypy also produces no errors there

**VS Code extension or command-line**
Pyright extension version 1.1.123
Commnad-line tool version 1.1.126

**Comment by erictraut** [comment]
This is included in pyright 1.1.127, which I just published. It will also be included in the next release of pylance.
