### ISSUE TITLE
Minimum Node Version Check

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#1709]
**Describe the bug**
Installing pyright with a version of node that's too old fails for simple commands (pyright --help). It'd help to know/set minimum version.

**To Reproduce**
```
nvm install 8.5
nvm use 8.5
npm install -g pyright@1.1.127
pyright --help
```
**Expected behavior**
Some minimum bound in the package.json to prevent errors from trying to run pyright.

**Comment by jakebailey** [comment]
We have the field set here: https://github.com/microsoft/pyright/blob/master/packages/pyright/package.json#L12

Perhaps v8 is old enough that it doesn't understand how to handle `engines`?

**Comment by hmc-cs-mdrissi** [comment]
Trying to install it with v11 gives me no warning/error message either even though package.json says 12+. Do you have to enable something for engines to be respected?

**Comment by hmc-cs-mdrissi** [comment]
Yeah doing some searching looks like on the user end I need to enable strict engine first. Running `npm config set engine-strict true `makes the error actually appear. I'll close this I guess and just think of it as node weirdness.

**Comment by hmc-cs-mdrissi** [comment]
Checking npm config docs, the default value is false, https://docs.npmjs.com/cli/v7/using-npm/config#engine-strict. I installed nvm earlier today as I ended up needing to debug npm version weirdness.

**Comment by jakebailey** [comment]
Yuck. Guess setting engines wasn't as helpful as intended. It could be worth adding a log line or something to our entrypoints, but then again, the oldest LTS version of node is v10 and it'll be out of its support window in less than a month.
