### ISSUE TITLE
Infer dict variable as TypedDict

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#1727]
```python
from typing_extensions import TypedDict

TagTypeDef = TypedDict("TagTypeDef", {"Key": str, "Value": str})

def tag(t: TagTypeDef) -> TagTypeDef:
    return t

t = {"Key": "k1", "Value": "v1"}

tag(t)
```

Errors with:
```
test.py:10:5 - error: Argument of type "dict[str, str]" cannot be assigned to parameter "t" of type "TagTypeDef" in function "tag"
```

**Describe the solution you'd like**

Since t conforms to `TagTypeDef`, infer t as a `TagTypeDef` and don't error.

**Additional context**

The current workaround is to provide a type annotation:

```
t: TagTypeDef = {"Key": "k1", "Value": "v1"}
```
However, this requires importing a third-party stub which is then needed at runtime.

Or, avoid an intermediate variable and supply the dictionary literal as the function argument:

```
t({"Key": "k1", "Value": "v1"})
```

pyright 1.1.128

**Comment by tekumara** [comment]
mypy has the same behaviour and it looks like both conform to [PEP 589](https://www.python.org/dev/peps/pep-0589/#using-typeddict-types):

> An explicit Movie type annotation is generally needed, as otherwise an ordinary dictionary type could be assumed by a type checker, for backwards compatibility. When a type checker can infer that a constructed dictionary object should be a TypedDict, an explicit annotation can be omitted. A typical example is a dictionary object as a function argument. 

It's just a little surprising that type inference differs when the same value is presented as a variable instead of a function argument.

**Comment by tekumara** [comment]
Looks like this has already been discussing in the context of return values in https://github.com/microsoft/pyright/issues/715

**Comment by tekumara** [comment]
Looks like this has already been discussed in the context of return values in https://github.com/microsoft/pyright/issues/715

**Comment by erictraut** [comment]
This is the correct behavior. The inferred type of t is `Dict[str, str]`. A type checker cannot "guess" that the type is going to be used in some other context where you want it to conform to a TypedDict of a particular shape.
