### ISSUE TITLE
Disallow comparison between types with no obvious overlap

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/pyright#1744]
**Is your feature request related to a problem? Please describe.**

Let's say you're writing some code to process an HTTP request. You write a line to parse out the status code:

```py
version, status, explanation = status_line.split(" ", 2)
if status == 200:
  print("It worked!")
```

Oops! `status` is a `str`. This condition will never be true.

**Describe the solution you'd like**

In TypeScript we started with a rule: in order to compare two types through equality, they have to be assignable in one direction.

In a world with singleton/literal types, you really end up needing a new type relationship kind, which we call *comparability*. Comparability is a bit more lax to try to pick out types that could *plausibly* have overlap.

For the purposes of this issue, the comparability and assignment compatibility rules *primarily* differ only in that

 * a union type is comparable to a target type if any of its constituents, rather than all of its constituents, are comparable to that target type,
 * an object type with some optional property is comparable to an object type containing a property of the same name if it has a compatible type, regardless of whether that property is optional,
 * literal types and enum member types are comparable both to and from their base primitive types *(maybe not relevant here)*
 * the Undefined type is comparable to and from the Void type
 * when relating any two signatures, each signature is always instantiated using type Any for all type arguments.

We used comparability to check for mistakes in

* Invalid type assertions (i.e. the `typing.cast` function in Python)
* Equality (e.g. `===`, `!==`, `==`, `!=`, and `switch`/`case`)

We also used comparability to better-model type narrowing as well.

**Additional context**

I tried documenting this in prose a while back over at https://github.com/microsoft/TypeScript/pull/20686.

**Comment by erictraut** [comment]
I like the idea in theory, but I don't know if it's possible in practice given that Python allows full overloads of the `__eq__` and `__ne__` operators. Pyright already enforces the types of these magic methods, but for most types, the second operand to the method is typed as `object`, which means that any object is allowed. So it's perfectly legitimate to say `if status == 200`, at least from a type perspective.

I wonder whether we could come up with some heuristics that would catch legitimate bugs but not generate a bunch of false positives. Maybe this is something we could disable in normal type checking mode but enable in strict mode, where users are more willing to change their code to avoid false positives?

I'll play around with some heuristics and try them on some real-world code bases to see what it looks like.

**Comment by DanielRosenwasser** [comment]
Yup, I figured that might be an issue - it's similar in most languages, and from a strict correctness perspective, there is nothing *wrong* with permitting it, but it does help catch a wide class of bugs.

I also think a heuristic for non-overridden methods, maybe even only enabling this in stricter checking contexts, might be the right call.

**Comment by erictraut** [comment]
I implemented this suggestion as a new diagnostic rule "reportUnnecessaryComparison". It uses some heuristics similar to the ones you've outlined above. It also includes the following special cases:
1. It is suppressed entirely if it's within an `assert` statement
2. It is suppressed if the LHS is an instance of a class that implements a custom `__eq__` override.
3. It is suppressed if the LHS is a class whose metaclass implements a custom `__eq__` override.

I ran this over my team's code base (250K+ lines of Python) which uses Pyright's strict type checking mode. The new diagnostic rule identified three real bugs in the code plus two bugs in our type stubs!

**Comment by erictraut** [comment]
Here's the commit if you're interested in the details: https://github.com/microsoft/pyright/commit/27fb622a5e87597e03d1e204eae1ef1382ab5193

**Comment by DanielRosenwasser** [comment]
>     1. It is suppressed entirely if it's within an `assert` statement

Heh, this is the first place I actually tried it in. Did you find it was too noisy there?

Could it be that `!=` deserves an exemption but not `==` in `assert`?

> I ran this over my team's code base (250K+ lines of production Python code) which uses Pyright's strict type checking mode. The new diagnostic check identified three real bugs in the code plus two bugs in our type stubs!

That's pretty cool! I'm glad this suggestion actually caught a few issues!

**Comment by erictraut** [comment]
Yeah, it was too noisy (too many false positives) for asserts. Pyright already disables similar checks within assert statements for a similar reason, so I wasn't surprised to see this.

**Comment by erictraut** [comment]
This is included in Pyright 1.1.130, which I just published. It will also be part of the next release of Pylance.

**Comment by Popkornium18** [comment]
> 2\. It is suppressed if the LHS is an instance of a class that implements a custom `__eq__` override.

I'm confused. Shouldn't this be fine, then?

```
from __future__ import annotations

from typing import Union


class StringLike:
    def __init__(self, value: str):
        self.value = value

    def __eq__(self, other: Union[object, str, StringLike]):
        if isinstance(other, str):
            return self.value == other
        elif isinstance(other, StringLike):
            return self.value == other.value
        return NotImplemented


banana = StringLike("banana")
fruits: list[str] = ["apple", "banana", "orange"]
result = banana in fruits # triggers reportUnnecessaryContains because of no overlap between "StringLike" and "str"
print(result)  # Output: True
```

**Comment by erictraut** [comment]
@Popkornium18, this issue is discussing the `reportUnnecessaryComparison` check. It applies to `==` and `!=` operators. You're not using a comparison here. Instead, you're using a containment (`in`) operator, and you're triggering a `reportUnnecessaryContains` check.
