### ISSUE TITLE
Non-workspace locations for `pyrightconfig.json`

### ISSUE THREAD

**Issue by zbs** [microsoft/pyright#1756]
I have several VS Code workspaces for copies of the same git repo:

```
- ~/zbs
    - dev
        - my_repo_v1                                                  <-- VS Code workspace #1
            - pyrightconfig.json
        - my_repo_v2                                                  <-- VS Code workspace #2
            - pyrightconfig.json

```
 I would like to use the same `pyrightconfig.json` for each of them without needing to add it to the git repository. Is there any way I can add it above my workspace roots and somehow configure the language server to point to it?
```
Language Server version: 2021.3.2
VS Code: 1.54.3
OS and version: Windows 10 Enterprise 20H2, using Remote SSH onto an RHEL 7 Host
Python version (& distribution if applicable, e.g. Anaconda): Python 2.7 on Miniconda 3
```

**Comment by erictraut** [comment]
No, there's currently no way to do that. Each workspace root requires its own pyrightconfig.json file.

Out of curiosity, if you're using VS Code, why are you not using Pylance? And is there a reason you are not using VS Code settings rather than a pyrightconfig.json file? I realize that there are configuration knobs provided in pyrightconfig.json that have no analog in VS Code settings, but these are more esoteric features.

**Comment by zbs** [comment]
> No, there's currently no way to do that. Each workspace root requires its own pyrightconfig.json file.
> 
> Paths inside of pyrightconfig.json are assumed to be workspace-relative, so sharing a pyrightconfig.json would be problematic.
> 
VS Code allows for non-workspace-relative paths in its settings. For example, you could have a setting that excludes `${workspaceRoot}/**/problematic_subdirectory`. I'm curious if something like that is more doable, maybe within the framework of VS Code settings.

> Out of curiosity, if you're using VS Code, why are you not using Pylance? And is there a reason you are not using VS Code settings rather than a pyrightconfig.json file? I realize that there are configuration knobs provided in pyrightconfig.json that have no analog in VS Code settings, but these are more esoteric features.

I am using VS Code + Pylance. Per [this issue](https://github.com/microsoft/pylance-release/issues/1070), the VS Code settings are insufficient to stop Pylance from attempting to index symlinks to _very_ large subdirectories, which essentially breaks the Python language features.

At any rate, thank you for the quick reply!

**Comment by erictraut** [comment]
The "exclude" config option is something we should probably consider exposing within VS Code settings. I think there's already an open issue on that in the pylance-release issue tracker. Feel free to upvote that issue, or create a new one if you can't find it.

**Comment by jakebailey** [comment]
I'm not sure we have a dedicated issue for that, but https://github.com/microsoft/pylance-release/issues/123 is close. Would be nice to have an issue for "add `python.analysis.exclude`" and such

**Comment by zbs** [comment]
[Done](https://github.com/microsoft/pylance-release/issues/1150). Thanks for keeping this train rolling!
