### ISSUE TITLE
How to set a global configuration instead of per project configuration in vscode?

### ISSUE THREAD

**Issue by mejliu** [microsoft/pyright#176]
Is there a way to do a global configuration in vscode? thanks.

**Comment by erictraut** [comment]
Can you provide more information about what you're trying to do? I'm not sure what you mean by "configuration in code".

The primary configuration mechanism in pyright is the "pyrightconfig.json" file, which is meant to be checked in at the root of your code base. You can override the behaviors defined in the config file on a per-source-file basis using a comment of the form "# pyright: <options>".

**Comment by erictraut** [comment]
Oh, I think I understand now. You want to specify a common configuration for all projects you open within VS Code. No, there's currently no way to do that.

**Comment by mejliu** [comment]
Thanks for your reply. Anyway, it is very good. Thanks.

**Comment by jclosure** [comment]
Is this still the case?  Perhaps falling back to `~/.pyrightconfig.json` and then `/etc/pyrightconfig.json` would allow some attributes to be set at a global-level.   Project-specific `./pyrightconfig.json` could override as set.

**Comment by jakebailey** [comment]
pyright has no config merging capabilities other than those done in the language server. You can control which config is used with `-p` at the CLI, though.

I have been thinking of a VS Code setting that would be akin to the `-p` flag at the pyright CLI, to make it easier to point to another config in the workspace (or somewhere else, but that's less good).

**Comment by erictraut** [comment]
> pyright has no config merging capabilities other than those done in the language server

Pyright 1.1.367 adds support for the "extends" setting in a config file. You can use this to inherit settings from other config files — including a global config file if you would like. For details, refer to [this documentation](https://microsoft.github.io/pyright/#/configuration).
