### ISSUE TITLE
Include LICENSE.txt in npm release

### ISSUE THREAD

**Issue by priv-kweihmann** [microsoft/pyright#1770]
Currently (IIRC that was different round about 9-12 months ago) no licensing information is shipped with the npm release (besides the meta data) - please include the LICENSE.txt file from the repo root into the release, so one can be sure about the exact terms and conditions when using this tool

**Comment by erictraut** [comment]
Sure, I don't see any reason not to include it, although I think it's redundant. Pyright is licensed under the standard MIT license, and the package.json metadata indicates as such. Most npm packages that are published under the standard MIT license don't ship a copy of the MIT license text.

**Comment by priv-kweihmann** [comment]
I'd like to disagree on that point - out of the ~1000 npm packages I pull regularly pyright is rather the exception than the norm :-)

So please include it - thx

**Comment by erictraut** [comment]
This is included in pyright 1.1.133, which I just published.
