### ISSUE TITLE
Internal error when using Extended Iterable Unpacking

### ISSUE THREAD

**Issue by filipatfunnel** [microsoft/pyright#178]
**Describe the bug**
- Internal error when using Extended Iterable Unpacking ([PEP 3132](https://www.python.org/dev/peps/pep-3132/))

**To Reproduce**
Use Extended Iterable Unpacking in a Python file in VS Code

**Expected behavior**
Pyright to function normally and not have an Internal error

**Screenshots or Code**
Example code that will cause the error:
```python
first, *rest = (1, 2, 3)
```

Screenshot showing pyright working properly ✅:
![Screenshot 2019-07-24 at 17 16 02](https://user-images.githubusercontent.com/40169918/61806125-71f7a480-ae37-11e9-9a8f-641a63bca634.png)

Screenshot showing pyright getting the Internal error ❌:
![Screenshot 2019-07-24 at 17 16 09](https://user-images.githubusercontent.com/40169918/61806145-7b810c80-ae37-11e9-8f85-9ea5bf8d4607.png)

**VS Code extension or command-line**
VS Code (v. 1.36.1) Pyright extension (v. 1.0.48)

**PS.**
Thanks a lot for all the work done on Pyright, and sorry if this is a user error.

**Comment by erictraut** [comment]
Thanks for the bug report. This is definitely a bug, and it should be straightforward to fix.

**Comment by erictraut** [comment]
This is now fixed in 1.0.49, which I just published

**Comment by filipatfunnel** [comment]
Wow, that was fast - impressive! Can verify that the update resolves the issue on my end as well.
