### ISSUE TITLE
Improve deducing the types when using if statements with "and" 

### ISSUE THREAD

**Issue by predragnikolic** [microsoft/pyright#1788]
**Describe the bug**

Given the following code:

```python
def optionalSum(a: Optional[int] = None, b: Optional[int] = None):
    if a is None and b is None:
        return
    return a + b
           ^^^^^ error: Operator "+" not supported for types "int" and "int | None"
           ^ type: None | int
               ^ type: None | int
```

Pyright reports an error that  `Operator "+" not supported for types "int" and "int | None"`

**To Reproduce**
Copy the following code in the editor and inspect the types of `a` and `b`.
Currently the types for `a` and `b` are `None | int`

**Expected behavior**
But I expect the types for `a` and `b` _in this case_ to be just `int` and no error to be reported,
because we had an early return statement where we checked the presence of both the `a` and `b` variable:

```python
def optionalSum(a: Optional[int] = None, b: Optional[int] = None):
    if a is None and b is None:
        return
    return a + b
           ^ type: int
               ^ type: int
```

**Additional context**
If I rewrite my code like this, Pyright can deduce the type correctly:
```python
def optionalSum(a: Optional[int] = None, b: Optional[int] = None):
    if a is None:
        return
    if b is None:
        return
    return a + b   # no errors now
           ^ type: `int`
               ^ type: `int`  
```

**Comment by jakebailey** [comment]
Are you sure you didn't mean `or`? `a is None and b is None` is only true if both are `None`. If either of them isn't `None`, then the condition isn't true.

Your last example is equivalent to:

```python
if a is None or b is None:
    return
return a + b
```

**Comment by erictraut** [comment]
Yes, I think pyright is doing the right thing here. It's highlighting a bug in your code ;). You should use an `or` operator in the first check rather than an `and`.

**Comment by predragnikolic** [comment]
> Are you sure you didn't mean or?
Yes, I just concluded that I wanted `or` 

Closing this because I was the one who wrongly deduced the types :) 🤦

**Comment by predragnikolic** [comment]
But just one question. Here is the original issue that bothered me:
```python
def run(self, point: Optional[int] = None) -> None:
    region = first_selection(self.view)
    ^^^^^^ type: None | Region
    if point is None and region is None:
                         ^^^^^^^^^^^^^^ 
        return
    hover_point = point or region.begin()
                           ^^^^^^ what should be the expected type here?

a) Region             # I would say a)
b) None | Region

```
