### ISSUE TITLE
pyright finds wrong error for reportInvalidStringEscapeSequence

### ISSUE THREAD

**Issue by SJang1** [microsoft/pyright#1800]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**
Gets an error _Unsupported escape sequence in string literal_ on the code
`print(c, end=' \%\%\%\%\%\% ')`
`for the \%\%\%\%\%\%`

**To Reproduce**
Just enable extension and write the code with _\%_ to show _%_

**Expected behavior**
There is no error, it should not show the error.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/29011440/116328894-fc3b1c80-a804-11eb-808a-5f3e93a18520.png)

**VS Code extension or command-line**
VSCode Extension

**Additional context**

**Comment by erictraut** [comment]
This error is correct. If you read the [Python documentation](https://docs.python.org/3/reference/lexical_analysis.html), it clearly spells out which escape sequences are supported, and "%" is not one of them. Furthermore, it says:

>Unrecognized escape sequences produce a DeprecationWarning. In a future Python version they will be a SyntaxWarning and eventually a SyntaxError.

So if you want to "future proof" your Python code, you should avoid using unrecognized escape sequences. If you don't care about this, you can disable the `reportInvalidStringEscapeSequence` diagnostic rule.

**Comment by SJang1** [comment]
Oh. Okay. Thanks!
