### ISSUE TITLE
bool is not a valid base class in Python

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#1808]
Python apparently does not allow `bool` to be used as a base class when defining a new class. Pyright should probably flag this as an error.

**Comment by JelleZijlstra** [comment]
This should be fixable by adding the `@final` decorator to bool in typeshed, assuming pyright implements that part of PEP 591: https://www.python.org/dev/peps/pep-0591/#id2.

**Comment by erictraut** [comment]
This is included in pyright 1.1.137, which I just published. It will also be included in the next release of pylance.
