### ISSUE TITLE
Wrong error using try and except in a function!

### ISSUE THREAD

**Issue by SurushCyrus** [microsoft/pyright#181]
**Environment**
Python 3.7.4
Pyright 1.0.49

**To Reproduce**
#No issue as I expected for following code:
# pyright: strict
def foo() -> int:
    result: int = 5
    return result

#Getting unexpected error on "int" in "def foo() -> int:" for the following code!:
#Error = Function with declared type of 'int' must return value
# pyright: strict
def foo() -> int:
    try:
        result: int = 5
    except Exception as e:
        print(e)
    else:
        return result

**Comment by erictraut** [comment]
This looks like correct behavior to me. You're declaring that the function foo will return a type "int", but if an exception occurs, it will execute the "print" statement and then fall through to the end of the function and return "None" implicitly. 

There are three ways to fix this:
1. Declare the return type as "Optional[int]"
2. Return an int value from the except clause
3. Re-raise the exception from the except clause after the print statement

**Comment by SurushCyrus** [comment]
Thanks Eric. Yes, great job. I go with option 3.
