### ISSUE TITLE
Remove support for PEP 637

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#1823]
I just noticed that [PEP 637](https://www.python.org/dev/peps/pep-0637/) was rejected by the Python steering committee. That means I should probably back out the related support in pyright.

I'm not sure what this means for [PEP 646](https://www.python.org/dev/peps/pep-0646/), which was relying on PEP 637 for the preferred syntax when using variadic type vars. Any thoughts here, @mrahtz or @gvanrossum?

**Comment by mrahtz** [comment]
Good point. The easiest option might be to revert the support for starred `TypeVarTuple`, and just leave the `Unpack[]` type operator for now?

**Comment by gvanrossum** [comment]
FWIW the SC did not accept or reject 646, but it's definitely not going into 3.10. They asked for a better description of the new syntax, so I am hopeful that that may make it into 3.11 yet.
________________________________

**Comment by erictraut** [comment]
This change is now implemented in pyright 1.1.140, which I just published. It will also be in the next release of pylance. I've retained support for `Unpack[]`.

**Comment by mrahtz** [comment]
Thanks, Eric!
