### ISSUE TITLE
module-level __getattr__

### ISSUE THREAD

**Issue by Akuli** [microsoft/pyright#1831]
**Is your feature request related to a problem? Please describe.**
Can't disable error for module-level `def __getattr__(name: str) -> Any: ...`

**Describe the solution you'd like**
Use separate error code for module-level `__getattr__` so that I don't have to silence all of `reportUnknownMemberType`

**Additional context**
Typeshed has many stubs marked as incomplete using module-level getattr, and they are all exclude-listed in `pyrightconfig.json`

**Comment by jakebailey** [comment]
I'd appreciate this too; we have some incomplete stubs we ship with Pylance (plus the python-type-stub working ground) and want to run pyright to detect other Unknowns in CI without removing the catchall.

**Comment by erictraut** [comment]
I've created a new diagnostic rule "reportIncompleteStub" that allows separates this check from the "reportUnkownMemberType".

This will be included in the next release of pyright.

**Comment by erictraut** [comment]
This is now implemented in pyright 1.1.140, which I just published. It will also be in the next release of pylance.
