### ISSUE TITLE
Have auto-import suggestions for popular abbreviations

### ISSUE THREAD

**Issue by Rizhiy** [microsoft/pyright#1837]
**Is your feature request related to a problem? Please describe.**
Many module names are too long and most people abbreviate them to something short, e.g `numpy` to `np`.
Unfortunately, pyright doesn't suggest auto-import for these abbreviations, would be nice if it did.

**Describe the solution you'd like**
Remember common abbreviations and use them to check for auto-import suggestions.
Might also be a good idea to let user define their own list.

**Additional context**
Common abbreviations that I've seen being used:
```
numpy -> np
pandas -> pd
matplotlib.pyplot -> plt
datetime -> dt
```

**Comment by erictraut** [comment]
This functionality is already provided by pylance, and we don't plan to replicate this functionality in pyright. While pyright does contain some simple language server features, it's primarily a type checker. More advanced language features like source indexing and abbreviation support for auto-completion are beyond the scope of pyright.
