### ISSUE TITLE
Can you clarify what is the difference between Pyright and Pylance?

### ISSUE THREAD

**Issue by ssaavedra** [microsoft/pyright#1859]
**Is your feature request related to a problem? Please describe.**
Currently the difference between pyright and pylance is difficult to understand.

**Describe the solution you'd like**
Currently in the FAQ of the README.md there is a question titled "What is the difference between Pyright and Pylance?".

The answer just says "Pylance leverages Pyright’s functionality with additional features, some of which are not open-sourced.", but it does not say which features are not open-sourced, why is it different and what are the changes that a user would expect from using one or the other.

It would be great to add context on which features are part of Pylance that have no room within Pyright today as well as what the plans are for each of the projects, especially Pyright, given that it allows for contributions from parties outside Microsoft. Maybe in the case of the future of Pylance it would be enough to redirect to the pylance-releases repository.

**Additional context**
Having a clear stance on licensing is, I believe, important, both to understand what contributions can fit within pyright and which of them are expected to be outside the community's broader scope, as well as to understand what to expect from each project.

**Comment by jakebailey** [comment]
The FAQ on the pylance-release repo has a number of sections that intends to flesh this out further: https://github.com/microsoft/pylance-release/blob/main/FAQ.md#what-is-the-relationship-between-pylance-pyright-and-the-python-extension

Perhaps the readme here can just point to that doc.

**Comment by erictraut** [comment]
Here's how to think about it. Pyright contains all of the logic and functionality for type analysis and type checking. That includes all of the functionality you would expect to see in a command-line static type checker like mypy.

Pylance builds upon pyright and adds language service features. These are interactive features that appear within smart editors and IDEs — completion suggestions, auto-import, signature help, hover text, semantic highlighting, "go to definition", refactoring tools, etc.

Pyright does contain some language service features and exposes those in the form of an LSP (language service provider), but that's not its primary focus. You should expect that most new language service enhancements will be implemented in the context of pylance.

If you consider the combined source code for both pyright and pylance, the vast majority of the code (just under 90% by line count) is found within the open-source pyright repo.

If you have bug reports or feature requests related to type checking or diagnostics, feel free to file those in the pyright repo. If you have bug reports or feature requests related to language service features, file those in the pylance-releases repo. If you're unsure, just pick one of the two, and we'll sort it out.

**Comment by jackbravo** [comment]
I had the same question. I think it is worth adding that if you want to use the Pylance VSCode extension for type checking as you would the Pyright extension, then you need to set the `python.analysis.typeCheckingMode` parameter to either "basic", or "standard", or "strict" since the default is "off".

**Comment by debonte** [comment]
@jackbravo, see https://github.com/microsoft/pylance-release/blob/main/USING_WITH_PYRIGHT.md which is our current documentation covering the differences between Pyright and Pylance, how to configure them to behave identically, etc.

**Comment by jackbravo** [comment]
Thanks @debonte, I was exactly looking for that info!
