### ISSUE TITLE
typeshed's VERSIONS file now supports sub-modules

### ISSUE THREAD

**Issue by srittau** [microsoft/pyright#1868]
typeshed's `VERSIONS` file now supports sub-modules. For example:

```
importlib: 2.7-
importlib.resources: 3.7-
```

Currently, pyright just ignores sub-modules and treats them like their parent module. It would be useful if pyright would recognize that a sub-module was not available in a certain Python version, though.

**Comment by erictraut** [comment]
Thanks for the enhancement request. This will be included in the next release of pyright and pylance.

**Comment by srittau** [comment]
Thank you for the amazing speed with which you handle issues and new features. I'm seriously contemplating switching our internal projects to pyright due to this and pyright's supported features.

**Comment by erictraut** [comment]
This is now addressed in pyright 1.1.140, which I just published. It will also be in the next release of pylance.
