### ISSUE TITLE
Implied 'else' check does not handle enum alias

### ISSUE THREAD

**Issue by layday** [microsoft/pyright#1885]
Implied 'else' checking is a fantastic feature in Pyright.  For Enums, this works quite well, except in the case where an alias is used.  An Enum can be created with multiple members having the same value (see https://docs.python.org/3/library/enum.html#duplicating-enum-members-and-values).  It would be useful if Pyright were able to detect this condition to avoid duplication.  Taking the example from the Python docs:

```py
from enum import Enum


class Shape(Enum):
    SQUARE = 2
    DIAMOND = 1
    CIRCLE = 3
    ALIAS_FOR_SQUARE = 2


def get_shape_value(shape: Shape):
    a: int
    if shape is Shape.SQUARE:
        a = shape.value
    elif shape is Shape.DIAMOND:
        a = shape.value
    elif shape is Shape.CIRCLE:
        a = shape.value

    a + 1  # "a" is possibly unbound

    b: int
    if shape is Shape.SQUARE or shape is Shape.ALIAS_FOR_SQUARE:
        b = shape.value
    elif shape is Shape.DIAMOND:
        b = shape.value
    elif shape is Shape.CIRCLE:
        b = shape.value
    
    b + 1  # Ok
```

**Comment by erictraut** [comment]
As a type checker, pyright doesn't have knowledge of the specific _values_ that make up an enumeration. It tracks the elements within an enum and assigns them literal types such as `Shape.SQUARE` and `Shape.DIAMOND`. It doesn't have any knowledge that `Shape.SQUARE` and `Shape.ALIAS_FOR_SQUARE` happen to have the same value at runtime.

The simple and straightforward workaround here is to include the `or` statement as you've done above.

**Comment by layday** [comment]
I was under the impression that enum member value types were literals, e.g. the following

```py
if Shape.SQUARE.value == 0:
    ...
```

is correctly flagged to always be false.  My thought was that Pyright could use this same facility to flag (or not flag) aliases without requiring one to compare their values.  This check could even be extended to enum mixins:

```py
class Shape(int, Enum):
    SQUARE = 2

if Shape.SQUARE == 2:
    ...
```

This is `True` at runtime but Pyright believes that `the types "Literal[Shape.SQUARE]" and "Literal[2]" have no overlap`.

**Comment by erictraut** [comment]
This is theoretically possible to add, but it would be quite complex, and I think this is too much of an edge case to justify the complexity. I'm going to close, but we can revisit in the future if this gets sufficient upvotes.
