### ISSUE TITLE
IntelliSense shows no suggestion or wrong suggestions in some context.

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#190]
**Describe the bug**
IntelliSense shows no suggestion or wrong suggestions in some context, witch include:
1. In `from X import Y` syntax and cursor at position Y. If Y is empty, intelliSense shows wrong suggestions.

2. In `for X in Y` syntax and cursor at position Y. IntelliSense shows no suggestion.

3. In `if/elif X` syntax and cursor at position X. IntelliSense shows no suggestion.

Please see these screenshots:

**problem 1**
![image](https://user-images.githubusercontent.com/3479453/62782315-936db700-baec-11e9-99b9-a0633a8a187b.png)
_case 1. Manually triggered IntelliSense after "import" using shortcut, suggests not only module members, but also may other things (like `ChildProcessError`)_

![image](https://user-images.githubusercontent.com/3479453/62782611-31618180-baed-11e9-97fe-3a5d6638368a.png)
_case 2. Manually triggered IntelliSense after "import" using shortcut, sometime suggests module name instead of members_

![image](https://user-images.githubusercontent.com/3479453/62782808-8d2c0a80-baed-11e9-8f12-c8d74d61094a.png)
_With at least one character specified, the suggestions becomes correct_

**problem 2**

![image](https://user-images.githubusercontent.com/3479453/62786935-31b24a80-baf6-11e9-831a-897dcc475a15.png)
_Manually triggered IntelliSense after "in" using shortcut, shows not suggestions_

![image](https://user-images.githubusercontent.com/3479453/62787075-7c33c700-baf6-11e9-9fc6-a69e0e87d063.png)
_Unlike problem 1, even with leading character provided, there's still no suggestion_

**problem 3**

![image](https://user-images.githubusercontent.com/3479453/62787136-a4232a80-baf6-11e9-9a99-c04808ef5787.png)
_Simillar to problem 2, Manually triggered IntelliSense here, no suggestion_

![image](https://user-images.githubusercontent.com/3479453/62787169-bb621800-baf6-11e9-9933-0dd21fe55d3e.png)
_If leading character provided, suggestion will show_

**Expected behavior**
case 1: should suggest variable exported from module X and nothing more.

case 2: should suggest available (maybe iterable only) variables from context

case 3: should suggest available variables from context.

![image](https://user-images.githubusercontent.com/3479453/62787345-1a279180-baf7-11e9-993a-9ed23728ba9b.png)
_should show all available variable if there's no way to determine what the user want  to input_

**VS Code extension or command-line**
VSCode extension 1.0.54

**Comment by erictraut** [comment]
All good suggestions. These will all be addressed in the next version of pyright.

**Comment by erictraut** [comment]
Thanks again for the suggestions. I've addressed all of these and more in 1.0.55, which I just published.

Keep the great suggestions coming!

**Comment by giyyapan** [comment]
Fix confirmed. Thanks! :heart:
