### ISSUE TITLE
Incorrect Undefined Variable for Outer Scope Var

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#1908]
**Describe the bug**
Variable marked as undefined when coming from an outer scope and then assigned in one branch.

**To Reproduce**
```
from typing import Callable, Optional


def f(x: Optional[bool]) -> Callable[[], bool]:
    def g() -> bool:
        if not x:
            x = True
        return x

    return g

```

Error message, "x" is not defined for the line `if not x`
**Expected behavior**
No error.

**VS Code extension or command-line**
pylance 2021.5.4-pre.1

**Comment by JelleZijlstra** [comment]
That error is correct. The code will throw an UnboundLocalError at runtime. To fix it, you need to write `nonlocal x`.

**Comment by hmc-cs-mdrissi** [comment]
That code is simplified part of a unit test that runs successfully. Also the error message goes away if I tweak to

from typing import Callable, Optional


```
def f(x: Optional[bool]) -> Callable[[], bool]:
    def g() -> bool:
        if not x:
            x_ = True
        else:
          x_ = False
        return x_

    return g


```even though that code starts the exact same way.

**Comment by JelleZijlstra** [comment]
That code is very different, because it creates a separate variable `x_` in the inner scope.

**Comment by hmc-cs-mdrissi** [comment]
Testing that, that does explain the error.A bit surprised that even though the two examples start the same, the later mutation in first breaks the first access. Reading the nonlocal documentation explains it.
