### ISSUE TITLE
Type alias is illegal after a for loop or while loop

### ISSUE THREAD

**Issue by Zomatree** [microsoft/pyright#1929]
**Describe the bug**
using a type alias after a for loop or while loop invalidates the type alias and results in pyright saying its an invalid type annotation.

If you remove the for loop or while loop it becomes valid again.

**Expected behavior**
The type alias to be a valid annotation whenever.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/39768508/120234220-6e14e480-c24f-11eb-87ec-f3133370ba0b.png)
![image](https://user-images.githubusercontent.com/39768508/120234417-d2d03f00-c24f-11eb-88d4-f578bca75496.png)

**VS Code extension or command-line**
Errors both in pylance and pyright
`pyright 1.1.136`
`pylance v2021.5.4`

**Additional context**
Python 3.9.5

In 3.10 this issue is not there.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.146, which I just published. It will also be included in the next release of pylance.
