### ISSUE TITLE
import package can't be recognized

### ISSUE THREAD

**Issue by silentmissile** [microsoft/pyright#194]
**Describe the bug**
in a completely new Django project, django.app can't be recognized in import expression

in apps.py, the hint of pyright is:

Import 'django.apps' could not be resolved

my platform:
win10 x64
vscode 1.37.0 x64 user setup
pyright 1.0.55

anaconda 2019.03 x64
python 3.7.3
django 2.2.4

**To Reproduce**
django-admin startproject mysite
cd mysite
python manage.py startapp demo

VSCode open mysite/demo/apps.py
move the mouse to django.apps in the 1st line

**Expected behavior**
the wrong hit can disapear

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```
def foo(self) -> str:
    return 3
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.

**Additional context**

**Comment by erictraut** [comment]
You need to configure pyright so it knows about the third-party imports like django. Pyright provides multiple configuration mechanisms depending on how you have your python environment set up. For details, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/import-resolution.md).

**Comment by erictraut** [comment]
Perhaps the easiest solution is to install the standard VS Code "Python" extension along with Pyright. The Python extension allows you to easily specify which python interpreter you're using for your project. Once you've configured it, pyright will use that same setting.

I followed your steps above and confirmed that it's working fine once it's configured correctly.

**Comment by silentmissile** [comment]
that's correct, after I assign anaconda python.exe to python.pythonpath, pyright can recognize the module
