### ISSUE TITLE
pyright allows calling `Union` and similar classes

### ISSUE THREAD

**Issue by Zomatree** [microsoft/pyright#1942]
**Describe the bug**
Pyright allows you to call `Union` and similar classes and trys to check the arguments types being passed as well. At runtime however this will fail as none of them are actually callable.

**Expected behavior**
I expect pyright to raise an error saying that they are not callable and for it to not attempt to type check the arguments being passed to the values inside.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/39768508/120664642-02b35880-c483-11eb-9155-8e6a4d848b7c.png)
at runtime you will get
`TypeError: Cannot instantiate typing.Union`
`TypeError: Callable() takes no arguments`

**VS Code extension or command-line**
`pyright 1.1.146`

**Comment by erictraut** [comment]
Thanks for the feature request. This will be implemented in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.147, which I just published. It will also be included in the next release of pylance.
