### ISSUE TITLE
"x is not a known member of module" error for reportGeneralTypeIssues should account for measures taken to prevent accessing an unsupported member

### ISSUE THREAD

**Issue by HunterAP23** [microsoft/pyright#1944]
**Is your feature request related to a problem? Please describe.**
pyright reports a "x is not a known member of module" error under reportGeneralTypeIssues when the "x" member can not be called due to preventative measures of a program.

Here is an example piece of code:
```python
import os
import sys

def get_info_linux():
    if not sys.platform.startswith("linux"):
        raise OSError("Operating system is not Linux.")
        return
    return os.sched_getaffinity(0)
```

On a Windows system trying to call the `get_info_linux` method will throw an exception and immediately exit the method.
The `os.sched_getaffinity` method is not supported on Windows, and so pyright will still interpret the use of it on Windows as a ***reportGeneralTypeIssues*** error despite the call never being able to actually occur.

**Describe the solution you'd like**
pyright could have added functionality for seeing whether or not an unsupported member function or variable is actually used.
I understand they may involve something closer to a unit-test of sorts where pyright would have to actually run the program with different inputs on different systems, but I feel that it may be possible to see whether or not an unsupported member gets used or not.

Currently the only workarounds are to ignore any ***reportGeneralTypeIssues*** errors, or change their diagnostic level to either "none", "warning", or "information", but neither of these solutions are ideal as other errors under the ***reportGeneralTypeIssues*** category would also be ignored or not reported properly.

**Comment by erictraut** [comment]
Pyright already does this, but you need to use the standard conditional expression forms that are mentioned in PEP 484 and used in typeshed stubs. The expression `sys.platform.startswith("linux")` is not one of those forms and is generally too complex for a static type checker to understand. If you use the same form that's used within the typeshed stubs, it will work fine.

```python
def get_info_linux():
    if sys.platform != "linux":
        raise OSError("Operating system is not Linux.")
        return
    return os.sched_getaffinity(0)
```

If you think it's important to support additional expression forms, that would be a good topic to bring up in the typing-sig. We would implement support for additional forms if they become part of the standard that all Python type checkers use.

If you don't like the above workaround, you can use a "# type: ignore" comment on that line to ignore the problem.

**Comment by HunterAP23** [comment]
Oh that's perfect!
I would still suggest that additional expression forms be implemented, just to cover more scenarios and cases, if possible.

Thank you for the help!

**Comment by jakebailey** [comment]
FWIW, there was a thread that was related to this last month about supporting other forms (thanks to other platforms besides the big three): https://mail.python.org/archives/list/typing-sig@python.org/thread/MMEB3JYAXDT3IPVNBI4BFXTU6ETCB3ES/

**Comment by erictraut** [comment]
Each new expression form involves rather gross and hard-to-maintain special-case code because they need to be evaluated early in an early phase of the analyzer when we're building the code flow graph. For this reason, we generally don't entertain adding support for new forms unless/until we have strong signal that they're needed. We currently support the same set of expression forms that are supported by the other major Python type checkers. The typing-sig discussion that Jake mentioned above is the best forum in which to discuss expanding that set.
