### ISSUE TITLE
Recursive protocol does not work with static methods

### ISSUE THREAD

**Issue by lijunkang12** [microsoft/pyright#1948]
**Describe the bug**
When static methods are included, recursive protocol typing seems not to work.

**Screenshots or Code**
```python
from typing import Protocol
from __future__ import annotations

class Family(Protocol):
    @staticmethod
    def static_union(f: Family, g: Family) -> Family: ...

    def union(self, g: Family) -> Family: ...

class SetFamily():
    @staticmethod
    def static_union(f: SetFamily, g: SetFamily) -> SetFamily: ...
    def union(self, g: Family) -> Family: ...

f: Family = SetFamily()  # not OK
```

In the previous example, we have the following error:
```
Expression of type "SetFamily" cannot be assigned to declared type "Family"
  "static_union" is an incompatible type
    Type "(f: SetFamily, g: SetFamily) -> SetFamily" cannot be assigned to type "(f: Family, g: Family) -> Family"
      Parameter 1: type "Family" cannot be assigned to type "SetFamily"
        "Family" is incompatible with "SetFamily"
      Parameter 2: type "Family" cannot be assigned to type "SetFamily"
        "Family" is incompatible with "SetFamily"
      Function return type "SetFamily" is incompatible with type "Family"
        "static_union" is an incompatible type
```

However, if the lines
```
    @staticmethod
    def static_union(f: Family, g: Family) -> Family: ...
```
are commented out, then there is no more error.

**VS Code extension or command-line**
Pylance 2021.6.0 (with Pyright 1.1.146)

**Comment by erictraut** [comment]
Pyright is doing the right thing here. Your protocol class indicates that the method `static_union` must accept parameters of type `Family`, but the `static_union` method in `SetFamily` is limiting these parameters to accept only `SetFamily` instances. That makes it incompatible with the protocol. Mypy emits the same error in this situation.

Perhaps this meets your needs?

```python
from typing import Protocol, TypeVar
from __future__ import annotations

_T = TypeVar("_T", bound="Family")

class Family(Protocol):
    @staticmethod
    def static_union(f: _T, g: _T) -> _T:
        ...

    def union(self, g: Family) -> Family:
        ...

class SetFamily:
    @staticmethod
    def static_union(f: _T, g: _T) -> _T:
        ...

    def union(self, g: Family) -> Family:
        ...

f: Family = SetFamily() # OK
```

**Comment by lijunkang12** [comment]
Thank you, your solution does indeed fix the problem.

However, I made a mistake in my example. If `union` method of `SetFamily` has signature `(g: SetFamily) -> SetFamily` then there is still an error. I have to change the signature into `(g: _T) -> _T`.

So, I wonder if I want to implement several recursive classes (for example, SetFamily, TupleFamily, ListFamily, etc) that are different implementations of the same data structure, the signature of which is described by a protocol, how should I annotate those different implementations? Should I use `_T` wherever the type of a variable in a class is supposed to be compatible with the protocol?

**Comment by erictraut** [comment]
Yes, that's one approach. 

Another approach is to not use protocols (structural typing) and use standard inheritance, perhaps with a mix-in class.

**Comment by lijunkang12** [comment]
You mean using abstract base classes? Anyway, I will investigate into the direction that you indicate.

Many thanks! I am truly grateful for your patience and your helpful answers!

**Comment by lijunkang12** [comment]
Sorry to bother you, but no matter how I try, I cannot find a solution without using your idea `_T = TypeVar("_T", bound="Family")`. Take the following as an example:
```Python
from __future__ import annotations
from abc import ABC, abstractmethod


class Family(ABC):
    @abstractmethod
    def union(self, g: Family) -> Family: ...


class SetFamily(Family):
    def union(self, g: SetFamily) -> SetFamily:
        return SetFamily()
```
Pyright complains that
```
Method "union" overrides class "Family" in an incompatible manner
  Parameter 2 type mismatch: base parameter is type "Family", override parameter is type "SetFamily"
    "Family" is incompatible with "SetFamily"
```

The reason I do not want to use `_T` to type the parameter `g` in the method `union` of `SetFamily` is that `g` should have type `SetFamily`, not just any subtype of `Family`. For example, `SetFamily` objects may have an attribute `foo: int` while this attribute is not required in the interface specified by `Family`. Hence if `g` is not typed as `SetFamily`, there is no way Pyright knows that `g` has an attribute `foo`. Do you have a solution for this?

**Comment by erictraut** [comment]
The diagnostic check generating this error is the `reportIncompatibleMethodOverride` check, which is off by default. I presume that you have enabled this check, or you have enabled "strict" mode which includes this check.

The reason this is an error is that you are violating the contract specified in the base class `Family`. It indicates that the `union` method must handle any instance of `Family` as an input parameter. What does your implementation of `SetFamily.union` do if it receives an input that is not a `SetFamily` instance? Does it crash? Does it handle it correctly?

I see two options:
1. Remove `union` from the `Family` base class and implement it only in child classes.

```python
class Family(ABC):
    ...

class SetFamily(Family):
    def union(self, g: SetFamily) -> SetFamily:
        return SetFamily()
```

2. Indicate in the base class that the return type is always the same as the type of `self` and modify subclasses to accept any `Family` for input parameter `g`.

```python
_TFamily = TypeVar("_TFamily")

class Family(ABC):
    @abstractmethod
    def union(self: _TFamily, g: Family) -> _TFamily:
        ...

class SetFamily(Family):
    def union(self, g: Family) -> SetFamily:
        if not isinstance(g, SetFamily):
            raise ValueError("Input must be SetFamily")
        return SetFamily()
```

**Comment by lijunkang12** [comment]
Many thanks for your precious time.

`Family` is supposed to be an abstract class (or interface, or protocol) for a data structure. It specifies some methods that the data structure should support. `SetFamily` is a concrete implementation of the data structure. There are other implementations, which we may call `FooFamily` and `BarFamily`. These three implementations should support all methods specified by `Family`, such as the `union` method in my previous example.

The intention behind this is that I have a function `f` that needs to use the data structure `Family`. However, `f` does not care about how one implements `Family`. All it wants is to have a class that supports all methods of `Family`. So, one should be able to plug any of the three concrete implementations `SetFamily`, `FooFamily`, `BarFamily` into the function `f`. Using abstract base class, this is easily accomplished. However, I cannot do so without evoking typing error under "strict" mode, which is my main concern right now.

Perhaps this sounds a little bit abstract. A real-world example is to implement the data structure `Graph`. Suppose that the abstract class `Graph` has an attribute `vertices` (which return an iterable of vertices), and a method `neighbour` (which takes a vertex as input and return an iterable of vertices). One can have multiple concrete implementations of this data structure. In one implementation (call it `PlainGraph`), one stores a set of vertices and a set of edges, which are themselves a tuple of two edges. In another implementation (call it `MatrixGraph`), one stores the adjacency matrix of the graph. Now imagine my function `f` takes a graph as input and output whether the graph contains a cycle. `f` need not concern about how a graph is implemented. All it wants is to query the list of vertices of the graph, and given the name of a vertex, query its neighbour in the graph. So, if `PlainGraph` and `MatrixGraph` are correctly implemented subclasses/subtypes of the abstract class/protocol `Graph`, then my function `f` will be able to take an instance of either class as input and works correctly.

However, since `PlainGraph` and `MatrixGraph` store the graph differently, they necessarily implements the method `neighbour` differently. This is still fine and does not cause any typing error. What causes typing error is the situation where we decide to add a new method `union` to the abstract class `Graph`. This method supposes to take two graphs as input and output the union of two graphs. Then clearly, `Graph.union` should have type `(Graph, graph) -> Graph`. But `PlainGraph.union` should have type `(PlainGraph, PlainGraph) -> PlainGraph`, while `MatrixGraph.union` should have type `(MatrixGraph, MatrixGraph) -> MatrixGraph`. But currently I do not know how to annotate these classes such that there is no typing error.

Returning to my previous example. `SetFamily.union` should have type `SetFamily -> SetFamily`, not `Family -> Family`, because the implementation of `SetFamily.union` supports only instances of type `SetFamily`, not `Family`. Use the example in the previous paragraph, `MatrixGraph` uses the fact that it stores the graph as a matrix to implement `union`, so `MatrixGraph.union` does not work with all inputs of type `Graph`: it only works with inputs of type `MatrixGraph`. Hence, the second option you propose is not desirable. The first option is not desirable either, since it is required that any implementations of `Family` should have the method `union`. If I remove `union` from `Family`, then in my function `f` which accepts an input of type `Family`, Pyright has no way to know that the input instance support the method `union`.

I am sorry this seems to be too complicated as a question, I even doubt that it is not relevant to Pyright itself, but rather to Python's type checking functionalities. I am really confused why Python's type checking does not support this usage of abstract class more naturally.

**Comment by lijunkang12** [comment]
I have finally figured out a solution for my problem!!!
```Python
TFamily = TypeVar("TFamily")

class Family(ABC):
    @abstractmethod
    def union(self:TFamily , g: TFamily) -> Family: ...

class SetFamily(Family):
    def union(self:TFamily, g: TFamily) -> SetFamily:
        return SetFamily()
```
The trick is to use type variable to enforce that the `union` method accept an input of the same type as the instance. One can also change the type hint of `Family.union` into `union(self:TFamily , g: TFamily) -> TFamily` without generating typing error. However, if one also changes the type hint of `SetFamily.union` into `union(self:TFamily , g: TFamily) -> TFamily`, there will be a typing error
```
Expression of type "SetFamily" cannot be assigned to return type "TFamily@union"
  Type "SetFamily" cannot be assigned to type "TFamily@union"
```
which I assume is a bug, since `self:TFamily` already bind `TFamily` to `SetFamily`.

To illustrate this solution really works, here is a minimal example:
```Python
class DictFamily(Family):
    def union(self:TFamily, g: TFamily) -> DictFamily:
        return DictFamily()

f = SetFamily()
g = SetFamily()
h = DictFamily()

f.union(g) # OK
f.union(h) # not OK
```
So now the type checker correctly infers that `f.union` only accepts input of type `SetFamily`, as intended.

**Comment by lijunkang12** [comment]
Of course, one can also use the same trick with type protocol instead of ABC:
```Python
from typing import Protocol, TypeVar
TFamily = TypeVar("TFamily")

class Family(Protocol):
    def union(self:TFamily , g: TFamily) -> Family: ...

class SetFamily:
    def union(self:TFamily, g: TFamily) -> SetFamily:
        return SetFamily()
```

**Comment by lijunkang12** [comment]
The lesson of this long struggle is that when designing a protocol (or an ABC), if one needs a method that supposes to take an input of the same class of `self`, one needs to use type variable to enforce that.

If the protocol does not have such

**Comment by lijunkang12** [comment]
Well, the aforementioned still has a little problem:
```Python
class SetFamily(Family):
    value: int
    def union(self:TFamily, g: TFamily) -> SetFamily:
        self.value # not OK
        ...
```
will generate two errors:
```
Type of "value" is unknown
Cannot access member "value" for type "object"
  Member "value" is unknown
```
Is this a bug?

**Comment by erictraut** [comment]
This is expected behavior. `TFamily` is bound to `Family`, and `Family` doesn't have a class or instance variable called `value`, so `self.value` should generate an error.

**Comment by erictraut** [comment]
You need to bind the TypeVar.

```python
# pyright: strict

from typing import Protocol, TypeVar

TFamily = TypeVar("TFamily", bound="Family")
TSetFamily = TypeVar("TSetFamily", bound="SetFamily")

class Family(Protocol):
    def union(self: TFamily, g: TFamily) -> "Family":
        ...

class SetFamily:
    value: int

    def union(self: TSetFamily, g: TSetFamily) -> "SetFamily":
        self.value  # OK
        return SetFamily()

f: Family = SetFamily()  # OK
```

**Comment by lijunkang12** [comment]
This is indeed the last missing piece. However, this solution only works with `Protocol`, but not with ABC:
```Python
TFamily = TypeVar("TFamily", bound="Family")
TSetFamily = TypeVar("TSetFamily", bound="SetFamily")

class Family(ABC):
    @abstractmethod
    def union(self: TFamily, g: TFamily) -> Family: ...

class SetFamily(Family):
    value: int
    def union(self: TSetFamily, g: TSetFamily) -> SetFamily:
        g.value  # OK
        return SetFamily()

f: Family = SetFamily()  # OK
```
This generates the error:
```
Method "union" overrides class "Family" in an incompatible manner
  Parameter 2 type mismatch: base parameter is type "TFamily@union", override parameter is type "TSetFamily@union"
    "Family" is incompatible with "SetFamily"
```

On the other hand, if `Family` is defined using `Protocol`, then no type variable is needed for `SetFamily`:
```Python
class Family(Protocol):
    def union(self: TFamily, g: TFamily) -> Family: ...

class SetFamily:
    value: int

    def union(self, g: SetFamily) -> SetFamily:
        g.value  # OK
        return SetFamily()

f: Family = SetFamily()  # OK
```

And this solution does not apply to static method. If `Family` has a static method `family_union` which takes two inputs of type `Family` while `SetFamily.family_union` takes two inputs of type `SetFamily`, then it seems that I cannot make `SetFamily` a subtype of `Family`. Is this intentional?
