### ISSUE TITLE
Getting unexpected error from “# pyright: strict”

### ISSUE THREAD

**Issue by SurushCyrus** [microsoft/pyright#195]
Env:
Python 3.7.4

Repro:
1-Install azure SDK via 
pip install azure

background:
https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-install?view=azure-python

2-in Python file have the following
# pyright: strict
from azure.storage.file import FileService

You get error for azure.storage.file!

Note: there no issue that I can see. If I remove # pyright: strict, problem goes away but it is a bad workaround since I want to catch my typing issues.

**Comment by erictraut** [comment]
To perform proper type checking, pyright needs type information for any libraries that you're importing. These come in the form of type stub (".pyi") files. These are similar to "header files" in the C world or "type definition files" in the TypeScript world. Unfortunately, most python libraries today do not ship with type stub files, so you will need to create your own partial stub files for the classes and functions that you use. If type stub files are not present, pyright can still perform some type checking, but it will not be complete. If you want to use "strict" mode, you're doing to need to create type stubs.

For more details, see [this documentation](https://github.com/microsoft/pyright/blob/master/docs/import-resolution.md).

**Comment by SurushCyrus** [comment]
Thanks for info. I am not familiar with the stubs files and how I create them. Can I follow "mypy" instructions described in https://github.com/python/mypy/wiki/Creating-Stubs-For-Python-Modules ?

**Comment by erictraut** [comment]
Yes, that link provides a good starting point. In most ways, stub files are like normal python files except that they leave out the implementation of functions and classes, including only the interface details (public method signatures, public instance variables, etc.).

**Comment by SurushCyrus** [comment]
Thank You Sir.
