### ISSUE TITLE
Type Stub PEP

### ISSUE THREAD

**Issue by srittau** [Microsoft/pyright#20]
Together with @rchen152, @solumin, and @JelleZijlstra I am currently writing a PEP about type stubs. (Progress is currently stalled a bit, since other projects took precedence, but I plan to continue working on it soon.) The PEP includes a reference section with links to existing type checkers and I'd like to include pyright. Could you give a brief, one-line explanation to be included in the PEP about what makes pyright special, compared to the other type checkers?

For reference, here are the existing explanations:

* mypy -- Optional Static Typing for Python
* PyCharm -- The Python IDE for Professional Developers
* Pyre -- A performant type-checker for Python 3
* pytype -- A static analyzer for Python code

Edit: https://github.com/srittau/type-stub-pep

**Comment by erictraut** [comment]
Hi Sebastian, thanks for your interest. 

Keep in mind that pyright is a work in progress. It's a side project with no full-time engineering team behind it. In that respect, I don't know if it has yet to earn a spot on this list.

There is one entry that I would like to encourage you to add. Microsoft does have an officially-supported [Python Language Server](https://github.com/Microsoft/python-language-server), an extension for VS Code that has been downloaded over 35M times already. It contains a Python type checker and is fully supported by a team at Microsoft. They are making improvements to it all the time. It isn't currently offered in the form of a command-line tool, but it is a capable type checker and deserves to be included in your list. You can contact the maintainers through the GitHub site I referenced above.

**Comment by srittau** [comment]
Thank you for your pointer to the language server. If at some point in the future you feel that pyright should be added to the list, please let us know, either in our current repository, or in the [PEPs respository](https://github.com/python/peps) after the PEP is released.
