### ISSUE TITLE
Map with os.path.basename bug

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#2029]
**Describe the bug**
```
import os

map(os.path.basename, ["hi.txt"])
os.path.basename("hi.txt")
```

**Expected behavior**
No errors.

**Actual behavior**
Last line is fine, but using map on a list of strings with os.path.basename gives,

```
No overloads for "__init__" match the provided arguments
  Argument types: (Overload[(p: PathLike[AnyStr@basename]) -> AnyStr@basename, (p: AnyStr@basename) -> AnyStr@basename], list[str])

```

**VS Code extension or command-line**
Pylance version 2021.6.4-pre.1

**Comment by erictraut** [comment]
I think pyright is doing the right thing here. Mypy gives the same error in this case.

**Comment by hmc-cs-mdrissi** [comment]
How? The code runs fine. The last line shows that function should work on strings so map should work fine with list of strings. If I replace the code with map using list comprehension pyright type checks it correctly.

[os.path.basename(file) for file in ["hi.txt"]] is ok, but list(map(os.path.basename, ["hi.txt"])) is not?

**Comment by hmc-cs-mdrissi** [comment]
Looking into this a bit more, mypy has this case marked as a bug https://github.com/python/mypy/issues/9864

**Comment by hmc-cs-mdrissi** [comment]
I guess it's a side effect of not that many overloaded functions compared to normal functions for this being so rare. It's a low priority fix for me as the existing workarounds are clean code so fine with closing this.

**Comment by erictraut** [comment]
OK, I'm going to close this.
