### ISSUE TITLE
[Feature Request] Break "reportPrivateUsage" into two parts

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pyright#2031]
I was trying to break classes in same files into separate files in same modules while roughly keeping the same code structure, to obtain better maintainability, and almost succeeded.

Then I found that with "reportPrivateUsage" being turned on, one class calling protected (single-underscore) methods from others gets reported because they are now in different sub-modules (files).

While I want the protected (single-underscore) methods to get ignored as if their accessibility were more like "internal" (as in Swift, which allows access through the whole module) than "protected", I still like the private (double-underscore) methods to get checked. Currently, it seems not possible with only one config item.

**Comment by erictraut** [comment]
From what I've seen, double underscores are very rarely used in Python. Most developers use a single underscore to mean "private". So I don't think this split would be beneficial to most users. We have split diagnostic checks in cases in the past, but only when we have good reason to do so. We don't want these to proliferate too much. It's also somewhat of a breaking change for users who have already set up their configuration as they like.

For these reasons, I think we will need to wait for signal from other pyright users that they want this change.

**Comment by erictraut** [comment]
I'm going to close this for now. If you have interest in this feature, please upvote or reply to this thread. We will reconsider in the future if there is sufficient interest.
