### ISSUE TITLE
Remove support for "mspythonconfig.json" in favor of "pyrightconfig.json"

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#2034]
Pyright currently supports an undocumented alternative config file name "mspythonconfig.json". It was added at a time when we had not yet finalized the plans around pylance, and it's no longer meaningful. I don't think anyone is using this alternative because it's not documented. I'd like to remove support for it completely. If someone happens to be using it, they can easily switch to "pyrightconfig.json" or specify a custom config path.

**Comment by erictraut** [comment]
@jakebailey, let me know if you have any concerns about this.

**Comment by erictraut** [comment]
This will be in the next release.

**Comment by jakebailey** [comment]
I don't think there are any concerns; you already fixed up the fourslash test stuff so that's the only thing we'll have to fix up in Pylance.

**Comment by erictraut** [comment]
This is included in pyright 1.1.154, which I just published. It will also be included in the next release of pylance.
