### ISSUE TITLE
Pyright does not handle guarded access involving AttributeError

### ISSUE THREAD

**Issue by NCPlayz** [microsoft/pyright#2036]
**Is your feature request related to a problem? Please describe.**
In similar vein to #1739, Pyright does not currently handle guarded access to an attribute that may not exist on all types.

**Describe the solution you'd like**
Currently, doing:
```py
from typing import Union
import random

class Foo:
    key: str = "Test!"

class Bar:
    ...

x: Union[Foo, Bar] = random.choice([Foo(), Bar()])

try:
    value = x.key
except AttributeError:
    value = "Hello World!"

print(value)
```
results in
![image](https://mypy.is-dangero.us/7xSf3DT.png)
I feel like `key` should not be inferred as being unknown as the existence of the attribute is being handled in the block.

**Comment by JelleZijlstra** [comment]
This is essentially the same as #2005, which was rejected.

**Comment by mikeshardmind** [comment]
```py
try:
    value = x.key
except AttributeError:
    value = "Hello World!"
```

A narrow case like this, where x is a Union of things where the type of key is either non-existant or homogenous with the handling of the abscence seems to make a lot of sense. It also fits in well with the way python encourages code to be written, including upcoming interpreter level changes to reduce the negative impacts of this (see zero cost exceptions in 3.11 https://bugs.python.org/issue40222)

I'm not sure I agree that this is the same as 2005, as that was a TypeError used as control flow, not an attribute error which is handled on a single assignment.

In terms of keeping it narrow what is supported, I don't think it makes sense to support anything broader than a single assignment guarded by *specifically* an AttributeError being caught, and assignment to the same name being provided in that handling.

There are currently supported ways to do this that work to varying degrees, but all of these are slower and stick out like sore thumbs if used in real world code.

```py
# Slower, type not inferred.
value = getattr(x, "key", "Hello World!")
```

```py
# Slower, type inferred, only works with types which runtime checkable via isinstance
# Would work with runtimecheckable protocols as well, but these are even slower for isinstance
value = x.key if isinstance(x, Foo) else "Hello World!"
```

```py
# Also slower, while the degree to which it is slower is reduced, 
# this is very obviously working around tooling limitations rather than tooling improving developer experience.
if TYPE_CHECKING:
    value = x.key if isinstance(x, Foo) else "Hello World!"
else:
    try:
        value = x.key
    except AttributeError:
        value = "Hello World!"
```

I'd rather not make stuff that can be known to be safe from what information static analysis has access to have negative impact on the time it actually requires at runtime or require things that stand out as sore thumbs in code.

I know the performance of special casing various things has come up before, but if the question is special case the tooling to understand a common efficient runtime pattern or special case the code that might be running for years, there's a very clear answer that the tooling should be what is slower. The tooling only runs while the code is in development and only to assist the developer.

**Comment by erictraut** [comment]
I consider this the same as the other issue. I think pyright is doing the right thing here as a type checker. Other type checkers (both in Python and other languages) also flag this situation as an error. Try it in mypy, for example.

I don't recommend using exception handling for non-exception (expected) control flow. If you are convinced you have good reason for doing this, you can disable the type checker's diagnostic using a variety of mechanisms including a `# type: ignore`.
