### ISSUE TITLE
Provide more support for untyped 3rd party package

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#204]
**Is your feature request related to a problem? Please describe.**
Current version of pyright only have very limited support for untyped 3rd party package, including (as far as I know):
- Give error when a package can't be resolved
- Shows intelliSense suggest about subfolders inside the packege when use `from A import B` syntax
- Treat anything that imported from a untyped package as 'Unkown', (but won't check if the imported member realy exists in the source package)

![image](https://user-images.githubusercontent.com/3479453/63139708-d1e60300-c011-11e9-827f-cacdd636fec3.png)
_no error when import non-exist variable_

![image](https://user-images.githubusercontent.com/3479453/63139725-e4603c80-c011-11e9-82a4-31493ad81a42.png)
_only suggests subfolders_

**Describe the solution you'd like**
Though it's reasonable that pyright relys on type stubs, most 3rd party packages (including wildly used ones) simply doesn't have one. 

I think pyright could provide some basic support to them by scan all exported member from a 3rd package when it's included, and implements the following features:
- Give error if an imported variable was not defined in the source pacakge.
- Support `Go to defination` for imported variable.
- Provide intelliSense suggest of package's exported member when using `from A import B` syntax.
- Support `Find all reference` for imported variable. It's ok to have only those references inside user's project.

Thank you.

_If scan 3rd party package can be a performance issue, I think it's ok to treat everything in the package to be the type of Unknow, and don't do any recursive scan to their sub-imports._

**Comment by erictraut** [comment]
Thanks for the suggestion, but I have a very clear and strong opinion on this matter. I feel very strongly that type stubs are the right approach here. Scanning third-party libraries for symbols is very costly and, at best, error-prone. The python world needs to wake up and get on board. For a more complete list of reasons, see [this part of the pyright documentation](https://github.com/microsoft/pyright/blob/master/docs/import-resolution.md#importance-of-type-stub-files).

In the meantime, if you're serious about type checking, you should create your own type stub files for libraries that don't provide them.

**Comment by giyyapan** [comment]
Thanks for your reply.

I totally agree with the "type stubs are the right approach" opinion, but there's so much work to do, and the python world seems not very positive about it (unlike the JS world).

I think one of the reason is that python's type system is not stand-alone but mixed with runtime, that's (in my opinion) a bad design which making type-stubs harder to write and need to use the TYPE_CHECKING trick often.

Anyway, I respect your decision. I think I'll just write a one-time parser to generate basic type stubs (everything treated as 'Any') for my dependencies.

**Comment by erictraut** [comment]
I've thought about adding a command-line switch to the CLI version of pyright that generates basic type stub files. I think that's a reasonable approach, and that would be pretty straightforward to implement. If you like that idea, feel free to create a new enhancement request.

**Comment by giyyapan** [comment]
That's awesome! I'll create a feature request.
