### ISSUE TITLE
Support "Go to Symbol in File..." functionality.

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#205]
`Go to Symbol in File...` is a commonly used functionality of VSCode in my experience, especially when the file is big.

Without it, if I'd like to find a function, I'd have to remember the exact spelling of it's name and use `Search` for couple of time, very inefficient.

It would be very nice that pyright can support this functionality by providing symbol information.

Thanks!

_As for `Go to Symbol in Workspace`, I don't use it much because it provides too much candidates and that makes it less useful, so I don't have any requirement about it._

**Comment by erictraut** [comment]
I've never used "Go to Symbol in File...". I didn't even notice it existed, but I can see how and where it would be useful. Thanks for the suggestion.

**Comment by erictraut** [comment]
Thanks again for the suggestion. This functionality will be in the next published version of pyright.

**Comment by erictraut** [comment]
This is now implemented in 1.0.56, which I just published.
