### ISSUE TITLE
rename() stops working in a virtual environment

### ISSUE THREAD

**Issue by ksalman** [microsoft/pyright#2065]
**Describe the bug**
rename() stops working if `pyvenv.cfg` exists in the same directory

**To Reproduce**
Create a test file `main.py`
```
def test():
    pass
test()
```
Rename works for test(), but if we have a file (even empty file) `pyvenv.cfg` in the same directory, rename stops working. I created a Docker image to test this with minimal config https://github.com/ksalman/neovim-pyright-issue

**Expected behavior**
rename works as expected

**Screenshots or Code**
https://github.com/ksalman/neovim-pyright-issue

**VS Code extension or command-line**
Neovim 0.5.0
Pyright 1.1.155

**Comment by jakebailey** [comment]
This file is typically created by `venv` for virtual environments, and we use this to help determine which code is library code (and therefore should be treated as read-only).

Are you putting your code inside a virtual environment?

**Comment by ksalman** [comment]
That is correct - I see the issue when I am in a virtual environment. I was originally seeing the issue when I was in a virtual environment. I started removing directories/files until only `pyvenv.cfg` was left and I was still seeing the issue.

**Comment by jakebailey** [comment]
Treating virtual environments as read-only is intentional. Why are you putting your code inside the virtual environment to edit it?

**Comment by ksalman** [comment]
Oh I see, I am putting the code in the wrong directory. Thanks for the prompt response.
