### ISSUE TITLE
`Protocol` property cannot be implemented as a simple field

### ISSUE THREAD

**Issue by tamuhey** [microsoft/pyright#2072]
Implementing a `property` in `Protocol` by a simple field is not allowed in `Pyright`, while mypy accepts it:

```python
class P(Protocol):
    @property
    def v(self) -> int:
        return 1

@dataclass
class Foo:
    v: int  # implementing property as a field

class Bar:
    @property
    def v(self) -> int:
        return 1

def f(x: P):
    ...

foo = Foo(1) 
f(foo) # ERROR: Argument of type "Foo" cannot be assigned to parameter "x" of type "P" in function "f"
bar = Bar()
f(bar) # OK
```

Is this as-designed?

**Comment by erictraut** [comment]
Yes, this is intended. A property is not the same as a simple field. They have similar but subtly different semantics.

**Comment by tamuhey** [comment]
Thanks! If I want to implement a `Protocol` that supports both `Foo` and `Bar` above, what should I do?
When I asked the same question in mypy community, they answered the above `P` workaround.

**Comment by erictraut** [comment]
`Foo` and `Bar` do not have anything in common other than the fact that they have a symbol named `v`, so there's no way to implement a protocol that supports both of these. As I said above, a property is not the same as a simple member. I recommend that you pick one or the other. Don't try to mix the two.
