### ISSUE TITLE
Documentation for `# pyright: ` comments seems to be missing

### ISSUE THREAD

**Issue by benesch** [microsoft/pyright#2089]
I recently learned about the feature where adding a comment like

```py
# pyright: reportConstantRedefinition=false
```

anywhere in a Python file will disable the specified lint in that whole file. But I found this in a GitHub issue and couldn't find it mentioned in the docs anywhere. Is it? And if not, it would be great if it were! Happy to submit a PR if someone wants to point me in the right direction.

**Comment by erictraut** [comment]
Here's the documentation: https://github.com/microsoft/pyright/blob/main/docs/comments.md

**Comment by benesch** [comment]
>.< sorry.
