### ISSUE TITLE
Type ignore should not require being leading comment

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#2092]
**Is your feature request related to a problem? Please describe.**
Currently if you have code like this,

`x: int = "hello" # type: ignore`

it type checks. But if you try this,

`x: int = "hello" # pylint: disable=error-msg # type: ignore`

it fails. Type ignore only works when it's leading comment on a line. That's fine when type checker is the only thing you want to ignore but is a bit confusing when you need to disable multiple lint/checkers for the same line.

**Describe the solution you'd like**
`# type: ignore` should  work regardless of it being first comment or later on a line.

**Additional context**
Low priority to me as pylint is not order sensitive so at least I can swap the two. Would be nice as it's confusing behavior though.

**Comment by erictraut** [comment]
I think the current behavior is correct based on PEP 484. Sounds like you have a workaround, so I'm going to close this as "won't fix".
