### ISSUE TITLE
list += sometimes ignores Optional operand

### ISSUE THREAD

**Issue by jtlapp** [microsoft/pyright#2094]
**Describe the bug**
The `+=` operator acting on lists sometimes accepts a type that can be `None`, regardless of type inferencing.

**Expected behavior**
`list1 += list2` should error whenever `list1 = list1 + list2` errors. If `list2` can be `None` at this point in the code, the error should be that type `None` is not a list.

**To Reproduce**
In the following code, pyright reports no error for function `add_values_no_error` but properly reports an error for the other functions.

```
from typing import Optional


def add_values_no_error(
    values1: list[float] = [], values2: Optional[list[float]] = None
) -> None:
    values1 += values2  # no type errors


def add_values_with_error1(
    values1: list[float] = [], values2: Optional[list[float]] = None
) -> None:
    values1 = values1 + values2  # properly complains about None type


def add_values_with_error2() -> None:
    values1: list[float] = []
    values2: Optional[list[float]] = None
    values1 += values2  # properly complains about None type
```

**VS Code extension or command-line**
I'm running a build of the master branch as of yesterday, using a VSCode extension. The extension reports a version of 1.1.156.

**Additional context**
The bug occurs both with and without the following configuration:

```
{
    "typeCheckingMode": "strict",
    "reportImportCycles": "none",
    "reportUninitializedInstanceVariable": "error",
}
```

**Temporary Workaround**

Don't use the `+=` operator with lists, though I do wonder if the problem exists with other types as well. However, a quick check of the above code changing `list[float]` to `float` showed everything working as expected.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by erictraut** [comment]
This fix is included in pyright 1.1.57, which I just published. It will also be included in the next release of pylance.

**Comment by jtlapp** [comment]
I didn't realize I was auto-syncing the latest pyright despite having built and loaded it manually. It auto-synced and immediately pointed out several errors where I was using += on lists and not checking for `None`. Thank you!

**Comment by jakebailey** [comment]
VS Code will always upgrade you if the marketplace has a newer version; if you want to build locally and force it to not update, you either need to have a dummy version like `9999.0.0` or set `"extensions.autoUpdate": false` to prevent any auto updates.

**Comment by jtlapp** [comment]
I'll file that for future reference, thanks. For pyright, I want to keep them coming.
