### ISSUE TITLE
Ability to transform specific files

### ISSUE THREAD

**Issue by delfick** [microsoft/pyright#2098]
**Is your feature request related to a problem? Please describe.**
It's possible to have custom python codecs that mean the file is transformed at import time. This breaks pyright because instead of operating on the python that is generated, it operates on the original file

**Describe the solution you'd like**
Is it possible to specify a command to be used to transform a file on particular conditions? (i.e. filename or the start of the file starts with a "# coding" comment.

**Additional context**
Specifically https://noseofyeti.readthedocs.io/en/latest/

**Comment by JelleZijlstra** [comment]
This seems difficult to achieve because custom codecs require arbitrary Python code to be executed for decoding, and Pyright doesn't execute Python code.

**Comment by erictraut** [comment]
Yeah, I don't see any way for a static analyzer to support this.

**Comment by delfick** [comment]
yeah, it basically requires the ability to ask pyright to run the file through some program before it operates on it.

**Comment by erictraut** [comment]
Yeah, pyright never executes code nor invokes the Python interpreter to execute code. It's a static analyzer.

**Comment by erictraut** [comment]
You could perhaps write a script that invokes the codec to generate the Python code, then invokes pyright. Use an `if TYPE_CHECKING` check to import the generated code at analysis time.

**Comment by delfick** [comment]
Yeah, that's what I'm saying, but as some kind of preAnalysis hook in pyright that says run the file through some arbitrary program to get the python to analyse.

**Comment by erictraut** [comment]
That's something you can script yourself if you'd like.

**Comment by delfick** [comment]
Does pyright have something so I can still `pyright` and it'll just work or are you saying I have to write a wrapper around pyright?

**Comment by erictraut** [comment]
You would need to generate the code, then invoke pyright. You could automate this using a script.

**Comment by delfick** [comment]
The problem there is when I'm trying to use pyright with say lsp in neovim,
I need pyright be the one who initiates the transformation.

**Comment by delfick** [comment]
so instead of just opening the file, it'd run it through some program first
