### ISSUE TITLE
Regression with --outputjson and non-json output

### ISSUE THREAD

**Issue by RobertCraigie** [microsoft/pyright#2099]
**Describe the bug**

When using the `--outputjson` flag, non-json output is printed as well

**To Reproduce**

`pyright --outputjson file.py`
```
No configuration file found.
pyproject.toml file found at ...
Loading pyproject.toml file at ...
Assuming Python platform Darwin
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding .git
stubPath ... is not a valid directory.
Searching for source files
Found 1 source file
{
    "version": "1.1.157",
    "time": "1626797455800",
    "generalDiagnostics": [],
    "summary": {
        "filesAnalyzed": 14,
        "errorCount": 0,
        "warningCount": 0,
        "informationCount": 0,
        "timeInSec": 0.373
    }
}
```

**Expected behavior**

Only valid json should be printed.

```json
{
    "version": "1.1.157",
    "time": "1626797455800",
    "generalDiagnostics": [],
    "summary": {
        "filesAnalyzed": 14,
        "errorCount": 0,
        "warningCount": 0,
        "informationCount": 0,
        "timeInSec": 0.373
    }
}
```

**VS Code extension or command-line**
Command-line version 1.1.157

**Additional context**

Original bug fix issue #1006

From testing previous versions, it seems that this bug was introduced in version 1.1.137

**Comment by jakebailey** [comment]
Are you certain that output isn't being printed to stderr? stdout will be JSON, but log messages may still be output to stderr (which is useful for CI actions like https://github.com/jakebailey/pyright-action).

**Comment by RobertCraigie** [comment]
Sorry, I didn't see https://github.com/microsoft/pyright/pull/1810 before creating this issue.

**Comment by RobertCraigie** [comment]
@jakebailey you are correct, I hadn't considered that and didn't find the PR you had created before opening the issue
