### ISSUE TITLE
Augmented assignment doesn't work on certain clases

### ISSUE THREAD

**Issue by Skyscimitar** [microsoft/pyright#210]
**Describe the bug**
Python augmented assignment expressions don't work on more complicated objects. The behaviour is the same when creating custom classes and implementing the augmented assignment magic methods.

**To Reproduce**
Run pyright on the provided code snippet

**Expected behavior**
No type exception should be thrown.

**Screenshots or Code**
Creating a list:
```
A: List[int] =  []
A += 0
``` 
The previous snippet throws the following error:
```
error: Operator '+' not supported for types 'List[int]' and 'int'
```
**VS Code extension or command-line**
The error occurs in both the VS Code extension and the command-line tool, both using version `1.0.56`

**Comment by erictraut** [comment]
I think this is correct behavior. The List[int] class doesn't support augmented assignment with a parameter of type int. When I try this in the Python interpreter, it raises a `TypeError: 'int' object is not iterable` exception. I think want you mean to do here is:
`
A: List[int] = []
A += [0]
`

**Comment by Skyscimitar** [comment]
Yes, my mistake for the built-in classes, sorry
