### ISSUE TITLE
possibility to allow overload implementation to be defined not as function def

### ISSUE THREAD

**Issue by cleoold** [microsoft/pyright#2100]
**Is your feature request related to a problem? Please describe.**

I cannot use overload decorators with function factories. Consider this extremely simple example:

```py
T = TypeVar('T')

def identity(s: T) -> T:
    return s

@overload
def hehe(s: int) -> int: ...
    ~~~^

@overload
def hehe(s: str) -> str: ...

hehe = identity
~~~^
```
Pyright reports these:
```
"hehe" is marked as overload, but no implementation is provided (reportGeneralTypeIssues)
Declaration "hehe" is obscured by a declaration of the same name (reportGeneralTypeIssues)
```

The walkaround is to define `hehe` as follows:
```py
def hehe(s):
    return identity(s)
```

However this seems very unnecessary. Generating functions by some factory and then typing it is quite useful. though this example does not use factories, one of my repo broke because of that (https://github.com/nonebot/nonebot/blob/37cd6823322bdfe9357186368ab42eeb0bc920e7/nonebot/plugin.py#L564, pls ignore unmatching arg name for now)

**Describe the solution you'd like**
Some setting other than "reportGeneralTypeIssues" to allow it. or we can check the type of the RHS of the assignment to see if it covers each overload.

**Additional context**

**Comment by erictraut** [comment]
The current behavior is intended. Mypy emits a similar error.

If you don't like the current behavior, you can silence it with a `# type: ignore` comment.
