### ISSUE TITLE
`type(x) is type(y)` type guard?

### ISSUE THREAD

**Issue by lmmarsano** [microsoft/pyright#2101]
**Describe the bug**
The provided example fails type check.
Is this a bug?

**To Reproduce**
Run `pyright` as shown.

```shellsession
$ pyright --outputjson stub.py
Loading configuration file at /home/LOM0227/project/pyrightconfig.json
Assuming Python version 3.9
Assuming Python platform Linux
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding .git
Searching for source files
Found 1 source file
{
    "version": "1.1.157",
    "time": "1626828972734",
    "generalDiagnostics": [
        {
            "file": "/home/LOM0227/project/stub.py",
            "severity": "error",
            "message": "Cannot access member \"x\" for type \"object\"\n  Member \"x\" is unknown",
            "range": {
                "start": {
                    "line": 5,
                    "character": 57
                },
                "end": {
                    "line": 5,
                    "character": 58
                }
            },
            "rule": "reportGeneralTypeIssues"
        }
    ],
    "summary": {
        "filesAnalyzed": 14,
        "errorCount": 1,
        "warningCount": 0,
        "informationCount": 0,
        "timeInSec": 0.248
    }
}
```

**Expected behavior**
From [type guards documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards)
> `type(x) is T` and `type(x) is not T`

and expression
> `type(x) is` _expr_

and inference
> _expr_`: type[T]`

one might expect implication `x: T`.

**Screenshots or Code**
> stub.py
```python
class Test:
  def __init__(self, x: object):
    self.x = x

  def __eq__(self, other: object):
    return type(other) is type(self) and self.x == other.x
```

**VS Code extension or command-line**
Version shown in command output.

**Comment by erictraut** [comment]
This isn't one of the type guards that pyright supports. For a full list of supported type guards see [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards). 

Each new type guard pattern requires custom logic which adds complexity and potentially slows down analysis, so we add them only in cases where we have good evidence that it is a pattern commonly used in Python code. This particular case strikes me as pretty unusual. Mypy (another Python type checker) also doesn't support this pattern, which is good evidence that it's not common.

For now, I'm going to close this request. We can revisit this decision in the future if there are sufficient upvotes indicating that other users would find it useful as well.

**Comment by lmmarsano** [comment]
@erictraut Could the conditions for `T` in [the documented type guard](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards) `type(x) is T` be clarified?
I would have considered `type(x) is` _any-expression_ a special case of this supported type guard.
A type guard documented with similar language
> `isinstance(x, T)` (where T is a type or a tuple of types)

works when substituting `T = type(y)`, eg, this example passes type checks.
```python
class Test:
  def __init__(self, x: object):
    self.x = x

  def __eq__(self, other: object):
    return isinstance(other, type(self)) and self.x == other.x
```
It is, however, not as precise as `type(other) is type(self)` for defining equality.

**Comment by erictraut** [comment]
Type guards involve very specific pattern matching. In this case, `T` must refer to a class or a tuple of classes. It cannot be a dynamic expression that evaluates to a class.
