### ISSUE TITLE
T invariance for `def factory_to_instance(arg: ModelFactory[T]) -> T: ...` calls

### ISSUE THREAD

**Issue by Jaakkonen** [microsoft/pyright#2109]
**Describe the bug**
When you have code which calls a method with signature similar to `def factory_to_instance(arg: ModelFactory[T]) -> T: ...` with `T` that can be any of multiple types, pyright reports a problem that `T` in the signature is invariant.

**To Reproduce**
Here's a sample to reproduce the issue. 
```python
from typing import TypeVar, Generic, Union
from abc import ABC, abstractmethod
from dataclasses import dataclass

@dataclass
class MyFirstModel:
    foo: int
@dataclass
class MySecondModel:
    bar: int

T = TypeVar('T')
class AbstractModelFactory(ABC, Generic[T]):
    model: T
    errors: list[Exception]
    @abstractmethod
    def __init__(self):
        self.errors = []
    def is_valid(self) -> bool:
        return not self.errors
    def get_model(self) -> T:
        return self.model
class MyFirstModelFactory(AbstractModelFactory[MyFirstModel]):
    def __init__(self, data: dict):
        super().__init__()
        try:
            self.model = MyFirstModel(**data)
        except Exception as ex:
            self.errors.append(ex)
class MySecondModelFactory(AbstractModelFactory[MySecondModel]):
    def __init__(self, data: dict):
        super().__init__()
        try:
            self.model = MySecondModel(**data)
        except Exception as ex:
            self.errors.append(ex)

def model_from_parser(factory: AbstractModelFactory[T]) -> T:
    if not factory.is_valid():
        raise ValueError("Provided factory was given invalid data")
    return factory.get_model()

data = {"foo": 1}

factory: Union[MyFirstModelFactory, MySecondModelFactory]
if "foo" in data:
    factory = MyFirstModelFactory(data)
else:
    factory = MySecondModelFactory(data)

# mypy - Cannot infer type argument 1 of "model_from_parser"
# pyright - Argument of type "MyFirstModelFactory | MySecondModelFactory" cannot be assigned to parameter "factory" of type "AbstractModelFactory[T@model_from_parser]" in function "model_from_parser"
#  Type "MyFirstModelFactory | MySecondModelFactory" cannot be assigned to type "AbstractModelFactory[T@model_from_parser]"
#    TypeVar "T@AbstractModelFactory" is invariant
#      Type "MyFirstModel | MySecondModel" cannot be assigned to type "MyFirstModel"
#    TypeVar "T@AbstractModelFactory" is invariant
#      Type "MyFirstModel | MySecondModel" cannot be assigned to type "MySecondModel"
my_model = model_from_parser(factory)  # Type error, but code works fine
print(my_model)
```
The type of `my_model` is inferred correctly to `(variable) my_model: MyFirstModel | MySecondModel` but the call results in an interesting error with `T@AbstractModelFactory` being invariant.

**Expected behavior**
The signature to `model_from_parser` when called is not narrowed down to be invariant for `T`. The code above should give an error.

**Workaround**
```python
...
if isinstance(factory, MyFirstModelFactory):
    my_model = model_from_parser(factory)
elif isinstance(factory, MySecondModelFactory):
    my_model = model_from_parser(factory)
print(my_model)
```
Here it seems that the type signatures for these specific calls are evaluated to be different and the invariance in the argument type doesn't matter because the argument type has been narrowed down to an invariant type.

**VS Code extension or command-line**
VS Code extension version 1.1.157.

**Comment by erictraut** [comment]
Pyright is doing the right thing in this case. Mypy (another Python type checker) gives a similar warning in the same location.

The type of `factory` is `MyFirstModel | MySecondModel`. You are trying to assign this to a parameter of type `AbstractModelFactory[T]`, and `T` is invariant. `MyFirstModel` derives from `AbstractModelFactory[MyFirstModel]`, and `MySecondModel` derives from `AbstractModelFactory[MySecondModel]`. There's no solution for `T` that is invariant in this case. `T` would have to be both `MyFirstModel` and `MySecondModel`, so the constraint cannot be met.

If you change `T` to be covariant, the code will type check without errors in both pyright and mypy.

```python
T = TypeVar("T", covariant=True)
```

**Comment by Jaakkonen** [comment]
You're right, it seems I somehow had a situation where just using `covariant=True` didn't work due to other problems. Closing this issue.
