### ISSUE TITLE
Detect and warn about missing match arms in if/elif chains or (Py>=3.10) match statements

### ISSUE THREAD

**Issue by Ran4** [microsoft/pyright#2112]
I often find myself writing code like this:

```python
from enum import Enum, auto


class CupSize(Enum):
    Small = auto()
    Medium = auto()
    Large = auto()
    Gigantic = auto()  # <- this was newly added


# ... in a completely different place:


def cup_size_display(cup_size: CupSize) -> str:
    if cup_size is CupSize.Small:
        return "Regular"

    elif cup_size is CupSize.Medium:
        return "Regular+"

    elif cup_size is CupSize.Large:
        return "The big one"
    # problem! we didn't handle the `Gigantic` case


print(cup_size_display(CupSize.Gigantic))
```

That is, you add something to an enum but you forgot to handle it everywhere.

The way I typically solve it is by writing the function like this:

```python
def cup_size_display(cup_size: CupSize) -> str:
    if cup_size is CupSize.Small:
        return "Regular"

    elif cup_size is CupSize.Medium:
        return "Regular+"

    elif cup_size is CupSize.Large:
        return "The big one"

    else:
        raise ValueError(f"Unhandled match arm {cup_size}")
```

This does help me find bugs and the error message makes it obvious what needs to be updated,
but this obviously only works if I run the code - and sometimes that won't happen until it's in production, as opposed to while I'm developing.

Is there any way to make PyRight detect this type of "problem" right now, or are there any plans to do so in the future?

I think this would be a super useful feature that lots of developers would use to find bugs in their code, but I will also admit that I'm
not sure how to properly detect that someone "just" missed the final case.

Obviously there's the match type that will show up in 3.10, but it doesn't solve the problem (since
it has the same behaviour - omitting the final arm will just lead to doing nothing, ultimately leading to
the function returning None in the first case shown above).

**Comment by erictraut** [comment]
Pyright already handles this. The sample you provided above generates an error:
```
Function with declared type of "str" must return value
  Type "None" cannot be assigned to type "str"
```

This error goes away if you add the missing `elif` check.

For more details about this feature, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#narrowing-for-implied-else).
