### ISSUE TITLE
Deferring resolution of ParamSpec in certain situations.

### ISSUE THREAD

**Issue by bijij** [microsoft/pyright#2116]
I'm not sure if this would be called a bug or just out of the scope of what Pyright is willing to do, seems fairly niche so I've written this as a feature request.

**Is your feature request related to a problem? Please describe.**

I recently encountered a scenario where a `ParamSpec` would fail to be bound when multiple different `ParamSpec` are used in a nested `Callable` using `Concatenate` (#2097).

This issue was resolved in a timely fashion, (Thank you Eric) however I have a question about whether this can be extended to support leaving the `ParamSpec` unbound in certain situations? 

**Describe the solution you'd like**

Consider the following python code:

```py
from typing import Callable, Generic, TypeVar
from typing_extensions import Concatenate, ParamSpec

P = ParamSpec("P")
Q = ParamSpec("Q")

T = TypeVar("T")
U = TypeVar("U")


class Foo(Generic[P, T, Q, U]):
    ...


def foo(func: Callable[Concatenate[Callable[P, T], Q], Callable[P, U]]) -> Foo[P, T, Q, U]:
    ...


reveal_type(Foo)
reveal_type(foo)


@foo
def bar(func: Callable[[int], str], a: float) -> Callable[[int], bool]:
    ...


reveal_type(bar)


@foo
def baz(func: Callable[P, str], a: float) -> Callable[P, bool]:
    ...


reveal_type(baz)


@foo
def qux(func: Callable[Concatenate[int, P], str], a: float) -> Callable[P, bool]:
    ...


reveal_type(qux)


```
![image](https://user-images.githubusercontent.com/8677174/126891276-eeb9b481-f95e-44cf-b712-d7594fbeb574.png)

Notice `bar` works flawlessly, and is essentially the example case I laid out in my previous issue.

However when `baz` is decorated by `foo` the output becomes `Foo[(), str, (a: float), bool]` i was woundering if this could instead be `Foo[P@baz, str, (a: float), bool]` with the `P` to be resolved by functions decorated by `baz` in this case, any function which returns a `str` would be valid.

Consequently, the example `qux` fails to type check seemingly because `P` is resolved to `()` beforehand?

**Additional context**
Just for the record this is using pyright 1.1.158.

Output if you're interested:
```
test.py
  test.py:19:13 - info: Type of "Foo" is "Type[Foo[Unknown, Unknown, Unknown, Unknown]]"
  test.py:20:13 - info: Type of "foo" is "(func: Callable[Concatenate[Callable[P@foo, T@foo], Q@foo], Callable[P@foo, U@foo]]) -> Foo[P@foo, T@foo, Q@foo, U@foo]"
  test.py:28:13 - info: Type of "bar" is "Foo[(_p0: int), str, (a: float), bool]"
  test.py:36:13 - info: Type of "baz" is "Foo[(), str, (a: float), bool]"
  test.py:39:2 - error: Argument of type "(func: Callable[Concatenate[int, P@qux], str], a: float) -> Callable[P@qux, bool]" cannot be assigned to parameter "func" of type "Callable[Concatenate[Callable[P@foo, T@foo], Q@foo], Callable[P@foo, U@foo]]" in function "foo"
    Type "(func: Callable[Concatenate[int, P@qux], str], a: float) -> Callable[P@qux, bool]" cannot be assigned to type "Callable[Concatenate[Callable[P@foo, T@foo], Q@foo], Callable[P@foo, U@foo]]"
      Parameter 1: type "Callable[P@foo, T@foo]" cannot be assigned to type "Callable[Concatenate[int, P@qux], str]"
        Type "() -> str" cannot be assigned to type "Callable[Concatenate[int, P@qux], str]"
          Function accepts too many positional parameters; expected 0 but received 1 (reportGeneralTypeIssues)
  test.py:44:13 - info: Type of "qux" is "Foo[(), str, (a: float), bool]"
```

I had hoped to use something like this in library code to programatically generate decorator functions which can be called with or withouth parentheses similar to `@dataclass` essentially a decorator used to decorate decorators.
`ParamSpec` and pyright are so close to getting me the ability to type-hint it the way I want. 

Thanks for your help.

**Comment by erictraut** [comment]
Pyright already supports deferral of ParamSpec matching, but it doesn't support deferral of Concatenate. That would add significantly more complexity. I don't think we'd be interested in adding this support unless/until we get signal from more users that it's important. Mypy doesn't support even basic ParamSpec deferral. I don't think that PEP 612 anticipated this usage. 

We will revisit this if we receive more upvotes or comments in the future, but for now I'm going to close this feature request.
