### ISSUE TITLE
Types unkown for certain vars despite being explicitly typed inline

### ISSUE THREAD

**Issue by Daggy1234** [microsoft/pyright#2118]
**Describe the bug**

I keep getting an error `app/app.py:25:1 - error: Type unknown for variable "app.app.asgi_app"`. This happens for a bunch of variables defined with explicit types.

```
app.app.app
  app/app.py:24:1 - error: Type unknown for variable "app.app.app"
app.app.asgi_app
  app/app.py:25:1 - error: Type unknown for variable "app.app.asgi_app"
app.routes.image_routes.router
  app/routes/image_routes.py:17:1 - error: Type unknown for variable "app.routes.image_routes.router"
.Message
  error: Type of metaclass unknown
  error: Type of base class unknown
app.routes.special_routes.router
  app/routes/special_routes.py:6:1 - error: Type unknown for variable "app.routes.special_routes.router"
```

**To Reproduce**

I couldn't reproduce for a smaller file so I'll just link relevant file and line. 

https://github.com/Daggy1234/dagpi-image/blob/main/app/app.py#L24

```py
app: FastAPI = FastAPI(docs_url=None, redoc_url=None)
```

https://github.com/Daggy1234/dagpi-image/blob/main/app/app.py#L25

```py
asgi_app: SentryAsgiMiddleware = SentryAsgiMiddleware(app)
```

https://github.com/Daggy1234/dagpi-image/blob/main/app/routes/image_routes.py#L17

```py
router: APIRouter = APIRouter()
```

https://github.com/Daggy1234/dagpi-image/blob/main/app/routes/special_routes.py#L6

```py
router: APIRouter = APIRouter()
```

I get this error

**Expected behavior**

I would expect the types to be known

**Screenshots or Code**

https://github.com/Daggy1234/dagpi-image/runs/3098336475 the Typechecking action.

**VS Code extension or command-line**

command-line

**Additional context**

I can reproduce locally

**Comment by erictraut** [comment]
I tried to repro with just the lines you mentioned, but I'm not seeing the error you're reporting. 

Which version of fastapi are you using? It looks from your requirements.txt that you're using 0.65.1. I tried that, and it worked for me. If you're using an older version that doesn't properly or completely annotate these symbols, that would explain what you're seeing.

If you can repro this with a smaller, self-contained file and more detailed repro steps, I'd be happy to take a look at it.

**Comment by Daggy1234** [comment]
Sure lemme try that!

**Comment by erictraut** [comment]
I cloned your repo, and I'm still not able to repro the problem. I'm going to close the issue. If you're able to provide repro steps, I'm happy to re-open and take another look.

**Comment by Daggy1234** [comment]
Hey eric sorry for the delay, school and life!

so I made an extremely simple minimal reproducible example 

https://github.com/Daggy1234/MinRepFastApi

Which contains just the `__init__`, the py.typed and the website.py file.

As mentioned the issue involves github actions. 

```sh

Run pyright --lib --verifytypes website --ignoreexternal
  pyright --lib --verifytypes website --ignoreexternal
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.11/x64
    VENV: .venv/bin/activate
Package name: "website"
Package directory: "website"
Path of py.typed file: "website/py.typed"

Public modules: 2
   website
   website.website

Symbols used in public interface:
website.website.website
  website/website.py:3:1 - error: Type unknown for variable "website.website.website"

Symbols exported by "website": 2
  With known type: 1
  With partially unknown type: 1
    (Ignoring unknown types imported from other packages)
  Functions without docstring: 0
  Functions without default param: 0
  Classes without docstring: 0

Other symbols referenced but not exported by "website": 0
  With known type: 0
  With partially unknown type: 0

Type completeness score: 50%

Completed in 0.547sec
```

Ths issue stems from there. Latest fastapi version as well!

**Comment by erictraut** [comment]
It looks like you're using the `--verifytypes` option in pyright. This option is meant to validate type completeness for py.typed libraries that are published for the consumption of others. It's not meant to be used for normal (non-library) code bases, since those are not imported by others. Are you publishing a library in this case? Or are you simply trying to do type checking on your code base? If it's the latter, then you should remove the `--verifytypes` option from the command line.

**Comment by Daggy1234** [comment]
okay sure lemme try with that flag removed
