### ISSUE TITLE
Support Code Formating

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#213]
Since we have #206 (command for import reordering), I think formating should also be considered.

Specifically, make pyright the formatter of python files so that we can use VSCode's `Format Document` command and `Format on save` functionality. 

We can use formatters like [autopep8](https://github.com/hhatto/autopep8).

**Comment by erictraut** [comment]
This veers into linting functionality (style enforcement), which I've tried to avoid. The only reason I'm thinking about including import reordering is because that logic will be needed for auto import insertion.

**Comment by erictraut** [comment]
The standard Python extension for VS Code already has support for pylon and (IIRC autopep8). Pyright and the standard Python extension will soon play together much better once [this PR](https://github.com/microsoft/vscode-python/pull/7011) is merged into the Python extension code.

**Comment by giyyapan** [comment]
Good to hear that!

**Comment by antoine1fr** [comment]
Sorry to comment an old feature request but to me, Pyright should be language-client agnostic and not assume end users only use VS Code. This feature would be beneficial to any language-client.

**Comment by gcanoxl** [comment]
agree with @antoine1fr

**Comment by erictraut** [comment]
@adonig, you can use the Microsoft Python extension in conjunction with the Pyright extension. In this configuration, the Pyright extension acts as its own language server; it's not managed or loaded by the Python extension. So you need to configure the "python.languageServer" to be "None". This tells the Python Extension that it shouldn't load any language server.

**Comment by erictraut** [comment]
If you think you are hitting a bug, please open a new bug report with repro steps.

**Comment by adonig** [comment]
@erictraut Thank you. I opened a bug report [here](https://github.com/microsoft/pyright/issues/4337).
