### ISSUE TITLE
Python Notebook Support

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#2143]
**Is your feature request related to a problem? Please describe.**
Running pyright cli on a .ipynb file fails as it doesn't find any source files. I'm guessing it's hard coded to only look for .py files.  This fails even when I give exact filename like this error message,

`Loading configuration file at /Users/mdrissi/Snapchat/Dev/training-platform/pyrightconfig.json
Assuming Python platform Darwin
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding .git
Searching for source files
File or directory "/Users/mdrissi/Snapchat/Dev/training-platform/barista/notebooks/Ad-Ranking Submitted Workflow API.ipynb" does not exist.
No source files found.
Completed in 0.309sec`

I can see that pylance works in python notebooks so unsure how it does it. Motivation for this feature is for CI jobs to check python notebook files with pyright.

**Describe the solution you'd like**
Support for pyright on non .py files and understanding of notebook file format in some way usable by CI script.

**Additional context**
This is low bonus for me. I checked and mypy does support notebooks, but even if they both didn't I could just push team members to keep most of there logic in .py and have notebook be simple script that builds on those utilities. My current team only checks in a couple notebooks and most notebooks stay local. For teams that check in a lot of notebooks (some data analysis) this would be pretty handy.

**Comment by erictraut** [comment]
Pyright is focused on type annotations and static type checking. Do you use type annotations within your notebooks?

As you mentioned, pylance (which builds upon pyright and is focused more on interactive features like completion suggestions), does support notebooks within VS Code.

It looks like jupyter offers a command-line tool to convert a notebook to a Python script.

> jupyter nbconvert --to script [YOUR_NOTEBOOK].ipynb

I think that would give you everything you need to write a CI script that works with pyright.

**Comment by hmc-cs-mdrissi** [comment]
Yes type annotations are recommended in notebooks for my team. We don't enforce an IDE across the team though so all type checks need to be CI doable. The python style guide my team uses doesn't distinguish notebooks vs .py files (beyond tooling workarounds).  `nbconvert --to script ` looks like it will cover my use case well. 

I'll go ahead and close the issue.
