### ISSUE TITLE
Type guard "x is None or isinstance(x, T)" narrows type to T

### ISSUE THREAD

**Issue by ethframe** [microsoft/pyright#2144]
**Describe the bug**
Type guard `x is None or isinstance(x, T)` narrows type to `T` instead of `Optional[T]`.

**To Reproduce**

The following code passes pyright's checks, but fails with a `TypeError` at runtime:

```python
def a(x: object) -> int:
    if x is None or isinstance(x, int):
        return x
    return 0


a(None) + 1
```

**Expected behavior**

```
error: Expression of type "int | None" cannot be assigned to return type "int"
```

**VS Code extension or command-line**
pyright 1.1.159

**Comment by erictraut** [comment]
This is fixed in pyright 1.1.160, which I just published. It will also be included in the next release of pylance.
