### ISSUE TITLE
Alias declaration in `from .x import *` has blank symbol name

### ISSUE THREAD

**Issue by mewil** [microsoft/pyright#2149]
**Describe the bug**
Based on the comment for `symbolName` in `AliasDeclaration` (copied below), I would expect `x` to appear as the `symbolName` for the module alias declaration resulting from `from .x import *`, but it is `undefined`.

```javascript
// The name of the symbol being imported (used for "from X import Y"
// statements, not applicable to "import X" statements).
symbolName?: string | undefined;
```

**To Reproduce**
File `__init__.py`:
```python
from .x import *

def foo():
   x.bar()
```
File `x.py`:
```python
def bar():
   pass
```

**Expected behavior**
Given my limited understanding of the Python import system and based [this quote](https://github.com/microsoft/pyright/issues/2140#issuecomment-892272399) (copied below) from #2140, there should be a local symbol `x`. Should the `symbolName` of the alias declaration therefore be `x`?

Apologies if this is due to a lack of understanding on my end.

> The statement from .ambiguous import foo assigns a value to the local symbol foo and (implicitly) assigns to the local symbol ambiguous. Relative imports have this implicit behavior.

**VS Code extension or command-line**

I tested this locally using a slightly modified (added logging only) version of the CLI with the commit `dfb796d84c4982f3d11f13ea5615d73d9e62b533`

**Comment by erictraut** [comment]
The `symbolName` field is an internal implementation detail of pyright. Are you seeing incorrect behavior (a false positive or false negative error, for example)? I guess I'm not sure what problem you're reporting here.

**Comment by mewil** [comment]
So I'm running a slightly modified version of Pyright, where one of the primary changes serializes a list of module nodes to JSON (which includes internal implementation details such as `symbolName`) and doing some analysis on the result.

This issue is therefore a question about the `symbolName` field in the case of the example I shared above. Given the comment indicates that `symbolName` will be defined for imports of the form `from X import Y`, is this case an exception to that comment or should `symbolName` be populated? I hope that makes a bit more sense.

**Comment by erictraut** [comment]
If you look in binder.ts and search for "wildcardNames.forEach", you'll see where these alias declarations are built. There are legitimate cases where the symbolName may be left unpopulated.
