### ISSUE TITLE
Support symbol renaming (editor.action.rename)

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#215]
VSCode has a symbol renaming command called "editor.action.rename" (default shortcut is "f2"). 

It's extremely useful, please support.

Thanks!

![image](https://user-images.githubusercontent.com/3479453/63420753-f5f27b80-c439-11e9-96b9-e2f203e9b091.png)
_Pressing "f2" on a variable in a TypeScript file triggers the rename code action_

**Comment by erictraut** [comment]
Thanks for the suggestion. I've implemented this functionality, and it will be included in the next release.

**Comment by erictraut** [comment]
This is implemented in 1.0.57, which I just published. Please give it a try and let me know what you think.

**Comment by giyyapan** [comment]
Just tried, works like a charm!
Many thanks!
