### ISSUE TITLE
Should not report "is not accessed" warning in '__init__.py' files

### ISSUE THREAD

**Issue by mangelozzi** [microsoft/pyright#2153]
**Describe the bug**
Should not report `is not accessed` warning in `__init__.py` files. It is pythonic to import various objects within the package to make them available directly from the packge.

**To Reproduce**
Create a package dir. Inside the dir place a `__init__.py` file. Within the init file import some objects from the package.

**Expected behavior**
Should not given a warning

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/19764314/128336504-fb5a3f82-06e4-435b-a0f5-b0e97ab70bc3.png)

**Comment by erictraut** [comment]
If your intent is to re-export a symbol from your module, you should follow the convention documented in PEP 484 and in [this guidance](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface). Re-exports are indicated through the use of `__all__` or by using a redundant form of import statements.
