### ISSUE TITLE
How to attach an attribute to event loop without pyright complaining?

### ISSUE THREAD

**Issue by MapleCCC** [microsoft/pyright#2158]
This is not a bug report, but a request for help on properly using Pyright.

Sorry for the lengthy background text. You don't really have to understand the background to examine the problem. I only include the background here for context. Feel free to skip them. 

<details>
<summary>Background context</summary>
 
The library `aiohttp` <a href="https://docs.aiohttp.org/en/stable/faq.html#why-is-creating-a-clientsession-outside-of-an-event-loop-dangerous">requires</a> that a `ClientSession` instance not created outside an event loop, and the life-cycle of a `ClientSession` instance shorter than the life-cycle of the event loop within which it's created. I don't want to pass the `ClientSession` instance around everywhere which is ugly and tedious. The most elegant way I come up with is to attach the `ClientSession` instance to the event loop itself. This approach is very similar to CPython developers' decision to remove the `loop` parameters in many asyncio-related stdlib functions, and instead make them use the `get_running_loop()` function to acquire the loop. I apply similar reasoning here and write a `get_running_client_session()` function.

</details>

I write a `get_running_client_session()` function which attaches a `ClientSession` instance to the event loop:

```python
import asyncio
from aiohttp import ClientSession

def get_running_client_session() -> ClientSession:
    loop = asyncio.get_running_loop()

    try:
        return loop._client_session

    except AttributeError:
        session = ClientSession()
        loop._client_session = session
        # Omitted code to make sure the session is closed when the loop is about to close
        return session
```

Pyright complains: `Cannot access member "_client_session" for type "AbstractEventLoop". Member "_client_session" is unknown`.

What can we do to make Pyright happy? Thanks in advance for any advise.

**Comment by erictraut** [comment]
You're modifying the internals of the event loop object in a way that is not safe. What if its implementation happens to have an internal private field named `_client_session`? Your code would overwrite this field! Even if it's safe with today's implementation, the implementation could change in the future. So this approach is fragile.

Are you instantiating the event loop object, or is it being instantiated by some code that's not under your control? If you're instantiating it, you could create your own subclass of `AbstractEventLoop` that has a defined attribute or property that allows you to store the associated session in a safe manner.

Another approach is to maintain a separate mapping between event loops and sessions.

If you want to stick with your current solution, then you could just cast `loop` to `Any` before modifying it.

**Comment by MapleCCC** [comment]
@erictraut Thank you for your kind reply. You are right that tampering with the internal of the event loop is not safe and should be discouraged.

Subclassing `AbstractEventLoop` would be too heavy a solution for me. Instead, I tried the mapping approach you suggested, and it worked perfectly!

Thank you for your help! It really solves my problem and helps me make my code safer and cleaner. I will close this issue then.
