### ISSUE TITLE
Structural typing / intersection types

### ISSUE THREAD

**Issue by Wenzil** [microsoft/pyright#2170]
**Is your feature request related to a problem? Please describe.**
It is difficult to express structural typing in type hints. It would be nice to be able to define intersection types, similar to [TypeScript intersection types](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#intersection-types).

**Example usage**

```py
class User(TypedDict):
    """Representation of a user"""
    Username: str

class UserPermission(TypedDict):
    """Access level granted to a user on a resource"""
    AccessLevel: str
    ResourceId: str

class WithUserPermissions(TypedDict):
    """A collection of user permissions"""
    Permissions: List[UserPermission]

def get_user_summary(username: str) -> User: ...
    """Retrieve summary of an existing user. Don't include permissions information"""

def get_user_details(username: str) -> User & WithUserPermissions: ...
    """Retrieve an existing user. Include permissions information"""

alice_summary = get_user_summary('alice')
alice_summary['Username'] # Valid
alice_summary['Permissions'] # Error

alice_details = get_user_details('alice')
alice_details['Username'] # Valid
alice_details['Permissions'][0]['ResourceId'] # Valid
```

**Additional context**
If there is a PEP issue tracker this request belongs to, please feel free to point me to it

**Comment by erictraut** [comment]
Yeah, the current Python typing spec doesn't provide any accommodation for intersection types. This would need to be pursued through the standardization process. This normally starts with a discussion in the [Python typing-sig forum](https://mail.python.org/archives/list/typing-sig@python.org/). If you can get support in that forum, then you (or someone else) could proceed to write a draft PEP.

**Comment by erictraut** [comment]
I'm going to close this issue since it's not really a pyright issue. It's a Python type standard issue, and pyright doesn't generally include type features if they are not part of the standard.
