### ISSUE TITLE
"Treat warnings as errors" flag

### ISSUE THREAD

**Issue by WasabiFan** [microsoft/pyright#2180]
**Is your feature request related to a problem? Please describe.**

I would like for some rules to be reported as warnings in local development but fail my CI pipeline. Right now, it seems like postprocessing pyright's output is the only way to achieve this.

Overriding the severity settings for Pylance would likely solve this problem for vscode users, but not for the command-line. And would introduce maintenance overhead in ensuring the vscode settings and the `pyproject.toml` match.

I don't currently see a way to do this, but I might be missing something.

**Describe the solution you'd like**

A command-line flag which, when supplied, would return error status if any warnings are identified.

**Comment by erictraut** [comment]
You can specify the severity of each diagnostic category in the pyrightconfig.json or pyproject.toml file. If you want different settings locally versus in CI, you can create multiple pyrightconfig.json files and use the "-p" option to point to the one you want to use for CI. 

You can use the same approach if you want to apply different diagnostic severities for different parts of your source tree. The [typeshed github](https://github.com/python/typeshed) repo uses this strategy, for example. You can see that they have a "pyrightconfig.json" and a "pyrightconfig.stricter.json" file at the top level of the repo.

**Comment by WasabiFan** [comment]
Thanks for the reply. Multiple/dynamic config files _are_ a workable solution to this problem.

In this case, I think this has similar shortcomings to putting that configuration in the vscode `settings.json`: using a separate configuration file duplicates other settings and requires manual maintenance. I have configuration which sets half a dozen other settings, and would need to duplicate them in each configuration.

The specific reason I think this type of option (treating warnings as errors) is worth handing "specially" over other potential options is that some rules come set to "warning" by default. To set up a system as described, the user would need to identify all rules which default to "warning" and override them to "error". So it's less clear or maintainable than a straight copy of your existing file which might just specify defaulting to the "basic" rules.

The typeshed example shows these effects; both files have copies of the same other settings, and the files are huge because they've had to identify and specify most/all options.

I _do_ think there's potentially a more general ergonomic improvement to be had here: allow multiple `-p` flags (or otherwise, a list of configs) -- merge them in a prescribed order. That would improve the general case here. For my particular scenario, a new normal configuration parameter for "treat warnings as errors" would then completely cover the need.

**Comment by erictraut** [comment]
Another solution you might want to consider is to invoke the pyright CLI with "--outputjson" flag. Your CI script can then use the JSON output to easily determine whether it should fail or succeed, and you can base this on whatever rules you would like to apply. In your case, that would be the presence of a warning diagnostic.

**Comment by erictraut** [comment]
Out of curiosity, why do you want to local diagnostics to be different from your CI results? Most people want those to be completely identical.

**Comment by WasabiFan** [comment]
> Another solution you might want to consider is to invoke the pyright CLI with "--outputjson" flag.

This is fair, and a good option. Right now I think I'm going to go with a  "grep for the '0 warnings, 0 errors' output line" approach, which is I guess the lower-tech equivalent. But this is good to keep in mind.

> Out of curiosity, why do you want to local diagnostics to be different from your CI results? Most people want those to be completely identical.

Good question and worth thinking through.

Some of the rules that Pyright supports I consider true errors -- they should be a sign that your code _does not work_, and ought to be fixed in development immediately. There is another class of errors which I don't want to make it into my `main` branch but am not worried about intermittently, or even for reviewability, such as `reportUnusedImport`. I _don't_ want unused imports to stick around, but I also would find it annoying if this were treated as an error -- especially in vscode, where it is indistinguishable from an unresolved import at a glance. So I want to be able to classify some rule failures as actual problems, and others as quality gates, with the intent to enforce both in the end but identify the difference to the end user.
