### ISSUE TITLE
Diagnostics are not reported correctly for untitled files

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#2182]
When using the pyright VS Code extension, you can designate an untitled file to be a python source file. Pyright doesn't properly handle this case because it assumes all files are on disk and use the "file" URI scheme.

**Comment by jakebailey** [comment]
We have a temporary fix for this in progress for Pylance (remembering the mapping for opened files), as we need this for the browser (which uses multiple different kinds of schemas for various opened files).

![image](https://user-images.githubusercontent.com/5341706/129394364-71aba210-154a-4a74-b465-8e3b857fe0a7.png)

![image](https://user-images.githubusercontent.com/5341706/129394376-11bc3946-da6b-4b48-ac6d-0e96778966ca.png)


The long term solution is to use URIs everywhere, but that is a larger refactor.

**Comment by erictraut** [comment]
Yesterday I investigated fixing this "the correct way", but as you suggested, it's a big change with high risk of regression. I like the approach you're taking with the temporary fix. It's much more contained.

**Comment by jakebailey** [comment]
Yes, though does have a risk of path aliasing. Thankfully, people don't tend to open files at their FS root at the same time as untitled files, or mix random VFSs together (if they even have access to them when `file://` is also available), so it should be stable for now.

**Comment by jakebailey** [comment]
Fixed in https://github.com/microsoft/pyright/commit/7f30794f53adf8452642bedc28e89926861dde05.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.162, which I just published. It will also be in the next release of pylance.
