### ISSUE TITLE
Option to require comparison operands to have overlapping types

### ISSUE THREAD

**Issue by jtlapp** [microsoft/pyright#2185]
# The problem

(I originally introduced this problem in #2184 as an aside to a different feature request.)

I am frequently forgetting to append parentheses to function calls that I put in conditional comparisons, and pyright never catches it. I have to trace these bugs down at runtime.

For example, I write this: ```if table.get_value == "abc"```
When I mean this: ```if table.get_value() == "abc"```

(EDIT: I removed the `x == None` example, because what I do is `x is None` as in standard Python, but it's not clear to me that this feature applies to the `is` operator. I do have a similar problem with that, though.)

In the original thread, @erictraut explained that a proper solution "would probably require us to hard-code a bunch of knowledge about many stdlib type semantics — something we're very reluctant to do. From a type perspective, the expression table.find_value == "x" is fine because the __eq__ operator is typed to accept any object as an input parameter."

# A Solution

What about adding a configuration option that requires the operands of comparison operators be able to assume the same type, according to the type hints? For example, when comparing operands that are each a union of multiple types, the type check would pass if at least one type in the union of one operand is identical to at least one type in the union of the other operand, and it would fail otherwise.

This would make the behavior more like that of a statically-typed language. If the comparison operator can support comparing different types, we can cast one (or both) of the operands to `Any` to bypass the restriction. I actually *want* to have to do this explicitly to confirm that it is intended. I'm fine with having to convert `float`s and `int`s if necessary; we do this all the time in statically-typed languages, and it's sometimes good to get a warning when we're mixing them.

This would give the most common situation its expected type checking and force us to explicitly assert when we mean to allow arbitrary comparisons.

I realize that this is entirely non-standard Python coding practice. But it *is* entirely standard coding practice in statically-typed languages (except when overloading operators). I am not alone in having shunned Python for the lack of static type-checking; it's features like this that can draw fans of statically-typed languages to Python.

# Static Type-Checking Mode

This is the third feature I've proposed that brings Python more into alignment with statically-typed languages, beyond what the strict type-checking mode allows. You could create an additional mode for folks like me who want to use Python like a statically-typed language, and this mode could have the following features (and counting):

- Option to require comparison operands to have overlapping types (the present feature)
- #2184
- #1924

**Comment by erictraut** [comment]
I understand the motivation here, but I think this takes things really far outside of standard Python practices. This would probably appeal to very few Python users and wouldn't be applicable for most Python code bases.

I'm going to close this request, but we do revisit requests like this periodically if they receive enough upvotes (thumbs up) signaling that there is wider support and demand for a feature.

**Comment by jtlapp** [comment]
Yeah, I know. I'm trying to make it possible for me to stay with Python, but I'd be hosed the moment I need to collaborate with others. I'll finish my program and get out of your hair. Thanks for all your help!
