### ISSUE TITLE
Message : Stub file not found for "google.cloud"

### ISSUE THREAD

**Issue by sylvainmouquet** [microsoft/pyright#2186]
Hello,

Could you explain why this error occurs? i have this code : 
`from google.cloud import tasks_v2
`

Thanks
Sylvain

**Comment by erictraut** [comment]
First, I presume that you have the `reportMissingTypeStubs` diagnostic check enabled. That check emits an error when a type stub (or a py.typed library with inlined types) cannot be found for an import.

Do you have type stubs installed for this library? If not, that would explain the message.

**Comment by erictraut** [comment]
I'm going to close this issue. Happy to re-open it if you think that you've identified a bug.
