### ISSUE TITLE
Narrowing incorrect when using any and equality against a literal

### ISSUE THREAD

**Issue by danr** [microsoft/pyright#2205]
When using the function `any` and equality against a literal narrowing is incorrect.

**To Reproduce** 
Save this to `narrow.py`:
```python
def f(i: int, b: bool):
    if any([i == 0 and b, i == 1]):
        pass
```
Run `pyright narrow.py`:
```
  /home/dan/narrow.py:2:27 - error: Condition will always evaluate to False since the types 
"Literal[0]" and "Literal[1]" have no overlap (reportUnnecessaryComparison)
```

Steps to reproduce the behavior.

**Expected behavior**
No error to be reported since the code is (at least morally) equivalent to 
```python
def f(i: int, b: bool):
    if i == 0 and b or i == 1:
        pass
```

**Comment by erictraut** [comment]
This is included in Pyright 1.1.163, which I just published. It will also be in the next release of Pylance.
