### ISSUE TITLE
Support narrowing based on a type guard assigned to a Final variable

### ISSUE THREAD

**Issue by jack1142** [microsoft/pyright#2212]
**Is your feature request related to a problem? Please describe.**
```py
from typing import Any, Final, Union, final
from typing_extensions import TypeGuard

@final
class X:
    ...

@final
class Y:
    ...

def is_x(obj: Any) -> TypeGuard[X]:
    return isinstance(obj, X)

def foo(obj: Union[X, Y]) -> None:
    t: Final = type(obj)
    if t is X:
        reveal_type(obj)
    else:
        reveal_type(obj)

def bar(obj: Union[X, Y]) -> None:
    t: Final = isinstance(obj, X)
    if t:
        reveal_type(obj)
    else:
        reveal_type(obj)

def baz(obj: Union[X, Y]) -> None:
    t: Final = is_x(obj)
    if t:
        reveal_type(obj)
    else:
        reveal_type(obj)
```
Currently this returns:
```
type_narrowing.py:18:21 - info: Type of "obj" is "X | Y"
type_narrowing.py:20:21 - info: Type of "obj" is "X | Y"
type_narrowing.py:25:21 - info: Type of "obj" is "X | Y"
type_narrowing.py:27:21 - info: Type of "obj" is "X | Y"
type_narrowing.py:32:21 - info: Type of "obj" is "X | Y"
type_narrowing.py:34:21 - info: Type of "obj" is "X | Y"
```

**Describe the solution you'd like**
I would want this to return the same thing that would be returned for this code:
```py
from typing import Any, Final, Union, final
from typing_extensions import TypeGuard

@final
class X:
    ...

@final
class Y:
    ...

def is_x(obj: Any) -> TypeGuard[X]:
    return isinstance(obj, X)

def foo(obj: Union[X, Y]) -> None:
    if type(obj) is X:
        reveal_type(obj)
    else:
        reveal_type(obj)

def bar(obj: Union[X, Y]) -> None:
    if isinstance(obj, X):
        reveal_type(obj)
    else:
        reveal_type(obj)

def baz(obj: Union[X, Y]) -> None:
    if is_x(obj):
        reveal_type(obj)
    else:
        reveal_type(obj)
```
Which would be this:
```py
type_narrowing.py:17:21 - info: Type of "obj" is "X"
type_narrowing.py:19:21 - info: Type of "obj" is "Y"
type_narrowing.py:23:21 - info: Type of "obj" is "X"
type_narrowing.py:25:21 - info: Type of "obj" is "Y"
type_narrowing.py:29:21 - info: Type of "obj" is "X"
type_narrowing.py:31:21 - info: Type of "obj" is "X | Y"
```

**Additional context**
Similar issue on mypy: https://github.com/python/mypy/issues/6670

**Comment by erictraut** [comment]
In the top code sample, the conditional check uses the expression `t`, but you are suggesting that the type of the expression `obj` should be narrowed. That's not how pyright's type narrowing logic works. Type narrowing is applied to expressions that appear within the conditional expression. I don't know if any static type checker in any language that tracks relationships between expressions to support the behavior you're proposing. Not even TypeScript does this.

What you're suggesting is technically type safe, but only in the specific case where all of the types are `@final` and the variable itself is `@Final`. That's such a narrow use case. I wouldn't be able to justify the significant complexity and performance overhead that this change would involve.

**Comment by jack1142** [comment]
> What you're suggesting is technically type safe, but only in the specific case where all of the types are `@final` and the variable itself is `@Final`.

Why would it not be type-safe if the types were not `@final`? Variable does have to be `@Final` so that it isn't modified indeed but I don't think the types need to be `@final` as well?
It wouldn't be that narrow of a use case if all it required is annotating the variable as `@Final` which seemed like enough to me for it to be type-safe.

**Comment by erictraut** [comment]
Yeah, it would still be a narrow use case. The use of `Final` annotations is very rare to begin with.

Here's a complete list of the type narrowing patterns that we support currently: https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards. This includes more cases than any other Python type checker. Each type narrowing pattern requires custom logic and tends to add complexity and performance overhead during analysis, so we maintain a high bar for which ones to add. Your proposed feature would require not just a new pattern but a significant new infrastructure for tracking dependencies between different expressions. 

We might revisit this in the future if we get significant signal from other users that this is a feature they want to see, but for now I'm going to close this enhancement request.
