### ISSUE TITLE
Iterable[str] | Iterable[bytes] cannot be assigned to Iterable[AnyStr]

### ISSUE THREAD

**Issue by Kache** [microsoft/pyright#2221]
**Describe the bug**
(source pasted below)

`foo(bar(s))` type-errors with:

> Argument of type "Iterable[str] | Iterable[bytes]" cannot be assigned to parameter "i" of type "Iterable[AnyStr@foo]" in function "foo"

Originally posted as a [SO question](https://stackoverflow.com/questions/68869110/python-static-type-hint-check-mismatch-between-iterableanystr-vs-iterablestr), but perhaps it's a bug?

**To Reproduce**
Save code to file, then `pyright foo.py`

**Expected behavior**
Expected `Iterable[str] | Iterable[bytes]` to be assignable to `Iterable[AnyStr]` and vice-versa.

**Screenshots or Code**
```py
from __future__ import annotations
from typing import AnyStr, Iterable


def foo(i: Iterable[AnyStr]):
    return i


def bar(i: Iterable[str] | Iterable[bytes]):
    return i


def baz(i: Iterable[str | bytes]):
    return i


def main():
    s = ['a']

    # makes sense to me
    baz(foo(s))  # allowed
    foo(baz(s))  # not allowed

    # makes sense to me
    baz(bar(s))  # allowed
    bar(baz(s))  # not allowed

    bar(foo(s))  # allowed
    foo(bar(s))  # nope -- why?
```

**VS Code extension or command-line**
CLI (`pyright 1.1.144`)

**Additional context**

**Comment by erictraut** [comment]
No, this isn't a bug. This is correct behavior.

The type `Iterable[str] | Iterable[bytes]` is not assignable to type `Iterable[AnyStr]`. A constrained type variable needs to be matched against one of its contraints, not multiple constraints. When a type variable is "solved", it needs to be replaced by another (typically concrete) type. If `foo(bar(s))` were allowed, what type would the `AnyType@foo` type variable resolve to? If it were resolved to type `str | bytes`, then the concrete return type of `foo` would be `Iterable[str | bytes]`. That's clearly wrong.

To help convince you that pyright is doing the right thing here, mypy reports the same errors.

**Comment by Kache** [comment]
I don't precisely understand, but it sounds to me like you're saying this is an artifact of the type variable solving implementation?

In that case, what is the right way/is there a way to type-hint the following?

```py
import random
from typing import Iterable, AnyStr

def foo(i: Iterable[AnyStr]):
    return i

def exclusive_bytes_or_str():  # type-inferred to be Iterator[bytes] | Iterator[str]
    if random.randrange(2) == 0:
        return iter([b'bytes'])
    else:
        return iter(['str'])

foo(iter([b'bytes']))          # fine
foo(iter(['str']))             # fine
foo(exclusive_bytes_or_str())  # same error
```

How do I express that `foo` can accept either `Iterable[str]`/`Iterable[bytes]`, and that it is safely/correctly receiving one or the other from `exclusive_bytes_or_str`?

**Comment by erictraut** [comment]
Yeah, this isn't really the intended use for a constrained TypeVar. I recommend using an overload instead.

```python
@overload
def foo(i: Iterable[str]) -> Iterable[str]: ...
@overload
def foo(i: Iterable[bytes]) -> Iterable[bytes]: ...

def foo(i: Iterable[str] | Iterable[bytes]):
    return i
```

**Comment by Kache** [comment]
Hm, but doesn't `foo(i: Iterable[str] | Iterable[bytes])` mean that it could receive `Iterable[str]` but return `Iterable[bytes]`? I wanted to use the TypeVar in order to constrain the return type to match.

**Comment by erictraut** [comment]
From the perspective of callers, the overload enforces that constraint.

**Comment by erictraut** [comment]
If you want to enforce that for the implementation of `foo`, you can stick with your original signature.

```python
@overload
def foo(i: Iterable[str]) -> Iterable[str]: ...
@overload
def foo(i: Iterable[bytes]) -> Iterable[bytes]: ...

def foo(i: Iterable[AnyStr]) -> Iterable[AnyStr]:
    return i
```

**Comment by Kache** [comment]
I see, thank you so much!

Submit the answer to the [SO question](https://stackoverflow.com/questions/68869110/python-static-type-hint-check-mismatch-between-iterableanystr-vs-iterablestr) if you'd like?

**Comment by erictraut** [comment]
Feel free to post the answer or link to this thread.
