### ISSUE TITLE
Unable to narrow optional type in `dataclass` `__post_init__`

### ISSUE THREAD

**Issue by plafosse** [microsoft/pyright#2224]
**Describe the bug**
I'm unable to find a workaround for the following issue where pyright can't deduce that `self.y` can never be None. I'm not sure if this is a bug or intended functionality.

```python
from dataclasses import dataclass
from typing import Optional

@dataclass
class NotWorking:
    x:int
    y:Optional[bool]

    def __post_init__(self):
        self.y = self.y if self.y is not None else bool(self.x)

    def get_y(self) -> bool:
        return self.y  # <---- Expression of type "bool | None" cannot be assigned to return type "bool"


class Working:
    def __init__(self, x:int, y:Optional[bool]=None):
        self.x = x
        self.y = y if y is not None else bool(self.x)

    def get_y(self) -> bool:
        return self.y # <---- No error
```

![image](https://user-images.githubusercontent.com/10556585/130794731-72b0fe54-c600-41e1-823b-301ef742ff85.png)

**VS Code extension or command-line**
VS Code Extension v1.1.163

**Comment by erictraut** [comment]
Yes, this behavior is expected. Pyright doesn't know about `__post_init__` and generally does not make assumptions about call order between methods. Mypy emits the same error here.

The recommended workaround in this case is to add an assert in your `get_y` method.
```python
assert self.y is not None
```

This assert serves to document your assumption that the instance variable is not `None` in this case.

**Comment by plafosse** [comment]
thanks for the response.

**Comment by plafosse** [comment]
What about this similar case?

```python
from typing import Optional
class Bar:
    def __init__(self, x:int, y:Optional[bool]=None):
        self.y = y
        if self.y is None:
            self.y = True

    def get_y(self) -> bool:
        return self.y # <---- Expression of type "bool | None" cannot be assigned to return type "bool"
```

**Comment by erictraut** [comment]
Incidentally, this isn't related to `dataclass` specifically. Your second example (with class `Bar`) would also result in the same error if the annotated type of instance variable `y` was `Optional[bool]`.

```python
self.y: Optional[bool] = y if y is not None else bool(self.x)
```

The reason it happens to work in your example is because you've left `y` unannotated, so its type is inferred from its assigned values. The type checker can determine that you are assigning only a `bool` value to it, so it infers that its type is `bool`.

**Comment by erictraut** [comment]
In your second example with `Bar`, `y` has two assignments. The first assigns a value of type `Optional[bool]`, and the second a type of `bool`, so its inferred type is `Optional[bool]`.

**Comment by erictraut** [comment]
For more information about type declarations, type inference, and the ways that pyright infers types, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).
