### ISSUE TITLE
Function header and docstring shown twice in hover

### ISSUE THREAD

**Issue by trevor87** [microsoft/pyright#2236]
**Describe the bug**
If Pyright is used with Jedi or Microsoft Language Server the function header and docstring are shown twice in the hover box. 

**To Reproduce**
1. Install ms-python.python
2. Remove Pylance extension (it is automatically installed with ms-python.python)
3. Choose an alternative language server (e.g. Jedi)
4. Install Pyright
5. Hover over a function in the code.

**Expected behavior**
I would expect the function header and docstring to be only shown once (as is the case when using Pylance). Expected behavior: 
![image](https://user-images.githubusercontent.com/6329259/131214623-bdbf76cd-ca57-4909-80d3-b72bc03fe2fd.png)

**Screenshots or Code**
Actual behavior:
![image](https://user-images.githubusercontent.com/6329259/131214405-b9c1d17d-df75-45aa-91d4-a821f544a1a0.png)

**VS Code extension or command-line**
VS Code extension 1.1.159

**Comment by erictraut** [comment]
Jedi and Pyright are both language servers. If you enable both of them, you'll see output from both of them. VS Code combines the output and shows both. I recommend using only one language server at a time — and I'd generally recommend using Pylance rather than Jedi or Pyright.

If, for some reason, you want to keep both Jedi and Pyright installed, you can disable the language server features of Pyright by setting "pyright.disableLanguageServices" to true.

**Comment by trevor87** [comment]
Thanks for clarifying! I did not realize that Pyright is a language server, as it is not listed as an option in the  `python.languageServer` dropdown menu. Indeed, setting `python.languageServer` to `None` solves this issue, but unfortunately breaks the pytest support (the testing option in the left toolbar disappears). Is this to be expected?

**Comment by erictraut** [comment]
The VS Code extension for Python has an extension model of its own, and it can load various linters, language servers, formatters, etc. The "python.languageServer" tells the Python extension which language server you want it to load. 

Pyright ships as a command-line tool but also as an VS Code plugin that runs independently from the Python extension. 

As I mentioned above, we recommend against using the Pyright VS Code extension and instead using Pylance, which is built on the Pyright type checker but also includes more advanced functionality like refactoring and Intellicode support. Pylance ships as a language server that the Python extension can load, so it should appear in the list of options for the "python.languageServer" setting. Is there a reason you don't want to use Pylance?

**Comment by erictraut** [comment]
Oh, I forgot to answer your question about pytest support. That's handled by the Python extension. I wouldn't expect the test case management functionality to depend on a language server, so I'm surprised to hear that this breaks when you set `python.languageServer` to "None". @jakebailey, do you have any insights here?

In any case, if you enable Pylance and uninstall the Pyright extension, you will get all of pyright's functionality along with all of the functionality of the core Python extension (including test case management).

**Comment by jakebailey** [comment]
The test explorer used to depend on the language server to map test names to locations, but that was recently changed as pytest and such can provide that info directly, so testing shouldn't depend on the language server anymore. I'm not sure when that change is coming (or if it's behind some sort of experiment). @karthiknadig would know.

**Comment by karthiknadig** [comment]
That change will be in the upcoming release of the python extension. It is currently in the insiders version of the extension. It is also not behind any experiment.

**Comment by trevor87** [comment]
Thanks for the detailed answers and the quick responses, I am very impressed!

Regarding your question about whether there is a reason I am not using pylance: I switched to vscode from my old proprietary IDE mainly because of vscode's open source license. Pylance unfortunately seems to be closed source, so I am currently evaluating whether there is a way to continue using vscode with open source software or whether I will switch back to my old IDE.
