### ISSUE TITLE
@final with Generic decorators

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#2242]
**Describe the bug**
final doesn't seem to work with generic decorators.

**To Reproduce**
Similar example as in https://github.com/python/mypy/issues/11037
```py
from typing import (
    Callable,
    Generic,
    Optional,
    TypeVar,
    Union,
    final,
    overload,
)

F = TypeVar("F")
G = TypeVar("G")


class cache_readonly(Generic[F, G]):
    def __init__(self, func: Callable[[F], G]) -> None:
        self.func = func
        self.name = func.__name__
        self.__doc__ = getattr(func, "__doc__", None)

    @overload
    def __get__(self, obj: F, typ) -> G:
        ...

    @overload
    def __get__(self, obj: None, typ) -> "cache_readonly[F, G]":
        ...

    def __get__(self, obj: Optional[F], typ) -> Union[G, "cache_readonly[F, G]"]:
        if obj is None:
            # accessed on the class, not the instance
            return self

        # Get the cache or set a default one if needed
        cache = getattr(obj, "_cache", None)
        if cache is None:
            cache = obj._cache = {}  # type: ignore

        if self.name in cache:
            val = cache[self.name]
        else:
            val = self.func(obj)
            cache[self.name] = val
        return val

    def __set__(self, obj: F, value: G) -> None:
        raise AttributeError("Can't set attribute")


class TestA:
    @final
    @cache_readonly
    def x(self) -> str:
        return "A"
```

**Expected behavior**
Pyright accepts the code (mypy does).

```
test.py:51:6 - error: Argument of type "cache_readonly[TestA, str]" cannot be assigned to parameter "f" of type "_F@final" in function "final"
    Type "cache_readonly[TestA, str]" is incompatible with bound type "(*args: Any, **kwargs: Any) -> Any" for type variable "_F@final"
      Type "cache_readonly[TestA, str]" cannot be assigned to type "(*args: Any, **kwargs: Any) -> Any" (reportGeneralTypeIssues)
```

**VS Code extension or command-line**
command-line tool, version 1.1.161

**Comment by erictraut** [comment]
Hmm, I think pyright is doing the right thing here. The `@final` decorator is annotated to take a callable parameter, but the `@cache_readonly` decorator changes the callable into a non-callable descriptor.

If you apply the `@final` first, the error goes away.

I'm not sure why mypy accepts this without an error.

**Comment by twoertwein** [comment]
Thank you for the explanation! Pandas is then using final + cache_readonly in the wrong combination, for example [here](https://github.com/pandas-dev/pandas/blob/9cb969e869611f2a9392bb42db12f118d73b928c/pandas/core/internals/blocks.py#L164).

**Comment by erictraut** [comment]
It's also possible that `@final` is annotated incorrectly in the typeshed stub file. If it accepts non-callable arguments at runtime, then its type declaration should arguably reflect that. If you think that's the case, I recommend filling a bug (or a PR) in the typeshed github project.

**Comment by twoertwein** [comment]
Based on [PEP 591](https://www.python.org/dev/peps/pep-0591/), I think that `@final` should work with properties (which should also cover the above example?): "The method decorator version may be used with all of instance methods, class methods, static methods, and properties."

Simpler example:

```py
from typing import final

class Test:
    @property
    def foo(self):
        return "foo"

    @final
    @property
    def bar(self):
        return "bar"
```

```
error: Argument of type "property" cannot be assigned to parameter "f" of type "_F@final" in function "final"
    Type "property" is incompatible with bound type "(*args: Any, **kwargs: Any) -> Any" for type variable "_F@final"
      Type "property" cannot be assigned to type "(*args: Any, **kwargs: Any) -> Any" (reportGeneralTypeIssues)
```

I will have a look whether that is "wrong" in typeshed.

**Comment by erictraut** [comment]
This is the same issue as above. Here's how typing.pyi defines `final`:

```python
    _F = TypeVar("_F", bound=Callable[..., Any])
    def final(f: _F) -> _F: ...
```

I'm reluctant to change pyright to simply ignore this type declaration.

**Comment by twoertwein** [comment]
Thank you, I just found it as well. I will open an issue at typeshed and close this issue here.

**Comment by twoertwein** [comment]
@erictraut  it was merged in typeshed :) https://github.com/python/typeshed/pull/5985#event-5230490698

**Comment by erictraut** [comment]
Thanks @twoertwein. I've pulled the latest typeshed stubs into pyright, and they'll be included in the next release.
