### ISSUE TITLE
Explore support for implied `init` argument in dataclass field

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#2256]
Refer to this thread for details: https://github.com/microsoft/pyright/discussions/1782#discussioncomment-1268772

**Comment by erictraut** [comment]
@patrick91, this support will be implemented in the next release of pyright.

**Comment by patrick91** [comment]
Awesome! I'm curious to see how this will be implemented! Thank you for doing this by the way!

**Comment by erictraut** [comment]
This is included in pyright 1.1.166, which I just published. It will also be included in the next release of pylance.
