### ISSUE TITLE
ParamSpec arguments cannot be bound to in TypeAlias

### ISSUE THREAD

**Issue by bijij** [microsoft/pyright#2260]
**Describe the bug**
a ParamSpec in a TypeAlias cannot be bound to unlike TypeVars.

**To Reproduce**
Consider the code below.

**Expected behavior**
Code would type-check

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/8677174/131992988-9f5ff8ec-4af9-4fb4-8139-3f595e85d7fb.png)

**VS Code extension or command-line**
pyright 1.1.165

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.166, which I just published. It will also be included in the next release of pylance.
