### ISSUE TITLE
Enum str mix-in not supported

### ISSUE THREAD

**Issue by austinbutler** [microsoft/pyright#2262]
**Describe the bug**

```
Expression of type "Literal['get']" cannot be assigned to declared type "Literal[HTTPMethod.get]"
  "Literal['get']" cannot be assigned to type "Literal[HTTPMethod.get]"PyrightreportGeneralTypeIssues
```

**To Reproduce**

Create `Enum` with `str` mix-in.

**Expected behavior**

No type issues reported.

**Screenshots or Code**

```python
import enum

class HTTPMethod(str, enum.Enum):
    """Possible HTTP methods to store in an APILog entry."""

    get: str = "get"
    post: str = "post"
    put: str = "put"
    delete: str = "delete"
    patch: str = "patch"

    def __str__(self):
        return self.value
```

**VS Code extension or command-line**

Extension v1.1.138

**Comment by erictraut** [comment]
You should not annotate the members of the enum with type `str` because these members are actually of type `HTTPMethod`. If you remove the `str` annotations, it will work as expected.

**Comment by austinbutler** [comment]
Got it, thanks!
