### ISSUE TITLE
TypeGuard[T] does not narrow type to T

### ISSUE THREAD

**Issue by iyakushev** [microsoft/pyright#2266]
**Describe the bug**
I wanted to use a function to determine the type of a given object but pyright does not change the object type in the `True` branch. Since I have to use some unique arbitrary value defined by the user to check against the true type, I cannot rely on a simple `isinstance` check (which works fine).

**To Reproduce**
```python
from typing import TypeVar
from typing_extensions import TypeGuard

T = TypeVar("T", bound="Base")
 
class Base:
    _t = 1

    def is_instance(self, k: Type[T]) -> TypeGuard[T]:
        return self._t == k._t
        
class Child(Base):
    _t = 2
    
    def bar(self):
        print("I'm an instance of Child")
        
def foo(some_obj: Base):
    if isinstance(some_obj, Child):
        some_obj.bar()  # Correctly narrows `some_obj` type to `Child`
    if some_obj.is_instance(Child):
        # `some_obj` type hasn't changed. `some_obj: Base`
        some_obj.bar()  # Error: Cannot access member "bar" for type "Base". Member "bar" is unknown.
    else:
        some_obj.bar()  # Error as expected. 
```

**Expected behavior**
I expect to see the same behavior as with `isinstance` function. Perhaps I've made a mistake in the `is_instace` type signature?

**VS Code extension or command-line**
Python3.9
Pyright 1.1.165

**Comment by erictraut** [comment]
This is expected behavior. Please refer to [PEP 647](https://www.python.org/dev/peps/pep-0647/#typeguard-type) for details. It says:

> If a type guard function is implemented as an instance method or class method, the first positional argument maps to the second parameter (after "self" or "cls").

You can read in the "Rejected Ideas" section why we decided to specify type guard methods in this manner.

That means the expression that is being narrowed in this case is `Child`, which is clearly not your intent.

You would need to change your code to the following:

```python
class Base:
    _t = 1

    def is_instance(self, value: object, k: Type[T]) -> TypeGuard[T]:
        return self._t == k._t

class Child(Base):
    _t = 2

    def bar(self):
        print("I'm an instance of Child")


def foo(some_obj: Base):
    if some_obj.is_instance(some_obj, Child):
        some_obj.bar()
    else:
        some_obj.bar()  # Error as expected.
```
