### ISSUE TITLE
Additional builtins / available variables throughout the project ("flake8 --builtins=...")

### ISSUE THREAD

**Issue by Nachtalb** [microsoft/pyright#2269]
**Is your feature request related to a problem? Please describe.**
As I can see there is no way to add additional builtins / available variables. I am working on a project that adds `_` (translating function) as a built-in somewhere so that it can easily be used anywhere. While flake8 is doing its job it ignores that "missing variable" in the code thanks to the [--builtins=](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-builtins) option, pyright however reports it as `reportUndefinedVariable`. Sacrificing `reportUndefinedVariable` is not an option tho as it is pretty important to have IMHO. 

**Describe the solution you'd like**
An [configuration](https://github.com/microsoft/pyright/blob/a881461577d20d313057d65f677fdacee6b2cc5f/docs/configuration.md) option that takes a list of strings that are recognized as available variables throughout the project (probably of type `Any`).

**Comment by erictraut** [comment]
Pyright doesn't hard-code any notion of builtins symbols. These come from the `builtins.pyi` stub file. You can specify your own builtins.pyi and add any symbols you would like along with their corresponding types.

**Comment by Nachtalb** [comment]
Ahh, I didn't realise that it works like this with stubs. Thanks!
