### ISSUE TITLE
About pyright for sublime_text ser

### ISSUE THREAD

**Issue by sttv9998877** [microsoft/pyright#2281]

**Comment by sttv9998877** [comment]
I'm now using Debian system and sumlime_text to code with python
There are some settings I need to change to adapt my project file
But when I modified the setting, it had not overridden the old one
And I search the path of setting file, found that nothing existed there, including the folder "LSP-pyright", I must create it by myself and write the settings directly in this file
Is that a bug, or it rightly would not initiate this aspect?

**Comment by erictraut** [comment]
I think you'd need to ask the maintainer of the LSP-pyright subline plugin. Here's a link to that repo: https://github.com/sublimelsp/LSP-pyright

**Comment by sttv9998877** [comment]
Ok，sorry🤣On Sep 9, 2021 13:45, Eric Traut ***@***.***> wrote:
I think you'd need to ask the maintainer of the LSP-pyright subline plugin. Here's a link to that repo: https://github.com/sublimelsp/LSP-pyright
