### ISSUE TITLE
Pyright does not understand VS Code python interpretator version

### ISSUE THREAD

**Issue by vit1251** [Microsoft/pyright#23]
Pyright provide error message about import error with most common Python module like ```aiohttp``` and etc.

I assume that Pyright VS Code plugin does not understand project selected Python version.

**Comment by erictraut** [comment]
Pyright contains built-in type stub files for the stdlib modules (those that ship with the Python interpreter) but doesn't contain type stubs for other third-party libraries like aiohttp. You need to provide these yourself (e.g. download them from the typeshed GitHub site) or configure pyright to look in your python environment. The instructions for doing so are on the pyright site.

**Comment by vit1251** [comment]
@erictraut your solution is sounds as support issue. I use PyCharm and you know what? PyCharm search Python and provide enwironments selection. I remove pyright now and think that right now it not production ready.

**Comment by erictraut** [comment]
Yeah, pyright is definitely a work in progress. It's not a production-ready solution.

**Comment by vit1251** [comment]
@erictraut it would be nice to teach pyright to find a Python, especially since it has already been selected and is most likely configured.

![изображение](https://user-images.githubusercontent.com/110534/55039609-e3644980-5035-11e9-928f-31923e5bedc7.png)

**Comment by xjose97x** [comment]
Why was this closed?

**Comment by erictraut** [comment]
Pyright now honors the venvPath setting from VS Code. If you have your python environment configured in VS Code, pyright should pick up the installed modules. If you're experiencing problems, feel free to open a new issue. I've also added a bunch of logging information to help diagnose issues. You can find that in the "Output" panel in VS Code (choose "Pyright" in the popup).

**Comment by xjose97x** [comment]
Thanks for the quick reply @erictraut !
