### ISSUE TITLE
The `from` clause of the raise statement can accept an exception class

### ISSUE THREAD

**Issue by MapleCCC** [microsoft/pyright#2311]
**Describe the bug**
Python official document [states](https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement) that the `from` clause of the raise statement can accept an exception class:

> The `from` clause is used for exception chaining: if given, the second _expression_ must be another exception class or instance.....If the expression is an exception class, the class will be instantiated and the resulting exception instance will be attached to the raised exception as the `__cause__` attribute.

However, Pyright complains when the `from` clause takes an exception class, as demonstrated by the following screenshot.

**To Reproduce**
```python
raise RuntimeError from ValueError
```

**Screenshots**
![image](https://user-images.githubusercontent.com/25131775/133914220-e5e7da8a-3ca8-4405-82a6-a774e4f709a7.png)

**VS Code extension or command-line**
pyright command-line 1.1.169

**Comment by erictraut** [comment]
Thanks for the issue report. I wasn't aware that exception classes were allowed in this context. I've updated the code to handle this case. It will be fixed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.170, which I just published. It will also be included in the next release of pylance.
