### ISSUE TITLE
Missing docstring when __doc__ is appended

### ISSUE THREAD

**Issue by JulianOrteil** [microsoft/pyright#2316]
**Describe the bug**
Pyright is failing to generate the complete docstring when the `__doc__` attribute is appended in a class. When importing the class into a session and running Python's built-in `help` command, this is not the case.

**To Reproduce**
Place the below code in a file and hover with the mouse like normal.

**Expected behavior**
A complete docstring.

**Screenshots or Code**
_From Pyright (using Pylance)_
![image](https://user-images.githubusercontent.com/23083317/134090018-608aa41d-babe-46ff-b6ff-3cd769d8ab71.png)

_Running the `help` command_
![image](https://user-images.githubusercontent.com/23083317/134089940-b0b2953a-2c78-4409-aa0c-98bd658c0d51.png)

_Example code_
```python
class A:
    """**description of attributes about this class abstract**"""


class B(A):
    """I am a complex docstring."""

    __doc__ += A.__doc__
```

**VS Code extension or command-line**
As an extension through Pylance. I am using the latest version of Pylance.

**Additional context**

**Comment by erictraut** [comment]
Pyright is a static type analyzer. It doesn't actually run the code, so it cannot support dynamic behaviors like this. The `help` command actually runs the code.
