### ISSUE TITLE
Ignore hidden directories by default

### ISSUE THREAD

**Issue by enderstorm** [microsoft/pyright#232]
**Describe the bug**
Pyright analyses .tox directory files.
It consumes a lot of resources (CPU, Memory).

**To Reproduce**
- Set up tox for your project and have it create venv

**Expected behavior**
Ignore files undex .tox.

**Screenshots or Code**
```
Could not import 'usercustomize' in file '/home/enderstorm/src/PROJECT/.tox/py37/lib/python3.7/site.py'
```

**VS Code extension or command-line**
VS Code ext, v of pyright is 1.0.58

**Comment by enderstorm** [comment]
This pyright setting helped:
```"exclude": ["**/.tox/**/*"]```
At least I would mention in the docs for noobs like me :)

**Comment by erictraut** [comment]
Yes, that's correct. There's an "exclude" feature specifically for situations like this. It's documented [here](https://github.com/microsoft/pyright/blob/master/docs/configuration.md).
