### ISSUE TITLE
Add a quick fix to change the parameter to optional when default value is None

### ISSUE THREAD

**Issue by fabiencelier** [microsoft/pyright#233]
**Is your feature request related to a problem? Please describe.**
When `strictParameterNoneValue` rule is activated and the default value of a parameter is `None`, the parameter must be Optional. I have just activated this rule and it is painful to write optional everywhere. 

**Describe the solution you'd like**
A quick fix in the VS Code extension to add the Optional to the parameter type.

**Comment by erictraut** [comment]
Thanks for the suggestion. This will be implemented in the next published version of VS Code.

**Comment by fabiencelier** [comment]
Nice, thank you :)

**Comment by erictraut** [comment]
This is now implemented in 1.0.60, which I just published.
