### ISSUE TITLE
Option to warn about explicitly disabled rules that are not violated

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#2339]
**Is your feature request related to a problem? Please describe.**
Pandas enabled pyright on its CI (thanks for your help!) but almost all rules are disabled. It would be great to have an option to warn about disabled rules that could be enabled when they are not violated anymore.

**Describe the solution you'd like**
An option to warn about explicitly disabled rules that are not violated when running `pyright` (all settings are loaded from the configuration file, including the files to be checked).

**Comment by erictraut** [comment]
It takes significant work to get to the point where a rule can be enabled. It will not happen by chance, so I don't think this feature would be useful.

Once a code base is "clean" for a given rule, that rule can be enabled for everyone to prevent further regressions.

**Comment by twoertwein** [comment]
> It takes significant work to get to the point where a rule can be enabled. It will not happen by chance, so I don't think this feature would be useful.

That makes sense (especially for pandas).
