### ISSUE TITLE
Unicode byte order mark confuses tokenizer

### ISSUE THREAD

**Issue by tannewt** [microsoft/pyright#235]
First, thank you for this code! I'm really interested in using the annotated internal structure for structured editing of python files on mobile.

**Describe the bug**
The unicode byteorder mark (0xefbbbf) messes up the first token. `  1:1 - error: Invalid token: """"This"`

**To Reproduce**
Run pyright over this file: https://github.com/adafruit/Adafruit_CircuitPython_CircuitPlayground/blob/620b22c172e8841c082e2fe043da8f18e2195379/examples/circuitplayground_buttons_1_neopixel.py Notepad adds the byteorder prefix for example.

**Expected behavior**
The byte order mark should be skipped during tokenization and result in the correct parsing of the top level comment.

**Screenshots or Code**
Python code is here: https://github.com/adafruit/Adafruit_CircuitPython_CircuitPlayground/blob/620b22c172e8841c082e2fe043da8f18e2195379/examples/circuitplayground_buttons_1_neopixel.py Not sure how to include the byte order mark inline.

**VS Code extension or command-line**
Command line for git commit: eda5ca53fdfd4f8c248ea75d0fb6e4d2667ca164

**Comment by erictraut** [comment]
I presume that you're trying to use the pyright source code independently from pyright (in its built form). The reason pyright's tokenizer doesn't need to deal with the Unicode BOM is that it should never see it. It presumes that it is removed at the time the file is read. If you look at the code src/analyzer/sourceFile.ts and search for "fs.readFileSync", you'll see that pyright is opening the file with a 'utf8' encoding. This removes the BOM from the text stream as it's being read into memory. You should be able to do something similar in your code that calls the tokenizer.

**Comment by tannewt** [comment]
Thanks for the response @erictraut. I haven't gotten to the point of loading the file myself. The bug occurs with my built version of the pyright CLI so Node must not strip it.

**Comment by erictraut** [comment]
Ah, my bad. It's not a problem in the VS Code extension because VS Code returns the BOM, but it is an issue with the command-line version. This will be fixed in the next release.

**Comment by erictraut** [comment]
This is now fixed in 1.0.60, which I just published. Thanks again for the bug report!
