### ISSUE TITLE
QST: module-level deprecations with __getattr__ and reportUnsupportedDunderAll

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#2351]
Is there a recommended way to use `__getattr__` for module-level depredations and still be compatible with reportUnsupportedDunderAll? Should deprecated symbols be exported with `__all__`?

```py
__all__ = ["Deprecated"]  # error: "Deprecated" is specified in __all__ but is not present in module (reportUnsupportedDunderAll)

def __getattr__(name: str):
    import warnings

    if name == "Deprecated":
        warnings.warn(
            "Deprecated is deprecated and will be removed in a future version."
            DeprecationWarning,
        )
        from foo import Deprecated

        return Deprecated

    raise AttributeError(f"module 'pandas.core.internals' has no attribute '{name}'")

```
The actual code is here: https://github.com/pandas-dev/pandas/blob/master/pandas/core/internals/__init__.py

**Comment by erictraut** [comment]
A static type checker won't be able to determine that "Deprecated" is handled programmatically at runtime by `__getattr__`.

This is a pretty special case, so my first suggestion is to suppress the `reportUnsupportedDunderAll` check for this file. 

```python
# pyright: reportUnsupportedDunderAll=false
```

Alternatively, you could use a `# type: ignore` on the line that includes the `__all__` definition.

```python
__all__ = ["Deprecated"] # type: ignore
```

Another option is to define `Deprecated` conditionally under a `TYPE_CHECKING` check:

```python
if TYPE_CHECKING:
    Deprecated: Any
```

**Comment by twoertwein** [comment]
Thank you very much for the suggestions!
