### ISSUE TITLE
Suggest from future import __annotations__

### ISSUE THREAD

**Issue by Timmmm** [microsoft/pyright#2353]
Just a small suggestion that would have helped me in the past:

Sometimes when you write type annotations for older Pythons, e.g. 3.7 Pyright will helpfully tell you that your annotation will cause a runtime exception and you should wrap it in quotes.

That works and I did it for a while before discovering the better solution of just doing `from future import __annotations__`.

Maybe the fixit could suggest that too?

**Comment by erictraut** [comment]
Thanks for the suggestion.

When you say "fixit", are you simply referring to the error message? I don't think we have a code action for this situation.

**Comment by Timmmm** [comment]
Ah yeah good point - I guess the ultimate fix would be two code actions - one to add quotes and one to add the future import.

But probably the easiest thing is just to change the error message.

**Comment by erictraut** [comment]
Thinking about this more, I don't know that it's worth recommending the use of `from __future__ import annotations` in the error message. That construct is available in Python 3.7 and newer, and these errors apply only to Python 3.7 and older. The intersection of the two conditions is Python 3.7, and most Python developers have now moved beyond 3.7.

**Comment by Timmmm** [comment]
Hmm I get these errors on Python 3.8 too, but you're probably right - the problem will solve itself in a few years.
