### ISSUE TITLE
Improve checks for runtime errors related to enums

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#2361]
Mypy contributors are working on adding static checks for several enum-related usages that result in runtime errors.

https://github.com/python/mypy/issues/11248

These include:
* Checking for duplicate keys in an enum
* Checking for external reassignment of keys
* Checking for subclassing of an enum class

These are all reasonable (and relatively cheap) checks to perform, so it would be nice if pyright implemented similar checks.

**Comment by erictraut** [comment]
This will be included in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.174, which I just published. It will also be included in the next release of pylance.

**Comment by sobolevn** [comment]
Oh wow, @erictraut! Awesome work! 👍

**Comment by erictraut** [comment]
I needed to back out the check for subclassing of an enum class. The check is more complex than I initially realized, and my naive approach resulted in a regression. See https://github.com/microsoft/pyright/issues/2367 for details. The correct check will require more complex logic.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.177, which I just published. It will also be included in the next release of pylance.
