### ISSUE TITLE
Cannot assign user-defined functions to `FunctionType`

### ISSUE THREAD

**Issue by MapleCCC** [microsoft/pyright#2368]
**Describe the bug**
Cannot assign user-defined functions to `FunctionType`.

**To Reproduce**
```python
from types import FunctionType

def f():
    pass

g: FunctionType = f
```

**Screenshot**
![image](https://user-images.githubusercontent.com/25131775/135900815-bd5914ef-3e38-4ccb-96f1-552d7d7391fb.png)

**VS Code extension or command-line**
pyright command-line 1.1.174

**Comment by MapleCCC** [comment]
I was thinking that maybe `FunctionType` is good to be used as type annotations because I saw that it's common to use `CodeType/FrameType/ModuleType` as type annotations in other places.

If we are only allowed to use `Callable` but not `FunctionType`, does it mean that we can't distinguish general callables and user-defined functions in current (static) type system?

**Comment by erictraut** [comment]
That's correct. The static type system doesn't differentiate between general callables and user-defined functions. From a type perspective, they're all callable.

**Comment by MapleCCC** [comment]
Very thank you for your patient and informative reply! It helps me understand the concepts.
