### ISSUE TITLE
Dataclass inheritance is ignored

### ISSUE THREAD

**Issue by NateScarlet** [microsoft/pyright#239]
**Describe the bug**
Dataclass inheritance is ignored

**To Reproduce**

![image](https://user-images.githubusercontent.com/21083014/64511047-0b124a00-d316-11e9-960e-1644cb98b89f.png)

**Expected behavior**
Not ignore inheritance 

**VS Code extension or command-line**
VS Code extension: 1.0.59

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release of pyright.

**Comment by erictraut** [comment]
This is now addressed in 1.0.62, which I just published.
