### ISSUE TITLE
Defect visibility pylance vs pyright (transparency of type checker defects)

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/pyright#2394]
I just created https://github.com/microsoft/pylance-release/issues/1913 because I am *using* the pylance extension - knowing full well that the type-checking parts come from pyright (see readme, here)

By reporting on the pylance extension, 
* I can provide the right version information for what I use (good)
* I drop type-check defects into a bucket where they will be difficult to discover for users (bad) - and I don't even know how well type check module defects are triaged and processed in pylance...

I believe it would be quite useful if Microsoft could find a clean way around this dilemma. I'd love to see all type-check defects easily visible and researchable in exactly one location (single source of truth), and I do like the convenience of pressing "Report Issue" in vscode ...

**Comment by jakebailey** [comment]
I'm confused; what is the dilemma? You are absolutely free to post type checking issues on the Pylance repo if you are using Pylance. We watch both trackers and fix things related to type checking regardless of where the issue started. In either case, we'll know exactly what version of things are being used as well; pylance prints the commit of pyright that it has on startup.

**Comment by shoffmeister** [comment]
> I'm confused; what is the dilemma? You are absolutely free to post type checking issues on the Pylance repo if you are using Pylance. We watch both trackers and fix things related to type checking regardless of where the issue started. In either case, we'll know exactly what version of things are being used as well; pylance prints the commit of pyright that it has on startup.

The "dilemma" is me (naïve user) trying to discover all reported type-checking defects in the most straight-forward fashion.

It is (IMHO) not clear from the readme here on pyright that members of the org here will create tracking issues in pyright, whenever issues are reported against the component in pylance. To that extent, the response by @erictraut addresses my concern; I'd like to suggest adding this to the readme, too.

**Comment by erictraut** [comment]
Thanks for the suggestion. I've updated the README to include a few sentences about filing bug reports and and enhancement requests.
