### ISSUE TITLE
Issue about import organization.

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#240]
We used to use [isort](https://github.com/timothycrosley/isort#configuring-isort) as our import organization solution by using it's CLI to format code before commit and configure it as the import organization provider in the vscode-python extension.

But the current version of pyright will sort import differently, to be specific:
- We configured --max-line-width = 120 in isort, but pyright seems to wrap lines longer than about 90 characters
- Isort always put `from X import Y` syntax below `import X` syntax, even they are in the same group.
```python
# in pyright
from a import a1
import b
from c impot c1
import d

# in isort
import b
import d
from a impot a1
from c impot c1
```
- Isort support multiple strategies of line wrapping, see [this doc](https://github.com/timothycrosley/isort#multi-line-output-modes)

I'm not asking pyright to implement isort's rules, I'm just asking for what you think of this feature so that we can adapt it.

These are several approaches I can tell:
- pyright provide some ability to configure import sorting (mainly the --max-line-width) and ability to call import sorting from the command-line version of pyright (we run the formating script before git commit), then we can move to pyright's solution.
- pyright do nothing, we disable the "organize imports on save" option provided by vscode.
Then we can either use another extension to achieve "import on save" functionality or wait until pyright and vscode-python combined together so that we can continue to use isort as import sorting provider.

Please tell me what you think, thank you!

**Comment by erictraut** [comment]
I was already reluctant to provide this feature because it falls into the category of linting and style formatting rather than type checking. In that sense, it's outside the domain of pyright. I don't want to go any further down that slippery slope at this time. There are other tools (like pylint and isort) that are custom-made for things like this, and they're going to be much more capable at that just. If pyright's import organization rules don't match your style guidelines, then ignore it and use a tool that provides more configuration.

**Comment by giyyapan** [comment]
I'll do that, thanks for your reply!

**Comment by giyyapan** [comment]
Hi Eric, I've made my own extension for formating and import organization (not published yet).

But unfortunately, since pyright also registered as a code-action provider, when adding config:
```
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  }
```
both pyright and my extension will sort imports, that's not expected.

Can you provide an option to disable import organization feature from pyright side? Otherwise, I won't be able to use the vscode's built-in "organize imports on save" functionality.

I really hate to ask this because I know you're reluctant about this feature, but I think this will be my last feature request related to import sorting.

Let me know if I'm getting anything wrong.
Thanks!

**Comment by erictraut** [comment]
You can simply choose another (non-conflicting) name for your code action command name. Mine is called "pyright.organizeimports". Likewise, you can choose a unique name for the user-visible string that appears in the context menu or code action menu. I chose the string "Organize Imports", so you could use something like "Organize Imports (MyExtensionName)" to avoid any ambiguity.

**Comment by giyyapan** [comment]
Thanks for your reply.

I already use a different and unique name.

![image](https://user-images.githubusercontent.com/3479453/65211184-612e7c80-dad0-11e9-89e8-073812f3d749.png)
_PyFormat is the name of my extension_

As you can see in the screenshot, there are three commands.

`Organize Imports` is a command provided by vscode, it triggers the built-in code-action `vscode.CodeActionKind.SourceOrganizeImports`, which both my extension and pyright registered as it's provider.

It's true that if I use a different name, a user can manually trigger that command or bind it to a shortcut, but it's a different thing when we talking about the setting:
```
"editor.codeActionsOnSave": {
  "source.organizeImports": true
}
```
I don't know if you use this setting yourself, but this setting is kind of a "vscode standard" way to accomplish "sort import on save" for any language. When set to true, vscode will trigger the built-in `Organize Imports` command when a file is saved, that command then triggers **ALL** provider for the `vscode.CodeActionKind.SourceOrganizeImports` code action.

So, as long as I'm not getting this wrong, it's really nothing I can do from my extension side to let only my extension do the import sorting without trigger pyright's when a user chooses to use the standard sort-import-on-save setting that vscode provide.

**Comment by erictraut** [comment]
No, I wasn't aware that you could configure it this way.

Adding a switch to disable this code action in pyright wouldn't be sufficient to address your needs. You'd need to also need to get a similar switch added to the built-in Python extension, and that team is unlikely to agree to such a change.

It looks like you can define custom code action kinds. I recommend you explore that option. You could register a code action of "source.organizeImports.custom" or whatever you want to call it. Then you can use that same string in the "editor.codeActionsOnSave" array.

**Comment by giyyapan** [comment]
You're right, I'll try adding a custom code action and see if it works with the "editor.codeActionsOnSave" setting.

Thanks for your advice.

**Comment by giyyapan** [comment]
I took your advice and the extension is now published: https://marketplace.visualstudio.com/items?itemName=giyyapan.pyformat

Thanks for your help again!
