### ISSUE TITLE
How to run the test suite?

### ISSUE THREAD

**Issue by OrenGitHub** [microsoft/pyright#2416]
What is pyright's equivalent of `make tests`?
I tried the following but failed:
- convert type-script files to javascript:
```
[root@6ffad18a9ef4 pyright]# tsc | grep error | wc -l
1652
```
- run `ts-node` on a single test file:
```
$ ts-node packages/pyright-internal/src/tests/parser.test.ts 2> log.txt                       
$ cat log.txt | grep error | wc -l
16
```
Am I missing something? thanks !

**Comment by erictraut** [comment]
To build pyright:
`npm run build`

To run the test suite:
`npm run test`

**Comment by erictraut** [comment]
Oh, I forgot to mention that you need to run the tests from the `packages/pyright-internal` directory.
