### ISSUE TITLE
Generic Protocol class with an Optional function argument rejects a matching concrete class

### ISSUE THREAD

**Issue by joell** [microsoft/pyright#2421]
**Describe the bug**
For some contravariant type variable `T`, a generic class that inherits `Protocol[T]` and has a method with a parameter of type `Optional[T]` rejects a concrete class where `T` is instantiated as `int` with a method parameter of `Optional[int]`.  However, if both parameters are not `Optional`, then everything typechecks.

To clarify, here's a Python file we'll call `rejected.py` that illustrates the problem:

```python
# pyright: strict
from typing import Optional, Protocol, TypeVar

T = TypeVar('T', contravariant=True)

class Abstract(Protocol[T]):
    def do(self, x: Optional[T]):
        ...

class Concrete:
    def do(self, x: Optional[int]):
        pass

def use_protocol(a: Abstract[int]):
    a.do(1)

use_protocol(Concrete())
```

And here's a Python file we'll call `accepted.py` in which `Optional[X]` is replaced with `X`:

```python
# pyright: strict
from typing import Protocol, TypeVar

T = TypeVar('T', contravariant=True)

class Abstract(Protocol[T]):
    def do(self, x: T):
        ...

class Concrete:
    def do(self, x: int):
        pass

def use_protocol(a: Abstract[int]):
    a.do(1)

use_protocol(Concrete())
```

**To Reproduce**
```
$ pyright rejected.py
...
rejected.py:17:14 - error: Argument of type "Concrete" cannot be assigned to parameter "a" of type "Abstract[int]" in function "use_protocol"
    "Concrete" is incompatible with protocol "Abstract[int]"
      "do" is an incompatible type
        Type "(x: int | None) -> None" cannot be assigned to type "(x: T@Abstract | None) -> None"
          Parameter 1: type "T@Abstract | None" cannot be assigned to type "int | None" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 infos 


$ pyright accepted.py
...
0 errors, 0 warnings, 0 infos 
```

**Expected behavior**
`rejected.py` would typecheck successfully, just as `accepted.py` does.

**VS Code extension or command-line**
This was run on Arch Linux on the command-line using Pyright 1.1.176.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.179, which I just published. It will also be included in the next release of pylance.
