### ISSUE TITLE
Add missing imports, remove unused import statements, and so on.

### ISSUE THREAD

**Issue by hongyi-zhao** [microsoft/pyright#2425]
I noticed another wonderful project [autoimport](https://github.com/lyz-code/autoimport/), which has the following [features](https://lyz-code.github.io/autoimport/#features):

- Add missing imports
- Remove unused import statements
- Moving the imports to the top

I'm not sure if `pyright` has already implemented the above features, as commented [here](https://github.com/wyuenho/emacs-python-isort/issues/2#issuecomment-938663760) and [here](https://github.com/emacs-lsp/lsp-mode/issues/3150#issuecomment-942432969). 

Regards,
HZ

**Comment by erictraut** [comment]
Pyright is primarily a static type checker. It does have limited support for completion suggestions that include auto imports, but the other features you list above are outside the scope of static type checking.

Pylance, which is a language server for VS Code that is built on top of pyright, contains additional features similar to those you mentioned. If you would like to suggest additional language server features for pylance, I recommend submitting those feature requests in the [pylance-release issue tracker](https://github.com/microsoft/pylance-release).
