### ISSUE TITLE
The inappropriate description for Emacs integration.

### ISSUE THREAD

**Issue by hongyi-zhao** [microsoft/pyright#2426]
The following description comes from [here](https://github.com/microsoft/pyright#emacs):

`For emacs users, you can install lsp-mode that includes lsp-pyright. To activate the pyright extension follow the instructions in the docs.`

In fact, `lsp-mode` and `lsp-pyright` are two separate packages, so the more accurate description should like this:

`For emacs users, you can install lsp-mode and lsp-pyright. To activate the pyright extension follow the instructions in the docs.`

**Comment by erictraut** [comment]
The current phrasing was provided by the maintainers of lsp-pyright. If they're OK with this proposed change, I'm happy to make it. Please reach out to them and have them reply.

**Comment by erictraut** [comment]
I'm going to close this. If the maintainers of lsp-pyright get back to me with a recommended change to the wording, I'm happy to make this.
