### ISSUE TITLE
Specify which rule is not respected

### ISSUE THREAD

**Issue by fabiencelier** [microsoft/pyright#243]
When a rule is not respected there is no way to know what is the name of this rule.

I think the name should be included in the error message (both in VS code and CLI) so I can disable it with a comment `# pyright: nameOfRule=false` or at least find it in the doc and understand how it works.

pylint does something like this.
In the CLI : 
>file.py:45:8: W0613: Unused argument 'my_var' (unused-argument)

In the extension : 
![pylint](https://user-images.githubusercontent.com/17087544/64611105-f21a9f00-d3d0-11e9-86a8-9fddb0381aa0.png)

**Comment by erictraut** [comment]
Thanks for the suggestion. This will be implemented in the next release of pyright.

**Comment by erictraut** [comment]
This is implemented in 1.0.61, which I just published.
