### ISSUE TITLE
Pyright hasn't processed assert only in a stringized annotation

### ISSUE THREAD

**Issue by GBeauregard** [microsoft/pyright#2442]
This is a really weird one from the rich codebase. I've been thinking for a while about the best thing to fix the behavior, but I'm pretty sure this is weird edgecase bug with pyright. This example isn't really great, but the behavior seems like a bug anyway.

If the annotation here is stringized, errors are thrown as if pyright hasn't processed the `assert _attr_module is not None` line, but if the annotation is not stringized then no errors are thrown.

```python
from typing import TYPE_CHECKING, Any, Iterable

import attr as _attr_module

try:
    import attr as _attr_module
except ImportError:
    _attr_module = None

if TYPE_CHECKING:
    assert _attr_module is not None

# several errors
# appears to not have processed the assert
def _get_attr_fields(obj: Any) -> Iterable["_attr_module.Attribute[Any]"]:
    return _attr_module.fields(type(obj)) if _attr_module is not None else []

# no errors
def _get_attr_fields(obj: Any) -> Iterable[_attr_module.Attribute[Any]]:
    return _attr_module.fields(type(obj)) if _attr_module is not None else []
```

**Describe the bug**
Pyright is behaving differently for the stringized and non-stringized annotations. In particular, it appears to not have understood the assert in the stringized annotation.

**To Reproduce**
Run code above in pyright

**Expected behavior**
No error with either example.

**VS Code extension or command-line**
pyright 1.1.179 Linux commandline

**Comment by erictraut** [comment]
This is intended behavior, not a bug.

A "stringized" annotation means that it's meant to be processed as a forward declaration. Code flow inference rules (those that apply type narrowing based on code flow ordering and on statements like `assert`) are not applied for forward-declared symbols. It wouldn't make sense to apply code flow analysis and type narrowing for forward declarations because the local (narrowed) type of an expression changes throughout the code, and the intended type of the type annotation would be ambiguous.

My recommended approach in this case is:
```python
try:
    import attr as _attr_module
except ImportError:
    if not TYPE_CHECKING:
        _attr_module = None
```

**Comment by GBeauregard** [comment]
Huh, I guess I didn't appreciate this type of backwards incompatibility with the (deferred) PEP proposal behavior with `from __future__ import annotations`.

I will have to read this more closely and try to understand if the alternative proposal has the same "problem".

Sorry for another extraneous issue; I'm learning one at a time...

**Comment by erictraut** [comment]
Yeah, `from __future__ import annotations` can introduce backward compatibility issues for some edge cases. Another one that comes up occasionally is this:

```python
class Foo:
    a: int
    int: str
```

This is arguably an anti-pattern, but it does type check without `from __future__ import annotations` and breaks when forward references are assumed.

**Comment by erictraut** [comment]
Within minutes of me posting the above response, this bug was filed: https://github.com/microsoft/pyright/issues/2443. :)
