### ISSUE TITLE
Object of type "ModuleType" is not callable

### ISSUE THREAD

**Issue by matteha** [microsoft/pyright#2450]
Please see the image, it gives these errors although it's valid code (standard plotly documentation at https://plotly.com/python/graph-objects/ )

![Selection_037](https://user-images.githubusercontent.com/36545991/137767497-713e1af9-bcf0-48a4-a032-00b78517f750.png)

![Selection_038](https://user-images.githubusercontent.com/36545991/137767807-a38466d3-7939-4be2-b025-c0cc1f401dec.png)

Not sure how to fix this. Thank you!

**Comment by erictraut** [comment]
Plotly is using dynamic (runtime) code to perform its submodule imports. A static type checker like pyright won't be able to deal with this. You will need to find type stubs for the library. 

It looks like this is a known issue being discussed in the plotly issue tracker: https://github.com/plotly/plotly.py/issues/1103

**Comment by erictraut** [comment]
Yeah, that's a reasonable temporary workaround. You could also configure pyright to assume Python 3.6 by setting the "pythonVersion" setting to "3.6", but that might have other undesirable side effects.

**Comment by matteha** [comment]
Thank you. I changed it to 3.6 indeed, using:

sys.version_info = (3,6) # temporary hack for type stub issues

My earlier solution didn't work well as it had other problems down the road but this seems to do the job until this gets addressed on the plotly side.
