### ISSUE TITLE
When describing "alias" types using a walrus operator, you get a different result than assigning them individually.

### ISSUE THREAD

**Issue by Ran4** [microsoft/pyright#2452]
**Describe the bug**
When describing "alias" types using a walrus operator, you get a different result than assigning them individually.

**To Reproduce**

```python
from dataclasses import dataclass


@dataclass
class Walrus:
    name: (WalrusName := str)


PersonName = str


@dataclass
class Person:
    name: PersonName


def main():
    walrus = Walrus(name="Wally")
    walrus.name  # type of name is `(variable) name: str`

    person = Person(name="Argh")
    person.name  # type of name is `(variable) name: PersonName`


if __name__ == "__main__":
    main()
```

**Expected behavior**

I expected the `name` of `walrus.name` to be detected as `name: WalrusName`, not `str`. Or at least consistent behaviour.

**VS Code extension or command-line**

Using command-line pyright 1.1.87

**Comment by erictraut** [comment]
This fix will be included in the next release.
