### ISSUE TITLE
Pyright accepts incorrect return annotations for generators

### ISSUE THREAD

**Issue by StockerMC** [microsoft/pyright#2457]
**Describe the bug**
Pyright accepts a direct return annotation for a generator (not `Generator`, `Iterator`, or `Iterable`) as its yield type. I do not believe this to be intended. If it is, the type of the called generators should be one of the three (`Iterator`?) and not the return annotation. The `yield`ed (and possibly `return`ed?) value should also be type checked based on that return annotation.

**Screenshots or Code**
```python
from collections.abc import Generator

def generator() -> int:  # should be an error
    yield None
    return 3

reveal_type(generator())  # int

def generator2() -> str:
    yield None  # expression of type "None" cannot be assigned to yield type "str" (correct)
    return 3

reveal_type(generator2())  # str

def generator3() -> bool:  # should be an error
    yield None
    return 3

def generator4() -> float:  # should be an error
    yield None
    return 3

def generator5() -> int:  # should be an error
    yield ''
    return None

def generator6() -> str:
    yield 1  # Expression of type "Literal[1]" cannot be assigned to yield type "str" (correct)
    return 5

def generator7() -> Generator[str, None, int]:
    yield None  # Expression of type "None" cannot be assigned to yield type "str" (correct)
    return 3
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool?
Command line (pyright 1.7.179)

**Additional context**
For the first five examples (excluding the one with the `Generator` return annotaton), mypy states `The return type of a generator function should be "Generator" or one of its supertypes`.

**Comment by erictraut** [comment]
This was an easy fix. All of the code was in place for this check already, but there was a bug in the logic. I've fixed the bug and improved the unit tests. The fix will be in the next release.
