### ISSUE TITLE
Type of value in Dataclass field's default_factory is not narrowed to literal

### ISSUE THREAD

**Issue by meandmymind** [microsoft/pyright#2496]
**Describe the bug**
Look at the screenshot. `"cat"` string literal should be recognised as of type `Animal`, when used inside complex type in default_factory, but it is recognised as `str`.

Also, error message should be more like `dict[str, int] is incompatible with dict[Animal, int]`

**Expected behavior**
I expect `animals_in_home: Dict[Animal, int] = field(default_factory=lambda: {"cat": 0, "dog": 0, "mouse": 0})` to be a valid statement in this context.

**Screenshots or Code**
```python
from dataclasses import dataclass, field
from typing import Dict, Literal


Animal = Literal["cat", "dog", "mouse"]

@dataclass
class Person:
    animals_in_home: Dict[Animal, int] = field(default_factory=lambda: {"cat": 0, "dog": 0, "mouse": 0})
```
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/24773652/139051411-aede84a4-a729-4927-8421-293e4fa42ab8.png">

**VS Code extension or command-line**
Pylance v2021.10.2

**Additional context**
Also present with `Set` and `List`.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.183, which I just published. It will also be included in the next release of pylance.
