### ISSUE TITLE
pyright --stats time per module

### ISSUE THREAD

**Issue by tpict** [microsoft/pyright#2498]
**Is your feature request related to a problem? Please describe.**
Both–pyright's language server hogs my CPU indefinitely when I'm working on a large Django project (~3k Python files). `pyright --stats` takes a full minute.

**Describe the solution you'd like**
 It would be helpful to get a breakdown of the time spent per module, so I can figure out where it's choking.

**Additional context**
`pyright --stats --verbose` does print each module as it's processed. Maybe it could spit out the time delta between each one?

**Comment by erictraut** [comment]
I've modified the CLI version of pyright to emit (very) verbose trace logging when both `--stats` and `--verbose` are specified. The output is the equivalent of the trace logging that is provided in the language server (pylance and pyright).

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.184, which I just published.
