### ISSUE TITLE
Assignment to Literal keys of nested Dict is not type checked

### ISSUE THREAD

**Issue by shamrin** [microsoft/pyright#250]
**Describe the bug**
Assigning to `Literal` keys of a nested `Dict` is not type checked.

**To Reproduce**
```python
from typing import Dict
from typing_extensions import Literal

Language = Literal['en', 'de']
languages: Dict[Language, str] = {}
languages['en'] = 'English'
languages['de'] = 'German'
languages['eo'] = 'Esperanto' # error, as expected

translations = Dict[Language, Dict[str, str]] = {}
translations['en'] = {}
translations['eo'] = {} # no error, but expected
```

**Expected behavior**
Expect to get a type error on the last line.

**Screenshots or Code**
<img width="731" alt="image" src="https://user-images.githubusercontent.com/510678/65020656-42947e00-d936-11e9-98ac-318b16fced3e.png">

**VS Code extension or command-line**
Name: Pyright
Id: ms-pyright.pyright
Description: VS Code static type checking for Python
Version: 1.0.62
Publisher: ms-pyright
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright

**Additional context**
May be related to #247.

**Comment by shamrin** [comment]
By the way, here's the work-around (["flat is better than nested"][1]):

```python
from typing import Dict, Tuple
from typing_extensions import Literal

Language = Literal['en', 'de']
translations: Dict[Tuple[Language, str], str] = {}
translations['en', 'one'] = 'one'
translations['de', 'one'] = 'eins'
translations['eo', 'one'] = 'unu' # error, as expected
```

[1]: https://www.python.org/dev/peps/pep-0020/

**Comment by erictraut** [comment]
There's a bug in your original code snippet above that explains why you're not seeing the expected error.
`translations = Dict[Language, Dict[str, str]] = {}`
should be
`translations: Dict[Language, Dict[str, str]] = {}`
When I make that change, pyright reports an error as you expected.

**Comment by erictraut** [comment]
I'm my analysis above is wrong and you still think this is a bug, please re-open.

**Comment by shamrin** [comment]
Thank you @erictraut! You are right of course. But I think pyright should have told me about a problem :) I'll create another issue.

**Comment by erictraut** [comment]
Yeah, that's a good point. Yes, please create another issue.
