### ISSUE TITLE
Metaclass properties are Unknown when using __new__ in a derived class

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#2505]
**Describe the bug**
When defining a `__new__` method in a class derived from a metaclass that isn't type any added properties will not be accessible/is Unknown. 

**To Reproduce**
Define a simple metaclass with a property foo, use that metaclass to construct a class Derived. Try and accessed Derived.foo.

**Expected behavior**
Derived.foo should be a known member and have type info.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/50501825/139229781-f9750e38-0021-43da-ac9c-e14032c2e8f0.png)

**VS Code extension or command-line**
pyright 1.1.182
pylance v2021.10.3

**Comment by erictraut** [comment]
This will be fixed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.184, which I just published. It will also be included in the next release of pylance.

**Comment by Gobot1234** [comment]
Thank you!
