### ISSUE TITLE
Support code action "add missing import".

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#251]
I know we discussed this, and pyright's auto-import feature works great, but this feature still useful in scenarios like when pasting some codes that contain variables that need to be imported.

Currently, there's no comfortable way to add missing imports after pasting codes, I have to delete a variable and type it again to trigger auto-import.

Thanks!

**Comment by erictraut** [comment]
Code actions don't provide any means for providing inputs, so there's no way to select the correct auto-import in the case of duplicates. When I run into this situation, I simply click on the symbol in question and type control-space to invoke the type completion menu, then select the appropriate auto-import selection. This is just as convenient and fast as a quick action with the added benefit of being able to disambiguate between duplicates. So I don't think it makes sense to add a code action here.

**Comment by giyyapan** [comment]
Ok, I'll try that trick. Thanks.

**Comment by ashb** [comment]
@erictraut (Sorry to go spelunking in old issues)

Would this be possible to achieve via a quick fix action?

**Comment by erictraut** [comment]
Pylance implements something like this. Please give it a try and see if it's what you have in mind.

**Comment by himat** [comment]
Hi, using pylance is not a valid option. I use vim and pylance can only be used in VS code.
I don't understand what you mean by `type control-space to invoke the type completion menu` - what actual command does your <control-space> map to?

When I try to do a quick fix action on this code I added here, I expect it to be able to auto import BasicAuthBackend from the right module. But the two given options are not ideal.
<img width="702" alt="image" src="https://user-images.githubusercontent.com/1156974/205488251-4857e93f-f4f5-401c-9212-84fd7f86536d.png">

The first one doesn't even say which module to import it from, and the second requires me to know the module name.
I have another file in my project called auth.py which defines BasicAuthBackend, so the language server should be able to see that automatically and suggest the right completion which would be `from .auth import BasicAuthBackend`
