### ISSUE TITLE
Subclass that overrides `__new__` should construct instances having revealed type of subclass (not superclass)

### ISSUE THREAD

**Issue by mosbasik** [microsoft/pyright#2510]
**Description**
When a subclass's `__new__` returns the result of `super().__new__`, the revealed type of an object returned by the subclass' constructor is that of the superclass.  I expect the revealed type to be that of the subclass.

**Example**
At my workplace, we subclass `collection.namedtuple` in order to define some defaults handling, arg validation and behavior associated with an immutable structure (we'd probably use a different approach today, sure; this was originally written using Python 2.7).  Here's a demonstrative snippet:

```python
from datetime import date
from typing import Optional
import collections

HolidayBase = collections.namedtuple('HolidayBase', 'name day')

class Holiday(HolidayBase):

    def __new__(cls, name: str, day: Optional[date]=None):
        '''Override to use today's date when the `day` kwarg is omitted'''
        day = day or date.today()
        obj = super().__new__(cls, name, day)
        reveal_type(obj)  # Type of "obj" is "~HolidayBase" (Sure, that makes sense)
        obj.__slots__ = ()
        return obj

    def __str__(self):
        '''Friendlier string representation'''
        return f'{self.name} ({self.day.isoformat()})'

p = Holiday('Jellybean Day')  # No `day` argument
assert str(p) == f'Jellybean Day ({date.today().isoformat()})'  # Definitely behaves like an instance of Holiday
assert isinstance(p, Holiday)  # Python thinks it's an instance of Holiday
reveal_type(p)  # Type of "p" is "~HolidayBase" (Wait, what?)
```

**VS Code extension or command-line**
I'm running Pylance `v2021.10.3`, which according to their [`CHANGELOG.md`](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2021103-27-october-2021) includes Pyright `1.1.182`.

**Additional context**

Since the main reason to override `__new__` is to do custom things with immutable objects, there's a decent amount of discussion online about namedtuples specifically - but they seem to fall into two buckets: discussions that predate type annotations that do talk about overriding `__new__` (with examples using `collections.namedtuple` that look very like mine) but say nothing about types, and discussions that postdate type annotations but that only mention `typing.NamedTuple`, which (since that's a very different animal) don't usually apply very much to my situation.

If this isn't actually a bug and I'm holding it wrong, I would appreciate any tips about what I could do differently to address this kind of error, which is currently happening all over the place in my codebase:
```python
holidays: list[Holiday] = [Holiday(name) for name in ['Red Day', 'Blue Day', 'White Day']]
# Expression of type "list[~HolidayBase]" cannot be assigned to declared type "list[Holiday]"
```

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.183, which I just published. It will also be included in the next release of pylance.
