### ISSUE TITLE
mypy_path equivalent to add extra stub files

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#2514]
**Is your feature request related to a problem? Please describe.**
A project might write its own stub files for a different un-typed project, see https://github.com/pandas-dev/pandas/pull/44233.

**Describe the solution you'd like**
mypy has `mypy_path` to add additional stubs. Pyright has `--typeshed-path` but it would require to first clone typeshed and then add any custom stubs.

**Comment by jakebailey** [comment]
The canonical way to add types for libraries you're using is `typings`, which you can configure to point at a different directory if wanted (so, for the PR above, `stubs`). You may also be able to configure `extraPaths` to point at the stub, but that may not work without a `-stubs` suffix.

Both are configurable in a `pyrightconfig.json`.

**Comment by twoertwein** [comment]
Thank you, I didn't see this option!
