### ISSUE TITLE
Does pyright execute the module for intellisense during import?

### ISSUE THREAD

**Issue by SatyaKomatineni** [microsoft/pyright#255]
Note: Hello this is an informational question. I wasn't sure where to ask.

In VSCode does pyright execute the module for intellisense for import statements?

for example

#import some module
import someModule

#try to use it to see what variables are there
someModule.x
someModule.y

At run time "someModule" is executed because of "import"

But during code editing does "pyright" through the language server, does it actually execute the "someModule" to know the real variables that it exposes?

Thanks again and sorry for the inconvenience if this is not the right place.

I looked in the docs, esp "Module resolution" and perhaps that is addressing not this aspect
Sayta

**Comment by erictraut** [comment]
Pyright never "executes" any code — that is, it doesn't invoke the python interpreter to "run" any code. Pyright analyzes python code, so it's more akin to a compiler. Through this analysis, pyright determines which symbols (variables, classes, functions, etc.) will be exposed by each module at runtime.

Pyright will not attempt to analyze third-party library _implementations_. It relies on type stub files to define the public interface for third-party libraries. If you can't find an existing type stub file, pyright can help you generate the type stub. See https://github.com/microsoft/pyright/blob/master/docs/type-stubs.md for more details.
