### ISSUE TITLE
Can't pass generic class instance to generic class argument containing generic types

### ISSUE THREAD

**Issue by Gaming32** [microsoft/pyright#2555]
**Describe the bug**
When I call a function to get a generic (`Collector[_T@to_list, Any, List[_T@to_list]]`), and pass it to a method in a generic class accepting a compatible generic (`Collector[_T@Stream, Any, _R@collect]`), it marks the types as incompatible.

**Expected behavior**
I expect no issues to be thrown.

**Screenshots or Code**

```python
class Collector(abc.ABC, Generic[_T, _A, _R]):
    @staticmethod
    def of(supplier: Callable[[], _R], accumulator: Callable[[_R, _T], Any]) -> 'Collector[_T, _R, _R]':
        class WrapperCollector(Collector):
            def supplier(self) -> _R:
                return supplier()
            def accumulator(self, result: _R, value: _T) -> Any:
                return accumulator(result, value)
            def finisher(self, result: _R) -> _R:
                return result
        return WrapperCollector()


def to_list() -> Collector[_T, Any, List[_T]]:
    return Collector.of(list, list.append)


@final
class Stream(Generic[_T]):
    @staticmethod
    def range(start: int, stop: Optional[int] = None, step: Optional[int] = None) -> 'Stream[int]':
        if stop is None:
            r = range(start)
        elif step is None:
            r = range(start, stop)
        else:
            r = range(start, stop, step)
        return Stream(r)

    def collect(self, collector: Collector[_T, Any, _R]) -> _R:
        result = collector.supplier()
        for value in self.it:
            collector.accumulator(result, value)
        return collector.finisher(result)


def test():
    print(Stream.range(5)
                .collect(to_list()))
```
`collectors.to_list` gives the following error:
```
Argument of type "Collector[_T@to_list, Any, List[_T@to_list]]" cannot be assigned to parameter "collector" of type "Collector[int, Any, _R@collect]" in function "collect"
    TypeVar "_T@Collector" is invariant
      Type "_T@to_list" cannot be assigned to type "int" (reportGeneralTypeIssues)
```

**VS Code extension or command-line**

Tested with both the Pylance extension in "basic" typing mode, and the Pyright command-line.
Pylance extension: `v2021.11.0`
Pyright command-line: `pyright 1.1.186`

**Comment by erictraut** [comment]
I'm not able to diagnose the problem because your sample doesn't show what value is assigned to the `collectors` variable. Could you provide that missing piece? Also, it looks like you are calling `to_list` as a method, but it's defined as a non-method function in this sample.

**Comment by erictraut** [comment]
One problem I see is that `to_list` is a generic function with a function-scoped TypeVar `_T`, but it doesn't include `_T` in any input parameters. That means the constraint solver will have no way to "solve" `_T` in the scope of the generic function. The return value will remain generic with no way of replacing the function-scoped TypeVar.

**Comment by Gaming32** [comment]
> I'm not able to diagnose the problem because your sample doesn't show what value is assigned to the `collectors` variable. Could you provide that missing piece? Also, it looks like you are calling `to_list` as a method, but it's defined as a non-method function in this sample.

In the codebase, `to_list` is in the `collectors` module. The original comment has now been edited for clarity.

**Comment by Gaming32** [comment]
> One problem I see is that `to_list` is a generic function with a function-scoped TypeVar `_T`, but it doesn't include `_T` in any input parameters. That means the constraint solver will have no way to "solve" `_T` in the scope of the generic function. The return value will remain generic with no way of replacing the function-scoped TypeVar.

That is most likely the cause of the problem, but I can't think of a way to change that.

**Comment by erictraut** [comment]
Does this meet your needs?

```python
class CollectorList(Generic[_T]):
    @staticmethod
    def to_list() -> Collector[_T, Any, List[_T]]:
        return Collector.of(list, list.append)

Stream.range(5).collect(CollectorList[int].to_list())
```

**Comment by erictraut** [comment]
Another option is to have `to_list` return `Collector[Any, Any, List[Any]]`, but that eliminates some type safety.

**Comment by Gaming32** [comment]
Using a class worked. Thank you!

<details>
    <summary>Final code</summary>

```python
class to_list(Collector[_T, Any, List[_T]], Generic[_T]):
    def supplier(self) -> List[_T]:
        return []

    def accumulator(self, result: List[_T], value: _T) -> None:
        result.append(value)

    def finisher(self, result: List[_T]) -> List[_T]:
        return result
```
</details>
