### ISSUE TITLE
Mixing Typevar + Paramspec Bug

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#2557]
**Describe the bug**
Passing a function that has an argument using Typevar to a function using Paramspec leads to an error of argument can't match typevar. I have two examples that show error. The second example is simpler one while the first is based on code I originally had which also used Concatenate. 

**To Reproduce**
```python
from typing import Callable, TypeVar

from typing_extensions import Concatenate, ParamSpec

P = ParamSpec("P")
R = TypeVar("R")
T = TypeVar("T")


def foo(
    msg: str, f: Callable[Concatenate["str", P], R], *args: P.args, **kwargs: P.kwargs
) -> R:
    return f(msg, *args, **kwargs)


def util1(x: str, y: str) -> str:
    return x + y


def util2(x: str, y: T) -> T:
    return y


foo("hello", util1, "world")
foo("hello", util2, 5)  # error


def foo2(f: Callable[P, R], *args: P.args, **kwargs: P.kwargs) -> R:
    return f(*args, **kwargs)


foo2(util2, "hello", 4)  # error
reveal_type(foo2(util2, "hello", 4)) # T@util2
```

The first error message is,

```
Argument of type "Literal[5]" cannot be assigned to parameter of type "T@util2"
 Type "Literal[5]" cannot be assigned to type "T@util2"
```

while the second error message is, 

```
Argument of type "Literal[4]" cannot be assigned to parameter of type "T@util2"
  Type "Literal[4]" cannot be assigned to type "T@util2"
```

**Expected behavior**

No errors and that reveal_type on both calls that fail show int instead of T@.

**VS Code extension or command-line**
pyright 1.1.186.

**Comment by erictraut** [comment]
This situation involves a ParamSpec that captures a signature with parameters whose types include one or more unsolved TypeVars and then expecting the constraint solver to solve those TypeVars as well. This is a case that I can't currently accommodate in pyright's constraint solver. It's already highly complex, and adding this would be difficult. I think you'll need to find some other workaround for what you're trying to do here.

I'm willing to revisit this again in the future if mypy's implementation of ParamSpec supports this case.

**Comment by hmc-cs-mdrissi** [comment]
One smaller request then, would it be doable to have a more informative type error of Paramspec does not support capturing TypeVar arguments? I see that mixing paramspecs and overloads gives an error message of paramspec and overloads aren't supported together. Can this similarly be caught or is it hard to detect too?

Not a priority if a challenge. When writing these examples I ended up scanning over pep to double check if this was allowed or not as I wasn't even sure if this was legal.

**Comment by erictraut** [comment]
This condition would be hard to detect. It would need to be special-cased deep in the bowels of the constraint solver.

Yeah, I also don't know if this is allowed by the PEP. It might be a case that wasn't contemplated by the PEP authors. I certainly haven't run across it before in any code samples or bug reports.

**Comment by erictraut** [comment]
These cases are now supported.
