### ISSUE TITLE
Problem with comparison operators

### ISSUE THREAD

**Issue by fxdave** [microsoft/pyright#256]
**The bug:**
Python supports comparison operator chaining like: `1 < x < 2` .  
Pyright recognizes the first `1 < x` as bool and thinks I compare bool with 2, which is not a problem with numbers, but if I use for e.g datetime in comparison, datetime is not comparable with bool so it shows error.

**Expected behavior**
`1 < x < 2` should be marked as correct.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/12275699/65275878-da58be80-db26-11e9-9f73-167201751e9c.png)

**VS Code extension or command-line**
Python 2.7
Pyright 1.0.63

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release of pyright.

**Comment by erictraut** [comment]
This is now fixed in 1.0.64, which I just published.
