### ISSUE TITLE
Pyright not narrowing type of variable with `if variable in dict` condition

### ISSUE THREAD

**Issue by StockerMC** [microsoft/pyright#2564]
**Describe the bug**
Pyright isn't narrowing the type of a variable in an if statement checking if the variable is in a dict.

**Expected behavior**
The type of the variable to be narrowed, consistent with mypy's behaviour.

**Screenshots or Code**
```python
def main(a: int | None):
    d: dict[int, str] = {}

    if a in d:
        reveal_type(a)
        # pyright: int | None
        # mypy: int
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool?
Command line (pyright 1.1.187)

**Comment by erictraut** [comment]
This isn't a type narrowing pattern currently supported by pyright. For a complete list of supported patterns, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards).

We do occasionally add support for new patterns, but each one adds complexity and runtime overhead to the analysis, so we support only common patterns. I don't know if this pattern is sufficiently common to merit inclusion. It also requires hard-coding special-cased knowledge of the internal semantics of `dict` or `Mapping`, which is something we try to avoid in the type checker logic.

I'm going to close this feature request for now, but we might reconsider it in the future if others upvote it (i.e. give it a thumbs up).

**Comment by hmc-cs-mdrissi** [comment]
Hmm, why would this be for dict/mapping and not any [Container](https://docs.python.org/3/library/typing.html#typing.Container). If a in d works for dict I'd have guessed it'd also work for set/other container types. I just noticed the current type guard list has,

`x in y (where y is instance of list, set, frozenset, or deque)`

Where do these types come from? list/set are common, deque feels very rare so unsure what shared pattern they have is. Curious if `__contains__` could be typed like this,

```
class Container(Generic[T]):
  def __contains__(self, x: object) -> TypeGuard[T]:
    ...
```

and have it cover all containers (and subclasses overriding contains would also need to use TypeGuard). Or does `in` have more magic than `__contains__`.
