### ISSUE TITLE
ClassVar should not allow TypeVar

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#2567]
PEP 526 says:

> Note that a ClassVar parameter cannot include any type variables, regardless of the level of nesting: ClassVar[T] and ClassVar[List[Set[T]]] are both invalid if T is a type variable.

See [this issue](https://github.com/python/mypy/issues/11538) in mypy issue tracker.

**Comment by hmc-cs-mdrissi** [comment]
I'm guessing the rule should also be extended to cover Paramspec/Typevartuple? The motivation seems like it applies for all generic parameters. Probably much rarer for the other two given usage frequency though.

**Comment by erictraut** [comment]
The next release will contain a new diagnostic check for a TypeVar used within ClassVar. It covers ParamSpec and TypeVarTuple as well. Internally, pyright treats these as special forms of TypeVar.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.188, which I just published. It will also be included in the next release of pylance.
