### ISSUE TITLE
Union[SomeType|None] not correctly discriminated by condition

### ISSUE THREAD

**Issue by LiamAttClarke** [microsoft/pyright#2572]
**Description**

Discriminating a Union type fails when symbol is immediately used in a function invocation.

**To Reproduce**

### Case 1 (Failure)
```python
some_flag = True
possibly_null_value: Union[SomeType, None]

def do_something(item: SomeType):
    pass

if some_flag and possibly_null_value:
    do_something(possibly_null_value) # Red Squiggle!
```
The red squiggle reads:
```
Argument of type "SomeType | None" cannot be assigned to parameter "item" of type "SomeType" in function "do_something"
  Type "SomeType | None" cannot be assigned to type "SomeType"
    Type "None" cannot be assigned to type "SomeType"
```

### Case 2 (Success)
```python
some_flag = True
possibly_null_value: Union[SomeType, None]

def do_something(item: SomeType):
    pass

if some_flag and possibly_null_value:
    temp = possibly_null_value # type of `temp` is correctly evaluated to `SomeType`
    do_something(temp) # No Red Squiggle!
```

**Expected behavior**

Symbols of type `Union[SomeType, None]` should evaluate to `SomeType` when discriminating condition tests for `None` case.

**VS Code extension or command-line**

Editor: Visual Studio Code
Extension: Pylance v2021.11.1

**Comment by erictraut** [comment]
I'm not able to repro the problem. The code sample as specified isn't valid, so I've needed to fill in some details. Perhaps I've gotten some of the details wrong?

```python
from typing import Union

class SomeType:
    ...

some_flag = True

def do_something(item: SomeType):
    pass

def func(possibly_null_value: Union[SomeType, None]):
    if some_flag and possibly_null_value:
        do_something(possibly_null_value)
```

This doesn't result in any errors for me.

**Comment by LiamAttClarke** [comment]
This ended up resolving itself after reloading my language server 🤷.

I'm no longer able to reproduce this case.

Sorry for the trouble!
