### ISSUE TITLE
Add `type(x) is type(y)` type narrowing

### ISSUE THREAD

**Issue by Zomatree** [microsoft/pyright#2573]
**Is your feature request related to a problem? Please describe.**
Currently `type(x) is type(y)` does not narrow `y` to be of type `x` when the type of `x` is known.

For example:
```py
def test(v1: str, v2: Any):
    if type(v1) is type(v2):
        reveal_type(v2)  # Any
```

**Describe the solution you'd like**
The solution i would expect is that `v2` is narrowed down to be of type `v1`, in this case, a `str`

**Comment by erictraut** [comment]
This isn't a type narrowing pattern currently supported by pyright. For a complete list of supported patterns, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards).

Each new pattern requires specialized code that adds complexity and potentially slows down analysis. We do occasionally add new support for new patterns but only in cases where we get a signal that it's a commonly-used idiom. We use two ways to gather that signal: 1) upvotes on issues, and 2) support for the pattern in other Python type checkers like mypy. In this particular case, I've never personally seen this pattern used in Python code. Mypy also doesn't support this pattern, and I don't see any feature requests in the mypy issue tracker requesting this feature. So I don't think this is a common enough pattern for us to support at this time. We can revisit this decision in the future if this issue receives enough upvotes.

I'm going to close this feature request for now, but we might reconsider it in the future if others upvote it (i.e. give it a thumbs up).

You might be able to make this pattern work with a user-defined TypeGuard. For details, refer to [PEP 647](https://www.python.org/dev/peps/pep-0647/).

**Comment by Zomatree** [comment]
Is this not classed under "`type(x) is T` and `type(x) is not T`"?

**Comment by erictraut** [comment]
T has to be a static type.

**Comment by erictraut** [comment]
Furthermore, the supported pattern narrows the type of the LHS expression, not the RHS expression.
