### ISSUE TITLE
Type inference for function parameters not resolved 

### ISSUE THREAD

**Issue by rajdeep87** [microsoft/pyright#2576]
**Is your feature request related to a problem? Please describe.**
Pyright support type inference for function return values, instance variables, class variables, and globals.
However, in the code below, Pyright cannot resolve the types for function parameter, `s3_client`, in the method, `load_df_from_s3`. 

The Pyright types is denoted by the line `Pyright type --> ` in the annotated code below. Note that these types are inferred using an external type stub.   

**Query:** 
Is there any inherent limitation of Pyright to not resolve the type for function parameter, `s3_client`, in the method, `load_df_from_s3`? Or the type inference in Pyright can be extended to infer the type of function parameter in this case?

```python
def write_df_to_s3_location(file_path, bucket_name, metadata_material_set, sep=None):
    s3_client = create_s3_client()
        **{Pyright type --> s3_client: (S3Client)}**
    df = load_df_from_s3(s3_client, bucket=bucket_name, path="")
    	**{Pyright type --> (variable) df: DataFrame}**
    s3_client.put_object(Body=file_path, Bucket=bucket_name)

def create_s3_client():
    return boto3.client("s3")
    **{Pyright type --> (function) create_s3_client: () -> S3Client}**

def load_df_from_s3(s3_client, bucket, path):
   **{Pyright type --> (function) load_df_from_s3: (s3_client, bucket, path) -> DataFrame}**
   raw_date = None
    try:
        raw_data = s3_client.get_object(Bucket=bucket_name, Key=object_path)
	**{Pyright type --> s3_client: (Any)}**
    except ClientError as e:
        logging.info("Bucket: {}, error {}", bucket_name, str(e))
    io_data = StringIO(raw_data)
    df = pd.read_csv(io_data)
    return df
``` 

**Describe the solution you'd like**
 The inferred type for function parameter, `s3_client`, in the method, `load_df_from_s3` should be `S3Client`.

**Comment by erictraut** [comment]
You are missing type annotations for the input parameters to the functions, so all of their types will be assumed to be `Any`. Types of input parameters cannot be inferred. You need to annotate them.

**Comment by rajdeep87** [comment]
Thank you for the quick response. This is helpful!

I have a follow-up question below.
> Types of input parameters cannot be inferred. You need to annotate them.
Is this due to some limitation of Pyright that it cannot infer the type of input parameters? Or the types of input parameters can never be inferred for functions in Python?

**Comment by erictraut** [comment]
If you don't provide the type of a symbol, pyright will infer it. However, in the case of input parameters, the inferred type is "Any", so you lose the value of type checking. In the case of an assignment to a local variable, pyright can infer the type based on the assigned value.

When pyright analyzes the implementation of a function, it can't know all of the ways the function might be called. 

Think of input parameter annotations as documenting your assumptions about what types are accepted by the function. It's the job of a static type analyzer to then verify whether those assumptions are broken anywhere.

For more details about static type checking in Python, refer to PEP 483 and 484 and [python/typing](https://github.com/python/typing/tree/master/docs).
