### ISSUE TITLE
Constraining Union types of dictionaries with if statements

### ISSUE THREAD

**Issue by nickmagginas** [microsoft/pyright#2582]
Hi when having a Union of dictionary types e.g. ```Union[dict[str, int], dict[str, dict[str, int]]]``` is there an appropriate if statement check to constraint the type of a variable with this type to a single member of the Union. 

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python

UnionType = Union[dict[str, int], dict[str, dict[str, int]]]

def foo(a: UnionType):
    if all(isinstance(value, int) for value in a.items()):
           b = a
    c = a
```

**Expected behaviour**
The type of b should be dict[str, int] but it is UnionType. Is there an appropriate check which will constraint the type of a to dict[str, int] within the if statement.

Thank you very much in advance for your reply and for open sourcing this beautiful tool.

**Comment by erictraut** [comment]
You would need to use a user-defined type guard function as defined in [PEP 647](https://www.python.org/dev/peps/pep-0647/). Search for `is_str_list` within the PEP for an example that's similar to yours.
