### ISSUE TITLE
Localization of error messages

### ISSUE THREAD

**Issue by coolkit-carl** [microsoft/pyright#259]
Like ts

![微信截图_20190924105336](https://user-images.githubusercontent.com/50738270/65477923-72a1cb00-deba-11e9-986b-019d80af6f71.png)

![微信截图_20190924105351](https://user-images.githubusercontent.com/50738270/65478001-ab41a480-deba-11e9-8410-c901484d0438.png)

**Comment by erictraut** [comment]
Thanks for the suggestion. This will require two very large pieces of work:
1. Adding localization support in pyright for all error and warning strings.
2. Providing localized strings for Chinese (and other languages).

I can do #1, but I will need help from the community on #2.

This is a low priority compared to other features in the queue, so it may be a while before I get to it.

**Comment by erictraut** [comment]
String localization support is now implemented in Pyright 1.1.40. Translations are not yet provided for any languages other than English, but the support is now in place.
