### ISSUE TITLE
Strange recursive generic not accepted on __init__ overload

### ISSUE THREAD

**Issue by bellini666** [microsoft/pyright#2593]
I'm adding some types to https://github.com/sbdchd/django-types and I had some trouble with `ArrayField` and a weird issue that I'm not sure how to describe. I created a small and very simplified example that can reproduce the issue without requiring django and all of its attributes:

```python
from typing import Any, Generic, List, Literal, Optional, TypeVar, overload

_T = TypeVar("_T", bound="Field[Any, Any]")
_ST = TypeVar("_ST", contravariant=True)
_GT = TypeVar("_GT", covariant=True)
_V = TypeVar("_V")


class Field(Generic[_ST, _GT]):
    def __set__(self, instance: Any, value: _ST) -> None:
        ...

    @overload
    def __get__(self: _T, instance: None, owner: Any) -> _T:
        ...

    @overload
    def __get__(self, instance: Any, owner: Any) -> _GT:
        ...


_C = TypeVar("_C", bound=Optional[str])


class CharField(Generic[_C], Field[_C, _C]):
    @overload
    def __new__(
        cls,
        *args: Any,
        null: Literal[False] = ...,
        **kwargs: Any,
    ) -> "CharField[str]":
        ...

    @overload
    def __new__(
        cls,
        *args: Any,
        null: Literal[True],
        **kwargs: Any,
    ) -> "CharField[Optional[str]]":
        ...


class ArrayField(Generic[_V], Field[_V, _V]):
    @overload
    def __init__(
        self: "ArrayField[List[_V]]",
        base_field: Field[Any, _V],
        null: Literal[False] = ...,
    ) -> None:
        ...

    @overload
    def __init__(
        self: "ArrayField[Optional[List[_V]]]",
        base_field: Field[Any, _V],
        null: Literal[True] = ...,
    ) -> None:
        ...

    @overload
    def __new__(
        cls,
        base_field: Field[Any, _V],
        *args: Any,
        null: Literal[False] = ...,
        **kwargs: Any,
    ) -> "ArrayField[List[_V]]":
        ...

    @overload
    def __new__(
        cls,
        base_field: Field[Any, _V],
        *args: Any,
        null: Literal[True],
        **kwargs: Any,
    ) -> "ArrayField[Optional[List[_V]]]":
        ...


class Foo:
    array = ArrayField(
        CharField(),
    )
    matrix = ArrayField(
        ArrayField(
            CharField(),
        ),
    )


reveal_type(Foo.array)
reveal_type(Foo.matrix)
reveal_type(Foo().array)
reveal_type(Foo().matrix)
```

That is pretty similar to what we can do to django. Basically we have an `ArrayField` that defines its inner field, which can also be another `ArrayField`. So, in that example, `ArrayField(CharField)` makes a descriptor that sets/gets `List[str]`. `ArrayField(ArrayField(CharField))` makes a descriptor that sets/gets `List[List[str]]`

If you try to run the current pyright version on that example it work nice for `array`, but `matrix` will have problems with the attribute definition. Like this:

```
  /tmp/baz.py:88:9 - error: Argument of type "ArrayField[List[str]]" cannot be assigned to parameter "base_field" of type "Field[Any, _V@ArrayField]" in function "__init__"
    TypeVar "_GT@Field" is covariant
      Type "List[_V@ArrayField] | None" cannot be assigned to type "List[str]" (reportGeneralTypeIssues)
  /tmp/baz.py:94:13 - info: Type of "Foo.array" is "ArrayField[List[str]]"
  /tmp/baz.py:95:13 - info: Type of "Foo.matrix" is "ArrayField[Unknown]"
  /tmp/baz.py:96:13 - info: Type of "Foo().array" is "List[str]"
  /tmp/baz.py:97:13 - info: Type of "Foo().matrix" is "Unknown"
```

There are 4 things that I can do that will fix that issue:

1) Remove `__init__` altogether. This works because `__new__` is not suffering the same issues and it the one that pyright considers when identifying the typing of the array and capturing the inner generics of the internal fields. This is not actually an option there because it has to support mypy too, and mypy seems to prefer the use `__init__` only (also, `__init__` will help pyright validate the available arguments for it)

2) Remove the typing from `self` and have a single `__init__` with the options for arguments validation and completion. The same as before, but also a problem for `mypy` because it relies on that typing. Like this:

```python
    def __init__(self, base_field: Field[Any, _V], null: bool = ...) -> None:
        ...
```

3) Remove only the typing from `self: "ArrayField[Optional[List[_V]]]"` but still keep the one for `self: "ArrayField[List[_V]]"`. Apparently that single change is enough to make the issues go away. Again, not an option for mypy. The change looks like this:

```python
    @overload
    def __init__(
        self: "ArrayField[List[_V]]",
        base_field: Field[Any, _V],
        null: Literal[False] = ...,
    ) -> None:
        ...

    @overload
    def __init__(
        self,
        base_field: Field[Any, _V],
        null: Literal[True] = ...,
    ) -> None:
        ...
```

4) Add 2 extra overloads that uses `Sequence` instead of `List`. We could only use sequence and the typing would still be correct, but again, mypy uses `__init__` and it would type the field descriptor as `Sequence[Sequence[str]]` which is incorrect since it really gets/sets lists. The change looks like this:

```python
    @overload
    def __init__(
        self: "ArrayField[List[_V]]",
        base_field: Field[Any, _V],
        null: Literal[False] = ...,
    ) -> None:
        ...

    @overload
    def __init__(
        self: "ArrayField[Optional[List[_V]]]",
        base_field: Field[Any, _V],
        null: Literal[True] = ...,
    ) -> None:
        ...

    @overload
    def __init__(
        self: "ArrayField[Sequence[_V]]",
        base_field: Field[Any, _V],
        null: Literal[False] = ...,
    ) -> None:
        ...

    @overload
    def __init__(
        self: "ArrayField[Optional[Sequence[_V]]]",
        base_field: Field[Any, _V],
        null: Literal[True] = ...,
    ) -> None:
        ...
```

Either of those 4 alternatives will yield this result:

```
/tmp/baz.py
  /tmp/baz.py:110:13 - info: Type of "Foo.array" is "ArrayField[List[str]]"
  /tmp/baz.py:111:13 - info: Type of "Foo.matrix" is "ArrayField[List[List[str]]]"
  /tmp/baz.py:112:13 - info: Type of "Foo().array" is "List[str]"
  /tmp/baz.py:113:13 - info: Type of "Foo().matrix" is "List[List[str]]"
```

Which is the correct and expected typing.

Now, like I said, I don't know exactly how to explain the issue, but is seems weird to me that the error presents itself in only a specific case (e.g. the option number 2 fixes it for some strange reason), while also not having the same issues for `__new__`.

Don't know also if I'm doing something wrong with the typing, but at the PR I created there I chose alternative number 4 (which is the only mypy friendly option) and it worked, but it seems to me that the original example should work without issues too.

Please tell me if you need any more info regarding this.

**Comment by erictraut** [comment]
It's unusual to include both `__new__` and `__init__` in a stub, since the signatures are typically redundant. Is there a reason you want to include both? Unless there's a good reason to do so, I recommend using just one or the other, not both.

In both the `__new__` and `__init__`, you've defined overloads for when `null` is `True` and `False`, but you haven't provided any overload for when the type of `null` is a `bool` (i.e. its value can't be determined statically or a default argument is assumed). I recommend that you provide a "fallback" overload that handles this case.

The instrumented `self` type in an `__init__` method is not specified in any PEP. It's a bit of a hack that was introduced in mypy and is now a loose convention, but it has unfortunately never been fully documented or spec'ed. I added limited support for it in pyright, but due to the lack of specification, it's quite possible that there are differences in assumptions. I'm very uncomfortable with the annotated `self` hack because it's an abuse of the type system, and it creates a bunch of ill-defined edge cases. The PEP review process is designed to identify and resolve issues like this, but unfortunately this never went through a comprehensive review or specification process.

You mentioned that "option 1" doesn't work with mypy. What problem are you seeing? I ran the latest version of mypy on your sample with the `__init__` method commented out, and it seemed to produce the right results without any errors.

**Comment by bellini666** [comment]
Hi @erictraut , thanks for the reply! The example I provided is a minimal one just to display the issue. The reason some things cannot be done another way (at least not at the moment) is mostly mypy compatibility. I'll try to explain bellow with some examples:

> It's unusual to include both __new__ and __init__ in a stub, since the signatures are typically redundant. Is there a reason you want to include both? Unless there's a good reason to do so, I recommend using just one or the other, not both.

Yes, I would really like to use just one, but to achieve what I want and have compatibility with both pyright and mypy, even though in this example a single one would be enough, there's another part of it that I omitted to keep the demo "simple", but let me show you here:

```python
from typing import Any, Generic, Literal, Optional, Sequence, Tuple, TypeVar, overload

_T = TypeVar("_T", bound="Field[Any, Any]")
_ST = TypeVar("_ST", contravariant=True)
_GT = TypeVar("_GT", covariant=True)
_V = TypeVar("_V")


class Field(Generic[_ST, _GT]):
    def __set__(self, instance: Any, value: _ST) -> None:
        ...

    @overload
    def __get__(self: _T, instance: None, owner: Any) -> _T:
        ...

    @overload
    def __get__(self, instance: Any, owner: Any) -> _GT:
        ...


_C = TypeVar("_C", bound=Optional[str])


class CharField(Generic[_C], Field[_C, _C]):
    @overload
    def __new__(
        cls,
        *args: Any,
        null: Literal[False] = ...,
        choices: None = ...,
        **kwargs: Any,
    ) -> "CharField[str]":
        ...

    @overload
    def __new__(
        cls,
        *args: Any,
        null: Literal[True],
        choices: None = ...,
        **kwargs: Any,
    ) -> "CharField[Optional[str]]":
        ...

    @overload
    def __new__(
        cls,
        *args: Any,
        null: Literal[False] = ...,
        choices: Sequence[Tuple[_C, str]] = ...,
        **kwargs: Any,
    ) -> "CharField[_C]":
        ...

    @overload
    def __new__(
        cls,
        *args: Any,
        null: Literal[True],
        choices: Sequence[Tuple[_C, str]] = ...,
        **kwargs: Any,
    ) -> "CharField[Optional[_C]]":
        ...


class Foo:
    char = CharField()
    char_nullable = CharField(null=True)
    char_with_choices = CharField(
        choices=[
            ("A", "Choice A"),
            ("B", "Choice B"),
        ],
    )
    char_with_choices_nullable = CharField(
        choices=[
            ("A", "Choice A"),
            ("B", "Choice B"),
        ],
        null=True,
    )


reveal_type(Foo.char)
reveal_type(Foo.char_with_choices)
reveal_type(Foo.char_nullable)
reveal_type(Foo.char_with_choices_nullable)
```
This will produce:
```
  # pyright
  /tmp/foo.py:85:13 - info: Type of "Foo.char" is "CharField[str]"
  /tmp/foo.py:86:13 - info: Type of "Foo.char_with_choices" is "CharField[Literal['A', 'B']]"
  /tmp/foo.py:87:13 - info: Type of "Foo.char_nullable" is "CharField[str | None]"
  /tmp/foo.py:88:13 - info: Type of "Foo.char_with_choices_nullable" is "CharField[Literal['A', 'B'] | None]"

  # mypy
foo.py:85: note: Revealed type is "foo.CharField[builtins.str]"
foo.py:86: note: Revealed type is "foo.CharField[builtins.str]"
foo.py:87: note: Revealed type is "foo.CharField[Union[builtins.str, None]]"
foo.py:88: note: Revealed type is "foo.CharField[Union[builtins.str, None]]"
```

I have to have those 4 `__new__` overloads, one for each possibility of null = True/False and the capture of the choices, which will then make the type only accept get/set as `Literal` of choices.

I can't remove any of those 4 possibilities. For example, trying to remove the first 2 `__new__` will make the definition without choices still be generic (i.e. `"CharField[_C@CharField]"` while the one with choices still reads `"CharField[Literal['A', 'B']]"`)

But ok, having accepted the fact that I have to define those 4 overloads, so far so good.

But then it comes the fact that django fields have a lot of arguments. Close to 22 specifically, not counting the ones that are specific for some fields. I didn't want to have to specify those 22 arguments 4 times, which not only isn't practical but is very error prune, so I had the idea of defining just the essential to define the type itself (those 4 overloads, just like I described), with both `*args` and `**kwargs`, and specify all the options in a single `__init__`.  For example, using that exact example above but adding this to `CharField`:

```python
    def __init__(
        self,
        verbose_name: Optional[str] = ...,
        name: Optional[str] = ...,
        primary_key: bool = ...,
        max_length: Optional[int] = ...,
        unique: bool = ...,
        blank: bool = ...,
        null: bool = ...,
        db_index: bool = ...,
        default: Optional[_C] = ...,
        editable: bool = ...,
        auto_created: bool = ...,
        serialize: bool = ...,
        unique_for_date: Optional[str] = ...,
        unique_for_month: Optional[str] = ...,
        unique_for_year: Optional[str] = ...,
        choices: Sequence[Tuple[_C, str]] = ...,
        help_text: str = ...,
        db_column: Optional[str] = ...,
        db_tablespace: Optional[str] = ...,
        validators: Iterable[Callable[..., None]] = ...,
        error_messages: Optional[Dict[str, Any]] = ...,
    ) -> None:
        ...
```

You will notice that pyright still reveals the same types as before, but now mypy will say that `char` and `char_nullable` (the ones without choices) requires type annotations and will type then as `Any`.

I worked around that by defining 2 overloads for `__init__` and defining `self: CharField[str]` and `self: CharField[Optional[str]]` and that fixes mypy. It still doesn't capture the literal from choices, but id didn't even before. Also, unless the signature for the field changes (which happens for some fields, but not all), I can define just one on the base field itself (the `Field`) and I just have to define the 4 `__new__` overloads in the subclasses. E.g. the `CharField`, `IntegerField`, `BooleanField` would all need to just define the `__new__` since the `Field.__init__` defines the 2 overloads that validates the possible arguments.

This works fine for both pyright and mypy.

The `ArrayField` is a case that the `__init__` signature differs from the `Field`, so I have to define those in it too. And after defining it and having the issue I'm describing here I decided to come to ask if that error in question is something that maybe pyright is doing "wrong" (leaving aside the fact that I'm having to define that `__init__` because of mypy's issues).

> In both the __new__ and __init__, you've defined overloads for when null is True and False, but you haven't provided any overload for when the type of null is a bool (i.e. its value can't be determined statically or a default argument is assumed). I recommend that you provide a "fallback" overload that handles this case.

I don't know if I'm the typing is doing something wrong here (you will for sure understand it better than me), but at `__new__` it defines it as `null: Literal[False] = ...,` and the other one as `null: Literal[True],`, which makes the `True` be considered only if defined explicitly, and `False` be considered if defined explicitly or not defined (hence the `...`), which should make it be the default value (which really is). I didn't provide an example of it specifically in the first post, but you can see in the example in this comment that it works just like that!

In the `__init__` I would really like to define just the signature, like the example I wrote in this comment above (i.e. `null: bool = ...`), but I had to define both the literals for mypy.

Having said that all, are you seeing any possibility of simplifying or something that might go wrong with that that I'm not aware?

> The instrumented self type in an __init__ method is not specified in any PEP. It's a bit of a hack that was introduced in mypy and is now a loose convention, but it has unfortunately never been fully documented or spec'ed. I added limited support for it in pyright, but due to the lack of specification, it's quite possible that there are differences in assumptions. I'm very uncomfortable with the annotated self hack because it's an abuse of the type system, and it creates a bunch of ill-defined edge cases. The PEP review process is designed to identify and resolve issues like this, but unfortunately this never went through a comprehensive review or specification process.

I agree! I would love that mypy used only `__new__` so I could define a single `__init__` for the 22 arguments validation. Mypy works when I define only `__new__`, but will get very confused as soon as I define `__init__` and don't type `self` accordingly.

So, I could write 4 `__new__` overloads for all the more than 30 `Field` subclasses, each one with 22 different arguments (some more), but that seems kinda insane to me. I chose to define 2 `__init__` on `Field` only and the 4 `__new__` for all the fields with only the necessary stuff to make the "magic typing" work (i.e. null and choices). I only have to define `__init__` again for some specific fields that have different signatures (there aren't many), and `ArrayField` is one of those.

And the option of defining those 4 `__new__` on the base `Field` doesn't work because I can't say that it returns something dynamic. If I did that I would `reveal_type` on the class `CharField` and it would return `Field[str, str]` instead of `CharField[str]`. Hence, all those 4 `__new__` are basically ctrl+c/ctrl+v, only changing the returned type to the class itself.

> You mentioned that "option 1" doesn't work with mypy. What problem are you seeing? I ran the latest version of mypy on your sample with the __init__ method commented out, and it seemed to produce the right results without any errors.

My previous example was a very simplified one that didn't contain the issue to why the alternative didn't work with mypy. I just wanted to show the typing issue in an isolated code (without relying on django stuff). Well, if you got this far you already understood that from my very long explanation.

ps. Also sorry for the very long text. I wanted to make sure that everything was properly explained since it is a very "complex" typing case (at least IMO).

**Comment by erictraut** [comment]
You lost me somewhere in all of that. If I understand you correctly, your goal is to avoid duplicating a bunch of parameters in overload signatures. The approach you're pursuing is a clever idea, but you're straying into parts of the type system that are poorly defined and therefore produce different results between type checkers. I recommend sticking with the straightforward and well-defined approach even if it requires duplication of signatures.

**Comment by bellini666** [comment]
Hey @erictraut , yeah sorry about that :(. I sometimes "overdo" in my explanation, but don't really know how to properly explain why all the "correct possibilities" doesn't work because of some things that pyright does different than mypy.

In summary, IMO I agree with you and I think that pyright is doing the right thing, but to keep compatibility with mypy in that code I need to workaround some issues in some ways that I consider counter productive, like having defining a 30 lines __new__ 4 times for 30 different fields.

Having said that, I'll consider your recommendation and, regarding this issue, you can probably close it.

But just want to make sure: Even though the whole approach described is "not ideal", the main issue that I described here is something that pyright can workaround? Or is it really something that is not intended to work, and when it works it is working "in spite of" instead of "because of"?

**Comment by bellini666** [comment]
Hey @erictraut ,

> I'm not sure how to interpret your last question. Which "main issue" are you referring to? You mentioned a bunch of different approaches above and different reasons why each of them didn't work.

I mean [the initial comment itself](https://github.com/microsoft/pyright/issues/2593#issue-1060786432).

The many approaches was an attempt to reply to your questions to "why I was trying to do things that way" since, for example, defining both `__new__` and `__init__` together does not make sense. I think I overdid in that reply and conducted the focus of the discussion to something else.

To be very specific at the comment itself, the main thing I'm referring to is this typing error.

```
  /tmp/baz.py:88:9 - error: Argument of type "ArrayField[List[str]]" cannot be assigned to parameter "base_field" of type "Field[Any, _V@ArrayField]" in function "__init__"
    TypeVar "_GT@Field" is covariant
      Type "List[_V@ArrayField] | None" cannot be assigned to type "List[str]" (reportGeneralTypeIssues)
```

I understand that the whole approach is not the correct one, but looking at this specific error and the reason to why it happens in that demo, could that be something that is actually a real pyright issue? Like, the same error doesn't happen neither for the `__new__`, even though they have the same typings and falls into the same overload rules, and the strangest thing that it is only present at the specific `ArrayField[List[str]]` overload, but the `ArrayField[Optional[List[str]]]` doesn't raise the same error message. The fact that similar code produces different results worries me here.

**Comment by erictraut** [comment]
That typing error is due to the use of a type variable within a type annotation on `self` within an `__init__` method. That gets deep into "unspecified" territory.

When I implemented support for annotated `self` within an `__init__` method, I specifically limited it to concrete types with no type variables. That was intended. I felt uncomfortable doing even that, but I didn't have much of a choice because typeshed stubs started to use this pattern in a handful of situations. I was assured at the time that only concrete types would ever be used for such annotations.

**Comment by bellini666** [comment]
Ok, I see. So, based on your response I'm understanding that this is a "wontfix" kind of issue, right? Np, I'll workaround that issue in some other way! Thank you so much for your responses!
