### ISSUE TITLE
Document how to run Pyright from a git branch

### ISSUE THREAD

**Issue by gwk** [Microsoft/pyright#26]
I just tried out Pyright and am encountering internal errors. I would like to run Pyright directly from a git branch, or if that is not possible, then with minimal fiddling, so that I can file bug reports against master (or whatever branch I should be testing).

I have been using mypy for quite a while now, and I've found that the only way I can be productive is if:
* I can install and run the latest branch of mypy;
* I can typecheck with my own fork of typeshed (which I can then make PRs from).

I think if the developers took a few minutes to make a short list of setup steps in `docs/` then they would see a payoff pretty quickly in terms of bug reports, PRs and relevant fixes to typeshed.

Pyright looks great, and I'd love to start using it! Thanks.

**Comment by erictraut** [comment]
Thanks for the suggestion. Just to clarify, are you looking for setup steps for how to debug problems and modify Pyright's code? Or are you more interested in how to configure it for your own use?

I'm currently publishing pyright on a frequent basis (multiple times a week), so the latest branch is never more than a few days from the published version.

Pyright has a configuration option for pointing to your own fork of typeshed. See docs/configuration for more details.

**Comment by jeremyBanks** [comment]
I'm not sure if this is the same confusion as the OP, but FWIW when I first downloaded and built pyright (from a release tag) I was confused because it didn't seem to be using the built-in typeshed definitions by default, so it was complaining that things like `instanceof` weren't defined. The actual installed release build seems to use these automatically, but I eventually realized I needed to specify `-t dist/typeshed-fallback` to get the same behaviour when I built myself. Perhaps that could be clarified (or fixed, if that isn't supposed to be necessary).

**Comment by gwk** [comment]
What I would like to do is set up my Pyright installation so that the `pyright` executable on my PATH is whatever version I choose to check out in git. The point is to make verifying a bug against the very latest version of Pyright as painless as possible; otherwise I will eventually file something that has already been fixed, which is a discouraging waste of everyone's time, and fairly common in my experience.

With python it's usually as simple as checking out the repo, e.g. mypy, and running `pip3 install -e .`. I don't know what the appropriate steps are for a node/npm project like this. Part of the reason I filed this is because the setup for mypy is actually a bit more convoluted due to the way they track typeshed as a submodule; it sounds like this is not necessary for Pyright.

 Ideally I could set up this way for both command line and VSCode extension, although the latter might be a stretch depending on how it all works.

**Comment by gwk** [comment]
Furthermore, a setup like this makes it possible for me to fork/branch and try out a fix to any issue that I encounter. While I don't expect to be a huge contributor, I am very interested in this project and would like to be in a position to help.

**Comment by erictraut** [comment]
I added the following [documentation](https://github.com/Microsoft/pyright/blob/master/docs/build-debug.md). Let me know what you think.

**Comment by gwk** [comment]
I just read through, and this is a great start. The crucial thing that is missing though is how to make a drop-in replacement of `pyright` appear in the PATH. this is really crucial because the typical situation is that I am working on my own python project, I run `make typecheck` or whatever that calls pyright, and I hit a bug in pyright. The first thing I want to do is pull the latest pyright master, and if that fixes it, great. If not, I can file a bug. Does that make sense?
