### ISSUE TITLE
Generator annotated as returning list

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#2604]
I get no errors for this code:
```python
def f() -> list[str]:
    yield "x"
```
But clearly the function doesn't return a list.

I'm in VSCode, pylance v2021.11.2.

**Comment by erictraut** [comment]
This will be addressed in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.190, which I just published. It will also be included in the next release of pylance.
