### ISSUE TITLE
Document setting configuration option via python comment

### ISSUE THREAD

**Issue by Tomaz-Vieira** [microsoft/pyright#2613]
**Is your feature request related to a problem? Please describe.**
[This comment](https://github.com/microsoft/pyright/issues/144#issuecomment-554683778) seems to be the only mention of the ability to change pyright's configuration settings via python comments. The syntax seems to have changed too, since the comment mentions a json-like syntax (`# pyright: reportMissingTypeStubs: false`), but I can only get it to work with an asignment-like syntax (`# pyright: reportMissingTypeStubs=false`). This is made stranger by the fact that setting `strict` via a comment has its own special syntax that doesn't look like an assignment or an append to the `strict` array in the config json.

**Describe the solution you'd like**
Some mention of this feature in `configuration.md`, if it's still intended to be used.

**Comment by erictraut** [comment]
This functionality is documented [here](https://github.com/microsoft/pyright/blob/main/docs/comments.md).
