### ISSUE TITLE
Option to disable automatic triggering of the function help popup.

### ISSUE THREAD

**Issue by CAPTAIN1947** [microsoft/pyright#2617]
**Is your feature request related to a problem? Please describe.**
pyright shows the parameter help popup every time I write a opening bracket parenthesis after a function.
I don't need the parameter help of the functions I use regularly. But I need it sometimes. 
So the option shouldn't disable it permanently. It should only disable the automatic triggering.

**Describe the solution you'd like**
I want to have a option to disable the automatic triggering of the popup. But that option shouldn't permanently disable it. We should be allowed to trigger it manually.

**Additional context**
OS: Windows 10
Text Editor: Sublime 4121
I wanted the same thing with autocompletion and sublime gives a built-in settings to do this but there's nothing like this for the parameter popup.

**Comment by erictraut** [comment]
The popup is displayed by your client. It's not under the control of pyright (the language server) if and when to display this. Which client (editor) are you using? You could talk to the maintainers of that client about your suggestion.

**Comment by CAPTAIN1947** [comment]
```Which client (editor) are you using?```
Sublime. (lsp-pyright)
Ok. I will ask there.
 Thank You.
