### ISSUE TITLE
Error in derived class with derived instance attribute

### ISSUE THREAD

**Issue by hacker-DOM** [microsoft/pyright#2621]
**Describe the bug**
Not 100% sure this is a bug, but it's certainly not expected: I have code such as that below.

```python
class ItemA:
    pass
    
class ItemB(ItemA):
    pass

class ContainerA:
    def __init__(self, item: ItemA) -> None:
        super().__init__()
        self.item = item
        
class ContainerB(ContainerA):
    def __init__(self, item: ItemB) -> None:
        super().__init__(item)
        
    def do_something_with_item(self):
       do_something_with_item_b(self.item) 
        
def do_something_with_item_b(item: ItemB):
    pass
```

I would expect the code not to give type errors, but it does.[1]

**Steps to reproduce**
1. Create a file with the code above.
2. Run `pyright [file]`

**VS Code extension or command-line**
I am running `pyright@1.1.190` (the latest version of `pyright` as of Nov 27, 21).

**Questions**
What is a workaround? Is it to declare the instance attribute as such? Thank you!

```python
class ContainerB(ContainerA):
    item: ItemB
    [...]
```

[1] I get the following error in the argument in the call to `do_something_with_item_b`.

```
Argument of type "ItemA" cannot be assigned to parameter "item" of type "ItemB" in function "do_something_with_item_b"
    "ItemA" is incompatible with "ItemB" (reportGeneralTypeIssues)
```

**Comment by erictraut** [comment]
Pyright is correct to generate a type error in this case, so this is not a bug. There is a type violation here because `item` has type `ItemA`, which is not a type compatible with `ItemB`.

Depending on your intent, you have a few options to properly type this code.

1. Use generics:

```python
_T = TypeVar("_T", bound=ItemA)

class ItemContainer(Generic[_T]):
    def __init__(self, item: _T) -> None:
        super().__init__()
        self.item = item

class ContainerA(ItemContainer[ItemA]):
    pass

class ContainerB(ItemContainer[ItemB]):
    def __init__(self, item: ItemB) -> None:
        super().__init__(item)

    def do_something_with_item(self):
        do_something_with_item_b(self.item)
```

2. Use an assert.

```python
    def do_something_with_item(self):
        assert isinstance(self.item, ItemB)
        do_something_with_item_b(self.item) 
```

**Comment by hacker-DOM** [comment]
Awesome, thank you!
