### ISSUE TITLE
Pip distribution

### ISSUE THREAD

**Issue by dave-kennedy** [microsoft/pyright#2655]
I'd like to install Python tools with Python tools and not have to learn another toolchain.

In other words, it would be nice if I could use pip to install pyright and not npm.

Yeah, there's [this](https://pypi.org/project/pyright/), but it's just a wrapper around npm and requires an entire Node installation under the hood. Ideally, Python tools would be written in Python.

**Comment by erictraut** [comment]
We've discussed this previous. We don't have any plans to publish a pip-based solution. Pyright is implemented in TypeScript and requires node to run. That's not going to change. If you want a Python-based type checker, mypy is available as an option.

As you noted, Robert Craigie has developed and published https://pypi.org/project/pyright/. You could talk to him about additional requirements that you have.
