### ISSUE TITLE
`import A.B.C.X as X` should be considered a redundant form in type stub

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#2663]
PEP 484 says the following about imported symbols within a type stub:
>Modules and variables imported into the stub are not considered exported from the stub unless the import uses the import ... as ... form or the equivalent from ... import ... as ... form. (UPDATE: To clarify, the intention here is that only names imported using the form X as X will be exported, i.e. the name before and after as must be the same.)

It doesn't explicitly state whether an import of the form `import A.B.C.X as X` should be considered a redundant form (and therefore treated as an export). Pyright currently assumes that it's not, but mypy appears to treat it as a redundant form. The PEP 484 language is sufficiently unclear that I could understand either interpretation. However, there appears to be precedent in typeshed. The `xml/__init__.pyi` file uses this form: `import xml.parsers as parsers`. I can't think of any reason why this import would be present unless it were intended to be treated as a redundant form (and therefore indicate that `parsers` is meant to be exported from the top-level `xml` module). 

Pyright should therefore treat this as a redundant form. For consistency, the same rule should apply to modules within a "py.typed" library.

**Comment by JelleZijlstra** [comment]
We're also discussing this import in python/typeshed#6523.

**Comment by erictraut** [comment]
@JelleZijlstra, what are your thoughts on the import form `import A.B.C.X from X`? Do you think that should be considered a form that implies a re-export of symbol `X` when used in a type stub? As I mentioned above, PEP 484 isn't very clear (even with the additional clarification that Guido added last year). 

@gvanrossum, what are your thoughts here? Perhaps an additional clarification is required in PEP 484?

**Comment by JelleZijlstra** [comment]
i don't feel strongly about it, but I think the fairest reading of the PEP 484 text is that it doesn't count as a re-export, because the part before and after the `as` isn't the same. Also, I don't see a strong reason to support this form because you can always write `from A.B.C import X as X` equivalently. If that affects some typeshed stubs, it's easy to change them.

**Comment by erictraut** [comment]
OK, thanks for the input. Based on this, I'm going to leave the current logic in pyright as is.
