### ISSUE TITLE
`ParamSpec` in the `__init__` of a generic class

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pyright#2667]
Version: from `main`, commit `275956d3d1e1814a3562a12a9c2a2ef4f3fde326`

I'm trying to encapsulate the args and kwargs to a function in a class.

## Code
```py
from typing import Callable, Generic, TypeVar
from typing_extensions import ParamSpec


P = ParamSpec("P")
T = TypeVar("T")


class Future(Generic[T]):
    ...


class Args(Generic[P]):
    def __init__(self, *args: P.args, **kwargs: P.kwargs) -> None:
        self.args = args
        self.kwargs = kwargs


def call_later(time: float, fn: Callable[P, T], args: Args[P]) -> Future[T]:
    ...


def launch_missiles(x: float, y: float, /, color: str) -> bool:
    ...


future = call_later(3.14, launch_missiles, Args(4.3, 3.5, color="foo"))
#                                               ^^^^^^^^^^^^^^^^^^^^^
```
## Error
At the last line: `Expected 0 positional arguments`
This is because `P` in `Args` is inferred to be empty for some reason

I assume I'm doing something completely wrong, but not sure what's the issue

**Comment by erictraut** [comment]
The `P.args` and `P.kwargs` are not meant to be used in this manner for capturing arguments to a call. They are meant to be used in an inner function to represent parameters already captured by a ParamSpec in an outer function or class. Refer to PEP 612 for details.

**Comment by decorator-factory** [comment]
Shouldn't there be an error on this line then?
```py
    def __init__(self, *args: P.args, **kwargs: P.kwargs) -> None:
```
the reported error is pretty confusing, even though this behaviour is invalid.

**Comment by erictraut** [comment]
You can specialize the class explicitly and then call its constructor like this:

```python
Args[[int, str]](3, "hi")
```

The error in your example is because you're trying to implicitly specialize `Args[P]` by calling a constructor, but you're doing so in a way that's invalid.
