### ISSUE TITLE
Edge cases in overload resolution

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#2671]
Consider this test case:
```python
from typing import overload
from typing import List, Any, Union
from typing_extensions import Literal


@overload
def overloaded(lst: List[str]) -> Literal[1]:
    pass


@overload
def overloaded(lst: List[int]) -> Literal[2]:
    pass


def overloaded(lst: List[Any]) -> int:
    raise NotImplementedError


def check(
    unannotated,
    list_union: List[Union[int, str]],
    union_list: Union[List[int], List[str]],
    explicit: Any,
):
    val = overloaded([])  # pyright and mypy: Literal[1]
    reveal_type(val)
    val2 = overloaded([unannotated])  # pyright: Literal[1], mypy: Any
    reveal_type(val2)
    val3 = overloaded(unannotated)  # pyright: Literal[1], mypy: Any
    reveal_type(val3)
    val4 = overloaded(list_union)  # pyright: Unknown, mypy: Literal[1] (and both give an error)
    reveal_type(val4)
    val5 = overloaded(union_list)  # pyright and mypy: Literal[2, 1]
    reveal_type(val5)
    val6 = overloaded(explicit)  # pyright: Literal[1], mypy: Any
    reveal_type(val6)
    val7 = overloaded(["x"])
    reveal_type(val7)  # Literal[1]
    val8 = overloaded([1])
    reveal_type(val8)  # Literal[2]
```
I was surprised about the cases (val2, val3, val6) where pyright infers Literal[1] and mypy infers Any. It's consistent with the rule that we pick the first overload that matches, but Michael's comment in https://github.com/python/typing/issues/253#issuecomment-389262904 (the closest we have to a spec of how overload works in mypy) suggests to avoid matches due to Any. That's also what I'd expect as a user.

I'm curious what led you to pick pyright's behavior here; I couldn't find any mention of it in the documentation.

**Comment by hmc-cs-mdrissi** [comment]
There's been a similar issue before on overload ambiguity with Any and answer then is here, https://github.com/microsoft/pyright/issues/2521#issuecomment-956823577  . Main reason is Any behaves poorly for IDE experience.

**Comment by JelleZijlstra** [comment]
Thanks @hmc-cs-mdrissi, that issue answers my questions.
