### ISSUE TITLE
Assertions do not appropriately narrow types in interaction with other methods

### ISSUE THREAD

**Issue by thisisrandy** [microsoft/pyright#2675]
**Describe the bug**
After asserting that a variable is of a given type and then reassigning it to the result of a method with identically-typed output, type information is lost.

**To Reproduce**
Open the code below in VSCode and observe the commented characteristics, or check with pyright and observe no error on line 12.

**Expected behavior**
`str` type for `item` should be maintained after assigning to `item.lower()` in all presented cases.

**Screenshots or Code**
```python
from typing import Any


def assert_str(item: Any) -> None:
    assert isinstance(item, str)
    item += 1  # error as expected


def assert_str_then_lower(item: Any) -> None:
    assert isinstance(item, str)
    item = item.lower()  # item: Any (LHS), str (RHS), (method) lower: () -> str
    item += 1  # no error


def accept_only_str(item: str) -> None:
    item = item.lower()  # item: str (LHS), str (RHS)
    item += 1  # error as expected
```

**VS Code extension or command-line**
pylance v2021.12.0
```
> pyright --version
pyright 1.1.193
```

**Comment by thisisrandy** [comment]
This is probably actually a dup of #2674 as it involves narrowing `Any`.

**Comment by erictraut** [comment]
The behavior is correct (or at least intended) in this case. 

Pyright is applying type narrowing based on the `isinstance` type guard. As I mentioned in #2674, `isinstance` is special in that it allows narrowing of `Any`. 

Pyright also applies narrowing on assignments. In this case, the expression `item.lower()` is being assigned to the symbol `item`, which has a declared type of `Any`. Type narrowing of `Any` is not done for assignments, so the resulting type of `item` after the assignment is `Any`.
