### ISSUE TITLE
update value with another type than defined in List or Dict

### ISSUE THREAD

**Issue by iqxd** [microsoft/pyright#268]
Define a list or dict with type hint of members,  then update the member value with a different type , there are no errors detected . 

codes:

l: List[int] = [1, 2, 3, 4, 5]
l[0] = 'a'

d: Dict[int,str] = {1 : 'str'}
d[1] = 123

VS Code extension version : 1.0.66

**Comment by erictraut** [comment]
Thanks for the bug report. I'm able to repro the problem as reported. I'll look into it.

**Comment by erictraut** [comment]
This will be fixed in the next published version of pyright.

**Comment by erictraut** [comment]
This is now fixed in version 1.0.67, which I just published.

**Comment by iqxd** [comment]
I tried the new version and it now works , thanks for the so quick fix !
