### ISSUE TITLE
False positive about type-var variance in callable protocol when used in union type

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pyright#2711]
This is a tracking issue.

Originated at microsoft/pylance-release#2172.

**Comment by erictraut** [comment]
I'm going to close this as "won't fix". We can leave the other bug open for now and see if others run into this. It seems like an extreme edge case to me.

**Comment by erictraut** [comment]
Oh, I just noticed that you have a proposed fix. I'll take a look at that before I close this.

**Comment by erictraut** [comment]
This is included in pyright 1.1.197, which I just published. It will also be included in the next release of pylance.
