### ISSUE TITLE
Do not obfuscate the library and provide types to use embedded Pyright

### ISSUE THREAD

**Issue by goto1134** [microsoft/pyright#2714]
**Is your feature request related to a problem? Please describe.**
I would like to use Pyright in my web service. The problem is that I have to run it as a subprocess right now. The library is obfuscated and does not provide types for typescript, so the only way is to build it yourself and add it as a dependency.

**Describe the solution you'd like**
I would like to have a library without obfuscation and get typescript types in it.

**Comment by erictraut** [comment]
This isn't a use case we currently support through the published version of Pyright. However, the code is open-sourced, so you're welcome to build it yourself.

**Comment by goto1134** [comment]
@erictraut, thank you for the reply!

Can I presume that the currently exported classes and functions API is stable and would not change significantly?

**Comment by erictraut** [comment]
It depends on what APIs you're referring to. If you use the main entry points — those defined by the language service protocol (LSP), then it's very stable. If you're talking about various internal functions and classes, then I can't make any guarantees about stability. Pyright is under active development, and the internals change frequently.

**Comment by goto1134** [comment]
I want to extend `LanguageServerBase`. Is it considered stable?

**Comment by erictraut** [comment]
Yeah, LanguageServerBase hasn't changed in a long time. It's the base class that Pylance derives from, so we tend to keep it stable. We do occasionally add new methods, but we don't tend to change or remove existing method.
