### ISSUE TITLE
venvPath setting silently ignored without venv path

### ISSUE THREAD

**Issue by ilyabosch** [microsoft/pyright#2715]
**Describe the bug**
Passing `venvPath` setting without `venv` silently does nothing.

**To Reproduce**
Specify venvPath without venv and observe no change in output

**Expected behavior**
An error or a warning is printed to inform user that specifying `venvPath` is not used.

**VS Code extension or command-line**
command line

**Additional context**
version: 1.1.1187

Other way around, specifying `venv` without `venvPath` creates a message that `venv` is ignored as no path is given.

**Comment by erictraut** [comment]
The command-line `venvPath` is intended to be used with a `venv` that is specified in the pyrightconfig.json file, so it's fine to pass only a `venvPath` but not a `venv` on the command line.
