### ISSUE TITLE
Add support for draft PEP 677 (Callable Type Syntax)

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#2720]
[PEP 667](https://www.python.org/dev/peps/pep-0667/) has now been accepted as a draft PEP. I think it's now far enough along that it makes sense to implement support for it in pyright.

**Comment by erictraut** [comment]
This is included in pyright 1.1.197, which I just published. It will also be included in the next release of pylance.

**Comment by kumaraditya303** [comment]
The correct link is https://www.python.org/dev/peps/pep-0677/

**Comment by Gobot1234** [comment]
There appears to be some disparity between the implementation here and that with the PEP https://github.com/python/peps/blob/main/pep-0677.rst?plain=1#L393-L394 
```
info: Type of "f3" is "(str) -> Coroutine[Any, Any, str]"
```
shouldn't this be Awaitable[str] as quoted by the PEP?

**Comment by erictraut** [comment]
Thanks for catching that. I overlooked that in the PEP. This will be fixed in the next release.
