### ISSUE TITLE
Package <name> cannot be resolved when installed with `poetry`

### ISSUE THREAD

**Issue by AbstractUmbra** [microsoft/pyright#2726]
**Describe the bug**
Unable to use `pyright --verifytypes <package>` when said package has been installed via `poetry` rather than `pip`

**To Reproduce**
Install local package via `poetry` (`poetry install`)
Attempt to run `pyright --verifytypes <package>`.

**Expected behavior**
The normal output of pyright and type assessment.

**Screenshots or Code**
![Termius_2021-12-17_02-08-05](https://user-images.githubusercontent.com/16031716/146477117-c861591f-5335-48ff-b254-afd98a79816a.png)

![Termius_2021-12-17_02-08-40](https://user-images.githubusercontent.com/16031716/146477174-5dd44f88-d9da-476c-af05-d04011ce83e7.png)

![Termius_2021-12-17_02-09-04](https://user-images.githubusercontent.com/16031716/146477203-b6022dfb-19d8-423b-8d8a-008d344481d0.png)

**VS Code extension or command-line**
CLI tooling, version: 1.1.192

**Additional context**
I have attached 3 screenshots:
1) Showing the problem.
2) Installing the project (through poetry's env) with pip.
3) Pyright working as intended.

I am wondering if this problem is more of a `poetry` issue than a pyright issue, perhaps due to how projects are installed but figured I would file this issue first.

**Comment by erictraut** [comment]
Could you provide more detailed repro instructions? Is "hodoana" the project found at https://github.com/cournape/hondana? When I run `poetry run pip install .` for this project, I receive an error "Poetry could not find a pyproject.toml file...".

Pyright determines the import resolution paths by executing the command `python3` with a small script that outputs the sys.path contents. It uses these import resolution paths to resolve the package specified in the `--verifytypes` command line option.

**Comment by AbstractUmbra** [comment]
Sorry, the project involved is [hondana](https://github.com/AbstractUmbra/Hondana).

Upon further testing here it seems that being inside the poetry-created venv, the path resolution will fail, but deactivating said venv and it will run nicely.

**Comment by AbstractUmbra** [comment]
As for clearer repro instructions:

1) Install the project with `poetry`. (`poetry install`)
2) Activate the project-created venv. `. /path/to/venv/activate`
3) Run pyright operations, in this case I used (`pyright --ignoreexternal --lib --verifytypes hondana`)
4) Deactivate the venv. (`deactivate`)
5) Re-run the same operation as step 3.

**Comment by AbstractUmbra** [comment]
Huh... Then I am assuming then this must be a local issue. I assumed it wasn't as I was getting the same behaviour on a GitHub Action process.

I'll try some more things locally, I guess. Thank you for your time!

**Comment by erictraut** [comment]
I don't think this is a bug in pyright. To diagnose the problem, set up your shell environment, then run `python3` and type `import sys` followed by `print(sys.path)`. You should see hondana in the import resolution paths (probably the last one). Pyright uses the output of `sys.path` to do import resolution.

**Comment by blade2005** [comment]
To leave a breadcrumb for others who found this issue. 

I fixed this issue by running pyright in poetry.
```bash
poetry run npx pyright --venv-path ./
```
