### ISSUE TITLE
Non-concrete protocol classes should not be assignable to `Type[Proto]`

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#2731]
PEP 544 indicates that a non-concrete protocol class shouldn't be assignable to `Type[Proto]`, but pyright allows this. See https://www.python.org/dev/peps/pep-0544/#type-and-class-objects-vs-protocols for details.

**Comment by erictraut** [comment]
This will be included in the next release.

**Comment by FasterSpeeding** [comment]
Random question since this caught my attention; is this behaviour just being changed strictly for stuff typed as `type[Proto]`; in other words will this influence how arguments typed like `type[T]` (Where `T` is declared as `TypeVar("T")` or `type[Any]` are treated?

**Comment by erictraut** [comment]
This affects only `type[Proto]`.

**Comment by erictraut** [comment]
This is included in pyright 1.1.198, which I just published. It will also be included in the next release of pylance.
