### ISSUE TITLE
Add reportTypeMismatch

### ISSUE THREAD

**Issue by dsuch** [microsoft/pyright#2735]
Hello,

could you please add a new configuration option, called "reportTypeMismatch" that will specifically catch only cases like the one below?

```python
class Hello:
    name: str
    def __init__(self):
        self.name = 123
```
Right now (v. 1.1.197), this will be caught via "reportGeneralTypeIssues" but it is a bit too broad really.

My use-case is that I have a codebase of about 150k lines of code that I am gradually adding static typing to.

There are several levels of type hints that I am adding, depending on the importance of a particular piece of code. Some parts are critical and they have very detailed type hints (stricter than the default strict mode) whereas many are of a less critical nature and use specific checks only. Naturally, some parts are in between the two. Configuration for them all is in their own pyproject.toml files.

Moreover, I also use VS Code and I would like for just a very few checks to be conducted whenever I open a Python module in the editor. Essentially, whenever I open some code that I have not looked at in a while, meaning it may not have any type hints, I would like for just a couple of things to be checked through "python.analysis.diagnosticSeverityOverrides".

These default, in-IDE checks, are very simple, such as "reportMissingParameterType" or "reportMissingTypeArgument" that are set to "error" - and that already goes a long way - but practically everything else is set to "none". This is fine because I have the additional pyproject.toml files through which pylance actually conducts thorough tests several times a day, without distracting me with their messages while I edit code.

Hence, I would also like to enable the hypothetical "reportTypeMismatch" in VS Code without having to enable "reportGeneralTypeIssues" which may catch too much.

Thank you.

**Comment by erictraut** [comment]
Type mismatch errors are at the heart of what a type checker does, so I'm reluctant to move those out of the "reportGeneralTypeIssues" diagnostic check. Perhaps we could approach this from the opposite direction. Which diagnostics are you seeing with `reportGeneralTypeIssues` that you would like to be able to disable independently from type mismatch errors?

**Comment by erictraut** [comment]
Many of the other diagnostics that are part of `reportGeneralTypeIssues` will typically lead to a cascade of type mismatch errors. For example, if you incorrectly define a TypeVar or have multiple incompatible declarations for a symbol, these will inevitably contribute to type mismatch errors. So disabling some of these but retaining the type mismatch errors will be very confusing and will make it difficult to diagnose the remaining errors.

**Comment by dsuch** [comment]
Thanks @erictraut - yes, you are right. It may be more productive to approach it from the other perspective.

In that case, with your permission, I will close this ticket until I have a clearer vision of what such a group of diagnostics to disable should look like.
