### ISSUE TITLE
reportIncompatibleMethodOverride not allowing extra args, even with *args/**kwargs at the base class

### ISSUE THREAD

**Issue by bellini666** [microsoft/pyright#2747]
Consider the following:

```python
from typing import Any


class Foo:
    def method(self, foo: int, **kwargs: Any) -> Any:
        ...


class Bar(Foo):
    def method(self, foo: int, bar: str, **kwargs: Any) -> Any:
        ...
```

If `reportIncompatibleMethodOverride` is used this gives an error:

```
/tmp/xxx.py
  /tmp/xxx.py:10:9 - error: Method "method" overrides class "Foo" in an incompatible manner
    Parameter 3 type mismatch: base parameter is type "Any", override parameter is type "str" (reportIncompatibleMethodOverride)
```

Even without `**kwargs` (or even if it had `*args`) this code should not, IMHO, give that error. All the other arguments are compatible, the subclass is just adding something else. This is a common use case where the subclass receives something extra, which only she will use, and pass the rest to the superclass through a `super()` call.

**Comment by JelleZijlstra** [comment]
This error is strictly correct, because you could write code like this:
```python
def f(foo: Foo):
    foo.method(1, bar=3)  # legal according to Foo.method, but breaks if `foo` is actually a `Bar`
```

**Comment by erictraut** [comment]
Yes, the current behavior is intended. This is a strict-mode check and is off by default, so I think it's reasonable for it to be picky about type safety.
