### ISSUE TITLE
Using Pyright with no-venv solutions such as PDM

### ISSUE THREAD

**Issue by MrHemlock** [microsoft/pyright#2767]
**Support for no-venv Solutions**
Currently there doesn't appear to be a way to use pyright with no-venv solutions such as PDM.  For context, this is what I'm referring to: https://pdm.fming.dev/ . The cliff notes is that PDM creates a folder with the libraries/packages you need for the particular projects and refers back to your system's Python versions to run them, eliminating the need for the venv.  

However that comes at a cost.  Because PDM doesn't create a venv, pyright doesn't know what to use in order to work read through the various libraries.  If I make the venv path my main installations, I end up with it seeing too many packages or potentially ones that aren't the same version.  

**Potential Solution**
My idea is to have a way to point pyright to the standard Python that's installed but exclude any installed packages, while letting you point to the `__pypackages__` directory used.  I'm sure it's possible with the currently config files, but I haven't been able to figure it out, and it'd be nice to have a simpler way to set it up.

**Comment by erictraut** [comment]
Pyright already supports this through the `extraPaths` configuration setting in the `pyrightconfig.json` or `pyproject.toml` file. Refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#main-pyright-config-options) for details.

**Comment by MrHemlock** [comment]
Would that allow me to filter out the libraries already installed in the system's Python?

**Comment by erictraut** [comment]
No, it doesn't exclude the site-packages in your currently-configured Python environment (whither it's a venv or the system's Python install). My understanding of PEP 582 is that it simply adds `__pypackages__` to the search paths (i.e. to `sys.paths`); it doesn't remove any existing search paths.

If your intent is to simulate a "fresh" Python install with nothing installed in conjunction with a PEP 582 "local packages directory", you can create a clean venv and activate it, then add the `__pypackages__` to your "extraPaths" configuration setting.

**Comment by MrHemlock** [comment]
Gotcha.  I really do appreciate you taking the time.
