### ISSUE TITLE
Incorrect type inference when unpacking in square brackets

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pyright#2774]
# Code
```py
things = [1, 2, 3, 4, 5]

[x, *xs] = things

reveal_type(x)
reveal_type(xs)

(y, *ys) = things

reveal_type(y)
reveal_type(ys)
```

# Issue
`ys` is inferred correctly as `list[int]`, but `xs` is inferred as `int`. `xs` should've been inferred as `list[int]`

**Comment by erictraut** [comment]
Can you check that you're running the latest version of pyright? I fixed this bug several versions ago, and I can no longer repro it.

**Comment by decorator-factory** [comment]
Sorry, you're right - I didn't realize I was running on an old version.
