### ISSUE TITLE
Optional can not be used without an argument in Runtime Type Introspection

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#2776]
**Describe the bug**
Same bug as this one, https://github.com/microsoft/pyright/issues/2723 but applied to Optional.

**To Reproduce**
```python
from typing import Any, Optional


def is_optional(ty: Any) -> bool:
    return ty is Optional # Error produced Expected one type argument after "Optional"

```

**Expected behavior**
No error message.

**VS Code extension or command-line**
pyright 1.0.202.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.203, which I just published. It will also be included in the next release of pylance.
