### ISSUE TITLE
Add support for functools.partialmethod

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#2787]
With the recently-added support for functools.partial, it would be easy to extend this to functools.partialmethod.

```python
import operator
from functools import partialmethod


class IntCmp:
    def __init__(self, value):
        self._value = value

    def _cmp(self, opr, other: int) -> bool:
        if isinstance(other, int):
            return opr(self._value, other)
        return NotImplemented

    __eq__ = partialmethod(_cmp, operator.eq)
    __ne__ = partialmethod(_cmp, operator.ne)

```

**Comment by erictraut** [comment]
This turns out to be more difficult than I thought because the `partialmethod` doesn't include a `__call__` method. I'm going to leave this unimplemented for now since no pyright users have requested it.

**Comment by powellnorma** [comment]
FWIW, in my project it would be very useful, since there is extensive use of `partialmethod`

**Comment by declaresub** [comment]
I too would like support for partialmethod.

**Comment by eachimei** [comment]
My project also uses `partialmethod` and currently `pyright` doesn't like it

**Comment by vacarme** [comment]
would be useful for me too. (and thank for your work)

**Comment by hacker1024** [comment]
Can this be either reopened or closed as unplanned?
