### ISSUE TITLE
Type narrowing with `asyncio.iscoroutine`, `inspect.iscoroutine`, and others

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pyright#2794]
**Is your feature request related to a problem? Please describe.**
Usually type narrowing is down with `isinstance` checks. For `Awaitable`, `Coroutine`, and `Callable[..., Awaitable[Any]]` there are special functions which are often recommended to be used instead.
```py
import asyncio
import inspect

asyncio.iscoroutine
asyncio.iscoroutinefunction

inspect.isawaitable
inspect.iscoroutine
inspect.iscoroutinefunction
```

**Describe the solution you'd like**
It would be awesome if pyright (and other type checkers) would be able to understand that those functions behave quite similar to their respective `isinstance` calls.

```py
import asyncio
from typing import Callable, Coroutine, Any

def func(f: Callable[..., int] | Coroutine[Any, Any, int]) -> None:
    if isinstance(f, Coroutine):
        reveal_type(f)  # Coroutine[Any, Any, int]
        return
    reveal_type(f)  # Callable[..., int]


def func2(f: Callable[..., int] | Coroutine[Any, Any, int]) -> None:
    if asyncio.iscoroutine(f):
        # Coroutine[Any, Any, int] will always match here
        # Reveal type could be 'Coroutine[Any, Any, int]'
        # Or maybe 'Coroutine[Any, Any, int] | Coroutine[Any, Any, Any]'
        reveal_type(f)
        return
    # Here 'f' should only ever be 'Callable[..., int]'
    reveal_type(f)
```

<details>
<summary>Current pyright output</summary>

```
info: Type of "f" is "Coroutine[Any, Any, int]"
info: Type of "f" is "(...) -> int"
info: Type of "f" is "Coroutine[Any, Any, Any]"
info: Type of "f" is "((...) -> int) | Coroutine[Any, Any, int]"
```
</details>

<details>
<summary>Current mypy output</summary>

```
note: Revealed type is "typing.Coroutine[Any, Any, builtins.int]"
note: Revealed type is "def (*Any, **Any) -> builtins.int"
note: Revealed type is "typing.Coroutine[Any, Any, Any]"
note: Revealed type is "Union[def (*Any, **Any) -> builtins.int, typing.Coroutine[Any, Any, builtins.int]]"
```
</details>

**Additional context**
@erictraut I saw your proposal about narrowing TypeGuards in the negative case. Without custom handling, this might actually be quite a good place for it. Take `asyncio.iscoroutine` for example. This is the current typeshed definition
```py
def iscoroutine(obj: object) -> TypeGuard[Coroutine[Any, Any, Any]]: ...
```

With your proposal, something like this could work here.
```py
T = TypeVar("T")

_T_co = TypeVar("_T_co", covariant=True)
_T_contra = TypeVar("_T_contra", contravariant=True)
_V_co = TypeVar("_V_co", covariant=True)

def iscoroutine(obj: Coroutine[_T_co, _T_contra, _V_co] | T) -> TypeGuard[Coroutine[_T_co, _T_contra, _V_co], T]: ...
```

**Comment by erictraut** [comment]
This is already defined using a `TypeGuard` annotation in typeshed, so I don't plan to add custom logic for it in pyright. I agree that the negative narrowing approach would work if that proposal is accepted.

In the meantime, you can use `assert callable(f)` in the negative case if you want to narrow for the callable.
