### ISSUE TITLE
Operator "+" not supported for types "Literal['example']" and "str | None"

### ISSUE THREAD

**Issue by mancuso** [microsoft/pyright#2808]
The following code:

import os

stack = "example" + os.environ.get('Environment') + "infrastructure"

Yields the following error: 

[Pyright reportGeneralTypeIssues] [E] Operator "+" not supported for types "Literal['example']" and "str | None"

Using VIM 8.2.

**Comment by erictraut** [comment]
Pyright is pointing out a bug in your Python program. The expression `os.eviron.get('Environment'`)` could return a value of `None`, and this will result in a runtime exception.

You can fix the bug by providing a default value for the `os.environ.get` call.
