### ISSUE TITLE
tuple of numbers incompatible with array

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#2809]
```python
import numpy as np
t: tuple[int, ...] = (1, 2)
np.prod(t)
```
Gives
```
  /home/neil/src/cmm/a.py:3:9 - error: Argument of type "tuple[Literal[1], Literal[2]]" cannot be assigned to parameter "a" of type "ArrayLike" in function "prod"
    Type "tuple[Literal[1], Literal[2]]" cannot be assigned to type "ArrayLike"
      "tuple[Literal[1], Literal[2]]" is incompatible with protocol "_SupportsArray[dtype[Unknown]]"
        "__array__" is not present
      "tuple[Literal[1], Literal[2]]" is incompatible with protocol "_NestedSequence[_SupportsArray[dtype[Unknown]]]"
        "__getitem__" is an incompatible type
          One or more overloads of "__getitem__" is not assignable
            Type "Overload[(__x: SupportsIndex) -> int, (__x: slice) -> Tuple[int, ...]]" cannot be assigned to type "(index: slice, /) -> _NestedSequence[_T_co@_NestedSequence]"
      "tuple[Literal[1], Literal[2]]" is incompatible with "bool"
```

**Comment by erictraut** [comment]
I have it narrowed down to this minimal example:
```python
from typing import Protocol, TypeVar, Union, overload

_T_co = TypeVar("_T_co", covariant=True)

class _NestedSequence(Protocol[_T_co]):
    @overload
    def __getitem__(self, index: int, /) -> _T_co | _NestedSequence[_T_co]:
        ...

    @overload
    def __getitem__(self, index: slice, /) -> _NestedSequence[_T_co]:
        ...

x: Union[int, _NestedSequence[int]] = (1, 2)
```

**Comment by erictraut** [comment]
This turned out to be a really challenging bug to find and fix. It resulted from a protocol class that referred to itself, and pyright was evaluating it recursively, eventually giving up. I've added additional type recursion checks to eliminate the problem. This will be fixed in the next release.

**Comment by NeilGirdhar** [comment]
That's awesome!  Thanks so much for the incredibly quick fix.

**Comment by erictraut** [comment]
This is included in pyright 1.1.206, which I just published. It will also be in the next release of pylance.

**Comment by NeilGirdhar** [comment]
Unfortunately, a slightly more complicated example breaks this again:
```python
import numpy as np
def f(shape: int | tuple[int, ...]) -> int:
    if isinstance(shape, int):
        shape_as_tuple = (shape,)
    else:
        shape_as_tuple = tuple(shape)
    reveal_type(shape_as_tuple)
    return int(np.prod(shape_as_tuple))
```

**Comment by erictraut** [comment]
There's a constant that controls how many levels of recursion are allowed in a type before type evaluator gives up. This is important because some types are infinitely recursive. This sample happens to hit the current limit. I'll increase it a bit to eliminate the error in the above sample, but there will inevitably be some type definition that will extend beyond this constant value. In most cases, the evaluated type works fine if it hits this limit, but in this particular case, it results in a false positive error.

**Comment by NeilGirdhar** [comment]
Okay, thank you.
