### ISSUE TITLE
help: configuration

### ISSUE THREAD

**Issue by humanitiesNerd** [microsoft/pyright#2826]
I have a project laid out like this:

```
tree -L 2                     <----- shows only 2 levels
.
├── bin
│   └── odoo
├── contrib                  <----- this is code, both these folders contain libraries
│   ├── l10n-italy
│   └── OCA
├── filestore
├── local
│   └── my-project           <---- this is code too, it's my own code
├── logs
├── poetry.lock
├── pyproject.toml
├── pyrightconfig.json
├── sperimentazione-clinica.cfg
└── src                      <---------- this is code and also type annotations for the Odoo code base. 
    ├── odoo
    └── odoo-stubs14

```

This layout is suggested in the book: Odoo 14 development cookbook 4th edition

My code is in `local/my-project` and it depends on

```
contrib/*
src/*
```

The `pyrightconfig.json` file is empty

I have the impression that Pyright is not finding the code in contrib and in src

Because no symbol in my own code can be sorted out

Can I keep this layout ? Or isn't it supported ?

More precisely, this is a description of the lsp session that lsp-mode (an Emacs based client) gives me

```
[X] /home/me/my-project
[-] /home/me/my-project/local/my-project
 `-[-] pyright:3550
    |-[-] Buffers
    |  `-[+] res_studio.py
    `-[+] Capabilities
[X] /home/me/my-project/bin

```
The first line points to the folder containing the `pyrightconf.json` file

The second line points to the folder containing a `__manifest__.py` and an `__init__.py` file

It seems both are deemed as roots by Pyright. 
Or maybe not, I don't know. I'm pasting this just for reference

Thanks in advance

**Comment by erictraut** [comment]
Please refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/import-resolution.md) for details about import resolution and [this documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) for general configuration. If the documentation isn't clear or you have follow-on questions, feel free to post them here.

**Comment by humanitiesNerd** [comment]
Thank you, I want to provide just a bit of clarification on my issue

I had started with the auto-root-discovery feature of lsp-mode turned on

The wrong root had been discovered and that information ended up written in a file that lsp-mode uses to store information about a project

Later, I was advised to turn the auto-root-discovery off but by then, the wrong root for my project was on the record

I have my pyrightconf.json file in the RIGHT root, that's why it wasn't found

Now I managed to correct the wrong information stored by lsp-mode and the pyrightconf.json does get found

I write this because it could be helpful for other confused lsp-mode users

Thanks again
