### ISSUE TITLE
Pyright doesn't infer that a variable can't have two types at once

### ISSUE THREAD

**Issue by ikamensh** [microsoft/pyright#2827]
Using pyright CLI, version `1.1.1204`.

I was expecting following to check out, because `y` can't have two types at the same time:
```python
def foo(y: str | int) -> str | int:
    return y + y
```

However, I get following exception:
```
  /Users/kai7rng/oss/gym/bla.py:7:12 - error: Operator "+" not supported for types "str | int" and "str | int"
    Operator "+" not supported for types "str" and "int"
    Operator "+" not supported for types "int" and "str" 
```

**Comment by erictraut** [comment]
If you want to specify that a method operates on a variable that can take on one of several types, you should use a constrained TypeVar rather than a union. Here's how that looks:

```python
from typing import TypeVar

_T = TypeVar("_T", str, int)

def foo(y: _T) -> _T:
    return y + y
```
