### ISSUE TITLE
Confusing error message when a library defines a long Union type

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#2832]
**Describe the bug**
This came up as I was working on some pandas typing stuff.  If you have a library that defines a type that is a `Union` of many types, and there is a mismatch, the error message doesn't help you figure out what the problem is

**To Reproduce**
```python
from typing import Union
import datetime

UType = Union[
    bytes,
    bool,
    int,
    float,
    str,
    complex,
    datetime.date,
    datetime.datetime,
    datetime.time,
]


def myfunc(
    x,
) -> UType:
    if x:
        return 10
    else:
        return "foo"


y: str = myfunc("meh")
```
The error message reported on the last line assigning `y` is:
```
Expression of type "UType" cannot be assigned to declared type "str"
  Type "UType" cannot be assigned to type "str"
    "bytes" is incompatible with "str"
    "bool" is incompatible with "str"
    "int" is incompatible with "str"
    "float" is incompatible with "str"
    "complex" is incompatible with "str"
    "date" is incompatible with "str"
    "datetime" is incompatible with "str"
  ...
```
Now, the issue here is that to make this work, you have to do
```python
y: str = cast(str, myfunc("meh"))
```

That's not obvious.  If `UType` was defined in a library (e.g., in the pandas stubs, `Scalar` is defined this way), you have no way to know that `UType` was a union of types and that is why the match didn't occur.  Note that `mypy` reports on the above:
```
Incompatible types in assignment (expression has type "Union[bytes, bool, int, float, str, complex, date, datetime, time]", variable has type "str")
```
That message helps diagnose the problem.

Conversely, if the function was defined as:
```python
def myfunc2(x) -> Union[
    bytes,
    bool,
    int,
    float,
    str,
    complex,
    datetime.date,
    datetime.datetime,
    datetime.time,
]:
   if x:
        return 10
    else:
        return "foo"
    
z: str = myfunc2("meh")
```
then you get a message:
```
Expression of type "bytes | bool | int | float | str | complex | date | datetime | time" cannot be assigned to declared type "str"
  Type "bytes | bool | int | float | str | complex | date | datetime | time" cannot be assigned to type "str"
    "bytes" is incompatible with "str"
    "bool" is incompatible with "str"
    "int" is incompatible with "str"
    "float" is incompatible with "str"
    "complex" is incompatible with "str"
    "date" is incompatible with "str"
    "datetime" is incompatible with "str"
  ...
```
which is showing the full union, and is easier to understand.

**Expected behavior**
Ideally, if a type was defined as a union of types and there was a mismatch, you'd get a full "trace" of the union of types to make it easier to diagnose the problem.

**VS Code extension or command-line**
VSCode pylance 2002.1.0

**Comment by erictraut** [comment]
Based on significant feedback from users, we use type alias names in error messages rather than the full types they represent. Mypy doesn't retain type alias names, and there are multiple open requests in the mypy issue tracker to have it switch to type aliases in error messages. So I think it would generally be a step backward to expand type aliases into its full type within error messages.

I can't think of a way to make the current error message clearer. It's telling you that a value of type `UType` can't be assigned to a value of type `str`, and it's explaining in detail why each of the subtypes within `UType` are not type compatible with `str`.

**Comment by Dr-Irv** [comment]
> I can't think of a way to make the current error message clearer. It's telling you that a value of type `UType` can't be assigned to a value of type `str`, and it's explaining in detail why each of the subtypes within `UType` are not type compatible with `str`.

You could add to the error message that `UType` is a `Union` of those types.  Then you have full information - not doing what `mypy` does - which is confusing because they don't output `UType` and not doing what pyright does, which is confusing because you don't know what `UType` is.

The issue comes up because if `UType` is in a type stub of a third-party library, and `UType` is not in the docs, it's hard to figure out the connection between `UType` and the types that are listed.
