### ISSUE TITLE
Issue with method prototype typing

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pyright#2836]
**Describe the bug**
When adding a method prototype, I would assume the first argument must be `Self` (or `A`) if it isn't a static / class method.

**To Reproduce**
```python
from __future__ import annotations
from typing import Callable

class A:
    update: Callable[[A], None]

    def do_something(self) -> None:
        self.update()  # error


def update_method(self: A) -> None:
    ...

A.update = update_method
```
```
error: Expected 1 more positional argument
```

**Expected behavior**
_No error_

**VS Code extension or command-line**
Command-line v1.1.205

**Additional context**
This works in mypy.

Removing the `Self` / `A` type from `Callable`, would result in an assignment error.
```
error: Cannot assign member "update" for type "Type[A]"
    Expression of type "(self: A) -> None" cannot be assigned to member "update" of class "A"
      Type "(self: A) -> None" cannot be assigned to type "() -> None"
        Keyword parameter "self" is missing in destination (reportGeneralTypeIssues)
```

**Comment by erictraut** [comment]
You have declared the variable `update` as an instance variable. If you were to assign it as an instance variable, the code wouldn't work.

```python
class A:
    update: Callable[[A], None]

    def __init__(self):
        self.update = update_method

    def do_something(self) -> None:
        self.update()

def update_method(self: A) -> None:
    ...

A().do_something() # Runtime exception
```

If your intent is for `update` to be a class variable, then you should declare it as such. This type checks and works correctly at runtime.

```python
class A:
    update: ClassVar[Callable[[A], None]]

    def do_something(self) -> None:
        self.update()

def update_method(self: A) -> None:
    ...

A.update = update_method

A().do_something()
```

**Comment by cdce8p** [comment]
Thanks for the response. I was indeed missing the `ClassVar` annotation.
