### ISSUE TITLE
Enabling basic type checking on a file by file basis with file-level comments?

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/pyright#2888]
Hey Eric, thanks so much for pyright, it's really making Python more enjoyable for me!

I'd love to gradually introduce it in a project that's full of type errors.

My plan was to set `"typeCheckingMode": "off"` as the default for the CI and then enable it one file after the other by adding a `# pyright: basic` comment to the top of the file. Unfortunately that doesn't seem to be working?

* I could add `# pyright: strict` but that would be too strict for the code quality in question (I'd rather firstly get everything up to `basic` standards before pursuing `strict`). While the `# pyright: strict` syntax apparently let's you disable specific diagnostic rules, that seems to require me to painstakingly list all strict rules that I want to disable for the time being.

* I could enable basic checking by adding the file path to `include` in the config. Still I'd rather have this setting in the file to facilitate maintenance (since it e.g. makes moving around files easier, since you don't have to update paths in a config file).

So would it be possible for Pyright to support `# pyright: basic`?

**Comment by erictraut** [comment]
Thanks for the feature request.

I didn't think to add support for `# pyright: basic` initially because "basic" is the default type checking mode in pyright. But in pylance, it's "off" by default.

I've added the support, and it will be included in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.212, which I just published. It will also be included in the next release of pylance.
