### ISSUE TITLE
How to pin the Pyright version?

### ISSUE THREAD

**Issue by roguh** [microsoft/pyright#2893]
**Is your feature request related to a problem? Please describe.**
The problem is Pyright currently has a bug #2892 that I just reported and I can't downgrade to an older version of `pyright`. I tried to pin the version to `0.0.12`, but that's the Pypi package, not the actual version of the installed `pyright`. I'm not fully sure how to downgrade `pyright` because it seems to do an `npm install` to install itself and I don't see how to control that part of the install.

**Describe the solution you'd like**
An easy way to select the version of pyright that is running.

**Additional context**
I can easily pin the version of `mypy` and many other Python packages. This is unexpected behavior.

**Comment by erictraut** [comment]
It sounds like you're using [this pypi package](https://github.com/RobertCraigie/pyright-python) to install pyright. This package is created and maintained by someone else (Robert Craigie). It is designed to always download and use the latest version of pyright to prevent you from getting a stale version. We update pyright frequently (usually 2 or 3 times a week), so it's important to stay up to date.

That said, it looks like Robert's pypi package does document a way to pin the version using an environment variable `PYRIGHT_PYTHON_FORCE_VERSION`.

**Comment by roguh** [comment]
Thank you, I apologize for missing this documentation.
