### ISSUE TITLE
Loss of implicit literal typing in classes

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pyright#2904]
**Screenshots or Code**
```py
from typing import Literal

TemperatureUnits = Literal["°C", "°F", "K"]

class UnitSystem:
    def __init__(self, temperature: TemperatureUnits) -> None:
        self.temperature_unit = temperature
        reveal_type(self.temperature_unit)

    def func(self) -> None:
        reveal_type(self.temperature_unit)
```

**Describe the bug**
With the assignment, I would expect pyright to copy the type from `temperature` for `self.temperature_unit`. This does seem to happen. However, when accessing `self.temperature_unit` in another function, the revealed type falls back to `str` which seems unintuitive.
```
information: Type of "self.temperature_unit" is "Literal['°C', '°F', 'K']"
information: Type of "self.temperature_unit" is "str"
```

**Expected behavior**
Both mypy and pyre keep the literal type.
```
Revealed type is "Union[Literal['°C'], Literal['°F'], Literal['K']]"
Revealed type is "Union[Literal['°C'], Literal['°F'], Literal['K']]"
```
```
Revealed type [-1]: Revealed type for `self.temperature_unit` is `typing.Union[typing_extensions.Literal['K'], typing_extensions.Literal['°C'], typing_extensions.Literal['°F']]`.
Revealed type [-1]: Revealed type for `self.temperature_unit` is `typing.Union[typing_extensions.Literal['K'], typing_extensions.Literal['°C'], typing_extensions.Literal['°F']]`.
```

**VS Code extension or command-line**
command-line, v1.1.212

**Additional context**
If the assignment is modified to include the type, the literal typing is kept.
```py
self.temperature_unit: TemperatureUnits = temperature
```
```
information: Type of "self.temperature_unit" is "Literal['°C', '°F', 'K']"
information: Type of "self.temperature_unit" is "Literal['°C', '°F', 'K']"
```

**Comment by erictraut** [comment]
In your example, `temperature_unit` is an instance variable with no declared type. Its type is therefore inferred based on the values assigned to it. We intentionally do not retain literal types in this case unless the variable is marked `Final` or its name is capitalized, which indicates it is meant to be treated as a constant. If your intent is to retain the literals, you should declare its type explicitly, as in `self.temperature_unit: TemperatureUnits = temperature`.

For more details about type declarations and type inference, please refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-declarations).

**Comment by cdce8p** [comment]
I figured that it might be intentional. The question is should it be?

Coming from mypy, I wouldn't have expected that behavior. The most concrete type is inferred. If I want a more general one, I would need to add a type declaration.

Another example for that pattern.
```py
def func(unit: Literal["°C"], some_str: str) -> None:
    if some_func():  # type: ignore
        var = unit
    else:
        var = some_str
    reveal_type(var)
```
```
error: Incompatible types in assignment (expression has type "str", variable has type "Literal['°C']")  [assignment]
note: Revealed type is "Literal['°C']"
```
Here mypy even raises an error since it infers `var` as `Literal['°C']` instead of `str`. To fix it, I would need to manually widen the type with `var: str = unit`. That is a bit excessive tbh, `mypy` doesn't seem to consider the `if - else`. The point still stands though that widening only happens when required, not automatically.

Lastly, what makes it so confusing in the first place is that inside `__init__` the type is correctly narrowed. Thus it isn't obvious IMO why the narrowing is lost suddenly.

**Comment by erictraut** [comment]
Pyright's type inference rules are consistent. I think you're advocating for some special-case handling here. I'm not convinced that special-casing is warranted here.

Consider the following:
```python
from typing import Literal

class Foo:
    def __init__(self, val: Literal[3, 4] = 3, cond: bool = True):
        self.a = 3

        self.b = val

        if cond:
            self.c = 3
        else:
            self.c = 4

        self.d = 3 if cond else 4

        if cond:
            self.e = val
        else:
            self.e = 3

        if cond:
            self.f = val
        else:
            self.f = 5  # Mypy: error

        if cond:
            self.g = 5
        else:
            self.g = val

        x1: Literal[3] = 3
        self.h = x1

        x2 = 3
        self.i = x2

        x3: Literal[3] = 3
        x4: Literal[4] = 4
        self.j = x3 if cond else x4


f = Foo()

reveal_type(f.a)  # Pyright: int, Mypy: int
reveal_type(f.b)  # Pyright: int, Mypy: Literal[3, 4]
reveal_type(f.c)  # Pyright: int, Mypy: int
reveal_type(f.d)  # Pyright: int, Mypy: int
reveal_type(f.e)  # Pyright: int, Mypy: Literal[3, 4]
reveal_type(f.f)  # Pyright: int, Mypy: Literal[3, 4]
reveal_type(f.g)  # Pyright: int, Mypy: int
reveal_type(f.h)  # Pyright: int, Mypy: Literal[3]
reveal_type(f.i)  # Pyright: int, Mypy: int
reveal_type(f.j)  # Pyright: int, Mypy: int
```

Mypy's behavior here seems very inconsistent, and I have a hard time reasoning what rules its using to determine whether a literal should be widened. Pyright is consistent.

**Comment by JelleZijlstra** [comment]
I think mypy's behavior is consistent: it shows a Literal type if the variable was declared with a Literal type, and a non-Literal type otherwise. The main exception is the `j` case, but that's probably an instance of your gripe (which I agree with) where mypy uses a join instead of a Union.

Mypy's behavior probably is that way for the historical reason that the typechecker predates Literal types, and when Literal support was added, the mypy devs were hesitant to infer them in too many cases.

**Comment by erictraut** [comment]
None of these variables have a declared type. Their types are all inferred.

**Comment by cdce8p** [comment]
> Mypy's behavior here seems very inconsistent, and I have a hard time reasoning what rules its using to determine whether a literal should be widened. Pyright is consistent.

It depends. I would exclude `f.j` for now. That doesn't seem to be implemented currently. The rule, as I understand it, is that mypy doesn't widen at all. The first assigned type is copied. That means
* If a explicit `Literal` is assigned, the target is inferred as `Literal`
* Just integers `3`, `4`, ... aren't **explicit** by that definitions. So the target is inferred as `int` instead.

**Comment by erictraut** [comment]
When mypy performs type inference, it widens in some cases and not in others. For both `a` and `b`, the value of the assigned expression is a literal type, but in the case of `a`, mypy widens the type to `int`, and in the case of `b` it doesn't. That's inconsistent.

**Comment by JelleZijlstra** [comment]
> None of these variables have a declared type. Their types are all inferred.

I mean the declared type of the RHS. Compare the `self.a` and `self.b` assignments: for mypy, the RHS of `self.a` is just `int`, but the RHS of `self.b` is `Literal[3, 4]`, because it was explicitly declared as a Literal. Mypy only infers literal types when you explicitly tell it to.

**Comment by erictraut** [comment]
Not to be pedantic, but I think it's important to be precise here. The RHS of an assignment is an expression, and expressions don't have declared types. Expressions may contain variables that have declared types.

**Comment by cdce8p** [comment]
I would agree that mypys handling is a bit strict in this case. Personally I do prefer how pyright handles it. That wasn't the reason for this issue though.

I found it unintuitive that the correctly narrowed type in `__init__` is lost in `func`. If I wanted `self.temperature_unit` to be `int`, I would have declared it that way.

```py
TemperatureUnits = Literal["°C", "°F", "K"]

class UnitSystem:
    def __init__(self, temperature: TemperatureUnits) -> None:
        self.temperature_unit = temperature
        reveal_type(self.temperature_unit)  # it's Literal["°C", "°F", "K"] here

    def func(self) -> None:
        reveal_type(self.temperature_unit)  # only 'int'
```

**Comment by erictraut** [comment]
> the correctly narrowed type in `__init__` is lost in `func`

The type annotation is associated with the parameter `temperature`, and that's not lost. If you reveal type type of `temperature`, you'll see that it is a literal type.

There is no type annotation for the variable `temperature_unit`, so its type must be inferred. Pyright is applying consistent type inference rules to determine its type.

**Comment by cdce8p** [comment]
> The type annotation is associated with the parameter `temperature`, and that's not lost. If you reveal type type of `temperature`, you'll see that it is a literal type.

True. It isn't clear to me why `self.temperature_unit` should be inferred differently in `__init__` compared to `func`. There is no other subsequent assignment happing that would require a wider type.

As a user, if I only assign a variable declared as `Literal`, I would have expected that to be inferred for the instance variable, too. Other inferred types don't loose their "precision" that way.

```py
class A:
    def __init__(self, x: list[int]) -> None:
        self.x = x
        reveal_type(self.x)  # list[int]
    
    def func(self) -> None:
        reveal_type(self.x)  # list[int]
```
It wouldn't be reasonable to infer `self.x` in `func` as `list[Any]`, just because it doesn't have a type declaration.

**Comment by erictraut** [comment]
The inferred type of `temperature_unit` is `int`, but locally within `__init__` is can be further narrowed to a literal type after the assignment. Outside of `__init__` (e.g. within `func`), it falls back to its (un-narrowed) inferred type.

```python
class A:
    def m1(self):
        self.x: int
        reveal_type(self.x) # int
        self.x = 3
        reveal_type(self.x) # Literal[3]

    def m2(self):
        reveal_type(self.x) # int
        self.x = 2 if random() > 0.5 else 3
        reveal_type(self.x) # Literal[2, 3]
```

Consider the following examples. In all three cases, `b` has no annotation, so it needs to be inferred from the type of the expression that is assigned to it. In all three cases, the type of the expression assigned to it is type `Literal[3]`.

```python
class A1:
    def __init__(self, a: Literal[3]) -> None:
        self.b = a
```

class A2:
    def __init__(self, a: Literal[3]) -> None:
        self.b = a if cond else 3
```

```python
class A3:
    def __init__(self) -> None:
        self.b = 3
```

The comparison between literal type inference rules and `list[int]` is specious. They're very different cases. Among other things, the list example involves a type argument to a generic class, not a type. PEP 586 (which introduced literals) provides significant latitude for type checkers to decide when literal types should be assumed and when not, and it does this for good reason. You wouldn't want `self.x = 3` to infer the type of `x` to be `Literal[3]` even though the type of the RHS expression is `Literal[3]`.

In any event, I think the current inference rules in pyright are self consistent, documented, and generally produce better results (fewer false positives and fewer surprises) than mypy. Changing the behavior of these inference rules by adding more special casing would add confusion. Changing these would also be very disruptive to code bases that currently use pyright for type checking, so the bar is very high for making a change.

**Comment by cdce8p** [comment]
> You wouldn't want `self.x = 3` to infer the type of `x` to be `Literal[3]` even though the type of the RHS expression is `Literal[3]`.

True. That should be inferred as `int`. I think of it as an inferred but not narrowed `Literal[3]`. It's different for the case `A1` though. If the RHS has a declared type, the LHS usually copies it. Unless it has its own type declaration which might be wider.

```py
def f1(x: str):
    a = x
    b: str | int = x
    reveal_type(a)  # str
    reveal_type(b)  # str | int
    b = 4
```
Note that here `b` still has the type `str | int` although it can be **inferred** as `str`. If that wouldn't be the case `b = 4` would be an error.

Why should the copy behavior be different for a variable declared `Literal`?

> Changing these would also be very disruptive to code bases that currently use pyright for type checking, so the bar is very high for making a change.

I'm not sure about that. We are only talking about a very limited set of issues. These are already errors if a dedicated type is added which likely was the intention all along. Thus IMO it's more likely a change would catch previously unnoticed errors. I would argue both `self.x = 4` assignments below should raise errors. This is what other type checkers (mypy, pyre) do.

```py
class C1:
    def __init__(self) -> None:
        self.x: Literal[2]
        self.x = 4

class C2:
    def __init__(self, x: Literal[2]) -> None:
        self.x = x
        self.x = 4
```

--
I was just about to submit the comment when I noticed something else. For the example (C3) I had expected that all type checkers would complain about it. However, here again `pyright` excepts the "wrong" assignment of `4` silently and just widens the type to `str | int`. If `str | int` was the intention, I should have added a type declaration. (Something I would do anyway for these cases.)
```py
class C3:
    def __init__(self, x: str) -> None:
        self.x = x
        self.x = 4

    def func(self) -> None:
        reveal_type(self.x)  # this should only be 'str'
```
```
# mypy
error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
note: Revealed type is "builtins.str"

# pyre
Incompatible attribute type [8]: Attribute `x` declared in class `C3` has type `str` but is used as type `int`.
Revealed type [-1]: Revealed type for `self.x` is `str`.
```

**Comment by erictraut** [comment]
> If the RHS has a declared type, the LHS usually copies it

As I explained above, the RHS of an assignment statement is an expression. Expressions don't have declared types. An expression's type is evaluated based on its constituent identifiers, literals, and operators. You're suggesting that an expression that consists of a single identifier that happens to be a variable with a declared type should somehow be treated differently from all other expressions. Why? That would be inconsistent.

Such special cases tend to breed yet more special cases. Consider the following, where x has a declared type but is further narrowed via a type guard. In this case, the type of expression `x` is different from the declared type of `x` because it has been locally narrowed. What rule would you propose be applied in this case when inferring the type of instance variable `y`? Would you apply your special case or not?

```python
class A:
    def m1(self, x: Literal[0, 1]):
        if x == 0:
            self.y = x
```

As for your example `C3`, I think mypy and pyre are wrong here. There is no type declaration for `x`, yet they are treating it as though there is. The pyre error message even uses the word "declared" which is just plain wrong. The type of the instance variable `x` is inferred based on the assignment. Inferring its type based on the "first" assignment (where "first" isn't based on runtime code flow but instead on location within the source file) is arbitrary and leads to many false positive errors. Mypy's issue tracker is full of issues about this. Pyright's inference rules for variables without a declaration is much more flexible and yet maintains type safety. It infers the type of an undeclared variable as the union of all assignments. If your intent is to constrain a variable to a particular type, you have the option of explicitly declaring its type with an annotation. Absent a type declaration, it shouldn't be constrained as such.

**Comment by cdce8p** [comment]
> You're suggesting that an expression that consists of a single identifier that happens to be a variable with a declared type should somehow be treated differently from all other expressions. Why? That would be inconsistent.

I had to check what mypy does. It seems like it always uses inferred type. The only difference being that it doesn't infer `x = 3` as `Literal[3]` but `int` instead, similar for `str` and possibly the other Literal types, I image.

> What rule would you propose be applied in this case when inferring the type of instance variable `y`? Would you apply your special case or not?

The type for `x` is narrowed to `Literal[0]` with the if statement. So that's what would be "assigned" to `self.y`.

> Inferring its type based on the "first" assignment (where "first" isn't based on runtime code flow but instead on location within the source file) is arbitrary and leads to many false positive errors.

Yes, false positives can be an issue. The solution for it however is strait forward.
```py
class A:
    y: int

    def m1(self, x: Literal[0, 1]):
        if x == 0:
            self.y = x

# --
def func(x: Literal[0, 1]):
    y: int
    if some_var():  # type: ignore
        y = x
    else:
        y = 52
```

> If your intent is to constrain a variable to a particular type, you have the option of explicitly declaring its type with an annotation. Absent a type declaration, it shouldn't be constrained as such.

That seems to be the difference in approach between pyright and mypy. `mypy` prefers the strict approach, one more error if it can prevent another, whereas pyright wants to prevent the false-positives at the cost of potentially missing one.

The main advantage I see with the way mypy handles it, is that it's more efficient IMO. Consider something like the example below. It would be much more cumbersome to add types to each instance variable when you've already done so for the function signature. I'm not sure I've seen a project that deliberately chooses to add types for both. It's also a case of remembering to do so for each and ever instance variable across the whole project. Miss one and you potentially miss a type error. I much prefer the "false positive" in that case which I can fix deliberately.
```py
class D:
    def __init__(
        self,
        some_var: int,
        some_var_2: str,
        some_var_3: list[int],
        some_var_4: Literal[2, 3],
    ) -> None:
        self.some_var = some_var
        self.some_var_2 = some_var_2
        self.some_var_3 = some_var_3
        self.some_var_4 = some_var_4
```
