### ISSUE TITLE
Async code and constrained TypeVars

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#2914]
**Describe the bug**
Using a constrained type variable with async code doesn't always work the same as its synchronous counterpart.

**To Reproduce**
Set up a constrained TypeVar then use that constrained TypeVar in a generic coroutine function signature.

**Expected behavior**
The two versions of the code should behave the same.

**Screenshots or Code**
https://pyright-playground.decorator-factory.su/?gist_id=f03100a04ec81b8db2d8c6c3f25cf6ca&filename=test2.py

**VS Code extension or command-line**
v2022.1.3

**Comment by erictraut** [comment]
The reason the behavior differs is that the `await` keyword currently doesn't participate in bidirectional type inference, so the type of the lambda couldn't be inferred in the async case. I've added support for this, so it will work in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.213, which I just published. It will also be included in the next release of pylance.

**Comment by Gobot1234** [comment]
Thank you!
