### ISSUE TITLE
Bi-directional type inference in lambda function parameters

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#2916]
**Is your feature request related to a problem? Please describe.**
lambda function parameters are untyped where they could be infered (as far as I can tell) from the callers annotation's. Ideally this code should have no Unknowns.
```py
from typing import TypeVar, Generic
T = TypeVar("T")
MsgT = TypeVar("MsgT", bound="Msg")

class Msg(Generic[T]):
    body: T
class Request: ...

def check(func: "(MsgT, int) -> object") -> MsgT:
    ...

notification: Msg[Request] = check(
    lambda msg, foo: (
        reveal_type(msg.body),  # revealed type is Unknown  # ideally this should be Request
        reveal_type(foo)  # revealed type is int  # this is already inferred
    )
)
```
Currently I have to define a def function which does mean I can get rid of the annotation to notification, but it's quite clunky and rather verbose especially for what are meant to be throw-away functions.

**Describe the solution you'd like**
Using bi-directional type inference the parameter types the type of msg.body should be Request.

**Comment by erictraut** [comment]
Thanks for the bug report. The logic for bidirectional type inference in lambdas was not properly handling the case where one or more of the matched parameter types was a TypeVar, as in your example. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.213, which I just published. It will also be included in the next release of pylance.

**Comment by Gobot1234** [comment]
Is this a won't fix cause this code still seems to error out on the latest version?

**Comment by erictraut** [comment]
It works correctly now if you provide a proper type argument for the bound type `Msg` in the `MsgT` type variable. 

```python
MsgT = TypeVar("MsgT", bound="Msg[Any]")
```

If you enable the `reportMissingTypeArgument` check (which is on by default in strict mode), pyright will tell you when you've omitted a type argument for a generic class.

**Comment by Gobot1234** [comment]
![image](https://user-images.githubusercontent.com/50501825/151709625-5ce42c5f-85d2-49aa-b695-0a63ec36a985.png)
it doesn't appear to be that way
```
% pyright --version
pyright 1.1.216
```

**Comment by erictraut** [comment]
The type of `msg` is inferred to be `MsgT@check`, which is correct. The type of `msg.body` is therefore `Any`, since it's based on the bound type of `MsgT`. There are no unknown types, and it passes type analysis without any errors. Do you see any problem here?

If I were to change the code to infer `msg` is type `Msg[Request]`, it would not change the behavior in this example, but it would break a number of other important use cases with lambda bidirectional type inference.

**Comment by Gobot1234** [comment]
> Do you see any problem here?

```py
        notification: GCMsgProto[econ.ItemCustomizationNotification] = await self._state.gc_wait_for(
            Language.ItemCustomizationNotification,
            check=lambda msg: (
                msg.body.request == ItemCustomizationNotificationEnum.CasketContents and msg.body.item_id[0] == self.id
            ),
        )
```
```
  /Users/James/PycharmProjects/steam-ext-csgo/steam/ext/csgo/backpack.py:240:72 - error: Expression of type "GCMsgsT@gc_wait_for" cannot be assigned to declared type "GCMsgProto[ItemCustomizationNotification]"
    Type "GCMsgProto[Any]* | GCMsg[Any]*" cannot be assigned to type "GCMsgProto[ItemCustomizationNotification]"
      "GCMsg[Any]*" is incompatible with "GCMsgProto[ItemCustomizationNotification]" (reportGeneralTypeIssues)
 ```
If this was fixed this error would go away (although I'm sure this could be fixed another way). 

> it would not change the behavior in this example

It wouldn't change anything in this example but surely it would be much nicer to get completion for attributes on `ItemCustomizationNotification` instead of having them being `Any` and it's more type safe.

> but it would break a number of other important use cases with lambda bidirectional type inference.

What cases are these?

**Comment by erictraut** [comment]
I have several heuristic in the constraint solver logic specifically to handle various cases, some of which mypy doesn't handle correctly. If I change these heuristics, I can make this case work, but the other cases break. So I think this will have to be a "won't fix".

**Comment by Gobot1234** [comment]
@erictraut what should I do moving forward? Shoud I open an issue about the first problem or should I just use regular functions instead of lambdas?

**Comment by erictraut** [comment]
You'll need to find a workaround.
