### ISSUE TITLE
Param doc string parsing

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#292]
When presenting signature hints, pyright doesn't present doc strings for individual parameters. It would be useful to present these comments if they are present.

**Comment by erictraut** [comment]
This will be included in the next version.

**Comment by erictraut** [comment]
This is now implemented in 1.0.77

**Comment by iansan5653** [comment]
@erictraut I'm having trouble getting this to work. How should docstrings for individual parameters be formatted?

**Comment by erictraut** [comment]
I added support for four different comment formats:
1. Epytext
2. reST
3. Google (variant 1)
4. Google (variant 2)

You can read more details in the source code:
https://github.com/microsoft/pyright/blob/b958b07a701d2524a0cc5d90ac11c0346612697e/server/src/analyzer/docStringUtils.ts#L60

Let me know what's not working, and I can maybe generalize it to accommodate more variations.

**Comment by maxnoe** [comment]
Support for the numpy convention would be great:
https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard
