### ISSUE TITLE
"xxx" is unknown import symbol

### ISSUE THREAD

**Issue by Jackeriss** [microsoft/pyright#2922]
**Describe the bug**
it shows 「"SoupStrainer" is unknown import symbol」when I wrote `from bs4 import BeautifulSoup, SoupStrainer`
I'm sure the package was installed correctly and there was no error msg on 'BeautifulSoup', only on 'SoupStrainer'

**Expected behavior**
it shouldn't show this error，or how can I ignore it?

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/7183428/150672013-db67fdc5-ca3d-4bd8-a950-345917347f6c.png)

**VS Code extension or command-line**
VS Code extension Pylance v2022.1.3 with basic checking mode

**Additional context**
BeautifulSoup doc about SoupStrainer:
https://www.crummy.com/software/BeautifulSoup/bs4/doc/index.html?highlight=soupstrainer

**Comment by JelleZijlstra** [comment]
I opened python/typeshed#7002 to mark `SoupStrainer` as accessible through the bs4 top-level namespace. 

Until that is deployed, you should be able to use `from bs4.element import SoupStrainer` to satisfy pyright.

**Comment by Jackeriss** [comment]
@JelleZijlstra thank you for replying, it works. but I meet another error when using the SoupStrainer
![image](https://user-images.githubusercontent.com/7183428/150684057-bc9582df-a55c-41f5-84af-bce90e41446a.png)

![image](https://user-images.githubusercontent.com/7183428/150683994-64788050-e937-4025-bcfc-a48e593c0b6a.png)
how to fix it?

**Comment by erictraut** [comment]
When reporting bugs, please include minimal, self-contained code samples. Incomplete code screen shots are much less useful.

This doesn't appear to be a bug in pyright. It's performing type checking correctly given the type information it has been given. If you suspect this is a problem in the type stubs for bs4, please file those bugs in the [typeshed repo](https://github.com/python/typeshed). Pyright (and all other Python type checkers) use stubs that originate from this repo. It looks like Jelle has already added one fix there.

**Comment by erictraut** [comment]
Jelle's PR was merged into the typeshed repo, and I've pulled the updated typeshed stubs into pyright. So the first issue you reported will be addressed in the next release of pyright.

As for the second issue you reported, I don't know enough about this library to determine whether this should be allowed. I know that pyright is correctly interpreting the type information in the stub and emitting an error in this case. If you suspect that the type information is incorrect, please file a bug in the typeshed project.
