### ISSUE TITLE
Cannot use `dict()` built-in function with TypedDicts

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/pyright#2923]
```python
from typing import TypedDict

class Movie(TypedDict):
    name: str

# works
movie: Movie = {'name': 'Foo bar'}

# Expression of type "dict[str, str]" cannot be assigned to declared type "Movie"
movie: Movie = dict(name='Foo bar')
```

(using pyright 1.1.214)

**Comment by erictraut** [comment]
Yes, this is expected behavior. The `dict` constructor returns a value of type `dict`, which isn't assignable to a TypedDict. You need to use a Python dict expression, whereby pyright can use bidirectional type inference to infer that it is a TypedDict.
