### ISSUE TITLE
Execution environments share each others search paths

### ISSUE THREAD

**Issue by Josverl** [microsoft/pyright#2924]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**

when using a `pyrightconfig.json` file that has execution environmentnts defined , where each of the execution environmnets has different `extraPaths` defined : 
the result is that pyright  acts and reports that each of the execution environments should use to **combination of all** extraPaths defined for all execution environment.

that is in contradiction to the documented behaviour , where each execution environment should be allow extraPaths to be spefied specifically for that execution environment

> The following settings can be specified for each execution environment.
> **extraPaths** [array of strings, optional]: Additional search paths (in addition to the root path) that will be used when searching for modules imported by files within this execution environment. If specified, this overrides the default extraPaths setting when resolving imports for files within this execution environment. Note that each file’s execution environment mapping is independent, so if file A is in one execution environment and imports a second file B within a second execution environment, any imports from B will use the extraPaths in the second execution environment.

**To Reproduce**

See repo : https://github.com/Josverl/pyright-exec-env
run pyright or pylance.
they prove false results as none of the script-xxxx.py files should pass without errors 
each of the execution environments hould only allow imports defined in the extraPaths for that execution environments , and flag import errors (`reportMissingImports`) for some of the imports

**Expected behavior**

**Screenshots or Code**
All code can be found in the repo linked above.

![image](https://user-images.githubusercontent.com/981654/150686484-da8a2ea2-c18b-4bc3-bcc6-2afcb9384505.png)

![image](https://user-images.githubusercontent.com/981654/150686465-c9eabee2-2405-463c-a0bd-85ce18645470.png)

![image](https://user-images.githubusercontent.com/981654/150686456-7e80be05-312b-4a48-939e-47daed156146.png)

**VS Code extension or command-line**
Note that the issue is observed from both the commandline and in VSCode pylance

pyright 1.1.214
Pylance v2022.1.3

**Additional context**
pyright output: 
[pyright.log](https://github.com/microsoft/pyright/files/7920775/pyright.log)

Pylance output : 
[pylance.log](https://github.com/microsoft/pyright/files/7920776/pylance.log)

I am aware that the that the stub files used in this example are not type-complete, I believe that is not relevant to the issue, but if it is the please advise.

**Comment by erictraut** [comment]
Thanks for the bug report. The repro was very helpful.

Your analysis is correct. The "extraPaths" for individual execution environments are not being processed correctly if there is a default "extraPaths" specified at the top level of the config file. A fix for this issue will be included in the next release.

In the meantime, you can work around the bug by deleting the `"extraPaths": []` line from your config file.

**Comment by Josverl** [comment]
Thanks for the very quick answer and the workaround.

I can confirm that not specifying a toplevel `"extraPaths": ` indeed allows pyright to report the expected reportMissingImports.
That is an acceptable workaround for me and happy to see it fully addressed in a next version.

**Comment by erictraut** [comment]
This is included in pyright 1.1.215, which I just published. It will also be included in the next release of pylance.
