### ISSUE TITLE
Wrong type of User in Django

### ISSUE THREAD

**Issue by Bazulenkov** [microsoft/pyright#2939]
**Describe the bug**
I use Django 3,2,4
I have User-model:
```
class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField("Email пользователя", unique=True)
    role = models.CharField(
        "Роль", max_length=20, choices=Role.choices, default=Role.CLIENT
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), auto_now_add=True)

    objects: UserManager = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        db_table = "users"
        verbose_name = _("user")
        verbose_name_plural = _("users")
        constraints = [
            models.CheckConstraint(
                check=models.Q(role__in=Role.values),
                name="%(class)s_role_valid",
            )
        ]

    def __str__(self):
        return f"{self.email}"

    @property
    def is_staff(self):
        return self.is_superuser
```

Django recommends to import User model like this
```
from django.contrib.auth import get_user_model

User = get_user_model()
```

If I make this,
I receive `User: Type[Model]`

And then I receive error: `Cannot access member "create_user" for type "BaseManager[Any]"
  Member "create_user" is unknown`
```
some_func():
    ....
    User.objects.create_user(**user_data)
    ....
```

**VS Code extension or command-line**
I use Pylance.

**Additional context**
I see that get_user_model() -> Type[Model]  - And this behavior generates the error above.

**Comment by erictraut** [comment]
Could you please create a minimal, self-contained sample? The sample above references a bunch of symbols that are presumably imported from somewhere. I'm not familiar with django, so I'm not able to reproduce the problem without additional information.

**Comment by Bazulenkov** [comment]
Look at https://github.com/Bazulenkov/yatube/blob/77dcf4cb88bd0357fc473a94038860807bca4249/posts/tests.py#L14
![image](https://user-images.githubusercontent.com/38315253/151393798-e8ec58b1-bb86-489e-a6a6-68c988899c64.png)

**Comment by erictraut** [comment]
I presume that you have the `django-stubs` stub package installed.

Pyright appears to be doing the right thing here.

The function `get_user_model` is annotated to return `Type[Model]`. The `Model` class has an attribute `objects` that is annotated as type `BaseManager[Any]`. The class `BaseManager` does not have a declared method `create_user`. Pyright is correctly reporting this type error.

If you think that the `django-stubs` are in error, please file a bug with the maintainer of that package.

**Comment by Bazulenkov** [comment]
I use Pylance,

**Comment by Bazulenkov** [comment]
> I presume that you have the `django-stubs` stub package installed.
> 
> Pyright appears to be doing the right thing here.
> 
> The function `get_user_model` is annotated to return `Type[Model]`. The `Model` class has an attribute `objects` that is annotated as type `BaseManager[Any]`. The class `BaseManager` does not have a declared method `create_user`. Pyright is correctly reporting this type error.
> 
> If you think that the `django-stubs` are in error, please file a bug with the maintainer of that package.

I see this by myself.

**Comment by erictraut** [comment]
Yes, I confirmed that pylance bundles stubs for django. They come from [this repo](https://github.com/typeddjango/django-stubs).
