### ISSUE TITLE
Inconsistent JSON output

### ISSUE THREAD

**Issue by ttbilgin** [microsoft/pyright#2949]
Could you please explain me why the second error section has a "rule" key but the first one does not have? It should be report rule for each error.

Here is the content of t.py file
'''
print(10/b
'''
![image](https://user-images.githubusercontent.com/854154/151529717-589ac2ba-fc24-46c3-b121-77100e2699b1.png)

**Comment by hmc-cs-mdrissi** [comment]
https://github.com/microsoft/pyright/blob/main/docs/command-line.md

> Not all diagnostics have an associated diagnostic rule. Diagnostic rules are used only for diagnostics that can be disabled or enabled. If a rule is associated with the diagnostic, it is included in the output. If it’s not, the rule field is omitted from the JSON output.
