### ISSUE TITLE
Check for missing await for `Awaitable`

### ISSUE THREAD

**Issue by ColCh** [microsoft/pyright#2963]
**Is your feature request related to a problem? Please describe.**

#1317 introduced brilliant check for missing `await` upon `Coroutine`, but it still is missing upon `Awaitable` type

**Describe the solution you'd like**

Given this code

```py
import asyncio
from typing import Awaitable

def my_fun() -> Awaitable[bool]:
    ...

async def sleep():
    asyncio.sleep(3) # err :)
    my_fun() # no err :(
```

screenshot format if you like

![image](https://user-images.githubusercontent.com/599439/151873952-5acf7181-3ba7-4a29-a8b8-1d2dc3c0d10c.png)

**Additional context**
 
Awaitable is a type for Future and Task as well as for Coroutine, but they are possible to be `await`'ed

**Comment by ColCh** [comment]
oops it's dupe for #2499,  sorry

**Comment by erictraut** [comment]
This was discussed in #1317, and we decided that we'd limit that feature to `Coroutine`. Please refer to that thread for details.
