### ISSUE TITLE
Add reference to VS Code python.analysis.diagnosticSeverityOverrides in pyright/docs/configuration.md

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#2981]
**Is your feature request related to a problem? Please describe.**
When looking at the various type checking options at https://github.com/microsoft/pyright/blob/main/docs/configuration.md , there was no mention that you could have a type setting like `reportPropertyTypeMismatch` in the VS Code `settings.md` file

**Describe the solution you'd like**
Add a line in that file that says that another way to handle settings is to use `python.analysis.diagnosticSeverityOverrides` in VS Code `settings.json` .  Indicate the priority of that versus `pyrightconfig.json` versus `pyproject.toml`

**Additional context**
This is what confused me when I reported a recent issue.

**Comment by erictraut** [comment]
The [configuration documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) talks about the configuration file. There are numerous configuration keys that also have settings counterparts. It's not specific to diagnostic severities.

The [settings documentation](https://github.com/microsoft/pyright/blob/main/docs/settings.md) does document the `python.analysis.diagnosticSeverityOverrides` setting.

**Comment by Dr-Irv** [comment]
Well, yes, but if you are looking at the different settings for turning off different type checking options at https://github.com/microsoft/pyright/blob/main/docs/configuration.md , there is a reference of what to do in `pyproject.toml` and `pyrightconfig.json`, and it would just be helpful to add this additional information on that page to make it easier to find.

There is never anything wrong with adding more and more documentation!
