### ISSUE TITLE
Where is new versions?

### ISSUE THREAD

**Issue by urtow** [microsoft/pyright#2984]
Pyright is great, but where I can find new versions?
I only found 0.0.13 in pypi

https://pypi.org/project/pyright/

**Comment by erictraut** [comment]
The `pyright` package in pypi is not maintained by Microsoft. It is a community-maintained package that downloads and installs the latest version of pyright. It checks for a new version each time you run it, so you if you use the pypi package, you should always be up to date with the latest version of pyright.
