### ISSUE TITLE
fsspec library - Why doesn't pyright find the type of a class in that library?

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#2988]
**Describe the bug**
We're using `s3fs` in our project, which depends on `fsspec` (https://pypi.org/project/fsspec/).  That library is not typed.  While trying to figure out some typing issues, I could not figure out why pyright couldn't figure out the type of a declared class in that library.

**To Reproduce**
See example below.  The revealed type is "Unknown"

**Expected behavior**
Would expect that it would know that `AbstractFileSystem` is a class.

**Screenshots or Code**
```python
from fsspec import AbstractFileSystem


def giveit(s: str) -> AbstractFileSystem:
    return AbstractFileSystem()


foo = giveit("hey")

reveal_type(foo)
```

**VS Code extension or command-line**
pylance 2022.2.0 in VS Code on Windows,  python 3.8

**Additional context**
In VSCode, if I right-click on `AbstractFileSystem` in the first line, and ask VSCode to find the definition, it can't find it.  If I hover over `AbstractFileSystem`, it says `(import) AbstractFileSystem: Unknown` .  If I then right click on `fsspec` and "Go to Definition", then `fsspec/__init__.py` opens up, and if I now hover over `AbstractFileSystem` in my file, it shows `(class) AbstractFileSystem`, and I can right-click on `AbstractFileSystem` in my code and it goes to the definition.

So I don't understand why it's not doing this inference without opening up `fsspec/__init__.py` .

**Comment by erictraut** [comment]
By default, pyright treats all imports from untyped libraries as "Unknown", so this is expected behavior.

If you want pyright to attempt to infer types from the code, you can enable `useLibraryCodeForTypes`. This is typically good enough for completion suggestions, but it often leads to false positives if you're using these inferred types for type checking. For that reason, pylance enables `useLibraryCodeForTypes` by default but pyright does not.

**Comment by Dr-Irv** [comment]
Well, I'm doing this from VS Code (pylance), and if `useLibraryCodeForTypes` is on by default, why didn't it pick up the type for this specific library?

I've tried it with other third party libraries, and the types __are__ correctly inferred for those libraries within VSCode.

**Comment by erictraut** [comment]
I'm not able to repro with Pylance. 

![Screen Shot 2022-02-04 at 2 32 35 PM](https://user-images.githubusercontent.com/7040122/152612105-8d5414ce-491b-4ff2-b06e-8d2291ae182b.png)

Can you repro with a fresh project using the sample above? If not, then it's probably a configuration or setting issue with your current project. Perhaps you have `useLibraryCodeForTypes` disabled?

**Comment by Dr-Irv** [comment]
> Can you repro with a fresh project using the sample above? If not, then it's probably a configuration or setting issue with your current project. Perhaps you have `useLibraryCodeForTypes` disabled?

Ugh.  You're right.  I forgot that I have that disabled because other third party libraries created problems, which is why I created #379 so I could easily pick and choose which libraries to include.
