### ISSUE TITLE
`Iterable` incorrectly evaluated as always truthy

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pyright#3006]
Pyright version: v1.1.219

```py
from collections.abc import Iterable

def f(foo: Iterable[int]) -> None:
    if foo:
        print(sum(foo))
        reveal_type(foo)  # Iterable[int]
    else:
        reveal_type(foo)  # Never
```
This doesn't seem right: there are definitely iterables which are falsey.
(admittedly, checking `Iterable` for truthiness doesn't make much sense to me. maybe there's a better example?)

However, if you explicitly define `__bool__` on the type, it does work correctly
```py
import random
from typing import TypeVar, Generic
from collections.abc import Iterable


T = TypeVar("T")


class CoolIterable(Iterable[T], Generic[T]):
    def __bool__(self) -> bool:
        return random.random() > 0.5


def f(foo: CoolIterable[int]) -> None:
    if foo:
        print(sum(foo))
        reveal_type(foo)
    else:
        reveal_type(foo)
```

---

Possibly related to #3005 ?

**Comment by erictraut** [comment]
Pyright currently treats all objects as implicitly truthy unless their class implements a `__bool__` or `__len__` method. Protocol classes should probably be exempt from this assumption since a class that conforms to a protocol may also implement a `__bool__` or `__len__` method.

This will be addressed in the next release.

**Comment by decorator-factory** [comment]
Hm. Does that mean that overriding `__bool__` with something non-default is considered an incompatible override (i.e. LSP violation)?

In particular, all objects derive from `object`, but:
```py
def f(x: object):
    if x:
        x  # x: object
    else:
        x  # x: Never 
```
Or, perhaps, a mixin class?

**Comment by erictraut** [comment]
Strictly speaking, any non-final class could be subclassed in a way that adds a `__bool__`, but that would preclude the use of this form of type narrowing for any class that isn't final. This is a case where I think practicality beats strictness. In the unlikely (theoretical) example you gave above, you can use `if bool(x):` if your intent is to support object subclasses that add a custom `__bool__` method.

**Comment by decorator-factory** [comment]
That seems reasonable.
