### ISSUE TITLE
crashed error in vscode extension:  fatal process out of memory: Failed to reserve memory for new V8 Isolate

### ISSUE THREAD

**Issue by joezhu1102** [microsoft/pyright#3020]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**
I meet a crashed effor of pyright in vscode. any one know what is the reason and how to solve it , thank you.

error info:
#FailureMessage Object: 0x7ff5ad1e8260
[Info  - 4:32:28 PM] Connection to server got closed. Server will restart.
[Info  - 4:32:29 PM] Pyright language server 1.1.195 starting
[Info  - 4:32:29 PM] Server root directory: /home/xxxxx/.vscode/extensions/ms-pyright.pyright-1.1.212/dist

#
# Fatal error in , line 0
# Fatal process out of memory: Failed to reserve memory for new V8 Isolate

**To Reproduce**
When start vscode with above version, pyright won't be started
I tried lower to 1.1.195, same issue.

**Expected behavior**
pyright should be started normally.

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
def foo(self) -> str:
    return 3
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.
vscode version info:
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:58:13.605Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 4.18.0-305.3.1.el8_4.x86_64

**Additional context**

**Comment by erictraut** [comment]
Hmm, we haven't received reports of this from other users.

A few thoughts... first, it looks like you're running a version of VS Code that is about half a year out of date. Could you try updating to the latest version? Second, if you're running VS Code, we recommend that you use Pylance rather than Pyright. Pylance is built on top of Pyright, and it has a superset of the functionality available on Pyright. I'd be interested to hear whether Pylance reproduces the same problem you're seeing.

**Comment by joezhu1102** [comment]
pylance has same problem log in output if don't upgrade vscode (just remove pyright).  
then I installed latest version VSCode and reset all workspace setting. 
Seems work now, no crash log, output of "python language server" is ok.
thank you!

> Hmm, we haven't received reports of this from other users.
> 
> A few thoughts... first, it looks like you're running a version of VS Code that is about half a year out of date. Could you try updating to the latest version? Second, if you're running VS Code, we recommend that you use Pylance rather than Pyright. Pylance is built on top of Pyright, and it has a superset of the functionality available on Pyright. I'd be interested to hear whether Pylance reproduces the same problem you're seeing.
