### ISSUE TITLE
[QUESTION] How to ignore this kind of errors

### ISSUE THREAD

**Issue by Ddystopia** [microsoft/pyright#3042]
Hello, I'm opening official examples of library usage ([python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot)) and getting these errors. What can I do, to ignore them all (something like filtering "user_data"), but not add comment every line or turning off pyright?
![First](https://i.imgur.com/K8oI15F.png)
![Second](https://i.imgur.com/YvPXPmM.png)
![Third](https://i.imgur.com/vsjvP1F.png)
I tried to do this, but it still throws
![_](https://i.imgur.com/rB1YFFi.png)

**Comment by erictraut** [comment]
It's difficult to diagnose issues like this from screen shots alone. For future questions or bug reports, please include minimal stand-alone code samples.

It appears from the screen shot that the static analyzer has determined that the value `context.user_data` potentially contains `None`. If it does, your program will crash at runtime. You would need to add code that verifies `context.user_data` is initialized with something other than `None` to make it safe.

If you are confident that `context.user_data` does not contain `None` at a particular point in the code, you can add the statement `assert context.user_data is not None`. This documents your assumption, validates your assumption at runtime, and tells pyright that it should subsequently assume that `context.user_data` is not `None`.
