### ISSUE TITLE
"int|None" object passed to range() function gives typing error

### ISSUE THREAD

**Issue by Nicolacarrino** [microsoft/pyright#3043]
**Describe the bug**
Pylance throws a `reportGeneralTypeIssues` error when passing `"int|None"` type object as argument of `range` function which accepts only `SupportsIndex`.

The error message is 
`Argument of type "int | None" cannot be assigned to parameter "__stop" of type "SupportsIndex" in function "__init__"
  Type "int | None" cannot be assigned to type "SupportsIndex"
    "__index__" is not present`

**Screenshots or Code**

```python
import os

num_processes = os.cpu_count()

# Create processes
for i in range(num_processes):
    print(i)

```

**VS Code extension or command-line**
I am running pyright as a VS Code extension using Pylance. Pylance v2022.2.1.

Since the return type of `cpu_count()` is `Optional[int]` and range accepts only `SupportsIndex`, how can I make Pyright (using Pylance) understand that this is not an error?
What kind of conversion could I do from `Optional[int]` to `SupportsIndex`?

**Comment by erictraut** [comment]
Pyright has found a bug in your code! You can fix it as follows:

```python
numProcesses = os.cpu_count()
if numProcesses is None:
    numProcesses = 1
```

Or

```python
numProcesses = os.cpu_count() or 1
```

**Comment by Nicolacarrino** [comment]
@erictraut Thank you for the suggestion!
