### ISSUE TITLE
`Final` variable not typed as `Literal` when it comes from an import.

### ISSUE THREAD

**Issue by TonyRippy** [microsoft/pyright#3044]
**Describe the bug**

Consider the following code:

```python
from typing import Final
TEST_CONSTANT: Final = 'foo'
reveal_type(TEST_CONSTANT)
```
When pyright is run against this code, `reveal_type` reports:
> Type of "TEST_CONSTANT" is "Literal['foo']"

... which is expected. We use [a library](https://github.com/tfranzel/drf-spectacular/blob/27ac1ca9f288c154ba2110d5ef8b828a0501ed60/drf_spectacular/drainage.py#L7-L12) that does the following: (simplified)

File "compat.py":
```python
if sys.version_info >= (3, 8):
    from typing import Final
else:
    from typing_extensions import Final
```
File "library.py":
```python
from compat import Final
TEST_CONSTANT: Final = 'foo'
```
File "my_code.py":
```python
from library import TEST_CONSTANT
reveal_type(TEST_CONSTANT) 
```
When pyright v1.1.211 is run against `my_code.py`, it reports:
> Type of "TEST_CONSTANT" is "Final"

... which is not expected. My guess at what is happening is that pyright doesn't recognize that "compat.Final" is actually "typing.Final"; some information gets lost through the import.

**VS Code extension or command-line**
We're running pyright from the command-line using: `yarn run pyright .`

**Comment by erictraut** [comment]
`Final` requires special handling in pyright. In particular, the binder (one of the early phases of type analysis) needs to know about `typing.Final` or `typing_extensions.Final`. Because of this, it will not work correctly if you alias `Final` from some other module. You need to import it directly from `typing` or `typing_extensions`.
