### ISSUE TITLE
Get `exclude` values from `.gitignore` (or any file)

### ISSUE THREAD

**Issue by wmayner** [microsoft/pyright#3047]
**Is your feature request related to a problem? Please describe.**
Often I want to simply exclude paths that are ignored by git. These are already listed in the `.gitignore` file, so it would be convenient and DRY if there were a way to specify that (i.e., something similar to the `--exclude-from` option in `rsync`).

**Describe the solution you'd like**
A natural solution is to support a key like `excludeFrom` in the config, which points to a file containing `exclude` values. Ideally this would be appended to the explicit values given to `exclude`.

**Comment by erictraut** [comment]
This has been discussed previously and rejected. Our thinking is that configuration details for source code management (such as git) should be separate from configuration details for other tools. The semantics are different between the two. 

Plus, embedding knowledge of one tool's configuration format, structure, and semantic interpretation within another independent tool is fraught with potential problems.

**Comment by wmayner** [comment]
Thanks for the reply—yeah, I see the logic there. I think `.gitignore` is a good motivating example, but my suggestion is slightly different and more agnostic than #129.

What I'm envisioning would not be specific to git or any other tool, and would not require mixing semantics across tools. It would just be adding a layer of indirection to existing configuration logic which would add flexibility and convenience. For my use-case (and I suspect many others) this flexibility would be valuable because I could choose to use the `.gitignore` as the exclude file, but it would require no commitment on the part of `pyright` to know about other tools' semantics apart from the very general "paths are lines in a file" assumption.

**Comment by erictraut** [comment]
The gitignore file format supports [patterns](https://git-scm.com/docs/gitignore) other than basic paths. That's perfectly legit for a tool like git to define — and even extend over time — the format and interpretation of its own configuration file. A tool like pyright should not take a dependency on the format, structure, and interpretation of another tool's configuration file.

**Comment by wmayner** [comment]
I agree. I'm not suggesting to support git's definition of patterns. I'm suggesting to use pyright's existing definition of paths—valid values for `include`, `exclude`, etc.—and support listing these indirectly, in a file pointed to by a new key, e.g. `excludeFrom`, rather than directly in the config file. I think this feature stands on its own (and if pyright's definition of path happens to coincide with git's in some cases, then that's a happy accident, with no implied support commitments 😸 ).

**Comment by erictraut** [comment]
Speaking as one of the people responsible for supporting pyright, the phrase "no implied support commitments" sounds problematic. :) It would become a support burden. Sorry, but I don't think this feature idea is something we would be interested in incorporating.

**Comment by wmayner** [comment]
Fair enough.
