### ISSUE TITLE
TypeVarTuple not assignable to tuple with bound types

### ISSUE THREAD

**Issue by ian-r-rose** [microsoft/pyright#3067]
**Describe the bug**

I was experimenting with `TypeVarTuple`s, and came up with some surprising behavior that seems like a bug to me. My use case is to try to describe a tuple where the first element is a callable and the rest of the elements are args (represented by a `TypeVarTuple`) to that function.

When I then try to assign a value with that type it works if I specify the arg types, but fails if I leave them as `Unknown/Any`.

**To Reproduce**

```python
from typing import Any, Callable

from typing_extensions import TypeAlias, TypeVarTuple, Unpack


TaskArgs = TypeVarTuple("TaskArgs")
Task: TypeAlias = tuple[Callable[[Unpack[TaskArgs]], Any], Unpack[TaskArgs]]

def fn(x: int, y: str) -> str:
    return str(x) + y

t1: Task[int, str] = (fn, 1, "2")  # works
t2: Task = (fn, 1, "2")  # fails
```

```python-traceback
error: Expression of type "tuple[(x: int, y: str) -> str, Literal[1], Literal['2']]" cannot be assigned to declared type "Task[Unknown]"
    Tuple entry 1 is incorrect type
      Type "(x: int, y: str) -> str" cannot be assigned to type "(*TaskArgs@Task) -> Any"
        Parameter 1: type "*TaskArgs@Task" cannot be assigned to type "*tuple[int, str]"
          Element size mismatch; expected 2 but received 0 (reportGeneralTypeIssues)

```

**Expected behavior**

I expected `t2` to have `TaskArgs` with type `Tuple[*Unknown]` so that any tuple of types could be assigned to it.

**VS Code extension or command-line**

pyright@1.1.222 via command line.

**Comment by erictraut** [comment]
The problem is that you've defined a generic type alias, but then you haven't supplied type arguments for it.

You will see the same problem for traditional TypeVars.

```python
_T = TypeVar("_T")
MyTypeAlias: TypeAlias = List[_T]
x: MyTypeAlias = ["a", 3] # Type argument is missing
```

If you provide type arguments (as you've done with `t1`), it will work fine.

**Comment by ian-r-rose** [comment]
I know that `mypy` isn't the final arbiter of things like this, but this sounds like it's counter to the behavior described [here](https://mypy.readthedocs.io/en/stable/generics.html#generic-type-aliases), which infers `Any` for the type arguments of an unspecified generic type alias.

More generally, is there a way for me to say "this could have anything for it's `TypeVarTuple`, or to infer it from the usage? I wasn't able to find one.

**Comment by erictraut** [comment]
Here's how you'd specify those type arguments using PEP 646 syntax:

```python
t2: Task[*tuple[Any, ...]] = (fn, 1, "2")
```

**Comment by ian-r-rose** [comment]
> Here's how you'd specify those type arguments using PEP 646 syntax:
> 
> ```python
> t2: Task[*tuple[Any, ...]] = (fn, 1, "2")
> ```

Ah, right you are! This is a fine workaround, though to me it still seems counter to the behavior of other generics, e.g.

```python
x = [1, "a"]
reveal_type(x)  # list[str | int]
```

**Comment by erictraut** [comment]
The statement `x = [1, "a"]` is an example of type inference. That's different from a type annotation, where you (the programmer) are spelling out the type. If you're providing a type annotation for a generic type, you should provide the type arguments. It's a very common mistake to omit them. Mypy will assume `Any` in this case, but that's often counter to the intent of the programmer who simply forgot to add the type argument or didn't realize that the type was generic.

**Comment by erictraut** [comment]
Thanks for explaining the use case. Makes sense.

**Comment by ian-r-rose** [comment]
Agreed it's an example of inference, I should have written my example to include an unbound generic, as in this, which pyright accepts:

```python
x: list = [1, "a"]
reveal_type(x)  # list[str | int]
```

I was hoping that I might be able to do the same with a more complex unbound generic, but can work with explicitly adding `Any`. Thanks for the discussion.
