### ISSUE TITLE
Variable is not defined in an if inside a list compreenshion in a class definition

### ISSUE THREAD

**Issue by bellini666** [microsoft/pyright#3069]
Don't know how to properly describe this, but this simple example should explain it.

```python
class Foo:
    A = [1, 2, 3]
    B = [3, 4, 5]
    C = [i for i in B if i not in A]
```

Running pyright on that example get the following:
![Screenshot from 2022-02-17 20-38-53](https://user-images.githubusercontent.com/134025/154589872-1a9bed0b-4c91-490b-a7f8-54a49e0a35eb.png)

This with 1.1.222

**Comment by JelleZijlstra** [comment]
I'm glad my report in #2977 actually helped find a real-world issue :)
