### ISSUE TITLE
Setting `typeshedPath` in the VS Code workspace settings

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/pyright#3079]
It is common practice to commit `pyrightconfig.json` into version control.

This does however somewhat clash with the `typeshedPath` option, which I have pointed to a local directory with my latest typeshed contributions ... I of course do not want to commit the path to my local typeshed into the repository ... so I end up always having a dirty `pyrightconfig.json` file in my repo, which disturbs my git workflow (e.g. I accidentally loose it when doing `git stash`).

I therefore would like to configure the `typeshedPath` in `.vscode/settings.json` (because I do not track that file in version control).

**Comment by erictraut** [comment]
You can already do this through the use of the `python.analysis.typeshedPaths` setting as documented [here](https://github.com/microsoft/pyright/blob/main/docs/settings.md).

**Comment by not-my-profile** [comment]
Ah, thanks! The reason I didn't find that setting was that I thought I could discover the pyright settings via the autocompletion by typing `pyright`:

![2022-02-19-163742_548x152_scrot](https://user-images.githubusercontent.com/73739153/154807772-049db86a-8a5c-4445-b7f9-d04af2386cb0.png)
