### ISSUE TITLE
Autocomplete suggestions for TypedDict

### ISSUE THREAD

**Issue by fluggo** [microsoft/pyright#308]
**Describe the bug**
The autocomplete suggestions for TypedDict suggest the dictionary's keys as attributes instead of keys. The suggestions do not include native dictionary methods such as `keys` or `setdefault`.

**To Reproduce**
![typeddict-intellisense](https://user-images.githubusercontent.com/2552507/67588810-a459bc00-f71c-11e9-9dbc-e748ec3a1226.png)

**Expected behavior**
A TypedDict's keys shouldn't be in the attributes suggestions, but they should be suggested for the `data['literal']` syntax. The suggestions should include dictionary methods.

**VS Code extension or command-line**
This is the VS Code extension version 1.0.81.

**Comment by erictraut** [comment]
Thanks for the bug report. When I initially added support for TypedDict, it was exposed only through the typing_extensions module, not through typings. It works as expected if you import TypedDict from typing_extensions, but the way that "_TypedDict" was exposed in typings.pyi was subtly different. I've adjusted the pyright code to handle both cases properly. The fix will be in the next release.

**Comment by erictraut** [comment]
This is now fixed in 1.0.82, which I just published.

**Comment by giyyapan** [comment]
@fluggo metioned that:

> A TypedDict's keys shouldn't be in the attributes suggestions, but they should be suggested for the data['literal'] syntax.

But pyright still suggest attributes here:

![image](https://user-images.githubusercontent.com/3479453/70239408-36d28e00-17a6-11ea-87cd-475644ac7409.png)

Additionaly, I noticed pyright extension won't suggest TypedDict's attributes for the `data['literal']` syntax.

@erictraut any plan on this?

![image](https://user-images.githubusercontent.com/3479453/70239341-19052900-17a6-11ea-875d-c0df96d1a0a2.png)

Additional context: I'm using Pyright 1.1.8 and using TypedDict from type_extension package.

Thanks!

**Comment by giyyapan** [comment]
Sorry, I noticed that the auto-complete suggestion for TypedDict attributes in my previous comment is actually provided by vscode-python extension, and it's gone after I disable vscode-python.

So my only `problem` would be:

> I noticed pyright extension won't suggest TypedDict's attributes for the `data['literal']` syntax.

Thank you.
