### ISSUE TITLE
Pyright recognize methods with leading double underscore parameter as different functions

### ISSUE THREAD

**Issue by AnhQuanTrl** [microsoft/pyright#3089]
**Describe the bug**
pyright report two function with the same signature (one with leading undescore in the parameter and one without) as incompatible.

**To Reproduce**
I created a protocol Comparable to be used in the sorting class:
```python
T = TypeVar("T", bound="Comparable")

class Comparable(Protocol):
  def __lt__(self: T, x: T) -> bool:
      ...
class Sort(ABC, Generic[T]):
    @abstractmethod
    def sort(self, data: List[T]) -> None:
        pass

class BubbleSort(Sort[T], Generic[T]):
    def sort(self, data: List[T]) -> None:
       ...
```
However, when creating an instance of bubble sort, `a = BubbleSort[int]()` Pylance/Pyright report this error:
```
Type "int" cannot be assigned to type variable "T@BubbleSort"
  Type "int" is incompatible with bound type "Comparable" for type variable "T@BubbleSort"
    "int" is incompatible with protocol "Comparable"
      "__lt__" is an incompatible type
        Type "(__x: int) -> bool" cannot be assigned to type "(x: int) -> bool"
          Position-only parameter mismatch; expected 1 but received
```
If I add double underscore to the signature of `__lt__`, the error is gone:
```python
class Comparable(Protocol):
    def __lt__(self: T, __x: T) -> bool:
        ...
```
**Expected behavior**
`(__x: int) -> bool` should be compatible with `(x: int) -> bool` because they have the same function signature.

**Comment by hmc-cs-mdrissi** [comment]
Double underscore is a type stub convention for a positional only parameter. Positional only parameters do not check name of the parameter. That's why `__x` works but not x. If you don't want to use double underscore syntax you can also use positional only marker and do,

```python
class Comparable(Protocol):
    def __lt__(self: T, x: T, /) -> bool:
        ...
```

But if you don't use any way of marking parameter as positional only it is treated as a potential keyword parameter. keyword parameters compatibility check includes name of the arguments.

**Comment by erictraut** [comment]
Yes, this behavior is correct. As @hmc-cs-mdrissi said, a parameter with a name starting with a double underscore is the convention used for a "positional only" parameter. Prior to [PEP 570](https://www.python.org/dev/peps/pep-0570/) and Python 3.8, a double underscore parameter name was the only way to express this. 

The two signatures are comparable:
```python
def foo(__x: int) -> None: ...

def foo(x: int, /) -> None: ...
```

Neither of these signatures is type compatible with:

```python
def foo(x: int) -> None: ...
```

If someone were to call the function with a keyword argument (`foo(x=3)`), it would crash.
