### ISSUE TITLE
Add type inference based on default values

### ISSUE THREAD

**Issue by Rizhiy** [microsoft/pyright#3092]
**Is your feature request related to a problem? Please describe.**
When an argument is provided without an explicit type, but with a default value, it would be nice if the type of default value is used.

**Describe the solution you'd like**
```python
def example(a="foo"):
    reveal_type(a) # Currently, returns 'Unknown', return 'str' instead
```

**Comment by erictraut** [comment]
It's an interesting idea. TypeScript does this, and it works well. 

One complication is that it's common to use `None` as the default argument value in Python, and it would be problematic to infer a `None` type for the parameter in this case. Maybe it would work if we applied inference in all cases other than `None`.

Another option that the Pylance team has been considering is to add a code action that allows you to insert a type annotation, and the recommended type annotation would be based on various clues including the default argument expression. If this code action were available, would that meet your needs? Or would you still want parameter type inference?

**Comment by erictraut** [comment]
The use of a `None` default value to imply an `Optional` type is supported, but PEP 484 has been updated to recommend against type checkers doing this. Pyright offers `strictParameterNoneValue` to enable or disable this behavior. It currently defaults to false, but we will likely switch to true at some point in the future in accordance with the updated PEP 484 recommendation.

I'll also note that `Optional[Any]` is not the same as `Any`. The former is more specific and indicates that the value might be `None`, so type validation is performed as though `None` is a possible value.

As with the other [feature request you submitted recently](https://github.com/microsoft/pyright/issues/3094), I think this feature is worth considering, but primarily for users of pyright who are not interested in static type checking. It would benefit those who are interested primarily in completion suggestions, etc. For users who are interested in static type checking, I would strongly encourage them to not rely on this feature and instead be explicit with parameter annotations.

**Comment by erictraut** [comment]
I've implemented a first cut at this functionality. It will be in the next release of pyright and pylance. Here's the documentation: https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#parameter-type-inference.

**Comment by erictraut** [comment]
This is included in pyright 1.1.224, which I just published. It will also be included in the next release of pylance.

**Comment by Rizhiy** [comment]
@JelleZijlstra Technically this is not a false positive since the types differ, the default value is `int`, but you are passing in `float`.
If default was `1.0`, then it shouldn't complain.

Taking that into account, I realise that many people expect that empty type annotation is the same as `Any`. Therefore, I think this functionality should be decided by a flag with default being false.

**Comment by erictraut** [comment]
This functionality was added primarily for users of pylance who are not interested in static type checking and know little or nothing about type annotations. Hiding this functionality under a flag that is off by default would therefore not work because these users would never discover the feature and therefore wouldn't benefit from it. It needs to be on by default.

@JelleZijlstra, thanks for the datapoint. We'll continue to monitor and listen for additional feedback. One datapoint isn't enough for us to do anything at this point. If we receive significant negative feedback, my plan is to change the inference from `int` to `Unknown | int`. This would still provide completion suggestions for `int` without rejecting a `float` value from being passed.

**Comment by twoertwein** [comment]
> Taking that into account, I realise that many people expect that empty type annotation is the same as `Any`. Therefore, I think this functionality should be decided by a flag with default being false.

Having an option to disable this behvior would be useful. Pandas uses its own special object as default values to know when a user did not provid the keyword (None often has already a meaning), e.g., in [to_numpy](https://github.com/pandas-dev/pandas/blob/d2aa44f50f6ac4789d4e351e4e52a53a358da42e/pandas/core/arrays/base.py#L463)

**Comment by howsiyu** [comment]
This causes a lot of errors when the default argument is a number but the function also accepts numpy/jax array.

**Comment by stunlocked1** [comment]
One thing that would be nice is that it wouldn't scream at None when it is the default argument

**Comment by carlosgmartin** [comment]
I have the same problem as @JelleZijlstra, for a different set of types. I'm strongly -1 on this change.

There's no reason why a type checker should assume a default value captures the only possible type of an argument.

**Comment by Rizhiy** [comment]
> This issue contains 1 positive feedback (the OP) and 4 negative feedbacks for this change. Seems to me like the balance is against it. I suggest making this optional and false by default.

??? This argument makes no sense. There are no positive feedbacks on this issue, since current version is working as intended and people are just using it. Did you go to every other closed issue in this repo and provide positive feedback?

Making this behaviour optional will be an improvement, but I guess it is not high priority.

**Comment by carlosgmartin** [comment]
I've [requested](https://github.com/microsoft/pyright/issues/10705) an option to disable this.
