### ISSUE TITLE
Using reveal_type with expected_string and expected_type with mypy and pyright

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#3096]
With pandas, we use both mypy and pyright to do type checking.

I'd like to use the new feature that pyright has with `expected_string` and `expected_type` to do type checking, but that  isn't supported by `mypy` - it expects `reveal_type` to only have one argument. 

What's the best way to use the new pyright `reveal_type` feature so that `mypy` can still type check the code ?

**Comment by JelleZijlstra** [comment]
I'm working on getting the `assert_type()` feature into Python: https://mail.python.org/archives/list/typing-sig@python.org/thread/MITFQ6Z45RRMXY3HNM66IC3XXS3TA3JN/. Once that is done, I'll also add support to mypy.

Until that's done, I don't think there's a portable way to test types across both mypy and pyright. There are mypy-specific solutions such as https://pypi.org/project/pytest-mypy-plugins/.

**Comment by erictraut** [comment]
There is a proposal to add `assert_type` to `typings` in Python 3.11. This would also be back-ported to `typings_extensions`. It would provide the equivalent of the `expected_type` feature in pyright's current implementation of `reveal_type`.

**Comment by Dr-Irv** [comment]
So is there something we can do in the meantime until that's available?

**Comment by erictraut** [comment]
I can't think of anything that would work across type checkers. This is why Jelle proposed that we standardize `assert_type`.
