### ISSUE TITLE
Can't resolve import statement in if ... else ... branch properly

### ISSUE THREAD

**Issue by spindensity** [microsoft/pyright#311]
**Describe the bug**
Pyright can't resolve import statement in if ... else ... branch properly.

**Environment**
- OS: Win10 1903 64bit;
- VS Code: 1.39.2;
- Pyright: 1.0.81;
- Python: python 3.7.4 in conda environment.

**To Reproduce**
The following code is considered problematic as the image illustrating:

```python
if False:
    import cProfile as pickle
else:
    import pickle

obj: int = 42

with open("obj.txt", mode="wb") as f:
    pickle.dump(obj, f)

with open("obj.txt", mode="rb") as f:
    obj2: int = pickle.load(f)
    print(obj2)
```

![Snipaste_2019-10-27_15-43-28](https://user-images.githubusercontent.com/33576822/67631388-a2385e80-f8d0-11e9-808a-64e054dfb5e6.png)

The following code is considered correct:

```python
if True:
    import pickle
else:
    import cProfile as pickle

obj: int = 42

with open("obj.txt", mode="wb") as f:
    pickle.dump(obj, f)

with open("obj.txt", mode="rb") as f:
    obj2: int = pickle.load(f)
    print(obj2)

```

![Snipaste_2019-10-27_15-43-59](https://user-images.githubusercontent.com/33576822/67631394-a95f6c80-f8d0-11e9-8725-3547ad1d897c.png)

**Expected behavior**
The two code fragments should be both considered correct.

**Comment by erictraut** [comment]
Thanks for the bug report. This is now fixed in 1.0.82, which I just published. If you're still seeing problems, feel free to re-open.
