### ISSUE TITLE
TypeVar and TypeGuard interaction

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#3119]
**Describe the bug**
Normally with typevars and narrowing, the variable preserves information about typevar with *. Like,

```python
def f(x: T) -> T:
  if isinstance(x, int):
    return x # type here is int*

  return x

```
Is it expected behavior that typeguards don't preserve typevar relationship? An example would be,

```python
from typing_extensions import TypeGuard

def is_int(x: object) -> TypeGuard[int]
  return isinstance(x, int)

def f(x: T) -> T:
  if is_int(x):
    return x # type here is int not int* so an error is produced

  return x
```

I'm unsure if this is as designed or a bug. Are there any other narrowing rules that don't preserve *?
**VS Code extension or command-line**
pyright 1.1.225

**Comment by erictraut** [comment]
Yes, this is expected. The current `TypeGuard` mechanism described in PEP 647 does not (and cannot) combine knowledge of the input expression type with the narrowed output type outside of what it is told by the user-defined type guard function. 

I have proposed (and prototyped) a variant of `TypeGuard` called `StrictTypeGuard` that would do what you're looking for here. You can read more about it [here](https://github.com/python/typing/discussions/1013#discussioncomment-1966238). So far, I haven't gotten enough interest from the typing community to justify moving forward with a PEP.
