### ISSUE TITLE
providing a type hint for a callable class seems to be impossible

### ISSUE THREAD

**Issue by meshantz** [microsoft/pyright#3128]
**Describe the bug**

At the very least the error message shown here (see below) is wrong. I am unsure if this is actually a legal type hint, but the interpreter (python 3.10.0) allows it.

**To Reproduce**

Using the code below results in the following message:
```
Expression of type "Type[Blah]" cannot be assigned to return type "(...) -> str"
  Type "Type[Blah]" cannot be assigned to type "(...) -> str"
    Function return type "Blah" is incompatible with type "str"
      "Blah" is incompatible with "str"
```

But the denoted return type of `"(...) -> str"` is not what I specified.

**Expected behavior**

The denoted return type should be `"[(...) -> str]"`, which would not be a type mismatch.  
If you decide this is not a legal type hint, then the message should indicate that instead.

**Code**

```
def class_factory() -> Type[Callable[..., str]]:
    class Blah:
        def __call__(self) -> str:
            return "yeah"

    return Blah
```

**VS Code extension or command-line**

VS Code extension: Pylance v2022.2.4

**Additional Info**

Ideally I want to constrain the callable's return type without constraining the parameters required, so I thought `Type[Callable[..., str]]` would be appropriate.

I guess what I'm looking for here is applying Type to a Protocol, which may or may not be valid.

I'm aiming for structural typing, as opposed to the nominal typing that `Type[Blah]` would result in.

FWIW `mypy` passes with the given type hint.

**Comment by erictraut** [comment]
This is not a legal type annotation. You would need to define a [callback protocol](https://www.python.org/dev/peps/pep-0544/#callback-protocols).

**Comment by meshantz** [comment]
Thanks for the speedy reply and the link. I'm not sure I can make the callback protocol work for my use-case (due to constraints not mentioned here).

I respect the call that this is not legal, however I still see the message as being misleading and confusing. Can it not be adjusted as in my second suggestion above?

> f you decide this is not a legal type hint, then the message should indicate that instead.

**Comment by erictraut** [comment]
I don't mind adding additional special case logic to improve error messages if I think that an error is going to be encountered by multiple users, but this is really obscure.

**Comment by meshantz** [comment]
Fair enough. Thanks for your consideration.
