### ISSUE TITLE
Incompatible method override when using @staticmethod in subclass

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/pyright#3134]
```python
# pyright: strict

class Foo:
    def foo(self, x: int):
        pass

class Bar(Foo):
    @staticmethod
    def foo(x: int):  # error: Method "foo" overrides class "Foo" in an incompatible manner
        pass
```

As far as I can tell the method is not actually incompatible. To quote [the standard library documentation](https://docs.python.org/3/library/functions.html#staticmethod):

>A static method can be called either on the class (such as `C.f()`) or on an instance (such as `C().f()`).

**Comment by erictraut** [comment]
Pyright is correct here. The override is incompatible. You should not intermix instance methods and static methods. In many contexts the difference can be ignored, but in some it will cause a crash.

```python
b = Bar()

Foo.foo(b, 3) # OK
Bar.foo(b, 3)  # Crash
```
