### ISSUE TITLE
__init__.py should take priority over modules

### ISSUE THREAD

**Issue by patrick91** [microsoft/pyright#314]
**Describe the bug**

**To Reproduce**
I'm working on library called Strawberry and we re-export some functions from __init__.py so they can be used with `strawberry.type`, we also have module inside strawberry called type, which seems to be taking precendece. Not even sure we should be able to access it directly :)

```
import strawberry

@strawerry.type
class ABC:
	id: str
```

**Expected behavior**
Pyright should not understand that `type` is being exported in the __init__.py

**Screenshots or Code**

<img width="503" alt="image" src="https://user-images.githubusercontent.com/667029/67713604-6b447480-f9c6-11e9-955b-9f7be1e7762c.png">

**VS Code extension or command-line**
Latest VS Code extension

**Comment by erictraut** [comment]
Thanks for the bug report. I've repro'ed the problem, and I'm working on a solution.

**Comment by erictraut** [comment]
This will be fixed in the next published version of pyright.

**Comment by erictraut** [comment]
This is fixed in version 1.0.83, which I just published.
