### ISSUE TITLE
Legality of addition with list[tuple[primative]] and list[tuple[Literal of primative]] is order-dependent

### ISSUE THREAD

**Issue by thisisrandy** [microsoft/pyright#3149]
**Describe the bug**
When adding variables of types e.g. `list[tuple[int]]` and `list[tuple[Literal[0]]]`, legality is order-dependent. Specifically, if the literal type comes first, pyright complains e.g., 'Operator "+" not supported for types "list[tuple[Literal[0]]]" and "list[tuple[int]]'.

**To Reproduce**
```python
foo: list[tuple[int]] = []
# fine
foo + [(0,)]
# Operator "+" not supported for types "list[tuple[Literal[0]]]" and
# "list[tuple[int]]"
[(0,)] + foo
```

**Expected behavior**
I understand that this is a variance thing. The `Literal` type is a subtype of a given primative type, so adding a supertype is illegal, whereas adding a subtype is acceptable. That said, I'm filing this as a bug, because it seems at least superficially inconsistent with similar cases. Consider the following:

```python
def add_int(addend: int):
    """We can add ints to literals and vice-versa"""
    one = 1  # Literal[1]
    one + addend
    addend + one


def add_int_list(to_add: list[int]):
    """Lists of literal ints get casted to list[int]. If we explicitly call them
    list[Literal[...]], we can ellicit an error"""
    one = [0]  # list[int]
    one + to_add
    to_add + one
    one_casted: list[Literal[0]] = [0]
    # error
    one_casted + to_add
    # ok
    to_add + one_casted


def add_float_tuple_lists(to_add: list[tuple[float]]):
    """Floats apparently can't be literals, so they get a pass"""
    one = [(0.0,)]  # list[tuple[float]]
    one + to_add
    to_add + one
```

I can convince myself that a tuple's immutability means that it should have the most specific type possible. Certainly that behavior is useful for pattern matching. I don't see how it's useful to complain about adding lists of tuples together when one or more list contains literals and the former's type is more restrictive.

One more example with classes instead of primatives:

```python
class Foo:
    pass

class Bar(Foo):
    pass

# ok
[Foo()] + [Bar()]
# error
[Bar()] + [Foo()]
```

Even this seems wrong to me. Unless I'm trying to assign the result to a variable of type `list[Bar]`, why should `[Bar()] + [Foo()]` be an error?

**VS Code extension or command-line**
pylance: v2022.3.0
pyright: 1.1.226

**Comment by erictraut** [comment]
Yes, this is unfortunate but expected behavior. 

The apparent inconsistency is due to the fact that pyright uses bidirectional type inference for binary operators to infer the type of the RHS based on the LHS. It cannot do the same in reverse.

I could remove the bidirectional type inference for binary operators entirely, which would eliminate this apparent contradiction, but this would result in type errors in all of the cases above instead of only some of them. I don't think that's a good tradeoff.

**Comment by thisisrandy** [comment]
> I could remove the bidirectional type inference for binary operators entirely, which would eliminate this apparent contradiction, but this would result in type errors in all of the cases above instead of only some of them. I don't think that's a good tradeoff.

No argument there. For the record, I checked mypy 0.931 with default options, and it complains differently. Specifically,

```python
from typing import Literal

foo: list[tuple[int]] = []
# fine
foo + [(0,)]
# also fine!
[(0,)] + foo


def add_int_list(to_add: list[int]):
    one_casted: list[Literal[0]] = [0]
    # error
    one_casted + to_add
    # also error!
    to_add + one_casted
```

The result are otherwise the same as pyright's.
