### ISSUE TITLE
Cannot assign member "bar" for type "Foo"

### ISSUE THREAD

**Issue by zakissimo** [microsoft/pyright#3155]
**Describe the bug**
Pyright errors when code is correct

**To Reproduce**
See below

**Expected behavior**
No errors should be displayed

![image](https://user-images.githubusercontent.com/64891486/156925264-5c487e4e-e000-49a1-b94a-44fad81272bb.png)
![image](https://user-images.githubusercontent.com/64891486/156925153-feb74b99-ce7b-45cb-bf7a-4327457d4aba.png)

**VS Code extension or command-line**
![image](https://user-images.githubusercontent.com/64891486/156925194-2cc678c5-41b5-4e03-a63a-94939879e031.png)

**Additional context**
I see [here](https://github.com/microsoft/pyright/issues/1574) that the problem was fixed last year, so I don't really understand how I still have the same issue

**Comment by erictraut** [comment]
This is intended behavior. You have not provided a type annotation for the instance variable `bar`, so its type is inferred from all assignments within the class implementation. You have assigned only one value to it, `None`, so its type is inferred to be `None`. If your intent is for it to be a different type, you should provide a type declaration, like this:

`self.bar: Optional[str] = None`

or if you're using Python 3.10,

`self.bar: str | None = None`

For more information about type declarations and type inference, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).

**Comment by erictraut** [comment]
For future issues, please post code snippets rather than (or in addition to) screen shots.
