### ISSUE TITLE
Resolution of type[T] using TypeVar with parent & child class as constraints is order-dependent

### ISSUE THREAD

**Issue by RocketRace** [microsoft/pyright#3159]
**Describe the bug**
When a `TypeVar` constrained by two related types, e.g. `class A` and `class B(A)`, is used inside `type[T]`, the type that `T` resolves to depends on the order in which the constraints are provided. Specifically, if `T` could resolve to more than one of the constrained types, the leftmost one is chosen.

As far as I can tell, this only occurs with `type[T]`, and plain `T` resolves as expected.

**To Reproduce**
Given a function `type[T] -> type[T]` with a `TypeVar("T", A, B)` as described, provide a value of type `type[B]` as its parameter. The return type is inferred as `type[A]`. If the order of the constraints is reversed, it is inferred as `type[B]`.

**Expected behavior**
The most specific type satisfying the arguments and constraints should be picked regardless of order, in this case `type[B]`.

**Screenshots or Code**
Here is a demonstration of the problem:
```python
class A:...
class B(A):...

T = TypeVar("T", A, B)
U = TypeVar("U", B, A)

def foo(t: type[T]) -> type[T]: return t
def bar(u: type[U]) -> type[U]: return u

FooB = foo(B)
BarB = bar(B)

reveal_type(FooB) # Type of "FooB" is "Type[A]"
reveal_type(BarB) # Type of "BarB" is "Type[B]"
```

**VS Code extension or command-line**
I have tried both the extension (`Pylance  v2022.3.0`) and the command-line (`pyright 1.1.227`).

**Additional context**
This issue can be mitigated in code by arranging the most specific constraints first.

**Comment by erictraut** [comment]
This is fixed in pyright 1.1.228, which I just published. It will also be included in the next release of pylance.
