### ISSUE TITLE
Adding lists of different types gives type error

### ISSUE THREAD

**Issue by smackesey** [microsoft/pyright#3166]
This code gives `Operator "+" not supported for types "list[int]" and "list[str]"`:

```python
x = [1]
y = ['a']
z = x + y
```

**Expected behavior**
There should be no error, and `z` should have inferred type `List[Union[int, str]]`

**VS Code extension or command-line**
pyright language server 1.1.228

**Comment by erictraut** [comment]
The current behavior is correct based on the `list` class definition in the typeshed stub `builtins.pyi`.

```
    def __add__(self, __x: list[_T]) -> list[_T]: ...
```
If you think this is incorrect, please file a bug (or a PR) in the typeshed repo. Pyright regularly picks up new versions of the typeshed stubs.

**Comment by JelleZijlstra** [comment]
This is a longstanding typeshed issue, python/typeshed#2383. It has proven hard to fix.
