### ISSUE TITLE
Support Unpack across Non-Variadic Generic Class

### ISSUE THREAD

**Issue by MarioIshac** [microsoft/pyright#3187]
In PyRight `1.1.299`, given `main.py`:

```
from typing import Generic, TypeVar
from typing_extensions import TypeVarTuple, Unpack

P = TypeVarTuple("P")
T = TypeVar("T")

class Body(Generic[T]):
    def __init__(self, x: T):
        self.x = x

class VariadicBody(Generic[Unpack[P]]):
    def __init__(self, *xs: Unpack[P]):
        self.xs = xs

class Call1(Generic[Unpack[P]]):
    def __init__(self, args: VariadicBody[Unpack[P]]) -> None:
        self.args = args

class Call2(Generic[Unpack[P]]):
    def __init__(self, *args: Unpack[Body[P]]) -> None:
        self.args = args

Call1[int, str](VariadicBody(1, "abc"))
Call2[int, str](Body(1), Body("abc"))
```

the resulting errors are:

```
main.py:20:43 - error: TypeVarTuple not allowed in this context
main.py:20:31 - error: Expected TypeVarTuple or Tuple as type argument for Unpack (reportGeneralTypeIssues)
```

`Call1` type checks successfully, but not `Call2`. The proposed feature is that specifying `[X1, X2]` for `Call2` should turn into it accepting `Body[X1]` for its first parameter and `Body[X2]` for its second parameter. While the `TypeVarTuple` PEP notes that unpacking `P` into another class taking `P` should work (as it did in `Call1`), it makes no comment on unpacking `P` across a class taking `T` (as I tried in `Call2`). So this feature would be on a bonus separate from what the PEP requires. 

If this feature request is accepted, I don't have an opinion on whether the syntax is `Unpack[Body[P]]` or `Body[Unpack[P]]` or something else.

**Comment by erictraut** [comment]
Pyright is correct here. You cannot use other classes in an `Unpack` annotation.

**Comment by MarioIshac** [comment]
I understand that, what Pyright currently does is right per the PEP. That's why I tagged as enhancement request instead of bug. It's of course alright if you consider this feature out of scope / not worthy of continued discussion, but don't want to give off the impression that I considered this a bug.

**Comment by erictraut** [comment]
Thanks for the clarification. Yeah, I consider this out of scope. If you want to propose extensions to the PEP, you could start a discussion in the [python/typing](https://github.com/python/typing/discussions) discussion section. This would need to go through the normal PEP ratification process before I would consider adding support for it in pyright.
