### ISSUE TITLE
Is pyright complaining rightfully here?

### ISSUE THREAD

**Issue by SHxKM** [microsoft/pyright#320]
**Describe the bug**
Not sure this is a bug but I couldn't find documentation for my specific issue at hand. To be sure: the *code* itself works and runs fine.

**To Reproduce**
I'm using a slightly modified version of [Paddle's webhook verification with Python](https://developer.paddle.com/webhook-reference/verifying-webhooks) code.

Given these lines:

```python
def verify_signature(request):
   # ...
    try:
        key = RSA.importKey(public_key_der)
    except ValueError:
        raise RSAPublicKeyInvalidException
    digest = SHA1.new()
    digest.update(serialized_data)
    verifier = PKCS1_v1_5.new(key)
    signature = base64.b64decode(signature)
    if verifier.verify(digest, signature):
        return True

    raise SignatureInvalidException
```

I'm getting `digest` highlighted with the following pyright error message:

> Argument of type 'SHA1Hash' cannot be assigned to parameter 'msg_hash' of type 
>
> 'ModuleType'  'SHA1Hash' is incompatible with 'ModuleType'pyright

**Expected behavior**

**Screenshots or Code**

<img width="883" alt="Screen Shot 2019-11-03 at 12 29 49" src="https://user-images.githubusercontent.com/6573474/68089322-aebf3880-fe35-11e9-9423-226906416361.png">

**Additional context**
Here is the relevant docstring for .`verify()` expecting a `msg_hash`:

```python
"""Check if the  PKCS#1 v1.5 signature over a message is valid.

        :parameter msg_hash:
            The hash that was carried out over the message. This is an object
            belonging to the :mod:`Crypto.Hash` module.
        :type parameter: hash object
"""
```
Relevant modules:

[Crypto.Signature -> pkcs1_15](https://pycryptodome.readthedocs.io/en/latest/src/signature/pkcs1_v1_5.html)

**Comment by erictraut** [comment]
I can't repro the problem because I don't know how you're importing these symbols. Can you paste the import statements that you're using to import RSA, SHA1, and PKS1_v1_5?

**Comment by SHxKM** [comment]
Thanks for the quick response @erictraut. Here it is: 

```python
from Crypto.PublicKey import RSA
try:
	from Crypto.Hash import SHA1
except ImportError:
	# Maybe it's called SHA
	from Crypto.Hash import SHA as SHA1
try:
	from Crypto.Signature import PKCS1_v1_5
except ImportError:
	# Maybe it's called pkcs1_15
	from Crypto.Signature import pkcs1_15 as PKCS1_v1_5
import hashlib

# PHPSerialize can be found at https://pypi.python.org/pypi/phpserialize
import phpserialize

```

This is how the folks at Paddle are doing it anyway. They’re a payment processor, so I hope I can trust their methods.

**Comment by erictraut** [comment]
It's difficult for a static analyzer like pyright to deal with conditional imports — especially when they're in try/except blocks because the runtime behavior can't be predicted statically. In such cases, pyright will generally treat the import as an "unknown" type, which effectively disables all type checks associated with those symbols.

I'm confused why you're seeing the error message above. I haven't been able to repro what you're reporting. I would expect that `verifier` would be an "unknown" type, which means that `verifier.verify` would also be "unknown", which means that the call arguments would not be analyzed. If you hover over `verifier` and `verify`, what type does pyright display? For me, it reports the following:
`(variable) verifier: Unknown`
`verify: Unknown`

It would also be useful to understand what types you're seeing for the `digest` symbol. Here's what I see:
`(variable) digest: Unknown`

**Comment by SHxKM** [comment]
pyright reports 

- `digest` as `digest: SHA1Hash`
- `verifier` as `verifier: PKCS115_SigScheme`

`verify` is just a function.

I think I can probably get rid of those dynamic imports since Paddle's guide probably wants their script to work regardless of which Python install one is running and whether there are already conflicting `Crypto` packages in it.

**Comment by erictraut** [comment]
OK, thanks. This appears to be a bug in the type stub files that ship with the Crypto library.

The type signature in the type stub file pkcs1_15.pyi defines the verify method as follows:
`def verify(self, msg_hash: ModuleType, signature: bytes) -> None: ...`

That tells pyright that the `msg_hash` parameter should be a module, which doesn't make sense. It also doesn't match the documentation for the verify method, which says that msg_hash should be a hash object, not a module.

I recommend that you report the bug to the library author. Most python library authors have limited experience with type stubs, and errors of this sort are not uncommon. Most libraries don't even include type stubs, so this library author is already one step ahead of most.

Here are a few workarounds in the meantime:
1. You can create local type stub libraries for this library. Pyright always uses local type stubs before looking in the third-party library. This would allow you to correct the bug locally.
2. Use a `# type: ignore` comment on that line to silence that error.
3. Apply an "Any" cast to digest when you pass it to the `verify` method (along with a comment indicating why the cast is currently required): `cast(Any, digest)`

**Comment by SHxKM** [comment]
@erictraut thanks again Eric.
