### ISSUE TITLE
Incorrect type of parameterized TypeAlias

### ISSUE THREAD

**Issue by bijij** [microsoft/pyright#3210]
**Describe the bug**
Not sure how to explain the bug, this image illustrates it pretty well though:
![image](https://user-images.githubusercontent.com/8677174/158789592-dcb042c3-49aa-41e5-a873-47074c942544.png)

**To Reproduce**
- Clone the [sample repository](https://github.com/bijij/pyright-issue)
- Run `pyright foo`

**Expected behavior**
the revealed type should instead be `(A, BT@Something, C) | (BT@Something, C)`

**Screenshots or Code**
Due to the seemingly required directory structure, have created a [sample repository](https://github.com/bijij/pyright-issue)

**VS Code extension or command-line**
pyright v1.1.230

**Comment by erictraut** [comment]
Thanks, I'm able to repro the problem, and I'll take a closer look.

**Comment by erictraut** [comment]
This will be fixed in the next release.

**Comment by erictraut** [comment]
This is fixed in pyright 1.1.231, which I just published. It will also be included in the next release of pylance.
