### ISSUE TITLE
Per-rule diagnostic controls

### ISSUE THREAD

**Issue by micimize** [microsoft/pyright#3221]
Similar to #2026 – there are many pyright issues that I'd like to be able to toggle at the editor level, so as to avoid having to litter type ignore comments everywhere.

It would be nice to have a fine-grained list of specific rules we could toggle, like pylint does.

**Comment by erictraut** [comment]
We don't have plans to split out every single error message. That would be too fine-grained and extremely cumbersome to manage (not to mention maintain). We try to provide intelligent groupings based on common use cases. 

If there are specific diagnostics that you'd like us to consider splitting out into separate diagnostic rules, please file a separate issue for each along with a justification for why you think it should be separate.

**Comment by erictraut** [comment]
Also, if you find that you need to add a bunch of `# type: ignore` comments in your code, then that's indicative of another problem — perhaps bugs in your code that you are choosing to ignore, problems with type information in libraries, or bugs in pyright that are resulting in false positives? If it's the latter, we'd appreciate receiving bug reports so we can fix those issues.

In general, you should rarely need to use a `# type: ignore` comment in typed Python code. My team has a 250K+ line Python code base, and it contains no `# type: ignore` comments.

**Comment by micimize** [comment]
#3220 is an example of a rule I would like to turn off independently due to conflicting conventions. However, the majority I've seen were instances where I'd say our types were slightly lacking:
1. partially unknown types such as under-specified generics
2. dynamic construction of a generic type argument bound by a protocol (assumed to have a zero-arg constructor) 

All of these fall under general type issues, so I ended up just disabling pyright. Eventually I'd like to go back and improve the typing but it isn't always a priority, and I think given the real state of python's ecosystem it is important for type checking tools to be flexible.

Actually now that I think about it, having a list of `ignore` patterns would serve pretty much the same purpose and require no refactoring, just an optional output filter. 

I will say that I think a fine-grained error taxonomies may be less burdensome to maintain than they seem, and seems to have become the de-facto standard approach for static analysis dev tools. But the option to ignore just straight up message substrings would be just fine for users like me who want fine-grained customization and/or gradual adoption.
