### ISSUE TITLE
Callable protocol attributes cannot be overriden by methods.

### ISSUE THREAD

**Issue by thesadru** [microsoft/pyright#3224]
When overwriting a protocol attribute of a parent it may only be overridden with another attribute, not a method. 

```py
import typing


class Callback(typing.Protocol):
    def __call__(self, value: int) -> str:
        ...


class Parent:
    callback: Callback


class Child(Parent):
    def callback(self, value: int) -> str: # "callback" overrides symbol of same name in class "Parent"
        ...

```
```
main.py
  main.py:14:5 - error: "callback" overrides symbol of same name in class "Parent"
    Type "(self: Self@Child, value: int) -> str" cannot be assigned to type "(value: int) -> str"
      Parameter name mismatch: "value" versus "self"
      Parameter 1: type "int" cannot be assigned to type "Self@Child"
        "int" is incompatible with "Child"
      Keyword parameter "value" is missing in destination (reportIncompatibleVariableOverride)
```

**Comment by erictraut** [comment]
This is "as designed" behavior. You are attempting to override an instance variable with a method.

The standard approach here is to mark `Parent` as an abstract base class (ABC) and define an abstract_method called `callback`.

```python
# pyright: strict

from abc import ABC, abstractmethod


class Parent(ABC):
    @abstractmethod
    def callback(self, value: int) -> str:
        raise NotImplemented()

class Child(Parent):
    def callback(self, value: int) -> str:
        ...
```

The `reportIncompatibleVariableOverride` rule is a strict-mode check, and it's intentionally picky about what it means about "compatible override". If you don't like the way it works, you can leave the rule disabled, disable it on a per-file basis, or use a `# type: ignore` or `# pyright: ignore[reportIncompatibleVariableOverride]` on that particular line.
