### ISSUE TITLE
`TypedDict` is incompatible with `dict`

### ISSUE THREAD

**Issue by relsunkaev** [microsoft/pyright#3226]
**Describe the bug**
When using `TypedDict` that should be compatible with `dict[str, <SomeType>]` annotation or even a bare `dict`, pyright deems the two incompatible.

**To Reproduce**
```python
from typing import TypedDict

class DictStrInt(TypedDict):
    some_str: int

def function(_: dict[str, int]):
    ...

x: DictStrInt = {"some_str": 1}

function(x)
```
will produce the following error
```
/Users/.../test.py
  /Users/.../test.py:11:10 - error: Argument of type "DictStrInt" cannot be assigned to parameter "_" of type "dict[str, int]" in function "function"
    "DictStrInt" is incompatible with "dict[str, int]" (reportGeneralTypeIssues)
```

**Expected behavior**
No errors.

**System info**
Python: 3.9
Pyright (CLI): 1.1.231

**Comment by erictraut** [comment]
This is the correct behavior. For details, refer to [PEP 589](https://peps.python.org/pep-0589/).
