### ISSUE TITLE
Override method with kwargs var is marked as incompatible override

### ISSUE THREAD

**Issue by bryanforbes** [microsoft/pyright#3230]
**Describe the bug**
Given the following code with `reportIncompatibleMethodOverride = "error"`:

```python
from __future__ import annotations

from typing import Any


class Base:
    def edit(self, *, arg_one: int | None = None) -> None:
        ...


class Other(Base):
    def edit(self, *, arg_two: int | None = None, **kwargs: Any) -> None:
        ...
```

Line 12 is marked as an error:

```
error: Method "edit" overrides class "Base" in an incompatible manner
    Parameter "arg_one" is missing in override
```

**Expected behavior**
No error is generated

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool?
Command line

Which version?
1.1.231

**Comment by erictraut** [comment]
This is intended behavior. If you override a method, you should include any keyword args in the override signature.
