### ISSUE TITLE
type[T] is incorrectly assumed to never be an instance of type[T]

### ISSUE THREAD

**Issue by RocketRace** [microsoft/pyright#3234]
**Describe the bug**
Pyright fails to recognize that `type[T]` may be an instance of `type[T]`, specifically when both arguments are `type`. This is to my knowledge the only edge case for which this holds, and is a result of python's type system.

While the assumption pyright makes is not correct, it's useful when reasoning with code. I'm not sure whether fixing the incorrectness could impact this ability.

**To Reproduce**
```python
from typing import TypeVar

T = TypeVar("T")
def foo(inst: type[T], cls: type[T]):
    if not isinstance(inst, cls):
        return
    reveal_type(inst) # Type of "inst" is "Never"

foo(type, type)
```

**Expected behavior**
The type of `inst` is inferred to be `type[type]`. 

**VS Code extension or command-line**

`pyright 1.1.231`, `v2022.3.2`

**Comment by erictraut** [comment]
This is an extreme edge case. "Fixing" it would result in less-ideal behavior for more common cases, so it's not a good idea to address this. There are obvious workarounds if your intent is to handle this particular edge case in your code.

**Comment by RocketRace** [comment]
Thank you, that's very true. Does the following also fall under the same rationale? It seems like stacked `type[]`s are erased as a part of it.
```python
from typing import TypeVar

T = TypeVar("T")
def foo(inst: T) -> type[T]:
    return type(inst)

reveal_type(foo(int)) # Type of "foo(int)" is "Type[int]"
```

**Comment by erictraut** [comment]
Yes, same rationale. Internally, pyright maintains a flag that indicates whether a type is "instantiable" or an "instance". Since this is a binary state, there's no way to represent "an instantiable instantiable". In practice, this doesn't come up in real-world use cases.
