### ISSUE TITLE
Possibly unbound variable in for loop, when using next to prevent unbound access

### ISSUE THREAD

**Issue by zdzolton** [microsoft/pyright#3240]
**Describe the bug**
Pyright tells me that a variable assigned within a `for` loop might possible be unbound after catching an error and using `next` to prevent accessing it.

**To Reproduce**
Run Pyright on the code below. It will result in this error:

```
Pyright: "ok" is possibly unbound
```

**Expected behavior**
I would expect that Pyright could determine that no code paths would access the variable `ok` in the `for` loop without first assigning to it.

**Screenshots or Code**
Here's my nearly minimal repro:
```python
def foo(n: int) -> int:
    if n == 3:
        raise RuntimeError("We don't like 3!")
    return n * 2


nums = range(0, 5)

for i in nums:
    try:
        ok = foo(i)
    except RuntimeError:
        print(f'Skipping {i}')
        next
    print(ok) # Pyright reports the problem here
```

**VS Code extension or command-line**
I'm running Pyright v1.1.232 from Neovim, as installed by the https://github.com/williamboman/nvim-lsp-installer project.

**Additional context**
My apologies in advance if this is a known issue or if solving this is a non-goal for the project. I did a cursory search for a similar issue, but failed to find any.

I appreciate any valuable attention you may spend here, and thank you all for making Pyright!

**Comment by erictraut** [comment]
It looks like you're expecting that `next` is a keyword of some sort, but it's simply a function. It will not prevent `ok` from being unbound. Perhaps you meant `continue` instead?

**Comment by erictraut** [comment]
I've updated the `reportUnusedExpression` check so it reports the suspicious use of `next` in your sample. This will be included in the next release.

**Comment by zdzolton** [comment]
Wow! You're totally right. That's what I get for changing between programming languages... 😥 

Thanks you, and my apologies!
