### ISSUE TITLE
Type inference in inherited method

### ISSUE THREAD

**Issue by amotzop** [microsoft/pyright#3247]
I think this is a bug, but maybe that's how type inference should work, I'm not sure.

**Describe the bug**
When a subclass overrides a method of its parent and changes its type annotations, the new annotations aren't used correctly to infer the types of members of the subclass.

**To Reproduce**
Run pyright on the code below. The revealed type will be `None`.

**Expected behavior**
The revealed type should be `int` (if we define the `__init__` function inside `Derived` instead of inheriting it, this is the behavior we get).

**Screenshots or Code**
```python
class Base:
    def __init__(self):
        self.member = self.func()

    def func(self):
        ...

class Derived(Base):
    def func(self) -> int:
        return 1

reveal_type(Derived().member)
```

**VS Code extension or command-line**
This happens both in VS Code (using pylance version 2022.3.2) and in the command-line tool (version 1.1.231)

**Comment by erictraut** [comment]
The current behavior is correct & intended. For the most part, classes are analyzed independently of each other. Inheritance is taken into consideration for subclasses, but not in reverse. After all, base classes are not supposed to know about child classes that derive from them. So if you annotate a symbol type in a base class, subclasses will inherit that type declaration, but the opposite is not true.

What you are suggesting would require that every method in the base class be reanalyzed in the context of every subclass that derives from the class.
