### ISSUE TITLE
cannot be assigned to declared type "T@func"

### ISSUE THREAD

**Issue by dvreed77** [microsoft/pyright#3267]
**Describe the bug**
I am getting unexpected behaviour using generics. When trying to assign a type that is within the bounds of the generic variable, I get the error:

```
Type "A" cannot be assigned to type "T@func"
```

**To Reproduce**
```python
from typing import TypeVar, Union, List


class A:
    def __init__(self, arg: str) -> None:
        self.arg = arg


class B:
    def __init__(self, arg: int) -> None:
        self.arg = arg


T = TypeVar("T", A, B)


def getA() -> A:
    return A("a")


def getB() -> B:
    return B(1)


def func(arg: T) -> T:
    out: T
    if isinstance(arg, A):
        out = getA()
    elif isinstance(arg, B):
        out = getB()

    return out


print(func(A("a")))
```

**Expected behavior**
No error message

**Screenshots or Code**
See above

**VS Code extension or command-line**
I am getting this error using pylance and also using the pyright CLI

**Comment by erictraut** [comment]
This is a known limitation of the way that pyright handles constrained type variables. The `isinstance(arg, A)` check narrows `arg` to the type `A*` which means that it's `A` when `T` is `A`. But the expression `getA()` has no relation to `arg`. If the return type is based on the narrowed `arg` type, it would work as expected.

```python
def func(arg: T) -> T:
    out: T
    if isinstance(arg, A):
        out = type(arg)("a")
    elif isinstance(arg, B):
        out = type(arg)(1)

    return out
```

I've looked into various ways to make the code in your sample type check without errors, but all approaches so far have proven to be computationally very expensive — to the extent that it would have a big impact on type analysis in all code. I'll think about this a bit more, but the answer is likely to be "this is a known and expected limitation that you need to accommodate in your code".

**Comment by dvreed77** [comment]
Thanks for taking the time to look into this

**Comment by erictraut** [comment]
I've already added a workaround that works specifically for return statements. So the following type checks without issues:
```python
def func(arg: T) -> T:
    if isinstance(arg, A):
        return getA()
    elif isinstance(arg, B):
        return getB()
```

I think that's the best I'm going to be able to do without adding significant overhead to the type analysis engine. I'm going to mark this as "as designed" and close it. Hopefully one of the above workarounds works out for you. 

Another (less satisfying) solution is to use an explicit cast:
```python
def func(arg: T) -> T:
    out: T
    if isinstance(arg, A):
        out = cast(T, getA())
    elif isinstance(arg, B):
        out = cast(T, getB())

    return out
```
