### ISSUE TITLE
Can't turn off pyright for JAX

### ISSUE THREAD

**Issue by danjenson** [microsoft/pyright#3277]
**Describe the bug**
It appears as though JAX is untyped, because I get a lot of 'None' returned from JAX functions. Also, with this pyrightconfig, it doesn't ignore them:
```json
{
  "venvPath": "/home/danj/.pyenv/versions/",
  "venv": "3.9.9",
  "ignore": [
    "/home/danj/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/*.py",
    "/home/danj/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jaxlib/*.py"
  ]
}
```

**To Reproduce**
Write code using any jax function.

**Expected behavior**
Either (1) it does not think all functions return None, or (2) it resepcts the ignore in the pyrightconfig.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/4793438/160983692-ff385fbe-5051-4fe8-907c-3fa9cd3009b7.png)

**VS Code extension or command-line**
pyright 1.1.234, neovim 0.6.1.

**Comment by erictraut** [comment]
The "ignore" section of the pyrightconfig.json config file is meant for files within your project, not for library files installed in your site-packages file. Pyright will auto-exclude source files from your active Python environment. So I recommend that you delete the "ignore" section.

Could you provide a self-contained minimal example of the problem you're seeing? It's difficult to diagnose problems from partial screen shots of code.

It would also be useful to know what version of the jax library you have installed.

Do you have any other pyright settings specified through the LSP?

If jax isn't a "py.typed" library and you have no type stubs installed for it, pyright will assume by default that all symbols exported from the library are "Unknown". If you enable "useLibraryCodeForTypes", it will attempt to infer types from the library source code where possible, but inferred types can be inaccurate.

**Comment by danjenson** [comment]
Here is a code example:

```python
import jax.numpy as jnp
import jax

a = jnp.mean(jnp.array([1, 2, 3])) + jnp.mean(jnp.array([1, 2, 3]))
```
This shows the error `Operator "+" not supported for types "None" and "None"`.

I'm using python 3.9.9 and jax 0.3.4.

**Comment by erictraut** [comment]
Thanks for the additional details. As I anticipated, this library isn't "py.typed", and it doesn't contain any type annotations. You have enabled "useLibraryCodeForTypes", so pyright will attempt to do its best to infer return types. But in this case, the library is using complex decorators that obscure the correct type of the functions. We generally don't recommend using "useLibraryCodeForTypes" if you enable static type checking; it was added primarily for pylance users who want reasonably-good completion suggestions but don't care about static type checking.

Your options are:
1. Disable "useLibraryCodeForTypes".
2. Find or create type stubs for jax that provide proper type declarations for the classes, functions or methods that you use in your code. You can use pyright's stub generation code to create a "first draft" of these stubs, but significant manual work will be needed to clean them up. 
3. Work with the maintainers of jax to add inlined type information within the library's code and publish it as a "py.typed" library. This is increasingly the route that library authors are going, at the urging of their users. We have prepared [this guidance](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md) for library authors who want to make this investment.

**Comment by erictraut** [comment]
One other option...

If you want to leave on "useLibraryCodeForTypes" for other libraries but effectively silence all errors for jax, you could create a minimal jax type stub that effectively makes all symbols into `Any`. To do this, create a file `typings/jax/__init__.pyi` in your project and add the following line:

```python
def __getattr__(name: str) -> Any: ...
```

**Comment by danjenson** [comment]
Thank you, the last one worked.
