### ISSUE TITLE
Infer missing return type based on current class

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#3281]
**Is your feature request related to a problem? Please describe.**
```py
from __future__ import annotations

class AB:
    def foo(self) -> int | str:
        ...

    def bar(self):
        return self.foo()

class A(AB):
    def foo(self) -> int:
        ...

reveal_type(A().bar())  # infers int | str, but it could be narrowed to just int
```
This would be useful for code bases that are still in the process of adding annotations.

**Describe the solution you'd like**
Pyright uses `A.foo` to infer the type of `A.bar` (but still uses `AB.foo` to infer the type of `AB.bar`)

**Comment by erictraut** [comment]
The current behavior is correct and intended. The inferred type of `bar` is `int | str` based on analysis of `A`. Inference of return types are done within the context of the base class. They are not re-analyzed for every base class. That would be extremely expensive and impractical.
