### ISSUE TITLE
Read-only descriptors are not compatible with read-only properties in protocols

### ISSUE THREAD

**Issue by bryanforbes** [microsoft/pyright#3287]
**Describe the bug**
Given the following code:

```python
from __future__ import annotations

from typing import Any, Protocol, TypeVar, cast, overload
from typing_extensions import Self


class Item(Protocol):
    @property
    def command(self) -> str:
        ...


def process_item(item: Item) -> None:
    ...


_DV_co = TypeVar('_DV_co', covariant=True)


class Descriptor(Protocol[_DV_co]):
    @overload
    def __get__(self, instance: None, owner: Any) -> Self:
        ...

    @overload
    def __get__(self, instance: object, owner: Any) -> _DV_co:
        ...


class Record:
    command: Descriptor[str]


class Thing:
    command: str


process_item(Record())
process_item(Thing())
```

An error is generated at line 38:

```
error: Argument of type "Record" cannot be assigned to parameter "item" of type "Item" in function "process_item"
    "Record" is incompatible with protocol "Item"
      "command" is an incompatible type
        "Descriptor[str]" is incompatible with "str" (reportGeneralTypeIssues)
```

**Expected behavior**
No error should be generated. Since the `Record` object has a descriptor that provides a read-only interface to `command` that returns the same type as the `Item` protocol is expecting, this should pass.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool?
Command line

Which version?
1.1.234

**Comment by erictraut** [comment]
I think pyright is correct here. A `str` is not the same as a descriptor object that returns a `str`. They are not type compatible. Mypy also emits the same error.

**Comment by Rapptz** [comment]
According to [PEP-544](https://peps.python.org/pep-0544/#using-protocols-in-python-2-7-3-5) it says property and abstractproperty should be equivalent to variable annotation for backwards compatibility reasons. Wouldn't this mean the behaviour on both mypy and pyright deviate from the PEP's intentions?

**Comment by erictraut** [comment]
I think it was a mistake for PEP 544 to include this exception because attributes and properties are not semantically the same, but I begrudgingly added support for it specifically for a `property` in a protocol class. However, I did so only as special cases for `property` not for general descriptors because the PEP says nothing about the latter.

**Comment by bryanforbes** [comment]
I've been thinking about this over the weekend and it seems that in order to write a function that only needs `obj.property` lookup, I would need multiple protocols:

```python
_DV_co = TypeVar('_DV_co', covariant=True)


class Descriptor(Protocol[_DV_co]):
    @overload
    def __get__(self, instance: None, owner: Any) -> Self:
        ...

    @overload
    def __get__(self, instance: object, owner: Any) -> _DV_co:
        ...


class DescriptorItem(Protocol):
    command: Descriptor[str]


class PropertyItem(Protocol):
    @property
    def command(self) -> str:
        ...


def process_item(item: DescriptorRecord | PropertyRecord) -> None:
    ...
```

Is there a better way to do this currently?

**Comment by bryanforbes** [comment]
> BTW, `DescriptorItem` should declare command as a `ClassVar`. Descriptors don't work when they're stored as instance variables.

Thanks! I had forgotten that part.

> It would be cleaner if you supported one or the other and not both.

I'm not sure why I should support one or the other and not both for the following (admittedly arbitrary example) API:

```python
class WritableItem(Protocol):
    title: str

class ReadOnlyItem(Protocol):
    @property
    def title(self) -> str: ...

class DescriptorItem(Protocol):
    title: ClassVar[Descriptor[str]]


# SQLAlchemy record
def ItemRecord:
    title: ClassVar[Column[str]]  # this is equal to `ClassVar[Descriptor[str]]`

# Cached data for autocomplete lookup
def ItemObject:
    _data: dict[str, str]

    def __init__(self, data: dict[str, str]) -> None:
        self._data = data

    @property
    def title(self) -> str:
        return self._data['title']

async def send_item_interaction(interaction: discord.Interaction, item: ???, text: str) -> None:
    embed = discord.Embed(title=item.command, description=text)
    await interaction.response.send_message(embed=embed)
```

For this API, I only need `item.title` and don't need `item.title = 'asdf'`. If I use `item: WritableItem`, I won't be able to pass `ItemRecord` or `ItemObject` since it is expecting a writable title property. If I use `item: ReadOnlyItem`, I won't be able to pass `ItemRecord`, even though I can do `item.title`. If I use `item: DescriptorItem`, I won't be able to pass `ItemObject` even though I can also do `item.title`.

Hopefully this clears up what I'm trying to accomplish.

**Comment by erictraut** [comment]
> I'm not sure why I should support one or the other and not both

Because providing multiple ways to do the same thing in an interface contract is often undesirable.
