### ISSUE TITLE
Ignore deleted variables when verifying types 

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#3295]
**Is your feature request related to a problem? Please describe.**
Explicitly deleted variables could be ignored from `--verifytypes` (or probably easier: authors should prefix variables with `"_"`).

**Describe the solution you'd like**

From pandas `__init__.py`
```py
# Let users know if they're missing any of our hard dependencies
hard_dependencies = ("numpy", "pytz", "dateutil")
missing_dependencies = []

for dependency in hard_dependencies:
    try:
        __import__(dependency)
    except ImportError as e:
        missing_dependencies.append(f"{dependency}: {e}")

if missing_dependencies:
    raise ImportError(
        "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
    )
del hard_dependencies, dependency, missing_dependencies
```

**Comment by erictraut** [comment]
Yes, the correct answer here is for the variables to be named such they are considered private (i.e. starting with `_`).
