### ISSUE TITLE
pyright-exe does not include typeshed_fallback directory

### ISSUE THREAD

**Issue by ttbilgin** [microsoft/pyright#3296]
I am creating a pyright-exe using pkg application. Here is my procedure:

npm i
cd /packages/pyright-internal
npm i
npm run build
cd /packages/pyright
npm i
npm run build
npm i -g pkg
cd /packages/pyright
pkg .

Until pyright 1.1.155 the /packages/pyright-internal/typeshed-fallback  folder is also embedded within exe file. However 1.1.2XX versions to not embed that folder and requires the typeshed folder using --typeshed-path parameter. 
Why typeshed folder not embedded in the exe file? How can I embed typeshed folder within the exe so that pyright.exe will yield just single exe file?

**Comment by erictraut** [comment]
The current code structure and build scripts are intended to build the supported variants of pyright and pylance. If you want to build it in other ways, you'll need to fork the project and modify it accordingly. I'm not familiar with the "pkg" app, so I'm not in a good position to give you advice here.
