### ISSUE TITLE
Keyword parameter is missing in source

### ISSUE THREAD

**Issue by dbrattli** [microsoft/pyright#3299]
**Describe the bug**

Since version 1.1.232 there seems to be a change in behavior for overloaded methods with keyword parameters that may have introduced a regression.

**To Reproduce**

Overloads with keyword argument names using double underscore is not ignored if prefixed with an argument that do not have such underscores. Please see provided minimal rero:

**Screenshots or Code**
```python
from typing import Any, Callable, TypeVar, overload

_A = TypeVar("_A")
_B = TypeVar("_B")

@overload
def pipe(value: _A) -> _A:
    ...

@overload
def pipe(value: _A, __fn1: Callable[[_A], _B]) -> _B:
    ...

def pipe(value: Any, *args: Callable[[Any], Any]) -> Any:
    return None
```
This gives error: `Keyword parameter "__fn1" is missing in source`:

```
Overloaded implementation is not consistent with signature of overload 2
  Type "(value: Any, *args: (Any) -> Any) -> Any" cannot be assigned to type "(value: _A@pipe, __fn1: (_A@pipe) -> _B@pipe) -> _B@pipe"
    Keyword parameter "__fn1" is missing in source Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

But adding double underscore to `value` as well somehow fixes the issue, but I don't understand why:

```python
from typing import Any, Callable, TypeVar, overload

_A = TypeVar("_A")
_B = TypeVar("_B")

@overload
def pipe(value: _A) -> _A:
    ...

@overload
def pipe(__value: _A, __fn1: Callable[[_A], _B]) -> _B:
    ...

def pipe(value: Any, *args: Callable[[Any], Any]) -> Any:
    return None
```

**VS Code extension or command-line**

VS Code extension 1.1.235

**Additional context**
The example is a minimal repro. Original code at: https://github.com/cognitedata/Expression/blob/main/expression/core/pipe.py

**Comment by erictraut** [comment]
I agree this is a bug. I'll work on a fix.

**Comment by erictraut** [comment]
On closer inspection, I think pyright is correct here. The parameter `__fn1` is not positional-only because it occurs after `value`, which is a parameter that can be specified by keyword. If you rename `value` to `__value`, it makes both `__value` and `__fn1` positional-only parameters. In other words, the signature becomes equivalent to `def pipe(value, fn1, /)`.
