### ISSUE TITLE
Attempting to generate a typestub file for Numpy results in hanging indefinitely

### ISSUE THREAD

**Issue by iansan5653** [microsoft/pyright#332]
**Describe the bug**
Trying to use Pyright (the extension or CLI) to generate a stub file for Numpy results in the program hanging indefinitely.

**To Reproduce**
Use the quick fix shortcut to generate a stub file for Numpy, or run `pyright --createstub numpy`.

**Expected behavior**
A type stub file should be generated.

**Screenshots or Code**
If run in the CLI, the following output is given before it hangs forever:
```sh
PS C:\Users\Ian Sanders\Git Repositories\scantron-reading> pyright --createstub numpy
Loading configuration file at C:\Users\Ian Sanders\Git Repositories\scantron-reading\pyrightconfig.json
No include entries specified; assuming C:\Users\Ian Sanders\Git Repositories\scantron-reading\pyrightconfig.json
```

If run in VSCode, the output is:
```
Starting type stub service instance
Loading configuration file at c:\Users\Ian Sanders\Git Repositories\scantron-reading\pyrightconfig.json
No include entries specified; assuming c:\Users\Ian Sanders\Git Repositories\scantron-reading\pyrightconfig.json
Setting pythonPath for service "Type stub": "C:\Users\Ian Sanders\AppData\Local\Programs\Python\Python37\python.exe"
```

**VS Code extension or command-line**
VSCode extension or CLI v1.0.84.

**Additional context**
Running on Windows.

**Comment by erictraut** [comment]
I just published version 1.1.0, which contains a major rewrite of the analyzer. I'm not able to repro the problem you've described with the new version. It's likely that it was fixed as part of the rewrite. I'm going to mark this as fixed, but please re-open it if you're still experiencing the problem.
