### ISSUE TITLE
Wrong types when unpacking PEP 646 unpacked tuple

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#3320]
Consider this code:

```python
from typing_extensions import Unpack, reveal_type

def f(x: tuple[int, Unpack[tuple[str, ...]], float]):
    a, b, *c = x
    reveal_type(a)  # int
    reveal_type(b)  # str
    reveal_type(c)  # list[float]
```
The unpacked part may contain any number of strings (including 0), so the last two types are wrong: `b` could be either a str or a float, and `c` is a list containing any number of strings plus possibly a float.

This seems difficult to get right in all cases and unlikely to come up in practice; I found it only because I am looking to implement this part of the PEP in pyanalyze and was wondering whether I need to handle this case. I think I'll just fall back to a union of all the values in the tuple.

**Comment by erictraut** [comment]
Yeah, this is difficult get right in practice. The complexity involved in this code is already very high. I don't think it's worth the additional complexity to try to model this edge case. If someone happens to come across this, they can work around it by modifying their code.
