### ISSUE TITLE
About the appearance of red wavy lines

### ISSUE THREAD

**Issue by Belonger** [microsoft/pyright#3322]
when i happly writing code, i am not finished the code  sentence, it will appear yellow and red wavy lines. for the yellow wavy lines that i was repaired. but for the red wavy lines, i couldn`t to make it disappeared. in the web, can`t find the answer, so i report the 'bug'😂.
this problem is
![QQ截图20220409224351](https://user-images.githubusercontent.com/57164274/162579070-731169b0-d7f0-4bb8-8be6-9848a9d2cf7d.png)
so how to repair it!

**Comment by Belonger** [comment]
how to completly eliminate the red wavy lines

**Comment by erictraut** [comment]
You eliminate the red wavy lines by eliminating syntax errors in your code. :)

Think of it like a spell checker in a word processor. Once you fix the misspellings, the red wavy lines go away.
