### ISSUE TITLE
__all__.extend rejects tuple of str

### ISSUE THREAD

**Issue by eagleoflqj** [microsoft/pyright#3323]
**Describe the bug**
`__all__.extend` accepts list but not tuple

**To Reproduce**
pyright this file
```py
a = 0
b = 1
__all__ = ['a']
__all__.extend(('b',))
```

**Expected behavior**
No warning.

**VS Code extension or command-line**
command line 1.1.235

**Comment by erictraut** [comment]
Yes, this is intended behavior. The supported forms for `__all__` are documented [here](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface). If you want your module to work with pyright, use one of the supported forms.
