### ISSUE TITLE
Add a CLI flag to run an arbitrary string against Pyright.

### ISSUE THREAD

**Issue by AbstractUmbra** [microsoft/pyright#3326]
**Is your feature request related to a problem? Please describe.**

I've run into a rather niche situation where I would like to run `pyright` against an arbitrary string representing Python code.

**Describe the solution you'd like**
Something similar to `pyright -c "from typing import Optional; a: Optional[int] = None; reveal_type(a);"`.

**Additional context**
I found that `mypy` supports this so one argument here would be feature parity, but I do acknowledge that it is a bit of a niche case.

**Comment by erictraut** [comment]
Yes, this seems like a very niche case. I recommend using pyright in one of the LSP-enabled editors if you want to quickly determine if arbitrary code will type check.

We might reconsider this in the future if there's sufficient interest, but I'm going to close the feature request for now.
