### ISSUE TITLE
reportMissingImports reported even though python.venvPath has been set

### ISSUE THREAD

**Issue by WillemMarais** [microsoft/pyright#333]
Pyright gives a `reportMissingImports` report for a module import even though I have `python.venvPath` set to the directory where the module can be imported. To be more specific, my `settings.json` file contain the following:
```
{
    "python.pythonPath": "/home/user/miniconda3/envs/env/bin/python",
    "python.venvPath": "/home/user/Projects/GitLab/project/python",
    "terminal.integrated.env.linux": {
        "PYTHONPATH": "/home/user/Projects/GitLab/project/python"
    }
}
```

In the directory `/home/user/Projects/GitLab/project/python`, I have the following content:
```
plotting/
plotting/xarray_plot.py
```

When I import `xarray_plot` from a python file say `/home/user/Projects/GitLab/project/notebooks/test.py`, Pyright gives the following report:
```
Import 'plotting.xarray_plot' could not be resolvedpyright (reportMissingImports)
Peek Problem
No quick fixes available
```
I am currently using Pyright version 1.0.84.

**Comment by erictraut** [comment]
`venvPath` is interpreted as a directory that contains multiple named virtual environments, each in its own subdirectory. You need to specify which venv you want by specifying the "venv" setting in your pyrightconfig.json file.

See this documentation for details: https://github.com/microsoft/pyright/blob/master/docs/configuration.md
