### ISSUE TITLE
Descriptors don't match equivalent descriptor protocol

### ISSUE THREAD

**Issue by bryanforbes** [microsoft/pyright#3338]
**Describe the bug**
Sorry for the long code example, but I wanted to give enough context. Given the following code:

```python
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Generic, Protocol, TypeAlias, TypeVar, cast, overload
from typing_extensions import Self

_T = TypeVar('_T')
_T_co = TypeVar('_T_co', covariant=True)


# equivalent declarations as to what is in dropbox/sqlalchemy-stubs:


class TypeEngine(Generic[_T_co]):
    @property
    def python_type(self) -> type[_T_co]:
        ...


class String(TypeEngine[str]):
    @property
    def python_type(self) -> type[str]:
        return str


class Column(Generic[_T]):
    type: TypeEngine[_T]

    def __init__(self, type_: TypeEngine[_T]) -> None:
        self.type = type_

    @overload
    def __get__(self, instance: None, owner: Any) -> Column[_T]:
        ...

    @overload
    def __get__(self, instance: object, owner: Any) -> _T:
        ...

    def __get__(self, instance: Any, owner: Any) -> Column[_T] | _T:
        if instance is None:
            return self

        # some black magic happens here
        return cast(_T, {})


# end equivalent declarations


class Descriptor(Protocol[_T_co]):
    @overload
    def __get__(self, instance: None, owner: Any) -> Self:
        ...

    @overload
    def __get__(self, instance: object, owner: Any) -> _T_co:
        ...


class ReadOnlyRecord(Protocol):
    @property
    def name(self) -> str:
        ...


class DescriptorRecord(Protocol):
    name: ClassVar[Descriptor[str]]


Record: TypeAlias = ReadOnlyRecord | DescriptorRecord


class RecordContainer:
    def add(self, record: Record, /) -> None:
        ...


@dataclass
class DataclassRecord:
    name: str


class SARecord:
    __tablename__ = 'things'

    name = Column(String())


container = RecordContainer()

dataclass_record = DataclassRecord('name')
container.add(dataclass_record)

sa_record = SARecord()
container.add(sa_record)
```

An error is generated on line 96 that `Column[str]` is incompatible with protocol `Descriptor[str]`.

**Expected behavior**
No error should be generated.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool?
Command line

Which version?
1.1.237

**Comment by erictraut** [comment]
The behavior is correct. This is a type violation. However, the error message could be clearer.

The problem is that `name` is a mutable class variable, so it is considered invariant during protocol type validation.

Mypy emits the same error in this case.

I've updated the code to emit a clearer diagnostic message. In particular, it now explains that the attribute is invariant because it is mutable.

```
Expression of type "SARecord" cannot be assigned to declared type "DescriptorRecord"
  "SARecord" is incompatible with protocol "DescriptorRecord"
    "name" is invariant because it is mutable
    "name" is an incompatible type
      "Column[str]" is incompatible with protocol "Descriptor[str]"
```

**Comment by bryanforbes** [comment]
> The problem is that `name` is a mutable class variable, so it is considered invariant during protocol type validation.

Is it `SARecord.name` that is mutable or `DescriptorRecord.name` that's mutable?

**Comment by erictraut** [comment]
It's an issue with the protocol class (`DescriptorRecord`).

**Comment by bryanforbes** [comment]
How should it be declared? It's not immediately obvious.

**Comment by erictraut** [comment]
I'm not sure. You could mark it as `Final`, but both pyright and mypy complain about it because "it must be initialized with a value". You could post the question on [python/typing](https://github.com/python/typing/discussions) to see if others in the typing community have any good suggestions.
