### ISSUE TITLE
Use Pyright for Python-based DSLs

### ISSUE THREAD

**Issue by thautwarm** [microsoft/pyright#3342]
**Is your feature request related to a problem? Please describe.**

This is not a real feature request. I just wonder if most of `pyright` functionalities work if I switch to an alternative parser which uses the parse node types and runtime exception types used in `pyright-internal`.

**Describe the solution you'd like**

Use alternative parsers to produce parse nodes used in Pyright.

**Additional context**

I'm investigating solutions to declarative UI programming in Python, and something like [RenPy](https://www.renpy.org/) or [enaml](https://github.com/nucleic/enaml) is pretty productive, until we consider the IDE integration. These Python-based DSLs can be represented in equivalent Python code, so I'm curious about the possibility to apply pyright for DSLs.

**Comment by erictraut** [comment]
This is way outside the bounds of what pyright is designed for. You're welcome to fork the pyright project, but we don't have any plans to support such functionality.

**Comment by thautwarm** [comment]
Sorry for be confusing. I was not asking for any action from Pyright team. I was wondering the feasibility of such extension.

**Comment by erictraut** [comment]
The feasibility depends on how much the DSL diverges from standard Python syntax and semantics. If the DSL is simply a subset of standard Python, it should be quite feasible. If the DSL adds new syntax or modifies the semantics of statements and expressions in standard Python, it would be less feasible to reuse the existing logic in pyright.
