### ISSUE TITLE
Incorrect type comparison for protocol containing immutable collection

### ISSUE THREAD

**Issue by rsokl** [microsoft/pyright#3345]
This behavior manifested in pyright `1.1.236` and persists in `1.1.237`.

```python
# pyright: strict

from typing import Sequence, Any, List
from typing_extensions import Protocol

class A(Protocol):
    param_groups: Sequence[Any]


def f(value: Sequence[Any], protocol: A):
    pass

class C:
    param_groups: List[Any] = [1, 2]

obj = C()

f(
    value=obj.param_groups,  # OK
    protocol=obj,  # "param_groups" is an incompatible type
)
```
```
Argument of type "C" cannot be assigned to parameter "protocol" of type "A" in function "f"
  "C" is incompatible with protocol "A"
    "param_groups" is invariant because it is mutable
    "param_groups" is an incompatible type
      "List[Any]" is incompatible with "Sequence[Any]"
```

**Comment by rsokl** [comment]
Sorry for the confusion. Being able to assign `obj.param_groups` to `value: Sequence[Any]` without issue – in contrast with the incompatible protocol matching – led me to believe this was an error. I think I am beginning to grasp the difference... will do some reading towards this end 😄

**Comment by erictraut** [comment]
Here's a thought experiment that might help in understanding why mutable class and instance variables need to be invariant for protocol matching. Consider if you pass an instance of `C` to a function that accepts a parameter of type `A`. That function could assign a new value to `param_groups` that is a `Sequence` but not a `List`. This would violate the type contract of `C`, which says that `param_groups` needs to be a `List`.

```python
class A(Protocol):
    param_groups: Sequence[Any]

def f(value: A):
    value.param_groups = (1, 2, 3)

class C:
    param_groups: List[Any] = [1, 2]

obj = C()
f(obj)

obj.param_groups.append([])  # Crash!
```

**Comment by rsokl** [comment]
Thanks so much for the example. This makes sense!

**Comment by rsokl** [comment]
A note to anyone who comes across this issue (I do on occasion because eric's example was so incisive) - a way to fix the original issue with protocol `A` is to simply remove the ability to set its `param_groups` field:

```python
class A(Protocol):
    @property
    def param_groups(self) -> Sequence[Any]: ...
```

This is a pretty powerful pattern for protocols!
