### ISSUE TITLE
Better autocomplete suggestions for Literal type.

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#335]
First of all, thanks for your great work!

Current version of pyright won't suggest literal values:
![image](https://user-images.githubusercontent.com/3479453/68740328-c82a6680-0625-11ea-8e1f-8fc741753df7.png)

**I wish we can have something similar to TypeScript's behaviour.**

Literal values were suggested after assignment mark (`=`):
![image](https://user-images.githubusercontent.com/3479453/68739940-f9eefd80-0624-11ea-976d-fa961156e413.png)

Only Literal values were suggested inside quote marks after assignment mark:
![image](https://user-images.githubusercontent.com/3479453/68740030-26a31500-0625-11ea-9192-366c894bdec6.png)

Also, Literal values were suggested when using comparing syntax:
![image](https://user-images.githubusercontent.com/3479453/68740261-a5984d80-0625-11ea-8cd5-78a178f9a721.png)
![image](https://user-images.githubusercontent.com/3479453/68740271-a9c46b00-0625-11ea-91d4-efec64eabaad.png)

**Comment by erictraut** [comment]
In TypeScript, variables almost always have defined types. In Python, the types are almost never specified — especially in the case of literals. The examples you provided in TypeScript don't really have a practical analog in Python, so I think this feature would have little or no utility. If you can come up with some specific common examples in Python where you think it would be useful, let me know. I'm struggling to come up with examples.

**Comment by erictraut** [comment]
Closing for now. If you come up with additional examples, I'll reconsider.

**Comment by giyyapan** [comment]
Sorry for the late response, I've been a little busy latly :p

The reason we define a string literal is because there is a string variable which can only hold several possible string values. These constrains may not from the python side, they might come from an API parameter specification, for database table design.

I know in python we almost never specify type, but that's the old python way, and type annotations features are meant to make a change. Isn't pyright going to encourage developer to type as many thing as they can by providing smarter error checks and auto complete suggestions (including string literals)?

This example demonstrates the actual use case of string literals in our project
```python
@dataclass
class Account:
    id: str
    verify_type: Literal["none", "normal", "normal_pending", "business", "business_pending"]

def get_verified_accounts(type: Literal["normal", "business"], len=30, offset=0) -> List[Account]:
    ...
```
A developer may forget what value can assign to an account's `verify_type` property, or can pass to the `get_verified_accounts` function, if autocomplete suggestions doesn't tell him the possible value, he will have to check the original defination before use it.

Above all, autocomplete is meant to save one from input every chatacter by provide most possible candidate, I don't see why string literals types shouldn't be supported because it's obviously easy to find all candidates for it.

I can be convinced that pyright has to deal with more important problems so this has to be delayed, but I really don't see way this feature is not needed.

**Comment by erictraut** [comment]
This will be included in the next version of pyright.

**Comment by erictraut** [comment]
This is now implemented in 1.1.15, which I just published.

**Comment by giyyapan** [comment]
Just tried this awesome new feature, works like a charm!
Thank you very much! :smile:

**Comment by jchnxu** [comment]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/4531670/204505189-c14bbbe9-6f97-4f81-add9-940ae8995d97.png">

I didn't spot the this feature in v1.1.281. Is it removed? 

Shouldn't the completion be "aaa" here? The type checking did work though.

**Comment by erictraut** [comment]
It's working for me.

Here's what is suggested prior to typing the quote:

![Screenshot 2022-11-29 at 8 11 48 AM](https://user-images.githubusercontent.com/7040122/204582412-78754fa6-f971-47cc-a059-a3a2dccb37b9.png)

Here's what's presented after typing a quote (with the second quote auto-completed):

![Screenshot 2022-11-29 at 8 09 32 AM](https://user-images.githubusercontent.com/7040122/204581811-39f6d78f-b5ed-4173-99f5-2b8a17d82f15.png)

And here's what's presented after typing `"a` (with the second quote auto-completed):

![Screenshot 2022-11-29 at 8 12 43 AM](https://user-images.githubusercontent.com/7040122/204582771-e49afb6e-dcd9-49c2-82f1-561b26260255.png)

Pyright doesn't automatically present completion suggestions when you type a quote character. You need to invoke the completion suggestion menu manually in this case. In VS Code, this is done by pressing Ctrl+Space.

This bug is 3 years old, so if you think that you've found a new bug, please open a new issue.

**Comment by jchnxu** [comment]
Thanks I got it working. And I'm using monaco editor in which I can send competion request on the char "[" and "(".
