### ISSUE TITLE
 Errors when trying to use the beartype.typing.TypeAlias instead of typing.TypeAlias

### ISSUE THREAD

**Issue by rbroderi** [microsoft/pyright#3363]
**Describe the bug**
I get errors when trying to use the beartype.typing.TypeAlias instead of typing.TypeAlias.

1. Expression of type "Type[str]" cannot be assigned to declared type "TypeAlias"
"Type[type]" is incompatible with "Type[TypeAlias]"

2. Expression of type "(Unknown) -> Any" cannot be assigned to declared type "TypeAlias"
"object" is incompatible with "TypeAlias"

3. Expression of type "(Unknown) -> Any" cannot be assigned to declared type "TypeAlias"
"object" is incompatible with "TypeAlias"

per Beartype:
beartype.typing.TypeAlias is literally just typing.TypeAlias. The former is a convenient synonym for the latter; the two are the exact same object. Specifically, this is how the beartype.typing subpackage declares TypeAlias

            from typing import (  # type: ignore[attr-defined]
                ...
                TypeAlias as TypeAlias,
                ...
            )

**To Reproduce**
Utilize TypeAlias not directly from typing.TypeAlias

**Expected behavior**
As beartype.typing.TypeAlias is a synonym for typing.TypeAlias it should function identically, all other typing.* types seem to work that I have tested other than TypeAlias.

**Screenshots or Code**
Code for problem #
1. Key: TypeAlias = str
2. CallbackFunction: TypeAlias = Callable[[Key], Any]
3. 
     def press(key: Key):
      print(f"'{key}' pressed")

**VS Code extension or command-line**
VS Code extension Pylance v2022.4.1

**Additional context**
None

**Comment by erictraut** [comment]
`TypingAlias` is one of a handful of special forms that pyright needs to handle early in the "binding" phase, prior to type evaluation. As such, if the symbol is imported by another module and re-exported, pyright does not know that it's the same type until it's too late. You need to import it directly from `typing` or `typing_extensions`. 

Is there a reason you cannot simply import this symbol from `typing` or `typing_extensions`? Why do you want to import it in aliased form from another library?

**Comment by rbroderi** [comment]
Here is the reason directly from beartype:
# Import PEP-agnostic type hints from "beartype.typing", a stand-in
# replacement for the standard "typing" module providing improved forward
# compatibility with future Python releases. For example:
# * "beartype.typing.Set is set" under Python ≥ 3.9 to satisfy PEP 585.
# * "beartype.typing.Set is typing.Set" under Python < 3.9 to satisfy PEP
484.
from beartype import typing

My reason is to support python versions prior to 3.9 and above 3.9 with the
future proofing of not needing to go change all List to list etc.

**Comment by erictraut** [comment]
The `typing_extensions` library already serves the purpose of providing backward compatibility for `typing` symbols, so there's no need for other libraries to abstract this symbol.

I can think of potential ways to support this in pyright, but it will add significant complexity and analysis performance overhead that will negatively impact everyone who uses pyright. I don't think it's a good tradeoff to accommodate what I see as an unnecessary and odd abstraction provided by this library. Please import `TypeAlias` from `typing` or `typing_extensions` directly if you want your code to work with pyright.

**Comment by JelleZijlstra** [comment]
> with the future proofing of not needing to go change all List to list etc.

I know that PEP 585 says that these aliases will eventually be dropped, but there is a good chance we'll delay that change. I am one of the maintainers of typing in the standard library and I see little reason for us to ever drop those aliases.
