### ISSUE TITLE
Parsable output from CLI-tool

### ISSUE THREAD

**Issue by priv-kweihmann** [microsoft/pyright#337]
**Is your feature request related to a problem? Please describe.**
Currently the output of the CLI-tool of pyright looks fancy, but isn't easily parsable by e.g. regex.

**Describe the solution you'd like**
I would like to have an option, which creates output for each finding in a format like

`<file>-<error-ID>-<severity>-<message>`

or an other form, as long as there is a common line based presentation of each finding.
Let's call it a "UNIX"-like output.

**Comment by erictraut** [comment]
Can you provide more information about your use case? Why do you want to parse the output text? There may be better ways to do this if I understand your use case better.

Incidentally, pyright doesn't have "error IDs" currently. I've thought about adding them, but that's pretty low on the priority list.

**Comment by priv-kweihmann** [comment]
Sure, no problem.
I'm doing a multi-language analysis framework for YOCTO build system - If you like, somehow similar to python [coala](https://coala.io), which runs a lot of tools on various source code and presents the findings in a common way (usually as Jenkins comp. output).

The build is usually performed on a headless build server, with multiple packages being build at the same time.

For me the easiest way would be to run the tool and transform the output into the used data model of the framework.
And that's where current pyright implementation is a bit tricky.

What I need is to have all information regarding a finding in one block (that could be json or the above mentioned line based output).

BTW: the missing error ID isn't of high importance to me at the moment.

Something like flake8 standard output directly comes into my mind, e.g.:
`
./cls/parser.py:40:5: C901 'Parser.__parseFile' is too complex (24)
./cls/value.py:164:9: E722 do not use bare 'except'
./cls/value.py:167:13: E722 do not use bare 'except'
./cls/value.py:259:5: C901 'TimeValue.IsAllowedValue' is too complex (17)
./cls/value.py:336:9: E722 do not use bare 'except'
./cls/value.py:414:9: E722 do not use bare 'except'
./cls/value.py:435:13: E722 do not use bare 'except'
./cls/helper.py:35:17: E722 do not use bare 'except'
./cls/specials.py:79:5: C901 'SpecialDepCycle.__buildTree' is too complex (13)
./cls/unititem.py:58:5: C901 'UnitItem.Validate' is too complex (11)
./cls/test.py:8:1: F401 'systemdlint.conf.knownMandatory' imported but unused
./cls/test.py:12:1: E302 expected 2 blank lines, found 1
`
that would be fairly enough for me right now

**Comment by erictraut** [comment]
Thanks for the additional information. If I were to add this feature, I'd prefer to format the output as JSON rather than some custom string format. JSON can be extended without breaking existing users. For example, error IDs could be added in the future simply by adding a new field to the JSON output.

**Comment by priv-kweihmann** [comment]
@erictraut json works for me.

**Comment by erictraut** [comment]
This feature will be included in the next published version.

**Comment by priv-kweihmann** [comment]
@erictraut thanks a lot

**Comment by erictraut** [comment]
This is now implemented in 1.1.3, which I just published.
