### ISSUE TITLE
Can't use pyright while connected to a VPN

### ISSUE THREAD

**Issue by aznd** [microsoft/pyright#3377]
**Describe the bug**
The lsp server does not start when I'm connected to a VPN. In my case, I'm using Mullvad VPN
I can use pylsp with no problem, so an issue with pyright

**To Reproduce**
- Connect to Mullvad VPN
- Try to start lsp server with :LspStart

**Expected behavior**
pyright should attach to the buffer/start normally

**Screenshot**

![2022-04-24-165318_507x399_scrot](https://user-images.githubusercontent.com/80119822/164982919-fb4ea296-1592-4ecb-b4e3-d8d22851a019.png)

**VS Code extension or command-line**
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

**Additional info**
my nvim config
https://github.com/aznd/dotfiles/blob/master/nvim/init.vim

When I execute pyright-langserver --stdio from the project root dir, nothing gets "outputted".

**Comment by erictraut** [comment]
Hmm, I don't know how the presence of a VPN would have any impact on pyright. Pyright doesn't make any network calls. I think you may need to diagnose this one on your own. It sounds like a problem with your editor or the LSP plugin for vim.

**Comment by aznd** [comment]
Yes, I just checked. pyright has no issues in vscode with a VPN. Guess its a editor or lsp plugin problem then
