### ISSUE TITLE
import could not be resolved

### ISSUE THREAD

**Issue by yangqi766** [microsoft/pyright#3378]
**Describe the bug**
I am use neovim , lsp server is pyright . the version is 1.1.239

When importing modules in the upper directory in the file. point out error  " import could not be resolved "

![企业微信截图_20220425163042](https://user-images.githubusercontent.com/13087771/165052122-87e1b0cf-7507-40fe-8494-deb9d13ae1b1.png)

**Comment by erictraut** [comment]
I can't tell what you're trying to point out in the highlighted areas of the screen shot. You have highlighted the file `account/views/oj.py` and the `options` and `problem` directories, but the imports don't appear to reference those. Could you clarify which import error you are asking about?

Also, can you explain what you mean by "the upper directory in the file"?

Are these import statements referring to source files within your local project, or are they referring to libraries installed within your Python environment?

This is likely a configuration issue. Please refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/import-resolution.md) for how pyright resolves imports.

**Comment by erictraut** [comment]
I was incorrect in my previous statement. I see that `problem.models` and `options.options` are referenced by the import statements in the screen shot. Is there a module called `problem/models.py` or `problem/models.pyi`? Likewise, do you have a file called `options/options.py` or `options/options.pyi`?

Are you opening the project as a directory? If so, the list of import resolution paths used by pyright should include the root directory of your project.

**Comment by yangqi766** [comment]
I mean that the file account/views/oj.py cannot import files in the directory、options、utils、problem.
![企业微信截图_20220426092848](https://user-images.githubusercontent.com/13087771/165200841-1b8bc67c-99a3-49c5-be16-e81469b9e386.png)


And，the pyright installed by nvim-lsp-installer and nvim-lsp-config in neovim  all config items  are default.  But when i use vscode , after install the pyright , all is well.

![企业微信截图_20220426093047](https://user-images.githubusercontent.com/13087771/165201037-7a7713fc-55cf-48ae-b578-cc09b14e07b5.png)

![企业微信截图_20220426093552](https://user-images.githubusercontent.com/13087771/165201492-a595ba58-c81f-454e-ae53-018990d0ca26.png)

![企业微信截图_20220426093727](https://user-images.githubusercontent.com/13087771/165201643-a3898f45-9265-4a34-8302-f97ce26df348.png)

**Comment by erictraut** [comment]
OK, good to hear all is well when you use VS Code. I'll let you take up the issue with the maintainers of the vim LSP plugin.

**Comment by zyrif** [comment]
I faced the same issue with Neovim LSP in a Django project. Solution seems to be to create a `pyrightconfig.json` or a `pyproject.toml` file with a `[tools.pyright]` section and define some configs such as `include`, `venvPath `and `venv`. If the config file is placed properly (project root) then `include `can be skipped.

**Comment by x00001101** [comment]
> I faced the same issue with Neovim LSP in a Django project. Solution seems to be to create a `pyrightconfig.json` or a `pyproject.toml` file with a `[tools.pyright]` section and define some configs such as `include`, `venvPath `and `venv`. If the config file is placed properly (project root) then `include `can be skipped.

I'm having this trouble and could not find any answer that solve this problem. Can you show me in a simple way to do that, I have no clue what to do with your solution. Where should I put the json file and what configs did it take, I mean the parameters, values, and all.

**Comment by zyrif** [comment]
@x00001101 Place the config file in the root of your project (for Django project, it's the directory that contains `manage.py` file). You can consult the [sample config file](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-config-file) for all the parameters and values, however I only needed to specify the `venvPath` and `venv` (I'm using Anaconda).

**Comment by aniketgm** [comment]
Probably, the folks with this issue, before this comment, might have found the workaround. For a quick, hack I simply created the file `pyrightconfig.json` in the project root and added the "include" setting as follows:
```
{
    "include": [
         "core",
         "api",
    ]
}
```
where, **core** and **api** are code folders in my django project. Other config was not required that much.

**Comment by nyngwang** [comment]
FYI: one cannot use `~` as the shorthand of `$HOME` in the `venvPath` and that `venvPath` and `venv` have to be used together. This way solves my problem: I have a conda env main that is served as the global python env in that I don't have to activate it manually because it's manually added in `$PATH`. Pyright somehow has some trouble accessing this global env from `$PATH` and specifying `venvPath` and `venv` with `pyrightconfig.json` located in my project root solves this problem.

**Comment by jrledezma** [comment]
Regards from 2023

I was facing the same issue with python 3.11, pyright and neovim 0.9, so i added the file in my project's directory root as the folks above this comments said, but, i also follow the next steps
- remove mi .venv directory
- create and activate a new virtual env
- install again all packages from requierments file

**Comment by ludblom** [comment]
Tried following @zyrif suggestion but do not really work out for me. I use pipenv and because of that my virtual environments are located in `/home/ludblom/.local/share/virtualenvs/`, so I add it to my `pyrightconfig.json` file where my `manage.py` file is located, it looks like this:

```
{
  "venvPath": "/home/ludde/.local/share/virtualenvs/",
  "venv": "test-WSINKhfz"
}
```
But still it is not able to find my imports.. Is it something I do wrong?

**Comment by ParsaJR** [comment]
Is there anyway for automating this? For example, is it possible to define some kind of global configuration for pyright that tells: "just find the .venv folder anywhere that you invoked, in any project"
