### ISSUE TITLE
classmethod decorator transforms callable into callable rather than producing a classmethod?

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#3382]
At the point at which the decorator is applied, the class method isn't a callable yet.  It's a classmethod object that replies to `__get__` to produce the bound method.  Yet, Pyright already thinks it's a callable:
```python
from __future__ import annotations
from typing import Callable

def decorate(c: classmethod[None]) -> Callable[[X], None]:
    def g(x: X) -> None:
        return c.__func__(type(x))
    return g

class X:
    @decorate  # error: Argument of type "(cls: Type[Self@X]) -> None" cannot be assigned to parameter "c" of type "classmethod[None]" in function "decorate"
    @classmethod
    def f(cls) -> None:
        print("okay")

x = X()
x.f()
```

**Comment by NeilGirdhar** [comment]
It may be worth leaving this until Python hopefully makes `classmethod` generic on the parameter types like `Callable`?

**Comment by erictraut** [comment]
This is intended behavior. `@classmethod` needs to be special-cased by type checkers. It needs to transform a callable into a callable.

**Comment by NeilGirdhar** [comment]
If there were a fully generic classmethod object, would it make more sense for `classmethod` to produce that object?

This way, it would have the extra attributes defined in the typeshed [here](https://github.com/python/typeshed/blob/197dac2c0c216230d39461ec415e6daabe5e8ea1/stdlib/builtins.pyi#L128).

Also, I'm sure you know, it's not really callable since if `decorate` tries to call `c`, `c` will raise.

Anyway, this I'm sure is rare enough that I can just ignore it.
