### ISSUE TITLE
typing.SupportsIndex and typing_extensions.SupportsIndex in TypeVar constraint

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#3388]
```python
from typing import TypeVar
import typing
import typing_extensions

U = TypeVar("U", int, typing_extensions.SupportsIndex)

def f(si: U) -> U:
    return si

def caller(si: typing.SupportsIndex):
    f(si)
```

produces (on current Pylance in VSCode):

```
Argument of type "SupportsIndex" cannot be assigned to parameter "si" of type "U@f" in function "f"
  Type "SupportsIndex" is incompatible with constrained type variable "U"
```

But `typing.SupportsIndex` and `typing_extensions.SupportsIndex` are protocols and define the same method, so it should solve the TypeVar to `typing_extensions.SupportsIndex`.

I wasn't able to reproduce this with a custom protocol but haven't isolated the exact difference.

(I found this while playing with `itertools.count`, which uses a TypeVar constrained to SupportsIndex in typeshed.)

**Comment by erictraut** [comment]
I'm not able to repro this with the latest published version of pyright or pylance. Are you using a private (not-yet-published) version of `typing_extensions.pyi`?

**Comment by JelleZijlstra** [comment]
That's embarrassing, I had `types-typing-extensions` installed! Removing it fixed the issue. Sorry for the noise.
