### ISSUE TITLE
Pyright not recognising classes imported

### ISSUE THREAD

**Issue by Fibonaccios** [microsoft/pyright#3391]
**Describe the bug**
I have been trying to declare the type of an argument passed as "X" where "X" is an import and for some reason Pyright does not recognise it.
An example would be easier to understand:

<img width="870" alt="Screenshot 2022-04-27 at 15 45 18" src="https://user-images.githubusercontent.com/56938540/165546283-56423cfd-1f2d-4c65-a82c-f34feb9507ae.png">

**To Reproduce**
Steps Above

**Expected behavior**
Not to throw an Error

**VS Code extension or command-line**
Running on Terminal
Pyright Version - 1.1.231

**Comment by erictraut** [comment]
The `docker` library is not a "py.typed" library, which means it does not claim to have type information included with it. I presume you have not installed (or created) [type stubs](https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md) for the library. That means all symbols imported from it are inferred to be "Unknown".

You have a couple of options here:
1. Find an existing type stub package and install it. I don't know if anyone has created one for this library.
2. Create your own type stubs for the package — or at least for the portions of it that you consume.
3. Disable strict type checking for your code so you don't see the `reportUnknownParameterType` error.
4. Enable the `useLibraryCodeForTypes` configuration option (or pass `--lib` to the command line) in which case pyright will attempt to infer the types from the `docker` Python code. Type inference from library code often produces incomplete or unknown types, so you still may have problems with "strict" type checking if you use this approach.

**Comment by Fibonaccios** [comment]
Thank you Eric!
