### ISSUE TITLE
__get__ type hints should not apply to instance variable access

### ISSUE THREAD

**Issue by Terrance** [microsoft/pyright#3393]
### Describe the bug

When an instance of a class using `__get__` is assigned as an instance variable in another class, type hints away from the assignment within the other class incorrectly follow the `__get__` method's type annotations.

### Expected behavior

`__get__` is only called when the class instance is accessed from another class directly, not from an instance attribute, so `self.inst` returns the object itself and its type should just be of that object's class.

### Code to reproduce

```python
class X:

    def __get__(self, obj: Any, objtype: Any = None) -> "BoundX":
        return BoundX(self)


class BoundX:

    def __init__(self, inst: X):
        self.inst = inst
        reveal_type(self.inst)  # Type of "self.inst" is "X"

    def foo(self):
        reveal_type(self.inst)  # Type of "self.inst" is "BoundX" (!)
```

For completeness, here's a more complete `__get__` pattern that I'm using:

```python
class X:

    @overload
    def __get__(self, obj: Any, objtype: Any = ...) -> "BoundX": ...
    @overload
    def __get__(self, obj: None, objtype: Any = ...) -> "X": ...

    def __get__(self, obj: Optional[Any], objtype: Optional[Type[Any]] = None):
        if not obj:
            return self
        return BoundX(self, obj)
```

### VS Code extension

Pyright v1.1.241 / Pylance v2022.4.2

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.243, which I just published. It will also be included in the next release of pylance.

**Comment by ooliver1** [comment]
I'm not sure if this is similar or completely different.

```py
    @t.overload
    def __get__(self, obj: Table, objtype=None) -> int:
        ...

    @t.overload
    def __get__(self, obj: None, objtype=None) -> Integer:
        ...

    def __get__(self, obj, objtype=None):
        return obj.__dict__[self._meta.name] if obj else self
``` from <https://github.com/piccolo-orm/piccolo>, pyright completely ignores the `__get__` return type and assumes `Integer`.

**Comment by erictraut** [comment]
@ooliver1, this issue was closed more than a year ago, and it's unlikely to be the same issue as the one you're experiencing. If you believe there is a bug, please open a new issue. If you have a question, feel free to start a discussion thread. In either case, please provide a self-contained minimal code sample that demonstrates the issue.

**Comment by ooliver1** [comment]
I was just wondering if it was worth it to make an issue since I did try pyright on the version you mentioned with the same results.
