### ISSUE TITLE
Failed to create nodejs.exe link

### ISSUE THREAD

**Issue by rayzchen** [microsoft/pyright#3400]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**

`pyright --createstub pyunity` crashes with `Error: Failed to create nodejs.exe link`

**To Reproduce**
Steps to reproduce the behavior.
Clone https://github.com/pyunity/pyunity
Run `pyright --createstub pyunity`

**Expected behavior**
No error

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.
Command-line tool

**Additional context**
Might be another issue, but after running it once (even just by running `pyright` with no arguments) causes all other runs to error with `* Environment already exists: C:\Users\raych\AppData\Local\Temp\pyright-python.raych\env`. I need to manually delete the folder to do anything else.

**Comment by erictraut** [comment]
It sounds like pyright didn't install correctly. How did you install it? Did you use the community-maintained Python wrapper on pypi, or did you install it directly through `npm --install pyright`?

Which platform are you on? I presume it's Windows based on the "nodejs.exe" error message?

Which version of node do you have installed on your machine? Perhaps try installing a new version directly from nodejs.org?

Do you see the same error if you run `pyright --help`?

**Comment by rayzchen** [comment]
I installed nodejs about a month ago, I installed pyright from pypi and I
get the same error with `pyright --help`.

**Comment by erictraut** [comment]
The error message "Failed to create nodejs.exe link" isn't coming from pyright. I suspect there's something wrong with your environment variables or your node installation. Perhaps PATH was corrupted or overwritten? Sorry, but I think you're going to need to diagnose this one on your own. Perhaps uninstall and reinstall node and pyright? I'm pretty confident this isn't a bug in pyright.

**Comment by rayzchen** [comment]
Path entry still exists
