### ISSUE TITLE
import * is not recursive

### ISSUE THREAD

**Issue by danlipsa** [microsoft/pyright#3413]
I am using version 1.1.241.

For:
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/paraview/package.py
I use a project pyrightconfig.json inside:
https://github.com/spack/spack
like this:
{
    "include" : [
        "lib/spack"
    ],
    "extraPaths" : [
        "lib/spack"
    ]
}
The symbol CMakePackage is not defined even if there is a 'from spack import *' that should have imported the file cmake.py that contains that class.
Adding 
from spack.build_systems.cmake import CMakePackage
fixes that missing symbol.

Do you have any suggestion on how to fix this? Maybe with changes to the config file? Thanks!

**Comment by erictraut** [comment]
First, it's generally a really bad idea to use a wildcard import from a library. PEP 8 recommends against it for good reasons. A wildcard import pollutes your module's namespace in ways that you do not control, so updates to the library can create namespace conflicts that are difficult to debug. So I highly recommend against using wildcard imports. It's unfortunate that this feature is a part of the Python language.

The symbols that are imported by a wildcard import are dictated by the `__all__` symbol defined within the target module. For details refer to [this documentation](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package). The module `lib/spack/spack/__init__.py` defines `__all__` as follows:
```python
__all__ = ['spack_version_info', 'spack_version']
```

That means these are the only two symbols that are imported through a wildcard import that targets this module. The symbol `CMakePackage` is not listed here, so it is not included in the wildcard import.

It looks like `CMakePackage` is declared in a submodule called `spack.build_systems.cmake`, so you would need to import it from that submodule.

```python
from spack.build_systems.cmake import CMakePackage
```

**Comment by danlipsa** [comment]
Thanks for the detailed explanation. Indeed, import * is not ideal. Interestingly, all classes are found correctly even if they are not listed in __init__. However everything is executed through the spack driver so that might do some path adjustment. I think I'll get rid of the import * to fix this.
