### ISSUE TITLE
Overriding a field type from a parent class should be disallowed 

### ISSUE THREAD

**Issue by Tomaz-Vieira** [microsoft/pyright#3416]
**Describe the bug**
Overriding the field type from a parent class is allowed, and can produce variance-like soundness errors, e.g.: when the parent class writes to one such overridden field.

**To Reproduce**
```python
# pyright: strict

from typing_extensions import reveal_type

class Animal:
    ...

class Dog(Animal):
    ...

class Cat(Animal):
    ...

class Parent:
    a: Animal

    def set_a(self, a: Animal):
        self.a = a

class Child(Parent):
    a: Dog
    def __init__(self) -> None:
        super().__init__()
        self.a = Dog()

child = Child()
reveal_type(child.a) # Type of "child.a" is "Dog"
child.set_a(Cat()) # unsound, no errors
```

**Expected behavior**
I'm not sure if this is the adequate solution, but it seems that child classes should not be able to change the type of a field from a parent class, even if the overriding type is a subtype of the original type.

**Comment by erictraut** [comment]
This is intended behavior. Child classes are allowed to override class and instance variables from base classes as long as the overridden type is a subtype. I agree this isn't 100% sound from a type perspective, but this is a case where practicality beats 100% soundness. 

Pyright's behavior is consistent with mypy in this case. Most code bases rely on the current behavior, so I'd be reluctant to change it, even with a strict-mode setting.
