### ISSUE TITLE
Implement pull model diagnostics

### ISSUE THREAD

**Issue by w0rp** [microsoft/pyright#3452]
**Is your feature request related to a problem? Please describe.**

All language servers at the moment use a "push" model for diagnostics, which provides errors to clients essentially at random. A new "pull" model for diagnostics makes it possible for clients to say that they'd prefer to explicitly ask for diagnostics from a server and display them at a time of their choosing. It would be advantageous to implement this in Pyright's language server.

**Describe the solution you'd like**

Implement the pull model diagnostics in Pyright per https://github.com/microsoft/language-server-protocol/issues/737 and https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification

**Additional context**

I am the primary author and maintainer of [ALE](https://github.com/dense-analysis/ale), and I am looking for any vendor of any language server to implement the new pull model first. I want to use any server as a test for implementing the new functionality for any potential server.

**Comment by erictraut** [comment]
Pyright's architecture is built around the current push model. We don't have any plans to change it at this time.

**Comment by w0rp** [comment]
It would be reasonable to make a plan for a Microsoft team to implement a reasonable change in behaviour made available by another Microsoft team.

**Comment by w0rp** [comment]
I'll note here in a comment and edit the description to indicate that this feature has finally been implemented in this pull request: https://github.com/microsoft/pyright/pull/10055
