### ISSUE TITLE
Defining a new function should not have completions (unless overriding)

### ISSUE THREAD

**Issue by jakebailey** [microsoft/pyright#346]
![image](https://user-images.githubusercontent.com/5341706/69288027-223ea500-0bad-11ea-95bb-174028f3aa39.png)

The function currently being typed for the first time is being suggested as a completion. This is a bit ackward (and the tooltip shown is oddly-typed as Unknown, when in reality it as no parameters yet).

I don't think it's valuable to offer anything after `def` since you're definitely creating something new. The only context where a suggestion would make sense after `def` is within a class where the intent is to override a function from a base.

(Or, potentially, if you're writing "overrides" and it was previously defined.)

**Comment by erictraut** [comment]
Thanks for the suggestion. The fix will be in the next version. I've implemented the logic for filling in the full signature for overridden methods from base classes.

Here's the change:
https://github.com/microsoft/pyright/commit/73547f08d1c326545d4c3386237684550ac07eca

**Comment by erictraut** [comment]
This is now implemented in 1.1.3, which I just published.
