### ISSUE TITLE
Pyright should correctly identify user-created module files

### ISSUE THREAD

**Issue by askfiy** [microsoft/pyright#3461]
**Describe the bug**
When creating a new file and importing it, it will prompt `xxx is unknown import symbol`.

The error disappears only when I quit the editor and reopen the file.

**To Reproduce**
1. I use django
2. Create a new py file in any package
3. Import the newly created py file into any other file

**Screenshots or Code**
![图片](https://user-images.githubusercontent.com/81478335/168421095-1d64b0e0-2131-4949-aaa5-d51f141eded8.png)

**VS Code extension or command-line**
I use neovim built-in LSP

**Comment by erictraut** [comment]
This symptom indicates that pyright isn't being informed of the new file creation. Pyright registers a file system watcher with the client through the language server protocol. It expects to receive file system change notifications when a new file is created. It sounds like this isn't happening. I confirmed that it works fine with VS Code, so I suspect this is a bug in the LSP plugin for neovim.

If you set "python.analysis.logLevel" to "Information" and then create a new file within your project, you should see pyright output something that looks like this:

```
[Info  - 7:45:22 AM] Searching for source files
[Info  - 7:45:22 AM] Found 28 source files
```

I'm guessing that you won't see this. If not, that confirms my theory.

I recommend filing an issue with the neovim LSP provider. They'll need to fix the issue in their code.

In the meantime, you can use the "Restart Language Server" command to manually trigger a restart, or you can quit and restart the editor.

**Comment by askfiy** [comment]
Where should I go to check the Log log? I really don't see any information.

After I restarted `Pyright` it did get recognized successfully...

**Comment by erictraut** [comment]
In VS Code, you would go to the "Output" tab to see the logs. I don't know where neovim displays it.

**Comment by askfiy** [comment]
Ok, thanks for your reply, I'll raise this question with `neovim`.
