### ISSUE TITLE
Error message is repeated

### ISSUE THREAD

**Issue by parched** [microsoft/pyright#3467]
**Describe the bug**
When I write
```python
"a" * "a"
```
The error message is shown twice
> Operator "\*" not supported for types "Literal['a']" and "Literal['a']"
    Operator "\*" not supported for types "Literal['a']" and "Literal['a']"

**Expected behavior**
The error message just appears once.

**VS Code extension or command-line**
Both, command line 1.1.245

**Comment by erictraut** [comment]
This isn't a repeated error message. It's a nested error message. The second line is indented from the first. The reason both of these messages are emitted can be seen more clearly when one or both of the types are unions.

```python
def func(a: str | int, b: str):
    return a * b
```

This results in the following error:
```
Operator "*" not supported for types "str | int" and "str"
  Operator "*" not supported for types "str" and "str"
```
