### ISSUE TITLE
Don't offer completion items directly after an integer constant + dot

### ISSUE THREAD

**Issue by jakebailey** [microsoft/pyright#347]
![image](https://user-images.githubusercontent.com/5341706/69289588-d6dac580-0bb1-11ea-930d-3d398d400d43.png)

This is distracting if you try to type float/complex.

Further, the `.` only works if you have a space after the integer constant to "complete" the token. Example, in IDLE:

![image](https://user-images.githubusercontent.com/5341706/69289672-24efc900-0bb2-11ea-806c-62a5b210dcbc.png)

This doesn't apply to things like `1.0.hex()` or `1j.imag`.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release. Here's the change:
https://github.com/microsoft/pyright/commit/ef51b85abf865c465db31c453b9196ca36e733a2

**Comment by erictraut** [comment]
This is now fixed in 1.1.3, which I just published.
