### ISSUE TITLE
Github action version of pyright

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#3484]
I assume @jakebailey's [github action version of pyright](https://github.com/jakebailey/pyright-action) is the recommended way to integrate pyright with github. It would be great to list it in [ci-integration.md](https://github.com/microsoft/pyright/blob/main/docs/ci-integration.md).

**Comment by erictraut** [comment]
Yes, good suggestion. I updated the docs accordingly.

**Comment by twoertwein** [comment]
Keeping the pre-commit example might be helpful for people who do not use github.

**Comment by erictraut** [comment]
Yeah, good point. I've added back the pre-commit hook example.
