### ISSUE TITLE
Update to latest typeshed stubs

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#349]
It has been a few months since pyright's typeshed stubs were updated to match the latest versions checked in to the typeshed repo.

**Comment by cshesse** [comment]
I filed a PR against typeshed after getting an error from pyright: https://github.com/python/typeshed/pull/3479 is that correct or should I be filing this against pyright to avoid waiting a few extra months?

**Comment by erictraut** [comment]
If it has already been fixed in typeshed, then file a bug against pyright to remind me to update to the latest typeshed stubs. If it hasn't been fixed in typeshed, then filing the bug (or submitting a PR) to typeshed is appropriate. Once the fix is accepted by typeshed, give me a ping, and I'll pull the change into pyright.

**Comment by erictraut** [comment]
This is now fixed in 1.1.4, which I just published.
