### ISSUE TITLE
"No overloads for ... match the provided arguments" for function with parameter of type `bool` and overloads of types Literal[True]/Literal[False]

### ISSUE THREAD

**Issue by ldorigo** [microsoft/pyright#3525]
See this snippet:

```python
from typing import Literal, overload

@overload
def foo(a: ..., b: ..., return_number: Literal[True]) -> int:
    ...

@overload
def foo(a: ..., b: ..., return_number: Literal[False]) -> str:
    ...

def foo(a: int, b: int, return_number: bool) -> int | str:
    return a + b if return_number else str(a + b)

def dosomething(return_number: bool) -> None:

    t = foo(1, 2, return_number)
```

Pylance shows an error on the last line. Interestingly, when I first created the issue the error was "No overloads for foo match the provided arguments", but upon reloading, it became

```
Argument of type "bool" cannot be assigned to parameter "return_number" of type "Literal[False]" in function "foo"
  "bool" cannot be assigned to type "Literal[False]"
```

In this case, shouldn't pylance just choose the general signature and set `t` to be of type `int | str` ?

**Comment by erictraut** [comment]
This is expected behavior. A `bool` value is not assignable to either `Literal[True]` or `Literal[False]`. Mypy emits the same error in this case.

If you want your function `foo` to work with `bool`, you would need to provide a third overload that accepts a `bool` parameter.
