### ISSUE TITLE
Pyright falsely expects type argument for `Unpack` when `Unpack` is used in an expression

### ISSUE THREAD

**Issue by kennipj** [microsoft/pyright#3529]
Consider this example code:

```py
from typing import Generic, get_origin, get_args
from typing_extensions import Unpack, TypeVarTuple

Ts = TypeVarTuple("Ts")


class SomeClass(Generic[Unpack[Ts]]):
    ...


for t in get_args(SomeClass.__orig_bases__[0]):  # type: ignore
    if get_origin(t) is Unpack:  # error: Expected a single type argument after "Unpack"
        print(t)  # prints: typing_extensions.Unpack[Ts]

```

You can also reproduce this with a simplified example:

```py
from typing_extensions import Unpack

Unpack # error: Expected a single type argument after "Unpack"
```

Both examples are perfectly valid python code, and I would expect pyright not to report any error in this case (disregarding the necessary `# type: ignore` in the first example).

Tested on pyright 1.1.251

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.252, which I just published. It will also be included in the next release of pylance.
