### ISSUE TITLE
Support constrained types from pydantic

### ISSUE THREAD

**Issue by karolzlot** [microsoft/pyright#3538]
**Is your feature request related to a problem? Please describe.**
Currently contrained types from pydatnic are not supported.
For example you can open this code snippet in vscode:
https://pydantic-docs.helpmanual.io/usage/types/#constrained-types

Effect: 
![image](https://user-images.githubusercontent.com/11590960/171987385-c5f2b652-7310-484d-b9d8-185090983a00.png)

**Describe the solution you'd like**
I'm not sure if this should be fixed in pyright or in pydantic.

**Additional context**
n/d

**Comment by karolzlot** [comment]
Related: https://github.com/samuelcolvin/pydantic/issues/156

**Comment by erictraut** [comment]
Pyright is a a standards-based type checker, and it doesn't contain any special-cased knowledge of non-standard behaviors in third-party libraries.

We do work with library developers to standardize behaviors as part of the Python typing standard. [PEP 681](https://peps.python.org/pep-0681/), which provided core support for pydantic, is a good example of this. 

I think it's unlikely that Pyright or the Python typing standard would ever support the annotation form that you have highlighted above. Type annotations cannot contain call expressions, and there are good reasons for this limitation.
