### ISSUE TITLE
question about io classes

### ISSUE THREAD

**Issue by cshesse** [microsoft/pyright#354]
Thanks for fixing my issues so quickly!

I use a number of `io.*` classes and am having trouble getting pyright to analyze the code.

```
import io


def f(kind):
    if kind == "raw":
        f = io.FileIO("test", mode="wb")
        return io.BufferedWriter(f)
    elif kind == "text":
        f = io.FileIO("test", mode="w")
        f = io.BufferedWriter(f)
        return io.TextIOWrapper(f)
    else:
        raise Exception("oh no")


x = f("raw")
x.write(b"meow")
```

This produces:

```
pyright --project .
Loading configuration file at C:\p\misc\pyright_test4\pyrightconfig.json
typingsPath C:\p\misc\pyright_test4\typings is not a valid directory.
Searching for source files
Found 1 source file
C:\p\misc\pyright_test4\test.py
  11:33 - error: Argument of type 'BufferedWriter' cannot be assigned to parameter 'buffer' of type 'IO[bytes]'
  'BufferedWriter' is incompatible with 'IO[bytes]'
  17:9 - error: Argument of type 'Literal[b'meow']' cannot be assigned to parameter 's' of type 'str'
  'bytes' is incompatible with 'str'
2 errors, 0 warnings
Completed in 1.27sec
```

I can't tell if this is my issue, a typeshed issue, or a pyright issue.  It seems that `BufferedWriter` takes `IO[bytes]` but maybe should take `BufferedIOBase`.  It's not clear to me what the relation between `IO[bytes]` and any of the `io.*` classes are.  Any ideas?  I can submit a PR to change it from `IO[bytes]` to `BufferedIOBase` but I'm not confident that will be accepted.  Should it be a union of those?

In addition, there's an error there about how I can't send a `bytes` to `write` even though that's the correct type to send in this case.  In fact, if I change it to be `x.write("meow")` the code will then fail to run, but pyright will actually produce a different error:

```
Found 1 source file
C:\p\misc\pyright_test4\test.py
  14:33 - error: Argument of type 'BufferedWriter' cannot be assigned to parameter 'buffer' of type 'IO[bytes]'
  'BufferedWriter' is incompatible with 'IO[bytes]'
  20:9 - error: Argument of type 'Literal['meow']' cannot be assigned to parameter 'b' of type 'Union[bytes, bytearray]'
  'str' is incompatible with 'bytes'
  'str' is incompatible with 'bytearray'
2 errors, 0 warnings
Completed in 1.276sec
```

I can manually annotate the return value:

```
import io
from typing import Union, TextIO


def f(kind) -> Union[io.BufferedIOBase, io.TextIOBase]:
    if kind == "raw":
        f = io.FileIO("test", mode="wb")
        return io.BufferedWriter(f)
    elif kind == "text":
        f = io.FileIO("test", mode="w")
        f = io.BufferedWriter(f)
        return io.TextIOWrapper(f)
    else:
        raise Exception("oh no")


x = f("raw")
x.write(b"meow")
```

I get:

```
pyright --project .
Loading configuration file at C:\p\misc\pyright_test4\pyrightconfig.json
typingsPath C:\p\misc\pyright_test4\typings is not a valid directory.
Searching for source files
Found 1 source file
C:\p\misc\pyright_test4\test.py
  12:33 - error: Argument of type 'BufferedWriter' cannot be assigned to parameter 'buffer' of type 'IO[bytes]'
  'BufferedWriter' is incompatible with 'IO[bytes]'
  12:16 - error: Expression of type 'TextIOWrapper' cannot be assigned to return type 'Union[BufferedIOBase, TextIOBase]'
  'TextIOWrapper' is incompatible with 'BufferedIOBase'
  'TextIOWrapper' is incompatible with 'TextIOBase'
  18:9 - error: Argument of type 'Literal[b'meow']' cannot be assigned to parameter 's' of type 'str'
  'bytes' is incompatible with 'str'
3 errors, 0 warnings
Completed in 1.259sec
```

That makes me think that typeshed is wrong on that and in fact there's a TODO in typeshed: https://github.com/python/typeshed/blob/master/stdlib/3/io.pyi#L149

It's unclear to me why this intentionally contains the wrong base class, but I assume that at least is a question for typeshed.  Changing that locally fixes the new error but still leaves the original errors.

Here's the version of pyright:

```
pyright --version
pyright 1.1.3
```

This is the config:
```
{
    "include": [
        "."
    ]
}
```

**Comment by erictraut** [comment]
I've verified that pyright is doing the right thing here. I'm not familiar enough with the internals of the IO classes in Python to say whether this is a bug in the typeshed stubs or a bug in your code. I recommend posting the question in the typeshed repo.

**Comment by cshesse** [comment]
Hmm, so I'm still confused then:

```
class BinaryX:
    def write(self, s: bytes) -> None:
        pass


class StringX:
    def write(self, s: str) -> None:
        pass


def g(kind):
    if kind == "binary":
        return BinaryX()
    elif kind == "string":
        return StringX()
    else:
        raise Exception("oh no")


x = g("binary")
x.write(b"test")
x.write("test")
```

This produces the following error:

```
Loading configuration file at C:\p\misc\pyright_test4\pyrightconfig.json
typingsPath C:\p\misc\pyright_test4\typings is not a valid directory.
Searching for source files
Found 1 source file
C:\p\misc\pyright_test4\test.py
  41:9 - error: Argument of type 'Literal[b'test']' cannot be assigned to parameter 's' of type 'str'
  'bytes' is incompatible with 'str'
  42:9 - error: Argument of type 'Literal['test']' cannot be assigned to parameter 's' of type 'bytes'
  'str' is incompatible with 'bytes'
2 errors, 0 warnings
```

How can both string and bytes be incompatible?

**Comment by erictraut** [comment]
They're both incompatible because the return type of function g is a union of types BinaryX or StringX. It could be either. That means usage of the return type needs to conform to proper use of _both_ a BinaryX and StringX. When you pass a bytes argument, it is incompatible with StringX. When you pass a str argument, it is incompatible with BinaryX.

My first thought is that you shouldn't define a function that returns two completely incompatible return types. That's problematic for a number of reasons. Consider restructuring your code.

Another potential solution here is to use overloads:
```
from typing import overload, TYPE_CHECKING

if TYPE_CHECKING:
    from typing_extensions import Literal

class BinaryX:
    def write(self, s: bytes) -> None:
        pass

class StringX:
    def write(self, s: str) -> None:
        pass

@overload
def g(kind: "Literal['binary']") -> BinaryX:
    ...
@overload
def g(kind: "Literal['string']") -> StringX:
    ...

def g(kind):
    if kind == "binary":
        return BinaryX()
    elif kind == "string":
        return StringX()
    else:
        raise Exception("oh no")


x = g("binary")
x.write(b"test")
```

**Comment by cshesse** [comment]
Ah thanks for the clarification!  I was under the impression that Union meant that the code had to work with any of the types in the Union, not all of them but your explanation makes sense.

I'm fine with restructuring my code, but this is unfortunately a wrapper of the `io.FileIO` function so it may need to return completely incompatible return types since that's what `io.FileIO` seems to be doing.  I'll try the overload method.  Thanks again!

**Comment by erictraut** [comment]
Another approach that we sometimes use in these circumstances... If you know that the type must be `BinaryX` even though the return type is `Union[BinaryX, StringX]`, you can add an assert statement `assert isinstance(x, BinaryX)` before you attempt to use it. This tells the type checker "I know more than you are able to infer this case". It imposes a tiny runtime overhead, but we find that tradeoff to be acceptable. Plus, if you run in debug mode, the assert statement will validate your assumption at runtime and throw an exception if you were incorrect.
