### ISSUE TITLE
Featreu request: Disable a single rule for an entire file

### ISSUE THREAD

**Issue by hacker-DOM** [microsoft/pyright#3541]
In my package [adoc-math](https://github.com/hacker-dom/adoc-math) I have an imports [file](https://github.com/hacker-DOM/adoc-math/blob/c04eebf354b6f36d29223de2f97c4afbbf8a54fd/adoc_math/_common/a_imports.py#L1) that contains all imports for the entire project. It would be great if pyright extended file-level `type: ignore` to constructs like `pyright: ignore[reportUnusedImport]`. From a user perspective it may seem intuitive that this should be possible, however, I 
unfortunately cannot estimate the difficulty of implementing it.

**Comment by hmc-cs-mdrissi** [comment]
`# pyright: reportUnusedImport=False`

is the way to do that and is already supported. Just add it the top of your file.

**Comment by hacker-DOM** [comment]
That works! Just a quick suggestion, it should we `reportUnusedImport=false` (lowercase f) - thank you!!
