### ISSUE TITLE
Add check for `# type` annotation comments

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#3557]
There is a healthy discussion in the typing-sig about deprecating `# type: ` comments. To help people move away from these, it would be useful to add a feature that flags the usage of type comments as an error.

**Comment by erictraut** [comment]
A new `reportTypeCommentUsage` diagnostic check will be included in the next release. It is off by default but included in the "strict" rule set.

**Comment by ntaylorwss** [comment]
I wanted to add my two cents (and a potential use case?) to this conversation, but first I just have to thank you for your dedication to this project. I've honestly never seen an issue board for a widely-used open source project kept this clean. It's extremely impressive.

I'm currently working on a project wherein I make heavy use of generics and overloads for the initialization of a class, but I also make the equivalent runtime validations in the implementation of the `__init__`. My goal is to have a type-safe experience when the user has type checking enabled (i.e. in their editor), but to also have a safe experience when the user does not have type checking enabled (i.e. in a notebook).

When it comes to writing tests for this class, I obviously want to extensively test the runtime functionality that throws errors in the face of incorrectly typed instantiations. This requires instantiating the class with incorrectly typed arguments in my tests, which are checked with pyright. The only way for these tests to make it past my pre-push check for pyright cleanness is to ignore these lines.

It's very much a deliberate ignore, as you can see. I'm intentionally calling functions incorrectly, to assert that my runtime validation mirrors the validation that pyright is doing statically.

I can definitely understand that this is perhaps unusual usage, and in general I agree that `# type: ignore` comments are bad practice. I've also being following the typing conversation in the Python community a lot lately, and it seems like typing in Python will always and forever be "opt-in"; for that reason, I want to create an experience that is typesafe both statically and at runtime, and doing so requires usage of `# type: ignore` in tests.

All that to say: I'm all for a check in strict mode, but if this were to become unavoidable baked-in behaviour, I would have a hard time.

**Comment by JelleZijlstra** [comment]
I think Eric's change won't do anything to `# type: ignore` comments, only to the "type comments" that were needed to add types to Python 2 (and, more rarely, Python <3.5) code. See https://peps.python.org/pep-0484/#type-comments for the specification. We're currently discussing deprecating these comments, but not `# type: ignore`—that's here to stay.

**Comment by ntaylorwss** [comment]
Totally misunderstood, my bad. I had conflated this with the (much earlier) conversation where there was some reluctance to add `# type: ignore` support. Good to know that that is safe. Thanks!

**Comment by erictraut** [comment]
As Jelle said, this check specifically targets type annotation comments, which are no longer necessary since Python 3.6 and [PEP 526](https://peps.python.org/pep-0526/) added support for variable type annotations. This change doesn't affect `# type: ignore` comments.

Your approach for testing runtime validating behavior sounds reasonable to me, and this is a perfectly legit use of `# type: ignore` comments.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.254, which I just published. It will also be included in the next release of pylance.

**Comment by dimaqq** [comment]
What's the new way of doing this?

```
except GoodException as e:  # type: GoodException[str]
```

**Comment by erictraut** [comment]
```python
e: GoodException[str]
except GoodException as e: ...
```
