### ISSUE TITLE
issubclass doesn't narrow type

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#3565]
**Describe the bug**
Pyright seems to support `issubclass` based on #306 but it seems it doesn't work.

**To Reproduce**
```py
# pyright: strict
from __future__ import annotations

def test(x: str | int) -> None:
    if issubclass(type(x), int):
        reveal_type(x)
```
Pyright (and mypy) infer `str | int`.

**Expected behavior**
Should be narrowed to `int`.

**Comment by erictraut** [comment]
Yes, you're using an expression form that is not currently supported by type narrowing. In particular, you're calling `type(x)` within the `issubclass` call and expecting `x` to be narrowed. 

We do occasionally add support for new type narrowing patterns but only if there is strong signal that it's a common pattern. I've never seen this pattern used before, and it's the first time we've received such a request. Furthermore, mypy doesn't support this pattern for narrowing, and I don't see any requests for this in the mypy issue tracker.

I'm going to close this feature request for now. We might reconsider it in the future if there is sufficient demand.

In the meantime, you can modify your code as follows so it uses a supported type narrowing pattern.

```python
def test(x: str | int) -> None:
    x_type = type(x)
    if issubclass(x_type, int):
        reveal_type(x_type)
```

**Comment by twoertwein** [comment]
I came across this pattern in [pandas/core/arrays/numeric.py](https://github.com/pandas-dev/pandas/blob/2db05d54f55a41d4a51f02e6cf45464e15c79054/pandas/core/arrays/numeric.py#L129) when trying to make this file be reportGeneralTypeIssues-compliant. I think in this instance, the `issubclass(...)` call can be replaced with `isinstance(dtype, NumericDtype)`.

**Comment by erictraut** [comment]
Yes, I agree that's a better solution.
