### ISSUE TITLE
TypedDict's `update()` method thinks that all fields need to be updated

### ISSUE THREAD

**Issue by wch** [microsoft/pyright#3580]
This is from https://github.com/python/typeshed/issues/8086. One of the maintainers there said that this would need to be special-cased by the type checker.

Here's an example of the issue:

```py
from typing import TypedDict

class Foo(TypedDict):
    a: str
    b: str

f: Foo = {"a": "A1", "b": "B1"}
f.update({"a": "A2"})

print(f)
# > {'a': 'A2', 'b': 'B1'}
```

When I run it through pyright, I get the following output:

```
/...../test.py:10:10 - error: Argument of type "dict[str, str]" cannot be assigned to parameter "__m" of type "Foo" in function "update"
    "b" is required in "Foo" (reportGeneralTypeIssues)
```

This is because the `update()` method declaration says that `self` and `__m` are the same type:

```py
def update(self: _T, __m: _T) -> None: ...
```

https://github.com/python/typeshed/blob/4967c8bc12587d503a9ffcbeb3b716b1e97f19cc/stdlib/typing.pyi#L902-L916

It would be helpful if Pyright had support for this.

**Comment by erictraut** [comment]
There's not an easy way to support this given the way pyright implements `TypedDict` support. It would require some very ugly special-case logic at a point in the type analysis engine where we do not have any special-case logic currently. 

I'll think about this a bit more, but my current inclination is to say that this will not be supported and that you will need to either avoid this use pattern (e.g. use `f["a"] = "A2"` instead) or use a `# type: ignore` comment to work around the error.

**Comment by erictraut** [comment]
Yes, I agree with your assessment of `TypedDict`. I also find it to be quite constraining and cumbersome. I tend to prefer `dataclass` for many use cases.

**Comment by erictraut** [comment]
After thinking about this more, I'm not able to come up with a straightforward way to support this feature request. It would involve some very ugly special-casing in the core of the type evaluator. We might reconsider this in the future if we get signal from enough users that this is important, but for now I'm going to close the request.

**Comment by mehdigmira** [comment]
Would like to see this implemented :). Partial updates are very common when working with dicts in Python (and hence with TypedDict). Mypy supports this pattern.

P.S: Thanks for all the great work put into pyright 👍
