### ISSUE TITLE
Order-dependent inference of `Never` involving `Callable[P, Any]`  

### ISSUE THREAD

**Issue by rsokl** [microsoft/pyright#3586]
I wanted to write a wrapper that would check if its target function had already been decorated by it. I found that checking `isinstance(func, MyWrapper)` produced a `Never` type for `func`.

This led me to discover the following order-dependent behavior:

```python
from typing import Any, Callable, Generic
from typing_extensions import ParamSpec

P = ParamSpec("P")

class A(Generic[P]):
    def __init__(self, callable_: Callable[P, Any]) -> None:
        if isinstance(callable_, A):
            reveal_type(callable_)  # type: Never

        if isinstance(callable_, type(self)):
            reveal_type(callable_)  # type: Self@A[P@A]

        if isinstance(callable_, A):
            reveal_type(callable_)  # type: A[P@A]
        
        self.fn = callable_
    
    def __call__(self, *args: P.args, **kwds: P.kwargs) -> Any:
        return self.fn(*args, **kwds)
```

It seems to me that the first `reveal_type(callable_)` should produce `A[P@A]`

**Comment by erictraut** [comment]
The current behavior is intended.

The first `isinstance` narrows the type of `callable_` to `Never` in the positive case and does not narrow in the negative (implied "else") case. The type of `__callable` after the first "if" statement is therefore the union of `Never` and `Callable[P, Any]`, which is `Callable[P, Any]`. 

The second `isinstance` narrows the type of `callable_` to `Self[P@A]` in the positive case and  and does not narrow in the negative (implied "else") case. The type of `__callable` after the first "if" statement is therefore the union of these two types, which is `Self[P@A] | Callable[P, Any]`. 

The third `isinstance` narrows this the type to `A[P@A]` in the positive case, as it should.

Mypy also narrows to `Never` in the first `isinstance` call.

**Comment by rsokl** [comment]
Thanks for the explanation, and apologies for the unnecessary issue.
