### ISSUE TITLE
pyright is assuming that all `==` operations return boolean, without respecting the `__eq__` method of the objects.

### ISSUE THREAD

**Issue by mmohaveri** [microsoft/pyright#3588]
**Describe the bug**
pyright is assuming that all '==' operations return boolean, without respecting the __eq__ method of the objects. Imagine that you're overloading `__eq__`
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
def foo(self) -> str:
    return 3
```

If your code relies on symbols that are imported from a third-party library, include the associated import statements and specify which versions of those libraries you have installed.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.

**Additional context**

**Comment by erictraut** [comment]
Pyright does honor overrides to `__eq__` and other comparison operators.

Here's an example:

```python
class Foo:
    def __eq__(self, other: object) -> str:
        return "Yes!"

x = Foo() == 1
reveal_type(x)  # str
```

If you think there's a bug here, please open a new bug and include a code snippet that demonstrates the problem. The code snippet in your example doesn't seem to have anything to do with `__eq__` operator overloading.

**Comment by mmohaveri** [comment]
Sorry, I accidentally hit submit before finishing the report, I was not able to reproduce the error in an stand alone situation, I'll fix the rest of my typing errors and submit another bug report as soon as I'm able to find the root cause of it.
