### ISSUE TITLE
Type is incompatible while two classes in cross reference

### ISSUE THREAD

**Issue by flyingcodes** [microsoft/pyright#359]
**Describe the bug**
script can be run success, and output "lance say ...",
but pyright show following error: 
Argument of type 'CB' cannot be assigned to parameter 'cb' of type 'CB'
  'CB' is incompatible with 'CB'

**IDE**
Version: 1.40.1 (system setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
pyright: current release

**Screenshots or Code**
```
class CB: pass

class CA:

    def ma(self, cb : CB) :
        fa(self, cb)
    
    def say(self, name : str) :
        print(name + " say ...")

class CB:

    def __init__(self) -> None: 
        self.name = "lance"

    def callCA(self, ca : CA) :
        ca.ma(self)



def fa(ca : CA, cb : CB):
    ca.say(cb.name)

CB().callCA(CA())
# lance say ...
```

**Or**
can i disable this error in this case?

**Comment by spindensity** [comment]
Do not try to redefine class CB, use forward references instead, see [PEP 484 Forward references](https://www.python.org/dev/peps/pep-0484/#forward-references).

Here's the fix:

```python
class CA:
    def ma(self, cb: "CB"):
        fa(self, cb)

    def say(self, name: str):
        print(name + " say ...")


class CB:
    def __init__(self) -> None:
        self.name = "lance"

    def callCA(self, ca: CA):
        ca.ma(self)


def fa(ca: CA, cb: CB):
    ca.say(cb.name)


CB().callCA(CA())
```

**Comment by flyingcodes** [comment]
> Do not try to redefine class CB, use forward references instead, see [PEP 484 Forward references](https://www.python.org/dev/peps/pep-0484/#forward-references).


thanks very much
