### ISSUE TITLE
Warn about deprecated types

### ISSUE THREAD

**Issue by rpmrmartin** [microsoft/pyright#3598]
**Is your feature request related to a problem? Please describe.**
From the `typing` module's [documentation](https://docs.python.org/3/library/typing.html#module-contents):

> This module defines several types that are subclasses of pre-existing standard library classes which also extend [Generic](https://docs.python.org/3/library/typing.html#typing.Generic) to support type variables inside []. These types became redundant in Python 3.9 when the corresponding pre-existing classes were enhanced to support [].
> The redundant types are deprecated as of Python 3.9 but no deprecation warnings will be issued by the interpreter. It is expected that type checkers will flag the deprecated types when the checked program targets Python 3.9 or newer.

Pyright does not issue any warnings when using the deprecated types and targeting Python 3.10

**Describe the solution you'd like**
I would like Pyright to issue a warning when deprecated types such as `typing.List` are used and Python >=3.9 is targeted.

**Comment by rpmrmartin** [comment]
The `typing` classes will be going away in the first release after October 5, 2025 (5 years after Python 3.9 was released): https://docs.python.org/3/library/typing.html#module-contents.

**Comment by erictraut** [comment]
I'll bring this up for discussion with the pylance team. Maybe we'll come to a different conclusion than last time. Nearly a year has passed, and Python 3.10 adoption is quite a bit higher at this point.

**Comment by erictraut** [comment]
2025 is the earliest these types could go away. I doubt if that will happen though. There's too much code in the wild that uses these types. It would be incredibly disruptive to remove support that soon.

**Comment by erictraut** [comment]
We have a couple of options for surfacing this functionality:
1. Add a new user-configurable diagnostic rule ("reportDeprecated"). We'd probably want to default it to "none" if typeCheckingMode is "off", "warning" if typeCheckingMode is set to "basic", and "error" if typeCheckingMode is "strict"
2. Emit a deprecated "hint" so the editors like VS Code display the deprecated symbol with a crossed-out style. This would be a more subtle approach and would be consistent with how deprecated symbols are reported in TypeScript. It wouldn't be user-configurable, and it wouldn't emit any diagnostics in CLI mode or if the client indicates that it doesn't support the deprecated hint. 
3. We could do both of the above (although we'd probably start with just one and add the other later).

Here's an example of how VS Code displays a deprecated hint:
![Screen Shot 2022-06-21 at 1 45 28 PM](https://user-images.githubusercontent.com/7040122/174894249-38a0e956-a1b9-4904-8b0f-facdd6614854.png)

If you needed to choose between option 1 and 2, which would you prefer?

**Comment by JelleZijlstra** [comment]
> The `typing` classes will be going away in the first release after October 5, 2025 (5 years after Python 3.9 was released): https://docs.python.org/3/library/typing.html#module-contents.

Probably not. https://discuss.python.org/t/concern-about-pep-585-removals/15901

**Comment by rpmrmartin** [comment]
> If you needed to choose between option 1 and 2, which would you prefer?

If I had to choose, I would prefer option 1 so that CI pipelines could report on the deprecated types.

**Comment by erictraut** [comment]
I discussed this with the pylance team. We've decided that Python 3.10 has not yet gained wide enough adoption for this feature to make sense at this time. We'll consider it again in a year. By then, 3.10 will have likely become the dominant version of Python, and 3.11 will have started to gain some adoption as well.

In the meantime, there are linters like flake8 that will flag the usage of these older classes.

**Comment by erictraut** [comment]
It has been more than a year since we revisited this issue. I think it's time to add the requested support. It would still be pretty noisy to enable it by default (even in strict mode), so I've decided to add a new option `deprecateTypingAliases` that is currently "false" by default but can be set to "true" in the pyright config file. This will be included in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.325, which I just published. It will also be included in an upcoming pylance release.
