### ISSUE TITLE
Support keyword argument renaming

### ISSUE THREAD

**Issue by deliseev** [microsoft/pyright#360]
If you try to rename the key argument in the function definition or when calling the function it will not lead to any results.

Before rename:
<img width="402" alt="Screenshot 2019-11-25 at 16 13 02" src="https://user-images.githubusercontent.com/623664/69535863-9fe42580-0f9e-11ea-99b1-f45972f17a54.png">

After:
<img width="382" alt="Screenshot 2019-11-25 at 16 13 15" src="https://user-images.githubusercontent.com/623664/69535904-bbe7c700-0f9e-11ea-933c-afd4a770d346.png">

Expected:
<img width="342" alt="Screenshot 2019-11-25 at 16 13 34" src="https://user-images.githubusercontent.com/623664/69535926-c5712f00-0f9e-11ea-8780-b80ee37a9e06.png">

Thanks!

**Comment by erictraut** [comment]
Thanks for the suggestion. This functionality will be in the next published version of pyright.

**Comment by erictraut** [comment]
Thanks again for the suggestion. In addition to implementing rename, I also implemented hover, definition and reference support for named arguments. This is implemented in 1.1.6, which I just published.
