### ISSUE TITLE
Pyright unexpectedly complains about incompatible types even after narrowing.

### ISSUE THREAD

**Issue by GoogleGenius** [microsoft/pyright#3600]
**Describe the bug**
Pyright adds an additional `builtins.type` type to the annotation of a parameter which consists of a `Union` of various `Type[]`s. I am not exactly sure why this happens, if you could explain, that would be greatly appreciated.
```python
(parameter) option_type: Type[PartialChannel] | Type[str] | Type[bool] | Type[int] | Type[float] | Type[Role] | Type[User] | Type[Mentionable] | type
```
Then, when attempting to narrow the type, VSCode Pylance doesn't highlight any errors while the command-line Pyright throws an error.

**To Reproduce**
Trying to mitigate the added `builtins.type` type in the `Union` in order to correctly match the types to the `type` parameter in returning a `ClassCommandOption` class, I have added an if statement to narrow the type annotation and remove the extra `builtins.type` type that Pyright had added. 
```python
if option_type not in OPTIONS_TYPE_MAP:
    raise TypeError(f"`{option_type}` is not a valid option type")
```
**_(Note that I added a `# pyright: ignore` comment in the code attached, removing it produces the issue as you would expect, explained later below)._**

In VSCode with Pylance it appears like this when hovering over the `type` parameter of the class, which seems to have no type issues:
```python
(parameter) option_type: Type[PartialChannel] | Type[str] | Type[bool] | Type[int] | Type[float] | Type[Role] | Type[User] | Type[Mentionable]
```
However, running on the command-line returns an error:
```txt
C:\Users\_\Documents\_\GitHub\hikari-crescent\crescent\commands\options.py
  C:\Users\_\Documents\_\GitHub\hikari-crescent\crescent\commands\options.py:331:14 - error: Argument of type "Type[PartialChannel] | Type[str] | Type[bool] | Type[int] | Type[float] | Type[Role] | Type[User] | Type[Mentionable] | type" cannot be assigned to parameter "__k" of type "Type[str] | Type[bool] | Type[int] | Type[float] | Type[PartialChannel] | Type[Role] | Type[User] | Type[Mentionable]" in function "__getitem__"
    Type "Type[PartialChannel] | Type[str] | Type[bool] | Type[int] | Type[float] | Type[Role] | Type[User] | Type[Mentionable] | type" cannot be assigned to type "Type[str] | Type[bool] | Type[int] | Type[float] | Type[PartialChannel] | Type[Role] | Type[User] | Type[Mentionable]"
      Type "type" cannot be assigned to type "Type[str] | Type[bool] | Type[int] | Type[float] | Type[PartialChannel] | Type[Role] | Type[User] | Type[Mentionable]"
        Type "type" cannot be assigned to type "Type[str]"
        Type "type" cannot be assigned to type "Type[bool]"
        Type "type" cannot be assigned to type "Type[int]"
        Type "type" cannot be assigned to type "Type[float]"
        Type "type" cannot be assigned to type "Type[PartialChannel]"
        Type "type" cannot be assigned to type "Type[Role]" (reportGeneralTypeIssues)
```

**Expected behavior**
Pyright should not complain about incompatible types. Also, the extension and command-line should work the same.

**Screenshots or Code**
- [The entire file](https://github.com/GoogleGenius/hikari-crescent/blob/68a3533f46f6c6c818913a074552d37a50991d0f/crescent/commands/options.py)
- [The particular lines](https://github.com/GoogleGenius/hikari-crescent/blob/68a3533f46f6c6c818913a074552d37a50991d0f/crescent/commands/options.py#L325-L331)

**VS Code extension or command-line**
Both the Pylance extension `v2022.6.21 Pre-Release` and command-line interface `1.1.255`. 

**Additional context**
- Strict mode enabled
- Python 3.7 mode enabled
- Everything for settings can be found in the pyproject.toml file of the repo I linked actually.

**Comment by erictraut** [comment]
Could you please produce a self-contained minimal sample that exhibits the problem?

**Comment by GoogleGenius** [comment]
> Could you please produce a self-contained minimal sample that exhibits the problem?

Here is a simplified example:
```python
from __future__ import annotations
from dataclasses import dataclass
from enum import IntEnum
from inspect import isclass
from typing import Any, Generic, Sequence, TypeVar, Union

T = TypeVar("T")


class RandomType:
    pass


class AnotherType:
    pass


@dataclass
class ImplWithOption(Generic[T]):
    type: OptionTypesT


class OptionType(IntEnum):
    STRING = 1
    BOOLEAN = 2
    INTEGER = 3
    FLOAT = 4


OptionTypesT = Union[str, bool, int, float, AnotherType]


OPTIONS_TYPE_MAP: dict[type[OptionTypesT], OptionType] = {
    str: OptionType.STRING,
    bool: OptionType.BOOLEAN,
    int: OptionType.INTEGER,
    float: OptionType.FLOAT,
    AnotherType: OptionType.STRING,
}


def option(
    option_type: type[OptionTypesT] | Sequence[type[AnotherType]],
) -> ImplWithOption[Any]:
    if (
        isclass(option_type)
        and issubclass(option_type, AnotherType)
        and option_type is not AnotherType
    ):
        option_type = AnotherType
    elif isinstance(option_type, Sequence):
        option_type = AnotherType

    if option_type not in OPTIONS_TYPE_MAP:
        raise TypeError(f"`{option_type}` is not a valid option type")

    return ImplWithOption(
        type=OPTIONS_TYPE_MAP[option_type],
    )
```
```
C:\Users\_\Documents\_\Programming\Pyright bug minimal example\pyright_bug.py
  C:\Users\_\Documents\_\Programming\Pyright bug minimal example\pyright_bug.py:58:14 - error: Argument of type "Type[AnotherType] | Type[str] | Type[bool] | Type[int] | Type[float] | type" cannot be assigned to parameter "__k" of type "Type[str] | Type[bool] | Type[int] | Type[float] | Type[AnotherType]" in function "__getitem__"
    Type "Type[AnotherType] | Type[str] | Type[bool] | Type[int] | Type[float] | type" cannot be assigned to type "Type[str] | Type[bool] | Type[int] | Type[float] | Type[AnotherType]"    
      Type "type" cannot be assigned to type "Type[str] | Type[bool] | Type[int] | Type[float] | Type[AnotherType]"
        Type "type" cannot be assigned to type "Type[str]"
        Type "type" cannot be assigned to type "Type[bool]"
        Type "type" cannot be assigned to type "Type[int]"
        Type "type" cannot be assigned to type "Type[float]"
        Type "type" cannot be assigned to type "Type[AnotherType]" (reportGeneralTypeIssues)
```

**Comment by erictraut** [comment]
Thanks for providing the sample.

I'm not able to repro the error as reported. I don't receive any error with the above code. I've configured pyright 1.1.255 to use strict mode and Python 3.7. 

I'm guessing that the error corresponds to the expression `OPTIONS_TYPE_MAP[option_type]`? (In the sample, that's line 56, but the error message indicates line 58, so I'm not 100% sure if that's the right location.)

Do you have any other non-default configuration settings in pythonconfig.json? Perhaps you're using a custom set of typeshed stubs?

Any other ideas about what might be different between your configuration and mine? Perhaps you could try creating a fresh virtual environment and workspace to see if you can still repro it.

**Comment by GoogleGenius** [comment]
> Any other ideas about what might be different between your configuration and mine? Perhaps you could try creating a fresh virtual environment and workspace to see if you can still repro it.

And this was the problem :)

Apparently, there was something wrong with my Python installation, my actual version was `3.10.4` but the launcher was running at `3.10.2`. 

Reran pyright and it's resolved. Thank you so much!

**Comment by GoogleGenius** [comment]
If I may ask one more question, do you know why Pyright adds the `builtins.type` to the type signature? I don't quite understand that.

**Comment by erictraut** [comment]
I wasn't able to repro that behavior. I'm also not sure what point in the code flow you are referring to. Was it after the `if` / `elif` statement? The type of a symbol will change based on type narrowing logic applied for assignments and type guards.

The type of `options_type` after the `if`/`elif` statement is the union of the narrowed types for the `if`, the `elif` and the (implied) `else` branches. The narrowing logic for one of those must have added a `type`.

**Comment by GoogleGenius** [comment]
I think it might have been for the check where `isclass` was used which added the extra `builtins.type`. Is there any alternative in this case?

**Comment by erictraut** [comment]
Are you still seeing an unexpected behavior, or is it working as you expect at this point? I thought you concluded that the problem you were previously seeing was due to some issue with your Python installation.

**Comment by GoogleGenius** [comment]
Yes, everything works fine, I was just wondering whether there was a way to avoid the extra check later to narrow the types back to the original due to the `isclass`, otherwise, it's all good 👍
