### ISSUE TITLE
Marketplace id does not match extension manifest

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/pyright#3604]
Hi there 👋!

**Describe the bug**
The extension's `name` part of the extension ID in [package.json](https://github.com/microsoft/pyright/blob/1d0abc2411eb5347f362871c50d0a75e14030a75/packages/vscode-pyright/package.json?rgh-link-date=2022-06-22T06%3A08%3A13Z#L2) does **not** match the `name` in the Microsoft Marketplace [[1](https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright)]. 

The full ID in the manifest is `ms-pyright.vscode-pyright` while it is published under `ms-pyright.pyright`.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots or Code**
N/A

**VS Code extension or command-line**
Extension (`main` branch)

**Additional context**
I wonder how you guys publish the extension under a different ID than in `package.json`, because I assume it must be rewritten before it is released?

If I were to build the extension from sources, does that mean I can install the Marketplace version and the locally-built one at once? I haven't tried but I think that can be treated as a bug.

**Comment by erictraut** [comment]
What is the problem you're reporting here? Are you seeing an incorrect behavior in some regard?

**Comment by erictraut** [comment]
Ah, I understand your question. Yes, the package name is modified temporarily as part of our build scripts. See `renamePackage.js` for details. We needed to do this because the package that includes the command-line version of pyright already had the name "pyright".

**Comment by filiptronicek** [comment]
Thanks for the quick response, @erictraut! I'll take a look.
