### ISSUE TITLE
In case of overloading `__eq__` **in a dataclass**, pyright assumes it always returns `bool`

### ISSUE THREAD

**Issue by mmohaveri** [microsoft/pyright#3621]
**Describe the bug**
If you try to overload `==` operator by redefining `__eq__` **in a dataclass**, pyright will not respect its return type hint and assumes it's returning bool. It **only** happens for `__eq__`. `!=` operator (`__ne__`) will follow the type hint.

**To Reproduce**
```python
@dataclass
class Data(object):
    def __eq__(self, other: object, /) -> str:
        return "string"

    def __ne__(self, other: "Data| bool", /) -> str:
        return "string"


A = Data()

a1 = (A == False)
a2 = (A == A)

reveal_type(a1)  # bool
reveal_type(a2)  # bool

a3 = (A != False)
a4 = (A != A)

reveal_type(a3)  # str
reveal_type(a4)  # str
```

**Expected behavior**
As we're overloading the operator (on the top of dataclass overloading the default one), I expect pyright to respect the __eq__ type hint.

**Screenshots or Code**
![1](https://user-images.githubusercontent.com/6017468/175930636-70c8de76-0965-4eba-87f6-dd188b627daa.png)

**VS Code extension or command-line**
The issue appears in both CLI and VS Code. version 1.1.255

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.256, which I just published. It will also be included in the next release of pylance.
