### ISSUE TITLE
Pyright loses type information of Literals with Generic TypedDicts

### ISSUE THREAD

**Issue by NCPlayz** [microsoft/pyright#3624]
**Describe the bug**
See code below. Seems like Pyright discards the type information of the value of `r` too early when typed for a Generic TypedDict.
It could be that I've misunderstood how Generic TypedDicts are intended to be used.

**Expected behavior**
Should be exactly the same as `TestAll`.

**Actual behavior**
```py
- 20:15 - error: Expression of type "dict[str, int]" cannot be assigned to declared type "TestAll2"
-   Type "dict[str, int]" cannot be assigned to type "TestAll2"
-     "dict[str, int]" is incompatible with "TestGeneric[Literal[1]]"
-     "dict[str, int]" is incompatible with "TestGeneric[Literal[2]]"
```

**Screenshots or Code**
```py
from typing import TypeVar, Union, Literal, Generic, TypedDict

T = TypeVar('T')
class Test(TypedDict):
    r: Literal[1]


class Test2(TypedDict):
    r: Literal[2]


TestAll = Union[Test, Test2]

t: TestAll = {"r": 1}

class TestGeneric(TypedDict, Generic[T]):
    r: T

TestAll2 = Union[TestGeneric[Literal[1]], TestGeneric[Literal[2]]]

t2: TestAll2 = {"r": 1} # will error
```

**VS Code extension or command-line**
VS Code Extension: Pylance `v2022.6.30`
Also on CLI: Pyright `v1.1.255`

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.256, which I just published. It will also be included in the next release of pylance.
