### ISSUE TITLE
Conditional TypedDict over bool 

### ISSUE THREAD

**Issue by NCPlayz** [microsoft/pyright#3625]
**Describe the bug**
Seems like trying to use a boolean value to have conditional TypedDict values does not work as intended, as Pyright seems to eagerly simplify the type into `bool` even though the keys may differ depending on the value. 

**To Reproduce**
See code.

**Expected behavior**
I expected Pyright to narrow down the type of `payload` to Parent. This effect can be achieved by using `str` / `int` Literals but not with `bool`.

**Screenshots or Code**
```py
from typing import List, Literal, TypedDict, Union


class BasePayload(TypedDict):
    id: int
    name: str


class Parent(BasePayload):
    is_parent: Literal[True]
    children: List[BasePayload]


class Orphan(BasePayload):
    is_parent: Literal[False]


Payload = Union[Parent, Orphan]


def parse(payload: Payload):
    reveal_type(payload["is_parent"]) # -> bool
    if payload["is_parent"]:
        reveal_type(payload) # -> Parent | Orphan
```

**VS Code extension or command-line**
VS Code: Pylance `v2022.6.30`

**Comment by erictraut** [comment]
It is working as intended. Pyright doesn't provide narrowing for the pattern you are using. For a complete list of supported type narrowing patterns, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards).

Each new type narrowing pattern requires custom logic and potentially adds overhead to type analysis. We occasionally add support for new patterns, but only if we have evidence that it's a commonly-used pattern. This is the first time I've ever seen this pattern used, and no pyright users have requested support for this previously. Unless and until we get additional signal that it is more broadly needed, we probably won't implement this.

You could use a user-defined type guard function.

```python
def is_parent(v: Payload) -> TypeGuard[Parent]:
    return v["is_parent"]

def parse(payload: Payload):
    if is_parent(payload):
        reveal_type(payload)
```

**Comment by erictraut** [comment]
Pyright also supports the narrowing pattern that discriminates between typed dicts based on `==` or `!=` comparisons.

So this works:
```python
def parse(payload: Payload):
    if payload["is_parent"] == False:
        reveal_type(payload) # Orphan
    else:
        reveal_type(payload) # Parent
```
