### ISSUE TITLE
Pyright exits with error code 1

### ISSUE THREAD

**Issue by diblaze** [microsoft/pyright#3627]
**Describe the bug**
When running Pyright, no output is produced and Pyright exits with error code 1.

**To Reproduce**
1. run Pyright

**Expected behavior**
It has worked before, but suddenly Pyright does not produce any output, and always exits with error code 1.
Reinstalled Pyright with Poetry, reinstalled language server and Pyright in VS Code.
Nothing helped.

**Comment by erictraut** [comment]
I presume you're installing the command-line version of pyright. Are you installing it through the [community-maintained Python wrapper](https://pypi.org/project/pyright/)? Or are you installing it using npm?

Which version do you have installed? If you run `pyright --version`, what does it print?

Which version did you previously have installed when it worked?

Which version of node do you have installed? If you run `node --version`, what does it print?

**Comment by erictraut** [comment]
Can you run `pyright --version` or `pyright --help`? Or does it crash when running those simple commands?

When you say `--verbose` does not work, what do you mean? Does it crash before you receive any output?

If you revert back to version 1.1.247, does it work again? If I understand you correctly, it stopped working while 1.1.247 was installed, and then you tried to update it. If that's correct, then it's not the updated version that caused the problem.

We haven't received any other reports of problems, so I'm guessing that there's something corrupt or misconfigured on your system.

**Comment by erictraut** [comment]
Sounds like it might be a problem with node. Perhaps uninstall and reinstall it.

**Comment by diblaze** [comment]
@RobertCraigie thank you! 
These flags helped me finding the issue. Apparently the my auth token for my private NPM repository has been invalidated  and I needed a new one.
Sadly Pyright did not tell me this without these flags.

These flags should be documented somewhere, and if they are, then maybe make them easier to find. 
Also Pyright should output errors regardless which process it is running.
```
Running node command with args: ['/home/xkvblad/.nvm/versions/node/v16.13.2/bin/npx', '--yes', 'pyright@1.1.255']
npm ERR! code E401
npm ERR! Incorrect or missing password.
```

**Comment by RobertCraigie** [comment]
> These flags should be documented somewhere, and if they are, then maybe make them easier to find.

These flags are documented here: https://github.com/RobertCraigie/pyright-python#configuration, do you have any suggestions as to how to make them easier to find?

> Also Pyright should output errors regardless which process it is running.

Yeah it is unfortunate that this didn't output anything. I think I misunderstood what `--silent` does and we should instead be using either `--quiet` or `--loglevel=error` instead according to https://docs.npmjs.com/cli/v8/using-npm/logging.
