### ISSUE TITLE
Incorrect type detection for partial when function has TypeVar and overloads

### ISSUE THREAD

**Issue by last-partizan** [microsoft/pyright#3640]
This is continuation of https://github.com/microsoft/pyright/issues/3614

I tried using that variant, and it works, except for cases when using it with partial.

**To Reproduce**
Copy provided example.

**Expected behavior**
After using `partial` type signature should be correct. (`partial[T@convert_number]`).

**Screenshots or Code**
```python
from decimal import Decimal
from functools import partial
from typing import Any, TypeVar, overload

T = TypeVar("T")


@overload
def convert_number(v: object) -> int: ...

@overload
def convert_number(v: object, t: type[T]) -> T: ...

def convert_number(v: object, t: type = int) -> Any:
    return t(v)


convert_decimal = partial(convert_number, type=Decimal)

v_ok = convert_number(1, Decimal)
reveal_type(v_ok)

v_fail = convert_decimal(1)
reveal_type(v_fail)
```

```
  /tmp/overloads.py:20:13 - information: Type of "convert_decimal" is "partial[int]"
  /tmp/overloads.py:23:13 - information: Type of "v_ok" is "Decimal"
  /tmp/overloads.py:26:13 - information: Type of "v_fail" is "int"
```

**VS Code extension or command-line**
- pyright 1.1.256

**Additional context**

It works fine without overloads and default value:

```python
from decimal import Decimal
from functools import partial
from typing import TypeVar

T = TypeVar("T")


def convert_number(v: object, t: type[T]) -> T:
    return t(v)


convert_decimal = partial(convert_number, t=Decimal)
reveal_type(convert_decimal)

v_ok = convert_number(1, Decimal)
reveal_type(v_ok)

v_fail = convert_decimal(1)
reveal_type(v_fail)
```

```
  /tmp/overloads.py:14:13 - information: Type of "convert_decimal" is "partial[T@convert_number]"
  /tmp/overloads.py:17:13 - information: Type of "v_ok" is "Decimal"
  /tmp/overloads.py:20:13 - information: Type of "v_fail" is "Decimal"
```

**Comment by erictraut** [comment]
Pyright contains special-case handling for partial, but this handling doesn't extend to overloads.

Mypy has the same limitation.

We might consider adding this support at some time in the future if we get sufficient signal from users that it's commonly request (e.g. in the form of thumbs-up reactions within this issue), but for now I'm going to close it as "as designed".
