### ISSUE TITLE
Incorrectly assigns a more specific type when using Any

### ISSUE THREAD

**Issue by YodaEmbedding** [microsoft/pyright#3643]
**Describe the bug**
Dictionary is incorrectly assigned the type `dict[str, int]` instead of `dict[str, Any]` when constructed with values of type `int` and `Any`.

**To Reproduce**
```python
from typing import Any

def f() -> Any:
    return None

d = dict(a=1, b=f())
d["c"] = "three"
```

Last line produces the error:
> `Argument of type "Literal['three']" cannot be assigned to parameter "__v" of type "int" in function "__setitem__"   "Literal['three']" is incompatible with "int"`

**Expected behavior**
`d` should be of type `dict[str, Any]`.

**Screenshots or Code**
See above.

**VS Code extension or command-line**
Neovim LSP.

**Additional context**
N/A.

**Comment by erictraut** [comment]
This behavior is intended.

Pyright's TypeVar constraint solver favors non-Any types over Any types. The `dict` constructor is an overloaded method, but the overload that applies in this case is:
```python
    def __init__(self: dict[str, _VT], **kwargs: _VT) -> None: ...
```

The constraint solver is solving `_VT` as `int` in this case, which is a valid solution.

If you want `d` to be `dict[str, Any]`, you have several options.

1. Use a dictionary expression: `d = {"a":1, "b":f()}`
2. Use a type declaration: `d: dict[str, Any] = ...`
