### ISSUE TITLE
enable preserveConstEnums

### ISSUE THREAD

**Issue by Zzzen** [microsoft/pyright#3648]
**Is your feature request related to a problem? Please describe.**
I am using the compiler API of pyright to the AST. But I can't do a reverse mapping on `nodeType` property. Because `ParseNodeType` is declared as const enum.  The only solution is to manually copy it out. 

source code: https://github.com/Zzzen/pyright-ast-viewer/blob/b8bf5b2d7589ad14984f9f0b0d7c8b71af2acdb1/src/compiler/api.ts#L20
website: https://zzzen.github.io/pyright-ast-viewer/

**Describe the solution you'd like**
It will be great if we can enable `preserveConstEnums` like [typescript](https://github.com/microsoft/TypeScript/blob/c6ff5f3b52d45842e5e56caf124cf5f5521c92ff/src/tsconfig-base.json#L25).

**Comment by erictraut** [comment]
We use const enums as a performance optimization in pyright. Disabling this will slow down analysis times for all users. I don't think that's a good tradeoff to enable your use case. If you want to do a reverse map for your particular use case, you can create a function that does so.

**Comment by Zzzen** [comment]
https://www.typescriptlang.org/tsconfig#preserveConstEnums

It's not going to hurt the performance of runtime. The number literal will still be inlined.

**Comment by erictraut** [comment]
Actually, there's already a function that provides the reverse mapping: parseTreeUtils.printParseNodeType. Please use this.

**Comment by Zzzen** [comment]
Cool, thanks!
