### ISSUE TITLE
TypeVar Error when referring to a subclass of a generic subclass of a generic TypedDict 

### ISSUE THREAD

**Issue by NCPlayz** [microsoft/pyright#3673]
**Describe the bug**
Seem to get an error when trying to use a class that subclasses a subclass of a generic TypedDict (and provide an explicit type for the TypeVar). Does not happen when a subclass of a generic TypedDict with an explicit type (`TD6`), or if the generic subclass (`TD7`) is used.
```py
Argument of type "dict[str, int | str]" cannot be assigned to parameter "a" of type "TD8" in function "func6"
  Type "Literal[1]" is not assignable to field "x"
    Type "Literal[1]" cannot be assigned to type "_T1@TD7"
  Type "Literal[1]" is not assignable to field "y"
    Type "Literal[1]" cannot be assigned to type "_T1@TD7"
```

**To Reproduce**
See code.

**Expected behavior**
I would think the tests for `TD7` would match `TD8`.

**Screenshots or Code**
Following from [`tests/samples/typedDict18.py`](https://github.com/microsoft/pyright/blob/67927318a0934befa2b47479763ae41d224f46b2/packages/pyright-internal/src/tests/samples/typedDict18.py):
```py
class TD6(TD5[Literal[1]]):
    z: str


def func4(a: TD6) -> Literal[1]:
    ...


func4({"x": 1, "y": 1, "z": "a"})
f2: TD6 = {"x": 1, "y": 1, "z": "a"}

reveal_type(func4({"x": 1, "y": 1, "z": "a"}))


class TD7(TD5[_T1], Generic[_T1]):
    z: str


def func5(a: TD7[Literal[1]]) -> Literal[1]:
    return a["x"]


func5({"x": 1, "y": 1, "z": "a"})
f3: TD7[Literal[1]] = {"x": 1, "y": 1, "z": "a"}

reveal_type(func5({"x": 1, "y": 1, "z": "a"}))


class TD8(TD7[Literal[1]]):
    ...

# errors from this point onwards
def func6(a: TD8) -> Literal[1]:
    return a["x"]


func6({"x": 1, "y": 1, "z": "a"})
f4: TD8 = {"x": 1, "y": 1, "z": "a"}

reveal_type(func6({"x": 1, "y": 1, "z": "a"}))
```

**VS Code extension or command-line**
VS Code extension: Pyright `v1.1.527`

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.258, which I just published. It will also be included in the next release of pylance.
