### ISSUE TITLE
Type incompatibility on Union type when both variables must be of same type 

### ISSUE THREAD

**Issue by thomasaarholt** [microsoft/pyright#3674]
**Describe the bug**

Sorry if this became a long post for a relatively straightforward issue. I thought I'd start with a "real-world" example, and then move on to a dummy example, since the dummy one might be dismissed as "why would you want to do that"?

### Real-life example
In the dataframe library [polars](https://github.com/pola-rs/polars) (similar to pandas) a dataframe can either be a `DataFrame` or a `LazyFrame`, with mostly similar methods. The following is a function that would add a "count" column that counts the number of instances of each `some_id`:

```python
import polars as pl
df = pl.DataFrame({"some_id": [1, 1, 1, 2, 2], "other_column": [1, 2, 3, 4, 5]})

def count(df: pl.DataFrame | pl.LazyFrame):
    # df_groupby is of the same type as `df`
    df_groupby = df.groupby(by="some_id").agg(pl.col("some_id").count().alias("count"))
    return df.join(other=df_groupby, on="some_id")
    #                    ^^^^^^^^^^ pyright warning is here
```

With pyright's basic type checking mode on, I get the following warning:
```
(variable) df_groupby: DataFrame | LazyFrame[Unknown]

Argument of type "DataFrame | LazyFrame[Unknown]" cannot be assigned to parameter "other" of type "DataFrame" in function "join"
  Type "DataFrame | LazyFrame[Unknown]" cannot be assigned to type "DataFrame"
    "LazyFrame[Unknown]" is incompatible with "DataFrame"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)

Argument of type "DataFrame | LazyFrame[Unknown]" cannot be assigned to parameter "other" of type "LazyFrame[Unknown]" in function "join"
  Type "DataFrame | LazyFrame[Unknown]" cannot be assigned to type "LazyFrame[Unknown]"
    "DataFrame" is incompatible with "LazyFrame[Unknown]"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

I would expect that pyright would be ok with this, since the type of `df` will always match `df_groupby`. mypy does not raise a warning.

### Minimal example
In the following function `foo(C: A|B)`, `C` can either be of type `A` or `B`. Both classes have the method `func`.
Calling the method on itself raises a warning, despite that the types will always match.

```python
class A:
    def func(self, foo: "A"):
        ...

class B:
    def func(self, foo: "B"):
        ...

def foo(C: A|B):
    C.func(foo=C)
    #          ^ pyright warning here
```

Shortening the pyright warnings a little:
1. `Argument of type "A | B" cannot be assigned to parameter "foo" of type "A" in function "func"`
2. `Argument of type "A | B" cannot be assigned to parameter "foo" of type "B" in function "func"`

Here the type of the method owner is EITHER `A`, in which case `foo` is a method of `A`, and thus an argument of type `A` should be allowed, OR `B`, in which case `foo` is a method of `B`, and thus an argument of type `B` should be allowed. 

**VS Code extension or command-line**
Running VSCode 1.68.1

**Comment by thomasaarholt** [comment]
Thank you for such a quick and detailed explanation! I'm impressed!

Your explanation makes sense, and I agree that this isn't worth all that work.
I was unaware of protocol classes, thanks for introducing them to me.

For anyone in the future coming to this issue, the MyProto class should inherit from Protocol:

```python
from typing import Protocol
from typing_extensions import Self

class MyProto(Protocol):
    def func(self, foo: Self): ...
```

Good explanations here: https://mypy.readthedocs.io/en/stable/protocols.html

**Comment by erictraut** [comment]
Good catch. I've updated my sample above to fix this bug.
