### ISSUE TITLE
No completions directly after `.`

### ISSUE THREAD

**Issue by jakebailey** [microsoft/pyright#369]
**Describe the bug**

Completions only appear after at least a single character has been typed after `.`.

**To Reproduce**

Try to complete something immediately after the `.`.

**Expected behavior**

The completion list shows the members of what I typed.

**Screenshots or Code**

![image](https://user-images.githubusercontent.com/5341706/69751889-d936a580-1104-11ea-824e-3e2051d7137a.png)

![image](https://user-images.githubusercontent.com/5341706/69751968-084d1700-1105-11ea-90fc-242c09aa1b00.png)

![image](https://user-images.githubusercontent.com/5341706/69751960-01be9f80-1105-11ea-858f-559ccfde81cc.png)

![image](https://user-images.githubusercontent.com/5341706/69751976-0e42f800-1105-11ea-81c9-81323343cf13.png)

**VS Code extension or command-line**

VS Code

**Additional context**

Could be some fallout from fixing #347.

**Comment by erictraut** [comment]
Thanks for the bug report. Yes, this was fallout from another recent fix. I need to get some unit tests in place for the completion provider so regressions like this don't go undetected.

Here's a quick fix for this problem:
https://github.com/microsoft/pyright/commit/c52ed3517aaa05f4e7d2e11d8de5841460e9456a

**Comment by erictraut** [comment]
This is now fixed in 1.1.7, which I just published.
