### ISSUE TITLE
Automatically add type annotations

### ISSUE THREAD

**Issue by withzombies** [microsoft/pyright#37]
It would be nice if pyright could add type annotations to existing code bases when it can properly deduce the variable/argument types.

**Comment by erictraut** [comment]
Thanks for the suggestion. It's something I've thought of doing, but there are a bunch of other higher-priority items ahead of it.

**Comment by erictraut** [comment]
After thinking about this more, I think it's beyond the scope of pyright to add annotations. It already supports smart type inference where possible, and this eliminates the need for explicit annotations in most cases. The one notable exception is annotations for function/method input parameters. These still need to be manually specified. I don't see a good way to automatically generate these in a way that wouldn't be error prone.
