### ISSUE TITLE
Don't report `Unnecessary "# pyright: ignore" rule` in unreachable code

### ISSUE THREAD

**Issue by Avasam** [microsoft/pyright#3711]
**Is your feature request related to a problem? Please describe.**
I have some platform-specific code that requires the use of `# pyright: ignore`. But when linting on another platform, I get an error saying `Unnecessary "# pyright: ignore" rule` because Pyright also correctly identify the code as unreachable. I cannot simply remove the comment since then linting will fail on the targeted platform.

**Describe the solution you'd like**
Don't report `Unnecessary "# pyright: ignore" rule` in unreachable code (or code that isn't linted anyway).

**Additional context**
Here's a visual example using Pylance:

![image](https://user-images.githubusercontent.com/1350584/179341226-fbf9528f-a521-4f5d-b65c-5bfbfc76de4e.png)
![image](https://user-images.githubusercontent.com/1350584/179341454-09e9c8c5-8cea-4eed-ba74-2ef4093e24dd.png)

**Comment by erictraut** [comment]
This will be included in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.261, which I just published. It will also be included in an upcoming release of pylance.
