### ISSUE TITLE
Bound TypeVar resolved as unknown when used in Union

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#3714]
**Describe the bug**
When using a bound TypeVar as the return type and as part of the input arguments in a union, pyright (and mypy) cannot resolve the return type when the function is called with an un-annotated object.

**To Reproduce**
```py
from __future__ import annotations

from typing import (
    TypeVar,
    overload,
)

class A:
    ...

AT = TypeVar("AT", bound=A)

def short(x: AT | str) -> AT:
    ...

@overload
def verbose(x: str) -> A:
    ...

@overload
def verbose(x: AT) -> AT:
    ...

def verbose(x: AT | str) -> AT:
    ...

def test(a: str | A):
    reveal_type(short(a))  # A
    reveal_type(verbose(a))  # A

def test2(a):
    reveal_type(short(a))  # Unknown
    reveal_type(verbose(a))  # A
```

**Expected behavior**
`short(a)` in `test2` is in all cases a TypeVar bound by A, so it should be possible to infer A as the return type.

**Comment by erictraut** [comment]
This is intended behavior. `Unknown` is an implied `Any`. In the case of `short` above, the TypeVar `AT` is being "solved" with `Unknown`, so the return type is `Unknown`.

**Comment by erictraut** [comment]
The correct way to handle this is to provide a type annotation for parameter `a` in `test2`.
