### ISSUE TITLE
add method to a class

### ISSUE THREAD

**Issue by tshemeng** [microsoft/pyright#372]
I want to add method to a class `Cell`
```python
def new_method(self,arg):
    pass

Cell.new_method = new_method
```
```
Cannot access member 'new_method' for type 'Cell'\n  Member 'new_method' is unknown
```
any way to fix this ?

**Comment by erictraut** [comment]
While this type of hackery is possible in a dynamic language like Python, it's fragile and goes against the philosophy of static type checking. 

If you must do this, you can cast away the type, effectively telling the type checker "I know better, so disable your type checking in this case".

```
cast(Any, Cell).new_method = new_method
```
