### ISSUE TITLE
Regression with chained comparisons

### ISSUE THREAD

**Issue by lovetox** [microsoft/pyright#3738]
Chained comparisons fail

**To Reproduce**
```python
a = '1'
b = '1'
x = a == b == '1'
```

This fails with `Condition will always evaluate to False since the types "Literal['1']" and "bool" have no overlap ​Pyright: reportUnnecessaryComparison`

This expression evaluates to True.

**Additional context**
This fails very recently so either it was introduced with 263 or 262.

**Comment by erictraut** [comment]
Thanks for the bug report. This was a long-standing bug that happened to be exposed by a different change I recently made. It will be fixed in the next release.

**Comment by erictraut** [comment]
This is fixed in pyright 1.1.264, which I just published. It will also be included in a future release of pylance.
