### ISSUE TITLE
support for packages installed in development mode

### ISSUE THREAD

**Issue by cshesse** [microsoft/pyright#374]
**Is your feature request related to a problem? Please describe.**

Right now it looks like if a virtual env is active, `pyright` will run `python -c "import sys, json; json.dump(sys.path, sys.stdout)"` to get the search path, which includes python packages installed in development mode, e.g. `pip install -e`.

It would be nice if this was also the case for specifying `venvPath` and `venv`.  Right now there's a noticeable difference in behavior between activating a virtualenv and using `venvPath` + `venv` in that the latter does not seem to support development mode packages.

**Describe the solution you'd like**

It looks like this is implemented with `.pth` files: https://docs.python.org/3/library/site.html

Here's the description of the format:

> A path configuration file is a file whose name has the form name.pth and exists in one of the four directories mentioned above; its contents are additional items (one per line) to be added to sys.path. Non-existing items are never added to sys.path, and no check is made that the item refers to a directory rather than a file. No item is added to sys.path more than once. Blank lines and lines beginning with # are skipped. Lines starting with import (followed by space or tab) are executed.

1) If a `site-packages` directory is found, process each file matching "*.pth" in that directory.
2) For each line in that file (except for blank lines and lines starting with "#") add the path to the python search paths.

**Comment by cshesse** [comment]
The main reason I noticed this is that I am trying to use only the pyright VSCode extension rather than both that one and the Python one since I'm never certain what behavior is from pyright and what is from the Python extension.

**Comment by cshesse** [comment]
I can give this a try in a PR if it's likely to be accepted.

**Comment by erictraut** [comment]
Thanks for the offer, but I'm still thinking about the right approach — or whether this is something we should support. 

The technique that pyright uses today to look for imports is already quite complicated and somewhat fragile. Calling the locally-installed python interpreter to ask it for its sys.path is used as a last resort only if all other techniques fail. I was hesitant to add this technique in the first place, and I'm very uncomfortable combining it with others.

This also relates to a request for pyright to support ".env" files as a way to specify search paths. If I add that support, it will further complicate the situation.

I've reached out to one of my colleagues who is responsible for the Microsoft Python Language Service (MPLS). I think he has experience with this, and I'd like to understand his perspective. I probably won't hear back from him until next week though.

**Comment by cshesse** [comment]
Makes sense, complicated and fragile path logic will just result in more complaints later.

One point of clarification though, if I understand the current setup correctly, this would be a change to `findPythonSearchPaths` and not `getPythonPathFromPythonInterpreter`, so it wouldn't be directly combining with the python path from interpreter thing.

**Comment by erictraut** [comment]
Ah, you're correct. I misunderstood your proposal. That eliminates some of my concerns then.

What do ".pth" files have to do with development mode? From what I've read, they could apply to any package regardless of how it's installed. I couldn't find any mention of "development mode" in the docs you reference above.

**Comment by cshesse** [comment]
From my tests, if I do `pip install -e <package>` in order to have a package installed in my virtual environment (actually a conda environment) and still be able to edit the files, it will add an entry to `c:\tools\miniconda3\envs\<venv name>\lib\site-packages\easy-install.pth`.

Removing that entry prevents `import <package>` from working in a python shell, so this seems to be where it's getting the import path from.

However, the last part of the description of a `.pth` file is `Lines starting with import (followed by space or tab) are executed.`  While that doesn't matter for `easy-install.pth`, there are some crazy google `.pth` files installed on my machine that totally do that, so maybe using `.pth` files is just going to be a bad time.

**Comment by cshesse** [comment]
So the reason I originally had this problem was that I wanted to use only `pyright` exclusively, but I currently need to be running the Python VSCode extension because it lets me set the currently active virtual environment.

Alternatively, if I could disable all features of the Python VSCode extension which overlap with `pyright`, that would also solve my issue.  Is that possible currently?

**Comment by erictraut** [comment]
I submitted a PR for the Python VS Code extension that allows you to disable the other features that overlap with pyright. The team responsible for the Python VS Code extension is working on testing and integrating my PR, and I hope that it will be in their next monthly release.

**Comment by cshesse** [comment]
Fantastic, thanks!  Since I am thinking now that the only way to get the actual python path is to run a python interpreter, I'll close this issue.  Thanks again for your help!
