### ISSUE TITLE
Error: Debug Failure. createKeyForReference received unexpected expression type #3695

### ISSUE THREAD

**Issue by rjurdi98** [microsoft/pyright#3743]
"An internal error occurred while binding file \"c:\\Users\\rteljurdi\\Desktop\\tb_api\\para_models.py\": Error: Debug Failure. createKeyForReference received unexpected index type\n    at createKeyForReference (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\codeFlowTypes.ts:237:13)\n    at createKeyForReference (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\codeFlowTypes.ts:218:25)\n    at C.visitAssignment (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:849:50)\n    at C.visitNode (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:132:29)\n    at C.walk (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:98:37)\n    at forEach (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:107:22)\n    at Array.forEach (<anonymous>)\n    at C.walkMultiple (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:105:15)\n    at C.walk (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:100:18)\n    at C._walkStatementsAndReportUnreachable (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:2583:22)\n    at C.visitSuite (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:345:14)\n    at C.visitNode (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:330:29)\n    at C.walk (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:98:37)\n    at callback (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:1290:22)\n    at C._trackCodeFlowExpressions (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:3236:9)\n    at C.visitIf (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:1265:48)\n    at C.visitNode (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:184:29)\n    at C.walk (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:98:37)\n    at C._walkStatementsAndReportUnreachable (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:2583:22)\n    at C.visitSuite (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:345:14)\n    at C.visitNode (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:330:29)\n    at C.walk (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:98:37)\n    at Object.callback (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:545:22)\n    at C._bindDeferred (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:4140:22)\n    at C.bindModule (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:298:14)\n    at callback (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\sourceFile.ts:1197:28)\n    at s.timeOperation (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\common\\timing.ts:44:28)\n    at callback (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\sourceFile.ts:1184:38)\n    at t.LogTracker.log (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\common\\logTracker.ts:43:20)\n    at t.SourceFile.bind (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\sourceFile.ts:1181:33)\n    at O._bindFile (c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\program.ts:931:34)\n    at c:\\Users\\rteljurdi\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\program.ts:1051:18"

**Comment by erictraut** [comment]
Which version of pyright are you using? This is a bug that was fixed several versions ago. Please upgrade to the latest version and see if you can repro. If so, we'll need to narrow down the repro case.

**Comment by rjurdi98** [comment]
I was using an older version, I ended up updating to the new pre-release version which fixed the issue. Thank you for your help!
