### ISSUE TITLE
Type-narrowing seems too aggresive in some cases

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pyright#3749]
Self-contained sample:
```python
from typing import Mapping

d0: Mapping[str, object] = {"a": 0}
# Type of `d0` is narrowed as "dict[str, int]".

d1 = dict(d0)
# Type of `d1` is inferred as "dict[str, int]".

d1.update("b", "")
# Type mismatch between `str` and `int`.
```

Practical sample:
```python
from flask import Flask
from werkzeug.routing import BaseConverter

app = Flask(__name__)

class MyConverter(BaseConverter):
    pass

app.url_map.converters["some_type"] = MyConverter
```

Some relating snippets from "werkzeug/routing.py":
![image](https://user-images.githubusercontent.com/15389744/181222350-2dc86ea8-db1a-4fa7-929a-562fe687d140.png)

![image](https://user-images.githubusercontent.com/15389744/181222687-9538035a-3c30-4273-b8db-586106f41862.png)

![image](https://user-images.githubusercontent.com/15389744/181222858-3bb34e45-1e65-4a65-a3af-0a16f2e78dcc.png)

Result is the same when line #1497 is modified into `self.converters = dict(self.default_converters)`.

**Comment by erictraut** [comment]
In your example, I presume that you intended the last line to be `d1.update(b="")`?

The type inference and narrowing rules are working as designed in this example. If your intent is for the constructed `dict` to accept `str` values in addition to `int` values, you would need to provide a type declaration for `d1`:

```python
d1: dict[str, int | str] = dict(d0)
```

**Comment by Azureblade3808** [comment]
Yes. It wouldn't be a problem if the code were in my project. But the real problematic code exists in the library "werkzeug" and I don't think it'll be easy to convince its maintainer that declaring
```python
DEFAULT_CONVERTERS: t.Mapping[str, t.Type[BaseConverter]] = dict(...)
```
is not enough to make typings right.

What is confusing me is that if a value is used purely in the scope it's been declared, its declared type will be almost useless. To make the declared types work, I may sometimes write code like
```python
DEFAULT_CONVERTERS: t.Mapping[str, t.Type[BaseConverter]] = cast("t.Any", dict(...))
```
or
```python
def build_default_converters() -> t.Mapping[str, t.Type[BaseConverter]]:
    return dict(...)

DEFAULT_CONVERTERS: t.Mapping[str, t.Type[BaseConverter]] = build_default_converters()
```
. The first pattern is not type-safe and the second pattern is just too verbose.
