### ISSUE TITLE
Error on EllipsisType 

### ISSUE THREAD

**Issue by mbergal** [microsoft/pyright#3760]
**Describe the bug**

This used to work
```
EllipsisType = type(...)

def a(d:EllipsisType): 
   pass
```

Now reports 
```
error: Illegal type annotation: variable not allowed unless it is a type alias (reportGeneralTypeIssues)
```

**Comment by erictraut** [comment]
Yes, this was a bug in previous versions of pyright that has since been fixed.

In this sample, `EllipsisType` is not a valid type alias; it's a simple variable, and variables cannot be used as a type annotation.

**Comment by mbergal** [comment]
So what is correct way to define `EllipsisType` for python < 3.10?

**Comment by erictraut** [comment]
I don't know of a good way to define `EllipsisType` for Python < 3.10. The class was exposed in 3.10 to address this shortcoming.

I guess you could use the following, but it's less than ideal.

```python
EllipsisType = Any
```
