### ISSUE TITLE
`--verifytypes` is flagging missing docstrings for property setters and overloads

### ISSUE THREAD

**Issue by thesadru** [microsoft/pyright#3787]
In some older versions `--verifytypes` often ignored missing docstrings in properties. Now warnings are being given for both getters, setters, and even overloads.

I am unsure when this behavior changed, I haven't used `--verbose` with `--verifytypes` for a long time.

**Comment by erictraut** [comment]
What is the behavior you expect here? Do you want `--verifytypes` to warn when properties are missing docstrings? Or you want it to ignore this omission? Note that missing docstrings are flagged as warnings, not errors. You can ignore them if you want.

**Comment by thesadru** [comment]
I expected only property getters to require docstrings. I don't think pylance ever shows setter docstrings anyways. I don't see what the point of adding docstrings to overloads would do either.

**Comment by erictraut** [comment]
This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.266, which I just published.
