### ISSUE TITLE
Leaking code helper processes

### ISSUE THREAD

**Issue by koliyo** [Microsoft/pyright#38]
I find pyright processes consuming 100% CPU. And even if I exit VS Code the processes are still running

```
49856   ??  R     32:25.19 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/silok/.vscode/extensions/ms-pyright.pyright-1.0.4/server/server.js --node-ipc --clientProcessId=49675
```

**Comment by erictraut** [comment]
Thanks for the bug report. Which version of pyright were you running when you saw this? There was a bug in versions prior to 1.0.4 that would have resulted in this behavior. I'm not aware of any causes in 1.0.4 or newer.

**Comment by erictraut** [comment]
In version 1.0.6 (just published), I added even more resiliency to protect against this case. Please let me know if you ever see this again.
