### ISSUE TITLE
Use Nx + Nx Cloud to speed up your Lerna 5 setup

### ISSUE THREAD

**Issue by juristr** [microsoft/pyright#3804]
**Is your feature request related to a problem? Please describe.**

Hey, I'm Juri, a core team member of [Nx](https://nx.dev) and [Lerna](https://lerna.js.org). I saw you [did upgrade to Lerna v5](https://github.com/microsoft/pyright/pull/3783) recently. Lerna v5 allows for an easy opt-into speeding up your workspace by enabling Nx as a task scheduler instead of `p-queue`.

**Describe the solution you'd like**

There's more [on this Lerna doc](https://lerna.js.org/docs/lerna-and-nx), but basically, it is along the lines of

- `npm install nx -D`
- set `useNx` to `true` in the `lerna.json`

That enables faster task scheduling and computation caching, which speeds up the workspace overall. Given this is an open source project it can also enable unlimited distributed caching with Nx Cloud. 

Let me if that sounds interesting. I can help in case 😃

**Additional context**

**Comment by erictraut** [comment]
No thanks.
