### ISSUE TITLE
Add the possibility to declare an import prefix

### ISSUE THREAD

**Issue by milouse** [microsoft/pyright#3805]
**Is your feature request related to a problem? Please describe.**

I’m currently working with a big python application. Each team work on a specific part of the codebase, which are in fact submodules of the big application itself (by submodule, I’m not necessarily refering to git submodule, but just from a code architecture point of view). Thus in each team repository, any import from whatever other piece of code always looks like

```python
import big_app.submodule.feature1.stuff
from big_app.submodule.feature2 import thing
```

However we don’t necessarily have access to the big_app repository and only work at the submodule level.

I don’t find any other way to work around that, and thus currently I got a lot of:

```
/path/to/projects/submodule/models/website.py
  /path/to/projects/submodule/models/website.py:2:6 - error: Import "big_app.submodule.utils.commons" could not be resolved (reportMissingImports)  
```
`big_app.submodule.utils.commons` being declared in `/path/to/projects/submodule/utils/commons.py` and `/path/to/projects/submodule` being the root of the repository, with pyright config file (among others).

**Describe the solution you'd like**

It could be great to add a new general configuration key, or a per execution environment one, to define an import prefix to explain that all import beginning by this prefix should be understood as starting from the project root.

For exemple:

```json
{
    …
    "importPrefix": [
        {"prefix": "big_app.submodule", "root": "/path/to/your/repo"},
        {"prefix": "big_app.submodule2", "root": "/path/to/your/repo2"}
        …
    ],
    …
}
```

Or maybe, by playing with the `executionEnvironments` key:

```json
{
    …
    "executionEnvironments": [
        {
            "root": ".",
            "pythonVersion": "3.0",
            "importPrefix": "big_app.submodule"
        },
        …
    ],
    …
}
```

**Additional context**
N/A

**Comment by erictraut** [comment]
Is each team member expected to locally clone all of the repos from the other teams?

Are you able to run your team's code locally (e.g. under the control of a debugger), or is it possible to run it only within the context of the larger app (e.g. once all of the submodules are integrated within a container or VM)? If you are able to run it locally, how does the Python interpreter know about the other teams' submodules and resolve them at runtime?

**Comment by milouse** [comment]
The big app is never run directly locally, but always inside some virtualization layer (docker, virtualbox, chroot…) which are provided by another mean and which we never have to deal with. Our local dev repository are mounted inside those environments at runtime.

It is not possible to run the code from each of our repo individually, we need to test it as part of the big app, through our virtualized environments.

Not all developer are required to clone all team repos, but very often, they clone every repo they use as dependency of their own code. We tried to use the `extraPath` settings, but again, it lacks the possibility of associate an extra path with a specific import prefix. Like:

```json
{
    …
    "extraPath": [
        "/path/to/another/piece/of/code/external/lib",  <-- no need for a prefix for that lib, used as this
        {"root": "/path/to/another/feature/to/prefix", "prefix": "big_app.feature2"}
    ]
}
```

That’s why I think (but I’m open to discussion, that’s the goal of a feature request :) ) my first proposition with the new `importPrefix` key is good, as it can support every use case, without modifying the way `extraPath` currently work.

**Comment by erictraut** [comment]
Thanks for the additional information. Yes, I can see how your suggested feature would help you with your particular use case. However, this seems like a very atypical arrangement, and we generally don't add new features unless we think that they will be more generally useful to some subset of pyright users.

Let's explore other potential workarounds that require a new feature specific to your use case. Perhaps you could use placeholder directories and symbolic links to point to the other locally-cloned dependent repos?

Would it make sense to auto-generate type stubs for the parts of the app and then check in these stubs as placeholders for other teams to use as a development-time "stand in" for the other subcomponents? For example, if feature1 depends on feature2, you could have type stubs for feature2's public interface checked in, and the team responsible for feature1 could then code against this interface.

**Comment by milouse** [comment]
Thank you very much for your answers. I totally understand the need to not spread effort in any direction only for one or two use cases. In any case, your answers were very valuable and I must admit we didn’t think about symbolic link. We successfully find a solution for our need through "proxy" folder construct and symbolic links and it fits perfectly with our need. So thanks again for your time !
