### ISSUE TITLE
Calling `assert_never()` with zero argument should trigger type error

### ISSUE THREAD

**Issue by MapleCCC** [microsoft/pyright#3807]
**Describe the bug**
Pyright doesn't emit error when `assert_never()` is called with zero argument.

With general type theory jargon, `assert_never()` function has type `void -> Any`. And the type of a zero-argument function is `unit -> Any`. These two types seem to be distinct.

Environment: Pyright command-line 1.1.266.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is fixed in pyright 1.1.267, which I just published. It will also be included in a future version of pylance.

**Comment by MapleCCC** [comment]
Thanks for the quick fix, Eric! I try the latest published release, and the static type behavior of `assert_never()` works properly now! :tada:
