### ISSUE TITLE
Treat any number of "_"s as the same as "_"

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#3811]
**Is your feature request related to a problem? Please describe.**
I'd like to see `__` (etc) treated the same as `_` etc.
```py
        def not_implemented(fn: Callable) -> None:
            @functools.wraps(fn)
            async def wrapped(*_, **__) -> Never:
#                                   ^^  Type of parameter "__" is unknownPylance[reportUnknownParameterType]
                raise NotImplementedError()

            setattr(cls, function.__name__, wrapped)
```
You also get an error also when you don't use a `__` variable.

**Describe the solution you'd like**
Ideally this error would disappear as would using `___` etc.

**Comment by erictraut** [comment]
There is a convention in Python for treating `_` as "I don't care about this value", but I'm not aware of any convention that extends this to multiple underscores.

I'm going to close this for now, but I would consider re-opening it in the future if there is sufficient interest from other pyright users (as indicated by thumbs-up reactions).

**Comment by Gobot1234** [comment]
I was reminded that there are cases where conventionally you can't reassign to `_` like with [gettext.gettext](https://docs.python.org/3/library/gettext.html#gettext.gettext), so you'd have to use something like `__` if you wanted to make it clear (at least to me) that the value is unused.

**Comment by jack1142** [comment]
More generally, I've also seen unused variables just being prefixed with `_` (to still be able to denote the meaning of the argument) or prefixed with something like `unused_` though I wouldn't call the latter a popular convention.

Here are `pylint`'s default unused variables and ignored argument names patterns in case that's helpful:
https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#dummy-variables-rgx
https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#ignored-argument-names

**Comment by erictraut** [comment]
This situation is a little different than unused variable detection. This is specifically related to "unknown type" detection. The `reportUnknownParameterType` is a strict-mode check, so I think it's OK for it to be a bit more opinionated than other checks. There's a simple and obvious workaround in this case — add an `Any` type annotation to the parameters.

```python
        def not_implemented(fn: Callable) -> None:
            @functools.wraps(fn)
            async def wrapped(*_: Any, **__: Any) -> Never:
                raise NotImplementedError()

            setattr(cls, function.__name__, wrapped)
```
