### ISSUE TITLE
Import 'orjson' could not be resolved

### ISSUE THREAD

**Issue by victoraugustolls** [microsoft/pyright#382]
**Describe the bug**
When using pyright extension in VSCode, importing `orjson` package gives me an error: "Import 'orjson' could not be resolved".
When I disable pyright, autocomplete works perfectly for `orjson`.

**To Reproduce**
Install python for vscode and pyright extensions.
pip install orjson
import orjson

**Expected behavior**
Expected pyright to find the module as Python for VSCode finds.

**Screenshots**
Without pyright:
![image](https://user-images.githubusercontent.com/7843637/69920373-fa312a80-1465-11ea-880c-01eda05371f8.png)

With pyright:
![image](https://user-images.githubusercontent.com/7843637/69920367-e71e5a80-1465-11ea-88a5-19e975ca9961.png)

**VS Code extension or command-line**
VS Code, version 1.1.7

**Comment by erictraut** [comment]
Pyright needs to know how you've configured your python environment (which python interpreter you're using, whether you're using a virtual environment, whether there are any custom import resolution paths configured, etc.). There are multiple ways of doing this. Please follow the instructions in the pyright documentation. https://github.com/microsoft/pyright/blob/master/docs/import-resolution.md

**Comment by victoraugustolls** [comment]
As by the docs, my pyright seems to be configured correctly. Orjson only has a `.so` file, could this be the reason? If so, what would be the right way to point pyright to the stub file that I made?

**Comment by erictraut** [comment]
Ah yes, pyright doesn't know how to import ".so" files. If the package doesn't come with its own type stub file, you can create your own. Create a directory called "typings" within your workspace. Within that directory, create a subdirectory called "orjson". Then place your `__init__.pyi` stub file within this. If you'd prefer to name the directory something other than "typings", you can configure it in pyrightconfig.json.

**Comment by victoraugustolls** [comment]
Created as follows:

![image](https://user-images.githubusercontent.com/7843637/69921017-2a2ffc00-146d-11ea-99e7-32ca65b21146.png)

Still the same error:

![image](https://user-images.githubusercontent.com/7843637/69921024-42a01680-146d-11ea-892d-b3472abd729a.png)

**Comment by victoraugustolls** [comment]
`__init__.pyi` for reference:

![image](https://user-images.githubusercontent.com/7843637/69921044-6d8a6a80-146d-11ea-9d09-5abcf6fb83ed.png)

**Comment by victoraugustolls** [comment]
Fixed after unchecking this box:

![image](https://user-images.githubusercontent.com/7843637/69923494-117f1080-1484-11ea-9a43-d4d603dbba16.png)

**Comment by erictraut** [comment]
Hmm, this setting shouldn't affect the behavior in this case. It should always prefer a type stub if one is present. I'm going to reopen and investigate it further.

**Comment by erictraut** [comment]
I've investigated further, and it looks like it's working as expected. Re-closing the bug.
