### ISSUE TITLE
Pattern matching not working when matching directly on a tagged union's tagged member

### ISSUE THREAD

**Issue by bryanforbes** [microsoft/pyright#3826]
**Describe the bug**
Given the following code:

```python
from __future__ import annotations

from typing import Literal, TypedDict
from typing_extensions import reveal_type


class One(TypedDict):
    a: Literal['one']
    b: str


class Two(TypedDict):
    a: Literal['two']
    b: int


Things = One | Two


def blah(things: One | Two) -> None:
    match things['a']:
        case 'one':
            reveal_type(things['b'])  # str | int
        case 'two':
            reveal_type(things['b'])  # str | int

    match things:
        case {'a': 'one', 'b': b}:
            reveal_type(b)  # str
        case {'a': 'two', 'b': b}:
            reveal_type(b)  # int

    if things['a'] == 'one':
        reveal_type(things['b'])  # str
    elif things['a'] == 'two':
        reveal_type(things['b'])  # int
```

The revealed types at lines 23 and 25 do not match the revealed types at lines 34 and 36. I've demonstrated this with `TypedDict`, but it happens with `NamedTuple` and classes.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
The revealed type at line 23 should match line 34 and line 25 should match line 36.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool?
Command line

Which version?
1.1.266

**Comment by erictraut** [comment]
This is currently working as designed. Type narrowing for target expression `things['a']` in a match statement narrows the type of expression `things['a']`, but it doesn't narrow the type of expression `things`. This could theoretically be added, but it would be a new capability. We do occasionally add support for new type narrowing patterns, but we do so only when there's signal that it's a commonly-used pattern.

Mypy also does not handle this case.

I'm going to close this for now, but we may reconsider it in the future if there's additional signal from pyright users (in the form of upvotes).
