### ISSUE TITLE
pyright cannot be used without internet connection

### ISSUE THREAD

**Issue by dan-bar-dov** [microsoft/pyright#3831]
Once pyright is installed, it should be usable without internet connection.
The documentation does not specify environment variables that *possibly* make this possible.

**Comment by erictraut** [comment]
You do not need connectivity to run pyright. Are you using the [community-maintained Python wrapper for pyright](https://github.com/RobertCraigie/pyright-python)? if so, it might require connectivity to check for new versions of pyright. You would need to check with the maintainers of that wrapper.

**Comment by RobertCraigie** [comment]
@dan-bar-dov Please see this issue for tracking support for offline usage: https://github.com/RobertCraigie/pyright-python/issues/2
