### ISSUE TITLE
Should sub-classes be allowed to return wider types in overloads?

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#3849]
**Describe the bug**
Mypy and pyright behave differently in the following example. Mypy's behavior seems more intuitive but pyright's behavior can also make sense as those wider return types are only returned in cases where the parent class doesn't accept those input arguments.

**To Reproduce**

```py
# pyright: strict

from datetime import timedelta
from typing import overload

import numpy as np
import numpy.typing as npt

class Timedelta(timedelta):
    @overload
    def __floordiv__(self, other: timedelta) -> int: ...
    @overload
    def __floordiv__(self, other: int) -> Timedelta: ...
    @overload
    def __floordiv__(
        self, other: npt.NDArray[np.timedelta64]
    ) -> npt.NDArray[np.intp]: ...
```

**Expected behavior**
Same behavior across mypy and pyright

mypy:

```
test.pyi:10: error: Signature of "__floordiv__" incompatible with supertype "timedelta"  [override]
test.pyi:10: note:      Superclass:
test.pyi:10: note:          @overload
test.pyi:10: note:          def __floordiv__(self, timedelta) -> int
test.pyi:10: note:          @overload
test.pyi:10: note:          def __floordiv__(self, int) -> timedelta
test.pyi:10: note:      Subclass:
test.pyi:10: note:          @overload
test.pyi:10: note:          def __floordiv__(self, timedelta) -> int
test.pyi:10: note:          @overload
test.pyi:10: note:          def __floordiv__(self, int) -> Timedelta
test.pyi:10: note:          @overload
test.pyi:10: note:          def __floordiv__(self, ndarray[Any, dtype[timedelta64]]) -> ndarray[Any, dtype[signedinteger[Any]]]
test.pyi:10: note: Overloaded operator methods can't have wider argument types in overrides
```

pyright: everything fine

**Additional context**
Found that when trying to enable pyright's `reportUnnecessaryTypeIgnoreComment` and mypy's `warn_unused_ignores`.

**Comment by erictraut** [comment]
This isn't a check that pyright performs currently. We could add it in the future if there is sufficient demand. This is the first time someone has requested it, and my intuition is that this is not a common source of bugs, so I'm inclined to not implement this additional check at this time. We might reconsider in the future if we get enough customer signal.
