### ISSUE TITLE
`@type_check_only` decorator is not observed in stubs when importing symbols

### ISSUE THREAD

**Issue by karolyi** [microsoft/pyright#3850]
**Is your feature request related to a problem? Please describe.**
Hey,

the typing module has a [convenience definition](https://peps.python.org/pep-0484/#the-typing-module) called `@type_check_only`, a decorator only available during type checking for use in stub files (see above); marks a class or function as unavailable during runtime. With using this decorator, pyright still offers the marked symbol in the stub file for importing, although it doesn't exist in the runtime, it's just a type helper. An example use case is [here](https://github.com/django-money/django-money/pull/686/files), the PR I created for django-money.

**Describe the solution you'd like**
Symbols marked with `@type_check_only` shouldn't be offered for importing in runtime modules.

**Additional context**
Using the stub defined above, I get the following symbol list when importing (`_FormatOptions` shouldn't be there):
![image](https://user-images.githubusercontent.com/987055/185757516-dcbe498d-21dc-4e6a-a995-3bc6ddb0b4ca.png)

**Comment by erictraut** [comment]
The `@type_check_only` decorator never gained adoption. If we see it used more broadly, it might make sense to add support for it in the type checker logic and reflect this knowledge to the higher-layer language service features. 

This is the first time I've seen this decorator used, and you're the first person who has requested such a capability. So for now, I don't think we will implement support for it. We will consider adding support in the future if we receive sufficient signal (e.g. in the form of upvotes).

**Comment by karolyi** [comment]
Thanks. Have my upvote on my own feature request. :)

**Comment by erictraut** [comment]
Typeshed appears to be starting to use the `@type_check_only` decorator. For that reason, I think it's worth considering adding some level of support for it in pyright as you suggest. I'll need to think about what exactly that means in terms of generating diagnostics and how it might affect language server features like completion suggestions.

**Comment by erictraut** [comment]
I investigated this further. Unfortunately, we won't be able to use `@type_check_only` as a way to filter the list of completion suggestions within a `from A import X` statement. When the pyright's completion provider computes the list of symbols to return in the context of an import statement, it does not have access to the evaluated types of the symbols. Evaluating the types of all symbols in the target module would be cost prohibitive on this code path. Users expect completion suggestions to appear very quickly, and pyright is designed to avoid evaluating types unless and until it is absolutely required. Determining whether a symbol is a class or function with a `@typing.type_check_only` decorator requires the type evaluation of that symbol.

**Comment by karolyi** [comment]
Is there not an easy way just to check for "what's the line before"?

**Comment by erictraut** [comment]
It's never that easy. The line before might be `@type_check_only` or `@typing.type_check_only` or some aliased version of these. Plus, there could be multiple decorators stacked on top of each other.

**Comment by karolyi** [comment]
`@type_check_only` shouldn't normally use other decorators imo... I'm not in the position to tell you what to do but you could also tie the ignoring of showing the import symbol when using the exact `@type_check_only` form ahead of the line.

**Comment by erictraut** [comment]
I can say from experience that telling users that we support `@type_check_only` but not other forms or aliases will create a bunch of noise and support issues for us, so I'm not willing to do that.
