### ISSUE TITLE
Make `True`/`False` literal compatible with protocol with `__bool__` method

### ISSUE THREAD

**Issue by MapleCCC** [microsoft/pyright#3856]
**Is your feature request related to a problem? Please describe.**
The property-based testing library Hypothesis provides a function [`assume()`](https://hypothesis.readthedocs.io/en/latest/details.html#making-assumptions) that behaves similar to `assert`, but is for filtering during test data generation. Its source code is rather simple:

```python
def assume(condition: object) -> bool:
    if not condition:
        raise UnsatisfiedAssumption()
    return True
```

The type annotation of `assume()` currently is not clear enough. It doesn't convey to the type checker that when the input argument is falsey, it raises instead of returns.

When I write unit tests with Hypothesis (please ignore most details, only the function return type is the concern here):

```python
from pathlib import Path
from hypothesis import assume
from hypothesis.strategies import DrawFn, composite, sampled_from

sample_files: list[Path]

@composite
def python_sources(draw: DrawFn) -> str:
    try:
        source = draw(sampled_from(sample_files)).read_text()
    except UnicodeDecodeError:
        assume(False)
    else:
        return source
```

Pyright complains that `Function with declared type of "str" must return value. Type "None" cannot be assigned to type "str"`.

I then try to make the type annotation of `assume()` more clear and useful/friendly, by leveraging `overload` and `Protocol`:

```python
from pathlib import Path
from typing import Literal, NoReturn, Protocol, overload
from hypothesis import assume as _assume
from hypothesis.strategies import DrawFn, composite, sampled_from

class Truthy(Protocol):
    def __bool__(self) -> Literal[True]: ...
class Falsy(Protocol):
    def __bool__(self) -> Literal[False]: ...

@overload
def assume(x: Truthy) -> Literal[True]: ...
@overload
def assume(x: Falsy) -> NoReturn: ...

def assume(x: object) -> bool:
    return _assume(x)

sample_files: list[Path]

@composite
def python_sources(draw: DrawFn) -> str:
    try:
        source = draw(sampled_from(sample_files)).read_text()
    except UnicodeDecodeError:
        assume(False)
    else:
        return source
```

However, Pyright complains that `Argument of type "Literal[False]" cannot be assigned to parameter "x" of type "Falsy" in function "assume"`.

**Describe the solution you'd like**
I think maybe it's natural to make `True`/`False` literals compatible with protocol with a `__bool__` method.

**Comment by erictraut** [comment]
The feature you're requesting would require some very hacky special-case logic. This might be justified for a commonly-used pattern, but I have a hard time imagining that the technique you're describing here would be used by anyone other than you.

I think you'll need to find some other workaround for the problem you're trying to solve.

**Comment by MapleCCC** [comment]
Thank you for the quick reply. I understand that it may be difficult to incorporate truthiness inference into type checker. I will try to look for other approaches then. Thank you anyway!
