### ISSUE TITLE
Trigger error if accessing attribute of X from an Optional[X]

### ISSUE THREAD

**Issue by giuscri** [microsoft/pyright#387]
**Is your feature request related to a problem? Please describe.**
pyright treats value of `Optional[X]` as value of type `X`. This is a problem: the programmer is not helped to prevent an `AttributeError` (that is here, a _null-pointer exception_).

**Describe the solution you'd like**
I'd like to have pyright trigger an error as I will surely face a runtime error.

One solution might be to consider `Optional[X]` as of type None, and force the programmer (to make pyright happy) to create a new variable of type `X`.

For example:
```
    def toDirection(x: str) -> Optional[Direction]:
        if x == "U":
            return Direction.UP
        elif x == "D":
            return Direction.DOWN
        elif x == "L":
            return Direction.LEFT
        elif x == "R":
            return Direction.RIGHT

        return None

    # toDirection("foo").RIGHT # this is *not* triggering an error! But it'll crash at runtime

    maybeDirection = toDirection("foo")
    if maybeDirection is None:
        ...
    else:
        direction = typing.cast(Direction, maybeDirection)
```

**Comment by erictraut** [comment]
Pyright is highly configurable. By default, it is very conservative in the errors it reports. This is one of those cases. You can enable more errors by enabling them in the pyrightconfig.json file. In this case, the configuration setting you want is called `reportOptionalMemberAccess`. You can either set it in the config file or add a comment at the top of the source file (`#pyright: reportOptionalMemberAccess=true`).

If you want all rules to be enabled, you can use enable `strict` mode for whole subdirectories or on a file-by-file basis (`# pyright: strict`). This allows you take an existing source code base and improve it over time.
