### ISSUE TITLE
Support matching `TypedDict` to complex recursive type alias-bound `TypeVar`s

### ISSUE THREAD

**Issue by Trimatix** [microsoft/pyright#3870]
**Is your feature request related to a problem? Please describe.**
Pyright appears to understand recursive type aliases correctly, but I've found an issue when bounding a type variable to a type alias _that makes use of_ a recursive type alias. I don't know if this is of consequence but, even more specifically, my concrete type is a TypeDict.

```python
RecursiveAlias = Union[str, Mapping[str, "RecursiveAlias"]]
SimpleAlias = Mapping[str, RecursiveAlias]
```

This is ok:
```python
myDict: SimpleAlias = {"hello": {"foo": "bar"}}
reveal_type(myDict) # dict[str, dict[str, str]]
```

And so is this:
```python
TSchema = TypeVar("TSchema", bound=RecursiveAlias)

class Parent(Generic[TSchema]):
    field: TSchema

class MySchema(TypedDict):
    name: str

class Child(Parent[MySchema]): ...

reveal_type(Child().field) # MySchema
```

But this is not ok:
```python
TSchema = TypeVar("TSchema", bound=SimpleAlias) # <-- Different bound

class Parent(Generic[TSchema]): ...

class MySchema(TypedDict):
    name: str

class Child(Parent[MySchema]): ... # Error on MySchema
```

This is the error:
```python
Type "MySchema" cannot be assigned to type variable "TSchema@Parent"
  Type "MySchema" is incompatible with bound type "SimpleAlias" for type variable "TSchema@Parent"
    TypeVar "_VT_co@Mapping" is covariant
      Type "object" cannot be assigned to type "RecursiveAlias"
        "object" is incompatible with "str"
        "object" is incompatible with "Mapping[str, RecursiveAlias]"
```

Here's the code in pyright playground so you can see the error: [playground](https://pyright-playground.decorator-factory.su/?gzip=H4sIANrZC2MC_1WQz4rDIBCH7z7F4MmA5AGEHpYt7KmwbLt7CWGxZroR_BPUFkLpu9fUJGy8qD--b4aZS_AW0jho9wfaDj4kOI0D_sjA4QMdBq34K-n2WiUOBzlMLIdvp70j5AvVNUR9wzejZYRdyZuYwsqWD92StG3JMTc0q7iht3BLiB2n_gK2zp32aIynIr8ufrrpWQb6eJCAN5TmN0-GrLgVIaej6tHKLM4zMjpHlMPZX123-1c_C8rIGOFTBnSJzetoZqWtBNR1vUCHscRsXVYlCOTjpEUBeaqFfO-16Vgp2izaUu0JV3KyyZABAAA%3D)

**Additional context**
The actual usage for this functionality is that I would like my classes to be generic in "schema" of their JSON-serialized form.

**Comment by erictraut** [comment]
This has nothing to do with recursive type aliases. It comes down to this simple type violation:

```python
y: MySchema = {"name": ""}
x: Mapping[str, str] = y # Type Error
```

The problem is that the value type of a TypedDict is `object`. It looks like you're assuming that it's a `str` here.

**Comment by Trimatix** [comment]
Ah I see! Many thanks :)

any readers with a similar problem, refer to [PEP-0589](https://peps.python.org/pep-0589/#type-consistency):
> A TypedDict isn’t consistent with any Dict[...] type, since dictionary types allow destructive operations, including clear(). They also allow arbitrary keys to be set, which would compromise type safety.
