### ISSUE TITLE
Type inference for Generator's return value

### ISSUE THREAD

**Issue by cbscsm** [microsoft/pyright#3873]
**Is your feature request related to a problem? Please describe.**

I know TypeScript has type inference for generator's last value.
```typescript
function foo(iter: Generator<number, string>): void {
    var curr = iter.next();
    while (!curr.done) {
        curr.value;  // number
        curr = iter.next();
    }
    curr.value;  // string
}
```

But I can't find type inference of return value from generator in Python.
```python
from collections.abc import Generator

def foo(it: Generator[int, None, str]):
    try:
        while True:
            reveal_type(next(it))  # int
    except StopIteration as exc:
        reveal_type(exc.value)  # Any, but str expected
```

I think that the type of `exc.value` should be `str`.

**Describe the solution you'd like**

I'm not sure, but could `StopIteration` be generic?
If `StopIteration[T]` implies that attribute `value` of it has type `T`,
`exc` in the above has `StopIteration[str]` and `exc.value`'s type is `str`.

For example, in `builtins.pyi`:
```python
_T = TypeVar('_T')

class StopIteration(Exception, Generic[_T]):
    value: _T
```

If there are multiple calling `next`s for multiple iterators, union type can be used.
```python
from collections.abc import Generator

def foo(it1: Generator[int, None, str], it2: Generator[int, None, bool]):
    try:
        while True:
            next(it1)
            next(it2)
    except StopIteration as exc:
        reveal_type(exc)  # Can be StopIteration[str | bool]
```

**Comment by erictraut** [comment]
The type of `StopIteration.value` is declared as `Any` in the typeshed stub `builtins.pyi`, so pyright is evaluating the type correctly here. The runtime behavior internal to the iterator cannot be reflected in the Python type system, so `Any` is probably the best that can be done here.

In any case, pyright is doing the right thing here from a type analysis standpoint, and there are no false positive errors produced here. Mypy evaluates the same type in this case. So I don't think there's anything to do here.
