### ISSUE TITLE
Completion doesn't work over some Django modules

### ISSUE THREAD

**Issue by megavenik** [microsoft/pyright#3874]
**Describe the bug**
I'm using `pyright` with vim through `coc` and `coc-pyright` and for some reason sometimes its suggestions work and sometimes don't.

**To Reproduce**
Try to work with Django's internals, like request object, nothing happens at all:

![image](https://user-images.githubusercontent.com/815281/187169091-f226f6d4-2a14-467b-92dd-968a215e9b03.png)

Or another case, with user-defined models, also nothing at all:

![image](https://user-images.githubusercontent.com/815281/187169318-abb856a1-6cc2-4b67-afff-7976fed47c09.png)

`title` suggestion expected to be here:

![image](https://user-images.githubusercontent.com/815281/187169341-e36764c1-c91e-4202-a7f7-6bc5cd5c2037.png)

**Expected behavior**
Suggestions working for `request` object and user-defined models.

**VS Code extension or command-line**
OS: MacOS 12.5, M1
Vim: 9.0.65
Python: 3.8.9 inside Pipenv shell
Django==2.2
[coc.nvim] coc-pyright 1.1.268 with Pyright 1.1.268

**Comment by erictraut** [comment]
Could you provide a self-contained minimal code snippet that exhibits the problem? It's difficult to debug from partial screen shots.

**Comment by megavenik** [comment]
@erictraut thanks for your answer! I've created a small repo with example - https://github.com/megavenik/pyright_debug/blob/main/polls/views.py#L6

Will it help you?

**Comment by erictraut** [comment]
I was able to clone your repo, but I'm not sure exactly what I'm looking at. There are a bunch of files. 

I think the main issue you're likely seeing is related to the fact that the django stubs define the type of `Model.objects` as `BaseManager[Any]`. The `Any` type argument obscures any further type analysis. The evaluated type of `all` in your example above is `Any`, which means there is no available completion suggestion.

I don't know much about django, so I recommend that you consult with others who have more experience with that library if you want advice here. From what I can see, pyright is correctly evaluating types given the type information provided to it, and it is correctly presenting completion suggestions based on those type evaluations.
