### ISSUE TITLE
`Unpack`ed `Callable` incompatible with lambda

### ISSUE THREAD

**Issue by colehaus** [microsoft/pyright#3878]
```py
from typing import Callable
from typing_extensions import Unpack

def foo(a: int, b: int) -> int:
    return a + b
w: Callable[[Unpack[tuple[int, int]]], int] = foo
x: Callable[[Unpack[tuple[int, int]]], int] = lambda a, b: a + b # Errors
y: Callable[[int, int], int] = foo
z: Callable[[int, int], int] = lambda a, b: a + b
```

Each of `w`, `y` and `z` type check. `x` does not. I would expect `x` to type check given than `w` and `z` do. The error given by pyright `1.1.268`  is:
```
error: Expression of type "(a: *tuple[int, int], b: Unknown) -> Unknown" cannot be assigned to declared type "(*tuple[int, int]) -> int"
    Type "(a: *tuple[int, int], b: Unknown) -> Unknown" cannot be assigned to type "(*tuple[int, int]) -> int"
      Parameter 1: type "int" cannot be assigned to type "*tuple[int, int]"
        "int" is incompatible with "*tuple[int, int]" (reportGeneralTypeIssues)
```

**Comment by erictraut** [comment]
Yes, the bidirectional type inference logic for lambda is not sophisticated enough to deal with unpacked tuples. This strikes me as a very odd usage, and it would require significant extra complex logic to support. We might consider this in the future if there's sufficient signal that it is needed by other users. In the meantime, you'll need to find a workaround.

**Comment by colehaus** [comment]
Okay, makes sense. For a little more context, the original use site was an attempt to type the precondition contract decorator [`deal.pre`](https://deal.readthedocs.io/basic/values.html#deal-pre):

```py
@deal.pre(lambda x, y: x > y)
def foo(x: int, y: int) -> int:
    return x + y
```
