### ISSUE TITLE
Please document pyright.disableLanguageServices

### ISSUE THREAD

**Issue by ex-nerd** [microsoft/pyright#390]
I see in #201 that `pyright.disableLanguageServices` was recently added, but it took a lot of searching to find out why was getting duplicate definitions.  Given that many people will be using pyright in conjunction with the main python extension, it would be really helpful to get a setup section dedicated setting them up together, either by setting `pyright.disableLanguageServices` or by whatever method is used to disable services in the python extension (I'm still digging through the docs to figure out what exactly that is).

**Comment by erictraut** [comment]
Thanks for the suggestion.

There is currently no way in the Python extension to disable the language service features. I [submitted a PR](https://github.com/microsoft/vscode-python/issues/7010) back in August, but it hasn't yet been integrated or released. It sounds like it's on track to getting rolled in and released in the next few months.

In the meantime, I agree that additional documentation can help here.

**Comment by erictraut** [comment]
I've updated the main README on the pyright site to include a section on this topic. Let me know if you have any further suggestions. Thanks!
