### ISSUE TITLE
Nested `TypedDict` with `NotRequired` key failing to satisfy key-existence check

### ISSUE THREAD

**Issue by hblanko** [microsoft/pyright#3900]
**Describe the bug**
When nesting a `TypeDict` inside another `TypeDict`, where the child one has a `NotRequired` key, Pyright keeps showing an error even after ensuring the existence of the key.

**To Reproduce**
The code snippet below reproduces the error using the specified version of Pylance extension in VSCode.

The second check fails with the error:
```
Could not access item in TypedDict
  "k" is not a required key in "A", so access may result in runtime exception
```

**Expected behavior**
Only the first check should fail, all the rest should pass.

**Screenshots or Code**
```python
from typing import Final, Literal, TypedDict

from typing_extensions import NotRequired


class A(TypedDict):
    k: NotRequired[int]


class B(TypedDict):
    a: A


b: B = B(a=A())

k: Final[Literal["k"]] = "k"


if b["a"][k] == 0:  # This properly shows an error
    ...


if k in b["a"] and b["a"][k] == 0:  # This shows an error but should pass
    ...


a: A = A()

if k in a and a[k] == 0:  # It also passes without the external TypedDict
    ...


a2: A = b["a"]

if k in a2 and a2[k] == 0:  # Assigning the nested TypedDict to a variable makes it pass too
    ...

```

**VS Code extension or command-line**
Pylance: v2022.8.50

**Additional context**
Python: 3.9.7

pyrightconfig.json:
```json
{
    "useLibraryCodeForTypes": true,
    "typeCheckingMode": "basic",
}
```

**Comment by erictraut** [comment]
Refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards) for supported type narrowing patterns.

Your code sample works as you expect if you use a string literal `"k"` rather than a variable `k` in the expression `k in b["a"]`. We intentionally do not support variables or other more complex expressions here for performance reasons. Is there a strong reason why you don't want to use a string literal here? IMO, it's just as readable and no more verbose.

**Comment by hblanko** [comment]
I understand your point for this given example, and I actually realized about the fact that using literal works as I expected.

However, I still think there are good reasons to support this behavior (which is the actual reason I posted this minimized example).

Consider the following snippet, where I add another `NotRequired` key to the child `TypedDict` class.

```python
from typing import Literal, Optional, TypedDict

from typing_extensions import NotRequired


class A(TypedDict):
    k: NotRequired[int]
    q: NotRequired[int]


class B(TypedDict):
    a: A


b: B = B(a=A())


def check_any_dict_key(b: B, key: Literal["k", "q"], value: int) -> Optional[bool]:
    if key in b["a"]:
        return b["a"][key] == value  # not passing since `key` is not a literal but a variable

    return None

```

To me, this is a legit use case (still a simplified case though). But I'd appreciate if you'd show me wrong :).

**Comment by erictraut** [comment]
As I said, we might consider extending support for this in the future if we receive sufficient signal that it's a common use case (e.g. in the form of thumbs-up reactions in this issue).

Adding such support has its downsides in that it will have a performance impact on general type analysis. We need to weigh the tradeoffs when adding new capabilities like this.

**Comment by hblanko** [comment]
Perfect, I can understand that point. I simply wanted to clarify on the second part of your argument, about potential use cases where the literal solution is just not an option.
