### ISSUE TITLE
feat(configuration): goToDefinition options

### ISSUE THREAD

**Issue by aarnphm** [microsoft/pyright#3908]
**Is your feature request related to a problem? Please describe.**
Given a stubs Python packages for a given library, such as [types-protobuf](https://pypi.org/project/types-protobuf/), with `pyright.analysis.useLibraryCodeForTypes = true`, pyright would use the targeted stubs instead of library code.
This behaviour is correct until a Python library that uses the same namespace (for example [googleapis-common-protos](https://github.com/googleapis/api-common-protos)), and pyright wouldn't be able to infer the imports for this given package (see image below for more context):
```python
from google.apis import control_pb2

control_pb2... # <- throws error
```

This is the correct behaviour, but I think that having the option to go to the implementation are also helpful.

**Describe the solution you'd like**
Provide a configuration field `goToDefinition` in conjunction with `analysis.useLibraryCodeForTypes` to surpass the stubs: 
```toml
analysis.goToDefinition = true
```

**Additional context**
![Screenshot 2022-09-03 at 20 37 01](https://user-images.githubusercontent.com/29749331/188296092-369c9ae3-499b-4110-a559-bba114220890.png)

**Comment by erictraut** [comment]
I recommend against installing `types-protobuf`. It contains a bug in that it includes an `__init__.pyi` file, which makes it a traditional (as opposed to an implicit namespace) package. That's what causes the problem you're seeing with import resolution. Pyright includes a bundled version of `protobuf` type stubs from typeshed (the same source as `types-protobuf`), but the errant `__init__.pyi` is removed so it works correctly.

If you uninstall the buggy `types-protobuf`, pyright will be able to resolve `google.api` correctly.

The feature you're proposing wouldn't make sense if pyright is unable to resolve the import, so I'm going to close the issue.
