### ISSUE TITLE
Local imports masking global imports

### ISSUE THREAD

**Issue by ysmu** [microsoft/pyright#3910]
Environment: CPython 3.10.4 on Windows

Consider the following code:
```py
import unittest.mock

def test():
    import unittest

    print(unittest.mock.Mock)
    print(unittest.TestCase)

test()

```
![image](https://user-images.githubusercontent.com/17018576/188336839-06f0fc05-425f-4209-92c2-cfb0a24b5c1b.png)

While pyright is not able to find `unittest.mock` in `test()`, the code above runs fine. It claims that `unittest.mock` is unused but it is clearly used by `unittest.mock.Mock`.

My speculation is that is has to do with variable scopes -- `import unittest.runner` created a `unittest` variable in the local namespace, masking the `unittest` variable created from `import unittest.mock` in the global namespace. This wouldn't have worked with other types of variables, but it looks like `import` is special (or maybe this is accidental in CPython's implementation?)

Is this a scenario pyright can support?

**Comment by erictraut** [comment]
Pyright is working as designed here.

Within the `test` function, there is a local variable called `unittest` that is assigned via an import statement. This local variable is distinct from the global variable `unittest`. The function `test` is relying on a temporal side effect of the Python import loader that `unittest.mock` will be populated and cached. That's a very fragile assumption. Pyright intentionally does not model implicit side effects of the import loader. In the general case, such side effects cannot be modeled correctly by a static type checker. Even in this specific case, I would consider it a bug to rely on such side effects. If you want to use `unittest.mock` within an execution scope, you should import it in that scope.
