### ISSUE TITLE
Shell complete

### ISSUE THREAD

**Issue by Freed-Wu** [microsoft/pyright#3911]
Can pyright provide complete for bash/zsh/fish/posh/etc? Like the following. TIA!

```
❯ pyright --<TAB>
option
--createstub        Create type stub file(s) for import
--dependencies      Emit import dependency information
--help              Show this help message
...
```

**Comment by erictraut** [comment]
I'm not an expert at shells, but I don't think that's possible. The shell simply executes pyright and passes it the supplied command-line arguments. There's no interaction between the shell and the executable before this.

**Comment by JelleZijlstra** [comment]
It is possible to define a customized set of autocompletions for a command (documented for bash in https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion.html; somebody wrote it for Black at psf/black#1576). Whether that's worth maintaining for pyright is a different question.

**Comment by erictraut** [comment]
I would welcome a contribution in this space if the solution isn't a maintenance burden. I don't plan to implement this functionality unless/until we receive stronger signal from users that it's needed. I'm going therefore close this feature request for now, but we might reconsider in the future if there are sufficient upvotes (thumbs-up reactions).

**Comment by akpircher** [comment]
It looks like mypy, pytest, and other python packages have bash completions hosted in [scop's bash-completion](https://github.com/scop/bash-completion) repo (which is specific to bash-completion v2 for bash 4.2+). I think scop just started creating them himself.

For anyone else who finds this issue while looking for bash-completion for pyright, I quickly threw something together: https://gist.github.com/akpircher/bc4aee788d2ffd7c813d32ba32e474d8

@erictraut, I'm happy to work with you to find a better place for this, either tracked here or in bash-completion repository, but I hope you don't mind that I just... did this. It was easy enough for me to make, and I thought it might be nice to share.

I do not know anything about completion in other shells.

**Comment by Freed-Wu** [comment]
<https://github.com/f/omelette> is a javascript library to generate shell completions for bash/zsh/fish. Maybe we can use it.
