### ISSUE TITLE
--verifytypes does not consider --lib or useLibraryCodeForTypes

### ISSUE THREAD

**Issue by teaishealthy** [microsoft/pyright#3915]
**Describe the bug**
When using `--verifytypes` pyright does not use library code for types.

**To Reproduce**
Import a symbol from a "non-py.typed" library. Now run `--verifytypes` with `--lib`.

Pyright will error on an unknown symbol. (Unlike when normally running `pyright`.)

**Expected behavior**
Pyright infers the type from the library code

**Version**
`pyright 1.1.269`

**Comment by erictraut** [comment]
Yes, this is intended behavior. The purpose of `--verifytypes` is to detect and report symbols that are missing type information. Libraries should not rely on `--lib` because other type checkers in the Python world do not have type inference capabilities as deep as pyright.
