### ISSUE TITLE
Incorrect interaction with attrs default override

### ISSUE THREAD

**Issue by Rizhiy** [microsoft/pyright#3917]
**Describe the bug**
`attrs` is similar to `dataclass`, but allows defining new `args` after `kwargs`, if `kwargs` are redefined.
`pyright` doesn't work properly with it.
Not sure whether the problem is with `attrs` type definitions or with `pyright`, so will create issues in both places.

**To Reproduce**
```python
from attrs import define


@define
class A:
    foo: int
    bar: str = "baz"


@define
class B(A):
    zoo: float
    bar: str = "zaz"


b = B(1, 2.7)
print(b)
>>> B(foo=1, zoo=2.7, bar='zaz')
```
This shows two errors for me:
![image](https://user-images.githubusercontent.com/5617397/188770355-bba8d427-3cba-474d-89dd-8a3a60a25e09.png)
![image](https://user-images.githubusercontent.com/5617397/188770379-f9033846-9834-46bf-a9fd-9b9b43ea95a9.png)

**Expected behavior**
No errors.

**Comment by erictraut** [comment]
Pyright contains no special knowledge of third-party libraries like `attrs`. It analyzes code based on the type information it is provided. 

We introduced [PEP 681](https://peps.python.org/pep-0681/), which covers many of the behaviors of libraries like `attrs` and `pydantic`. These libraries differ slightly from the standard lib `dataclass`, and PEP 681 doesn't capture all of those nuances (such as the one you highlight here), but it does cover most standard behaviors. 

My understand (which might be incorrect) is that the `@define` decorator in `attrs` does not default to kwargs. Rather, it defaults to positional parameters, which means that fields with defaults cannot appear after fields without defaults. If you want to use keyword args with `@define`, you can use `@define(kw_only=True)`. Then pyright will not complain about the field order.
