### ISSUE TITLE
comment seems not match what code does?

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#392]
not sure whether it is a bug or comment is simply wrong.

but this
https://github.com/microsoft/pyright/blob/560759afe3324bfa0e4e1c7d3efce8850a81b656/server/src/analyzer/importResolver.ts#L834

```typescript
// Always prefer stub files over non-stub files.
const entry = implicitImportMap.get(implicitImport.name);
if (!entry || !entry.isStubFile) {
   implicitImportMap.set(implicitImport.name, implicitImport);
}
```

seems behavior opposite of the comment where it prefer regular py over pyi file.

should it be entry.isStubFile rather than !entry.isStubFile

**Comment by erictraut** [comment]
I think the code is correct. It's deciding whether to add a new entry to the map or overwrite an existing entry. It should overwrite an existing entry only if that entry is not a stub file. If we changed it to `entry.isStubFile`, we'd end up overwriting a stub file with a non-stub file. Make sense?

**Comment by heejaechang** [comment]
ah. yes. you are right. it is checking entry not implicitImport just created.

**Comment by erictraut** [comment]
Yeah, I guess this code could have been clearer.
