### ISSUE TITLE
Narrow down descriptor based tagged unions

### ISSUE THREAD

**Issue by saryou** [microsoft/pyright#3928]
Pyright can narrow down tagged unions which based on literals correctly like:

```
from typing import Literal, Union


class A:
    tag: Literal['a']


class B:
    tag: Literal['b']


def take_a(a: A):
    pass


def test(u: Union[A, B]):
    if u.tag == 'a':
        take_a(u)
```

But it doesn't work if tags are based on descriptors.

reproduce: 

```
from typing import TypeVar, Generic, overload, Any, Union
from typing_extensions import LiteralString


T = TypeVar('T', bound=LiteralString)


class Tag(Generic[T]):
    def __init__(self, tag: T):
        self.tag = tag

    @overload
    def __get__(self, instance: None, owner: Any = ...) -> 'Tag[T]':
        ...

    @overload
    def __get__(self, instance: Any, owner: Any = ...) -> T:
        ...

    def __get__(self, instance, owner=None):
        if instance is None:
            return self
        return self.tag


class A:
    tag = Tag('a')


class B:
    tag = Tag('b')


def take_a(a: A):
    pass


def test(u: Union[A, B]):
    # pyright knows u.tag is Literal['a', 'b']
    if u.tag == 'a':
        take_a(u)

# error: Argument of type "A | B" cannot be assigned to parameter "a" of type "A" in function "take_a"
#     Type "A | B" cannot be assigned to type "A"
#         "B" is incompatible with "A" (reportGeneralTypeIssues)
```

pyright: 1.1.270

**Comment by erictraut** [comment]
In your second example, `tag` doesn't have a declared type, so its type must be inferred. Also, `tag` is a writable class variable, so there's no type-safe guarantee that it won't be overwritten. 

You could work around the above issues by adding a type declaration for `tag`:
```python
    tag: Tag[Literal["a"]] = Tag("a")
```

This will doesn't work for type narrowing, however. The current type narrowing logic for discriminating based on member types does not work with descriptors — much less descriptors with overloaded `__get__` methods. It would be possible to add such support if there were sufficient demand for it, but I don't think this is a common usage patter. I'm going to close the enhancement request for now, but we may consider it again in the future if we receive sufficient signal from other users that this is desired. If you're interested in the functionality, please upvote this issue (add a thumbs-up reaction).

**Comment by saryou** [comment]
thanks for your reply!

> In your second example, tag doesn't have a declared type, so its type must be inferred. Also, tag is a writable class variable, so there's no type-safe guarantee that it won't be overwritten.

It's true, but almost everything in python is writable. So I think it's reasonable to assume that it won't be changed. Beside, pyright claims this is error: 

```
class A:
    tag = Tag('a')

A.tag = Tag('b')

# error: Cannot assign member "tag" for type "Type[A]"
#   Expression of type "Tag[Literal['b']]" cannot be assigned to member "tag" of class "A"
#     TypeVar "T@Tag" is invariant
#       "Literal['b']" cannot be assigned to type "Literal['a']" (reportGeneralTypeIssues)
```

> The current type narrowing logic for discriminating based on member types does not work with descriptors — much less descriptors with overloaded `__get__` methods. It would be possible to add such support if there were sufficient demand for it, but I don't think this is a common usage patter.

This is the point. Pyright already knows that `__get__` returns discriminable literals so I thought it is better to be able to narrow down like first example. But I also know that it is not common pattern so I just upvoted myself.
