### ISSUE TITLE
`TypeVar` loses subtype information when placed inside `tuple`

### ISSUE THREAD

**Issue by colehaus** [microsoft/pyright#3930]
In the following code, pyright 1.1.270 CLI raises a type error on `bb`:

```py
from typing import Literal, TypeAlias, TypeVar

A = TypeVar("A")

def foo(x: A) -> tuple[A, int]:
    return x, 2

def bar(x: A) -> A:
    return x

Variant: TypeAlias = Literal["ab", "cd"]
v: Variant = "ab"

bb: Variant = foo(v)[0] # Type error here
cc: Variant = bar(v)
dd: str = foo("ef")[0]
```

That error is:
```
error: Expression of type "str" cannot be assigned to declared type "Variant"
    Type "str" cannot be assigned to type "Variant"
      "str" cannot be assigned to type "Literal['ab']"
      "str" cannot be assigned to type "Literal['cd']" (reportGeneralTypeIssues)
```

I would expect `bb` to type check just like `cc` does. Indeed, this all type checks in mypy 0.971.

**Comment by erictraut** [comment]
The current behavior is intended. Literal values are not retained by the TypeVar constraint solver in this case.

Mypy appears to be inconsistent in how it handles this case.

```python
AB: TypeAlias = Literal["ab"]
def func(val: AB):
    reveal_type(foo(val)) # tuple[Literal["ab"], int]
    reveal_type(foo("ab")) # tuple[str, int]
```

Pyright generates a consistent solution in both cases (`tuple[str, int]`).

To get the result you are looking for, you would need to hint the type constraint solver by providing a type declaration for the result.

```python
x1: tuple[Literal["ab"], int] = foo(v)
bb: Variant = x1[0]

# Or
x2: tuple[Variant, int] = foo(v)
bb: Variant = x2[0]
```
