### ISSUE TITLE
Pyright-langserver as a TCP server?

### ISSUE THREAD

**Issue by Dronte** [microsoft/pyright#3932]
I understand that this issue is mostly related to `vscode-languageserver` but since pyright is the end product I'm trying to use I'm posting the issue here.

The behavior of `--socket` argument is wired.  First it accepts port number, not path to a socket.

Second this port number is a port where _client listens_ . On start this port sends a couple of messages then it just listens to initialize request. If there is nobody listening on that port, the server exists. I see no reason on this behaviour. These  messages are not needed to the client, it can send initialise request without them. Additionally, it makes the only order that client and server must be started - first client, bind to port, and then provide this port to the server. 

I see no reason, why this order can't be reversed - first run the server, make it listen on some port, then tell the client which port to connect to. And It gives the client an ability to reconnect to the server without restarting it. Isn't it much simpler way than making the client responsible to behave like a server?

**Comment by erictraut** [comment]
As you said, this is related to `vscode-languageserver`, not pyright. We have no plans to change this.
