### ISSUE TITLE
Type narrowing on Union with generic members introduces 'Unknown' type arguments

### ISSUE THREAD

**Issue by kyle-query** [microsoft/pyright#3933]
**Describe the bug**

Using `if instanceof(..., cls)` to narrow a Union with generic members type inserts `Unknown` as the type argument.

**To Reproduce**

```python
from dataclasses import dataclass
from typing import Generic, TypeVar, Union

T = TypeVar('T')
V = TypeVar('V', str, int, float, bool)

@dataclass
class Bar(Generic[V]):
    bar: V

@dataclass
class Foo(Generic[T, V]):
    foo: Union[T, Bar[V]]

    def test(self) -> None:
        self.foo # T@Foo | Bar[V@Foo]

        if isinstance(self.foo, Bar):
            self.foo            # Bar[Unknown]* | Bar[V@Foo] <-- should only be Bar[V@Foo]
            self.foo.bar        # Unknown | V@Bar, error in strict mode
            v: V = self.foo.bar # error in strict mode, type of "bar" is unknown, type of "bar" is partially unknown
            return

        self.foo        # object*
        t: T = self.foo # ok in strict mode
```

**Expected behavior**

In the conditional branch, `self.foo` should have the type `Bar[V@Foo]` rather than `Bar[Unknown]* | Bar[V@Foo]`.

**Screenshots or Code**

See code example under "to reproduce".

**VS Code extension or command-line**

```sh
$ cat pyproject.toml
[tool.pyright]
typeCheckingMode = "strict"

$ pyright --version
pyright 1.1.267
```

Reproduced both with pyright on the command line and using neovim + lspconfig.

**Comment by hmc-cs-mdrissi** [comment]
```python
x = Foo[Bar[int], str]()
x.foo # Could be Bar[int]
```

isinstance check may match both T and Bar[V] is the issue. If it matches T, then you have T*/Bar[unknown] case.

**Comment by kyle-query** [comment]
Thanks Mehdi, that makes sense and you're correct. I was able to work around the issue by adding another class to tag the `T` value:

```python
@dataclass
class Quux(Generic[T]):
    quux: T

@dataclass
class Bar(Generic[V]):
    bar: V

@dataclass
class Foo(Generic[T, V]):
    foo: Union[Quux[T], Bar[V]]
```
