### ISSUE TITLE
circular import though "from x import *" doesn't work

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#394]
for example, 
f.py
```python
from b import *
foo: int = 1
print(bar)
```

b.py
```python
from f import *
bar: int = 1
print(foo)
```
either bar or foo will show error as unknown symbol depends on which file is the starting point of the analysis

the reason seems bindModule doesn't handle circular imports
https://github.com/microsoft/pyright/blob/master/server/src/analyzer/binder.ts#L139

due to that, 
when it hits this
https://github.com/microsoft/pyright/blob/master/server/src/analyzer/binder.ts#L1154

module symbol table is not set for the circular one yet, since code path is at 
https://github.com/microsoft/pyright/blob/master/server/src/analyzer/sourceFile.ts#L683

and didn't reach here yet
https://github.com/microsoft/pyright/blob/master/server/src/analyzer/sourceFile.ts#L695

so, this._fileInfo.importLookup returns null and skip any symbols from that modules.

not sure whether it is intentionally not supported scenario or just a bug.

I dont know what is a fix if it is a bug. feels like this part some how needs to be lazy
https://github.com/microsoft/pyright/blob/master/server/src/analyzer/binder.ts#L1154

like how binding already does for _bindDeferred with deferredBindingTasks.

**Comment by heejaechang** [comment]
actually, thinking a bit more, it is not "not lazy" is the issue, the issue is the cache. result of import is different on base on import path, but code treat all same. 
ex) import of a -> b and import of b -> a

I think BindModule should track import path and if it is a circular import, it shouldn't cache but always recalculate?

**Comment by erictraut** [comment]
I think it's doing the right thing in this case. If you run the program above, the python interpreter will also fail to resolve the circular dependency, and it will print "NameError: 'bar' is not defined" (or "'foo' is not defined" depending on which file you execute).

**Comment by heejaechang** [comment]
let me tag @MikhailArkhipov @jakebailey to give you better examples than my simplified version

**Comment by erictraut** [comment]
Some additional background: The binder looks at only one file at a time. It never attempts to resolve symbols across files or invoke the parser or binder for other files. It also doesn't deal with any types (except for a few special built-in symbols like `__name__` that have pre-defined types). The binder, therefore, should never have any involvement in circular dependencies.

Yeah, let me know if you find any other examples. Thanks!

**Comment by MikhailArkhipov** [comment]
I think @heejaechang means simplified version of the tests we have
https://github.com/microsoft/python-language-server/blob/master/src/LanguageServer/Test/ImportsTests.cs#L407

https://github.com/microsoft/python-language-server/blob/master/src/LanguageServer/Test/ImportsTests.cs#L479

https://github.com/microsoft/python-language-server/blob/master/src/LanguageServer/Test/ImportsTests.cs#L534

**Comment by heejaechang** [comment]
binder do looks other file?
https://github.com/microsoft/pyright/blob/master/server/src/analyzer/binder.ts#L1154

when wild card is involved in import? I can see in callback it calls bind on other file for that code path.

**Comment by erictraut** [comment]
Ah yes, my bad. I forgot about this case. It does indeed bind another file in the case of wildcard imports.

**Comment by MikhailArkhipov** [comment]
Tests above works fine. Although I noticed that addition of a missing module does not resolve existing error which is similar to https://github.com/microsoft/python-language-server/issues/944

**Comment by heejaechang** [comment]
circular reference works fine in pyright due to lazy bind. only thing I noticed was wildcard case but looks like that is expected behavior.

other cases, such as "from a import b" from the unit tests above,
empty symbol "b" will be created first and then later connected to actual decls. so there is no cycle.

**Comment by heejaechang** [comment]
let me take a look at microsoft/python-language-server#944 tomorrow. and let you know if there is anything stand out. 

@erictraut sorry for keep opening issue for something that is actually working correctly. I wasn't sure how I can contact you except opening issue here. or whether it is okay for me to directly ping you from team.

**Comment by erictraut** [comment]
No problem. Happy to chat on GitHub or on Teams — whatever works best for you.

**Comment by MikhailArkhipov** [comment]
This one can be closed I think :-)
