### ISSUE TITLE
Using Literal with strings or bytes from typing-extensions results in an error when imported from another module

### ISSUE THREAD

**Issue by pszpetkowski** [microsoft/pyright#3945]
**Describe the bug**
This is a weird one. If `Literal` from `typing-extensions` is imported directly in the same module that it is used, there is no typing error. However if there is a dedicated e.g. `compat` module that imports the same `Literal` from `typing-extensions` and then some module imports `Literal` from this `compat` module it results in an error, but only if provided values are of type string or bytes (int and bool work fine).

Example of an error:
> "foo" is not defined

**To Reproduce**
Just type the code provided below into two separate files and you will see the error.

**Expected behavior**
There should be no error, just like in the case when `Literal` is imported in the same file.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/18597734/190135513-f901de71-3a25-4960-9097-4197eaf0ca07.png)

package/compat.py:
```python
from typing_extensions import Literal

__all__ = ["Literal"]
```

module.py:
```python
from package.compat import Literal

item: Literal["foo", "bar"]
```

I'm using the latest `typing-extensions` i.e. `4.3.0`.

**VS Code extension or command-line**
I use pyright in VS Code via Pylance v2022.9.10

**Comment by erictraut** [comment]
It turns out that this bug was already fixed as part of https://github.com/microsoft/pyright/issues/3944. I confirmed that I'm no longer able to repro with pyright 1.1.271. This fix will appear in a future release of pylance.

**Comment by pszpetkowski** [comment]
Great, thank you for verifying that it's already fixed.
