### ISSUE TITLE
Invalid checking of Callable params

### ISSUE THREAD

**Issue by loisapplambda** [microsoft/pyright#3959]
I am getting an error with the following code sample:

```
from typing import Callable


class Container:
    pass


FunctionType = Callable[[Container], None]


def wrapper(func: FunctionType) -> FunctionType:
    return func


class HelloWorldContainer(Container):
    @wrapper
    def get_hello(self) -> None:
        pass
```

The error I am getting is:

```
error: Argument of type "(self: Self@HelloWorldContainer) -> None" cannot be assigned to parameter "func" of type "FunctionType" in function "wrapper"
    Type "(self: Self@HelloWorldContainer) -> None" cannot be assigned to type "FunctionType"
      Parameter 1: type "Container" cannot be assigned to type "Self@HelloWorldContainer"
        "Container" is incompatible with "HelloWorldContainer" (reportGeneralTypeIssues)
```

This is odd since `HelloWorldContainer` is a subclass of `Container`. I think the ordering here is suspicious, I'd expect the last error to be `"HelloWorldContainer" is incompatible with "Container"`. Could this be a bug where src and dest are accidentally swapped?

Thanks.

**Comment by erictraut** [comment]
This isn't a bug. The problem is that the type of the `self` parameter is not `Container`. It is some type that is a subclass of `Container`. Callable parameter types are contravariant. Not surprisingly, mypy emits the same error as pyright here.

To type this correctly, you would need to do something like this:

```python
TContainer = TypeVar("TContainer", bound=Container)

def wrapper(func: Callable[[TContainer], None]) -> Callable[[TContainer], None]:
    return func
```

**Comment by loisapplambda** [comment]
Thank you.
