### ISSUE TITLE
Invariant type error with generics

### ISSUE THREAD

**Issue by rchl** [microsoft/pyright#3963]
**Describe the bug**
I'm sorry if this is just a question from someone who doesn't understand (co/contra/in)variance very well and not an actual bug but I won't know until I ask. :)

The code below, which is a simplified example of a JS-like Promise implementation in python, triggers the following error:

```
Expression of type "Promise[Type[int]]" cannot be assigned to return type "Promise[int | None]"
  TypeVar "T@Promise" is invariant
    Type "Type[int]" cannot be assigned to type "int | None"
      "Type[type]" is incompatible with "Type[int]"
```

I'm not sure if that's a bug or just my lack of knowledge on how to implement this correctly.

**To Reproduce**
1. Try the code sample

**Expected behavior**
No error ideally

**Screenshots or Code**
```python
from typing import Generic, Optional, TypeVar

T = TypeVar('T')


class Promise(Generic[T]):
    @classmethod
    def resolve(cls, resolve_value: T) -> 'Promise[T]':
        return cls(resolve_value)

    def __init__(self, value: T) -> None:
        self.value = value


def return_type() -> Promise[Optional[int]]:
    return Promise.resolve(int)


result = return_type()
```

**VS Code extension or command-line**
Pyright 1.1.271

**Comment by erictraut** [comment]
There are a few problems here.

First, when calling `Promise.resolve`, you should pass an object (like `0`) not a type (like `int`). I suspect this was just a typo, so I've replaced `int` with `0` in the `return_type` function implementation in your sample above.

Second, `resolve` uses a class-scoped TypeVar `T`, which means that the return type (`Promise[T]`) must match the type of the class through which it is invoked. If it is invoked through a `Promise[str]`, then `T` must be `str`. 

```python
Promise[str].resolve("hi") # Legal
Promise[int].resolve(1) # Illegal
Promise.resolve(1) # Ambiguous because T is not specified for the calling type
```

If I understand the intent of your code, here's how you would want to implement `return_type`:
```python
def return_type() -> Promise[int | None]:
    return Promise[int | None].resolve(0)
```

If you don't plan to subclass `Promise`, you could also switch to a static method that uses a method-scoped TypeVar.

```python
from typing import Generic, TypeVar, final

T = TypeVar("T")
S = TypeVar("S")

@final
class Promise(Generic[T]):
    @staticmethod
    def resolve(resolve_value: S) -> "Promise[S]":
        return Promise(resolve_value)

    def __init__(self, value: T) -> None:
        self.value = value

def return_type() -> Promise[int | None]:
    return Promise.resolve(0)
```

**Comment by rchl** [comment]
Amazing. A method-scoped typevar fixes my issues. Thank you for spending the time to explain and fix my issue. :)

(And yes, the `int` was a typo I made when creating this simplified example.)
