### ISSUE TITLE
Improve type checking

### ISSUE THREAD

**Issue by qmmp123** [microsoft/pyright#3986]
How can I solve error below without adding one more condition?
```python
from typing import Optional

def foo(a: str):
    print(a)

def bar(a: Optional[str], b: Optional[str]):
    my_flag = a is not None and b is not None
    if my_flag:
        foo(a) # Here I get type checking error
```
`Argument of type "str | None" cannot be assigned to parameter "a" of type "str" in function "foo"    Type "str | None" cannot be assigned to type "str"      Type "None" cannot be assigned to type "str"`

**Comment by erictraut** [comment]
Pyright includes an advanced static type checking feature called [Aliased Conditional Expressions](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#aliased-conditional-expression). None of the other Python type checkers support this. It was a concept I took from the typechecker compiler, which added support for this about a year ago now.

The feature has limits, however. The aliased conditional expression must be of certain forms and cannot operate on multiple variables. The expression you're using above is too complex to work with this feature. You'll need to simplify the expression so it operates only on `a` or `b`, not both. Or you can move the entire conditional expression directly into the `if` statement.
