### ISSUE TITLE
IO Generics not inferred based on file mode.

### ISSUE THREAD

**Issue by nupanick** [microsoft/pyright#399]
Although #286 claims otherwise, I am finding that the type of IO is not automatically inferred from the file mode.

```py
f1 = open('foo.wad', 'wb')
# (variable) f1: IO[Any]
f2 = open('foo.wad', mode='rb')
# (variable) f2: IO[Any]
f3 = open('foo.txt', encoding='utf-8')
# (variable) f3: IO[Any]
```

I would expect to get `IO[bytes]`, `IO[bytes]`, and `IO[str]`, respectively.

Using pyright 1.1.8 for VS Code 1.40.2.

**Comment by erictraut** [comment]
#286 was an experiment. It required me to edit the typeshed builtins.pyi file. I recently sync'ed the typeshed files that ship with pyright with the latest version from the typeshed repo. During that sync, my manual edits to builtins.pyi were deleted.

I think it's important for pyright to track the official typeshed stub files, so I'm reluctant to add back my manual edits. If you want to see this feature added, I encourage you to file an issue or submit a PR in the [typeshed repo](https://github.com/python/typeshed).
