### ISSUE TITLE
Auto path excludes should not override explicitly passed paths

### ISSUE THREAD

**Issue by RobertCraigie** [microsoft/pyright#3999]
**Describe the bug**

It looks like by default, Pyright auto excludes paths that match these patterns:

- `**/node_modules`
- `**/__pycache__`
- `**/.*`

These are very reasonable defaults but they still apply even if you explicitly pass a path that matches these filters, e.g.

```
pyright foo/.bar/baz.py
```

Even when the `foo/.bar/baz.py` file exists, Pyright will output something like:

```
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /prisma-client-py/typings is not a valid directory.
Searching for source files
No source files found.
Completed in 0.293sec
```

**To Reproduce**

1. `mkdir -p foo/.bar`
2. `echo 'i = 1\ni.strip()' > foo/.bar/baz.py`
3. `pyright foo/.bar/baz.py`

**Expected behavior**

Pyright should type check the `foo/.bar/baz.py` file.

**Screenshots or Code**

Not really relevant but this is the code I used to check if Pyright would report an error or not.

```python
i = 1
print(i.strip())
```

**VS Code extension or command-line**

Command-line 1.1.273

**Comment by erictraut** [comment]
This is working as designed.

If you want to override the default auto-exclude, you'll need to provide a configuration file and specify an "exclude" with some dummy directory. If no exclude is provided, the auto-exclude file specs are applied.

**Comment by RobertCraigie** [comment]
This is very surprising to me, what is the reasoning that a default exclude filter should apply to a path that I explicitly pass? I can understand why it would apply to subpaths but I'd expect that if I explicitly pass a file to Pyright then it would be type checked and not just silently exclude it because it matches default filters.

Aside from that, this behaviour lead to a bug in my workflow as I didn't realise that Pyright wasn't type checking certain files because the actual command I run looks like this:

```
$ pyright foo/.bar/prisma tests
...
Searching for source files
Found 86 source files
```

So it wasn't immediately obvious that something was wrong because Pyright was finding some source files to check.

Even if this behaviour stays the same it would help a lot to have a warning output for any paths that are explicitly passed, e.g.

```
$ pyright foo/.bar/prisma
...
Searching for source files
Ignoring foo/.bar/prisma as it matches an exclude filter
```

**Comment by erictraut** [comment]
There are a couple of design principles at play here.

First, it's important for the CLI version of pyright to have consistent behavior with the LSP version. Differences between the two result in surprises for users and are difficult to justify. For that reason, both apply auto-exclude directories consistently.

Second, when using the CLI, you can specify specs (globs) for files, directories, or both. Or you can specify no file or directory specs, in which case the "include" list is taken from the pyrightconfig.json file. There is no way to override the "exclude" list from the command line; that must be done through the pyrightconfig.json file. It's perfectly reasonable (and sometimes desirable) for globs specified in the "include" list to intersect with globs specified in the "exclude" list.

We added the "Auto-exclude" output to make it clear that certain directories are excluded by default.
