### ISSUE TITLE
"Precise typing of alternative constructors" fails

### ISSUE THREAD

**Issue by betafcc** [microsoft/pyright#4001]
**Describe the bug**

This fails with 'error: TypeVar bound type cannot be generic'

```py
T = TypeVar('T')

class Base(Generic[T]):
    Q = TypeVar('Q', bound='Base[T]')
```

Works fine on mypy and is on the docs: https://mypy.readthedocs.io/en/stable/more_types.html?highlight=mixin#precise-typing-of-alternative-constructors

**To Reproduce**
Just run the example with `npx -y pyright --pythonversion 3.10`

**Comment by JelleZijlstra** [comment]
I fixed the mypy docs: https://github.com/python/mypy/commit/dc5c299aa190949f2300b163ccc10257a779006d (accidentally committed straight to master, sorry).

**Comment by erictraut** [comment]
Yes, pyright is correct here. PEP 484 is very clear that bounds for a TypeVar cannot include other TypeVars.

> A type variable may specify an upper bound using bound=<type> (note: <type> itself cannot be parameterized by type variables)

A bound must be a specialized (non-generic) type. Mypy fails to flag this as an error.
