### ISSUE TITLE
verifytypes completeness score not impacted by missing type annotations in class defined in __all__

### ISSUE THREAD

**Issue by kristapratico** [microsoft/pyright#4002]
**Is your feature request related to a problem? Please describe.**
I would like to use `--verifytypes` to monitor the type completeness of our client libraries. We typically mark all files in a module as private (prefixed with underscore) and expose the public interface under the __all__.

```
azure-treehouse
├── azure
│   ├── __init__.py
│   └── treehouse
│       ├── __init__.py
│       ├── _models.py
│       └── py.typed
```

treehouse/__init__.py
```python
from ._models import Tree

__all__ = ["Tree"]
```

treehouse/_models.py
```python
class Tree:

    def __init__(self, *, location: str, num_branches) -> None:
        self.location = location
        self.num_branches = num_branches
```

When I run `--verifytypes`, I get the following output:

```
Public modules: 1
   azure.treehouse

Symbols used in public interface:
azure.treehouse._models.Tree.__init__
  ...\treehouse\azure-treehouse\azure\treehouse\_models.py:5:9 - error: Type annotation for parameter "num_branches" is missing
azure.treehouse._models.Tree.num_branches
 ...\treehouse\azure-treehouse\azure\treehouse\_models.py:7:14 - error: Type unknown for variable "azure.treehouse._models.Tree.num_branches"

Symbols exported by "azure.treehouse": 1
  With known type: 1
  With ambiguous type: 0
  With unknown type: 0
  Functions without docstring: 0
  Functions without default param: 0
  Classes without docstring: 0

Other symbols referenced but not exported by "azure.treehouse": 4
  With known type: 1
  With ambiguous type: 0
  With unknown type: 3

Type completeness score: 100%

Completed in 0.797sec
```

I would like to understand why the missing type annotations on the `Tree` class do not count towards the overall Type completeness score. I read this excerpt of the typed-libraries.md doc (great read, btw!) to mean that exposing a type under __all__ would indicate to the type checker to consider it and its members as public:

> A module can expose an __all__ symbol at the module level that provides a list of names that are considered part of the interface. The __all__ symbol indicates which symbols are included in a wildcard import. All symbols included in the __all__ list are considered public even if the other rules above would otherwise indicate that they were private. For example, this allows symbols whose names begin with an underscore to be included in the interface.

**Describe the solution you'd like**
For the type annotation errors under "Symbols used in public interface:" to count towards the Type completeness score or maybe an option to be able to do this.

**Additional context**
pyright==1.1.273

**Comment by erictraut** [comment]
Thanks for the detailed bug report. That made it easy to repro the problem.

There was a bug in the code that calculates the metrics that are used for the type completeness percentage. In particular, the code was not correctly handling the case where a private symbol with an incomplete type was re-exported as a symbol from another module.

This will be addressed in the next release.

**Comment by kristapratico** [comment]
@erictraut thanks! I tried 1.1.274 and this is the output I see for the above example:

```
Public modules: 1
   azure.treehouse

Symbols used in public interface:
azure.treehouse._models.Tree.__init__
  ...\azure-treehouse\azure\treehouse\_models.py:5:9 - error: Type annotation for parameter "num_branches" is missing
azure.treehouse._models.Tree.num_branches
  ...\treehouse\azure-treehouse\azure\treehouse\_models.py:7:14 - error: Type unknown for variable "azure.treehouse._models.Tree.num_branches"

Symbols exported by "azure.treehouse": 1
  With known type: 0
  With ambiguous type: 0
  With unknown type: 1
  Functions without docstring: 0
  Functions without default param: 0
  Classes without docstring: 0

Other symbols referenced but not exported by "azure.treehouse": 4
  With known type: 1
  With ambiguous type: 0
  With unknown type: 3

Type completeness score: 0%

Completed in 0.906sec
```

Just to confirm, it seems the 1 known type does not impact the score because the overall Tree type is unknown. Is that correct?

**Comment by erictraut** [comment]
Yes, that's correct.

The "type completeness score" is calculated based on the public symbols exported by the module and its submodules. It doesn't include other symbols that are referenced but not exported. 

In your example, the only publicly exported symbol is `azure.treehouse.Tree`, and its type is partially unknown. This type references four other symbols including `testpkg1.azure.treehouse._models.Tree`, `testpkg1.azure.treehouse._models.Tree.__init__`, `testpkg1.azure.treehouse._models.Tree.location` and `testpkg1.azure.treehouse._models.Tree.num_branches`. Of these symbols, three of them have known types, and one has a partially unknown type (due to the missing parameter annotation).

If you use the `--verbose` option, pyright will provide more details.
