### ISSUE TITLE
drodown list has too many "noises" 

### ISSUE THREAD

**Issue by laoshaw** [microsoft/pyright#4025]
**Is your feature request related to a problem? Please describe.**

when I want to see a dropdown list of methods, coc-pyright gave me lots of options and many of them are not useful, see the screenshot, what I really need is just the "f", not "v".

![image](https://user-images.githubusercontent.com/18351761/194735521-033ca832-1ca5-466f-a1ac-173b3ad651db.png)

**Describe the solution you'd like**

as a comparison to my c++ code, only useful methods are shown up in the dropdown list:
![image](https://user-images.githubusercontent.com/18351761/194735537-5ff3555b-ec19-4e7d-8c53-babf15c21e18.png)
so is typescript:
![image](https://user-images.githubusercontent.com/18351761/194735549-46f8e8c9-e037-4ece-96a6-af0d288a3cc0.png)

can pyright do similar sorting for dropdown suggestions? i.e. the most useful methods on the top?

**Additional context**

**Comment by erictraut** [comment]
This is working as designed. Here's what it looks like in VS Code.

![Screen Shot 2022-10-08 at 10 32 30 PM](https://user-images.githubusercontent.com/7040122/194739744-3e26916d-2831-45ca-938d-87c7d5eca567.png)

The completion suggestions come from the `re.pyi` stub file, which indicates which symbols are exported from the `re` module. This includes functions, variables, classes, and type aliases. You'll see that the stub file includes variable symbols `A`, `ASCII`, etc.

![Screen Shot 2022-10-08 at 10 35 03 PM](https://user-images.githubusercontent.com/7040122/194739821-10b07c09-6ea4-4637-912a-7b602ae4a8a0.png)

You can further filter the list by typing one or more characters.
