### ISSUE TITLE
Support for overloaded functions

### ISSUE THREAD

**Issue by jeongukjae** [microsoft/pyright#404]
**Describe the bug**

I wrote below code,

```python
import re
from typing import Union, Callable, Match

def test(for_match: Union[str, Callable[[Match[str]], str]], some_text: str):
    some_pattern = re.compile('some-pattern')
    some_pattern.sub(for_match, some_text)
```

and the below code is the type of `Pattern` class. (https://github.com/python/typeshed/blob/a06abc5dff2928b7111452fe9f44a922585ebde0/stdlib/3/typing.pyi#L563)

```python
class Pattern(Generic[AnyStr]):
    flags: int
    groupindex: Mapping[str, int]
    groups: int
    pattern: AnyStr

    def search(self, string: AnyStr, pos: int = ...,
               endpos: int = ...) -> Optional[Match[AnyStr]]: ...
    def match(self, string: AnyStr, pos: int = ...,
              endpos: int = ...) -> Optional[Match[AnyStr]]: ...
    # New in Python 3.4
    def fullmatch(self, string: AnyStr, pos: int = ...,
                  endpos: int = ...) -> Optional[Match[AnyStr]]: ...
    def split(self, string: AnyStr, maxsplit: int = ...) -> list[AnyStr]: ...
    def findall(self, string: AnyStr, pos: int = ...,
                endpos: int = ...) -> list[Any]: ...
    def finditer(self, string: AnyStr, pos: int = ...,
                 endpos: int = ...) -> Iterator[Match[AnyStr]]: ...

    @overload
    def sub(self, repl: AnyStr, string: AnyStr,
            count: int = ...) -> AnyStr: ...
    @overload
    def sub(self, repl: Callable[[Match[AnyStr]], AnyStr], string: AnyStr,
            count: int = ...) -> AnyStr: ...

    @overload
    def subn(self, repl: AnyStr, string: AnyStr,
             count: int = ...) -> Tuple[AnyStr, int]: ...
    @overload
    def subn(self, repl: Callable[[Match[AnyStr]], AnyStr], string: AnyStr,
             count: int = ...) -> Tuple[AnyStr, int]: ...
```

It looks like `some_pattern.sub(for_match, some_text)` should not raise any errors but raise below error.

```text
No overloads for 'some_pattern.sub(for_match, some_text)' match parameters
  Argument types: (Union[str, (p0: Match[str]) -> str], str)
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.

Both

* Extension: 1.1.9
* cli: 1.1.9

**Comment by erictraut** [comment]
For overloads, the arguments to the call must match one of the overload definitions. Each overload is checked in turn until there's a match. In your example, there are no such matches, hence the error. The type of the expression `for_match` is defined as a union type, and that's not assignable to either of the two overloaded methods for `sub`.

It's not clear to me why `sub` is defined with overloads in this case. It would be better to define it with a union type:
```
def sub(self, repl: Union[AnyStr, Callable[[Match[AnyStr]], AnyStr]], string: AnyStr,
            count: int = ...) -> AnyStr: ...
```
If it were defined this way, your sample would not result in a type check error.

You may want to file a bug (or submit a PR) within the typeshed repo.

**Comment by jeongukjae** [comment]
Oh, thank you for this great explanation. It is clear to me now that this behavior is as designed.
