### ISSUE TITLE
Add support for the draft PEP 698 (typing.override)

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#4047]
### Discussed in https://github.com/microsoft/pyright/discussions/4046

<div type='discussions-op-text'>

<sup>Originally posted by **thomkeh** October 13, 2022</sup>
It's of course only a draft right now, but pyright has often been very quick with such things so I thought I'd ask :smile: 

`typing-extensions` has runtime support for it now: https://github.com/python/typing_extensions/blob/main/CHANGELOG.md#release-440-october-6-2022</div>

**Comment by erictraut** [comment]
This will be included in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.276, which I just published. It will also be included in a future release of pylance.

**Comment by mehdigmira** [comment]
Is there a plan to add a "strict enforcement" option ? https://peps.python.org/pep-0698/#strict-enforcement-per-project
I haven't seen anything about this in the documentation.

**Comment by erictraut** [comment]
We might consider adding a strict enforcement option if and when the PEP is accepted. The PEP is in draft form, and the support provided by pyright is provisional. If the PEP is rejected by the Python Steering Council, we will remove support for this functionality.

**Comment by NeilGirdhar** [comment]
Just coming back to this issue.  I'm also interested in a strict enforcement option so that I can quickly find the spots that are missing an `@override`.
