### ISSUE TITLE
Non-optimal registration and unregistration of DidChangeWatchedFilesNotification on initialize

### ISSUE THREAD

**Issue by rchl** [microsoft/pyright#4061]
**Describe the bug**
It's not a bug just some non-optimal behavior that could potentially be optimized.
On initialization the `DidChangeWatchedFilesNotification` is registered, then unregistered and then registered again.
It doesn't cause any issues but seems sub-optimal.

**To Reproduce**
Initialize pyright in a project:

```
:: <-- LSP-pyright client/registerCapability(1): {'registrations': [{'id': '567d92a9-e648-4d54-b81a-805ef287913d', 'method': 'workspace/didChangeWatchedFiles', 'registerOptions': {'watchers': [{'globPattern': '**/pyrightconfig.json', 'kind': 7}, {'globPattern': '**', 'kind': 7}]}}]}
...
:: <-- LSP-pyright client/registerCapability(5): {'registrations': [{'id': 'bf90b11a-c290-4163-b181-2793174e7dee', 'method': 'workspace/didChangeWatchedFiles', 'registerOptions': {'watchers': [{'globPattern': '**/pyrightconfig.json', 'kind': 7}, {'globPattern': '**', 'kind': 7}]}}]}
:: <-- LSP-pyright client/unregisterCapability(6): {'unregisterations': [{'id': '567d92a9-e648-4d54-b81a-805ef287913d', 'method': 'workspace/didChangeWatchedFiles'}]}
```

It's called once from:

https://github.com/microsoft/pyright/blob/50e12b4bea4fcdb61d96f855ca1e430bb8b41ca8/packages/pyright-internal/src/languageServerBase.ts#L1329-L1338

and once from:

https://github.com/microsoft/pyright/blob/50e12b4bea4fcdb61d96f855ca1e430bb8b41ca8/packages/pyright-internal/src/languageServerBase.ts#L663-L663

**Expected behavior**
Don't re-register if there were no changes that warrant it.

Pyright 1.1.275

**Comment by erictraut** [comment]
Yes, this is intentional.
