### ISSUE TITLE
Implement support for draft PEP 696 (Type defaults for TypeVarLikes)

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#4078]
[PEP 696](https://peps.python.org/pep-0696/) is far enough along that we should consider adding support for it in pyright.

Checklist:
- [x] Add support for `default` parameter in `TypeVar`, `TypeVarTuple`, `ParamSpec` with error handling
- [x] Add support for TypeVar scope determination for TypeVars that appear within `default` type expressions in class declarations
- [x] Add support for TypeVar scope determination for TypeVars that appear within `default` type expressions in type aliases
- [x] Add support for TypeVar scope determination for TypeVars that appear within `default` type expressions in functions
- [x] Add support for applying default type in explicit class specialization cases
- [x] Add support for applying default type in explicit type alias specialization cases
- [x] Add support for applying default type in cases where TypeVar is unsolved by constraint solver
- [x] Update parser to support PEP 696 support within PEP 695 TypeVar syntax (e.g. `class Foo[T = int]`)
- [x] Add support for TypeVar scope determination for PEP 695 TypeVars that appear within `default` type expressions in class declarations
- [x] Add support for TypeVar scope determination for PEP 695 TypeVars that appear within `default` type expressions in type aliases
- [x] Add support for TypeVar scope determination for PEP 695 TypeVars that appear within `default` type expressions in functions
- [x] Check for TypeVar with default that precedes TypeVar without default

**Comment by erictraut** [comment]
I'm blocked on some open questions about the draft PEP which I've sent to the PEP's author.

**Comment by erictraut** [comment]
This will be included in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.286, which I just published. It will also be included in a future version of pylance.

**Comment by winstxnhdw** [comment]
Hey Eric,

Pyright correctly parses my `TypeVar` with `default` but Pylance still gives me the following warning. What's up with that?

```
Type variable default types require Python 3.13 or newer
```

**Comment by Gobot1234** [comment]
You need to import `TypeVar` from `typing_extensions` to use `default` currently.

**Comment by winstxnhdw** [comment]
I see. Thank you so much!

**Comment by erictraut** [comment]
I'll note that [PEP 696](https://peps.python.org/pep-0696/) has not yet been approved, so I recommend against using this functionality in production code at this stage. If the PEP is ultimately rejected or revised, your code will need to be modified. If you're simply playing around with the functionality because you're curious or want to provide feedback on the draft PEP, that's fine.

@Gobot1234, have you submitted this PEP for approval? Is there a timeline that the steering council has committed to for reviewing it?

**Comment by Gobot1234** [comment]
The PEP has been submitted yes, the SC said it is being reviewed for 3.13. https://github.com/python/steering-council/issues/177#issuecomment-1538925572 is the latest communication from them that I have seen
