### ISSUE TITLE
Function signature does not show default values

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/pyright#408]
**Describe the bug**
Function signature help does not show default values. Instead, it shows types as `Unknown`

**To Reproduce**
```python
class A:
    def __init__(self, x = False): ...
x=A(
```

**Expected behavior**
It is probably better not to show `Unknown` and rather show original signatures with defaults. I.e. `(x = False)`

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/12820357/70589783-796cdf80-1b85-11ea-8822-22cd2ed96cea.png)

**Comment by erictraut** [comment]
The full signature won't be available in all cases (e.g. if the callee is a Callable type), but I agree that in cases where the full signature is available and a default value is provided, it would be useful to display the default value. I'm not entirely convinced that the type (in this case "Unknown") should be omitted even if default values are displayed.

**Comment by erictraut** [comment]
Here's a change that includes the default value in the signature: https://github.com/microsoft/pyright/commit/97d9b36c3ab5039c6fdb254e19977b2424eaffc7

**Comment by MikhailArkhipov** [comment]
Perhaps use `Any` ? I was thinking about how user tells between actual `Unknown` type, i.e. `we could not figure what it is` and legitimate `Any` type parameter.

**Comment by erictraut** [comment]
This is now fixed in version 1.1.10, which I just published.
