### ISSUE TITLE
Odd behavior with abs() with timedelta and SupportsAbs

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#4082]
**Describe the bug**
Seems like `SupportsAbs` is not handled correctly

**To Reproduce**
Using python 3.9,
```python
from __future__ import annotations
from datetime import timedelta
from typing_extensions import reveal_type
from typing import SupportsAbs


class Foo(SupportsAbs[Foo]):
    def __abs__(self) -> Foo:
        ...


f = Foo()
reveal_type(abs(f))
reveal_type(f.__abs__())


class Goo(int):
    def __abs__(self) -> Goo:
        ...


g = Goo()
reveal_type(abs(g))
reveal_type(g.__abs__())


class Too(timedelta):
    def __abs__(self) -> Too:
        ...


t = Too()
reveal_type(abs(t))
reveal_type(t.__abs__())
```
pyright 1.1.276 reports:
```text
  abstd.py:7:23 - error: "Foo" is not defined (reportUndefinedVariable)
  abstd.py:13:13 - information: Type of "abs(f)" is "Unknown"
  abstd.py:14:13 - information: Type of "f.__abs__()" is "Foo"
  abstd.py:23:13 - information: Type of "abs(g)" is "Goo"
  abstd.py:24:13 - information: Type of "g.__abs__()" is "Goo"
  abstd.py:33:13 - information: Type of "abs(t)" is "timedelta"
  abstd.py:34:13 - information: Type of "t.__abs__()" is "Too"
```

**Expected behavior**
mypy 0.982 reports:
```text
abstd.py:13: note: Revealed type is "abstd.Foo"
abstd.py:14: note: Revealed type is "abstd.Foo"
abstd.py:23: note: Revealed type is "abstd.Goo"
abstd.py:24: note: Revealed type is "abstd.Goo"
abstd.py:33: note: Revealed type is "datetime.timedelta"
abstd.py:34: note: Revealed type is "abstd.Too"
```

**Screenshots or Code**

See above

**VS Code extension or command-line**
pyright command line 1.1.276

**Comment by erictraut** [comment]
The code above will generate an exception if you run it in the python interpreter:

`NameError: name 'Foo' is not defined`

Mypy doesn't detect this class of error.

The way to correct this in the code is to enclose the type argument `Foo` in quotes.
`class Foo(SupportsAbs["Foo"]): ...`

If you fix this bug, pyright and mypy evaluate the same types.

**Comment by Dr-Irv** [comment]
There is still something that seems funky here with respect to the class `Too`  :
```python
class Too(timedelta):
    def __abs__(self) -> Too:
        ...


t = Too()
reveal_type(abs(t))
reveal_type(t.__abs__())
```
The revealed types here are `timedelta` and `Too`, respectively.  I don't understand why the revealed type of `abs(t)` is `timedelta` as opposed to `Too`.

**Comment by erictraut** [comment]
Mypy generates the same answer here. It comes from the fact that the `timedelta` class is declared as follows:

`class timedelta(SupportsAbs[timedelta]): ...`

This is a bit fishy and doesn't reflect the runtime class hierarchy, so it's arguably a bug in the typeshed definition for `timedelta`.

Both pyright and mypy use a shortcut for protocol matching when a class claims to directly derive from a protocol class. Rather than checking the types of all members of that protocol, they use the direct base protocol class.

**Comment by erictraut** [comment]
I've incorporated the updated typeshed stubs and confirmed that the behavior that you found to be unexpected no longer occurs. The updated typeshed stubs will be included in the next release of pyright.
