### ISSUE TITLE
Hundreds of reportGeneralTypeIssues

### ISSUE THREAD

**Issue by GiorgosXou** [microsoft/pyright#4089]
## Describe the bug
In many cases such in this specific [code](https://github.com/GiorgosXou/untappdscr/blob/main/untappdscr/__init__.py) *(which runs perfectly fine)* hundreds of  *(mainly)* `reportGeneralTypeIssues`-errors appear from nowhere. In previous versions of `pyright` this didn't happen.

## To Reproduce
Just open this [code](https://github.com/GiorgosXou/untappdscr/blob/main/untappdscr/__init__.py) in your edditor *(I don't really know how to explain it in simplier terms)*.

## Expected behavior
Maybe this shouldn't happen? Maybe `reportGeneralTypeIssues` shouldn't default to `error`, I don't really know... but the thing is that it happens and I'm really confushed as to why it happens, any Idea?

## Screenshots or Code
![image](https://user-images.githubusercontent.com/11987271/197575470-3359cdd9-3163-4998-86f0-a69f1549fdce.png)

## Additional context
I use [AstroNvim](https://github.com/AstroNvim/AstroNvim) and here's my [config file](https://github.com/GiorgosXou/our-neovim-setup), i'm also using the latest version of pyright

**Comment by erictraut** [comment]
Pyright is a static type checker. It's a tool that allows you to write more robust and maintainable code. Code that "runs perfectly" often contains latent bugs that show up later when you expose the code to new inputs or make some change to the code base that violates an existing assumption.

If you don't find value in static type checking, you have the choice of disabling all type violation errors — or uninstalling pyright altogether.
