### ISSUE TITLE
`pyright --createstubs foo` sometimes creates an incorrect nested folder structure

### ISSUE THREAD

**Issue by Josverl** [microsoft/pyright#4092]
**Describe the bug**
Depending in the existing stubs, an incorrect / weird folder structure is created to store the stubs.

Example nested and repeated stubs:
``` 
\---stubs
    +---bar
    |   \---stubs
    |       \---baz
    +---baz
    \---foo
        \---stubs
            +---bar
            \---baz
```

This appears to depend on the order in which stubs are generated; 
- if a module imports another module for which the stub already exists, an additional nested stub folder is created.

**To Reproduce**
pyright 1.1.276
Python 3.9.13
Windows 11

- create 3 python files, foo.py , bar.py , baz.py 
- foo imports bar, bar imports baz 

generating the stubs, in dependant first order results in a clean structure 
```
pyright --createstub  foo
pyright --createstub  bar
pyright --createstub  baz
```
```
+---.vscode
\---stubs
    +---bar
    +---baz
    \---foo
```
-------------------------------------

Below results in unwanted nesting 
```
pyright --createstub  baz
pyright --createstub  bar
pyright --createstub  foo
```
``` 
+---.vscode
\---stubs
    +---bar
    |   \---stubs
    |       \---baz
    +---baz
    \---foo
        \---stubs
            +---bar
            \---baz
```

**Expected behavior**
no nesting as all stubs are generated by pyright 

**Screenshots or Code**
foo.py
```python
# foo
import bar
class Foo:
    pass
```
baz.py
```
import baz
class bar(baz.Baz):
    pass
```

baz.py
```
# baz
class Baz:
    pass
```

pyproject.toml
```
[tool.pyright]

stubPath = "stubs"
pythonVersion = "3.8"
pythonPlatform = "Windows"

```

**Comment by erictraut** [comment]
You are using `--createstubs` in a way that it was not designed to be used. It is intended to create "draft" type stubs for installed libraries that are missing type information. You appear to be running it on code files within your own project!?!? Can you explain why you're doing this? If this is your own code, there's no reason to generate type stubs. You can (and should) add type annotations inline within your source files.

**Comment by Josverl** [comment]
@erictraut ,

I'm trying to use pyright to build type-only stubs for MicroPython, and specifically for the frozen files included in the firmware.
so when running pyright against MicroPython code intended to be run on a MCU or similar, the sources of the frozen modules are not available. 
Also due to the memory and CPU constrained nature, there are obstacles to adding type information inline to these modules directly, and these would be stripped as the modules are frozen to bytecode or machine code.

So for a MicroPython developer , these **are 3rd party modules** that are installed on the (remote) micropython machine.

I find that pyright produces better stubs for these to-be-frozen files than mypy's createstub, hence my exploration to see if it is possible to use pyright to create the stubs.

for reference: https://github.com/Josverl/micropython-stubs#what-do-you-get

**Comment by erictraut** [comment]
Pyright's stub creation assumes that you are creating stubs for an installed library, not your local project. If you want this to work, you'll need to install the library as you would normally. This typically means it will show up in your `site-packages` directory. If you try to run the `--createstub` option on your project, it will violate a bunch of assumptions, and you'll end up with a mess.

**Comment by Josverl** [comment]
Thanks for the clarification
In MicroPython normal is a bit different; there is no site-packages at all.
A subset of the modules/libraries can be installed on regular python for compatibility & testing , so I'll give that a spin to see if that process works better. 
For the modules that require specific hardware or processors, or depend specifically on micropython.  I'll continue to use mypy createstubs.
