### ISSUE TITLE
Pyright raises error when f-string is key for dict

### ISSUE THREAD

**Issue by JoeCSykes** [microsoft/pyright#4093]
**Describe the bug**
Pyright raises error when f-string is the key for a dict. The error is 

**To Reproduce**
          from typing import TypedDict
          
          class Test(TypedDict):
              mykey: int
          
          var: Test = {"mykey": 3}
          var: Test = {f"mykey": 3}

Error: Expression of type "dict[str, int]" cannot be assigned to declared type "Test" (reportGeneralTypeIssues)

**Expected behavior**
expect that the key can be a string or an f-string without raising error.

If your code relies on symbols that are imported from a third-party library, include the associated import statements and specify which versions of those libraries you have installed.

**VS Code extension or command-line**
running pyright version 1.1.276

**Comment by erictraut** [comment]
Why are you using an f-string here? 

An f-string is considered a dynamic expression. It does not produce a literal string because it must be evaluated at runtime to determine the actual string value. A `TypedDict` initialization requires literal string values for static type checking.

**Comment by JoeCSykes** [comment]
Ah yes I see what you mean and agree. 

It might be worth raising a more specific error message for this than the one currently being raised
