### ISSUE TITLE
Non json output generated when using --outputjson and --verifytypes

### ISSUE THREAD

**Issue by melching-jaai** [microsoft/pyright#4127]
**Describe the bug**
Output of pyright using `--outputjson` is not in json format.

**To Reproduce**
Running `pyright --outputjson --verifytypes <import>`

**Screenshots or Code**
Outputs the follwing on stdout:
```
Assuming Python platform Darwin
Assuming Python version 3.10
{
  ...
}
```

**VS Code extension or command-line**
command-line
version 1.1.278

**Comment by erictraut** [comment]
This is included in pyright 1.1.279, which I just published.
