### ISSUE TITLE
Fail to infer decorated function arguments

### ISSUE THREAD

**Issue by tamuhey** [microsoft/pyright#413]
Is it difficult to infer the arguments of decorated function?
For example, pyright fails to infer the below code:
```python
from toolz import curry


@curry
def add(x: int, y: int) -> int:
    return x + y


add3 = add(3) # raise: Argument missing for parameter 'y'
```

**Comment by erictraut** [comment]
A decorator can completely change the signature of the decorated function. If the decorator isn't annotated, pyright has no visibility into how it is transforming the function. For that reason, it's really important for all decorators to have proper type annotations.

In cases where type annotations aren't found for a decorator, pyright currently makes the assumption that the decorator doesn't modify the decorated function's signature. That's a reasonable assumption most of the time. In the example you provided, that assumption fails.

I can't think of any solution here other than to encourage everyone to annotate their decorators.
