### ISSUE TITLE
Option to ignore `reportUninitializedInstanceVariable` in stubs

### ISSUE THREAD

**Issue by Avasam** [microsoft/pyright#4137]
**Is your feature request related to a problem? Please describe.**
`reportUninitializedInstanceVariable` is raised in type stubs. Since there's not way to disable rules per folder or file-type, I have to disable it entirely or add `# pyright: reportUninitializedInstanceVariable=false` at the top of all my stubs.

**Describe the solution you'd like**
An option to ignore `reportUninitializedInstanceVariable` in `.pyi` files specifically.

**Additional context**
A workaround is to add `=...` but that does no comply with Typeshed's practices.
Since both are valid, this is more of a stylistic choice. Enforcing it forces redundancy.

**Comment by erictraut** [comment]
I agree that this check doesn't make sense for stub files. I've changed pyright to skip the check entirely for stubs. This will be included in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.279, which I just published. It will also be included in a future version of pylance.
