### ISSUE TITLE
Narrow nested union fields in match statement

### ISSUE THREAD

**Issue by otonnesen** [microsoft/pyright#4139]
**Is your feature request related to a problem? Please describe.**
Pyright does not narrow when matching nested union fields.

**Describe the solution you'd like**
I'd like `never` in the third match arm in the example below to be inferred as `Never` rather than `Foo | Bar`.

**Additional context**
```python
from dataclasses import dataclass
from typing import reveal_type


class Foo: pass
class Bar: pass

@dataclass
class Baz:
    a: Foo | Bar

match Baz(Foo()):
    case Baz(a=Foo() as foo):
        reveal_type(foo)  # Type of "foo" is "Foo"
    case Baz(a=Bar() as bar):
        reveal_type(bar)  # Type of "bar" is "Bar"
    case Baz(a=never):
        reveal_type(never)  # Type of "never" is "Foo | Bar"
```

**Comment by erictraut** [comment]
I think this is asking too much of the type narrowing logic. Not surprisingly, mypy also doesn't perform type narrowing in this case. 

You'll need to find some other workaround.

**Comment by otonnesen** [comment]
Understandable. I suppose it's simple enough to just match the field on its own to get the exhaustiveness I'm looking for (at the expense of a little more screen real estate), eg:
```python
match Baz(Foo()):
    case Baz(a=a):
        match a:
            case Foo() as foo:
                reveal_type(foo)  # Type of "foo" is "Foo"
            case Bar() as bar:
                reveal_type(bar)  # Type of "bar" is "Bar"
            case never:
                reveal_type(never)  # Type of "never is "Never"
```

Appreciate the quick response!
