### ISSUE TITLE
don‘t  inspect import lib may more compatible

### ISSUE THREAD

**Issue by aboutmydreams** [microsoft/pyright#415]
Import 'requests' could not be resolvedpyright (reportMissingImports)
![image](https://user-images.githubusercontent.com/34613360/70674582-64956680-1cc1-11ea-9379-2b750bd46896.png)

**Comment by erictraut** [comment]
You need to configure pyright so it knows how to locate the import. It supports multiple ways to specify search paths. Please refer to [the documentation](https://github.com/microsoft/pyright/blob/master/docs/import-resolution.md).
