### ISSUE TITLE
Document how to test your own local library with `--verifytypes`

### ISSUE THREAD

**Issue by Avasam** [microsoft/pyright#4152]
**Is your feature request related to a problem? Please describe.**
I wanna run `--verifytypes` on a library where I want to improve the type completeness score. (either because I'm adding a `py.typed` marker, or simply completing missing annotations)

Running `pyright --verifytypes the_lib` doesn't work because the version found in `site-packages` isn't the one I'm actively working on.

**Describe the solution you'd like**
I would like https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#verifying-type-completeness to explain how to run `--verifytypes` on a local library in my working directory.

**Additional context**
After a while of searching around, I found the `--editable` flag in pip. Running the following command first `pip install -e .` (where `.` is the path to the folder containing `setup.py`) finally allowed me to test locally. I think that a mention of this could be useful in the doc, for those who are less familiar.

**Comment by erictraut** [comment]
Editable installs are pretty well known in the Python ecosystem, especially among library authors and maintainers. I don't think the "verifying type completeness" doc is the right place to document this.

**Comment by Avasam** [comment]
Alright, guess I just hadn't learned about it yet.

**Comment by byarbrough** [comment]
I didn't know about the `-e` option and was helped out by this issue.
