### ISSUE TITLE
Remove root directory from search path

### ISSUE THREAD

**Issue by zdc13** [microsoft/pyright#4172]
**Is your feature request related to a problem? Please describe.**
When running pyright, it will add the root path to the search path, which is undesirable if using relative paths and is prone to errors, since behavior when running is dependant on the cwd. For exemple, if I have a requests.py in my root path and `import requests`, it will resolve it instead of the requests module and break lsp.

**Describe the solution you'd like**
Root folder is not added to search path (or an option?).

**Additional context**

**Comment by erictraut** [comment]
You should be able to handle this through the use of "execution environments" in the pyright config file. This is the use case they were designed for. The root directory of the execution environment is automatically added to the search path, but if the execution environment is a subdirectory within your main project, the main project's root directory will be omitted.

**Comment by erictraut** [comment]
> Also what if there is only one directory?

You will need to create a subdirectory to make this work.

If an import statement within a module references another module within the same directory (as in your example), Python's loader mechanism will resolve to that local module. Is your intent is to copy the module to a new location (one where that other peer module is no longer present) before executing it? If so, then it would make sense to put the module into its own subdirectory and treat it as a separate execution environment. Execution environments were meant to model different executable boundaries within a monorepo.

**Comment by zdc13** [comment]
@erictraut What I mean is the import statement (`import requests`) refers to the global scope, which shouldn't include the root directory. Local import are for that (`from . import requests`). Note that a local import depends on the module location w/r to the importing module, whereas unqualified imports (`import requests`) do not (1). This is in line with how pip will install packages (where `import requests` will not consider the execution environment for import resolution, but will include the globally available `requests` module).

(1) They actually do if executed normally `python test.py` (which I think is a design mistake), but do not if executed as a module, when called as an entrypoint of an installed module or when imported by a module not in the same execution context. https://docs.python.org/3/library/sys_path_init.html

The example in https://github.com/microsoft/pyright/issues/4172#issuecomment-1308943267 does not work if called directly, but works when installed as a module, sorry for the confusion.
