### ISSUE TITLE
Inheriting and overriding descriptor protocol behaviour from `builtins.property` silently has no effect

### ISSUE THREAD

**Issue by bzoracler** [microsoft/pyright#4192]
**Describe the bug**

Creating a subclass of `builtins.property` then overriding `__get__` has no effect.

**To Reproduce**
```python
from typing import Generic, Callable, TypeVar

_R = TypeVar("_R")

class StaticProperty1(Generic[_R]):
    def __init__(self, fget: Callable[[], _R], /) -> None: ...
    def __get__(self, __obj: None, __type: type, /) -> _R: ...

class StaticProperty2(property, Generic[_R]):
    def __init__(self, fget: Callable[[], _R], /) -> None: ...
    def __get__(self, __obj: None, __type: type, /) -> _R: ...  # type: ignore[override]

class C:
    @StaticProperty1
    def prop1() -> int: ...
    @StaticProperty2
    def prop2() -> int: ...
```

**Expected behavior**
```python
>>> reveal_type(C.prop1)      # Pylance: Type of "C.prop1" is "int"
>>> reveal_type(C().prop1)    # Pylance: Cannot access member "prop1" for type "C"
>>> reveal_type(C.prop2)      # Pylance: Type of "C.prop2" is "int"
>>> reveal_type(C().prop2)    # Pylance: Cannot access member "prop2" for type "C"
```

**Screenshots or Code**

Pyright's current behaviour is:

```python
>>> # Expected
... reveal_type(C.prop1)      # Pylance: Type of "C.prop1" is "int"
>>> # Expected
... reveal_type(C().prop1)    # Pylance: Cannot access member "prop1" for type "C"
>>> # Unexpected; `__get__` specifies the return type
... reveal_type(C.prop2)      # Pylance: Type of "C.prop2" is "StaticProperty2"
>>> # Unexpected; parameter `__obj` of `__get__` is `None`, no signature exists for `__obj: C`
... reveal_type(C().prop2)    # Pylance: Type of "C().prop2" is "int"
```

**VS Code extension or command-line**
This was reproduced inside of Visual Studio Code:
 - Visual Studio Code Version: 1.73.1
 - Pylance  v2022.11.20

**Comment by erictraut** [comment]
Yeah, I wouldn't expect this to work. The `property` class is highly special-cased in type checkers. There are many hacks that are needed to make the common use cases work. I recommend against subclassing from `property` if you want your code to work with static type checkers.

**Comment by bzoracler** [comment]
Thanks for the explanation. Is there currently no way of expressing specifically the subclass relation in pyright, and also retain the descriptor protocol? I didn't want to resort to this, which (while works) is deprecated:

```
class C:
    @classmethod
    @StaticProperty2
    def prop2(cls) -> int: ...
```

I'm trying to create stubs for a third-party package which has implemented this as a proper subclass of `builtins.property` (`Boost.Python.StaticProperty`; MRO `[<class 'Boost.Python.StaticProperty'>, <class 'property'>, <class 'object'>]`).

**Comment by erictraut** [comment]
You could try modeling this as a custom descriptor class, one that doesn't derive from `property` but has the relevant semantics of `property`. I realize that might not accurately reflect the implementation in the third-party library, but it might be worth the tradeoff.
