### ISSUE TITLE
Narrow Types of variables in Tuples in Match Statement

### ISSUE THREAD

**Issue by mezuzza** [microsoft/pyright#4208]
**Is your feature request related to a problem? Please describe.**
Take the following code:
```python
def test(a: int | None, b: int | None):
  match a, b:
    case None, None:
      a = 1
      b = 2
    case _, None:
      b = 3
      a + b # a is int | None
    case None, _:
      a = 4
      a + b # b is int | None
    case _, _:
      a + b # both are int | None
  return a + b # both are int | None
```
It's a common pattern I've picked up from other languages. I'd expect both a and b to be not null by the end of the match statement, but pyright is unable to see that.

If you do the same code, but with an `elif` ladder, you get #4207 which seems like a bug (code reproduced below for convenience). But this one produces odd behavior.
```python
def test(a: int | None, b: int | None):
  if a is None and b is None:
    # branch 1
    a = 1
    b = 2
  elif b is None:
    # branch 2
    b = 3
    a + b  # a is int | None
  elif a is None:
    # branch 3
    a = 4
    a + b
  else:
    # branch 4
    a + b
  return a + b  # a is int | None
```

It also seems that the one variable case works just fine: 
```python
def test4(a: int | None):
  match a:
    case None:
      a = 3
    case _:
      pass
  return a + 4
```

**Describe the solution you'd like**
I want match statements to narrow the type of variables inside tuples. Ideally, this would work with a defined subset of iterables in general, but I suppose that the special case of tuples is more likely than the rest.

**Additional context**
```sh
» python --version
Python 3.10.8
» pyright --version
pyright 1.1.280
```

**Comment by erictraut** [comment]
Pyright does narrow the type of the target expression (in this case, a tuple), but narrowing does not apply to individual subexpressions that are used within the target expression (in this case, `a` and `b`).

**Comment by mezuzza** [comment]
Yea, that's what I figured, but - playing devil's advocate here - would it be bad to special case `Tuple` in particular? The language clearly treats tuple in a special way given how it treats match and return.

```
match a, b:
```

```
return a, b
```

**Comment by JelleZijlstra** [comment]
The language doesn't treat tuples specially there. That's just syntax for a tuple.

**Comment by kwshi** [comment]
I'm also coming across this; I second that it would be a very nice enhancement to have narrowing for tuples apply to subexpressions within the tuple. Here's my real-world (ish) example:
```python
T = int | list[int]
def compare(a: T, b: T) -> int:
  match a, b:
    case int(), int():
      # compare `a` and `b` directly
      return a-b

    case list(), list():
      # compare `a` and `b` lexicographically
      for x, y in zip(a, b):
        if x != y: return x-y
      return len(a) - len(b)

    case int(), list():
      # convert the int to a singleton list, then compare lexicographically
      return compare([a], b)

    case list(), int():
      # same as above
      return compare(a, [b])

```

The `match` way of disambiguating/narrowing types of `a` and `b` seems the cleanest, but it's unsupported by pyright. Here are the alternatives I can think of, each of which is in my opinion either unpleasantly verbose or somewhat unreadable:

```python
# I think this is acceptable, but a little annoyingly verbose when `match` exists
def compare_isinstance(a: T, b: T) -> int:
  if isinstance(a, int) and isinstance(b, int):
    # compare `a` and `b` directly
    return a-b

  if isinstance(a, list) and isinstance(b, list):
    # compare `a` and `b` lexicographically
    for x, y in zip(a, b):
      if x != y: return x-y
    return len(a) - len(b)

  if isinstance(a, int) and isinstance(b, list):
    # convert the int to a singleton list, then compare lexicographically
    return compare([a], b)

  if isinstance(a, list) and isinstance(b, int):
      # same as above
      return compare(a, [b])

# pyright narrows types effectively here, but the nested match is very annoying to write
# & disrupts logical flow of code, making is kind of unreadable
def compare_nested_match(a: T, b: T) -> int:
  match a:
    case int():
      match b:
        case int(): return a-b
        case list(): return compare([a], b)
    case list():
      match b:
        case int(): return compare(a, [b])
        case list():
          for x, y in zip(a, b):
            if x != y: return x-y
          return len(a)-len(b)
```

Of these options I think the `match` code is definitely the cleanest & most elegant implementation (if anyone can think of something better, I'm all ears). Can I survive using `if` and `isinstance`? Sure, but ideally I shouldn't have to compromise on the cleanliness of my code in order to enable type-checking. Point being, regardless of whether Python inherently treats tuples specially, I do think having this feature would be tremendously nice in pyright.

**Comment by brasswood** [comment]
Joining the bandwagon. Here's something I tried in order to work around #10736:

```python
import random

def mystery() -> float | None:
    if bool(random.getrandbits(1)):
        return random.random()
    else:
        return None

def main():
    x = mystery()
    y = mystery()
    z = mystery()
    if type((x, y, z)) != tuple[float, float, float]:
        return
    reveal_type((x, y, z)) # tuple[float | None, float | None, float | None]

main()
```
