### ISSUE TITLE
Overloaded decorators can hide parameters with default values

### ISSUE THREAD

**Issue by wlritchi** [microsoft/pyright#4211]
**Describe the bug**

Some decorators change the type of the decorated function's inputs. Because there is no easy way to describe a "mapping" over a ParamSpec, such decorators may be typed with a series of overloads, one for each number of parameters up to a reasonable maximum:

```python
@overload
def boxed_args(
    func: Callable[[_P1], _R],
) -> Callable[[Box[_P1]], _R]:
    pass

@overload
def boxed_args(
    func: Callable[[_P1, _P2], _R],
) -> Callable[[Box[_P1], Box[_P2]], _R]:
    pass

@overload
def boxed_args(
    func: Callable[[_P1, _P2, _P3], _R],
) -> Callable[[Box[_P1], Box[_P2], Box[_P3]], _R]:
    pass

...
```

When such a decorator is applied to a function with default values for one or more parameters, Pyright selects the first matching overload for the decorator, i.e. the overload with only the required parameters. It then forgets about the parameters with default values:

```python
# inferred type (Box[str]) -> None
@boxed_args
def takes_str_and_default_int_decorated(p1: str, p2: int = 404) -> None:
    print(p1, p2)

# does not typecheck
takes_str_and_default_int_decorated(Box("Luc"), Box(0))
```

**To Reproduce**

Run Pyright via the command-line, or observe the inferred types via Pylance.

```
pyright 1.1.280
/home/wlritchi/oss/python-tooling-sandbox/sandbox/__init__.py
  /home/wlritchi/oss/python-tooling-sandbox/sandbox/__init__.py:63:53 - error: Expected 1 positional argument (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
```

<details>
<summary>Full output</summary>

```
No configuration file found.
pyproject.toml file found at /home/wlritchi/oss/python-tooling-sandbox.
Loading pyproject.toml file at /home/wlritchi/oss/python-tooling-sandbox/pyproject.toml
Assuming Python platform Linux
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /home/wlritchi/oss/python-tooling-sandbox/typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.280
/home/wlritchi/oss/python-tooling-sandbox/sandbox/__init__.py
  /home/wlritchi/oss/python-tooling-sandbox/sandbox/__init__.py:63:53 - error: Expected 1 positional argument (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
Completed in 0.877sec
```
</details>

**Expected behavior**

The inferred type for the decorated function should be overloaded based on each matching overload of the decorator. In the example above, the decorated function should have a type equivalent to `(Box[str]) -> None` overloaded with `(Box[str], Box[int]) -> None`.

**Screenshots or Code**

Complete example [on GitHub](https://github.com/wlritchi/python-tooling-sandbox/blob/variadic-decorator-with-default-params/sandbox/__init__.py)

<details>
<summary>Inline:</summary>

```python
#!/usr/bin/env python3

from abc import ABC
from functools import wraps
from typing import Any, Callable, Generic, TypeVar, overload

_T = TypeVar('_T')


class Box(ABC, Generic[_T]):
    def __init__(self, value: _T):
        self.value = value


_P1 = TypeVar('_P1')
_P2 = TypeVar('_P2')
_P3 = TypeVar('_P3')
_R = TypeVar('_R')


@overload
def boxed_args(
    func: Callable[[_P1], _R],
) -> Callable[[Box[_P1]], _R]:
    pass


@overload
def boxed_args(
    func: Callable[[_P1, _P2], _R],
) -> Callable[[Box[_P1], Box[_P2]], _R]:
    pass


@overload
def boxed_args(
    func: Callable[[_P1, _P2, _P3], _R],
) -> Callable[[Box[_P1], Box[_P2], Box[_P3]], _R]:
    pass


def boxed_args(func: Callable[..., _R]) -> Callable[..., _R]:
    @wraps(func)
    def wrapper(*args: Any) -> _R:
        return func(*(arg.value for arg in args))

    return wrapper


def takes_str_and_default_int(p1: str, p2: int = 404) -> None:
    print(p1, p2)


@boxed_args
def takes_str_and_default_int_decorated(p1: str, p2: int = 404) -> None:
    print(p1, p2)


if __name__ == '__main__':
    # typechecks successfully
    takes_str_and_default_int("Typechecker", 1)
    # does not typecheck
    takes_str_and_default_int_decorated(Box("Luc"), Box(0))
```
</details>

**VS Code extension or command-line**

pyright 1.1.280 via [pyright-python](https://github.com/RobertCraigie/pyright-python)

**Additional context**

mypy and Pyre both have very similar bugs; discussion at python/mypy#14144 and facebook/pyre-check#693 may be relevant if this is a weakness in the Python type system rather than in Pyright's implementation.

**Comment by erictraut** [comment]
I think pyright (and mypy and pyre) are doing the right thing here. I don't consider this a bug. Default values are not captured by a `Callable` unless you use a `ParamSpec`. In your example above, you're using normal type variables, not a `ParamSpec`, and a `TypeVar` has no way of capturing the notion of "a parameter that has a default argument value". 

I see what you're trying to do here, but you're abusing the Python type system in a way that it wasn't intended to be used.
