### ISSUE TITLE
Relative imports with 1.1.280 and reportMissingModuleSource = true are incorrectly reported

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#4212]
**Describe the bug**
In the pandas-stubs repo, our type checking works fine with pyright 1.1.279.  But with 1.1.280, the relative imports are coming up as " Import ".rolling" could not be resolved from source (reportMissingModuleSource)" .  (for example)  We have `reportMissingModuleSource=true`, but this wasn't an issue with version 1.1.279

**To Reproduce**
Install the pandas-stubs repo, and do `pyright pandas-stubs` with `pyright` version 1.1.280

**Comment by erictraut** [comment]
Apologies for the regression. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.281, which I just published. It will also be included in a future release of pylance.
