### ISSUE TITLE
Metaclass instance functions not resolving in child class

### ISSUE THREAD

**Issue by Twistedsnail** [microsoft/pyright#4214]
<h3> Environment data </h3>

-   Language Server version: 2022.11.30
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

```python
import typing
import types

SELF_TYPE = typing.TypeVar('SELF_TYPE')

class A(type):
    def __enter__(cls: SELF_TYPE) -> SELF_TYPE:
        print("Enter A")
        return cls
    
    def __exit__(cls, exc_typ: type[Exception], exc_val: Exception, exc_tbc: types.TracebackType) -> None:
        print("Exit A")

class B(metaclass=A):
    ...


with B as b:
    ...
```

<h3> Expected behavior </h3>

No errors are thrown and type[b] is B

<h3> Actual behavior </h3>

Pylance errors thrown:
`Object of type "Type[B]" cannot be used with "with" because it does not implement __enter__`
`Object of type "Type[B]" cannot be used with "with" because it does not implement __exit__`

Even more surprisingly if I add
`assert isinstance(B, A)`
before the `with` statement, the errors turn into `Object of type "Never" ...` implying that the class B is not an instance of the metaclass A, which it is.

`B.__enter__()` also hints as `Never` while runtime and mypy correctly have `<class 'B'>` and `Type[B]` respectively.

This doesn't align with runtime or mypy behaviour.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.
