### ISSUE TITLE
Adding support NotebookDocumentClientCapabilities in pyright-python-langserver

### ISSUE THREAD

**Issue by MrBago** [microsoft/pyright#4222]
The LSP 3.17 specification added support for notebook documents via NotebookDocumentClientCapabilities. I think it would be awesome if pyright could support this part of the specification and provide analysis for notebook documents.

I'd like to understand what would need to be added to pyright and how much effort it would be to add support for notebook documents.

If there is interest in including this improvement in pyright and someone could help provide guidance on the work, I may have capacity to work on this and submit a patch.

**Comment by erictraut** [comment]
While pyright does have some basic language server capabilities, it is focused on static type checking. We don't have plans to expand its language server functionality beyond what it provides currently.

Pylance (Microsoft's Python language server built on pyright) already supports notebooks. If you're interested in that functionality, please use Pylance.
