### ISSUE TITLE
More specific diagonistic rule for "... is not a known member of" errors

### ISSUE THREAD

**Issue by wookayin** [microsoft/pyright#4235]
**Is your feature request related to a problem? Please describe.**
Currently "... is not a known member of" errors, often being false-positive due to dynamic attributes or lazy-loading is classified as the `reportGeneralTypeIssues` rule. Can we assign a more specific rule or diagnostic category for such errors?

**Describe the solution you'd like**
For example, `reportUnknownMember` or some other names whichever are appropriate.

The reason why I'm asking this is: It would be nice to ignore some false-positive errors manually by `# pyright: ignore [...]` directives, but `reportGeneralTypeIssues` is too general so I would like to avoid doing `# pyright: ignore [reportGeneralTypeIssues]`.

**Additional context**

https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/common/diagnosticRules.ts#L13

**Comment by erictraut** [comment]
Reporting accesses to undeclared attributes is one of the main jobs of a static type checker, so I don't think it would make sense to place this check under a separate diagnostic rule.

Static type checking is intended to help produce more robust and bug-free code and to catch bugs prior to execution. If you're interested in gaining these benefits of static type checking, I recommend avoiding the use of dynamic attributes in general. In cases where a class is intended to be used with dynamic attributes, you can define a `__getattr__` and `__setattr__` method on the class, which indicates your intent to the type checker that such dynamic behavior is intended.

**Comment by wookayin** [comment]
Thank you Eric for the fast feedback. That makes sense, and I respect the team's decision.

One side note is that such false-positive errors are often in regard to third-party libraries we don't have much control over AND lacking stub files. For instance, `np.random.RandomState` (numpy; which is however fixed as of the latest pyright + latest numpy version), and tensorflow/torch also used to have such issues.

I am not aware of any other solution that makes use of `TYPE_CHECKING` to work around the false-positive reports rather than simply ignoring them.

**Comment by erictraut** [comment]
Thanks for the additional context. Can you provide more details about `np.random.RandomState`? How does it require the use of dynamic attributes? Additional examples with numpy and tensorflow/torch would also be helpful.
