### ISSUE TITLE
Variable defined within if condition marked as undefined within if body

### ISSUE THREAD

**Issue by iamexe** [microsoft/pyright#4264]
**Describe the bug**
Variable defined within if condition marked as undefined.

**To Reproduce**
The following code will run, variable will be defined yet it's marked as undefined
from os.path import exists
if exists(i = input("file: ")):
    (open(i,'r'))

**Expected behavior**
Variable not marked as undefined.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/60526252/205049670-ef0c7e49-d6a2-40d0-b309-d9bb85fd17f6.png)

**VS Code extension or command-line**
VS Code Python extension v2022.18.2
Pylance language server 2022.11.30 (pyright 04a10583)

**Comment by erictraut** [comment]
Pyright is correct here. The code in your example does not define a local variable `i`. It passes a keyword argument called `i` to the function `exists`. `exists` doesn't have a keyword parameter called `i`, so running the above code produces the following exception. `TypeError: exists() got an unexpected keyword argument 'i'`.

If your intent is to define a local variable `i`, you should use an assignment expression (walrus) operator `:=` like this:

```python
if exists(i := input("file: ")):
    (open(i,'r'))
```

**Comment by iamexe** [comment]
Ah okay. As I am just learning python your elaboration was useful to me.
Thank you very much for the elaboration!
