### ISSUE TITLE
reportShadowedImports triggers on __main__

### ISSUE THREAD

**Issue by Creonalia** [microsoft/pyright#4277]
**Describe the bug**
reportShadowedImports triggers on `__main__`

**To Reproduce**
Create a file named `__main__.py`

**Expected behavior**
There should not be any errors

**VS Code extension or command-line**
VS Code extension 2022.11.40

**Comment by erictraut** [comment]
Can you provide more details or repro steps?

**Comment by Creonalia** [comment]
That's it, there are no additional steps
![image](https://user-images.githubusercontent.com/52385967/205550602-c816c3c4-5c28-4ee3-9743-6c9b77dfda7d.png)

**Comment by erictraut** [comment]
Steps:
1. Create an empty source file called `__main__.py`
2. Create a `pyrightconfig.json` file and enable the `reportShadowedImports` configuration option

Resulting error message: `"__main__.py" is overriding the stdlib module \"__main__"`

**Comment by rchiodo** [comment]
This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.283, which I just published. It will also be included in a future version of pylance.

**Comment by IanDLacy** [comment]
This may be helpful to someone. Rather than temporarily disabling the feature, I found that if you open VSCode in the directory above `__main__.py`, you don't get the warning.
