### ISSUE TITLE
overload operator by value

### ISSUE THREAD

**Issue by dumbPy** [microsoft/pyright#428]
I am trying to overload a method based on argument value, more precisely by bool.
Disclaimer: I have also asked it on [stackoverflow](https://stackoverflow.com/questions/59359943/python-how-to-write-typing-overload-decorator-for-bool-arguments-by-value)

The example code of what I am trying to ask is below.  
None of the examples on the internet try to overload argument value as such.  
One of the argument is a bool value and I want to overload a method based on the bool value rather than the usual, argument type.

```python
from typing import overload, Union

@overload
def myfunc(arg:bool=True)-> str: ...

@overload
def myfunc(arg:bool=False)-> int: ...

def myfunc(arg:bool)->Union[int, str]:
    if arg: return "something"
    else: return 0
```

Is the overloading code in the above example code correct ?  
Can you give an example/blog/source that mentions this kind of overloading, since I couldn't find anything in Python docs and [pep-484](https://www.python.org/dev/peps/pep-0484/)

I found one probable way of doing it is with `typing.Literal` as used in [latest python docs (since python v3.8)](https://docs.python.org/3/library/typing.html#typing.Literal)
```python
from typing import overload, Union, Literal

@overload
def myfunc(arg:Literal[True])-> str: ...

@overload
def myfunc(arg:Literal[False])-> int: ...

def myfunc(arg:bool)->Union[int, str]:
    if arg: return "something"
    else: return 0

```
But I cannot move to python 3.8 just yet as I am working on production code that is still on python 3.6, soon upgrading to 3.7 at best.  
Hence I am still looking for answers on how to achieve this in python 3.6

**Comment by dumbPy** [comment]
Posted here since I couldn't find an answer on the internet and pyright being a static typechecker, people here would know this a lot better.

**Comment by erictraut** [comment]
You're on the right track. You need to use `Literal[True]` and `Literal[False]`. You can work around the need for Python 3.8 by importing Literal from `typing_extensions` and placing the annotation in quotes. This will prevent the python interpreter from evaluating the type at runtime.

**Comment by dumbPy** [comment]
Thank You!!!
pyright is the way !! :smile:
