### ISSUE TITLE
`reportPrivateImportUsage` error from exported import of an imported name

### ISSUE THREAD

**Issue by brentyi** [microsoft/pyright#4287]
**Describe the bug**

Hi! I'm coming from https://github.com/google/jaxtyping/pull/49, where we're running into some unexpected behavior with importing names that seem properly exported in an `__init__.py`.

It's probably best explained with an example --

When try to import certain names from our package, in this case `exporttest`, we're running into a reportPrivateImportUsage error:
```python
# try_import.py
from exporttest import _Assigned  # OK
from exporttest import Imported   # reportPrivateImportUsage error!
```

However, in `exporttest/__init__.py`, both names are actually exported using the `import X as X` convention!
```python
# exporttest/__init__.py
from .src import _Assigned as _Assigned
from .src import Imported as Imported
```

The difference ends up being how `Imported` and `_Assigned` are initially defined:
```python
# exporttest/src.py
from typing import List
from typing import List as Imported

_Assigned = List
```

**To Reproduce**
I've put a minimum example for reproducing this error in this repo: https://github.com/brentyi/jaxtyping-export-repro

**Expected behavior**
To be honest, I'm not entirely sure that this is a bug, but it's weird that the internal `exporttest <=> exporttest.src` interface is impacting the `exporttest <=> try_import.py` interface.

The short-term solution is to stick with the `_Assigned = List` pattern for making aliases, but this breaks for special types like `Annotated`. Adding an `__all__ = ["Imported", "_Assigned"]` to `src.py` also works (this is how https://github.com/google/jaxtyping/pull/49 currently suppresses the error), but feels cumbersome.

Is this considered a bug? Any suggestions for working around it?

**VS Code extension or command-line**
I'm running `pyright try_import.py` with `pyright 1.1.282`.

---

cc @patrick-kidger

**Comment by erictraut** [comment]
Thanks for preparing the detailed example.

This will be fixed in the next release.
