### ISSUE TITLE
no paramerter error on pydantic models when used with alias and "allow_population_by_field_name" 

### ISSUE THREAD

**Issue by rajshrestha86** [microsoft/pyright#4290]
For following pydantic model where we are allowed to populate by alias or field_name, I am getting no parameter and missing argument error on pyright.

**Code**
```python
from pydantic import BaseModel, Field


class User(BaseModel):
    full_name: str = Field(None, example="00000", alias="fullName")
    address: str

    class Config:
        allow_population_by_field_name = True


user = User(full_name="John", address="USA")
```

**Command-line**
Running pyright from a command-line gives following errors:
```bash
  ./main.py:12:13 - error: No parameter named "full_name" (reportGeneralTypeIssues)
  ./main.py:12:8 - error: Argument missing for parameter "fullName" (reportGeneralTypeIssues)
```

<br/>
Is this the expected behavior or do I need additional configurations to make it work with pydantic?

**Comment by erictraut** [comment]
Pyright doesn't support pydantic's non-standard `Config` mechanism. It supports only those features that are common to pydantic and `dataclass`. This is handled through the `dataclass_transform` mechanism described in [PEP 681](https://peps.python.org/pep-0681/).

**Comment by blast-hardcheese** [comment]
There doesn't seem to be a lot of documentation around this, so I'll leave the results of my experience here in case others find this issue as I did.

Ultimately I ended up with a PEP593-based solution, as I have more familiarity around `Annotated` over `dataclass_transformers`.

 To placate both pyright and mypy, the above example can be reformulated as such:

```python
from typing import Annotated
from pydantic import BaseModel, Field


class User(BaseModel):
    full_name: Annotated[str, Field(None, examples=["00000"], alias="fullName")]
    address: str

    class Config:
        allow_population_by_field_name = True


user = User(full_name="John", address="USA")
```

Thank you, pyright is an invaluable tool.
