### ISSUE TITLE
Cannot access member 'get' for type 'List[str]'   Member 'get' is unknown

### ISSUE THREAD

**Issue by danieldaeschle** [microsoft/pyright#430]
**Describe the bug**
```
{
	"resource": "/home/daniel/Projects/Python/ministry-shift-manager-identity/identity/views.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Cannot access member 'get' for type 'List[str]'\n  Member 'get' is unknown",
	"source": "pyright",
	"startLineNumber": 11,
	"startColumn": 38,
	"endLineNumber": 11,
	"endColumn": 41
}
```

**To Reproduce**
Install flask

**Expected behavior**
Works

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```
current_app.config.get('')
```

**VS Code extension or command-line**
VS Code extension

**Comment by erictraut** [comment]
To my knowledge, the built-in `List` class (which is simply an alias of `list`) doesn't support a `get` method. It's certainly not included in the stdlib typestub files for builtins.pyi.

I can't tell from your code example what type `current_app.config` is. I'd need more context to provide more guidance.

**Comment by danieldaeschle** [comment]
````pip install flask```

```
from flask import Flask, current_app

@app.get("/")
def index():
    current_app.config.get("value")

```

**Comment by erictraut** [comment]
I don't know enough about flask to understand what this code is supposed to do, but I think pyright is doing the right thing.

current_app.config is of type `Union[List[str], Any]`. Pyright is inferring this type from the flask implementation (refer to the `__getattr__` function in class `LocalProxy`). List has no `get` method, so this will fail if a list is returned. You can see this by running the following script, which produces an exception.

```
my_list = ['1', '2', '3']
my_list.get('1')
```

I can offer a couple of workarounds:
1. Find or create a type stub for flask that properly defines the input and return types for the library. You could use pyright to generate a "first draft" of these type stubs, but you'd need to hand edit them to add more type information. I'm not sure what type `LocalProxy.__getattr__` is meant to return. You'd need to do that research.
2. Add a cast to your code, casting `current_app.config` to the appropriate type before attempting to call `get`. Once again, I don't know what type it is intended to be.
3. Add an assert to constrain the type of `current_app.config`. This would look like `assert isinstance(X, current_app.config)` where `X` is the appropriate type.

**Comment by dzpt** [comment]
@erictraut there are many `get` usecases in Flask.
`request.form.get`
`request.args.get`

any chance to ignore or blacklist this particular case in config file?
