### ISSUE TITLE
Consider evaluating apipkg.initpkg (py.xml)

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/pyright#431]
**Is your feature request related to a problem? Please describe.**
Consider evaluating apipkg.initpkg. For example, in `py` several modules are added dynamically. Alternative, of course, to craft a stub. However, it is probably not too complicated to special case population of tuples?
```python
apipkg.initpkg(__name__, attr={'_apipkg': apipkg, 'error': error}, exportdefs={
    # access to all standard lib modules
    'std': '._std:std',

    '_pydir' : '.__metainfo:pydir',
    'version': 'py:__version__', # backward compatibility

    # pytest-2.0 has a flat namespace, we use alias modules
    # to keep old references compatible
    'test' : 'pytest',
...
```

**Describe the solution you'd like**
Constructions such as `from py.xml import html` to just work.

**Comment by erictraut** [comment]
I've consistently stuck with the principle that Pyright would include special-case logic only for modules and types that are part of the Python spec. Since apipkg is a third-party library and not part of the Python spec, it doesn't meet that bar.
