### ISSUE TITLE
Can't type a generic with a recursive type alias (within that type alias definition)

### ISSUE THREAD

**Issue by evtn** [microsoft/pyright#4315]
**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
from typing import Generic, TypeVar, Union

class A: pass

T = TypeVar("T", bound=A)

class B(A, Generic[T]): pass
class C(A): pass

D = Union[B["D"], C] # same error with `D = B["D"]` line, but then the line wouldn't make much sense
```

This produces:
```
   10:13  error   Type "D" cannot be assigned to type variable "T@B" ​Pyright:reportGeneralTypeIssues
                    Type "D" is incompatible with bound type "A" for type variable "T@B"
                      Type "D" cannot be assigned to type "A"
```
It seems to me that it is trivial to check that `B` is a subtype of `A` and so that it can be a generic parameter of `B`.
Moreover, replacing `"D"` inside brackets to, e.g. `Union[B[Any], C]` would fix the problem (while making types less precise).

I've stumbled on #2717 in my search for solution, it is similar but from the reply there looks like it is specific to dataclasses.

**VS Code extension or command-line**
lsp-pyright in Sublime Text 4

**Comment by erictraut** [comment]
This is a form of recursion that pyright doesn't currently support. The bound of the type variable is validated at the time that `B["D"]` is evaluated, but the definition of `D` hasn't yet been determined at that point.

I've added additional logic to skip the false positive error in this case, but the change effectively skips the bound (or constraint) check when the type argument is a partially-evaluated recursive type alias. That means that there could be a false negative, but it's better than a false positive.

This change will be in the next release.
