### ISSUE TITLE
"Unconditional" exception caught by context manager causes unreachable code

### ISSUE THREAD

**Issue by Terrance** [microsoft/pyright#4318]
#### Describe the bug

When using a context manager that consumes certain well-known exceptions, in a way that unconditionally throws one of those exceptions, any code following that block is considered unreachable.

#### To reproduce

I encountered this whilst trying to use [psycopg transactions](https://www.psycopg.org/psycopg3/docs/basic/transactions.html#transaction-contexts) in a unit test, where I want to attempt a database change and make assertions on it, but then rollback the whole change each time:

```python
from psycopg import connect, Rollback

def main():
    db = connect(...)
    with db.transaction():
        ...  # Create test models/data etc.
        raise Rollback
    ...  # pyright: Code is unreachable
```

For the actual code I'm writing, I can replace this usage with a non-context solution and the likes of `db.rollback()` instead, though this isn't the only library I've seen that consumes well-known exceptions in this way.

#### Expected behavior

Ideally this wouldn't be considered dead code, though I realise this is likely an awkward corner case, and I suspect there's not enough type information to indicate that context managers can consume certain exception types like this.

#### Third-party libraries

In this case I'm using the latest version of psycopg, 3.1.4.

#### VSCode extension

Pyright v1.1.283 / Pylance v2022.12.20

**Comment by erictraut** [comment]
Some context managers "swallow" all exceptions, while most do not. The standard way to tell a type checker which behavior a context manager employs is by specifying a different return type for the `__exit__` method.

```python
class ContextManager1:
    # A return type of Literal[True] or bool indicates that this
    # context manager swallows exceptions.
    def __exit__(self, *exc_info: object) -> bool: ...

class ContextManager2:
    # A return type of Literal[False] or None indicates that this
    # context manager does not swallow exceptions.
    def __exit__(self, *exc_info: object) -> None: ...
```

The context manager defined by psycopg in this case is defined to _not_ swallow exceptions, so pyright (and other type checkers like mypy) will therefore conclude that the exception raised within the `with` block will propagate outside of the block, and the subsequent code will be unreachable.

So, this is a bug in psycopg that you'd need to report to that library's maintainers.
