### ISSUE TITLE
Support inlayhint feature

### ISSUE THREAD

**Issue by leaxoy** [microsoft/pyright#4325]
Recently LSP 3.17 support inlayhint to insert some hint msg.

**Comment by erictraut** [comment]
Pyright is focused on type checking. It supports some basic language server features, but we don't have plans to add any new language server features to pyright.

Inlay hints are already supported by pylance, which adds language server features on top of pyright's core type checking functionality.

**Comment by leaxoy** [comment]
That's a pity, because pylance is not open source, many people can't use advanced LSP features without using vscode.

**Comment by DetachHead** [comment]
[basedpyright](https://github.com/DetachHead/basedpyright) and [pyright-inlay-hints](https://github.com/jbradaric/pyright-inlay-hints) both support inlay hints
