### ISSUE TITLE
Pyright classifies unannotated abstractmethod return as `None`

### ISSUE THREAD

**Issue by smackesey** [microsoft/pyright#4333]
**Describe the bug**

It's possible that this is "as designed", but this behavior seems surprising to me:

```
from abc import ABC, abstractmethod

class Foo(ABC):

    @abstractmethod
    def foo(self):
        ...


def takes_foo(foo_obj: Foo):
    foo_obj.foo()  # has type of `None`
```

It looks like the same inference rules applied to normal methods are applied to abstract methods, so that the lack of a return statement in the abstract method causes pyright to infer a type of `None`. But since abstract methods can never have a return statement in the body, this is an unjustified inference-- it seems more sensible to have an `Unknown` return type for an unannotated abstract method.

**Comment by erictraut** [comment]
Inferring `None` in this case is as designed. You should provide an explicit return type annotation in this case.
