### ISSUE TITLE
Variadic overloads overlapping

### ISSUE THREAD

**Issue by Lee-matod** [microsoft/pyright#4344]
**Describe the bug**
When overloading a function signature with variadic parameters and type hinting a variadic keyword-only argument, pyright will think that the overloads still overlap, producing the error below.
```python
Overload 2 for "send" will never be used because its parameters overlap overload 1
```

**To Reproduce**
Pyright needs to be set to its strict mode, and you should be able to reproduce it with this code snippet:
(`Message` and `Handler` can be changed for any type)
```python
@overload
async def send(*args: str, handler: Literal[None] = ..., **options: Any) -> Message:
    ...

@overload
async def send(*args: str, handler: Handler = ..., **options: Any) -> tuple[Message, Handler]:
    ...

async def send(*args: Any, **options: Any) -> Any:
    handler: Handler | None = options.get("handler")
    # etc
```

**Comment by erictraut** [comment]
I'm not able to repro with this code sample. Could you provide additional context? In particular, the symbols `Message` and `Handler` are not defined above. 

Here's the modified sample that I used to try to repro the problem:

```python
# pyright: strict

from typing import Any, Literal, overload

class Message: ...
class Handler: ...

@overload
async def send(*args: str, handler: Literal[None] = ..., **options: Any) -> Message:
    ...

@overload
async def send(*args: str, handler: Handler = ..., **options: Any) -> tuple[Message, Handler]:
    ...

async def send(*args: Any, **options: Any) -> Any:
    handler: Handler | None = options.get("handler")
```

**Comment by Lee-matod** [comment]
After further testing, I have realized that this is an issue on my end. Apparently `Handler` was the thing that was causing it to error (I'm guessing it's because it's an instance instead of a class?). I apologize for not providing these details earlier.
