### ISSUE TITLE
Any comment that contains the word "region" triggers an error "#region is missing corresponding #endregion"

### ISSUE THREAD

**Issue by return42** [microsoft/pyright#4345]
Any comment that contains the word ``region`` triggers an error 

    #region is missing corresponding #endregion

This issue is reported on [pylance-release](https://github.com/microsoft/pylance-release)

- https://github.com/microsoft/pylance-release/issues/3765

.. but the implementation responsible for this seems to be here in pylint (but I may be wrong)

**Comment by erictraut** [comment]
Yes, this is a duplicate bug. This feature is owned by the pylance team, so let's leave the other bug open. They'll fix the problem in pylance and push the fix to pyright.

cc @rchiodo
