### ISSUE TITLE
reportMissingImports : import streamlit

### ISSUE THREAD

**Issue by donhuvy** [microsoft/pyright#4349]
GitHub Codespace. Use a jupyter notebook template.

```
%pip install streamlit
```

then

```
import streamlit
```

![image](https://user-images.githubusercontent.com/1328316/208226776-1dc022e7-0613-472a-bac7-a755b390c6f5.png)

**Comment by erictraut** [comment]
Pyright doesn't have support for jupyter notebooks. Pylance, which is built on top of pyright, has support for notebooks. Please use pylance instead.
