### ISSUE TITLE
Open a gitter channel

### ISSUE THREAD

**Issue by sammyrulez** [microsoft/pyright#435]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a place to ask questions about the project

**Describe the solution you'd like**
Many OS project has a gitter channel or other form of community support

**Additional context**
I have noob questions and I don't want to open trivial issues ( again )

**Comment by erictraut** [comment]
Thanks for the suggestion. I've set up a new Gitter channel: https://gitter.im/microsoft-pyright/community#

**Comment by Strum355** [comment]
Has the gitter channel been moved/removed? Gives a 404 now

**Comment by erictraut** [comment]
Now that github supports a "Discussions" feature, I've shut down the gitter channel. Feel free to start a new discussion topic directly in github by clicking on the "Discussions" tab above.
