### ISSUE TITLE
Optionally warn if classes or functions marked with `@typing.type_check_only` are used in runtime code

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/pyright#4375]
[`@typing.type_check_only`](https://docs.python.org/3/library/typing.html#typing.type_check_only) may be used to mark a class or function to be unavailable at runtime.

Pyright however currently does not issue any warning when calling classes or functions marked with `@typing.type_check_only` in runtime code, even when running Pyright in strict mode.

This is related to #3850, which was about respecting `@type_check_only` for autocompletion, which has been rejected due to performance concerns ("users expect completion suggestions to appear very quickly").

If checking `@type_check_only` is so expensive it could just be behind a feature flag that is not enabled by default but I think especially when using Pyright within a CI (which is not as time-sensitive as autocompletion) you definitely want Pyright to check that your code does not accidentally use any type-check-only classes/functions that will result in runtime errors.

**Comment by erictraut** [comment]
We currently have no plans to support `@type_check_only` for reasons described in the issue you linked. We might consider this in the future if there's sufficient signal from users that it's important. Please upvote the original issue if you're interested. It has currently received only one upvote from the original author of that issue.
