### ISSUE TITLE
Improve documentation display

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/pyright#438]
**Is your feature request related to a problem? Please describe.**
Improve documentation display in tooltips and completion item info wrt wrapping/colors/fonts.

**Describe the solution you'd like**
Compare
Pyright
![image](https://user-images.githubusercontent.com/12820357/71200983-f9faa280-224d-11ea-83d3-c64daee8e18a.png)

Jedi
![image](https://user-images.githubusercontent.com/12820357/71201009-04b53780-224e-11ea-8eb7-65aaeb69b92f.png)

MPLS
![image](https://user-images.githubusercontent.com/12820357/71201042-14cd1700-224e-11ea-8f7e-299ee1f52be0.png)

**Comment by erictraut** [comment]
I've made some improvements to the documentation display so it matches the MPLS display above. 

There's additional room for improvement. Unlike the MPLS, Pyright doesn't currently attempt to parse the doc string and reformat it.

The incremental improvement will be in the next release.

**Comment by erictraut** [comment]
This is now fixed in version 1.1.12, which I just published.
