### ISSUE TITLE
response is not defined in the REQUEST library

### ISSUE THREAD

**Issue by mdalifarzan** [microsoft/pyright#4385]
**### REQUEST IS NOT DEFINED IN THE REQUESTS LIBRARY**

While using the requests library it is showing that response is not defined in the request library.

Please consider this problem

link to the problem - https://drive.google.com/file/d/1J7QvCsidgik3Dg4FRASHLVBgxZYPnmrq/view?usp=sharing

**Comment by erictraut** [comment]
When filing bugs, please provide a minimal, self-contained code sample that exhibits the problem. It's very difficult to diagnose from screen shots.

The requests library is an untyped library. Its type information is provided by type stubs maintained as part of the [typeshed project](https://github.com/python/typeshed). Type checkers like pyright and mypy consume (and bundle) the type stubs from typeshed. If you think that there is an error in the requests type stubs, please file a bug (or even better, a PR) with the typeshed project. Pyright will then pick up the fix.
