### ISSUE TITLE
Unexpected folder collapse on file save

### ISSUE THREAD

**Issue by NateScarlet** [microsoft/pyright#440]
**Describe the bug**
Folder auto collapsed on file save. not happening if pyright disabled.

**To Reproduce**

1. `git clone https://github.com/NateScarlet/issue-repro.git -b pyright-1 --depth 1`
2. open `project.code-workspace`
3. change folder collapse state to
![image](https://user-images.githubusercontent.com/21083014/71227857-7a3b0980-231b-11ea-8721-fc1c97333643.png)
4. comment any line in `packageN.py`
5. folder auto collapsed

**Expected behavior**
Keep folder collapse state unchanged.

**Screenshots or Code**
![2019-12-20_11-34-31](https://user-images.githubusercontent.com/21083014/71228464-229d9d80-231d-11ea-8c6c-ca6986093746.gif)

**VS Code extension or command-line**
VSCode extension: 1.1.11

**Additional context**
This problem will not happen if i remove the `.` folder from workspace.
But i am using git submodule, so `.` folder needed in my workspace to use vscode source control.

**Comment by erictraut** [comment]
Very strange. Pyright has nothing to do with VS Code's display of folders and files in the left panel. This sounds like a bug in VS Code. Please report it in the VS Code repo.
