### ISSUE TITLE
"Disallow Any" Config Option

### ISSUE THREAD

**Issue by Burtannia** [microsoft/pyright#4429]
Would it be possible to get options to disallow the use of the `Any` type similar to those available in mypy?

**Comment by erictraut** [comment]
Pyright's philosophy on `Any` is different than mypy's. In particular, pyright distinguishes between an "explicit Any" and an "implicit Any", which is referred to as `Unknown`. For details, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/mypy-comparison.md#unknown-type-and-strict-mode).
