### ISSUE TITLE
Improper warning when `dataclass` has parenthesis or arguments 

### ISSUE THREAD

**Issue by plafosse** [microsoft/pyright#4431]
**Describe the bug**
```python
from dataclasses import dataclass

@dataclass()
class Foo:
    bar: int

x = Foo(1) # Expected no arguments to "Foo" constructor

@dataclass
class Foo2:
    bar: int

x = Foo2(2) # No error

@dataclass(frozen=True)
class Foo3:
    bar: int

x = Foo3(1) # Expected no arguments to "Foo3" constructor
```

**VS Code extension or command-line**
Vscode Pyright extension v1.1.287

**Additional context**

**Comment by erictraut** [comment]
I'm not able to repro the problem you're seeing. I suspect that you have an old version of a library called `dataclass` installed in your python environment that is overriding the stdlib library of the same name. Please try removing this (e.g. `pip uninstall dataclass`) and see if that fixes your issue.

**Comment by plafosse** [comment]
Ah your right, my project is vendoring `dataclass.py` to support python3.6
