### ISSUE TITLE
`pyright-langserver --stdio` silently returning an exit code of 1

### ISSUE THREAD

**Issue by jelacious** [microsoft/pyright#4446]
**Describe the bug**
`pyright-langserver` is silently returning an exit code of 1 upon being fed a file through `--stdio`.  This essentially means the LSP server is silently crashing upon receiving any Python file. Calling the `pyright` CLI program with both `PYRIGHT_PYTHON_DEBUG` and `PYRIGHT_PYTHON_VERBOSE` enabled does not seem to give any indication of anything wrong with the `pyright` command, returning an exit code of 0.

![image](https://user-images.githubusercontent.com/103415686/212092289-a1a18548-9991-42d8-828a-0afb9246029c.png)

Note: `echo $status` is the fish shell equivalent of `echo $?` which returns the last run command's exit code.

**To Reproduce**
1. Create a new Python file (hello.py) with the following content:
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

if __name__ == "__main__":
    print("Hello!")
```
2. Attempt to run:
```bash
$ pyright-langserver --stdio < hello.py
```
3. Check exit code:
```bash
$ echo $?
1
```
4. Cry.

**Expected behavior**
`pyright-langserver` not silently returning an exit code of 1 and instead displaying some information about the input file and continuing to run in perpetuity, or exiting with a 0 as an EOF was encountered (not quite sure what the correct behaviour is but I am quite certain it isn't to return a non-zero exit code).

**Screenshots or Code**
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

if __name__ == "__main__":
    print("Hello!")
```

**VS Code extension or command-line**
```bash
$ pyright --version
pyright 1.1.288
```
Python Version: `3.10.9`
OS: `Arch-Linux (6.1.4-arch1-1)`
Installation method: Tried both via `pip install pyright` (in a virtualenv) and `pacman -S pyright` (even after clearing cache).
Editor: `neovim (0.8.2)`
Shell: `fish/bash` (tried in both)

**Additional context**
I honestly have no idea why it would just silently boop me out. :(

**Comment by erictraut** [comment]
You shouldn't be invoking `pyright-langserver` directly. It's an internal module and cannot be invoked on its own. You should be using `langserver.index.js`.

If you want to understand the correct way to invoke pyright as a language server, you may want to look at how other folks who have done it. For example, here's the [LSP extension for neovim](https://github.com/fannheyward/coc-pyright).

**Comment by IamtherealBrian** [comment]
Hi, have you solved the problem? I met the same issue. Where to find more definition about langserver.index.js?
