### ISSUE TITLE
Add provisional support for PEP 702 (marking classes and functions as deprecated)

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#4456]
See https://peps.python.org/pep-0702/ for details.

**Comment by erictraut** [comment]
This will be included in the next release.

**Comment by erictraut** [comment]
This feature includes a new diagnostic rule called `reportDeprecated`. It's off by default but on in strict mode. If disabled, deprecated symbol usage is displayed in VS Code using a strike-through appearance (using a diagnostic hint).

![164f1d3f-f909-4e30-8acb-f186e93e690d](https://user-images.githubusercontent.com/7040122/212457397-d282e217-abb3-4274-a48a-abfbdf5af67e.jpg)

![f9082477-20f3-4ca2-b84e-80473fd75841](https://user-images.githubusercontent.com/7040122/212457398-eedaa45c-bbb8-4b37-aec1-624fc9ba939a.jpg)

**Comment by JelleZijlstra** [comment]
Thanks as always for your fast work! Let me know if the implementation leads to any feedback about the PEP. I will also amend the PEP to note the pyright implementation.

**Comment by erictraut** [comment]
Oh, I forgot to mention that this feature will not work at runtime until the `deprecated` symbol is added to `typing_extensions`. As a temporary workaround, I've defined `deprecated` in the `typing_extensions.pyi` stub that is bundled with pyright.

**Comment by erictraut** [comment]
This is included in pyright 1.1.289, which I just published. It will also be included in a future release of pylance.

**Comment by FeeeeK** [comment]
Maybe I don't understand something, but it doesn't seem to work for overloads of __init__ in classes:
![image](https://user-images.githubusercontent.com/26704473/226145401-73166834-1ba0-4512-be24-fb29d4964417.png)
but works for function overloads
![image](https://user-images.githubusercontent.com/26704473/226145339-3dd709dc-1f0f-4c84-9b42-e678a40cbe76.png)

**Comment by erictraut** [comment]
@FeeeeK, this was an oversight. The implementation doesn't currently handle deprecated constructors. This will be addressed in the next release.

**Comment by erictraut** [comment]
Could you please file a new bug so this doesn't get lost?
