### ISSUE TITLE
Variable that cannot be reached is marked as possibly unbound

### ISSUE THREAD

**Issue by EvgeniGenchev** [microsoft/pyright#4462]
**Describe the bug**
I am using pyright through lspsaga.nvim extension which works fine 99% of the cases. However, from time to time I get a "var" is possibly unbound error, for variables that I have made absolutely sure are defined. I don't have all examples documented (I wish i had), but I can provide you with the latest.

![image](https://user-images.githubusercontent.com/59848681/212545782-38d4bd20-eee3-4fcc-8ae5-3de17159e4e8.png)

In this code it can be seen that if the variable `ip` is not in initialized in the code on local or even global level the code after the first if statement is unreachable. Thus, this code with "possibly unbound" variable will never be executed.

**To Reproduce**
Creat a file with the following code:
```python
def test(arg:int):
    if arg == 1:
        print(locals())
        var = 10
        print(locals())

    if "var" not in locals():
        return None

    return var
test(1)
```
Then execute the:
```sh
$ pyright main.py
```

**Expected behavior**
Variables that are part of code that under some condition have become unreachble should not be marked as `possibly unbound` if they are defined outiside said condition.

**VS Code extension or command-line**
The code was tested both on:
1. neovim v0.8.1 + lspsaga
2. pyright 1.1.284

**Comment by erictraut** [comment]
Pyright is working as designed here. Checking for a variable by name within the "locals" dictionary is a non-standard technique, and I recommend against using this. I don't plan to add support for this anti-pattern in pyright.

The recommended way to ensure that variables are not unbound is to initialize them along all code paths.

If you don't want pyright to check for variables that are possibly unbound, you can disable the `reportUnboundVariable` check.
