### ISSUE TITLE
Feature: optional setting to report complex type inference

### ISSUE THREAD

**Issue by laundmo** [microsoft/pyright#4469]
**Is your feature request related to a problem? Please describe.**
Sometimes one might accidentally end up relying on complex chains of type inference. This can lead to issues where changing one small type leads to type errors down the line. These errors can be annoying to track back to their source, therefore it might be better to avoid overreliance on inference.

**Describe the solution you'd like**
Ideally, it would be a warning which defaults to off normally and maybe to a large threshold in strict mode, which can be configured to warn/error at a certain number of inference steps.

examples of what i think inference steps could be:
- `a = 1` inferred that `a` is `int` with 1 step
- ```py
   def a():
      return 1
   b = a()
   ```
  inferred that `b` is `int` by 2 steps (literal `1` to return of `a`: step 1, return of `a` to type of `b`: step 2)

i might consider 3 or 4 inference steps worthy of a specifying the type, as that is the level where tracking it down might become annoying

**Additional context**
Besides being a feature I would consider quite useful, this might help in debugging or analyzing issues with pyright type inference.

**Comment by erictraut** [comment]
Relying on type inference is generally a good thing, not something to be avoided. If a change in your code results in a type violation, pyright will inform you.

It's unlikely would ever add a feature such as what is being proposed here.

**Comment by laundmo** [comment]
> If a change in your code results in a type violation, pyright will inform you.

yeah, it will alert me 4 calls down the line where i then have to trace back to the source of the change, which is especially annoying when refactoring. Any good thing is only good in moderation.
