### ISSUE TITLE
`type[T]` cannot be an instance of a runtime checkable protocol

### ISSUE THREAD

**Issue by RocketRace** [microsoft/pyright#4485]
**Describe the bug**
`isinstance` checks comparing instances of `type` / `type[object]` / `type[T]` / `type[Any]` to any `@runtime_checkable` marked `Protocol` infer the instance as `Never`.

**Expected behavior**
The instance should be inferred as the intersection of `type` and the given protocol, i.e. `<subclass of type and ...>`. 

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
from typing import Any, Protocol, runtime_checkable

@runtime_checkable
class Foo(Protocol):
    foo: int # or ClassVar[int]

def bar(cls: type[Any]): # or any other type expression
    if isinstance(cls, Foo):
        reveal_type(cls) # Never
```

**VS Code extension or command-line**
- Pylance v2023.1.20

**Additional context**

Mypy infers the reveal_type call to be unreachable. However, if `type[Any]` is replaced with `type`, the inferred result is `__main__.<subclass of "type" and "Foo">`. Evidently, since these behaviors are different there is an additional bug on mypy's end here too.

**Comment by erictraut** [comment]
The behavior of `isinstance` narrowing is not well defined. Pyright's implementation has been tuned over time to produce the "best" answer most of the time. I don't think that producing an intersection in this case is the best approach. 

If you change your annotation for `cls` to be either `object` or `Any`, it will be narrowed to `Foo` in your example.

The type of `type` and `type[Any]` should be equivalent, so mypy's behavior is inconsistent.
