### ISSUE TITLE
PEP-681 & pydantic: modify __init__ signature with pydantic.Extra.allow

### ISSUE THREAD

**Issue by ringohoffman** [microsoft/pyright#4499]
**Is your feature request related to a problem? Please describe.**

Comes from [PEP-681](https://peps.python.org/pep-0681/)

https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md

**Describe the solution you'd like**

`pydantic.BaseModel` subclasses defined with `extra=pydantic.Extra.allow` (corresponding to [json schema `additionalProperties: true`](https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties)) do not modify the `__init__` signature to indicate that arbitrary `kwargs` are supported, which leads to static typing errors when using arbitrary `kwargs`.

```python
import pydantic


class MyMyodel(pydantic.BaseModel, extra=pydantic.Extra.allow):
    an_arg: int


model1 = MyMyodel(an_arg=1)
model2 = MyMyodel(an_arg=1, another_arg=1)  # Pylance: No parameter named "another_arg"
```

I would really like if this could be supported since this is the expected usage of `extra=pydantic.Extra.allow`.

**Comment by erictraut** [comment]
The `extra` parameter isn't standardized as part of `dataclass` or PEP 681, so this isn't something we can support currently. If you would like to advocate for an extension to PEP 681, you're welcome to do so, but you'd need to make a convincing argument to rally the support of the typing community. The best place for that discussion is in the [python/typing discussion forum](https://github.com/python/typing/discussions).

As a workaround, you could define your own `__init__` method. If an `__init__` is present, `dataclass_transform` will not synthesize one.
