### ISSUE TITLE
Flag to report unnecessary type: ignore

### ISSUE THREAD

**Issue by layday** [microsoft/pyright#450]
**Is your feature request related to a problem? Please describe.**
Sometimes a `type: ignore` is added to hide erroneously-generated errors in the type checker.  However `type: ignore` comments might be left in the codebase after the issue is fixed and eventually mask genuine type-checking errors e.g. if the programmer were to make changes to the offending line of code.

**Describe the solution you'd like**
A new flag similar to `reportUnnecessaryCast` to indicate to pyright that unused `type: ignore`s should produce an error or for unused `type: ignores` to produce an error by default - the latter might stymie users who run pyright alongside mypy or another type checker.

**Comment by erictraut** [comment]
I'm not a fan of `type: ignore`. I added support for it in Pyright very reluctantly. It's a blunt instrument. There's almost always a better way to silence a type error using `cast`, an assert, or other techniques. For that reason, we never use `type: ignore` in the large python code base that my team develops. We set "enableTypeIgnoreComments" to false in pyrightconf.json. I encourage you to try to avoid `type: ignore` as well.

**Comment by layday** [comment]
Fair enough - I agree that `type: ignore` is best avoided and I don't feel very strongly about this request, so I'll close it.  Thanks for taking the time to respond.

**Comment by rattrayalex** [comment]
This configuration option now exists: [`reportUnnecessaryTypeIgnoreComment`](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#:~:text=setting%20is%20%27none%27.-,reportUnnecessaryTypeIgnoreComment,-%5Bboolean%20or%20string)
