### ISSUE TITLE
Pyright shows false `"xxx" is not a known member of module` error message.

### ISSUE THREAD

**Issue by kekekio** [microsoft/pyright#4503]
**Description**
I installed neovim with coc-pyright, and when I try to use python modules, it shows `"xxx" is not a known member of module`. But Python and Pycharm runs this file correctly. Autocomplete doesn't work with them either, but completion in Pycharm works fine. I don't have idea what I do wrong. 

**To Reproduce**
Just install neovim with pyright server and completion plugin. I already tried autoinstaller LSP like mason and coc-pyright, and now I've connected neovim with pyright directly with the same result.
Same result, if I use virtual env. (but pycharm autocomplete doesn't work with venv too)

**Expected behavior**
When I type `mediapipe` (or any another module) completion must show mediapipe modules like Image, Matrix, etc.

**Screenshots or Code**
```python
    import cv2
    import mediapipe as mp
    import numpy as np

    mp_face_mesh = mp.solutions.face_mesh
    face_mesh = mp_face_mesh.FaceMesh(min_detection_confidence=0.5, min_tracking_confidence=0.5)
    cap = cv2.VideoCapture(0)
    a = cv2.
```
![Pycharm displays completion](https://user-images.githubusercontent.com/52344723/213863305-7638407b-6650-421b-af0d-afd6c7d87254.png)
Pycharm displays completion

![Pycharm displays completion](https://user-images.githubusercontent.com/52344723/213863364-0bd3a986-6bbe-4536-baf5-58090e621790.png)
Pycharm displays completion

![but neovim doesn't](https://user-images.githubusercontent.com/52344723/213863424-2935606e-b7ee-4b01-8bc8-eefd68e5354e.png)
but neovim doesn't

![comand-line pyright](https://user-images.githubusercontent.com/52344723/213863489-f4805792-4a46-4dee-8010-388490e0fdcb.png)
comand-line pyright

**Vim extension or command-line**
I ran pyright from command-line and vim-extention with pretty same result.

**Additional context**
I'm newbie in python, and I might installed python in wrong way.  I just typed `pip install modulename`. I will be glad for your advice.

**Comment by erictraut** [comment]
The cv2 library does not ship with any type information, and it's a native library (not written in Python), so there's no way to extract even basic type information without loading/executing the library and introspecting it. Pyright never loads or executes arbitrary third-party library code for security reasons. PyCharm does this, which explains why you're seeing some basic type information in PyCharm.

The best answer here is for maintainers of OpenCV to provide type information with their library in the form of embedded type stubs (".pyi" files). I encourage you to report this to the OpenCV maintainers. The more they hear from users, the more likely that they will respond to this need.

**Comment by erictraut** [comment]
Pyright's `--createstub` creates stubs based on an analysis of Python code. It doesn't work with libraries that are written in other languages. There are other tools such as "stubgen", which is part of mypy, that can produce minimal stubs from such libraries. Here's some [additional documentation](https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md) that you may find helpful.

**Comment by erictraut** [comment]
The ipython shell is actively running the code, so it's able to do "live" introspection. Pyright uses only static information and never runs the code it is analyzing. If you want completion suggestions for a library, you will need to find or generate static type information for it. I don't know anything about mediapipe. You might want to reach out to its maintainers.
