### ISSUE TITLE
Pyright resolves types too broadly for literals when using TypeGuard

### ISSUE THREAD

**Issue by robert-bn** [microsoft/pyright#4506]
The resolved type on literal unions is sometimes too wide.

The following minimal example demonstrates this 

```python
from typing import Literal, TypeGuard, TypeVar

Foobar = Literal["foo", "bar"]
foobar_enumeration: list[Foobar] = ["foo", "bar"]

T = TypeVar('T')

def is_element(x: object, xs: list[T]) -> TypeGuard[T]:
    return x in xs

def foo(x: str):
    assert is_element(x, foobar_enumeration)
    reveal_type(x)
```

When checking the revealed type in pyright we get `str`:

![image](https://user-images.githubusercontent.com/26419016/213924616-78e21378-fb17-4095-bbf2-a75eb4ce8a3b.png)

This is of course not wrong as `Foobar` is a subtype of `str`,  but is useless for verifying the correct validation of input. It seems as if `T` is solved as `str` in the call to is_element and not the more specific type `Foobar`.

In contrast, Mypy correctly determines the type to be `Union[Literal['foo'], Literal['bar']]` in this example, which is what I would expect pyright to do.

I'm running pyright as a VS Code extension using Pylance version v2023.1.30

**Comment by erictraut** [comment]
Pyright is working as designed here. The constraint solver does not retain literals unless required by a constraint. You wouldn't want it to do so in most cases. Mypy is inconsistent in how and when its constraint solver retains literals. For details refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/mypy-comparison.md#constraint-solver-behaviors).

**Comment by robert-bn** [comment]
> Pyright is working as designed here. The TypeVar constraint solver does not retain literals unless required by a constraint. You wouldn't want it to do so in most cases. 

Thank you, that makes sense.

For posterity, I think you might have meant 

```python
T = TypeVar('T', bound=LiteralString)
```

in your reply (which has the same desired behaviour), since specifying the upper bound as the particular literal union we're interested in is no more generic than just specifying the type.

**Comment by erictraut** [comment]
Yes, if you want `T` to accept any literal string value, then an upper bound of `LiteralString` will accomplish that. If you want it to take on only `Literal["foo"]` or `Literal["bar"]` (or a union of the two), then an upper bound of `Foobar` will accomplish that.
