### ISSUE TITLE
Union, Unnecessary isinstance call and numpy.in32 Second argument to "isinstance" 

### ISSUE THREAD

**Issue by FrancescElies** [microsoft/pyright#4510]
**Describe the bug**
I think the following example might be two different issues but I packed it together in this issue but in two separate functions `integer_or_float` and `integer_or_float_v2`.

I will be glad to separate them if you think it makes sense.

**To Reproduce**
```toml
[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
typeCheckingMode = "strict"
```
```python
import numpy as np
import pyright
from typing import Union

Int32Like = Union[int, np.int32]
FloatLike = Union[float, np.float32]

MyTypes = Union[Int32Like, FloatLike]


def integer_or_float(value: MyTypes) -> str:
    if isinstance(value, (int, np.int32)):
        return "int"
    elif isinstance(value, (float, np.float32)):
        return "float"
    else:
        raise RuntimeError


def integer_or_float_v2(value: MyTypes) -> str:
    if isinstance(value, (int, np.integer)):
        return "int"
    elif isinstance(value, (float, np.floating)):
        return "float"
    else:
        raise RuntimeError


print(integer_or_float(1))
print(integer_or_float(np.int32(1)))
print(integer_or_float(1.0))
print(integer_or_float(np.float32(1.0)))

print("===============")
print(integer_or_float_v2(1))
print(integer_or_float_v2(np.int32(1)))
print(integer_or_float_v2(1.0))
print(integer_or_float_v2(np.float32(1.0)))

print("===============")
print(f"{np.__version__=}")
print(f"{pyright.__version__=}")

```

Pyright produces the following errors
```❯ pyright my_isinstance.py
No configuration file found.
pyproject.toml file found at C:\s\mytest\isinstance.
Loading pyproject.toml file at C:\s\mytest\isinstance\pyproject.toml
Assuming Python version 3.11
Assuming Python platform Windows
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath C:\s\mytest\isinstance\typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.290
C:\s\mytest\isinstance\my_isinstance.py
  C:\s\mytest\isinstance\my_isinstance.py:12:26 - error: Second argument to "isinstance" must be a class or tuple of classes
    TypeVar or generic type with type arguments not allowed (reportGeneralTypeIssues)
  C:\s\mytest\isinstance\my_isinstance.py:14:28 - error: Second argument to "isinstance" must be a class or tuple of classes
    TypeVar or generic type with type arguments not allowed (reportGeneralTypeIssues)
  C:\s\mytest\isinstance\my_isinstance.py:23:10 - error: Unnecessary isinstance call; "float | float32" is always an instance of "float | floating[Unknown]" (reportUnnecessaryIsInstance)
3 errors, 0 warnings, 0 informations
Completed in 0.814sec
```
But code executes as expected
```
❯ python my_isinstance.py
int
int
float
float
===============
int
int
float
float
===============
np.__version__='1.24.1'
pyright.__version__='1.1.290'
```
**Expected behavior**
Maybe the code above would be better written with with `functools.singledispatch` but despite of that should still pyright complain about the code above?

- `Unnecessary isinstance call; "float | float32" is always an instance of "float | floating[Unknown]"` is maybe related to #4509
- `Second argument to "isinstance" must be a class or tuple of classes TypeVar or generic type with type arguments not allowed` is that right? code seems to run fine.

**Comment by erictraut** [comment]
The `unnecessaryIsInstance` diagnostic is working as designed here, for the same reasons explained in [this issue](https://github.com/microsoft/pyright/issues/4509).

The other diagnostics are also correct, at least given the type information provided by numpy to pyright. Numpy's type stubs defines `np.int32` as a type alias for `signedinteger[_32Bit]`. That is, it is defined as a specialized version of a generic class. If you use an actual specialized class in an `isinstance` call at runtime, you will receive a runtime error, which is what pyright is telling you here.

Try this, for example:
```python
print(isinstance(["a"], list[str])) # TypeError
```

The reason that the use of `np.int32` and `np.float32` do not generate a TypeError at runtime is that they are not actual specialized generic classes at runtime. Numpy's type stubs are modeling them differently from the runtime implementation. You could report this as a bug to the numpy maintainers, but it's unlikely they will change it.

In any case, pyright is working correctly here.
