### ISSUE TITLE
Adding autocompletion for modules imported by __import__.

### ISSUE THREAD

**Issue by Rid1-fz-06** [microsoft/pyright#4515]
**Is your feature request related to a problem? Please describe.**
If I do an import using `import` keyword, the autocompletion triggers for the contents of that module. But if I import any module using `__import__` instead of `import`, autocompletion doesn't work

**Describe the solution you'd like**
Autocompletion should be triggered for classes, function, attributes if any module is imported through `__import__`.

**Comment by erictraut** [comment]
The use of `__import__` won't work for static analysis. It's typically used for more dynamic behaviors that are not supported by the standard `import` statement. If you want your code to work with static analyzers, then I recommend avoiding `__import__`.
