### ISSUE TITLE
`pyright` and `pyright-langserver` get stuck analyzing the `RFExplorer-for-Python` library

### ISSUE THREAD

**Issue by yehorb** [microsoft/pyright#4519]
**Describe the bug**
`pyright` and `pyright-langserver` get stuck analyzing the https://github.com/RFExplorer/RFExplorer-for-Python library. 

**To Reproduce**
```powershell
(base) PS C:\> git clone git@github.com:RFExplorer/RFExplorer-for-Python.git --branch master --depth 1
Cloning into 'RFExplorer-for-Python'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 23 (delta 4), reused 9 (delta 2), pack-reused 0
Receiving objects: 100% (23/23), 53.35 KiB | 93.00 KiB/s, done.
Resolving deltas: 100% (4/4), done.
(base) PS C:\> cd .\RFExplorer-for-Python\
(base) PS C:\RFExplorer-for-Python> $Env:PYTHONPATH = "${pwd}\RFExplorer"
(base) PS C:\RFExplorer-for-Python> pyright.cmd --lib
No configuration file found.
No pyproject.toml file found.
stubPath C:\RFExplorer-for-Python\typings is not a valid directory.
Assuming Python platform Windows
Searching for source files
Found 15 source files
^C
(base) PS C:\RFExplorer-for-Python>
```

After executing the `pyright.cmd --lib` command, the process gets stuck and exits only after `^C`.

Opening any file from the `RFExplorer-for-Python` directory in the `neovim` editor with `pyright` language server configured and enabled leads to similar results - the command `cmd.exe /C pyright-langserver --stdio` is executed, but the process gets stuck, does not react to LSP commands, process remains open even after `neovim` is closed, it is only possible to kill the process from the Task Manager.

**Expected behavior**
`pyright` CLI tool successfully completes the analysis and outputs the analysis results (`errors, warnings, informations` messages).

`pyright-langserver` successfully completes the analysis and works as intended with LSP client - responds to LSP commands, provides code navigation, completion etc., shuts down correctly.

**VS Code extension or command-line**
`pyright 1.1.290`

Both the command-line tool and the langserver tool suffer from the same issue.

**Comment by erictraut** [comment]
This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.292, which I just published. It will also be included in a future release of pylance.

**Comment by excubo-jg** [comment]
This change causes one of our functions which threw a "code is too complex to analyze" error to now getting analyzed which is much appreciated. The function did not and even now does not cause a "long operation warning" so I assume that it has always been a close call. The code's complexity score is driven by a long list of if-elif (match-case) statements and it seems the change in complexity calculation did the trick. I am wondering if using the ratio complexity score / time spent might be useful to identify easy to analyze code with high cyclomatic complexity where a higher cc threshold could be applied.

**Comment by erictraut** [comment]
Using "time spent" is not a good idea because it's highly variable based on hardware speeds, disk speed, CPU utilization, etc. It would result in non-determinism even on the same machine, which is not something people appreciate in their tools. So I don't think we can use "time spent" in the calculation.

**Comment by ifuatgucluer** [comment]
Thanks

12 Şub 2023 Pzr 16:21 tarihinde excubo-jg ***@***.***> şunu
yazdı:
