### ISSUE TITLE
[BUG] type variables lost when casting a class as a (**P) -> T

### ISSUE THREAD

**Issue by GreyElaina** [microsoft/pyright#4525]
**Describe the bug**
pyright cannot cast a normal class to a normal callable with correct typevar informations.

**To Reproduce**
```py
from typing import TypeVar, Callable, Generic
from typing_extensions import ParamSpec

P = ParamSpec("P")
T = TypeVar("T")

class Test(Generic[T]):
    def __init__(self, a: T):
        self.a = a

def t(x: T) -> T:
    return x

def ca(x: Callable[P, T]) -> Callable[P, T]:
    return x

reveal_type(ca(t)) # correctly, "(x: T) -> T"
reveal_type(ca(Test)) # typevar information lost, "(a: Unknown) -> Test[Unknown]"
```

**Expected behavior**
it will reveal the type correctly, "(a: T@Test) -> Test[T@Test]", however the source of typevar is still a quiz(to me), it's a problem to be thought.

**Screenshots or Code**
presented

**VS Code extension or command-line**
vscode pylance (latest) and command-line shows the same.

**Additional context**

**Comment by erictraut** [comment]
Pyright is working as designed here. In the case of `ca(Test)`, the `Test` class is a generic class, but you have failed to provide a type argument for `Test`, so the expression is interpreted as `Test[Unknown]`. The effective type of its constructor is `(a: Unknown) -> Test[Unknown]`.

**Comment by GreyElaina** [comment]
well, TypeVar cannot be passed indirectly.
