### ISSUE TITLE
Type narrowing didn't work in class method which narrowed params type

### ISSUE THREAD

**Issue by GreyElaina** [microsoft/pyright#4531]
**Describe the bug(as designed again ?)**
pyright cannot infer a narrowed type defined in a classmethod which returns "Self@Base[T]".
in my view, the narrowing should works, like a callable: "(T) -> Self[T]" (a example!).

it's a corner case, i guess, but this confused me. if there is better solution, i would like to check it.

**To Reproduce**
```py
from typing import Generic, TypeVar

T = TypeVar("T", bound=str | int)

class Base(Generic[T]):
    def __init__(self, a: T) -> None:
        self.a = a
    
    @classmethod
    def narrow(cls, a: int):
        # do something, like valid check.
        return cls(a)

class Subclass(Base[T]):
    ...
    # you can annotate "Base.narrow" s return type with "Base[int]", or annotate "cls: type[Base[int]]"
    # however in subclass it's still 'Base[int]', this causes problems.
    # the HKT might solve the problem but typing donot support it currently.

reveal_type(Base.narrow)  # Type of "Base.narrow" is "(a: int) -> Base[T@Base]"
reveal_type(Base.narrow(1)) # it's Base[Unknown], which i prefer a inferable generic.
```

**Expected behavior**
```py
reveal_type(Base.narrow)  # Type of "Base.narrow" is "(a: int) -> Base[int]"
reveal_type(Base.narrow(1)) # Base[int]
reveal_type(Subclass.narrow(1)) # Subclass[int], the narrow method also works in subclasses.
```

**Screenshots or Code**
`pass`

**VS Code extension or command-line**
latest pylance

**Additional context**

**Comment by erictraut** [comment]
Pyright is working correctly here. You are using type variables incorrectly in your code sample.

You are attempting to call a class method on an unspecialized generic class. The binding of a class method occurs as part of the member access (i.e. `Base.narrow`), so you must use a specialized form of the class if you want this to work (i.e. `Base[int].narrow`).
