### ISSUE TITLE
`reportUnnecessaryComparison` should apply to conditional expressions of the form `x is None` and `x is not None`

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#4537]
The `reportUnnecessaryComparison` check doesn't currently report unnecessary `is` and `is not` operations when used with `None`.

This comes from a mypy feature request: https://github.com/python/mypy/issues/14541.

**Comment by Joy4689** [comment]
import useful_tools is not working in python code

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.292, which I just published. It will also be included in a future release of pylance.
