### ISSUE TITLE
Get rid of "N files to analyze" message?

### ISSUE THREAD

**Issue by Seanld** [microsoft/pyright#4538]
**Describe the bug**
Not necessarily a bug, but an unwanted feature that I cannot figure out how to disable. Whenever I modify a file in Doom Emacs, while having multiple other files open, I get a message that pops up saying "__ files to analyze" (where the underscore is however many files it's analyzing). This is incredibly annoying, so I figured I'd find where in the ELisp that string was, and patch it out, or disable it with whatever variable it's associated with. Turns out, it exists in Pyright. None of the Pyright config options appear to work for me either. What can I do to stop Pyright from producing this message?

**To Reproduce**
Have multiple files open with the "openFilesOnly" mode enabled, and modify a file. I can only speak as to Emacs, but I presume a similar thing occurs in other editors, as the message comes from Pyright.

**Expected behavior**
I should be able to disable this message from appearing.

I didn't raise this anywhere in Emacs or lsp-mode bugs, because I found the string in the Pyright codebase. And I couldn't find any settings in either of those two that solved my situation, so I figured I'd ask here. If it doesn't belong here, I apologize in advance.

**Comment by erictraut** [comment]
This feature is by design, and there is no way to disable it. It works well with VS Code and appears in the bar at the bottom of the window. I don't know how emacs or its lsp plugin present such messages.
