### ISSUE TITLE
Set[str] | List[str] is not valid for Set[str | int] | List[str | int]

### ISSUE THREAD

**Issue by Rafaeltheraven** [microsoft/pyright#4543]
**Describe the bug**
I've got a method which takes either a set or a list of either strings or integers (or some more types, but the smallest example is `str | int`). If I now try to call this method with a variable defined as `Set[str] | List[str]` pyright says:

```
Type "Set[str] | List[str]" cannot be assigned to type "List[str | int] | Set[str | int]"
      "List[str]" is incompatible with "List[str | int]"
        TypeVar "_T@list" is invariant
          Type "str" cannot be assigned to type "str | int "
            "str" is incompatible with "int"
      "Set[str]" is incompatible with "Set[str | int]"
        TypeVar "_T@set" is invariant
```

**To Reproduce**
Have a method which takes either a `list` or `set` of `str` or `int` and have another method which takes specifically a `list` or `set` of `str`. Then, try to call this first method with the list/set from the second.

**Expected behavior**
Pyright correctly deduces that `str` is in `str | int` so this should be fine.

**Screenshots or Code**
```python
def foo(arg: Set[str | int] | List[str | int]):
    return

def bar(arg: Set[str] | List[str]):
    foo(arg) # <- error occurs here
```

This occurs on `pyright 1.1.291` using python 10

**Comment by ifuatgucluer** [comment]
Thanks

28 Oca 2023 Cmt 16:42 tarihinde Rafaeltheraven ***@***.***>
şunu yazdı:
