### ISSUE TITLE
Environment variable interpolation in config

### ISSUE THREAD

**Issue by smackesey** [microsoft/pyright#4547]
**Is your feature request related to a problem? Please describe.**

Suppose a team of developers works on two repos, A and B. B consumes libraries that live in A. The locations of A and B differ on different developer machines. Because of this, referencing A from B's pyright configuration requires a variable path-- AFAICT there is currently no way to specify this.

**Describe the solution you'd like**

One could use environment variable interpolation to point to the root of another repo:

```
### pyproject.toml (B)

[tool.pyright]

extraPaths = [
  "${A_ROOT}/some/a/lib",
  "${A_ROOT}/some/other/a/lib",
]
```

That way, when running e.g. an LSP renameSymbol operation from B, it would update references in both A and B. This could also be useful in the `include` setting.

**Additional context**

- We are working on adopting Pyright across the whole team over at [Dagster](https://github.com/dagster-io/dagster), and have exactly this problem. There is an OSS and an internal repo-- we'd like devs to be able to execute refactors in OSS that propagate to the internal repo. 
- Powerful Python linter [Ruff](https://github.com/charliermarsh/ruff) supports this: https://github.com/charliermarsh/ruff#extend

**Comment by erictraut** [comment]
We've discussed this previously and decided against adding any dependencies on shell-specific syntax in the pyright configuration files.

The `extraPaths` configuration is designed to be used for project-relative paths. If you're specifying paths outside of your project, you're using it in a way that it was not intended to be used. I'd be interested in understanding why you are specifying extra paths outside of your project. There are likely other ways to address that issue.

**Comment by smackesey** [comment]
>I'd be interested in understanding why you are specifying extra paths outside of your project.

Like I stated in "Additional Context":

>There is an OSS and an internal repo-- we'd like devs to be able to execute refactors in OSS that propagate to the internal repo.

These two repos can be considered part of the same "project", for dev purposes they would ideally live in the same repo, but they need to be in separate repos because the internal one is private.

**Comment by erictraut** [comment]
Yeah, this is pretty far outside of the intended use of `extraPaths`.  Perhaps a symbolic link would address your use case?

**Comment by smackesey** [comment]
>Perhaps a symbolic link would address your use case?

OK I will experiment with creating a symlink at `A_root/B` that points to `B_root`, though I worry this will disrupt our other tools. I do think there's a strong case for env var interpolation, very useful for anyone working with inter-dependent repos-- that's why `ruff` has it. But I've made my case and I'll rest it.

**Comment by erictraut** [comment]
Environment variable conventions and variable expansion syntax vary by platform and shell, so it's generally not a good idea to use environment variables in tools that are intended to be used cross platform by teams of engineers. It is for this reason that other compilers and language servers provided by Microsoft do not generally support environment variables in their config files.
