### ISSUE TITLE
Skip printing file when --level suppressed all messages

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#4549]
**Is your feature request related to a problem? Please describe.**
`pyright --skipunannotated` emits information-level messages for skipped functions. When running `pyright --skipunannotated --level warning` the information-level messages are suppressed but there is still a listing for each file even if it only had information-level messages.

**Describe the solution you'd like**
If no information/warning/errors are reported, it would be nice to not even print the file.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.292, which I just published.
