### ISSUE TITLE
`type(None)` is not assignable to `type[object]`?

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pyright#4550]
Code:
```py
_type_descriptions: dict[type[object], str] = {dict: "object", type(None): "null"}
```
Error:
```
Expression of type "dict[Type[dict[Unknown, Unknown]] | Type[None], str]" cannot be assigned to declared type "dict[Type[object], str]"
```
What's wrong here?

If you replace `type(None)` with `type(0.9)` or `type(Exception)`, Pyright doesn't complain. It's specifically with `type(None)`.

Pyright version: `1.1.291`, Python version: `3.11`

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.
