### ISSUE TITLE
Generic TypeGuard incorrectly widens Literal type to str

### ISSUE THREAD

**Issue by ImogenBits** [microsoft/pyright#4558]
**Describe the bug**
It's a bit weird to explain, this code should illustrate it better:
```python
from typing import Literal, TypeGuard, TypeVar


SomeType = Literal["test"]

def normal_typeguard(val: SomeType) -> TypeGuard[SomeType]:
    return True

T = TypeVar("T")
def generic_typeguard(val: T) -> TypeGuard[T]:
    return True


def f(var: SomeType):
    if normal_typeguard(var):
        reveal_type(var)    # Type of "var" is "Literal['test']"

    if generic_typeguard(var):
        reveal_type(var)    # Type of "var" is "str"
```
When using a typeguard with a generic argument (doesn't matter if it's on the first or any other argument) and return type, it will not correctly narrow the type to the literal type, but rather just to `str`.

**Expected behavior**
The narrowed type should be `Literal["test"]`. It works correctly when `SomeType` is set to pretty much any other type I tried, including generic types and even nested literal types like `set[Literal["test"]]`.

**VS Code extension or command-line**
VS Code extension, pyright e96b3ece

**Comment by erictraut** [comment]
This behavior is intended. It's not a bug. The TypeVar constraint solver does not retain literals unless that's required by some constraint. In most cases, you wouldn't want literals to be retained. For example, you probably wouldn't expect `generic_typeguard(1)` to be evaluated as `Literal[1]`; you'd expect it to be evaluated as `int`.

**Comment by ImogenBits** [comment]
maybe I'm in the minority with this, but I absolutely would expect that to be evaluated as `Literal[1]`. What is the upside of intentionally widening the type like that?

My actual use case is that I want to properly narrow `T | Missing` (for some custom type `Missing`) to `T`. Is that not possible with pyright? I'm using an explicit literal type as what amounts to an easier to use enum, so I have to retain that info and can't just use `str`.

**Comment by erictraut** [comment]
I don't think you would be happy with the results in general if pyright retained literals in its constraint solver. It would be almost unusable for many common use cases.

As I mentioned, the constraint solver doesn't retain literals unless it's required by some constraint. You could add a constraint, for example, by specifying a bound on the type variable (e.g. `typing.LiteralString' or `SomeType`).

**Comment by ImogenBits** [comment]
Is there something obvious I'm missing that would cause problems? To me this seems pretty much identical to sometimes discarding info about what subtype a value is, shouldn't it always be able to "upcast" it to str/int at the places where that is actually needed rather than doing so prematurely at the point where the type guard is called? Especially since that does seem to be the behaviour when the type guard is for types like `list[Literal[1]]` (or any other generic type, regardless of variance) and that doesn't seem to be causing any issues?

I can see how I could add a constraint, but then the type guard wouldn't for for all the other use cases. It honestly seems very counterintuitive that it's not possible to make a function that properly checks if an element of `T | None` is `T` and signals this to the type system in a way that treats `Literal[1]` as an actual type.

**Comment by erictraut** [comment]
Mypy is inconsistent in how it handles literals in its constraint solver. See [this documentation](https://github.com/microsoft/pyright/blob/main/docs/mypy-comparison.md#constraint-solver-literals) for additional details.
