### ISSUE TITLE
Type isn't narrowed to the most specific type when checking isinstance of a Generic

### ISSUE THREAD

**Issue by ringohoffman** [microsoft/pyright#4560]
**Describe the bug**

Consider the following:

```python
from typing import Generic, TypeVar

T = TypeVar("T")


class MyBaseClass(Generic[T]):
    my_value: T


class MyDerivedClass(MyBaseClass, Generic[T]):
    my_value: T

    def my_method(self) -> None:
        ...


class MyContainer:
    my_instance: MyBaseClass[str] | MyDerivedClass[str]

    def call_my_method(self) -> None:
        assert isinstance(self.my_instance, MyDerivedClass)
        reveal_type(self.my_instance)  # Type of "self.my_instance" is "MyDerivedClass[Unknown] | MyDerivedClass[str]"
        self.my_instance.my_method()

```

**Expected behavior**

Why can't this be narrowed further to `MyDerivedClass[str]`? Isn't this a proper subset of `MyDerivedClass[Unknown]`?

**VS Code extension or command-line**
Pylance for VSCode v2023.1.41

**Comment by erictraut** [comment]
You have a bug in your code. The `MyDerivedClass` derives from the class `MyBaseClass`, which is a generic class that accepts a single type argument. You've omitted a type argument, which effectively means that you're deriving from `MyBaseClass[Any]`. I suspect that you meant `MyBaseClass[T]`. If you enable the `reportMissingTypeArgument` check in pyright, it will report bugs like this.
