### ISSUE TITLE
per-line coverage reporting

### ISSUE THREAD

**Issue by vors** [microsoft/pyright#4566]
**Is your feature request related to a problem? Please describe.**
I'd like to get insights into the coverage provided by pyright, up to per-line resolution.
For example a line with `# type: ignore` should be not covered in this report ("0" in the cobertura notation), while a line where all types are properly checked and pass the test should be covered as "1".

**Describe the solution you'd like**
Implement a flag that allows to produce a coverage report in one of the existing coverage formats like cobertura.
Corresponding mypy feature https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-cobertura-xml-report

**Additional context**
We currently collect mypy coverage and track it as one of key metrics and we need this feature in order to consider migration to pyright as the main type-checker.

**Comment by erictraut** [comment]
I'm interested in understanding your underlying motivation for requesting this feature. How do you use the mypy feature currently? What do you do with the per-line information?

Unlike mypy, pyright performs type analysis on all code — even for unannotated functions and methods. It also has a mode where you can disable `# type: ignore` comments, effectively ignoring them. If you run pyright with `"enableTypeIgnoreComments": false` and in strict mode, you should get a good sense for your type coverage. It won't be on a per-line basis, but it will allow you to do comparisons (e.g. to verify that there are no regressions). Pyright also supports output in JSON format, so you can easily write scripts that post-process the list of resulting diagnostics.

**Comment by vors** [comment]
Thank you for the quick replay, Eric!

We are supporting many teams working in a large monorepo. There are various degrees of the type checks adoption across these teams. We want to set some organizational goals, do targeted initiatives to increase coverage and have metrics that reflect the work.

Currently, we upload the generated reports from mypy to codecov and allow people to navigate historic trends on a per-folder basis and at the same time dig into the details up to the line basis when they want to understand how to improve.

Let's say that there is a file with 100 lines of python code.
20 of these lines are comments and blank lines.
And there is a function of 10 lines that are marked with `@no_type_checks` decorator.
And then there are another 10 lines with `# type: ignore` comments.

Ideally, I'd have a way to get the information that only 60 out of the potential 80 lines are covered by the type checker.

Thank you for the suggestion about using the strict mode and the number of generated diagnostics -- it's also an interesting metric. I believe the one that I'm describing is more akin to the `test coverage` metric that is universally understood.

**Comment by erictraut** [comment]
I don't know that tracking such metrics on a per-line basis is the best approach. 

In any case, I don't think we'd be inclined to add such a feature within pyright unless we received strong signal from pyright users. This is the first time we've received such a request. 

I'm going to close the request for now since we have no plans to add this. We might reconsider in the future if we receive additional signal (in the form of upvotes).

In the meantime, I think you can easily build a script based on the facilities I mentioned above that will produce metrics that are similar to what you're looking for. This should take no more than a few dozen lines of script, and you can produce whatever format you desire (e.g. text, json, xml).

**Comment by vors** [comment]
Sounds good, thank you for the consideration and the great tool!
