### ISSUE TITLE
dict.get ignores variable type annotation

### ISSUE THREAD

**Issue by munkybutt** [microsoft/pyright#4568]
**Describe the bug**
Not sure if this is a bug or an intended change in functionality, but dicts defined with `dict[str, Any] ` no longer allow their values to be defined as specific types when using the `dict.get` method.

**To Reproduce**
I may be misremembering, but until recently this would define the variable `var` as `str | None`:
```python
def type_test(d: dict[str, Any]) -> str | None:
    var: str | None = d.get("value1")
    return var
```
But now it defines it as `Any | None`
![image](https://user-images.githubusercontent.com/7100563/216289413-f1e22f55-1143-4a3c-9282-cae94478e632.png)

**Expected behavior**
`Any` to be defined as a more specific type when accessed with `get`

**Comment by munkybutt** [comment]
The same with:
```python
icon_name: str | None = project_data["icon"] if "icon" in project_data else None
```
![image](https://user-images.githubusercontent.com/7100563/216291787-7c41e40d-5e1c-4f1e-8b79-e6728768fed4.png)

**Comment by erictraut** [comment]
This is as designed. You have declared the type of `var` to be `str | None`, but then you're assigning a value of type `Any | None` to `var`. When you assign a type of `Any` to a variable, its type is narrowed to `Any`.

This behavior hasn't changed. I think you're misremembering. 

If parameter `d` is a dict that contains only `str` values, then you should specify the type `dict[str, str]`.

**Comment by munkybutt** [comment]
Ok fair enough

The issue I have is the `dict` value type varies by key, so annotating it would require a very long and complex type.

Aside from my user case, it also occurs if I leave the `dict` value annotation as `Unknown` which also seems like it never used to do this:
```python
def type_test(d: dict) -> str | None:
    var: str | None = d.get("value1")
```
![image](https://user-images.githubusercontent.com/7100563/216383526-4113a41a-b347-4785-86eb-9b38c3785eee.png)

It also seems inconsistent with the standard get of a `dict` which does allow the type to be modified:
```python
def type_test(d: dict) -> str | None:
    var: str | None = d["value1"]
```
![image](https://user-images.githubusercontent.com/7100563/216381995-7886239c-bdc2-41a4-84d3-79385be34ecd.png)

This also gives a different result to what I would expect:
```python
def type_test(d: dict) -> str | None:
    var: str | None = d["value1"] if "value1" in d else ""
```
![image](https://user-images.githubusercontent.com/7100563/216382342-cd0c84b5-9189-4df8-91a4-1ea9630d45d0.png)

Functions being able to convert the type without a warning being raised also seems weird:
```python
def type_test(d: dict[str, Any]) -> str | None:
    var: str | None = d.get("value1")
    return var
```
![image](https://user-images.githubusercontent.com/7100563/216384560-c1931ef1-d89c-4113-a1b2-7e6713d61f6b.png)

If `None` is removed from `var`'s annotation then the error message implies that it should work too:
```python
def type_test(d: dict) -> str | None:
    var: str = d.get("value1")
    return var
```
![image](https://user-images.githubusercontent.com/7100563/216386792-e6ff29ba-6b2f-44d3-b56b-fb4adaced168.png)


if this is as intended behaviour, I guess the correct way of defining the type would be with `typing.cast`?
