### ISSUE TITLE
Request textDocument/completion failed

### ISSUE THREAD

**Issue by ycy2077** [microsoft/pyright#457]
**Describe the bug**
I get an error message in the VSCode Output
**To Reproduce**
Searching for source files
Found 34 source files
[Error - 11:33:18 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'startsWith' of undefined
  Code: -32603 
[Error - 11:35:20 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'startsWith' of undefined
  Code: -32603 

![Snipaste_2019-12-27_23-36-52](https://user-images.githubusercontent.com/15774890/71522973-e3191780-2901-11ea-863c-d5180b6d1a8e.jpg)

**Comment by erictraut** [comment]
Do you happen to remember the context of the error? What type of statement or expression were you typing? Was it immediately after a "."?

**Comment by erictraut** [comment]
Thanks for reporting the problem. I'm not able to repro the crash. If you see it again, please note what you are doing at the time — and if possible provide a code example.

**Comment by ycy2077** [comment]
when I input Chinese char in print() function
![image](https://user-images.githubusercontent.com/15774890/71539104-493d8300-2972-11ea-8c81-a63748a6b918.png)

**Comment by ycy2077** [comment]
I find out the bug is not cased by Chinese. it case by single quotes, my chinese input software use single qutes to division, so the bug appear in Chinese.
![image](https://user-images.githubusercontent.com/15774890/71539409-c0751600-2976-11ea-8949-a3b58d5d9561.png)
![image](https://user-images.githubusercontent.com/15774890/71539414-cc60d800-2976-11ea-8e6f-9ef38a8a858e.png)

**Comment by ycy2077** [comment]
![Jietu20191228-134648-HD (1)](https://user-images.githubusercontent.com/15774890/71539566-0d59ec00-2979-11ea-99b6-05f374ef9dc5.gif)

**Comment by erictraut** [comment]
Thanks! That was very helpful. I was able to find the problem, and it will be fixed in the next version of pyright.

**Comment by erictraut** [comment]
This is now fixed in 1.1.16, which I just published.
