### ISSUE TITLE
Model Name Needed

### ISSUE THREAD

**Issue by homerolol** [microsoft/pyright#4590]
**Describe the bug**
The model name and str main in Official.py is needed

**To Reproduce**
run src/recChatGPT/Official.py

**Expected behavior**
The expected behavior is to wrap the ChatGPT API 

**Screenshots or Code**
![Screenshot (38)](https://user-images.githubusercontent.com/23107207/217126790-64c3dfcd-b1ab-4bb2-bdd3-fac7fcc6af58.png)
```

If your code relies on symbols that are imported from a third-party library, include the associated import statements and specify which versions of those libraries you have installed.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.

**Additional context**
API_Key doesn't want to be defined

**Comment by erictraut** [comment]
If you want to report a suspected bug in pyright, please include a minimal, self-contained sample of the code. If the code relies on a third-party library, include the version of that library in the bug report.

If you want to report a bug with a third-party library like chatGpt, please file the bug in the appropriate issue tracker.
