### ISSUE TITLE
Alternative syntax for unions error on type alias 

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#4615]
**Describe the bug**

[PEP 604](https://peps.python.org/pep-0604/) allows writing union types as `X | Y` in Python 3.10

When running under Python 3.9 and using `from __future__ import annotations` the `X | Y` syntax is allowed on function args but not type aliases.

**To Reproduce**
```python
from __future__ import annotations

A = str | None


def f(a: str | None) -> None:
    pass
```

Pyright errors on the type alias `A` and not the function argument `a`:
```
$ pyright
3:9 - error: Alternative syntax for unions requires Python 3.10 or newer
```
**Expected behavior**

No error on the type alias.

**VS Code extension or command-line**
pyright 1.1.293
pylance

**Additional context**

The above was run in a venv with python 3.9

**Comment by hmc-cs-mdrissi** [comment]
That code does crash in 3.9. Aliases can't use X | Y syntax in 3.9 because alias is evaluated at runtime there. You can instead do,

A: TypeAlias = "str | None"

**Comment by erictraut** [comment]
Yes, as @hmc-cs-mdrissi said, this generates a runtime exception in Python 3.9. Pyright is telling you about the error. This is intended behavior, not a bug.
