### ISSUE TITLE
Extend file-level type comment to support "off"

### ISSUE THREAD

**Issue by jakkdl** [microsoft/pyright#4617]
**Is your feature request related to a problem? Please describe.**
We have a bunch of test files in flake8-trio that I'd like to default to checking with pyright, but some tests require incorrect code and pyright will obviously complain about those. We've previously excluded all test files, but I would like to be able to enable/disable pyright selectively among those to catch when I write test code that *shouldn't* have type errors.

Listing all the files individually in the config is not a reasonable alternative in this case imo, and don't want to split them into different directories or rename them for working with different exclude patterns.

**Workarounds I tried**
* I thought https://github.com/microsoft/pyright/blob/main/docs/comments.md#file-level-type-controls would solve it, with a line such as `# pyright: off` at the beginning of it. But the docs only describe being able to write `strict` or `basic`, and trying various other parameters ("off", "ignore", "exclude") did not work.
* Alternately I thought I could exclude the files in the config, and then selectively enable them back with a `pyright: strict` - but that does not seem to enable type checks for the file again. (For quite reasonable reasons). Neither does ignored files.
* It *does* work to write `# pyright: basic, reportGeneralTypeIssues=false,reportUndefinedVariable=false,[...]` - but it's quite the hassle to have to type out every single error for a file.
* `analyzeUnannotatedFunctions=false` kind of mostly works, but gives an information warning (and I don't see a way of disabling information warnings for a file?)
* `# pyright: basic, typeCheckingMode=off` also does not work.

(sidebar, getting error messages for incorrect `# pyright: ` comments would be very handy)

**Describe the solution you'd like**
I would like a standalone line with `# pyright: off` to work on a file level, to mirror `typeCheckingMode` and the ability to write `# pyright: basic` / `# pyright: strict`

**Comment by erictraut** [comment]
This feature already been suggested (and rejected) in [this issue](https://github.com/microsoft/pyright/issues/4321).

**Comment by jakkdl** [comment]
Ah, sorry I didn't see that one. But since file-level `# type: ignore` works (although it took me a second to figure out that it has to be before the first code line) I'm fine with the status quo. Thanks!
