### ISSUE TITLE
async function return type-hint is Any

### ISSUE THREAD

**Issue by wangxin688** [microsoft/pyright#4624]
Facing a stange issue with async return type hint.
here is source code:
```python
from httpx import AsyncClient
from pydantic import BaseModel

class UserIdentity(BaseModel):
    a: str
    b: int
    c: bool

class TestClient:
    def __init__(
        self,
        client: AsyncClient,
        token: str = None,
        app_id: str = "APP_ID",
        app_secret: str = "APP_SECRET",
    ):
        self._app_id = app_id
        self._app_secret = app_secret
        self._client = client
        self._headers = {"Authorization": "Bearer " + token, "Content-Type": "application/json; charset=utf-8"}
    
    async def get_user_identity(self, code: str)->UserIdentity:
        data = {"grant_type": "authorization_code", "code": code}
        url = "https://xxxx.com/api/v1/users"
        result = await self._client.post(url, headers=self._headers, data=data)
        return UserIdentity(**result.json())

async def test():
    async with AsyncClient() as client:
        lark_api = TestClient(client=client,token="123")
        user_info = await lark_api.get_user_identity()
```

Pyright type-hint is `Any`:
![image](https://user-images.githubusercontent.com/36665036/218295340-d979b6d9-765b-4cc1-a4ea-34a506bc5a36.png)
but the same code in Pycharm will have right type hint:
![image](https://user-images.githubusercontent.com/36665036/218295392-9c2914bf-3d0d-42b6-a21e-906eb965f6b1.png)

So, I'm not sure it's a bug or pyright does not support async type-hint?

**Comment by erictraut** [comment]
The `get_user_identity` method requires you to pass an argument for the `code` parameter. If you add the required argument to the call, pyright will evaluate its type as you expect.

By default, pyright will tell you when you have omitted required arguments. You must have disabled the `reportGeneralTypeIssues` check or suppressed the diagnostics.

![Screenshot 2023-02-11 at 10 31 20 PM](https://user-images.githubusercontent.com/7040122/218296698-c6799165-b627-4072-9a5e-f30752643c8b.png)
