### ISSUE TITLE
is_dataclass doesn't promise DataclassInstance

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#4626]
```python
from dataclasses import is_dataclass

def f(X: type) -> None:
    if is_dataclass(X):
        reveal_type(X)  # information: Type of "X" is "type"
```
Should this be the pyright internal type `type[DataclassInstance]`?  As far as I can tell, this is
```python
class DataclassInstance(Protocol):
    __dataclass_fields__: ClassVar[dict[str, dataclasses.Field[Any]]]
```
[Related typing-sig post.](https://mail.python.org/archives/list/typing-sig@python.org/thread/SBAMCXJ4UAP5BJCKPFLBRRYD2SKOQHAM/)

**Comment by erictraut** [comment]
I think pyright is doing the right thing here.

Here's the overloaded definition of `is_dataclass` from typeshed:

```python
@overload
def is_dataclass(obj: DataclassInstance | type[DataclassInstance]) -> Literal[True]: ...
@overload
def is_dataclass(obj: type) -> TypeGuard[type[DataclassInstance]]: ...
@overload
def is_dataclass(obj: object) -> TypeGuard[DataclassInstance | type[DataclassInstance]]: ...
```

You are passing an argument of type `type` which is the equivalent of `type[Any]`. This matches the first overload, which does not incorporate a `TypeGuard`.

I recommend that the overload ordering in typeshed be swapped.
