### ISSUE TITLE
Object of type "None" cannot be called

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#4627]
**Describe the bug**
`type(None)()` is not a valid call even thought at runtime it works

**To Reproduce**
https://pyright-playground.decorator-factory.su/?gzip=H4sIALEt6WMC_yupLEjV8MvPS9XU0AQAHR7H_AwAAAA%3D

**VS Code extension or command-line**
pyright: 1.1.293

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.294, which I just published. It will also be included in a future release of pylance.
