### ISSUE TITLE
Adding support for Gitlab CI output

### ISSUE THREAD

**Issue by ErezAmihud** [microsoft/pyright#4628]
When using gitlab ci you can export a report in a subset of the [code-climate format](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types) - [this is the subset spec](https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool)

I would like to add a `--format` flag that can be `json` or `gitlab` depending if the user wants the json output in the custom pyright spec of the gitlab spec.

I have implemented it in a fork and getting it ready for a merge-request. \
The reason this issue is opened is to:
1. Document.
2. Be sure that the pyright maintainers would be open to add it to the pyright repo or would prefer it being an outside tool.

**Comment by erictraut** [comment]
Thanks for checking with us. I don't think we'd be interested in supporting alternate output formats in pyright itself. There are countless potential formats that different users would want, and maintaining them all in pyright itself isn't really feasible. The `--outputjson` format should allow you to wrap pyright with a small script that transforms the output into whatever format you would like.

**Comment by umowais** [comment]
في الاثنين، ١٣ فبراير ٢٠٢٣ ٠١:٥٨ Eric Traut ***@***.***> كتب:

**Comment by celestialorb** [comment]
@erictraut While there can be many various output formats I'd disagree that maintaining a small set of the most common standard output formats isn't feasible. [Ruff](https://docs.astral.sh/ruff/settings/#output-format) is able to seemingly do so with ease and it really helps keep CI definitions clean by not having to perform an extra step to convert it.
