### ISSUE TITLE
Cannot use type variable for the init argument type and method type

### ISSUE THREAD

**Issue by maomao905** [microsoft/pyright#4629]
**Describe the bug**
I created a class that receives any subclass instance of `Exception` class as an argument when initializing the class.
I defined a property that returns the exception and I want to use a type variable because those two types should be the same, but the pyright error occurs.
```
Type "T@__init__" cannot be assigned to type "T@orig_exp" (reportGeneralTypeIssues)
```

**To Reproduce**
```sh
$ pyright sample.py
```

sample.py
```python
from typing import TypeVar

T = TypeVar("T", bound=Exception)

class SampleException(Exception):

    def __init__(self, msg: str, orig_exp: T):
        self.__msg = msg
        self.__orig_exp = orig_exp

    @property
    def msg(self) -> str:
        return self.__msg

    @property
    def orig_exp(self) -> T:
        return self.__orig_exp
```

**Expected behavior**
There should be no lint error.

**VS Code extension or command-line**
command-line with the pyright version 1.1.293

**Comment by erictraut** [comment]
You are using the type variable incorrectly here. It appears that you intend for it to be a class-scoped type variable. To do this, you need to add it to the class declaration, as follows:

```python
class SampleException(Exception, Generic[T]):
    ...
```
