### ISSUE TITLE
Callable params and type-hint is not effective when import in a other file

### ISSUE THREAD

**Issue by wangxin688** [microsoft/pyright#4632]
fileA i18n_loder.py:
```python
rom collections import defaultdict
from functools import reduce
from operator import getitem
from typing import Callable, Literal, Union

from src.app.netcare.const import LOCALE
from src.utils.i18n_trans import locale
from src.utils.singleton import singleton


@singleton
class I18n:
    def __init__(self, locales: dict = locale) -> None:
        self.locales = locales

    def gettext(self, path: str, locale: Literal["en_US", "zh_CN"] = "en_US", **kwargs) -> Union[dict, str]:
        founded: Union[dict, str] = self._find(locale, path)

        if len(kwargs) > 0 and isinstance(founded, str):
            try:
                return founded.format_map(defaultdict(str, **kwargs))
            except KeyError:
                return founded
        return founded

    def _find(self, language: LOCALE, path: str) -> Union[dict, str]:
        try:
            return reduce(getitem, path.split("."), self.locales[language])
        except (KeyError, TypeError):
            return f"missing translation for {language}"


_i18n: I18n = I18n()
_: Callable[..., Union[dict, str]] = _i18n.gettext
```
file B will import '_' function to load i18n message for locale
```
from .i18n_loader import _
a = _()
```
there is not function params and type-hint when use in different file. it working in the same file.
in the same file:
![image](https://user-images.githubusercontent.com/36665036/218714505-243f882a-b2fe-4a7e-ae5c-a43ba17dbea4.png)
in the different file:
![image](https://user-images.githubusercontent.com/36665036/218714573-7ae7475e-097f-4505-9093-c2bd663cb790.png)
it's working in pycharm:
![image](https://user-images.githubusercontent.com/36665036/218714723-214f042c-0c56-46df-88d0-330df9218590.png)
So I don't know if this is a bug?  or I  just need to replace `...` with specifical params and types.
thanks

**Comment by erictraut** [comment]
This is working as designed.

The type of `_` is declared as `Callable[..., Union[dict, str]]`. Within that file, it is assigned a value of `_i18n.gettext`, which is compatible with the declared type. Locally, type narrowing is applied for the assignment. That means the local type (immediately after the assignment) takes on the narrowed type.

When you import the symbol from another file, the type of that symbol is the declared type (`Callable[..., Union[dict, str]`). Any type narrowing that was applied locally in the other file does not apply to the import.

If your intent is for `_` to simply be an alias for `_i18n.gettext`, then you should omit the type declaration for `_`: `_ = _i18n.gettext`.
