### ISSUE TITLE
Subclasses of tuple seem to lose the ability to be matched

### ISSUE THREAD

**Issue by tmke8** [microsoft/pyright#4634]
**To Reproduce**

This works fine:
```python
def f(x: tuple[int, int] | None) -> None:
    match x:
        case tuple((y, z)):
            reveal_type(y)  # Type of "y" is "int"
            print(f"{y}, {z}")
        case None:
            print("nothing")
```
but if I create a subclass it doesn't work anymore:
```python
class IntPair(tuple[int, int]):
    pass

def g(x: IntPair | None) -> None:
    match x:
        case IntPair((y, z)):
            reveal_type(y)  # Type of "y" is "Unknown"
            print(f"{y}, {z}")
        case None:
            print("nothing")
```

I'm not sure whether subclassing `tuple` is maybe discouraged, but I would have thought it would work. It does definitely work at runtime and it also works in mypy. See here: https://mypy-play.net/?mypy=latest&python=3.11&gist=3d04219117f4fb417390417d7e84a9d8

**Comment by gvanrossum** [comment]
Sounds good, I was going to recommend looking at what CPython allows. In any case, while the PEP calls out a certain set of builtin types, the `__match_args__` mechanism is powerful enough to get the same effect for any type: define `__match_args__ = ["__some_private_attr"]` and have a property named `__some_private_attr` that returns `self`.
