### ISSUE TITLE
pyright always installs prebuilt node

### ISSUE THREAD

**Issue by lucidfrontier45** [microsoft/pyright#4656]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**
pyright installs prebuilt node even after the first run. This bug happens at 1.1.293 and and 1.1.294. 1.1.292 doesn't have this bug.

**To Reproduce**
1. `python3.11 -m venv venv`
2. `venv/bin/pip install pyright==1.1.294`
3. `venv/bin/pyright`
4. `venv/bin/pyright`

**Expected behavior**

At the second run pyright doesn't try to install node again.

**Screenshots or Code**

![image](https://user-images.githubusercontent.com/655305/219826408-983aeca3-91e8-4265-b609-c1a938c9c1d1.png)

**Additional context**

Tested on Windows 11, WSL2, Debian 11, Python3.11.1

**Comment by erictraut** [comment]
Pyright runs on top of node. It doesn't install node. 

It looks like you're using the Python wrapper for pyright, which does install node. The wrapper is maintained by the community. Please report any bugs related to the wrapper in [this project](https://github.com/RobertCraigie/pyright-python).
