### ISSUE TITLE
Typing a function that specializes a function.

### ISSUE THREAD

**Issue by hgrecco** [microsoft/pyright#4659]
**Describe the bug**
I have coded a function that specialize a generic class according to some rules. While the function works, pyright (through pylance in vscode) reports a bunch of errors. I have narrowed to a simple example that it receives a generic or specialized tuple/list and if it is specialized returns the same. If it is generic (or specialized to Any in one case), specialize it according to a value.

**To Reproduce**
```python


import typing as ty

# These are the concrete types
CT = list[int] | tuple[int] | list[float] | tuple[float]

############
# Version 1
############

# Here pyright says that the parameter ty is partially unknow, which is fine
# because is one of the options
# It also reports an error for both return outputs.
def specialize1(typ: type[list] | type[tuple] | CT, value: int | float) -> CT:
    if typ in (list, tuple):
        return typ[type(value)]
    
    return typ

############
# Version 2
############

GT2 = list[ty.Any] | tuple[ty.Any]

# Here pyright reports an error for the `get_origin` output
def specialize2(typ: type[CT] | type[GT2], value: int | float) -> type[CT]:
    if typ in (list[ty.Any], tuple[ty.Any]):
        return ty.get_origin(typ)[type(value)]
    
    return typ
    
############
# Version 3
############

T = ty.TypeVar("T")

GT = list[T] | tuple[T]

# Here pyright  reports an error for both return outputs.
def specialize3(typ: type[CT] | GT[T], value: int | float) -> type[CT]:
    if typ in (list, tuple):
        return typ[type(value)]
    
    return typ
```

**Expected behavior**

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
def foo(self) -> str:
    return 3
```

**VS Code extension or command-line**

VS Code
Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No

PyLance: v2023.2.30

**Comment by erictraut** [comment]
Why are you doing runtime specialization, out of curiosity? This is quite atypical, and it's going to interfere with static type checking rules. Specialization is normally a type-checking concept, as type arguments are generally ignored at runtime. Are you using some runtime type checker that requires specialization?

Looking at your code sample, pyright is behaving as I would expect in each case. I don't see any bugs here. Is there a specific behavior that you would like me to explain in more detail?

In Version 1 of your code, the parameter `typ` is annotated with an odd union of both instantiables (e.g. `type[list]`) and instances (e.g. `list[int]`). Is this what you intend? I suspect that you meant for all subtypes in the union to be instantiable.

In Version 2 of your code, you're calling `get_origin`, which can return `None`. Your code isn't checking for this condition.

**Comment by hgrecco** [comment]
Thanks for your prompt response. I am working on a package that uses annotations during runtime to do additional things. For convenience reasons, I am allowing users to subspecify the annotation and then the library infers the rest from context.

Consider the following dummy example.

```python
x: tuple = (1., 2., 3.)
```
the library will redefine the annotation as:
```python
x: tuple[float] = (1., 2., 3.)
```
This information is then used in other parts of the package. I am trying to use type annotations in the helper functions.

Regarding your comments about the code. 

> In Version 1 of your code, the parameter typ is annotated with an odd union of both instantiables (e.g. type[list]) and instances (e.g. list[int]). Is this what you intend? I suspect that you meant for all subtypes in the union to be instantiable.

What do you mean by odd annotation. I meant to say it is either the generic list type, the generic tuple type or a concrete list or tuple. Also, what do you mean by all instantiatable. `list[int]` is instantiatable:

```python
>>> list[int]((1, 2, 3))
[1, 2, 3]
```

> In Version 2 of your code, you're calling get_origin, which can return None. Your code isn't checking for this condition.

`get_origin` will never return `None` as its argument is either `list[ty.Any]` or `tuple[ty.Any]`. So I do not need to check for this.

**Comment by erictraut** [comment]
> the library will redefine the annotation as... `tuple[float]`

Your library's behavior is therefore inconsistent with the rules of static type checking. According to PEP 484, an annotation of `tuple` is the equivalent of `tuple[Any]`.

> What do you mean by odd annotation.

If you expand the type alias `CT`, the annotated type of parameter `typ` is:
```python
type[list] | type[tuple] | list[int] | tuple[int] | list[float] | tuple[float]
```
A value with the annotation `type[list]` is instantiable, but a value with the annotation `list` is not (because it refers to an already-instantiated `list`). Your union therefore contains a combination of instantiable and non-instantiable types. I don't think that's what you're intending here.

> `get_origin` will never return `None`

The type declaration for `get_origin` is found in `typing.pyi`:
```python
def get_origin(tp: Any) -> Any | None: ...
```
The declaration indicates that it can return `None`. You may happen to know that in your particular use case, it won't return None. In that case, you would need to add an `assert` to your code to both document your assumption (for the static type checker and for human readers) and provide runtime validation of your assumption.

```python
        x = ty.get_origin(typ)
        assert x is not None
        return x[type(value)]
```

**Comment by hgrecco** [comment]
Thanks again for your response

> A value with the annotation type[list] is instantiable, but a value with the annotation list is not (because it refers to an already-instantiated list).

My fault here. When I simplified the code, I missed adding `type` in version 1 annotations. Fixed now.

> Your library's behavior is therefore inconsistent with the rules of static type checking. According to PEP 484, an annotation of tuple is the equivalent of tuple[Any].

I agree, but providing certain flexibility that makes the code more readable or flexible without sacrificing output correctness is sometimes desirable. Consider:

```
class MyClass:
     s: tuple
     # rest of th code goes here

obj = MyClass(s=(1., 2., 3.)
```

Upon instantiation, the library goes through the arguments and:
1) check that I have been provided a tuple (as required)
2) go through the elements and, as they are float, store someplace that `s` is of type `tuple[float]`. 

Why should this be a problem?

> You may happen to know that in your particular use case, it won't return None.

It is not what `I` know but what the code knows, as it is below an if that serves as a guard.

```python
    if typ in (list[ty.Any], tuple[ty.Any]):
        return ty.get_origin(typ)[type(value)]
```
When return line is reached, the origin is either `list` or `tuple`.

**Comment by erictraut** [comment]
> Why should this be a problem?

You will run into issues with static type checking if you are interpreting type annotations differently than the static type checking rules. For example, if you have a variable whose type is annotated as `type[list]`, a static type checker will interpret this as `type[list[Any]]`, which means that it is already specialized. If you attempt to respecialize it, that will be considered an error by a static type checker.

> It is not what I know but what the code knows

I'm not sure what you mean by "the code knows". According to static type checking rules, `get_origin` always returns type `Any | None`. This is independent of any type guards you may be using. You happen to have some knowledge about the internal behavior of `get_origin` to know that in this particular case it won't return `None`, but a static type checker does not have access to this knowledge. So you're making an assumption that is not valid for a static type checker. To document this assumption, you would need to include an `assert` as I mentioned above.

**Comment by hgrecco** [comment]
Consider the following code: 
```python
def f(x: int | None):
    return 2 * x

def g(x: int | None):
    if isinstance(x, int):
        return 2 * x
    raise Exception
```

In `f`, pylance reports a problem as `2 * None` is not supported. But the second is fine, because `2 * x` is behind an if that is like a guard. Without any assertion of anything else. My take is that pyright is not propagating types through `if <something> in <tuple of types>`:

as this reports no problems:
```python
def h(x: int | None):
    if type(x) is int:
        return 2 * x
    raise Exception
```

but this does:
```python
def h(x: int | None):
    if type(x) in (int, ):
        return 2 * x
    raise Exception 
```

**Comment by erictraut** [comment]
There are a couple of issues with your logic.

First, `isinstance(x, int)` is a supported type guard pattern whereas `<something> in <tuple of types>` is not. For a complete list of supported type guard patterns, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards).

Second, even if `<something> in <tuple of types>` were a supported type guard pattern, this would narrow the type of the expression `<something>`, but that would have no bearing on the output type of `get_origin`. The `get_origin` function is not overloaded. It always returns `Any | None` regardless of the types of its input arguments.

**Comment by hgrecco** [comment]
Thanks!
