### ISSUE TITLE
need LSP in WSL to use python env from Windows

### ISSUE THREAD

**Issue by azinsharaf** [microsoft/pyright#4665]
I might post this question in different channels since frankly I'm not sure about the source of issue.

I need to use Windows at work mainly because I use a commerical python library (`ArcPy`) which is only works in Windows with the current license we have.

Since I highly prefer to work on linux environment I installed WSL on Windows and doing all of my tasks with it. Everything works fine except that python library in Windows. Currently I am writing python codes in WSL using Neovim and Pyright LSP. I need to use that python venv in Windows. I've set `python3_host_prog` pointing to `python.exe` in Windows (using `/mnt/c/...` and `:checkhealth` in neovim recognizes it successfully.)

The problem starts with LSP. If I open the python file in Neovim (from WSL) pyright LSP crashes so I won't have any code completion, etc. LSPInfo log doesn't give me any information.

I have installed and configured Neovim in Windows too (using astroNvim) and it works but it has its own issues and perfromance is not good.

My goal is the set the LSP in WSL in a way that can use the python env from Windows. Hope it is doable.

**Comment by erictraut** [comment]
The maintainers of pyright don't have any experience with neovim, so there's not much we can do to help you here.

Please check with the maintainer of the pyright LSP for neovim. They may be able to help you.
