### ISSUE TITLE
Literal integers are translated into `int` in type transformations

### ISSUE THREAD

**Issue by mailund** [microsoft/pyright#4677]
**Describe the bug**

While trying to statically check matrix dimensions in a small library, I ran into a problem with `pyright` turning `Literal[n]` for some integer `n` into type `int`.

**To Reproduce**

A simplified version looks like this:

```python

from __future__ import annotations

from typing import (
    Generic,
    Literal as L,
    TypeVar, 
    overload,
    assert_type
)


_D1 = TypeVar("_D1")
_D2 = TypeVar("_D2")
_D3 = TypeVar("_D3")

# TypeVarTuple is an experimental feature; this is a work-aroudn
class Shape:
    """Class that works as a tag to indicate that we are specifying a shape."""
class Shape1D(Shape, Generic[_D1]):
    """Class that works as a tag to indicate that we are specifying a shape."""
class Shape2D(Shape, Generic[_D1,_D2]):
    """Class that works as a tag to indicate that we are specifying a shape."""


_Shape = TypeVar("_Shape", bound=Shape)
Scalar = int | float


class Array(Generic[_Shape]):
    @overload # Adding witht the same shape
    def __add__(self: Array[_Shape], other: Array[_Shape]) -> Array[_Shape]:
        ...
    @overload # Adding with a scalar
    def __add__(self: Array[_Shape], other: Scalar) -> Array[_Shape]:
        ...
    def __add__(self, other) -> Array:
        return self # Dummy implementation
    
    # Adding with a scalar
    def __radd__(self: Array[_Shape], other: Scalar) -> Array[_Shape]:
        return Any # type: ignore

    @overload # matrix-matrix multiplication
    def __matmul__(
        self: Array[Shape2D[_D1,_D2]], other: Array[Shape2D[_D2,_D3]]
    ) -> Array[Shape2D[_D1,_D3]]: ...
    @overload # matrix-vector multiplication
    def __matmul__(
        self: Array[Shape2D[_D1,_D2]], other: Array[Shape1D[_D2]]
    ) -> Array[Shape1D[_D1]]: ...
    @overload # vector-matrix multiplication (one could argue for a different shape)
    def __matmul__(
        self: Array[Shape1D[_D1]], other: Array[Shape2D[_D1,_D2]]
    ) -> Array[Shape1D[_D2]]: ...

    def __matmul__(self, other) -> Array:
        return self # Dummy implementation

    
A = Array[Shape2D[L[3],L[4]]]()
B = Array[Shape2D[L[4],L[5]]]()
x = Array[Shape1D[L[4]]]()
y = Array[Shape1D[L[3]]]()

reveal_type(A + 1.0) ; assert_type(A + 1.0, Array[Shape2D[L[3],L[4]]])
reveal_type(1.0 + A) ; assert_type(1.0 + A, Array[Shape2D[L[3],L[4]]])
reveal_type(A + A)   ; assert_type(A + A,   Array[Shape2D[L[3],L[4]]])

reveal_type(A @ x) ; assert_type(A @ x,   Array[Shape1D[L[3]]])
reveal_type(y @ A) ; assert_type(y @ A,   Array[Shape1D[L[4]]])

reveal_type(A @ B) ; assert_type((A @ B), Array[Shape2D[L[3],L[5]]])
```

Mypy playground [here](https://mypy-play.net/?mypy=1.0.0&python=3.11&gist=d0c6b2b2cb668a284094958c6c141684)
Pyright playground [here](https://pyright-playground.decorator-factory.su/?gzip=H4sIAMa89WMC_7VVwW6bQBC98xUj5wIqsWo7uThKFdJIvfiWqJfIQhsY7FVhFy1LYqR-fGd3jWMwRE0rcwDtvNk37w2z4GVKFhDHWa1rhXEMvCil0sCEkJppLkXleTZHNyUXmxb3PaDrBwpUPAntYsU1KpYDq2DlIk9NiT-ZCsGu5CuqXLLUYayqUOmYWNELPM-LH2Zw2-7wJ7ScBBScd4NzG1x0gwsKehdt5KkucwRekQXAXUn6ChSadGXIjMcb0FtCTQK8SfXrkilZp8JLcpIEj1tW4tIqnEwm321Mb5m2qZXxxkCzDWgJXKQ8YRr3OAJTCFWJCc8a0ykGlSGbEs8x-ezBt8-w7d4zeV0HZ605H6oZUjvPUZfepS3WeUk2MgnhRdYivbWrwHtMWM4U5XGh4TdkNB2atjvhkVKs8Q967ZZW7l07S3ABUZoaBW9cbzXJI1msQCfH5qaY0XyzNI1jv8I8WzrmljEESZtULxrA5bduxBU2l0IaIwGRaKi6md8l8I2QCj-SZjpk3X5Kk2vQv4vp19kTvxOeEJksYnqoi6IxZz1He3rMh8Cm2tvB2YApdV5XJz0umFZ8d-keUNS55mVuZrVV7GQRThgJO9Q4Vrg_JIdT0Z-Kd3xO-GK9tixHDroElLCE6XQ6JvYVEy3VWcXOrNgRoRacjYl06oY7Cr4UCIms85Q-AZsaISMjDFKeZahoUtzBCz5nptUz2vW90XEz89bMUOH_n3w3-hF9qbrKVs-Ldbh6vlqv137g3Q_gVwa_dviui88cbqFmAFo4yFP4iiy3f0o_gi8wm34N4Ob4B9qGw3F5QYeGcmlH1KfZh_-aJnIkMKCGSOAjmh7PHexOPVGwx3LoS1dHQ6knZmxwaP-IgPs-wT460o1ry_IHDaSArT8JAAA%3D)

The addition works fine with both checkers, but the matrix multiplication doesn't.

When doing `A @ B`, for example, `mypy` sees that `A`'s first dimension is `_D1=Literal[3]` and that `B`'s second dimension is `_D3=Literal[5]`, so it gives the multiplication the type `Array[Shape2D[Literal[3],Literal[5]]`.

With `pyright`, on the other hand, the type is inferred to be `Array[Shape2D[int,int]]`. The `Shape2D` is correct, but the `Literal[-]` types got turned into `int`.

While it is true that the `Literal[-]` types here _are_ integers, `Literal[3] != int`, so what gives?

If I don't use `Literal[-]`, both checkers are happy to infer the dimensions of a matrix-multiplication. They will both take the first and third dimensions and make a matrix out of them.

```python
class N: pass
class M: pass
class K: pass

AA = Array[Shape2D[N,M]]()
BB = Array[Shape2D[M,K]]()
reveal_type(AA + AA); assert_type(AA + AA, Array[Shape2D[N,M]])
reveal_type(AA @ BB); assert_type(AA @ BB, Array[Shape2D[N,K]])
```

When it is the (abstract) types `N`, `M`, and `K`, that I use for dimensions, the inferred dimensions are the correct.

**Expected behavior**

I was expecting `Literal[n]`  to remain `Literal[n]` in the output types, and not be translated into `int`.

**Comment by erictraut** [comment]
This is by design. See [this documentation](https://github.com/microsoft/pyright/blob/main/docs/mypy-comparison.md#constraint-solver-behaviors) for details. Pyright's constraint solver retains literals for TypeVars only in cases where doing so is required to satisfy the constraints.
