### ISSUE TITLE
Question: Fine grained issue checking

### ISSUE THREAD

**Issue by bbkgh** [microsoft/pyright#4686]
Hi. Is there anyway to just run a specific subset of reportGeneralTypeIssues (or any other ruleset) which generates `"X" is unknown import symbol` ?  I want to just check my codes for this issue type.
thanks

**Comment by erictraut** [comment]
There's currently no way to disable specific diagnostics. Pyright supports about 60 independent diagnostic rules (e.g. `reportGeneralTypeIssues`) that can be controlled independently, but you cannot control the individual diagnostic messages within them.

You can suppress diagnostics on an individual line by using a `# type: ignore` or `# pyright: ignore` comment.

Unknown imports will affect the type checking of your code, potentially masking bugs in your code. Is there a reason you don't want to fix those issues in your code?
