### ISSUE TITLE
Possible use an ignore directive conditional on Python version?

### ISSUE THREAD

**Issue by wch** [microsoft/pyright#4710]
I'm using pyright to do type checking in on GitHub Actions. Some of the type annotations I'm using are based on Pandas 1.5. However, on Python 3.7, the latest available version of Pandas is 1.3, which has some different types from 1.5. For example, in 1.3, `pd.Series` does not expect a type argument, but in 1.5 it does expect one, so you would do something like `pd.Series[int]`. I use `pd.Series[int]` in my code, and this causes pyright to report errors on Python 3.7, even though the code in question runs just fine on Python 3.7 with Pandas 1.3.

Is there a way to use a `# pyright: xxxx=False` directive in the file, conditional on the Python version?

**Comment by erictraut** [comment]
You can specify which version of Python you want pyright to assume when it is performing its type analysis (through the `pythonVersion` configuration setting or command-line option. You can also run python multiple times, once for different versions of Python (or different platforms, if you want).

There is no way to conditionalize `# pyright` comments in a file based on Python version. It's unlikely that we would add such a feature.
