### ISSUE TITLE
`JSONDecodeError` with `--outputjson`

### ISSUE THREAD

**Issue by jgbos** [microsoft/pyright#4711]
Not sure if this is an issue with pyright, but I'm struggling to use the JSON output.

I'm running pyright tests on code using python's `subprocess`:

```python
from pathlib import Path
import shutil
import json

_found_path = shutil.which("pyright")
PYRIGHT_PATH = Path(_found_path) if _found_path else None

proc = subprocess.run(
    [str(PYRIGHT_PATH .absolute()), str(file_.absolute()), "--outputjson"],
    cwd="<path to package dir>",
    encoding="utf-8",
    text=True,
    capture_output=True,
)

json.loads(proc.stdout)
```

I (sometimes) get this error:
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

On my system the error does not produce itself consistently, but on my Gitlab CI it always does.  

Does this sound like something that could be a result of pyright?  I'll try to get an example json output for you.

**Comment by erictraut** [comment]
This is unlikely to be a problem in pyright. You'll need to debug it more to determine the problem. Perhaps dump the JSON output when you receive the error and manually examine it.
