### ISSUE TITLE
Improvement to the interaction between --verifytypes and PEP 696

### ISSUE THREAD

**Issue by bijij** [microsoft/pyright#4720]
**Is your feature request related to a problem? Please describe.**
Pyright's `--verifytypes` feature will produce an error if a type annotation containing a generic type with generics with PEP 696 defaults is not explicitly annotated.

**Describe the solution you'd like**
`--verifytypes` (and perhaps this should be configurable) should not error if a generic type with defaults is not explicitly annotated, assuming the type is the default.

**Comment by erictraut** [comment]
I'm not able to repro the problem. Could you provide a minimal, self-contained repro?

Here's my attempt to repro the problem:

test_pkg1
 - __init__.py
 - py.typed
 
```python
# __init__.py
from typing import Generic, TypeVar

_T = TypeVar("_T", default=int)

class Foo(Generic[_T]): ...

# Note that Foo does not have any type arguments
def foo(x: Foo) -> None:
    pass
```

The above code produces no errors when I run `--verifytypes` on it. If I remove the `default=int` from the `_T` TypeVar call, then `--verifytypes` produces an error as expected. So it appears to be working correctly.

**Comment by erictraut** [comment]
Closing as "can't repro". If you have more details and a repro, I'm happy to reopen and investigate.
