### ISSUE TITLE
Class attributes types doesn't depends on __init__ passed arguments

### ISSUE THREAD

**Issue by AiroPi** [microsoft/pyright#4730]
I don't know if this is a bug or it is intended, but I guess it could be improved

**To Reproduce**
In VSCode or with pyright playground.

**Expected behavior**
Type of class attribute could be more precise while we explicitly pass them in arguments.

**Screenshots or Code**
```python
class Test:
    def __init__(self, a: str | None):
        self.a: str | None = a
        
class Test2(Test):
    def __init__(self):
        super().__init__("1")
        b = self.a.lower()  # here it says None hasn't lower() method, but we explicitly passed "1" that is a string

test = Test("1")
test.a.lower()  # same
```

**VS Code extension or command-line**
both

**Comment by erictraut** [comment]
Pyright's behavior is correct here. The declared type of instance variable `a` is `str | None`. Type narrowing is performed only locally within a function. It is not narrowed based on function or method calls.
