### ISSUE TITLE
Allow multiple directories for stubPath

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#4746]
**Is your feature request related to a problem? Please describe.**
We have github projects that have multiple submodules.  Each submodule has a set of stubs, and we'd like the parent project to be able to refer to all the different stub paths.  This would be equivalent to specifying multiple paths with `mypy` using `mypy_path`, by extending `stubPath` to allow multiple directories.

**Describe the solution you'd like**
Allow `stubPath` to specify multiple paths to look for stubs.

**Comment by heejaechang** [comment]
how about using `extraPaths`? https://microsoft.github.io/pyright/#/configuration?id=main-configuration-options

**Comment by Dr-Irv** [comment]
> how about using `extraPaths`? https://microsoft.github.io/pyright/#/configuration?id=main-configuration-options

It's not clear from the documentation that is doing the same thing as what `stubPath` does, where we can create different stubs for different modules.

**Comment by erictraut** [comment]
It should work fine. The `extraPaths` are used after `stubPaths`, but you can define the resolution order in `extraPaths`.
