### ISSUE TITLE
FYI: 404 on pyright npm page

### ISSUE THREAD

**Issue by linter-purgatory** [microsoft/pyright#4749]
**Describe the bug**
The "command line tool" link on this page links to https://github.com/Microsoft/pyright/blob/HEAD/packages/pyright/docs/command-line.md, which does not exist and 404s. It should be https://github.com/microsoft/pyright/blob/main/docs/command-line.md.

**To Reproduce**
Click the link

**Expected behavior**
no 404

![image](https://user-images.githubusercontent.com/85951133/223877483-fac48a25-7015-4bf8-8636-3d29717e7cbd.png)

**Comment by erictraut** [comment]
How are you accessing the documentation page? You need to view the documentation through the path https://microsoft.github.io/pyright/#/.

**Comment by linter-purgatory** [comment]
It was this page, but it looks like the readme is missing now? https://www.npmjs.com/package/pyright

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.299, which I just published.
