### ISSUE TITLE
Submodules for aliases are always considered unknown (even for 3rd party libraries)

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pyright#4750]
Here's a specific [example](https://github.com/pallets-eco/flask-sqlalchemy/blob/5f47f03bec05e9765b293331a01b86ef7246b689/src/flask_sqlalchemy/extension.py#L323):

```python
import sqlalchemy as sa
import sqlalchemy.orm

def make_scoped_session(
        self, options: dict[str, t.Any]
    ) -> sa.orm.scoped_session[Session]: # Pyright thinks sa.orm is unknown
```

I understand this is by design at the moment because what the user should have done is something like this:

```python
import sqlalchemy as sa
import sqlalchemy.orm as sa_orm


def make_scoped_session(
        self, options: dict[str, t.Any]
    ) -> sa_orm.scoped_session[Session]: # Pyright understands sa_orm now
```

The problem is there are 3rd party libraries that are doing this. 

In my code, I'm trying to use the return value from `make_scoped_session`

```python
session = make_scoped_session()
session. # Pylance/Pyright thinks session is unknown so offers no completions
```

From my point of view Pylance seems broken. And it's very hard for me to tell that the root cause is Flask-SQLAlchemy taking advantage of module side effects.

**Comment by rchiodo** [comment]
Here's the problem in a real app:

```python
@bp.route('login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        user: User | None = db.session.execute(db.select(User).filter_by(username=username)).scalar_one_or_none()
```

`db.session` is unknown in this case because of the implementation of `make_scoped_session`. If I fix the code in Flask-SQLAlchemy, I can get completions:

![image](https://user-images.githubusercontent.com/19672699/223881401-46698616-9a98-461b-99ff-04e3b826896e.png)

**Comment by erictraut** [comment]
This is by design. We discussed this particular case yesterday in our meeting.

This is disallowed because it's a loader side effect that should not be relied upon. This was the conclusion of a recent discussion in python/typing. See [this documentation](https://microsoft.github.io/pyright/#/import-resolution) for details.

Please file bugs against the third-party libraries who are relying on this behavior.

**Comment by rchiodo** [comment]
I realize it's a bug in the 3rd party library but I don't think any of users will understand that. They just think Pyright/Pylance doesn't work. 

That's my argument for making a special case for this situation in 3rd party libraries.

**Comment by rchiodo** [comment]
Or maybe we could detect this situation when they're doing a completion and we can say this is a bug in the 3rd party library at that point?

**Comment by erictraut** [comment]
No, this is a bug in the library. Please work with the library authors to fix it. Working around library bugs is not a scalable approach.

**Comment by rchiodo** [comment]
Just to make sure I'm clear on understanding the potential problems, this might happen:

``
import a

def do_stuff():
    print(a.b.stuff)

import a.b
```

So depending upon when `do_stuff` is called it may or may not succeed.

I want to be clear when I log the issue against the 3rd party library

**Comment by rchiodo** [comment]
My guess is the 3rd party library authors will reject the change unless I can clearly demonstrate it potentially failing. 

For them the situation is always this:

```python
import a
import a.b
```

So as far as they're concerned, those two statements are atomic.

**Comment by gramster** [comment]
It's ugly, but unless I am reading things wrong, this is the expected behavior, so it isn't a bug in the 3rd party library. In **https://docs.python.org/3/reference/import.html#submodules** section 5.4.2 on submodules:

> When a submodule is loaded using any mechanism ...  a binding is placed in the parent module’s namespace to the submodule object.

**Comment by erictraut** [comment]
Please work with the library author to get this fixed. I don't plan to compromise this principle in pyright. We spent a bunch of time discussing this in python/typing, and I was insistent that we establish a principle for this very reason.

**Comment by gramster** [comment]
I thought the discussion there was about import hooks and weird custom import stuff, but this seems unrelated to that.

**Comment by erictraut** [comment]
No, this is specifically a case that we discussed. Guido agreed that this should not be supported. See point #4 in [this post](https://github.com/python/typing/issues/1358#issuecomment-1454845928). This is the very "slippery slope" that I was concerned about. Please work with the library author to get this fixed. If they are unwilling to accept a PR to fix it, then tell pylance users to report the problem to the library author.

**Comment by gramster** [comment]
We can't tell them to fix something that is not broken. See emphasis above: binding 'orm' in the sqlalchemy module to the submodule sqlalchemy.orm is a "fundamental feature of the import system".

**Comment by erictraut** [comment]
Rich has asserted that it is broken from the perspective of pylance users. If you want to fix the problem that pylance users have reported, the right place to fix it is in the library. Please pursue that approach before suggesting that we should violate this principle in the type checker.

There are many things in Python that happen to work at runtime but will produce broken experiences for developers who are relying on language servers and other static analysis tools. This is an ecosystem, and all participants in the ecosystem must work together to improve it. In this case, it's reasonable to ask the library author to make a change (or to accept a PR that introduces a change).

**Comment by gramster** [comment]
Can you clearly state the principle for future reference?

**Comment by erictraut** [comment]
Refer to the bottom of this post: https://github.com/python/typing/issues/1358#issuecomment-1454845928

**Comment by erictraut** [comment]
Also, see [this documentation](https://microsoft.github.io/pyright/#/import-statements) for pyright.

**Comment by gramster** [comment]
We can stick to that, but the only standing we then have to tell someone else to change their code is as a workaround to us not supporting the documented semantics of submodule loading, not as a 'fix' to their code.

**Comment by dsedivec** [comment]
What is the recommended way to get around this in code?

`import sqlalchemy.orm` means a very commonly used name just became 4.6x longer, to say nothing of additional wrapping and indentation necessary as a result.  This is surely not even the worst case, just a relatively common one from where I stand.

`from sqlalchemy import orm` might be a bit too opaque that you're referring to SQLAlchemy's `orm` package.

I guess we could use `import sqlalchemy.orm as sa_orm`, which readers can probably recognize.

We could also probably disable type checking on `sa.orm` or something, but that's very noisy and could hide actual important errors.

We're not left with a lot of useful options here?

**Comment by Andrej730** [comment]
I guess the recommended pyright workflow is to use `import sqlalchemy.orm as sa_orm` for this case - so it would take replacing `sa.orm` with `sa_orm` in the entire codebase to make code compliant.

I wonder if there's a hack to make type checker recognize submodule as an attribute of aliased module, so code can be made compliant without changing the established use of library. 

Assigning it directly of course creates more problem than resolves:

<img width="699" height="226" alt="Image" src="https://github.com/user-attachments/assets/eb813765-47a5-4328-acab-5da4de3047eb" />
