### ISSUE TITLE
Pyright treats non-bytestring arguments of (Django) HttpResponse's constructor as errors. 

### ISSUE THREAD

**Issue by anthony-S93** [microsoft/pyright#4753]
I'm new to Django and I'm still trying to get the hang of things, that's why I rely heavily on Pyright's error messages.  Today, I saw this error which I find a bit puzzling: 

![2023-03-09-132712_1506x165_scrot](https://user-images.githubusercontent.com/69449791/223929569-bed594c9-80f3-4f7e-a1ce-a36d93ebff6a.png)

To test things out, I changed the constructor argument to a byte string, and the error message disappears. 

![2023-03-09-133731_488x117_scrot](https://user-images.githubusercontent.com/69449791/223930061-150e693f-54fc-41da-926d-bfe526c1ad9c.png)

Apparently, according to Pyright, only byte strings are allowed as arguments for `HttpResponse`'s constructor. However, that's not actually the case to [Django's documentation](https://docs.djangoproject.com/en/4.1/ref/request-response/#httpresponse-objects). 

Am I missing something here?

**Comment by erictraut** [comment]
Can you provide a minimal, self-contained code sample in text form? I'm not able to debug issues from partial screen shots.

**Comment by anthony-S93** [comment]
Here are the steps I went through these steps to create the environment. 
1) `mkdir helloworld`
2) `cd helloworld`
3) `python -m venv .venv/`
4) Activate the virtual environment
4) `pip install django~=4.0.0`
5) `django_admin startproject helloworld_project .`
6) `python manage.py startapp myApp`
7) `cd myApp/` and edit `views.py` as follows
```python
from django.http import HttpResponse

def myView(request):
    return HttpResponse("Hello, world.")
```

**Comment by erictraut** [comment]
Thanks, that's helpful.

The `django` library has no type information, so pylance needs to infer type information from the available code. In this particular case, the `HttpResponse` is defined as follows:

```python
class HttpResponse(HttpResponseBase):
    def __init__(self, content=b"", *args, **kwargs):
        ...
```

The parameters have no static type annotations, so pylance needs to infer their types. In this case, it's using the default argument type (which is a `bytes` object) to infer that the `content` parameter must be `bytes`.

There are type stub files available for django that you can install into your Python environment (`pip install django-stubs`). Stub files are used to provide more accurate type information for packages like django that don't include type information of their own. If you install the stubs, the error message will go away.

Alternatively, if you don't want to see any static type errors, you can set `python.analysis.typeCheckingMode` to "off".

**Comment by anthony-S93** [comment]
> The `django` library has no type information, so pylance needs to infer type information from the available code. In this particular case, the `HttpResponse` is defined as follows:

That makes sense. Thank you so much for your quick response.

> There are type stub files available for django that you can install into your Python environment (`pip install django-stubs`). Stub files are used to provide more accurate type information for packages like django that don't include type information of their own. If you install the stubs, the error message will go away.

Noted. I didn't know that there were stub files for django. Thank you. This is very helpful.
