### ISSUE TITLE
Import "requests" could not be resolved from source

### ISSUE THREAD

**Issue by hitrust** [microsoft/pyright#4757]
**Describe the bug**
can't resolve modules installed in venv

**Screenshots or Code**
![2023-03-10_092724](https://user-images.githubusercontent.com/3360631/224199861-db825d3f-276f-4996-827e-9db917a7d42e.png)

**VS Code extension**
![2023-03-10_093125](https://user-images.githubusercontent.com/3360631/224200591-02a08287-f4ae-4628-bd03-a1db8922dda2.png)
![2023-03-10_093355](https://user-images.githubusercontent.com/3360631/224200594-e9a1b46a-c003-4683-a090-a21742995c24.png)
![2023-03-10_093409](https://user-images.githubusercontent.com/3360631/224200597-e794f68e-64db-4a57-a7d8-b38c6a9d8495.png)

**Comment by erictraut** [comment]
This means that you are importing the `requests` library but you don't have the this package installed in the selected virtual environment. Refer to the `Output` tab (select "Pyright") for logging that will help you diagnose the issue.

If you don't want to see this diagnostic, you can set `reportMissingSource` to false in your config file.

It looks like you're using Pyright with VS Code. We recommend using Pylance instead. It contains all of the functionality in Pyright plus many advanced language server features.

**Comment by hitrust** [comment]
thanks for your reply.

> This means that you are importing the requests library but you don't have the this package installed in the selected virtual environment. Refer to the Output tab (select "Pyright") for logging that will help you diagnose the issue.

As you see, from the screenshots above, the 'requests' package was installed, and the code using  'requests' package runs well in the virtual environment.

It's years from using vs code. This issue occurs since vs code was updated using the latest two versions. other  packages also could not be resolved, but the codes run well.

> It looks like you're using Pyright with VS Code. We recommend using Pylance instead. It contains all of the functionality in Pyright plus many advanced language server features.

From the screenshots above, 'Python', 'Pylance' are installed, not 'Pyright'

![2023-03-11_093221](https://user-images.githubusercontent.com/3360631/224457719-10b2d175-f633-47f5-a828-03b44b11c3ae.png)
