### ISSUE TITLE
pyright doesn't spot some kinds of changes to collections, giving spurious reportUnnecessaryComparison errors.

### ISSUE THREAD

**Issue by phaker** [microsoft/pyright#4758]
**Describe the bug**

Pyright doesn't notice that (these i tried) list/deque.pop() and deque.popleft() mutate the sequence, giving you an `reportUnnecessaryComparison` error if you modify a collection between two conditional tests accessing same index.

Checked few versions between 1.1.289 (latest) and 1.1.260 (july 2022) and none worked. Thought it might be a known limitation but didn't find any similar issues that weren't fixed.

**To Reproduce**

Example:

~~~python
# pyright: strict

from collections import deque

def f(d: deque[int]) -> str:
    if d[0] == 0:
        d.popleft()
        if d[0] == 1: # <-
            return 'impossible?'
    return 'ok'

print(f"{f(deque([0, 1, 2, 3]))=}") # sanity check, does print ...='impossible?'


def g(d: list[int]) -> str:
    if d[-1] == 0:
        d.pop()
        if d[-1] == 1: # <-
            return 'impossible?'
    return 'ok'

print(f"{g([3, 2, 1, 0])=}") # sanity check
~~~

To which pyright reports `Condition will always evaluate to False since the types "Literal[0]" and "Literal[1]" have no overlap` on both marked lines.

**Expected behavior**
No diagnostic. :)

**VS Code extension or command-line**

All defaults, other than setting `strict` to enable `reportUnnecessaryComparison` check.

Broken on pyright 1.1.298, checked few versions back to .260 so it's like that at least since July 2022.

**Comment by erictraut** [comment]
This behavior is "as designed", not a bug.

Type narrowing applies to index expressions with constant numeric indices. This can lead to false positives in certain cases, as you demonstrate in your code, but it is deemed a practical tradeoff given the benefits of type narrowing for index expressions. Mypy also narrows in this case and will exhibit similar false positives, as will type checkers in other languages like TypeScript.

Type checkers generally don't have knowledge of the internals of container classes or the methods that modfiy them. The type system doesn't have provisions for declaring such information.

For more information about type narrowing, see [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-narrowing).

You have a couple of options here:
1. Defeat the type narrowing by using a variable (like `x := 0`) or numeric expression (like `-0`).
2. Suppress the `reportUnnecessaryComparison` diagnostic on that line using a `# type: ignore` or `# pyright: ignore` comment.
3. Disable the `reportUnnecessaryComparison` diagnostic for the file by using `# pyright: reportUnnecessaryComparison=false`.

**Comment by phaker** [comment]
Thanks for the super quick response, suppressed it.

Reported here because i tried mypy (and pytype but i don't really use it so...) and couldn't get it to misbehave, though it will let far more through.
