### ISSUE TITLE
Class variable of root object not found?

### ISSUE THREAD

**Issue by karolyi** [microsoft/pyright#4765]
Hey,

I've just bumped into this. Consider the following code:
```python
class Root(object):
    _my_var = True


class Inherited1(Root):
    def test(self):
        print(self._my_var)
        self._my_var = False
        print(self._my_var)

x = Inherited1()
x.test()
```

When running this, it will print `True` and `False`, as in first it prints the root class' `_my_var`, then that of `Inherited1`. When using "goto definition" with pyright, it refuses to recognize the `_my_var` of `Root`.

Is this intentional? I would expect to find both definitions, in `Root` and then in `Inherited1.test()`.
I'm still using the latest pyright in Sublime Test with lsp-pyright.

**Comment by erictraut** [comment]
Yes, this is intentional. You haven't declared the type of `_my_var` in either the base class or the child class. The type is therefore inferred locally to each class implementation. If you add a type annotation in the base class (`_my_var: bool = True`), you will see a different behavior.

**Comment by karolyi** [comment]
Thanks, and apologies for the disturbance.
