### ISSUE TITLE
Enable pyright to infer checks from functions

### ISSUE THREAD

**Issue by ioangatop** [microsoft/pyright#4767]
It seems that `pyright` at the moment can not understand checks from functions.

It would be great to have this functionality, as it promotes the code to me more modular!

```py3
from typing import Optional

def check_none(num: Optional[int]) -> bool:
    return num is None

def add_one(num: Optional[int]) -> int:    # this works fine
    if num is None:
        return 0

    return num + 1

def add_one_check(num: Optional[int]) -> int:    # this results in error
    if check_none(num):
        return 0

    return num + 1
```

**Comment by soraros** [comment]
A solution is present in the newer versions of python: you might want check out [`TypeGuard`](https://peps.python.org/pep-0647/).
