### ISSUE TITLE
pyright doesn't propagate refinement info about generic parameters to "parent"

### ISSUE THREAD

**Issue by colehaus** [microsoft/pyright#4769]
**Is your feature request related to a problem? Please describe.**

```py
def foo(x: list[int] | list[str]):
    if len(x) == 0:
        raise RuntimeError("Empty list")
    elif isinstance(x[0], int):
        reveal_type(x[0]) # int
        reveal_type(x) # list[int] | list[str]
        return x
    else:
        reveal_type(x[0]) # str
        reveal_type(x) # list[int] | list[str]
        return x
```

The same behavior occurs with `match/case` constructs.

**Describe the solution you'd like**

I would have expected the information about `x[0]` to allow pyright to narrow `x` as well since the lists was declared as homogenously typed.

**Additional context**

This seems like it's sort of the opposite of https://github.com/microsoft/pyright/issues/4208 (subvalue refinement not being applied to broader context instead of refinement not being applied to subexpressions).

Mypy also seems to have the same behavior as pyright.

**Comment by erictraut** [comment]
This isn't a supported type guard pattern. Please refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards) for a complete list of supported type guards.

We do occasionally add new type guard patterns, but each one requires custom code and potentially affects performance of code analysis. This is a pattern that we're unlikely to support. We might change our mind in the future if we receive sufficient feedback from enough pyright users.

You can create your own user-defined type guards using the `TypeGuard` functionality introduced in [PEP 647](https://peps.python.org/pep-0647/).

**Comment by colehaus** [comment]
Okay, makes sense. Just for a little more context/motivation, my original use case was closer to:

```py
def foo(x: list[int] | list[str]):
    match x:
        case [int(), *_]:
             …
        case [str(), *_]:
            …
        case []:
            …
```
which seems like it may be a relatively common usage pattern with pattern matching.
