### ISSUE TITLE
Is it possible to turn of suggestions for private members of packages?

### ISSUE THREAD

**Issue by UtkarshVerma** [microsoft/pyright#4792]
**Is your feature request related to a problem? Please describe.**
When I type, `pyright` also suggests I use the private members of a class. Is there any option to opt out of this behaviour?

Here is a short demo of what I'm seeing:

https://user-images.githubusercontent.com/31820255/225851149-497d723e-6e11-43f0-b35d-921097865505.mp4

**Comment by erictraut** [comment]
No, there's currently no way to disable the display of private variables. They're already sorted such that they appear at the bottom of the suggestion list, after public members.

The pylance team maintains the completion provider logic in pyright, so if you want to suggest this change, you could file a feature request in the [pylance-release](https://github.com/microsoft/pylance-release) project. They will likely move the request to discussion to get feedback from the broader pyright/pylance community.
