### ISSUE TITLE
wrong overload of comparison used

### ISSUE THREAD

**Issue by amotzop** [microsoft/pyright#4795]
**Describe the bug**
When comparing a generic class with an `Unknown`  type parameter that comes from a restricted TypeVar to another object which fails the restrictions, the wrong overload of the comparison is used (the generic class' one instead of the other).

**Expected behavior**
In the following code the revealed type is `int` (coming from `GenericCls.__ge__`), but `b` can't be of type `S` so this is the wrong overload to use (`Cls.__le__` should be used instead, and the revealed type should be `str`).
Note that if a had a type like `GenericCls[int]` then the revealed type will indeed be `str`.

**Screenshots or Code**
```python
from typing import Any, Generic, TypeVar

S = TypeVar("S", int, str)

class GenericCls(Generic[S]):
    def __ge__(self, other: S) -> int:
        ...

class Cls:
    def __le__(self, other: Any) -> str:
        ...

a = GenericCls()
b = Cls()
reveal_type(a >= b)
```

**VS Code extension or command-line**
This happens in the both in the newest VS code and pyright versions (`1.1.299`)

**Comment by erictraut** [comment]
The current behavior is as designed. PEP 484 specifies that when a type argument is omitted, its type is `Any`. This is true even if the associated TypeVar has a bound or a constraint. If you want pyright to evaluate this as you desire, you'll need to provide a type argument for `GenericCls`.
