### ISSUE TITLE
`http.cookies` type issue

### ISSUE THREAD

**Issue by aspizu** [microsoft/pyright#4804]
```py
from http.cookies import BaseCookie
cookies = BaseCookie()
```

```
Type of "cookies" is partially unknown
  Type of "cookies" is "BaseCookie[Unknown]"
```

**Comment by erictraut** [comment]
What issue are you reporting? Are you asking why pyright is telling you that the type is partially unknown?

You are apparently using strict type checking. In strict mode, pyright will tell you when you assign a value to a variable that is unknown or partially unknown. In your code example, the `BaseCooke` class is a generic class that accepts a single type argument. The constructor doesn't accept any parameters that indicate the value of the type argument, so it must be explicitly specified by the caller.

```python
cookies = BaseCookie[bytes]()
```

**Comment by aspizu** [comment]
Thanks
