### ISSUE TITLE
Test new releases of `pyright` with `pandas-stubs`

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#4811]
**Is your feature request related to a problem? Please describe.**
A few times, you've upgraded pyright and it causes the CI for `pandas-stubs` to fail.  The `mypy` team has started running tests using `pandas-stubs` (and other stub projects) to verify that they haven't broken anything before issuing a new release.

**Describe the solution you'd like**
You develop test scripts that pull `pandas-stubs`, create the environment, and run a new release of `pyright` against the version in `main`.  If an error comes up, then determine if you have introduced a regression, or if you've improved `pyright` so that we have to fix our stubs.

**Comment by erictraut** [comment]
An appreciable fraction of the issues that you report against pyright turn out to be bugs in the pandas stubs, so I'm not inclined to use pandas stubs as a way to validate pyright.

I implement unit tests for most functionality (and bug fixes) in pyright to prevent regressions. Please continue to report issues that you think may be issues in the type checker.

**Comment by Dr-Irv** [comment]
> An appreciable fraction of the issues that you report against pyright turn out to be bugs in the pandas stubs or a misunderstanding of how the type system works, so I'm not inclined to use pandas stubs as a way to validate pyright.
> 
> I implement unit tests for most functionality (and bug fixes) in pyright to prevent regressions. Please continue to report issues that you think may be issues in the type checker.

I think you are missing my point.  Any current version at https://github.com/pandas-dev/pandas-stubs/tree/main has gone through a CI that uses `pyright` to validate the stubs (and our test files that test the stubs), and that returns zero errors.  The `pyproject.toml` file has the most recent version of `pyright` that we ran tests on.   If you have a new release of `pyright`, you can grab that version and run the same CI that we do.  If it doesn't pass, it's more likely that you've introduced a regression in `pyright` than us having a bug in `pandas-stubs`, because the version in our `main` branch has passed CI with `pyright`.

**Comment by Dr-Irv** [comment]
Thanks for reopening!

**Comment by erictraut** [comment]
Another library that would be good to add to this test is `bidict`. See [this discussion](https://github.com/microsoft/pyright/discussions/3530) for details.

**Comment by erictraut** [comment]
Thanks to help from @hauntsaninja, we now have his [mypy_primer tool](https://github.com/hauntsaninja/mypy_primer) hooked up in pyright's CI workflow. The mypy_primer tool (which was originally designed to work with mypy) now supports pyright as well. It checks out old and new versions of pyright and runs both versions on a number of open-source libraries including `pandas-stubs` and `bidict`. If differences are detected, they are reported in the form of a PR comment. We will expand the list of tested libraries over time.

**Comment by Dr-Irv** [comment]
@erictraut this is great news!

There have certainly been cases in the past where you fixed a pyright bug that uncovered a bug in `pandas-stubs`.  If your CI identifies such a case, how would you like us to proceed with addressing those types of bugs in `pandas-stubs` ?

**Comment by erictraut** [comment]
The idea behind the new pyright CI script is that it won't block a PR if it generates new (or different) output for `pandas-stubs` (or other libraries), but it provides visibility into the impact of such a change. Depending on the impact, the author (typically me) can then take appropriate actions. That might involve contacting the library maintainer or finding some better solution in pyright. So, to answer your question, I think it depends on the specific details. If it appears to be a real bug in `pandas-stubs`, I can file a bug in the `pandas-stubs` repo or at-mention you in the pyright PR to get your opinion.
