### ISSUE TITLE
None type for class attribute returns outside method after being handled with exception in method

### ISSUE THREAD

**Issue by ilrico** [microsoft/pyright#4814]
```
class Endpoint:
    id: str | None = None
    (...)

    @staticmethod
    def load(name: str) -> Endpoint:
        (...)
        endpoint = Endpoint(**kwargs) 
        if endpoint.uid is None:
            raise ValueError("whatever")
        print(endpoint.uid)    # here mouse over endpoint.uid shows pyright see it as str only
        return endpoint


endpoint = Endpoint.load(name="ept1")
print(endpoint.uid)    # here mouse over endpoint.uid indicates pyright see it as str | None
```

**Expected behavior**
endpoint.uid should not be seen as str | None but str after load() factory
same problem if load() is not staticmethod

pyright 1.1.299
python 3.11.1

**Comment by erictraut** [comment]
The current behavior is correct. Type narrowing is applied locally within an execution scope (a function or the global module scope). Narrowed types do not persist beyond a function call. Static type checkers do not perform global program analysis to propagate such information across calls. Doing this statically would be impossible in most cases and infeasible in others.

There are a couple of standard ways to handle this in typed code. The most common is to add a runtime `assert` statement after calling a function that has an internal side effect.

```python
endpoint = Endpoint.load(name="ept1")
assert endpoint.uid is not None
```

The other way is to make the class generic. For example, `Endpoint` could take a type parameter `T`, and the instance variable `uid` could be set to type `T`. When you construct an `Endpoint`, it would default to `Endpoint[None]`, and the `load` function could return an `Endpoint[str]` to indicate that the `uid` is now a `str`.
