### ISSUE TITLE
Classes methods break descriptors

### ISSUE THREAD

**Issue by klen** [microsoft/pyright#4837]
_Pyright version 1.1.300_

I'm trying to implement something like ORM and found the problem with pyright:

Preparations (pay attention on **GenericField**):
```python
from __future__ import annotations

from typing import Generic, TypeVar, Union, overload

from typing_extensions import Self

TV = TypeVar("TV")


class GenericField(Generic[TV]):
    @overload
    def __get__(self, instance: None, owner) -> Self:
        ...

    @overload
    def __get__(self: GenericField[TV], instance: Model, owner) -> TV:
        ...

    def __get__(self, instance: Model | None, owner) -> Union[Self, TV]:
        ...

    def __set__(self, instance: Model, value: TV) -> None:
        ...

    def is_null(self) -> bool:
        ...


class IntField(GenericField[int]):
    ...


class StrField(GenericField[str]):
    ...


class Model:
    pass
```

Example1 (works fine)
```python
class Example(Model):
    name = StrField()
    rate = IntField()

example = Example()
example.name  # str -- 👍
example.rate  # int -- 👍
example.rate = 12  # int -- 👍
example.rate = "foo"  # incompatible -- 👍

Example.name  # StrField -- 👍
Example.name.is_null()  # pass -- 👍
Example.rate  # IntField -- 👍
Example.rate = "foo"  # cannot assign -- 👍

```

But the typing is breaks down we change the attributes inside a class methods
```python
class Example(Model):
    name = StrField()
    rate = IntField()

    # Pay attention to the method
    def reset(self: Example) -> None:
        self.name = ""
        self.rate = "invalid"  # pass -- 😱
        
# And Example.name/rate are broken now
Example.name  # StrField | str -- 😱
Example.name.is_null()  # is_null is unknown -- 😱
Example.rate  # IntField | str -- 😱
Example.rate = "foo"  # cannot assign -- 👍
```

Is it a bug? Or Im doing something wrong?

BTW: with Mypy everything is working well

**Comment by erictraut** [comment]
I would expect it to work without repeating the type within `ClassVar`:

```python
class Example(Model):
    name: ClassVar = StrField()
    rate: ClassVar = IntField()
```

This currently generates an error. I've filed a separate bug on this topic: https://github.com/microsoft/pyright/issues/4838

**Comment by klen** [comment]
@erictraut Thank you for the explanation 🙏 You are absolutely correct about classvariables.

But basically it feels like an error. Because the class variable is a **descriptor** and `ExampleModel.name` can never become a string after `self.name = 'str'`.  

Maybe Pyright should consider descriptors as class variables because as we know: `Descriptors only work when used as class variables. When put in instances, they have no effect.` ?

For now it feels kinda uncomfortable to duplicate typing for every field (real example bellow):

```python
# Instead this (types working fine for classes and instances)
class Category(AIOModel):

    id = fields.AutoField()
    title = fields.CharField(unique=True)
    description = fields.CharField(null=True)
    is_active = fields.BooleanField(default=True)
    is_pinned = fields.BooleanField(default=False)
    order  = fields.IntegerField(null=True)
    owner = fields.AIOForeignKey(User, null=True)

# User's have to write this:
class Category(AIOModel):

    # note: fields.AnyName is a descriptor and generic types are inferred from definition
    id: ClassVar[fields.AutoField[int]] = fields.AutoField()
    title: ClassVar[fields.CharField[str]] = fields.CharField(unique=True)
    description: ClassVar[fields.Charfield[str | None]] = fields.Charfield(null=True)
    is_active: ClassVar[fields.BooleanField[bool]] = fields.BooleanField(default=True)
    is_pinned: ClassVar[fields.BooleanField[bool]] = fields.BooleanField(default=False)
    order: ClassVar[fields.IntegerField[int | None]] = fields.IntegerField(null=True)
    owner: ClassVar[fields.AIOForeignKey[Coroutine[None, None, User | None]] = fields.AIOForeignKey(User, null=True)
```

#4838 should help a lot, but maybe do it automatically for descriptors?

**Comment by klen** [comment]
@erictraut and there is one more problem, when I mark the variables as classvars, mypy (i'm using pyright on my desktop, but CI is tuned to use mypy) starts show errors like `Cannot assign to class variable "name" via instance ` and seems like it has a meaning. The python docs says:

`As introduced in [PEP 526](https://peps.python.org/pep-0526/), a variable annotation wrapped in ClassVar indicates that a given attribute is intended to be used as a class variable and should not be set on instances of that class.`

So `ClassVar`doesn't look as an solution. Maybe pyright should process descriptors separatelly? And don't update types when the descriptors are updated inside an instance methods?
