### ISSUE TITLE
site-packages used instead of python3.9/site-packages 

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#4839]
Given _pyrightconfig.json_:
```json
{ "venvPath": ".", "venv": ".venv" }
```

And packages installed into both
- _.venv/lib/python3.9/site-packages/_ and
- _.venv/lib/site-packages/_

pyright will only import packages from _/.venv/lib/site-packages/_, eg:
```
  Found the following 'site-packages' dirs
    /.venv/lib/site-packages
    /.venv/lib64/site-packages
  Looking in python search path '/.venv/lib/site-packages'
```

whereas the python interpreter only imports packages from _/.venv/lib/python3.9/site-packages_, eg: 
```
. .venv/bin/activate
python -c 'import sys;print(sys.path)'
['', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/.venv/lib/python3.9/site-packages']
```

### Repo from  https://github.com/microsoft/pyright/discussions/4791

Here's a full repo using docker that installs pygls. pygls installs `py.typed` into _.venv/lib/site-packages/pygls_ (see directory listing below). So pyright ignores _.venv/lib/python3.9/site-packages_ which causes a `reportMissingImports` error.

```
❯ docker run --rm -it --entrypoint /bin/bash python:3.9-slim -c 'set -x; python -m venv .venv; .venv/bin/pip install pygls pyright; ls -al .venv/lib/site-packages/pygls; echo "import lsprotocol.types" > foo.py; echo {\"venvPath\": \".\",\"venv\": \".venv\"} > pyrightconfig.json; .venv/bin/pyright --verbose foo.py;'
+ python -m venv .venv
+ .venv/bin/pip install pygls pyright
Collecting pygls
  Downloading pygls-1.0.1-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 KB 5.1 MB/s eta 0:00:00
Collecting pyright
  Downloading pyright-1.1.300-py3-none-any.whl (17 kB)
Collecting lsprotocol
  Downloading lsprotocol-2023.0.0a1-py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.5/69.5 KB 5.5 MB/s eta 0:00:00
Collecting typeguard<3,>=2.10.0
  Downloading typeguard-2.13.3-py3-none-any.whl (17 kB)
Collecting nodeenv>=1.6.0
  Downloading nodeenv-1.7.0-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: setuptools in /.venv/lib/python3.9/site-packages (from nodeenv>=1.6.0->pyright) (58.1.0)
Collecting attrs
  Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 KB 7.0 MB/s eta 0:00:00
Collecting cattrs
  Downloading cattrs-22.2.0-py3-none-any.whl (35 kB)
Collecting exceptiongroup
  Downloading exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Installing collected packages: typeguard, nodeenv, exceptiongroup, attrs, pyright, cattrs, lsprotocol, pygls
Successfully installed attrs-22.2.0 cattrs-22.2.0 exceptiongroup-1.1.1 lsprotocol-2023.0.0a1 nodeenv-1.7.0 pygls-1.0.1 pyright-1.1.300 typeguard-2.13.3
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the '/.venv/bin/python -m pip install --upgrade pip' command.
+ ls -al .venv/lib/site-packages/pygls
total 16
drwxr-xr-x 2 root root 4096 Mar 25 00:06 .
drwxr-xr-x 3 root root 4096 Mar 25 00:06 ..
-rwxr-xr-x 1 root root 3034 Mar 25 00:06 ThirdPartyNotices.txt
-rwxr-xr-x 1 root root   65 Mar 25 00:06 py.typed
+ echo 'import lsprotocol.types'
+ echo '{"venvPath":' '".","venv":' '".venv"}'
+ .venv/bin/pyright --verbose foo.py
 * Install prebuilt node (19.8.1) ..... done.

added 1 package, and audited 2 packages in 3s

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.6.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.2
npm notice Run npm install -g npm@9.6.2 to update!
npm notice 
Loading configuration file at /pyrightconfig.json
Assuming Python version 3.9
Assuming Python platform Linux
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /typings is not a valid directory.
Search paths for /
  /root/.cache/pyright-python/1.1.300/node_modules/pyright/dist/typeshed-fallback/stdlib
  /
  /typings
  /root/.cache/pyright-python/1.1.300/node_modules/pyright/dist/typeshed-fallback/stubs/...
  /.venv/lib/site-packages
Searching for source files
Found 1 source file
Could not import 'lsprotocol' in file '/foo.py'
  Looking in stubPath '/typings'
  Attempting to resolve stub package using root path '/typings'
  Attempting to resolve using root path '/typings'
  Looking in root directory of execution environment '/'
  Attempting to resolve stub package using root path '/'
  Attempting to resolve using root path '/'
  Finding python search paths
  Found path '/.venv/lib'; looking for site-packages
  Found path '/.venv/lib/site-packages'
  Found path '/.venv/lib64'; looking for site-packages
  Found path '/.venv/lib64/site-packages'
  Did not find '/.venv/Lib'
  Found the following 'site-packages' dirs
    /.venv/lib/site-packages
    /.venv/lib64/site-packages
  Looking in python search path '/.venv/lib/site-packages'
  Attempting to resolve stub package using root path '/.venv/lib/site-packages'
  Attempting to resolve using root path '/.venv/lib/site-packages'
  Looking for typeshed stdlib path
  Looking for typeshed stdlib path
  Attempting to resolve using root path '/root/.cache/pyright-python/1.1.300/node_modules/pyright/dist/typeshed-fallback/stdlib'
  Typeshed path not found
  Looking for typeshed third-party path
  Looking for typeshed stubs path
  Typeshed path not found
Could not import 'lsprotocol.types' in file '/foo.py'
  Looking in stubPath '/typings'
  Attempting to resolve stub package using root path '/typings'
  Attempting to resolve using root path '/typings'
  Looking in root directory of execution environment '/'
  Attempting to resolve stub package using root path '/'
  Attempting to resolve using root path '/'
  Finding python search paths
  Found path '/.venv/lib'; looking for site-packages
  Found path '/.venv/lib/site-packages'
  Found path '/.venv/lib64'; looking for site-packages
  Found path '/.venv/lib64/site-packages'
  Did not find '/.venv/Lib'
  Found the following 'site-packages' dirs
    /.venv/lib/site-packages
    /.venv/lib64/site-packages
  Looking in python search path '/.venv/lib/site-packages'
  Attempting to resolve stub package using root path '/.venv/lib/site-packages'
  Attempting to resolve using root path '/.venv/lib/site-packages'
  Looking for typeshed stdlib path
  Looking for typeshed stdlib path
  Attempting to resolve using root path '/root/.cache/pyright-python/1.1.300/node_modules/pyright/dist/typeshed-fallback/stdlib'
  Typeshed path not found
  Looking for typeshed third-party path
  Looking for typeshed stubs path
  Typeshed path not found
pyright 1.1.300
/foo.py
  /foo.py:1:8 - error: Import "lsprotocol.types" could not be resolved (reportMissingImports)
1 error, 0 warnings, 0 informations 
Completed in 0.742sec
```

**Comment by erictraut** [comment]
Yeah, pyright resolves the `site-packages` before looking for `python3.x/site-packages`. It sounds like the Python interpreter is resolving them in the opposite order. This is related to [this issue](https://github.com/microsoft/pyright/issues/4708).

One of the challenges here is that pyright often doesn't know which version of Python will be used at runtime. By default, it assumes the latest stable version (currently 3.11). So, unless you tell pyright which version you're using, it cannot know which `python3.X/site-packages` will be used at runtime.

Most pyright users don't use the `venv` and `venvPath` mechanism for configuration. Instead, pyright uses the current python interpreter as configured in the shell (if running from the CLI) or in the IDE (if running the language server). Using this technique, pyright can ask the current python interpreter for its `sys.paths` import resolution paths, so it doesn't need to concern itself with the vagaries of replicating the algorithm that the Python runtime uses to build `sys.paths`. Would it work for you to switch to this configuration mechanism?

**Comment by tekumara** [comment]
Thank you for the explanation. The reason I hit this actually was because I was trying out the Zed IDE which [uses pyright](https://docs.zed.dev/languages/python#virtual-environments) directly. It doesn't start an LSP, python interpreter or otherwise have a concept of virtualenv. Via pyrightconfig.json is the only way I can see to configure how Zed runs pyright. 


> One of the challenges here is that pyright often doesn't know which version of Python will be used at runtime. By default, it assumes the latest stable version (currently 3.11). So, unless you tell pyright which version you're using, it cannot know which python3.X/site-packages will be used at runtime.

I tried setting `pythonVersion` but still hit the same issue, eg:

```json
 {
     "venvPath": ".",
     "venv": ".venv",
     "pythonVersion": "3.9"
 }
 ```

**Comment by erictraut** [comment]
Could you activate this venv and dump its `sys.path`? I'm interested in seeing whether `lib/site-packages` and `lib/python3.9/site-packages` are both present — and if so, which order they appear in.

Do you know why there is both a `lib/site-packages` and a `lib/python3.9/site-packages` in your virtual environment? Are some packages installed in one and other packages installed in the other?

**Comment by tekumara** [comment]
Just `lib/python3.9/site-packages`:
```
. .venv/bin/activate
python -c 'import sys;print(sys.path)'
['', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/.venv/lib/python3.9/site-packages']
```

`pygls` is installing itself into both `lib/site-packages` and a `lib/python3.9/site-packages`, eg:
```
❯ tree .venv/lib/site-packages
.venv/lib/site-packages
└── pygls
    ├── ThirdPartyNotices.txt
    └── py.typed
    
❯ tree .venv/lib/python3.9/site-packages/pygls
.venv/lib/python3.9/site-packages/pygls
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-39.pyc
│   ├── capabilities.cpython-39.pyc
│   ├── constants.cpython-39.pyc
│   ├── exceptions.cpython-39.pyc
│   ├── feature_manager.cpython-39.pyc
│   ├── progress.cpython-39.pyc
│   ├── protocol.cpython-39.pyc
│   ├── server.cpython-39.pyc
│   ├── uris.cpython-39.pyc
│   └── workspace.cpython-39.pyc
├── capabilities.py
├── constants.py
├── exceptions.py
├── feature_manager.py
├── lsp
│   ├── __init__.py
│   └── __pycache__
│       └── __init__.cpython-39.pyc
├── progress.py
├── protocol.py
├── py.typed
├── server.py
├── uris.py
└── workspace.py
```

**Comment by erictraut** [comment]
It sounds like you could simply delete the `lib/site-packages` directory from your venv, and both the virtual environment and pyright would then work as intended.

I wonder if this is a bug in the `pygls` installer. I've never seen a package install itself twice in two locations.

My inclination is to close this bug as "won't fix" for now but revisit it in the future if this proves to be a real issue that other users encounter. So far, you're the only one who has encountered it, and it's not clear to me that it's a real issue. Plus, it appears that there's a pretty straightforward workaround.

**Comment by crides** [comment]
I'm pretty sure my issue is related. for a `pyrightconfig.json` with:

```json
{ "pythonVersion": "3.8"
}
```

`pyright` doesn't actually include Python 3.8's `site-packages` from pip (in my case, `$HOME/.local/lib/python3.8/site-packages/`), unless I explicitly include that in `extraPaths`. Having `pythonVersion` only enabling a different set of language features is pretty weird

**Comment by tekumara** [comment]
FYI version [1.1.309](https://github.com/microsoft/pyright/releases/tag/1.1.309) added:
> Enhancement: Added command-line option `pythonpath` that allows the path to the python interpreter to be specified.
