### ISSUE TITLE
Certain `django` subpackages seem to be omitted by `pyright --createstub` 

### ISSUE THREAD

**Issue by anthony-S93** [microsoft/pyright#4846]
Set-up: 
1) Create a `test` directory and `cd` into it.
```
$ mkdir test
$ cd test
```
2) Initiatize a virtual environment and activate it. 
```
$ python -m venv .venv/
$ cd .venv/bin/
$ ./activate
``` 
3) Install the latest version of `Django` after virtual environment has been activated
```
$ pip install django
```
4) Use the following minimal `pyrightconfig.json`:
```json
{
    "venvPath": "./",
    "venv": ".venv",
    "stubPath": "./.stubs/"
}
```
5) Create the directory for stub files
```
$ mkdir .stubs/
```
6) Generate stubs for `Django`:
```
$ pyright --createstub django
```
The command ran and the stubs were generated inside the `.stubs/` directory as expected. So far so good. However, when I compared the directory structures between  `.stubs/django` (left terminal in screenshot below) and the actual `django` directory inside `site-packages` (right terminal in screenshot below), I noticed that a lot of sub-packages are omitted in the generation of stub files. 

![2023-03-27-200715_1914x1044_scrot](https://user-images.githubusercontent.com/69449791/227937266-941694fe-3ad2-4186-97b6-2c960cc7c4ed.png)

The stub files for the `django.contrib.admin` sub-package, for instance, seemed to be omitted by pyright. I mean, I _could_ manually generate the stub files for that particular sub-package by running `pyright --createstub django.contrib.admin`, but it's a bit of a pain to do so considering that there are so many missing sub-packages. 

Is this by design? Or am I doing something wrong here?

**Comment by erictraut** [comment]
Pyright generates stubs for the specified module and any dependent submodules. Some submodules (like the `django.admin` submodule) are independent from the `django` module, so you'd need to generate those separately if you want them.

There are other stub generation tools available if you would prefer a different behavior.

**Comment by erictraut** [comment]
I'll also mention that there are existing django stubs (`pip install django-stubs`) that are community-maintained, so you shouldn't need to generate and clean up your own copy.
