### ISSUE TITLE
`isinstance` checks are not constraining the type

### ISSUE THREAD

**Issue by ktbarrett** [microsoft/pyright#4851]
**Describe the bug**
`isinstance` checks are not further constraining the type of the object they apply to inside function bodies.

**To Reproduce**
Paste below code into VS Code and check squiglies on the call to `len` on line 5 and 20. Also hover mouse over object in each code section where the error is and see the type of the object has not changed in the section.

**Expected behavior**.
There should be no error on line 6 or 21 in the below example. On line 5, pyright should know the type of `a` is both an `Iterable[object]` and `Sized`, but it reports it is `Iterable[object]` and line 6 errors. On line 20 it should know that the type of `a` is `B`, but it reports it is `A` and line 21 errors. A final improvement would be that it could know and warn that the branch on line 7 is dead code (perhaps this is out of scope).

**Screenshots or Code**
```python
from typing import Iterable, Sized

def length1(a: Iterable[object]) -> int:
    if isinstance(a, Sized):
        reveal_type(a)
        return len(a)
    elif isinstance(a, int):
        return 0
    else:
        return len(list(a))

class A: ...

class B(A):
    def __len__(self) -> int:
        return 0

def length2(a: A) -> int:
    if isinstance(a, B):
        reveal_type(a)
        return len(a)
    else:
        return 0
```

**VS Code extension or command-line**
Using VS Code w/ pylance v2023.3.30.

**Additional Context**
mypy 1.1.1 successfully checks this code and the output is:
```
main.py:5: note: Revealed type is "__main__.<subclass of "Iterable" and "Sized">"
main.py:20: note: Revealed type is "__main__.B"
Success: no issues found in 1 source file
```

I also tried adding `assert`s in the code sections, to no avail.

**Comment by erictraut** [comment]
I'm not able to repro the problem you're describing. Pylance v2023.3.30 (and pyright) emit no errors for this code, and the revealed types are the same as mypy's output. Could you try to repro with default pylance settings and a fresh virtual environment?

**Comment by erictraut** [comment]
Ah, yes. Pyright doesn't perform code flow analysis or narrow types within stub files, which are not supposed to contain arbitrary code. Doing this type of analysis is expensive, so we do it only where it's needed.
