### ISSUE TITLE
stubPath default value broken for v1.1.301

### ISSUE THREAD

**Issue by FrancescElies** [microsoft/pyright#4862]
**Describe the bug**
The default value for stubPath seems to be `./typings`, this was working fine in `v1.1.300` but once upgraded to [v.1.1.301](https://github.com/microsoft/pyright/compare/1.1.300...1.1.301) (which touched `stubPath`) pyright started complaining about missing stubs.

**To Reproduce**
pyright v.1.1.301 and pyproject.toml without `stubPath`

**Additional context**
The current workaround is to explicitly add `stubPath = "./typings"` in `[tool.pyright]` section of the `pyproject.toml`

**Comment by erictraut** [comment]
Thanks for the bug report, and apologies for the regression. This affected only the CLI, not the code paths used for the language server, so our unit tests didn't catch it. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.302, which I just published.
