### ISSUE TITLE
Pyright stopped using library stubs without py.typed for inference by default

### ISSUE THREAD

**Issue by Ovsyanka83** [microsoft/pyright#4885]
**Describe the bug**
Our internal library's pydantic schemas suddenly started working incorrectly. When you have a "LibraryType | None" in the function argument, then you assign "LibraryType" to it, it still throws an error about None. reveal_type shows that the type is "Unknown | None".

This seems to be the case because "--lib" argument is now not "on" by default.

**To Reproduce**
```
from my_lib.schemas import Hello


def foo(bar: Hello | None):
    bar = Hello()
    bar.d # Attribute error on pyright because None does not have attribute "d"
```
**Expected behavior**
I would expect pyright to work in the same manner as in the previous version where it indexed all libraries automatically and used their code for inference.

**VS Code extension or command-line**
Command-line
Version: 1.1.301

**Additional Context**
There's a line in changelog similar to this. If this was expected out of the release, then I apologize for confusing myself. However, this update has still broken the majority of our CI.

**Comment by erictraut** [comment]
Is `Hello` is an `Unknown` type? I can't tell from your example.

The `--lib` setting (i.e. `useLibraryCodeForTypes` configuration setting) has never been on by default in pyright. Perhaps you changed your configuration?

What version of pyright were you using previously? I confirmed that this behavior didn't change between 1.1.300 and 1.1.301, but I didn't go back further.

**Comment by Ovsyanka83** [comment]
Yes, hello is of `Unknown` type.

I didn't change my configuration at all. In fact, the aforementioned code works fine in pylance in version v2023.3.40 and worked in pyright in my CI just fine until today when it automatically updated (same happened on my local machine).

I.e. This error only exists in CLI, it has started happening today after pyright forcefully updated on both the CI and the local machine, and it is fixed either with `--lib` or by adding `py.typed` to the package.

**Comment by erictraut** [comment]
The `useLibraryCodeForTypes` setting is on by default in pylance but off by default in pyright. That has been true for all versions of pylance and pyright.

If you want `useLibraryCodeForTypes` to be on for pyright, you can either use `--lib` on the command line or specify `"useLibraryCodeForTypes" = true` in your `pyproject.toml` or `pyrightconfig.json` config file.

In the off chance that pyright 1.1.301 introduced some unexpected change, I've gone back several versions. I don't see any change in behavior for the code sample posted above. I'm struggling to come up with any theories that could explain why your CI worked previously but does not work with pyright 1.1.301. Is it possible that you had manually added a "py.typed" to one of the dependent libraries but recently upgraded that library, which caused the "py.typed" marker file to be deleted?

In any case, it sounds like your CI is working again now that you've enabled `--lib`.

**Comment by Ovsyanka83** [comment]
No, there is no chance I have added or deleted py.typed. The library is rather new and I was the only maintainer so it never had py.typed but today suddently a ton of errors started popping up for old code.

Well, as long as we're in sync that it's the expected behavior -- I am fine. py.typed is required anyways so I can safely close this issue :)

**Comment by Ovsyanka83** [comment]
Forgot to say: Thanks for your time and your work on pyright!

**Comment by erictraut** [comment]
I just noticed that in the title you mentioned "library stubs". You don't mention "stubs" anywhere else in the issue description. Does your library include stub (".pyi") files? Pyright should use stubs even if the library is not marked "py.typed". Is your library available in an open-source repo? If you still think that something in pyright changed between 1.1.300 and 1.1.301 and you would like to get to the bottom of it, I'll need more information about your setup — either access to your repo or more detailed repro instructions.

**Comment by Ovsyanka83** [comment]
I have written my title incorrectly:

- The library is not open source, sadly
- Mentioning stubs was a brainfart on my part, sorry
- The library is a simple typed package without py.typed that is installed from internal repos
