### ISSUE TITLE
`TypedDict` error when accessing `NotRequired` property in indexed `dict`

### ISSUE THREAD

**Issue by xavdid** [microsoft/pyright#4887]
**Describe the bug**

When accessing a `NotRequired` key in a `TypedDict` that's fetched via a variable index lookup, there's a type error:

```
Could not access item in TypedDict
  "x" is not a required key in "MyDict", so access may result in runtime exception
```

**To Reproduce**

Access a `NotRequired` key of a `TypedDict` that is retrieved via a list index (or dict lookup, same effect).

**Expected behavior**

After verifying that `l[n]` has a given key, I'd expect `l[n]['some_key']` to not report type errors.

**Screenshots or Code**

```python
from typing import NotRequired, TypedDict


class MyDict(TypedDict):
    x: NotRequired[str]


def some_func(l: list[MyDict]):
    n = 0
    if "x" in l[n]:
        # Could not access item in TypedDict
        #   "x" is not a required key in "MyDict", so access may result in runtime exception
        print(l[n]["x"])
```

**VS Code extension or command-line**

Running via Pylance `v2023.3.40` in VSCode Version `1.76.2`

**Additional context**

This works as expected:

```py
def some_func(l: list[MyDict]):
    if "x" in l[0]:
        print(l[0]["x"])
```

The issue seems to be around the use of a variable for index access.

**Comment by erictraut** [comment]
This is by design. Pyright doesn't perform any narrowing on index expressions that use a variable for a subscript. In general, it's unsafe to do so. Mypy and other type checkers do the same.

If you want this to type check without errors, you'll need to assign the expression `l[n]` to a local variable, as follows:

```python
def some_func(l: list[MyDict]):
    n = 0
    m = l[n]
    if "x" in m:
        print(m["x"])
```

Or you can use a walrus operator if you prefer:

```python
def some_func(l: list[MyDict]):
    n = 0
    if "x" in (m := l[n]):
        print(m["x"])
```
