### ISSUE TITLE
Any hope for Sublime Text support?

### ISSUE THREAD

**Issue by pirate** [Microsoft/pyright#49]
I'd love to see pyright support in other editors.  How difficult would it be to port over?

Is it feasible / worth trying to do? Is Microsoft interested in helping that process or should we start a separate repo to build bindings for other editors.

Feel free to close this issue if it's not going to happen.

**Comment by erictraut** [comment]
This is outside the scope of what we're trying to tackle with pyright. You're welcome to start other projects that consume pyright's LS (language server) for use with other environments.
