### ISSUE TITLE
Overloaded functions cannot be passed to map

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#4917]
**Describe the bug**
Overloaded functions cannot be passed to map.

**Expected behavior**
The same behaviour if I was to use a generator comprehension. This code should and does work at runtime.

**Screenshots or Code**
```py
import os

def _(*args: str | os.PathLike[str]):
    map(os.fspath, args)
```
<img width="816" alt="image" src="https://user-images.githubusercontent.com/50501825/230512462-6a0ba90c-3618-46dd-ad20-d613d13716c0.png">

**VS Code extension or command-line**
pylance: v2023.4.11

**Additional Context**
```py
import os
def bad_fspath(x: str | os.PathLike[str]) -> str: ...

def _(*args: str | os.PathLike[str]):
    map(bad_fspath, args)  # fine
    (os.fspath(arg) for arg in args)  # also fine
```

**Comment by erictraut** [comment]
I think pyright is doing the right thing here. There is no overload that accepts the type `str | PathLike[str]`. Union expansion doesn't apply in this case. 

Mypy generates the same error here.

**Comment by Gobot1234** [comment]
But why does the generator expression version of this work then?

**Comment by erictraut** [comment]
Because union expansion is applied evaluating a call expression and the target callable is overloaded.

**Comment by Gobot1234** [comment]
Well if that's it is I guess I'll stick to the generator expression, mypy generated an error in both cases so I assumed mypy was just having problems. Thank you.

**Comment by erictraut** [comment]
For me, mypy handles the generator expression without any type errors, just like pyright. Perhaps you're using an older version of mypy.
