### ISSUE TITLE
Support multiple unused variables

### ISSUE THREAD

**Issue by EvgeniGenchev** [microsoft/pyright#4926]
**Is your feature request related to a problem? Please describe.**

When working with functions or classes that require callback functions, I  rarely use all the possible arguments that a callback function may provide, which makes for really annoying pyright exceptions about unused varibables. A solution that I use in cases where the I do not need only one argument is putting `_` as the name of the unused variable, which is not possible to be done for multiple variables.

![image](https://user-images.githubusercontent.com/59848681/230764706-838be75a-51ad-43ca-9962-1917c1b5bb5c.png)

 
**Describe the solution you'd like**
I suggest similarly to `pylint` to either support multiple underscore notations or underscore + number notations like so:

```python

def function(_, __, ___, _1):
    pass

function(1,2,3,4)

```

**Tested on**
`nvim 0.9`

**Comment by erictraut** [comment]
Pyright never generates diagnostics for unused function parameters. It only generates hints with a tag that tells an editor to display the text in a greyed-out manner. Neovim has chosen to request this hint but then display it as a normal diagnostic. I've tried to get the neovim maintainers to change the behavior, but they are not convinced. See [this issue](https://github.com/microsoft/pyright/issues/1118) for details. 

I recommend that you configure neovim not to display any "hints". Hints with the "Unnecessary code" tag are not intended to be displayed as diagnostics, and other editors (like VS Code) do not display them as such.

In any case, pyright is working as designed here.
