### ISSUE TITLE
uwsgi missing import should not be reported

### ISSUE THREAD

**Issue by delahondes** [microsoft/pyright#4927]
import uwsgi only works in python code executed through uwsgi binary (see https://uwsgi-docs.readthedocs.io/en/latest/PythonModule.html#the-uwsgi-python-module), which is indeed extremely strange, I agree.

For this reason it will never work in VSC context. It is therefore a bug to report 'import uwsgi' as not working.

**Comment by erictraut** [comment]
Pyright is working as designed here. If it cannot find the import on any of the static import paths and is configured to report missing imports, it will generate a diagnostic in this case. 

Your choices are:
1. Ignore the diagnostic.
2. Disable the `reportMissingImports` diagnostic for your entire project.
3. Suppress the `reportMissingImports` diagnostic for a single file (e.g. by using a `# pyright: reportMissingImport=false` comment at the top.
4. Suppress the diagnostic for a single line (e.g. by using a `# type: ignore` or `# pyright: ignore[reportMissingImports]` comment at the end of the line).

**Comment by delahondes** [comment]
The 4th advice really fit my use case and works like a charm, sorry for the noise and thanks!
