### ISSUE TITLE
Recognise truthy and falsy values as such

### ISSUE THREAD

**Issue by DaviDevMod** [microsoft/pyright#4931]
**Is your feature request related to a problem? Please describe.**
Currently, for the type checker only `True` and [a few more values](https://github.com/microsoft/pyright/issues/445#issuecomment-568177746) are considered truthy.

```python
# Return type inferred as `Literal[True]`.
def f():
    if True:
        return True

    # Code is unreachable.
    return False


# Return type inferred as `bool`.
def g():
    if 1:
        return True

    return False


# Even though `f` directly returns `Literal[True]`,
# the return type here is still inferred as `bool`.
def h():
    if f():
        return True

    return False
```

 When `True` is used in a `while` condition, the type checker knows that that `True` does not provide an exit condition, which is very useful.

```python
# Return type inferred as `Literal[True]`.
def f():
    while True:
        if True:
            return True

    # Code is unreachable.
    return False


# Return type inferred as `Literal[True] | None`
def g():
    while f():
        if True:
            return True
```

Annotating the return type like so `def g() -> bool:` would make the type checker scream:

> Function with declared type of "bool" must return value on all code paths
  Type "None" cannot be assigned to type "bool"

**Describe the solution you'd like**
It would be great for the type checker to recognise [truthy and falsy values](https://docs.python.org/3/library/stdtypes.html#truth-value-testing) other than `True` and `False`, even when they are used as a funciton returned value rather than directly.

**Additional context**
To directly address the [discussion](https://github.com/microsoft/pyright/issues/445#issuecomment-568177746) mentioned at the beginning, one common enough use case may be a function returning some information to be validated in a loop. Here is a simple example:

```python
from math import nan


def get_two_integers() -> tuple[int, int]:
    return 0, 1


def divide_two_integers(n: int, m: int):
    if m == 0:
        return nan

    return n / m


# Return type inferred as `float | None`,
# even though the `operands` tuple is a truthy value
# and the only way to leave the loop is to return a `float`.
def dividetor():
    while operands := get_two_integers():
        if operands[1]:
            return divide_two_integers(*operands)
        print("Cannot divide by 0.")
```

If anything, this issue will serve as a reference for people looking for the same feature.

**Comment by DaviDevMod** [comment]
I would personally rewrite the function with something like a C-style [do...while](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/do...while) cause writing `while True:` gives me anxiety 

```python
def dividetor():
    operands = get_two_integers()

    while operands[1] == 0:
        print("Cannot divide by 0.")
        operands = get_two_integers()

    return divide_two_integers(*operands)
```

But yes, one can easily rearrange the code whenever facing the issue (or be explicit about the return type and `# type: ignore` the error from the type checker). It's just a nice to have feature.
Thank you for outlining the reason why the feature is not being implemented.

**Comment by DaviDevMod** [comment]
Just for the records: I bumped into another use case, that is using regex matches in conditions.

Here is what I was trying to do:

```python
PASSWORD_MIN_LEN = 6
PASSWORD_MAX_LEN = 32
# Match a sequence of at least one lowercase character from the basic Latin alphabet.
LOWER_REGEX = re.compile(r"[a-z]+")
# Match a sequence of at least one uppercase character from the basic Latin alphabet.
UPPER_REGEX = re.compile(r"[A-Z]+")
# Match a sequence of at least one digit.
DIGIT_REGEX = re.compile(r"\d+")
# Match a sequence of at least one character that is either an underscore or
# not a word character, nor a digit, nor a space.
EXOTIC_REGEX = re.compile(r"_|[^\w\d\s]+")


def is_valid_password(password: str):
    return (
        PASSWORD_MIN_LEN <= len(password) <= PASSWORD_MAX_LEN
        and LOWER_REGEX.search(password)
        and UPPER_REGEX.search(password)
        and DIGIT_REGEX.search(password)
        and EXOTIC_REGEX.search(password)
    )
```

The return type of `is_valid_pass` is inferred as `Match[str] | Literal[False] | None`.
The workaround is to use `# type: ignore` (casting each regex to `bool` would probably be silly):

```python
def is_valid_password(password: str) -> bool:
    return (
        PASSWORD_MIN_LEN <= len(password) <= PASSWORD_MAX_LEN
        and LOWER_REGEX.search(password)
        and UPPER_REGEX.search(password)
        and DIGIT_REGEX.search(password)
        and EXOTIC_REGEX.search(password)
    )  # type: ignore
```

<sub>Props to [this answer](https://stackoverflow.com/a/36281098/18928520) for  the tiny regexps approach.</sub>

**Comment by erictraut** [comment]
I wouldn't recommend adding a cast or ignoring the issue. Pyright is identifying a legitimate bug in your code here. As written, `is_valid_password` can return `None`, so if it is called by a function that assumes it returns a `bool` (as its annotation suggests), then your code will fail.

```python
print(is_valid_password("        "))  # None
```

**Comment by DaviDevMod** [comment]
@erictraut you are totally right about the hidden bug.
Even though, as the name suggests `is_valid_password` is meant to be used as a guard in control flow, where there is no distinction between the various truthy and falsy values. But still, saying that the function returns a `bool` when it doesn't is not good. Thanks for the catch.

And I don't even know how I missed the possibility to cast the whole condition :sweat_smile:
