### ISSUE TITLE
python.analysis.executionEnvironments setting

### ISSUE THREAD

**Issue by award999** [microsoft/pyright#4945]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Similar to the python.analysis.extraPaths setting, it would be nice if there were a vscode setting for execution environments.

**Additional context**
Yes this is possible in the pyrightconfig.json file, but it would be nice if all our project configurations could live in the .vscode/settings.json file.

**Comment by erictraut** [comment]
Execution environments are used by very few pyright users. It's unlikely that we'd make these available in language server settings. We typically reserve these more advanced and esoteric settings for config files.

We could revisit this in the future if we get signal from users that this is important.
