### ISSUE TITLE
polars warning

### ISSUE THREAD

**Issue by shaooping** [microsoft/pyright#4968]
![2023-04-18_191201](https://user-images.githubusercontent.com/37577427/232760843-82ee0f48-bdf0-42f7-a072-aa7d026c593c.png)

Just like the picture, despite the red line warning, it outputs the results correctly. I don't know the reason.

I need help, thank you!

**Comment by shaooping** [comment]
OS: windows11
Vscode: 1.77.3
Python version: from anaconda python 3.10.10
Polars version: 0.17.5

**Comment by erictraut** [comment]
Polars is a typed library (i.e. it contains a "py.typed" marker file, indicating that it provides inlined type information that static type checkers should honor). The `read_excel` function is declared as an overloaded function with three possible overloads. All of these overloads require keyword arguments for the `sheet_id` and `sheet_name` parameters. You haven't provided these keyword arguments, so pyright correctly reports an error.

If you think that the type information for `read_excel` is incorrect, please report the bug to the maintainers of the `polar` library.

For future pyright bug reports, please include a minimal, self-contained code sample in text form. Debugging issues from screen shots is not preferable.
