### ISSUE TITLE
Unclear docs about CLI and configuration

### ISSUE THREAD

**Issue by karolzlot** [microsoft/pyright#4993]
Questions about content on:
https://github.com/microsoft/pyright/blob/main/docs/command-line.md
and
https://github.com/microsoft/pyright/blob/main/docs/configuration.md

1. ```
    (1) If specific files are specified on the command line, the pyrightconfig.json file is ignored.
    ```
    But what happens if pyproject.toml is present and files are specified on CLI?
    I'm getting:
    ```
    pyproject.toml file found at /home/runner/work/ __(path edited out)__
    Loading pyproject.toml file at /home/runner/work/ __(path edited out)__
    ```
    But it seems it's not true because it is also ignored. (so this is a bug)


2. Also, what happens if I also specify `-p` on command line? 
Does it take priority over other CLI arguments?

3. Does `-p` support both `pyproject.toml` and `pyrightconfig.json`?

4. Is list of files on command line eqivalent to `include`? 
5. If yes, is it possible to also specify `exclude` and `ignore` in CLI?

**Comment by erictraut** [comment]
1. If specific files are specified on the command line, it overrides the files or directories specified in the `pyrightconfig.json` or `pyproject.toml` file. The config file (if present) still provides all of the other configuration settings in this case.

2. The `-p` allows you to specify an alternate `json` config file. It works in conjunction with the other CLI arguments.

3. The `-p` supports only `json` files, not `toml` files. The `json` file is the "native" configuration file format for pyright, whereas `toml` files were added as somewhat of an afterthought based on user feedback. It would be possible to add support for alternate `toml` files, but we haven't ever received such a request from users.

4. Yes, the list of files on the command line overrides what's found in the `include` section of the config file.

5. No, it's not possible to specify `exclude` from the command line. If you need that level of configuration, you should define a configuration file.

I've updated the documentation to clarify point number 1.
