### ISSUE TITLE
Wildcard character in config json

### ISSUE THREAD

**Issue by Harold2017** [microsoft/pyright#50]
Many thanks for this powerful tool! It runs really fast!
But as titled, it would be helpful if wildcard characters can be used in json configure. 
Thanks!

**Comment by erictraut** [comment]
Thanks for the suggestion. Can you provide more details about your use case? Are you talking about paths in the configuration? For those settings that act as "filters" (e.g. include, exclude, and ignore), I can see how a wildcard would be useful. For settings that point to specific directories (venvPath, typeshedPath, typingsPath, root) or for non-path settings, a wildcard wouldn't make as much sense.

**Comment by Harold2017** [comment]
@erictraut , Hi! I thought it's useful to include this feature in "filters" settings and so did my use case.
Many thanks!

**Comment by erictraut** [comment]
Sorry this one took so long. I finally got to it. This functionality will be in the next published version.

I've added support for three wildcards that are used in other config files (like TypeScript):
** matches a directory or directory hierarchy
* matches a sequence of zero or more characters
? matches a single character

**Comment by erictraut** [comment]
This is implemented in 1.0.51, which I just published.
