### ISSUE TITLE
pyright fails when opening a file mounted via sshfs

### ISSUE THREAD

**Issue by sourproton** [microsoft/pyright#5012]
**Describe the bug**
Using helix-editor, pyright works fine on local files, but fails when trying to work with files in a directory mounted via sshfs. Helix log shows
```
2023-04-26T10:27:29.881 helix_lsp::transport [ERROR] err <- "cannot open path of the current working directory: Permission denied\n"
2023-04-26T10:27:29.881 helix_lsp::transport [ERROR] err: <- StreamClosed
```

**To Reproduce**
1 - mount a directory with sshfs
2 - open a file in the sshfs directory
3 - pyright will immediately fail

**Expected behavior**
Expected pyright to behave like on normal local files.

**Comment by sourproton** [comment]
I found that if I'm on home and open the file with `helix sshfsfolder/file` it works, but if I `cd` to `sshfsfolder` and do `helix file`, it doesn't work.

I'm not having this problem with other language servers.

**Comment by erictraut** [comment]
I don't know the first thing about helix, its lsp support, or sshfs. You'll need to work with the maintainer of the helix lsp provider or debug the problem yourself. If you have any additional details or clues, I'm happy to help you out, but I'm going to close this issue for now.
