### ISSUE TITLE
List[T] should be compatible with List[Optional[T]]

### ISSUE THREAD

**Issue by st-pasha** [microsoft/pyright#5017]
**Describe the bug**
Inside a list, a value of type `T` is not considered assignable to type `Optional[T]`.

**To Reproduce**
```python
x: List[str] = ['a', 'b', 'c']
y: List[Optional[str]] = x
```
produces the following error:
```
Expression of type "list[str]" cannot be assigned to declared type "List[str | None]"
  "list[str]" is incompatible with "List[str | None]"
    TypeVar "_T@list" is invariant
      Type "str" cannot be assigned to type "str | None"
        Type cannot be assigned to type "None" Pylance[reportGeneralTypeIssues]
```

**Expected behavior**
No error.

**VS Code extension or command-line**
VS Code Extension `Pylance v2023.4.30`

**Additional context**
Python 3.8.16

**Comment by erictraut** [comment]
`List[str]` is not compatible with `List[str | None]`. You may find [this documentation](https://microsoft.github.io/pyright/#/type-concepts?id=generic-types) helpful.

**Comment by st-pasha** [comment]
Thank you, that was very helpful!
