### ISSUE TITLE
The default value of 'useLibraryCodeForTypes' is still false.

### ISSUE THREAD

**Issue by okura25** [microsoft/pyright#5029]
**Describe the bug**
https://github.com/microsoft/pyright/blob/332bfa8323ed573631bd2813b72443567b38d1d5/packages/pyright-internal/src/analyzer/service.ts#L822-L823
It seems that the code specified in this section sets `configOptions.useLibraryCodeForTypes` to false when it is undefined, so it is likely that cannot reach the setting on [L830](https://github.com/microsoft/pyright/blob/332bfa8323ed573631bd2813b72443567b38d1d5/packages/pyright-internal/src/analyzer/service.ts#L830).
In fact, when the setting was not specified in the configuration file, the behavior was the same as when `useLibraryCodeForTypes = false`.

**To Reproduce**
pyright 1.1.305

**Comment by erictraut** [comment]
Good catch. Thanks for the bug report.

**Comment by erictraut** [comment]
This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.306, which I just published.
