### ISSUE TITLE
Regression: Invalid references with circular imports in 1.1.300

### ISSUE THREAD

**Issue by last-partizan** [microsoft/pyright#5030]
**Describe the bug**
Some time ago i noticed that references in my project included not only references, but also function or methods with same name. When renaming a function, it will also rename unrelated functions with same name, but i believe the core problem is in invalid references.

Today i tested different pyright versions, and looks like this started with 1.1.300.

Bug happens in nvim when using pyright as language server. VScode with pylance does not have this issue.

**To Reproduce**
1. Install https://github.com/neovim/nvim-lspconfig and pyright.
2. Clone example project: https://github.com/last-partizan/pyright-examples/tree/2c1b5e35922c8ce04b34d00d802bc66cffcaf750 (branch `invalid-references`).
3. Position cursor at `update_historical_traffic` at line 4 and call `:lua vim.lsp.buf.references()`. It will return `utils.update_historical_traffic`.
  ![image](https://user-images.githubusercontent.com/301015/235108216-7ad34ce0-797f-4545-920e-864ad6801823.png)

<details>
    <summary>Instead of cloning project you can create files manually:</summary>

```python
# File: app/tasks.py
from app import utils


def update_historical_traffic():
    ...


def port_update_historical_traffic(port):
    utils.update_historical_traffic(port)


def update_portmap(switch):
    ...
```
```python
# File: app/utils.py
def update_historical_traffic(port):
    ...


def start_update_portmap():
    from app.tasks import update_portmap
    update_portmap(None)
```
</details>

**Expected behavior**
Expected correct result when using pyryght 1.1.299:
![image](https://user-images.githubusercontent.com/301015/235108790-dbfeb9a2-d00e-447b-be0d-fbbe15df8fc0.png)

**VS Code extension or command-line**
LSP server is running with following arguments:
```
node /usr/bin/pyright-langserver --stdio
```

**Additional context**

Full LSP server log:
[lsp.log](https://github.com/microsoft/pyright/files/11352069/lsp.log)

**Comment by debonte** [comment]
>VScode with pylance does not have this issue.

This repros for me in Pylance. Might be related to https://github.com/microsoft/pylance-release/issues/4285?
