### ISSUE TITLE
Allow setting venv from CLI

### ISSUE THREAD

**Issue by mmohaveri** [microsoft/pyright#5043]
**Is your feature request related to a problem? Please describe.**
I'm trying to run pyright installed in a virtual environment (which contains all the requirements of the project as well) from outside of the virtual environment (by calling the `<virtual envs rool>/<virtual env name>/bin/pyrigh`).

When I do this, pyright does not recognize my installed packages correctly and the only way I found around the issue is to set the `venv-path` and `venv` values in the configuration.

The problem is that I cannot set the value of the `venv` (virtual environment's name) from CLI, which means I can not allow other developers to choose their virtual environment name and have to hard code it in the config.

**Describe the solution you'd like**
Currently, we have the ability to set `venv-path` from CLI by using `--venv-path`, I want to have the same ability but with `venv`.

**Comment by erictraut** [comment]
The `venv` and `venvPath` mechanism is designed to be used in cases where the `venv` name is common to all developers in a team. 

The more common configuration mechanism (and the one that sounds like it is what you're looking for) is for pyright to use the Python environment that is currently configured in the shell. Simply enable the virtual environment that you desire (e.g. by using `source <venv>/bin/activate`) and then run pyright. There's no need to specify a `venvPath` or `venv` using this method.

**Comment by mmohaveri** [comment]
@erictraut I understand what you're saying regarding the `activate virtual environment` approach, but what I'm trying to do is to write a set of helper shell scripts (actually Makefiles) for other developers of the team to use as a kind of shortcut. And I though it would be nice if they worked correctly even if the virtual environment is not activated (one fewer step to do when working maybe?).

I have two notes regarding your response:

Firstly, respectfully, It feel weird that an option to change the behavior of the program is in the configuration, but not in CLI.

Secondly, I don't understand the reasoning behind `mechanism is designed to be used in cases where the venv name is common to all developers in a team.`.
That truly have newer happened to me in my 10 years working in python teams. Normally, each team member has their own naming scheme for their virtual environments on their system, and some even have multiple virtual environments  for a single project (maybe they want to test something new and don't want to modify their original environment, maybe they have different environments for different python version, etc.)

For these reasons I ask you to please reconsider your position on "as desinged" tag if possible.

**Comment by erictraut** [comment]
You're attempting to use the `venv`/`venvPath` facility in a manner for which it wasn't designed, so it predictably won't work. As I explained, pyright has a different (more commonly-used) mechanism that should meet your requirements.

If you're writing a helper shell script and your script is provided the name and location of the venv that is specific to the developer, simply activate that venv and then invoke pyright.
