### ISSUE TITLE
Type Narrowing not happening inside an `if` statement

### ISSUE THREAD

**Issue by xavdid** [microsoft/pyright#5048]
**Describe the bug**

Given a pair of `TypedDict`s with no common fields in a union, I'd expect the union to be narrowed given a successful key check. Interestingly, this works _outside_ the `if` statement, but not inside.

**To Reproduce**

```py
from typing import TypedDict, reveal_type

class Success(TypedDict):
    data: str

class Failure(TypedDict):
    err: int
    message: str

def process_response(response: Success | Failure):
    if 'err' in response:
        reveal_type(response) # Type of "response" is "Success | Failure"; I'd expect Failure only
        return
    
    reveal_type(response) # Type of "response" is "Success"; as expected
```

**Expected behavior**

I'd expect the type of `response` to be `Failure` inside the `if` statement and `Success` outside it.

**VS Code extension or command-line**

Using Pyright via Pylance. Extension version is `v2023.4.40`

**Comment by erictraut** [comment]
Pyright will perform this narrowing if you mark `Success` as `@final`. If it's not marked final, it can potentially be subclassed, so it's not safe to narrow it.
