### ISSUE TITLE
Since v1.1.305: Second argument to "isinstance" must be a class or tuple of classes

### ISSUE THREAD

**Issue by stefanberger** [microsoft/pyright#5053]
**Describe the bug**

**To Reproduce**

test.py:
```
_list_types = [list, tuple]
data=[]
isinstance(data, tuple(_list_types))
```

$ pyright test.py
No configuration file found.
pyproject.toml file found at /home/stefanb/keylime.
Loading pyproject.toml file at /home/stefanb/keylime/pyproject.toml
Assuming Python version 3.9
Assuming Python platform Linux
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Searching for source files
Found 1 source file
pyright 1.1.305
/home/stefanb/keylime/test.py
  /home/stefanb/keylime/test.py:3:18 - error: Second argument to "isinstance" must be a class or tuple of classes
    TypeVar or generic type with type arguments not allowed (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
Completed in 0.792sec

**Expected behavior**
No report since 2nd argument is a tuple.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.306, which I just published. It will also be included in a future release of pylance.
