### ISSUE TITLE
Inferred type of annotated variable is inconsistent with mypy result

### ISSUE THREAD

**Issue by jfmcoronel** [microsoft/pyright#5057]
**Describe the bug**
Variable assignment statement annotated with `Sequence` _(via either the colon-based type hint syntax or a type comment)_ uses type of assigned list literal instead of simply using the annotation.

**To reproduce**
See minimized reproducible example below.

**Expected behavior**
mypy follows the type hint as is.

mypy feedback:

- test.py:7: note: Revealed type is "typing.Sequence[builtins.int]" _(for `x`; inconsistent with Pyright)_
- test.py:8: note: Revealed type is "typing.Sequence[builtins.int]" _(for `y`; inconsistent with Pyright)_
- test.py:9: note: Revealed type is "builtins.list[builtins.int]" _(for `z`; consistent with Pyright)_

**Screenshots or code**
```python
from collections.abc import Sequence

x: Sequence[int] = [1, 2, 3]
y = [1, 2, 3]  # type: Sequence[int]
z: list[int] = [1, 2, 3]

reveal_type(x)  # Type of "x" is "list[int]" (incorrect; should be `Sequence[int]`)
reveal_type(y)  # Type of "y" is "list[int]" (incorrect; should be `Sequence[int]`)
reveal_type(z)  # Type of "z" is "list[int]" (correct)
```

**VS Code extension or command-line**
Pyright 1.1.305 _(command line)_

**Additional context**
Removing the type parameter in `Sequence[int]` yields the same incorrect behavior. Not sure if this is actually a mypy bug, but mypy's current behavior seems more proper for this particular instance _(why bother annotating if it gets overridden anyway?)_.

This becomes problematic when passing the said variable to a function that expects `list[T]` _(or the like)_ which is invariant; mypy flags this while Pyright does not.

**Comment by erictraut** [comment]
This behavior is correct. The `reveal_type` reveals the narrowed type of the expression, not the declared type. The type is narrowed on assignment based on the assigned value.

Mypy's behavior is inconsistent here. If you change `x: Sequence[int] = [1, 2, 3]` to two separate lines (`x: Sequence[int]` followed by `x = [1, 2, 3]`), you'll see that it produces the same behavior as pyright.

See [this documentation](https://microsoft.github.io/pyright/#/mypy-comparison?id=assignment-based-type-narrowing) for more information.
