### ISSUE TITLE
Type narrowing in method decorator

### ISSUE THREAD

**Issue by JoeZiminski** [microsoft/pyright#5059]
In general I have trouble finding a neat way to handle state changes on a class variable (this is often related to GUI in which a window may or may not be open). Currently I handle this by type narrowing with asserts / if statements. However, this gets a bit messy when there are many methods that need such a variable. It would be nice to wrap certain methods in decorators that perform type narrowing, however as far as I can tell this is not supported, though maybe it is not supported for good reason!

Maybe there are better ways to handle this problem (please do enlighten me if so), but it would be nice if it was possible to do something like this
```
from functools import wraps

def type_narrow_class_attribute(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        assert args[0].class_var is not None, "Type narrow class var"
        func(*args, **kwargs)
    return wrapper

class MyClass:
    def __init__(self):
        self.class_var: Optional[Int] = None

    def update_on_file_load(self, new_data):
        self.class_var = new_data

    @type_narrow_class_attribute
    def do_something_with_class_var(self):
        self.class_var += 1
```

instead of this

```
class MyClass:
    def __init__(self):

        self.class_var: Optional[Int] = None

    def update_on_file_load(self, new_data):
        self.class_var = new_data

    def do_something_with_class_var(self):
        if self.class_var is not None:
            self.class_var += 1
```

**Comment by erictraut** [comment]
Pyright is working as designed here. 

The recommended solutions are:
1. Wherever possible, initialize a class or instance variable in the constructor with a value that is not `None`. That way, it is guaranteed never to contain a `None` type.
2. If option 1 isn't possible, then use an `if` guard or an assert statement. These serve as documentation (and runtime validation) of your assumptions.

I wouldn't recommend using the the technique you've described above. It is messy, difficult for a human to read, and it obscures the intent for a static type checker.
