### ISSUE TITLE
Incorrect type inference for matplotlib

### ISSUE THREAD

**Issue by JanEricNitschke** [microsoft/pyright#5060]
**Describe the bug**
After upgrading to version 1.1.306  i am now getting type errors for matplotlib calls.

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
import matplotlib.pyplot as plt
figure: plt.Figure
axes: plt.Axes
figure, axes = plt.subplots()
axes.imshow([], zorder=0)
```
```
D:\CSGO\ML\csgo\awpy\pyright_debugging.py
  D:\CSGO\ML\csgo\awpy\pyright_debugging.py:4:16 - error: Expression of type "FigureBase | Unknown" cannot be assigned to declared type "Figure"
    Type "FigureBase | Unknown" cannot be assigned to type "Figure"
      "FigureBase" is incompatible with "Figure" (reportGeneralTypeIssues)
  D:\CSGO\ML\csgo\awpy\pyright_debugging.py:4:16 - error: Expression of type "Any | ndarray[Any, dtype[Any]] | Unknown" cannot be assigned to declared type "Axes"
    Type "Any | ndarray[Any, dtype[Any]] | Unknown" cannot be assigned to type "Axes"
      "ndarray[Any, dtype[Any]]" is incompatible with "Axes" (reportGeneralTypeIssues)
```

**VS Code extension or command-line**
This happens when running from the command-line with version 1.1.306. The vscode extension (pylance: v2023.4.40) still infers `Figure` and `Axes` as the types for figure and axes.

**Comment by erictraut** [comment]
This is intended behavior. Matplotlib is an untyped library, and I presume that you have no type stubs installed for it. When pyright encounters an untyped library, it can either infer that the types of all imported symbols are `Unknown` or it can attempt to infer the types from the library source code. This is controlled by the `useLibraryCodeForTypes` configuration option. Prior to 1.1.306, the pyright CLI defaulted `useLibraryCodeForTypes` to false. We made the decision to switch this default value of this setting so it matches pylance. 

You can restore the old behavior by setting `useLibraryCodeForTypes` to false explicitly in your pyrightconfig.json or pyproject.toml file.

**Comment by JanEricNitschke** [comment]
Ah, i missed the change of `useLibraryCodeForTypes`. 

I guess pylance gets this correct in vscode because it has access to these: https://github.com/microsoft/python-type-stubs/tree/main/matplotlib

Sadly there seems to be no easy way to also install these such that the pyright CLI also has access?

**Comment by erictraut** [comment]
Refer to [this documentation](https://github.com/microsoft/pylance-release/blob/main/USING_WITH_PYRIGHT.md) for eliminating differences in behavior between pylance and pyright.
