### ISSUE TITLE
Since v1.1.306: New reported issue due to misunderstood SQLAlchemy column datatypes

### ISSUE THREAD

**Issue by stefanberger** [microsoft/pyright#5062]
**Describe the bug**

Since v1.1.306 pyright reports a few more issues related to datatypes of SQLAlchemy columns. An example is the following:

/home/stefanb/keylime/keylime/cloud_verifier_tornado.py
  /home/stefanb/keylime/keylime/cloud_verifier_tornado.py:1281:12 - error: Invalid conditional operand of type "ColumnElement[bool]"
    Method __bool__ for type "ColumnElement[bool]" returns type "NoReturn" rather than "bool" (reportGeneralTypeIssues)

This corresponds to the following code (https://github.com/keylime/keylime/blob/c1f742eedc200f2d663e2615e1de4acccd6c4d53/keylime/cloud_verifier_tornado.py#L1281):

```
        # if the user did terminated this agent
        logger.error(">>>>> %s", str(type(stored_agent.operational_state)))
        logger.error(">>>>> %s", str(type(stored_agent)))
        if stored_agent.operational_state == states.TERMINATED:
```

The runtime output shows that `stored_agent.operational_state` is an `int`:
```
2023-05-03 08:57:43.882 - keylime.verifier - ERROR - >>>>> <class 'int'>
2023-05-03 08:57:43.882 - keylime.verifier - ERROR - >>>>> <class 'keylime.db.verifier_db.VerfierMain'>
```

Annotation of the `operational_state` like the following doesn't work:
```
    operational_state: int = Column(Integer)
```

I am not sure what the solution is other than `# pright: ignore` annotation.

**To Reproduce**

Run pyright on keylime:

git clone https://github.com/keylime/keylime.git
tox -r -vv -e pyright

**Expected behavior**
Considering that during runtime the Column(Integer) is an int, no error should be reported.

**Comment by erictraut** [comment]
This error message is related to a new check that was implemented in pyright 1.1.306. To read more about it, refer to [this issue](https://github.com/microsoft/pyright/issues/5039). It determines whether a conditional is using an object that does not implement the `__bool__` method or implements a `__bool__` method that returns a value whose type is not `bool`.

Digging into this case, the expression `stored_agent.operational_state == states.TERMINATED` is evaluated as type `ColumnElement[bool]`. The `ColumnElement` class derives from the `ClauseElement` class, which implements a `__bool__` method that is annotated to return a `NoReturn` type. 

I don't know enough about SQLAlchemy and its class hierarchies to diagnose the problem further, but I think pyright is doing the right thing here in generating this error.

**Comment by stefanberger** [comment]
The unfortunate problem is that even this trick doesn't work:

```
        operational_state: int = stored_agent.operational_state
        if operational_state == states.TERMINATED:
```

```
/home/stefanb/keylime/keylime/cloud_verifier_tornado.py
  /home/stefanb/keylime/keylime/cloud_verifier_tornado.py:1283:34 - error: Expression of type "Column[int]" cannot be assigned to declared type "int"
    "Column[int]" is incompatible with "int" (reportGeneralTypeIssues)
```

It looks like the annotation `# pyright: ignore`  is the only way out.

**Comment by erictraut** [comment]
If you're familiar with the SQLAlchemy library, perhaps you can diagnose the problem further. If you're not, you might want to consult with someone who is more familiar with the way SQLAlchemy is intended to work here. For example, is the `ColumnElement[bool]` instance the correct result for an `==` comparison? If so, does `ColumnElement` really generate an exception its `__bool__` method is called? (I think the answer here must be no because it would generate a runtime exception if that were the case.)

**Comment by rcarpa** [comment]
Commenting here in case it will be useful for somebody. To correctly support type hints for Declarative mappings, the following steps have to be performed: https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#orm-declarative-models

**Comment by dbolser** [comment]
> It looks like the annotation `# pyright: ignore` is the only way out.

Is there a more precise way to ignore this? e.g. ` pyright: ignore #345`?

**Comment by dbolser** [comment]
For anyone googling like me, see `pip install sqlalchemy-stubs` (https://stackoverflow.com/a/76982753/22829104)

**Comment by co-odw** [comment]
> For anyone googling like me, see `pip install sqlalchemy-stubs` (https://stackoverflow.com/a/76982753/22829104)

the stubs do not work with 2.0

This 3 step approach worked for me: https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#migrating-an-existing-mapping

**Comment by gae-rafatjah** [comment]
> > For anyone googling like me, see `pip install sqlalchemy-stubs` (https://stackoverflow.com/a/76982753/22829104)
> 
> the stubs do not work with 2.0
> 
> This 3 step approach worked for me: https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#migrating-an-existing-mapping

I confirm that this works.
