### ISSUE TITLE
Featire request: Allow unpacking of type variable bound to typed dict

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#5069]
```python
from typing import Generic, Unpack

from typing_extensions import TypedDict, TypeVar


Extra = TypeVar('Extra', bound=TypedDict)


class C(Generic[Extra]):
    def f(self, **kwargs: Unpack[Extra]) -> None:  # error: Expected TypedDict type argument for Unpack (reportGeneralTypeIssues)
        pass
```

**Comment by NeilGirdhar** [comment]
Ultimately, I'd like something like this to work if possible?
```python
from typing import Generic, Unpack

from typing_extensions import TypedDict, TypeVar, override


class EmptyDict(TypedDict, total=True):
    pass


Extra = TypeVar('Extra', bound=TypedDict, default=EmptyDict)


class C(Generic[Extra]):
    def f(self, **kwargs: Unpack[Extra]) -> None:  # error: Expected TypedDict type argument for Unpack (reportGeneralTypeIssues)
        pass


class D(C):
    @override
    def f(self) -> None:  # error: Method "f" overrides class "C" in an incompatible manner
        pass



D().f()
```

**Comment by erictraut** [comment]
This would require an extension to the Python type system, so it is best discussed in the python/typing forum. It would probably require a new PEP or an extension to [PEP 692](https://peps.python.org/pep-0692/).

There are two extensions that would be required:
1. It would need to be clarified that the `TypedDict` special form can be used as a type (e.g. as a variable type annotation or a bound). Currently, this is not clear. Mypy specifically generates an error when it is used in this manner. Pyright doesn't currently, but it probably should.
2. The functionality in PEP 692 would need to be extended to accommodate an `Unpack[T]` where `T` is specifically bound to a `TypedDict` (assuming 1 is allowed).

I'm going to close this enhancement request for. If you want to get feedback from the broader typing community about these changes/extensions, please open an issue in python/typing.

**Comment by NeilGirdhar** [comment]
@erictraut Okay, many thanks for your thorough explanation as always!
