### ISSUE TITLE
Behavior change with matplotlib between pyright 1.1.305 and 1.1.306

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#5076]
Install matplotlib 3.7.1, python 3.9.16

Command line pyright, with following code:
```python
import matplotlib.pyplot as plt

_, ax = plt.subplots(1, 1)
reveal_type(ax)
```

With pyright 1.1.305, I get:
```text
pyplottst.py:4:13 - information: Type of "ax" is "Unknown"
```

With pyright 1.1.306, I get:
```text
pyplottst.py:4:13 - information: Type of "ax" is "Any | ndarray[Any, dtype[Any]] | Unknown"
```

With mypy 1.2, I get:
```text
pyplottst.py:4: note: Revealed type is "Any"
```

So the behavior change with pyright 1.1.306 is making it hard to do type checking in a consistent way across pyright and mypy.

I'm not sure if this is a bug or feature of the latest version of pyright, but if a feature, we'll have to figure out what to do about it.

**Comment by erictraut** [comment]
Matplotlib isn't a typed library. 

Mypy evaluates the types of all symbols from an untyped library as `Any`. If that's the behavior you want in pyright, you can set `useLibraryCodeForTypes` to false in your pyright configuration.

Prior to 1.1.306, the pyright CLI defaulted `useLibraryCodeForTypes` to false, but after much discussion we decided to change the default to true to match pylance. See [this issue](https://github.com/microsoft/pyright/issues/4904) for details.
