### ISSUE TITLE
Inferred type for async generators is wrong

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#5080]
**Describe the bug**
The inferred return type of async generators is wrong, pyright currently shows Generator[...] not AsyncGenerator[...]

**To Reproduce**
<img width="391" alt="image" src="https://user-images.githubusercontent.com/50501825/236944007-a1201830-3c16-425e-96d1-b7b7bd135ec3.png">
Following typehint
<img width="971" alt="image" src="https://user-images.githubusercontent.com/50501825/236944162-5da62aa1-0794-4bb1-a2e6-a6d3336451a0.png">

**Expected behavior**
Pyright should suggest AsyncGenerator

**Screenshots or Code**
```python
async def foo():
    yield
```

**VS Code extension or command-line**
pylance v2023.5.11

**Comment by erictraut** [comment]
Pyright does infer the correct return type here. The `async` keyword acts something like a decorator, which changes the return type of the function. If you hover over `foo` in the function definition, you'll see that it returns `Generator`, but if you hover over a different reference to `foo` (which refers to the "decorated" function), you'll see that it correctly transforms `Generator` into `AsyncGenerator`.

![image](https://user-images.githubusercontent.com/7040122/236974367-774e72c1-0a5b-45da-86a3-cb778927138f.png)
