### ISSUE TITLE
Deprecated decorator false positive

### ISSUE THREAD

**Issue by ItsDrike** [microsoft/pyright#5082]
**Describe the bug**
PEP 702 proposes an introduction of a new `@deprecated` decorator, which pyright already seems to be recognizing. This is fine when it's imported from `typing_extensions`, however pyright also treats custom functions named "`deprecated`" in the same way.

**To Reproduce**
1. Create a custom function named `deprecated`
2. Use this function as to decorate another function
3. Notice the decorated function was marked deprecated

**Expected behavior**
I'm not sure this is actually a bug, or if it was introduced as a feature to support other implementations of deprecated. However I'm assuming it's a bug, and if so, only the deprecated decorator actually imported from `typing_extensions` (or later `typing`) should be marking a function as deprecated, custom implementations might not act the same way, in fact they might not even be decorators.

That said, it would probably be pretty weird for someone to implement a function called `deprecated` that's not a decorator, and this could actually be useful for custom implementations, so perhaps it's worth keeping around as a feature, I'm only reporting this since I haven't seen any mention of this being a feature, so in case this isn't supposed to happen, it might be worth addressing.

**Screenshots or Code**
![image](https://github.com/microsoft/pyright/assets/20902250/e810b178-03dc-4717-b0f2-4c4810c2e9b9)

**Comment by erictraut** [comment]
Thanks for the bug report. This is definitely unintentional. It's an easy fix, and it will be included in the next release of pyright.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.307, which I just published. It will also be included in a future release of pylance.
