### ISSUE TITLE
Pyright doesn't know opencv anymore

### ISSUE THREAD

**Issue by RunDevelopment** [microsoft/pyright#5094]
**Describe the bug**
We recently found that our CI suddenly failed because pyright complained:
```
error: "bool8" is not a known member of module (reportGeneralTypeIssues)
```
(The module is `numpy` here. The code snippets was `numpy.bool8`.)

Because of this, I tried upgrading from 1.1.294 to the latest version: 1.1.307. However, this was even worse. The error message got better:

```
error: "bool8" is not a known member of module "numpy" (reportGeneralTypeIssues)
```

But we also got a few hundred new ones, because pyright now also doesn't know opencv anymore. Examples:
```
error: "THRESH_BINARY" is not a known member of module "cv2" (reportGeneralTypeIssues)
error: "resize" is not a known member of module "cv2"
error: "cvtColor" is not a known member of module "cv2"
```

**To Reproduce**
See [this GitHub actions CI log](https://github.com/chaiNNer-org/chaiNNer/actions/runs/4939924192/jobs/8831114987?pr=1793). I'm currently trying to get pyright working again over in https://github.com/chaiNNer-org/chaiNNer/pull/1793.

**Expected behavior**
Pyright should let the code pass.

**VS Code extension or command-line**
We are using command line pyright v1.1.307, opencv-python v4.7.0.72, and numpy v1.24.3. For information about the exact installation, check the CI log.

**Comment by erictraut** [comment]
Please provide a minimal, self-contained code sample that demonstrates the problem you're seeing.

**Comment by erictraut** [comment]
We recently changed the default value of the `useLibraryCodeForTypes` configuration setting from "false" to "true" in pyright (to match the default in pylance). That may explain the difference you're seeing here. If so, that is intended. You can verify this by explicitly setting the value to "false" in the configuration file.

**Comment by RunDevelopment** [comment]
`useLibraryCodeForTypes: false` fixed the issue with OpenCV. Thank you very much!
