### ISSUE TITLE
Incorrect return type for python's built-in `next`

### ISSUE THREAD

**Issue by RunDevelopment** [microsoft/pyright#5097]
**Describe the bug**
If `next` is called with an iterator of item type `Unknown` and a default value is given, the return type of `next(iter, default)` will only be the type of the default value. The `Unknown` of the item type is ignored.

**To Reproduce**
The return type of the following function is inferred as `None`.

```py
def get_first(l: list):
    return next(iter(l), None)
```

![image](https://github.com/microsoft/pyright/assets/20878432/29762273-4ad9-4a3b-bd7d-740f9e867a00)

(Using pylance in VSCode.)

**Expected behavior**
The return type of the above example should be `Unknown | None`.

**Screenshots or Code**
See above.

**VS Code extension or command-line**
Pylance VSCode extension version: v2023.5.10 (which uses pyright 1.1.305)
VSCode version: 1.78.1

I have also been able to reproduce this using pyright command line 1.1.307.

**Additional context**
The return type of `next` is correct if no default value is given.

![image](https://github.com/microsoft/pyright/assets/20878432/1e5a9917-b278-4543-8836-c2cfeee68ba4)

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.

If you're interested in the details... Pyright includes some heuristics when evaluating the type of a call to a generic function. If one or more of the type variables go unsolved and these type variables are included in the return type (e.g. the function `def func(x: T | None) -> T | int: ...` is called with `func(None)`), we don't want these to turn into an `Unknown`, so pyright drops the `Unknown` in this case. In your sample, the type variable `_T` in the `next` function _is_ solved, so the `Unknown` should not be dropped in this case.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.308, which I just published. It will also be included in a future release of pylance.
