### ISSUE TITLE
Unknown members in module

### ISSUE THREAD

**Issue by LukeHankey** [microsoft/pyright#5098]
**Describe the bug**
Modules are not found from the base module, specifically in matplotlib.

**To Reproduce**
```py
import matplotlib as mlp

print(mlp.colors)
print(mlp.cm)
```
Run with pyright>=1.1.306.
Current matplotlib version is 3.7.0

**Expected behavior**
Modules are to be found and not raise an error for `reportGeneralTypeIssues`.

**Screenshots or Code**
![image](https://github.com/microsoft/pyright/assets/68163698/ec4a8b5a-6228-4df7-9dc0-cfe3cf5bd8bb)

**VS Code extension or command-line**
CLI + pre-commit. Failing versions are 1.1.306 and 1.1.307

**Comment by erictraut** [comment]
Pyright's behavior is correct here. The `matplotlib` top-level module doesn't explicitly import the `colors` or `cm` submodules into its namespace (e.g. `from . import colors`). If you want to safely access these submodules in your code, you would need to import them explicitly, as in `import matplotlib.colors`.
