### ISSUE TITLE
Return type hint for __truediv__ seems unused for type inference

### ISSUE THREAD

**Issue by moskupols** [microsoft/pyright#5110]
**Describe the bug**
Pyright doesn't seem to use the return type hint of `__truediv__` method when analyzing a division operation.

**To Reproduce**
See code example. Note that the return type of use_truediv is inferred as Unknown.

**Expected behavior**
The return type of `Example.use_truediv` is inferred as float instead of Unknown. I expect this to work since it works for `Example.use_divide`.

**Screenshots or Code**
```python
class Example:
    def __truediv__(self, that) -> float:
        return 42.0 / that

    def divide(self, that) -> float:
        return 42.0 / that

    def use_truediv(self, that): # -> Unknown
        return self / that

    def use_divide(self, that):  # -> float
        return self.divide(that)
```

**VS Code extension or command-line**
I'm running pyright 1.1.307 with coc-pyright

**Comment by erictraut** [comment]
Pyright does honor the `__truediv__` (or `__rtruediv__`) return type. The inferred type of a `/` operator is based on the types of its two operands. In your function `use_truediv`, the type of `self` is `Self@Example`, and the type of `that` is `Unknown` (i.e. an implicit `Any`). When the type of either of the operands for a binary operator is unknown, pyright evaluates the type of the operation as `Unknown`. If you provide a type annotation for `that`, it will work as you are expecting.

```python
    def use_truediv(self, that: object):  # -> float
        return self / that
```
