### ISSUE TITLE
Pyright Survey Results (2023)

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#5114]
Back in February, I posted [a survey](https://github.com/microsoft/pyright/issues/4601) that asked about your experience with the pyright project. I want to thank everyone who responded to the survey. We had just shy of 50 respondents.

Here's a summary of the survey results. Since this is the third year we've conducted this survey, I've included some year-over-year comparisons.

![image](https://github.com/microsoft/pyright/assets/7040122/eaf30620-6215-4bbc-af78-deea8bf12d83)

![image](https://github.com/microsoft/pyright/assets/7040122/d7124ef2-6272-498a-90d6-8a15c889d775)

![image](https://github.com/microsoft/pyright/assets/7040122/94853b57-bdf8-40fb-97bb-7c83f4a9ad18)

![image](https://github.com/microsoft/pyright/assets/7040122/3c3d2bb3-02ff-4b15-a0c1-825346d6d259)

![image](https://github.com/microsoft/pyright/assets/7040122/c32d28b5-4b06-4072-9c04-0b660d410353)

![image](https://github.com/microsoft/pyright/assets/7040122/5838c2d7-7681-40f5-943d-735b219aeebb)

Compared to other Microsoft open-source project that also participated in the survey, pyright received the highest “NSAT” (net satisfaction) score. NSAT is a number between 0 and 200 with 100 being “neutral”. The overall NSAT for the pyright project was 160.

In the written responses, several respondents mentioned that they appreciated my responsiveness and thorough explanations. A couple also mentioned that they felt I was sometimes too dismissive of bug reports or feature requests. Fair enough.

As of last month, I am no longer working for Microsoft, but I am still contributing to pyright in my spare time. (Even when I was employed by Microsoft, pyright was not my day job.) Pyright continues to be a Microsoft-sponsored open source project, and it remains the foundation for Pylance, Microsoft’s language server for Python developers.

**Comment by trinhanhngoc** [comment]
Hi @erictraut As a pyright/pylance follower, I just wanted to say that you are amazing, really amazing. I have never met a developer who addresses issues as quickly as you. Your answers to all questions are also very detailed and easy to understand. I'm a bit shocked to learn that you are no longer working for Microsoft, and this was not your day job either. I am a bit worried about the future of pyright without your contribution.

**Comment by Julian** [comment]
You know this of course, but I (as an outsider) have observed your tact in responding to issues -- I think as a maintainer one makes a decision on whether to prefer being "softer" on issues -- leaving them open which sometimes makes filers feel better but which ultimately leads often to stale issues or false hope that something will be considered when it's really just not going to happen -- or being brisker, faster with closes, having users be slightly more "man did he really need to close it that quick", but ending up with more clarity, immediate feedback, a cleaner bug tracker, a higher bar for what's really considered to be worked on so ideally a higher quality bit of software, etc.

The point of the comment just being -- as a fellow maintainer but just a user of this repo, I get it a bit :) and think it's a perfectly reasonable strategy regardless of making a few extra unintentional offenses which is going to show up on such a survey. So yeah, it's appreciated, and if I were you, I wouldn't change much there!

Thanks for all your work.

**Comment by xavdid** [comment]
Just wanted to chime in with the above- I'm always impressed with your superhuman response times (even at odd hours). I can understand how some might call your responses curt, but you _do_ answer questions and keep your issue queue clean.

I wish you luck in your next endeavors and really appreciate what you've brought to the Python typing community.
