### ISSUE TITLE
PEP-612 return parameter specification type hinting

### ISSUE THREAD

**Issue by Mardoxx** [microsoft/pyright#5119]
With Python 3.11

Taking the example here, https://peps.python.org/pep-0612/#semantics

```python
P = ParamSpec("P")
U = TypeVar("U")

class Y(Generic[U, P]):
  f: Callable[P, str]
  prop: U

  def __init__(self, f: Callable[P, str], prop: U) -> None:
    self.f = f
    self.prop = prop

def a(q: int) -> str: ...

Y(a, 1)   # Should resolve to Y[(q: int), int]
Y(a, 1).f # Should resolve to (q: int) -> str
```

What is this type definition here? `Y[(q: int), int]` - I understand what its intent is, but what _is_ it

`foo: Y[(q: int), int] = ...` gives a type error. So why does `foo = Y(a, 1)` display it instead of `Y[Unknown, int]` or something else

Being able to specify named arguments like this would be very useful, is it proposed?

**Comment by erictraut** [comment]
Converting to discussion since this is a question, not a bug report.
