### ISSUE TITLE
Cannot Unpack a TypeVar which is Bounded by a TypedDict.

### ISSUE THREAD

**Issue by mezuzza** [microsoft/pyright#5138]
**Describe the bug**
As the title says, it is not possible to unpack a TypeVar which is bounded by a TypedDict. I'd imagine that the 

**To Reproduce**
Run pyright on the code below.

**Expected behavior**
The code typechecks

**Screenshots or Code**
```python
from typing import TypeVar, Generic, TypedDict
from typing_extensions import Unpack

T = TypeVar("T", bound=TypedDict)

class Foo(Generic[T]):
  def baz(self, **kwargs: Unpack[T]): # type error
    ...
```

**VS Code extension or command-line**
Command-line

**Additional context**
pyright version: 1.1.294
python version: 3.10

I know this is a bit of an odd use case and there are a few workarounds, but the fact that this doesn't work is a bit surprising to me.

**Comment by erictraut** [comment]
`TypedDict` is a special form, not a class, so it doesn't make sense to use it as the bound for a TypeVar.

Also, you can't use a TypeVar in an Unpack statement for `**kwargs`. This isn't permitted by [PEP 692](https://peps.python.org/pep-0692/). You need to use a concrete TypedDict class.
