### ISSUE TITLE
Version >= 1.1.307 fails to recognize CDK constructs

### ISSUE THREAD

**Issue by michelesr** [microsoft/pyright#5156]
**Describe the bug**
After updating to version 1.1.307 or later, CDK fails to recognize instances of CDK construct classes.

**To Reproduce**
- install the `constructs==10.2.1` package with pip
- create an instance of a cdk construct class 

**Expected behavior**
Variable `c` is recognized as variable of type `Construct`

**Screenshots or Code**

```
from constructs import Construct

c = Construct("foo", "foo", "bar", "hello", "world")
```

See screenshots
<img width="472" alt="Screenshot 2023-05-23 at 10 48 18" src="https://github.com/microsoft/pyright/assets/2516077/e5537fe6-ffc7-45cc-b158-ff40d3aa4b28">
<img width="768" alt="Screenshot 2023-05-23 at 10 48 56" src="https://github.com/microsoft/pyright/assets/2516077/db9c4fdd-ab13-458e-80ae-6e714d18c59a">

**Comment by erictraut** [comment]
I'm going to close this issue since it's already tracked in the other pylance-release issue.

**Comment by michelesr** [comment]
reported
