### ISSUE TITLE
true should be recognized as keyword in json or not recognized at all

### ISSUE THREAD

**Issue by mugnier102** [microsoft/pyright#5161]
Open a python file with some json string in it.
Some of this json should be boolean True value.
The keywords "True" is recognized.
however, the JSON say that True value should be write as lower case.
change it in the editor, true is no more a keyword...
We should be able to see that the value is in a json array.

Correct but not recognized
    payload = {
            "lang": "FR",
            "nfc": true,
            "nfcDataFormat": "Decimal",
            "nfcByteOrder": true
    }

Not correct but recognized:
    payload = {
            "lang": "FR",
            "nfc": True,
            "nfcDataFormat": "Decimal",
            "nfcByteOrder": True
    }

**Comment by erictraut** [comment]
There is no such thing as a "JSON Array" built in to the Python language, nor is there a builtin symbol `true`. Python's stdlib does offer a module that converts a Python dict into a stringified JSON output. This module converts `True` to `true` in the resulting JSON strong. Perhaps that's what you have in mind?

If you paste the first dictionary into a Python source file and run it, the Python interpreter will generate a runtime exception "NameError: name 'true' is not defined. Did you mean: 'True'?".

So is correct in flagging the error in your code above.

**Comment by mugnier102** [comment]
Thanks for this interesting answer ;-) I will be more careful on proposed correction then.
