### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'param')

### ISSUE THREAD

**Issue by debonte** [microsoft/pyright#5173]
Maybe related to #5091? The hit counts of the two stacks are pretty similar over the past couple months. However, we're still seeing this error in Pylance 2023.5.31 (Pyright 1.1.309), but don't have any hits of #5091 since 2023.5.30 (Pyright 1.1.307). Maybe because of https://github.com/microsoft/pyright/commit/1e330a7bd699613e3fa720ccfdc0ff7fbd0662a6?

TypeError: Cannot read properties of undefined (reading 'param')</br>at param <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L9656'>pyright-internal/src/analyzer/typeEvaluator.ts:9656:44</a></br>at matchFunctionArgumentsToParameters <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L10684'>pyright-internal/src/analyzer/typeEvaluator.ts:10684:29</a></br>    at validateFunctionArguments <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L8666'>pyright-internal/src/analyzer/typeEvaluator.ts:8666:47</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L3653'>pyright-internal/src/analyzer/typeEvaluator.ts:3653:38</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeUtils.ts#L487'>pyright-internal/src/analyzer/typeUtils.ts:487:8</a></br>at expandedType <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L3646'>pyright-internal/src/analyzer/typeEvaluator.ts:3646:29</a></br>at expandSubtype <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L3677'>pyright-internal/src/analyzer/typeEvaluator.ts:3677:12</a></br>at mapSubtypesExpandTypeVars <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L8595'>pyright-internal/src/analyzer/typeEvaluator.ts:8595:25</a></br>at validateCallArguments <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L1569'>pyright-internal/src/analyzer/typeEvaluator.ts:1569:12</a></br>at getTypeOfDecorator <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L15788'>pyright-internal/src/analyzer/typeEvaluator.ts:15788:15</a></br>at applyClassDecorator <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L15294'>pyright-internal/src/analyzer/typeEvaluator.ts:15294:37</a></br>at getTypeOfClass <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L19465'>pyright-internal/src/analyzer/typeEvaluator.ts:19465:38</a></br>at getTypeForDeclaration <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L19788'>pyright-internal/src/analyzer/typeEvaluator.ts:19788:29</a></br>at getInferredTypeOfDeclaration <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L17848'>pyright-internal/src/analyzer/typeEvaluator.ts:17848:15</a></br>at getAliasedSymbolTypeForName <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L17576'>pyright-internal/src/analyzer/typeEvaluator.ts:17576:25</a></br>at evaluateTypesForImportFromAs <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L18334'>pyright-internal/src/analyzer/typeEvaluator.ts:18334:20</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/common/timing.ts#L40'>pyright-internal/src/common/timing.ts:40:19</a></br>    at evaluateTypesForStatement <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L1480'>pyright-internal/src/analyzer/checker.ts:1480:32</a></br>at Array.forEach (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L1479'>pyright-internal/src/analyzer/checker.ts:1479:25</a></br>at visitImportFrom <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L424'>pyright-internal/src/analyzer/parseTreeWalker.ts:424:28</a></br>at visit <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L933'>pyright-internal/src/analyzer/parseTreeWalker.ts:933:20</a></br>at visitNode <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L915'>pyright-internal/src/analyzer/parseTreeWalker.ts:915:36</a></br>at walk <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L307'>pyright-internal/src/analyzer/checker.ts:307:18</a></br>    at walk <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L924'>pyright-internal/src/analyzer/parseTreeWalker.ts:924:21</a></br>at Array.forEach (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L922'>pyright-internal/src/analyzer/parseTreeWalker.ts:922:14</a></br>at walkMultiple <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L917'>pyright-internal/src/analyzer/parseTreeWalker.ts:917:17</a></br>at walk <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L307'>pyright-internal/src/analyzer/checker.ts:307:18</a></br>at walk <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L2569'>pyright-internal/src/analyzer/checker.ts:2569:17</a></br>at _walkStatementsAndReportUnreachable <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L286'>pyright-internal/src/analyzer/checker.ts:286:13</a></br>    at check <a href='https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/pyright/packages/pyright-internal/src/analyzer/sourceFile.ts#L1033'>pyright-internal/src/analyzer/sourceFile.ts:1033:28</a></br>

**Comment by erictraut** [comment]
I'm 90% sure that I found and fixed the underlying cause of this problem. Since I'm not 100% sure, I added some additional asserts that will fire if I'm incorrect.
