### ISSUE TITLE
Typical error: x is not a known member of module

### ISSUE THREAD

**Issue by CreatorZZY** [microsoft/pyright#518]
![image](https://user-images.githubusercontent.com/38124587/74523299-cdb28800-4f57-11ea-9562-ce73e9e2b054.png)
![image](https://user-images.githubusercontent.com/38124587/74523497-1d914f00-4f58-11ea-95dc-fda31aca318f.png)

**Comment by erictraut** [comment]
I presume that you have enabled the setting `pyright.useLibraryCodeForTypes`? There are limits to the type information that Pyright can extract directly from a library implementation. In this case, the `normal` method in the `random` module isn't implemented in Python but appears to have a native implementation. Pyright therefore doesn't know about it.

What's needed here is a type stub for numpy.
