### ISSUE TITLE
`"abc" is not a known member of module "collections"` error when importing `collections`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#5241]
**Describe the bug**
when importing `collections` with `import collections`, pyright incorrectly says `"abc" is not a known member of module "collections"` 

**To Reproduce**
```py
from collections.abc import Sequence # no error
import collections

foo: collections.abc.Sequence # "abc" is not a known member of module "collections"
bar: Sequence # no error
```
**Expected behavior**
no error

If your code relies on symbols that are imported from a third-party library, include the associated import statements and specify which versions of those libraries you have installed.

**VS Code extension or command-line**
[playground](https://pyright-playground.decorator-factory.su/?gzip=H4sIAG0uf2QC_0srys9VSM7PyUlNLsnMzyvWS0xKVsjMLcgvKlEITi0sTc1LTuWC8pGUcXGl5edboWvUg-tISiyygusHAGFGbXpkAAAA)

**Additional context**
this works in mypy and at runtime

**Comment by erictraut** [comment]
This is intended behavior. Pyright intentionally doesn't model import loader side effects. If you intend to reference the module `collections.abc` in your code, you should import it with an `import collections.abc` statement.

See [this documentation](https://microsoft.github.io/pyright/#/import-statements?id=unsupported-loader-side-effects) for details.
