### ISSUE TITLE
A venvPath per execution environment

### ISSUE THREAD

**Issue by mercury-dr** [microsoft/pyright#525]
**Is your feature request related to a problem? Please describe.**
I am not able to specify more than one venvPath for my codebase.

I have a software project that contains two individual python codebases/environments which share a git repository, and are built into separate docker containers and linked at runtime. 

Currently, I am able to get pyright to recognise my module imports for the first (django) container by using pyrightconfig.json in the following way:
```
{
  "exclude": ["django/app/pip_modules"],
  "venvPath: "django/app"
  "executionEnvironments": [
    {
      "root": "django/app/",
      "venv": "pip_modules",
      "extraPaths": ["django/"]
    }
  ]
}
```

But I am not able to add in the other python container and its venv at the same time, because it uses a distinct venvPath.

**Describe the solution you'd like**
I would like to use pyrightconfig.json in the following way:
```
{
  "exclude": ["django/app/pip_modules", "worker/tasks/pip_modules"],

  "executionEnvironments": [
    {
      "root": "django/app/",
      "venvPath: "django/app/",
      "venv": "pip_modules",
      "extraPaths": ["django/"]
    },
    {
      "root": "worker/tasks/",
      "venvPath: "worker/tasks/",
      "venv": "pip_modules",
      "extraPaths": ["worker/"]
    }
  ]
}

```
or something to that effect.

**Comment by erictraut** [comment]
The venvPath mechanism is defined by the standard Python extension for VS Code. I don't want to deviate from it for this rather esoteric use case.

As a workaround, let me suggest using a single venv path with symbolic links that point to the directories that contain your two environments.

Another potential workaround is to set up a multi-root workspace in VS Code and use separate pyrightconfig.json files for each root.

**Comment by mercury-dr** [comment]
The first workaround should do the trick, thank you Eric.
