### ISSUE TITLE
Consistent syntax for ignoring per line and ignoring per file

### ISSUE THREAD

**Issue by wolph** [microsoft/pyright#5266]
**Is your feature request related to a problem? Please describe.**

I'm constantly having trouble remembering which syntax goes where when ignoring a specific line or file with pyright.

To illustrate, I mean this per-file syntax:
```
# pyright: reportPrivateUsage = false
```

Versus this per-line syntax:
```
wrapper._wrapped = True  # pyright: ignore[reportGeneralTypeIssues]
```

It would be much more obvious if both were using the `ignore[...]` syntax :)

**Describe the solution you'd like**
Allow for `# pyright: ignore[reportPrivateUsage]` to work for entire files as well

**Comment by erictraut** [comment]
The per-file syntax is designed to support severity levels like `# pyright: reportPrivateUsage=warning`. It also accepts `false` (which is the same as `none`) and `true` (which is the same as `error`).

There's another good reason why the syntax is different between the two: we don't want users to confuse the meaning of a per-file versus per-line comment. In fact, if you attempt to use the per-file syntax at the end of a non-empty line, pyright will emit an error.

**Comment by jorenham** [comment]
@erictraut What about something like:

```
# pyright: disable[reportPrivateUsage]
```

This makes the syntax consistent, while maintaining distinguishability.
