### ISSUE TITLE
Crash with OOM on hydra-zen

### ISSUE THREAD

**Issue by hauntsaninja** [microsoft/pyright#5268]
pyright crashes with `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` when run on https://github.com/mit-ll-responsible-ai/hydra-zen.

This is a regression somewhere in between 1.1.307 and 1.1.310.

**Comment by erictraut** [comment]
Thanks for reporting. This is a duplicate of https://github.com/microsoft/pyright/issues/5163.
