### ISSUE TITLE
Feature: either-or type narrowing.

### ISSUE THREAD

**Issue by tlambert03** [microsoft/pyright#527]
Curious what you think of this case:

```python
def a_or_b(a: Optional[int] = None, b: Optional[int] = None) -> int:
    if (a is None) and (b is None):
        raise ValueError("either a or b must provided.")
    # we now know that one of a or b MUST be non-None

    return a if a is not None else b  # <-- Error: 'None' cannot be assigned to 'int'
```
<img width="529" alt="Screen Shot 2020-02-17 at 3 29 49 PM" src="https://user-images.githubusercontent.com/1609449/74684645-6cc6c200-519a-11ea-8266-67541d846320.png">

**Desired outcome**
type narrowing.  (not sure whether it's possible!)

**Additional context**
tested on pyright 1.1.22

**Comment by tlambert03** [comment]
additional note... I recognize this syntax would be valid.  Just curious about the above case:
```python
def a_or_b(a: Optional[int] = None, b: Optional[int] = None) -> int:
    if a is not None:
        return a
    elif b is not None:
        return b
    raise ValueError("either a or b must provided.")
```

**Comment by erictraut** [comment]
This is beyond the capabilities of Pyright (or any type checker in any language that I'm familiar with). Type narrowing works on individual symbols, not collections of symbols. The type of symbol `a` cannot be narrowed, nor can the type of symbol `b`.

You can rewrite the function in a way that works:

```
if a is not None:
    return a
if b is not None:
   return b
raise ValueError("either a or b must provided.")
```

You can also add asserts to help the type checker in cases where it cannot otherwise make inferences.
```
if a is not None:
    return a
assert b is not None # Because of check at start of function
return b
```

**Comment by tlambert03** [comment]
ok, that works for me!  still learning about the capabilities of type checkers.  (but I must say, I am _loving_ how much it improves my code structure! so thank you!)

Thanks for the prompt reply and explanation!

**Comment by erictraut** [comment]
BTW, if your initial statement used an `or` operation rather than an `and`, the types of both `a` and `b` would have been narrowed.

Glad to hear you're finding it useful!

**Comment by tlambert03** [comment]
oh interesting!  thanks
