### ISSUE TITLE
How about parsing inspect.Signature parameters to impose constraints on signature.bind?

### ISSUE THREAD

**Issue by spacether** [microsoft/pyright#5286]
If you have a question about a behavior that you’re seeing in Pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**
How about parsing inspect.Signature parameters to impose constraints on signature.bind?

**Describe the solution you'd like**
I would like vscode to show problems if incorrect arguments are passed into signature.bind
Signatures are immutable so this should be possible. 
Doing this would be very helpful because it could allow an unpacked dict to be used as an input. The output could be put into a typeddict. 

**Additional context**
I am interested in ingesting json schema object (dict) payloads and imposing type constraints. 
A couple of difficulties are that additional properties are allowed to have specific types which is similar to python kwargs accumulation
Also keys can have invalid python variable names

The invalid variable names could be addressed by making a new Parameter class to use with signature which allows invalid name keys
The additionalProperties could be accumulated into a kwargs property 
But the ide error detection would need to be powered by my suggestion above

**Comment by erictraut** [comment]
In general, pyright has no specialized knowledge of individual methods in stdlib. It works based on type information that comes from typeshed type stubs. The `Signature.bind` method is currently defined as `def bind(self, *args: Any, **kwargs: Any) -> BoundArguments: ...`. What you're proposing here would require significant special-case logic and knowledge for one particular method (or a family of related methods). This is not something we normally do in pyright, but it's not entirely without precedent. I added special knowledge of `functools.partial` after receiving requests from several dozen pyright users.

This is the first time I've received a request for supporting `Signature.bind`. In fact, I've never encountered (or even heard of) it before. I presume that it's quite specialized. I'm interested in understanding your use case more.

Another thing that I'll point out is that pyright is a standards-based type checker, so we generally don't add type checking functionality unless it is standardized and supported by other type checkers like mypy and pyre. I don't know if the functionality you have in mind is already specified in sufficient detail that other type checkers could also implement the same functionality. If not, it would require a formal specification in the form of a PEP with the associated review and ratification process.

I'm going to close this enhancement request now, but it's something I'd be willing to revisit in the future if there's sufficient signal from other pyright users that it's something they'd like to see (e.g. in the form of upvotes).

If your use case is mainly about providing types for `**kwargs` parameters, perhaps the recently-accepted [PEP 692](https://peps.python.org/pep-0692/) would meet your needs. You can use the functional version of `TypedDict` to specify keys that are not allowed as identifiers. Pyright already has full support for PEP 692 including type checking and signature help.
