### ISSUE TITLE
Duplicate error messages for **kwargs recent strictness

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#5287]
**Describe the bug**
```python
class Foo:
  def __init__(self, x: int = 1, y: str = "", z: list[int] | None = None):
    ...

kwargs: dict[str, object] = {}
Foo(**kwargs)
```

The last line produces 3 errors all about kwargs not matching.

**Expected behavior**
1 error message instead of 3. For this example it's not that many, but I've seen lines hit dozens of errors for single **kwargs for functions with long amount default arguments (like matplotlib's functions). My current record is ~50 errors for 1 **kwargs line.

**VS Code extension or command-line**
pyright 1.1.314

**Additional context**
I understand recent **kwargs strictness. It did give me >100+ type errors when I upgraded pyright versions mostly duplicates on same line and haven't found any real bugs from it. It is a valid type unsafety but feels a bit too strict for kwargs usage. I think ignoring duplicate error messages it'd be more friendly ~10 errors. 

I'll note though this is consistent with mypy. It also produces multiple error messages for same kwargs unpack incompatibility.

**Comment by erictraut** [comment]
The current behavior is as designed here. I don't consider this a bug.
