### ISSUE TITLE
Unexpected unbound outside a "assumed" for-loop

### ISSUE THREAD

**Issue by GreyElaina** [microsoft/pyright#5292]
**Describe the bug**
Even when a list is judged as non-empty by using if not x_list in code, Pyright still infers the variable declared in the subsequent for iteration on it as unbounded.

**To Reproduce**
explained in just one snippet.

**Expected behavior**
the variable declared in the subsequent is inferred as bounded.

**Code or Screenshots**
```py
a: list = [1]
if not a:
    raise KeyError
for i in a:
    x = 1
i  # unbound.
x  # unbound.
```

**VS Code extension or command-line**
Pylance, `v2023.5.30`.

**Additional context**

**Comment by yanyongyu** [comment]
It seems pyright can not detect if var is a list with no element.
