### ISSUE TITLE
Type Check Failing for List[TypedDict]

### ISSUE THREAD

**Issue by grant-zietsman** [microsoft/pyright#530]
**Describe the bug**
Pyright seems to be losing type annotations when TypedDict in Lists.

**To Reproduce**
See screenshot below.

**Expected behavior**
I would have expected no errors/warnings from Pyright.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/7155647/74751457-f4cdca00-5275-11ea-8512-9bcead9dac16.png)

**VS Code extension or command-line**
VS Code 1.42.0
Pyright 1.1.22

**Additional context**
Might be related to https://github.com/microsoft/pyright/issues/114.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next version of Pyright.

**Comment by erictraut** [comment]
This is now fixed in 1.1.24, which I just published.
