### ISSUE TITLE
User-generated Generic Type Aliases not supported

### ISSUE THREAD

**Issue by dmlyubim** [microsoft/pyright#531]
nested generic aliasing (and some other forms of generic aliasing) generate errors

**To Reproduce**

> from typing import TypeVar, Union, Optional
> S = TypeVar('S')
> Response = Optional[Union[S, int]]
> 
> def response(query: str) -> Response[str]:
>     return 0
> 

generates error report 

>  8:29 - error: Object of type 'Optional[Union[Unknown, int]]' cannot be subscripted
>   8:29 - error: Object of type 'int' does not define '__getitem__'
> 

**Expected behavior**
Response[S] is a valid generics 

**Additional context**

I saw also other instances when pyright cannot recognize generic types even in a single-nested generic alasing context, e.g. 

Alias = Optional[T, int]

class C(Generic[T2]):

   def f() -> Alias[T2]: ...

or even simply 

class C(Alias[T2]): 
....

in many such or similar cases pyright failed to recognize Alias[T] as generic use with varying error messages.

**Comment by erictraut** [comment]
I think you're confused about the way generics work in Python.

The expression `Response[str]` implies that `Response` is a generic class — a class that is defined with an explicit or implicit Generic subclass. But you have defined `Response` as a union of `S`, `int` and `None`, none of which are valid generic classes. So Pyright is doing the right thing by telling you that `Response[str]` is an error.

What is your intent here? Do you want the response method to return a union of `str`, `int` and `None`?

**Comment by dmlyubim** [comment]
Thasks -- 

The example is quoted almost verbatim from python generic manual. https://docs.python.org/3/library/typing.html

what they have their is parameter reduction for the purpose of alizsing 
> from typing import TypeVar, Iterable, Tuple, Union
> S = TypeVar('S')
> Response = Union[Iterable[S], int]

the caveat is that in other languages it is usually accompanied by explicit parameter declaration, e.g. 

> type NewType[T1, T2] = OldType[T1. T2, int, str]

also along nesting such as 

> type NewType[T1] = Type1[Type2[T1]]

Since python doesn't have new type explicit parameter declaration, and all these rules are pretty much moot at runtime and do not preclude translation, it is hard for me to tell how far this alising is meant to extend in python (parameter nesting/ multiple parameters supported?) but example as given is almost a direct quote of the manual (it only adds nesting).

I made a typo in additional context, it is meant to read 
> Alias = Union[T, int]

which does not even have nesting, and inheriting type parameter through inheritacne is absolutely legal (also found in generic examples).

**Comment by erictraut** [comment]
I stand corrected. There's no mention in any of the type-related PEPs about user-defined generic type aliases, and I've never seen any example before. But the documentation you cited is pretty clear that they are supported. 

Pyright currently contains no support for user-defined generic type aliases, which is why you're receiving these errors. I'll work on adding this support. In the meantime, you'll need to find a workaround that doesn't involve a type alias.

**Comment by erictraut** [comment]
I've implemented support for user-defined generic type aliases. This will be in the next version of Pyright.

**Comment by erictraut** [comment]
This is now implemented in 1.1.24, which I just published.
