### ISSUE TITLE
Release 1.1.250 may be incorrectly tagged

### ISSUE THREAD

**Issue by liblit** [microsoft/pyright#5318]
Tags [1.1.250](https://github.com/microsoft/pyright/releases/tag/1.1.250) and [1.1.251](https://github.com/microsoft/pyright/releases/tag/1.1.251) are both associated with commit b46034527e5492eb6d0561b443b7de82cd063dc5, which is described as "Published 1.1.251". Should tag 1.1.250 instead be associated with commit 8a9b23bff380b75be1541bccb4f61fa0124b70fd, which is described as "Published 1.1.250"?

**Comment by erictraut** [comment]
You're asking about a github tag from 64 versions ago? Why do you care?

**Comment by liblit** [comment]
>You're asking about a github tag from 64 versions ago?

Indeed I am!

> Why do you care?

I am upgrading a piece of software that got left behind using an old Pyright release. Rather than leap straight to the latest release, I am proceeding cautiously: upgrading one Pyright release at a time, with testing in between. I happened to notice that 1.1.250 and 1.1.251 were tagged to the same release.

Obviously this is not an _urgent_ bug. But since I'd already noticed it anyway, I thought you'd rather know than not know. Conversely, if this was intentional, perhaps you would tell me why, which might cause me to revise my update strategy in some way.

**Comment by erictraut** [comment]
That was unintentional. These tags are used primarily for our internal build process. If you want to bisect changes, I recommend using the officially published versions in the npmjs registry rather than using git tags and building from scratch.
