### ISSUE TITLE
`TypeAliasType` seems to have the semantics of `TypeAlias` – can it be more like `type X = Y`?

### ISSUE THREAD

**Issue by tmke8** [microsoft/pyright#5341]
The following works with the new `type X = Y` syntax:

```python
from typing import assert_type

class C[T]:
    type L = list[T]

    vals: L

    def f(self) -> L:
        return self.vals


def f(c: C[int]) -> None:
    assert_type(c.f(), list[int])
```

but it doesn't work with `TypeAliasType`:
```python
from typing import Generic, TypeAliasType, TypeVar, assert_type

T = TypeVar("T")

class C(Generic[T]):
    L = TypeAliasType("L", list[T])  # error: Generic type alias within class cannot use bound type variables T

    vals: L  # error: Expected type arguments for generic type alias "L"

    def f(self) -> L:  # error: Expected type arguments for generic type alias "L"
        return self.vals


def f(c: C[int]) -> None:
    assert_type(c.f(), list[int])
```
I'm guessing the reason for the error is that if you do the same with `TypeAlias`, then at runtime, `L` will be generic because we specialized `list` with a `TypeVar`, but this isn't a problem with `TypeAliasType`, I think, so the above code should be safe?

**Comment by erictraut** [comment]
This is included in pyright 1.1.315, which I just published. It will also be included in this week's insiders release of pylance.
