### ISSUE TITLE
Option to accept file list from the standard input

### ISSUE THREAD

**Issue by vors** [microsoft/pyright#5342]
**Is your feature request related to a problem? Please describe.**

We have a relatively large monorepo. I'd like to implement a functionality that quickly runs type checking only on MODIFIED (compare to the merge-base with mainline branch) files. This is exactly the same approach that we take with linter. It can be easily done now, however when we pass the list of files to `pyright` through the command line we quickly run into the command line buffer limit of files. In order to mitigate this problem the proposal is to allow passing the list of files though the stdin.

**Describe the solution you'd like**
One common way to do it is to allow `pyright -` to mean "read filepaths from command line".

**Additional context**
N/A

**Comment by erictraut** [comment]
I recommend against type checking only modified source files. Modifications to one file can affect type checking of any files that depend upon it (i.e. import directly or transitively from it). Pyright is designed to be fast enough that you can run it on a large code base without needing to resort to workarounds like this. Out of curiosity, how big is your source base, and how long does it take to run pyright fully?

**Comment by erictraut** [comment]
I've added the requested enhancement because I think it may be useful in some cases, but as I mentioned above, I recommend against using the approach you outlined above.

**Comment by erictraut** [comment]
This is included in pyright 1.1.315, which I just published.

**Comment by erictraut** [comment]
Ah darn. After manually testing the new feature, I added a small change that included a bug. You'll need to wait for the next pyright release for the feature.

**Comment by kyle-query** [comment]
Confirmed this is working now. However it would be easier to use if pyright would split on line breaks rather than spaces, because commands like `ls` or `find` typically print one file per line.
