### ISSUE TITLE
Nested decorator ParamSpec are not typechecked

### ISSUE THREAD

**Issue by nathanpage-credo** [microsoft/pyright#5349]
**Describe the bug**
It looks like when using a nested decorator with a `ParamSpec`, the function definition is not properly typechecked.

**To Reproduce**
Steps to reproduce the behavior.

Here is my code snippet
```python
from typing import Callable
import functools

from typing_extensions import ParamSpec


P = ParamSpec("P")


def foo() -> Callable[[Callable[P, bool]], Callable[P, int]]:
    def foo_wrap(check: Callable[P, bool]) -> Callable[P, int]:
        @functools.wraps(check)
        def check_loop(*args: P.args, **kwargs: P.kwargs) -> int:
            finished = check(*args, **kwargs)
            return 1 if finished else 2

        return check_loop

    return foo_wrap


@foo()
def check_me(a: int, *, b: int) -> bool:
    return bool(a + b)


a = check_me()
```

**Expected behavior**

`check_me()` should return an error saying that `a` and `b` arguments are missing. Mypy correctly reports this as an error.

**Code or Screenshots**

**VS Code extension or command-line**

Vs Code extension (Pylance v2023.6.20)

**Additional context**

**Comment by erictraut** [comment]
This was fixed two weeks ago in pyright. The fix was in last week's "insiders release" of pylance. It will be included in this week's production release.
