### ISSUE TITLE
CLI: Ability to force color output 

### ISSUE THREAD

**Issue by Tomaz-Vieira** [microsoft/pyright#5357]
**Is your feature request related to a problem? Please describe.**
I sometimes like to pipe the output of `pyright` to other tools (e.g.  `less -R`), but this always causes pyright to omit colors in its output.

**Describe the solution you'd like**
A way to force the output of colors, even if not writing to a tty. Maybe something like the `--color=always` flag that `ls` takes

**Comment by erictraut** [comment]
Please refer to this recent [discussion topic](https://github.com/microsoft/pyright/discussions/5319).
