### ISSUE TITLE
[Feature request] reportUntypedFunction setting

### ISSUE THREAD

**Issue by vors** [microsoft/pyright#5370]
**Is your feature request related to a problem? Please describe.**
I'd like to enforce the rule that all newly written code should have type annotations in the function signatures in our monorepo.
Currently I cannot leverage pyright for this job: there are settings like `reportUntypedFunctionDecorator` which are great, but I need a simpler one -- just warning on an untyped function definition. Then I can integrate it into the linter in a suitable way. Without it I'm resorting to doing this outside-of-pyright-ecosystem which is prone to conflicts with our main type checker.

**Describe the solution you'd like**
new `reportUntypedFunction` setting that would enable emitting a diagnostic on untyped function signature.

**Additional context**
MyPy has this feature https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-every-function-has-an-annotation-no-untyped-def
I'm currently using mypy for it, but it has it's own downsides:
1. More complexity then needed.
2. Inconsistent experience, because 2 type checkers are used.
3. MyPy has perf issues even on a single file analyse -- make our linter unresponsive https://github.com/python/mypy/issues/14636#issuecomment-1592220032

I could in theory implement this myself outside of any type checker ecosystem, but the amount of edge cases makes this non-trivial. The type-checker seems like a reasonable place for that type of diagnostics.

**Comment by erictraut** [comment]
Pyright supports an option called `reportUnknownParameterType`. I think that's what you're looking for.

There is no way to enforce return type annotations because pyright can typically infer return types, so adding explicit annotations provides no value and represents unnecessary additional work.

**Comment by vors** [comment]
For future readers I ended up leveraging https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
