### ISSUE TITLE
[Bug] Pyright ignores additional type hint 

### ISSUE THREAD

**Issue by qmmp123** [microsoft/pyright#5385]
**Describe the bug**
I have function that gets ```arg``` with type hint of BaseClass. In some cases I want to specify that ```arg``` has another type

**To Reproduce**
See the code

**Expected behavior**
I think pyright can change type of ```arg``` for block of code. I mean while cursor in condition after type hint pyright should return type `Bar` for `obj` instead of `Foo`. Also it will be nice if pyright can use not only type hint but functions like `isinstance` to infer type 

**Code or Screenshots**

```python
class Foo:
    type_: str
    pass

class Bar(Foo):
    pass


def function(obj: Foo):
    if obj.type_ == "Bar":
        obj: Bar  # here i get type Bar
        obj  # here i get type Foo but should be Bar
   obj # here it should be again Foo
   if isinstance(obj, Bar):
       obj # here i get type Foo but it will be nice if pyright will infer type Bar
```

**VS Code extension or command-line**
Pyright == 1.1.316

**Comment by erictraut** [comment]
Pyright is working correctly here. This is not a bug.

You have declared the type of `obj` to be `Foo`, but then you've later declared the same symbol to be a different type `Bar`. A symbol can have only one type declaration. For details, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts).

Pyright applies type narrowing for type guards such as `isinstance`. For details, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced).
