### ISSUE TITLE
Improve type interference if return type is set by argument

### ISSUE THREAD

**Issue by karolzlot** [microsoft/pyright#5386]
If you have a question about a behavior that you’re seeing in Pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**

Currently if return type is set by argument, then type interference is able to correctly detect return argument, but not in all cases.

It works correctly with `get_value1()`, but not with `get_value2()`.

```python

from typing import cast, Optional, Any, Type


def get_from_db(key_name: str) -> Any:
    """Get a config value from the database"""
    value = ...
    return value


def get_value1(key_name: str, type_: Type):
    # get value and check its type

    value = get_from_db(key_name)

    assert isinstance(value, type_)
    return cast(type_, value)


a1 = get_value1("key1", str)
a2 = get_value1("key2", int)

# above inlay hints as desired


def get_value2(key_name: str, type_: Optional[Type] = None):
    # get value and check its type if type is given

    value = get_from_db(key_name)

    if type_ is None:
        return value
    else:
        assert isinstance(value, type_)
        return cast(type_, value)


b1 = get_value2("key1", str)
b2 = get_value2("key2", int)
b3 = get_value2("key3")

# desired inlay hints:
# b1: str
# b2: int
# b3: Any

```

**Describe the solution you'd like**
I would like pyright to more precisely detect types in `get_value2()`.

**Additional context**
![image](https://github.com/microsoft/pyright/assets/11590960/452f2ee1-b2f1-410b-96eb-6d019dbafe80)

**Comment by erictraut** [comment]
Return type inference for a function that has annotated parameters is based on the provided annotations. It sounds like you are looking for the return type to be re-analyzed for every call. That would be prohibitively expensive, so it's not something we'd be interested in implementing. The Python type system has other mechanisms to handle this efficiently. You can use generics and overloads to correctly type such a function.

**Comment by karolzlot** [comment]
@erictraut 


I found solution:

```python

def get_value2(key_name: str, type_: Type = Any):
    # get value and check its type if type is given

    value = get_from_db(key_name)

    assert isinstance(value, type_)
    return cast(type_, value)


def utility_cast(type_: Type, value):
    assert isinstance(value, type_)
    return cast(type_, value)


b1 = get_value2("key1", str)
b2 = get_value2("key2", int)
b3 = get_value2("key3")

```

-----------

Thank you for suggestion of using TypeVar and overload. From what I tried it seems however that it isn't possible to do this, as Literal isn't compatible with Type.


```python

from typing import cast, Optional, Any, Type, overload, Literal, TypeVar


T = TypeVar("T", Type)

@overload
def get_value2(key_name: str) -> Any: ...

@overload
def get_value2(key_name: str, type_: Literal[T] = ...) -> T: ...

def get_value2(key_name: str, type_: Type = None):
    # get value and check its type if type is given

    value = get_from_db(key_name)

    if type_ is None:
        return value
    else:
        assert isinstance(type_, Type)
        assert isinstance(value, type_)
        aaa =utility_cast(type_, value)
        return aaa


def utility_cast(type_: Type, value):
    assert isinstance(value, type_)
    return cast(type_, value)



b1 = get_value2("key1", str)
b2 = get_value2("key2", int)
b3 = get_value2("key3")

```



![image](https://github.com/microsoft/pyright/assets/11590960/4426ef2e-ab0b-49da-86cf-507aeabeb766)

![image](https://github.com/microsoft/pyright/assets/11590960/df050239-4d2d-493b-ace9-30e648aa24b9)

**Comment by karolzlot** [comment]
I also started discussion about this: https://github.com/microsoft/pyright/discussions/5390
