### ISSUE TITLE
Non helpful error when using `Final` on an attribute

### ISSUE THREAD

**Issue by adriangb** [microsoft/pyright#5387]
```python
from dataclasses import dataclass
from typing import Final

@dataclass
class Foo:
    x: Final[int] = 1

m = Foo()
m.x = 2
"""
pyright: Member "x" cannot be assigned through a class instance because it is a ClassVar (reportGeneralTypeIssues)
mypy: Cannot assign to final attribute "x"  [misc]
"""
```

I don’t know that I’d call this a bug but I do think the mypy error is a lot more helpful.

**Comment by erictraut** [comment]
This isn't a bug. The PEP that introduced `Final` indicates that a `Final` variable defined at the class level is a `ClassVar`. That means it cannot be reassigned through an instance.

**Comment by adriangb** [comment]
I don't disagree with you, I'm not reporting this as a bug, I'm reporting it as a non-helpful error message for someone who hasn't read the PEP. The MyPy error does a much better job of explaining the issue.
