### ISSUE TITLE
Feature request: Add ability to import from `cwd`.

### ISSUE THREAD

**Issue by hacker-DOM** [microsoft/pyright#5407]
Hi there,

I've used Pyright for years happily in Vs Code. I even made a tool that used the fact that Pyright can import from `cwd`. (In particular, the tool creates a directory called `pytypes`, and then in other files I can do `import pytypes.boo.bla` and it just works)

Recently I have transitioned to Neovim. I took Pyright with me (Lsp), but I am having trouble getting the same behavior. When I put `python.analysis.extraPaths` to contain `path/to/my/dir`, it works. However, it doesn't work by default, nor if I put `.` in extrapaths. On the flipside, a pyproject.toml with `tool.pyright.include = ["."]` does work.

I have two options:
(1) Put the full path of every project in my Lsp settings
(2) Create a small pyproject.toml before each project

Is there a way to automatize this to work automatically as it does in Vs Code? Thank you!

**Comment by erictraut** [comment]
Pyright doesn't resolve imports from cwd. It resolves imports from the project root directory (plus any additional directories specified in "extraPaths"). The project root directory is specified by a language client like VS Code.

If you run the command-line version of pyright, it attempts to find your project root directory by starting at cwd and lookup up the directory hierarchy until it finds a `pyrightconfig.json` or `pyproject.toml` file. If it doesn't find a config file, then it falls back to the current working directory.

In VS Code, the project directory is always well defined, and it's passed to pyright via the language server protocol. Other language clients should do the same. If you want pyright to use additional directories for import resolution, you can specify them using "extraPaths".

**Comment by hacker-DOM** [comment]
Thank you for your explanation sir! Thanks to the explanation I discovered that Neovim's Pyright config looks for a set of specific files https://github.com/neovim/nvim-lspconfig/blob/0011c435282f043a018e23393cae06ed926c3f4a/lua/lspconfig/server_configurations/pyright.lua#L3-L10. When I change that to default to `cwd()` when it doesn't find any, it works! 🙂

**Comment by anthony-S93** [comment]
> it works!

No. This will only break pyright's single-file support in neovim.
