### ISSUE TITLE
Generic descriptor parametrized by synthesized generic `self` type results in type errors in subclasses

### ISSUE THREAD

**Issue by shiftinv** [microsoft/pyright#5434]
**Describe the bug**
As far as I can tell, this is very similar to https://github.com/microsoft/pyright/issues/2346, and started happening in 1.1.219.

Taking this simplified `@property` replica as an example:
```py
from typing import Callable, Generic, Optional, Type, TypeVar, Union
from typing_extensions import Self, reveal_type

T_contra = TypeVar("T_contra", contravariant=True)
T_co = TypeVar("T_co", covariant=True)

class customproperty(Generic[T_contra, T_co]):
    def __init__(self, f: Callable[[T_contra], T_co]) -> None:
        self.f = f

    # overloads left out for brevity and to better debug type inference
    def __get__(self, instance: Optional[T_contra], owner: Type[T_contra]) -> Union[Self, T_co]:
        if instance is None:
            return self
        return self.f(instance)
```

Using this to decorate a method in a generic class produces an error when trying to access it on a subclass instance:
```py
T2 = TypeVar("T2")

class A(Generic[T2]):
    def __init__(self, data: T2) -> None:
        self.data: T2 = data

    @customproperty
    def value(self):
        return 42

    def func(self) -> None:
        reveal_type(self.value)  # customproperty[Self@A[T2@A], int] | int


class B(A[T2]):
    def func(self) -> None:
        reveal_type(self.value)  # error: Cannot access member "value" for type "B[T2@B]"

reveal_type(A.value)  # customproperty[Self@A[T2@A], int] | int
reveal_type(B.value)  # customproperty[B[T2@B], int] | int
```
The error message doesn't provide details as to why it cannot access the `value` member.

The type of `B.value` (i.e. at the class level) is closer to what I'd expect, it appears that pyright infers the type of `self.value` in `B` differently.

**Expected behavior**
In <1.1.219, `self.value` in `B` is of type `customproperty[Self@A[T2@B], int] | int` and does not throw an error.
Not sure if `Self@A` or `Self@B` would be more accurate there.

**VS Code extension or command-line**
cli, 1.1.316

**Additional context**
There are a few solutions that seem to fix this, but none of them feel quite right:
- Explicitly annotate the `self` type as `A[T2]` in the decorated method: Proposed in the linked issue, but arguably more of a workaround - would have to be specified for every one of these properties.
- Remove the annotation of `owner` in the descriptor: Not sure why this works - it might lead towards the underlying issue here? I may be missing something, though. It would be fine for our use-case, since we don't care about the `owner` type.
- Make `T2` contravariant: Not correct given the intended usage of `.data`.

**Comment by erictraut** [comment]
The problem is with the `owner` parameter annotation in the `__get__` method. You've defined it as `type[T_contra]`. When the decorator is applied to `A.value`, the type captured by `T_contra` is `Self@A`. When the `value` attribute is accessed from within the `B` class, the value passed to the `owner` parameter is of type `type[Self@B]`. Since you've used a contravariant TypeVar, this isn't allowed because `type[Self@B]` is not a supertype of `type[Self@A]`; it's a subtype.

In most descriptor classes that I've seen (including those defined in typeshed stubs), the `owner` class is annotated as `type` or `type[Any]`. If I make that change to your code sample, it type checks without error.

**Comment by shiftinv** [comment]
Thanks for the explanation, that makes sense. For our purposes `owner: type[Any]` is perfectly fine, then - I wasn't certain if this is a typing quirk that I missed in the PEPs, or something else.

What led to the assumption that the `self.value` access in `B` should work is that `B.value` is inferred as `customproperty[B[T2@B], int] | int`, in which case the access would be fine even with contravariance.
Using the proposed `owner: Type[Any]`, the type of `self.value` is different compared to `B.value`:
```py
class B(A[T2]):
    def func(self) -> None:
        reveal_type(self.value)  # customproperty[Self@A[T2@A], int] | int

reveal_type(B.value)  # customproperty[B[T2@B], int] | int
```

I suppose my confusion mainly stems from the fact that the decorator's type capture/binding is seemingly re-evaluated for `B` in the case of `B.value`, whereas `self.value` continues to use the binding from `A` (excuse any incorrect terminology, it's a bit late :sweat_smile:).
