### ISSUE TITLE
Conflict with nptyping

### ISSUE THREAD

**Issue by KristofHorvath** [microsoft/pyright#547]
**Describe the bug**
With nptyping (https://github.com/ramonhagenaars/nptyping) type hints can specify the number of rows and columns, like Array[int, 3, 2] which means a numpy array containing integers and shaped 3*2. Pyright shows a 'Numeric literal not allowed in type annotation' error.

**To Reproduce**
from nptyping import Array
def fun(x: Array[int, 3, 2]):
    pass

**Expected behavior**
Numeric literals have special meaning here and should handle.

**Version information**
Python: 3.7.2
Pyright VSCode extension: 1.1.25

**Comment by erictraut** [comment]
nptyping uses typing semantics that are not defined by the Python standard. There is no way in the standard to specify array or tensor sizes using type arguments. 

Pyright's implementation conforms to the Python spec and doesn't implement any non-standard extensions.

nptyping appears to provide runtime type checking, but it won't work for static type checkers like Pyright.

**Comment by KristofHorvath** [comment]
Thank you for the explanation. What type annotation would you recommend for numpy arrays (at least without dimensions)?

**Comment by bfelbo** [comment]
I would love to know as well. It would be amazing if pyright could support nptyping without dimensions!
