### ISSUE TITLE
Heuristics tuple type inference for list of tuple

### ISSUE THREAD

**Issue by PabloLION** [microsoft/pyright#5477]
**Is your feature request related to a problem? Please describe.**
List with tuples as its elements is heavily used in searching algorithms like Dijkstra with heap, A* with heap. Yet the current type annotation system requires us to specify the type of the list.
Before [pylance 2023.6.31](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023631-21-june-2023-prerelease) and [pyright 1.1.315](https://github.com/microsoft/pyright/releases/tag/1.1.315) there was no such requirement

- behavior of pylance 2023.6.30
  ![pylance 2023.6.30](https://github.com/microsoft/pyright/assets/36828324/6dbe1068-80ab-4876-bf2e-d6eebbcfe5cf)
- behavior of pylance 2023.6.31 to 2023.7.10
  ![pylance 2023.6.31](https://github.com/microsoft/pyright/assets/36828324/47f61e65-04d3-4104-9838-9ac0e634ad93)
  (2023.7.10 uses my preferred locale language and I don't know where to change it)
<details><summary>code in the screenshot</summary>

> Code was for https://leetcode.com/problems/network-delay-time/description/

```py
class Solution:
    def networkDelayTime(self, times: list[list[int]], n: int, k: int) -> int:
        # route: {from: [(to, time), ...]}
        route: dict[int, list[tuple[int, int]]] = defaultdict(list)
        for u, v, t in times:
            route[u].append((v, t))

        pq = [(0, k)]  # priority queue, [(time, from), ...]
        res, visited = 0, set()
        while len(visited) < n and pq:
            t, u = heappop(pq)
            if u in visited:
                continue
            visited.add(u)
            res = max(res, t)
            for v, nt in route[u]:
                heappush(pq, (t + nt, v))

        return res if len(visited) == n else -1
```

</details>

**Describe the solution you'd like**

I can see that in pylance 2023.6.30, although no error was reported, it recognizes `(variable) pq: list[tuple[Literal[0], int]]`
and same in pylance 2023.7.10. But in and 2023.7.10 after removing type annotation `route: dict[int, list[tuple[int, int]]]` it becomes `(variable) pq: list[Unknown]`

The best solution for me is to add some heuristics for tuple expressions like [list expressions](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#list-expressions), for the [Bidirectional Type Inference](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#bidirectional-type-inference-expected-types).

To be specific,
On a tuple `t=(0, int_var)`, we can infer `tuple[Literal[0],int]`(preferred, as it is right now) or `tuple[int, int]` (for context).
Similarly, a tuple of `t=("a", str_var)` with `tuple[Literal["a"],str]` or `tuple[str, str]`.
After this, pylance can infer the correct type of these tuples when they are in a list via Bidirectional Type Inference.

**Additional context**
None

**Comment by erictraut** [comment]
Can you provide a minimal, self-contained example that repros the problem? It's difficult to debug an issue from partial screen shots.

**Comment by erictraut** [comment]
Please refer to pyright documentation for the default inference rules it uses for lists and tuples. You can override the default inference rules using an explicit type annotation, in which case bidirectional type inference will be used.

We're unlikely to change the default inference rules because this would likely create a bunch of churn (creating new false positives) in code bases that use pyright.

I'm going to close this issue, but feel free to respond to my question above and/or correct my understanding of what you're proposing if I got it wrong.
