### ISSUE TITLE
Adding support for infinite generators

### ISSUE THREAD

**Issue by amirsoroush** [microsoft/pyright#5531]
Here is my simplified snippet:

```python
from collections.abc import Generator

def probing_sequnce(key: str) -> Generator[int, None, None]:
    idx = hash(key) % 10
    i = 0
    while True:
        yield idx + i
        i += 1

def insert(item: str) -> int:
    for idx in probing_sequnce(item):
        if slots[idx] is None:
            slots[idx] = item

slots: list[str | None] = [None] * 10
insert("key1")
```
Basically I was implementing a hashmap and I was hundred percent sure that `insert` function would never reaches outside of the `for-loop`. That's because `probing_sequnce` is an infinite generator so it eventually finds an empty slot.

However I get this error message from Pylance:

```none
Function with declared type of "int" must return value on all code paths
  Type "None" cannot be assigned to type "int" Pylance[reportGeneralTypeIssues]
```

As a workaround I used this one instead:

```python
def insert(item: str) -> int:
    probing_sequnce_gen = probing_sequnce(item)
    while True:
        idx = next(probing_sequnce_gen)
        if slots[idx] is None:
            slots[idx] = item
```
The problem solved but I thought it would be nice if I could tell Pylance that my generator is infinite by changing:

```python
Generator[int, None, None]
```
to
```python
from typing import NoReturn

Generator[int, None, NoReturn]
```
Using for-loop looked a bit cleaner to me.

Thanks.

**Comment by amirsoroush** [comment]
I should mention that `Mypy` also complains about it but in an ambiguous way:

```none
Missing return statement  [return]mypy(error)
```
Pylance correctly stats that there is a path which ends in `None` and it's in compatible with my return type.

**Comment by erictraut** [comment]
Such a feature would be technically very difficult to implement. Type evaluation depends on the code flow graph for a function. This is a case where the code flow graph (in particular, an edge from the top of the `for` loop to the code that comes after) would be conditioned on the return type of the iterator expression in the `for` loop. There are a few special cases where I've added support for "conditional" code flow edges based on type analysis (e.g. for context managers that swallow exceptions based on the return type of the `__enter__` method), but this added significant complexity to the type evaluator and had a measurable impact on type evaluation performance. I don't think that "infinite generators" are common enough to merit something like this. I'm willing to revisit this in the future if there's sufficient interest from other pyright users, but for now I'm going to close this.

Here are a couple of straightforward workarounds.

1. Simply delete the return type annotation from `insert`. Pyright will infer `None`, which is fine.
2. Insert a `raise` or `assert` statement after the `for` loop.

```python
assert False, "Should never get here because the for loop will never return"
```

**Comment by winstxnhdw** [comment]
Is it not possible for Pyright to just trust the develop if they were to do `Generator[int, None, NoReturn]`?
