### ISSUE TITLE
legal named arguments reported unknown in certain situations

### ISSUE THREAD

**Issue by dmlyubim** [microsoft/pyright#554]
**Describe the bug**

In situations when additional named arguments are allowed, pyright reports unknown named argument

**To Reproduce**
Steps to reproduce the behavior.

> def f(p1:Any, **kwargs:Any):
>     print (p1)
>     print(kwargs)
> 
>  
> 
> 
> other_kwargs={"a1":1, "a2":2}
> 
>  
> 
> f(0, p2=1, **other_kwargs)
> 

translates executes as expected by python, but pyright reports p2 as unknown argument.

**Expected behavior**

**Additional context**
I haven't checked specifically, but perhaps it is possible that arbitrary positional arguments in similar situation are not handled properly either, not just named arguments.

**Comment by erictraut** [comment]
I'm not able to repro the problem as reported. It turns out that Pyright already handles the case where there are named arguments plus kwargs. I think I understand the problem you were seeing. I'll follow up with you directly.
