### ISSUE TITLE
Pyright VSCode extension does not pick new .pyi stubs or updates to existing ones.

### ISSUE THREAD

**Issue by c3-willydouhard** [microsoft/pyright#555]
**Is your feature request related to a problem? Please describe.**
I have a program that creates / update .pyi stubs in the typeshed dir used by Pyright based on certain events. If it happens before the Pyright language server boots, everything works. However if the LS boots first and then a new .pyi file is created, Pyright will not pick it up.

**Describe the solution you'd like**
Two possibilities:
1. Pyright watches the typeshed dir and picks up changes on the fly (without the user having to open the .pyi file in VSCode)
2. A command to reboot the Pyright LS cleanly is exposed in VSCode's command palette. Similarly to TypeScript's "Restart TS server" command.

**Comment by erictraut** [comment]
Thanks for the feature suggestion. This sounds reasonable and consistent with commands exposed by other language servers.

**Comment by c3-willydouhard** [comment]
Thank you for your quick response!

**Comment by erictraut** [comment]
This is now addressed in Pyright 1.1.27, which I just published.
