### ISSUE TITLE
IntelliSense does not work for 3rd party libs in a virtual environment

### ISSUE THREAD

**Issue by HymanZHAN** [microsoft/pyright#556]
**Describe the bug**
When I want to access a function of a class that is defined in installed packages, I am not able to get IntelliSense.

**To Reproduce**
1. Create a `.venv` virtual environment via pipenv: `pipenv shell`
2. Install FastAPI: `pipenv install fastapi`
3. Create a main.py file, where a FastAPI instance `app` gets created and used.
4. Try to access `app.include_router`

**Expected behavior**
1. `include_router` gets autocompletion and can go to definition.

**Screenshots or Code**
```python
from fastapi import FastAPI

app = FastAPI(title="Test Project", openapi_url="/api/v1/openapi.json")

app.include_router(...)
```

**VS Code extension or command-line**

Extension. 
Version: 1.1.25.

**Additional context**
With Python extension's language server:

![Screenshot from 2020-03-06 10-17-58](https://user-images.githubusercontent.com/26806995/76097232-593a9a00-5f95-11ea-9f37-573f2af6cd0d.png)

With pyright only:

![Screenshot from 2020-03-06 10-19-13](https://user-images.githubusercontent.com/26806995/76097252-60fa3e80-5f95-11ea-92c9-a5a2671a7f7d.png)

My pyrightconfig.json file:
```json
{
  "include": ["app"],
  "exclude": ["**/node_modules", "**/__pycache__"],
  "venvPath": "/home/xzhan/Development/Projects/desci_online/backend/app/.venv",
  "reportMissingImports": "warning",
  "ignore": ["tests"],
  "typeshedPath": ".venv/lib/python3.7/site-packages/mypy/typeshed",
  "typingsPath": ".venv/lib/python3.7/site-packages/sqlalchemy-stubs/"
}
```

My project structure:
```
backend/app/
├── app
│   ├── core
│   ├── __init__.py
│   ├── main.py
│   ├── manage.py
│   ├── modules
│   └── scripts
├── Pipfile
├── Pipfile.lock
├── pyrightconfig.json
├── tests
│   └── ...
├── .venv
│   ├── bin
│   ├── include
│   ├── lib
│   ├── LICENSE.md
│   ├── .project
│   ├── share
│   └── src
└── .vscode
    ├── settings_example.json
    └── settings.json
```
It is quite possible that I got something wrong in the config file... If that's the case please kindly let me know as I am a bit confused about how `venv` and `venvPath` differ and work together. 

Thanks in advance!

**Comment by erictraut** [comment]
By default, Pyright uses type stub files to understand types for third-party libraries. It has a mode where it can attempt to extract type information directly from the installed library implementation, but this mode is not on by default. You need to enable the "pyright.useLibraryCodeForTypes" setting in VS Code. Type information derived from implementation files is often incomplete, so high-quality type stubs will provide a better (and faster) IntelliSense experience.

**Comment by HymanZHAN** [comment]
Got it. Thanks for the prompt response! And thanks for making pyright!

**Comment by dzpt** [comment]
@erictraut most of 3rd party lib doesn't have stub files.
by setting `pyright.useLibraryCodeForTypes`, will it automatically priority to search for stub before use code for type or use code for type only ?

**Comment by erictraut** [comment]
Pyright always prefers type stubs if they're available. If you enable `useLibraryCodeForTypes`, it will still look for ".pyi" files first. If it cannot find a type stub, it will then attempt to extract type information from the implementation ('.py') files.
