### ISSUE TITLE
False(?) rejection of overriding abstract property with literal

### ISSUE THREAD

**Issue by prophile** [microsoft/pyright#5564]
**Describe the bug**
When a parent class defines an abstract property, and a subclass implements this not as an `@property` but assignment to a literal value, both runtime and mypy accept it but Pyright rejects it.

**Code or Screenshots**
```python
import abc

class Parent(abc.ABC):
    @property
    @abc.abstractmethod
    def an_attribute(self) -> str:
        raise NotImplementedError

class Child(Parent):
    an_attribute = "foo"
```

This produces the error: `"Literal['foo']" is incompatible with "property"`

**VS Code extension or command-line**
Produced running pyright on the command line.

```bash
$ pyright --version
pyright 1.1.318
```

**Comment by erictraut** [comment]
This is intended. You are attempting to override a property with a simple attribute. These have different semantics. For example, the property is read-only and cannot be accessed via the class.

Here's the proper type-safe way to implement this property:

```python
class Child(Parent):
    @property
    def an_attribute(self) -> str:
        return "foo"
```

**Comment by prophile** [comment]
It is contravariant in both those cases is it not? The parent class supports the attribute being read from instances, and so does the subclass. It is true that the subclass supports _more_ operations but that is after all what subclasses do.

**Comment by erictraut** [comment]
A simple class variable and a property (which is implemented as a descriptor object) share many behaviors but differ in some important ways. If you access the attribute via the class (as opposed to an instance of the class), these differences become apparent. For that reason, pyright enforces consistency between an abstract class and a concrete implementation. If the ABC indicates that a property is required, then you should provide a property in your implementation. Likewise, if the ABC indicates that a class variable is required, then you should provide a class variable in your implementation.

**Comment by prophile** [comment]
How would an ABC indicate that a class variable is required?

**Comment by erictraut** [comment]
I guess there's no way for an ABC to indicate that a class variable is required.

It sounds like you're really looking for a way to specify a structural subtype. A `Protocol` may serve your purposes better than an `ABC`.

**Comment by Dzeri96** [comment]
@erictraut while I somewhat agree with @prophile on a superficial level (as does mypy apparently), I wanted to report what I consider an inconsistency in the behavior of pyright itself.
If we simply type-hint the variable like so: ` an_attribute:str = "foo"`,  pyright stops complaining.

Is this by design or a bug?

**Comment by erictraut** [comment]
@Dzeri96, I'm not sure what you mean by "simply type-hint the variable like so". Can you provide a code sample? If you mean [this](https://pyright-play.net/?code=JYWwDg9gTgLgBAQwEYGMBQaUBsEGddwAKCUApgHYwAUyKAdAIIBCAwgJQBcacPcAAmCgQwpWAE9uvPrTrJcMKAhQwQpGAAsIAE0k8tpAGaJyAfQQwFwJAFcYpKrlJYDbOAFoAfHHlQuvf3CKwI5wAHIQMACS4FikqpSkWgCiUEJQGNh4BCzqwFhaVMRklJy6xmYWUFa2pBzeCnAAvHAARAYQEC1oQA), then pyright does emit an error, as it should.

**Comment by Dzeri96** [comment]
@erictraut That's interesting. I pasted your code after mine (without a type-hint)  into VS Code and as you can see, your code doesn't raise an error. For reference I'm using Pylance v2024.10.1 and VS Code 1.94.2

![VS Code screenshot](https://github.com/user-attachments/assets/b7f0eb0d-58bc-4afe-8043-23943d4e5bfa)

**Comment by erictraut** [comment]
@Dzeri96, it looks like you're using "basic" type checking mode rather than "standard". In basic mode, the `reportIncompatibleMethodOverride` check [is disabled by default](https://microsoft.github.io/pyright/#/configuration?id=diagnostic-settings-defaults). The "standard" type checking mode enables all checks that are mandated by the [typing spec](https://typing.readthedocs.io/en/latest/spec/index.html). Of course, you're free to disable any checks that you want or suppress any specific diagnostics.

**Comment by Dzeri96** [comment]
You're right. I was getting just the `reportAssignmentType` error instead of `reportIncompatibleMethodOverride`. Still, the former doesn't get triggered when the overriding property is type-hinted. I don't know if this is by design or not...

**Comment by erictraut** [comment]
Yes, this is working as designed. If you omit a type declaration for a class-scoped attribute, the declared type is inherited from its parent. If you provide a type declaration in a child class that conflicts with the declared type in its parent, this mismatch is reported as an incompatible override.
