### ISSUE TITLE
[GeneralTypeIssues] Reported "Expected TypedDict type argument for Unpack" when used with `TypeVar`

### ISSUE THREAD

**Issue by bowentan** [microsoft/pyright#5574]
<h3> Environment data </h3>

-   Language Server version: 2023.6.40
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): Miniconda-Python/3.10.8
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
class _Type(TypedDict):
    b: int


_TypeVar = TypeVar("_TypeVar", bound=_Type)

class A(Generic[_TypeVar]):
    def __init__(self, **kwargs: Unpack[_TypeVar]) -> None:
        ...
```

<h3> Expected behavior </h3>

Not sure..

<h3> Actual behavior </h3>

Pylance reported the `GeneralTypeIssues` error for the line with `Unpack` with the error message "Expected TypedDict type argument for Unpack".

<h3> Logs </h3>

```
Expected TypedDict type argument for Unpack Pylance(reportGeneralTypeIssues)
```

I am not very familiar with the `Unpack` typing and not sure whether the codes above were the correct way to use `TypeDict` and `Unpack` together with `TypeVar`. I actually tried the codes with the following codes and they worked properly:
```python
class TypeParams(_Type):
    a: int

class B(A[TypeParams]):
    def __init__(self, **kwargs: Unpack[TypeParams]) -> None:
        super().__init__(**kwargs)
```
So is such an error report correct for indicating my wrong usage of `TypeVar` and `TypeDict`, or a false positive?

**Comment by erictraut** [comment]
I think pyright's behavior is correct here.

[PEP 646](https://peps.python.org/pep-0646/) introduced the special form `Unpack`. At that time, the only type argument allowed for `Unpack` was a `TypeVarTuple`. 

[PEP 692](https://peps.python.org/pep-0692/), which introduced the ability to use a `TypedDict` to annotate a `**kwargs` parameter, extended `Unpack` to allow the use of a concrete `TypedDict` type. It does not allow other types to appear in this location, including unions of TypedDicts or type variables bound to TypedDicts.

The problem with allowing type variables is that there would be no way for a constraint solver to solve such variables in the general case.

```python
T = TypeVar("T", bound=MyTypedDict)

def func(**kwargs: Unpack[T]) -> T: ...

x = func(**{"a": 1, "b": 0})
reveal_type(x) # What type should this be?
```
