### ISSUE TITLE
reportMissingModuleSource for reportlab, Correct

### ISSUE THREAD

**Issue by Adesoji1** [microsoft/pyright#5577]
If you have a question about a behavior that you’re seeing in pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem.

**Describe the solution you’d like**
A clear and concise description of the solution you would like to see.

Import "reportlab.lib.pagesizes" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports) . This python library exists but pylance reports it as reportmissingimport. the library is called  reportlab. https://pyng.tech/docs/reportlab/pdfgen/textobject.m.html

**Comment by erictraut** [comment]
I'm not able to repro the problem. I installed the latest version of the library from pypi (`pip install reportlab`), created a new source file and typed `import reportlab.lib.pagesizes`. Pyright resolved the import without an issue.

I'm guessing that you don't have the correct Python environment configured or have failed to install the library into that environment, but you haven't provided enough details for me to determine. Please refer to pyright's documentation and [troubleshooting tips](https://microsoft.github.io/pyright/#/import-resolution?id=debugging-import-resolution-problems) for more information. The output logs may also help you diagnose the problem.
