### ISSUE TITLE
node report issues - JavaScript heap out of memory

### ISSUE THREAD

**Issue by muribury123** [microsoft/pyright#5588]
Hi,

I used this plugin for long time ago, but now it's starting to give me problems.
Things that change, I only can think in the project size that now is 200M.
I'm in Ubuntu22, but I recently change, and before I work with Ubuntu18 and 20, that has the same problem

I started to see that when I try things like 'go to definition', it takes like a minute (when it works), and see lot of errors like 'Client n quit with exit code n and signal n' (the numbers change so I put an 'n')
And another thing I notice is that node starts to give me some problems, because ubuntu tell me to send the report.

I follow the README and install with basic configuration. Commenting code here and there I discover the line that give me problems.
I tried to look where node is launch, and without that line, node doesn't start:
lspconfig.pyright.setup {}
with the line node starts with:
CPU: 100 to 250
MEM: 6 to 13
RES: 1 to 2
The problem with node apparently is a resource problem, so maybe it's getting too much resources with the basic configuration.
"JavaScript heap out of memory"

Neovim version
NVIM v0.10.0-dev-698+g02d859a07
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info

Nvim-lspconfig version last
Ubuntu22
inter core i7
python 3.7
node v18.17.0
Steps to reproduce
Install plugin with Suggested configuration

Actual behavior
It takes some minutes to 'go to definition'
node stop working
$ free -h
               total        used        free      shared  buff/cache   available
Mem:            15Gi       7,2Gi       639Mi       1,2Gi       7,5Gi       6,3Gi
Swap:          2,0Gi       1,1Gi       912Mi

== LSP log ==
[START][2023-07-26 10:00:40] LSP logging initiated [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "\n<--- Last few GCs --->\n\n[35793:0x6435f20] 706547 ms: Mark-sweep (reduce) 1869.1 (2046.0) -> 1869.1 (1992.8) MB, 2193.1 / 0.0 ms (average mu = 0.386, current mu = 0.000) last resort; GC in old space requested\n[35793:0x6435f20] 708360 ms: Mark-sweep (reduce) 1869.1 (1992.8) -> 1869.1 (1979.8) MB, 1813.2 / 0.0 ms (average mu = 0.250, current mu = 0.000) last resort; GC in old space requested\n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834 [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 5: 0xf3039f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 6: 0xf10760 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 7: 0xf07d2c v8::internal::FactoryBasev8::internal::Factory::AllocateRawArray(int, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 8: 0xf07ea5 v8::internal::FactoryBasev8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Handlev8::internal::Map, int, v8::internal::Handlev8::internal::Oddball, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 9: 0x11c2f0e v8::internal::MaybeHandlev8::internal::OrderedHashMap v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocatev8::internal::Isolate(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "10: 0x11c2fc3 v8::internal::MaybeHandlev8::internal::OrderedHashMap v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehashv8::internal::Isolate(v8::internal::Isolate*, v8::internal::Handlev8::internal::OrderedHashMap, int) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "11: 0x12cd30d v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "12: 0x17035b9 [/usr/bin/node]\n" [START][2023-07-26 13:44:12] LSP logging initiated [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "\n<--- Last few GCs --->\n\n[87797:0x5badf20] 353038 ms: Mark-sweep (reduce) 1862.2 (2045.5) -> 1862.2 (1990.5) MB, 995.3 / 0.0 ms (average mu = 0.438, current mu = 0.000) last resort; GC in old space requested\n[87797:0x5badf20] 354840 ms: Mark-sweep (reduce) 1862.2 (1990.5) -> 1862.2 (1974.3) MB, 1802.1 / 0.0 ms (average mu = 0.232, current mu = 0.000) last resort; GC in old space requested\n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834 [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 5: 0xf3039f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 6: 0xf10760 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 7: 0xf07d2c v8::internal::FactoryBasev8::internal::Factory::AllocateRawArray(int, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 8: 0xf07ea5 v8::internal::FactoryBasev8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Handlev8::internal::Map, int, v8::internal::Handlev8::internal::Oddball, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 9: 0x11c2f0e v8::internal::MaybeHandlev8::internal::OrderedHashMap v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocatev8::internal::Isolate(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "10: 0x11c2fc3 v8::internal::MaybeHandlev8::internal::OrderedHashMap v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehashv8::internal::Isolate(v8::internal::Isolate*, v8::internal::Handlev8::internal::OrderedHashMap, int) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "11: 0x12cd30d v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "12: 0x17035b9 [/usr/bin/node]\n" [START][2023-07-26 15:26:17] LSP logging initiated [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "\n<--- Last few GCs --->\n\n[95110:0x6fcdf20] 570221 ms: Scavenge (reduce) 1976.9 (2080.2) -> 1976.0 (2080.2) MB, 6.9 / 0.0 ms (average mu = 0.346, current mu = 0.462) allocation failure; \n[95110:0x6fcdf20] 570272 ms: Scavenge (reduce) 1977.0 (2080.2) -> 1976.1 (2080.2) MB, 21.4 / 0.0 ms (average mu = 0.346, current mu = 0.462) allocation failure; \n[95110:0x6fcdf20] 570298 ms: Scavenge (reduce) 1977.0 (2080.2) -> 1976.2 (2080.5) MB, 6.1 / 0.0 ms (average mu = 0.346, current mu = 0.462) allocation failure; \n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory\n 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834 [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 5: 0xf42265 [/usr/bin/node]\n 6: 0xf43168 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node]\n 7: 0xf53673 [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 8: 0xf544e8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 9: 0xf2ee4e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "10: 0xf30217 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "11: 0xf113ea v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "12: 0x12d674f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "13: 0x17035b9 [/usr/bin/node]\n" [START][2023-07-26 15:36:23] LSP logging initiated [ERROR][2023-07-26 15:36:23] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "\n<--- Last few GCs --->\n\n[97111:0x6bb0f20] 532971 ms: Mark-sweep (reduce) 1863.9 (2039.3) -> 1863.9 (1987.5) MB, 2504.2 / 0.0 ms (average mu = 0.294, current mu = 0.000) last resort; GC in old space requested\n[97111:0x6bb0f20] 536481 ms: Mark-sweep (reduce) 1863.9 (1987.5) -> 1863.9 (1983.8) MB, 3509.8 / 0.0 ms (average mu = 0.139, current mu = 0.000) last resort; GC in old space requested\n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834 [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 5: 0xf3039f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 15:36:23] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 6: 0xf10760 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/bin/node]\n 7: 0xf07d2c v8::internal::FactoryBasev8::internal::Factory::AllocateRawArray(int, v8::internal::AllocationType) [/usr/bin/node]\n 8: 0xf07ea5 v8::internal::FactoryBasev8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Handlev8::internal::Map, int, v8::internal::Handlev8::internal::Oddball, v8::internal::AllocationType) [/usr/bin/node]\n 9: 0x11c2f0e v8::internal::MaybeHandlev8::internal::OrderedHashMap v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocatev8::internal::Isolate(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/bin/node]\n10: 0x11c2fc3 v8::internal::MaybeHandlev8::internal::OrderedHashMap v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehashv8::internal::Isolate(v8::internal::Isolate*, v8::internal::Handlev8::internal::OrderedHashMap, int) [/usr/bin/node]\n" [ERROR][2023-07-26 15:36:23] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "11: 0x12cd30d v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 15:36:23] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "12: 0x17035b9 [/usr/bin/node]\n" [START][2023-07-26 16:08:31] LSP logging initiated [ERROR][2023-07-26 16:08:31] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "\n<--- Last few GCs --->\n\n[101147:0x7738f20] 363091 ms: Mark-sweep (reduce) 1862.0 (2039.0) -> 1862.0 (1986.3) MB, 1251.0 / 0.0 ms (average mu = 0.324, current mu = 0.000) last resort; GC in old space requested\n[101147:0x7738f20] 364354 ms: Mark-sweep (reduce) 1862.0 (1986.3) -> 1862.0 (1968.8) MB, 1263.0 / 0.0 ms (average mu = 0.199, current mu = 0.000) last resort; GC in old space requested\n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834 [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 5: 0xf3039f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n 6: 0xf10760 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/bin/node]\n 7: 0xf07d2c v8::internal::FactoryBasev8::internal::Factory::AllocateRawArray(int, v8::internal::AllocationType) [/usr/bin/node]\n 8: 0xf07ea5 v8::internal::FactoryBasev8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Handlev8::internal::Map, int, v8::internal::Handlev8::internal::Oddball, v8::internal::AllocationType) [/usr/bin/node]\n 9: 0x11c2f0e v8::internal::MaybeHandlev8::internal::OrderedHashMap v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocatev8::internal::Isolate(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/bin/node]\n10: 0x11c2fc3 v8::internal::MaybeHandlev8::internal::OrderedHashMap v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehashv8::internal::Isolate(v8::internal::Isolate*, v8::internal::Handlev8::internal::OrderedHashMap, int) [/usr/bin/node]\n11: 0x12cd30d v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 16:08:31] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "12: 0x17035b9 [/usr/bin/node]\n" [START][2023-07-26 16:27:45] LSP logging initiated [ERROR][2023-07-26 16:27:45] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "\n<--- Last few GCs --->\n\n[103641:0x5decf20] 510891 ms: Mark-sweep (reduce) 1862.1 (2041.5) -> 1862.1 (1985.3) MB, 2700.5 / 0.0 ms (average mu = 0.315, current mu = 0.000) last resort; GC in old space requested\n[103641:0x5decf20] 513125 ms: Mark-sweep (reduce) 1862.1 (1985.3) -> 1862.1 (1971.8) MB, 2233.0 / 0.0 ms (average mu = 0.195, current mu = 0.000) last resort; GC in old space requested\n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834 [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 5: 0xf3039f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n 6: 0xf10760 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/bin/node]\n 7: 0xf07d2c v8::internal::FactoryBasev8::internal::Factory::AllocateRawArray(int, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 16:27:45] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" " 8: 0xf07ea5 v8::internal::FactoryBasev8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Handlev8::internal::Map, int, v8::internal::Handlev8::internal::Oddball, v8::internal::AllocationType) [/usr/bin/node]\n 9: 0x11c2f0e v8::internal::MaybeHandlev8::internal::OrderedHashMap v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocatev8::internal::Isolate(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/bin/node]\n10: 0x11c2fc3 v8::internal::MaybeHandlev8::internal::OrderedHashMap v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehashv8::internal::Isolate(v8::internal::Isolate*, v8::internal::Handlev8::internal::OrderedHashMap, int) [/usr/bin/node]\n11: 0x12cd30d v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 16:27:45] .../vim/lsp/rpc.lua:675 "rpc" "/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver" "stderr" "12: 0x17035b9 [/usr/bin/node]\n"

**Comment by erictraut** [comment]
Is your code in a publicly-accessible repo, by any chance? Or are you able to give me temporary access to your repo? Without repro steps, it's going to be very difficult to diagnose the problem you're seeing.

I've added some additional internal type caching over the past few versions of pyright that could increase memory pressure in some cases, but pyright includes logic that monitors heap size and deallocates the cache if the memory usage exceeds a high water mark.

What version of node are you using? Older versions of node have some GC bugs where they are not able to reclaim memory in certain cases that involve circular references. If you're using a version of node prior to v16, could you please try updating to a new version? I recommend v18, which is the latest stable version. Running `node --version` will tell you which version is installed and used by default on your system.

**Comment by erictraut** [comment]
You mentioned above "Commenting code here and there I discover the line that give me problems." Could you provide the line of code that you isolated the problem to?

**Comment by erictraut** [comment]
Without further repro steps, there's not much I can do with this. If you're able to provide additional details, I'm happy to investigate further. I'm going to close the issue for now.
