### ISSUE TITLE
Typing Not Narrowing From Usage of builtins.type()

### ISSUE THREAD

**Issue by ImplyingICheck** [microsoft/pyright#5590]
**Describe the bug**
The type of variables is not narrowed after using `builtins.type()` to compare two variables. This also applies to calls to `isinstance(foo, type(bar))`.

**Code or Screenshots**

```python
IntegerRepresentation = int | str


def same_type_hint_different_class(
  a: IntegerRepresentation,
  b: IntegerRepresentation,
) -> IntegerRepresentation:
  if type(a) != type(b):
    return 0
  if isinstance(a, str):
    return b[0]
  return 0
```
outputs the following:

```
>>> npx pyright scratch_2.py
scratch_2.py
  scratch_2.py:11:12 - error: "__getitem__" method not defined on type "int" (reportGeneralTypeIssues)
```
If I am not mistaken, the check `type(a) != type(b)` also guarantees that `isinstance(a, str) == isinstance(b, str)` since `type(foo)` is a stricter than `isinstance`. Is this sufficient for pyright to know that `b`—in the above example—must also be a `str`?

**VS Code extension or command-line**
Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool? Which version?

I am using the command-line tool.

```plain-text
>>> npx pyright --version
pyright 1.1.319
```

**Comment by erictraut** [comment]
This is working as intended.

The statement `type(a) != type(b)` is not a supported type guard. For a full list of supported type guards, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards).

Also, type narrowing is performed on individual variables, not on combinations of variables. The statement `type(a) != type(b)` does not allow `a` to be narrowed. Nor does it allow `b` to be narrowed. 

The type-safe way to write the above code is:
```python
IntegerRepresentation = int | str


def same_type_hint_different_class(
    a: IntegerRepresentation, b: IntegerRepresentation
) -> IntegerRepresentation:
    if isinstance(a, str) and isinstance(b, str):
        return b[0]
    return 0
```

**Comment by ImplyingICheck** [comment]
Thank you very much the quick response! Off topic, but I really appreciate all the effort you put into maintaining Pyright. I'm always amazed at how fast and courteous your responses are.

> The statement `type(a) != type(b)` is not a supported type guard. For a full list of supported type guards, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards).

My apologies, I completely missed that portion of the documentation. I've given it a read over and will keep it in mind going into the future.

> Also, type narrowing is performed on individual variables, not on combinations of variables. The statement `type(a) != type(b)` does not allow `a` to be narrowed. Nor does it allow `b` to be narrowed.

I am not sure I quite understand this. Is this within the context of pyright or in general?

Would you mind pointing out where I'm going wrong in my thought process?

```python
if type(a) != type(b): # For any code after this block, it must be that type(a) == type(b)
    pass
if isinstance(a, str): 
    # Since we have that type(a) == type(b) above, it must mean that isinstance(b, str) is also True
```

**Comment by erictraut** [comment]
> Is this within the context of pyright or in general?

This is true of pyright, mypy, and all other static type checkers and compilers (in all languages) that I'm familiar with. 

> Would you mind pointing out where I'm going wrong in my thought process?

The type of `a` at the top of the function is `int | str`. The type guard `type(a) != type(b)` does nothing to narrow `a`. The type of `a` is still `int | str`. We can't narrow it to `str` because it might be `int`, and we can't narrow it to `int` because it might be `str`. The same is true for `b`. So this statement does not (and cannot) narrow the type of either `a` or `b`.

We could state "the type of `a` is `str` if the type of `b` is also `str` and the type of `a` is `int` if the type of `b` is also `int`", but this involves a sort of "entanglement" between `a` and `b`. This sort of conditional type evaluation would create many false dependencies between variables and would be prohibitively expensive in all but the simplest of cases. That's why no type checkers or compilers do it.

**Comment by ImplyingICheck** [comment]
Thank you for going through that. I was thinking about about that number or relationships would grow `O(n!)` for n variables. Then, with the perspective of wanting consistent behaviour from a program, it would be better to not support coupling.

Thinking back on my experience with static languages—though it has been a while—it makes sense that one usage of overloads was to convert differing argument types to one base case. Thinking of the coupling issue also puts into perspective the balance dynamic languages take between strong and weak typing.
