### ISSUE TITLE
Set a root path for reporting purposes

### ISSUE THREAD

**Issue by bobthemighty** [microsoft/pyright#5593]
**Is your feature request related to a problem? Please describe.**
We run pyright under [pants](https://pantsbuild.org). Each pyright run happens in a sandboxed hermetic environment, with a long directory path under /tmp.

Accordingly, we get lengthy output paths in error messages:

```
[...]
Found 436 source files
pyright 1.1.274
/private/var/folders/41/65mtw91x2b55t__32h793c1r0000gn/T/pants-sandbox-9nuQlH/src/learning/examples/cross_val/cross_val.py
  /private/var/folders/41/65mtw91x2b55t__32h793c1r0000gn/T/pants-sandbox-9nuQlH/src/learning/examples/cross_val/cross_val.py:63:5 - error: Argument missing for parameter "job_type" (reportGeneralTypeIssues)
  /private/var/folders/41/65mtw91x2b55t__32h793c1r0000gn/T/pants-sandbox-9nuQlH/src/learning/examples/cross_val/cross_val.py:65:20 - error: "load_dataset_local" is not a known member of module (reportGeneralTypeIssues)
  /private/var/folders/41/65mtw91x2b55t__32h793c1r0000gn/T/pants-sandbox-9nuQlH/src/learning/examples/cross_val/cross_val.py:68:20 - error: "splitting" is not a known member of module (reportGeneralTypeIssues)
```

This is hard to read.

**Describe the solution you’d like**
I'd like a command line and json option to set the reporting root path. If set, file paths are rendered relative to that path. The above would become (with a reporting root of 'src')

```
src/learning/examples/cross_val/cross_val.py
  src/learning/examples/cross_val/cross_val.py:63:5 - error: Argument missing for parameter "job_type" (reportGeneralTypeIssues)
  src/learning/examples/cross_val/cross_val.py:65:20 - error: "load_dataset_local" is not a known member of module (reportGeneralTypeIssues)
  src/learning/examples/cross_val/cross_val.py:68:20 - error: "splitting" is not a known member of module (reportGeneralTypeIssues)
```

Edit: I'm happy to open a PR for this change, but want to make sure it would be welcome.

**Comment by erictraut** [comment]
This isn't a setting that we'd be interested in adding, at least not at this time. It sounds very specific to your use case. 

My recommendation is to use pyright's `--outputjson` command-line option and then write a small script to post-process the output so it appears in a way that suits your needs. This shouldn't take more than a dozen lines of code.
