### ISSUE TITLE
Add configuration switch to enable experimental features

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#5598]
Pyright implements a number of experimental features that are meant to inform potential future PEPs. Such features are currently available to all pyright users by default. There's a danger that users could unintentionally take a dependency on these features and later be disappointed when these features are ultimately modified or removed. Examples include: inlined TypedDict definitions, support for `ReadOnly` TypedDict fields, and `StrictTypeGuard`. We should probably put these under a configuration flag. This will also make it clear in the source that a feature is experimental.

**Comment by erictraut** [comment]
This will be included in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.320, which I just published. It will also be included in a future version of pylance.

**Comment by reuben** [comment]
Hi @erictraut, sorry for the question in this old issue but I couldn't find an answer anywhere else: has the flag made its way to Pylance since then? I'd love to use some of the experimental features in VSCode, such as:

 - https://github.com/python/typing/discussions/1412
 - https://peps.python.org/pep-0728/

**Comment by erictraut** [comment]
@reuben, You can enable `enableExperimentalFeatures` in your config file (either `pyrightconfig.json` or `pyproject.toml`). Pylance fully supports pyright config files.

**Comment by antonio613** [comment]
> Pyright implementeert een aantal experimentele functies die bedoeld zijn om potentiële toekomstige PEP's te informeren. Dergelijke functies zijn momenteel standaard beschikbaar voor alle pyright-gebruikers. Het gevaar bestaat dat gebruikers onbedoeld afhankelijk worden van deze functies en later teleurgesteld zijn wanneer deze functies uiteindelijk worden gewijzigd of verwijderd. Voorbeelden hiervan zijn: inline TypedDict-definities, ondersteuning voor TypedDict-velden en . Waarschijnlijk moeten we deze onder een configuratievlag plaatsen. Dit maakt ook duidelijk in de bron dat een functie experimenteel is.`ReadOnly``StrictTypeGuard`
