### ISSUE TITLE
Renaming symbol is super slow with Pyright's language server

### ISSUE THREAD

**Issue by HymanZHAN** [microsoft/pyright#560]
**Describe the bug**
Renaming a symbol (by pressing F2) is super slow.

**To Reproduce**
1. Set `"python.languageServer": "None"` in local settings.json.
2. Find a short function and rename some local variables.

**Expected behavior**
Rename should finish quickly.

**Screenshots or Code**

- Python Extension's Language Server

![Peek 2020-03-09 23-42](https://user-images.githubusercontent.com/26806995/76277876-6ccd5580-6260-11ea-8a17-41cbbe51c249.gif)

- Pyright's Language Server

![Peek 2020-03-09 23-41](https://user-images.githubusercontent.com/26806995/76277881-6fc84600-6260-11ea-9782-642cb3509471.gif)

**VS Code extension or command-line**
VS Code extension: 1.1.26

**Additional context**
`pyright.useLibraryCodeForTypes` is set to `true`, if that is relevant.

**Comment by erictraut** [comment]
Thanks for the suggestion. There is an opportunity to improve the "rename symbol" speed but only in certain cases. If the symbol is declared outside of the current file or is declared within the current file but is potentially visible to other files via import (i.e. it is declared within a module or class scope), then Pyright needs to analyze all other files in the program to determine whether they have used that symbol. That can be very expensive, depending on the number of files in your program.

Currently, Pyright shortcuts this global analysis if the symbol is a local function parameter. There are other cases where this optimization can be applied — namely, any case where the symbol is declared within the same file and is not declared within a class or module scope. Local variables (such as `like` in your example above) can be renamed without analyzing all files in the program. However, a function, variable, or class declared at the global level (like `check_is_bookmarked` in your example) will still require global analysis and will still be relatively slow.

I've added this optimization, and it will be in the next published version of Pyright.

**Comment by HymanZHAN** [comment]
Thanks for the prompt and detailed explanation! Really appreciate it.

My main pain point is the slowness when renaming local variables as I don't usually rename functions so thanks for addressing that! One curious question though: Do you have any idea how Python Extension's language server is achieving the quick rename (even with class methods)? It seems that they do a global analysis when the project is first loaded and cache the info in memory. May I ask if there's a plan to use caching to improve the rename performance?

**Comment by erictraut** [comment]
Yes, the Python Extension is using upfront analysis and caching. Pyright used to do the same, but this approach take a lot of CPU cycles upfront and consumes massive amounts of memory on an ongoing basis. I switched Pyright to use a "lazy analysis" approach where it does analysis only on demand and caches only some information, not full type information. This is the same approach used by other leading-edge language servers like the one for TypeScript. There's currently no plan to go back to doing upfront analysis and full in-memory caching for all files in a program. While this would speed up "rename symbol" operations, these operations are not common enough to justify all of the other downsides.

**Comment by HymanZHAN** [comment]
Got it. Thank you for the explanantion!

**Comment by erictraut** [comment]
This is now addressed in Pyright 1.1.27, which I just published.

**Comment by HymanZHAN** [comment]
Cool! Thank you so much!
