### ISSUE TITLE
Support subtypes of `NotImplementedError`

### ISSUE THREAD

**Issue by alexchandel** [microsoft/pyright#5608]
**Is your feature request related to a problem? Please describe.**
[Raising NotImplementedError is suggested as a best practice for abstract methods here](https://stackoverflow.com/a/44575926).  Pyright special-cases this exception to look for a method that's implemented by a subclass.  However, some libraries [like Pyomo](https://github.com/Pyomo/pyomo/blob/0c140def3006fa441d90e889bfbae35f78486051/pyomo/common/errors.py#L143) subclass this exception.  This still follows the practice, but Pyright does not currently support subclasses of `NotImplementedError`, so it does not make the subclass inference.

**Describe the solution you’d like**
Pyright should include subclasses of `NotImplementedError` alongside `NotImplementedError` when determining to look for subclass implementations of a method.

**Comment by erictraut** [comment]
Thanks for the suggestion. I think this is a reasonable request. I've updated the logic to exempt not only `NotImplementedError` but also subclasses thereof. This will be included in the next release of pyright and a future release of pylance.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.320, which I just published. It will also be included in a future version of pylance.
