### ISSUE TITLE
Crash in flownode (about 50 hits in 2023.7.40 Pylance release)

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pyright#5622]
Error: Debug Failure. setIncompleteSubtype can be called only on a valid incomplete cache entry</br>at None <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L272'>pyright-internal/src/analyzer/codeFlowEngine.ts:272:25</a></br>    at exprListResult <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pylance-internal/src/jinja/jinjaParser.ts#L2853'>pylance-internal/src/jinja/jinjaParser.ts:2853:62</a></br>at func (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L869'>pyright-internal/src/analyzer/codeFlowEngine.ts:869:41</a></br>at getTypeFromLoopFlowNode <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L585'>pyright-internal/src/analyzer/codeFlowEngine.ts:585:31</a></br>at getTypeFromFlowNode <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L1079'>pyright-internal/src/analyzer/codeFlowEngine.ts:1079:19</a></br>at getTypeFromCodeFlow <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L18472'>pyright-internal/src/analyzer/typeEvaluator.ts:18472:24</a></br>    at node <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L969'>pyright-internal/src/analyzer/typeEvaluator.ts:969:43</a></br>    at node <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L974'>pyright-internal/src/analyzer/typeEvaluator.ts:974:51</a></br>at node <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L974'>pyright-internal/src/analyzer/typeEvaluator.ts:974:51</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/common/timing.ts#L40'>pyright-internal/src/common/timing.ts:40:19</a></br>at getTypeOfExpression <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L1448'>pyright-internal/src/analyzer/codeFlowEngine.ts:1448:45</a></br>at isCallNoReturn <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L427'>pyright-internal/src/analyzer/codeFlowEngine.ts:427:66</a></br>at getTypeFromFlowNode <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L1079'>pyright-internal/src/analyzer/codeFlowEngine.ts:1079:19</a></br>at getTypeFromCodeFlow <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L18472'>pyright-internal/src/analyzer/typeEvaluator.ts:18472:24</a></br>at node <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L969'>pyright-internal/src/analyzer/typeEvaluator.ts:969:43</a></br>at getTypeOfExpression <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L2220'>pyright-internal/src/analyzer/typeEvaluator.ts:2220:20</a></br>at getDeclaredTypeForExpression <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L14956'>pyright-internal/src/analyzer/typeEvaluator.ts:14956:37</a></br>at evaluateTypesForAssignmentStatement <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L18290'>pyright-internal/src/analyzer/typeEvaluator.ts:18290:24</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L18404'>pyright-internal/src/analyzer/typeEvaluator.ts:18404:8</a></br>at evaluateTypeForSubnode <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L19916'>pyright-internal/src/analyzer/typeEvaluator.ts:19916:31</a></br>    at getInferredTypeOfDeclaration <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L20233'>pyright-internal/src/analyzer/typeEvaluator.ts:20233:35</a></br>at func (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L20177'>pyright-internal/src/analyzer/typeEvaluator.ts:20177:14</a></br>at getEffectiveTypeOfSymbolForUsage <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L20773'>pyright-internal/src/analyzer/typeEvaluator.ts:20773:31</a></br>at getTypeOfMemberInternal <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L5393'>pyright-internal/src/analyzer/typeEvaluator.ts:5393:35</a></br>at getTypeOfClassMemberName <a href='https://github.com/microsoft/pyrx/blob/6dac6a56119f02b4268ac807fc1f7deb85364fcd/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L1867'>pyright-internal/src/analyzer/typeEvaluator.ts:1867:27</a></br>

**Comment by erictraut** [comment]
Can you narrow it down to a specific version of pylance or pyright? When you say "stable Pylance release", are you specifically referring to [2023.7.40](https://github.com/microsoft/pylance-release/releases/tag/2023.7.40)? Or does this include earlier versions of pylance?

This assertion is explained by a bug that was introduced in pyright 1.1.315 but was fixed in 1.1.316 (in [this commit](https://github.com/microsoft/pyright/commit/1340dfac2239b9bb086780bfdb20dee9bd791367)).

**Comment by rchiodo** [comment]
Sorry yeah I should have put what version. 2023.7.40 which should be pyright 1.1.318. Unless we messed up insertion somehow.

**Comment by erictraut** [comment]
I've re-reviewed the code, and I don't understand how we can get into this condition. I've updated the assertion so it logs additional clues. 

I'm going to close this bug since it's not actionable in its current form. Please open a new one with additional details if/when this shows up again in the pylance telemetry.

**Comment by erictraut** [comment]
Reopening now that we have a repro case.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.323, which I just published. It will also be included in a future release of pylance.
