### ISSUE TITLE
Provide more information why "Cannot create consistent method ordering" is triggered

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#5642]
**Is your feature request related to a problem? Please describe.**

I'm working [towards a PR](https://github.com/twoertwein/pandas-stubs/tree/iter_interpolate) for pandas-stubs which triggered "Cannot create consistent method ordering" ([[1]](https://github.com/twoertwein/pandas-stubs/blob/2775a58547b115a58f527d236f69148e3a2cae32/pandas-stubs/core/indexes/datetimes.pyi#L40), [[2]](https://github.com/twoertwein/pandas-stubs/blob/2775a58547b115a58f527d236f69148e3a2cae32/pandas-stubs/core/indexes/timedeltas.pyi#L34)) even though I did not change any class ordering (but some classes are now generic and I removed some typing-only helper classes). 

**Describe the solution you’d like**
It would be great, if pyright can provide more information about why it cannot infer a consistent ordering. I'm not sure whether it makes sense but something ala, class A has two inheritance chains (and list them) that conflict with each other (or inherit twice from the same class).

**Comment by erictraut** [comment]
This is the same error message and terminology provided by the Python interpreter in this case. It's also the same wording used by mypy for this error.

The problem has nothing to do with "inference". It has to do with an inability to calculate a consistent method resolution ordering based on the MRO algorithm documented [here](https://www.python.org/download/releases/2.3/mro/). This is obviously too involved to include in an error message.
