### ISSUE TITLE
TypeGuard may not be strict enough?

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pyright#5643]
After turning on experimental features, try this code:

```python
def is_cardinal_direction(val: str) -> TypeGuard[Literal["N", "S", "E", "W"]]:
    return val in ("N", "S", "E", "W")

def func(direction: Literal["NW", "E"]):
    if is_cardinal_direction(direction):
        reveal_type(direction) # Literal["N", "S", "E", "W"]
    else:
        reveal_type(direction) # Literal["NW", "E"] <-- Shouldn't this be just Literal['NW']?
```

Or perhaps this is behaving this way because `Literal['N', 'S', 'E', 'W']` is not a subtype of `Literal['NW', 'E']` so it can't be narrowed in the else situation so it just returns the input type.

I feel like this makes the new PEP harder to explain though. 

For example in the positive case, TypeGuard can expand the type:

```python
def tg(x: object) -> TypeGuard[str | int]:
    return isinstance(x, (str, int))

y: str = 'foo'
if tg(y):
   reveal_type(y) # str | int
```

But without an explicit negative, it's harder to reason about what the TypeGuard is saying in the negative case.

**Comment by erictraut** [comment]
The results you're reporting here are consistent with today's TypeGuard behavior. If you set `enableExperimentalFeatures` to `true`, you will see this:

```python
def func(direction: Literal["NW", "E"]):
    if is_cardinal_direction(direction):
        reveal_type(direction)  # Literal["E"]
    else:
        reveal_type(direction)  # Literal["NW"]
```

I've confirmed this works as expected.

I suspect that you haven't properly enabled experimental features.

**Comment by rchiodo** [comment]
Yeah, it doesn't repro now. I must have misconfigured it somehow.
