### ISSUE TITLE
Raising errors while giving completions

### ISSUE THREAD

**Issue by XCarCedo** [microsoft/pyright#5657]
**Describe the bug**
I got this error from pyright LSP saying that object 'None' have no known member x This is a little strange since the object i'm referring to is clearly not None and pyright raises this error while giving me correct completions about that object

**Code or Screenshots**
![lsp_error](https://github.com/microsoft/pyright/assets/69898738/00fe7ed5-6bb4-4cd8-8275-0561960c3d59)
pygame-ce==2.3.0

**VS Code extension or command-line**
I'm running pyright in sublime text

**Comment by erictraut** [comment]
Please provide a minimal, self-contained code sample that demonstrates the problem. It's not really feasible to diagnose type violation errors from partial screen shots.

**Comment by XCarCedo** [comment]
Sorry about the that, here's the [gist](https://gist.github.com/XCarCedo/5bc5759f04884f03d943396999521a45) that causing the problems for me in lines 46 & 48 (pygame-ce have to be installed to run the code)

I thought that if pyright gives completions then surely it knows the object type, so when it gives error about the object being a None that seemed a little strange
Is there any way to fix the code instead of disabling the whole type checking system?

**Comment by erictraut** [comment]
The instance variable `current_anim` has no type declaration (i.e. you haven't provided an annotation), so its type is inferred from all assignments to it within the class implementation. It is assigned in three places. For the first assignment (in the `__init__` method), it is assigned a value of type `tuple[Literal["idle"], list[Surface]]`. The second assignment (in the `set_anim` method), it is assigned a value of type `tuple[str, list[Surface]]`. The third assignment (in the `update` method), it is assigned a value of type `Self`, which refers to an instance of `Button` or a subtype thereof. It's that third assignment that results in your bug. If `current_anim` is assigned a value of type `Button`, then an attempt to later index this value (`self.current_anim[0]`) will result in a crash.

I don't know enough about how this code is supposed to work, but pyright is correct in pointing out a type violation in your code. You'll need to figure out how to fix the bug based on your understanding of your code.

This isn't a bug in pyright, so I'm closing the issue.
