### ISSUE TITLE
Incorrect argument name for attrs class when field starts with an underscore

### ISSUE THREAD

**Issue by rafales** [microsoft/pyright#5658]
So with `attrs` you can have a private field with `_` prefix. But it generates `__init__` argument without the `_` prefix. Like this:

```python

In [12]: import attr

In [13]: @attr.define()
    ...: class Person:
    ...:     name: str
    ...:     _age: int
    ...: 

In [14]: Person
Out[14]: __main__.Person

In [15]: Person(name="John", age=35)
Out[15]: Person(name='John', _age=35)

In [16]: Person(name="John", _age=35)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Person.__init__() got an unexpected keyword argument '_age'

In [17]: Person.__init__
Out[17]: <function __main__.Person.__init__(self, name: str, age: int) -> None>
```

But pyright doesn't recognize that:

<img width="527" alt="Screenshot 2023-08-06 at 13 26 57" src="https://github.com/microsoft/pyright/assets/919812/c1b85faa-26bf-4907-9355-2192bf6d6870">

Note: this is `attrs`-specific functionality, `dataclasses` simply name the argument `_age`.

**Comment by erictraut** [comment]
Pyright has no specific knowledge of `attrs` (or any other third-party libraries). Pyright supports `attrs` through PEP 681 (dataclass_transform) which is used by libraries like `attrs` that have dataclass-like semantics. In places where attrs deviates from dataclass behaviors, these are unsupported in pyright.

You may be able to work around this by using a field description with an `"alias"` argument.
