### ISSUE TITLE
Support of recursive type aliases

### ISSUE THREAD

**Issue by dmlyubim** [microsoft/pyright#569]
For a longer and detailed discussion of recursive types see similar issue in mypy: https://github.com/python/mypy/issues/731

For example, a simple recursive definition of a tree, without specifying leaf node type, could be:

    N=TypeVar['N']
    MyTree= List[[Union['MyTree[N]', N]]]

**Comment by erictraut** [comment]
Note that Pyright already supports recursive types. A class definition, for example, can include class or instance variables that are of the same type as the enclosing class. The problem is specific to type aliases. I've changed the title of the bug to reflect this.

**Comment by erictraut** [comment]
This is now implemented in Pyright 1.1.69, which I just published. It will appear in the next Pylance release as well.
