### ISSUE TITLE
Typeshed for tkinter invalidcommand is not correct

### ISSUE THREAD

**Issue by rafrafek** [microsoft/pyright#5720]
The typeshed for tkinter `ttk.Entry.invalidcommand` uses `tkinter._EntryValidateCommand` which means

```python
TypeAlias = str | list[str] | tuple[str, ...] | Callable[[], bool]
```
but it should use something like
```python
Callable[[], None]
```

https://github.com/microsoft/pyright/blob/393be11e9dd2551d84edead7b21aaf10d1406c7d/packages/pyright-internal/typeshed-fallback/stdlib/tkinter/ttk.pyi#L186

`invalidcommand` is just a function that is called when the `validatecommand` returns False. It is undocumented in the Python docs.

Example snippet for tests:
```python
from tkinter import DoubleVar, Tk
from tkinter.ttk import Button, Entry, Frame, Label

root = Tk()
root.resizable(False, False)
validate_value = root.register(lambda value: False), "%P"
frame = Frame(root, padding=10)
frame.grid()
Label(frame, text="Hello World!").grid(column=0, row=0)
txt = DoubleVar(value=4.5)
Label(frame, textvariable=txt).grid(column=1, row=1)
Entry(
    frame,
    textvariable=txt,
    validate="all",
    validatecommand=validate_value,
    invalidcommand=lambda: print("Validation error!"),  # <-- Wrong typeshed
).grid(column=1, row=2)
Button(frame, text="Quit", command=root.destroy).grid(column=2, row=3)
root.mainloop()
```

The lambda below should be allowed here:

<img width="482" alt="image" src="https://github.com/microsoft/pyright/assets/23004737/d4bc4df0-0d73-47dd-8ee7-500a8419bd00">

**Comment by erictraut** [comment]
Pyright consumes the typeshed stubs from the [typeshed project](https://github.com/python/typeshed). If you think there's a bug in a stub, please report the error (or even better, submit a PR) there.
