### ISSUE TITLE
Recursive coroutine call shows error

### ISSUE THREAD

**Issue by albireox** [microsoft/pyright#5745]
## Environment data

-   Language Server version: 2023.8.31 (pyright 03f79a81)
-   OS and version: macOS 13.5
-   Python version (& distribution if applicable, e.g. Anaconda): pyenv 3.11.3

## Code Snippet

```python
async def test():
    await test()
    return
```

## Repro Steps

It seems that a coroutine that calls itself is evaluated as a function. See the minimum example above. That throws an error `"None" is not awaitable`.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.324, which I just published. It will also be included in a future release of pylance.
