### ISSUE TITLE
Type narrow a tuple of union

### ISSUE THREAD

**Issue by hwong557** [microsoft/pyright#5769]
Is `pyright` able to type narrow a container (list or tuple) of unions? In the below example, inside the `if` statement, `seq` is a `tuple[str]`. How can I make pyright infer this? Thanks! `pyright` is a fantastic tool.

```
def my_func(seq: tuple[str | int]):
    if all(isinstance(x, str) for x in seq):
        reveal_type(seq) # presently pyright thinks seq is tuple[str | int]

```

I'm on version 1.1.323.

**Comment by erictraut** [comment]
Narrowing the type of a mutable container (such as `list` or `set`) is generally unsafe. The type `list[str]` is not a subtype of `list[str | None]`. (For additional details, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts?id=generic-types).)

Tuples are immutable, so `tuple[str]` _is_ a subtype of `tuple[str | int]`. That means this type narrowing would be safe.

The use of the `all` function isn't a supported type guard pattern in pyright (or in any other Python type checker, to my knowledge). For a complete list of supported type guard patterns in pyright, see [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards). Type guard patterns are incredibly specific — following distinct syntactical forms. It's unlikely that we'd ever support something as complex as the expression form in your code sample above.

If you want to handle more complex type guard patterns, you can use a user-defined type guard described in [PEP 647](https://peps.python.org/pep-0647/). (Full disclosure: I authored this PEP.) Here's what that might look like for your code sample:

```python
from typing import TypeGuard

def is_str_tuple(seq: tuple[str | int]) -> TypeGuard[tuple[str]]:
    return all(isinstance(x, str) for x in seq)

def my_func(seq: tuple[str | int]):
    if is_str_tuple(seq):
        reveal_type(seq)
```

Of course, you can generalize this type guard function using generics.
