### ISSUE TITLE
String keys in dictionaries incorrectly raise reportGeneralTypeIssues issue: Type "Literal[...]" is not hashable

### ISSUE THREAD

**Issue by syedtaqi95** [microsoft/pyright#5801]
**Describe the bug**
Steps:
1. Start IDE with pyright version >= 1.1.323 (e.g. VSCode with pylance v2023.8.40) and reportGeneralTypeIssues enabled as a warning/error. Alternatively install pyright (via pip, poetry etc.) to use its CLI. 
2. Create a new Python file and create a dictionary object with string key.
3. (Optional) If using pyright CLI, run `python -m  pyright`

Expected behaviour:
No warning/error reported by pyright/pylance.

Actual behaviour:
Pylance/pyright reports the following error:

```
Dictionary key must be hashable
  Type "Literal['key1']" is not hashable
```

**Note:** From my tests, this bug does not occur in pyright versions <= v1.1.322. So looks like a change made in v1.1.323 has introduced this bug.

**Code or Screenshots**

Python code:
```python
my_dict = {"key1": 1}
```

**VS Code extension or command-line**
Pyright (using CLI) >= v1.1.323
Pylance VSCode extension >= v2023.8.40

**Comment by erictraut** [comment]
I'm not able to repro the reported issue. Can you confirm that you are able to repro the problem with just the single line of code above? Or is additional context required?

Which version of python are you using? Are you using custom typeshed stubs? Do you have any other non-default settings specified in your configuration?

**Comment by syedtaqi95** [comment]
That was a good question which led to me to the solution. I am using a private fork of typeshed in my project which was out of date. After synchronising my typeshed fork with the original repo the issue has gone away. Thanks!
