### ISSUE TITLE
Experimental TypeGuard doesn't support `type` the same as original TypeGuard

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pyright#5815]
Using this code here, the revealed type of cls is different with the experimental support on:

```python
class C():
    c_member: int
    pass

def is_c(o: type) -> TypeGuard[type[C]]:
    return o.__annotations__.get('c_member') != None

def func4(cls: type):
    if is_c(cls):
        reveal_type(cls)
```

With experimental support off, the type cls is `type[C]`, with experimental support on, the type is `type`. 

I believe this is breaking some of the mypy primer validation on this run here:
https://github.com/microsoft/pyright/pull/5813

At least the pydantic error that is new is a result of this problem.

**Comment by erictraut** [comment]
This is included in pyright 1.1.325, which I just published. It will also be included in an upcoming pylance release.
