### ISSUE TITLE
Obsolete example in mypy comparison docs

### ISSUE THREAD

**Issue by hamdanal** [microsoft/pyright#5818]
**Describe the bug**
The example in this section https://microsoft.github.io/pyright/#/mypy-comparison?id=narrowing-for-implied-else in the docs type checks correctly by mypy now

**Code or Screenshots**
```python
class Color(Enum):
    RED = 1
    BLUE = 2

def is_red(color: Color) -> bool:
    if color == Color.RED:
        return True
    elif color == Color.BLUE:
        return False
    # mypy reports error: Missing return statement
```

**VS Code extension or command-line**
N/A

**Comment by erictraut** [comment]
Thanks! I've updated the documentation accordingly.
