### ISSUE TITLE
"Type variable has no meaning in this context" when casting a decorator

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/pyright#5821]
**Describe the bug**
When typing an existing generic (in this case, a decorator), `pyright` does not seem to like my use of a type variable. In the code below, see how `retry1` works fine before `cast`ing but fails afterwards. This works in mypy, but having read https://github.com/microsoft/pyright/issues/3806#issuecomment-1208343640, I suspect that `pyright` is behaving as intended (*) and I should wait for Python 3.12 and PEP 695.

(*) right? I wonder if that is true, as PEP 695 says that "their semantic meaning is valid only when used within the context of a generic class, function, or type alias", and I wonder if `Callable[[F], F]` should provide said "context of a generic [...] function".

**Code or Screenshots**
```python
from collections.abc import Callable
from typing import Any, TypeVar, cast

F = TypeVar("F", bound=Callable[..., Any])

# This typed decator works fine: the decorated function
# has the same type as the original function:
def retry1(fun: F) -> F:
    return fun

# Now imagine `retry1`` was untyped, and I wanted to type it:
retry2 = cast(Callable[[F], F], retry1)
# > error: Type variable "F" has no meaning in this context

def undecorated(_value: int) -> str:
    ...

@retry1
def decorated1(_value: int) -> str:
    ...

@retry2
def decorated2(_value: int) -> str:
    ...

reveal_type(retry1)
reveal_type(retry2)

reveal_type(undecorated)
reveal_type(decorated1)
# As a result, decorated2 is typed incorrectly:
reveal_type(decorated2)
```

**VS Code extension or command-line**
pyright 1.1.324 via command line

**Comment by bersbersbers** [comment]
For the record, here's a workaround that I found using `Protocol`:

```python
from collections.abc import Callable
from typing import Any, Protocol, TypeVar, cast

F = TypeVar("F", bound=Callable[..., Any])

class Decorator(Protocol):
    def __call__(self, _fun: F) -> F:
        ...

def retry1(fun: F) -> F:
    return fun

retry3 = cast(Decorator, retry1)

def undecorated(_value: int) -> str:
    ...

@retry3
def decorated3(_value: int) -> str:
    ...

reveal_type(retry3)
reveal_type(undecorated)
reveal_type(decorated3)
```

**Comment by erictraut** [comment]
This is correct behavior. A type variable has meaning only when scoped to a function (a `def` statement), a class, or a type alias. You're using a type variable in a location where it is not associated with a legal scope.

The correct way to do this is through the use of a callback protocol.

```python
class IdentityProto(Protocol):
    def __call__(self, val: F, /) -> F:
        ...

retry2 = cast(IdentityProto, retry1)
```

When working on PEP 695, there was some discussion about providing some way to specify type parameters that are scoped to a `Callable` type annotation, but we decided that it was out of scope (and orthogonal to the main objectives of the PEP).

**Comment by gh-andre** [comment]
> A type variable has meaning only when scoped to a function (a def statement), a class, or a type alias.

This is what the error message should really say
