### ISSUE TITLE
Conditional matches narrowing not correctly performed

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#5824]
**Describe the bug**
Conditionals do not narrow types correctly in match or regular exhaustive if statements. 

**Code or Screenshots**
<img width="761" alt="Screenshot 2023-08-26 at 23 38 38" src="https://github.com/microsoft/pyright/assets/50501825/1cdf8190-32ad-4db5-9a61-e88f69354bdb">

```python
from typing import Any, assert_type

x: int | None = Any
y: int | None = Any
print(x, y)
match (x, y):
    case (None, None):
        assert_type(x, None)
        assert_type(y, None)
    case (None, _):
        assert_type(x, None)
        assert_type(y, int)
    case (_, None):
        assert_type(x, int)
        assert_type(y, None)
    case _:
        assert_type(x, int)
        assert_type(y, int)

# similar case with if statements
from typing import Any, assert_type

x: int | None = Any
y: int | None = Any
print(x, y)
if x is None and y is None:
    assert_type(x, None)
    assert_type(y, None)
elif x is None and y is not None:
    assert_type(x, None)
    assert_type(y, int)
elif x is not None and y is None:
    assert_type(x, int)
    assert_type(y, None)
else:
    assert_type(x, int)  # errors down here
    assert_type(y, int)
```

**VS Code extension or command-line**
pylance v2023.8.40

**Comment by erictraut** [comment]
Yes, this is by design. Pyright does not track conditional types (what I sometimes refer to as "entanglement") between symbols. This would require the type checker to track conditions like "the type of `x` is `int` if the type of `y` is `None` otherwise the type of `x` is `int | None`". You can see how this would quickly become infeasible to track. For this reason, I'm not aware of any type checker or compiler in any language that does this.

**Comment by Gobot1234** [comment]
Understood, a followup question, changing the code to use bindings
```py
match (x, y):
    case (None, None):
        assert_type(x, None)
        assert_type(y, None)
    case (None, new_y):
        assert_type(new_y, int)
    case (new_x, None):
        assert_type(new_x, int)
    case (new_x, new_y):
        assert_type(new_x, int)
        assert_type(new_y, int)
```
Does this still require entanglement types? Cause it seems to still work for the bottom couple of cases but just not on the first or has it been put into an invalid state?

**Comment by erictraut** [comment]
The subject expression initially has the type `tuple[int | None, int | None]`. The pattern `(None, None)` does not allow this to be narrowed in the negative (fall-through) case, so the type is still `tuple[int | None, int | None]` when the next case statement is considered for narrowing.

Pyright contains some special-case handling to handle match statements where the subject is a tuple of known length and one entry in the tuple is narrowed by a pattern. For example:

```python
match (x, y): # Subject type is tuple[int | None, int | None]
    case (None, _): # Positive narrowed type is tuple[None, None], negative narrowed type is tuple[int, int | None]
        assert_type(y, int | None)
    case (_, None): # Positive narrowed type is tuple[int, None], negative narrowed type is tuple[int, int]
        assert_type(x, int)
    case (_, _):
        assert_type(x, int)
        assert_type(y, int)
```

In this example, the subject type is initially `tuple[int | None, int | None]` (which has a known length), and the first case statement pattern affects only the first element, narrowing it to `int` in the negative (fall-through) case. That means the narrowed subject type is narrowed to `tuple[int, int | None]` in the fall-through case. The next case statement affects only the second entry of the tuple, so the type is narrowed to `tuple[int, int]` in the fall-through case.

It would be theoretically possible with your previous example to narrow `tuple[int | None, int | None]` to `tuple[int, int | None] | tuple[int | None, int]` in the fall-through case, but this quickly blows up in complexity (O(n!) where n is the number of affected elements in the tuple). For that reason, I decided to limit this support to the case where a single tuple entry is affected. This special-case handling already goes well beyond what mypy does.

Regardless of how sophisticated the type checker's type narrowing logic is, there will always be ways to structure your code to defeat the type checker. Likewise, there's always ways to structure your code to work within the limits of the type narrowing logic.

**Comment by Gobot1234** [comment]
Thanks for the detailed response
