### ISSUE TITLE
Support type narrowing of Literal unions

### ISSUE THREAD

**Issue by yangchoo** [microsoft/pyright#5837]
**Is your feature request related to a problem? Please describe.**
Support type narrowing of Literal unions using any type guard.

Currently, using the `x in y` type guard fails compiler checks.
```python
BirdType = Literal[ "raven", "tern"]
AnimalType = Literal["raven", "tern", "cat"]

def feed_bird(animal: AnimalType):
  assert animal in get_args(BirdType)
  if animal == "raven":
    ...
  elif animal == "tern":
   ...
  else:
    assert_never(animal)   # this fails
```

**Describe the solution you’d like**
Support type narrowing of Literal unions. This can be via the `get_args` pattern which works in runtime or any other type guard.

**Comment by yangchoo** [comment]
I'll admit I'm not a Python types expert and perhaps there is a better approach. Open to hearing any other potential solutions to accomplish the same intent.

**Comment by erictraut** [comment]
Pyright already supports type narrowing based on the `x == <literal>` pattern. It also supports the `x in y` pattern, which appears in the assert statement in the code above. For a complete list of supported type narrowing patterns, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards).

The issue with this code sample is that it's confusing type expressions with value expressions. The statement `BirdType = Literal["raven", "tern"]` defines a type alias that is intended to be used in type annotations, but you're using it in a value expression. The `get_args` call is intended for code that needs to do runtime introspection for purposes of dynamic type checking. It's not something that typical code would call. It's unlikely that we'd add special-case logic to support it for purposes of static type checking.

If you change your assert to `assert animal in ("raven", "tern")`, that avoids mixing type expressions and value expressions, and the code will type check without errors.

**Comment by yangchoo** [comment]
Thanks for the quick reply!

> assert animal in ("raven", "tern")

I understand that works. Apologies for not phrasing the request more precisely.

Fundamentally, I'm looking for a way to avoid redefining the type expression again as a value expression to avoid the problem of keeping these in-sync.
I.e.
```python
BirdType = Literal["raven", "tern"]
BIRD_TYPES = ("raven", "tern")
```

`get_args` seemed to be an elegant way to do so. Is there another way of accomplishing the compiler check without having to explicitly redefine?

**Comment by erictraut** [comment]
I don't think there's a way to do this in the Python static type system without redefining. Type expressions and value expressions should remain separate. 

You could switch to a dataclass hierarchy.

```python
from dataclasses import dataclass
from typing import Literal, assert_never

@dataclass
class Animal:
    species: Literal["raven", "tern", "cat"]

@dataclass
class Bird(Animal):
    species: Literal["raven", "tern"]

def feed_bird(animal: Animal):
    assert isinstance(animal, Bird)

    if animal.species == "raven":
        ...
    elif animal.species == "tern":
        ...
    else:
        assert_never(animal.species)
```

There might also be some creative things you could do with Enums.

**Comment by wyattscarpenter** [comment]
@yangchoo In case you're still interested in this question, I learned of a solution from https://stackoverflow.com/questions/64522040/dynamically-create-literal-alias-from-list-of-valid-values/64522240#64522240 . It goes like this:

```py
from typing import Literal, get_args, assert_never, reveal_type

BirdType = Literal[ "raven", "tern"]
birds: tuple[BirdType, ...] = get_args(BirdType)
AnimalType = Literal["raven", "tern", "cat"]

def feed_bird(animal: AnimalType):
  assert animal in birds
  if animal == "raven":
    ...
  elif animal == "tern":
   ...
  else:
    assert_never(animal)   # this works perfectly, and successfully asserts never
```
get_args returns Any, and we can (ab)use this fact to immediately assign its result to a tuple annotated with the very same type we got the args from. This gives us a usable version of the type, without duplicating the data definition! (Technically, the expressions could still get out of sync, if someone changed how `birds` was defined, but that's much less likely, ime.)

**Comment by yangchoo** [comment]
@wyattscarpenter Thanks for the tag! That seems like a reasonable enough solution for now. Still somewhat suboptimal in terms of needing to remember an additional explicit tag, but better than most of the alternatives for something lightweight and quick.
