### ISSUE TITLE
Better inference for zip

### ISSUE THREAD

**Issue by mikeshardmind** [microsoft/pyright#5842]
If you have a question about a behavior that you’re seeing in pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**

given the following

```py
x: Iterable[tuple[*Ts]
x1, x2, *xn = zip(*x)
```
the types of x1-xn should be inferable from the typevartuple

Note, this also doesn't work with the toy case:
```py
x: list[tuple[int, str]] = [(i, str(i)) for i in range(10)]
ints, strs = zip(*x)
```

**Describe the solution you’d like**

There's not really a clear way to go about this with better type stubs. Even if the proposed Map originally left out of PEP 646 gets accepted, `__next__` on the iterator would need to be a Union type still. The preferred solution would be similar to the special support for partial that some type checkers have, adding additional support for the specific case with zip, where it is immediately unpacked and not kept in scope.

**Comment by erictraut** [comment]
For the first code sample, I'm not sure if I should assume that `Ts` represents a `TypeVarTuple` or whether you meant it to be psuedo-code that represents "any concrete tuple type".

Is this what you intended?

```python
from typing import Iterable, TypeVarTuple

Ts = TypeVarTuple("Ts")

def func(x: Iterable[tuple[*Ts]]):
    x1, x2, *xn = zip(*x)

    reveal_type(x1)  # Currently reveals "tuple[Union[*Ts]]"
```

If so, what type would you prefer be revealed on the last line? I can't think of any better (more precise) type in this case.

As for the second example, I agree that special-casing of `zip` could produce a more correct answer (a narrower type). Overriding the typeshed definition of a function and providing special-case logic is something we try to avoid in pyright. We've made only a few exceptions to this rule, including `functools.partial` and `functools.total_ordering`. Those are both calls that mypy special-cases, and we received dozens of upvotes from pyright users for these. While we've received some requests for improved inference for `zip`, I don't think we've received enough feedback to meet the bar for special-casing this. Also, it appears that mypy hasn't implemented anything special for `zip` either. If either of these factors changes, I'd be open to revisiting this decision.

**Comment by mikeshardmind** [comment]
> For the first code sample, I'm not sure if I should assume that Ts represents a TypeVarTuple or whether you meant it to be psuedo-code that represents "any concrete tuple type".

Is this what you intended?

> If so, what type would you prefer be revealed on the last line? I can't think of any better (more precise) type in this case.

`tuple[Ts[0]]`

so if the input type was:
```
Iterable[tuple[int, str, bool, bytes]]
```
then the types I'd want inferred: 
```
x1: tuple[int]
x2: tuple[str]
xn: Iterable[tuple[bool | bytes]
```

The case of xn is unfortunate, with this example, but that's partially the point here. It's really a fixed length(2) Iterable where the first element is a tuple of bools and the second element is a tuple of bytes, which there's also not a good way to express (or zip wouldn't be hard to express)

zip just transposes the layout here. So the heterogenous tuples become homogenous as if we were looking at rows and switched to looking at columns.

If seeing an example would help:

```py
>>> data = [(i, str(i), bool(i), i.to_bytes(8)) for i in range(10)]
>>> a, b, *c = zip(*data)
>>> a
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
>>> b
('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')
>>> c
[(False, True, True, True, True, True, True, True, True, True), (b'\x00\x00\x00\x00\x00\x00\x00\x00', b'\x00\x00\x00\x00\x00\x00\x00\x01', b'\x00\x00\x00\x00\x00\x00\x00\x02', b'\x00\x00\x00\x00\x00\x00\x00\x03', b'\x00\x00\x00\x00\x00\x00\x00\x04', b'\x00\x00\x00\x00\x00\x00\x00\x05', b'\x00\x00\x00\x00\x00\x00\x00\x06', b'\x00\x00\x00\x00\x00\x00\x00\x07', b'\x00\x00\x00\x00\x00\x00\x00\x08', b'\x00\x00\x00\x00\x00\x00\x00\t')]
```

As for usefulness, this came up when dealing with some data processing where we need to preprocess columns of data. rearranging the data this way ended up faster to do in python to *then* pipeline to native code. there's a type ignore and a long comment currently, but this seems like something that there's *almost* enough support for in the type system as is. Maybe the case of *xn doesn't need to be supported better than what's above since I imagine most people would unpack to a matching length.

**Comment by erictraut** [comment]
`tuple[Ts[0]]` isn't a valid type in the Python type system. You can't index into a TypeVarTuple. You can index into a tuple, once a TypeVarTuple has been replaced by a concrete type, but this code sample doesn't involve a concrete type. Even with a concrete type, it may not be possible (or may be ambiguous) to index into a tuple. For example, if the concrete version of the TypeVarTuple was `tuple[()]` (the empty tuple) or `tuple[*tuple[str, ...], float]` (a tuple with an indeterminate number of entries).

As for the special-casing of `zip`, I don't think there's enough signal to justify that at this time. It's something we might consider in the future based on pyright user feedback, but I'm going to close this for now.

**Comment by mikeshardmind** [comment]
> `tuple[Ts[0]]` isn't a valid type in the Python type system. 

yeah, but that would be the intent And why I mentioned:

> [..]for the specific case with zip, where it is immediately unpacked and not kept in scope.
and
> [...]but the type checker would need to know the input types at the point it reaches zip for this to work.

This one's really about the lack of the type system having good ways to express parts of this even if we can conceptualize clear rules for how it behaves with types in common use patterns of zip.

> As for the special-casing of `zip`, I don't think there's enough signal to justify that at this time. It's something we might consider in the future based on pyright user feedback, but I'm going to close this for now.

Alright, thanks for taking the time to consider it. Perhaps this needs more in the type system itself before this can be supported better. 

In case it matters for future resisting of this, In my own use, I can say at least that your concern about indeterminate length tuples is not something I would need limited special support for, nor the example with `*xn`, which was more provided for conceptual completeness.
Unpacking to a number of variables that are known to be equal in length to the type variable tuple in the example above covers my needs.

**Comment by matrs** [comment]
What about a simpler case as:
```py
def test_process_vcomps(proc_vcomps: ValidCompsDict, pre_vcomps: ValidCompsDict):
    for (qidx, vcomps), (pre_qidx, pre_vcomps) in zip(  # type: ignore
        proc_vcomps.items(), pre_vcomps.items()
    ):
        for vcomp, pre_vcomp in zip(vcomps, pre_vcomps):
            store_counter[vcomp.store] += 1
            pre_store_counter[pre_vcomp.store] += 1 # pylance only warning
```
in this first `for` loop, `pywright` infers everything correctly, first tuple elements as int, second as a `ValidComps` object,   except for `pre_vcomps`, which it should be the same type as the inferred type of `vcomps`, but it says it is  a `ValidCompsDict`. This produces to infer `pre_vcomp` in the second loop as an `int` instead of a `ValidComp` object, which causes the complain with `pre_vcomp.store`.

I'm using  an up to date vscode with `pylance-2024.5.100`.
