### ISSUE TITLE
Callable protocol definition and ParamSpec issue

### ISSUE THREAD

**Issue by lmazuel** [microsoft/pyright#5844]
**Describe the bug**

I define a callable protocol following the official doc of [Annotating callable object](https://docs.python.org/3/library/typing.html#annotating-callables). Especially the part of the end that says:

> Callable cannot express complex signatures such as functions that take a variadic number of arguments, [overloaded functions](https://docs.python.org/3/library/typing.html#typing.overload), or functions that have keyword-only parameters. However, these signatures can be expressed by defining a [Protocol](https://docs.python.org/3/library/typing.html#typing.Protocol) class with a [__call__()](https://docs.python.org/3/reference/datamodel.html#object.__call__) method

In particular, I define a decorator that adds a keyword only argument to the function it decorates, and I use a callable protocol to define this kwarg-only parameter. I can't get pyright to be happy while mypy is super happy with it.

**Code or Screenshots**

This is a mypy playground:
https://mypy-play.net/?mypy=latest&python=3.11&gist=bba538a9212466a819ffb0343c925b84

You can see that mypy has no issue to type check everything, include on purposed wrong code.

While I run the same file on Pyright, I get this:
```
  callable_paramspec.py:11:30 - error: Keyword parameter "something_added" cannot appear in signature after ParamSpec args parameter (reportGeneralTypeIssues)
  callable_paramspec.py:20:28 - error: Keyword parameter "something_added" cannot appear in signature after ParamSpec args parameter (reportGeneralTypeIssues)
  callable_paramspec.py:24:16 - error: Expression of type "_Wrapped[P@my_decorator, T@my_decorator, (*args: P.args, something_added: bool = False, **kwargs: P.kwargs), T@my_decorator]" cannot be assigned to return type "TracedMethod[P@my_decorator, T@my_decorator]"
    "_Wrapped[P@my_decorator, T@my_decorator, (*args: P.args, something_added: bool = False, **kwargs: P.kwargs), T@my_decorator]" is incompatible with protocol "TracedMethod[P@my_decorator, T@my_decorator]"
      "__call__" is an incompatible type
        Type "(*args: P.args, something_added: bool = False, **kwargs: P.kwargs) -> T@my_decorator" cannot be assigned to type "(*args: P.args, something_added: bool = False, **kwds: P.kwargs) -> T@TracedMethod"
          Parameter 1: type "*tuple[P.args, ...]" cannot be assigned to type "*tuple[P.args, ...]"
            "builtins.tuple" is incompatible with "builtins.tuple"
          Parameter 3: type "P.kwargs" cannot be assigned to type "P.kwargs"
            Type "P.kwargs" cannot be assigned to type "P.kwargs" (reportGeneralTypeIssues)
```

I'm using pyright 1.1.324, and Python 3.11.4.

**Comment by erictraut** [comment]
You're adding a parameter between `*args` and `**kwargs` in `TraceMethod.__call__` and further below in the `wrapper` function. This is expressly forbidden in PEP 612 for reasons explained in the PEP. Here's the exact text:

> Note that this also why we have to reject signatures of the form `(*args: P.args, s: str, **kwargs: P.kwargs)`.

Mypy [has a bug](https://github.com/python/mypy/issues/14832) where it doesn't correctly identify this error. 

You'll need to fix the bug in your code if you want it to work with type checkers that comply with the PEP 612 spec.

**Comment by lmazuel** [comment]
Thanks @erictraut, while I read the PEP I didn't find this part.

So it means I can't type this for now, as my decorator is adding a kwarg only parameter and I can't change that fact :(. Thanks for your prompt response.

**Comment by Kroppeb** [comment]
Ah, this sucks. I assumed this would work.
