### ISSUE TITLE
Bug on inference for dict

### ISSUE THREAD

**Issue by rayansostenes** [microsoft/pyright#5846]
There's a bug on the inference for dicts when they are constructed from a tuple of tuples.

```python
new_dict = dict((("a", 1), ("b", 2)))

reveal_type(new_dict)
# Type of "new_dict" is "dict[Literal['a', 'b'], Literal[1, 2]]"

new_dict["c"] = 3
# Argument of type "Literal['c']" cannot be assigned to parameter "__key" of type "Literal['a', 'b']" in function "__setitem__"
#   Type "Literal['c']" cannot be assigned to type "Literal['a', 'b']"
#     "Literal['c']" cannot be assigned to type "Literal['a']"
#     "Literal['c']" cannot be assigned to type "Literal['b']"
# Argument of type "Literal[3]" cannot be assigned to parameter "__value" of type "Literal[1, 2]" in function "__setitem__"
#   Type "Literal[3]" cannot be assigned to type "Literal[1, 2]"
#     "Literal[3]" cannot be assigned to type "Literal[1]"
#     "Literal[3]" cannot be assigned to type "Literal[2]"
```

I honestly kind of like this error, it gives me a way to "almost" build an immutable dict.
And I really hate having to write TypedDict definitions for every small dict.

**Comment by erictraut** [comment]
This is working as intended.

For details about pyright's default inference rules, refer to the documentation [for tuple expressions](https://microsoft.github.io/pyright/#/type-inference?id=tuple-expressions) and [for dictionary expressions](https://microsoft.github.io/pyright/#/type-inference?id=dictionary-expressions).

If you want to override the default inference rules, you can use an explicit type declaration.

```python
new_dict: dict[str, int] = dict((("a", 1), ("b", 2)))
```
