### ISSUE TITLE
Classes inheriting from NamedTuple can't be assigned to a relevant protocol

### ISSUE THREAD

**Issue by mrzor** [microsoft/pyright#5849]
**Description**
The [NamedTuple typeshed](https://github.com/python/typeshed/blob/8888ac0d6dcb2d20b1621550cb64b69eba289f11/stdlib/typing.pyi#L861) specifies `_fields` as a `ClassVar[tuple[str, ...]]`. However I cannot figure out a way to satisfy both caller and callee typing when using it.

**Code**

~~~python
from typing import NamedTuple, Protocol, TypeVar, ClassVar, Type

class Thing(NamedTuple):
    stuff: int

class NamedTuplishA(Protocol):
    _fields: ClassVar[tuple[str, ...]]

class NamedTuplishB(Protocol):
    _fields: tuple[str, ...]

TA = TypeVar("TA", bound=NamedTuplishA)
def demoA(t: Type[TA]) -> TA:
    print(t._fields)  # OK
    return t()
demoA(Thing)  # KO: Type[Thing] cannot be assigned to NamedTuplishA

TB = TypeVar("TB", bound=NamedTuplishB)
def demoB(t: Type[TB]) -> TB:
    print(t._fields)  # KO: NamedTuplishB does not define _fields as a ClassVar
    return t()
demoB(Thing)  # OK
~~~

I'd like a way to have both caller and callee be OK.

**Usage**
Seen using pyright 1.1.325 using emacs lsp-mode

**Comment by erictraut** [comment]
The `_fields` attribute in a `NamedTuple` is not writable, so it must be defined in the protocol as read-only. Python lacks a direct way (such as a `readonly` keyword) to specify that an attribute is read-only, so [PEP 544](https://peps.python.org/pep-0544/) (which introduced `Protocol`) indicates that you should use a `@property` in the protocol definition.

```python
class NamedTuplishA(Protocol):
    @property
    def _fields(self) -> tuple[str, ...]:
        ...
```

**Comment by mrzor** [comment]
Thank you for the clarification. I have tried out your suggestion like so:

~~~python
from typing import NamedTuple, Protocol, TypeVar, Type

class Thing(NamedTuple):
    stuff: int

class NamedTuplishA(Protocol):
    @property
    def _fields(self) -> tuple[str, ...]:
        ...

TA = TypeVar("TA", bound=NamedTuplishA)
def demoA(t: Type[TA]) -> TA:
    print(t._fields)  # KO: Cannot access member "_fields" for type "Type[NamedTuplishA]*"
    return t()
demoA(Thing)  # OK
~~~

And yet it produces a type error different from the previous ones.

---

> The _fields attribute in a NamedTuple is not writable

I do not believe this statement to be accurate, as the following snippet highlights:

~~~python
#! python-3.11.3

from typing import NamedTuple

class Thing(NamedTuple):
    n: int
 
print(Thing._fields)  # => ('n')
Thing._fields = tuple()  # OK: that works
print(Thing._fields)  # => ()
t = Thing(1) # OK: the class appears to be functional w.r.t. creating new instances
print(t)  # => Thing(n=1)
~~~

I do agree that writing to `_fields`  is terrible taste, and maybe it _should_ have been read-only, but AFAICT it is not.

**Comment by erictraut** [comment]
This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.326, which I just published. It will also be included in a future release of pylance.

**Comment by mrzor** [comment]
Thank you very much for your consideration in implementing a fix.

I updated pyright moments ago and could unfortunately not not observe the hoped-for change in behavior.

Notably, the following test case - which is my best transcription of your initial recommendations - does not validate:
~~~python
from typing import NamedTuple, Protocol, TypeVar, Type

class Thing(NamedTuple):
    stuff: int

class NamedTuplishA(Protocol):
    @property
    def _fields(self) -> tuple[str, ...]:
        ...

TA = TypeVar("TA", bound=NamedTuplishA)
def demoA(t: Type[TA]) -> TA:
    print(t._fields)  # KO: Cannot access member "_fields" for type "Type[NamedTuplishA]*"
    return t()
demoA(Thing)  # OK
~~~

I tried the following alternative version, which didn't validate either:
~~~python
from typing import NamedTuple, Protocol, TypeVar, Type, ClassVar

class Thing(NamedTuple):
    stuff: int

class NamedTuplishA(Protocol):
    _fields: ClassVar[tuple[str, ...]]

TA = TypeVar("TA", bound=NamedTuplishA)
def demoA(t: Type[TA]) -> TA:
    print(t._fields)  # OK
    return t()
demoA(Thing)  # KO
# Argument of type "Type[Thing]" cannot be assigned to parameter "t" of type "Type[TA@demoA]" in function "demoA"
#   Type "Thing" cannot be assigned to type "NamedTuplishA"
#     "Thing" is incompatible with protocol "NamedTuplishA"
#       "_fields" is not a class variable (lsp)
~~~

It looks like the `"_fields" is not a class variable (lsp)` is the root of the misunderstanding for the second case.

**Comment by erictraut** [comment]
When you define a property within a `Protocol`, you must access it through an instance of the protocol class, not through the protocol class itself. In your first code sample above, you're attempting to access it through `type[TA]` which is the protocol class, not an instance.

Your second code sample above type checks without error using the latest version of pyright (1.1.326).
