### ISSUE TITLE
Cannot type `self` for overloads of enum methods

### ISSUE THREAD

**Issue by NCPlayz** [microsoft/pyright#5857]
**Describe the bug**
I was trying to write an overload for a method of an Enum but encountered an issue where Pyright seemed to say either `"Type" is not defined` if I typed `self` as `Literal[Enum.value]` or `Type arguments for "Literal" must be None, a literal value (int, bool, str, or bytes), or an enum value` if I typed `self` as `Literal[value]`.

**Code or Screenshots**

Was trying to implement something along the lines of this:
```python
from __future__ import annotations

from enum import Enum
from typing import Literal, overload


class Type(Enum):
    integer = 1
    boolean = 2

    @overload
    def parse(self: Literal[Type.integer], expr: str) -> int: # "Type" is not defined
        ...

    @overload
    def parse(self: Literal[Type.boolean], expr: str) -> bool: # "Type" is not defined
        ...

    def parse(self, expr: str) -> int | bool:
        if self == Type.integer:
            return int(expr)
        elif self == Type.boolean:
            return expr in ["yes", "no"]
```

**VS Code extension or command-line**
`Pylance language server 2023.8.40 (pyright 03f79a81)`

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.326, which I just published. It will also be included in a future release of pylance.
