### ISSUE TITLE
TypeVar/ParamSpec top-level scoping issue

### ISSUE THREAD

**Issue by A5rocks** [microsoft/pyright#5866]
**Describe the bug**

I can't type a variable a certain type as typevar scoping is not done at the top level, but I *can* get a function to return that exact same type.

This is kind of https://github.com/microsoft/pyright/issues/5821 but I think the fact you can assign it as a function return type makes it a bit different.

This effects https://github.com/python-trio/trio/issues/2775#issuecomment-1701303762 because of https://github.com/python-trio/trio/blob/e97bcb61b8b02523c82435b5408ff46efca5dfc3/trio/_core/_ki.py#L186-L189.

**Code or Screenshots**

```python
from typing import ParamSpec, Callable, TypeVar

ArgsT = ParamSpec("ArgsT")
RetT = TypeVar("RetT")

does_not_work: Callable[[Callable[ArgsT, RetT]], Callable[ArgsT, RetT]]
def does_work() -> Callable[[Callable[ArgsT, RetT]], Callable[ArgsT, RetT]]: ...
```

**VS Code extension or command-line**

Command line, `pyright==1.1.325`.

**Comment by erictraut** [comment]
I think pyright is working correctly here. I don't consider this a bug.

A type variable has meaning only when it is bound to a `def` statement, a `class` statement, or in a type alias definition. 

Pyright has some special-case logic that treats type variables within a `Callable` as though they are bound to that callable in the special case where that callable is returned from another function. That why `does_work` works the way it does.

**Comment by A5rocks** [comment]
Is there any way to export the result from `does_work` at least?

```py
use_this: ??? = does_work()
```

**Comment by erictraut** [comment]
Yes, the right way to do this is through the use of a callback protocol (PEP 544).

```python
from typing import Callable, ParamSpec, Protocol, TypeVar

ArgsT = ParamSpec("ArgsT")
RetT = TypeVar("RetT")

class Callback(Protocol):
    def __call__(self, x: Callable[ArgsT, RetT], /) -> Callable[ArgsT, RetT]:
        ...

does_not_work: Callback

def does_work() -> Callback:
    ...
```

**Comment by A5rocks** [comment]
Ah geh, I had *just* realized I could use a protocol too. Sorry about wasting your time!
