### ISSUE TITLE
checking config file into repo?

### ISSUE THREAD

**Issue by dcsan** [microsoft/pyright#587]
more of a question - what is your suggestion of whether the `pyrightconfig.json` should be checked into a projects repo or kept somewhere like a person's home directory?

My feeling is that it's a project specific configuration file, like an `.eslint`, but I have colleagues who would say its more IDE specific and should be kept out.

interested what others are doing.

Is there a way to have pyright read the config from another directory or use a global user config?

Is there a way to share and merge configs a bit like:
https://eslint.org/docs/developer-guide/shareable-configs

**Comment by erictraut** [comment]
pyrightconfig.json was designed to be checked in to a repo so everyone on a development team gets the same results. This also allows you to use it with a centralized CI (continuous integration) server. I would consider it a project-specific configuration file similar to .eslint, tsconfig.json, .gitignore, etc.

Currently, the command-line version of pyright allows you to specify the path (and file name) of the config file, but the VS Code version of pyright always assumes that it will be in the root of your workspace and will be called "pyrightconfig.json".

There's currently no support for config merging or referencing one config from another.

I'm interested in understanding your use cases in more detail. If there are other users who share similar use cases, we can explore ways to address them.
