### ISSUE TITLE
Expose API similar to `getBestOverloadForArguments` for attributes (`__getattr__`) from `TypeEvaluator`

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#5870]
pylance would like to implement https://github.com/microsoft/pylance-release/issues/4764 

```python
from typing import Any, Literal, overload

class A:
    @overload
    def __getattr__(self, item: Literal['baz']) -> str:
        pass

    @overload
    def __getattr__(self, item: str) -> int | str:
        pass

    def __getattr__(self, item: str) -> Any:
        return None

ab = A()
ab.baz # go to def
```

currently there is no API exposed from type eval that would return right `__getattr__` used for `baz`. internally, it has `applyAttributeAccessOverride` that does most of the work and has `CallResult.overloadsUsedForCall` but it is not exposed anywhere.

currently `Pylance` implemented its own logic to find right `overload` but it would be nice if that info is exposed so that pylance can just use that API like `getBestOverloadForArguments`

**Comment by erictraut** [comment]
The `getBestOverloadForArguments` function is already exposed. What functionality is missing? I presume you already have the type of the `__getattr__` method (returned from `getTypeOfObjectMember`)? If so, you can call `getBestOverloadForArguments` with a single argument of type `Literal['baz']`, and it will return the correct overload. From that, you can determine the declaration for that overload.

Or are you saying that you would prefer that `getDeclarationsForNameNode` automatically handle the logic for `__getattr__` and `__getattribute__` overrides and return the applicable `__getattr__` declaration(s)?

**Comment by heejaechang** [comment]
let me try this

> The getBestOverloadForArguments function is already exposed. What functionality is missing? I presume you already have the type of the __getattr__ method (returned from getTypeOfObjectMember)? If so, you can call getBestOverloadForArguments with a single argument of type Literal['baz'], and it will return the correct overload. From that, you can determine the declaration for that overload.

**Comment by heejaechang** [comment]
so, this is code I wrote to test

parent is pointing to `a.baz`

```ts
        const classType = this._evaluator.getType(parent.leftExpression);
        if (!classType || !isClass(classType)) {
            return undefined;
        }

        const strClassType = this._evaluator.getBuiltInType(parent, 'str') as ClassType;
        const nameLiteralType = ClassType.cloneWithLiteral(
            ClassType.cloneAsInstance(strClassType),
            parent.memberName.value
        );

        const argList: FunctionArgument[] = [
            {
                // Provide "name" argument.
                argumentCategory: ArgumentCategory.Simple,
                typeResult: { type: nameLiteralType },
            },
        ];

        const typeResults = this._evaluator.getTypeOfObjectMember(parent.memberName, classType, '__getattr__');
        if (typeResults && typeResults.type.category === TypeCategory.OverloadedFunction) {
            const bestMethod = this._evaluator.getBestOverloadForArguments(
                parent.memberName,
                typeResults as TypeResult<OverloadedFunctionType>,
                argList
            );

            console.log(bestMethod);
        }
```

it works for `baz` but if I have something like this `a.zoo`, it doesnt return 

```ts
@overload
    def __getattr__(self, item: str) -> int | str:
        pass
```

is it by design?

**Comment by heejaechang** [comment]
oops. ignore. it works as expected. sorry!

**Comment by erictraut** [comment]
There are a number of subtle bugs in the code you posted above. If this code is going to be added to files in the pyright code base, please submit a PR for review.

**Comment by heejaechang** [comment]
the code is in `pylance` but if there is a bug, would like to fix them as well. should I just duplicate/follow what `applyAttributeAccessOverride` does?

**Comment by heejaechang** [comment]
I fixed up a few places

basically, making sure `node.leftExpression` is `class instance` before calling `getTypeOfObjectMember` 

```ts
const instanceType = evaluator.getType(node.leftExpression);
    if (!instanceType || !isClassInstance(instanceType)) {
        return undefined;
    }
```

and gave some flags to `getTypeOfObjectMember` 

```ts
export function getBestMatchGetAttrMethods(evaluator: TypeEvaluator, node: MemberAccessNode) {
    const strClassType = evaluator.getBuiltInType(node, 'str');
    if (!isInstantiableClass(strClassType)) {
        return undefined;
    }

    const instanceType = evaluator.getType(node.leftExpression);
    if (!instanceType || !isClassInstance(instanceType)) {
        return undefined;
    }

    const typeResults = evaluator.getTypeOfObjectMember(
        node,
        instanceType,
        getAttrName,
        { method: 'get' },
        undefined,
        MemberAccessFlags.SkipAttributeAccessOverride | MemberAccessFlags.SkipObjectBaseClass
    );
    if (!typeResults) {
        return undefined;
    }

    if (typeResults.type.category === TypeCategory.Function) {
        return typeResults.type;
    }

    if (typeResults.type.category !== TypeCategory.OverloadedFunction) {
        return undefined;
    }

    const nameLiteralType = ClassType.cloneWithLiteral(ClassType.cloneAsInstance(strClassType), node.memberName.value);
    const argList: FunctionArgument[] = [
        {
            // Provide "name" argument.
            argumentCategory: ArgumentCategory.Simple,
            typeResult: { type: nameLiteralType },
        },
    ];

    const bestMethod = evaluator.getBestOverloadForArguments(
        node.memberName,
        typeResults as TypeResult<OverloadedFunctionType>,
        argList
    );

    return bestMethod;
}
```

**Comment by erictraut** [comment]
You addressed some of the issues I saw in the previous code.

A few minor things that would help readability and make the code more robust:
* Use `isFunction` and `isOverloadedFunction` rather than directly comparing the category of the type.
* Rather than using a `as TypeResult<OverloadedFunctionType>` cast, use `{ type: typeResults.type }`.

Your code handles `__getattr__`, but it doesn't handle `__setattr__` or `__delattr__`. It also doesn't handle `__getattribute__`. The `__getattr__` is the most common of these, but it seems odd that you wouldn't provide support for the others. You'd need to determine which of these is appropriate for the given context (whether it's been read, written, or deleted).
