### ISSUE TITLE
Can't use user-defined kwargs in between ParamSpec args/kwargs 

### ISSUE THREAD

**Issue by diceroll123** [microsoft/pyright#5873]
**Describe the bug**
A method annotated with ParamSpec args/kwargs with user-defined kwargs in between them in the signature _works_ fine, but PyRight/Pylance says `Keyword parameter "delay" cannot appear in signature after ParamSpec args parameter`.

While the code works as expected, the revealed type information for the method does not resolve the ParamSpec args/kwargs, this seems more like a self-inflicted limitation, however I do admit it's a strange use case.

**Code or Screenshots**

```python
from typing import Generic, ParamSpec, TypeVar, Callable, reveal_type
import time

P = ParamSpec("P")
T = TypeVar("T")
R = TypeVar("R")

class Task(Generic[P, R]):
    def __init__(self, func: Callable[P, R]) -> None:
        self.func = func
    
    def dispatch(self, *args: P.args, **kwargs: P.kwargs) -> R:
        return self.func(*args, **kwargs)
    
    def dispatch_with_delay(
        self,
        *args: P.args,
        delay: int | None = None,
        **kwargs: P.kwargs,
    ) -> R:
        if delay:
            print(f"Waiting {delay} secs...")
            time.sleep(delay)
        print("kwargs", kwargs)  # does not include delay, as expected
        return self.func(*args, **kwargs)

def make_task() -> Callable[[Callable[P, R]], Task[P, R]]:
    def decorator(func: Callable[P, R]) -> Task[P, R]:
        return Task[P, R](func)
    return decorator

@make_task()
def say_thing(text: str) -> None:
    print(f"Saying the thing: {text}")

@make_task()
def say_thing_kwarg(*, text: str) -> None:
    print(f"Saying the thing with kwarg: {text}")

def say_thing_later() -> None:
    say_thing.dispatch("blah")
    say_thing.dispatch_with_delay("blah but delayed", delay=2)
    say_thing_kwarg.dispatch_with_delay(delay=2, text="blah but delayed")  # this works but... at what cost to sanity?

reveal_type(say_thing.dispatch)
reveal_type(say_thing_kwarg.dispatch_with_delay)

say_thing_later()
```

![image](https://github.com/microsoft/pyright/assets/1243957/8f6b9b17-b120-4539-9d51-a096738a8814)

![image](https://github.com/microsoft/pyright/assets/1243957/ce6d8ce1-f3c3-4c1e-b875-344b337104df)

**VS Code extension or command-line**
Pylance v2023.8.51

**Comment by hmc-cs-mdrissi** [comment]
This specific case is not supported in PEP 612 that defined in ParamSpec. It would be nice feature and I have seen use cases like yours where it makes sense, but at moment according to type system specification there is no way to add keyword args with paramspec. This issue makes more sense in [here](https://github.com/python/typing/discussions) or [here](https://discuss.python.org/c/ideas/6) and if there's agreement then a new pep may be needed.
