### ISSUE TITLE
pyright-langserver uses different default for `useLibraryCodeForTypes`

### ISSUE THREAD

**Issue by rymndhng** [microsoft/pyright#5874]
**Describe the bug**

According to the configuration, the default value of `useLibraryCodeForTypes` should be True. 

I am using pyright-langserver (through Emacs/Eglot), and I noticed that it shows different different errors compared to running `pyright` on a file. I also noticed that there's a fallback value in the server configuration, see https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/server.ts#L86. Should this default option be removed to match the default configuration?

**VS Code extension or command-line**

Running through command-line `pyright` and `pyright-langserver` in Emacs through Eglot.

**Comment by erictraut** [comment]
Thanks for the bug report.

Yes, this default value should be changed to true. This bug was left over from an earlier time when the default value of this setting was false.

This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.326, which I just published. It will also be included in a future release of pylance.
