### ISSUE TITLE
np._ArrayOrScalarCommon should be hashable

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#5878]
**Describe the bug**
The private class `np._ArrayOrScalarCommon` in numpy 1.24.4 is inferred by pyright to be not hashable even though the class has no parent class that overwrites `__hash__` and itself also does not overwrite `__hash__`. (Only some subclasses of it overwrite `__hash__`.)

**Code or Screenshots**

```python
from typing import Hashable
import numpy as np

def test(x: Hashable) -> None: ...

def foo() -> np._ArrayOrScalarCommon: ...

test(foo())```

**Comment by erictraut** [comment]
This behavior is working as designed. The Python runtime automatically considers a class _not hashable_ (i.e. it sets `__hash__` to `None`) if it overrides `__eq__` without also overriding `__hash__`. Pyright is mirroring this behavior in its internal logic. To fix this, the numpy stub will need to define a `__hash__` method in the `_ArrayOrScalarCommon` class.
