### ISSUE TITLE
PEP 702: For deprecated methods, include name of class in error message

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#5891]
<img width="568" alt="Screenshot 2023-09-05 at 8 40 49 AM" src="https://github.com/microsoft/pyright/assets/906600/33c758d5-2b76-4fac-9e90-e337c93c42fa">

Currently the error message for calling a deprecated method is just "This function `dict` is deprecated."
It would be clearer if the error from pyright said something like "Method dict of pyright.BaseModel is deprecated".

Code used for completeness:

```python
import pydantic

class X(pydantic.BaseModel):
    y: int

def f(x: X):
    x.dict()
```

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.326, which I just published. It will also be included in a future release of pylance.
