### ISSUE TITLE
deprecations not correctly marked for coroutine functions

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#5896]
## Environment data

-   Language Server version: 2023.8.50
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

## Code Snippet

```python
from typing_extensions import deprecated


@deprecated("don't use this")
async def foo():
    ...


@deprecated("don't use this either")
def bar():
    ...


async def main():
    await foo()
    bar()
```

<img width="239" alt="image" src="https://github.com/microsoft/pylance-release/assets/50501825/3e983c70-263e-4150-b6a4-cae91c068576">

## Expected behavior

Both foo and bar should be striked through

## Actual behavior

Only the sync function bar is striked through

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.326, which I just published. It will also be included in a future release of pylance.
