### ISSUE TITLE
ParamSpec defaults don't work with Literal["..."] 

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#5904]
**Describe the bug**
ParamSpec doesn't work with the literal string "..." as a default (Expected type expression but received "ellipsis") when the literal ellipsis works fine.

**Code or Screenshots**
```python
P = ParamSpec("P", default="...")
```

<img width="808" alt="image" src="https://github.com/microsoft/pyright/assets/50501825/a734d9d7-9ad2-4b41-a951-91842fd7a14d">

**VS Code extension or command-line**
pylance: v2023.8.50

**Comment by erictraut** [comment]
I'm not sure why one would ever enclose `...` in quotes. It isn't a forward reference, after all.

That said, I agree this should work.

This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.327, which I just published. It will also be included in an upcoming release of pylance.
