### ISSUE TITLE
ExitStack is treated differently than other context managers?

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#5914]
```python
from contextlib import ExitStack, nullcontext


with ExitStack() as stack:
    stack.enter_context(nullcontext())
    x = 1


print(x)  # Pyright: x is possibly unbound?


with nullcontext():
    y = 1


print(y) # Pyright: no error
```

**Comment by erictraut** [comment]
This is working as intended. It's not a bug.

Some context managers swallow exceptions while others do not. Type checkers like mypy and pyright take their cues from the return type of the `__exit__` method. If the return type is `None` or `Literal[False]`, the type checker assumes that exceptions are not swallowed. If the return type is `bool` or `Literal[True]`, the type checker assumes that exceptions are swallowed and execution will resume after the `with` block.

**Comment by bluenote10** [comment]
@erictraut That makes sense, thanks for clarifying!

Is it then also intended that even code that can never raise fails to type check? For instance:

```py
def test() -> int:
    with ExitStack() as stack:
        x = 42
    return x
```

Here pyright complains `"x" is possibly unbound`, but as far as I can see `x` can never be unbound. Would it be possible to see that this is impossible despite the context manager indicating it swallows exceptions? Or is such a judgement (which statement can or cannot raise) only possible in the most basic of statements anyway and therefore pyright doesn't even attempt to infer it?

**Comment by erictraut** [comment]
> but as far as I can see x can never be unbound

Almost any operation can theoretically raise an exception in Python, so a type checker must make conservative assumptions within a `try` block. (I realize there's not an explicit `try` block in your example, but the context manager implicitly acts like one.)
