### ISSUE TITLE
pyright requires a large heap size when the input contains a large number of files

### ISSUE THREAD

**Issue by rymndhng** [microsoft/pyright#5931]
**Describe the bug**

I'm running pyright over a large codebase. I'm unable to show the code unfortunately. In the code I'm running, there are two top-level folders: *lib* and *bin*.  The *lib* folder has ~2500 python modules. The *bin* folder has ~1300 python files. The code in *bin* contains imports on *lib*. However, *lib* never imports from *bin*.

Previously on `v1.1.288`, I was able to run pyright with the default nodejs heap size. I'm currently using nodejs18.

Since upgrading to `1.1.316` (and testing every point release afterwards), I've started seeing "JavaScript Heap out of Memory" errors. I can work around this issue by increasing the max heap size, bumping it from 2048 to 8192 via `--max-old-space-size=8192`.

I've noticed that the OOM issues I'm seeing are linked to the number of input files. With the two folders above:

Running a single pyright commmand via `pyright lib bin` will trigger an OOM.

However, if I run pyright separately for each top-level folder: `pyright lib; pyright bin`, then I don't see an OOM issue.

**Code or Screenshots**

I'm unable to show our code, however, this is the output of `pyright` when the OOM scenario shows up.

```
<--- Last few GCs --->

[19910:0x7f8660008000]   269132 ms: Scavenge 3722.7 (4127.3) -> 3707.3 (4127.3) MB, 4.4 / 0.0 ms  (average mu = 0.254, current mu = 0.278) allocation failure; 
[19910:0x7f8660008000]   269164 ms: Scavenge 3723.3 (4127.5) -> 3707.8 (4127.5) MB, 4.3 / 0.0 ms  (average mu = 0.254, current mu = 0.278) allocation failure; 
[19910:0x7f8660008000]   269195 ms: Scavenge 3723.9 (4128.0) -> 3708.4 (4128.0) MB, 3.9 / 0.0 ms  (average mu = 0.254, current mu = 0.278) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x103fdb7d5 node::Abort() [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
 2: 0x103fdb9c5 node::OOMErrorHandler(char const*, bool) [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
 3: 0x1042364f4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
 4: 0x1043f17c5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
 5: 0x1043f51c7 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
 6: 0x1043f215e v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
 7: 0x1043ef4ae v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
 8: 0x1043e387b v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
 9: 0x1043e4143 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
10: 0x1043c7d7e v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
11: 0x1047b52bf v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
12: 0x103e1a9b9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/raymond.huang/src/.conda/lib/libnode.108.dylib]
```

**VS Code extension or command-line**

Running `pyright` on the CLI.

**Comment by erictraut** [comment]
Are you pretty confident that this issue does not repro with 1.1.315 but reliably does with 1.1.316? Or did you upgrade from some version older than 1.1.315? I've looked at all the changes between 1.1.315 and 1.1.316, and I don't see any that should have any effect on memory usage or heap management.

Pyright retains an in-memory type cache for performance reasons. This cache can grow large — effectively overflowing the available heap space if it is not monitored. For that reason, we have a mechanism that watches for heap exhaustion and deallocates everything in the cache if and when that limit approaches. It sounds like that's not happening in your case. Either that, or the garbage collector is failing to release the memory. Some older versions of node (<14) had a bug in the GC that caused this problem, but I'm not aware of any such problem with newer versions of node.

Let's try this. Enable `"verboseOutput": true` in your pyrightconfig.json file (or `verboseOutput = true` if you're using a pyproject.toml file). Then repro the bug and look at the log output. You should see a bunch of outputs relating to heap monitoring leading up to the point where the heap is exhausted and crash occurs.

**Comment by erictraut** [comment]
@rymndhng, I want to make sure you saw my question above. I won't be able to make further progress on this issue without additional information.

**Comment by rymndhng** [comment]
@erictraut Sorry for the delay in response. 

> Are you pretty confident that this issue does not repro with 1.1.315 but reliably does with 1.1.316? Or did you upgrade from some version older than 1.1.315? I've looked at all the changes between 1.1.315 and 1.1.316, and I don't see any that should have any effect on memory usage or heap management.

I upgraded from `1.1.288`. I should have clarified that in the original request. When I have some time, I'll try bisecting the releases between `1.1.288` and `1.1.316` to identify which release when this started happening.

> Let's try this. Enable "verboseOutput": true in your pyrightconfig.json file (or verboseOutput = true if you're using a pyproject.toml file). Then repro the bug and look at the log output. You should see a bunch of outputs relating to heap monitoring leading up to the point where the heap is exhausted and crash occurs.

Sounds good, I'll give this a try.

**Comment by erictraut** [comment]
Since this issue has no repro or additional details that could help with diagnosis, it's not actionable at this time. I'm going to close it, but if additional details are provided, I'm happy to reopen and investigate further.

**Comment by rymndhng** [comment]
Thanks Eric. I took a second look at this error and it's particularly difficult for me to repro because we also adopted `useLibraryCodeForTypes`. If I turn this on on our initial version 1.1.288, my codebase also OOMs.

We have since upgraded to 1.1.329 and are no longer seeing OOMs.
