### ISSUE TITLE
npm: No matching version found for pyright@1.1.327.

### ISSUE THREAD

**Issue by haxfn** [microsoft/pyright#5940]
**Describe the bug**
I was trying `npm install pyright@1.1.327`. This was originally being done inside Mason in neovim to install pyright inside neovim (giving the error  npm ERR! notarget No matching version found for pyright@1.1.327.)

**The error**
```
(node:63532) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/pyright failed, reason:
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in: /Users/vpaudel343/.npm/_logs/2023-09-14T05_36_45_283Z-debug-0.log
```

**Comment by erictraut** [comment]
This looks like it's either a problem with your network or a temporary issue with the npmjs registry. I just confirmed that I'm able to install pyright@1.1.327 without an issue. I don't think there's anything that pyright's maintainers can do here.

Please try again later and/or try from a different network.
