### ISSUE TITLE
Type inference based on hasattr checks

### ISSUE THREAD

**Issue by Ovsyanka83** [microsoft/pyright#5964]
**Is your feature request related to a problem? Please describe.**
We have a scenario when we get a union of a lot of types (15+) into a function argument when doing API versioning. We would then like to narrow this union based on hasattr checks but it doesn't work as expected. It would greatly support duck-typing code style. It feels that the behavior should match truthy and falsy checks but it doesn't. For example, pyright would infer the following types correctly:

```python
from typing import Literal

def a(b: str | Literal["", 0, False] | None):
    if b:
        reveal_type(b)  # str
    else:
        reveal_type(b)  # Literal["", 0, False] | None
```

**Describe the solution you’d like**

The following logic would probably make sense and cover most/all dangerous edge cases.
```python

from dataclasses import dataclass


@dataclass
class A:
    a: int


@dataclass
class B:
    a: int
    b: str


@dataclass
class C:
    c: bytes


class D:
    def __getattr__(self, attr: str) -> Any:
        ...  # any logic here


def check(arg: A | B | C | D):
    if hasattr(arg, "a"):
        reveal_type(arg)  # Should output A | B | D
    else:
        reveal_type(arg)  # Should output C | D
```

I understand that it's similar to [this](https://github.com/microsoft/pyright/issues/5860) request. However, in this situation we have hundreds of such models and thousands of attributes to consider -- making user-defined type guards is simply not viable. I also propose a much simpler logic compared to the issue above because we are only inferring the type if we are given a well-defined union.

**Comment by erictraut** [comment]
Dataclasses can be subclassed, so it wouldn't be safe to perform narrowing as you're suggesting. For example, it's possible to subclass `C` and add a new attribute `a` to the subclass.

It would be safe if the classes were marked `@final`, but that's infrequently used.

Even if this were safe, adding support for type guard patterns is not something we do without significant justification. Each new pattern requires significant special-casing logic and often has a measurable impact on analysis performance, even in code where that pattern isn't used. We'd need to see strong signal from many other pyright users that this type guard pattern is something they want to see before considering it.

For these reasons, I'm going to close this enhancement request for now.
