### ISSUE TITLE
`__slots__`  not recognized on abstract classes defined with `abc.ABC` but are with `abc.ABCMeta`

### ISSUE THREAD

**Issue by SebbyLaw** [microsoft/pyright#5976]
**Describe the bug**

Defining an ABC with `abc.ABC` does not cause pyright to raise an error for missing attributes. However, using `abc.ABCMeta` instead does. This carries over to implementations of the ABC.

In my opinion, `abc.ABC` should act the same as `abc.ABCMeta` and cause pyright errors to be raised.

**Code or Screenshots**
With ABC:
```python
from abc import ABC

class Base(ABC):
    __slots__ = ("foo",)

    def __init__(self, foo: str):
        self.foo = foo
        self.bar = "bar"  # 'Base' object has no attribute 'bar'; no pyright error

class Derived(Base):
    __slots__ = ("baz",)

    def __init__(self, foo: str, baz: str):
        super().__init__(foo)
        self.baz = baz
        self.hello = "hello"  # 'Derived' object has no attribute 'hello'; no pyright error
```
With ABCMeta:
```python
from abc import ABCMeta

class Base(metaclass=ABCMeta):
    __slots__ = ("foo",)

    def __init__(self, foo: str):
        self.foo = foo
        self.bar = "bar"  # "bar" is not specified in __slots__ (correct)

class Derived(Base):
    __slots__ = ("baz",)

    def __init__(self, foo: str, baz: str):
        super().__init__(foo)
        self.baz = baz
        self.hello = "hello"  # "hello" is not specified in __slots__ (correct)
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool? Which version?

Pylance in `ms-python.vscode-pylance-2023.9.10`
Also tested in
Pyright v1.1.319
Pyright v1.1.327

**Comment by Azureblade3808** [comment]
Seems a typeshed issue? `__slots__` attribute of `abc.ABC` is not listed in the stubs (https://github.com/python/typeshed/blob/main/stdlib/abc.pyi#L43). You may file an issue there.

**Comment by erictraut** [comment]
Yes, I think that's a correct diagnosis. At runtime, `ABC` does have a `__slots__` class attribute, but this isn't reflected in the typeshed definition in `abc.ABC`.

**Comment by SebbyLaw** [comment]
Thank you. I have opened a pull request to typeshed
