### ISSUE TITLE
Type of NewType is unknown

### ISSUE THREAD

**Issue by bfelbo** [microsoft/pyright#598]
**Describe the bug**
This is a crazy case, but I'm reporting it nevertheless in case it's useful. For the union type below that we use during our SQL wrapper function (it's later typed more specifically), pyright gives `Type of "DBValueType" is unknown`.

**To Reproduce**
```
from typing import NewType, Union as U, List
from datetime import datetime

# Union type for all data types retrieved from DB, giving minimal typing assistance.
DBValueType = NewType(
    "DBValueType", U[U[U[U[U[int, str], float], List[int]], bool], datetime]
)
```

**Expected behavior**
No type error as the type is specified.

**VS Code extension or command-line**
1.1.30

**Comment by erictraut** [comment]
You're using `NewType` inappropriately. It is constrained to work only with a class as a parameter. You're using a union of classes. 

What you should be using in this case is a simple type alias of the form:
```
DBValueType = Union[int, str, float, List[int], bool, datetime]
```

**Comment by bfelbo** [comment]
That's great to know. Thanks! I'll close this issue then.

**Comment by bfelbo** [comment]
On a related note, do you have any suggestions for a good intro to python typing?

For instance, I still haven't found a good source on writing type stubs for 3rd party libraries.

**Comment by erictraut** [comment]
PEP 483 and PEP 484 provide a good overview. Are you looking for something more specific?

**Comment by bfelbo** [comment]
Thanks. I'll read them again. I guess I'm looking for an example codebase that has everything setup with self-made type stubs, imported 3rd party type stubs, etc. Anyway, this is off-topic, thanks for your help!
