### ISSUE TITLE
Add a test for virtual environments

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pyright#5990]
All the current tests mimic the python environment at the moment. It would be nice to have tests that run inside of a true virtual environment so we can catch issues like:

https://github.com/microsoft/pyright/issues/5943

**Comment by rchiodo** [comment]
Thoughts on how to do this:
- Change test code to read real python environment
- Add test that verifies imports from the environment
- Update test action to install a module
- Run all test code with virtual environment

Maybe have a flag that only does this on CI? Otherwise local developer will have to run with an environment with those imports in it.

**Comment by erictraut** [comment]
> Maybe have a flag that only does this on CI?

Yes, please don't enable this for local tests, at least not by default!

A few additional considerations... 
* Pyright (and pylance) support a variety of ways to specify the python environment: 1) a python path specified via the Python extension (which can alternatively be populated from a local ".env" file), 2) the `python.pythonPath` setting from the client, the `python.venvPath` from the client, 3) the `venv` + `venvPath` mechanism (where `venvPath` can come from the config file, `python.venvPath` setting, or command-line option), 4) the PYTHON_PATH shell variable. Do we want to test all of these configuration mechanisms? A subset? It's a huge test matrix if we test them all.
* Independent of the way that pyright is told about the python environment, there are other factors that affect import resolution such as the presence of ".pth" files and symlinks. File system case sensitivity is also a consideration. It's not clear which subset of these we'd want to include in the test matrix.

**Comment by rchiodo** [comment]
Yeah, it seems it needs to run a subset of the tests. 14 mins just to run tests (windows) on last run. If we want to have any sort of test matrix, we'd have to pair that down. Maybe just import tests to start with? They're most affected by python path settings? I mean no need to run type eval tests with different python paths.
