### ISSUE TITLE
Add documentation for running from the command line

### ISSUE THREAD

**Issue by kinow** [Microsoft/pyright#6]
Hi,

I do very little JS & TS (have two projects with Vue.js, still with ES6, to be migrated). The node dependency is not an issue for me to use `pyright`, and coming from a Java background I do miss more tools like SpotBugs, PMD, CheckStyle, clirr, etc.

However, I am still somewhat more confident when using PyCharm rather than VS Code - though for editing small files I prefer VS Code. The `README` file mentions the command line, and I tried finding a task in the `package.json` files that would allow me to produce a binary to be called from the command line in Ubuntu, without luck.

I hate opening issues in GitHub projects for questions/support like this one, sorry. But I really would like to play more with pyright in an environment I am more faimliar, can debug, use other linters/analyzers, and see how it goes. Promise to report all issues and try to contribute back.

Cheers
Bruno

**Comment by erictraut** [comment]
I just published the command-line version to the public npm registry and added instructions to the main pyright `README` for installing and invoking the tool.

**Comment by kinow** [comment]
Thanks!
