### ISSUE TITLE
Re-assigned `@property` cannot be accessed

### ISSUE THREAD

**Issue by Avasam** [microsoft/pyright#6011]
**Describe the bug**
When assigning a Class' property as another class' member, that member becomes inaccessible

**Code or Screenshots**
See the following, I'd expect no error and for the type to not be unknown:
![image](https://github.com/microsoft/pyright/assets/1350584/c076d812-7f12-478d-8289-c6a8492c0483)
(this comes from trying to stub openpyxl like the [source](https://foss.heptapod.net/openpyxl/openpyxl/-/blob/branch/3.1/openpyxl/cell/cell.py#L326) )

Minimal repro (tested with pyright from cli):
```python
>>> class A:
...     @property
...     def foo(self) -> str:
...         return "bar"
...
>>>
>>> class B:
...     foo = A.foo
...
>>> B().foo  # error: Cannot access member "foo" for type "B" (reportGeneralTypeIssues)
'bar'
```

Similar issue for mypy: https://github.com/python/mypy/issues/13975

**VS Code extension or command-line**
Pylance v2023.9.21
pyright 1.1.321

**Comment by erictraut** [comment]
Yes, this behavior is correct. The property defined in class `A` is specialized for that class (and subclasses thereof). The `self` parameter type is specific to `A`. You cannot reuse it in another unrelated class like `B`.
