### ISSUE TITLE
Typeshed Fallback has incorrect typings for unittest.TestCase.assertLessEqual

### ISSUE THREAD

**Issue by ImogenBits** [microsoft/pyright#6037]
Currently [the included typings](https://github.com/microsoft/pyright/blob/6426ebccc0d83a3325d67096bdb00667c02b2d04/packages/pyright-internal/typeshed-fallback/stdlib/unittest/case.pyi#L128-L131) for `unittest.TestCase.assertLessEqual` use `SupportsDunderLT` and `SupportsDunderGT` when they should be using `SupportsDunderLE` and `SupportsDunderGE`. This leads to false positives when making tests for classes that only implement the lax comparisons and not the strict ones.

**Comment by erictraut** [comment]
These stub files come from the [typeshed project](https://github.com/python/typeshed). Pyright and all of the other major Python type checkers use these same stubs. If you think that there are errors in them, please file a bug or a PR in typeshed.
