### ISSUE TITLE
Is it possible to implement Go to definition inside Doc-strings or comments?

### ISSUE THREAD

**Issue by aspizu** [microsoft/pyright#6041]
I don't think this is a thing in the LSP spec, but it would be a very helpful feature.

**Comment by erictraut** [comment]
Pyright is focused on type checking. It offers some basic language server features, but we have no plans to add any new language server features to pyright. If you use pylance and would like to suggest new language server features in that extension, you can file an enhancement request [here](https://github.com/microsoft/pylance-release).

**Comment by aspizu** [comment]
pylance is proprietary
