### ISSUE TITLE
v1.1.329: bytes related type narrowing incompatibility even if disableBytesTypePromotions=false

### ISSUE THREAD

**Issue by pinterior** [microsoft/pyright#6059]
**Describe the bug**

1.1.329 introduced new switch `disableBytesTypePromotions` that is off by default to keep old behavior.
but some old behavior is not retained by default.

assume `x` as `int | bytes`:
- on 1.1.318, `if not isinstance(x, bytes)` infers `x` as `int`
- on 1.1.319, with default setting,  `if not isinstance(x, bytes)` infers `x` as `int | bytearray | memoryview`

**Code or Screenshots**

```python
from typing import Union
from typing_extensions import assert_never, reveal_type


def f(x: Union[int, bytes]):
    if not isinstance(x, bytes):
        reveal_type(x)
```
```
$ PYRIGHT_PYTHON_FORCE_VERSION=1.1.329 pyright bs.py
bs.py
  bs.py:7:21 - information: Type of "x" is "int | bytearray | memoryview"
0 errors, 0 warnings, 1 information 
```

**VS Code extension or command-line**

command-line tool, 1.1.329

**Comment by erictraut** [comment]
This behavior is intended. When you set `disableBytesTypePromotions` to false, the use of `bytes` within a type annotation implies `bytes | bytearray | memoryview`. However, when you use narrow this type with `isinstance`, the runtime distinguishes between these three types. Pyright is therefore reflecting the runtime behavior here. Previously it did not. 

You have two options:
1. Set `disableBytesTypePromotions` to false and add an additional `isinstance` guard (e.g. `isinstance(x, int)`) to make your code type safe.
2. Set `disableBytesTypePromotions` to true and update your code so it is explicit about where it accepts `bytearray` and `memoryview`.
