### ISSUE TITLE
False positive for reportInvalidStringEscapeSequence in very long string

### ISSUE THREAD

**Issue by arvidfm** [microsoft/pyright#6062]
**Describe the bug**
If you have a string containing more than 32768 characters, and the 32768th character is a backslash, Pyright always emits a `reportInvalidStringEscapeSequence`, even if the escape sequence is actually valid.

You can hit this issue e.g. when dealing with autogenerated code. In my case I encountered it in the output of `pyside6-rcc`.

**Code or Screenshots**
Gist here: https://gist.github.com/arvidfm/267994b592bc124ffd311561d7bc4725

Note the `\n` on the final line. Changing `\n` to e.g. `xn` makes the error go away.

**VS Code extension or command-line**
* pyright 1.1.329 (CLI, using pyright-python)

**Comment by erictraut** [comment]
Thanks for the bug report. Great diagnosis and repro steps!

This will be fixed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.330, which I just published. It will also be included in an upcoming release of pylance.
