### ISSUE TITLE
Unbounded Error reported even though sys.exit is called in the case of unbounded

### ISSUE THREAD

**Issue by singhda8** [microsoft/pyright#6083]
**Describe the bug**
Pyright will output the error `reportUnboundVariable` even though sys.exit is called beforehand and the code is not reachable

**Code or Screenshots**

```python
import sys

def set_val(num: int):
    if num == 1:
        return "1"
    else:
        raise Exception("Failed")
    
def raise_error():
    sys.exit(1)

try:
    val = set_val(1)
except Exception as e:
    raise_error()

new_val = val
```

If I were to invoke `sys.exit` directly rather than calling `raise_error`, then the error is not reported.

**Comment by erictraut** [comment]
This is working as intended. If you want pyright (or mypy) to treat a function as though it never returns control back to the caller, you need to explicitly declare its return type as `typing.NoReturn`.

```python
def raise_error() -> NoReturn:
    sys.exit(1)
```
