### ISSUE TITLE
Custom type-guard function not working in `else` part

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pyright#6112]
**Describe the bug**

See sample below. I'm expecting that the type in else part be narrowed as "bool", but got "str | bool" instead.

**Code or Screenshots**

```python
from typing import TypeGuard, assert_type

def is_str(x: object, /) -> TypeGuard[str]: ...

def correct(x: str | bool):
    if isinstance(x, str):
        ...
    else:
        _ = assert_type(x, "bool")

def wrong(x: str | bool):
    if is_str(x):
        ...
    else:
        _ = assert_type(x, "bool")  # "str | bool"?
```

**VS Code extension or command-line**

Pylance and CLI, with Pyright version from 1.1.327 through 1.1.330.

**Comment by erictraut** [comment]
Draft PEP 724 is implemented within pyright, but you need to enable it by setting `enableExperimentalFeatures` to true. This functionality could change if PEP 724 is further modified or rejected, so use it with caution.
