### ISSUE TITLE
option to enforce error codes in `pyright:ignore`/`type:ignore` comments

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#6164]
**Is your feature request related to a problem? Please describe.**
adding a `type:ignore` or `pyright:ignore` comment without specifying a code is bad because it could unintentionally suppress another type of error

**Describe the solution you’d like**
a new option that enforces error codes on `type:ignore`/`pyright:ignore` comments. mypy has one called `ignore-without-code`

**Comment by DetachHead** [comment]
seems like the code can only be specified on `pyright:ignore` but not `type:ignore` so, maybe this option could also ban `type:ignore` comments

**Comment by erictraut** [comment]
There is already an option to ignore `# type: ignore`. You can set `enableTypeIgnoreComments` to false, and pyright will treat all `# type: ignore` comments as if they were normal comments. There is no way to disable `# pyright: ignore` comments or comments without codes. This is something we might consider adding in the future if there's sufficient demand (based on thumbs up votes), but I'm going to close this feature request for now.

**Comment by DetachHead** [comment]
> This is something we might consider adding in the future if there's sufficient demand (based on thumbs up votes), but I'm going to close this feature request for now.

In that case why close it? I think it's unlikely this issue will get many upvotes if it's closed

**Comment by DetachHead** [comment]
looks like ruff has a rule for this: https://docs.astral.sh/ruff/rules/blanket-type-ignore/
