### ISSUE TITLE
option to ban `Any`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#6165]
**Is your feature request related to a problem? Please describe.**
pyright has options to ban untyped values (eg. `reportUnknownParameterType`, `reportUnknownArgumentType`, etc.) but there doesn't seem to be one to ban values explicitly typed as `Any`

```py
from typing import Any


def foo(bar, baz: Any) -> Any:
    print(bar) # error: unknown type
    print(baz) # no error
```
**Describe the solution you’d like**
an option to ban values with the `Any` type, like mypy's `disallow-any-expr` option

**Comment by erictraut** [comment]
It's unlikely we would add such a feature. Pyright implements a different mental model for `Any` and differentiates between explicit and implicit `Any` (the latter being referred to as `Unknown`). For details, refer to [this documentation](https://microsoft.github.io/pyright/#/type-inference?id=unknown-type). Explicit references to `Any` are legitimate and almost impossible to avoid in typed code.
