### ISSUE TITLE
Relative auto-imports

### ISSUE THREAD

**Issue by patrick-kidger** [microsoft/pyright#6181]
The pyright language server offers auto-imports via the `python.analysis.autoImportCompletions` flag.

However, it always performs these as absolute imports. It would be nice to additionally offer the ability to perform these as relative imports, analgous to pylance's `python.analysis.importFormat` flag. Unfortunately in this case I can't use pylance itself as [it is not licensed for use with vim etc.](https://github.com/microsoft/pylance-release/blob/main/FAQ.md#can-i-load-pylance-in-code--oss).

FWIW this is the only pylance option I find myself really missing when outside of VSCode.

**Comment by erictraut** [comment]
Pyright is focused on type checking. It includes some basic language server capabilities, but we have no plans to add new language server features.
