### ISSUE TITLE
Indexing by position in standard lists is now being flagged incorrectly

### ISSUE THREAD

**Issue by mark-todd** [microsoft/pyright#6193]
**Describe the bug**
Indexing by position in standard lists is now being flagged incorrectly. I believe this must be quite a recent change, as I'm using the latest version of pyright and it's only started very recently.

**Code or Screenshots**
```python
test = [1,2,3]
x = test[0] # Raises error on this line
```
Error:

No overloads for "`__getitem__`" match the provided argumentsPyright[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
builtins.pyi(1038, 9): Overload 2 is the closest match
Argument of type "`Literal[0]`" cannot be assigned to parameter "`__s`" of type "`slice`" in function "`__getitem__`"
  "`Literal[0]`" is incompatible with "`slice`" Pyright[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)

I am running pyright as a VS Code extension, v1.1.332

**Comment by erictraut** [comment]
I'm not able to repro the problem with the sample code. I can't think of any recent change that would have affected this. 

I wonder if there's something corrupt in your installation. Perhaps you accidentally edited the `builtins.pyi` stub file bundled in pyright. Please do the following:
1. Uninstall the pyright VS Code extension, delete it from the local cache, and reinstall it
2. Create a new project
3. Create a new virtual environment and select it
4. Create a new source file in your project and paste in your code sample from above

Are you still able to repro the problem?

**Comment by mark-todd** [comment]
It's strange, I've reinstalled and I can't reproduce this now.

I've also found other references to this same bug in other projects: https://github.com/openai/openai-python/issues/270
(they solved it here by suppressing the error I believe)
So I'm pretty sure it's not something I've overridden my end, but at the same time not sure what to do about it - it's something of a phantom bug.

**Comment by erictraut** [comment]
Glad to hear the problem went away.

The situation described in the linked case is different from the code sample you posted above. I don't think this is a phantom bug. I suspect you just had something corrupted in your pyright install. This can happen if you accidentally modify one of the bundled type stub files (like `builtins.pyi`). By reinstalling, you restore the original (uncorrupted) file.

**Comment by Avinash-Raj** [comment]
@mark-todd May I know the steps you have done to fix the issue? I can't even after reinstalling `python`, `pylance` extensions. Even not after reinstalling vs code.

**Comment by d-miketa** [comment]
I get the exact same issue too, but using Pyright within Emacs. I have tried reinstalling my venv as well as Pyright, and neither made the errors go away.

**Comment by erictraut** [comment]
@d-miketa, if you're able to provide repro steps, I'd be happy to look into the problem.
