### ISSUE TITLE
Cannot assign kwargs to dict variable when kwargs are annotated by Unpack and TypedDict

### ISSUE THREAD

**Issue by rk-terence** [microsoft/pyright#6194]
**Describe the bug**

According to [PEP 692](https://peps.python.org/pep-0692/), we can annotate `**kwargs` in function signatures using `TypedDict`.
Inside the function body, `kwargs` will be a variable of type `dict` during runtime, so I think it is reasonable to consider `kwargs` variable as of type `dict`. However, Pyright complains this.

**Code or Screenshots**

```python
from typing import TypedDict, Unpack, Any


class Options(TypedDict):
    font: str
    size: int


def f(**kwargs: Unpack[Options]) -> dict[str, Any]:
    return kwargs  # Pylance complains

```

The complaint is
```
Expression of type "*Options" cannot be assigned to return type "dict[str, Any]"
  "*Options" is incompatible with "dict[str, Any]"
Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

**VS Code extension or command-line**
I am running Pyright (1.1.330) through Pylance.

**Comment by erictraut** [comment]
This behavior is correct. A `TypedDict` object is not type compatible with a `dict`. Refer to [PEP 589](https://peps.python.org/pep-0589/) for details. You can use a `Mapping[str, Any]` here. Or you can construct a new dict from the `kwargs` — `return dict(kwargs)`.
