### ISSUE TITLE
Align pyright and pylance release cadence

### ISSUE THREAD

**Issue by MartinBernstorff** [microsoft/pyright#6198]
I tried searching, but `is:issue "pylance" "release"` gave me 77 pages of results, so sorry if this is a duplicate!

**Is your feature request related to a problem? Please describe.**
We're using pyright in our CI, and it sometimes catches errors that the latest version of pylance does not.

For example, with 
* `pyright==1.1.332`
* `pylance==v2023.10.30`
* type checking mode `strict`

the following code produces an error with pyright, but not pylance: 

 ```python
 def test_fn() -> pd.Series[int]:
    return pd.Series([1])
 ```
 
![image](https://github.com/microsoft/pyright/assets/8526086/a474562a-bd2d-4baa-bad3-b9ba8302efac)

**Describe the solution you’d like**
Provide a way of keeping the latest pyright version aligned with the latest version of pylance.

**Comment by erictraut** [comment]
Please refer to [this documentation](https://github.com/microsoft/pylance-release/blob/main/USING_WITH_PYRIGHT.md).

**Comment by MartinBernstorff** [comment]
@erictraut Thanks! I think the documentation addresses a separate issue.

1) Potential misalignment between Pyright and Pylance settings (addressed by docs)
2) Version-misalignment between Pyright and Pylance

### Misalignment between Pyright and Pylance settings
Pylance raises an error that pd.Series is an untype generic:
![image](https://github.com/microsoft/pyright/assets/8526086/3c028ffd-d000-4bdc-8709-b3ed169dc575)

Pyright does not. I tried setting:
```toml
useLibraryCodeForTypes = true
extraPaths=[]
autoSearchPaths=true
```

But still get the misalignment running the abovementioned versions. Not sure what to try next?

### Misalignment between Pyright and Pylance versions
Settings-misalignment might very well be the root cause of the problem I'm seeing, but I can still see version-misalignment being a problem during development. @rchiodo's point is good for Github Actions, but we are running CI locally before pushing, and would love to align Pylance and Pyright versions there as well.

**Comment by erictraut** [comment]
As mentioned in the documentation, pylance bundles additional type stubs that are not included in pyright. If you want the same behaviors between the two, you need to use the same type stubs. In the case of pandas, I recommend installing `pandas-stubs` into your python environment (e.g. `pip install pandas-stubs`). This will override the stubs bundled in pylance, and you'll get the same behavior between pylance and pyright.

**Comment by MartinBernstorff** [comment]
Ah, that's on me, thank you so much.
