### ISSUE TITLE
Unknown alert is displayed when importing an external library.

### ISSUE THREAD

**Issue by Umisyo** [Microsoft/pyright#62]
**Describe the bug**
When importing a library of foreign nature, even if it is normal, "Import [library_name] could not resoleved" will be warned.

**To Reproduce**
Import library to your code.
Example
```python 
import numpy
```

**Expected behavior**
No warning.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/44742896/55680970-d27fd600-595b-11e9-9a24-296a479ab9ab.png)

**VS Code extension or command-line**
VS Code extension, var1.0.9

**Comment by erictraut** [comment]
You need to tell Pyright where it can find the external packages that you want to import. Do you use virtual environments (venvs)? If so, you can specify the virtual environment using a combination of the "venvPath" and "venv" settings. If not, you can use the PYTHONPATH environment variable to point to your imports.

For additional information, see [this documentation](https://github.com/Microsoft/pyright/blob/master/docs/import-resolution.md).
