### ISSUE TITLE
add "Statements must be separated by newlines or semicolons" to Type Check Diagnostics Settings

### ISSUE THREAD

**Issue by yysc622** [microsoft/pyright#6221]
When there are no parentheses in print, Python 2.7 can run the print statement normally. So the error 'Statements must be separated by new lines or semiconons' should be considered to be added to the Type Check Diagnostics Settings to turn off this warning in vscode

https://github.com/microsoft/pyright/blob/main/docs/configuration.md#type-check-diagnostics-settings

![image](https://github.com/microsoft/pyright/assets/77236294/0bb5d964-851c-4615-9cc3-611dbc73b564)

**Comment by erictraut** [comment]
Pyright doesn't support Python 2.x. If you are using versions of Python prior to 3.x, you should use a different type checker and language server.
