### ISSUE TITLE
Type inference issue with bytes

### ISSUE THREAD

**Issue by povilasb** [microsoft/pyright#6227]
**Describe the bug**

**pyright** assumes that `bytes` type is `bytearray | memoryview`

**Code or Screenshots**

```python
class Req:
    def __init__(
        self,
        method: str | bytes,
    ):
        self.method = (
            method.decode("ascii").upper()
            if isinstance(method, bytes)
            else method.upper()
        )
```
Simplified version of https://github.com/encode/httpx/blob/e63b6594f2863b7c8274eb0991ebc6cad63661f7/httpx/_models.py#L310

<img width="810" alt="image" src="https://github.com/microsoft/pyright/assets/1213442/5215c71c-9141-4c72-b102-5f4737b7c420">

<img width="625" alt="image" src="https://github.com/microsoft/pyright/assets/1213442/9fe763f1-701d-4508-b896-3929368184fb">

**VS Code extension or command-line**

**pyright** (CLI) `1.1.332` 
```py
error: Cannot access member "upper" for type "memoryview" 
```

**Comment by erictraut** [comment]
This is intended behavior, not a bug.

The type annotation `bytes` has historically implied `bytes | bytearray | memoryview`. This is a not-very-well-documented behavior that was implemented many years ago by mypy, and many libraries and code bases now rely on it.

The following code is therefore considered legal:
```python
Req(bytearray())
```

[PEP 688](https://peps.python.org/pep-0688/) largely eliminates the need for this behavior and recommends that type checkers no longer perform this form of "type promotion". Pyright still retains this older behavior for backward compatibility reasons, but you can disable it by setting the `disableBytesTypePromotions` configuration setting to "true". In strict type checking mode, it already defaults to "true". For additional details, refer to the [pyright documentation](https://microsoft.github.io/pyright/#/configuration?id=type-check-diagnostics-settings).

**Comment by povilasb** [comment]
Awesome, thank you for a thorough explanation 🙇‍♂️
