### ISSUE TITLE
Infinite loop in `_getModuleNameForImport`

### ISSUE THREAD

**Issue by debonte** [microsoft/pyright#6232]
**Describe the bug**
1. Start VS Code without a workspace (no open folder)
2. `File: New Untitled Text File`
3. Change language of file to Python

Result: Infinite loop in `_shouldWalkUp` loop in `_getModuleNameForImport`.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.334, which I just published. It will also be included in a future release of pylance.
