### ISSUE TITLE
[VSCode][Protocol] Incompatible types with non-matching variable names

### ISSUE THREAD

**Issue by MadhuVK** [microsoft/pyright#6235]
### Describe the bug

**Behavior**: Type issue reported when assigning an existing type to a protocol type, if the variable name does not match. If the variable name does match, no type issue.

**Expected**: Variable name should not matter since they express the same signature. I would expect the first assignment listed in my code sample to be valid.

Note: I haven't tested this, but I suspect that original double-underscore variable might be causing issues, as I recall it undergoes some mangling.

**Code or Screenshots**
![screen](https://github.com/microsoft/pyright/assets/1362193/6160cbd4-f870-4307-9084-ba8cae42a42c)

```python
#!/usr/bin/env python3

from abc import abstractmethod
from typing import Protocol, Self

class ComparableInvalid(Protocol):
    @abstractmethod
    def __lt__(self, x: Self) -> bool: ...

x: ComparableInvalid = 4

class ComparableValid(Protocol):
    @abstractmethod
    def __lt__(self, __value: Self) -> bool: ...

y: ComparableValid = 4
```

### Environment Information
Python 3.10.13
Python VSCode Extension v2023.18.0

**Comment by erictraut** [comment]
This behavior is correct. The `int.__lt__` method does not accept a keyword parameter. It must be passed positionally. But your `CompareInvalid` protocol specifies that the class must supply an `__lt__` method whose parameter is called `x`. PEP 570 introduces a way to specify that parameters are positional-only using the `/` special parameter.

```python
class ComparableInvalid(Protocol):
    @abstractmethod
    def __lt__(self, x: Self, /) -> bool:
        ...
```

Prior to Python 3.7, there was no official way to indicate that a parameter is positional-only, but there was a common convention to use names starting with a double underscore. Pyright honors this convention and treats `__value` as though it is positional-only.

This is all working correctly, so I don't consider this a bug. Consequently closing the issue.

**Comment by MadhuVK** [comment]
Thanks for the clarification, I wasn't aware of PEP 570 and positional-only arguments.
