### ISSUE TITLE
YO GUYS I HAVE SOME SOME PROBLEMS IN MY PYTHON CODE AT HERE. PLS HELP ME!!!

### ISSUE THREAD

**Issue by castjebaonotgay** [microsoft/pyright#6236]
HELP ME PLSS!!
![image_2023-10-26_205047951](https://github.com/microsoft/pyright/assets/147998686/e4065617-2028-4bc9-9418-5cbf2663efb9)

**Comment by erictraut** [comment]
If you have questions about type checking in general, please post your question to the [python/typing discussion forum](https://github.com/python/typing/discussions) or the [pyright discussion forum](https://github.com/microsoft/pyright/discussions). 

If you think you have found a bug in pyright, please provide the information in the bug report template including a minimal self-contained snippet of code.
