### ISSUE TITLE
Pyright mishandles call with varargs following keyword arg

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#6247]
https://pyright-play.net/?code=CYUwZgBGAUCGA0EBGBKAXAKAtiAHWAzgRhjEgLwCMiAVNAEzwopA

Pyright generates two errors for this code:

```python
def f(a, b):
    pass

f(b=1, *(2,))
```

However, it works at runtime. (I'm not sure why, as it's a very weird pattern; I can only imagine it was accepted due to an oversight while implementing the parser.) Mypy and pyanalyze also accept this code without errors.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.334, which I just published. It will also be included in a future release of pylance.
