### ISSUE TITLE
"Subset" of `TypedDict` in not accepted in `TypedDict.update`

### ISSUE THREAD

**Issue by SebbyLaw** [microsoft/pyright#6249]
Hello again. This was introduced from pyright 1.1.332 -> pyright 1.1.333
For real this time :trollface: 

**Describe the bug**

A "subset" TypedDict can't be passed into the `dict.update` function of a "superset" TypedDict
e.g: the fields & annotations of the "subset" TypedDict are a subset of the fields & annotations of the "superset" TypedDict

**Code or Screenshots**

Here's the code in pyright playground: https://pyright-play.net/?pyrightVersion=1.1.333&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgCYAiSAxjAFD1UA2AhgM6tQBiYYAFEQjKUaASgBctKFKjMxmFHWlQARnNYwQk6VTnBGYZnQYt2UAELMQ-EhWoxxWqbPmLpqqOs31gPKAF4uHl5mPwBGABoVPwAiACZoyKo-AGYAOgAGEXplS39zS2Cw9MjlGNj06KzvHlSAVwRSQ2JeHJARKQBiKGIQcE0fMDqGpt4Ab2jmaLlQ4qho5Sm58uiAX3aoLpQwbt7cWiA

And below for visibility:
```py
from typing import TypedDict


class Foo(TypedDict):
    a: int
    b: str
    c: float


class Bar(TypedDict):
    a: int
    b: str


foo = Foo(a=1, b="2", c=3.0)

bar = Bar(a=10, b="20")


foo.update(bar)  # error
foo.update({"a": 10, "b": "20"})  # no error
```

**VS Code extension or command-line**

pyright 1.1.333

**Comment by erictraut** [comment]
This was an intentional change. The old code was not type safe.

Code in [pyright playground](https://pyright-play.net/?pyrightVersion=1.1.332&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgCYAiSAxjAFD1UA2AhgM6tQBiYYAFEQjKUaASgBctKFKjMxmFHWlQARnNYwQk6VTnBGYZnQYt2UAELMQ-EhWoxxWqbPmLpqqOs31gPKAF4uHl5mPwBGABoVPwAiACZoyKo-AGYAOgAGEXpaJjYOCwAva0FbUQklZ1RXKXdPRygdDw1s5WYC-3M24LDI5RiEhpi0MBgqAAtmAEJorNpSYmAoAFcEUkNiAH0fPm25bjBeyzkLEAclbdSVtZhiXlbT%2Biv1raDtw4LZ2gQQKt5tgG1olRogBdLJ5Yh4TCsVDqZgoKi3AFA0GRPQGey0IA)

```python
from typing import TypedDict

class Foo(TypedDict):
    a: int
    b: str
    c: float

class Bar(TypedDict):
    a: int
    b: str

foo = Foo(a=1, b="2", c=3.0)


class Baz(TypedDict):
    a: int
    b: str
    c: str

baz = Baz(a=1, b="", c="gotcha!")

def update_foo(foo: Foo, bar: Bar):
    foo.update(bar)

update_foo(foo, baz)

print(foo["c"])
assert isinstance(foo["c"], float)
```

**Comment by SebbyLaw** [comment]
I see, that makes sense. It's a shame though, because I was using this pattern with `typing_extensions.Unpack` like so:

```py
from typing import TypedDict
from typing_extensions import Unpack


class Foo(TypedDict):
    a: int  # something like a "Primary Key" that isn't mutable
    b: str
    c: float


class EditFoo(TypedDict, total=False):
    b: str
    c: float


def update_foo(foo: Foo, **kwargs: Unpack[EditFoo]) -> None:
    foo.update(kwargs)


foo = Foo(a=1, b="2", c=3.0)

update_foo(foo, c=4.0)
```

**Comment by erictraut** [comment]
There's a draft [PEP 728](https://github.com/python/peps/pull/3441) that would solve your problem. It's still in the early stages though. Using PEP 728, you'd be able to define `EditFoo` as follows:

```python
class EditFoo(TypedDict, total=False):
    b: str
    c: float
    __extra_keys__: Never
```
