### ISSUE TITLE
python.analysis.exclude is not respected by Pyright

### ISSUE THREAD

**Issue by ppeetteerrs** [microsoft/pyright#6250]
**Is your feature request related to a problem? Please describe.**
I think it makes sense for Pyright to append / override the default list of excluded filespecs with ones specified in VSCode's python.analysis.exclude. Currently VSCode users would need to duplicate the excluded list of file specs in pyrightconfig.json.

**Describe the solution you’d like**
Add the option to package.json and the corresponding append / override logic to configOptions.ts or service.ts. It should be a pretty trivial change.

**Comment by erictraut** [comment]
`python.analysis.exclude` isn't currently a supported language server setting for either pyright or pylance. If you want to specify an `exclude` setting, you can do so in your `pyrightconfig.json` file or `pyproject.toml` file.

There has been some demand for adding this support. If you're interested, please upvote [this issue](https://github.com/microsoft/pylance-release/discussions/2581). I'll leave it up to the pylance team to decide whether to add such a feature.

If we were to implement this, it would not be an "append" operation. As with other config options that are exposed in both config files and as a language server setting, the config file would take precedence over the language server setting.

**Comment by erictraut** [comment]
I just realized the other issue (the discussion topic that I linked to) is locked and marked as complete.

@debonte, it looks like `python.analysis.include`, `python.analysis.exclude`, and `python.analysis.ignore` settings were added to pylance. Why wasn't this implemented in the pyright code base? I'd think that we'd want this to be consistent across pyright and pylance. Was this just an oversight?

**Comment by ppeetteerrs** [comment]
Thanks for the prompt response, really appreciate it!

**Comment by debonte** [comment]
> Was this just an oversight?

Yes, an oversight on our part.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.334, which I just published.
