### ISSUE TITLE
Request to not escape colon after drive letter in the URI of RPC response

### ISSUE THREAD

**Issue by rk-terence** [microsoft/pyright#6264]
**Is your feature request related to a problem? Please describe.**
I am recently trying to use the Pyright language server in Jupyterlab with the help of [jupyterlab-lsp](https://github.com/jupyter-lsp/jupyterlab-lsp) on Windows platform, and have been faced with an issue that prevents me from jumping to definition (https://github.com/jupyter-lsp/jupyterlab-lsp/issues/1005). After some digging, I have found that the root cause is that Pyright tries to encode the character `:` inside file URIs when giving responses to RPCs. For example, the RPC JSON would be like
```json
{
  "jsonrpc":"2.0",
  "id":6,
  "result":
    [
      {
        "uri":"file:///e%3A/tmp/mre-jupyterlab-pyright-jump-to-def/mymodule.py",
        "range":{"start":{"line":0,"character":4},"end":{"line":0,"character":9}}
      }
    ]
}
```

I have also tried the pylsp language server, which returns URI of the form `file:///e:/tmp/mre-jupyterlab-pyright-jump-to-def/mymodule.py`, and jupyterlab-lsp has no problem parsing it. 
It states in https://datatracker.ietf.org/doc/html/rfc8089#appendix-E.2 that including `:` in path is vaild in URIs.

**Describe the solution you’d like**
I would like that the character `:` inside the file URIs given by the Pyright language server is not encoded.

**Comment by erictraut** [comment]
@debonte & @rchiodo, I'm interested in your thoughts on this one.

**Comment by rchiodo** [comment]
I believe we encode it that way because that's how VS code gives it to us. If we didn't escape it, I believe this wouldn't work for VS code, but we'd have to try it to verify that.

**Comment by erictraut** [comment]
@rchiodo, do you mind if I assign this to you to investigate further? Since I don't have a Windows machine, it's difficult for me to validate a potential fix. If you determine that the current behavior is correct, feel free to close as "won't fix".

**Comment by rchiodo** [comment]
Sure, I just can't promise it will be looked at any time soon.

**Comment by erictraut** [comment]
I'd think it would be pretty straightforward and quick to investigate, no? If you don't have time, perhaps someone else on the pylance team could take it on?

**Comment by rchiodo** [comment]
I believe the change would be to special case the escaped characters here:
https://github.com/microsoft/pyright/blob/863afb7234cb210286ae3d8cffff62b7b0a9e42f/packages/pyright-internal/src/common/realFileSystem.ts#L393

But that code seems correct to me. Seems like jupyterlab-lsp should support this format.

**Comment by rchiodo** [comment]
Testing that change worked for me locally wouldn't take long, but I'm not confident this wouldn't break other things elsewhere. Especially given all the problems we've had with weird file paths in the last couple of days.

**Comment by erictraut** [comment]
I agree, this seems like a dangerous change to make. This sounds like a bug in jupyterlab-lsp. It should handle escaped URLs properly. Closing as "won't fix".

**Comment by rk-terence** [comment]
Thank you for your attention and discussion on this.
