### ISSUE TITLE
Incorrect type-narrowing of nested iterables with generics

### ISSUE THREAD

**Issue by MartinBernstorff** [microsoft/pyright#6267]
**Describe the bug**
I have a generic class with a type-hint that can either be an `Iterable[_T0]` or `Iterable[Iterable[_T0]]`.

```python
class Seq(Generic[_T0]):
    def __init__(self, iterable: Iterable[_T0] | Iterable[Iterable[_T0]]):
        self._seq = iterable

        if all(not isinstance(item, Iterable) for item in iterable):
            reveal_type(iterable)
```

Since `all(not isinstance(item, Iterable) for item in iterable)` is only true for `Iterable[_T0]`, I would expect the type to now be `Iterable[_T0]`.

However:
![image](https://github.com/microsoft/pyright/assets/8526086/573a209b-ef3a-4197-b9ea-c1f01d020929)

Thanks for an awesome tool! It truly makes the Python ecosystem _so much better_.

**VS Code extension or command-line**
Pylance language server 2023.10.50 (pyright cfe56bfb).

**Context**
I am trying to implement a container pipeline to allow for things like: 

```python
(Seq([1,2], [3,4])
    .flatten()
    .map(lambda x: x*2)
)
```

I need the type-narrowing to correctly type-hint the flatten method.

**Comment by erictraut** [comment]
Please refer to [this issue](https://github.com/microsoft/pyright/issues/2012).
