### ISSUE TITLE
"cow" is unknown import symbol

### ISSUE THREAD

**Issue by PhuocHoan** [microsoft/pyright#6272]
**Describe the bug**
It shows bugs ["cow" is unknown import symbol] when I wrote `from cowsay import cow`. I'm sure that the package cowsay was installed correctly.

**Code or Screenshots**
```
import sys
from cowsay import cow

if len(sys.argv) == 2:
    cow("Hello, " + sys.argv[1])
```
the package cowsay is up-to-date version now (6.1)

**VS Code extension or command-line**
I'm using Pylance in VS Code with up-to-date version too (v2023.10.50)

**Comment by erictraut** [comment]
This module appears to be dynamically modifying its global namespace. If you look at the main module, it contains the following line: `globals()[ch_name] = func`. This sort of runtime hackery won't work with static analysis tools like pyright.

**Comment by ooker777** [comment]
Why can't static analysis tools work with global namespace being dynamically modified?
