### ISSUE TITLE
Request to add a config option for the python interpreter path in different execution environments

### ISSUE THREAD

**Issue by rk-terence** [microsoft/pyright#6282]
**Is your feature request related to a problem? Please describe.**
I am trying to use Pyright language server inside a "global" Jupyterlab, where multiple ipykernels are configured so that I can select different kernels for different notebooks located at different projects (directories).

When working in this scenario, for different kernels, the python interpreters are different; therefore, the search paths should be different for Pyright to function properly. 
Fortunately, Pyright does have such configuration options, i.e., `executionEnvironments`.
According to the [doc](https://microsoft.github.io/pyright/#/configuration?id=execution-environment-options), the available 4 configurations for each environment are
- `root`
- `extraPaths`
- `pythonVersion`
- `pythonPlatform`

through which I cannot specify the python interpreter.
I know that Pyright will try to use the python interpreter to determine the search path so that installed packages for that kernel will be correctly parsed.
Without this option, I have to make a workaround by manually adding python search paths of each kernel in `extraPaths` option for each execution environment.

**Describe the solution you’d like**
I think it would be great if we can specify the python interpreter path for different execution environments. 
For example, if the option is called `interpreterPath`, for each execution environment we can set
```json
{
  "interpreterPath": "/path/to/python/python3.x"
}
```
and the search paths would be able to be determined for this execution environment, just as how we determine the search paths for the default python interpreter. Besides, `pythonVersion` and `pythonPlatform` could also be auto-determined through `interpreterPath`.

**Comment by erictraut** [comment]
The "execution environment" mechanism implemented in pyright is designed for a very narrow use case. It has significant limitations, and what you're proposing here goes well beyond its design. I recommend that you look for other approaches.

Here are two that you could try:
1. Model it as a multi-root workspace. Each root can have its own settings, including the interpreter.
2. Instantiate separate instances of the pyright language server for each kernel.
