### ISSUE TITLE
Strange behaviour of cached_property with django_mongoengine (introduced in1.1.334 )

### ISSUE THREAD

**Issue by last-partizan** [microsoft/pyright#6309]
**Describe the bug**
This is a tricky case, because `django_mongoengine` is old untyped, monkey-patchy attempt to adapt mongoengine to django. But, look at this.

In both cases `_authors` in Unknown, but when used with `@cached_propery` it becomes `cached_property[Unknown]` in one case and just `Unknown` in the second. (when using  pyright@1.1.333 - both are Unknown)

Does it looks like a bug on the side of pyright or django-mongoengine?

**Code or Screenshots**

```
pip install django-mongoengine
```

```python
from functools import cached_property
from typing import reveal_type
from django_mongoengine import Document


class Book(Document):
    @cached_property
    def authors_cached(self):
        return self._authors

class BookRaw:
    def set_unknown(self, v):
        self._authors = v

    @cached_property
    def authors_cached(self):
        return self._authors


def test_django_mongoengine(book: Book):
    reveal_type(book.authors_cached) # information: Type of "book.authors_cached" is "cached_property[Unknown]"
    book.authors_cached.count() # Cannot access member "count" for type "cached_property[Unknown]"


def test_raw(book: BookRaw):
    reveal_type(book.authors_cached)  # information: Type of "book.authors_cached" is "Unknown"
    book.authors_cached.count()
```

```
/home/serg/src/pyright-examples/cached-property-with-deps.py
  /home/serg/src/pyright-examples/cached-property-with-deps.py:30:17 - information: Type of "book.authors_cached" is "cached_property[Unknown]"
  /home/serg/src/pyright-examples/cached-property-with-deps.py:31:25 - error: Cannot access member "count" for type "cached_property[Unknown]"
    Member "count" is unknown (reportGeneralTypeIssues)
  /home/serg/src/pyright-examples/cached-property-with-deps.py:36:17 - information: Type of "book.authors_cached" is "Unknown"
1 error, 0 warnings, 2 informations
```

**VS Code extension or command-line**

* pyright 1.1.334

**Comment by erictraut** [comment]
This stems from the fact that the `Document` class defined in the `django_mongoengine/document.py` file uses a dynamic base class that has an unknown type. In the case where a type checker cannot determine the class hierarchy for a class, it needs to make conservative assumptions about the class — e.g. which attributes it has and which other types it is compatible with. In this case, this is leading to the an unfortunate overload match on the `cached_property` descriptor.

I think pyright's behavior here is correct in that it's working as designed, so I don't consider this a bug. I don't see any straightforward ways to make this behavior less confusing without potentially causing new false positive errors in other code, so I'm going to leave it as is.

**Comment by last-partizan** [comment]
Is there anything i can do on the side of django_mongoengine to improve this behavior?

**Comment by erictraut** [comment]
You could create type stubs for the library that use static types rather than dynamic. Or you could effectively inline static types by doing something like this:

```python
if TYPE_CHECKING:
    class Document(
        mtc.TopLevelDocumentMetaclass,
        DjangoFlavor,
        me.Document,
    ):
        swap_base = True
else:
    class Document(
        django_meta(
            mtc.TopLevelDocumentMetaclass,
            DjangoFlavor,
            me.Document,
        )
    ):
        swap_base = True
```
