### ISSUE TITLE
multiprocessing.Array does not evaluate to an Array type

### ISSUE THREAD

**Issue by balzic** [microsoft/pyright#6313]
**Describe the bug**
When using the Array type from multiprocessing, it does not result in an iterable type with e.g. the possibility of using __setitem__ or __getitem__.

**Code or Screenshots**
![image](https://github.com/microsoft/pyright/assets/24868401/9a2fbe91-cf40-4ea7-a3b3-d4aa40ac7ee5)

```
import ctypes as c
import multiprocessing as mp

shouldBeArray = mp.Array(c.c_double, 10, lock=False)
isNotArray = shouldBeArray[0]
```

Using sublime text 3 on windows 10
![image](https://github.com/microsoft/pyright/assets/24868401/35d884cb-24a3-4736-aa9d-39e52747b378)

**Comment by erictraut** [comment]
Pyright's behavior is correct based on the type information in the typeshed stubs. Mypy's output is the same.

If you think that there's a bug in the typeshed type information for `ctypes`, please file a bug or a PR in the [typeshed project](https://github.com/python/typeshed).
