### ISSUE TITLE
Should not report `not derive from BaseException` when derive from Unknown

### ISSUE THREAD

**Issue by NateScarlet** [microsoft/pyright#632]
**Describe the bug**
When extend error from a untyped library, pyright will report the extended error is not derive from BaseExeption, which is not always true.

**To Reproduce**
Steps to reproduce the behavior.
1. from graphql import GraphQLError
2. define a Error inherit GraphQLError
3. raise defined error
4. got `not drive from BaseException` report

**Expected behavior**
Not report such error.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/21083014/79832220-8b844780-83db-11ea-94d8-96b0d35db0bf.png)

**VS Code extension or command-line**
VSCode extention: 1.1.33

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next version of pyright.

**Comment by erictraut** [comment]
Thanks again for the bug reports. This is now fixed in 1.1.34, which I just published.
