### ISSUE TITLE
Missing space in reveal_type() output for "not"

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#6345]
Minimal example: `reveal_type(not y)` outputs 'Type of "noty" is "bool"' (https://pyright-play.net/?code=E4UwbiCGA2D6AuBPADiAFAOwPbwASIEog). It should, of course, be "not y".

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.335, which I just published. It will also be included in a future release of pylance.
