### ISSUE TITLE
pyright cannot capture the mutable default xxx for field yyy is not allowed: use default_factory

### ISSUE THREAD

**Issue by braindevices** [microsoft/pyright#6370]
**Describe the bug**
in python >=3.10 (can be earlier) the dataclass field default cannot be a mutable.
pyright should capture this and warn in general mutable as default issue.
example code will have error:

```
Traceback (most recent call last):
  File "./mutable_field_default.py", line 4, in <module>
    @dataclasses.dataclass
     ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'list'> for field b is not allowed: use default_factory
```

**Code or Screenshots**

```python
import dataclasses
from typing import List

@dataclasses.dataclass
class A():
    a: int = 1
    b: List = [] # should be an error
    #b: List = dataclasses.field(default_factory=list)

@dataclasses.dataclass
class B():
    x: A = A() # should be an error
    #x: A = dataclasses.field(default_factory=A)


def test(a: List = []): # should at least be a warning
    pass


if __name__ == "__main__":
    print("hello")
```

**VS Code extension or command-line**
command-line: 1.1.333

**Comment by erictraut** [comment]
This isn't really a type violation, so it's not clear that detecting this error should be the job of a type checker. It falls somewhere between a type error and a linter error.

I'm going to convert this to an enhancement request and consider it as such.

**Comment by erictraut** [comment]
Pyright already supports an optional check for an explicit or implicit call within a function's default argument expression. It's not enabled by default (even in strict mode) because this condition isn't strictly a bug, and there are legit uses. 

```python
# pyright: reportCallInDefaultInitializer=warning

def test(a: list[int] = []): # Warning is generated here
    pass
```

**Comment by erictraut** [comment]
It looks like this limitation (where a default value assigned within the body of a `dataclass` must be hashable) is specific to the stdlib `dataclass`. It doesn't apply to other dataclass-like libraries (like `attrs` and `pydantic`) that use `dataclass_transform` (PEP 681). I'm reluctant to add a check for a behavior that is specific to `dataclass`, especially given that it's not a type violation. We might revisit this decision in the future if there's sufficient signal from pyright users that they want to see this functionality (e.g. in the form of upvotes or duplicate enhancement requests), but for now I'm going to close this issue.
