### ISSUE TITLE
pyright 1.1.334 report strange errors for builtin type and keywords

### ISSUE THREAD

**Issue by braindevices** [microsoft/pyright#6371]
**Describe the bug**
when I am in conda environment the pyright cannot work properly (1.1.333 is fine)
report strange errors for builtin types and keywords, it also try to inspect the builtin lib
this never happens in 1.1.333 or before
```
./nodeenv/bin/node ./cache/pyright-python/1.1.334/node_modules/pyright/index.js  pyright-bug.py
<root>/pyright-bug.py
  <root>/pyright-bug.py:4:8 - error: "int" is not defined (reportUndefinedVariable)
  <root>/pyright-bug.py:6:12 - error: "int" is not defined (reportUndefinedVariable)
  <root>/pyright-bug.py:10:5 - error: "print" is not defined (reportUndefinedVariable)
/anaconda-root/miniconda3/envs/py311/lib/python3.11/typing.py
  /anaconda-root/miniconda3/envs/py311/lib/python3.11/typing.py:366:54 - error: "frozenset" is not defined (reportUndefinedVariable
......
```

**Code or Screenshots**

```python
import dataclasses
@dataclasses.dataclass
class A():
    a: int = 1

def test(a:int):
    pass

if __name__ == "__main__":
    print("hello")

```

**VS Code extension or command-line**
command-line: 1.1.334

**Comment by erictraut** [comment]
I'm not able to repro the problem. Your environment or your pyright install are likely corrupt. Please reinstall pyright within a freshly-created virtual environment. 

This is unlikely to be a bug in pyright, so I'm going to close.

If you're still able to repro the problem after a fresh install, please provide step-by-step repro steps, and I'll re-open the issue.
