### ISSUE TITLE
Import resolution from non-root folders doesn't work (despite that the Python extension works).

### ISSUE THREAD

**Issue by tomasaschan** [microsoft/pyright#639]
It seems that Pyright (the VS Code extension) doesn't use the same module resolution root folder(s) as the Python extension, which makes it pretty hard to use them together.

To reproduce (full repo [here](https://github.com/tomasaschan/pyright-module-resolution-repro)):

1. Install both the Python extension (`ms-python.python`) and the Pyright extension (`ms-pyright.pyright`). Reload window if required.

1. Create the following files:

   `src/module_a/__init__py`:
   ```py
   def foo():
       pass
   ```

   `src/module_b/__init__.py`
   ```py
   from module_a import foo

   def bar():
      foo()
   ```

1. Create a virtual environment in this folder:

   ```sh
   virtualenv .venv
   ```

1. Select the Python interpreter in that virtual environment (Command Palette>`Python: Select Interpreter`>`.venv/bin/python`)

1. Open [`src/module_b/__init__.py`](/src/module_b/__init__.py).

1. Pyright reports `Import "module_a" could not be resolved`, while the Python extension has no trouble resolving the module.

1. Optional: Change the import to `from src.module_a import foo`. Now Pyright finds the module, but the Python extension does not.

**Comment by erictraut** [comment]
Thanks for the issue report. 

The language server that's built in to the Python extension for VS Code automatically special-cases a subdirectory called "src" and assumes that you want to add it to the search paths. I've added a similar mechanism to pyright. This will be in the next version.

**Comment by erictraut** [comment]
This is now addressed in version 1.1.35, which I just published.

**Comment by niksauer** [comment]
I still have this issue. Any option I can force set?

**Comment by niksauer** [comment]
Thanks, [this](https://github.com/microsoft/pyright/issues/578#issuecomment-603370694) comment of yours solved the problem. I had to add an execution environment matching my `"include": ["src"]` setting.

Strange thing is that this wasn't necessary before I had an `__init__.py` file in `src` (which is required for `unittest discover`. 

Here's the setup in case any one comes across the issue again:

**pyrightconfig.json**
```
{
  "include": ["src"],
  "stubPath": "src/typestubs",
  "pythonPlatform": "Linux",
  "typeCheckingMode": "basic",
  "reportMissingImports": true,
  "reportMissingTypeStubs": true,
  "executionEnvironments": [
    {
      "root": "src"
    }
  ]
}
```

**Project Structure**

```
├── Dockerfile
├── Pipfile
├── Pipfile.lock
├── README.md
├── bin
│   └── bootstrap.sh
├── docker-compose.yml
├── pyrightconfig.json
├── setup.cfg
├── src
│   ├── __init__.py
│   ├── app
│   ├── broker
│   ├── evse
│   ├── hems
│   ├── manage.py
│   ├── registry
│   ├── simulation
│   └── util
└── swagger.yml
```

**Comment by jakebailey** [comment]
The auto search path system won't add `src` if it contains a `__init__.py`, as that file existing implies one can do `import src`, and using `src` as an import root might prevent that from working. For example, are you supposed to do `import simulation` or `import src.simulation`? What will `unittest` be attempting to do?

Personally, I wouldn't recommend using a `src` folder if you can avoid it. Import resolution is one reason (among a few). It's more common to have a folder in your workspace that's the project (e.g., the django repo has a top-level folder `django`, and imports things as `django.<something>`, and that avoids a lot of oddities as compared to dropping potentially non-unique names at the top level.
