### ISSUE TITLE
pyrightconfig.json does not seem to allow comments anymore

### ISSUE THREAD

**Issue by strangemonad** [microsoft/pyright#6411]
First, thanks for all the awesome work!

I think this is a regression.
- I know way back in 1.1.115 the parser was changed to JSONC https://github.com/microsoft/pyright/releases/tag/1.1.115
- Then in 1.1.297 some of the JSONC parsing was made more strict. It seems it may now just be allowing trailing commas but no longer accepts comments?
    -  https://github.com/microsoft/pyright/issues/4722#issuecomment-1459138991
    - https://github.com/microsoft/pyright/commit/f8ce7ca1fdc4fab68650dacf2fc1e3ddee365467

This definitely falls under quality of life improvement but it would be handy to be able to leave comments in the config file

**Comment by erictraut** [comment]
I don't think anything has changed here.

I'm not able to repro any problem with slash-slash comments in the config file.

Could you provide repro steps for the problem you're seeing?

**Comment by strangemonad** [comment]
oh my! pardon my fat fingering and tired eyes. I'd converted some things from toml and left a `#` comment 🤦 

Closing this as user error. Thanks again for the tireless and fantastic work on pyright. It really is a charm to have this level of type theory rigor in the python ecosystem
