### ISSUE TITLE
Incorrect Documentation for Import Resolution

### ISSUE THREAD

**Issue by NfNitLoop** [microsoft/pyright#6415]
**Describe the bug**

The import resolution docs [currently say][1] that for absolute imports, Pyright will:

* Try to resolve relative to the root directory of the execution environment. If no execution environments are specified in the config file, use the root of the workspace.
* Try to resolve using any of the extra paths […]
* If no execution environment is configured, try to resolve using the local directory `src`.

What they fail to mention is that absolute imports will **also be resolved** from the directory including the script file.  (Even in [cases where that's not correct][2]. 😞)

[1]: https://github.com/microsoft/pyright/blob/ace7edb41e02b5d6b1490977eff45663bbc43a08/docs/import-resolution.md
[2]: https://github.com/microsoft/pylance-release/discussions/3708#discussioncomment-7536971

**Code or Screenshots**

To reproduce:

`poetry new foo; cd foo`

```python
# foo/__init__.py
import bar

bar.hello()
```

```python
# foo/bar.py
def hello():
    print("hello")
```

It's important to document the fact that Pyright resolves imports this way, because it differs from Python's module resolution when loading/running code as a module:

```
> poetry run python -m foo
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/codyc/code/3rdparty/pyright/bug_repro/foo/foo/__init__.py", line 2, in <module>
    import bar
ModuleNotFoundError: No module named 'bar'
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool? Which version?

I can reproduce this in the CLI and VSCode (Pylance). Seems to be a core pyright error.  Reproduced in v1.1.335.

**Comment by erictraut** [comment]
Thanks for the bug report. Yes, I agree this should be covered in the documentation. I've updated it accordingly.

**Comment by Holi0317** [comment]
Is it possible to turn off this behavior?

**Comment by erictraut** [comment]
> Is it possible to turn off this behavior?

No, not currently. We could consider adding configuration option if there's sufficient demand.

If this resulted in a false positive, there would be more pressure to offer a solution, but it's a false negative.
