### ISSUE TITLE
renaming import alias changes typename as well

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#642]
**Describe the bug**
renaming import alias changes type name as well

**To Reproduce**
```python
from testLib1 import Test1 as t1

a = t1()
```

rename t1 to t2 at t1()

**Expected behavior**
t1 on import statement and t1 on t1() is renamed to t2. but it also changed Test1

**VS Code extension or command-line**
latest pyright extension on vscode

**Additional context**
if I do "FAR" on t1, it finds this

![image](https://user-images.githubusercontent.com/1333179/80542244-8128f700-8961-11ea-82de-3619daa0abe7.png)

it looks like code doesn't distinguish alias symbol with actual symbol it is aliasing.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next version of Pyright.

**Comment by erictraut** [comment]
This is now addressed in version 1.1.35, which I just published.
