### ISSUE TITLE
Doing a star import that contains TypeVar in its scope changes its type to Unknown

### ISSUE THREAD

**Issue by nytelytee** [microsoft/pyright#6420]
**Describe the bug**
Doing a star import that contains TypeVar in its scope twice seems to change its type to Unknown. More info in the code example.

**Code or Screenshots**
Say you have a file called `test_helper.py`, and its only content is a single line that imports TypeVar:
```python
from typing import TypeVar
```

Now, in a different file, you do something like this:
```python
from test_helper import *
T = TypeVar('T')
reveal_type(T)
```
This will reveal the type as `TypeVar`. This is fine, it is what I would expect. 
Now, duplicate the line containing the star import:
```python
from test_helper import *
from test_helper import *
T = TypeVar('T')
reveal_type(T)
```
Suddenly, T's type gets reported as `Unknown`.

It also seems to happen even if you explicitly import TypeVar from typing before doing the two star imports.

In my case, this happened because I accidentally duplicated the star import from a utility file that contains some commonly used objects that happens to import TypeVar; pyright proceeded to complain that `Type argument for "Generic" must be a type variable` when I tried using the TypeVar I created.

I know star imports are generally not good practice, but I still feel like this is weird behavior.
I am not sure if it happens with anything other than TypeVar; I assume so.

**VS Code extension or command-line**
I am running pyright as a command-line tool; this issue happened on `1.1.335`, the latest version at the time of writing this. Seeing that an issue happened, I tried with the latest source to see if the issue had been fixed in the meantime; it was not.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.336, which I just published. It will also be included in a future release of pylance.
