### ISSUE TITLE
verifytypes reports re-exported stdlib functions as missing docstrings

### ISSUE THREAD

**Issue by jakkdl** [microsoft/pyright#6442]
**Describe the bug**
Re-exporting functions from the stdlib in a package, as is done in https://github.com/python-trio/trio/blob/master/src/trio/socket.py#L56, gives errors about them missing docstrings when running `--verifytypes`. Presumably because they lack docstrings in the stubs, which is by design (found #4250 when searching), but feels like `--verifytypes` should have a special case for ignoring that so we're not forced to use `--ignoreexternal` or similar.

**Code or Screenshots**
Minimal repro
`foo/__init__.py`
```python
from socket import gethostname as gethostname
```
```
$ pyright --verifytypes foo 
Module name: "foo"
Package directory: "/tmp/foo/.venv/lib/python3.11/site-packages/foo"
Module directory: "/tmp/foo/.venv/lib/python3.11/site-packages/foo"
Path of py.typed file: "/tmp/foo/.venv/lib/python3.11/site-packages/foo/py.typed"

Public modules: 1
   foo

Symbols used in public interface:

Symbols exported by "foo": 1
  With known type: 1
  With ambiguous type: 0
  With unknown type: 0
  Functions without docstring: 1
  Functions without default param: 0
  Classes without docstring: 0

Other symbols referenced but not exported by "foo": 0
  With known type: 0
  With ambiguous type: 0
  With unknown type: 0

Type completeness score: 100%

Completed in 0.565sec
```

**VS Code extension or command-line**
```
$ pyright --version
pyright 1.1.335
```

**Comment by erictraut** [comment]
Hmm, your library is re-exporting symbols from stdlib? I'm curious why it's doing that. I wouldn't think that's advisable. I don't think I'd want to add special-case handling for this in pyright. 

As a workaround, you could use the `--outputjson` feature of pyright and write a short script to filter the output as you see fit. That way, you could add any special-case exceptions that you want.

**Comment by A5rocks** [comment]
We do it to provide a semi-consistent interface: for instance, we offer async socket capabilities and it is nice not to have to have an extra `import socket` to use e.g. `SO_REUSEADDR` (though that's a bad example cause we intentionally don't reexport it on Windows!).
