### ISSUE TITLE
Unknown type on mypy type stubs, on version 1.1.335.

### ISSUE THREAD

**Issue by BaconPancakes** [microsoft/pyright#6447]
Bit of a shot in the dark in here - apologies for the inarticulation.  

On Release version Pylance v2023.11.0 bundled with `pyright 1.1.332`, the following type hints are possible by having the mypy generated type stubs (pyi) in a typings folder pointed to by VSCode.

Caller code
![image](https://github.com/microsoft/pyright/assets/6261265/fce8a24d-65fd-45a3-9d1f-2e2114cbe28e)

Mypy type stub
![image](https://github.com/microsoft/pyright/assets/6261265/dd883f6d-92ba-40d1-98cb-24e8d7d562e4)

With the pre-release version of Pylance v2023.11.12 bundled with pyright 1.1335, this no longer works:

Caller code
![image](https://github.com/microsoft/pyright/assets/6261265/e6568425-193e-4840-8b39-475081fa1398)

Mypy type stub
![image](https://github.com/microsoft/pyright/assets/6261265/9c7f5b13-9faf-4bd0-87da-af09638962bf)

**Comment by erictraut** [comment]
Could you please provide a minimal, self-contained code sample in text form? Debugging from partial screen shots isn't really feasible.

**Comment by BaconPancakes** [comment]
I was worried that there would be some protobuf weirdness involved, but a minimal reproducible example was easier than I thought.

foo.pyi
```python
from __future__ import annotations
import builtins
import typing

class PhysicalUnits():
    """Define physical units to be used for specifications and conversions"""
    class Unit(_Unit, metaclass=_UnitEnumTypeWrapper):
        pass
    class _Unit:
        V = typing.NewType('V', builtins.int)
    class _UnitEnumTypeWrapper(builtins.type):
        M = PhysicalUnits.Unit.V(2)
```


bar.py
```python
import foo

a = foo.PhysicalUnits.Unit.M   # should resolve to Type[V]


```

**Comment by erictraut** [comment]
This class definition is invalid. It references undefined identifiers.

Note that `from __future__ import annotations` defers evaluation of type annotations, but it has no effect on expressions that are outside of annotations.

Pyright reports these errors, as you can see in the screen shot below. In the future, if you have stubs that are not working as you expect, try opening the stub in pyright to see if there are any errors.

![image](https://github.com/microsoft/pyright/assets/7040122/887f8f0c-f549-4db9-866b-bce57f600341)

You can fix the class definition by reordering the statements and changing the assignment of `M` to a type annotation:

```python
from __future__ import annotations
from typing import NewType

class PhysicalUnits:
    class _Unit:
        V = NewType("V", int)

    class _UnitEnumTypeWrapper(type):
        M: PhysicalUnits.Unit.V

    class Unit(_Unit, metaclass=_UnitEnumTypeWrapper):
        pass

a = PhysicalUnits.Unit.M
```

When you generate a type stub using a tool like mypy or pyright, it's often necessary to manually fix up the results. I tell users that they should consider the output of such a tool as a "first draft". Some manual fix-ups are almost always required. This is a good example.

**Comment by BaconPancakes** [comment]
Thanks for the insight. pyright on `foo.pyi` doesn't report undefined identifiers, but when I rename to `foo.py` I see the errors.

There is indeed an undefined class reference in the generated mypy type stub. I guess my question then relates to how pyright/pylance chooses to handle attributes of classes that inherit from undefined identifiers.

To use your fixed stub as an example:

foo.py
```python
from __future__ import annotations
from typing import NewType

class PhysicalUnits:
    class _Unit():
        V = NewType("V", int)

    class _UnitEnumTypeWrapper(UndefinedClass, type):
        M: PhysicalUnits.Unit.V

    class Unit(_Unit, metaclass=_UnitEnumTypeWrapper):
        pass
```


bar.py
```python
from . import foo

a = foo.PhysicalUnits.Unit.M 
```

In the older version of Pylance/Pyright, `a` actually does still resolve to `PhysicalUnits.Unit.V`. In the new version, pyright reports `unknownMemberType`. 

The mypy type stubs here are generated dynamically from protos, which would mean I would have to patch them dynamically to fix them. So I'd rather keep the old behavior.

**Comment by erictraut** [comment]
> `foo.pyi` doesn't report undefined identifiers

It should show errors (and does for me). Perhaps something in your configuration, such as an "exclude" setting that is suppressing errors for `.pyi` files?

The current behavior in pyright is correct, so I don't plan to make any change here.

As I said, you shouldn't expect to be able to generate stubs and use them without modifications. Some manual fix-ups are almost always required.

**Comment by BaconPancakes** [comment]
Roger that. Thanks for taking the time!
