### ISSUE TITLE
Regression: Self not working as expected

### ISSUE THREAD

**Issue by adampauls** [microsoft/pyright#6460]
**Code or Screenshots**

```python
@dataclass
class Bar:
    foo: "Foo"

@dataclass
class Foo:
    @classmethod
    def get(cls, bar: Bar) -> Self:
        return bar.foo //  error: Expression of type "Foo" cannot be assigned to return type "Self@Foo"
```

New as of 1.1.335 and still present in 1.1.336. Perhaps this is expected behavior but I'm not sure why? 

**VS Code extension or command-line**
Command line.

**Comment by NeilGirdhar** [comment]
Isn't this a correct type error?  How do you know that `bar.foo` is a subclass of `Self`?

**Comment by erictraut** [comment]
Pyright is working correctly here. The type `Foo` is not compatible with the type `Self`. If you were to subclass `Foo`, the type of `Self` would no longer refer to `Foo` in that context.

If `get` always returns an instance of `Foo`, you should change the return type annotation to `Foo`.
