### ISSUE TITLE
Improved decorator type variable solving

### ISSUE THREAD

**Issue by datanorris** [microsoft/pyright#6462]
I'm doing this type of thing

```
from typing import TypeVar, Callable, Optional


_V = TypeVar('_V')
_R = TypeVar('_R')

def decorator_factory(condition: Callable[[_V], bool]) -> Callable[[Callable[[_V], _R]], Callable[[_V], _R]]:
    return lambda f: f

class Foo:
    def decorator_condition(self) -> bool:
        return True

    @decorator_factory(condition=decorator_condition)
    def hello_foo(self) -> None:
        print("hello")

class Bar(Foo):
    @decorator_factory(condition=Foo.decorator_condition) # error "Foo" is incompatible with "Bar"
    def hello_bar(self) -> None:
        print("hello")
```

If I understand right, the solver gets no constraint on `_V` from `condition`, so infers` Foo`, which means the factory creates a decorator on a function taking `Foo`, and can't be applied to a function taking `Bar`.

If the constraint on `self` from `hello_bar` was taken into account, `_V` could have been resolved as `Bar` instead of `Foo`. Can the solver be extended, at least at decorator sites, to look at constraints not just from the arguments passed to the decorator factory, but the argument passed to the generated decorator?

**Comment by erictraut** [comment]
That's not what's happening here. The type of the expression `Foo.decorator_condition` binds `self` to `Foo`. The type of expression `Foo.decorator_condition` is therefore `(Foo) -> bool`. This has nothing to do with the constraint solver.

I think pyright is working correctly here, so I'm going to close this request.

**Comment by datanorris** [comment]
Oh because `Self` is class-scoped when I want a method-scoped type variable

Thanks
