### ISSUE TITLE
Rewriting `for x in ...: yield x` to `yield from ...` changes the inferred signature

### ISSUE THREAD

**Issue by Popkornium18** [microsoft/pyright#6468]
Consider this example:

```
# pyright: strict
import subprocess


def _capture_process_output(command: list[str]):
    popen = subprocess.Popen(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )

    for line in iter(popen.stdout.readline, ""):
        yield line

    popen.stdout.close()
    return_code = popen.wait()
    if return_code:
        raise Exception(f"Process failed with exit code {return_code}")
```

Pyright infers the return type to be `Generator[str, Any, None]`. I would expect that the inferred return Type would not change when rewriting the yield statement as `yield from iter(popen.stdout.readline, "")`. However the return type is inferred as `Generator[str, Unknown, None]` and pyright raises an error: `Return type, "Generator[str, Unknown, None]", is partially unknown`

**Comment by erictraut** [comment]
This is intended behavior. In the case of a simple `yield` statement, the "send type" (the second type argument for `Generator`) is provably irrelevant if the result of the yield expression is not used. In this case, pyright infers the send type as `Any` to avoid emitting a meaningless "partially unknown` error. 

If the result of the yield expression is used (e.g. if you change your code to `x = yield line`, then you'll see that the "sent type" switches to an `Unknown`.

In the case of a `yield from` statement, the "send type" is always relevant, so it's always inferred as `Unknown`.

If you want to avoid this error, you should provide an explicit return type annotation for your generator function.

**Comment by Popkornium18** [comment]
Thanks for the detailed explanation
