### ISSUE TITLE
Returns types of generic properties in subclasses of a generic base class are not type checked.

### ISSUE THREAD

**Issue by elenakrittik** [microsoft/pyright#6476]
**Describe the bug**
If you have a base class `Base` generic over T that has a property defined whose return type is T, overriden property in a subclass of `Base` (called `Concrete`) can have incompatible return type with the one specified in `Concrete`'s base class list.

**Code or Screenshots**
```py
from typing import Generic, TypeVar

T = TypeVar("T")

class Base(Generic[T]):
    @property
    def x(self) -> T: ...

class Concrete(Base[str]): # T specified as str here
    @property
    def x(self) -> int: # int is incompatible with T which is str for this subclass
        return 0
```

**VS Code extension or command-line**
Via command-line and in a command-line IDE via pyright-langserver, both are version 1.133.

**Comment by erictraut** [comment]
Pyright detects this condition if you enable the `reportIncompatibleMethodOverride` configuration option. I'm guessing that you don't have this enabled.

Code sample in [pyright playground](https://pyright-play.net/?code=MQAgDgngTglg5gCwC4C4RQKZgPZSQSQDsBjbAWzAEMkYAjAGwwFkMkFsATAeQDcMpYHDAF4kUAK4YAUFIBmUciCQQwMQnBAwKuJCADiGQvxjEANCAAqKjADVKUGRZDDL1u1AAUAIgteAlDLE9JQAziEgAEKhGB4GRrDEANoWALp%2BKFIgWSAAAmAKYPzKmdlCsiAAHh4hGPSyfiAAtAB8lhnZHSAAdD2BwWEgAMLYJJhIMVE1iSFiae3ZeQVFECVZZZXVtfVNrWqoq51j4lCEIAAMMkA)

**Comment by elenakrittik** [comment]
Oh, you're right, sorry! Although it's a bit unexpected that it's only enabled on "strict" by default.
