### ISSUE TITLE
Incorrect typing when unpacking a  union of TypedDict

### ISSUE THREAD

**Issue by vmeurisse** [microsoft/pyright#6486]
**Describe the bug**
When unpacking a union of `TypedDict`, individual items are typed as `object` instead of the real type.

In the example bellow, `c["a"]` has type `int | str` but when unpacked it becomes `object`.

**Code or Screenshots**
```python
from typing import TypedDict, reveal_type

class DictInt(TypedDict):
    a: int

class DictString(TypedDict):
    a: str

def func(a: int | str):
    ...

def f2(a: DictInt, b: DictString):
    func(**a)
    func(**b)
    c = a or b
    reveal_type(c["a"])  # --> Type of "c["a"]" is "int | str"
    func(**c)  # --> Argument of type "object" cannot be assigned to parameter "a" of type "int | str" in function "func"
```
[pyright-play](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgCYAiSAxjADRQjEBuxAhgDYD68CxAUHyrtWAZxFRKNAJIoYACiK8K1GAEoAXHyjaordZlkCho8ZJgBlGCFRoFJZTQ1adeqCKsDSxYFGABXFCo5V1R8AB83KycdKAA6eM9vXwAmYP0zGTooACN0lUtrdGidf0C5ACpy1lVnbVKgyuyamKooAF5dKFwc2oZmNi4eYjkqAG0AIlZxgF1mkoCG8qpVIA)

**VS Code extension or command-line**
Tested using the lastest cli (1.1.336).

**Comment by erictraut** [comment]
Pyright already contains special-case logic to handle unpacking of a TypedDict class. Adding support for unions of TypedDicts in this case would add significant complexity to an already-complex piece of logic. I'm therefore hesitant to add this for such an edge case. I'm going to reject this feature request for now. I might reconsider in the future if there is sufficient signal from other pyright users that this is an important case.
