### ISSUE TITLE
read-only Protocol variable

### ISSUE THREAD

**Issue by sarisia** [microsoft/pyright#649]
**Describe the bug**

[PEP 544 #protocol-members](https://www.python.org/dev/peps/pep-0544/#protocol-members)
describes how to define a read-only protocol variable as:

> By default, protocol variables as defined above are considered readable and writable. To define a read-only protocol variable, one can use an (abstract) property.

So I tried the code below:

```python
class Proto(Protocol):
    @property
    def field(self) -> bool:
        ...

class ProtoImpl:
    field: bool

a: Proto = ProtoImpl()
```

Then I got this message:
```
Expression of type "ProtoImpl" cannot be assigned to declared type "Proto"
  "field" is an incompatible type
    "bool" is incompatible with "bool"
```

**Expected behavior**

`ProtoImpl` provides readable `field`, so it can be said `ProtoImpl` satisfies
`Proto` protocol that requires read-only variable `field`, I think.

I'm not sure this behavior is intended or not.

**VS Code extension or command-line**
VSCode Extension
`ms-pyright.pyright 1.1.34`

**Comment by erictraut** [comment]
I interpreted the statement in PEP 544 to mean that you would need to use a property in both the protocol definition and the implementation. It strikes me as wrong that one could define it as a property in the protocol definition but a simple member definition in the implementation. A property is similar to a simple member, but there are important differences. Plus, it would be odd that the member is treated as read-only when accessed through a protocol but not through the implementation itself.

I'll need to investigate further.

In the meantime, you can work around this by defining a property in your implementation.

**Comment by sarisia** [comment]
Fine, I can do workaround as suggested. Thank you for quick respond.

**Comment by erictraut** [comment]
I'm going to close this issue as "won't fix". As I mentioned above, I don't think it makes sense to treat a property in a protocol as the same as a non-property field in class that purports to implement that Protocol.
