### ISSUE TITLE
Expression of type "list[str]" cannot be assigned to declared type "list[<Literals>]"

### ISSUE THREAD

**Issue by randolf-scholz** [microsoft/pyright#6513]
```python
from typing import Generic, Literal, TypeVar

K = TypeVar("K", bound=str)
KEYS = Literal["foo", "bar"]

class A(Generic[K]):
    table_names: list[K]

class B(A[KEYS]):
    table_names = ["foo", "bar"]  # ❌
    # Expression of type "list[str]" cannot be assigned to declared type "list[KEYS]"
```

This example checks with `mypy --strict` (1.7.0), but fails with `pyright` (1.1.336).

**Comment by erictraut** [comment]
You haven't declared the type of `B.table_names`. The reason this works in mypy is that it treats simple assignments as type declarations, but pyright does not. Mypy's approach works in this case, but it creates many other problems that are avoided by pyright with its approach. When you don't include a type annotation, pyright infers types.

You can fix this in your code by adding a type declaration for `B.table_names`.

**Comment by randolf-scholz** [comment]
But why doesn't it use the type hint provided by the parent class? `B` is declared as `A[KEYS]`, so we can infer that `B.table_names` is `list[KEYS]`.

**Comment by randolf-scholz** [comment]
Like, the following works just fine in `pyright` as well:

```python
class C(A[KEYS]): ...

reveal_type(C.table_names)  # "C.table_names" is "list[Literal['foo', 'bar']]"
C.table_names = ["foo", "bar"]  # ✅
```

So why does the assignment fail inside the class body....

**Comment by randolf-scholz** [comment]
> You haven't declared the type of B.table_names. The reason this works in mypy is that it treats simple assignments as type declarations, but pyright does not.

The type is declared inside the parent class. `B` is declared as a subtype of `A[KEYS]`, so we can infer that `B.table_names` is `list[KEYS]`. And `pyright` does this inference, after all the error message reads

> Expression of type "list[str]" cannot be assigned to declared type "list[KEYS]"

The issue is that it considered the right-hand side as `list[str]`

Curiously, if we do the assignment outside the class body, it works just fine:


```python
class C(A[KEYS]): ...

reveal_type(C.table_names)  # "C.table_names" is "list[Literal['foo', 'bar']]"
C.table_names = ["foo", "bar"]  # ✅
```

**Comment by randolf-scholz** [comment]
I still feel like `pyright`s behavior here just blatantly violates the gradual guarantee. This code checks with `mypy`, `ty`, `zuban` and `pyrefly`, just `pyright` doesn't like it:

```python
from typing import Mapping, Literal

class Base[Key]:
    items: Mapping[Key, int]

class ImplA(Base[Literal["foo", "bar"]]):
    items: Mapping[Literal["foo", "bar"], int] = {"foo": 1, "bar": 2}  # ✅️

class ImplB(Base[Literal["foo", "bar"]]):
    items = {"foo": 1, "bar": 2}  # ❌️
```
