### ISSUE TITLE
ParamSpec doesn't work with keyword-only parameters

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#6522]
```python
from typing import Generic
from typing_extensions import ParamSpec

P = ParamSpec('P')
class C(Generic[P]):
    def f(self, x: int, *args: P.args, y: int | None = None, **kwargs: P.kwargs) -> int:
        return x + (0 if y is None else y)
```
gives
```
error: Keyword parameter "y" cannot appear in signature after ParamSpec args parameter (reportGeneralTypeIssues)
```

I think if anything, this form that should be allowed over having keyword parameters before positional ones.  When we implemented PEP 448, we considered making the latter pattern illegal.

**Comment by erictraut** [comment]
This behavior is correct. PEP 612 explicitly disallows what you're trying to do here. You are not allowed to include keyword parameters between the `*args: P.args` and `**kwargs: P.kwargs` parameters in a signature.

**Comment by NeilGirdhar** [comment]
Thanks for the quick reply!  I've [started a discussion](https://discuss.python.org/t/allow-keyword-only-parameters-with-paramspec/39326).
