### ISSUE TITLE
Annotated results in Any type annotation when used with VSCODE

### ISSUE THREAD

**Issue by pablovela5620** [microsoft/pyright#6525]
**Describe the bug**
In VSCode, when hovering over a function that outputs a [jaxtyping](https://github.com/google/jaxtyping) type, rather than showing the relevant type (In this example I would expect `UInt8[np.ndarray, "height width 3"]`) it just produces the `Any` type

Based on this issue here over on jaxtyping https://github.com/google/jaxtyping/issues/62 It uses the AnnotatedType under the hood
This may also be a relevant issue https://github.com/microsoft/pylance-release/issues/2306

**Code or Screenshots**
![jaxtyping-any](https://github.com/microsoft/pyright/assets/25287427/4f8de1a2-e093-42b5-afb7-4fe8185c97fc)

```python
import numpy as np
from jaxtyping import UInt8

def test(sample_input: UInt8[np.ndarray, "height width 3"]) -> UInt8[np.ndarray, "height width 3"]:
    return sample_input


test(np.ones((640, 480, 3), dtype=np.float32))
```

This particular example depends on Numpy and [JaxTyping](https://github.com/google/jaxtyping)

**VS Code extension or command-line**
I am using Pylance in VSCode, the Pylance language server version is 2023.11.10

**Comment by erictraut** [comment]
This isn't the behavior I'm seeing. 

![image](https://github.com/microsoft/pyright/assets/7040122/79cf8feb-7784-42f0-bd12-a65f0c5b1040)

Perhaps you have an old version of `jaxtyping` installed? Try `pip install jaxtyping --upgrade`. If that doesn't work, try upgrading `numpy` as well.

**Comment by pablovela5620** [comment]
I'm using jaxtyping 0.2.23 (the latest version) and 1.26.0 numpy (latest version is 1.26.2) could this have to do with my version of VSCode?

Another question I have, you mention here https://github.com/microsoft/pylance-release/issues/2306#issuecomment-1024813328 that pyright/pylance does not provide the metadata outside of the first parameter. Are there any vscode settings that can be changed such that they can be provided on hover?

especially when dealing with lots of tensors/arrays theres alot of value knowing what the expected shape should be on hover
so rather than just `ndarray` the following `UInt8[np.ndarray, "height width 3"]` would give much more context

**Comment by erictraut** [comment]
> I'm using jaxtyping 0.2.23

Hmm, then I can't explain why we're seeing different results.

> could this have to do with my version of VSCode?

No, that's unlikley. It's possible that it has something to do with your virtual environment. You could try creating a new venv from scratch.

> Are there any vscode settings that can be changed such that they can be provided on hover?

No. For the reasons I mentioned above, it's unlikely that such functionality would be added.

**Comment by LTMeyer** [comment]
Hello,

> especially when dealing with lots of tensors/arrays theres alot of value knowing what the expected shape should be on hover so rather than just ndarray the following UInt8[np.ndarray, "height width 3"] would give much more context

I'm following up on this issue. On many projects involving arrays or tensor, it is indeed particularly useful to get to know their shapes. Jaxtyping is a great tool to declare these shapes directly in the types. However, they cannot be visualized in one glance on VSCode when putting the mouse over a function. Where would changes required to be able to see such shapes in the IDE?

Below are some related issues that may have been already mentioned:
- https://github.com/microsoft/pylance-release/issues/2306 where [@erictraut 's comment](https://github.com/microsoft/pylance-release/issues/2306#issuecomment-1024813328) indicates this could/should not be done.
- https://github.com/patrick-kidger/jaxtyping/issues/163 where [@patrick-kidger's comment (https://github.com/patrick-kidger/jaxtyping/issues/163#issuecomment-1926349539)] indicates this should be done outside of jaxtyping itself.

**Comment by LTMeyer** [comment]
Thank you so much for the quick reply. I'll check this thread with interest.
