### ISSUE TITLE
Uppercase constant cannot be redefined during first assignment

### ISSUE THREAD

**Issue by carlos-souto** [microsoft/pyright#6538]
I am not sure if this is the intended behaviour...
I am using "strict" type checking mode.

Consider the following example:
```python
MY_CONSTANT: int
match input("INPUT VALUE: "):
    case "0": MY_CONSTANT =  0
    case "1": MY_CONSTANT =  1
    case "2": MY_CONSTANT =  2
    case _:   MY_CONSTANT = -1
```

The type checker raises the issue: 
"MY_CONSTANT" is constant (because it is uppercase) and cannot be redefined

![image](https://github.com/microsoft/pyright/assets/83190503/f99fb911-ceb0-4091-9fba-101d3234e964)

However, the constant is not being redefined, only the assignment depends on some variable.
This may be relevant when a constant is first initialized during a module's initialization.

**Comment by erictraut** [comment]
Yes, this is intended behavior. Your code is assigning different values to the constant (i.e. giving it a different definition on different code paths). If your intent is for this to be a constant, it should be assigned a single value. If your intent is not for this to be a constant, it shouldn't be named as though it is.
