### ISSUE TITLE
Django queryset method no found

### ISSUE THREAD

**Issue by karambaq** [microsoft/pyright#6542]
**Describe the bug**
Can't go to the definition of the django model queryset method 

**Code or Screenshots**
```python
from django.db import models


class TestModelQuerySet(models.QuerySet):
    def custom_filter(self):
        return self.filter(...)


class TestModelManager(models.Manager):
    ...


class TestModel(models.Model):
    objects = TestModelManager.from_queryset(TestModelQuerySet)()


TestModel.objects.custom_filter() # <-- When I'm trying to go to definition of objects or custom_filter it fails
```

1) When I'm trying to go to the definition on `custom_filter` it fails
2) When I'm trying to go to the definition on `objects` it opens `.pyi` file
Btw, PyCharm can find the method with the same code above.

# Requirements:

```
asgiref           3.7.2
Django            4.2.7
django-stubs      4.2.6
django-stubs-ext  4.2.5
pip               23.3.1
setuptools        68.2.2
sqlparse          0.4.4
types-pytz        2023.3.1.1
types-PyYAML      6.0.12.12
typing_extensions 4.8.0
```

**VS Code extension or command-line**
I'm not sure, I guess as VSCode extension integrated into PyLance but I have installed both.
Pylance: v2023.6.40

**Comment by erictraut** [comment]
Pyright is working as designed here, so I don't consider this a bug.

This is a known problem in the django stubs. The issue is that the `BaseMode` defines `objects` as follows:

```python
    objects: ClassVar[BaseManager[Self]]
```

You have assigned a value to `objects`, but you haven't provided a type declaration for it, so the base class type declaration is used. You will need to provide a type declaration in the `TestModel` class if you want this to work in pyright.

```python
class TestModel(models.Model):
    objects: ClassVar[TestModelQuerySet] = TestModelManager.from_queryset(TestModelQuerySet)()
```

**Comment by mvaled** [comment]
Hi @erictraut,

Even the explict annotation, it fails in some scenarios:

```python
class TombstoneQS(db.QuerySet["Tombstone"]):
    def dispose(self, *, batch_size: int = 200): ...

class Tombstone(db.TrackedModel, db.Model):
    filename = models.CharField(max_length=MAX_ATTACHMENT_NAME_LENGTH)
    objects: t.ClassVar[TombstoneQS] = TombstoneQS.as_manager()  # type: ignore
```

But it says:

```
attachments/tasks.py:92:20 - error: Cannot access member "dispose" for type "BaseManager[Tombstone]"
```

Please note that the explicit type annotation did work in version 1.1.323.

**Comment by mvaled** [comment]
Hi @erictraut,

I created this sample repository that show-cases the issue: https://github.com/mvaled/pyrightbug6542

**Comment by erictraut** [comment]
You're using an outdated version of `django-types`. If you update to the latest version, the problem will go away.
