### ISSUE TITLE
`Self` detection is incorrect when using an unbound method

### ISSUE THREAD

**Issue by jace** [microsoft/pyright#6544]
**Describe the bug**

When investigating problems in Mypy's handling of `Self`, I found an edge case where Pyright gets it wrong. The full report is at https://github.com/python/mypy/issues/16554 and the specific issue in Pyright is with calling unbound methods that return `Self`. Pyright assigns `Self` from the class on which the method is called, not the instance that is passed in for the `self` parameter. Mypy does the opposite. PEP 673 does not specify the correct behaviour for such a call.

```python
from typing import Self

class Parent:
    def method(self) -> Self:
        return self

class Child(Parent):
    pass

p = Parent()
c = Child()
reveal_type(Child.method(p))  # Pyright: Child, but actual is Parent
reveal_type(Parent.method(c))  # Pyright: Parent, but actual is Child
```

**Comment by erictraut** [comment]
As I mentioned in my response to https://github.com/python/mypy/issues/16554, I think pyright's behavior is correct here. I don't consider this a bug.
