### ISSUE TITLE
Ignore Python 2 import

### ISSUE THREAD

**Issue by jugmac00** [microsoft/pyright#656]
Hi,

for one of my projects I still have to maintain Python 2 compatibility.

My import section looks like
```
try:
    # Python 2
    from xmlrpclib import ServerProxy
    from xmlrpclib import Fault
    from xmlrpclib import ProtocolError
except:
    # Python 3
    from xmlrpc.client import ServerProxy
    from xmlrpc.client import Fault
    from xmlrpc.client import ProtocolError
```

Also see the attached screenshot
![Screenshot from 2020-05-05 09-39-36](https://user-images.githubusercontent.com/9895620/81044374-841d6d80-8eb4-11ea-9ad3-8dd8d1b7aaa6.png)

In #144 you made clear there will be no #noqa annotation.

What is the recommended way to silence the shown errors?

I looked through the documentation but could not find anything.

Thank you very much!

**Comment by erictraut** [comment]
You have a few options:
1. Use # type: ignore on each line
2. Use # pyright: reportMissingImports=false at the top of the file
3. Replace the try/except with a conditional test based on python version, like the following:

```
if sys.version_info < (3,):
    # Python 2
    from xmlrpclib import ServerProxy
    from xmlrpclib import Fault
    from xmlrpclib import ProtocolError
else:
    # Python 3
    from xmlrpc.client import ServerProxy
    from xmlrpc.client import Fault
    from xmlrpc.client import ProtocolError
```

**Comment by jugmac00** [comment]
Thank you very much!
