### ISSUE TITLE
Variable subtype override is incompatible

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#6564]
The [Inheritance of Class and Instance Variables](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=inheritance-of-class-and-instance-variables) docs state a variable override using a subtype is OK:
```python
class Parent:
    x: int | str | None
    y: int

class Child(Parent):
    x: int  # This is OK because 'int' is a subtype of 'int | str | None'
    y: str  # Type error: 'y' cannot be redeclared with an incompatible type
```

however pyright 1.1.337 with `reportIncompatibleVariableOverride=true` doesn't like the override `x:int`: 

```
  check.py:6:5 - error: "x" overrides symbol of same name in class "Parent"
    Variable is mutable so its type is invariant
      Override type "int" is not the same as base type "int | str | None" (reportIncompatibleVariableOverride)
```

**Comment by erictraut** [comment]
The error is correct for the reasons indicated in the error message. The field is mutable, so it is invariant — i.e. its type must match exactly in the child class. It cannot be a subtype.

Here's an example of how this leads to type violations:

```python
class Parent:
    x: int | str | None

class Child(Parent):
    x: int

def modify_parent(p: Parent):
    p.x = ""

c = Child()
modify_parent(c)
# At this point, Child is corrupt because `x` is not an `int`
```

**Comment by tekumara** [comment]
Are the docs incorrect then? They state:

```
class Child(Parent):
    x: int  # This is OK because 'int' is a subtype of 'int | str | None'
```

**Comment by erictraut** [comment]
Ah yes, the documentation was out of date. I just fixed it.
