### ISSUE TITLE
Using typing.get_args with the new 3.12 PEP 695 feature (Type Parameter Syntax)

### ISSUE THREAD

**Issue by Questionsdenombres** [microsoft/pyright#6576]
## Environment data
- Windows 11
- Python 3.12
- VScode: 1.84.2
- Pylance: v2023.11.10

## Code Snippet
```python
from typing import get_args, Literal

type T = Literal["a", "b"]
values = get_args(T.__value__) # pylance reports apply on this line
print(values)
```

## Analysis
Moving "TypeAlias" to the new type parameter syntax (3.12 PEP 695 feature), I understand they are not completely equivalent
and typing.get_args behaves differently. 

I moved as stated in [CPython #112472](https://github.com/python/cpython/issues/112472) and it works fine.

However pylance reports:
- Type alias "T" cannot be used in this context
- Type of "__value__" is unknown

It's probably not a bug, but a not considered limit case.

Simplification using PEP 695 is great.
Great job !

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.339, which I just published. It will also be included in a future release of pylance.
