### ISSUE TITLE
Overload detection bug: arg formed by lists concatenated with addition operator

### ISSUE THREAD

**Issue by DeflateAwning** [microsoft/pyright#6584]
**Describe the bug**
Getting error (when there should not be an error) about arg formed by lists concatenated with addition operator. Code seems fine to me.

**Code or Screenshots**
If possible, provide a minimal, self-contained code sample (surrounded by triple back ticks) to demonstrate the issue. The code should define or import all referenced symbols.

```python
import subprocess

pg_dump_output = subprocess.check_output(
	['pg_dump'] + pg_dump_command_args + ['--dbname', self.conn_str]
)
```

This gives the error:
```
No overloads for "check_output" match the provided argumentsPyright[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
subprocess.pyi(1629, 9): Overload 6 is the closest match
```

As far as I can tell, this code is fine, and it certainly runs fine.

**VS Code extension or command-line**
VS Code extention

**Comment by DeflateAwning** [comment]
```python

import subprocess

conn_str = 'postgres://some_address.com:5432/db_name'
pg_dump_command_args = ['--schema', '--no-permissions']

pg_dump_output = subprocess.check_output(
	['pg_dump'] + pg_dump_command_args + ['--dbname', conn_str]
)

```

**Comment by erictraut** [comment]
Thanks, but I don't see any type errors with the above code sample. Please confirm that you are seeing an error.

**Comment by DeflateAwning** [comment]
Issue was elsewhere in the code. Thank you for checking anyway.
