### ISSUE TITLE
`typing.Self` is not usable as a value

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/pyright#6587]
Possibly related to #6582.

Code sample in [pyright playground](https://pyright-play.net/?strict=true&enableExperimentalFeatures=true&code=JYWwDg9gTgLgBDAnmYA7A5gKAGZQiBZNdOUSWOAZQFMAbbTTAE2u1IGcB9du7AChgAuQmGoBKQZjjS4UajACuUVAg5VeUmQGIZu3QD9D%2BzdJ0AiGvTNrUEeADcAhrWBNSKmAAtg7OAGMIVBhqAA8YRh9uXj50eUcYGCgBIgwAGjgLXjMxMTgdABUoBWogA)

```python
import typing
from typing import Self

def is_self(t: type):
    return t is Self
    #           ~~~~
    # "Self" is not valid in this context

is_self(getattr(typing, "Self")) # True
```

In this example, I get the following error:

```
"Self" is not valid in this context
```

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.339, which I just published. It will also be included in a future release of pylance.
