### ISSUE TITLE
Detect Impossible Value Comparisons in Union and Literal Types

### ISSUE THREAD

**Issue by philippHorn** [microsoft/pyright#6602]
**Is your feature request related to a problem? Please describe.**
It would be really nice to have a way to stop comparisons of Union/Literal variables against values that can not possibly be in the Union.
**Describe the solution you'd like**
I think this example highlights what I mean pretty well:
```
source: Literal["http", "websocket"] = "http"
if source == "websocke":
    do_something()
```
I would like this to be detected by the type check and ideally have a similar behaviour for Unions as well.

**Comment by erictraut** [comment]
Pyright already support this capability, but it's not enabled by default. You need to enable the `reportUnnecessaryComparison` check.

Code sample in [pyright playground](https://pyright-play.net/?pyrightVersion=1.1.337&code=MQAgDgngTglg5gCwC4C4RQKZgPZSQVQDtCMBjDAZwoEMoIBhbAWzFpgu0IF4koBXDAChBAMyjMQSCGBiE4IGC1xIQAGRhIMUagBthHPlHJp1m7ToDaAImRIwVgDQgrAdwwAjDqQDWGJFYBdEC5nW3tBGBEQAyMMYJDXDy9fKxRBEAzwaiphIA)
