### ISSUE TITLE
Class attribute / methods starting with __ (double underscore) is still valid out of class

### ISSUE THREAD

**Issue by Starmania** [microsoft/pyright#6605]
**Describe the bug**
When you name a instance or a method of a class (didn't tested for module) starting with two underscore, pyright continue to think theses objects are accessible to other contexts that the class itself. 

**Other info**
PEP008: *name mangling*

**Code or Screenshots**
[Pyright playground](https://pyright-play.net/?code=MQAgKgFglgziDGB7AJgUxDCiDucCGCANnjHNlAC4QgEAOATlAG54XqsWMBGArmyNiwhYCRADsYUNPVTIa8VKShdC6RHxCIAZhiS1UAKCPxipGgGFTMAFwGQ9kGh0B9Z1DGVXAChipCWgEoQAFoAPhAAOXFUWwc4jD8tADpXBmZWVAB5LgArVHgKEABecHoeQzi7BycQV0x1QmRnMUQKZzxafTx6H0SA2Pj7WhIYYysQLksRrzwp0n6q%2BxrXd09nXv8gsMjogcGYHn0egJS3Dzb1gMX467jff1O0ljZsvILbh3vkuqweRubWu1Oqhul4rkZQABBQplMQUKAAW1QABphIVyIRCCB6HhYOhoZxlHxUABRej0RD0VEABRJ1IADPSABzWEBiPBIkAIvBiADmhHcvIMsysYMejGeWVy%2BQowrmMDFPwaTRabQ6XWORiAA)

```python
class aClass:
    def __init__(self) -> None:
        self.__privateObject = True
    
    def __should_not_appear(self):
        pass

class bClass(aClass):
    def __init__(self) -> None:
        super().__init__()
        
        self.__privateObject
        self.__should_not_appear()


# At runtime, it will raise AttributeError, PEP008: name mangling
aClass().__privateObject
aClass().__should_not_appear()
```

**VS Code extension or command-line**
Tested with Vscode, Pylance v2023.11.13

**Comment by erictraut** [comment]
Pyright supports this check if you enable `reportPrivateUsage`.

Code sample in [pyright playground](https://pyright-play.net/?code=MQAgDgngTglg5gCwC4C4RQKZgPZSQBVgDcBDJDAVQGcS4MBeJKAVwwCg2BjAGxKqpAkAwr34o2ISSAAmGAGYgA%2BopgA7GEmUAKKhm5yAlCAC0APhAA5bKozip9kLv0A6ZWGJkMAeQBGAKwxOJBB6EAAVFnZ7CSlZBWUqBGxmbmlFVWxNEjAwDBIoHT1DOwdJMD4qDh4KkB8RCq1hUSoDEsk4pRV1TUVC-SMzS2tbGNKqZlyCg1cujW0DUYdF%2Byc5GfcYUnJfAKDlqVWZxOTU9MzFbNz8rQWOUABBYJZVJBgAWwwAGhANEAB3GDcbjoEgwXQgR5MGA%2BZjkACiUCguG%2B%2BDh%2BAADOiABxoVQkD4gN4kVRwbhqOBsJoNaZuDzbfyBJCU%2Br8G5HJIpNIZLI5PJTDhAA)
