### ISSUE TITLE
variable has incorrect type after being narrowed inside context manager that suppresses an exception

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#6620]
**Describe the bug**
when a context manager that suppresses an exception assigns to a variable, its type is incorrect afterwards

**Code or Screenshots**
```python
from contextlib import AbstractContextManager
from types import TracebackType
from typing import Generic, Literal, TypeVar, override, reveal_type

out_T = TypeVar("out_T", covariant=True)


class SuppressError(Generic[out_T], AbstractContextManager[out_T]):
    @override
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
        /,
    ) -> Literal[True]:
        return True


foo: Exception | None = None

with SuppressError():
    foo = Exception("asdf")
    raise Exception

reveal_type(foo) # pyright says None, but it's Exception at runtime
```
[playground](https://pyright-play.net/?strict=true&code=GYJw9gtgBAxmB2AXApgD0QGwJYCMpYgAcwREoBBHAZ0RAEMZEBhBFdAWTvjoHNkQAsAChQkKIgCehZFXxESZACr0YyHAwDWiqcmGjokwlng85xUlADiyePywwANFAAyWFPQxPt0gGp0QTmAAbvwgWAAmyE4gyCF0GAD6hrpCwmAArogJilAAvFDeyH4gABQARBlZimVOcEH%2BWFyIucrpyACUwl1CMBh0VLIAyumEhDEDAKIg4KXWtmEwANqV2QC6TpQ0KsysaIic3Hwgy5lr7QBcwlDXUAACwaERKTdQkcBQCQlobp8lVy83KjIDDABz-AFQNAwJI6c7iHSLABC-WQE1QqkIiCwCFWUAAPlAAHIIKLggFQhL1DBtOHIoFojFYhD4okksFCCHXWgMNSaOHKHnqGBaHQs4m2dmcqAAeklN3aUAAtAA%2BFxufjxRatZCrS4czkxRDpEDwAogNrdPRgMBwhnITHY00E8XIPKs2zdADubgAFlBhqNxlQpjMShcycBrW67Q6EOV%2BuFgGVOvrrvQsECoDGmfBujE4olkiVI2AFQBiKCECRhHg%2BshUOgSWQupw4TL4RAAclk2cdUDoZHNSAIyCAA)

**Comment by erictraut** [comment]
Thanks, I'm able to repro this, and I agree it's a bug. I'll investigate further.

**Comment by erictraut** [comment]
This will be addressed in the next release.
