### ISSUE TITLE
`AbstractContextManager.__enter__`'s return type is `_T_co` when it returns `Self` at runtime

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#6624]
from https://github.com/python/mypy/issues/16605. seems like pyright has the same issue, so i originally thought it was a typeshed problem but as far as i can tell it's not, but rather both type checkers seem to be special casing `AbstractContextManager`.

----

```py
from contextlib import AbstractContextManager
from types import TracebackType
from typing import reveal_type, override


class Foo(AbstractContextManager[int]):
    @override
    def __exit__(
        self,
        __exc_type: type[BaseException] | None,
        __exc_value: BaseException | None,
        __traceback: TracebackType | None,
    ) -> bool | None:
        return super().__exit__(__exc_type, __exc_value, __traceback)


with Foo() as a: # no error
    reveal_type(a) # pyright says int, but it's actually Foo at runtime
```
[playground](https://pyright-play.net/?code=GYJw9gtgBAxmB2AXApgD0QGwJYCMpYgAcwREoBBHAZ0RAEMZEBhBFdAWTvjoHNkQAsAChQkKIgCehZFXxESZACr0YyHAwDWiqcmGjokwlng85xUlBDIAbsjoYA%2BoeQAaKGFsgQWACa6hwsIwGHRUsgBiYGAAFJQ0KsysaIic3HwgANrGiAC6AJQAXMJQJVAAAh783n7FpX7AUA4OaFiITdG1paVUyBjALp1djc2oME46BeI6GQBCocgAoqPIhIhYCDlQAD5QAHIIroNdTWhj1vYArsiTcz1Lqqvr8Nt7BwNCQ6VNtAxqmpPKX7qGBaHQvfbwQ4fUp5KAAWgAfFAcFEMOCDkVoZ8rIgLiBnlQLtIQNE8gA6E6oVrtSljZxuWkOc4YK4MpwqP4gvKBAJCADurQAFlBIjFYaEoHRJgBiKDwMBQKokQZWWz2cbSaJ0WGywgSbw8QVkKh0CSybJuHAXMitADksgYuPsGAkIqikrIIAuSAIyCAA)

i think this is because in the stubs, `__enter__` is not marked as an abstract method, but since it's a protocol it should be treated as abstract regardless:
```py
# contextlib.pyi
@runtime_checkable
class AbstractContextManager(Protocol[_T_co]):
    def __enter__(self) -> _T_co: ...
```
and in the `AbstractContextManager` implementation, it returns `self`.
```py
# contextlib.py
class AbstractContextManager(abc.ABC):

    """An abstract base class for context managers."""

    __class_getitem__ = classmethod(GenericAlias)

    def __enter__(self):
        """Return `self` upon entering the runtime context."""
        return self
```

copy/pasting the stub makes it work correctly, so it appears that there's some special casing that's causing this behavior:
```py
from types import TracebackType
from typing import reveal_type, override, runtime_checkable, Protocol, _T_co
from abc import abstractmethod

@runtime_checkable
class AbstractContextManager(Protocol[_T_co]):
    def __enter__(self) -> _T_co: ...
    @abstractmethod
    def __exit__(
        self, __exc_type: type[BaseException] | None, __exc_value: BaseException | None, __traceback: TracebackType | None
    ) -> bool | None: ...


class Foo(AbstractContextManager[int]): # error: Class derives from one or more protocol classes but does not implement all required members
    @override
    def __exit__(
        self,
        __exc_type: type[BaseException] | None,
        __exc_value: BaseException | None,
        __traceback: TracebackType | None,
    ) -> bool | None:
        return super().__exit__(__exc_type, __exc_value, __traceback)


with Foo() as a:
    reveal_type(a)
```

**Comment by erictraut** [comment]
Protocol classes can provide [default implementations of methods](https://peps.python.org/pep-0544/#protocol-members), and if a class explicitly derives from that class, it inherits those implementations. 

Pyright distinguishes between a default implementation and a "template" method by looking for a `...` in the method body. If a `...` is present, it assumes that means "this must be implemented by a subclass".

```python
class MyProto(Protocol):
    def method1(self):
        # This is considered a default implementation.
        return None

    def method2(self):
        # This is considered a protocol method that must be implemented for conformance with the protocol.
        ...
```

In stubs, all methods use `...`, so looking for `...` cannot be used to differentiate between these two cases. Pyright therefore skips this check if the protocol class is defined in a stub file.

It looks like typeshed uses the convention that protocol methods are decorated with `@abstractmethod` if they must be supplied by a class, and it omits `@abstractmethod` if it's a default implementation. I don't think this convention is specified in any PEPs. However, upon further investigation, it is alluded to in [PEP 544](https://peps.python.org/pep-0544/#explicitly-declaring-implementation), which says:

> The semantics of `@abstractmethod` is not changed, all of them must be implemented by an explicit subclass before it can be instantiated.

I'll explore whether it's feasible for pyright to adopt this convention. It might be disruptive for existing code bases that use pyright.

If I do make this change, it still won't report an error for `AbstractContextManager.__enter__` without a change to typeshed.

**Comment by erictraut** [comment]
@JelleZijlstra & @AlexWaygood, any thoughts or advice?

**Comment by AlexWaygood** [comment]
I don't understand the premise of the bug report here. There's no error at runtime if you subclass `AbstractContextManager` without overriding the default implementation of `__enter__`. Surely the behaviour we should be _aiming_ for is for type checkers to reflect the runtime behaviour?

```pycon
>>> from contextlib import AbstractContextManager
>>> class Foo(AbstractContextManager):
...     def __exit__(self, *args): pass
...
>>> with Foo() as f:
...     print(f)
...
<__main__.Foo object at 0x0000022EF9991340>
```

> It looks like typeshed uses the convention that protocol methods are decorated with `@abstractmethod` if they must be supplied by a class, and it omits `@abstractmethod` if it's a default implementation.

In general, our policy is to accurately reflect what happens at runtime, unless there's a good reason to do otherwise. I don't think we have a special exemption to that policy (yet) for protocol methods: if it's decorated with `@abstractmethod` at runtime, we try to make sure it also has that decorator in the stubs.

It's possible we should start decorating more protocol methods with `@abstractmethod` in our stubs. I can see the point you're making about type checkers finding it hard to differentiate protocol members with "mixin methods" that are provided as a convenience for people subclassing the protocol.

In general, I rather wish mixin methods weren't a thing. From my experience, they're still pretty underspecified, and cause a lot of issues like this for type checkers, stub authors, and the implementation of `typing.Protocol` at runtime :(

**Comment by AlexWaygood** [comment]
> i guess the issue is that since the abstract method in the stubs doesn't reflect the actual method, so not implementing it causes the method that returns the wrong type to be called.

And this is exactly why mixin methods in protocols and ABCs are problematic. We can't annotate `__enter__` as returning `Self` in the stubs, or we're effectively mandating that _all_ context managers _have_ to return `Self` from `__enter__` in order for type checkers to consider them valid implementations of the `AbstractContextManager` protocol. That would obviously be incorrect. But by giving `AbstractContextManager.__enter__` the more vague return type `_T_co` in the stub, we put direct subclassers of the protocol who want to make use of the mixin method at a disadvantage. It's an impossible situation for us at typeshed; there's no way to please everybody here.
