### ISSUE TITLE
"possibly undefined" false positive in `finally` block when `try` and `except` blocks assign to the same variable, and exception is not assigned to an existing variable

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#6628]
```py
try:
    a = 1
except BaseException:
    a = 2
finally:
    print(a) # error: "a" is possibly unbound
```

i know this was raised before (https://github.com/microsoft/pyright/issues/2402#issuecomment-939351854), but i think pyright should be able to detect whether the exception is being assigned to a variable that has already been defined or not. here, that isn't the case so it's safe to assume that it can never be unbound

**Comment by erictraut** [comment]
Pyright is working as designed here. I don't consider this a bug.

**Comment by DetachHead** [comment]
why not? it's impossible for this variable to be unbound, and i don't see why pyright can't simply check whether the variable the exception is being assigned to has already been defined or not, which if i understand correctly is the only possible way that can happen
