### ISSUE TITLE
Dict comprehension and typeddict

### ISSUE THREAD

**Issue by FrancescElies** [microsoft/pyright#6643]
With the latest pyright version v1.1.338 (4-12-2024) I saw the following not working for TypedDict but works fine with a dict.

```py
# mytest.py
#
# with-env {PYRIGHT_PYTHON_FORCE_VERSION: "latest"} { pyright mytest.py }
from typing import TypedDict


class Letters(TypedDict):
    vowels: dict[str, str]
    consonants: dict[str, str]
    numbers: dict[str, str]


a_dict: dict[str, dict[str, str]] = {
    "vowels": {"a": "1"},
    "consonants": {"b": "2", "c": "3"},
    "numbers": {"1": "4"},
}
a_typeddict: Letters = {
    "vowels": {"a": "1"},
    "consonants": {"b": "2", "c": "3"},
    "numbers": {"1": "4"},
}

# this is ok
flat_dict = {k: v for x in a_dict.values() for (k, v) in x.items()}

# pyright throws error
flat_typeddict = {k: v for x in a_typeddict.values() for (k, v) in x.items()}
# mytest.py:22:70 - error: Cannot access member "items" for type "object"
#   Member "items" is unknown (reportGeneralTypeIssues)
# mytest.py:22:68 - error: Type of "items" is unknown (reportUnknownMemberType)
# mytest.py:22:59 - error: Type of "k" is unknown (reportUnknownVariableType)
# mytest.py:22:62 - error: Type of "v" is unknown (reportUnknownVariableType)
# mytest.py:22:1 - error: Type of "flat_typeddict" is partially unknown
#   Type of "flat_typeddict" is "dict[Unknown, Unknown]" (reportUnknownVariableType)
```

Am I missing something or this is a bug?

Thanks

**Comment by erictraut** [comment]
Pyright is working correctly here. This isn't a bug.

A `dict[str, dict[str, str]]` is a nominal type, and all keys in such a `dict` have associated values that are of type `dict[str, str]`. That means `a_dict.values()` returns a value of type `Iterable[dict[str, str]]`.

By contrast, `Letters` is a `TypedDict`, which means it's a structural type definition. A type is compatible with `Letters` if it is a `Mapping[str, object]` with three keys (`vowels`, `consonants`, and `numbers`) whose types are `dict[str, str]`. It is allowed to have other keys as well, and the values associated with those keys cannot be known statically. The only thing that we can say statically is that the value is of type `object`. That means the type of `a_typeddict.values()` returns a value of type `Iterable[object]`.

There is an early [draft of a PEP](https://github.com/python/peps/pull/3441/files) that would allow a `TypedDict` class to specify that it cannot contain any keys beyond those that are specified. With this proposal, you would be able to define `Letters` like this:

```python
class Letters(TypedDict):
    vowels: dict[str, str]
    consonants: dict[str, str]
    numbers: dict[str, str]
    __extra__: Never
```

And then a static type checker could safely determine that `a_typeddict.values()` should return a value of type `Iterable[dict[str, str]]`.
