### ISSUE TITLE
Argument missing error for optional `pydantic.BaseModel` field

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/pyright#6657]
The following code works:

```python
import pydantic

class Person(pydantic.BaseModel):
	lastname: str | None

Person()
```

but pyright 1.1.338 complains:

```
  /tmp/foo.py:6:1 - error: Argument missing for parameter "lastname" (reportGeneralTypeIssues)
```

**Comment by hmc-cs-mdrissi** [comment]
> In Pydantic V1, fields annotated with Optional or Any would be given an implicit default of None even if no default was explicitly specified. This behavior has changed in Pydantic V2, and there are no longer any type annotations that will result in a field having an implicit default value.

You are relying on pydantic V1 behavior that doesn't match with how dataclasses normally works and I'd guess is unlikely dataclass transform would support special casing fields with None as being not required.

```python
class Person(pydantic.BaseModel):
  lastname: str | None = None
```

is needed.

**Comment by erictraut** [comment]
@hmc-cs-mdrissi is correct. It looks like you're relying on behavior that is specific to pydantic. Pyright has no specific knowledge of pydantic's peculiarities. It implements support for pydantic and similar libraries using `dataclass_transform`, introduced in PEP 681. 

To make this code work with pyright, you'd need to modify it so it is consistent with how `dataclass` works, as in the code sample @hmc-cs-mdrissi provided above.
