### ISSUE TITLE
Specialcasing for reportImplicitOverride and @final

### ISSUE THREAD

**Issue by mehdigmira** [microsoft/pyright#6663]
**Is your feature request related to a problem? Please describe.**

The following code logs an error which is fine and makes sense. Event if `random_method` signature is coherent between class A and class B, subclassing B with a class C, would cause C.random_method to return B while it's supposed to return C according to the original signature.

```python
from __future__ import annotations

from typing import Self


class A:
    def random_method(self, data: Self) -> Self:
        ...

class B(A):
    def random_method(self, data: B) -> B:
        ...

```

**Describe the solution you’d like**

Since the problem only arises when subclassing B, would it make sense for pyright to consider that the override if actually coherent if B is marked as final ?

**Comment by erictraut** [comment]
I don't think this special-casing is justified. I also don't think it's aligned with the thinking in [PEP 698](https://peps.python.org/pep-0698/), which introduced `@override`. 

This is a strict-mode check, and I think it should be, well, strict.
