### ISSUE TITLE
Unnecessary extra escaped quotation at the of overrideParamNamePositionOnly diagnostic

### ISSUE THREAD

**Issue by insilications** [microsoft/pyright#6665]
It seems there is an unnecessary extra escaped quotation at the of `overrideParamNamePositionOnly` diagnostic `...is position-only\""`:
https://github.com/microsoft/pyright/blob/a7b3f2e852562701795fa9b132696aa2fbb9812d/packages/pyright-internal/src/localization/package.nls.en-us.json#L672

Version: latest main branch Pyright

**Comment by erictraut** [comment]
Thanks for reporting. This will be fixed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.340, which I just published. It will be included in a future release of pylance.
