### ISSUE TITLE
Provide tests at the LSP level in Pyright

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pyright#6677]
Pylance has a series of tests we run on submission that run the language server in a worker thread and then exercise the language server by passing messages to the worker thread. 

This request is to add these sort of tests to Pyright as well. Theoretically this would have caught this issue:
#6676

**Comment by erictraut** [comment]
@rchiodo, is this work that you have plans to complete in a specific timeframe? If so, what is the approximate timing? If it's just a suggestion for something we might want to do in the future but there are no concrete plans to implement it, then I'd prefer to close it.

**Comment by rchiodo** [comment]
Next month or so was my timeframe. I'm currently working on writing tests in Pylance for virtual workspaces and improving the perf of the URI change on the Pylance side. After that I wanted to add these tests.
