### ISSUE TITLE
"str" is incompatible with "list[]" when adding item to Dictionary

### ISSUE THREAD

**Issue by pymike00** [microsoft/pyright#668]
**Describe the bug**

When adding an item to a Python Dictionary with the dict[key] = value syntax, Pyright throws the following error: **Argument of type "Literal['some-random-string']" cannot be assigned to parameter "v" of type "list[int]" in function "__setitem__"  "str" is incompatible with "list[int]"** . 
Bug seems somehow related to https://github.com/microsoft/pyright/issues/567

**To Reproduce**
1) create bugreport.py file;
2) add the following code:

```
n = [1, 2, 3]
my_dict = {"data": n}

my_dict["s"] = "some-random-string"
```

**Expected behavior**
I expect no error to be shown for adding an element to a dictionary.

**Screenshots or Code**
![bugreport-pyright](https://user-images.githubusercontent.com/32687496/81771849-a77c9400-9516-11ea-877e-55ab3687f4db.png)
```
n = [1, 2, 3]
my_dict = {"data": n}

my_dict["s"] = "some-random-string"
```
error: Argument of type "Literal['some-random-string']" cannot be assigned to parameter "v" of type "list[int]" in function "setitem" "str" is incompatible with "list[int]"

**VS Code extension or command-line**
Pyright is running as a VS Code extension with version 1.1.36

**Additional context**
Bug originally discovered when trying to add an element to a Django View's context, and it doesn't only happen with Lists of Integers.

**Comment by erictraut** [comment]
Thanks for submitting the issue.

Pyright is working as designed in this case. 

The challenge is that when Pyright encounters a symbol with no type annotation, it needs to infer the type from the context. When it encounters a list or dictionary, it needs to infer the type argument(s).

Here are the rules it uses when inferring the type of a dictionary based on an assignment:
1. If the keys and values of the assigned dictionary are all the same type, use those types as the type arguments. 
2. If the keys and values of the dictionary are of mixed types, the behavior depends on the configuration setting "strictDictionaryInference". If this setting is disabled (as it is by default), it assumes that the mixed type argument should be `Any`. If this setting is enabled, it assumes that the mixed type argument should be a union of the types.

Examples:
```
my_dict = {"a": [1, 2, 3]} # assumes type is Dict[str, List[int]]
my_dict = {"a": 3, "b": "random"} # assumes type is Dict[str, Any] or Dict[str, Union[int, str]]
```

Your example above falls under the first case. It's inferring that the type of `my_dict` is `Dict[str, List[int]]`. When you later attempt to assign a value that doesn't match the type `List[int]`, it emits an error.

The workaround is easy: provide an explicit type annotation. When a type annotation is provided, Pyright doesn't need to infer the type. Here's how that would look:
```
my_dict: Dict[str, Any] = {"data": n}
```
Or if you're using a version of Python prior to 3.6:
```
my_dict = {"data": n} # type: Dict[str, Any]
```

Mixed-type dictionaries are generally very bad for static type checking. So is the "Any" type, which effectively disables type checking for that symbol.

If you're using Python 3.8, you can take advantage of the new TypedDict class that allows you to specify different value types for different keys. In your example above, you could define a TypedDict where the type of "data" is `List[int]` and the type of "s" is `str`.

**Comment by pymike00** [comment]
That makes perfect sense indeed.

Thanks for your awesome feedback.

Happy Coding!
Michele
