### ISSUE TITLE
Mark overloads of a function as being deprecated if `warnings.deprecated` is set on the function definition

### ISSUE THREAD

**Issue by Viicos** [microsoft/pyright#6689]
As discussed [here](https://discuss.python.org/t/how-should-warnings-deprecated-be-handled-with-typing-overload/40641):

```python
import warnings

@overload
def func(x: int) -> None:
    ...

@overload
def func(x: str) -> None:
    ...

warnings.deprecated("message")
def func(x: str | int) -> None:
    return None
```

overloads should be considered as being deprecated.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.340, which I just published. It will be included in a future release of pylance.
