### ISSUE TITLE
There is no way to get the full non-truncated pyright error

### ISSUE THREAD

**Issue by carlos-sarmiento** [microsoft/pyright#6694]
**Describe the bug**
I'm running into a typing error using Pyright in which the output of the error is truncated and I cannot read the full error to try to understand what is going on. The actual code being typechecked is not the issue. The issue is that I haven't found any way to get the full, non truncated error Pyright is generating. It seems like the error message is getting truncated somewhere deep in the pipeline.

**Code or Screenshots**
```bash
pyright somePath/sensor_only.py 
somePath/sensor_only.py
  somePath/sensor_only.py:45:53 - error: Argument of type "(entity_id: str, new: HassValue) -> Coroutine[Any, Any, None]" cannot be assigned to parameter "callback" of type "EntityListenerCallback" in function "listen_state_new"
    Type "(entity_id: str, new: HassValue) -> Coroutine[Any, Any, None]" cannot be assigned to type "EntityListenerCallback"
      Type "(entity_id: str, new: HassValue) -> Coroutine[Any, Any, None]" cannot be assigned to type "(*, entity_id: str, attribute: HassValue, old: HassValue, new: HassValue) -> (Awaitable[None] | None)"
        Keyword parameter "attribute" is missing in source
        Keyword parameter "old" is missing in source
      Type "(entity_id: str, new: HassValue) -> Coroutine[Any, Any, None]" cannot be assigned to type "(*, attribute: HassValue, old: HassValue, new: HassValue) -> (Awaitable[None] | None)"
        Keyword parameter "attribute" is missing in source
        Keyword parameter "old" is missing in source
      Type "(entity_id: str, new: HassValue) -> Coroutine[Any, Any, None]" cannot be assigned to type "(*, entity_id: HassValue, old: HassValue, new: HassValue) -> (Awaitable[None] | None)"
    ... (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations 
```

If your code relies on symbols that are imported from a third-party library, include the associated import statements and specify which versions of those libraries you have installed.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool? Which version?

Command line -> v1.1.339

**Comment by erictraut** [comment]
This is by design. Error messages can be arbitrarily long, so there needs to be some limit on them. Pyright is already providing way more details than other type checkers by providing hierarchical error information. 

If you need help understanding why pyright is generating an error in a particular location, feel free to post a question to the pyright discussion forum. Please include a minimal, self-contained code sample.

**Comment by carlos-sarmiento** [comment]
I understand truncating the error message for the majority of use cases, but in this case it would actually be useful to see the full hierarchy of the check. Would this work better as a feature request (adding a flag to the CLI to remove the limit during a specific call) or would that also be rejected?

I appreciate the advise of posting on the forum, but in this case, if I could see the full hierarchy I could resolve my issue without having to post. This would be faster and less work than preparing a self-contained example and running the risk of people not responding.

**Comment by erictraut** [comment]
> Would this work better as a feature request (adding a flag to the CLI to remove the limit during a specific call) or would that also be rejected?

That would be rejected. This doesn't meet the bar for adding a new command-line option.
