### ISSUE TITLE
Usage of dir on a Module throws an error

### ISSUE THREAD

**Issue by TheCleric** [Microsoft/pyright#67]
**Describe the bug**
When running the builtin `dir` function on an imported module an error is shown:
`Argument of type 'Module' cannot be assigned to parameter of type 'object'`

**To Reproduce**
```python
import builtins

dir(builtins)
```

**Expected behavior**
No error is thrown for this valid usage of dir.

**VS Code extension or command-line**
VS Code

**Additional context**
Python 3.6 (Anaconda)

**Comment by erictraut** [comment]
Thanks for the bug report. I just checked in a fix, which will be part of the next release.

**Comment by erictraut** [comment]
This is fixed in 1.0.11, which I just released.
