### ISSUE TITLE
Rust style type inference on further usage of a variable

### ISSUE THREAD

**Issue by gaurishg** [microsoft/pyright#6710]
Pycharm can infer more concrete datatype of objects based on its usage down the line. For example
```python
list_of_ints = [] # Pycharm infers it as list[int] based on next line
list_of_ints.append(1) # VS Code remains at list[Any]

x = list_of_ints[0] # x is infered as int in Pycharm and Any in VS Code
```

If we can get such inference in Pylance, it would save so much time spent in typing.

![Screenshot from 2023-04-06 20-55-57](https://user-images.githubusercontent.com/30369942/230373974-d75eac55-d587-4b51-911a-dce7833652c8.png)

![Screenshot from 2023-04-06 20-56-06](https://user-images.githubusercontent.com/30369942/230374018-8e23908e-61b2-4f70-b5b2-7a7765882717.png)

![Screenshot from 2023-04-06 20-56-14](https://user-images.githubusercontent.com/30369942/230374048-fffafb8c-9482-4b3f-94e5-421dec6f2a76.png)

![Screenshot from 2023-04-06 20-56-21](https://user-images.githubusercontent.com/30369942/230374075-69e244de-c46b-4d9d-b57e-1296daf3f915.png)

**Comment by erictraut** [comment]
After thinking about this more, I don't think this would be a good idea. It would introduce inconsistent type inference behaviors in pyright. It would also require some hard-coded assumptions about the way that certain methods in the `dict` and `list` classes work. Hard-coding knowledge of specific methods within specific classes is something that we generally avoided in pyright. Type information for `dict` and `list` and their associated methods are provided by the typeshed stubs, and hard-coding knowledge beyond what is provided in the stubs is problematic.

The recommended approach here is to provide an explicit type annotation for the variable.

```python
list_of_ints: list[int] = []
list_of_ints.append(1)
```
