### ISSUE TITLE
Some settings have wrong defaults in the schema

### ISSUE THREAD

**Issue by rchl** [microsoft/pyright#6711]
I haven't verified all settings but I've noticed that some have `default` value that doesn't match the actual default value.

For example `deprecateTypingAliases` has `true` in the schema but `false` in documentation (and code):

https://github.com/microsoft/pyright/blob/f605c8fb24c95fbcfc1d5b3ba0a7116ca8169008/packages/vscode-pyright/schemas/pyrightconfig.schema.json#L164C6-L169
https://github.com/microsoft/pyright/blob/fd5900f7e7ec3d492c964da2d2459fca9cfc18ed/docs/configuration.md?plain=1#L310-L310

Same for `enableExperimentalFeatures` for example.

I suppose those defaults would ideally match the default `typeCheckingMode` which currently is `standard`.

**Comment by erictraut** [comment]
Good catch. We've tweaked these default values in the code over time, but the changes haven't always been reflected in the package manifest. I did a pass over all of the type checking settings and fixed the defaults.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.340, which I just published.

**Comment by rchl** [comment]
Also noticed that `reportImplicitStringConcatenation` was `warning` as default in the schema but `none` in practice.

(sorry for not creating a new issue but I though that this can just be drive-by fixed in 1 min)

**Comment by erictraut** [comment]
@rchl, thanks. This will be fixed in the next release.
