### ISSUE TITLE
TypeGuard widens types

### ISSUE THREAD

**Issue by SebbyLaw** [microsoft/pyright#6731]
**Describe the bug**

`typing.TypeGuard` widens the type of a variable when earlier, regardless of if the execution branch is restricted to that guard.

**Code or Screenshots**

```python
from typing import TypeGuard, Literal, reveal_type
import random


def foo(x: str) -> TypeGuard[Literal["c", "d"]]:
    return x in ["c", "d"]

# pretend this came from user input or similar
my_variable: Literal["a", "b", "c"] = random.choice(["a", "b", "c"])

if foo(my_variable):
    reveal_type(my_variable)  # Type of "my_variable" is "Literal['c', 'd']"

reveal_type(my_variable)  # Type of "my_variable" is "Literal['c', 'd', 'a', 'b']"
```

**VS Code extension or command-line**
Reproducible in pyright 1.1.334 and 1.1.440 (latest)

**Comment by erictraut** [comment]
Pyright is working correctly in the code above. This isn't a bug.

I'm not sure I understand what behavior you expect. If you provide more details, I may be able to help you find a solution to the problem you're trying to solve.

If you want to understand `TypeGuard` in more detail, I recommend reading PEP 647. You may also be interested in [PEP 724](https://peps.python.org/pep-0724/) which is in draft form.

**Comment by LyricLy** [comment]
Are you sure it's working correctly? It doesn't make sense to me that the type should be able to widen (turning from `Literal["a", "b", "c"]` to `Literal["a", "b", "c", "d"]`) based on a `TypeGuard`.

**Comment by erictraut** [comment]
> Are you sure it's working correctly?

Yes, this is how PEP 647 works. I'm the author of this PEP, so I can speak with authority here.

Your user-defined type guard function narrows the input type `str` to the return type `Literal["c", "d"]`.

I suspect that you're looking for the behavior specified in PEP 724, which applies a stricter narrowing interpretation. Pyright has provisional support for PEP 724. You can enable it by setting `enableExperimentalFeatures` to "true" in your config. This PEP has not yet been approved, and there's a chance it could be rejected. If that happens, the provisional support will be removed. If it is approved, the provisional support will become the default behavior.
