### ISSUE TITLE
pyright@1.1.340 It doesn't work

### ISSUE THREAD

**Issue by krator3** [microsoft/pyright#6744]
**Describe the bug**
pyright@1.1.340 it doesn't work at all.  It does not display any errors or code hints. In pyright@1.1.339 everything is working correctly. Therefore, this is a mistake and I want everything to work correctly.

**Code or Screenshots**
To reproduce the error, simply create any file with the ".py" extension and create any error. Example:
```python
prnt(j2h)
```

**VS Code extension or command-line**
I am using pyright in neovim on arch linux. Pyright was installed using the Mason extension. I also asked other people if they have the same error. At least 3 more people answered yes. In addition, several other people here mention problems with this version. Also, judging by the reviews from one person, it works, but he installed it through the official archlinux repository. Even in this case, he did not work for me. It's possible that I'm doing something wrong or he didn't say something important, but it needs to work through Mason, as it is the best way to get the right package in any distribution. Developers, if you don't understand something, then write and I will try to give you an answer to your question. Thanks in advance for the interaction!

**Comment by erictraut** [comment]
"It doesn't work" isn't enough for us to go on. 

I don't know what Mason is, and I know nothing about neovim, so I'm not in a good position to help you diagnose the problem. You'll need to provide more details and probably do some of your own debugging.

Here's my best guess... The latest version of pyright contained a massive change that affected nearly every file. Internally, all file paths were converted to URIs to support some new use cases in pylance. I suspect that the problem you're seeing is related to that. We've already fixed a number of regressions related to that change, and those fixes will be included in the next release (1.1.341). We could wait until it's released and see if that fixes things for you.

**Comment by aabbccddeeffggj** [comment]
I have this same error, I'll write here the relevant part of the issue I sent to the neovim repository:

> Hi, for some reason Pyright is not working on my neovim at all, all the other LSPs I use are working, it was working and in the same day it stop doing so.
> 
> I tested with a minimal configuration, tested with neovim's stable release, tested in neovim nightly, all of these gives me the same output: All the LSPs are working, except by Pyright.
> 
> The LSP gets attached with the lsp-config.nvim, but none of its functionality works, the completion I set doesn't work; holding down TAB (the key I choose to toggle on completion + to browse through the options), I lose control over the cursor and have to use my mouse to click on neovim's window to regain it.
> 
> Using the minimal_init.lua configuration with any language servers works, except by Pyright, it returns the following:
> 
> Spawning language server with cmd: `pyright-langserver --stdio` failed. The language server is either not installed, missing from PATH, or not executable.
> 
> I have pyright-langserver in my PATH, I can use this command on a terminal.
> I tested the pyright on terminal and it worked.
> 
>

**Comment by erictraut** [comment]
I just published pyright 1.1.341, which fixes the known regressions introduced in 1.1.340. Please try 1.1.341 and see if it addresses the problem you're seeing.

**Comment by aabbccddeeffggj** [comment]
It is working now, thanks a lot.

**Comment by erictraut** [comment]
Great to hear! I'm going to close this issue then.
