### ISSUE TITLE
PyTorch 1.5.0: torch.Tensor.backward() 'retain_graph'

### ISSUE THREAD

**Issue by schuhschuh** [microsoft/pyright#675]
**Describe the bug**
Pyright error message "no parameter named 'retain_graph'". The tooltip in VS Code shows it expects `keep_graph`, but the PyTorch documentation and source code reveals it should indeed by `retain_graph`.

**To Reproduce**
Paste below code in new file in VS Code with Pyright enabled.

**Expected behavior**
Pyright should recognize `retain_graph` as valid, not `keep_graph`.

**Screenshots or Code**
```
import torch
x = torch.tensor(0.0, requires_grad=True)
x.backward(retain_graph=False)  # line of error
```
![Screen Shot 2020-05-16 at 1 32 00 AM](https://user-images.githubusercontent.com/975451/82105803-1fb0a880-9715-11ea-9362-1ecb50df99dd.png)
![Screen Shot 2020-05-16 at 1 32 08 AM](https://user-images.githubusercontent.com/975451/82105807-263f2000-9715-11ea-98e2-d920b1c61cdd.png)

**VS Code extension or command-line**
VS Code extension version 1.1.36

**Additional context**
- [PyTorch source line defining `torch.Tensor.backward()`](https://github.com/pytorch/pytorch/blob/f39222a13dbad4deaac2dc8c376b630bc2b0da78/torch/tensor.py#L156)

**Comment by erictraut** [comment]
Thanks for the report.

PyTorch ships with type stub files, which is laudable. But it appears that the stub in this case has a bug.

Here's how it defines the interface for the `backward` method:
```
def backward(self, gradient: Optional[Tensor]=None, keep_graph: _bool=False, create_graph: _bool=False) -> None: ...
```
If you think this is in error (and based on what you've said above, it sounds like it is), then you should file a bug against PyTorch and have them fix the type stub. Or you could submit a PR directly to the PyTorch repo with a fix.

In any case, this isn't a bug in Pyright.

**Comment by schuhschuh** [comment]
Thanks, I had a suspicion that this was something to be fixed in PyTorch, but still fail to locate the stub file in their repo. As you've posted a snippet, would mind sharing where to find the file containing it? I can then either submit a PR or reach out to the PyTorch folks pointing at it.

**Comment by schuhschuh** [comment]
Sorry, never mind. I found the stubs in the `torch/__init__.pyi` of my installation.
