### ISSUE TITLE
pyright 1.1.339 thinks enums are mutable

### ISSUE THREAD

**Issue by lengau** [microsoft/pyright#6750]
**Describe the bug**
When overriding a symbol in a child class, if the parent class declares the type `enum.Enum` for that symbol, the child class isn't allowed to make a more precise type definition.

I'm not entirely sure, but this seems like a variation of https://github.com/microsoft/pyright/issues/6725

**Code or Screenshots**
A minimal reproducer:

```python
import enum
class Eee(enum.Enum):
    EEE = "eeeeeeee"

class Parent:
    def __init__(self, e: enum.Enum):
        self.enum_choice: enum.Enum = e


class Child(Parent):
    def __init__(self, e: Eee):
        self.enum_choice: Eee = e

```

**VS Code extension or command-line**
pyright 1.1.339 and 1.1.340 from the command line

**Comment by erictraut** [comment]
The current behavior is correct. Pyright isn't saying that the enum is mutable. However, the `enum_choice` variable is mutable. That means it must be treated as invariant for type safety.

If you want `Parent` to support arbitrary enums, it should be defined as generic.

```python
class Parent[T: Enum]:
    def __init__(self, e: T):
        self.enum_choice: T = e
```
