### ISSUE TITLE
Use bound TypeVar for types synthesized for "self" and "cls" parameters

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#676]
Consider the example:

```
class BaseClass:
    @classmethod
    def c(cls):
        return cls()
    
    def f(self):
        return self
    
class SubClass(BaseClass):
    pass

x = SubClass().f()
y = SubClass.c()
```
x and y should be of type SubClass, but currently they're inferred to be BaseClass.

**Comment by erictraut** [comment]
This is now implemented, although the exact example above doesn't work entirely. The problem is that when the 'self' or 'cls' variable is used within an expression like `cls()`, it needs to be made concrete, so it adopts its bound value. So `cls()` evaluates to type `BaseClass`.

**Comment by erictraut** [comment]
This is implemented in version 1.1.39, which I just published.

**Comment by yellowjello** [comment]
I just found myself running into this exact problem. You mentioned that the example doesn't work entirely, so what changes did you make to the example to get it to work?

**Comment by erictraut** [comment]
You can make the above example work by introducing an explicit type variable for cls.

```
_T = TypeVar("_T", bound="BaseClass")

class BaseClass:
    @classmethod
    def c(cls: Type[_T]) -> _T:
        return cls()

class SubClass(BaseClass):
    pass

a = BaseClass.c() # Type of a is BaseClass
b = SubClass.c() # Type of b is SubClass
```
