### ISSUE TITLE
Pyright  1.1.340 and 1.1.341 is either very slow or stuck forever

### ISSUE THREAD

**Issue by SebastianMorawiec** [microsoft/pyright#6770]
**Describe the bug**
I am running pyright on our python project and it is either very-very slow or just stuck in infinite loop running on a single file. I cant tell which is it - but it takes at least 20 min to finish which at this point I just stopped waiting.

**Code or Screenshots**
Its hard for me to provide single independent example of this bug, but it happens when I try to run pyright on this file:
https://github.com/zapatacomputing/orquestra-workflow-sdk/blob/main/src/orquestra/sdk/_base/_traversal.py

This repo is open-sourced, so for reproduction, just clone it, do 
`pip install -e ".[dev]"`
 and run
`python -m pyright src/orquestra/sdk/_base/_traversal.py`

**VS Code extension or command-line**
I am using python-package pyright. 
Bug happens on versions 1.1.340 and 1.1.341. 
Version 1.1.339 works fine.

Reproduced both locally on M1 Mac machine and our CI which is ubuntu-based github action machine.

**Comment by erictraut** [comment]
Thanks for the bug report. I'm able to repro the problem, and I've determined that it was introduced as part of [this bug fix](https://github.com/microsoft/pyright/issues/6685). I'll investigate further.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.342, which I just published. It will also be included in a future release of pylance.
