### ISSUE TITLE
Isn't able to provide any static analysis from a vendor of a gitrepo installed.

### ISSUE THREAD

**Issue by tagptroll1** [microsoft/pyright#6802]
**Describe the bug**
This might be an odd-ball to describe. I have a private-github repo (On an organisation, if that's relevant), that I installed on my local project through pip. This private repo has a dependency (in this case discord.py) that I use to inherit from in a wrapper class (for commands.Bot), and pyright (and jedi) are unable to provide any static analysis or auto completion for any of the inherited methods.

I've replicated the case in a single file, and multi file project without encountering the issue. It's only relevant to a pip installed git package. I've constructed a simple case here, with `-` in the file name representing a `/` for directories. https://gist.github.com/tagptroll1/10ece9549ba1f4cf83e02b92ca331bc2 

When i import this wrapper class I get autocompletion for the module itself, and `logout` which is a method i defined/overriden in my wrapper. But none of the other methods that should be inherited from commands.Bot are present. 

**Code or Screenshots**
Simplest possible replication is probably to create a repository on github, setup.py and all. It exposes a single class that inherits from some thirdparty (or possibly stdlib?). 
Install the package through pip, i.e `pip install "git+ssh://git@github.com/org/lib.git#egg=packagelib"`
Then try to get autocompletion from the imported package
```py
import packagelib

bot = packagelib.Bot() 
bot.r... # missing autocompletion
```

adding anything to the new class we're exporting will show up in the auto completed, but nothing from the inherited class.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool? Which version?

Been able to replicate the behavior with neovim (V0.9.4) and pyright on WSL2/Ubunuty20.04, and vsc (1.85.1) with pylance 

Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

![image](https://github.com/microsoft/pyright/assets/26819588/a7052e69-5ac2-4f8d-ba5e-65978c233200) 
^Image only shows overwritten method.

**Comment by erictraut** [comment]
Based on the symptoms you're describing, it sounds very unlikely that it's a bug in pyright. I'm willing to investigate further it if you can narrow down the problem and provide a simpler repro case. Your current repro steps are too vague and complex. If a repro requires a new github repo, please create such a repo and provide step-by-step repro instructions. Better yet is if you can find a repro that doesn't involve so many complex steps.

You can also use the "Go To Definition" command (or whatever it's called in neovim) to determine how pyright is resolving the imports in your code. This may give you a clue as to what's happening here.

**Comment by tagptroll1** [comment]
I appreciate the efforts to look into this! I would also be thankful for any guidance in where to forward this if we can't resolve it here.
Here's a the minimal project structure i was able to set up. I tried doing it by inheriting from list or some other standard lib class, but that seems to work as expected. So i installed `requests` and inherited from Request. (forgot to rename the class from MyList). Now I'm only getting type completion on the custom method, and nothing from the Request object. 

https://github.com/tagptroll1/test-pyright-lib
https://github.com/tagptroll1/pyright-project

pyright-project is running it's own venv with just test-pyright-lib installed with: 
```
pip install "git+ssh://git@github.com/tagptroll1/test-pyright-lib.git#egg=lib"
```
test-pyright-lib is running in a venv, with just requests installed through pip normally `pip install requests`

**Comment by erictraut** [comment]
When I attempt to run the "pip install" command above, it fails with an error: "git@github.com: Permission denied (publickey)." I switched from ssh to https (`pip install "git+https://github.com/tagptroll1/test-pyright-lib.git#egg=lib"`) and it then installed fine.

I was then able to see completions just fine. 

<img width="328" alt="image" src="https://github.com/microsoft/pyright/assets/7040122/5ef7e40f-516d-4bd2-aaf0-93081a944224">

<img width="268" alt="image" src="https://github.com/microsoft/pyright/assets/7040122/85dc5932-b39b-4fe3-a77b-7e20f217800a">

<img width="573" alt="image" src="https://github.com/microsoft/pyright/assets/7040122/34a1b60b-7b58-49d9-9963-26db94e0d594">

I'm using VS Code here. I don't know the first thing about neovim, so if you need help configuring that client, you'll need to look elsewhere for assistance.

I'm going to close this bug since there doesn't appear to be anything wrong with pyright here.

**Comment by tagptroll1** [comment]
My apologies, I had mixed up jedi and pyright as my lsp server when setting up the test. pyright does infact work as expected here. I did modify the lib & project files above to now produce the expected behavior. (I just changed it to the discord.py Bot class to inherit from, that I'm originally failing on)

bot.run() should be available, while only bot.custom is, which i set in the lib project.

Please do give it another try :)
