### ISSUE TITLE
Weird overload transforming behavior for matching from existed overload function type

### ISSUE THREAD

**Issue by GreyElaina** [microsoft/pyright#6822]
**Describe the bug**
unexpected overload expanding or transforming...? [playground](https://pyright-play.net/?code=MQAgpGBQBmBOD2BbEB9F0CuAXDsCmaIAlogA7yxYgCGAdrfFtVkfLQM4wLJYCepRWgHNiZClQCCtXgBoQAFX54AatVhyACmuqIAyqTwBjOQGE2h5nlqXNCLPEPwANqepOn1AEZO8c%2BADc8WCd4agATOXxAtxQ%2BAzkAcSsgokNISHkQAF4FJVVYAAoAInkigEpIACVs3IN84sqiuUd-NSI6LCz5WAw8CpMARhrFOrViwaaQT3gMWjCskzcPbz7IEwAmYbyxoo3J6dn5xfcvH37KoZyRlR2TC8mWto6unt8pmbmFpdPVu82r7aFXaVdYPAJPWidbq9OQHT7HZZndIaGpaWA6fRGYoacqQDSXEBojEGQzYga4yC6AAW1AMW1GQOptLwYNasHakJeMPehy%2BJxWFUgoAgkEMHnY7EJzCwQVoBQ0dgczgA2kyDABdMoALkgID1IAAAqQEAZKLxdfqwnhoCAmLAhHgsAV2HgnNAyiAALQAPhAarwOv1QZAADow%2BlhVAxdQJYT4OwCklaClDKqaRrtRa9QboxLEI6qfAwlmQFabY4xC6CmL2M0kOQXSga1rbUplVosDLYLQ08z1ZrA8G9fgcN2QDWCoKg2XxzG8ANna7oC2NPHlQifuvzJZrDLlfJNOq5FJeP2PT6QBuVu25PJ1YOh2GQyWSzOLC71ou3Su11efFvaAsGVdzwfdD2PaQzy9X0-1AjRXH5f99yPEAT37B9gyfF9p2tWcXQAZi-Zc43YddvmvMxAJ3SwwMJFC0M1aDL3I-94OYxDQOVFC73vEsgyw19cPfPAABYiJ-UjYIAoCrBog86Ig09GIvKS2KcIh2CwZDeKHPUBMjSADVXdgQwrBs8FFcVJX0OgMINAIghCcJBJtO0HSdF03TkEhSB8fNIRbTT1BAVonF6Fs4lAoLlN9SLlWijD%2BPDEt7MCYJQmLHDXLUdyiO8sg-KsLAW0ELA5FC8LWwMZVSpiqrQNqxL9QEoNUscjKXNtHLHTy0RfLwfzioUcq3EquK73PWK2zvJq9PDINOrcnrPOgfL%2BsGlt5IqgN6uQybdpmvj9RHXBaBC0aLKFcAoCiPAYkigobNoCpbvupRHtIOhTLnBcygKdTNPirBYE1D0QFAGMQDwAAPEkZTCFsAAMAa06LEcgV6nFid6nu%2Bj9J3%2BjTUeB0G9VAAB3PAiFgMIQAc9LwmIWhoCCAB%2BDG8GiLGHtx4TCL%2BlGgZBsowYpqmabptKnNpwQWdgdnMexgwPq%2B4SxIFomhdJ8GaElGG4bwBGQGRzXBei9V0fSIA)

> `T` is a normal and simple TypeVar: `T = TypeVar("T")`.

both `case2` & `case3` have `Callable[..., ...]` for the `caseX` return's return, when pass the first parameter type `T` (for `Span`, `implement` param's type), it seems pyright transforms the outer Callable type to a `Overload`.

weird overload transforming behavior, see `case2` & `case3`.

`T` is a normal and simple TypeVar: `T = TypeVar("T")`.

it works as expected for normal type like `list[_T]`, see `case4`.

**Code or Screenshots**
see the playground link.

**VS Code extension or command-line**
`pylance v2023.12.101` & `pyright-play.net`.

**Comment by GreyElaina** [comment]
Take a detour.

```python
class Call(Protocol[P, R]):
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R:
        ...

class Call1(Protocol[R]):
    def __call__(self: Call1[Call[..., T]], x: Callable[[T], Any]):
        ...

class Pos:
    @property
    def case3(self: Pos[Callable[Concatenate[T, P], Any]]) -> Callable[P, Call1[Call[..., T]]]:
        ...
```

**Comment by GreyElaina** [comment]
More interesting things. if `T` is a callable defined for `Span.target(implement=)`, this `T` will be transformed to a `Overload[...]` by pyright.

very, very, interesting.

**Comment by GreyElaina** [comment]
https://github.com/microsoft/pyright/blob/e9e78ce7eafaab29b26cd29967784541ca7a8858/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L26031

this will return `OverloadedFunctionType` for some cases.

**Comment by erictraut** [comment]
I've stared at this code for a long time, and I can't figure out what you're trying to do here.

You're using a class decorator `Pos.compose` which is a class method on a generic class `Pos` which takes a single type argument. Since you haven't provided a type argument, I presume that you are assuming this should be `Pos[Any].compose`? That means the bound type of `Pos.compose` is `compose(compose_cls: type[Pattern[Any]]) -> Pos[Any]`. Is this what you intend?

I've already spent more time than I'd like on this, so I'm going to close it. If you have a simpler version of this code that you think actually demonstrates a bug in pyright, please file a new issue.
