### ISSUE TITLE
Pylance does not recognize 'import cpuinfo'

### ISSUE THREAD

**Issue by ullix** [microsoft/pyright#6823]
It reports: 
"Import "cpuinfo" could not be resolvedPylance(reportMissingImports(https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)"

though Python does import and software runs correctly.

https://pypi.org/project/py-cpuinfo/

**Comment by erictraut** [comment]
I'm not able to repro the problem as reported. Pyright resolves the import fine for me. 

<img width="402" alt="image" src="https://github.com/microsoft/pyright/assets/7040122/cacc9ac3-c5b4-44c4-9b0d-f0e1a40b48c3">

I suspect the Python environment you have selected does not match the one that you've installed the library into. If you want to provide more details, I'm happy to help you diagnose further, but I'm going to close the issue because I don't think this is a pyright bug.

**Comment by ullix** [comment]
Sorry, but it does not work on my system:
![image](https://github.com/microsoft/pyright/assets/9335726/46f8cb8b-a7fe-4804-8dfe-1fb33943ecdf)


Linux Mint 21
Python 3.10.12

Visual Studio Code:
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-91-generic

**Comment by erictraut** [comment]
Which version of pyright are you using?

Are you using a virtual environment? 

How are you specifying the python environment to pyright?

**Comment by ullix** [comment]
What is "pyright"?
Neither vscode nor python were started in a virtual environment.

I just shut down the only running copy of vscode and restarted from a terminal, all outside a venv. Exact same outcome as shown above. As seen in vscode:

![image](https://github.com/microsoft/pyright/assets/9335726/5a68488f-619a-48e8-a7b7-765b42966def)

**Comment by erictraut** [comment]
Pyright is a type checker. You're filing a bug in the pyright issue tracker, so I assumed that you were using pyright.

Pyright also ships with a basic language server that can be used with clients that support the language server protocol, but it looks like you're not using the pyright language server. Instead, you're using pylance.

Pylance is Microsoft's premium Python language server built on top of pyright. It adds many language server features on top of pyright. Pylance is licensed to run only on official builds of VS Code. 

If you need help with pylance, you can file a bug report or submit a question in discussion section of the [pylance-release github site](https://github.com/microsoft/pylance-release).

**Comment by ullix** [comment]
Aha!
It is when I click on reportMissingImports in the error-message-popup (see my pic) it brings me to your site. So I thought ...
Thanks for the Pylance link.
