### ISSUE TITLE
Jupyter notebook magic command

### ISSUE THREAD

**Issue by InSuperposition** [microsoft/pyright#6852]
When using Jupyter "magic" command and declaring a variable `x` in the same cell, all following cells throw a `reportUndefinedVariable` error. The code runs correctly.

<img width="572" alt="Screenshot 2023-12-29 at 7 34 53 PM" src="https://github.com/microsoft/pyright/assets/433871/50c1807f-2dc6-40fb-a928-77e88623fce0">

Pylance extension: v2023.12.1

VS Code:
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z (2 wks ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.2.0

**Comment by erictraut** [comment]
Pyright doesn't include any Jupyter notebook functionality. This is all added by the pylance extension. I think this is a known limitation of pylance currently. You can search the [pylance issue tracker](https://github.com/microsoft/pylance-release) and discussions forum for more details.
