### ISSUE TITLE
Support type narrowing for tagged objects via `in` checks.

### ISSUE THREAD

**Issue by apollo13** [microsoft/pyright#6871]
**Is your feature request related to a problem? Please describe.**

If I define an `Event` like this:
```py
class NewJobEvent(TypedDict):
    tag: Literal["new-job"]
    job_name: str
    config_file_path: str


class CancelJobEvent(TypedDict):
    tag: Literal["cancel-job"]
    job_id: int
 

Event = Union[NewJobEvent, CancelJobEvent]
```
pyright is able to narrow the type if I do:
```py
if event["tag"] == "new-job":
  reveal_type(event) # information: Type of "event" is "NewJobEvent"
```
Now it would be great if it could narrow:
```py
if event["tag"] in {"new-job", "new-job"}:
  reveal_type(event)
```
as well. Currently the revealed type stays `Event`

**Comment by erictraut** [comment]
It's unlikely we'd add support for this. [Type inference for set expressions](https://microsoft.github.io/pyright/#/type-inference?id=set-expressions) doesn't retain literal types. That means the type of the expression `{"new-job", "new-job"}` is `set[str]`.

**Comment by apollo13** [comment]
Stupid question, but what about `("new-job", "new-job")` then. As far as I can see a tuple retains the types -- ie:
```py
from typing import reveal_type, TypedDict, Union, Literal

class Test1(TypedDict):
    tag : Literal['a']

class Test2(TypedDict):
    tag : Literal['b']

Test = Union[Test1, Test2]


a = ('a', 'b')
b = {'a', 'b'}
reveal_type(a)
reveal_type(b)


def x(c: Test):
    if c["tag"] in ('a', ):
        reveal_type(c) # would it make sense to narrow to Test1 here?
```

**Comment by erictraut** [comment]
> As far as I can see a tuple retains the types

Yes, it's more likely that we might add support for a pattern involving tuples. However, this doesn't strike me as a common enough pattern to justify the additional complexity and analysis performance costs. Each new narrowing pattern is relatively expensive to implement, maintain, and execute.

I would be willing to reconsider if we receive strong signal from pyright users (e.g. in the form of upvotes of this or a similar issue).

In the meantime, you can modify your code to use the currently-supported built-in type guard patterns or implement a user-defined TypeGuard function.

**Comment by apollo13** [comment]
Thanks, makes sense! For everyone else who is new to typing, user-defined TypeGuards are specified here https://peps.python.org/pep-0647/

**Comment by insilications** [comment]
> > As far as I can see a tuple retains the types
> 
> Yes, it's more likely that we might add support for a pattern involving tuples. However, this doesn't strike me as a common enough pattern to justify the additional complexity and analysis performance costs. Each new narrowing pattern is relatively expensive to implement, maintain, and execute.
> 
> I would be willing to reconsider if we receive strong signal from pyright users (e.g. in the form of upvotes of this or a similar issue).
> 
> In the meantime, you can modify your code to use the currently-supported built-in type guard patterns or implement a user-defined TypeGuard function.

I fully agree that it adds more complexity to implement and maintain. But maybe people will start to use this pattern more and more. I have discovered this rule in Pylint recently:

```
Derived from the Pylint linter.

Fix is always available.

What it does
Checks for repeated equality comparisons that can rewritten as a membership test.

Why is this bad?
To check if a variable is equal to one of many values, it is common to write a series of equality comparisons (e.g., foo == "bar" or foo == "baz").

Instead, prefer to combine the values into a collection and use the in operator to check for membership, which is more performant and succinct. If the items are hashable, use a set for efficiency; otherwise, use a tuple.

Example

foo == "bar" or foo == "baz" or foo == "qux"
Use instead:

foo in {"bar", "baz", "qux"}
```
https://docs.astral.sh/ruff/rules/repeated-equality-comparison/


I was curious. It is only more performant if you need multiple comparisons. The if pattern, even with many comparisons, is already very optimized.
