### ISSUE TITLE
"MultiDict" is not defined

### ISSUE THREAD

**Issue by Tybion** [microsoft/pyright#6885]
VSCode reports "MultiDict" is not defined and gives a link to this github repo.

Code ..
```
def reset(self):
        blankData = MultiDict([('csrf', self.reset_csrf())])
        self.process(blankData)
```

The code runs fine on Ubuntu 22.04 in a flask app.

VSCode is running on a M1 Macbook Air with Sonoma 14.1.2 

Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

**Comment by erictraut** [comment]
`MultiDict` is not a builtin symbol, so you need to import it from somewhere. If it appears to be a builtin symbol in your distro, then you're using a non-standard distro.

In any case, this isn't a bug in pyright, so closing.
