### ISSUE TITLE
Narrowing on Generics

### ISSUE THREAD

**Issue by max-muoto** [microsoft/pyright#6886]
In some cases, you might end up narrowing a generic type with `issubclass`.

```python
class Base:
    ...


class BaseA(Base):
    field_1: str


def update_objects[T: Base](
    type: type[T],
    objs: Iterable[T],
) -> None:
    if issubclass(type, BaseA):
        for obj in objs:
            obj.field_1 = "test" # Cannot assign member "field_1" for type "Base*"
```

In this case, it would useful if the `objs` were narrowed in this block. In this example, if Pyright narrowed `objs` as `Iterable[BaseA]`.

The same goes if we were using `isinstance`.

```python
class Base:
    ...

class BaseA(Base):
    field_1: str


def update_objects[T: Base](
    obj: T,
    objs: Iterable[T],
) -> None:
    if isinstance(obj, BaseA):
        for obj in objs:
            obj.field_1 = "test" # Cannot assign member "field_1" for type "Base*"
```

I'm curious if this is something that would make sene in Pyright, or something that was already considered and discarded.

**Comment by max-muoto** [comment]
The closet thing to a workaround I find here was a `TypeGuard` with an unused argument.

**Comment by erictraut** [comment]
This form of narrowing wouldn't be safe. The type of `type` and `objs` are not necessarily the same. 

Consider the following:

```python
from typing import Iterable

class Base:
    ...

class BaseA(Base):
    field_1: str

class BaseB(Base):
    pass

def update_objects[T: Base](_type: type[T], objs: Iterable[T]) -> None:
    if issubclass(_type, BaseA):
        for obj in objs:
            obj.field_1 = "test"

update_objects(BaseB, [BaseA()])
```

You may want to change your code to the following, which is type safe.

```python
from typing import Iterable

class Base:
    ...

class BaseA(Base):
    field_1: str

class BaseB(Base):
    pass

def update_objects[T: Base](objs: Iterable[T]) -> None:
    for obj in objs:
        if isinstance(obj, BaseA):
            obj.field_1 = "test"

update_objects([BaseA(), BaseB()])
```

**Comment by max-muoto** [comment]
> This form of narrowing wouldn't be safe. The type of `type` and `objs` are not necessarily the same.
> 
> Consider the following:
> 
> ```python
> from typing import Iterable
> 
> class Base:
>     ...
> 
> class BaseA(Base):
>     field_1: str
> 
> class BaseB(Base):
>     pass
> 
> def update_objects[T: Base](_type: type[T], objs: Iterable[T]) -> None:
>     if issubclass(_type, BaseA):
>         for obj in objs:
>             obj.field_1 = "test"
> 
> update_objects(BaseB, [BaseA()])
> ```
> 
> You may want to change your code to the following, which is type safe.
> 
> ```python
> from typing import Iterable
> 
> class Base:
>     ...
> 
> class BaseA(Base):
>     field_1: str
> 
> class BaseB(Base):
>     pass
> 
> def update_objects[T: Base](objs: Iterable[T]) -> None:
>     for obj in objs:
>         if isinstance(obj, BaseA):
>             obj.field_1 = "test"
> 
> update_objects([BaseA(), BaseB()])
> ```

Makes sense. I think my understanding of different types being allowed for the same generic param was flawed.

Thanks!
