### ISSUE TITLE
Slow performance on regular expression

### ISSUE THREAD

**Issue by KaustubhPatange** [microsoft/pyright#6890]
When running pyright on this specific file https://github.com/bmaltais/kohya_ss/blob/master/sdxl_gen_img.py from the repo, it takes about 10 mins to completely analyze the file.

<img width="562" alt="Screenshot 2024-01-03 at 11 54 32 PM" src="https://github.com/microsoft/pyright/assets/22119598/98586050-2ba9-44ce-b3f1-0dff8666a4cb">

...

After commenting lines from [2314 - 2449](https://github.com/bmaltais/kohya_ss/blob/master/sdxl_gen_img.py#L2314-L2448), it takes 6 seconds. The marked lines are python's regular expression matching operations.

<img width="527" alt="Screenshot 2024-01-03 at 11 40 35 PM" src="https://github.com/microsoft/pyright/assets/22119598/4c6e758c-58ac-48ee-bccc-a3d1bbc748d7">

...

I'm using `pyright` with `time` command to measure total command execution time, 
```
time python sdxl_gen_img.py
```

To reproduce, clone the [repo](https://github.com/bmaltais/kohya_ss), create a virtual env with python 3.9, and install dependencies from `requirements.txt` omitting `onnxruntime-gpu`.

___
**pyright version**: 1.1.344
**python version**: 3.9
**machine**: mac m2 pro

**Comment by erictraut** [comment]
Thanks for the bug report. The code in question involves a very complex code flow graph (nested loops, try statements, and many conditional statements). Pyright has a cutoff point for code complexity (as measured by cyclomatic complexity) beyond which it will refuse to analyze a function. Your function doesn't quite reach the cutoff point, but it's relatively close.

I found a few optimizations that got the analysis time from several minutes to about 3.6sec on my machine. That's still really slow for type analysis of a single source file, but I'm not sure I can do much better given the complexity of the function. You could reduce this significantly if you refactored your code into subroutines.

The optimizations I added will be in the next release of pyright.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.345, which I just published. It will also be included in a future release of pylance.
