### ISSUE TITLE
Pydantic models are ignoring hasattr checks for pyright

### ISSUE THREAD

**Issue by SebastianMorawiec** [microsoft/pyright#6897]
(Edited out as it turned out I put some wrong conclusions. Simpler snipped provided)

Given following code:

```python
import typing as T

class A:
    def __init__(self):
        self.a = 1

class B:
    ...

MY_TYPE = T.Union[A, B]

class D:
    def __init__(self):
        self.a: MY_TYPE = A()

d = D()

x: MY_TYPE = A()

if hasattr(d.a, "a"):
    print(f"{d.a.a}")


```

pyright reports issue on the print() statement as type B does not have "a" attribute.

If object is not part of other instance, hasattr seems to be working correctly

Observed using pyright 1.1.344 (installed as python package)

**Comment by erictraut** [comment]
Pyright is working as designed here, so I don't consider this a bug. It's a potential enhancement request, but it's one that we'd be unlikely to add.

A `hasattr` call is not a supported type narrowing pattern. For a full list of supported type guards, see [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards).

Each new type guard pattern is very specific to the use case and requires custom logic that is difficult to implement and maintain and potentially slows down analysis. We do occasionally add support for a new type guard, but only if we receive strong signal from pyright users that it's a common-enough pattern.

The more typical way of performing the test in your sample code is:

```python
if isinstance(d.a, A):
    print(f"{d.a.a}")
```

This is a supported type guard pattern, and it narrows the type as expected.

An an alternative workaround, you can write a user-defined type guard function using the `TypeGuard` mechanism introduced in PEP 647.
