### ISSUE TITLE
"remove" is not a known member of modulePyright (reportGeneralTypeIssues)

### ISSUE THREAD

**Issue by Haibao425** [microsoft/pyright#690]
VSCode: all versions.
 "remove", "listdir"..... all of the functions from os library are not recognized by Pyright.

**Comment by erictraut** [comment]
The following code produces no errors for me.
```
import os
os.listdir()
os.remove('path')
```

Could you please provide a more complete code sample?

**Comment by erictraut** [comment]
I'm closing the bug for lack of a repro case. If you are able to provide more information, I'm happy to re-open it.
