### ISSUE TITLE
dataclass_transform: allow `field_specifiers` to be arbitrary (statically-checkable) types, not just 

### ISSUE THREAD

**Issue by tbrugere** [microsoft/pyright#6923]
Hello! 
Not sure if this is the right place, but I would like to make a feature suggestion for `dataclass_transform`

**Is your feature request related to a problem? Please describe.**
I have this code with a dataclass-like class where fields are defined by a type annotation. Here is a minimal example of what it looks like in practice:

Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgGoCGIANISQIIA2S5AzjXSimDOTMQCY00xGAH14CYqIAWqGGyj9e5AMYNWLcSHIoWwXBHYo4NAGKpyDAFBWCUALy1JFEAAoARAXcBKKwEkAZVFTPwBRABkAEQAuKHMUSwBtFhgQAF0HKHdgJGIGfncrczz%2BaKJJRmYWTI4uHj5%2BRIIaQOCwqLSbAAElHjUNLR09A1cAawB3UTAUBjhRfmJgcgBXBhh7AhBl4hocktEWSRUkPZAWe1di-MSOODSqb19%2BlmqAWTAFhldvaJsof8UiygolEqCQYlErhYeWANAAVHCJpQ0CwflYARioPoQFjcvkaPhUFBhGIJFJZCh5FCYd4AHTg4gQFjfX6YtmYYBQVohCKRTAoWC0kEQETkXrkEGs9nSk64kr8qBIkAoqXStVQaH1VLUhiwuX4xXjZEsRLZPEFNK%2BdVsvKy6SsXja6G63bmn5QADElhAxDFcCg9uq5EBS1W%2BAAbpZtujrdKEBoY7H-nloaqkxjtEhoVAKAxtqEQOA3MB3BAsyxUBhkcsRZSoABvPb5AC%2BPj%2B7OdwCFohwKVBKHBIO%2B7f%2BC05IN7YjBEJ1wDRcYTNme1QACsQztN3p9XFu8mjE1AEiLYldGil0gfyMIT%2BbEnIMo4AMwANhH-L4IASDFEkZAzAARgwxCxMADBgLwb5jsCPZgH205Dp284djC9KUuuX4-pQAFAZkj5QHCGooVexA2GuG4oLuXxHsQ9juAAUmA0goO4NDEfYACsAAsvhAA)

```python
from typing import TypeVar, TypeAlias, Annotated, get_type_hints, dataclass_transform, Any, Final

T = TypeVar("T")
IS_FIELD: Final[str] = "field"
Field:TypeAlias = Annotated[T, IS_FIELD]

@dataclass_transform(kw_only_default=True, field_specifiers=(Field[Any],))
class Model():

    def __init__(self, **kwargs):
        for field, t in get_type_hints(self).items():
            if IS_FIELD in t.__metadata__:
                if field in kwargs:
                    setattr(self, field, kwargs["field"])
                elif hasattr(self, field): #already has a default value
                    pass
                else:
                    raise ValueError(f"missing argument {field}")

        self.__post_init__()

    def __post_init__(self):
        pass


class PersonModel(Model):

    name: Field[str]
    age: Field[int] = 36

    internal_variable: float

    def __post_init__(self):
        self.internal_variable = 3 * self.age

PersonModel(name="John", age=54)

```

Before `@dataclass_transform`, this allowed to statically check attribute access to `PersonModel` (but not calls to `__init__`). 

With `@dataclass_transform` we could typecheck calls to `__init__` too, except the current `dataclass_transform` specification does not allow for `field_specifiers` to be arbitrary type expressions (they have to be either classes or functions).

So Pyright raises an error on the `dataclass_transform` call and on the construction (it complains that `internal_variable` argument is missing).

**Describe the solution you’d like**
It would be great if the `field_specifiers` argument of `dataclass_transform` accepted not only classes (or functions) but arbitrary (checkable) type expressions). 
Or if this is not possible, if it could at least work in this use-case with annotations.

Best!

**Comment by erictraut** [comment]
Thanks for posting, but this isn't the right place for such a feature suggestion. The `dataclass_transform` mechanism is part of the official [typing specification](https://typing.readthedocs.io/en/latest/spec/dataclasses.html#the-dataclass-transform-decorator). Changes to it would require changes to the spec. 

Are you able to change your code to use the standard mechanism as it's currently spec'ed? If that's possible, I recommend going that route. It may be a tough sell to convince the community that `dataclass_transform` should be augmented to support your non-standard usage.

If you'd like to make your case, you could post to the [python typing forum](https://discuss.python.org/c/typing/32).

**Comment by tbrugere** [comment]
Alright,
Thank you for taking the time to write an answer
