### ISSUE TITLE
Suppress diagnostic by pattern

### ISSUE THREAD

**Issue by eyalk11** [microsoft/pyright#6937]
I have a class that is written badly in which I add attributes on the run (from outside).
I want to supress all warning related to this class (a lot) . For this I need to have a pattern (wildcard) or regex to supress warnings. 
Instead of doing `reportGeneralTypeIssues=false`

**Comment by erictraut** [comment]
It's unlikely we'd add a feature like this.

**Comment by erictraut** [comment]
I am considering breaking up `reportGeneralTypeIssues` into more granular errors. That might help you out.

If you would like suggestions for how to fix your class to avoid the need to suppress errors, feel free to post to the pyright discussion forum.
