### ISSUE TITLE
Missing reportUninitializedInstanceVariable error when pure class variable is not initialized

### ISSUE THREAD

**Issue by michelbl** [microsoft/pyright#6938]
NB: I'm not sure if it's a bug or an enhancement request, please change the label if appropriate.

**Describe the bug**

When I define a pure class variable and I forget to declare its value, I get no error report.

**Code or Screenshots**

```python
from typing import ClassVar


class MyClass:
    pure_class_var: ClassVar[str] # I don't yet declare its value but it's okay, I may want to declare the value in subclasses


p = MyClass()

print(p.pure_class_var)  # I would expect a type error here
```

At runtime, it crashed with `AttributeError: 'MyClass' object has no attribute 'pure_class_var'`

**VS Code extension or command-line**

pyright CLI 1.1.345

**Comment by michelbl** [comment]
Thank you for you quick and thorough answer!

> This option is almost never used because it requires a very particular (non-standard) coding form that most Python users don't like. Your request feels similar. Maybe it would make sense to lump this check in with the `reportUninitializedInstanceVariable` check?

I didn't know that `reportUninitializedInstanceVariable` was so uncommon! But I guess that most people that turn this option on would also like to turn on this check. So it would make sense to me to "lump in it" as you suggest.

> And I'm generally reluctant to add new checks that can't be enabled in strict mode because they're almost never discovered or used.

I guess that the kind of people I mention before take a few minutes to discover what's available on the shelf here: https://github.com/microsoft/pyright/blob/main/docs/configuration.md

Anyways, I agree that this feature is of little interest if it only serves a tiny proportion of the user community, so decide what you think best serves the community.

**Comment by erictraut** [comment]
I'm going to decline this enhancement request for now. I might reconsider in the future if there's a signal from more pyright users that it's a desired feature. If you're interested in seeing this feature, please upvote (thumbs up) this issue.

In the meantime, I'm going to close the issue because I have no plans to implement it at this time.
