### ISSUE TITLE
pyproject.toml support

### ISSUE THREAD

**Issue by nihaals** [microsoft/pyright#694]
**Is your feature request related to a problem? Please describe.**
A lot of popular Python tools now support configuration from `pyproject.toml` which allows all your configuration to be in one file (and TOML's quite nice)

**Describe the solution you'd like**
If there is a `pyproject.toml` file with a table for something like `tool.pyright`, use that and don't look for `pyrightconfig.json`.

**Comment by erictraut** [comment]
Thanks for the suggestion, but Pyright already has multiple configuration mechanisms including pyrightconfig.json, command-line, and VS Code settings. I don't plan on adding yet another.

**Comment by nihaals** [comment]
I think the main difference is the fact that pyproject's role is to completely replace every other system so that there isn't "just another system" and is now recommended for *every* Python package, so everything will already have it (it is also meant to be used for dependency tracking for example Poetry).

**Comment by notpushkin** [comment]
@erictraut I understand your decision and if you really don't want this in your project, that's fine, but pyproject.toml is far beyond just “another config file” – most of the Python tooling ecosystem now supports it, so it's really a central place, like how many tools in JS ecosystem support both own config files and package.json. 

If you don't want to implement it yourself, but aren't otherwise against the idea, perhaps I could put up a PR for you?

**Comment by erictraut** [comment]
As I said, I'm not interested in supporting another configuration mechanism. Pyright already supports multiple config mechanisms, and the code involved is already very complicated because it needs to deal with precedence between these different mechanisms. Adding yet another will make the code more difficult to maintain.

**Comment by WhyNotHugo** [comment]
Maybe this could replace `pyrightconfig.json`?

The standard in the python community is to just have `pyproject.toml` and all project settings there (e.g.: flake, pip and black are doing the same).

Given that the target of pyright is that exact same community, it makes sense to align, right?

**Comment by pikeas** [comment]
Strong agree with the other responses, `pyproject.toml` is the new standard and it would be nice if Pyright supported it!

**Comment by macintacos** [comment]
I feel like enough time has passed that I'd like to bump this again. `pyproject.toml` has been a life saver compared to other configuration management options in Python projects, and at this point a tool that doesn't support it makes me seriously consider just not using it and looking for alternatives. Pyright's awesome enough that I really would prefer to not do that :)

**Comment by erictraut** [comment]
I guess I don't have a good appreciation for what problem would be solved by supporting `pyproject.toml`. Can you help me understand what pain point results from storing pyright's configuration settings in a `pyrightconfig.json` file? Or put another way, what problem is solved by moving this to `pyproject.toml`?

I can think of a bunch of downsides of merging configuration information for every development tool into a single configuration file, but I'm not seeing much of an upside.

You said that `pyproject.toml` "has been a lifesaver", which is a pretty strong statement. That implies that there must be some big problem that I'm not seeing. Please help me understand.

Just so you can understand my perspective...

Currently, pyright allows users to configure settings in four ways:
1. Through command-line options
2. Through LSP client settings (including user-specific, project-specific and workspace-specific overrides)
3. A dedicated pyrightconfig.json configuration file
4. File-specific overrides in the form of # pyright comments

Combining all of these configuration settings with the proper override precedence and handling dynamic updates to all of them at runtime is incredibly complicated already. Just documenting all of these configuration mechanisms is a big challenge. So from my perspective, the last thing pyright needs is yet another place to store configuration settings. Supporting a fifth location would require us to define additional precedence rules, track changes to yet another file to respond to live updates, handle and report error cases with parsing that file, document the pyright config schema in that new format, etc.

**Comment by WhyNotHugo** [comment]
> I can think of a bunch of downsides of merging configuration information for every development tool into a single configuration file, but I'm not seeing much of an upside.

pyright is pretty much a snowflake, and it's very annoying to see a single application behave so differently. I can copy all linting settings from one project to another by just copying one file -- except pyright, which for some reason needs to behave entirely different from the rest of the ecosystem.

**Comment by mikeloomisgg** [comment]
> Can you help me understand what pain point results from storing pyright's configuration settings in a pyrightconfig.json file?

One goes to create a modern python project, follows best practices according to the most recent standards. They create a pyproject.toml. They are told by the language documentation itself that all of the tools related to running, building, packaging, testing, linting, and formatting should be using the pyproject.toml file. https://www.python.org/dev/peps/pep-0518/#tool-table

The problem this solves for me is that I can point anyone to the project file of a python project and it will tell them everything there is to know about all of the tools being used alongside the project. Except for Pyright. As the person above pointed out, going forward - Pyright is the one tool in the ecosystem that demands its own special configuration file. I'll admit, supporting a pyproject.toml instead of or in addition to the pyrightconfig.json appears to me as an outsider as something that would be incredibly easy.

Can you help me to understand why you think it might be better for every tool to have its own unique configuration file, in defiance of the language features?

**Comment by erictraut** [comment]
@WhyNotHugo and @mikeloomisgg, thanks for sharing your perspectives. I appreciate your input.

Here are some arguments in favor of separate configuration files.

1. Different tools intersect different user groups and use cases. For this reason, I wouldn't expect all tools that I happen to use in my project to store all their settings in the same format and the same file. For example, some Python projects are stored in a git repo and others are not. I wouldn't expect the git tool to store its settings in the same location as all the other tools I use in my project. I don't find it odd that I need to edit a separate ".gitignore" configuration file.
2. Storing and maintaining settings in multiple files doesn't seem at all onerous to me, but based on the feedback in this thread, there are many who disagree with this viewpoint.
3. When pyright is used for interactive editing or in "watch" mode, it monitors files on disk including the pyrightconfig.json file. Any change to this configuration file triggers a complete reanalysis of the entire project using the newly updated settings. If all project settings for all tools are stored in a single file, any change to this file will cause unnecessary reanalysis to be performed.
4. Pyright ships with a JSON schema that describes its configuration format. A smart editor (such as VS Code) is able to use this schema to validate the configuration file contents and provide completion suggestions and interactive help during editing. This largely eliminates the need to consult documentation when updating your configuration. It also eliminates a large class of configuration errors. To my knowledge, no similar schema validation is provided for pyproject.toml files, especially for tool-specific sections.

If you do not use an editor that understands JSON schemas or you use pyright in a non-interactive manner, then I can understand why #3 and #4 might not be important to you.

Based on the large number of responses to this issue, it's clear that there are many pyright users who feel strongly about pyproject.toml support. I'll discuss the topic with my colleagues and respond back to this thread with an update.

**Comment by erictraut** [comment]
After some internal discussion, we decided to add support for pyproject.toml. This support comes with a few caveats and limitations:

* If pyrightconfig.json and pyproject.toml are both present, the pyrightconfig.json file always takes precedence. There is no attempt to merge settings between the two.
* As I mentioned above, there is no schema available for toml-based settings, so some classes of configuration errors will go unreported and undetected.
* If you configure pyright to automatically analyze all files within the project, it will automatically start this analysis as soon as you open the project in VS Code and a "pyrightconfig.json" file is present. If your settings are within "pyproject.toml", you will need to first open a python (".py" or ".pyi") file to trigger VS Code to load the pyright language server and start the analysis.

Support for pyproject.toml will be included in the next release of pyright. This support will also be inherited by pylance.

**Comment by erictraut** [comment]
This is included in pyright 1.1.133, which I just published. It will also be in the next release of pylance.

**Comment by abceleung** [comment]
I am using both Pylance (with type checking set to basic) and Poetry in VSCode.
The Python Language Server says my Pyproject file is missing "[tool.pyright] section.
How do I configure it?

**Comment by erictraut** [comment]
Please refer to the documentation [here](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-pyprojecttoml-file).
