### ISSUE TITLE
import request issue any solutions

### ISSUE THREAD

**Issue by saiteja25755** [microsoft/pyright#6962]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem.

**Describe the solution you’d like**
A clear and concise description of the solution you would like to 
i have created a code but after running it it is showing that modulenotfounderror the import requests are not found

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by erictraut** [comment]
Since there are no details here, I assume this was opened in error. Closing.
