### ISSUE TITLE
False positive "calling abstract method"

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#6965]
```python
from contextlib import AbstractContextManager
from time import perf_counter_ns
from types import TracebackType

from typing_extensions import Self, override

class Timer(AbstractContextManager['Timer']):
    def __init__(self) -> None:
        super().__init__()
        self.start = 0
        self.end = 0

    @override
    def __enter__(self) -> Self:
        super().__enter__()
        self.start = perf_counter_ns()
        return self

    @override
    def __exit__(self,
                 exc_type: None | type[BaseException],
                 exc_val: None | BaseException,
                 exc_tb: None | TracebackType,
                 /) -> None:
        super().__exit__(exc_type, exc_val, exc_tb)
        self.end = perf_counter_ns()

    def elapsed(self) -> float:
        return self.elapsed_ns() / 1e9

    def elapsed_ns(self) -> int:
        return self.end - self.start


with Timer():
    pass
```
Gives:
```
  /Users/neil/src/cmm/a.py:28:9 - error: Method "__exit__" cannot be called because it is abstract and unimplemented (reportGeneralTypeIssues)
```

While `AbstractContextManager.__exit__` is abstract, it is also implemented.  This is a peculiarity of Python (I would have preferred for this method not to be abstract).  In my opinion, this should not be a PyRight error.  What do you think?

**Comment by erictraut** [comment]
Pyright is behaving correctly in this case. If this is a bug, it's a bug in typeshed, which defines `AbstractContextManager.__exit__` as an `@abstractmethod`. If this method is actually implemented in the base class, it shouldn't be defined as abstract.

**Comment by NeilGirdhar** [comment]
I'm alright with that, but FYI the method is decorated with `@abstractmethod` in the runtime despite being implemented.

**Comment by NeilGirdhar** [comment]
https://discuss.python.org/t/can-we-make-abstractcontextmanager-exit-concrete/43025

**Comment by NeilGirdhar** [comment]
It appears that 

> Pyright is behaving correctly in this case. If this is a bug, it's a bug in typeshed, which defines `AbstractContextManager.__exit__` as an `@abstractmethod`. If this method is actually implemented in the base class, it shouldn't be defined as abstract.

While I agree that that would be sensible, it appears that that disagrees with [the specification](https://docs.python.org/3/library/abc.html?highlight=abstractmethod#abc.abstractmethod) of `abstractmethod`: 
> Note: Unlike Java abstract methods, these abstract methods may have an implementation. This implementation can be called via the [super()](https://docs.python.org/3/library/functions.html#super) mechanism from the class that overrides it. This could be useful as an end-point for a super-call in a framework that uses cooperative multiple-inheritance.

Therefore, from [the discussion](https://discuss.python.org/t/can-we-make-abstractcontextmanager-exit-concrete/43025/4), it appears that this is a bug with PyRight not discovering that the method does have an implementation, and should be fine to call?

If you don't agree, would you mind commenting on the linked thread so that we can come to some agreement of where the change should be made?  I'm happy to submit a PR for the typeshed if you think that's a better solution, but there doesn't seem to be agreement.

**Comment by erictraut** [comment]
> While I agree that that would be sensible, it appears that that disagrees with [the specification](https://docs.python.org/3/library/abc.html?highlight=abstractmethod#abc.abstractmethod) of abstractmethod.

If `AbstractContextManager` were defined as an `ABC`, then your assertion would be correct. However, it's defined as a runtime-checkable `Protocol`. When a class explicitly derives from a protocol (as `Timer` does in your example), it must implement all unimplemented methods in the protocol, and it is not allowed to call (via `super()`) any methods that are unimplemented in the protocol. It would be unsafe to allow this.

For a protocol class defined in a source (".py") file, a type checker can distinguish between an "implemented method" and an "unimplemented method" by looking at the body of the method. For example, if the body is `...` or `raise NotImplementedError()`, it is considered unimplemented. However, in a type stub file, all method bodies are `...`. That means there must be some other way to distinguish between an implemented and an unimplemented method in a protocol class defined in a stub file. The way this is done is through the use of an `@abstractmethod` decorator.

In this particular example, `AbstractContextManager` is defined as follows within `contextlib.pyi`:

```python
@runtime_checkable
class AbstractContextManager(Protocol[_T_co]):
    def __enter__(self) -> _T_co: ...
    @abstractmethod
    def __exit__(
        self, __exc_type: type[BaseException] | None, __exc_value: BaseException | None, __traceback: TracebackType | None
    ) -> bool | None: ...
```

This means the `__enter__` method should be considered "implemented" in the protocol, and the `__exit__` method should be considered unimplemented (and therefore unsafe to call).

If the `__exit__` method is actually implemented in the runtime `AbstractContextManager`, then the typeshed stubs should not mark it as an `@abstractmethod`.

I think mypy should also emit an error in this case.

**Comment by NeilGirdhar** [comment]
Thank you for taking the time to provide such a clear explanation.  I will simply propose changing this class to an ordinary ABC in the typeshed to match the runtime.

**Comment by ariofrio** [comment]
**Update:** After investigating this, I see that this is happening on Pyright 1.1.331, the version of Pyright bundled with the last Pylance version that still runs on Visual Studio Code forks. The latest Pyright version 1.1.376 does not have this problem. I'll ignore the type error for now, migrate to a different extension, and upgrade Pyright when I have time. I'm leaving this here in case anyone else has a similar problem.

> If AbstractContextManager were defined as an ABC, then your assertion would be correct.

Is calling an abstract method from an override actually supported by pyright? I'm getting the following type checking error:

```
Method "my_method" cannot be called because it is abstract [reportGeneralTypeIssues]
```

For the following code:

```
class Base(ABC):
  @abstractmethod
  def my_method(self):
    return "Something basic"

class Specialized(Base):
  @override
  def my_method(self):
    return super().my_method() + ", and then more"
```

Which according to the documentation for `ABC` and [`abstractmethod`](https://docs.python.org/3/library/abc.html#abc.abstractmethod) should be allowed:

> Note: Unlike Java abstract methods, these abstract methods may have an implementation. This implementation can be called via the [super()](https://docs.python.org/3/library/functions.html#super) mechanism from the class that overrides it. This could be useful as an end-point for a super-call in a framework that uses cooperative multiple-inheritance.

Furthermore, since the error is categorized as `reportGeneralTypeIssues`, there's no way to ignore only this type-checking error either in the configuration file or in the line itself, without risking ignoring other type-checking errors around it. For example:

```
return (
  super().my_method() # type: ignore
) + 234
```

Seems to let the mistake through (or at least something similar I did with lists did).
