### ISSUE TITLE
Attributes defined in a mixin class are misidentified as missing if `self` is annotated as a protocol.

### ISSUE THREAD

**Issue by mikenerone** [microsoft/pyright#6966]
pyright 1.1.345 CLI

Attributes defined in a mixin class are misidentified as missing if `self` is annotated as a protocol.

```python
class NumGetter(Protocol):
    def get_num(self) -> int:
        return 3

class GetDoubledMixin:
    def get_doubled_num(self: NumGetter) -> int:
        return self._double(self.get_num())  # <--------- error: Cannot access member "_double" for type "NumGetter"

    def _double(self: NumGetter, num: int) -> int:
        return 2 * num
```
There are few more knock-on errors that result from that one, as well.

Note that removing the `self` annotations (correctly) results in `error: Cannot access member "get_num" for type "GetDoubledMixin*"`. This is a "pick your failure" situation.

**Comment by erictraut** [comment]
Pyright is doing the right thing here, so this isn't a bug.

The typical way to define a mix-in class like this is to derive explicitly from the protocol class, like this:

```python
class GetDoubledMixin(NumGetter):
    def get_doubled_num(self) -> int:
        return self._double(self.get_num())

    def _double(self: NumGetter, num: int) -> int:
        return 2 * num
```
