### ISSUE TITLE
Can't recognize the parameters passed in by the decorator.

### ISSUE THREAD

**Issue by Fjyyyyy** [microsoft/pyright#6998]
I am using neovim, pyright version: 1.1.345 

![image](https://github.com/microsoft/pyright/assets/31431332/1f4a441c-76ce-4ed1-a25a-e5f6685b94f2)

This code works fine but pyright gives me a argument missing error.

**Comment by erictraut** [comment]
Could you please provide a self-contained, minimal code sample in text form?

**Comment by erictraut** [comment]
Pyright is working as intended. You haven't provided any annotations for your decorator, so pyright makes the assumption that it doesn't change the signature of the decorated function. Mypy makes the same assumption. 

If your decorator transforms the signature of the functions it decorates, then you need to annotate it accordingly.

Here's an example:

```python
from typing import Callable, Concatenate, ParamSpec, TypeVar

P = ParamSpec("P")
R = TypeVar("R")

def deco(func: Callable[Concatenate[int, P], R]):
    def wrapper(*args: P.args, **kwargs: P.kwargs):
        return func(1, *args, **kwargs)

    return wrapper
```
