### ISSUE TITLE
Unclear how the VS Code extension works

### ISSUE THREAD

**Issue by narfanar** [Microsoft/pyright#7]
It adds no new configuration or commands to VS Code, and reports no errors in the Problems panel.

Running on the latest Insiders.

**Comment by erictraut** [comment]
The VS Code extension won't be started until you open a ".py" or ".pyi" file.

**Comment by narfanar** [comment]
I do have some open.

Actually, there're a couple of new things. Just to make sure: this extension doesn't include a "name" on its messages, does it? As in, this could be an error from it:

![image](https://user-images.githubusercontent.com/5769148/54877527-8e071d00-4e28-11e9-92bb-d140a36fa842.png)

I was expecting something like this:

![image](https://user-images.githubusercontent.com/5769148/54877534-a37c4700-4e28-11e9-8c44-f9fc67dcba5b.png)

Note the "name" `pylint(blah)` before the `[line, column]`. Otherwise, I mistook it for something native to the VSCode Python extension.

**Comment by erictraut** [comment]
Ah yes, I'm not filling in that string currently. I'll fix it.
