### ISSUE TITLE
Suppress more errors for unbound classes

### ISSUE THREAD

**Issue by QUANZHOU1990** [microsoft/pyright#700]
**Is your feature request related to a problem? Please describe.**
Now we have to generate typestub files for external libraries. Otherwise, pyright would raise errors when we want to use a member of external classes. I do not like this behavior since it brings more work to developers. Whether a used member of external classes exists or not can be handled by unit tests. 

**Describe the solution you'd like**
Could we have a configuration parameter to suppress the errors mentioned above? 

**Additional context**

**Comment by erictraut** [comment]
Thanks for the suggestion.

A few follow-up questions for you:
1. Do you have the "Use Library Code For Types" (pyright.useLibraryCodeForTypes) setting enabled?
2. Do you use "strict" mode or default type checking mode?
3. Could you provide a specific code snippet and a list of the specific diagnostic rules that you think are too noisy?

**Comment by QUANZHOU1990** [comment]
Hi Eric, 
thanks for the quick response!
Regarding the followup questions: 
1. No. I do not see a documentation for useLibraryCodeForTypes. Is it a configuration parameter? If yes, it is not in the configuration README. 
2. default, which i think is basic based on the Configuration README. 
3. The diagnostic information is 
 ```
18:13 - error: "config" is not a known member of module (reportGeneralTypeIssues)
  24:18 - error: Cannot access member "default_app" for type "Unbound"
  Unsupported type "Unbound" (reportGeneralTypeIssues)
```
The corresponding code is 
```
18:13 logging.config.dictConfig(_config.logging)
24:18 app = bottle.default_app()
```
logging and bottle is just the built-in logging and standard bottle `pip install bottle`.

**Comment by erictraut** [comment]
"pyright.useLibraryCodeForTypes" is a VS Code setting and is documented [here](https://github.com/microsoft/pyright/blob/master/docs/settings.md). Are you using the VS Code extension, or are you using the command-line version of Pyright?

**Comment by QUANZHOU1990** [comment]
Ah, that is why. No, I am using command-line. I want to make it part of the CICD.

**Comment by erictraut** [comment]
For the command-line, this option is exposed via the "--lib" command-line argument documented [here](https://github.com/microsoft/pyright/blob/master/docs/command-line.md).

I'll look into the problem in more detail. Unresolved imports should not be treated as "Unbound", so based on your description, this sounds like a bug.

**Comment by QUANZHOU1990** [comment]
Thanks for the information, Eric!

I think i made a mistake. If i start the virtual env (where lib code is installed), and run the pyright. The error information related to "Unbound" is gone. 
Sorry for the confusion...

**Comment by erictraut** [comment]
I'm going to keep it open for now. I'd like to repro the case you were seeing because it sounds like a bug.

**Comment by QUANZHOU1990** [comment]
To provide more information. 
I use poetry to create the virtual env. When i created the issue i stated, i did not start the `poetry shell` or use `poetry run pyright`. Maybe that is why pyright couldn't find the lib code. 
If i start the `poetry shell` or use `poetry run pyright`, then the `Unbound` errors are gone. 
As to the error related to `logging.config`, that is a bug. And pyright does spot it correctly. The code only imported `logging`, not `logging.config`, which would produce the bug. 
I think it is my misuse of pyright, rather than a bug. But if you want more information, please let me know.

**Comment by QUANZHOU1990** [comment]
And a side question, what pyright refers to for type checking if i do not generate pyi files? I can run pyright with no problem in the poetry venv, even though i do not generate type stub files manually.

**Comment by erictraut** [comment]
By default, if pyright can't find a type stub, it will assume the imported symbol or module is of "unknown" type, effectively disabling all further type checks associated with that symbol. It should not treat it as an "unbound" symbol, which is why I want to investigate this problem further.

If you enable the "useLibraryCodeForTypes" setting (or use the "--lib" command-line switch), pyright will first look for a type stub. If it doesn't find a type stub, it will then look for the ".py" file that implements that library and extract as much type information as it can. Type information extracted from library code will typically be incomplete especially if (as is typical) the code contains no type annotations. So using this method, you'll see a combination of unknown and known types. This method can also double or triple the time it takes to perform the analysis, which can be an issue for large code bases.

**Comment by QUANZHOU1990** [comment]
I see. So two more questions: 
1. with --lib, pyright will exhaust the files in `PYTHONPATH` for py files? 
2. i have a test here: 
```
import logging
logging.config
```
just `pyright` without `--lib` will raise error on this since logging does not have config attribute ( we need to import `logging.config`). I do not have `logging` typestubs (not intentionally generated at least). Where does pyright look to find such error?

**Comment by erictraut** [comment]
1. Pyright users a variety of techniques for resolving imports. They are documented [here](https://github.com/microsoft/pyright/blob/master/docs/import-resolution.md). The same technique is used for .py and .pyi files.

2. Pyright ships with a set of type stubs from the typeshed repo. It includes stubs for all of the stdlib libraries that ship with Python, and that includes the "logging" module.

**Comment by QUANZHOU1990** [comment]
Thanks for all the info! Very helpful!

**Comment by erictraut** [comment]
OK, thanks for the additional information. I think everything is working as expected, so I'm going to close the issue.
