### ISSUE TITLE
no module named 'reuests'

### ISSUE THREAD

**Issue by saiteja25755** [microsoft/pyright#7001]
If you have a question about a behavior that you’re seeing in pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem.

**Describe the solution you’d like**
A clear and concise description of the solution you would like to see.

import requests not found issue problem from  3weeks iam unable to run python because of that please solve immediatly

**Comment by erictraut** [comment]
You haven't provided enough information in this ticket, so I'm going to close. If you have a question about pyright, consider posting to the discussion forum. If you want to report a bug, please follow the instructions in the bug template and supply information about repro steps, etc.
