### ISSUE TITLE
Type of higher-order function is no longer correctly inferred

### ISSUE THREAD

**Issue by Quaffel** [microsoft/pyright#7002]
I often use generic identity functions to provide type annotations for lambda expressions. I typically use them when passing a higher-order function to another (poorly typed or very generic) function.

Since pyright 1.1.346, I've started getting errors related to the type inference of the passed higher-order function. Consider the following self-contained example:

```python
import typing

_T = typing.TypeVar("_T")


def identity(_type: typing.Type[_T], it: _T) -> _T:
    return it


def foo(test: str) -> None:
    return


class Box(typing.Protocol):
    item: str


test = identity(               # <-- reports error of type reportGeneralTypeIssues [1]
    typing.Callable[[Box], None],
    lambda it: foo(it.item))
```

The problem analogously occurs if the type of the function's parameter is changed to `typing.Any`.

```python
another_test = identity(       # <-- reports error of type reportGeneralTypeIssues [2]
    typing.Callable[[typing.Any], None],
    lambda it: foo(it.item))
```

In case this behavior is deliberate, I'd be glad if you could point me to the corresponding pull request such that I can try to understand its rationale.

Thank you for your time.

**Error messages:**

[1]:
```raw
  <project path>/identity.py:19:5 - error: Argument of type "type[(Box) -> None]" cannot be assigned to parameter "_type" of type "type[_T@identity]" in function "identity"
    Type "type[Callable]" cannot be assigned to type "type[(it: Unknown) -> None]"
      Function accepts too many positional parameters; expected 0 but received 1
        Function return type "Callable" is incompatible with type "None"
          "Callable" is incompatible with "None" (reportGeneralTypeIssues)
```

[2]:
```raw
  <project path>/identity.py:24:5 - error: Argument of type "type[(Any) -> None]" cannot be assigned to parameter "_type" of type "type[_T@identity]" in function "identity"
    Type "type[Callable]" cannot be assigned to type "type[(it: Unknown) -> None]"
      Function accepts too many positional parameters; expected 0 but received 1
        Function return type "Callable" is incompatible with type "None"
          "Callable" is incompatible with "None" (reportGeneralTypeIssues)
```

**VS Code extension or command-line**
pyright (cli): 1.1.346 and 1.1.347, does not occur with 1.1.34

**Comment by erictraut** [comment]
The new behavior is correct. This change was made as part of an effort to tighten up pyright's conformance with the official Python typing spec.  The `typing.Callable` symbol is a special form and is not compatible with `type[T]`, so you cannot use it in this manner. Mypy generates the same error in this code.

The problem with treating `Callable` as compatible with `type` is that it's not an instantiable class. That means the following will produce a runtime error. Previously pyright didn't catch bugs like this.

```python
def func(val: type[_T]) -> _T:
    return val()

func(Callable[..., None])
```
