### ISSUE TITLE
dataclass_transform is incredibly finicky

### ISSUE THREAD

**Issue by Aran-Fey** [microsoft/pyright#7003]
Since apparently nothing I report is considered a bug, I won't waste my time going into too much detail. But `@dataclass_transform()`  is extremely poorly supported, and the tiniest change can lead to completely different results. Some examples:

```python
@dataclass_transform()
class MetaClassParent(type):
    pass

class MetaClassChild(MetaClassParent):
    pass

class Demo(metaclass=MetaClassChild):
    x: int

Demo(3)  # Error: Expected no arguments to "Demo" constructor
```

```python
def my_field(
    *,
    init: bool = False,
    my_extra_arg: bool,
) -> Any:
    ...

@dataclass_transform(field_specifiers=(my_field,))
class MyDataClass:
    pass

class Demo(MyDataClass):
    x: int = my_field(my_extra_arg=True)

Demo()  # Signature is *args, **kwargs for some reason
```

Among other problems that I can't reproduce with a short snippet.

**Comment by erictraut** [comment]
Moving this to a discussion since it's a question about how to use `dataclass_transform` rather than a bug report.
