### ISSUE TITLE
Since v1.1.339: Cannot override abstract method's parameter with ignored '_' parameter

### ISSUE THREAD

**Issue by stefanberger** [microsoft/pyright#7005]
**Describe the bug**

Since v1.1.339 we cannot override an abstract method's parameter with an ignored parameter anymore (keylime project).

```
git clone https://github.com/keylime/keylime.git
cd keylime
pyright keylime/mba/elchecking/
```

The abstract method essentially looks like this:
```
    @abc.abstractmethod
    def why_not(self, globs: Globals, subject: Data) -> str:
        raise NotImplementedError

```

The overriding method looks like this:
```
    def why_not(self, _: Globals, subject: Data) -> str:
        return ""
```

The reported error looks like this:
```
/home/stefanb/keylime/keylime/mba/elchecking/tests.py
  /home/stefanb/keylime/keylime/mba/elchecking/tests.py:107:9 - error: Method "why_not" overrides class "Test" in an incompatible manner
    Parameter 2 name mismatch: base parameter is named "globs", override parameter is named "_" (reportIncompatibleMethodOverride)
```

Is it a bug or a feature that a method parameter's name must be the same as the abstract method's name? I would understand the complaint if the parameter's types were different.

**Code or Screenshots**

Reproducer:

```python
import abc

class A:
    @abc.abstractmethod
    def fun(self, s: str) -> bool:
        raise NotImplementedError

class B(A):
    def fun(self, _: str) -> bool:
        return True
```

**Comment by erictraut** [comment]
This is intended behavior, not a bug. In Python, the name of a parameter is significant unless it's a positional-only parameter. That means you can't simply rename a parameter and expect an override to be compatible with a base class.

If your intent is for these parameters to be position-only, you can use the `/` parameter separator introduced in [PEP 457](https://peps.python.org/pep-0457). 

```python
import abc

class A:
    @abc.abstractmethod
    def fun(self, s: str, /) -> bool:
        raise NotImplementedError

class B(A):
    def fun(self, _: str, /) -> bool:
        return True
```

If the parameter isn't positional-only, you should stick with the same name in the override.
