### ISSUE TITLE
Passing enum values result in incompatible types

### ISSUE THREAD

**Issue by dqian96** [microsoft/pyright#7014]
Hey everyone, have a question about literal type widening with regards to enum values.
I have the following enum and method definition:

```python
class AnEnum(Enum):
    A = auto()
    B = auto()

class Clazz:
    def __init__(self):
        pass

    def fn(
        self, d: AnEnum, selected_states: Optional[Set[str]] = None
    ) -> List[str]:
        pass
```

And the following caller:
```python
example: AnEnum = AnEnum.A
res = clazz.fn(example)
```

pyright says I have the following error:

```python
 Argument of type "Literal[AnEnum.A]" cannot be assigned to parameter "d" of type "AnEnum" in function "fn" 
"Literal[AnEnum.A]" is incompatible with "AnEnum" [reportGeneralTypeIssues]                                           
```

To my understanding, pyright should widen the `Literal[AnEnum.A]` to `AnEnum` when calling the method, and be accepted. Is this correct understanding?

**Comment by erictraut** [comment]
Could you provide a self-contained code sample? I've tried to cobble together a full sample from your snippets above, but this doesn't result in any errors, so I'm guessing that I'm missing something.

Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBApgdgV2gSwgBzCALlAooiAGigEMEswAoSgYwBsSBnRqAQTnyQApOIBKAFyUoItlAC8pcmC59hogEISpFWdXpMWAYQYAvXUNFQAJjGBQA%2BheRxkWK10Yw6wQfKMi0m6kdPngcI7OwMTGAmwcBMROdDA0WDDGFoxYJAmM4U5YANopIAC6UAA%2BUAByYHAwyuWVfFAAtAB8UHTIKblYBYYeIgB0-dQwAB4k6LHh7LzKkwS9rLR6uso6JPpqlCAwLJIa%2Br0BXMOjaLFyQA)

```python
from enum import Enum, auto

class AnEnum(Enum):
    A = auto()
    B = auto()

class Clazz:
    def __init__(self):
        pass

    def fn(self, d: AnEnum, selected_states: set[str] | None = None) -> list[str]:
        ...

example: AnEnum = AnEnum.A
clazz = Clazz()

res = clazz.fn(example)

```

**Comment by erictraut** [comment]
I'm going to close this issue since there is no repro. If you are able to provide repro steps, please post them here, and I'm happy to take a look.
