### ISSUE TITLE
Go to references

### ISSUE THREAD

**Issue by korchizhinskiy** [microsoft/pyright#7045]
I use pyright lsp for nvim and have these situation.
I have a class of resolutions, and his realization in another module.
![image](https://github.com/microsoft/pyright/assets/100942887/1a7ebc31-3cdd-461c-9b54-7d5ed9cc9ba3)
When i use API of references, i view only this class
![image](https://github.com/microsoft/pyright/assets/100942887/6a9b70ff-ed7c-4488-9a05-9bcd7203f5b4)
But if i search in project, i am finding more then one usage.
![image](https://github.com/microsoft/pyright/assets/100942887/6a6b1c6e-b586-45c9-9bbb-a5ed0d8d63a5)

Important that... 
If a go to file with realization, then reference find work as need to me, he find all realizations of class, but after a while, the same behavior reappears.

**Comment by erictraut** [comment]
It's unlikely we can debug this from the description you've provided. Could you put together a set of detailed repro steps?

**Comment by erictraut** [comment]
It may be easiest to create a temporary github repo with a small project that includes just a few files — the minimum needed to repro the behavior you're reporting.

**Comment by korchizhinskiy** [comment]
Oh, sorry, i didn't add package in pyright config -> include, after this action - work wonderfully
Thank you!
