### ISSUE TITLE
Spawning new language servers again and again

### ISSUE THREAD

**Issue by f4T1H21** [microsoft/pyright#7048]
**Describe the bug**
Whenever I open a python file with nvim, pyright gets attached to the file, this is expected. The problem begins when I exit the neovim. Pyright server instance doesn't terminate, instead it keeps running at the background which leds hardware resource occupation. And when I open a python file again, there spawns a new instance of the pyright language server. This is so annoying. One thing I noticed is after 5 instances, there's no new instance of the pyright language server spawning.

**Screenshot**
![image](https://github.com/microsoft/pyright/assets/83399767/66a2b3de-06be-4e1f-8168-d67b5076b630)

I don't think this is relevant, but I use this configuration code in nvim to integrate pyright.
```lua
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"
local util = require "lspconfig/util"

-- if you just want default config for the servers then put them in a table
local servers = { "pyright", "other_lang_servers" }

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
    root_dir = util.root_pattern(vim.loop.cwd()),
  }
end
```

**Versions**
pyright 1.1.325
NVIM v0.9.5

**Comment by erictraut** [comment]
I don't know anything about nvim or how its LSP support works, so I won't be of much help to you here. If you're able to repro the behavior with VS Code, I'd be happy to look into it.

You may need to work with the maintainers responsible for LSP support in nvim to figure out what's going on. Or you could debug the problem yourself using the pyright using the [build instructions](https://microsoft.github.io/pyright/#/build-debug).

**Comment by erictraut** [comment]
I suspect this is because the language server support in nvim is not sending a proper "shutdown" command to the LSP. I'm going to close the issue because I don't think there's anything for pyright to do here. If you find additional details or would like additional assistance, feel free to post back to this thread.
