### ISSUE TITLE
Unable to index python3-gi library correctly.

### ISSUE THREAD

**Issue by aszswaz** [microsoft/pyright#7060]
coc-pyright version: 1.1.347

**What's the output of `:CocCommand workspace.showOutput Pyright`**

```txt
Workspace: /home/aszswaz/Documents/aszswaz/demo
Using python from /usr/bin/python

[Info  - 15:14:06.543] Pyright language server 1.1.347 starting
[Info  - 15:14:06.544] Server root directory: file:///home/aszswaz/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist
[Info  - 15:14:06.567] Starting service instance "demo"
[Info  - 15:14:06.654] Setting pythonPath for service "demo": "/usr/bin/python"
[Info  - 15:14:06.757] Assuming Python version 3.11
[Info  - 15:14:07.302] Found 18 source files
[Info  - 15:14:10.502] [FG] Long operation: checking: file:///home/aszswaz/Documents/aszswaz/demo/linux/bluetooth/python/server_advertising.py (2241ms)
[Info  - 15:14:10.505] [FG] Long operation: analyzing: file:///home/aszswaz/Documents/aszswaz/demo/linux/bluetooth/python/server_advertising.py (3171ms)
```

python3-gi is the python binding of GTK object. pright cannot index this library correctly. The example is as follows:

```python
from gi.repository import GLib
```

coc-pyright prompt: "GLib" is unknown import symbol (Pyright reportGeneralTypeIssues).

Is there a way to make coc-pyright ignore `python3-gi`, at least without giving an error message?

**Comment by erictraut** [comment]
Can you clarify by what you mean by "index this library"? Do you mean that pyright is unable to resolve the import?

Where can I find the `python3-gi` library? I don't see a package by that name in the pypi index.

**Comment by erictraut** [comment]
Closing the issue since I haven't heard a response.

**Comment by aaruni96** [comment]
I have the same issue. Pyright cannot resolve things imported from `gi`.

```
import gi
gi.require_version("OSTree", "1.0")
from gi.repository import OSTree, GLib
```

Pyright complains : `Pyright: "OSTree" is unknown import symbol`, and also `Pyright: "GLib" is unknown import symbol` .

The library is actually called [PyGObject](https://pypi.org/project/PyGObject/), but shows up as `gi` in code. This is the GObject Introspection library, providing python bindings to some other C libraries via GObject Introspection.

@erictraut pinging you, because I have insufficient permissions to reopen this issue, and I don't want to create a duplicate issue.

**Comment by erictraut** [comment]
I'm not able to install `PyGObject` from pip on my system. It looks like it requires a C compiler. That probably means it's not a Python library but instead a native library with Python bindings. If you want pyright to work with such a library, you'll need to install (or create) stub files that define the public interface to the library. I don't know if such stubs exist. For more information about stub files, refer to [this documentation](https://microsoft.github.io/pyright/#/type-stubs).

**Comment by aaruni96** [comment]
Thanks for the hint with type stubs, with the keyword I was able to find this project : https://github.com/pygobject/pygobject-stubs , which provides type stubs for gi. This also needs ` reportMissingModuleSource` to be set to false to suppress the warning about the source files being missing.
