### ISSUE TITLE
Add error if a `TypeAliasType` instance is used as a second argument to `isinstance` or `issubclass`

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#7086]
The following generates a runtime error. It would be nice if pyright would catch and report this error:

```python
type X = int | str
isinstance(1, X)
```

**Comment by davidingle188** [comment]
# Define a union type X that can be either an int or a str
X = int | str

# Check if the value 1 is an instance of the type X
result = isinstance(1, X)

# Print the result
print(result)

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.349, which I just published.
