### ISSUE TITLE
overloading methods in class

### ISSUE THREAD

**Issue by xSpecialFoodx** [microsoft/pyright#7093]
i've posted it in pylance-release repo as well.
i've discovered a bug in pylance in version 2023.12.1 that didn't exist in 2023.11.10.
if i have a class with 2 methods overloaded or more it doesn't suggest the parameters when i do a( for example.
```py
from typing import overload

class a:
  @overload
  def __init__(self, x: int):
    ...

  @overload
  def __init__(self, x: float):
    ...

  def __init__(self, x):
    return 3
```
a( gives me no suggestions.
with 1 overload it works.
if the overloads are for functions at top level and not class methods it works with multiple overloads though.
python 3.11.6.
i've managed to find that it works on 11.11 and downwards, and stops to work at 11.12 and upwards.
which means the bug most likely came to exist between 7-10 of november 23.

**Comment by debonte** [comment]
Looks like this was fixed in Pyright 1.1.341. Pylance just shipped a prerelease build this morning that includes the fix.
