### ISSUE TITLE
Support for f-strings

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#71]
Python 3.6 and newer supports f-strings (format strings) as described in [PEP 498](https://www.python.org/dev/peps/pep-0498/). Pyright doesn't currently parse these strings, so there's no type checking performed on them.

**Comment by vistatest** [comment]
As a result, pyright reports that a variable is not accessed when it is accessed within f-strings.

**Comment by erictraut** [comment]
f-strings are now supported in pyright 1.0.40, which I just published.

**Comment by vistatest** [comment]
Thanks a lot, works great!
