### ISSUE TITLE
Wrong type gussing after str.encode

### ISSUE THREAD

**Issue by nyaoouo** [microsoft/pyright#7102]
**Describe the bug**
wrong type gussing

**Code or Screenshots**
```python
def test(s: bytes | str):
    if isinstance(s, str):
        s = s.encode()
    if s[-1] != 0:
        s += b'\0'
    ....
```
![image](https://github.com/microsoft/pyright/assets/64143453/8cc021ac-4cb7-4c2a-afab-8ccb2769621f)
report error `Operator "+=" not supported for types "bytes | bytearray | memoryview" and "Literal[b"\x00"]";Operator "+" not supported for types "memoryview" and "Literal[b"\x00"]"`

**VS Code extension or command-line**
Vs Code extension v1.1.348

**Comment by erictraut** [comment]
Pyright's behavior here is correct. The `bytes` type annotation historically has been treated as meaning `bytes | bytearray | memoryview`. That means you could pass any of these types to `test` without a type error.

[PEP 688](https://peps.python.org/pep-0688/#removal-of-the-bytes-special-case), which was recently accepted as part of Python 3.12 recommends that this special treatment of `bytes` be reversed. Pyright accordingly introduced a new configuration option named `disableBytesTypePromotions` that allows you to disable this historic behavior. If you set `disableBytesTypePromotions` to true, you'll see that pyright behaves the way you were assuming for `bytes`.

You can test this by adding the following line to the top of the file that contains your code sample.

```python
# pyright: disableBytesTypePromotions=true
```
