### ISSUE TITLE
UnionTypes are typed as `type[UnionType]` 

### ISSUE THREAD

**Issue by adampauls** [microsoft/pyright#7110]
**Describe the bug**

The (runtime) type of a union type like `int |str` is `types.UnionType`, but the function invocation below does not typecheck.

```python
from types import UnionType
from typing import Any

def foo(x: UnionType) -> None:
    ...

#  error: Argument of type "type[int] | type[str]" cannot be assigned to parameter "x" of type "UnionType" in function "foo"
#    "type[type]" is incompatible with "type[UnionType]" (reportArgumentType)
foo(int | str)
```

**VS Code extension or command-line**
Command line version 1.1.348.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.349, which I just published.
