### ISSUE TITLE
Type inference issue with Literal and Union in Tuple

### ISSUE THREAD

**Issue by FeeeeK** [microsoft/pyright#7122]
**Describe the bug**
Pyright doesn't correctly infer the type of a variable based on associated Literal values in a Union of Tuple types.

**Code or Screenshots**

```python
from typing import Literal, Tuple, Union

class Result:
    foo: str

def is_ok() -> (
    Union[
        Tuple[Literal[True], Result],
        Tuple[Literal[False], Exception],
    ]
):
    ...

ok, result = is_ok()
if ok:
    print(result.foo)  # Cannot access member "foo" for type "Exception"
```

**VS Code extension or command-line**
cli version: `1.1.348`

**Comment by LeeeeT** [comment]
This looks the same as https://github.com/microsoft/pyright/issues/3919.

If you want conditional narrowing, you can use pattern matching:

```python
match is_ok():
    case True, result:
        print(result.foo)
    case False, exception:
        raise exception
```

**Comment by erictraut** [comment]
Pyright is working as designed here. This isn't a bug. The type of `result` is `Result | Exception` after the call to `is_ok`. It can't be narrowed any further. 

As @LeeeT said, you could use a `match` statement. Or you could use the following.

```python
result = is_ok()
if result[0] is True:
    print(result[1].foo)
```
