### ISSUE TITLE
Chaining functions accepting callbacks & `*args` typed with `TypeVarTuple` fails to bind types properly

### ISSUE THREAD

**Issue by Enegg** [microsoft/pyright#7136]
**Describe the bug**
Given a function A which accepts an arbitrary function B as a callback and positional arguments for it, it should be possible to pass A another function with similar behavior (including itself), so long as the call chain eventually calls a function C which exits the "stack".

**Code**
```python
# python 3.10
from collections import abc
from typing_extensions import TypeVar, TypeVarTuple, Unpack

T = TypeVar("T")
PosArgsT = TypeVarTuple("PosArgsT")

def call(func: abc.Callable[[Unpack[PosArgsT]], T], *args: Unpack[PosArgsT]) -> T:
    return func(*args)

def callback(num: int, /) -> int:
    return num

x = call(call, callback, 123)  # pylance reports an error
# also, it fails to infer x: int, reports x: T(1)@call instead
print(x)  # 123
```
![image](https://github.com/microsoft/pyright/assets/42005170/2df3e817-ca8b-4f46-8d62-3da6e030a195)

<details>
<summary>Problem caught while chaining two functions from the anyio library</summary>

```python
# python 3.10
import anyio  # 4.2.0
import anyio.to_thread
import os

Pathish = os.PathLike[str] | str

async def foo() -> None:
    def runner(path: Pathish, /) -> None:
        ...

    async with anyio.create_task_group() as tg:
        async for path in anyio.Path(".").glob("**/*.py"):
            tg.start_soon(anyio.to_thread.run_sync, runner, path)  # pylance reports an error
```
Signatures of called functions:
![image](https://github.com/microsoft/pyright/assets/42005170/22883d9e-9540-4975-a212-93505cbe11e8)
![image](https://github.com/microsoft/pyright/assets/42005170/96706a92-82d8-4d86-9ed7-ecc0ce186878)
Error:
![image](https://github.com/microsoft/pyright/assets/42005170/f36ea8e9-89dc-46a6-96e9-7e633bd85b64)

</details>

**VS Code extension or command-line**
VS Code extension - Pylance `v2023.12.1`

**Comment by erictraut** [comment]
Thanks for the bug report, but this was fixed many versions ago in pyright.

Code sample in [pyright playground](https://pyright-play.net/?pyrightVersion=1.1.348&pythonVersion=3.10&code=GYJw9gtgBAxmA28CmMAuBLMA7AzldEADmCKlAIYBGMAsAFCiRSoCeh6WA5gPpIAeqJLky58REmQAqbJADVyIADRRphOQskBXQsmUBVLIXIwA1vXqSoAXhUz5IABQAiSU4CU9AApgcAQRCcOJY2quogWjpIzt5%2BAUHu5nT0ACZIwLDkiA7AmlgwAFwU1AB0AMKZ8FTIANrVBkam1TH%2BgZIAum3K7coAVAqBhfXGJk0%2BLUFtblAAtAB8Kvn0UMtQIEiomiBYUDl5Dn1xHknHqekwFZTDDliaEIUcqMoA9FNz%2BFioi3Qrq%2Bub2zcIIl6HxrBksudEMpIfBLqZlABGABMAGYjoQQA8HHwjsC6EA)

It looks like you're using using an older version of pylance. Please upgrade to the latest version (or the latest prerelease version), and this should be fixed.

**Comment by Enegg** [comment]
Oh, didn't consider checking prerelease. It is indeed a few versions ahead, and the problem's gone. Thanks for timely response!

**Comment by Enegg** [comment]
@erictraut, I was too fast with my response; the code I've provided as repro steps indeed no longer fails, but the situation with `anyio`'s functions remains.
![image](https://github.com/microsoft/pyright/assets/42005170/8646772e-cdc3-42df-8edd-4595cd9988cf)

I don't see any noticeable differences between their function's definitions and my code though, besides the existence of keyword-only parameters (which all have defaults).

Lib code sample in [playground](https://pyright-play.net/?pyrightVersion=1.1.348&pythonVersion=3.10&strict=true&code=GYJw9gtgBAxmA28CmMAuBLMA7AzgOgEMAjGKdCABzBFSgEEB3A9VY5AGigGEDE2kAsAChQkKKgCeFdFgDmZStVoAVKUgBqBEJzpYJw0dEnS5AfSQAPVElyZcCqjSiqKGrcoCuFDlACqWCgIYAGthYWVTACUkVAA3XigAXmc1TRAACgAiCOi43kyASmEABTAcOhBZHGUklNc0z28kLNLyyurCsKFhABMkYCgcVhpTHDBsdOEoaahgDywYAC5uXnh%2BAG11-0CQ9daKquUAXSOdJhYN3QkT9imZgCotKuXtoOC9soPq07vprAIIEhlmAiAArFC0ZIAOWwSFuQgKUAAtAA%2BKAwrBA35QPC4rrCAg4CQLKB9AYgeajYkwSZCGazeZLFZ8IjITavXb7drHU7OKIxeLwH50h5PHAvAJvD5tQ7C%2BnEAhYHrYUwqmCKmBIeDLIjjeC1ABivBwcOx6oWWrWrKBUF1CCgAB90bDahjTSLpvByCwkCBgWCIY7nZjXbD4YjUXzcoLFtj6bi8PihGSoBSsJiMlgPBBljJUJwAPQRtF52Me1MxDwgLBQLMQJNDLSoUbjLDpNNUhacNMZzgARgATABmApAA)

I'm using Pylance `v2024.1.101` now.

**Comment by Enegg** [comment]
I have also just discovered that adding a 2nd `call` to my initial repro code:
```py
call(call, call, callback, 123)
```
Makes pyright indefinitely hang. I tried both in the playground (shows "waiting for server" and from that point on no further error reports are made) and in VS Code (shows "1 file to analyze"; also checking the output tab shows fatal error).
<details>
<summary>Output tab logs</summary>

```
2024-01-27 19:36:48.722 [info] [Info  - 7:36:48 PM] (18152) Background analysis(3) started
2024-01-27 19:41:21.890 [info] 
<--- Last few GCs --->

[18152:000000FC00340000]   280926 ms: Mark-Compact 1989.4 (2064.5) -> 1985.0 (2068.5) MB, 4061.28 / 0.00 ms  (average mu = 0.451, current mu = 0.239) allocation failure; scavenge might not succeed
[18152:000000FC00340000]   287379 ms: Mark-Compact 1995.6 (2071.0) -> 1990.2 (2073.5) MB, 6343.00 / 0.00 ms  (average mu = 0.235, current mu = 0.017) allocation failure; scavenge might not succeed


<--- JS stacktrace --->


2024-01-27 19:41:21.892 [info] FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

2024-01-27 19:41:22.071 [info]  1: 00007FF717BD2786 node::SetTracingController+80086
 2: 00007FF717BD2A13 node::OnFatalError+595

2024-01-27 19:41:22.072 [info]  3: 00007FF71A8C19B3 v8::Function::NewInstance+835
 4: 00007FF71A8C1943 v8::Function::NewInstance+723
 5: 00007FF71A98A367 v8::CppHeap::CollectGarbageInYoungGenerationForTesting+74791
 6: 00007FF7194D1594 v8::MicrotasksScope::PerformCheckpoint+543732
 7: 00007FF7194CC8ED v8::MicrotasksScope::PerformCheckpoint+524109
 8: 00007FF7194BCCE7 v8::MicrotasksScope::PerformCheckpoint+459591
 9: 00007FF7196C7C73 v8::MicrotasksScope::PerformCheckpoint+2601683
10: 00007FF7199E4D3A v8_inspector::String16::String16+2535050
11: 00007FF7199E5688 v8_inspector::String16::String16+2537432
12: 00007FF77A04CFD1 

2024-01-27 19:41:22.471 [info] [Error - 7:41:22 PM] Server process exited with code 134.
2024-01-27 19:41:22.482 [info] [Info  - 7:41:22 PM] Connection to server got closed. Server will restart.
2024-01-27 19:41:22.482 [info] true
2024-01-27 19:41:23.915 [info] [Info  - 7:41:23 PM] (17300) Pylance language server 2024.1.101 (pyright version 1.1.348, commit cfb1de0c) starting
```
</details>

**Comment by erictraut** [comment]
This issue has been closed. If you would like to report other bugs, please open a new issue for each so they can be tracked accordingly.
