### ISSUE TITLE
Add multi-root workspaceFolder support to path variable expansion

### ISSUE THREAD

**Issue by Seairth** [microsoft/pyright#7137]
Currently, pyright does not support path variable expansion for tokens in the form of `${workspaceFolder:name}`, which is documented by VSCode for multi-root workspaces.  Following from the invitation at https://github.com/microsoft/pylance-release/issues/4405#issuecomment-1912811225, I added the feature. The current commit can be found at https://github.com/Seairth/pyright/commit/37fff578e2cb4d558def86b4edebab883c848051.

Overall changes:
* Re-ordered the `expandPathVariables` arguments and added an additional argument for the list of workspaces
* Enhanced `expandPathVariables` to iterate over the workspaces and perform variable expansion for tokens in the form of `${workspaceFolder:name}`
* Updated existing tests that used `expandPathVariables`
* Added new tests for `expandPathVariables` (including tests for existing functionality)

All tests pass.  I have also built the VSCode extension and verified the new functionality.

Before I submit a PR, I want to make sure the commit meets "Contributing" requirements.

**Comment by erictraut** [comment]
Thanks for the contribution. It looks good to me, but I'd like the pylance team members to review it as well. Please go ahead and submit the PR.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.350, which I just published.
