### ISSUE TITLE
Tuple size mismatch of function return value

### ISSUE THREAD

**Issue by hologerry** [microsoft/pyright#716]
**Describe the bug**
The return value tuple size not correctly analyzed.

**To Reproduce**
Steps to reproduce the behavior.
1. Write a function with more than one kind return value
2. Hover on the error information.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/11660168/84027849-3bc90200-a9c2-11ea-96e4-c8c1f1a1745b.png)

![image](https://user-images.githubusercontent.com/11660168/84027728-07554600-a9c2-11ea-8d0c-af82d8581525.png)

```
def func(arg=False):
    a, b, c = 1, 2, 3
    d, e, f = 4, 5, 6
    if arg is False:
        return a, b, c
    return a, b, c, d, e, f

ret1a, ret1b, ret1c = func(arg=False)
ret2a, ret2b, ret2c, ret2d, ret2e, ret2f = func(arg=True)
```

**VS Code extension or command-line**
VS Code extension
VS Code and pyright are both the latest version.
**Additional context**

**Comment by msfterictraut** [comment]
The behavior is correct. Your function has no declared return type annotation, so a type checker like Pyright will need to infer its return type based on the return statements. In this case, there are two return statements. One returns a 3-element tuple, the other a 6-element tuple, so the effective return type is a union of these two types.

When you attempt to assign this union to either a 3-element tuple or a 6-element tuple, one of the two union elements will not match the destination type, hence the errors.

There are several ways you can work around the issue:
1. Returning different types (or different numbers of return values) based on input arguments is not an advisable pattern, so my best advice is not to use this pattern. Change your function so it doesn't return different tuple sizes.

2. If that's not feasible for some reason, use overloads to describe the different behaviors of your function. Place the following code before your actual function definition.

```
@overload
def func(arg: Literal[False]) -> Tuple[int, int, int]:
   raise NotImplementedError()

@overload
def func(arg: Literal[True]) -> Tuple[int, int, int, int, int, int]:
   raise NotImplementedError()
```

Note that the use of `Literal` requires Python 3.7 or newer.

3. If you don't like either of those suggestions, you can annotate your function with a return type of `Tuple[int, ...]`. This will tell the type checker "this function returns a tuple that contains all "int" values, but the number of values is indeterminate".

**Comment by hologerry** [comment]
Hi @msfterictraut, sorry for my poor skills in python.
Thanks a lot for your comprehensive explanation.
