### ISSUE TITLE
silence formatStringNestedQuote

### ISSUE THREAD

**Issue by mustafa0x** [microsoft/pyright#7162]
I'm using 3.12 and would like to silence `formatStringNestedQuote`.

> Strings nested within an f-string cannot use the same quote character as the f-string prior to Python 3.12 Pylance

**Comment by erictraut** [comment]
Pyright conditionally emits this error based on the pythonVersion you've configured. If you haven't specified a pythonVersion in the configuration settings or on the command line, pyright will default to the version of the python interpreter that you've configured. 

If you're seeing this error, then you have not correctly configured pyright to assume Python 3.12 or newer.

**Comment by mustafa0x** [comment]
That fixed it, thanks.
