### ISSUE TITLE
`__setattr__` is not used to infer typing when the attribute itself is typed

### ISSUE THREAD

**Issue by guillaume-alliander** [microsoft/pyright#7163]
**Describe the bug**
`__setattr__` is not used to infer typing when the attribute itself is typed.
 
**Code or Screenshots**

What I am trying to do: have a class (`MyContainer`) with one attribute `a:int` but which would accept `a=2.0` as assignment. `__setattr__` will do a cast to `int` (minimalistic example, of course). 

```python
from dataclasses import dataclass
from typing import Any, Literal, overload

@dataclass
class MyContainer:
    a: int

    @overload
    def __setattr__(self, __name: Literal["a"], __value: int) -> None:
        ...

    @overload
    def __setattr__(self, __name: Literal["a"], __value: float) -> None:
        ...

    def __setattr__(self, __name: str, __value: Any) -> None:
        if __name == "a":
            if isinstance(__value, int):
                super().__setattr__(__name, __value)
            elif isinstance(__value, float):
                super().__setattr__(__name, int(__value))
            else:
                raise Exception("Boom")
        else:
            super().__setattr__(__name, __value)


m = MyContainer(a=1)
m.a = 2.0  # pyright complains here. At runtime, m.a is 2, as expected.
print(m)
```

**VS Code extension or command-line**

Running on the cli, version 1.1.349

**Comment by erictraut** [comment]
Pyright is working correctly here, and I don't consider this a bug. The statement `m.a = 2.0` invokes the `__setattr__` method on your code, and pyright uses its signature to validate the assigned type. It's correctly reporting a type violation.

It looks like you want support for dataclass converters. The attrs library already has support for this, and there is a draft [PEP 712](https://peps.python.org/pep-0712/) that proposes to add this to the stdlib. Unfortunately, the Python steering council recently hinted that they're unlikely to accept it.

Here's what the code would look like with converter support.
```python
@dataclass
class MyContainer:
    a: int = field(converter=int)
```

With converters not an option, it may make sense for you to abandon dataclass in this case and use a regular class with a property.

```python
class MyContainer:
    _a: int

    def __init__(self, a: int):
        self._a = a

    @property
    def a(self):
        return self._a

    @a.setter
    def a(self, val: float):
        self._a = int(val)
```
