### ISSUE TITLE
Enum members not recognized as instances of Self in classmethods

### ISSUE THREAD

**Issue by tapetersen** [microsoft/pyright#7169]
**Describe the bug**
When defining class methods on enums I would have expected members to be recognized as instances of the class and accepted as return values for a method typed as returning `Self`

**Code or Screenshots**
Code sample in [pyright playground](https://pyright-play.net/?strict=true&locale=en&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDKApgDbACwAUFjnlESgK4RVUDGJAhgM7eEycYjbgAoGzAHQBRJhACUALipQVUAPIBpKAF56siZ0YwwIua0qqoAAQ49uEIjAAWYACbLVrosCgJOIbiIRDm45KABaAD5CUmAlC0tVEEdGEBR%2BQWEJTSogA)

```python
from typing import Self
import enum

class Status(enum.Enum):
    OK = enum.auto()

    @classmethod
    def parse(cls) -> Self:
        return Status.OK

```

**VS Code extension or command-line**

Visible in current pylance version in VS-code  v2023.12.1 (and pyright playground as above)

**Comment by erictraut** [comment]
Pyright's behavior here is correct. The `Self` type is effectively a type variable that has an upper bound of the containing class. It is not the same as the class itself. 

The correct way to annotate this method is:

```python
    @classmethod
    def parse(cls) -> "Status":
        return Status.OK
```

If you really want to use `Self` for some reason, you'd need to change your method's implementation to the following:

```python
    @classmethod
    def parse(cls) -> Self:
        return cls("OK")
```
