### ISSUE TITLE
Reporting potential runtime error on list comprehension with safe value retrieval

### ISSUE THREAD

**Issue by iamkhav** [microsoft/pyright#7182]
**Describe the bug**
Hey all,
I might have found a bug on the following code.
It seems that pyright disregards a condition where the list comprehension makes sure not to induce a `KeyError` by blindly accessing an optional dictionary key (on a `TypedDict`).

**Code**

```python
from typing import TypedDict, NotRequired

TestDictDef = TypedDict(
    "TestDictDef",
    {
        "key": NotRequired[str]
    },
)

test_dict: list[TestDictDef] = [{"key": "abcdef"}, {"key": "ghijkl"}, {}]

x: list[str] = [e["key"] for e in test_dict if e.get("key") is not None]

print(x)
# ['abcdef', 'ghijkl']
```

Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgCYAiSAxjADRQByYMASsQI4CuSIZAUHwLEAzjEo1yxYFAC8hEhWowAFHyjqoAIiGjxYqZtpqNAb2MaNmgNbE4mgFyNmbLjzIBtUSAC65qAF8jAEoBGBEYAH1SJUcAGyRRdx0xJUlgb1kodxNrWwctAEMAIypSA0CoHJs7R000AAskACsrWM0Kk39fPgAPOISYTxgfTPdid1y7DOBcKGJMFFhwqKVMaWIAOjRiFUnNIMxhKBRmJxRiXyA)

Pyright's output:
```
Could not access item in TypedDict
  "key" is not a required key in "TestDictDef", so access may result in runtime exception  (reportTypedDictNotRequiredAccess)
```
From pyright playground:
<img width="801" alt="image" src="https://github.com/microsoft/pyright/assets/44270110/bc4c6101-d63c-4b04-8a83-f42193301232">

I'm running version 1.1.349 which is at this time the most recent version.

**Comment by erictraut** [comment]
Pyright is working as designed here, so I don't consider this a bug. You're using a conditional expression (`e.get("key") is not None`) that is not a support type guard pattern. For a full list of supported type guard patterns, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards). Each type guard pattern requires custom logic and is very specific to that form. It's unlikely that we'd ever add support for a form as complex as `<TD>.get(<Literal>) is not None`. If you want to use a type guard as complex as this, you would need to write your own user-defined type guard function using PEP 647's `TypeGuard`.

Alternatively, you could use a supported type guard pattern like `S in D` (where S is a string literal and D is a TypedDict).

```python
x: list[str] = [e["key"] for e in test_dict if "key" in e]
```

**Comment by iamkhav** [comment]
Thank you so much for your detailed answer, @erictraut!
This is very helpful.
