### ISSUE TITLE
`reportRedeclaration` false negative when redeclaration has the same type

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#7192]
```py
foo: int = 1 # no error
foo: int = 2

bar: int = 1 # error
bar: str = ""
```
[playground](https://pyright-play.net/?strict=true&deprecateTypingAliases=true&enableExperimentalFeatures=true&reportCallInDefaultInitializer=true&reportImplicitOverride=true&reportImplicitStringConcatenation=true&reportPropertyTypeMismatch=true&reportMissingSuperCall=true&reportShadowedImports=true&reportUninitializedInstanceVariable=true&reportUnnecessaryTypeIgnoreComment=true&reportUnusedCallResult=true&code=GYexC4AIEsDsBdIF5IEZIGJKxJApgE4EgECwAUKBDAspAEwUUBGAhgVHIiulocWXJsOkAM7wCdAERSgA)

**Comment by erictraut** [comment]
Pyright is working as intended here. If you declare the type the same in multiple locations, there's no conflict and therefore no cause to generate an error.

**Comment by DetachHead** [comment]
it's obviously a mistake though. in my case, i accidentally copy/pasted a variable twice when i intended the second one to have a different name
