### ISSUE TITLE
`isinstance` check incorrectly changes type to include `list[Any]` outside of the if statement

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#7193]
```py
def foo(value: object):
    print(value)
    if isinstance(value, list):
        print(value) # error: reportUnknownArgumentType (correct)
    print(value) # error: reportUnknownArgumentType (wrong) 
```
[playground](https://pyright-play.net/?strict=true&deprecateTypingAliases=true&enableExperimentalFeatures=true&reportCallInDefaultInitializer=true&reportImplicitOverride=true&reportImplicitStringConcatenation=true&reportPropertyTypeMismatch=true&reportMissingSuperCall=true&reportShadowedImports=true&reportUninitializedInstanceVariable=true&reportUnnecessaryTypeIgnoreComment=true&reportUnusedCallResult=true&code=CYUwZgBGD20BQDcCGAbAriAXBaAjAViAMYAuAlJgLABQEdEADgE4CWAdiYqhmTfRC0gsAzu2EkkbIiC7oQAGggoR5KrX71m7TsjlkIAYgggmTaEwhwi5psXJ9NrDrJ6Hjp85YDuZtgHMyIA)

this is because the if statement changes the type to `list[Any] | object` after the if statement, which is technically correct, but redundant because `object` is wider than `list[Any]` so the type can be simplified to just `object`, avoiding the error. here's the same example in typescript which does simplify unions like this:
```ts
declare const foo: unknown

if (Array.isArray(foo)) {
    foo // any[]
}
foo //still unknown

declare const bar: any[] | unknown // gets simplified to just `unknown`
```
[playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPAK4oDWKSA7igLABQ9AltvABQCCMMUAngHSM0nbj1a4kASgnwA3vXgKceeYoD0qgHoB+egF964+uu316oSLATJ0WAEaxCUFDwDaAXXgAfYmQrUjqopBwdpAA)

**Comment by erictraut** [comment]
This behavior is correct and intended, not a bug.
