### ISSUE TITLE
Support type change on variable reassignment / initialisation

### ISSUE THREAD

**Issue by nabilnaffar-sf** [Microsoft/pyright#72]
**Is your feature request related to a problem? Please describe.**
Usage example:
```
_client: Optional[SlackClient] = None

def _get_client() -> SlackClient:
	global _client
	if not _client:
		_client = SlackClient()
	return _client
```
error: `Expression of type 'Optional[SlackClient]' cannot be assigned to return type 'SlackClient'`

**Describe the solution you'd like**
Property type should be changed per assignment.

**Comment by erictraut** [comment]
This is now fixed in 1.0.19, which I just published.
