### ISSUE TITLE
what is Pyright complaining about? assigned to parameter "v" in function "__setitem__"

### ISSUE THREAD

**Issue by SHxKM** [microsoft/pyright#722]
**To Reproduce**

```python
# MAX_FILE_SIZE is an int == 75, REDIRECT_TARGET is a string 
from .common import REDIRECT_TARGET, MAX_FILE_SIZE 

def some_func(request):
      context = {"form_details": form_details}
      context["max_file_size"] = MAX_FILE_SIZE 
      context["redirect_to"] = REDIRECT_TARGET
```

**Describe the bug**
I'm not sure what is Pyright complaining about here, highlighting the last two lines:

> Argument of type "Literal[75]" cannot be assigned to parameter "v" in function "__setitem__" of type "dict[str, Unknown]"
  "int" is incompatible with "dict[str, Unknown]"

> Argument of type "str" cannot be assigned to parameter "v" in function "__setitem__" of type "dict[str, Unknown]"
  "str" is incompatible with "dict[str, Unknown]"

**Expected behavior**
No complaints. I'm adding two new keys to a dictionary.

**Comment by msfterictraut** [comment]
This appears to be the same issue as #718. Please review that response for an explanation.

**Comment by SHxKM** [comment]
@msfterictraut thanks for the prompt response, will inspect.
