### ISSUE TITLE
`if var is None: raise ...`-guard not working

### ISSUE THREAD

**Issue by sebastianvitterso** [microsoft/pyright#7220]
**Describe the bug**
Inside one of my functions, I have a variable typed as such: `var: MyType | None`, and when I then add a `if var is None: raise Exception("Error")`, it still doesn't accept that it's not `None` further down in the code.

After some debugging, I found it happens only when re-assigning to the variable at a later time, for some reason. See screenshots below.

**Code or Screenshots**
I realize the code isn't minimal, but I didn't manage to make it smaller without alerting ruff (creating yellow lines everywhere).

![image](https://github.com/microsoft/pyright/assets/37065184/83bacc8c-36f3-4a2b-a996-eb2fa2e45175)

The  `find` function is made to mimic JS' `Array.find`, and has the signature `def find(items: Iterable[T], predicate: Callable[[T], bool]) -> T | None`.

**VS Code extension or command-line**
VS Code extension through Pylance `v2024.1.104 (pre-release)`.

**Comment by erictraut** [comment]
Debugging problems from partial screen shots makes it very difficult to diagnose problems. Please create a minimal, self-contained code sample and post the code in text form.

**Comment by sebastianvitterso** [comment]
This also caused the problem. Turns out having an extra function is what causes it - either if it's a lambda function or a regular function.

```python
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from typing import TypeVar


@dataclass
class Session:
    """A session."""

    id: str
    name: str


T = TypeVar("T")


def find(items: Iterable[T], predicate: Callable[[T], bool]) -> T | None:
    """Find the first item to match a predicate in an iterable and return it, None if no match is found."""
    return next((item for item in items if predicate(item)), None)


def test_1():
    """Test 1, works fine."""
    sessions = [Session(id="id1", name="session"), Session(id="id2", name="session")]
    session = find(sessions, lambda s: s.id == "id1")

    if session is None:
        raise Exception("Found no string")

    # the `id` in `session.id` here has no red line
    find(sessions, lambda s: s.id != session.id and s.name == "session1")


def test_2():
    """Test 2, with reassignment, shows red squiggly."""
    sessions = [Session(id="id1", name="session"), Session(id="id2", name="session")]
    session = find(sessions, lambda s: s.id == "id1")

    if session is None:
        raise Exception("Found no string")

    find(sessions, lambda s: s.id != session.id and s.name == "session1")
    # Error                                  ^^ "id" is not a known member of "None"

    session = Session(id="2", name="testing")


def test_3():
    """Test 3, with reassignment, with full-on function, shows red squiggly."""
    sessions = [Session(id="id1", name="session"), Session(id="id2", name="session")]
    session = find(sessions, lambda s: s.id == "id1")

    if session is None:
        raise Exception("Found no string")

    def is_same(s: Session) -> bool:
        """Return True if Sessions share id."""
        return s.id == session.id
        # Error                ^^ "id" is not a known member of "None"

    find(sessions, is_same)

    session = Session(id="2", name="testing")

```

<details><summary>Screenshot:</summary>
<p>

![image](https://github.com/microsoft/pyright/assets/37065184/be686c07-a46a-437f-a42b-5c50bbd46821)



</p>
</details>

**Comment by erictraut** [comment]
Pyright is working as intended here, so I don't consider this a bug. 

Your code samples involve a variable captured by an inner closure (a lambda). In the general case, a static type checker cannot assume that the captured variable will not be modified after it is captured by a closure. It has no knowledge of when the closure will be used (i.e. when the lambda will be called). The type checker therefore must generally assume that the type of the captured variable within the inner scope is not narrowed.

Pyright is able to safely use the narrowed type if it can prove that there are no assignments to the captured variable after the definition of the inner function or lambda, but in some of your examples, you are writing to the captured variable after the lambda definition.

You can read more about this in [this section of pyright's documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=narrowing-for-captured-variables).

There are a couple of ways that you can modify your code so it is provably type safe. 
1. Don't assign a new value to the captured value after it is used in a lambda.
2. Create a separate variable (e.g. through a walrus operator assignment) that you then capture by the lambda.

```python
def test_2():
    """Test 2, with reassignment, shows red squiggly."""
    sessions = [Session(id="id1", name="session"), Session(id="id2", name="session")]
    session = find(sessions, lambda s: s.id == "id1")

    if (temp := session) is None:
        raise Exception("Found no string")

    find(sessions, lambda s: s.id != temp.id and s.name == "session1")

    session = Session(id="2", name="testing")
```
