### ISSUE TITLE
Type produced by a factory function considered as Unknown in some contexts

### ISSUE THREAD

**Issue by kr41** [microsoft/pyright#7224]
**Describe the bug**
Type produced by a factory function in some contexts considered as `Unknown`. The bug firstly appears about a week ago and it's still present in the latest release `1.1.350`.

**Code**
```python
from typing import assert_type


class Base:
    pass

def type_factory() -> type[Base]:
    class DynamicType(Base):
        pass

    return DynamicType

assert_type(type_factory(), type[Base])  # ok


T = type_factory()
assert_type(T, type[Base])  # ok
assert_type(T(), Base)  # ok


def func() -> T:  # error: Variable not allowed in type expression
    return T()

assert_type(func(), T)  # error: "assert_type" mismatch: expected "Base" but received "Unknown"


d: dict[str, T] = {} # error: Variable not allowed in type expression
assert_type(d, dict[str, T])  # error: "assert_type" mismatch: expected "dict[str, Base]" but received "dict[str, Unknown]"

```

**VS Code extension or command-line**
```
$ venv/bin/pyright --version
pyright 1.1.350
```

**Comment by erictraut** [comment]
Pyright's current behavior is correct. I've been tightening up its behavior to conform with the typing spec.

You are assigning a dynamic value to a variable `T` and then using that variable within a type annotation (in the return type for `func`). As the error message indicates, this isn't allowed.
