### ISSUE TITLE
pyright incorrectly adds the script directory to the module search path

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#7226]
```py
# foo/a.py
a = 1
```
```py
# foo/b.py
import a # no pyright error
```
```py
# main.py
import foo.b
```

running `python main.py` will cause the following error:
```
> python main.py
Traceback (most recent call last):
  File "C:\project\main.py", line 4, in <module>
    import foo.b
  File "C:\project\foo\b.py", line 4, in <module>
    import a  # no error
    ^^^^^^^^
ModuleNotFoundError: No module named 'a'
```

**Comment by erictraut** [comment]
Pyright is working as designed here. This isn't a bug.

Refer to [this documentation](https://microsoft.github.io/pyright/#/import-statements) for details.

**Comment by DetachHead** [comment]
@erictraut that's not related to this issue. the problem is that when running a python file as a module, the imports are not relative to the location of the file.

```py
# foo/a.py
a = 1
```
```py
# foo/b.py
import a # no pyright error
# should be `import foo.a`
```
```console
> python -m foo.b
ModuleNotFoundError: No module named 'a'
```

**Comment by DetachHead** [comment]
there should be an option to disable that behavior imo, since many projects do not intend for all of their python files to be executed as scripts like that
