### ISSUE TITLE
Unknown C++ import

### ISSUE THREAD

**Issue by kiwixz** [microsoft/pyright#723]
liblogger is C++ with bindings.

a.py: `from liblogger import loglevel`
pyright: `"loglevel" is not accessed`

b.py: `from a import Logger, loglevel`
pyright: `"loglevel" is unknown import symbolPyright (reportGeneralTypeIssues)`

pyright does not seem to produce autocomplete for `loglevel` even in the `a.py` file.

I'm running pyright 1.1.41 in vscode.

**Comment by erictraut** [comment]
If liblogger is a C++ library with no python code, then Pyright won't be able to analyze it to extract type information or symbols. You will need a type stub for the library if you want it to provide auto-completion or type checking of any sort.

**Comment by kiwixz** [comment]
Would it be possible to add a fallback to extract symbols (even untyped) like microsoft lsp ?

**Comment by erictraut** [comment]
No, I don't plan to add any extraction for C++ libraries. The correct solution is to create a type stub library.
