### ISSUE TITLE
Can use functions but not classes as `dataclass_transform` `field_specifiers`

### ISSUE THREAD

**Issue by bradleyharden** [microsoft/pyright#7241]
According to the `typing.dataclass_transform` [documentation](https://docs.python.org/3/library/typing.html#typing.dataclass_transform), the `field_specifiers` argument accepts a `tuple` of `Callable[..., Any]` objects. Notably, the documentation states:

> Specifies a static list of supported **classes** or functions that describe fields [emphasis mine]

The related issue #5102 notes that the such `Callable`s must return `Any`. And, indeed, I can successfully implement a `dataclass_tranform` field specifier _function_. But I can't seem to find any way to implement a field specifier _class_ without an error.

The following example contains my attempt.

```python
from typing import Any, dataclass_transform

class MetaField(type):
    def __call__(cls, *args, **kwargs) -> Any:
        super().__call__(*args, **kwargs)

class Field(metaclass=MetaField):
    def __init__(self, *args, **kwargs):
        return

def field(*args, **kwargs) -> Any:
    Field(*args, **kwargs)

@dataclass_transform(field_specifiers=(field, Field))
class Base:
    pass

class Test(Base):
    a: int = field(init=False)
    b: int = Field(init=True)

def test():
    x = Test()
```

A few notes on this example:
- Pylance gives an error for `Test.b`, claiming:

> Expression of type "Field" cannot be assigned to declared type "int"

- Adding the metaclass `__call__` implementation seems to have no effect on the way Pyright interprets the expression `Field()`.
    - Am I misunderstanding which `__call__` method is relevant here? I don't think so, because adding an exception to that implementation of `__call__` does indeed throw when `Field()` is called.

- Despite the complaint that `Field` is incompatible with `int`, Pyright _does_ seem to respect the `init=True` argument to `Field`. When `Field` is given as a field specifier, the `x = Test()` line gives an error of

> Argument missing for parameter "b"

But if I remove `Field` as a field specifier, that error goes away.

Am I misunderstanding the documentation or the design intent of `dataclass_transform`? Or is my implementation wrong somehow? Or is this a genuine bug?

I'm running Pyright using the standard VS Code extensions for Python on Ubuntu 22.04.

**Comment by erictraut** [comment]
Practically speaking, you need to use a function, not a class. That's the precedent set by the stdlib `dataclass`, and that's what all Python type checkers assume at this point.

**Comment by bradleyharden** [comment]
I guess that's fair. But the documentation is confusing in that case. Where would I go to seek clarification or correction of the documentation?

**Comment by debonte** [comment]
> Where would I go to seek clarification or correction of the documentation?

The docs source is here: https://github.com/python/cpython/blob/d4d5bae1471788b345155e8e93a2fe4ab92d09dc/Doc/library/typing.rst#L2724

> But the documentation is confusing in that case

As is the PEP:

> `field_specifiers` specifies a static list of supported classes that describe fields. Some libraries also supply functions to allocate instances of field specifiers, and those functions may also be specified in this tuple. If not specified, `field_specifiers` will default to an empty tuple (no field specifiers supported). The standard dataclass behavior supports only one type of field specifier called Field plus a helper function (`field`) that instantiates this class, so if we were describing the stdlib dataclass behavior, we would provide the tuple argument `(dataclasses.Field, dataclasses.field)`.

**Comment by bradleyharden** [comment]
Doesn't that quote suggest the current implementation of type checkers is wrong/incomplete?

**Comment by erictraut** [comment]
`dataclass_transform` is designed to match the semantics and type-checking behavior of `dataclass`. This is how `dataclass` works, so `dataclass_transform` should work likewise. I think type checkers are implemented correctly. The current documentation is admittedly misleading and should be fixed.

**Comment by bradleyharden** [comment]
It looks like pyright passes the [dataclasses_transform_class](https://github.com/python/typing/blob/main/conformance/tests/dataclasses_transform_class.py) test as part of the [Python Type System Conformance Tests](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html), which seems to test this exact case. I tried my original snippet again, and I no longer get the error

> Expression of type "Field" cannot be assigned to declared type "int"

I suppose this issue has been fixed now. Would it make sense to change the labels and close this as fixed rather than not planned?
