### ISSUE TITLE
Consider supporting "PYTHONCASEOK"

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#725]
**Is your feature request related to a problem? Please describe.**
supporting PEP 235 (https://www.python.org/dev/peps/pep-0235/) on import errors.

**Describe the solution you'd like**
looking at code, it looks like implementation always try to preserve casing from file system and let file system decides case sensitive-ness when finding modules (file name, folder name). if pyright supports, PEP 235, it probably need some way to treat case sensitive file system like case insensitive so it can find import name with different casing.

**Comment by heejaechang** [comment]
opened a request based on some question from @MikhailArkhipov

**Comment by erictraut** [comment]
If I'm reading PEP 235 correctly, the current behavior of Pyright matches that of the Python interpreter by default. I think that is the correct and preferred behavior. My opinion is that we should not add support the non-standard handling provided by PYTHONCASEOK.

**Comment by heejaechang** [comment]
tagging @MikhailArkhipov

**Comment by jakebailey** [comment]
I would advocate against working on this variable until it's definitely needed; it's a bit of plumbing and setup to get this variable piped down from the places that can provide it, especially with the oddity in how a client like VS Code obtains its environment variables.

**Comment by MikhailArkhipov** [comment]
Sure as long as we are on the same page.
