### ISSUE TITLE
reportDefaultArgumentType

### ISSUE THREAD

**Issue by MichalMachura** [microsoft/pyright#7255]
Problem:

Configuration option 'reportArgumentType' treats the same cases of default argument and a function call argument assignment with types mismatch. 

<img width="947" alt="obraz" src="https://github.com/microsoft/pyright/assets/44579524/74a05928-515b-4d05-913a-5e56e242c80b">

Solution:

Additional configuration option: `reportDefaultArgumentType`

**Comment by erictraut** [comment]
Thanks for the suggestion. I'm not convinced there's a compelling need to split out these two cases into separate diagnostic checks. It's something I'm willing to revisit in the future if enough other pyright users have a similar request. For now, I'm going to close this.
