### ISSUE TITLE
Add pythonpath to pyright configuration

### ISSUE THREAD

**Issue by b-chu** [microsoft/pyright#7264]
If you have a question about a behavior that you’re seeing in pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**
It's cleaner to specify pyright options in the configuration settings rather than through command line.
https://github.com/microsoft/pyright/blob/main/docs/configuration.md

**Describe the solution you’d like**
Allow pythonpath to be specified in pyproject.toml (similarly to venv) rather than solely in the command line.

**Comment by erictraut** [comment]
I don't think it makes sense to support `pythonpath` in the config file. The config file is meant to be checked in and shared among all developers on a project, so it shouldn't contain any absolute paths. The `pythonpath` will typically need to be an absolute path and will necessarily be different for each developer.

**Comment by b-chu** [comment]
Can you pass an env var to pythonpath? More generally, how can developers specify their own virtual environments (which may be different for each developer) for pyright? Especially in the context of pre-commit

**Comment by erictraut** [comment]
Pyright uses the configured python environment, so developers can simply activate the appropriate virtual environment before running pyright, and it will pick up the correct python interpreter. It does this by simply shell executing "python3" or "python" (depending on the platform).

**Comment by b-chu** [comment]
Pre-commit uses the system python environment instead of the selected python environment though (even if you activate the virtual environment before running pre-commit). How would you have pre-commit specify the correct environment in that scenario?

**Comment by b-chu** [comment]
Hi, is there any update on this?

**Comment by erictraut** [comment]
This issue is closed, which means we currently have no plans to address it.

**Comment by b-chu** [comment]
I mean with regards to the question posed above. How does the integration with pre-commit work?
```
Pre-commit uses the system python environment instead of the selected python environment though (even if you activate the virtual environment before running pre-commit). How would you have pre-commit specify the correct environment in that scenario?
```
