### ISSUE TITLE
Incorrect TypeVar inference when using strictParameterNoneValue 

### ISSUE THREAD

**Issue by dislocated-su** [microsoft/pyright#7269]
**Describe the bug**
When using `strictParameterNoneValue = false`, the type of optional parameters is implicitly inferred as Optional, however when the parameter is a unconstrained `TypeVar` that behavior doesn't seem desirable.

When using  `strictParameterNoneValue = true` (the default), `None` is treated as member of `TypeVar` and everything works as intended.

**Code or Screenshots**

```python
# pyright: strictParameterNoneValue = false

from typing import TypeVar

T = TypeVar("T")

def foo(name: str, default: T = None) -> str | T:
    bar: dict[str, str] = {}
    return bar.get(name, default)  # reportReturnType "str | T@foo | None" is incompatible with  "str | T@foo"

baz = foo("") # inferred type: str (i'd expect it to be str | None)
qux = foo("", 123) # inferred type: str | int
```

**VS Code extension or command-line**

Comes up in Pylance and the command line tool
VS Code 1.86.1
Pylance v2024.2.2

Pyright 1.1.350

**Comment by erictraut** [comment]
Pyright is working as intended here. I agree that these two features don't work well together. I recommend moving away from `strictParamterNoneValue` set to `false`. This mode is supported only for backward compatibility with old code bases. It should not be used for any new code. For that reason, I don't intend to add any further special-casing to support `strictParameterNoneValue` set to `false.
