### ISSUE TITLE
`list` as a default argument for a parameter of type `Callable[[list[T]], C]` results in `list[Unknown]` when called

### ISSUE THREAD

**Issue by InSyncWithFoo** [microsoft/pyright#7276]
**Reproducible minimal example**

From [this StackOverflow question](https://stackoverflow.com/q/78001004) ([playground link](https://pyright-play.net/?strict=true&code=GYJw9gtgBAxmA28CmMAuBLMA7AzgOgEMAjGKdCABzBFSgGEDFjkBYAKFEigBMDUCY8AjhxIcZStVq9%2Bg4TnadoqAJ4V0WAOYSqNKAHEkWJCHQwANFAAqapADUCIduytQAvNdsOQACgDkVn4AlOx07p4U9o7%2BdMHObAACMgJCIuxyIlAAogAeBJTIPobGpjAA2lYAukEAXOxQDTx8BDVQ8Og4qBWV9Y29DdxIwLAIyGg%2BovDAlnCIKKjUrQxMRMhlZe2d3ZWWdJXhm6hBUAC0AHz0dWyNN1AgSKgAriBYI3No1BNIU3jJIWzsJB5ApIcK5fIUQplACMlgATNV4vcAG5IRgAfVUkR8QIhyDwszGqB8QWOUAAxFAKCpTJoABa0NwXQ5lACqWAA1lgwAB3LA9NhAA)):

```py
from collections.abc import Callable
from dataclasses import dataclass
from typing import Generic, TypeVar

T = TypeVar('T')
C = TypeVar('C')

@dataclass
class Example(Generic[T]):
    data: list[T]
    
    def collect(self, collector: Callable[[list[T]], C] = list) -> C:
        return collector(self.data)
```

```py
example = Example([1, 2])

reveal_type(example.collect())  # pyright => list[Unknown]
```

The type of `example.collect(list)` is correctly inferred as `list[int]`, however.

`list` alone should have been assignable to `Callable[[list[T]], C]` and the return type should have been `list[int]`.

**Comment by erictraut** [comment]
Pyright is working as designed here. You are assigning `list`, which is interpreted as `list[Any]` in this context. If your intent is for the default argument to be constrained to the type `list[T]`, then you should specify that.

```python
    def collect(self, collector: Callable[[list[T]], C] = list[T]) -> C:
        return collector(self.data)
```
