### ISSUE TITLE
`reportPrivateUsage` false positive when accessing protected member from supertype within a nested class

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#7281]
```py
class Foo:
    def _foo(self):
        ...

class Bar(Foo):

    def bar(self):
        class Baz:
            @staticmethod
            def foo():
                self._foo() # error: "_foo" is protected and used outside of the class in which it is declared
```
[playground](https://pyright-play.net/?strict=true&deprecateTypingAliases=true&enableExperimentalFeatures=true&reportCallInDefaultInitializer=true&reportImplicitOverride=true&reportImplicitStringConcatenation=true&reportPropertyTypeMismatch=true&reportMissingSuperCall=true&reportShadowedImports=true&reportUninitializedInstanceVariable=true&reportUnnecessaryTypeIgnoreComment=true&reportUnusedCallResult=true&code=MYGwhgzhAEBiD28BcBYAUNT0AmBTAZtAPr6IAUEuI%2BAlKhlowHQvrqiQwBCYATmQnh02DTHkIAjPhSq16jRhyjQeAL3kLNAAQgAXMLoCWwALa5dAC3jZ0mzeOil4ZYaLubK1JiXI1oAYmhcXl54XiRoACIfeEjoQxgAB1DdXGBU7GgwADtMgFdKTPg83QhDPGh4QktcaCUYQ2zoAHcLYwt43XiYPA5eXBs3Rn7dPN4mtRcgA)

since `Baz.foo` is a static method, the `self` refers to the `Bar` class, and since `Baz` is defined inside the `Bar` class, it should be able to access its protected members.

**Comment by erictraut** [comment]
Pyright is working as designed here. This isn't a bug.
