### ISSUE TITLE
Implement support for TypeIs (PEP 742)

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#7293]
It would be useful for pyright to add support for the proposed TypeIs special form from [PEP 742](https://peps.python.org/pep-0742/). I am happy to contribute the implementation myself. I know pyright previously had support for `StrictTypeGuard`, so it may just be a matter of bringing back that support and renaming the special form.

**Comment by erictraut** [comment]
Yeah, this should be easy to bring back. 

If you haven't already done so, it would be useful if you could add `TypeIs` to `typing_extensions.pyi`.

**Comment by erictraut** [comment]
This will be included in the next release.

**Comment by JelleZijlstra** [comment]
Thank you! Yes, the runtime support will be in the next release of typing-extensions (expected in a week) and I already added it to typeshed.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.351, which I just published.
