### ISSUE TITLE
Type hinting class attribute with a class that has a metaclass doesn't work in some cases

### ISSUE THREAD

**Issue by oskarkk** [microsoft/pyright#7311]
I'm using a class from a library, that has some metaclass that causes issues with type hinting. Here's the code from the library, where I removed everything that's not relevant:

```python
def with_metaclass(meta, *bases):
    class metaclass(meta):
        __call__ = type.__call__
        __init__ = type.__init__

        def __new__(cls, name, this_bases, d):
            if this_bases is None:
                return type.__new__(cls, name, (), d)
            return meta(name, bases, d)

    return metaclass("temporary_class", None, {})


def removed_class_attributes_metaclass():
    class Meta(type):
        _base_cls_name = None

        def __new__(meta, cls_name, bases, dct):
            return super(Meta, meta).__new__(meta, cls_name, bases, dct)

    return with_metaclass(Meta)


class Foo(removed_class_attributes_metaclass()):
    pass
```

Then I have a class where I want to use `Foo` in type hint:

```python
class Bar:
    # case 1
    foo: Foo
    
    # case 2
    foo: Foo = Foo()

    # case 3
    foo = Foo()

    # case 4
    @property
    def foo(self) -> Foo:
        return Foo()

    # case 5
    @property
    def foo(self) -> Foo: ...
```

In cases 1-3, type of `Bar().foo` is `Unknown`, in cases 4-5 it's correctly `Foo`.

Version:
Pylance async client (2024.2.102) started with python extension (2024.1.10511008)
Pylance language server 2024.2.102 (pyright version 1.1.351, commit 87171fbf)

I think the problem started appearing in one of the versions over the last couple of months. In 2023, I added many type hints to my code in the form `foo: Foo`, using various classes with the same metaclass as `Foo`, and I remember it working correctly.

**Comment by erictraut** [comment]
Pyright is working as designed here, so I don't consider this a bug.

You're dynamically creating classes here. This won't work with static type analysis tools like pyright or mypy. They need to be able to understand class hierarchies and cannot handle such dynamic code.

You can work around this limitation by adding a return type annotation to `removed_class_attributes_metaclass` of `type[object]`. Without this, the inferred return type is `type[Any]` which will result in unknowns in some cases.

**Comment by oskarkk** [comment]
Why in this case typing it as a property works, but a normal type hint or just assignment results in unknown? Also when I do `foo = Foo()` on module level, as a normal variable, `foo` has type `Foo`, not Unknown.

Thanks for `type[object]` suggestion, it works.
