### ISSUE TITLE
Introduce a way to run in CI with stability across releases

### ISSUE THREAD

**Issue by lengau** [microsoft/pyright#7315]
**Is your feature request related to a problem? Please describe.**
While Pyright is fantastic to use as an LSP, its usage in CI can be difficult given that patch releases will change the way that rules work or even the classifications of rules. This has several side-effects:

1. New errors popping up suddenly with an updated patch version
2. `pyright: ignore[rule]` suddenly being ignored because the same problem is attached to a different rule name
3. Checks being moved around can mean that things that were previously configured as warnings are now errors

The end result is that using pyright in CI, especially for bugfix branches of applications/libraries, either results in commits/PRs that are purely "to satisfy pyright" or requires us to freeze at a specific pyright version, which will then often disagree with the version being used as a language server.

**Describe the solution you’d like**

A CLI flag or environment variable that can be used to limit pyright's errors (or downgrade certain errors to warnings) in CI for backwards compatibility. These rules don't have to live indefinitely, but providing a few months of these being warnings before upgrading them to errors in this mode would ease things.

**Comment by erictraut** [comment]
What you're proposing isn't feasible in my opinion. It would greatly increase the maintenance costs of pyright and slow progress.

If you don't want to deal with changes on a per-release basis, I recommend that you pin the version of pyright in your CI scripts and then pick some cadence for upgrading.
