### ISSUE TITLE
pyright emits warnings from ignored paths

### ISSUE THREAD

**Issue by ShineyDev** [microsoft/pyright#7325]
**Describe the bug**
Despite the description [here](https://github.com/microsoft/pyright/blob/main/docs/configuration.md?plain=1#L15), pyright is emitting unnecessary type-ignore warnings from an ignored path.

**Code or Screenshots**
`a: int = 0  # type: ignore` incorrectly emits a warning
`a: int: ""` is correctly silent

**VS Code extension or command-line**
Using pyright 1.1.350.

**Comment by erictraut** [comment]
Can you provide more details? Are you saying that you have specified a file or directory in the "ignore" configuration setting and you have enabled the `reportUnnecessaryTypeIgnoreComment` diagnostic check?

**Comment by erictraut** [comment]
I was able to repro the problem. I agree that "ignore" should take precedence over unnecessary type ignore comments. I've updated the logic accordingly. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.352, which I just published.
