### ISSUE TITLE
Multiple redefinitions of the same variable seems break pyright

### ISSUE THREAD

**Issue by AlexanderPodorov** [microsoft/pyright#7327]
**Describe the bug**
See example code.
Please note that type of "a" is not changing during re-assignments.

```python
# copy the line below 64 times
a = 1  # 1st
a = 1  # 2nd
...
a = 1  # 64th, work fine, but 65th ...
a = 1  # causes all 65 lines to report "Type of "a" is unknown"
```

**VS Code extension or command-line**
Pylance v2024.2.103 (pre-release), Pyright 1.1.351.

**Comment by erictraut** [comment]
Yes, this is intended. For performance reasons, pyright does not attempt to perform type inference for variables with an undeclared type if there are more than 64 assignments. This leads to long analysis times in untyped code, and this has a significant negative impact on language server features like completion suggestions. 

You can avoid this by declaring the type of the variable (i.e. adding an `a: int` statement at the top of the function).
