### ISSUE TITLE
Allow parsing implicit kwargs overloads

### ISSUE THREAD

**Issue by Archmonger** [microsoft/pyright#7329]
**Is your feature request related to a problem? Please describe.**
Right now, Python doesn't support type hinting for any higher order callables with new kwargs. `Concatenate` notably exists, but only supports overloading `args`.

This is a frequent limitation to type hinting our APIs over at [`reactive-python/reactpy`](https://github.com/reactive-python/reactpy).

**Describe the solution you’d like**
This could be resolved by allowing pyright to parse implicit (untyped) kwargs overloads in situations like this:

```python
def component(function: Callable[P, T]):
    def constructor(
        *args: P.args, key: Any | None = None, **kwargs: P.kwargs
    ) -> Component:
        return Component( ... )

    return constructor
```

**Comment by erictraut** [comment]
The feature you're proposing would require a change to the typing spec — and probably a PEP. If you're interested in spearheading such a change, the [Python typing forum](https://discuss.python.org/c/typing/32) is the right place to start that discussion.
