### ISSUE TITLE
PyInstaller .spec file injected values get linted incorrectly

### ISSUE THREAD

**Issue by DragonRulerX** [microsoft/pyright#7351]
Hello,

I'm running Python 3.12 in a Windows 11 Pro environment.

**Is your feature request related to a problem? Please describe.**
I use PyInstaller to create a distributable executable.
PyInstaller leverages ".spec" files that have special values/functions injected into it at runtime like:
- Analysis
- PYZ
- EXE
- SPECPATH
- etc

Refs:
- https://pyinstaller.org/en/v3.2.1/runtime-information.html
- https://pyinstaller.org/en/v3.2.1/spec-files.html

I've noticed that pyright is able to lint these files (because they are python files), but I don't see a way to teach pyright about these injected values. I've had to ignore the file for now which is not ideal.

**Describe the solution you’d like**
Unless there is any advice on how to fix this - I'd like to either have these values known to pyright or a way to teach pyright about them.

**Comment by erictraut** [comment]
First, pyright is a type checker, not a linter. If you're interested in linting, take a look at pylint, ruff, or other linters.

Second, pyright is a standards-based type checker that follows the Python type spec. It has no specialized knowledge of any third-party libraries. It's unlikely that we'd ever add specialized support for pyinstaller. The question is whether there are existing mechanisms in pyright that might support your use case.

I don't know much about pyinstaller or the mechanism by which it "injects" symbols into the module namespace. It's possible that [this mechanism](https://microsoft.github.io/pyright/#/builtins) might serve your needs.
