### ISSUE TITLE
Pyright shows `datetime.utcnow` and `datetime.utcfromtimestamp` as deprecated for python versions lower than 3.12

### ISSUE THREAD

**Issue by Popkornium18** [microsoft/pyright#7353]
`datetime.utcnow` and `datetime.utcfromtimestamp` [were deprecated in 3.12](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow). Pyright flags these functions as deprecated on python versions lower than 3.12, suddenly breaking CI pipelines without any code changes or python version changes.

```
printf "from datetime import datetime\ndatetime.utcnow()\n" > file.py
pyright --pythonversion 3.10 file.py

.../file.py
  .../file.py:2:10 - error: The method "utcnow" in class "datetime" is deprecated
    Use timezone-aware objects to represent datetimes in UTC; e.g. by calling .now(datetime.UTC) (reportDeprecated)
1 error, 0 warnings, 0 informations
```

Pyright version: 1.1.351

**Comment by Viicos** [comment]
You can find the reason here: https://github.com/python/typeshed/pull/11009#discussion_r1388825585
