### ISSUE TITLE
Place JSON output on single line when watching

### ISSUE THREAD

**Issue by mrcljx** [microsoft/pyright#7368]
**Is your feature request related to a problem? Please describe.**
I want to parse the output of Pyright that runs in watch mode.

Currently quite a bit of cruft is required to find out where a new JSON message begins (if I don't want to make assumptions about the format or timing). 

**Describe the solution you’d like**
By putting the JSON on a single line (i.e. not pretty printing it), the output becomes a line-delimited JSON stream (aka LDJSON) which is easy to parse (a bunch of libraries to consume it exist too).

**Comment by erictraut** [comment]
JSON output is primarily meant to be parsed by tools, not by humans. Tools should have no problem parsing the JSON output regardless of whether it includes extra carriage returns, so I don't understand what benefit there is in removing the carriage returns and other formatting. I guess I don't follow what you mean by "quite a bit of cruft is required...".

My hesitation here is that I don't know if other pyright users are currently using JSON output with the watch feature. It's an unusual combination, so the answer might be no. But if they are, they probably would not be in favor of this change.

**Comment by erictraut** [comment]
I'm not convinced this change is a good idea, so I'm going to close.

**Comment by mrcljx** [comment]
When watch mode is combined with JSON output mode, the program keeps running and each time a check completes, a multiline JSON object is printed. Hence stdout effectively contains a stream of JSON objects. 

However parsing that byte stream back into a stream of objects is rather complicated: finding out where a new object starts requires parsing bytes until a root `}` is found and that tends to require a parser that can consume an object and return a cursor so that then the next object can be consumed. Most standards libraries don’t have such a parser: they consume whole objects and throw on additional bytes. The „cruft“ I meant was „writing your own JSON parser that can handle this“. 

By adopting https://jsonlines.org/ in that scenario (watch and json output) each line would be guaranteed to contain one whole JSON object. This allows combining a line reader with a JSON reader to parse the byte stream back into a stream of JSON objects.

But I understand the reservation.
