### ISSUE TITLE
`TypedDict` incompatible with `dict[str, Any]`

### ISSUE THREAD

**Issue by rossmacarthur** [microsoft/pyright#7385]
**Describe the bug**

Something typed with a `TypedDict` is not compatible with `dict[str, Any]`. Is there any reason why it can't be? `TypedDict` will always have string keys.

**Code or Screenshots**

```python
from typing import Any, TypedDict

class Person(TypedDict):
    name: str
    age: int

def takes_dict_any(d: dict[str, Any]) -> None: ...

person: Person = {"name": "John", "age": 21}
takes_dict_any(person)
"""
13:16 - error: Argument of type "Person" cannot be assigned to parameter "d" of type "dict[str, Any]" in function "takes_dict_any"
    "Person" is incompatible with "dict[str, Any]" (reportArgumentType)
"""
```

If your code relies on symbols that are imported from a third-party library, include the associated import statements and specify which versions of those libraries you have installed.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool? Which version?
```
❯ pyright --version
pyright 1.1.352
```

**Comment by erictraut** [comment]
This isn't allowed by the typing spec for reasons that are described in the original [PEP 589](https://peps.python.org/pep-0589/#type-consistency), which introduced TypedDict.

For reference, you can find the official Python typing spec [here](https://typing.readthedocs.io/en/latest/source/reference.html). And the [Python typing forum](https://discuss.python.org/c/typing/32) is a good place to get answers to questions about the spec.

You may also be interested in draft [PEP 728](https://peps.python.org/pep-0728/) which provides a way to define a "closed" TypedDict which is (under certain specific circumstances) type compatible with a `dict[str, T]`. The most recent version of pyright (1.1.352) has provisional support for this draft PEP if you want to try it out. You need to set `enableExperimentalFeatures` to true in your config to enable it.
