### ISSUE TITLE
Incorrectly Reports Missing Library `dotenv`

### ISSUE THREAD

**Issue by brian-comply0** [microsoft/pyright#7397]
**Describe the bug**
Pyright in VS Code is reporting that `import dotenv` could not be resolved even though the library is installed via `pip install python-dotenv` and the code executes correctly.

This is my Python code. Not something I've downloaded. I've used the `dotenv` library for a few months to read a `.env` file from the file system. This continues to happen correctly, consistently honoring changes to the .env file when appropriate.  

Even though the library is installed and the code runs as expected, Pyright is reporting: 
**Import "dotenv" could not be resolved Pylance ([reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports))**

**Code or Screenshots**
This happens with either my original code or a simplified version for demonstrating this error:
- Original: `from dotenv import load_dotenv `
- Simplified: `import dotenv`

![Screenshot 2024-03-04 142140](https://github.com/microsoft/pyright/assets/106116211/0d3fa5d0-0404-439b-84cd-2be66a4dacf9)

**VS Code extension or command-line**
Running as a VS Code extension. 

Pylance version 2024.2.2 
- running inside extension WSL version 0.86.0
  - the WSL extension is running inside VS Code Version 1.87.0

Python 3.10.12
- installed within Ubuntu 22.04.03 LTS 
  - running in WSL2 
    - on a Windows 11 Laptop

**Additional Notes**
This is the only library I am using where the Python `import` name does not match the `pip install` name. Even though the statement in Python is `import dotenv`, the pip install name is `python-dotenv`. I suspect this name mismatch is the related to the incorrect behavior.

**Comment by erictraut** [comment]
I'm not able to repro the problem as reported.

This is almost certainly not a bug in pyright, but rather an issue with your configuration or your Python environment. Please refer to [this documentation](https://microsoft.github.io/pyright/#/import-resolution). If that doesn't help you resolve the issue, try creating a fresh virtual environment and a fresh project with a default pyright configuration. From that clean point, you should be able to do a comparison to see what's different about your current configuration and environment.
