### ISSUE TITLE
Dictionary KeyError when using try/except with a decorator 

### ISSUE THREAD

**Issue by TimekillerTK** [microsoft/pyright#7399]
**Describe the bug**

Decorator function with a try/except for `KeyError` results in a Pyright key error when trying to access a dictionary key which is annotated with `NotRequired`. 

This does not happen when you have a try/except block inserted into the code (`undecorated_function`) directly.

```
Could not access item in TypedDict
  "key" is not a required key in "ExampleDictionary", so access may result in runtime exceptionPylance[reportTypedDictNotRequiredAccess](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportTypedDictNotRequiredAccess)
```

**Code or Screenshots**

```python
from typing import Callable, ParamSpec, TypedDict, TypeVar

from typing_extensions import NotRequired

T = TypeVar("T")
P = ParamSpec("P")


class ExampleDictionary(TypedDict):
    key: NotRequired[str]


def keyerror_handler(func: Callable[P, T]) -> Callable[P, T]:
    def inner_function(*args: P.args, **kwargs: P.kwargs) -> T:
        try:
            return func(*args, **kwargs)
        except KeyError as err:
            raise SystemExit(1) from err

    return inner_function


@keyerror_handler
def decorated_function(dictionary: ExampleDictionary) -> str:
    return dictionary["key"] # <- Error


def undecorated_function(dictionary: ExampleDictionary) -> str:
    try:
        return dictionary["key"]
    except KeyError as err:
        raise SystemExit(1) from err
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool? Which version?

Using Pylance with VS Code:

```
2024-03-05 09:53:44.019 [info] [Info  - 09:53:44] (65114) Pylance language server 2024.2.3 (pyright version 1.1.348, commit cfb1de0c) starting
```

**Comment by erictraut** [comment]
Pyright's behavior here is correct from a static typing perspective.

You appear to be using an exception handler here for normal (non-exceptional) control flow. If this is a normal condition that you expect in your code, you should switch from an exception handler to simple conditional logic (like `if "key" in dictionary`).

If you don't want pyright to statically detect unguarded accesses to not-required TypedDict fields, you should not enable the `reportTypedDictNotRequiredAccess` check.
