### ISSUE TITLE
Constructors only return `() -> None` instead of function signature and docstring

### ISSUE THREAD

**Issue by joelostblom** [microsoft/pyright#7405]
**Describe the bug**
Since Pyright 1.1.335, constructors don't show the signature or docstring in the pop up. Instead they just show `() -> None` as in this example:

![image](https://github.com/microsoft/pyright/assets/4560057/cad69616-66d8-4c99-bfac-4bbb9fcb76ec)

**VS Code extension or command-line**
This is in VS Code and [seems to have been an issue since Pyright 1.1.335](https://github.com/microsoft/pylance-release/issues/5223#issuecomment-1974962124)

**Comment by erictraut** [comment]
This isn't a type-checking issue. It's a language server issue, so I'm going to ask that it be transferred to the pylance team for diagnosis and triage.

@debonte, @rchiodo

**Comment by debonte** [comment]
I bisected this to Pyright 1.1.335. There were a couple of signature help changes in that [changelog](https://github.com/microsoft/pyright/releases/tag/1.1.335), but I didn't track it down to a particular commit. I'll do that now.

**Comment by debonte** [comment]
It was regressed by https://github.com/microsoft/pyright/commit/3741108c3

**Comment by erictraut** [comment]
This is included in pyright 1.1.353, which I just published.

**Comment by joelostblom** [comment]
Thank you!
