### ISSUE TITLE
__package__ is not typed correctly

### ISSUE THREAD

**Issue by svenberkvens** [microsoft/pyright#7408]
**Describe the bug**
The module global variable `__package__` is typed as `str`, but it can be `None` too.

**Code or Screenshots**

Write a file `/tmp/test.py`:
```python
print(repr(__package__))
```

and run:

```shell
$ python3 /tmp/test.py
None
```

Caught this incorrect typing in a third party module:

```python
...
__package__ = None
...
```

Pyright CLI says:

```
error: Expression of type "None" cannot be assigned to declared type "str"
    "None" is incompatible with "str" (reportAssignmentType)
```

**VS Code extension or command-line**
The error appears in the CLI and in the LSP when using Neovim. Pyright version 1.1.352.

**Comment by erictraut** [comment]
This is included in pyright 1.1.353, which I just published.

**Comment by alicederyn** [comment]
This has broken the common idiom of doing `importlib.resources.files(__package__)` (e.g as suggested [here](https://dev.to/bowmanjd/easily-load-non-python-data-files-from-a-python-package-2e8g)). I tried doing `assert __package__` at the top of my module, but pyright does not appear to be updating its assumption that it may be None; it needs to be asserted in every function using `__package__`.

Was there any evidence this change would catch sufficient real-world issues to justify the impact it will have on legitimate code?

**Comment by erictraut** [comment]
`assert __package__` will narrow the type. As with all type narrowing, it applies on to the execution scope in which the `assert` occurs. So if your `assert __package__` is in the module (global) scope, the narrowing will not apply to other function scopes. You'd need to repeat the assertion within a function if you want the type to be narrowed in that context.

**Comment by alicederyn** [comment]
I appreciate this is how pyright works, but is there also a real mechanism whereby `__package__` could be non-None at module scope but None when accessed inside a function?
