### ISSUE TITLE
Making `"analyzeUnannotatedFunctions": false` less verbose

### ISSUE THREAD

**Issue by Avasam** [microsoft/pyright#7415]
**Is your feature request related to a problem? Please describe.**
I am trying to gradually introduce type-checking into a big untyped project. For that reason I use `"analyzeUnannotatedFunctions": false` , but it results in hundreds (763) of `information: Analysis of function "..." is skipped because it is unannotated` that would be added to the job logs every run. Which makes validating existing (and future) annotations with pyright a harder sell.

**Describe the solution you’d like**
I'd like a way to make `"analyzeUnannotatedFunctions": false` less verbose or to prevent `information` level from being printed.
Maybe having a diagnostic code with that message could allow silencing it.

**Comment by erictraut** [comment]
Setting `analyzeUnannotatedFunctions` to false is very uncommon, so I don't know if it makes sense to invest in a way to make it easier to control the output of these outputs. It's something I'd consider in the future if we receive signal from more pyright users that this is desired, but I'm going to close it for now.

In the meantime, if you're using pyright within an editor like VS Code, you can filter out an "information" diagnostics. If you're using pyright from the command line, you can use the JSON output option and write a several-line script to filter out any "information" diagnostics.

Incidentally, I wouldn't recommend using the `analyzeUnannotatedFunctions` feature for gradually introducing typing. Pyright is quite good at performing analysis of unannotated functions, so this approach probably buys you relatively little. It might be easier to enable analysis for all functions but selectively disable specific diagnostic rules until you're ready to tackle that class of type violation.
