### ISSUE TITLE
Pylance throws wrong "unnecessary comparison" error

### ISSUE THREAD

**Issue by NathanAP** [microsoft/pyright#7420]
## Context

I'm in strict mode getting an `Unecessary Comparion` error. 

In my example, I have a variable that tries to assign a non existant key from a dict, which throws an error. In this case, the value of `test` will be `1` and not `123` but Pylance still throws an `unnecessary comparison` error in `except` session.

![image](https://github.com/microsoft/pylance-release/assets/12821171/016aff83-cbdd-42c8-a4db-4456acbaf096)
Note: `test2` error is because its not being used, sorry about it.

As you can see in this image, test assumes its value before the error is thrown:
![image](https://github.com/microsoft/pylance-release/assets/12821171/7bfbd726-5b25-4d06-a4d4-2952f4f405d3)

## Expected behavior

No errors.

## Actual behavior

Pylance throws "unnecessary comparison" error.

**Comment by erictraut** [comment]
Please include a minimal, self-contained repro with code in text form. Debugging issues from partial screen shots isn't really possible.

**Comment by NathanAP** [comment]
Well, I can just add the same code I showed in my example anywhere with Pylance in strict mode:

```python
def test():
   dict_value: Dict[str, int] = { "a": 1 }
   foo: int = 0
   try:
      foo = dict_value["a"]
      bar: int = dict_value["b"] # raises KeyError
   except Exception:
      print(foo) # 1
      if foo is None: # Pylance shows "Unnecessary comparison"
         # does stuff
```

In this scenario its obvious that it will never be `None`, but in my case, I have a dynamic `dict` being returned by a LLM. Something close to this:

```python
result = call_llm() # lets say it resolves into something like: { "error": True }

bot_answer = "Hello!"
bot_articles = "These are my suggestions:"
try: 
   bot_answer += result["answer"]
   bot_articles += result["suggestions"]["articles"] # raise exception
except Exception:
   if bot_answer is None: # Pylance reportUnnecessaryComparison
      bot_answer = "Something went wrong."
```

**Comment by erictraut** [comment]
You have not provided a self-contained, minimal code example as requested. The first example is invalid code, and the second example contains a method `call_llm` that is not defined. I can't tell what type that function claims to return. I'm guessing that it's defined to return a `dict[str, str]` or something like that. If that's the case, then all values in the `dict` will evaluate to type `str`.

It's unlikely that this is a bug in pyright. It's almost definitely user error or an error in the return type annotation for `call_llm`, so I'm going to close the issue.

If you have additional questions, feel free to post here. If you think that you have evidence that it's actually a bug in pyright, I'm willing to re-open.
