### ISSUE TITLE
Right way to type hint with `@overload` in `typeCheckingMode = "strict"`

### ISSUE THREAD

**Issue by wangkev** [microsoft/pyright#7429]
With `typeCheckingMode = "strict"`, this snippet

```python
from typing import overload

@overload
def add(x: float, y: float) -> float:
    ...
@overload
def add(x: str, y: str) -> str:
    ...
def add(x: str | float, y: str | float) -> str | float:
    return x + y
```

raises the following error:

```
Operator "+" not supported for types "str | float" and "str | float"
  Operator "+" not supported for types "str" and "float" when expected type is "str | float"
  Operator "+" not supported for types "float" and "str" when expected type is "str | float"  (reportOperatorIssue)
```

What is the correct way to implement type hints for the implementation function in strict mode? In standard mode, you can omit type hinting the implementation function, but strict mode complains if you do not add type hints to the implementation function.

**Comment by erictraut** [comment]
Pyright is behaving correctly here, so this isn't a bug.

If you have general questions about how to use the Python static type system, feel free to post to the [pyright discussion forum](https://github.com/microsoft/pyright/discussions) or the [Python discussion forum](https://discuss.python.org/c/typing/32).

Your question is really about how to write a polymorphic function in python that is type safe (and therefore validates that its input parameters do not violate type safety). Here's one way to do this:

```python
def add(x: str | float, y: str | float) -> str | float:
    if isinstance(x, str):
        assert isinstance(y, str)
        return x + y
    
    assert isinstance(y, float)
    return x + y
```

Here's an alternative solution that uses constrained TypeVars.

```python
def add[T: (str, float)](x: T, y: T) -> T:
    return x + y
```
