### ISSUE TITLE
Improving Russian translations

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pyright#7441]
@erictraut in https://github.com/microsoft/pyright/issues/7439 wrote:

> Some of the strings are translated poorly ... I've heard this from other people as well. Is there a way the pylance team could supply better translations?

I looked through the [Russian translation strings](https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/localization/package.nls.ru.json) and can confirm that a lot of them can be confusing. For example:
```
"finalNonMethod": "Функцию \"{name}\" нельзя пометить как @окончательную, так как она не является методом"
# for some reason the `@frozen` decorator name was translated here

"keyValueInSet": "Пары \"ключ-значение\" не допускаются в наборе"
# `set` is translated as `множество`, not `набор`

"overlappingOverload": "Перегрузка {obscured} для \"{name}\" никогда не будет использоваться, так как ее параметры перекрывают перегрузку {obscuredBy}"
# this is backwards from the English translation (reads as "the {obscured} overload obscures the {obscuredBy} overload")

"delTargetExpr": "Не удается удалить выражение"
# it's a bit subtle, but 'Не удается <verb>' implies that there's a temporary error or fault, like 'Unable to load this page'; vs the en-us "Expression cannot be deleted" which clearly indicates that what you're doing is wrong
```

I would like to work on this and improve these translations (I'm a native speaker). Should I make a pull request?

**Comment by erictraut** [comment]
That's great, thanks for offering. Yes, please create a pull request.

**Comment by decorator-factory** [comment]
I have a small question about terminology in error messages:
```
"formatStringNestedQuote": "Strings nested within an f-string cannot use the same quote character as the f-string prior to Python 3.12",
"formatStringUnicode": "Format string literals (f-strings) cannot be unicode",
"formatStringIllegal": "Format string literals (f-strings) require Python 3.6 or newer",
"formatStringUnterminated": "Unterminated expression in f-string; expecting \"}\"",
```
Sometimes "Format string literals (f-strings)" is used, and sometimes it's just "f-strings". Maybe it'd be better to just call them `f-strings`?

**Comment by erictraut** [comment]
Yeah, there are small inconsistencies in the error messages — a consequence of them being added piecemeal over multiple years. Use your best judgement when translating.

**Comment by debonte** [comment]
> please create a pull request.

I greatly appreciate your willingness to contribute improved Russian strings.

Currently the source of truth for our loc strings is the Microsoft loc team's repo which is not publicly accessible. If we check in loc changes in Pyright they will be overwritten the next time we get an update from the loc team.

We have an [internal issue](https://github.com/microsoft/pyrx/issues/4537) tracking the need to improve this situation. We'll need some way to merge changes from the community and from the loc team.

I'll prioritize thinking about how to best solve this. In the meantime, my suggestion would be to create a PR but to not merge it until we have a plan.

As a side note, I'm not sure why the strings we're getting from them Microsoft loc team are so poor. Perhaps because the translators are language experts but not programmers.

**Comment by decorator-factory** [comment]
Just to be clear, I didn't mean that all the translations are wrong/bad: most of the time it does convey what error is happening. But sometimes it uses terms inconsistently or uses a weird translation for a particular term

Translating technical stuff is not easy, especially if you're not an expert in the tool the strings are for :smiley_cat:

**Comment by debonte** [comment]
I think the best approach is for me to submit a bug against our loc team that includes all of your suggested changes. There is [a form](https://aka.ms/provide-feedback) where external users can submit loc feedback directly, but it will be easier for us to track the status of your changes if we file a bug directly.

In the bug I'll need to provide the string id, current translation, and preferred translation of each string that you want to change, so opening a PR may still be the simplest approach. I can copy all of the info I need from there and then close the PR.

**Comment by erictraut** [comment]
Closing this issue since there's nothing actionable beyond submitting the form as suggested above.
