### ISSUE TITLE
Literal subtype info in `TypeVarTuple` discarded in chained call

### ISSUE THREAD

**Issue by colehaus** [microsoft/pyright#7451]
```py
from __future__ import annotations

from typing import Generic, Literal, TypeVar, TypeVarTuple

Shape = TypeVarTuple("Shape")
DType = TypeVar("DType")
DType2 = TypeVar("DType2")

class float64:  # noqa: N801
    ...
class float32:  # noqa: N801
    ...

class ndarray(Generic[*Shape, DType]):  # noqa: N801
    def astype(self: ndarray[*Shape, DType], dtype: type[DType2]) -> ndarray[*Shape, DType2]:
        raise NotImplementedError

def random(shape: tuple[*Shape]) -> ndarray[*Shape, float64]:
    raise NotImplementedError

def fn() -> None:
    out1: ndarray[Literal[100], Literal[2], float64] = random((100, 2))
    out2: ndarray[Literal[100], Literal[2], float32] = out1.astype(float32)
    out3: ndarray[Literal[100], Literal[2], float32] = random((100, 2)).astype(float32) # Type error here
```

In the above code, `out1` and `out2` type check. `out3` does not:

```
➜ pyright --version
pyright 1.1.353
➜ pyright ml_scratch/type.py
ml_scratch/type.py
  ml_scratch/type.py:30:56 - error: Expression of type "ndarray[int, int, float32]" cannot be assigned to declared type "ndarray[Literal[100], Literal[2], float32]"
    "ndarray[int, int, float32]" is incompatible with "ndarray[Literal[100], Literal[2], float32]"
      Type parameter "Shape@ndarray" is invariant, but "*tuple[int, int]" is not the same as "*tuple[Literal[100], Literal[2]]" (reportAssignmentType)
```

No errors are raised in mypy 1.9.0.

**Comment by erictraut** [comment]
Pyright is working as intended here. The constraint solver normally doesn't preserve literals when solving type variables. It will preserve literals in cases where bidirectional type inference (an "expected type") is used. In this case, the call expression for the `astype` method is evaluated with an expected type, but the type of the `astype` method is already specialized based on the type of the object it is bound to — i.e. the type of the expression `random((100, 2))`. This expression is necessarily evaluated without the benefit of bidirectional type inference, so it is evaluated as `ndarray[int, int, float64]`, and this means the partially-specialized type of the `astype` method is `(dtype: type[DType2]) -> ndarray[int, int, DType2]`. 

If you want to retain the literals, you'll need to break up the expression as you've done with `out1` and `out2`.
