### ISSUE TITLE
`Final` not allowed in the context of dataclasses.

### ISSUE THREAD

**Issue by pawelrubin** [microsoft/pyright#747]
**Describe the bug**
`Final` not allowed in the context of dataclasses.

**To Reproduce**
Steps to reproduce the behavior.

Consider this piece of code
```python
from dataclasses import dataclass
from typing import Final


@dataclass
class Foo:
    bar: Final[str] = "G.R. Emlin"
```
Hovering over the `Final[str]` produces an error: 
```shell
"Final" is not allowed in this context
```

**Expected behavior**
`Final` shouldn't be labeled as **not allowed in this context**

**Additional context**
- VS Code extension: - 1.1.44
  - settings:
    ```json
		{
  			"pyright.typeCheckingMode": "strict",
  			"pyright.useLibraryCodeForTypes": true
		}
	```
- Python: 3.8.3

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next version of Pyright.

**Comment by erictraut** [comment]
This is now fixed in version 1.1.45, which I just published.

**Comment by pawelrubin** [comment]
@erictraut Thank you!
Btw, could you link a commit with the bug fix so I could see the actual implementation? :pray:

**Comment by erictraut** [comment]
Sure, here's the commit for the bug fix: https://github.com/microsoft/pyright/commit/93e1fc731465bfdfaf6f842280ed232d07ded01d
