### ISSUE TITLE
Pyright (reportCallIssue)

### ISSUE THREAD

**Issue by mikewang68** [microsoft/pyright#7470]
I use neovim code backtrader program with pyright pluin , some function or class display error or warning ,  but program can be running , i dont know how to fix it ,  thanks
By the way , the same code is normal with jupyter lab.

Code :

from datetime import datetime
import backtrader as bt

class SmaCross(bt.Strategy):
    params = dict(
        pfast=10,  # period for the fast moving average
        pslow=30   # period for the slow moving average
    )

    def __init__(self):
        sma1 = bt.ind.SMA(period=self.p.pfast)  # fast moving average
        sma2 = bt.ind.SMA(period=self.p.pslow)  # slow moving average
        self.crossover = bt.ind.CrossOver(sma1, sma2)  # crossover signal

    def next(self):
        if not self.position:  # not in the market
            if self.crossover > 0:  # if fast crosses slow to the upside
                self.buy()  # enter long

        elif self.crossover < 0:  # in the market & cross to the downside
            self.close()  # close long position

cerebro = bt.Cerebro()  # create a "Cerebro" engine instance

data = bt.feeds.YahooFinanceData(dataname='MSFT',
                                 fromdate=datetime(2011, 1, 1),
                                 todate=datetime(2012, 12, 31))

cerebro.adddata(data)  # Add the data feed

cerebro.addstrategy(SmaCross)  # Add the trading strategy
cerebro.run()  # run it all
cerebro.plot()  # and plot it with a single command

Report :
 模块不可调用 Pyright (reportCallIssue) [42, 16]
 │     模块不可调用 Pyright (reportCallIssue) [43, 16]
 │     应为 0 个位置参数 Pyright (reportCallIssue) [44, 43]
 │     “SimpleMovingAverage”不是模块“..indicators”的已知成员 Pyright (reportAttributeAccessIssue) [72, 34]
 │     无法存取类型“tuple[tuple[Literal['maperiod'], Literal[20]]]”的成员“maperiod” Pyright (reportAttributeAccessIssue) [72, 88]
 │        成员"maperiod"未知 
 │     没有名为“dataname”的参数 Pyright (reportCallIssue) [92, 28]
 │     没有名为“fromdate”的参数 Pyright (reportCallIssue) [92, 51]

![image](https://github.com/microsoft/pyright/assets/45821213/ed08e9c5-cf5e-4b0e-b3c4-dff96fa6f884)

**Comment by erictraut** [comment]
It appears that the `backtrader` library is doing some very hacky things that manipulate the global namespace in ways that a static analysis tool like pyright cannot understand.

Pyright is working correctly here, so I don't consider this a bug. 

If this library is important to you and you'd like it to work with static analysis tools, please let the maintainers know that they should not do this type of dynamic namespace manipulation.

You may be able to work around the issue by not using the short-hand aliases and instead using the actual class names defined in the library.
