### ISSUE TITLE
Add directive for disabling pyright

### ISSUE THREAD

**Issue by felixmulder** [microsoft/pyright#7471]
Pyright allows top level directives like:

```python
# pyright: strict
```

Which is helpful, but in a monorepo setting in the process of adopting Pyright, it would be useful to allow:

```python
# pyright: off
```

To turn off reports entirely for the file. We could use a top-level `type: ignore`, but during our rollout we still have Mypy. Until Pyright has enough type information to surpass Mypy, we only allow Pyright to consider `# pyright:` directives/comments.

**Comment by erictraut** [comment]
As you said, `# type: ignore` serves the same purpose. I don't think a `# pyright: off` is justified, so I'm going to close this issue.

**Comment by felixmulder** [comment]
Yes, but since that also disables Mypy -- it's not really a great solution for us.

Our engineers care very much about not having abundant error reporting. And while we upgrade dependencies, add stubs, and improve annotations -- Pyright is more precise than Mypy and will report things that the engineers don't feel comfortable addressing themselves.

Are there other alternatives for us here?

Lowering the bar substantially for Pyright is one option, but ideally we'd keep Pyright reporting things properly and phasing out Mypy.

**Comment by erictraut** [comment]
If you need to exclude or ignore specific files or directories, you can add them to pyright's "exclude" or "ignore" configuration in your pyrightconfig.json or pyproject.toml file.

You can also disable pyright by default in all files and selectively enable in specific files using `# pyright: basic` or `# pyright: standard` in those specific files.

**Comment by felixmulder** [comment]
Neither of those are great to be perfectly honest.

The former will feel frictionful to engineers -- the latter will require us to ratchet files in order to push the repo in the right direction 😔

We've been meaning to layer our own LSP on top of Pyright. Maybe it's just time we do that...

**Comment by felixmulder** [comment]
Thanks anyway for the snappy turnaround!
