### ISSUE TITLE
Recent rules are too strict

### ISSUE THREAD

**Issue by MitchellBarker** [microsoft/pyright#7484]
There's been a lot of new rules added recently, which is great, but I think the "basic" severity might be too strict for several. My expected behavior out of the "strict" rule set is that errors show when the code itself will break and warnings show if there are typing issues. Obviously "strict" should show errors for both those scenarios.

There may be more that have popped up, but `reportArgumentType`, `reportInvalidTypeForm`, `reportAssignmentType`, and `reportAttributeAccessIssue` all seem to be throwing errors where they should just be warnings in a non strongly-typed project.

**Comment by MitchellBarker** [comment]
If it's a breaking change, shouldn't the semantic versioning be bumping major versions? Or at least minor versions?

**Comment by erictraut** [comment]
We try to avoid making breaking changes. That's my point. If we were to change these defaults, it would be disruptive to existing pyright users. When I split `reportGeneralTypeIssues` into multiple other rules, I retained the same defaults to preserve the existing behavior. For example, all diagnostics that are now reported under the `reportArgumentType` rule were previously reported under `reportGeneralTypeIssues`. In both cases, these rules have a default diagnostic severity of `error` in "basic" type checking mode. The only difference is that now you can manually override the default in a finer-grained manner.

**Comment by MitchellBarker** [comment]
Ah, yeah, I guess changing these to "warning" now would be backwards incompatible. I didn't realize they were split out from `reportGeneralTypeIssues`. I'm sure that granularity is an improvement for a lot of people.
I do know I can override in my environment, which I'm already doing, but I'd suggest, to preserve previous behavior, `reportGeneralTypeIssues` overrides should still have applied to all sub rules. 
My environment perviously had set `reportGeneralTypeIssues` to "warning" and granularizing these caused a bunch of errors to pop up where none had before. So now I'm playing whackamole to preserve behavior. It seems to me like that should not have happened.

**Comment by erictraut** [comment]
Yes, even splitting existing rules into finer-grained rules is arguably a breaking change for the reason you mentioned, and it was documented as such [in the release notes](https://github.com/microsoft/pyright/releases/tag/1.1.348). I didn't make that change lightly. In fact, I held off on making that change for more than a year, but the feedback from pyright users was very strong that they wanted finer-grained controls. Apologies that this is causing you some short-term pain. the good news is that it's a one-time fix for your configuration settings.

**Comment by MitchellBarker** [comment]
No worries man. It'll be fine. Can I ask why that didn't go into a new major/minor version? And I wanna note that I'm only being so persistent because I love this project. So sorry if that comes off as unappreciative. I'm super thankful for all this work.

**Comment by erictraut** [comment]
I don't see how a major/minor version would have helped here. Would you have pinned your project to the old major version in that case?

Major/minor version changes come with their own tradeoffs. This would likely break many existing CI scripts, the PyPi-distributed pyright wrapper, test suites that invoke pyright, etc. In other words, I think changing the major/minor version would have been pretty disruptive.

**Comment by MitchellBarker** [comment]
> Would you have pinned your project to the old major version in that case?

^Exactly that. It's just that many projects trust their packages to only introduce breaking changes in a major version, if they're following semantic versioning. So then, if a later release comes out with breaking changes, it _should_ require developer intervention to make sure the upgrade process goes smoothly.

Or from semver.org:
> MAJOR version when you make incompatible API changes
MINOR version when you add functionality in a backward compatible manner
PATCH version when you make backward compatible bug fixes
