### ISSUE TITLE
Do not allow matching PEP 695 type aliases

### ISSUE THREAD

**Issue by LeeeeT** [microsoft/pyright#7485]
Since version [1.1.346](https://github.com/microsoft/pyright/releases/tag/1.1.346), pyright no longer complains about the following code which fails at runtime.

```python
type Int = int

match 1:
    case Int():
        print("int")
```

Maybe related to https://github.com/microsoft/pyright/issues/5662.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.355, which I just published.
