### ISSUE TITLE
Dealing with products of overloads

### ISSUE THREAD

**Issue by rmorshea** [microsoft/pyright#7517]
# Summary

In short, Pyright ignores explicitly declared overloads and prefers overloads from `Protocol`s returned by decorators. That is, if a function has a decorator which returns a `Protocol` with an overloaded `__call__` Pyright will always choose to use the protocol's overloads instead of any that were explicitly declared for the decorated function.

In an ideal world, Pyright would automatically infer the interface of the decorated function to be a product of the declared overloads, but in our world, it seems best to choose the "outer-most" or "most explicitly" declared overloads.

## An Example

Imagine you have a decorator similar to the one below:

```python
from typing import Any, Callable, Concatenate, NewType, ParamSpec, Protocol, TypeVar, overload

P = ParamSpec("P")
R = TypeVar("R")
Session = NewType("Session", object)  # e.g. SQLAlchemy session


class SessionFunc(Protocol[P, R]):

    @overload
    def __call__(self, session: Session, *args: P.args, **kwargs: P.kwargs) -> R: ...

    @overload
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R: ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...


def uses_session(func: Callable[Concatenate[Session, P], R]) -> SessionFunc[P, R]: ...
```

This decorator works great on its own:

```python
@use_session
def my_func(session: Session, my_param: int) -> int: ...

reveal_type(my_func(Session(), 1))  # int
reveal_type(my_func(1))  # int
```

However, if `my_func` needs be overloaded, things fall apart:

```python
@overload
def my_func(session: Session, my_param: str) -> str: ...

@overload
def my_func(session: Session, my_param: int) -> int: ...

@uses_session
def my_func(session: Session, my_param: str | int) -> str | int:
    ...
```

While you might expect the following:

```python
reveal_type(my_func(Session(), "hello"))  # str
reveal_type(my_func("hello"))  # str
```

What you get is:

```
reveal_type(my_func(Session(), "hello"))  # str | int
reveal_type(my_func("hello"))  # str | int
```

It appears that Pyright ignores the overloads declared for `my_func` and chooses the `overload` declared on `SessionFunc.__call__`.

# Solutions

As has been [mentioned before](https://discuss.python.org/t/some-improvements-to-function-overloads/36275/3), `overload` is under-specified so I full expect that this might not be something that the Pyright maintainers want to address. However, I feel there's at least some value in laying things out.

## The Ideal Solution

In a perfect world, it would be great if Pyright could compute the "product" of all possible overloads automatically. So, in the example above where you declare:

```python
@overload
def my_func(session: Session, my_param: str) -> str: ...

@overload
def my_func(session: Session, my_param: int) -> int: ...

@uses_session
def my_func(session: Session, my_param: str | int) -> str | int:
    ...
```

Pyright ought to infer that the interface of `my_func` is:

```python
@overload
def my_func(my_param: str) -> str: ...

@overload
def my_func(session: Session, my_param: str) -> str: ...

@overload
def my_func(my_param: int) -> int: ...

@overload
def my_func(session: Session, my_param: int) -> int: ...
```

Behavior like this would certainly require a PEP to fully describe though so it doesn't seem like something that we'd see any time soon

## A Realistic Solution(?)

In the meantime, one way that Pyright could choose to alleviate the current shortcomings in overloading might be to select the "outer-most" or "most explicitly" declared overloads instead of the "inner-most". That is, in the example above, instead of choosing the overloads from  `SessionFunc.__call__`, Pyright should prefer those declared for `my_func`. The result of this change in opinion would allow users to manually describe overload products themselves. That is I could write:

```python
@overload
def my_func(my_param: str) -> str: ...

@overload
def my_func(session: Session, my_param: str) -> str: ...

@overload
def my_func(my_param: int) -> int: ...

@overload
def my_func(session: Session, my_param: int) -> int: ...

@use_session
def my_func(session: Session, my_param: str | int) -> str | int:
    ...
```

Pyright should then be able to correctly determine:

```python
reveal_type(my_func(Session(), "hello"))  # str
reveal_type(my_func("hello"))  # str
```

Absent this sort of capability you'd probably end up resorting to doing this any way when `TYPE_CHECKING`:

```python
if TYPE_CHECKING:
    @overload
    def my_func(my_param: str) -> str: ...

    @overload
    def my_func(session: Session, my_param: str) -> str: ...

    @overload
    def my_func(my_param: int) -> int: ...

    @overload
    def my_func(session: Session, my_param: int) -> int: ...

    def my_func(session: Session, my_param: str | int) -> str | int:
        ...
else:

    @use_session
    def my_func(session: Session, my_param: str | int) -> str | int:
        ...
```

**Comment by erictraut** [comment]
Overload behavior is underspecified in some ways, but this isn't one of them. If you apply a decorator to only the implementation of an overloaded function, that overload will not apply to the individual overloads. In this respect, the typing spec is very clear, and I don't see this changing.

**Comment by rmorshea** [comment]
As [shown here](https://pyright-play.net/?strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCKcANFAMICGANtZQEbUCmZ5YKAxpTEyty1AByTAO4AVRAIAKlEJQgBlBEw5kp4GGA5hqZCcoBqssmABuTENTCUAJmRBNzNAPrxlAWABQXqVAC8UDJyisocABQARFIRAJReAEr%2BUPpMRiCR8bFeCkwAzrlI7EnC4pKROfmFKBEm9ABWKjAxUFAAxFBMAHRonVAKAIoAMgTUHAAWTBBwULl5Bexei54cdPl9c1UAYgCunGHqYJra1ADaUmTxALoxAFxLLS0AAmYWVrZeD1A2TMBQzs5cWj-MKzajAMizSrsG7rKEoMgAKlkaFyMKknWRuURCIA1iJMWjOnjMc0ALQAPig8RhnVp9wez3MlmsNg%2BD2%2Bv3%2BgOowNB4KgSJAKMJmOxxKFqMCRPxErJlOpUFpnXpLQ5fwBNB5zhBTDBiIJhGIYplwsNcDlZppdO8NrV20hzkh8xQYWAuw4MKotAYzBObE4-D4PBOFWdakuF2uUApsOdO04Z0jVuVNq8jNeLLT9ryjo2C08aqmzjdeydVRhoaqZCLCFk8hhuRgIAtjZAyaWaZezPenke2dyubhXkLcGL7p1cIrefhUBrdYgMNQTWjlKX7dTvf7g%2Bdw5%2Bs9HJfCZehsar%2B%2BcteCDabUAAPpgUMuY627w%2BYOulg4nDy3EwwkXDzCSt2DCGIyAiCZaDAWI4k8IA), Pyright ignores the "outer-most" overloads regardless of whether the decorator is placed on overloads. I've amended the description to reflect this.

**Comment by erictraut** [comment]
Overloads apply only to functions, not to objects. The code sample that you posted applies a decorator that transforms a function into a (callable) object. Overloads will not work with that approach.

**Comment by rmorshea** [comment]
Got it. Thanks for the reply.
