### ISSUE TITLE
Missing Import

### ISSUE THREAD

**Issue by K3PLAR** [microsoft/pyright#7520]
After installing flask and running a snippet calling "from flask" it displayed 'import "flask" could not be resolved'

**Comment by erictraut** [comment]
You have not provided enough information to repro or to diagnose the problem. 

It's unlikely that this is a bug in pyright, so I'm going to close the issue.

Please refer to [this documentation](https://microsoft.github.io/pyright/#/import-resolution) for information about how pyright resolves imports. If you are still having problems, feel free to open a thread in the discussion section to ask for assistance.
