### ISSUE TITLE
Extend variable access checks to consider prior code paths

### ISSUE THREAD

**Issue by ntw-au** [microsoft/pyright#7523]
**Is your feature request related to a problem? Please describe.**
The below code gives a spurious `reportOptionalSubscript` error because it doesn't consider that the code path via `is_valid` guards the possibility of `counts` being `None`.

```python
from typing import Optional


class Example():
    def __init__(self, count: Optional[int]):
        self.counts = None

        if count:
            self.counts = [count] * count

    @property
    def is_valid(self) -> bool:
        return self.counts is not None

    def count(self, index: int) -> int:
        if not self.is_valid:
            raise ValueError('Object is in an invalid state')

        return self.counts[index]  # Raises 'Object of type "None" is not subscriptable'
                                   # Pylance[reportOptionalSubscript]
```

**Describe the solution you’d like**
Pylance considers variable preconditions enforced by prior code paths, so that the above code sample passes with no errors from Pylance.

**Comment by erictraut** [comment]
This feature request is based on a fundamental misunderstanding of how type narrowing works.

For more details, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-narrowing).

**Comment by ntw-au** [comment]
> This feature request is based on a fundamental misunderstanding of how type narrowing works.

I'm sure that's true, but please humour me briefly. Take the following example:

```python
def is_indexable(value):
    # Function consists entirely of hoisted type guards and logical expressions
    return isinstance(value, list) or isinstance(value, np.ndarray)


def size(value: Union[list, np.ndarray, int]):
    if is_indexable(value):
        return len(value)  # reportArgumentType error

    if isinstance(value, list) or isinstance(value, np.ndarray):  # Equivalent to calling is_indexable()
        return len(value)  # OK

    return 1
```

Considering that `is_indexable` consists of nothing but a valid type guard expression hoisted into a function, couldn't it be considered to be a type guard itself?

**Comment by erictraut** [comment]
@ntw-au, your second example is very different from the first. The `is_indexable` function is a valid type guard whereas `is_valid` in your first example is not.

If you want `is_indexable` to be treated as a type guard, you need to annotate it as such.

```python
def is_indexable(value: object) -> TypeGuard[np.ndarray | list]:
      return isinstance(value, list) or isinstance(value, np.ndarray)
```

**Comment by ntw-au** [comment]
Thank you, that's very helpful; I wasn't aware of `TypeGuard`. Reading [PEP 647](https://peps.python.org/pep-0647/) indicates that I should be able to use that in the `is (not) None` case as long as it's narrowed to the positive case, and as long as it's a free function rather than a method.

```python
def is_valid(counts) -> TypeGuard[list[int]]:
    return counts is not None


def is_not_valid(counts) -> TypeGuard[None]:
    return counts is None


def count(counts: Optional[list], index: int):
    if is_not_valid(counts):
        assert counts is None  # OK

    if is_valid(counts):
        return counts[index]  # OK

    raise ValueError()

```

I can work with that. Thanks very much again.
