### ISSUE TITLE
Wrongful error flagging when defining functions with the same name in several if/elif/else branches

### ISSUE THREAD

**Issue by Gouvernathor** [microsoft/pyright#7524]
**Describe the bug**
When the same function (with the same name but different body) is defined in several branches of the same if/elif/else branch, pyright reports that the second obscures the first, when it's actually not the case.

**Code or Screenshots**
```py
    def _iter_all_close_relatives(self, *, with_relationship=False):
        if with_relationship:
            def zp(itr, r): return itr # here
        else:
            repeat = itertools.repeat
            def zp(itr, r): return zip(itr, repeat(r))
        yield from zp(self._parents, Relationship.PARENT)
        yield from zp(self._children, Relationship.CHILD)
        yield from zp(self._spouses, Relationship.SPOUSE)
```

At the "here" location, the following error is signaled on the `zp` symbol : ```Function declaration "zp" is obscured by a declaration of the same namePylance[reportRedeclaration](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportRedeclaration)
family.py(520, 17): See function declaration```

**VS Code extension or command-line**
Using Pylance v2024.3.100 in VSCode.

**Comment by erictraut** [comment]
This is by design, not a bug. These are different declarations with different (incompatible) types. The first has an inferred return type of `Unknown`, and the second has an inferred return type of `zip[tuple[Any, Any]]`. You cannot redeclare the same symbol with incompatible types. 

You can fix this in your code by providing explicit return types (and preferably also parameter types) for both declarations.

**Comment by Gouvernathor** [comment]
If this is due to the return type, then the error message should reflect that.

**Comment by erictraut** [comment]
This is due to the fact that you have redeclared the same symbol, which is what the error message indicates.

**Comment by Gouvernathor** [comment]
When I redeclare the same symbol using two functions with the same return type, the error doesn't appear. Therefore, and as your previous message indicates, the issue is with a function being obscured by another _of a different return type_. That should appear in the error message.

**Comment by Gouvernathor** [comment]
The error message is still inaccurate in the current prerelease of Pylance, v2024.3.102
@erictraut 

As a reminder, despite the error message mentioning that the problem is due to "declaration of the same symbol", declaring the same symbol twice is not what triggers it, and the real trigger which in your words is the the different definitions have "incompatible types" is missing from the error message.
