### ISSUE TITLE
Special case for passing string Literals to `sys.intern`

### ISSUE THREAD

**Issue by SebbyLaw** [microsoft/pyright#7532]
**Is your feature request related to a problem? Please describe.**

Currently `sys.intern` does not special case literals

```py
import sys

x: Literal["foo"] = sys.intern("foo")  # error, because `str` is not `Literal["foo"]`
```

**Describe the solution you’d like**

If possible, it would be nice if pyright special-cased this builtin function when known string literals are passed as arguments.

**Comment by erictraut** [comment]
Pyright doesn't special-case functions. Its behaviors are based on the type information provided in typeshed. If you would like to suggest a modification to the type definition of this function, you can open an issue or a PR in the [typeshed project](https://github.com/python/typeshed).
