### ISSUE TITLE
Allow pyright to recognize that a class is compatible with a protocol when singledispatchmethod is used

### ISSUE THREAD

**Issue by chunyang** [microsoft/pyright#7543]
**Is your feature request related to a problem? Please describe.**
Consider the following protocol and two classes.
```python
class BooleanUnaryOp(Protocol):
    def __call__(self, arg) -> bool: ...


# BooleanUnaryOp protocol implementation via implicit subtyping.
class IsPositive:
    @singledispatchmethod
    def __call__(self, arg) -> bool:
        raise NotImplementedError

    @__call__.register
    def _(self, arg: int) -> bool:
        return arg > 0


# BooleanUnaryOp protocol implementation via explicit subclassing.
class IsPositiveExplicit(BooleanUnaryOp):
    @singledispatchmethod
    def __call__(self, arg) -> bool:
        raise NotImplementedError

    @__call__.register
    def _(self, arg: int) -> bool:
        return arg > 0
```

Despite the classes being compatible with the protocol in that they each have a `bool`-returning unary callable member `__call__`, Pyright reports errors for the two classes above. In the case of `IsPositive`, the error surfaces when an instance of the class is used where a protocol subtype/subclass is expected.

```python
def apply_unary_op(op: BooleanUnaryOp, operand):
    return op(operand)

op1: BooleanUnaryOp = IsPositive()
```

```
Argument of type "IsPositive" cannot be assigned to parameter "op" of type "BooleanUnaryOp" in function "apply_unary_op"
  "IsPositive" is incompatible with protocol "BooleanUnaryOp"
    "__call__" is an incompatible type
      Type "singledispatchmethod[bool]" cannot be assigned to type "(arg: Unknown) -> bool"  (reportArgumentType)
```

In the case of `IsPositiveExplicit`, the error is surfaced when the class is declared.
```
"__call__" overrides method of same name in class "BooleanUnaryOp" with incompatible type "singledispatchmethod[bool]"  (reportIncompatibleMethodOverride)
```

Pyright Playground: [link](https://pyright-play.net/?code=GYJw9gtgBMCuB2BjALmMAbAzlAlhADmCMlJjvAOboCmAJjpvgIbKIAWE1ybYtAUKEhRkAT3zkKuAkRIAFcKkQY%2BKxOiaZsAITQ0m8AKrwmIEQHl8ACnlhFGAJQAuPlFdRa1YFAD63xE3R0X0tManRgABooEwp7KABaAD4oACNdRygAOmyVPgBiKB0Man0jE3N8KHwFMCV0KXwaTnhkFhwweCgANxwmBvQcRBwSTFgU0XFKTL41DWwASUxZMDJkHC7qZzcoAAEyShp6RhZ2Tm5eFzcPL19-QODQ8KiYuKTU9Mvt1xAmBmooABytnmBCa1BadAAoiBwCAVNsdrcAkFvJkQNQKAxkNQ4dtrj4QmFItEQBQMuRkK9kmkMFsvt8uLAQJ0YlBkgAGXIFIp6QzGUwWKo1Or9ajNVprDrdXpQagAD0ag2GpDGs00EmmaoWSxWw3W1EhCoGQ2Qlh5JT55QsTk%2Bu32VDoDGYrA4XB4-Dxnh8fmRDyJz1JVPetNt2x%2Bf0BwNBYvB2No0Nh8LciJ991R6MxmGxuKuXu8hKeJLJuBaQZp6Dp9PRyCZLNJbKgnJU3N0FrKAsq1VstQwovFbSlPT6fRoG3qYC85Ho6JQ7XgmvUmigi2Wq3183g0%2BoKEr7jzqZRBeJLwS1I%2B9IZNeZpCJmQP3jwjUsLyTrj2EkOTpOrvOHtzNzuIJH3QI8A1iU9gwrUM3HDUJI2QEFGhjCF4xhIhX12e9gLRDEsRxW18XzR5j1JclSwg8tdzDRlr1ZDlcjAfAAEYMnNUp%2BQqKAAF5lx1NcNksew%2BEYgAmVjW3Yq1Kh4lddTWDZDUVE1BOE-AAGZxOKSSO243jVz1DYNy3FAVKAA)

**Describe the solution you’d like**
I would like to see Pyright recognize that the two classes above are compatible with the protocol.

Filed as a feature request rather than a bug after reading https://github.com/microsoft/pyright/issues/7358#issuecomment-1967455571.

**Comment by erictraut** [comment]
Thanks for the feature request.

We currently have no plans to add special-case support for functools.singledispatch. This would be significant work, and it's not clear whether this would be a good investment. We've received a couple of requests for it over the years, but there's not yet enough signal to justify the investment. I'm therefore going to reject the feature request now. I'm willing to revisit in the future if there's additional signal (e.g. in the form of upvotes).
