### ISSUE TITLE
__package__ not recognized as str

### ISSUE THREAD

**Issue by matt-the-midnight-hacker** [microsoft/pyright#7544]
**Describe the bug**
I get error: 
```
error: Argument of type "str | None" cannot be assigned to parameter "s" of type "str" in function "myf"
    Type "str | None" cannot be assigned to type "str"
      "None" is incompatible with "str" (reportArgumentType)
```
vscode hover over `__package__` shows me type `str` not `str | None`

**Code or Screenshots**

```python
def myf(s: str):
    print(s)

myf(__package__)
```

**VS Code extension or command-line**
I use pyright 1.1.355 installed via pip from command line.
I just updated pyright, before I used `1.1.352` and I did not get this error there.

**Comment by erictraut** [comment]
Pyright's current behavior is correct. The correct type of `__package__` is `str | None`, not `str`. It will be fixed in pylance once it releases a new version.

See [this issue](https://github.com/microsoft/pyright/issues/7408) for details.
