### ISSUE TITLE
Match case for tuple representation of data

### ISSUE THREAD

**Issue by korchizhinskiy** [microsoft/pyright#7559]
Hi. Whenever I'm using tuple resolving with match/case I face the problem.

I have one enumeration with user roles:
```python
from enum import Enum

class UserRole(Enum):
    UNKNOWN = "UNKNOWN"
    KU = "KU"
```

I use this enumeration in match case. Do not  understand the meaning of the code, example abbreviated:
```python
from typing import assert_never

class Service:
    def __init__(self, user_role: tuple[UserRole, int | None]) -> None:
        self.user_role = user_role

    @property
    def service(self) -> int:
        match self.user_role:
            case (UserRole.UNKNOWN, _):
                return 1
            case (UserRole.KU, _):
                return 2
            case _ as never: # Pyright: Pattern will never be matched for subject type "Never" [reportUnnecessaryComparison] 
                assert_never(never)
```

And get error: `Pyright: Pattern will never be matched for subject type "Never" [reportUnnecessaryComparison]
`

Pyright version: 1.1.355
Python: 3.11.3

**Comment by erictraut** [comment]
Pyright is working as intended here, so this isn't a bug.

You have apparently enabled the `reportUnnecessaryComparison` rule, which is disabled by default. In your code sample, the last case statement is provably never needed, so you can delete it. Pyright already detects exhaustion for match statements, so there's no need to create a dummy case statement and an `assert_never` to manually check for exhaustion.

If you don't want pyright to detect unnecessary case statements, simply disable the `reportUnnecessaryComparison` check.

**Comment by AlexWaygood** [comment]
I disagree that this issue should have been closed. It means that pyright will, in strict mode, complain about the example [given in the `typing` documentation](https://docs.python.org/3/library/typing.html#typing.assert_never) to illustrate an idiomatic use of `assert_never`:

```py
def int_or_str(arg: int | str) -> None:
    match arg:
        case int():
            print("It's an int")
        case str():
            print("It's a str")
        case _ as unreachable:
            assert_never(unreachable)
```

It's true that the last branch in this code is unreachable -- but that's the whole point of having the branch to begin with: to ensure that the previous branches do indeed exhaustively handle all possibilities, and to raise an assertion _at runtime_ if there was a programming error and they were not, in fact, exhaustive. While pyright has the `reportMatchNotExhaustive` diagnostic to statically check whether all branches were exhaustive, I think it's entirely reasonable for users to want to enforce that invariant at runtime as well as statically, which is what the third branch here is for.

Mypy emits no errors on this code snippet with both `--strict` and `--warn-unreachable` enabled. It specifically makes sure not to emit diagnostics about unreachable branches if the only statements in that branch are things such as `assert False` or a call to a function with all arguments annotated as `NoReturn`/`Never`, as these branches are obviously _meant_ to be unreachable. See https://github.com/python/mypy/blob/35fbd2a852be2c47e8006429afe9b3ad4b1bfac2/mypy/checker.py#L2812-L2838.
