### ISSUE TITLE
Function with TypeVar result type treats as Union

### ISSUE THREAD

**Issue by Hattonuri** [microsoft/pyright#7563]
<h3> Environment data </h3>

-   Language Server version: 2024.3.2
-   OS and version: linux x64
-   Python version 3.11.7: 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

```python
from typing import TypeVar


class A:
    def func(self, other: "A") -> "A":
        return other


class B:
    def func(self, other: "B") -> "B":
        return other


AB = TypeVar('AB', A, B)


def ab_func(ab: AB) -> AB:
    return ab.func(ab.func(ab)) # reportArgumentType
```

<h3>Result</h3>

```text
Argument of type "A* | B*" cannot be assigned to parameter "other" of type "A" in function "func"
  Type "A* | B*" cannot be assigned to type "A"
    "B*" is incompatible with "A"Pylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)
Argument of type "A* | B*" cannot be assigned to parameter "other" of type "B" in function "func"
  Type "A* | B*" cannot be assigned to type "B"
    "A*" is incompatible with "B"Pylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)
```

**Comment by erictraut** [comment]
Pyright is working as intended here. You're using a value-constrained TypeVar here. Value-constrained TypeVars are unique to the Python type system and impose difficulties for type evaluators. There are limitations to what a single-pass type evaluator can do with value-constrained TypeVars. You're hitting one such limitation.

Constrained TypeVars impose a different set of limitations for multi-pass type evaluators like mypy, which fails in different ways.

For more details about how pyright handles constrained TypeVars, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=value-constrained-type-variables) and [this documentation](https://microsoft.github.io/pyright/#/mypy-comparison?id=value-constrained-type-variables).

My recommendation is to avoid using value-constrained TypeVars in your code if you can help it. They are not well specified in the typing spec, and your mileage may vary when using them. If you must use them, you'll need to work around limitations like the one you're encountering here.
