### ISSUE TITLE
Wrong errors

### ISSUE THREAD

**Issue by not-programmer98** [microsoft/pyright#7593]
**Describe the bug**
Pyright gives wrong errors for things that aren't errors

**Code or Screenshots**
![Imagepipe_0](https://github.com/microsoft/pyright/assets/126913926/4eb1098a-51a1-4109-bdf6-a5f291488b30)

**VS Code extension or command-line**
It gives me the same errors in vscode and neovim.
However pylance from Microsoft doesn't givee these errors

**Comment by debonte** [comment]
It's very difficult to reproduce problems from screenshots. Please provide a complete, minimal code sample that reproduce this issue along with required packages and versions.

What versions of Pyright and Pylance are you using?

Please read https://github.com/microsoft/pylance-release/blob/main/USING_WITH_PYRIGHT.md.
