### ISSUE TITLE
pyright on command-line with watch (-w) insensitive to file changes

### ISSUE THREAD

**Issue by scanny** [microsoft/pyright#7609]
When running `pyright` from the command-line (MacOS, zsh) with the "watch" option (`-w`), saving the source file being checked does not trigger a fresh run. This works in `1.1.354` but not in `1.1.357`.

This behavior appears to be intermittent, like sometimes it makes a fresh run and sometimes it doesn't. Happy to experiment more if you need help narrowing it down :)

Command line I'm using is:
```bash
pyright -w source.py tests/test_source.py
```

When I use `^C` to quit and restart, the trace is always the same, here it is just in case that's a clue:
```bash
Watching for file changes...
^CTraceback (most recent call last):
  File "/Users/scanny/.virtualenvs/venv/bin/pyright", line 8, in <module>
    sys.exit(entrypoint())
  File "/Users/scanny/.virtualenvs/venv/lib/python3.9/site-packages/pyright/cli.py", line 34, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/Users/scanny/.virtualenvs/venv/lib/python3.9/site-packages/pyright/cli.py", line 19, in main
    return run(*args, **kwargs).returncode
  File "/Users/scanny/.virtualenvs/venv/lib/python3.9/site-packages/pyright/cli.py", line 30, in run
    return node.run('node', str(script), *args, **kwargs)
  File "/Users/scanny/.virtualenvs/venv/lib/python3.9/site-packages/pyright/node.py", line 124, in run
    subprocess.run(node_args, env=env, **kwargs),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1126, in communicate
    self.wait()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1917, in _wait
    (pid, sts) = self._try_wait(0)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1875, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

```

**Comment by erictraut** [comment]
The file system event handlers in MacOS are notoriously flaky. The OS allows a very small number of them per process and across all processes. If you exceed that number, it simply fails to allocate more. We (the maintainers of pyright) and many others (including the maintainer of [chokidar](https://github.com/paulmillr/chokidar), the library we use in the pyright CLI to abstract file system events) have spent significant time attempting to work around these limitations, but it's still flaky at times.

I'm not aware of any changes we've made to the file system watcher code in pyright recently, so I don't think this is a recent regression or change in behavior. I suspect that you're just hitting some limits on your system. Perhaps your project or your Python environment grew in size recently, and that's triggering the flakiness.

I don't know if there's anything we can do here.

@rchiodo, are you aware of any changes that were introduced by the pylance team that could have potentially affected the chokidar-based file system events mechanism used in the CLI version of pyright?

**Comment by erictraut** [comment]
@scanny, typically when we hit these file system event limits, pyright's logic detects this condition and logs a warning in the output. Are you seeing any such warnings? Please try adding the command-line option `--verbose` to see if the additional output provides clues.

**Comment by rchiodo** [comment]
> @rchiodo, are you aware of any changes that were introduced by the pylance team that could have potentially affected the chokidar-based file system events mechanism used in the CLI version of pyright?

The only one that would make sense is the URI change, but that was in 1.1.340

**Comment by erictraut** [comment]
@scanny, I don't think there's anything actionable for us to do here, so I'm going to close this issue. If you are able to get additional clues or repro steps, I'd be happy to investigate further.

**Comment by scanny** [comment]
Sure @erictraut, no worries :)

@rchiodo I do see a message in the logs:
```Watcher could not use native fsevents library. File system watcher disabled.```
Is that the one you were thinking of? Interestingly, that appears under 1.1.357 but does not under 1.1.354.

**Comment by rchiodo** [comment]
No sorry. The change I was talking about had to do with paths of files being different. 

That error you see comes out when chokidar fails to load the file watcher for some reason.
