### ISSUE TITLE
pyright cannot handle built-in python 3 class method __subclasses__

### ISSUE THREAD

**Issue by QUANZHOU1990** [microsoft/pyright#761]
**Describe the bug**
pyright reports `reportGeneralTypeIssues` on `__subclasses__`, which is a built-in class method since python 3.0 

**To Reproduce**
run the pyright against following: 
```
class test_class(object): 
    def __init__(self):
        print(1)
print(test_class.__subclasses__())
```

**Expected behavior**
pyright can handle it since it is a built-in method. 

**Screenshots or Code**

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.
command-line. 1.1.39

**Additional context**

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.46, which I just published.
