### ISSUE TITLE
Incorrect type inference involving unpacked tuple in match statement

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#7613]
```
def f(x: tuple[int, str, *tuple[range, ...]]) -> None:
    match x:
        case [1, *ts]:
            reveal_type(ts)
        case _: pass
```
([playground](https://pyright-play.net/?pythonVersion=3.13&strict=true&code=CYUwZgBGAUAeBcEAuBXADgGxAbQJYDskAaCAZyQCcSAqVTHCgQ3wHMQSA6LgXW4EoIAWgB8EAHIB7fCHgAoCAogBbRkgDGACwgJ5ivWsakQEbAEYaSUtzl7biiiABuIRhgD6SAJ5oQ0S3107AyMIN0Q0Q1IgA))

Produces:
`Type of "ts" is "list[str]"`

Which is wrong; `ts` is a list containing a single str and an arbitrary number of `range` objects.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.
