### ISSUE TITLE
Allow specifying default values for generically-typed fields in dataclasses where the TypeVar has a default

### ISSUE THREAD

**Issue by tmke8** [microsoft/pyright#7614]
**Is your feature request related to a problem? Please describe.**
I was writing code like this:

```python
from dataclasses import dataclass
from typing import Generic, reveal_type
from typing_extensions import TypeVar

T = TypeVar("T", bound=str | None, default=None)

@dataclass
class C(Generic[T]):
  x: T = None  # Expression of type "None" cannot be assigned to declared type "T@C". Type "None" cannot be assigned to type "T@C"

c = C()
reveal_type(c.x)  # None
c2 = C("foo")
reveal_type(c2.x)  # str
```

but pyright is giving an error.

**Describe the solution you’d like**
I think the above code should be safe? I can see why pyright would reject it in the case where the type variable doesn't have a default value – in that case inferring the type variable for `C` cannot really work correctly. But as long as the `TypeVar` default and the type of the default value agree, I can't see how it's unsafe.

**Comment by erictraut** [comment]
No, this isn't safe. Consider:

```python
c = C[str]()
reveal_type(c.x) # reveals "str", but actually "None"
```

**Comment by tmke8** [comment]
Can't you tell from the signature of the synthesized `__init__` that `C[str]` is wrong? Actually, I'm realizing now that the issue isn't really about TypeVars with defaults. It's about whether to treat the dataclass fields as a function signature. For function signatures, pyright allows specifying default values for parameters with generic types. So, it might be possible to allow the same for dataclass fields.
