### ISSUE TITLE
Pyright unable to assign type "int" to type "Number | Word" in inflect library

### ISSUE THREAD

**Issue by Cascalda** [microsoft/pyright#7626]
**Describe the bug**
Pyright unable to assign type "int" to type "Number | Word" in inflect library. 
Also not being able to access member "capitalize" for type "List[str]", which i guess is intended.

**Code or Screenshots**
![image](https://github.com/microsoft/pyright/assets/111849193/3e1070e0-ecc3-4cdb-925c-a1bc10dd4de3)
![image](https://github.com/microsoft/pyright/assets/111849193/b92b2a16-49e3-411a-8d6c-c38090ebe655)

```python
import inflect

inflect = inflect.engine()
number_to_words = inflect.number_to_words


def convert_age_to_words(age_minutes: int) -> str:
    """Converts age in numbers to words."""
    display_age_minutes = number_to_words(age_minutes, andword="").capitalize()
    result = f"{display_age_minutes} minutes"

    return result
```

**VS Code extension or command-line**
I am running Pyright as a VSCode extension, with Pylance uninstalled so I dont get the error messages everytime I open VSCode.

**Comment by erictraut** [comment]
Pyright's behavior here is correct according to the Python typing spec. This isn't a bug.

The class `Number` has no type relationship to class `int`, so a type checker will generate an error if you attempt to assign an `int` to a variable or parameter of type `Number`.
