### ISSUE TITLE
Incorrect unreachable code detection after return in `contextlib.suppress`

### ISSUE THREAD

**Issue by jacobbogdanov** [microsoft/pyright#764]
**Describe the bug**
if there is a `return` statement in a `with contextlib.suppress(Exception)` block, then all the code _after_ is grayed out as unreachable.
 
**To Reproduce**
See the code example below

**Expected behavior**
Code after a `return` in a `contextlib.suppress` is not marked as unreachable.

**Screenshots or Code**
```python
import contextlib
from typing import NoReturn

def func() -> int:
    with contextlib.suppress(KeyError):
        return func2()

    return 5  # this line is grayed out

def func2() -> NoReturn:
    raise KeyError
```

<img width="323" alt="Screen Shot 2020-06-25 at 2 34 14 PM" src="https://user-images.githubusercontent.com/48320751/85778883-09711180-b6f1-11ea-82ef-5e8351a18f90.png">

<img width="353" alt="Screen Shot 2020-06-25 at 2 36 10 PM" src="https://user-images.githubusercontent.com/48320751/85779076-3ae9dd00-b6f1-11ea-9cff-e64adf4bbe43.png">

**VS Code extension or command-line**
pyright vscode extension version 1.1.45

**Comment by erictraut** [comment]
I think this behavior is correct. The call to `func2` always generates an exception, so control flow will never continue after it is called. The `return 5` statement will never be executed.

Are you assuming that the context manager is somehow catching and suppressing the raised exception? If so, a type checker would have no way of knowing this.

**Comment by jacobbogdanov** [comment]
From the docs: https://docs.python.org/3/library/contextlib.html#contextlib.suppress
> Return a context manager that suppresses any of the specified exceptions if they occur in the body of a with statement and then **resumes execution with the first statement following the end of the with statement.**

(emphasis mine.)

So while `func2` always raises an exception, in this example calling `func` will return `5`.

Here is the discussion about `mypy`s `--warn-unreachable` flag with regards to `contextlib.suppress`: https://github.com/python/mypy/issues/7214

**Comment by erictraut** [comment]
As per discussion in this PR thread (https://github.com/microsoft/pyright/pull/771), I'm going to close this for now. Fixing it will add significant complexity to the code, and I'm reluctant to fix it given that 1) assuming behavior of the context manager based on its `__exit__` method return type is not part of the Python spec, and 2) there's already a well-defined way in the language to catch exceptions (namely, try/except blocks).
