### ISSUE TITLE
Lacking type refinement for false-y dicts

### ISSUE THREAD

**Issue by strangemonad** [microsoft/pyright#7646]
I'm not sure if this is a bug or a feature request. Generally, I'd like better ways to streamline refining truthy and falsey types. In the following code, we can refine that `document_metadata` is either None or a non-empty dict. It would be great if that type refinement could propagate.

```python
import typing

def get_document_metadata() -> dict[str, dict[str, str]]:
    ...

metadata_by_document_name = get_document_metadata()
document_name = "doc1"

document_metadata = metadata_by_document_name.get(document_name, None) or None
typing.reveal_type(document_metadata)
property: str | None = document_metadata and f"metadata {document_metadata}"
```

In the last line, the only way that `document_metadata` is falsey is if it's None. if you explicitly test for None, you lose some of the niceties of pipelining values through `and` and `or` e.g.

```
... = document_metadata is None or f"metadata {document_metadata}"
```
yields `bool|str`

**Comment by erictraut** [comment]
This is definitely not a bug. Pyright is working as intended here.

I will change this to an enhancement request and consider it in that context.

**Comment by erictraut** [comment]
The Python type system has no provision for differentiating between an empty or non-empty dict (or list or set). It's theoretically possible to add behind-the-scenes type information internal to the type checker to track metadata like this, but there are major downsides to doing so. It leads to unexpected and opaque behaviors. It results in types that cannot be "spelled" in annotations or printed (e.g. in reveal_type output or hover text). It also adds types whose behavioral rules are not defined in the type spec. For these reasons, I'm very reluctant to add such a feature.

I also find this coding pattern to be difficult to read. I had to stare at the above code for quite some time to convince myself that I understood what it was doing. If your intent is to write robust and maintainable code, I recommend using patterns that are readable and understandable to other developers.

For these reasons, I'm going to reject this enhancement request.

I'm willing to revisit this in the future if there is sufficient demand / signal from pyright users, but for now I have no plans to implement this.
