### ISSUE TITLE
@classmethod complaining about the first `cls` non-optional argument

### ISSUE THREAD

**Issue by sam-goodwin** [microsoft/pyright#7662]
**Describe the bug**
I can't seem to define a class method that accepts the `cls` parameter. PyRight flags it as a type error.

**Code or Screenshots**
If possible, provide a minimal, self-contained code sample (surrounded by triple back ticks) to demonstrate the issue. The code should define or import all referenced symbols.

```python
class Foo:
    @classmethod
    def foo(cls):
        ...
```

I get this error:
```py
Argument of type "(cls: type[Self@Foo]) -> None" cannot be assigned to parameter "f" of type "() -> _R_co@classmethod" in function "__init__"
  Type "(cls: type[Self@Foo]) -> None" cannot be assigned to type "() -> _R_co@classmethod"Pylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)
```

**VS Code extension or command-line**
Both CLI and VS Code have the same problem.

* pyright 1.1.358
* ms-python.vscode-pylance v2024.4.1
* Python 3.10.13

**Comment by sam-goodwin** [comment]
Error goes away if i accept no arguments (as suggested in the type error)

![image](https://github.com/microsoft/pyright/assets/38672686/c62addb4-b1d0-4ae9-a099-4678fbcd1daf)

**Comment by sam-goodwin** [comment]
```py
class classmethod(Generic[_T, _P, _R_co]):
    @property
    def __func__(self) -> Callable[Concatenate[type[_T], _P], _R_co]: ...
    @property
    def __isabstractmethod__(self) -> bool: ...
    def __init__(self, f: Callable[Concatenate[type[_T], _P], _R_co], /) -> None: ...
    @overload
    def __get__(self, instance: _T, owner: type[_T] | None = None, /) -> Callable[_P, _R_co]: ...
    @overload
    def __get__(self, instance: None, owner: type[_T], /) -> Callable[_P, _R_co]: ...
    if sys.version_info >= (3, 10):
        __name__: str
        __qualname__: str
        @property
        def __wrapped__(self) -> Callable[Concatenate[type[_T], _P], _R_co]: ...
```

**Comment by erictraut** [comment]
I'm not able to repro this issue.

https://pyright-play.net/?pythonVersion=3.10&code=MYGwhgzhAEBiD28BcBYAUNT0ACpIQFsBTAFwAt4ATdLaSogM2gcQApQIBKVDWrAOkHogA

My best guess is that you have a really old, stale version of `typing_extensions` installed in your environment. Please try to repro with a new, clean virtual environment.

I'm pretty confident this isn't a bug in pyright, so I'm going to close the issue.

**Comment by sam-goodwin** [comment]
My typing_extensions is latest:
```
typing-extensions==4.11.0
```

**Comment by sam-goodwin** [comment]
There is something wrong with the `Concatenate` type in my setup.

If i monkey patch the `classmethod`'s `__init__.py` function:

Replace this:
```py
def __init__(self, f: Callable[Concatenate[type[_T], _P], _R_co], /) -> None: ...
```

With:
```py
def __init__(self, f: Callable[..., _R_co], /) -> None: ...
```

Then the error goes away.

It looks like Concatenate is always resolving to `[]` on my machine and therefore always expects zero arguments.

My typesheds in VS Code come from:
```
.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/builtins.pyi
``

But the same errors also happen in CLI which is installed by
```
pyright==1.1.358
```

**Comment by sam-goodwin** [comment]
`PyLance` is complaining about `Concatenate[type[_T], _P]`

Expected type expression but received "_ExtensionsSpecialForm"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)

**Comment by sam-goodwin** [comment]
Another monkey patch that fixes my problem is to import `Concatenate` from `typing` instead of `typing_extensions` in `builtins.pyi`.

Got the idea from: https://github.com/python/typing_extensions/issues/48

**Comment by erictraut** [comment]
It sounds like something in your current environment is corrupt. Have you tried creating a clean virtual environment as I suggested above? 

Do you have a typing-extensions stub library installed? Those would override the stubs that ship with pyright or pylance.

**Comment by sam-goodwin** [comment]
Perhaps I misunderstood what you meant by clean environment. I cleaned it but re-produced it from my `requirements.txt`.

See here:
https://gist.github.com/sam-goodwin/6834dd69cb7a18d642f37b11a39d6918

If I dial this back to just `pyright` and no other dependencies, I do indeed see the error go away. Thanks for the lead, I will clean up my dependencies and try and zero in on the culprit.

**Comment by sam-goodwin** [comment]
Tracked it down to `include = ["py.typed"]` in a transitive dependency. I am depending on this `packyak` package (which I own). Removing the `py.typed` from the wheel fixes the problem. 

https://github.com/sam-goodwin/packyak/blob/fd882ec3252aba6894c4f61d74c12e1f0bbe1a03/pyproject.toml#L7
