### ISSUE TITLE
Error assigning members in a `__new__` function

### ISSUE THREAD

**Issue by gpanago** [microsoft/pyright#7668]
The following code gives an error on the assignment on `foo`: `Cannot assign member "foo" for type "A*"`

```
class A:
    def __new__(cls, foo):
        obj = object.__new__(cls)
        obj.foo = foo
        return obj
```

This is definitely valid python code and will run without errors. While it is customary to initialize a class in the `__init__` method, there are edge cases where using just a `__new__` function is preferred. AFAIK the standard does not prevent this (but I apologize in advance if it does).

Adding the following member function makes the error go away, which I think is a bit counterintuitive:

```
class A:
    def __new__(cls, foo):
        obj = object.__new__(cls)
        obj.foo = foo
        return obj

    def func(self):
        self.foo = 0
```

**VS Code extension or command-line**
Latest VS Code extension (pyright 1.1.358)

**Comment by erictraut** [comment]
This is an intentional design decision, not a bug.

If you want to use this pattern, you should declare the variable within the class body.

```python
class A:
    foo: int

    def __new__(cls, foo: int):
        obj = object.__new__(cls)
        obj.foo = foo
        return obj
```

**Comment by gpanago** [comment]
Well, ideally you would do that in a stub, but AFAIK pyright does not scan the stubs while error tagging the implementation yet (is this planned for the future?). Adding something like this:

```python
class A:
    foo: int
    def __new__(cls: type[A], foo: int) -> A: ...
```

in a stub file does not make the error go away. In my situation, this class is a generic class, and the `foo` variable's type depends on that generic. The pattern you are suggesting would require me to using generics in the implementation file.
