### ISSUE TITLE
Support exhausted matching on enums

### ISSUE THREAD

**Issue by thomascobb** [microsoft/pyright#767]
**Describe the bug**
Mypy supports exhaustive matching on Enums, so if an entry is added later and not checked, it will show an error. An example is https://github.com/python/mypy/issues/6366#issuecomment-560369716

**To Reproduce**
1) Create a new file with the text:
```python
from enum import Enum
from typing import NoReturn


class SomeEnum(Enum):
    VALUE1 = 1
    VALUE2 = 2
    VALUE3 = 3


def assert_never(x: NoReturn) -> NoReturn:
    """Used to cause Mypy to catch impossible cases."""
    # https://github.com/python/mypy/issues/6366#issuecomment-560369716
    assert False, "Unhandled type: {}".format(type(x).__name__)


def func1(a: SomeEnum):
    if a == SomeEnum.VALUE1:
        pass
    elif a == SomeEnum.VALUE2:
        pass
    else:
        assert_never(a)
```
pyright correctly gives an error for a: `Argument of type "Literal[SomeEnum.VALUE3]" cannot be assigned to parameter "x" of type "NoReturn" in function "assert_never". "Literal[SomeEnum.VALUE3]" is incompatible with "NoReturn"Pyright (reportGeneralTypeIssues)`

2) Change `a ==` to `a is`. pyright gives an error for a: `Argument of type "SomeEnum" cannot be assigned to parameter "x" of type "NoReturn" in function "assert_never". "SomeEnum" is incompatible with "NoReturn"Pyright (reportGeneralTypeIssues)`

3) Comment out `VALUE3 = 3`. pyright gives an error for a: `Argument of type "Never" cannot be assigned to parameter "x" of type "NoReturn" in function "assert_never". Type "Never" cannot be assigned to type "NoReturn"Pyright (reportGeneralTypeIssues)`

**Expected behavior**
1) This is correct
2) pyright should give the same error as in 1)
3) pyright should not give an error

**VS Code extension or command-line**
VS Code extension v1.1.46 

**Additional context**
Thanks for https://github.com/microsoft/pyright/issues/653 , Enum support is really good now!

**Comment by erictraut** [comment]
Thanks for the suggestion. I didn't know that mypy supported this special use of NoReturn. I've added the same for Pyright. It can be used for all forms of type narrowing, not just for enums. For example:

```
def func2(val: Literal["a", "b"]):
    if val == "a":
        pass
    elif val == "b":
        pass
    else:
        assert_never(val)


def func3(val: Union[str, int]):
    if isinstance(val, str):
        pass
    elif isinstance(val, int):
        pass
    else:
        assert_never(val)
```

**Comment by erictraut** [comment]
This is now implemented in version 1.1.47, which I just published.

**Comment by thomascobb** [comment]
Thanks for the quick response! I can confirm that pyright now understands the NoReturn trick. However, if I change `a == SomeEnum.VALUE1` to `a is SomeEnum.VALUE1` then the type narrowing doesn't occur. Shall I open a new issue for that?

**Comment by erictraut** [comment]
Yeah, that's a separate issue. Currently, type narrowing supports "is" and "is not" operators only for None values, since that's the most common pattern. I didn't realize you could use "is" in place of "==" for other types. Is there a difference between the two?

**Comment by erictraut** [comment]
My general philosophy for type narrowing support is to support the most common expression types and calls and not the more esoteric ones. Each one requires hand-coded logic and adds complexity. Since no one else has requested this broader support for "is" previously, I will likely not add it unless/until it is upvoted — especially given that there's such an easy workaround.

**Comment by thomascobb** [comment]
Thanks for that, I've added a new issue #779 with details on the differences so others can add upvote it if they want
