### ISSUE TITLE
Not equal operator <> syntax (Python 2)

### ISSUE THREAD

**Issue by ypapouin** [microsoft/pyright#768]
**Describe the bug**
When the "<>" operator is detected by Pyright, "Expected expression"is displayed.
All next code is unreachable.

**To Reproduce**
Open a python 2 file that include the `<>` operator in a function.

**Expected behavior**
`<>` was a valid `not equal` operator on python2, it should be supported.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/22446243/85855622-d6915100-b7b6-11ea-8c45-db1c8fda4cff.png)

**VS Code extension or command-line**
1.1.26

**Comment by erictraut** [comment]
Sorry, Pyright doesn't support Python 2, and we have no plans to add such support.

**Comment by erictraut** [comment]
Actually, it would be easy to have the parser do a better job if it sees the "<>" token. It will need to report an error since this is illegal in Python 3, but it would at least avoid the cascade of errors that follows.

**Comment by erictraut** [comment]
This is now addressed in version 1.1.47, which I just published.
