### ISSUE TITLE
Constants type checking

### ISSUE THREAD

**Issue by yatima1460** [microsoft/pyright#77]
```python3
value = 10 #pyright: const
...
value = 3 #error here
```

Or something similar and Pyright will emit an error if the value is changed across the program

**Comment by Yatima1460** [comment]
Maybe even a variable that can be assigned only once would be interesting like:

```python3
value = otherfunction() #pyright: once
...
value = 3 #error here
```

**Comment by erictraut** [comment]
As far as I'm aware, there's currently no standard way in the Python spec to annotate variables as constant. 

I'll think about this more, but I'm not in favor of introducing pyright-specific syntax, even if it's in comments.

**Comment by Yatima1460** [comment]
The only thing I can think that can add this without a comment is a config option like:

`python.uppercasevariablesareconstants = True`

**Comment by erictraut** [comment]
I like that idea! It's consistent with the PEP 8 naming conventions, and most Python code already follows that convention.

**Comment by silviogutierrez** [comment]
What about https://mypy.readthedocs.io/en/latest/final_attrs.html from typing_extensions?

Or does this checker aim not to use typing_extensions?

**Comment by Yatima1460** [comment]
@silviogutierrez Didn't know about Final, it seems experimental

mypy examples shows:
```python
DEFAULT_ID: Final = 0
BORDER_WIDTH: Final = 2.5
//etc
```
Isn't this too repetitive?
Uppercase variables should always be constants according to PEP8

**Comment by Yatima1460** [comment]
Their only good point is:

> A final attribute declared in a class body without an initializer must be initialized in the __init__ method (you can skip the initializer in stub files):
```python
class ImmutablePoint:
    x: Final[int]
    y: Final[int]  # Error: final attribute without an initializer

    def __init__(self) -> None:
        self.x = 1  # Good
```

It's somewhat like references as class fields in C++, not bad 
This is the only reason why I would support Final in Pyright

**Comment by erictraut** [comment]
I think it makes sense to implement support for Final, but I still like @Yatima1460's suggestion for treating upper-case names as constants. The latter would need to be optional (off by default).

**Comment by erictraut** [comment]
This is now implemented in version 1.0.27, which I just published.

**Comment by karolzlot** [comment]
> but I still like @yatima1460's suggestion for treating upper-case names as constants. The latter would need to be optional (off by default).

How to enable this check in `settings.json`:

```
"python.analysis.diagnosticSeverityOverrides": {
    "reportConstantRedefinition": "error"
},
```

**Comment by erictraut** [comment]
@karolzlot, there is now a standard way to specify constants in Python typing. Refer to [PEP 591](https://peps.python.org/pep-0591/) for details. Pyright has full support for this PEP.
