### ISSUE TITLE
useLibraryCodeForTypes has been specified in both the config file and the client settings—in LSP

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#7734]
"The useLibraryCodeForTypes has been specified in both the config file and the client settings. The value in the config file (false) will take precedence"

Getting this error with the LSP even though I'm passing no configuration to PyRight.  Is there a way to debug this?

```lua
        lspconfig.pyright.setup {
            settings = {
                pyright = {
                    disableOrganizeImports = true,
                    disableTaggedHints = true
                },
                python = {
                    analysis = {
                    }
                }
            },
            on_attach = on_attach,
            capabilities = capabilities
        }
```

**Comment by erictraut** [comment]
I'm not sure what you mean by "I'm passing no configuration to pyright". Pyright configuration files (either "pyrightconfig.json" or "pyproject.toml") are automatically discovered by pyright. There's no need to "pass them" to pyright. I'm guessing that you have a configuration file present.

If you have questions about how to build and debug pyright, please refer to [this documentation](https://microsoft.github.io/pyright/#/build-debug?id=debugging-pyright).

**Comment by NeilGirdhar** [comment]
Sorry, what I mean is that my client settings are empty as shown in the question.  Yes, I have a configuration, and I'm happy that it's being used.  I just don't see where the client settings could be coming from if it's not the one I actually passed?
