### ISSUE TITLE
None check be invalidity within the def or lambda within the for loop

### ISSUE THREAD

**Issue by KarisAya** [microsoft/pyright#7752]
**Describe the bug**
None check be invalidity within the def or lambda within the for loop

**Code or Screenshots**
```python
from collections.abc import Callable

func_dict: dict[str, Callable] = {}
key_list: list[str] = []

for key in key_list:
    func = func_dict.get(key)
    if func:
        f = lambda: func() #Object of type "None" cannot be called
```

**VS Code extension or command-line**
vscode 1.88.1 
Pylance v2024.4.1

**Comment by erictraut** [comment]
This is working as designed, so I don't consider it a bug. See [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=narrowing-for-captured-variables) for details.

In general, a type checker cannot retain a narrowed type for a variable that is captured by an inner scope. Pyright has some sophisticated logic to determine whether that captured variable is modified on any code path in the outer function after it is captured. If it's able to prove that no such code path exists, it retains the narrowed type in the inner scope. However, in your example, `func` is being modified in a loop in the outer scope, so this condition cannot be proven, and it's not safe for the type checker to retain the narrowed type within the lambda.

You can avoid this problem your code by introducing a temporary variable.

```python
    if func:
        temp = func
        f = lambda: temp()
```
