### ISSUE TITLE
Tagged union boolean discriminant

### ISSUE THREAD

**Issue by 0e4ef622** [microsoft/pyright#7753]
**Describe the bug**
Using a boolean as the tag in a union requires `== True` to narrow.

**Code or Screenshots**

```python
from typing import Literal

def f(v: tuple[str, Literal[True]] | tuple[None, Literal[False]]):
    if v[1]:
        reveal_type(v[0])  # Type of "v[0]" is "str | None"

    if v[1] == True:
        reveal_type(v[0])  # Typye of "v[0]" is "str"
```

**VS Code extension or command-line**
```
$ pyright --version
pyright 1.1.359
```

**Comment by erictraut** [comment]
Pyright is working as intended here, so this isn't a bug. See https://github.com/microsoft/pyright/issues/6113.

You can use `==` or `is`, but you can't use a truthy/falsy check if you want pyright to narrow the type in this case.
