### ISSUE TITLE
Prebuilt node install fails - v22.0.0 not found

### ISSUE THREAD

**Issue by monkpit** [microsoft/pyright#7762]
Using pyright v1.1.360 has started failing for me today in my CI pipeline with the following error:

```
 * Install prebuilt node (22.0.0) .Failed to download from https://unofficial-builds.nodejs.org/download/release/v22.0.0/node-v22.0.0-linux-x64-musl.tar.gz
 ```
 
 When I follow the link, it indeed does not exist. It looks like this version of node was [released today](https://nodejs.org/en/about/previous-releases)

I am caching pyright in a private repository to avoid issues like this, but I can't avoid this one since it seems to be done at runtime. 

For reference, the command in my CI environment is: `pyright . --venvpath <path>`, and pyright is installed in a previous step using `poetry`.

Can anyone reproduce this? Are there any workarounds? Can I override the version of node that pyright is asking for via a flag?

**Comment by erictraut** [comment]
Pyright requires that you have node installed already.

I'm guessing that you're using the [community-maintained Python wrapper for pyright](https://github.com/RobertCraigie/pyright-python), which automatically installs node if needed.

In any case, this isn't a bug in pyright itself.

**Comment by monkpit** [comment]
Thanks for the quick response! I'll move the discussion there.
