### ISSUE TITLE
Infinite loop (and OOM later) with datetype library

### ISSUE THREAD

**Issue by minmax** [microsoft/pyright#7786]
I try to use [`datetype`](https://github.com/glyph/DateType) library, but pyright going wild.

It consume all available memory (for the node) and eventually crashes with

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

Lib source code: https://github.com/glyph/DateType
Used lib version: datetype==2024.2.28
Pyright version: 1.1.360

Minimal code to reproduce:
```python
from datetype import AwareDateTime
from datetime import datetime

def foo(d: AwareDateTime):
    pass

foo(datetime.now())
```

Also if run pyright on https://raw.githubusercontent.com/glyph/DateType/trunk/src/datetype/__init__.py
it will also fail with an OOM.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.361, which I just published.
