### ISSUE TITLE
`builtins.print` and `builtins.input` are not instances of `types.BuiltinFunctionType`?

### ISSUE THREAD

**Issue by IAmREGE** [microsoft/pyright#7788]
**Describe the bug**
The title said it.  
As both `type(print)` and `type(input)` output `<class 'builtin_function_or_method'>`, `__import__("types").BuiltinFunctionType` also outputs `<class 'builtin_function_or_method'>`, so `print` should be able to be assigned to a variable declared with type `types.BuiltinFunctionType`.  
BTW, `BuiltinFunctionType` in `Lib/types.py` is defined as: `BuiltinFunctionType = type(len)`.

**Expected Behaviour**
No errors output, just like runtime:
```
<built-in function print>
<built-in function input>
```
Execute both `isinstance(print, types.BuiltinFunctionType)` and `isinstance(input, types.BuiltinFunctionType)` in an interactive Python Shell returns `True`.

**Actual Behaviour**
It outputs:
```
Untitled-1.py:2:38 - error: Expression of type "Overload[(*values: object, sep: str | None = " ", end: str | None = "\n", file: SupportsWrite[str] | None = None, flush: Literal[False] = False) -> None, (*values: object, sep: str | None = " ", end: str | None = "\n", file: _SupportsWriteAndFlush[str] | None = None, flush: bool) -> None]" is incompatible with declared type "BuiltinFunctionType"
    "function" is incompatible with "BuiltinFunctionType" (reportAssignmentType)
```
Even if I replace `print` with `len` on Line 2, it keeps complaining:
```
Untitled-1.py:2:38 - error: Expression of type "(obj: Sized, /) -> int" is incompatible with declared type "BuiltinFunctionType"
    "function" is incompatible with "BuiltinFunctionType" (reportAssignmentType)
```

**Code or Screenshots**
**`Untitled-1.py`**
```python
  import types
  io_func: types.BuiltinFunctionType = print
  print(io_func)
  io_func = input
  print(io_func)
```

**VS Code extension or command-line**
Pyright 1.1.360, installed from pacman.

**Comment by erictraut** [comment]
Pyright's behavior is correct here and in compliance with the Python static type system. 

You are confusing static typing with the internal objects that are used to implement type annotations at runtime. These are not the same. Please do not file any more bug reports of this nature.

To understand the static type system in Python, refer to [this site](https://typing.readthedocs.io/en/latest/). You may also find [pyright's documentation](https://microsoft.github.io/pyright/#/getting-started) useful.
