### ISSUE TITLE
`reportMissingTypeStubs` default value is incorrect in some places

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#7789]
i'm not sure what the correct defaults are supposed to be, but there are several places where the default values for this rule don't match:

- here it says the default value is `"none"` (i'm assuming this means the default for the "standard" type checking mode): https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingTypeStubs
- here it says the default for the `"basic"` and `"standard"` type checking modes is `"warning"`: https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-settings-defaults
- in the json schema, it says the default is `"warning"`:
  https://github.com/microsoft/pyright/blob/695062234796983c49bb3530f61a6151eb217078/packages/vscode-pyright/schemas/pyrightconfig.schema.json#L206-L210
- in reality, the default for both of them is `"none"`:
  https://github.com/microsoft/pyright/blob/695062234796983c49bb3530f61a6151eb217078/packages/pyright-internal/src/common/configOptions.ts#L626
  https://github.com/microsoft/pyright/blob/695062234796983c49bb3530f61a6151eb217078/packages/pyright-internal/src/common/configOptions.ts#L728

----

currently the options are defined/documented in several different spots, which is redundant and is prone to issues like this. maybe there should be a single schema that's used to generate all the docs, schemas, and validation for all of them? maybe something like [zod](https://github.com/colinhacks/zod)

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.361, which I just published.

**Comment by fannheyward** [comment]
Hello, `reportInvalidTypeForm` has the same issue:

- https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportInvalidTypeForm is `error`
- https://github.com/microsoft/pyright/blob/3af2bbc1f8087286343a349cebfd7ef0beea18a7/packages/vscode-pyright/schemas/pyrightconfig.schema.json#L200 is `warning`
- https://github.com/microsoft/pyright/blob/3af2bbc1f8087286343a349cebfd7ef0beea18a7/packages/vscode-pyright/package.json#L274-L280 is `error`
