### ISSUE TITLE
Private member access

### ISSUE THREAD

**Issue by Yatima1460** [Microsoft/pyright#78]
I don't know if this is exactly in the scope of Pyright but I will suggest it anyway:

Pyright should output an error or warning (if strict mode is enabled or not) when accessing the private member of a class with _variable

here types are not even read but maybe it's right to think that "_variable" has also the type of being "private"

**I noticed that only double underscore variables are an error so maybe a warning for single underscore is nice**

**Comment by erictraut** [comment]
Funny you should ask about this. I just added this feature in the latest version (1.0.14), which was published yesterday. :) 

The [config setting](https://github.com/Microsoft/pyright/blob/master/docs/configuration.md) is called "reportPrivateUsage".
