### ISSUE TITLE
Regression: Using PEP-695 type variables causes scoping issues

### ISSUE THREAD

**Issue by bryanforbes** [microsoft/pyright#7800]
**Describe the bug**
Given the following code:

```python
from __future__ import annotations

from typing import Protocol


class Patcher(Protocol):
    def object[T](self, target: object, attribute: str, new: T) -> T: ...
```

The following error is produced:

```
blah.py:7:33 - error: Expected type expression but received "(self: Self@Patcher, target: ..., attribute: str, new: T@object) -> T@object" (reportGeneralTypeIssues)
```

If I remove the type variable, I can use `object` as a type. This was not an issue in 1.1.359.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool?
Command line

Which version?
1.1.360

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.361, which I just published.
