### ISSUE TITLE
hover type for `type` of type aliases is incorrect

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#7806]
```py
Foo = int

def foo(a: type[int], b: type[Foo]):
    a # (parameter) a: type[int]
    b # (parameter) b: Foo
```
![image](https://github.com/microsoft/pyright/assets/57028336/1c576008-309d-481d-9171-e60311af69b0)
![image](https://github.com/microsoft/pyright/assets/57028336/e5e81af0-e0ac-4a19-9b4e-20efd5c27bd7)

when hovering over `b`, the type should be `type[Foo]` (or `type[int]`, if it's supposed to resolve the type alias to its original type)

`reveal_type` on both of them behaves correctly and returns `type[int]`

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.361, which I just published.
