### ISSUE TITLE
Type option of tuple entry not removed after check

### ISSUE THREAD

**Issue by TuNeXiZz** [microsoft/pyright#7808]
Minimal example:
```
foo = 5

def test_func(x: None|int) -> tuple[int | None]:
    return (x,)

bar = test_func(foo)
if None not in bar:
    reveal_type(bar)
if bar[0] is not None:
    reveal_type(bar)
    
def test_func2(x: None|int) -> int | None:
    return x

bar2 = test_func2(foo)
if bar2 is not None:
    reveal_type(bar2)
```
Behavior:
The reveal_type of bar both still see bar as type tuple[int | None] although their  checks in the respective lines above rule out the option of the tuple entry being None.
For bar2 it works as expected and the reveal_type(bar2) only shows int instead of int | None.

Question:
Why is the expected type of the tuple entry not adjusted after the check as if it where a single value? Is there a better way to get Pylance to recognize that the tuple entry can't be None than to explicitly use the cast function of the typing module?

**Comment by erictraut** [comment]
The first two cases are not supported type guard patterns in pyright (the type checker upon which pylance is based). They're also not supported by other Python type checkers like mypy.

For a full list of type guard patterns supported by pyright, see [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards).

You can make this work by adding an overload definition for `test_func`.

```python
@overload
def test_func(x: None) -> tuple[None]: ...
@overload
def test_func(x: int) -> tuple[int]: ...
def test_func(x: None | int) -> tuple[int | None]:
    return (x,)
```

**Comment by erictraut** [comment]
We do occasionally add support for new type guard patterns, but the bar is high. Each new pattern requires customized logic which can also affect overall analysis performance. We therefore add support for new patterns only after there is clear signal that it's a common pattern. This particular pattern hasn't been requested before, so there's no (yet) enough justification to add such support. 

I'm going to close this feature request for now, but I'm willing to reconsider it in the future if there's additional signal from pyright users in the form of upvotes on this issue.

**Comment by TuNeXiZz** [comment]
Thank you @erictraut for the quick reply and pointing me to the documentation of type guard patterns. Unfortunately, this leaves me even more confused, as the two cases I showed in my example seem to be supported by the type guard according to the documentation:
![image](https://github.com/microsoft/pyright/assets/79518940/cd383702-10b0-4271-a06f-ef1a0632b687)
and
![image](https://github.com/microsoft/pyright/assets/79518940/3f13ccea-a4a1-4d00-a326-77acc9bdf478)
Am I missing something?

**Comment by erictraut** [comment]
The first of these patterns (`x[I] is B`) narrows a union of tuples. 

```python
def func1(x: tuple[int] | tuple[None]):
    if x[0] is None:
        reveal_type(x)  # tuple[None]
    else:
        reveal_type(x)  # tuple[int]
```

It doesn't perform "tuple expansion" for a tuple that contains union elements (i.e. it doesn't expand `tuple[int | None]` into `tuple[int] | tuple[None]`). This is why I suggested that you use an overload above.

The second pattern (`x in y`) isn't applicable in your case because it narrows the type of `x`, not `y`. Here's an example of how it works:

```python
def func2(x: int | None):
    if x in (1, 2, 3):
        reveal_type(x)  # Literal[1, 2, 3]
```
