### ISSUE TITLE
Preceding `if isinstance: reveal_type` calls influence later `if issubclass: reveal_type` result.

### ISSUE THREAD

**Issue by randolf-scholz** [microsoft/pyright#7821]
[pyright-playground](https://pyright-play.net/?pyrightVersion=1.1.361&strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgGoCGIANFCMQG7HkA2A%2BvAsQFCiRQDGYZs2L8YSMCgDOAOnIAjfpmy58AWXIJk6LlwDSUALyESFEAAoARHssBKfQCYjJzmat6HdrqWdFXlK1IvUidjPzIAyxCvLn5mcikpKAAxMDBzDS1UNABtPSpSAF1bAC4uKAqoABNiYChWVnAQBvMpYmZgGjAYAAtiEBKoTO1cjxoQwpoAelsoAFoAPihLVLA8gB8xqFJ1icsyysPMOqQpVCkYchR%2BYnNuvuooNo6ZBriEqQbS8qPfukYWOwSHdev1ZlAAMTLADK7WAAAFVnlEWlxiiwIVLD8-uRTsQoAA5boASWwIggxBQMGIVQAoiAmrp3okoAAhALDbJ5ArFA6VGp1BpNFrPTpQe79Qac9B5BzjByTKAzeZLSzskAbLY7PZ835IE5naSXa63CWPDi3UW2b6-P4MJhsC0gh7gqGWWEdeHq5HqtHqzHYo4gXFtQkksnEClUmn0xmxeIs9kALwymhG3KKNv5tXqjVwIrhXVBAyGaa5WoV01mi2Wyc1cu2uwV%2B0Dh31mESAFdFAmpOYnWbbDQnVas7bKv8HUDOM6wRU3dLRg54UL86x5Su881WAHx8G8WGYKSEOTKdS6QzcEze1AAIqdgAeqayMvymd11Rzq%2B3rUL4uLUplq%2BDYTFWKrLPeD71uMTaYh%2BbYGucxo3LOjyiq8rDMp8rBjuOtD2oCA7Fq6MJwvCkHIpBaKQbutrtqcSFXChZrDsCo7wbak6EcCg7zqRnoUXo5GPtRj60XqBpSN2WH9jxxGsTO7GtpxBGOnJLp8e6ZGCcJD6iQ%2BhRQOsd6PpRInbLphQAFRGaWL5Lpuwrrtsy7fg04lBiG%2BJEkeEZRuesZXkAA)

[mypy-playground](https://mypy-play.net/?mypy=latest&python=3.12&gist=4021719ec06474dde0edc6b201fc6afd)

```python
from typing import TypeVar, reveal_type
from collections.abc import Mapping

K = TypeVar("K")
K2 = TypeVar("K2")
V = TypeVar("V")
V2 = TypeVar("V2")

class Foo(Mapping[K,V]):
    def __ror__(self, other: Mapping[K2, V2], /) -> "Foo[K|K2, V|V2]":
        if isinstance(other, self.__class__):
            reveal_type(other)  # "Self@Foo[K@Foo, V@Foo]"
        raise NotImplementedError

class Bar(Mapping[K,V]):
    def __ror__(self, other: Mapping[K2, V2], /) -> "Bar[K|K2, V|V2]":
        if isinstance(other, type(self)):
            reveal_type(other)  # "Self@Bar[K@Bar, V@Bar]"
        raise NotImplementedError

class Baz(Mapping[K,V]):
    def __ror__(self, other: Mapping[K2, V2], /) -> "Baz[K|K2, V|V2]":
        if issubclass(type(other), type(self)):
            reveal_type(other)  # "Mapping[K2@__ror__, V2@__ror__]"
        raise NotImplementedError

class Qux(Mapping[K,V]):
    def __ror__(self, other: Mapping[K2, V2], /) -> "Qux[K|K2, V|V2]":
        if isinstance(other, self.__class__):
            reveal_type(other)  # "Self@Qux[K@Qux, V@Qux]"
        if isinstance(other, type(self)):
            reveal_type(other)  # "Self@Qux[K@Qux, V@Qux]"
        if issubclass(type(other), type(self)):
            reveal_type(other)  # "Self@Qux[K@Qux, V@Qux] | Qux[K@Qux, V@Qux]* | Mapping[K2@__ror__, V2@__ror__]"
        raise NotImplementedError
```

In the last example, there is an unexpected result `"Self@Qux[K@Qux, V@Qux] | Qux[K@Qux, V@Qux]* | Mapping[K2@__ror__, V2@__ror__]"` which is suddenly different from result `"Mapping[K2@__ror__, V2@__ror__]"` we get without the preceding `isinstance`+`reveal_type` calls.

---

Additionally, 3 questions:

1. Why does `issubclass` not narrow the type in the 3rd class? If we instead do the following, we get the `Self` type:

 ```python
class Mox(Mapping[K,V]):
    def __ror__(self, other: Mapping[K2, V2], /) -> "Mox[K|K2, V|V2]":
        other_cls = type(other)
        self_cls = type(self)
        if issubclass(other_cls, self_cls):
            reveal_type(other_cls)  "type[Self@Mox[K@Mox, V@Mox]]"
        raise NotImplementedError
```

2. In Example ②, when we do `isinstance(other, type(self))` it narrows `other` to `"Self@Bar[K@Bar, V@Bar]"`, which I assume means `Self`, i.e. `Bar` (or subtype) with the generics bound to the same value as for the instance `self`. Is this for pragmatic reasons? Because formally, it seems `Bar[Unknown, Unknown]` would be correct. (I guess we have an issue because generic `Self` is not supported, so one cannot "unbind" the typevars).

3. How would you narrow `other` to `Bar[K2, V2]`? Is it only possible with `cast`?

**Comment by erictraut** [comment]
Pyright is working as intended here, so I don't consider this a bug. Type narrowing can affect downstream types.

To answer your other questions:
1. There is no type narrowing in your third example because the argument to `issubclass` is the expression `type(other)` which is not a narrowable expression. For details about narrowable type expressions, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-narrowing).
2. Yes, your assumption is correct.
3. `if isinstance(other, Bar)`

**Comment by randolf-scholz** [comment]
> Pyright is working as intended here, so I don't consider this a bug. Type narrowing can affect downstream types.

But we are not in an else clause, and the preceding if clauses contain nothing that would influence later code. So how can these `if isinstance` calls logically have any effect on later type inference?


```python
if isinstance(A, Typ):
    pass
# What do we know about A at this point, that we didn't know before?
```
