### ISSUE TITLE
TypeVar/ParamSpec cannot work in the context of a Callable annotation

### ISSUE THREAD

**Issue by lkct** [microsoft/pyright#7825]
**Describe the bug**
See the code example below. The bug arises when a Callable is used with TypeVar/ParamSpec. However, the Callable should suffice as the context of the type vars, similar to something like `def func(x: T) -> T:`.
BTW, mypy is ok with this example.

**Code or Screenshots**
```python
from collections.abc import Callable
from typing import Any, ParamSpec, TypeVar

T = TypeVar("T")
P = ParamSpec("P")

func: Callable[[T], T] = lambda x: x
# Type variable "T" has no meaning in this context

# --------

decorator: Callable[[Callable[P, T]], Callable[P, T]] = lambda x: x
# ParamSpec "P" has no meaning in this context
# Type variable "T" has no meaning in this context
# Expression of type "(x: (...) -> Unknown) -> ((...) -> Unknown)" is incompatible with declared type "((**P) -> T) -> ((**P) -> T)"

@decorator
def wrapped(x: int) -> int: return x
# Argument of type "(x: int) -> int" cannot be assigned to parameter of type "(**P) -> T"
```

**VS Code extension or command-line**
I'm using vscode with pylance but it's also reproducible through Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBAxmA28CmMAuBLMA7AzgOgEMAjGKdCABzBFSgGEDFjkBYAKFEilQE8L0sAczKVqtAIJYeAGigAFAiAIQAyhRSyAKnyQA1Re3aaoAXijb1%2BkAAoARJtsBKdnNPzFytSjtynhjgCuWDAAXPSM8MxIANrRmgC6WvFukRBEACYEUAAeYdnsAMTmOlAAboroUVD2tlAAFgQ4UFhgUBBIBFgCwgLcdehNcFioSNmo-kUAtNMz0-7pKNQEqNRhDExEyLHrkZsxckmJ4RtbB%2BbxyWapGVm5OYXuSqrqpLa%2B9Y3Nre2d3WRYfQGsGwIzGDwsSDKFSqNQ%2BTRabQ6XSE-0BgxBo3GbCKAFFshQQEgcDhMACwMBuCVbNY7tY8PTHFBJgA%2BKAAVSwAGsWgB3LCMllQax0hlM1kc7lgPmOWpAgRwSjLdB7KA89CoOpQBYwSKE9KU9TVYUAKmNcgFrM0FqF1lN5rF5hl-gAAtqlisQOwFhSeUoKOp0jSwgJUNaQ2FCagAiAAflsVBxCBBAF2sMoOSDZDqXcQ2HhrUYJ0WrQiJDGiTBFgkPqVlAKB52iMQOmKbxDdS7daHOwgA)

**Comment by erictraut** [comment]
Pyright is working correctly here and [in accordance with the typing spec](https://typing.readthedocs.io/en/latest/spec/generics.html#scoping-rules-for-type-variables). TypeVars and ParamSpecs can be used only within the scope of a `def` statement, a `class` statement, or a type alias definition. They cannot be scoped to a variable definition. If you want to define a generic callable, you need to use a callback protocol.
