### ISSUE TITLE
update typeshed to support redis-py 3.5.x

### ISSUE THREAD

**Issue by jaypaik** [microsoft/pyright#783]
**Describe the bug**
`HMSET` is [deprecated](https://redis.io/commands/hmset), and `HSET` with a mapping arg should be used instead. The currently bundled typeshed stubs don't allow for a mapping kwarg to be passed to `hset`.

It looks like the update to support this made it into typeshed a couple days ago: https://github.com/python/typeshed/pull/4293

Could you update to the latest version of typeshed in the next release?

**To Reproduce**
1. Install redis-py@3.5.3
2. Attempt to pass a mapping to `hset`.
3. See error.

**Expected behavior**
No error.

**Screenshots or Code**
![Screen Shot 2020-07-01 at 8 40 56 PM](https://user-images.githubusercontent.com/8624213/86314258-10f65600-bbdc-11ea-94ef-298a33b55cc0.png)

**VS Code extension or command-line**
Name: Pylance
Id: ms-python.vscode-pylance
Description: A performant, feature-rich language server for Python in VS Code
Version: 2020.6.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance

**Additional context**

**Comment by erictraut** [comment]
I've updated typeshed stubs to the latest found in the typeshed repos. This will be included in the next release of pyright.

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.49, which I just published.
