### ISSUE TITLE
Incorrect resolution for "type cannot be assigned to type"

### ISSUE THREAD

**Issue by qyloxe** [microsoft/pyright#7847]
This code:

```python
from typing import TypeVar, Type

T = TypeVar("T", bound="DBTable")


class DBTable:
    def __init__(self, tablename: str, aschema: str) -> None: ...


class DBTableUser(DBTable):
    def InitUsers(self) -> None:
        print("InitUsers")


class DBTableUser2(DBTable):
    def InitUsers2(self) -> None:
        print("InitUsers2")


# def GetTable(tablename: str, aschema: str, aclass: Type[T]) -> T: # THIS WORKS OK - without pylance error
def GetTable(tablename: str, aschema: str, aclass: Type[T] = DBTable) -> T:  # using default value to "aclass" makes pylance unhappy
    # This is the pylance message:
    # (parameter) aschema: str
    # Expression of type "T@GetTable | DBTable" cannot be assigned to declared type "T@GetTable"
    # Type "T@GetTable | DBTable" cannot be assigned to type "T@GetTable"PylancereportGeneralTypeIssues
    atable: T = aclass(tablename, aschema)
    return atable


def main() -> None:
    atable_user: DBTableUser = GetTable("user", "", aclass=DBTableUser)
    atable_user.InitUsers()
    atable_user2: DBTableUser2 = GetTable("user", "", aclass=DBTableUser2)
    atable_user2.InitUsers2()


main()
```

Assignment of `aclass` instantation to `atable` variable should work without errors, because the default parameter of `DBTable` is bounded as base class to `T` in `TypeVar` declaration.

When the default parameter is removed, everything is ok. Also calling `GetTable` with `aclass=DBTable` is also OK.

## Environment data

Pylance language server 2023.1.10 (pyright bbf0ae78) starting
VSCode windows, latest

**Comment by erictraut** [comment]
Are you really using version 2023.1.10 of pylance? That's well over a year out of date. Please update to the latest. 

I'm not able to repro the issue you're seeing with an up-to-date version of pylance or pyright.

Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgGoCGIANISQFB0FQC8tCZlAFAEQHc0AjMAFcUAE2bcAIgCEC5AQBti3AJQM6AY0XkAzrqiz5S4gC46US1DHFgUAPr3USGI867ii4DRgLlKcggzKF0Yaig9TQALYghyUxCw1SgAWgA%2BKAA5MBRggDoCjW09AyM-YgBVDxBOMpNVcytrWygASRQXKuIQXXdPYGT0rJyzCyarBBBUGB52zurdNSKdfUM5cq6QACZa9frGqxs7OZhN3R2PL0GM7NyD8ahJ6dmO04WtpYYAYma7AHFiDBjMpOL4TAEgglQuFIjE4lCwjRyMV9AkiOwANoEAC610ICR%2BBAAEq0AMpQADqAHkAEoAaXJVLpqSgAHcXFERPgEHAdChNMQoN1wCA6EcoACgeVQeUIcFoUjdNFYvFEjCUbo0SQsdiWGtgcQ8QQElAfsJdKgMEdyMJFPgAG7kRTCQUwMBQbjIlaLKBxADWxAMPL5Aqgoii5AQPLGlkJUSQBgTsBij155H5gqC%2BnIaFGTR%2BnAQlECgO6yVhKoRovzUAAogAPSaBi05KBgOzwdgeggAAUlBqgAB99eVuFBNOmUGB8AJBSUkGhcmJYO6bMUQMRl53Bbw%2B4CDdwY6a2Dve-3ykORyYxxOUFOZ3P9AulyvYCRu3updeAAppjMbnA8ABXIQCddFiFafQXV0I9yDBZQ0T1L0ShlcES0VZU4nUJoNxgYQQBQCJ4OIDRxTiVBODxW48ysODynsc1ugSOplE2PVzxMHhGJAfgPV45D9GYFjKmqbDaOIhjqjyE4zko2CJO4rZmL2Vjqi2dj92lbhuN47h%2BI1ISVJE7otjEyw6JMSSTOk14zh2dQGHIlA5LoIA)

**Comment by qyloxe** [comment]
@erictraut Thank you! After update to latest version of vscode AND pylance, the types are correctly resolved! Sorry, for the alert...
