### ISSUE TITLE
Building the server fails with missing worker_threads dependency

### ISSUE THREAD

**Issue by rchl** [microsoft/pyright#785]
**Describe the bug**
I've tried to build the server but it fails when trying to import `worker_threads`.

**To Reproduce**
1. `npm run install:all`
2. `npm run build:serverProd`

**Expected behavior**
Server builds successfully.

**Screenshots or Code**

```
ERROR in ./src/server.ts
Module not found: Error: Can't resolve 'worker_threads' in '/Users/me/workspace/lsp/pyright/server/src'
 @ ./src/server.ts 18:25-50
```

**Additional context**
I don't see the `worker_threads` dependency on NPM. Is it some internal dependency that wasn't published?

**Comment by jakebailey** [comment]
Pyright requires at least Node v12 to run, the first build to include worker threads without experimental flags. Is your node version too old?

**Comment by rchl** [comment]
Yes, I'm on v10. Will try v12, thanks. :)
