### ISSUE TITLE
Infer tuple size when using range in tuple comprehensions

### ISSUE THREAD

**Issue by JonathanPlasse** [microsoft/pyright#7851]
**Describe the bug**
Pyright does not infer the size of a tuple when using `range` in tuple comprehensions.
In the case when range can be known statically (i.e. using integer litterals), I would like that Pyright infer that a tuple have the size of the `range` iterator used in the tuple comprehension.

**Code or Screenshots**

```python
from typing import assert_type

a = assert_type(tuple(range(3)), tuple[int, int, int])
a = assert_type(tuple(i**2 for i in range(3)), tuple[int, int, int])
```

https://pyright-play.net/?pythonVersion=3.12&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCGAzkQKZ4D68CpAsAFAMFQC8hJ5MVipAFDAFcEAGz4gC6PgGYAlDIA0sIaIDaqGIvWaUMALoymrdmUrU%2BgkXyQAqawCYowXJkwoo4yb1kKlltTu0NVz0DeiA

Pyright 1.1.361

**Comment by erictraut** [comment]
Pyright is working as intended here; this isn't a bug.

Static type checkers have no special knowledge of `range` or any other function or class. They don't actually run the code. They simply use type information provided to them, and then they apply standardized rules based on that type information.

The symbol `range` is a class. When you call `range(3)`, the evaluated type is simply `range`. It has a method `__iter__` defined to return `Iterator[int]`. The number of iterations it supplies is an unknown quantity to pyright based on the type information it is provided.

I'll note that other static type checkers like mypy treat `range` the same way, and they evaluate the same type for tuple comprehensions.

If you want a tuple with a known length, you'll need to use a tuple expression: `(0, 1, 2)`. Or you can use an explicit cast.

**Comment by JonathanPlasse** [comment]
Thank you, I will use `(0, 1, 2)`, this is enough for my case.

**Comment by JonathanPlasse** [comment]
I tried what you suggested, but it does not work on Pyright 1.1.365.
```python
a: tuple[int, int, int] = tuple(i for i in (0, 1, 2))
```
https://pyright-play.net/?pythonVersion=3.12&code=IYLgBALgrgDgNgUwNoEsB2EA0Z1ZxgXTAF5JZEAKFMAMwHsAnHfMCgBmwEZsAmASj4AoIA
