### ISSUE TITLE
Type variable re-scoping doesn't work under certain circumstances with higher-order functions

### ISSUE THREAD

**Issue by LeeeeT** [microsoft/pyright#7867]
Prior to version [1.1.357](https://github.com/microsoft/pyright/releases/tag/1.1.357) the following code was type checked as I expected.

```python
from collections.abc import Callable


def d[T, R](c: Callable[[T], R]) -> Callable[[T], R]: ...


@d
def f[A, B](c: Callable[[list[A]], list[B]]) -> tuple[A, B]: ...


def id[T](value: T) -> T: ...


reveal_type(f(id))
```

The revealed type is `tuple[A@f, A@f]`.

Starting with version [1.1.358](https://github.com/microsoft/pyright/releases/tag/1.1.358), pyright is no longer able to determine the correct type of `f(id)`, it is now `tuple[Unknown, A@f]`. I presume the regression was introduced by #7630 or #7634.

A few observations:
- If you remove the `@d` decorator, it stops working on 1.1.357 either, although it doesn't change the type of the `f` function itself.
- Wrapping `A` and `B` in `list[]` (or any other generic) in the `f`'s signature prevents pyright from successfully re-scoping type variables; if you rewrite `f` as `def f[A, B](c: Callable[[A], B]) -> tuple[A, B]` it works.

I understand I'm in a gray area of the typing spec. Feel free to close this. 😔

**Comment by erictraut** [comment]
Closing this as "won't fix".
