### ISSUE TITLE
Type checks: failure to infer type in nested types

### ISSUE THREAD

**Issue by PabloLION** [microsoft/pyright#7869]
## Environment data
* Language Server version: 2024.5.1 (6 May 2024) Release, (pyright version 1.1.360, commit 4bc8428d) 
* OS and version: macOS 14.1.1 (23B81)
* Python version: brew installed python@3.12 3.12.2 64-bit

### Relevant config:

* python.analysis.typeCheckingMode: "strict"

## Code Snippet
Code sample in [pyright playground](https://pyright-play.net/?pythonVersion=3.13&code=GYJw9gtgBAxmA28CmMAuBLMA7AzldEADmCKlACZICOArkgFD3paoD6qAnoUuVALz4WACgCMASnoAjMAnZce-KNIRCAKiDoT6heAENmreOhxkBRk0IDa6ugBooAMV3wcSALoSd%2BrIeOoAdLqE3FjkahpInnoG5gFBIWHK8HLc5Fqx7DQ6SKzMplCxVkJ5KTz2NpH2xSyl5PZOLpEe9BmoWci5LIHBSKFC1WycqeURYhKt7Tl53Qn9JUNlSjLJC2npfpnZvqhIIM6KhZaiI5pVIvXOrmLNE1tGO3vwM71hx1AVYy0bbXfoD87PPpvJK1T70Si0HI-Dp5RQQuhFebyOrvUZVJHDRyXJoSeFQyadOI9IEYxYfXHUOibGFdeIvOY1Vb2EGrMF46k5e67fYCPFFc6o05QN4NK7NdnQzl-blPOlAgXk8GU-G-f6y4mvAUs5FjIA)

Pylance could not infer that `tuple[int, Literal[True]] | tuple[int, Literal[False]]` is same as `tuple[int, bool]`, with the following error:

```text
Argument of type "tuple[int, bool]" cannot be assigned to parameter "object" of type "tuple[int, Literal[True]] | tuple[int, Literal[False]]" in function "append"
  Type "tuple[int, bool]" is incompatible with type "tuple[int, Literal[True]] | tuple[int, Literal[False]]"
```

```python
from collections import deque

int_typed = int(1)
bool_typed = bool(True)

plain_list = list([True, False])
plain_list.append(True)
plain_list.append(bool_typed)

list_tuple_int = list([(int_typed, True), (int_typed, False)])
list_tuple_int.append((int_typed, True))
list_tuple_int.append((int_typed, bool_typed))

list_tuple_literal = list([(1, True), (1, False)])
list_tuple_literal.append((1, True))
list_tuple_literal.append((1, bool_typed))

deque_tuple_int = deque([(int_typed, True), (int_typed, False)])
deque_tuple_int.append((int_typed, True))
deque_tuple_int.append((int_typed, bool_typed))

deque_tuple_literal = deque([(1, True), (1, False)])
deque_tuple_literal.append((1, True))
deque_tuple_literal.append((1, bool_typed))
```

For `*_tuple_int`,`*_tuple_literal` (`*`=`list`/`deque`) `.append((int_typed, bool_typed))` is highlighted with the following type check above.

## Expected behavior

Pylance should infer that `tuple[int, Literal[True]] | tuple[int, Literal[False]]` is same as `tuple[int, bool]` and not highlight the type check error.

## Logs
Let me know if additional logs are required.

**Comment by erictraut** [comment]
Pyright is working as designed here, so this isn't a bug.

Pyright will elide redundant (equivalent) types in a union, but it will not combine unlike types into simpler type forms. It also doesn't perform expansion of tuples under most circumstances.

You can fix this trivially by adding an explicit type declaration. For example:
```python
list_tuple_int: list[tuple[int, bool]] = list([(int_typed, True), (int_typed, False)])
```

I'm not aware of any Python type checkers that do what you're looking for here. Discovering potentially-mergable tuples within a union would be very expensive in general. It's an O(n^2) operation which isn't bad when the union contains only two subtypes, but for large unions, this would be very costly. This would likely have a measurable impact on type analysis performance for some code bases, so adding such a feature (which is pretty esoteric) would be a bad tradeoff for the vast majority of pyright users. For that reason, I'm going to reject this enhancement request.

**Comment by PabloLION** [comment]
Thanks for the detailed explanation and I'm totally with you. I didn't think about the reason that deep nor about the implementation. Next time I'll try to be more careful when creating an issue.
