### ISSUE TITLE
aliases from other modules are incorrectly marked as deprecated when `deprecateTypingAliases` is enabled if the alias has the same name as a deprecated alias

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#7875]
```py
from collections.abc import Set as AbstractSet

def foo(a: AbstractSet[str]): # error: This type is deprecated as of Python 3.9; use "collections.abc.Set" instead
  pass
```
[playground](https://pyright-play.net/?strict=true&deprecateTypingAliases=true&enableExperimentalFeatures=true&reportCallInDefaultInitializer=true&reportImplicitStringConcatenation=true&reportImplicitOverride=true&reportMissingSuperCall=true&reportPropertyTypeMismatch=true&reportShadowedImports=true&reportUnnecessaryTypeIgnoreComment=true&reportUninitializedInstanceVariable=true&code=LAKAZgTg9gtgBAYygG2QUwQFwJZQHYDOAdAIYBGCc2MADlBJnAMpqMkFwCCZBmEJWFplAiQAEzRg4YKFAAUJAFxcefAZiEBtXhAC6ASmUBiOGgjQIygCoALbB0wBPGmiocJNCBhKY0YuOxwUFIACo6YNvhwAMxEAJwA3HAArgSuAERIqBg4%2BMTkCERC6VSEviRioHBwNOwEoEA)

`collections.abc.Set` is not deprecated, but it's incorrectly being treated as such because its alias has the same name as `typing.AbstractSet`

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.363, which I just published.
