### ISSUE TITLE
Improved type inference with ternary assignments

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pyright#7882]
**Is your feature request related to a problem? Please describe.**
For ternary assignments, pyright seems to prefer the type of the most rhs expression even if solving with the middle one would lead to a better / more precise outcome.

```py
from typing import Generic, TypeVar
_T = TypeVar("_T")

class Key(Generic[_T]): ...
class CustomDict:
    def __getitem__(self, key: Key[_T]) -> _T: ...
    def __setitem__(self, key: Key[_T], value: _T) -> None: ...

data = CustomDict()
KEY_SET: Key[set[str]] = Key()

s1 = data[KEY_SET]
reveal_type(s1)  # pyright can correctly infer this as `set[str]`

s2 = data[KEY_SET] = set()
s3 = data[KEY_SET] = {"a", "b"}
reveal_type(s2)  # here it's `set[Unknown]` from the rhs expr
reveal_type(s3)  # this again is `set[str]` from the rhs expr
```

```py
  test.py:13:13 - information: Type of "s1" is "set[str]"
  test.py:17:13 - information: Type of "s2" is "set[Unknown]"
  test.py:18:13 - information: Type of "s3" is "set[str]"
```

**Describe the solution you’d like**
Not sure how much work it would be but it would be awesome if pyright could use the middle expr as well when inferring the lhs. This is the mypy output:
```py
test.py:13: note: Revealed type is "builtins.set[builtins.str]"
test.py:17: note: Revealed type is "builtins.set[builtins.str]"
test.py:18: note: Revealed type is "builtins.set[builtins.str]"
```

--
Just for comparison, what happens if incompatible types are used:
```py
s4 = data[KEY_SET] = {1, 2}
reveal_type(s4)
```

```py
# pyright
  test.py:20:6 - error: Argument of type "set[int]" cannot be assigned to parameter "value" of type "_T@__setitem__" in function "__setitem__"
    Type "set[int]" is incompatible with type "set[str]" (reportArgumentType)
  test.py:21:13 - information: Type of "s4" is "set[int]"

# mypy
test.py:20: error: Cannot infer type argument 1 of "__setitem__" of "CustomDict"  [misc]
test.py:21: note: Revealed type is "builtins.set[Any]"
```

**Comment by erictraut** [comment]
I think pyright's behavior here is correct.

First, there's no such thing as a "ternary assignment". What you're referring to here is a "chained assignment". In Python, it's possible to chain together an arbitrary number of assignments. When the Python runtime encounters this construct, it first evaluates the RHS. Then it assigns it to each of the chained targets left to right. For example, `a = b = c = 1 + 1` first evaluates `1 + 1`, then it assigns this value to `a`, then `b`, then `c`. You might wonder why the order matters. It normally doesn't, but there are cases where it's important.

```python
my_list = [10]
my_list[x] = x = 0 # This will crash
```

For static typing, pyright applies bidirectional type inference when evaluating the RHS if the first assignment has a declared type. If the first assignment doesn't have a declared type, then normal inference rules are used. Regardless, the evaluated type is then assigned to all targets left to right, mirroring the runtime.

Now that you understand how this works, you can see that there's a straightforward workaround in your code sample. If you want pyright to use bidirectional type inference for the RHS expression, make sure the first assignment target has a declared type.
