### ISSUE TITLE
Different results for `type[T]` vs `TypeVar("Cls", bound=type)`.

### ISSUE THREAD

**Issue by randolf-scholz** [microsoft/pyright#7897]
[pyright-playground](https://pyright-play.net/?pyrightVersion=1.1.361&code=CYUwZgBGD20NoGEA2BnAXBALgTwA4gF0AKAY1Q2RQEoIBaAPgkrQCgJ2IBLSTlFAVwBGZAIZ9SqADRcAdpiqsOSiLjEo2HAE4gAbiBFIA%2BjnwTq7AMQQARCZBxOcghAA%2BWPCABU1je22Z%2BTRkIMhRLGzsHJ1d3fG9ZEmgAW1VMTkEkEAgAd05MAAsbSgABGGgfFlBIQRFNOAAVYlCMSMaaBlj7RsUObi4%2BIVFxUOlHeR7lFTVfCG09A2MPMxoIK1sPKMwCTxjI6EEAKxASLe8Z-0Dg0JYgA)

```python
def foo[Cls: type](cls: Cls) -> Cls:
    if issubclass(cls, int):
        pass
    reveal_type(cls)  # "type[int] | type*"
    return cls  # "type[int] | type*" incompatible with "Cls@foo"

def bar[T](cls: type[T]) -> type[T]:
    if issubclass(cls, int):
        pass
    reveal_type(cls)  # "type[int]* | type[object]*"
    return cls
```

By the way, is there any preference between the two from a type-checker perspective?

**Comment by erictraut** [comment]
Pyright is working as intended here, so I don't consider this a bug. For comparison, mypy's behavior matches pyright's in this case.

These are different cases, so I wouldn't expect consistent behavior here.

I recommend using the latter approach in most cases. Creating a TypeVar that is bound to `type` is almost never the right answer.
