### ISSUE TITLE
use of `Protocol` with `__call__` requires argument names to match

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#7898]
**Describe the bug**
If you create a `Protocol` class with a `__call__()` method, then the callable passed into a function must have the names of the arguments match.

**Code or Screenshots**

```python
from typing import Protocol


class MyPro(Protocol):
    def __call__(self, x: int) -> int: ...


def foo(yf: MyPro, z: int) -> int:
    return yf(z)


def try1(x: int) -> int:
    return x * 2


def try2(xxx: int) -> int:
    return xxx * 3


print(foo(try1, 4))
print(foo(try2, 5))

```

The above reports an error in the second call to `foo` with `try2` as an argument:
```
protocolmatch.py:21:11 - error: Argument of type "(xxx: int) -> int" cannot be assigned to parameter "yf" of type "MyPro" in function "foo"
    Type "(xxx: int) -> int" is incompatible with type "(x: int) -> int"
      Parameter name mismatch: "x" versus "xxx" (reportArgumentType)
```

It's not clear to me why the names of the arguments have to match when using `Protocol`.  Shouldn't a protocol that has `__call__()` only depend on the types of the arguments in the `__call__()` declaration, not the names?  I looked at the typing specs and couldn't find anything, but I don't know them as well as you do!

Note:  `mypy` 1.10 reports a mismatch as well.

**VS Code extension or command-line**

pyright command line version 1.1.362

Note:  for `pandas-stubs`, we'd like to be able to have a method with overloads where the arguments of the `Callable` that is a parameter determine what other arguments are allowed.  In addition, the `Callable` can have an unknown number of arguments after the first argument.  So `Protocol` seems to be the recommended way, but then it forces the user to pass in a function where the first argument has a specific name, as opposed to a specific type.

**Comment by erictraut** [comment]
Pyright's behavior here is correct, so this isn't a bug.

If you want to describe a callable where the parameters are positional-only, you need to indicate as such within your protocol definition.

```python
class MyPro(Protocol):
    def __call__(self, x: int, /) -> int: ...
```

For more details, refer to the recently-expanded [Callables](https://typing.readthedocs.io/en/latest/spec/callables.html) chapter in the Python typing spec.

**Comment by Dr-Irv** [comment]
@erictraut thanks for the explanation
