### ISSUE TITLE
References only allowed mode

### ISSUE THREAD

**Issue by Yatima1460** [Microsoft/pyright#79]
It would be worth a discussion the idea to add a config that disallows None assignment globally as a valid variable type in Unions (realistically only disallowed in your project files only, not from values coming from external modules)
Basically disallowing """null pointers""".
It's not that rare to call a function using a dictionary (`d[key]()`) and then having a None value because it was assigned before instead of a dummy function throwing NotImplementedError

**Comment by erictraut** [comment]
I don't think it's feasible to disallow None assignments globally. None (or at least Optional, which is a union with None) is used pervasively in Python. 

Pyright already flags an error if a None type is used where it should be used.

It currently allows the use of Optional[X] in cases where X is allowed but None isn't. In other words, it assumes (conservatively) that the programmer knew what he/she was doing in this case.

I've implemented a set of configuration flags that enforce stricter assumptions around Optional[X] types. Check out the documentation for reportOptionalSubscript, reportOptionalMemberAccess, reportOptionalCall, and reportOptionalIterable.

**Comment by Yatima1460** [comment]
It's true that None is used everywhere in Python (sadly) but the more time passes the less I'm noticing I'm using it in projects to prevent "null pointer" errors

I think it would be feasible to disallow `= None` assignment only for your project files.
Passing None to an external module function should not be counted as error.

Only "internal" None should be considered

**Comment by erictraut** [comment]
Rather than disallowing None (which is not intrinsically unsafe), I think it's better to flag cases where the *use* of None is invalid.

I've added a bunch of config switches for this purpose. Please try enabling the following on your project: reportTypeshedErrors, reportOptionalMemberAccess, reportOptionalCall, reportOptionalIterable, reportOptionalContextManager, reportOptionalOperand.
