### ISSUE TITLE
Add formatter (junit)

### ISSUE THREAD

**Issue by yuriy1337** [microsoft/pyright#790]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem.
VS Code plugins are great, but it would also be great to enforce error free code in CI builds.
Azure pipelines supports output in JUnit format. It would be great to support multiple output formats.

**Describe the solution you'd like**
Add custom formatters

**Comment by erictraut** [comment]
The command-line version of Pyright already supports an option for outputting results in JSON format (--outputjson switch). This structured format allows other tools to transform the reported diagnostics in any manner they choose. It should be straightforward to write a script that outputs this in JUnit format or any other format required by your CI system.

**Comment by erictraut** [comment]
I'm going to mark this as closed. If the json output doesn't meet your needs for some reason or you have additional questions or suggestions, please let me know.
