### ISSUE TITLE
field recognition failed

### ISSUE THREAD

**Issue by zhuangzhuang** [microsoft/pyright#791]
**Describe the bug**
https://github.com/django/django/blob/master/django/utils/datastructures.py#L215

field recognition failed

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
success recognition like pycharm

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/521058/86504433-b97a0500-bdea-11ea-988f-1dc378a5c83b.png)
![image](https://user-images.githubusercontent.com/521058/86504438-d7476a00-bdea-11ea-9656-8e1b8bfad88b.png)

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.

**Additional context**

**Comment by erictraut** [comment]
This code is using a non-standard pattern to inject a new field into an object instance. There are many ways in a language as dynamic as Python to defeat a static type checker. Adding support for all such non-standard patterns isn't feasible.
