### ISSUE TITLE
Type ignore inside comment block disables complete file type checking

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pyright#7928]
**Describe the bug**
This seems a bit strange. The `type: ignore` seems to disable pyright completely, not even the result of `reveal_type` is printed. All that even though the line itself is commented.

```py
# x: int
# x = ""  # type: ignore[assignment]

reveal_type(1)
```
```bash
$ pyright --verbose test.py 
Search paths for file:///.../project
  /Users/.../.nvm/versions/node/v18.17.1/lib/node_modules/pyright/dist/typeshed-fallback/stdlib
  /.../project
  /.../project/typings
  /Users/.../.nvm/versions/node/v18.17.1/lib/node_modules/pyright/dist/typeshed-fallback/stubs/...
  /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12
  /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload
  /.../project/venv-312/lib/python3.12/site-packages
Found 1 source file
pyright 1.1.363
0 errors, 0 warnings, 0 informations 
Completed in 0.47sec
```

Changing it to this or removing the `type: ignore` and everything works as expected.
```py
x: int  # <- not commented anymore
# x = ""  # type: ignore[assignment]

reveal_type(1)
```
```
test.py:4:13 - information: Type of "1" is "Literal[1]"
```

**VS Code extension or command-line**
1.1.363

**Comment by erictraut** [comment]
This is intended behavior. PEP 484 and the typing spec indicate that if a `type: ignore` comment is found by itself on a line with no code preceding it, it suppresses diagnostics for the entire file. Pyright allows a `type: ignore` comment to be combined with other comment text.

**Comment by cdce8p** [comment]
Would it make sense to consider restricting the whole file `type: ignore` to if it's in a line on its own? That's what mypy is doing in this case. It also helps when writing code, as you can comment out whole blocks without having to worry that type checking doesn't work anymore.

**Comment by erictraut** [comment]
Specifically, the typing spec says:

> A # type: ignore comment on a line by itself at the top of a file, before any docstrings, imports, or other executable code, silences all errors in the file. Blank lines and other comments, such as shebang lines and coding cookies, may precede the # type: ignore comment.

I think pyright is consistent with the spec.

**Comment by cdce8p** [comment]
> Blank lines and other comments, such as shebang lines and coding cookies, may precede the # type: ignore comment.

I'd interpret that as "other comment lines" `before` the type ignore comment, since it refers to "black line and other comments". But that's probably splitting hairs at this point. E.g. something like this:
```py
#!/usr/bin/env python3
# some comment
# type: ignore
```

As mentioned [earlier](https://github.com/microsoft/pyright/issues/7928#issuecomment-2113657460), I think from a coding perspective, this current behavior can be unexpected but I guess it's your call.
