### ISSUE TITLE
Go To Definition jumps to source rather than typeshed stubs

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#795]
"Go to Definition" on stdlib functions jumps to the module source rather than the typeshed stubs.

The behaviour of the default python extension ie: without pyright, is to jump to the module source.

This is also the behaviour in PyCharm.

**Comment by tekumara** [comment]
This is also the behaviour in PyCharm.

**Comment by erictraut** [comment]
If you have both a type stub (including those that ship as part of typeshed) _and_ a library implementation is present, Pyright will show you the definition in both locations, and you can choose between them. For example, see this screen shot.

<img width="954" alt="Screen Shot 2020-07-06 at 7 33 05 AM" src="https://user-images.githubusercontent.com/7040122/86605038-0a107000-bf5b-11ea-9d42-ac6363be0185.png">

**Comment by tekumara** [comment]
It defaults to the type stub, is there a way to default to the more useful source instead? (or even better, ignore the type stub altogether)

**Comment by tekumara** [comment]
Duplicate https://github.com/microsoft/pylance-release/issues/65

**Comment by erictraut** [comment]
I'm not sure what you mean by "it defaults to the type stub". You should see both options appear, as in the screen shot above. It doesn't default to one or the other.

Both the type stub and the source contain valuable information depending on your objective. From a type perspective, the information in the type stub is typically more definitive than any type information inferred from the source. Type stubs often provide overloads, generic definitions, functions definitions with generic parameter types, etc. that the original source does not contain.

**Comment by tekumara** [comment]
By default, I was meaning which file was chosen for display first. In my case, I get the `.pyi` file displayed first:

<img width="806" alt="Screen Shot 2020-07-09 at 9 06 53 pm" src="https://user-images.githubusercontent.com/125105/87032576-2d237400-c228-11ea-82a8-956822a2b641.png">

Perhaps there a loading order somewhere that can be configured?

**Comment by jakebailey** [comment]
We should be displaying the `py` file first. The server does have control over which item it selects first.

**Comment by huguesv** [comment]
@jakebailey VS Code ignores the server results ordering. I've tested by having the server reverse() the results before returning them, and it made no difference to the order displayed in VS Code, no difference to which one is selected.

Is there something in particular you were thinking of that would allow control over this?

**Comment by jakebailey** [comment]
Huh, I really had thought that the specification allowed you to mark one as the "preferred" choice. But, it's just a plain list? Unfortunately this'd mean we need the LSP to change to allow us to pick a result (or some change in VS Code to prefer the first one, for example).

**Comment by jgubler** [comment]
I'm also having the same problem. I understand that it may make sense in certain cases (overloading etc as you mentioned) to show the pyi file, so it probably shouldn't be hidden.
However I think the much much more prominent use case is "go to the source definition of this function/constant/etc to modify it", in which case it's obviously far preferable if the selected (and expanded) choice is the .py file.

**Comment by potatochip** [comment]
I don't even see an option to view the stdlib source. When I peek the module it only shows the typestub.

**Comment by killa1218** [comment]
> I don't even see an option to view the stdlib source. When I peek the module it only shows the typestub.

I met the same problem and would appreciate if also add built-in class/functions into options choosing py or pyi.

**Comment by cangyin** [comment]
> I don't even see an option to view the stdlib source. When I peek the module it only shows the typestub.

Please reopen the issue. I have searched so many issues that claims to be solved with lengthy discussions, but none of them actually helps me.

**Comment by erictraut** [comment]
@cangyin, you're commenting on an issue that has been closed for multiple years. If you have a question, please post it to the pyright discussion forum with details about your situation. If you think that you are seeing a bug, please create a new bug report with repro details.
