### ISSUE TITLE
return type of subclass constructor incorrectly inferred as super class

### ISSUE THREAD

**Issue by CNSeniorious000** [microsoft/pyright#7953]
![image](https://github.com/microsoft/pyright/assets/74518716/2f76be92-eead-48ae-9971-90fe5f474b2a)

**Describe the bug**
I want to declare my `SimpleMap` returns the "deepest" type when possible. So I type hint it like above.

**Code or Screenshots**

```python
from typing import *

M = TypeVar("M", bound="SimpleMap")  # represents a subclass of `SimpleMap`


class SimpleMap(dict):
    @overload
    def __new__(cls, map: M, **kwargs) -> M: ...

    @overload
    def __new__(cls, map: dict, **kwargs) -> Self: ...

    def __new__(cls, map, **kwargs):  # type: ignore
        if isinstance(map, cls) and map.__class__ is not cls:
            return map.__class__(map, **kwargs)

        return super().__new__(cls, map, **kwargs)


class SubclassSimpleMap(SimpleMap):
    pass


map1 = SubclassSimpleMap({})

reveal_type(map1)
reveal_type(SimpleMap(map1))


class AnotherSubclass(SimpleMap):
    def __init__(self, simple_map: SimpleMap): ...


simple_map = SimpleMap({})

map2 = AnotherSubclass(simple_map)
# wrong! This should be `AnotherSubclass` instead of `SimpleMap``
reveal_type(map2)
```

**VS Code extension or command-line**
Yes. I am using the latest `pylance` inside VS Code, and I tried my `pyright 1.1.363` too:
<details>
<img src="https://github.com/microsoft/pyright/assets/74518716/3d3b8c30-3fec-4dd3-b51f-0f2f357ed583">
</details>

**Comment by erictraut** [comment]
Pyright is behaving correctly here, so I don't consider this a bug.

The type evaluation behavior for [constructor calls](https://typing.readthedocs.io/en/latest/spec/constructors.html) was recently clarified in the official Python typing spec, and pyright is conformant with the spec.

The first overload of the `__new__` method in your example returns the type `M`, which evaluates to `SimpleMap` when calling `AnotherSubclass(simple_map)`.
