### ISSUE TITLE
Support different type for class variable and instance variable

### ISSUE THREAD

**Issue by last-partizan** [microsoft/pyright#7995]
I'm not sure if this is a bug, but i'm not sure it's not a bug. So, i'm creating Feature request for this.

**Is your feature request related to a problem? Please describe.**
In django-modeltranslation, before we added types, we used class variable to populate instance variable with same name, but different type. And now this decision is biting our asses (https://github.com/deschler/django-modeltranslation/issues/736).

Here's cleaned up code:

```python
from typing import Any, ClassVar, Iterable

from modeltranslation.fields import TranslationField


class FieldsAggregationMetaClass(type):
    fields: ClassVar[Iterable[str]]

    def __new__(cls, name: str, bases: tuple[type, ...], attrs: dict[str, Any]) -> type: ...


class TranslationOptions(metaclass=FieldsAggregationMetaClass):
    def __init__(self) -> None:
        self.fields: dict[str, set[TranslationField]] = {f: set() for f in self.fields}


class BookTranslationOptions(TranslationOptions):
    fields = ["name"]
```

This leads to error when assigning `fields`, because it's being treated as instance variable, not class var.

> error: Expression of type "list[str]" is incompatible with declared type "dict[str, set[TranslationField]]"
>  "list[str]" is incompatible with "dict[str, set[TranslationField]]" (reportAssignmentType)

**Describe the solution you’d like**

It would be really nice, if on the class level `fields` was treated as class variable, allowing assignling a list. But on the instance level - it was using type from `__init__` (or type from annotation without ClassVar.

**Comment by erictraut** [comment]
Class and instance variables with mismatched types are not allowed by the Python typing spec, so this isn't something that pyright will support.

I think it's very unlikely this will ever be supported in the typing spec, but if you would like to make an argument in favor of it, the [Python typing forum](https://discuss.python.org/c/typing/32) is the place to discuss it.

**Comment by last-partizan** [comment]
Thanks for the idea. I've got a suggestion from the forum to try something like this:

```python
from __future__ import annotations

from typing import Any, Generic, Iterable, Protocol, TypeVar, overload
from typing_extensions import reveal_type

ClassT = TypeVar("ClassT")
InstanceT = TypeVar("InstanceT")


class ClassOrInstanceAttribute(Protocol, Generic[ClassT, InstanceT]):
    @overload
    def __get__(self, obj: None, owner: type) -> ClassT: ...
    @overload
    def __get__(self, obj: object, owner: type) -> InstanceT: ...
    def __set__(self, obj: object, value: InstanceT) -> None: ...


class TranslationField: ...


class FieldsAggregationMetaClass(type):
    fields: ClassOrInstanceAttribute[Iterable[str], dict[str, set[TranslationField]]]

    def __new__(cls, name: str, bases: tuple[type, ...], attrs: dict[str, Any]) -> type: ...


class TranslationOptions(metaclass=FieldsAggregationMetaClass):
    def __init__(self) -> None:
        ...
        # self.fields: dict[str, set[TranslationField]] = {f: set() for f in self.fields}


class BookTranslationOptions(TranslationOptions):
    fields = ["name"]  # This is a problematic line


reveal_type(BookTranslationOptions.fields)
reveal_type(BookTranslationOptions().fields)
```

And revealed types is correct, but assignment still fails.

```
types-test.py:10:7 - warning: Type variable "ClassT" used in generic protocol "ClassOrInstanceAttribute" should be covariant (reportInvalidTypeVarUse)
types-test.py:34:14 - error: Expression of type "list[str]" is incompatible with declared type "ClassOrInstanceAttribute[Iterable[str], dict[str, set[TranslationField]]]"
    "list[str]" is incompatible with protocol "ClassOrInstanceAttribute[Iterable[str], dict[str, set[TranslationField]]]"
      "__get__" is not present
      "__set__" is not present (reportAssignmentType)
types-test.py:37:13 - information: Type of "BookTranslationOptions.fields" is "Iterable[str]"
types-test.py:38:13 - information: Type of "BookTranslationOptions().fields" is "dict[str, set[TranslationField]]"
1 error, 1 warning, 2 informations
```

Can this be fixed on the side of pyright?

**Comment by erictraut** [comment]
> Can this be fixed on the side of pyright?

I think pyright is working correctly here, so I don't consider this a bug.

You have declared that the type of `fields` is an instance variable in the metaclass, which means that it's a class variable in class objects created from that metaclass. You are then attempting to overwrite this class variable with a value that is incompatible with its declared type.

Mypy has some holes where it doesn't always detect that an instance variable in a metaclass is the same as a class variable in class objects created from it, which is why it doesn't catch this error.

If your intent is for `FieldsAggregationMetaClass.fields` to be a ["pure" class variable](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=pure-class-variables), you can declare it as such by using `ClassVar` in its declaration. 

```python
    fields: ClassVar[ClassOrInstanceAttribute[Iterable[str], dict[str, set[TranslationField]]]]
```

This makes the type violation go away because a class variable on the metaclass is not the same as a class variable on the class object created from that metaclass.
