### ISSUE TITLE
Support for PYTHONPATH

### ISSUE THREAD

**Issue by kinow** [Microsoft/pyright#8]
Hi,

I just tried the command line (thanks for publishing it to `npm` registry!), and it seems to be working! Except for some missing imports, but I assume `pyright` probably is not processing the [PYTHONPATH](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) yet?

Here's an example:

```
~/Development/python/workspace/cylc/lib/cylc$ PYTHONPATH=$(pwd -P)/../ pyright -P . batch_sys_manager.py
Finding source files
Found 1 source files
Analyzed 1 file in 1.7sec
/home/kinow/Development/python/workspace/cylc/lib/cylc/batch_sys_manager.py
  Import 'cylc.task_message' could not be resolved (119, 6)
  Import 'cylc.cylc_subproc' could not be resolved (122, 6)
  Import 'cylc.task_job_logs' could not be resolved (123, 6)
  Import 'cylc.task_outputs' could not be resolved (125, 6)
  Import 'cylc.wallclock' could not be resolved (126, 6)
  Import 'parsec.OrderedDict' could not be resolved (127, 6)
  'batch_sys' may be unbound (399, 24)
  'batch_sys' may be unbound (411, 24)
  'batch_sys' may be unbound (417, 25)
  'rec_id' may be unbound (474, 12)
  'text' may be unbound (475, 29)
  'rec_id' may be unbound (476, 25)
  'os.getpgid' has type 'Unbound' and is not callable (404, 39)
  'os.killpg' has type 'Unbound' and is not callable (404, 29)
  'KILL_CMD_TMPL' is not a known member of 'Unbound' (417, 35)
  'match' is not a known member of 'Unbound' (476, 32)
  'close' is not a known member of 'None' (753, 28)
11 errors, 6 warnings 
Find Source Files:    0.001sec
Read Source Files:    0.001sec
Tokenize:             0.075sec
Parse:                0.187sec
Post-parse Walker:    0.141sec
Semantic Analyzer:    0.25sec
Type Analyzer:        1.001sec
```

But if instead of `pyright` I execute `python`, the import statements that failed, this time will work.

```
~/Development/python/workspace/cylc/lib/cylc$ PYTHONPATH=$(pwd -P)/../ python
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cylc.task_message
>>>
```

**Comment by maxmcd** [comment]
You can add paths to the `executionEnvironment` section in the configuration: https://github.com/Microsoft/pyright/blob/master/docs/configuration.md#execution-environment-options

**Comment by erictraut** [comment]
I'm somewhat conflicted about supporting the PYTHONPATH environment variable in the command-line tool and the python.pythonPath setting in VS Code. Pyright already provides a couple of ways to configure this setting. I'll keep this feature request open for now while I ponder it further.

In the meantime, you can pass the main python environment path to the command-line using the "--python-path" option. If you plan to run the command repeatedly on a particular code base, it's worth setting up a pythonconfig.json file.

**Comment by kinow** [comment]
Thanks @erictraut 

It would be more convenient, but if there is a workaround, I'd be fine using that instead.

Note, I found `pyright` from [HackerNews thread](https://news.ycombinator.com/item?id=19473631) (not sure if you were aware of the post) front page yesterday. There's another user who commented something similar - though not sure if the same issue - there:

>I just installed it. It  gives red squiggly lines under variables that haven't been assigned  (typos) and for incorrect methods on variables it can type-deduce. This  is without me adding any typing-hints to the script I'm working on.Only  issue I see immediately is it does not use the default sys.path that  the vs-code-configured python interpreter uses, so it cannot resolve  some of the packages I'm using.But overall, very nice.

Thanks

**Comment by MuhistheHolvi** [comment]
I can confirm this issue. I just installed pyright in VSCode and all imports can't be resolved. I have python.pythonPath configured and pylint (for example) works normally.
VScode version:
February 2019 (version 1.32)
OS: macOS Mojave 10.14.3
I can help with more debugging if needed.

**Comment by erictraut** [comment]
Thanks for the suggestion. I've added support for the PYTHONPATH environment variable in 1.0.7, which was just published. You can read more about it in this [documentation](https://github.com/Microsoft/pyright/blob/master/docs/import-resolution.md).

**Comment by kinow** [comment]
Thanks @erictraut !!!

**Comment by bfelbo** [comment]
Is there a way to globally provide the PYTHONPATH env variable to pyright?

I often have small 1-file python scripts, where I don't want to create a `pyrightconfig.json` file every time.

**Comment by erictraut** [comment]
Pyright should already pick up the PYTHONPATH environment variable if it's set. I assume you're using the VS Code extension (as opposed to the command-line version)?

Please check out the documentation on [Import Resolution](https://github.com/microsoft/pyright/blob/master/docs/import-resolution.md) and let me know if you are able to diagnose the problem.

**Comment by bfelbo** [comment]
I've created a new issue for this here: #143
