### ISSUE TITLE
pyright:command not found

### ISSUE THREAD

**Issue by kaixiongg** [Microsoft/pyright#80]
I have tried to download pyright in linux using npm which give me feedback like "/home/kaixiong/.npm-global/bin/pyright -> /home/kaixiong/.npm-global/lib/node_modules/pyright/index.js + pyright@1.0.15".
Then I type "pyright", however the bash keeps saying that command not found .. Any help would be really appreciated!

**Comment by erictraut** [comment]
Did you install it globally using `sudo nom install -g pyright`? If so, then it sounds like a PATH issue with node.

**Comment by kaixiongg** [comment]
Yes.I have also used "sudo npm install -g pyright" and update the node. :(

**Comment by erictraut** [comment]
Here's [an article](https://medium.com/@jagatjyoti.1si13cs040/npm-g-install-npm-package-not-working-as-desired-why-why-why-19795abf0b59) that might help you diagnose the problem.

**Comment by kaixiongg** [comment]
I followed the instruction and FIXED it. Really appreciate your help though I think it might be not a good place to post this kind of issue :(     ANYWAY, THANKS :)
