### ISSUE TITLE
`__doc__` inside class body has type `str | None` even though doc-string is defined

### ISSUE THREAD

**Issue by Andrej730** [microsoft/pyright#8006]
**Describe the bug**
Example is below -  `y` is `str | None` but should be just `str` since doc-string is defined and recognized by pyright (judging based on the `Foo` tooltip)

**Code or Screenshots**
```python
class Foo:
    """test_doc"""
    y = __doc__

    reveal_type(y)
```

**VS Code extension or command-line**
https://pyright-play.net/?code=MYGwhgzhAEBiD28BcBYAUNT0BEuAuAphHgPoAm8wu26W0AntALzQnmVu1YBOBAbgTAgSeegAcCACnoBKIA

**Comment by erictraut** [comment]
This is by design. The `__doc__` property of a function is writable, so it can be set to `None` even if it is set to another value at the time the function is defined. The type of the `__doc__` symbol comes from the `object` class in typeshed, where it is defined as `str | None`.
