### ISSUE TITLE
Overloaded decorators break type inference for self-referential methods

### ISSUE THREAD

**Issue by DeCarabas** [microsoft/pyright#8008]
**Describe the bug**
It would seem that pyright sometimes loses the ability to infer the type of a method that has been decorated with a decorator *if* the decorator has overloads. The simplest way to trigger this is to:

1. Have a decorator with overloads, and
2. Apply this decorator to a method that refers to itself.

This is an odd corner one, I'm sorry if I'm not describing it well. Here's my example:

I'm building a little python DSL for grammars, and as a result I have a decorator that transforms a method into a rule:

```python
class Rule:
    def __init__(self, *args):
        self._args = args

    def __or__(self, other) -> "Rule":
        return Rule(self, other)

    def __add__(self, other) -> "Rule":
        return Rule(self, other)

@typing.overload
def rule(f: None | str = None) -> typing.Callable[[typing.Callable], Rule]: ...


@typing.overload
def rule(f: typing.Callable) -> Rule: ...


def rule(
    f: None | str | typing.Callable = None,
) -> Rule | typing.Callable[[typing.Callable], Rule]:
    def _rule(callable):
        return Rule(callable, name)

    if callable(f):
        name = f.__name__
        return _rule(f)
    else:
        name = f
        return _rule
```

Here I'm trying to describe the standard decorator function pattern where the decorator can either take arguments or not, so it's overloaded on the type of its arguments to either *be* a decorator or *return* a decorator depending on how it is called. It always eventually generates a `Rule`.

Basic usage works well:

```python
class Grammar:
    @rule("the start rule")
    def start(self):
        return self.expression | self.statement

    @rule
    def expression(self):
        return Rule("Mumble")

    @rule
    def statement(self):
        return Rule("Grumble")
```

Pyright correctly identifies the types of `Grammar.start`, `Grammar.expression`, and `Grammar.statement` as `Rule`. (Which is why `self.expression | self.statement` also type-checks in the body of `Grammar.start`.)

But pyright gets confused when I add a self-referential method:

```python
class Grammar:
    #...
    @rule
    def identifier_list(self):
        return Rule("identifier") | (self.identifier_list + Rule("identifier"))
```

In this case pyright complains:

```
/home/doty/tmp/repro.py
  /home/doty/tmp/repro.py:52:37 - error: Operator "+" not supported for types "() -> Unknown" and "Rule" (reportOperatorIssue)
1 error, 0 warnings, 0 informations 
```

It would seem that, inside the definition of `Grammar.identifier_list`, it thinks that the type of `Grammar.identifier_list` is ... something? (Maybe it's just not applying the decorator result? I don't really know.)

Note that if the decorator is not overloaded, then everything works great. i.e., if you replace all the definitions of `rule` with:

```python
def rule(f: None | str = None) -> typing.Callable[[typing.Callable], Rule]:
    def _rule(callable):
        return Rule(callable, name)

    name = f
    return _rule
```

...and then adjust all the uses in `Grammar` appropriately, then everything works and pyright is happy.

**Code or Screenshots**

Here's the whole example:

```python
import typing


class Rule:
    def __init__(self, *args):
        self._args = args

    def __or__(self, other) -> "Rule":
        return Rule(self, other)

    def __add__(self, other) -> "Rule":
        return Rule(self, other)


@typing.overload
def rule(f: None | str = None) -> typing.Callable[[typing.Callable], Rule]: ...


@typing.overload
def rule(f: typing.Callable) -> Rule: ...


def rule(
    f: None | str | typing.Callable = None,
) -> Rule | typing.Callable[[typing.Callable], Rule]:
    def _rule(callable):
        return Rule(callable, name)

    if callable(f):
        name = f.__name__
        return _rule(f)
    else:
        name = f
        return _rule


class Grammar:
    @rule("the start rule")
    def start(self):
        return self.expression | self.statement

    @rule
    def expression(self):
        return Rule("Mumble")

    @rule
    def statement(self):
        return Rule("Grumble")

    @rule
    def identifier_list(self):
        return Rule("identifier") | (self.identifier_list + Rule("identifier"))
```

**VS Code extension or command-line**
This is pyright 1.1.364, from the command line:

```
doty@fred ~/tmp> pyright --version
pyright 1.1.364
```

This reproduces on the command line and as an LSP from within eglot.

**Comment by erictraut** [comment]
You haven't provided a return type annotation for `identifier_list`. Pyright is often able to infer return types by analyzing the code within the method, but this doesn't work for recursive methods. You can fix this by adding an explicit return type annotation `-> Rule`.

**Comment by DeCarabas** [comment]
Oh, wild, it fixes the problem!

I would not have predicted that. How does the return type factor into the typing for the decorator? Regardless of the return type of the method, it should match `typing.Callable`, right? In which case the second signature of `rule` should match, and the type of the member should be known to be `Rule`?

**Comment by DeCarabas** [comment]
I guess the question is: given that the type of the member does not depend on the return type of the method, why does pyright need to know the return type before it can properly evaluate the decorator? 

(It has something to do with resolving the overload on the decorator, clearly, because the whole thing works if there is no overload on the decorator...)
