### ISSUE TITLE
Feature Request: Insert all arguments of a function

### ISSUE THREAD

**Issue by plutonium-239** [microsoft/pyright#8011]
I would like to be able to insert all arguments of a function at once, when the cursor is inside a function call (or similar scope).
This had been implemented by the [Anaconda LSP](https://damnwidget.github.io/anaconda/IDE/#complete-function-and-class-parameters), but that is not actively maintained and updated. In addition, it was snippet-like; so that you can edit the values on right side of `arg_name=` by cycling through them using a keybind (I don't know if this is the LSP's responsibility or the editor's, but I'll just leave it here).

So, for a function with 7 arguments, it does the following:
```py
f( )
  ^cursor
{trigger action}
f(arg1= , arg2=, arg3=, arg4=, arg5=, arg6=, arg7=)
       ^cursor
```

**Is your feature request related to a problem? Please describe.**
Yes, sometimes I know that I would need to write out all the arguments of a function, and when there are 5+ arguments, using normal completion (i.e. each argument one by one) can get a bit tedious.

**Describe the solution you’d like**
An "insert all arguments" action/completion/snippet (I don't know what would be suited best for this).

**Comment by erictraut** [comment]
Your feature request involves a language server feature. While pyright does have some basic language server functionality, we have no plans to add new LSP functionality to pyright. Pyright is focused entirely on type checking and static type analysis.

All new language server functionality is implemented in pylance, which is Microsoft's Python language server. Pylance builds on the static type analysis features of pyright. 

If you're not already using pylance as your language server, I recommend switching to it. You will get all of the type checking benefits of pyright plus a bunch of advanced language server features like symbol indexing, syntax highlighting, and refactoring tools. If there are language server features you'd like to suggest that pylance doesn't already support, you can file those feature requests in the [pylance-release](https://github.com/microsoft/pylance-release/issues) issue tracker.
