### ISSUE TITLE
TypeVar constraint type cannot be generic

### ISSUE THREAD

**Issue by nrbnlulu** [microsoft/pyright#8012]
**Describe the bug**
pyright: "TypeVar constraint type cannot be generic"

**Code or Screenshots**
```python
from collections.abc import Hashable
from typing import Protocol


class HasIDField[K: Hashable](Protocol):
	id: K

	def __hash__(self) -> int: ...


class Repository[K: Hashable, T: HasIDField[K]](Protocol):
	data: list[T]

	def get(self, key: K) -> T | None:
		return next((v for v in self.data if v.id == key), None)

```
![image](https://github.com/microsoft/pyright/assets/88795475/bdd4a65f-59d0-4f1c-a410-33307de1f6d6)

**VS Code extension or command-line**
`pyright 1.1.360`

Is this a bug or a wanted behaviour? (*seems quite reasonable to me...*)

**Comment by randolf-scholz** [comment]
See https://github.com/python/typing/issues/548 and https://github.com/nekitdev/peps/blob/main/peps/pep-9999.rst
