### ISSUE TITLE
Import "pandas_ta" could not be resolved

### ISSUE THREAD

**Issue by Rakesh-656** [microsoft/pyright#8041]
Import "pandas_ta" could not be resolved

**Comment by erictraut** [comment]
Please stop filing these bogus bug reports.

**Comment by Rakesh-656** [comment]
how to sovle this issue

**Comment by Rakesh-656** [comment]
import concurrent.futures
import time
import re
import numpy as np
from datetime import datetime,timedelta
from NorenRestApiPy.NorenApi import NorenApi
import pandas as pd
import pandas_ta as ta
class ShoonyaApiPy(NorenApi):
    def __init__(self):
        NorenApi.__init__(self, host='https://api.shoonya.com/NorenWClientTP/', websocket='wss://api.shoonya.com/NorenWSTP/')        
        global api
        api = self
