### ISSUE TITLE
Pyright runs forever on an identity function being called with a tuple containing two references of itself as argument

### ISSUE THREAD

**Issue by InSyncWithFoo** [microsoft/pyright#8047]
From #7250 ([playground](https://pyright-play.net/?pyrightVersion=1.1.365&strict=true&code=CYUwZgBGDaAqC6AKAbgLgrAlBAtAPg1QFgAoCciAJxABcBXSgOwmVNOuRAEMAbAfRoBPAA4hEYROIA0UTHNJA)):

```python
def f[T](v: T) -> T:
    return v

reveal_type(f((f, f)))
```

With `[f]` instead of `(f, f)`, it [outputs](https://pyright-play.net/?pyrightVersion=1.1.365&strict=true&code=CYUwZgBGDaAqC6AKAbgLgrAlBAtAPg1QFgAoCciAJxABcBXSgOwmVNOuRAEMAbAfRoBPAA4hEYRNDDxMmUkA) a ~15KB message:

```text
Type of "f([f])" is "list[(v: list[(v: list[(v: list[(v: list[(v: list[(v: list[... -> list[(v: ) -> ]]) -> list[(v: list[(v: ) -> ]) -> list[(v: ) -> ]]]]]]]]]]"
```

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.373.
