### ISSUE TITLE
Parameterized type aliases have unpredictable argument order

### ISSUE THREAD

**Issue by kyle-query** [microsoft/pyright#8058]
**Describe the bug**

I have some code like so:

```python
from typing import Generic, TypeVar

T = TypeVar("T")
U = TypeVar("U")

class Foo(Generic[T]):
    t: T

class Bar(Generic[T, U]):
    t: T
    u: U

FooBar = Union[Foo[T], Bar[T, U]]
```

While I can't write `FooBar[T, U] = ...` to explicitly specify the order of type arguments due to it being a syntax error, the order is almost always the order in which they occur within the right hand side. So above I would expect `FooBar`'s first parameter to be `T`, and the second to be `U`.

However I've encountered some cases where the order is not what I expect, which results in a lot of confusion because I can never actually see which order pyright thinks the arguments are in. Having this be part of the hover text would be very useful.

More importantly though, it seems like the inferred ordering is not consistent. In a file that instantiates a generic type, I can tell from the type error that pyright has the arguments backwards from what I expect. Editing the file where the generic type is defined, by switching their ordering, does resolve the type error. However after doing that, in the same class definition a `match/case` shows the arguments were apparently inferred to be backwards from how they were inferred in the other file.

Perhaps I'm not supposed to be declaring generic type aliases, or I'm misunderstanding how pyright determines the ordering of parameters?

**Code or Screenshots**

If the issue description doesn't help narrow the problem down, I can provide access to a private repository where the problem occurs consistently.

**VS Code extension or command-line**

Both. I'm using pyright v1.1.362 on the command line, and pylance v2024.5.1 in Visual Studio Code.

**Comment by erictraut** [comment]
Can you provide a minimal, self-contained code sample that demonstrates the problem you're seeing? The above code type checks without errors and works as I would expect.

You're correct that type parameters for a generic type alias should be in the order they appear in the expression (left to right). This is how pyright's logic implements this, so if you're seeing something different, I'd find that surprising.

I'll note that you're using an archaic mechanism for defining type aliases. A slightly-more-modern (but still deprecated) way to define type aliases is with the [TypeAlias](https://typing.readthedocs.io/en/latest/spec/aliases.html#typealias) directive:

```python
FooBar: TypeAlias = Foo[T] | Bar[T, U]
```

As of python 3.12, the recommended way to define type aliases is with the new `type` keyword. This allows you to specify type parameter order explicitly. Here's how the code looks if you use this modern form. Note that I've also replaced the deprecated `Union` with the modern `|` operator.

```python
class Foo[T]:
    t: T

class Bar[T, U]:
    t: T
    u: U

type FooBar[T, U] = Foo[T] | Bar[T, U]
```

**Comment by erictraut** [comment]
OK, I'm going to close the issue for now since there's nothing actionable. I'm happy to re-open it if you can provide a repro and/or more details.
