### ISSUE TITLE
narrowing does not work when the variable being narrowed is on the right hand side of the `==` operator

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#8064]
```py
def f(a: int | None):
    if 1 == a:
        reveal_type(a)  # int | None
    if a == 1:
        reveal_type(a)  # Literal[1]
```
[playground](https://pyright-play.net/?code=CYUwZgBGAUCGBcECWA7ALhAPhAcgexRAEp4BYAKAiuUgEYIBeBiBC69iAJxADcRYANgH00ATwAOIOESoBiZOiy4CINtSSRYjZrTKUOVbn0EiJU2DIjyAMkjQhOggNq0AuhSA)

**Comment by erictraut** [comment]
Pyright is working as intended, so this isn't a bug.

For a complete list of supported type guard expression forms, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards).

**Comment by elenakrittik** [comment]
Sorry for posting in a closed thread, but may i know why exactly was this closed? The list of supported type guard expressions doesn't have to stay constant (or does it?), and (to an outsider) it looks like it will be fairly simple to narrow in both cases. Will it affect the performance too much or it's too hard to implement compared to the benefit or ...?
