### ISSUE TITLE
"Enum" is not iterable

### ISSUE THREAD

**Issue by rsokolewicz** [microsoft/pyright#8073]
**Describe the bug**

My pyright wrongly states that Enums are not iterable.

**Code or Screenshots**

```
from enum import Enum


def foo(bar: Enum):
    for element in bar:
        pass
    [element.name for element in bar]

```

here pyright will complain both the for loop as the list comprehension. 

**VS Code extension or command-line**

Command-line: v1.1.224 (earliest non-yanked version on pypi), and v1.1.365 (latest as of 05/06/2024). I thought maybe it has to do with the python version, but I get the same problem on python 3.9.12 and python 3.11.9.

**Comment by LeeeeT** [comment]
An instance of `Enum` itself is not iterable. `type[Enum]` is iterable. To make your code work change the annotation of `bar` like this:
```python
def foo(bar: type[Enum]): ...
```

**Comment by rsokolewicz** [comment]
🤦
