### ISSUE TITLE
Pass a list of values to `typing.Literal` using `typing.Unpack`

### ISSUE THREAD

**Issue by shner-elmo** [microsoft/pyright#8075]
**Describe the bug**
Hey, so I'm basically trying to pass a list of values to `typing.Literal` instead of rewriting the same values again and again by using `typing.Unpack`. But its not working:

![image](https://github.com/microsoft/pyright/assets/102916448/c35785e8-8b46-4e81-9ed3-f5f3c51feaf8)

Am I using it wrong or is it a bug ?

**Code or Screenshots**
To reproduce:

```python
from typing import Literal, Unpack

some_tuple = ('a', 'b', 'c')


def get_smth(x: Literal[Unpack[some_tuple]]):
   ...
```

**VS Code extension or command-line**
I'm running `pyright 1.1.365` on Pycharm

```[tasklist]
### Tasks
```

**Comment by erictraut** [comment]
Variables are not allowed in type annotations according to the [typing spec](https://typing.readthedocs.io/en/latest/spec/annotations.html), so this won't work. Also, the `Unpack` type directive doesn't work like this. If you want to describe the static type that is the union of three literal strings, you correct way to do this is `Literal['a', 'b', 'c']`.
