### ISSUE TITLE
Distinguish between errors and warnings 

### ISSUE THREAD

**Issue by kaixiongg** [Microsoft/pyright#81]
Could we tell the difference between warnings and errors given all of the messages on terminal?
I have run pyright on my own code on the Linux and it returns all of the places which could be an "error" with a statistic saying that how many errors and how many warnings there are.
But I am wondering could I distinguish them based on the description of the error messages?

**Comment by erictraut** [comment]
Good suggestion. The difference between errors and warnings is easy to tell in the VS Code UI, but the command-line version of pyright doesn't differentiate.

**Comment by erictraut** [comment]
I've improved the formatting of the output to include not only an "error" or "warning" string but also text colors to make the output easier to read. The change will be in the next published version 1.0.17. Thanks again for the suggestion!

**Comment by erictraut** [comment]
This is now fixed in 1.0.17, which I just published
