### ISSUE TITLE
Composite conditional is not recognized when narrowing down type

### ISSUE THREAD

**Issue by danpascu** [microsoft/pyright#8104]
I have the following piece of code:

```py
def limit[T: ComparableNumber, U: ComparableNumber](value: T, *, min: U | None = None, max: U | None = None) -> T:
    if min is not None is not max and min > max:
        raise ValueError('lower boundary cannot be higher than the upper boundary')
    ...

```

`ComparableNumber` is a protocol, but it's not really relevant to this issue so I won't include it for brevity, same with the rest of the function body. The issue arises because `min` and `max` can be `None`.

The line with the composite conditional `min is not None is not max` gets flagged by pyright with the error:

`Operator ">" not supported for "None"`.

By replacing `min is not None is not max` with its equivalent form `min is not None and max is not None` the error goes away, but I think the former should be accepted and handled the same way as the latter, since they are the same condition written in 2 different ways.

This is with command line pyright.

**Comment by erictraut** [comment]
This isn't a supported type guard pattern. For a full list of supported patterns, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards).

We do occasionally add support for new patterns, but each one requires special-case logic and has the potential for slowing down overall type analysis, so we do so only in cases where we have strong signal from pyright users that it's a common pattern. This is the first time I've ever seen this pattern used, so I don't think it's idiomatic or common. 

I'm going to close the feature request, but I'm willing to reconsider it in the future if there is sufficient signal (e.g. in the form up thumbs-up reactions to this issue) from other pyright users.
