### ISSUE TITLE
sagemath autocompletion

### ISSUE THREAD

**Issue by GopherJ** [microsoft/pyright#8115]
**Is your feature request related to a problem? Please describe.**
I'm always curious on how to use sage in python and get autocompletion, is that something pyright can support?

```py
 ⚠  finiteField = GF(25)
 >> finiteField.
```

**Describe the solution you’d like**
A clear and concise description of the solution you would like to see.

**Comment by GopherJ** [comment]
https://github.com/microsoft/pylance-release/issues/58

**Comment by erictraut** [comment]
I'm not sure what "sage" is. I presume it's a Python library? Does it include inline static type annotations, or do you have a type stub for it? If so, then pyright and pylance should be able to provide completion suggestions. If it's an untyped library, then your experience may be mixed.

In any case, pyright is focused on type checking. It has some basic language server features, but we don't plan to add new language server capabilities to pyright. If you have feature requests that are specific to language server features like completion suggestions, please file those feature requests in the [pylance-release project](https://github.com/microsoft/pylance-release).
