### ISSUE TITLE
Bare `type` member is inferred as Unknown

### ISSUE THREAD

**Issue by matejcik** [microsoft/pyright#8136]
**Describe the bug**
```python
import typing

class Cls:
    _some_type: type
    _any_type: type[typing.Any]
    _concrete_type: type[type]

reveal_type(Cls._some_type)  # information: Type of "Cls._some_type" is "Unknown"
reveal_type(Cls._any_type)  # information: Type of "Cls._any_type" is "Any"
reveal_type(Cls._concrete_type)  # information: Type of "Cls._concrete_type" is "type[type]"
```

It seems that pyright incorrectly "upgrades" the member from `type[Unknown]` to `Unknown`, dtto with `Any`.

This can of course lead to problems, such as:

```python
def foo() -> type:
    ...

class Cls:
    _type: type | None = None

    def get_type(self) -> type:
        if self._type is None:
            self._type = foo()
        return self._type  # error: Expression of type "Unknown | None" is incompatible with return type "type"
```

**VS Code extension or command-line**
both extension and cli
**1.1.358** and newer (up to current 1.1.367) report this as error.
_(Earlier versions would report `self._type` from the second example to be of type `type | Unknown`, which looks like a different bug, so my guess would be that it's not a "regression" so much as a problem uncovered by solving a different problem?)_

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.368.
