### ISSUE TITLE
failed use "--version" when debug

### ISSUE THREAD

**Issue by zhuangzhuang** [microsoft/pyright#814]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots or Code**
![捕获](https://user-images.githubusercontent.com/521058/87002968-5672de80-c1ed-11ea-9b65-55420f034c48.PNG)

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.

**Additional context**

**Comment by erictraut** [comment]
Sorry, but I don't understand problem you are reporting. Could you please fill in the issue template?
