### ISSUE TITLE
Inheriting class doesn't recognize kw_only=True from parent class

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#8140]
This comes from mypy issue https://github.com/python/mypy/issues/17375.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.368.

**Comment by npip99** [comment]
![Image](https://github.com/user-attachments/assets/cac96006-89b3-4338-b7d4-359de15ba38d)

Checking on pyright version `1.1.36` and this issue doesn't appear to be fixed.

**Comment by 9en9i** [comment]
Still not working in version 1.1.405

**Comment by erictraut** [comment]
This change was reverted because of [this discussion](https://discuss.python.org/t/dataclass-transform-inheriting-class-doesnt-recognize-kw-only-true-from-parent-class/55734/2). The `dataclass_transform` behavior is spec'ed to follow the behavior of the built-in `dataclass` class. In this case, pydantic unfortunately deviates from the behavior of `dataclass`.
