### ISSUE TITLE
How to set special pythonPath from command line flag?

### ISSUE THREAD

**Issue by zhuangzhuang** [microsoft/pyright#815]
**Is your feature request related to a problem? Please describe.**
when use command line there has no why to set pythonPath
![image](https://user-images.githubusercontent.com/521058/87005494-ac498580-c1f1-11ea-8a6f-40c65a78cee3.png)

**Describe the solution you'd like**
add flag to select pythonPath full pathname.
https://github.com/microsoft/pyright/blob/master/docs/command-line.md

**Additional context**

**Comment by erictraut** [comment]
There are two ways you can do this:
1. If you have a pyrightconfig.json file, you can specify an "execution environment" and list all of the extra search paths in the "extraPaths" array. For an example, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md#sample-config-file).
2. If you don't provide a configuration, Pyright will try to invoke the python interpreter to ask it for its list of import resolution paths.

Import resolution in Python (and therefore in Pyright) is very complicated. If you're having problems configuring it correctly, you can try passing the "--verbose" flag to the command-line, and it will print additional logs that may help you diagnose the configuration problem.
