### ISSUE TITLE
Type "UnionType" is incompatible with type ...

### ISSUE THREAD

**Issue by nrbnlulu** [microsoft/pyright#8151]
**Describe the bug**
I am trying to specialise a function for union using `type[<uniont_type>]` why isn't is possible?
*Sorry for the lame description I couldn't find the correct terms. I hope the example is enough though.*

```python
from typing import Iterator, TypeVar, Callable

T = TypeVar("T")


def get_deserializer(type_: type[T]) -> Callable[[bytes], T]:
    # get deserializer somewhow
    raise NotImplementedError()


class Foo:
    ...
class Bar:
    ...

reveal_type(get_deserializer(Foo))
reveal_type(get_deserializer(Foo | Bar))
```
```
Argument of type "UnionType" cannot be assigned to parameter "type_" of type "type[T@get_deserializer]" in function "get_deserializer"
  Type "UnionType" is incompatible with type "type[T@get_deserializer]"  (reportArgumentType)
```
Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCSMApiAIYy4A0UAKosQGpkg0DCZANp2QEafEAUINpQAvHQbMQACgBEtOQEphggCbFgUNMRgB9DQGdSSLkgBepGfATE9ALlgMA2rQC6SqAFoAfFA7cfALOzrxwJIZuNO72glDxUADE2rpQRiZmliBQhpDEAO4AFmD5cQnkSMZQAHJgMATYAhDEKCRqAKIg4LIqwgDGPIaGUABiYGCxCVAAdLOCA2RDUABCLJMJs9PCIMQAbsRcejbEMjr66SCmnBZWY2BKvTv7h8enugbExpeZt%2BNQAD4rFgPYRAA)

**Comment by erictraut** [comment]
This is prohibited by the [python typing spec](https://typing.readthedocs.io/en/latest/spec/special-types.html#type).

A type that is compatible with `type` is assumed to be callable, where the call invokes the constructor. This would not work with a `UnionType` object.

You may be interested in a new proposal for `TypeForm`: https://discuss.python.org/t/typeform-spelling-for-a-type-annotation-object-at-runtime/51435/39.
