### ISSUE TITLE
Handle Function Declarations in `if`/`else`

### ISSUE THREAD

**Issue by max-muoto** [microsoft/pyright#8153]
Currently, if you try and have some conditionally logic for defining a function, you'll end up with `Function declaration "wrapped" is obscured by a declaration of the same name` error. Doing this can be quite helpful if you have some decorator wrapping logic, perhaps trying to handle an async/non-async case:

```python
def wrap_func(
    func: Callable[_P, _R] | Callable[_P, Awaitable[_R]],
) -> Callable[_P, _R] | Callable[_P, Awaitable[_R]]:
    if asyncio.iscoroutinefunction(func):

        @functools.wraps(func)
        async def wrapped(*args: _P.args, **kwargs: _P.kwargs) -> _R:
            # Custom logic...
            return await func(*args, **kwargs)
    else:

        @functools.wraps(func)
        def wrapped(*args: _P.args, **kwargs: _P.kwargs) -> _R:
            # Custom logic...
            return func(*args, **kwargs)

    return wrapped
```

[Pyright Playground
](https://pyright-play.net/?pyrightVersion=1.1.366&pythonVersion=3.13&strict=true&code=GYJw9gtgBAxmA28CmMAuBLMA7AzgOgEMAjGKdCABzBFSgGEDFjkAoUSKVATwvSwHMylarQAqPJADUCIADRQACjIIQAyhRTyAggHcC6VMyQtyVGlGABXLGjAIcJ4eYI4uNzC08sA%2BgCUoALxQ4hrSIAAUAER%2BkQCUPgqBispqGjBR3gpxngAmSMBQOiAEFN5WNuEsUNUW1jAAXPSM8EYA2pnyfgC6UAA%2BTUxEyO0K2noGbd1dsiyxUAC0AHwDLUNII52%2BPf0Mg8MdULr6hmvtW131VTXoBS5uMJh46Dhw4JYYWPl1GNjh5TCxS5XGo1AAC-1Qdng%2BCKJRwfzq8RBILuNigeQKsIoGhy4QAVDJ%2BDhGplCCAifI8XiANZ6cnEqCk2mEnBzJaM3yXZHcqAAYnolhwkOg8DA-HQMDwUuBPOqICQqEsICwUAI41o-3xLMpNLpRKRNSQ0KQQNl4O%2BUJhxQo8P%2BBu5GMK1pxWvpJIUZIpUCpzLdjI9vv1C2Wfi5spq-LoguFUFF4sl0vDNXliuVtQqBPpOsDrM8IJTSpVWJxQA)

**Comment by erictraut** [comment]
The code in your sample is attempting to declare the symbol `wrapped` in two contradictory ways. It's the same as if you had done this:

```python
if condition:
    x: int = 0
else:
    x: str = ""
```

At the core of pyright's design is the assumption that a symbol cannot have contradictory type declarations, so this is not something we would support.

What you can do in this case is use different symbol names to avoid the declaration conflict.

```python
def wrap_func(
    func: Callable[_P, _R] | Callable[_P, Awaitable[_R]],
) -> Callable[_P, _R] | Callable[_P, Awaitable[_R]]:
    if asyncio.iscoroutinefunction(func):

        @functools.wraps(func)
        async def async_wrapped(*args: _P.args, **kwargs: _P.kwargs) -> _R:
            # Custom logic...
            return await func(*args, **kwargs)

        return async_wrapped
    else:

        @functools.wraps(func)
        def sync_wrapped(*args: _P.args, **kwargs: _P.kwargs) -> _R:
            # Custom logic...
            return func(*args, **kwargs)

        return sync_wrapped
```
