### ISSUE TITLE
TypeError when not assigning to intermediate variable.

### ISSUE THREAD

**Issue by randolf-scholz** [microsoft/pyright#8165]
In the example below, the method

```python
    def __invert__(self) -> "WrappedEncoder[Y, X]":
        decoder = invert_encoder(self.encoder)
        return WrappedEncoder(decoder)
```

Type checks, but if we remove the intermediate variable and directly pass `invert_encoder(self.encoder)` as the argument to `WrappedEncoder`, we get type errors. Code sample in [pyright playground](https://pyright-play.net/?strict=true&code=MYGwhgzhAECiB2wD2ATApgJwNoA0A00AmgLoBcAUNFdOgGbRqKpoAUEaItBAHqdPtAD0ASmgBaAHxE%2BAOjmVqdGmmTo2HLtACefQgRHipOWfPJKAlvABumAC4B9Rqsy4CJFmj4Jn2ASX2iknBM6Nh6-GTQcjLk5KCQMADqGGAADqloKN7Mvm7ELNmhrkTEwhTUDCGYXlW5JbEVSvb2luYO9uqcBE45NT7FJIFSAHJI8J4KFVTsnDI9odAAvJU%2BDYpo9M2WNhjtnbRD0ABEyWkZWbVY4TjER%2BVTVOg%2BS9Dbdo61%2B3O1wpNTGGhbABXDDwaCndKZQqYFhPHKiaAAYmggFByNaPDavax2faHE4pSEXfrXW73B4A4Gg8EE87QjAsN67D4%2BL7zTDCBHIwAy5NB0cp6Gz9jw%2BAIDEFCGT-oCQWCZrRvj4FcwWNxfn8lHC1HKCDoiAFDPxJRUKTLoHKlaEZJrWFpfkA)

```python
class Encoder[X, Y]:
    def encode(self, x: X, /) -> Y: ...
    def decode(self, y: Y, /) -> X: ...

def invert_encoder[X, Y](e: Encoder[X, Y], /) -> Encoder[Y, X]: ...

class WrappedEncoder[X, Y](Encoder[X, Y]):
    encoder: Encoder[X, Y]

    def __init__(self, encoder: Encoder[X, Y]) -> None:
        self.encoder = encoder

    def __invert__(self) -> "WrappedEncoder[Y, X]":
        decoder = invert_encoder(self.encoder)
        return WrappedEncoder(decoder)  # ✅

    def invert(self) -> "WrappedEncoder[Y, X]":
        return WrappedEncoder(invert_encoder(self.encoder))  # ❌ 

    def encode(self, x: X, /) -> Y:
        return self.encoder.encode(x)

    def decode(self, y: Y, /) -> X:
        return self.encoder.decode(y)
```

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.373.
