### ISSUE TITLE
Respect `PYTHONSAFEPATH` if set

### ISSUE THREAD

**Issue by thejcannon** [microsoft/pyright#8168]
Docs links:
- https://docs.python.org/3/using/cmdline.html#envvar-PYTHONSAFEPATH
- https://docs.python.org/3/using/cmdline.html#cmdoption-P

> Don’t prepend a potentially unsafe path to [sys.path](https://docs.python.org/3/library/sys.html#sys.path):
> `python -m module` command line: Don’t prepend the current working directory.
> `python script.py` command line: Don’t prepend the script’s directory. If it’s a symbolic link, resolve symbolic links.
> `python -c code` and `python` (REPL) command lines: Don’t prepend an empty string, which means the current working directory.

Reproducer:

```console
$ mkdir foo
$ cat <<EOF > example.py
import foo
EOF
$ export PYTHONSAFEPATH=1
$ pyright example.py
```

doesn't error on `foo` import

but:

```console
$ python -c 'import foo'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'
```

**Comment by erictraut** [comment]
Pyright is working as designed here, so I don't consider this a bug. I'm going to change this to an enhancement request instead.

I'm also going to reject this enhancement request for now. This is unlikely a feature we would ever implement, but it's possible we might reconsider if there's sufficient interest from pyright users (in the form of upvotes).

**Comment by thejcannon** [comment]
Would you consider the enhancement request if it was a new flag for pyright?

The underlying issue is that folks (who very much don't understand implicit namespace packages) are getting confused why pyright locally (due to some empty doors, but again they don't know that) is giving them different errors than in CI.
