### ISSUE TITLE
Erroneous `reportArgumentType` with `ParamSpec` using `Callable` with `TypeVar` Argument

### ISSUE THREAD

**Issue by ringohoffman** [microsoft/pyright#8170]
**Code or Screenshots**

```python
from typing import Callable, Generic, ParamSpec, TypeVar, reveal_type


class PreTrainedModel:
    ...

class LlamaModel(PreTrainedModel):
    ...

TransformerT = TypeVar("TransformerT", bound=PreTrainedModel)
BlockEstimatorP = ParamSpec("BlockEstimatorP")
BlockEstimatorT = TypeVar("BlockEstimatorT")

class Model(Generic[BlockEstimatorP, BlockEstimatorT]):
    def __init__(
        self,
        block_type: Callable[BlockEstimatorP, BlockEstimatorT],
        *args: BlockEstimatorP.args,
        **kwargs: BlockEstimatorP.kwargs,
    ) -> None:
        ...

class TransformerBlock(Generic[TransformerT]):
    def __init__(
        self,
        transformer_type: type[TransformerT],
    ) -> None:
        ...

# Argument of type "type[LlamaModel]" cannot be assigned to parameter "transformer_type" of type "type[TransformerT@TransformerBlock]"
#   Type "type[LlamaModel]" is incompatible with type "type[TransformerT@TransformerBlock]"
model = Model(TransformerBlock, LlamaModel)
reveal_type(model)  # Type of "model" is "Model[(transformer_type: type[TransformerT@TransformerBlock]), TransformerBlock[Unknown]]"

model2 = TransformerBlock(LlamaModel)  # OK
reveal_type(model2)  # Type of "model2" is "TransformerBlock[LlamaModel]"

```

[Playground URL](https://pyright-play.net/?pythonVersion=3.13&strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDCAhgDYlEBGJApgDRQDi1K1ISAxvQApEhEQBlBNU5QAKomoA1XvRDUAbtVIB9eMIBQW9uQDOuqF3li%2BqagBMAsmHPUSALg1RnUAHTvtegwBlyEIta2JAAURtQmRGZWNnYAlI4ubh4aESi6wLgQrGJQALzikjIgwQBEqemZ2SX0FGAArijmuWERUYFxGgBCJGDsANYAorowWEQwuFx5hrz8QiKl3b2Dw6PjIFwlsV09-UMj-ms5%2BRLCRQs7y-tjuGKbnkT6UO0hTCxs7ADai7srBxP030uqxuAF14k4XLZgFAVCpUEgYLDghDEs5dHZgLQUaiqEs1JJ7IRSOQqNQvhc9sD1gCKb9riAxCCsaiXAAqXhoXSEwGUv7rVwc3TMllQVmsvoAd0F3NpVzWXFcksFwucsSgAFoAHxQAByYBYCRF7lc90e5QyICyIEBwVerA4H3NlQZYMNzihMLhKARSOxiXRJExfpcMD4aQtVvxwkJ6jJTst2SZ2LVWt1%2BuobtRxq0AGIoABBEBoOpZFD4MDQ2NQEqxj6%2BfgBGIkEElKDsIgoFBgfAUahQB66JBoFjmWBgKAIGZZGCsauhjsVBMgKPUVsV2CSOeSR1hxdWsQAAXjVsBLY0eecJz7Ne39f8zxbmAMqHYkEnI1JUAlCIAFhvhFuwg7guEbZEeu6gdaFxnhATZTM8wTHqwgL0HejZBFs8hKKosbBLBGHOHmV5QOuJT4XYrZIAYJTPB8wTzuGzorjG25IQy4Egc6p6xPQbGAh8ACqKB9F2EooCCZ4aORJAAExTHxFzBGhzxqlAeYAPIANIaFhygkCueFNjJqlEZupHSTJlHUQpSx1n46F2GeQA)

**Describe the bug**

There shouldn't be any difference in acceptability between the last 2 calls. They are functionally equivalent.

**VS Code extension or command-line**
```console
$ pyright --version
pyright 1.1.367
```

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.370
