### ISSUE TITLE
Overridden method with additional default parameters loses parent type information

### ISSUE THREAD

**Issue by mmdanggg2** [microsoft/pyright#8178]
<h3> Environment data </h3>

-   Language Server version: 2024.6.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.13
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
class A():
    def test(self, foo: str):
        print(foo.capitalize())


class B(A):
    def test(self, foo, bar: str = "baz"):
        print(foo.capitalize() + bar)

```

<h3> Repro Steps </h3>

1. Override a parent class method and add a new parameter with a default value

<h3> Expected behavior </h3>

Unspecified parameter types should be inferred from the parent definition, as they are when the additional parameter is not there

<h3> Actual behavior </h3>

Unspecified parameter types are lost and must be specified again
![image](https://github.com/microsoft/pylance-release/assets/3161587/31703f52-fb7b-4cd7-9b3d-6e40d5f4451a)

**Comment by mmdanggg2** [comment]
Understandable, I was just starting to mess around with generics and was confused why this one method had no type information when all the other methods correctly listed their types. It just feels inconsistent, especially when I'm using @override and any other change was correctly flagging that it was an incompatible override, surely widening to All type is also incompatible?

**Comment by erictraut** [comment]
> surely widening to `All` type is also incompatible

I can see why you'd think it's incompatible, but it's actually not. The `All` type is consistent with all other types in the Python type system. This is intentional, as it allows for gradual typing.
