### ISSUE TITLE
More intuitive find-definition behavior within VS Code extension

### ISSUE THREAD

**Issue by leungbk** [microsoft/pyright#818]
**Describe the bug**
``` python3
def hello():
    a = 1
    a += 1
    return 42
```

Within VS Code, invoking Go To Definition on `a` at the line `a += 1` presents two candidates for the definition, which I wouldn't have expected. But the deliberate manner in which `DefinitionProvider` is written makes me suspect, as someone who isn't familiar with many Python idiosyncrasies, there is a good reason for this.

**Expected behavior**
Jump to `a = 1`, in contexts like these where there is clearly only one definition.

**Comment by erictraut** [comment]
The definition of "Definition" varies from language to language. In typed programming languages, there's usually one location where a symbol is defined along with its type. In Python, symbols are introduced to a scope by virtue of being assigned. And oftentimes in Python, a symbol's type isn't annotated, so it must be inferred from all of the places where it is assigned.

Take the following examples:

```
a = 1
a = "hi"
```

```
if foo():
  a = 3
else:
  a = "hi"
```

```
class Foo:
  def method1():
      self.a = 3

  def method2():
      self.a = "hi"
```

Ask yourself the following: where is the symbol `a` "defined" in each of these cases? In practice, a symbol is "defined" every time it is assigned in Python. Its type, if not explicitly annotated, is the union of the types that are assigned to it. In the three examples above, the inferred type is `Union[int, str]`.
