### ISSUE TITLE
finding error statsmodels.api and fbprophet

### ISSUE THREAD

**Issue by manishmanimidipally** [microsoft/pyright#8182]
If you have a question about a behavior that you’re seeing in pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem.

**Describe the solution you’d like**
A clear and concise description of the solution you would like to see.

import statsmodels.api as sm
from fbprophet import Prophet
not gettng librabries

**Comment by erictraut** [comment]
You haven't provided enough information in your enhancement request, so I'm going to close the issue.

If you would like to request a new feature, please fill out the template in its entirety.
