### ISSUE TITLE
Recent type alias enhancement does not always work

### ISSUE THREAD

**Issue by InSyncWithFoo** [microsoft/pyright#8185]
Reproducible example ([playground](https://pyright-play.net/?pyrightVersion=1.1.368&pythonVersion=3.13&strict=true&code=C4TwDgpgBAcgygWQIZigXigEwJYGNgDaAzsAE5QA%2BsA9gHYQA0UJpAugLABQXmEAZlD4AKAPoAuWIhQBKMVygKoAYkVQAeho1Qk%2BAK5IANhIVDQkbQexIi0ycjASzEAjnzEylGvSYtWHTqoqqsEQAB6Q%2BBCYEqbg0IZWNnYo6Fh4hCyeMHSMzGT%2BqvKKSEip8PZFCkEKmlq41KSkEPjGseYJ1rblKBIAKnEAgpbW-ZBclVBNAG4QhiJOQiXSE9XBCvWNzcDGoxBDibvjAYoipRglK6paxXqGxlBCU0ikVgBGBhC2JRLdYJdrijCEWAURiTxeSHen20SD6g2GREO3GRTigvQGqUyVGwtGAR14AgA5qI%2BgNbABaAB8XggcmOVSuam0tyMija8QRtnRjjiBBxwFYnic7jY-xC4S2oIeqI6SXRqX5nhYR1UUymqXRYvUTJ0wH0rJMMs5aIGPMgfNxgqowt8WsBEsi0Qe4LeHy5prR8IOcRVimmswM8zijymy3pygBuv192F-KtUBt%2BTtCiBkqdu32Ix9yNUInVGDVWq0UbubJdkLdUDVpOTUFTjrBz1d0OrnsgmcR2a4QA), `^` signals "hover"):

```python
type NSMap = dict[str | None, str]

def f(_: NSMap):
    #    ^^^^^ actual:   (type alias) NSMap: type[dict[str | None, str]]
    #          expected: (type alias) NSMap = dict[str | None, str]

    aa = NSMap
    #    ^^^^^ correct:  (type alias) NSMap: TypeAliasType

    reveal_type(aa)
    #          correct:  TypeAliasType

    _a = aa
    #    ^^    actual:   (variable) aa: NSMap
    #          expected: (variable) aa: TypeAliasType
```

```python
type TA = str | int

def g(_: TA) -> None:
    #    ^^ actual:   (type alias) TA: type[int] | type[str]
    #       expected: (type alias) TA = int | str

    vv = TA
    #    ^^ actual:   (type alias) TA: type[int] | type[str]
    #       expected: (variable) TA: TypeAliasType

    reveal_type(vv)
    #       actual:   type[int] | type[str]
    #       expected: TypeAliasType

    _v = vv
    #    ^^ actual:   (variable) vv: TA
    #       expected: (variable) vv: TypeAliasType
```

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.370
