### ISSUE TITLE
pip package?

### ISSUE THREAD

**Issue by javier-alvarez** [microsoft/pyright#819]
How do I configure my build to use pyright without taking a dependency on npm?

**Comment by erictraut** [comment]
The command-line version of pyright runs in node, so you will need node installed on your system. Npm (the node package manager) ships with node. You don't technically need npm to run pyright, but it is required to install it.

**Comment by tekumara** [comment]
mypy, pyre and pytype don't have the node dependency. They have a lower barrier to entry.

**Comment by erictraut** [comment]
Pyright is written in TypeScript (and compiled to Javascript) for reasons of performance and for integration with VS Code. It therefore requires a Javascript environment, which is provided by node.

Installing node is no more difficult than installing a Python environment. If you find that node is truly too much of a barrier for adoption, then you do have other options like mypy.

**Comment by tekumara** [comment]
Having a pip distribution that bundled the node (or [deno](https://github.com/denoland/deno)?) runtime with pyright could ease adoption.

**Comment by tekumara** [comment]
See https://github.com/RobertCraigie/pyright-python which is pip installable. It installs node via `nodeenv` and pyright via `npx`.
