### ISSUE TITLE
Assertion in `computeMroLinearization` seen in Pylance telemetry

### ISSUE THREAD

**Issue by debonte** [microsoft/pyright#8191]
This is a new assert that was added in https://github.com/microsoft/pyright/pull/8086. I updated the links below to point to pyright instead of pyrx, so they should work for you.

Error: Debug Failure. False expression.</br>at assert <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/typeUtils.ts#L3159'>pyright-internal/src/analyzer/typeUtils.ts:3159:20</a></br>at cb <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/common/cancellationUtils.ts#L32'>pyright-internal/src/common/cancellationUtils.ts:32:15</a></br>at invalidateTypeCacheIfCanceled <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L16530'>pyright-internal/src/analyzer/typeEvaluator.ts:16530:15</a></br>at getTypeOfClass <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21109'>pyright-internal/src/analyzer/typeEvaluator.ts:21109:38</a></br>at getTypeForDeclaration <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21429'>pyright-internal/src/analyzer/typeEvaluator.ts:21429:29</a></br>at getInferredTypeOfDeclaration <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L19371'>pyright-internal/src/analyzer/typeEvaluator.ts:19371:15</a></br>    at None <a href='https://github.com/microsoft/pyrx/blob/c4ef9375a3e8ac2c86b6ac29668426756cf78e0c/packages/pylance-internal/src/languageService/semanticTokenProvider.ts#L653'>pylance-internal/src/languageService/semanticTokenProvider.ts:653:39</a></br>at func (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L19218'>pyright-internal/src/analyzer/typeEvaluator.ts:19218:39</a></br>at evaluateTypesForImportFrom <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L19874'>pyright-internal/src/analyzer/typeEvaluator.ts:19874:20</a></br>at callback <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/common/timing.ts#L40'>pyright-internal/src/common/timing.ts:40:19</a></br>at evaluateTypesForStatement <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/checker.ts#L1556'>pyright-internal/src/analyzer/checker.ts:1556:28</a></br>at visitImportFrom <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L433'>pyright-internal/src/analyzer/parseTreeWalker.ts:433:28</a></br>at visit <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L933'>pyright-internal/src/analyzer/parseTreeWalker.ts:933:20</a></br>at visitNode <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L915'>pyright-internal/src/analyzer/parseTreeWalker.ts:915:36</a></br>at walk <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/checker.ts#L279'>pyright-internal/src/analyzer/checker.ts:279:18</a></br>    at None <a href='https://github.com/microsoft/pyrx/blob/c4ef9375a3e8ac2c86b6ac29668426756cf78e0c/packages/pylance-internal/src/common/indentationUtils.ts#L1030'>pylance-internal/src/common/indentationUtils.ts:1030:75</a></br>at func (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L922'>pyright-internal/src/analyzer/parseTreeWalker.ts:922:14</a></br>at walkMultiple <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L917'>pyright-internal/src/analyzer/parseTreeWalker.ts:917:17</a></br>at walk <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/checker.ts#L279'>pyright-internal/src/analyzer/checker.ts:279:18</a></br>at walk <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/checker.ts#L2834'>pyright-internal/src/analyzer/checker.ts:2834:17</a></br>at _walkStatementsAndReportUnreachable <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/checker.ts#L260'>pyright-internal/src/analyzer/checker.ts:260:13</a></br>    at callback <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/common/timing.ts#L40'>pyright-internal/src/common/timing.ts:40:19</a></br>at callback <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/common/logTracker.ts#L61'>pyright-internal/src/common/logTracker.ts:61:19</a></br>at log <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/sourceFile.ts#L906'>pyright-internal/src/analyzer/sourceFile.ts:906:32</a></br>at callback <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/common/logTracker.ts#L61'>pyright-internal/src/common/logTracker.ts:61:19</a></br>at log <a href='https://github.com/microsoft/pyright/blob/5d7736905665c180e48b89a053927ea387cc047a/packages/pyright-internal/src/analyzer/program.ts#L1886'>pyright-internal/src/analyzer/program.ts:1886:32</a></br>

**Comment by erictraut** [comment]
Thanks for reporting. I'm not 100% sure how this can occur, but I have some theories. I haven't been able to repro it on demand yet. In any case, there's an easy fix that removes the assert, so I'll add that.

**Comment by erictraut** [comment]
This is included in pyright 1.1.369.

**Comment by debonte** [comment]
@erictraut, we're still seeing this in telemetry for Pylance 2024.6.102 which includes Pyright 1.1.369. The assert that you removed in the linked commit is not the assert we're hitting, which is this one: https://github.com/microsoft/pyright/blob/1168be715e64961106b6cd18c01db87ed285d715/packages/pyright-internal/src/analyzer/typeUtils.ts#L3162

**Comment by erictraut** [comment]
Yes, this is already fix in the main branch. It was reported by a pyright user who provided a concrete repro.

In somewhat related news, Shantanu (hauntsaninja) just expanded the number of projects that mypy_primer runs on pyright by about 10x. This expanded set of tests includes at least one project that would have caught this regression before it was merged.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.370
