### ISSUE TITLE
`validation.yml` uses `actions/cache@v3`, which uses a `deprecated` version of `Node.js`

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/pyright#8199]

**Comment by hamirmahal** [comment]
https://github.com/microsoft/pyright/actions/runs/9619864162

**Comment by hamirmahal** [comment]
![image](https://github.com/microsoft/pyright/assets/43425812/d674aade-da38-4b34-8fd3-ce4667ad0ab6)

**Comment by erictraut** [comment]
As I mentioned in the PR, I'm not sure what problem this is solving. Pyright's CI scripts are working fine for me. Is your concern that they may stop working at some point in the future? 

Out of curiosity, why do you care about the pyright build / CI environment?

**Comment by hamirmahal** [comment]
> As I mentioned in the PR, I'm not sure what problem this is solving. Pyright's CI scripts are working fine for me. Is your concern that they may stop working at some point in the future?

Yes. https://github.com/microsoft/pyright/pull/8201#issuecomment-2183872403 has some more information.
