### ISSUE TITLE
`foo = {hello := "world"}` reports `Operator ":=" is not allowed in this context without surrounding parentheses`

### ISSUE THREAD

**Issue by tamird** [microsoft/pyright#8216]
```python
foo = {hello := "world"}
```

**Comment by erictraut** [comment]
Interesting. It looks like the grammar was changed in Python 3.10 to accept this. In Python 3.8 and 3.9, this generated a syntax error. When I implemented support for `:=` initially, it was based on the 3.8 grammar.

I've updated pyright's parser to support this and emit an error only for older versions of Python.

**Comment by erictraut** [comment]
This is included in pyright 1.1.369.

**Comment by tamird** [comment]
It looks like 1.1.369 wasn't release to [pypi](https://pypi.org/project/pyright/#history). Is a delay expected?

**Comment by erictraut** [comment]
The [python wrapper for pyright](https://github.com/RobertCraigie/pyright-python) (the tool published to pypi) is maintained and published by someone else. He typically publishes an update to pypi within 24 hours after I publish a new version to npm.

**Comment by tamird** [comment]
Ah, sems it's [waiting for a human](https://github.com/RobertCraigie/pyright-python/pull/279).

**Comment by RobertCraigie** [comment]
v1.1.369 has been released to PyPi :)
