### ISSUE TITLE
string literal narrowing with `in` operator breaks with other types besides a tuple

### ISSUE THREAD

**Issue by Andrej730** [microsoft/pyright#8224]
See example below - it does work fine if we check if some literal type instance is in a tuple of literals but breaks if we use a list instead (or I guess it also breaks with other types, like set/dict).
```python
from typing import Literal, assert_type

STR_LITERAL = Literal["AA", "BB", "CC", "BA"]

def test_str(a: STR_LITERAL):
    if a in ("AA", "BB"):
        assert_type(a, Literal["AA", "BB"])
    else:
        assert_type(a, Literal["CC", "BA"])

    if a in ["AA", "BB"]:
        # error
        assert_type(a, Literal["AA", "BB"])
    else:
        # error
        assert_type(a, Literal["CC", "BA"])

    # Let's define a list of literals explicitly.
    b: list[Literal["AA", "BB"]] = ["AA", "BB"]
    if a in b:
        assert_type(a, Literal["AA", "BB"])
    else:
        # error
        assert_type(a, Literal["CC", "BA"])
```

Also noticed that narrowing string literals by any string methods is not supported. 
Any workarounds for this besides mentioning all possible literals in `str literal in (xx, yy, zz, ww)`?
```python
from typing import Literal, assert_type

STR_LITERAL = Literal["AA", "BB", "CC", "BA"]

def test_str_operations(a: STR_LITERAL):
    if a.endswith("A"):
        assert_type(a, Literal["AA", "BA"])  # error
    else:
        assert_type(a, Literal["BB", "CC"])  # error

    if a.startswith("B"):
        assert_type(a, Literal["BB", "BA"])  # error
    else:
        assert_type(a, Literal["AA", "CC"])  # error

    if "A" in a:
        assert_type(a, Literal["AA", "BA"])  # error
    else:
        assert_type(a, Literal["BB", "CC"])  # error
```

**Comment by erictraut** [comment]
Pyright is working correctly here, so this isn't a bug.

The type of the expression `("AA", "BB")` is `Tuple[Literal["AA"], Literal["BB"]]`. Literals are retained when inferring the type of a tuple expression. By contrast, the type of the expression `["AA", "BB"]` is `list[str]`. Literals are not retained when inferring the type of list, set, or dict expressions. Refer to pyright's documentation for details.

**Comment by Andrej730** [comment]
> By contrast, the type of the expression `["AA", "BB"]` is `list[str]`

But what about the example below? We explicitly define it as a list of literals but it still breaks in `else` block.
And any ideas for workarounds for narrowing string literals similar to string operations `endswith`, `startswith`, `str in literal`?

```python
    # Let's define a list of literals explicitly.
    b: list[Literal["AA", "BB"]] = ["AA", "BB"]
    if a in b:
        assert_type(a, Literal["AA", "BB"])
    else:
        # error
        assert_type(a, Literal["CC", "BA"])
```
