### ISSUE TITLE
assert on `getTypeOfClass` 

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#8227]
**Describe the bug**
getting assert on this callstack

![image](https://github.com/microsoft/pyright/assets/1333179/56fab86c-0ddb-4ef2-9021-3697a5a9dfd1)

**Code or Screenshots**

we got it from telemetry, so we don't have repro steps.

**VS Code extension or command-line**
we got it from pylance

**Comment by erictraut** [comment]
This is a duplicate of https://github.com/microsoft/pyright/issues/8191, which is already fixed in pyright 1.1.369.
