### ISSUE TITLE
Auto-import suggestions not provided for names followed by dots.

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#824]
**Describe the bug**
Pyright will give auto-import suggestions for unimported names, but if this name is followed by a dot (`.`), the auto-import suggestions will not be shown.

It's quite common that we copy & paste some codes from other files and try to resolve all the missing imports quickly, those codes might have names followed by dots.

Currently, I have to "workaround" this by type a character like `,` after the name to avoid this issue and trigger auto-import, then remove the character.

Please see these screenshots.
No auto-import suggestion provided:
![image](https://user-images.githubusercontent.com/3479453/87277136-4ec87800-c514-11ea-8a8b-27e9c7e67f30.png)

Auto-import suggestion provided:
![image](https://user-images.githubusercontent.com/3479453/87277198-66076580-c514-11ea-95d9-61b1da444c6a.png)

![image](https://user-images.githubusercontent.com/3479453/87277434-dd3cf980-c514-11ea-92da-27f5d8b2efe5.png)

![image](https://user-images.githubusercontent.com/3479453/87277515-065d8a00-c515-11ea-969b-7e86a4b7517f.png)

**Expected behavior**
Names followed by dots can trigger auto-import suggestion just like other cases.

**VS Code extension or command-line**
VSCode extension 1.1.52

Thanks!

**Comment by erictraut** [comment]
Thanks for the issue report. This will be addressed in the next version of Pyright.

**Comment by erictraut** [comment]
This is now fixed in Pyright 1.1.53, which I just published. It will also be in the next version of Pylance.
