### ISSUE TITLE
`@classmethod` in subclass cannot override `@staticmethod` in superclass and vice versa

### ISSUE THREAD

**Issue by 0scarB** [microsoft/pyright#8240]
**Describe the bug**
Unlike with MyPy, a compatible class method cannot override a static method from the superclass. An error also occurs in the reverse case when you try to override a class method with a static method.

**Code or Screenshots**
The following Python code recreates these errors. `B.meth` and `D.meth` cause errors. The specific error messages are provided as comments.

```python
import typing

class A:
    class_var: typing.ClassVar[int] = -1

    @staticmethod
    def meth() -> None:
        A.class_var = 1

class B(A):
    class_var: typing.ClassVar[int] = -1

    # Pyright Error:
    # Method "meth" overrides class "A" in an incompatible manner
    #   Base method is declared as a staticmethod but override is not
    #   Positional parameter count mismatch; base method has 0, but override has 1 (reportIncompatibleMethodOverride)
    @classmethod
    def meth(cls) -> None:
        cls.class_var = 1

class C:
    class_var: typing.ClassVar[int] = -1

    @classmethod
    def meth(cls) -> None:
        cls.class_var = 1

class D(C):
    class_var: typing.ClassVar[int] = -1

    # Pyright Error:
    # Method "meth" overrides class "C" in an incompatible manner
    #   Base method is declared as a classmethod but override is not
    #   Positional parameter count mismatch; base method has 1, but override has 0
    #   Parameter 1 mismatch: base parameter "cls" is keyword parameter, override parameter is position-only (reportIncompatibleMethodOverride)
    @staticmethod
    def meth() -> None:
        A.class_var = 1
```

**Expected Behaviour**
`B.meth` and `D.meth` should not cause errors.

**Why is this important?**
The disassembly of classes `A` and `B` shows why it's desirable to use a class method over a static method when you need to access class variables:
```py
import dis
dis.dis(A)
dis.dis(B)
```
```
Disassembly of meth:
  7           0 RESUME                   0

  9           2 LOAD_CONST               1 (1)
              4 LOAD_GLOBAL              0 (A)
             14 STORE_ATTR               1 (class_var)
             24 RETURN_CONST             0 (None)

Disassembly of meth:
 18           0 RESUME                   0

 20           2 LOAD_CONST               1 (1)
              4 LOAD_FAST                0 (cls)
              6 STORE_ATTR               0 (class_var)
             16 RETURN_CONST             0 (None)
```
The class method uses the faster `LOAD_FAST` operation to access the `A` (`cls`) whereas the static method accesses the global `A` using `LOAD_GLOBAL`. The consumer of the class does not care whether `meth` is a class method or a static method. This choice is an implementation detail that the implementer makes based on whether or not they need to access class variables, choosing the faster class method if they do.

When accessing class variables, using `cls.<attribute>` is preferable for the implementer because the class name can change without the access code being changed.

When writing a package, you may want the consumer of that package to subclass a superclass from the package, containing static methods. The consumer of the package should have the freedom to override the package's static methods with class methods as needed.

This behaviour diverges from the current MyPy implementation (I haven't tested other type checkers). This makes it harder for package maintainers because the have to test against multiple type checkers.

It's possible that there are cases where you want to differentiate between static methods and class methods (I can't think of any off the top of my head), possibly when using dunder methods or other magic. These cases are niche and should not be the enforced default behaviour (IMO). It's very understandable if this was an oversight in the current implementation of Pyright or maybe I'm missing some good reason for this to be the default behaviour.

**Test Environment (Versions, etc.)**
I tested with the following versions of Python, Pyright and MyPy:
```
Python 3.12.3
pyright 1.1.368
mypy 1.10.1
```
I ran Pyright like this:
```
pyright static-classmethod.py
```
and MyPy like this:
```
mypy --strict static-classmethod.py
```
MyPy returns:
```
Success: no issues found in 1 source file
```
---
Thanks for providing a type checker that's easy to set up in many editors!

**Comment by erictraut** [comment]
Pyright is working as designed here. A staticmethod is not equivalent to a classmethod when accessed through the class object, so Liskov is violated if you intermix the two. I don't know why mypy has chosen not to flag this as a type violation, but it probably should.

Of course, if you have reason to violate the type system in particular instances for performance or other reasons, you can suppress individual errors in your code, but I don't think a type checker should allow this by default.

This specific detail is not currently specified in the Python typing spec, but I plan to write a chapter soon to clarify the behavior.

**Comment by 0scarB** [comment]
I think this is worth thinking twice about. In the majority of cases a static method can be substituted with a class method. For example:
```py
import typing

class Base(typing.Protocol):
    @staticmethod
    def calc(): ...
    
class A(Base):
    @staticmethod
    def calc():
        return 1 + 2
        
class B(Base):
    class_var = 1

    @classmethod
    def calc(cls):
        return cls.class_var + 2
        
def call_calc(inst: Base):
    return inst.calc()
    
call_calc(A)
call_calc(B)
```
From the point of view of `call_calc`, `A` and `B` have the same interface (and can be substituted). This might be the reason MyPy permits it.

It's worth considering to what extent class methods and static methods actually differ and whether these differences should be externalised by the default behaviour.

For some background, I personally ran into this issue in my code and it would have been smoother experience with MyPy's current behaviour.

Your decision as a maintainer should out-weight mine so happily keep this closed but I think it's worth reconsidering.

**Comment by erictraut** [comment]
There's always a tension with type checkers between being more lax (permissive) to make things "smoother" for users who don't want to be bothered with certain type violations that they don't see as problematic in their code versus more strict (stringent) checks that catch more potential bugs.

In this particular case, I feel that pyright's behavior is justified and consistent with other decisions that I've made in pyright. Of course, if and when this behavior is defined in the [typing spec](https://typing.readthedocs.io/en/latest/spec/index.html), I will honor whatever the spec indicates. Until then, I don't plan to make a change in this behavior.

Pyright is currently the only Python type checker that is compliant with all of the existing [spec conformance tests](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html).

We're working to standardize some of these currently-unspecified behaviors to make it easier to move between type checkers and get deterministic behavior. If you have strong opinions about such behaviors, you're welcome to follow along and contribute to the discussions on the [Python typing forum](https://discuss.python.org/c/typing/32).

**Comment by 0scarB** [comment]
I get where you're coming from. I still think, practically speaking, that "smoother" would be better here and that the correctness guarantees gained by Pyright's behaviour are marginal. Go with what you think is best. Thanks for the clarification and info!
