### ISSUE TITLE
List[int] cannot be assigned to a parameter of type List[int | str]

### ISSUE THREAD

**Issue by Minituff** [microsoft/pyright#828]
Screenshot of the code
<img width="1132" alt="Screen Shot 2020-07-14 at 8 36 44 AM" src="https://user-images.githubusercontent.com/8152401/87445705-38bac600-c5ad-11ea-9ccd-e6f7fa8bc66c.png">

The actual code:
```python
from typing import List, Optional, Union, Dict, Any


def add(input_list: List[Union[int, str]]) -> List[int]:
    output_list = []

    for item in input_list:
        if isinstance(item, int):
            output_list.append(item)

    return output_list


input_list: List[int] = [1, 5, 6]
output_list = add(input_list)


# It should also be able to work like this
input_list: List[Union[int,str]] = [1, "two", "three", "four", 5, 6]
output_list = add(input_list)
```

I had also tried writing the function as:
```python
input_list: Union[List[str], List[int]]
```
But this defines _input_list_ as a list of strings OR a list of ints
The purpose of the function is to take a list of strings, or ints and return only a list of ints.

Pyright Version: 1.1.52
Python Version: 3.7.6 
Python VSCode Extension: (2020.6.91350)

I wanted to make sure I was using Pyright correctly, and if not. How would I structure my typing to work as intended here?
Thanks

**Comment by erictraut** [comment]
The `List` type in Python is a mutable type, which means that if you pass a list to a function, it is allowed to add to that list. You have declared that `input_list` is of type `List[int]` which means that it's guaranteed to contain only `int` entries. You then attempt to pass it to a function that accepts a parameter of type `List[Union[int, str]]`, which means that the function is able to insert both `int` and `str` entries into this list. This would violate the assumptions made by the original `input_list` type, so it is considered a type violation. In formal terms, the type variable for a `List` is considered `invariant`, which means that it's not legal to assign a `List[int]` to a `List[str]` or to a `List[Union[int, str]]`. The element types must match exactly. For more information about invariance, refer to [PEP 483](https://www.python.org/dev/peps/pep-0483/).

In your example, the function `add` does not need to modify the list, so a simple workaround here is to specify that the parameter `input_list` is type `Sequence[Union[int, str]]`. A `Sequence` is similar to a list except that it cannot be modified.
