### ISSUE TITLE
Paramspec checking issue

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#8294]
**Describe the bug**

```python
from collections.abc import Callable
from typing import ParamSpec

P = ParamSpec('P')

def call_f(f: Callable[P, object], *args: P.args, **kwargs: P.kwargs) -> object:
    return f(*args, **kwargs, name="foo")
```

This code type checks when name should be treated as invalid argument.

**VS Code extension or command-line**
pyright cli 1.1.369. Fairly recent regression 1.1.366 correctly flags the error while 1.1.367 passes.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.370
