### ISSUE TITLE
TypedDict shows error and cannot assign it in dict[str, TypedDict]

### ISSUE THREAD

**Issue by vladimir-sama** [microsoft/pyright#8297]
`Argument of type "dict[str, str | list[str] | int | bool | None]" cannot be assigned to parameter "value" of type "Game" in function "__setItem__"`

So this worked in VSCode with Pylance, now I am trying to use Zed with Pyright but it doesn't handle TypedDict.
That or I'm using it wrong.

```python

class Game(TypedDict):
    title:str
    image:str
    description:str
    command:List[str]
    is_shell:bool
    time_played:int
    last_played:int
    time_added:int

game_list : Dict[str, Game] = {}

# Asume all variables are there
        game_list[item_id] = {
            'title' : item_title,
            'description' : item_description,
            'command' : shlex.split(item_command),
            'image' : image,
            'last_played' : 0,
            'time_played' : 0,
            'time_added' : int(time.time()),
            'is_shell' : False
        }
```

**Comment by erictraut** [comment]
Could you provide a self-contained, minimal code sample that exhibits the problem? The code sample above references a bunch of symbols that are not defined.

**Comment by erictraut** [comment]
Here's an attempt to create a minimal repro, but this type checks without errors in pyright:

```python
from typing import TypedDict

class Game(TypedDict):
    title: str

x: dict[str, Game] = {"test": {"title": "test"}}
```

**Comment by vladimir-sama** [comment]
```
game_list[item_id] = {
            'title' : item_title,
            'description' : item_description,
            'command' : shlex.split(item_command),
            'image' : image,
            'last_played' : 0,
            'time_played' : 0,
            'time_added' : int(time.time()),
            'is_shell' : False
        }
```
Issue is here, defining an element like `game_list[string_key] = {All keys in Game}`

**Comment by vladimir-sama** [comment]
```python
from typing import TypedDict, Dict, List

class Game(TypedDict):
    title:str
    description:str
    dates_played:List[int]


game_list : Dict[str, Game] = {}

game_list['KEY'] = {
    'title' : 'GAME TITLE',
    'description' : 'GAME DESC',
    'time' : [1, 2, 3]
}
```
`Argument of type "dict[str, str | list[int]]" cannot be assigned to parameter "value" of type "Game" in function "__setitem__"`

**Comment by erictraut** [comment]
I'm not able to repro the problem with the above code sample. Here's the code in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgCYAiSAxjADRSU30AySAzjALABQPVANgEM2bKAHFBEYgAoiCMoxgBKAFw8oG2Ehj9iKjiHWbSxNlRBIEMJGBT6Yh7pqilBMUwH0EQuGRWsOAG1UGABdHgjuNEliD352fBUGahhAg3oJKVCoAF4oAG8AX0joqTiEwIByAGkAUQBNSuy8-KMNSusdYkqoJMqxAEEAWVrCAEkCZlrK2jaoSpMzCysbFB6%2BwZGGWoBlAGEZuYW3T29BX1J1qECARnoAJnoAZnDuYu4gA).

Perhaps you have an outdated version of pyright installed? Or maybe you have some custom configuration options specified?

**Comment by vladimir-sama** [comment]
Found it, `item_description` could have been `None` in my code.
This needs better errors, thanks for the help!
