### ISSUE TITLE
False positive on magic methods in `MagicMock`

### ISSUE THREAD

**Issue by PerchunPak** [microsoft/pyright#8306]
**Describe the bug**
This is probably an extreme edge-case, but if I redefine `return_value` at `MagicMock().__str__`, pyright says `Cannot assign to attribute "return_value" for class "function"`, even though it is valid code in runtime.

**Code or Screenshots**
![image](https://github.com/microsoft/pyright/assets/68118654/b4a9f671-ef43-428d-949e-dfc987c4b14d)

Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBArgdgSwC5IKYGckDoJgMYDWUCEADmCElALICGA5gntfgQFBvQC8NDTLhABQBKTlgD64zCElYQqJDBBxxAN1oAbGKig8ARAEYATAGY9QA)

**VS Code extension or command-line**
Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool? Which version?

command-line, 1.1.370

**Comment by erictraut** [comment]
Pyright is working correctly here, and this isn't a false positive.

The job of a type checker is to detect and report type violations, and your code has a type violation.
