### ISSUE TITLE
The pyright and pylance VSCode extensions interfere with each other

### ISSUE THREAD

**Issue by ileonte** [microsoft/pyright#832]
I get the following errors on project load when both the pyright and pylance VSCode extensions are enabled:
![image](https://user-images.githubusercontent.com/1776226/87475075-cab5e380-c62c-11ea-88c4-279eadc42331.png)

I have noticed this starting with version 1.1.52 of the pyright extension and version 2020.7.1 of pylance.
I have previously used both of these at the same time - versions 1.1.50 of pyright and 2020.6.1 of pylance have worked together for me in the past.

**Comment by erictraut** [comment]
Please don't use Pylance and Pyright together. They will conflict. I've posted a notice in the README indicating as such. They are effectively the same code, so running two copies will have unexpected and undesired effects.

**Comment by ileonte** [comment]
Understood. I was aware that pylance used pyright but they did use to work together so I thought this may be a bug. Thanks for the clarification.
