### ISSUE TITLE
__getitem__ method not defined on type axis

### ISSUE THREAD

**Issue by F-Depi** [microsoft/pyright#8336]
Simply attempting to access Axes items produces error complaining about getitem method not defined, but the code seems to work correctly. Here’s a snippet:

![image](https://github.com/microsoft/pyright/assets/120582465/8891acf8-3be6-4f7b-a1b7-625b220bb6b0)

```python
import matplotlib as plt
fig, axs = plt.subplots(1, 2)
axs[0].plot([1, 2, 3], [4, 5, 6])
```

Running  pyright on neovim.

**Comment by erictraut** [comment]
Pyright is working correctly here, so this isn't a bug.

This appears to be an issue in the matplotlib library. It includes an embeded stub file `matplotlib/axes/_axes.pyi` that defines the `Axes` class. This class definition doesn't include a `__getitem__` method, nor do any of its parent classes. If you think that it should include a `__getitem__` method, please report the issue to the maintainers of `matplotlib`.

**Comment by F-Depi** [comment]
Ok, is there a workaround at least?

**Comment by erictraut** [comment]
You could add a `# type: ignore` or `# pyright: ignore` comment to temporarily suppress the error while you're waiting for a fix from the matplotlib maintainers.
