### ISSUE TITLE
Imports resolution in Rye projects broke in 1.1.371

### ISSUE THREAD

**Issue by catwell** [microsoft/pyright#8367]
Steps to reproduce: install [rye](https://rye.astral.sh), then for instance:

```bash
mkdir repro
cd repro
rye init
rye add quart
echo "import quart" > src/repro/foo.py
rye install pyright
pyright
```

This worked up to version 1.1.370, with 1.1.371 you get:

> error: Import "quart" could not be resolved

I suppose the reason is microsoft/pyright#8341, because the behavior of the Python interpreter changes depending on the current path.

Is there a way to disable this sandboxing of the interpreter?

(I think this is an issue with pyright and not Rye but I have still opened [a bug on their end as well](https://github.com/astral-sh/rye/issues/1215).)

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.372.
