### ISSUE TITLE
It shall not be needed to reload the window when a pyrightconfig.json file has been created/ changed in a workspace root folder

### ISSUE THREAD

**Issue by jamilraichouni** [microsoft/pyright#837]
see #836

**Comment by erictraut** [comment]
Pyright already detects when an existing config file is modified or deleted, but it does not detect when a new config file is added.

**Comment by erictraut** [comment]
I've added support to detect when a new config file is added to a workspace. This will be in the next version of Pyright / Pylance.

**Comment by jamilraichouni** [comment]
Ah, that seems to be true. I should have better reported it immediately because I can't reproduce it. My fault.
You may close this one. Is it possible that I re-open it, if I can reproduce that behaviour?

**Comment by erictraut** [comment]
I'll leave this issue open until I release the next version that contains the fix.

**Comment by jamilraichouni** [comment]
Now I understand. :-)
Thanks for your great work!

**Comment by erictraut** [comment]
This is now fixed in Pyright 1.1.54, which I just published. It will also be included in the next release of Pylance.

**Comment by jamilraichouni** [comment]
Thank you Eric!
