### ISSUE TITLE
Regression: `is_dataclass(x)` returns `TypeIs[type[DataclassInstance]]` -- should be `TypeIs[DataclassInstance | type[DataclassInstance]]`

### ISSUE THREAD

**Issue by rsokl** [microsoft/pyright#8391]
Checking if object is an _instance_ of a dataclass type leads to unreachable code

```python
from dataclasses import is_dataclass
from typing import Any

def f(x: Any):
    if is_dataclass(x) and not isinstance(x, type):
        # this code is unreachable
```

I think this regression started in 1.1.366

**Comment by erictraut** [comment]
Pyright's behavior is correct here, so I don't consider this a bug. For comparison, mypy's behavior is the same.

The `is_dataclass(x)` call uses `TypeIs`, and it narrows the type to `type[DataclassInstance]. The `not isinstance(x, type)` call narrows this type to `Never`.

If you change the annotation for `x` from `Any` to `object`, it will work as you intend.
