### ISSUE TITLE
Ignore unused variables

### ISSUE THREAD

**Issue by xSpecialFoodx** [microsoft/pyright#8411]
So basically, if I have 1 variable i want to ignore normally I'd do: a, _ = b, however, if I have 2 variables i want to ignore without overwriting the first _, I can't then use the _ variable twice, normally I'd assume there's support for __, but apparently pylance doesn't recognize it as a variable to ignore.
I suggest adding support for `__`, and if not, then at least let me ignore that line, pylance doesn't support ignoring a line for unaccessed variables, from what I know.

**Comment by erictraut** [comment]
If you don't intend to use the variable for anything, then you can use `_` in all instances. It doesn't matter if you overwrite a variable if you never use its value.

Pyright (and therefore pylance) doesn't generate a diagnostic for an unused variable by default. You can request that it generate a diagnostic by enabling the `reportUnusedVariable` diagnostic check. If you don't want these diagnostics to appear in your code, you can leave it off.

**Comment by xSpecialFoodx** [comment]
> If you don't intend to use the variable for anything, then you can use `_` in all instances. It doesn't matter if you overwrite a variable if you never use its value.
> 
> Pyright (and therefore pylance) doesn't generate a diagnostic for an unused variable by default. You can request that it generate a diagnostic by enabling the `reportUnusedVariable` diagnostic check. If you don't want these diagnostics to appear in your code, you can leave it off.

its useful to have it on, but not in that case, i want a comment to turn it off for the specific line.

**Comment by erictraut** [comment]
You can use `# pyright: ignore[reportUnusedVariable]` to disable this diagnostic on a single line. Or you can use `# type: ignore` to disable all type checker diagnostics on the line.

**Comment by xSpecialFoodx** [comment]
> You can use `# pyright: ignore[reportUnusedVariable]` to disable this diagnostic on a single line. Or you can use `# type: ignore` to disable all type checker diagnostics on the line.

it doesn't work in my case in vscode

**Comment by erictraut** [comment]
Before adding the comment, are you seeing a diagnostic (i.e. a text range underlined with a red squiggle)? If so, the diagnostic should go away after you add the comment.

**Comment by xSpecialFoodx** [comment]
> Before adding the comment, are you seeing a diagnostic (i.e. a text range underlined with a red squiggle)? If so, the diagnostic should go away after you add the comment.
> 
> ![image](https://private-user-images.githubusercontent.com/7040122/348485936-4af0802d-83ac-4d20-a398-2a7aa34a9cca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4OTA0MDAsIm5iZiI6MTcyMDg5MDEwMCwicGF0aCI6Ii83MDQwMTIyLzM0ODQ4NTkzNi00YWYwODAyZC04M2FjLTRkMjAtYTM5OC0yYTdhYTM0YTljY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTNUMTcwMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2VkNmQ3OTViNWM5NzRmNWMzMTI3NDUwNGFiZGEzYTgwYTA5NWY1YTljMTUwNTZmNjNkNjJkZmQ3MjA0NTkxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2QuBuhK4VwpSYDKLVtRnz-lKQtUrLivbohFqD9X2qY4)

no, its just grayed out.

**Comment by erictraut** [comment]
> no, its just grayed out.

Then it's working as it should. That's not a real diagnostic you're seeing. The subtle "grayed out" behavior is caused by something called a "tagged hint". That's just a visual indicator that the symbol isn't used.

If you are using the pyright VS Code extension (as opposed to pylance) and you don't want pyright to generate any tagged hints (and therefore don't want to see any of these visual indicators), you can change the `pyright.disableTaggedHints` setting to true in your VS Code settings. Pylance doesn't currently provide this setting, but they are considering adding support for it.

**Comment by xSpecialFoodx** [comment]
> > no, its just grayed out.
> 
> Then it's working as it should. That's not a real diagnostic you're seeing. The subtle "grayed out" behavior is caused by something called a "tagged hint". That's just a visual indicator that the symbol isn't used.
> 
> If you are using the pyright VS Code extension (as opposed to pylance) and you don't want pyright to generate any tagged hints (and therefore don't want to see any of these visual indicators), you can change the `pyright.disableTaggedHints` setting to true in your VS Code settings. Pylance doesn't currently provide this setting, but they are considering adding support for it.

I'm using pylance.
I'm thinking it'd be nice either way to have it as a comment.
