### ISSUE TITLE
"possibly unbound" error is too strict

### ISSUE THREAD

**Issue by russelldavis** [microsoft/pyright#844]
```python
for x in [1,2,3]:
    print(x)
print(x)
```

On the last line, pyright says: `"x" is possibly unbound`. But `x` will always be bound at that point (with a value of `3`).

I'm guessing pyright is just handling the general case of an iterable that might be empty. But it seems worth handling the common scenario of iterating over a fixed list that is known to be non-empty.

**Comment by russelldavis** [comment]
On further thought, using the variable after the loop, without also assigning it in an `else` clause, is not as common, and is often a code smell anyway.

**Comment by erictraut** [comment]
Thanks for the suggestion.

Unfortunately, there's no way for a type checker to know whether a loop will be executed one or more times. It's completely dependent on the internal logic of the class that implements the iterator. 

One could argue that a type checker should have internal knowledge about internal implementations of certain built-in classes like `list`, but that's a very slippery slope, and I've avoided it so far. It's one of the core principles that I've stuck to throughout the development of Pyright.
