### ISSUE TITLE
Error when using Literal value variable in literal type

### ISSUE THREAD

**Issue by yanyongyu** [microsoft/pyright#8451]
**Describe the bug**

When using literal value assigned to a const var in Literal type, pyright complains about the var usage in Literal. I'm not sure this is valid use case or not, but this error has not occured before.

**Code or Screenshots**

[playground](https://pyright-play.net/?code=GYJw9gtgBApgdgV2gSwgBzCALlAooiAKFEiiwE81k4BzKVDbKAGWSxhAEMAbQwgY26cAzsKgAxMGAAU%2BJAEoAXISiqoAfXEB5LVAC8UAETAphvoW26DksADpNO1QGIylGIpZsOPANo37lgC6fJwerOxc3H46gc6wIOAghKGeEb7%2BDlqxUC5gANbJYV6RPuHeURlB2bkFQA)

```python
from enum import Enum
from typing import Literal

class Foo(Enum):
    _FOO = "foo"


FOO = Foo._FOO  # type: Literal[Foo._FOO]

a: Literal[FOO]  # error: reportInvalidTypeForm
a: Literal[Foo._FOO]  # ok
a: Literal[Literal[Foo._FOO]]  # ok
```

**VS Code extension or command-line**

pyright 1.1.372

related to https://github.com/yanyongyu/githubkit/issues/116

**Comment by erictraut** [comment]
Pyright is correct here. You are not allowed to use variables (whether or not they are marked `Final`) in a type annotation. There is good reason for this, and the typing spec is very clear on this point.
