### ISSUE TITLE
Recursion crash

### ISSUE THREAD

**Issue by grigoryvp** [Microsoft/pyright#85]
**Describe the bug**

Given lots of Python source code files that import and call each other methods, pyright will fails with "RangeError: Maximum call stack size exceeded" error, while mypy works fine.

**To Reproduce**

I created a simple generator that can be used to auto-generate a large enough source code base:

```sh
git clone https://github.com/grigoryvp/python-src-gen.git
cd python-src-gen
pipenv install
pipenv run python app.py generate --num-files 10000
cd out
npx pyright begin.py
```

Output is:
```
npx: installed 1 in 3.212s
No venvPath specified, and no search paths found for configured python interpreter.
Searching for source files
Found 1 source file
Error performing analysis: {}
```

**Expected behavior**
Analysis completion

**VS Code extension or command-line**
I'm running latest command-line version via npx.

**Comment by erictraut** [comment]
The internal crash is triggered by an exceptionally long import chain. Such long chains won't appear in real code, but they can occur in contrived cases like this. I've added logic to detect this case and report it as a meaningful error. I've currently set the max import chain length to 256.
