### ISSUE TITLE
Imprecise error message for `reportInconsistentConstructor`

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#8500]
Given this program:

```
from typing import Self

class X:
    def __new__(cls, *args: object, **kwargs: object) -> Self: ...
    def __init__(self, *args: object, a: int) -> None: ...
```

Pyright correctly reports `reportInconsistentConstructor`. However, the error message is not great:

```
Mismatch between signature of __new__ and __init__ in class "X"
  Signature of __init__ is "(..., a: int)"
  Signature of __new__ is "..."  (reportInconsistentConstructor)
```
I would interpret `Signature of __new__ is "..."` to mean that it's a signature like `Callable[..., T]`, but that's not what's happening here.

This came up in python/typeshed#12346.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.373.
