### ISSUE TITLE
Does not work in VS Code Jupyter notebook

### ISSUE THREAD

**Issue by han-steve** [microsoft/pyright#8528]
**Describe the bug**
While Pyright works perfectly in .py files, it doesn't activate in a jupyter notebook. Most online searches point me to setting `  "python.languageServer": "Pylance"`, but I don't have Pylance since I'm running on an open source build. 

**Code or Screenshots**
Open a jupyter notebook and type 
```
import math
math.sqrt()
```
Hover over `sqrt` to show doc string, nothing happens. However, using pyLance with the MS VS Code, it works. 

**VS Code extension or command-line**
Using VS Code extension. Running on code server.

**Comment by erictraut** [comment]
Pyright is working as intended here, so this isn't a bug.

Pyright is an open-source type checker. It offers some basic language server features like hover text, completion suggestions, signature help, semantic replace, go to definition, find references, and a handful of additional features. If you want more advanced language server features like support for notebooks, semantic highlighting, refactoring, indexing, etc., those are features that pylance adds on top of pyright. As you've noted, pylance is licensed to run only on VS Code, not on other editors like VS Codium, neovim, emacs, etc.
