### ISSUE TITLE
False unreachable after throwing in a suppressing context manager

### ISSUE THREAD

**Issue by rijenkii** [microsoft/pyright#8530]
**Describe the bug**
Pyright marks normally unreachable code that comes after a context manager that suppresses all exceptions as still unreachable.

**Code or Screenshots**
```python
import types
from contextlib import AbstractContextManager
from typing import Literal


class log_exceptions(AbstractContextManager[None, Literal[True]]):
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ):
        if exc_type and exc_value:
            print(exc_type, exc_value, traceback)

        return True


with log_exceptions():
    raise Exception("hello!")


print("I'm alive!")
```

When ran, script prints `<class 'Exception'> hello! <traceback object at 0x7f343a736cc0>` followed by `I'm alive!`, but in editor pyright marks all code after `raise` as unreachable.

**VS Code extension or command-line**
https://pyright-play.net/?strict=true&code=JYWwDg9gTgLgBDAnmApgZwFADMoRHAYwgDsYUAPGAG2ACM5RJY4BBWtGKAQwJgGESZSgFkuxLgHMUUbLnxIwwYhIbho8ADLAy3Khn0EqXNGjhUIEgPoUCKMDGAk0ACjYduvAaQoxR4qVAA2gByJCgANHBaOlxUgQAqUACuKAC6qQCUAFwYcHlwACYoWHCW1uTaZc65%2BbVoKFRY4TW1eTaWCihZCMgogQBCxigAouS29o7EqXAAPnChxBEtre0AbrEp3YP1o%2BMOJLPzYc2t%2BZw8KLQ8ANbdnWgAdIkXVwTX8b2HC0u12cu1wBK7U6cDEBTgaw2XX%2BpzgYCgShgzmBvUikKoKUi51sr2uGX0sLgUBQMCSUGIcESKX0GAA7toABZmCzlPaTFx-WrcYD1OC7Oz7YjOABEDIa5gAhML8fp4YiRQBJADk%2BFiwFWKCl%2BKAA

**Comment by erictraut** [comment]
Pyright is working correctly here, so this isn't a bug. 

If you want to indicate that your context manager swallows exceptions, you need to add an explicit return type annotation to the `__exit__` method indicating as such. You can use a type annotation of `Literal[True]` or `bool` in this case.

For more details, refer to [this section](https://typing.readthedocs.io/en/latest/spec/exceptions.html#context-managers) of the Python typing spec.

**Comment by rijenkii** [comment]
Sorry, I could swear I've tried that.
