### ISSUE TITLE
Overlapping imports resolved in wrong order

### ISSUE THREAD

**Issue by layday** [microsoft/pyright#854]
When importing from a package in Python, imports in `__init__` appear to take precedence, so that a symbol `foo` re-exported in `package.__init__` shadows a module `package.foo`, which contains the original `foo` symbol. However, when importing `package.foo` or `from package import foo`, Pyright resolves this to the module.  This is with the extension, version 1.1.53.

### To reproduce

Create a package `test` containing two files:

* `__init__.py`, the contents of which are `from .foo import foo`
* `foo.py` containing `foo = None`

Import the package from the enclosing folder in a new file `import_test.py`:

```py
from test import foo

reveal_type(foo)
```

Observe that the revealed type is "Module".  It should be "None".

For a real-world example, you can try this with `from prompt_toolkit.shortcuts import prompt`.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next version of Pyright & Pylance.

**Comment by erictraut** [comment]
This is now fixed in Pyright 1.1.54, which I just published. It will also be included in the next release of Pylance.
