### ISSUE TITLE
Having the Pyright and Python vscode extensions enabled causes docstrings to be duplicated in tooltips

### ISSUE THREAD

**Issue by ileonte** [microsoft/pyright#857]
The code I'm using to test this is as follows:
```
import sys as _sys
from select import epoll, EPOLLIN

def do_epoll(poller: epoll) -> None:
    '''
    `epoll()` a thing until some stuff happens . Take the result and frobulate it.
    Finally, returning nothing.
    '''
    poller.register(_sys.stdin.fileno(), EPOLLIN)
    poller.poll(-1)


poller = epoll()
do_epoll(poller)
```

* with the pyright extension disabled: ![image](https://user-images.githubusercontent.com/1776226/87886198-be15fe80-ca23-11ea-84a6-0d536f59676f.png)
* with pyright extension enabled: ![image](https://user-images.githubusercontent.com/1776226/87886251-1cdb7800-ca24-11ea-8ac4-cac800977778.png)

This doesn't seem to happen with the Python and Pylance extensions enabled (as far as I can tell Pylance takes over the tooltip contents).

I'm using version 1.1.54 of the Pyright VSCode extension.

**Comment by erictraut** [comment]
You should enable only one language server at a time. If you have a language server configured with the Python extension, then uninstall Pyright. If you have Pyright installed, then disable the language server in the Python extension. If you run multiple language servers at the same time, you will naturally get duplicate errors, hover strings, completion suggestion, etc.

For more details, see [the main README](https://github.com/microsoft/pyright#using-pyright-with-vs-code-python-extension) for Pyright.

**Comment by ileonte** [comment]
Fair enough. But just FYI there is nothing in the README that mentions not using Pyright with the Python extension. If fact the REAME states: `Pyright’s type-checking functionality and language features are now incorporated into a VS Code extension called Pylance` and then `Pylance is designed to work with the Python extension for VS Code.`

Also the REAME specifically calls Pyright a type-checker not a language server.
