### ISSUE TITLE
Argument of type "str | bytes" cannot be assigned to type "AnyStr@parse_qsl | None"

### ISSUE THREAD

**Issue by bukzor** [microsoft/pyright#8623]
I can reproduce this problem in my nvim LSP and [pyright-play.net](https://pyright-play.net/?code=MQAgDgngTglg5gCwC4C4QGcmwMZIFAwC2YA9lEiAK5QA2NMARgHRgCGU6ApngGZkhJOmAPrZWXEDAB2IANoAiPiXkAaEA3kN28gLoo8IQ%2BFhSkACmp1GLdlxsdOwgI7oaZwSLFcAlN6A), but not at the CLI. I don't know why :(

```python
import urllib.parse

for test_case in ["foo", b"bar"]:
    print(urllib.parse.parse_qsl(test_case))
    # └╴E  Argument of type "str | bytes" cannot be assigned to type "AnyStr@parse_qsl | None"
```

**Comment by erictraut** [comment]
This behavior is correct if you have `strictListInference` enabled. This is off by default, but it's enabled in "strict" mode. That may explain why you're seeing different behaviors.

When `strictListInference` is disabled, the type of the expression `["foo", b"bar"]`  is evaluated as `list[Unknown]`.  When `strictListInference` is enabled, it is evaluated as `list[str | bytes]`. This, in turn, causes `test_case` to be evaluated as `str | bytes`. As the error message indicates, `str | bytes` is not assignable to `AnyStr`, which is a value-constrained type variable that accepts only `int` or `str` but not a union of the two.

**Comment by bukzor** [comment]
For anyone else passing by, this is the workaround: 🤢 

```
import urllib.parse
for test_case in ["foo", b"bar"]:
   if isinstance(test_case, str):
      value = urllib.parse.parse_qsl(test_case)
   else:
      value = urllib.parse.parse_qsl(test_case)
   print(value)
```

**Comment by erictraut** [comment]
> Now I need to understand why/how a `str | bytes` is incompatible with `AnyStr`.

TypeVars with value constraints are used in situations where the type must be consistent anywhere that TypeVar is used. For example:

Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCKcAyjCAFAUAmApsFAIbXUAUAHgFyHFkgA0UONyKlyASigBaAHw8xIThSgqoIWjACuIFFHZQA1EKo16sWgGcYrRtysgoAHygAjODEuCXd8k9fvLcSVVJhYbL3ETDytWACJGWK9Yl1jJKABiKABhEEYLAAsKIA)

```python
from typing import AnyStr

def add(x: AnyStr, y: AnyStr) -> AnyStr:
    # x and y must be either `int` or `bytes`, not a combination of the two
    return x + y

def test(a: str | bytes, b: str | bytes):
    add(a, b)

test("a", b"b")  # Crash
```

**Comment by bukzor** [comment]
I've proposed a (slight?) amendment to the design intent, here https://discuss.python.org/t/proposal-relax-un-correlated-constrained-typevars/59658.
