### ISSUE TITLE
Coerce Literal return types in set/list/dict constructions

### ISSUE THREAD

**Issue by randolf-scholz** [microsoft/pyright#8638]
I found this discrepancy between `mypy` and `pyright` when writing unit tests for a `lazydict` type.

Code sample in [[pyright playground]](https://pyright-play.net/?strict=true&reportMissingModuleSource=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCGAzkQKZ4D68CpANFAMIEA2zBARs6QFDcAmUALxQA3gCIAgmIBcUNhHZ8CsgAz0xAIRlyCCpbICM6htvmLlUAEwBfbsTKVqpABR96fJAGMYAbSIwQeiZWDi4fHwBdelQYCIiASigoAGIoCEQ4WUBQcnoEOBAkNAALGFlAGXJuVNRgchBSPlkxD28-APpnZ0SAWgA%2BKAAZJBhyFh8VBKgAHygO7r7B4ZBRgwnp2ahegaGR5h9LBIixbiA), [[mypy-playground]](https://mypy-play.net/?mypy=latest&python=3.12&gist=fb7dfd151bee4b008bd2836a3c0d8495)

```python
from typing import assert_type, Callable

d = {"A": lambda: 0, "B": lambda: 1, "C": lambda: 2}
assert_type(d, dict[str, Callable[[], int]])  # mypy: ✅, pyright: ❌
# inferred: "dict[str, (() -> Literal[0]) | (() -> Literal[1]) | (() -> Literal[2])]"
```

<details> <summary> more elaborate example </summary>

Code sample in [[pyright playground]](https://pyright-play.net/?strict=true&reportMissingModuleSource=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAySMApiAIYA2ANFOQM71kwD68CJtAwlZeQEaUSAKGEAPAAwAuQsTJUA2hIC6UALxQJ4gIwyipCpQXbVG7eIBMeuYYUXTUC8IZM8bRCQAUk2vvlGVAEpnRmZ3Dm9tXxtFE2CXMPYvMQtog0V7eNC3JM8FHygxKML7WkokehgFVBhlYOFgFGkoHko%2BQRIFBWU0-yVlBz4IfgATciktRt0W3gEhLp7ZdKMTQfJhsalzRqsZtrnO7t7bezWN8acEnI9PRoluWY6F48UVOpDXVlyph-2no6WfVWWU%2B4S8O1%2B7XmAL8JwGIMSNwUd1oPygO0W5UqClaUMOixq8KgUAAxFAIIg4DJAKDktAQcBASDQAAsYDJADLkwiAA), [[mypy-playground]](https://mypy-play.net/?mypy=latest&python=3.12&gist=2653a043f1bbbeec5772bb39a832859d)

```python
from typing import Literal, assert_type, Callable

x0: Literal[0] = 0
x1: Literal[1] = 1
x2: Literal[2] = 2
assert_type(x0, Literal[0])
assert_type(x1, Literal[1])
assert_type(x2, Literal[2])
assert_type([x0, x1, x2], list[int])

fn0: Callable[[], Literal[0]] = lambda:0
fn1: Callable[[], Literal[1]] = lambda:1
fn2: Callable[[], Literal[2]] = lambda:2
assert_type(fn0, Callable[[], Literal[0]])
assert_type(fn1, Callable[[], Literal[1]])
assert_type(fn2, Callable[[], Literal[2]])
assert_type([fn0, fn1, fn2], list[Callable[[], int]])  # mypy: ✅, pyright: ❌
```

</details>

**Comment by erictraut** [comment]
This difference is intentional and not something that I plan to change. For reasons behind pyright's inference behaviors and why they differ from mypy's, refer to [this documentation](https://microsoft.github.io/pyright/#/mypy-comparison).

If you want to override pyright's default inference behaviors here, you can specify a type annotation for `d`:

```python
d: dict[str, Callable[[], int]] = {"A": lambda: 0, "B": lambda: 1, "C": lambda: 2}
```

**Comment by randolf-scholz** [comment]
I am aware of the difference and I prefer `pyright`'s behavior generally, but it seems that `Literal` is already sometimes excluded from this rule. After all, `pyright` also infers `list[int]` for `[1,2,3]`, and not `list[Literal[1, 2, 3]]`, and `list[Color]` for `[Color.RED]` when using enums.

So I assume internally there is some rule like 

*"When in context list/set/dict-constructor, and the type is a union of literals, then upcast to non-literal supertype"*.

However, there are some surprising consequences of this exception:

```python
t1 = (1,)
t2 = (2,)
t3 = (3,)
reveal_type({"A": t1, "B": t2, "C": t3})  # dict[str, tuple[Literal[1,2,3]]]
reveal_type({"A": (1,), "B": (2,), "C": (3,)})  # dict[str, tuple[int]]
```

What I was thinking is what if the behavior is changed towards:

*"When in context list/set/dict-constructor, and the type is a union, and if you can simplify the union by upcasting literals, then do so."*.

Not sure how disruptive this would be, but I believe this could simplify the behavior and avoid surprising examples like the one above, where the proposed algorithm would simplify the values type as:

```
tuple[Literal[1]] | tuple[Literal[2]] | tuple[Literal[3]]
-> tuple[int] | tuple[int] | tuple[int]  # replace with supertype
-> tuple[int]  # simplify redundant union
-> accept, since the union is simpler (fewer members)
```

**Comment by randolf-scholz** [comment]
Basically, Joins of Literals seem OK in certain contexts (literal set/list/dict constructors) as Literals refer to specific values of a type, and the current behavior of `pyright` reflects that.

Why, in the same context, shouldn't those same rules also apply to generics parametrized by Literals?
