### ISSUE TITLE
hover doesn't show func/method docs

### ISSUE THREAD

**Issue by jeffreyyjp** [microsoft/pyright#868]
**Describe the bug**
When hover to a func/method, the docs don't show well.

**To Reproduce**
Steps to reproduce the behavior.
Hover to any func/method that have docs

**Expected behavior**
Show docs

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
![image](https://user-images.githubusercontent.com/17985592/88028177-e4928180-cb6a-11ea-82f4-7340ca900762.png)

The second one shows it.
![image](https://user-images.githubusercontent.com/17985592/88028234-f411ca80-cb6a-11ea-91d3-674626d1d124.png)

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.

I'm using Pylance(2020.7.2) with Python(2020.7.94776) extension

**Additional context**

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next version of Pyright & Pylance.

**Comment by erictraut** [comment]
This is now implemented in Pyright 1.1.55, which I just published. It will also be included in the next release of Pylance.
