### ISSUE TITLE
type error on `map`

### ISSUE THREAD

**Issue by uf-fipper** [microsoft/pyright#8697]
## Environment data

-   Pylance version: v2024.8.1
-   OS and version: win11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.4

## Code Snippet

```python
a: list[int | None] = [1, 2, 3, None]
b = map(lambda x: x or 0, a)
```

## Expected behavior

`type(b) == map[int]`

## Actual behavior

![image](https://github.com/user-attachments/assets/7ef00d3c-31bb-4eed-98f1-26f0828e403f)

![image](https://github.com/user-attachments/assets/cc54f7dc-d500-4c37-9688-19106153808b)

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.388.
