### ISSUE TITLE
Exponentiation over constants can't figure out type 

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#871]
**Describe the bug**
i = 1 + 2
i2 = 1 ** 2

pyright correctly figure out "i" type as int but not for i2. it shows "Any"

**To Reproduce**
i2 = 1 ** 2 

and hover i2

**Expected behavior**
figure out i2 as int type

**VS Code extension or command-line**
vscode

**Additional context**
I guess this might be due to a result that could be exceeding max int value? but i = sys.maxsize +1 still shows int for "i", so that might not be the case?

**Comment by erictraut** [comment]
Pyright is doing the right thing in this case.

This appears to be a bug in the typeshed `builtins.pyi` file. If you look in the `int` class, it defines `__pow__` as follows:

```
    def __pow__(
        self, __x: int, __modulo: Optional[int] = ...
    ) -> Any: ...  # Return type can be int or float, depending on x.
```

It should probably be changed to include two overloads — one for float, and a second for int. Each should then return the appropriate type.

Please file a bug or submit a PR to typeshed.

**Comment by hauntsaninja** [comment]
Replied over at https://github.com/python/typeshed/issues/4352#issuecomment-662179901

@erictraut mypy includes some wording in their issue template that helps redirect people towards typeshed. It doesn't always work, but doing so might make your life a little easier :-)
