### ISSUE TITLE
`diagnosticMode` is no longer defaulting to "openFilesOnly"

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#8719]
With the latest changes in "main", I noticed that the `diagnosticMode` setting is no longer defaulting to "openFilesOnly". The Pyright VS Code extension is now analyzing all of the files in my projects.

**Comment by erictraut** [comment]
@rchiodo, looks like this is fallout from your settings change. Do you have time to look into this today, or should I?

**Comment by erictraut** [comment]
@rchiodo, it looks like this affects more than just `diagnosticMode`. A bunch of functionality is broken in the VS Code extension for pyright. It's pretty much unusable currently. I'm going to revert your change for now.

**Comment by rchiodo** [comment]
I can look now. Was OOF for a bit.

**Comment by rchiodo** [comment]
I'm not reproducing. Do you have an example layout? I only see errors for the opened files.

**Comment by erictraut** [comment]
I'm running debug also. Did you un-revert (i.e. reapply) your commit?

**Comment by rchiodo** [comment]
Reproing now. Not sure what the problem was. 

It seems there are some settings that should always be applied. 'checkOpenFilesOnly' is one of them. I'll need to double check all of the options in 'CommandLineOptions' to make sure they're not one of the json allowed settings.

**Comment by rchiodo** [comment]
Maybe it would be good to separate the parts of the CommandLineOptions into two sections. 'Json/pyproject.toml' configurable parts and those that are command line only.

**Comment by erictraut** [comment]
Yeah, sounds reasonable. Maybe move all of the Json/pyproject.toml configurable fields into a sub-structure that hangs off CommandLineOptions?

**Comment by rchiodo** [comment]
Yeah my thoughts exactly.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.376.
