### ISSUE TITLE
Getting an error using the Tinygrad machine learning framework in Pyright that I am not getting in Pylance/Pycharm's Version

### ISSUE THREAD

**Issue by aryang20** [microsoft/pyright#8721]
<img width="2301" alt="Screenshot 2024-08-09 at 12 20 02 PM" src="https://github.com/user-attachments/assets/f8f6fc8a-6a38-4100-b47c-2a609a0deae8">

**Comment by erictraut** [comment]
You haven't provided enough information for me to help you diagnose the problem.

If you think this is a bug in pyright, please follow the bug reporting instructions and provide a self-contained, minimal code sample (in text form) that repros the issue. Diagnosing issues from (tiny) screen shots isn't really feasible.

If you have questions about how to use pyright or a particular error message that you're seeing, feel free to post a question in the discussion section.

If you are seeing differences between pyright and pylance, you may find [this documentation](https://github.com/microsoft/pylance-release/blob/main/USING_WITH_PYRIGHT.md) useful.
