### ISSUE TITLE
PythonPath from vscode-pyright is not settable if there is a pyrightconfig.json

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pyright#8727]
Found another issue with the recent config changes. Python path is not settable from the settings.json. Seem obvious in hindsight, but I think this should be allowed.

**Comment by rchiodo** [comment]
I should have a fix shortly. I think this one setting should special cased? Or maybe in both places.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.376.
