### ISSUE TITLE
Member variable in assignment alias doesn't always narrow collection type

### ISSUE THREAD

**Issue by alwaysmpe** [microsoft/pyright#8735]
**Describe the bug**
When assigning an empty collection to a member variable and local variable in the same line, the type of the resulting local member variable depends on the order of assignment. Not a big problem, but it was confusing.

**Code or Screenshots**

```python
class Foo:

    str_list: list[str] | None = None

    def bar(self):
        self.str_list = str_list = []
        # Type of "append" is partially unknown
        str_list.append("bar")
        return str_list

    def baz(self):
        str_list = self.str_list = []
        # no error
        str_list.append("baz")
        return str_list
```

**VS Code extension or command-line**
pylance/pyright/playground

**Comment by erictraut** [comment]
Yes, this behavior is intended. In a chained assignment, the type of the RHS is evaluated in the context of the first assignment target. This type is then assigned to subsequent (chained) targets. The evaluation of the RHS can be influenced by bidirectional type inference depending on whether the first assignment target has a declared type. In your example, `self.str_list` has a declared type, but `str_list` does not.
