### ISSUE TITLE
Feature request: code lenses

### ISSUE THREAD

**Issue by leungbk** [microsoft/pyright#874]
**Is your feature request related to a problem? Please describe.**
[Code lenses](https://vscode.rocks/codelens/), [part of the LSP spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_codeLens), display information about surrounding source text: for example, type annotations for functions, the number of times a symbol is referenced, or clickable commands to run tests.

**Describe the solution you'd like**
With Pyright's type-inferencing system, it would be useful to have a code lens displaying a Haskell-style type annotation above a function, uninterrupted by the names of the arguments.

For example,

``` python
def fibonacci (n: int) -> int:
    ...
```

would, when code lenses are enabled, appear in the editor as

``` python
int -> int
def fibonacci (n: int) -> int:
    ...
```

**Comment by erictraut** [comment]
Thanks for the suggestion. We're unlikely to add this to Pyright, but it is a feature that we are considering for Pylance. Could you please create a new feature request in the [pylance-release](https://github.com/microsoft/pylance-release) repo? That way, others can comment on it and upvote it. Thanks!

I'm going to close the feature request here.
