### ISSUE TITLE
Possibly unbound variable bound in loop that is guaranteed to happen at least once

### ISSUE THREAD

**Issue by alwaysmpe** [microsoft/pyright#8748]
**Describe the bug**
A variable bound in a loop that is guaranteed to involve at least one iteration is raising a possible unbound error.

Possible duplicate of #8489 however I don't think so. According to that, the "unbound variable" check is based on static code flow analysis. In this case it's trivially possible to know that the value will be bound.

**Code or Screenshots**

```python
def foo():
    bound = False

    while not bound:
        var = "var"
        bound = True
    
    # "var" is possibly unbound
    print(var)
```

In my case the initialization is done in the loop because I'm iteratively trying to find a valid range, the range start/end is initialized once outside of the loop then updated within the loop. All values dependent on these  are derived in the loop.

**VS Code extension or command-line**
pylance/pyright/playground

**Comment by erictraut** [comment]
Pyright is working as designed here, so I don't consider this a bug. This has been discussed before in issues like #7822. 

The `reportPossiblyUnboundVariable` check was separated from `reportUnboundVariable` so you can disable or suppress the former if you choose to not initialize variables along all paths prior to a loop.
