### ISSUE TITLE
Implement new `reportIncompatibleVariableOverride`

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#877]
Pyright currently supports a diagnostic rule called `reportIncompatibleMethodOverride` that detects when a subclass overrides a base class method in an incompatible way.

It would be useful to have a similar rule called `reportIncompatibleVariableOverride` that detects when a subclass declares an instance variable that is of an incompatible type. Properties and class variables will need to be taken into consideration.

For more thoughts, refer to this issue: https://github.com/microsoft/pylance-release/issues/157#issuecomment-663099813

**Comment by jakebailey** [comment]
For reference, this rule would not flag the code in #157 as it would be "compatible", correct?

**Comment by erictraut** [comment]
No, it would still flag the code as in error because a property is not the same as a variable. They have different semantics. However, the user could disable this rule if they don't care about those semantic differences.

**Comment by jakebailey** [comment]
Oh, this is my mistake. I meant the other override issue we had talked about previously, which is #867.

**Comment by erictraut** [comment]
Correct. `reportIncompatibleMethodOverride` would be specific to methods, and `reportIncompatibleVariableOverride` would be specific to non-method fields including instance variables and property objects.

**Comment by erictraut** [comment]
This is addressed in Pyright version 1.1.57, which I just published. It will also be included in the next version of Pylance.
