### ISSUE TITLE
Inference on variables according to information provided by Paramspec

### ISSUE THREAD

**Issue by Xukai-Liu** [microsoft/pyright#8770]
```
from typing import TypeVar, Callable
from typing_extensions import ParamSpec
T = TypeVar('T')
P = ParamSpec('P')

def build(cls: Callable[P, T], *args: P.args, **kwargs: P.kwargs)-> T:
    return cls(*args, **kwargs)

class Poop:
    def __init__(self, amount: int, strength: float)->None:
        return

def pooper(amount: int, strength: float)->Poop:
    return Poop(amount, strength)

build(pooper, )
```

As my example provides, the type checker should have the information needed to produce the specific arguments from the Callable once it is provided. But from my experiments it doesn't seem this functionality exists. Please let me know if this could be implemented in pyright as I do not have a detail level understanding of this repository. If it is possible I'd be glad to implement it as I understand this may not be of high priority.

**Comment by erictraut** [comment]
What you're asking for here isn't a type checking feature but rather a language server feature. In particular, it would involve adding some special-case logic for completion suggestions to handle this specific case.

Pyright is focused on type checking features. It does offer some basic language server features, but we don't have plans to add new language server functionality at this time.

If you are a pylance user, you could submit a feature request in the [pylance-release project](https://github.com/microsoft/pylance-release) and see if the pylance team might consider adding this functionality. It's also possible that someone else has already requested this feature in pylance, in which case you can upvote it to increase its priority.
