### ISSUE TITLE
datetime.utcnow() is reported as deprecated for Python 3.10, with unavailable fix suggestion

### ISSUE THREAD

**Issue by gh-andre** [microsoft/pyright#8774]
**Describe the bug**

`datetime.utcnow()` is reported as a deprecated for Python 3.10 (it is deprecated in 3.12) and the error message suggests to use `datetime.now(datetime.UTC)` (`datetime.UTC` was introduced in 3.11).

**Code or Screenshots**

```python
from datetime import datetime

# Visual Studio reports this error
# Error (active)	reportDeprecated
# The method "utcnow" in class "datetime" is deprecated
# Use timezone-aware objects to represent datetimes in UTC; e.g. by calling .now(datetime.UTC)
print(datetime.utcnow())
```

**VS Code extension or command-line**

I originally encountered this error in Visual Studio, which is configure with Python 3.10 (says so in Python environments). However, I can reproduce this from command line (v1.1.376) and explicitly specified Python version, like this:

```
pyright --pythonversion 3.10 test.py
```
, which reports:

> test.py:3:16 - error: The method "utcnow" in class "datetime" is deprecated
>    Use timezone-aware objects to represent datetimes in UTC; e.g. by calling .now(datetime.UTC) (reportDeprecated)

**Comment by erictraut** [comment]
Pyright's behavior here is correct, so I don't consider this a bug.

The deprecation information comes from the [typeshed stub](https://github.com/python/typeshed/blob/f4d099dd7758771e52a416349f46636759485e9e/stdlib/datetime.pyi#L273), which unconditionally applies a `@deprecated` decorator to that method. If you think this is in error, please file a bug or a PR in the typeshed project.

**Comment by gh-andre** [comment]
Surprisingly, they don't maintain any kind of versioning for types and various deprecations for Python 3.12, which is not yet available on many stable Linux distributions, will now be splattered across a bunch of source. Ok, not much can be done there. Thanks for pointing out where the error is coming from. Good to know.

One thing you may want to consider is to use Python 3.10 friendly suggestion, which is to use `datetime.timezone.utc` instead of `datetime.UTC`.
