### ISSUE TITLE
error: No overloads for "cast" match the provided arguments (reportCallIssue)

### ISSUE THREAD

**Issue by stefanos82** [microsoft/pyright#8777]
Based on #8649 I have a related `memv = memoryview().cast()` behavior with latest version `1.1.376`; I decided to play with various examples from https://github.com/fluentpython/example-code-2e/ 

The issue I face took place with https://github.com/fluentpython/example-code-2e/blob/master/11-pythonic-obj/vector2d_v3.py

The error is this:

```
$ pyright vector2d_v3.py                                                                                                                                     
/home/stefanos/development/FluentPython2nd/vector2d/vector2d_v3.py                                                                                                                             
  /home/stefanos/development/FluentPython2nd/vector2d/vector2d_v3.py:150:16 - error: No overloads for "cast" match the provided arguments (reportCallIssue)                                    
  /home/stefanos/development/FluentPython2nd/vector2d/vector2d_v3.py:150:44 - error: Argument of type "str" cannot be assigned to parameter "format" of type "_IntegerFormats" in function "cast"                                                                                                                                                                                             
    Type "str" is incompatible with type "_IntegerFormats"                                                                                                                                     
      "str" is incompatible with type "Literal['b']"                                                                                                                                           
      "str" is incompatible with type "Literal['B']"                                                                                                                                           
      "str" is incompatible with type "Literal['@b']"                                                                                                                                          
      "str" is incompatible with type "Literal['@B']"                                                                                                                                          
      "str" is incompatible with type "Literal['h']"                                                                                                                                           
      "str" is incompatible with type "Literal['H']"                                                                                                                                           
      "str" is incompatible with type "Literal['@h']"                                                                                                                                          
    ... (reportArgumentType)                                                                                                                                                                   
2 errors, 0 warnings, 0 informations
```

For some reason, `typecode = chr(octets[0])` that contains `d` of type `string`, the cast from `memv = memoryview(octets[1:]).cast(typecode)` interprets it as plain `d`...if I replace `typecode` with `'d'`, it works as expected.

_Originally posted by @stefanos82 in https://github.com/microsoft/pyright/issues/8649#issuecomment-2294468229_

**Comment by erictraut** [comment]
Please create a minimal, self-contained code sample that demonstrates the issue you're seeing — as requested in the bug template.

**Comment by stefanos82** [comment]
Sample code:

```py
def frombytes(cls, octets):
    typecode = chr(octets[0])
    memv = memoryview(octets[1:]).cast(typecode)
    return cls(*memv)
```

`pyright` output:

```
/home/stefanos/development/FluentPython2nd/tmp.py
  /home/stefanos/development/FluentPython2nd/tmp.py:3:12 - error: No overloads for "cast" match the provided arguments (reportCallIssue)
  /home/stefanos/development/FluentPython2nd/tmp.py:3:40 - error: Argument of type "str" cannot be assigned to parameter "format" of type "_IntegerFormats" in function "cast"
    Type "str" is incompatible with type "_IntegerFormats"
      "str" is incompatible with type "Literal['b']"
      "str" is incompatible with type "Literal['B']"
      "str" is incompatible with type "Literal['@b']"
      "str" is incompatible with type "Literal['@B']"
      "str" is incompatible with type "Literal['h']"
      "str" is incompatible with type "Literal['H']"
      "str" is incompatible with type "Literal['@h']"
    ... (reportArgumentType)
2 errors, 0 warnings, 0 informations
```

**Comment by erictraut** [comment]
Thanks for the sample.

Pyright is working correctly here, so I don't consider this a bug. 

If you look at the type definition for the `memoryview.cast` method in the [typeshed stub](https://github.com/python/typeshed/blob/f4d099dd7758771e52a416349f46636759485e9e/stdlib/builtins.pyi#L863), there is no overload that accepts a (non-literal) `str` argument. If you think that `memoryview.cast` should accept a `str` argument, please consider filing a bug or a PR with the typeshed project. Pyright and all other major Python type checkers rely on typeshed stubs for type information about stdlib classes and functions.

I fixed a bug recently in pyright that would have previously masked the error in `memoryview.cast`. That would explain why you didn't see the error in older versions of pyright. Now that this bug is fixed, pyright correctly reports a type error in this situation.

**Comment by stefanos82** [comment]
Excuse my ignorance, but why `memv = memoryview(octets[1:]).cast('d')` works as expected which is accepting an `str` and `memv = memoryview(octets[1:]).cast(typecode)` does not?

**Comment by erictraut** [comment]
The type of expression `'d'` is `Literal['d']`. This is a subtype of `str`. 

The type definition for the method `cast` indicates that it accepts an argument of type `Literal['d']` but not `str`.

If you want to make your code type safe, you could add an assertion to document your assumptions. The type of `typecode` will then be narrowed if the assert succeeds.

```python
def frombytes(cls, octets):
    typecode = chr(octets[0])
    assert typecode in ("c", "f", "d")
    memv = memoryview(octets[1:]).cast(typecode)
    return cls(*memv)
```

**Comment by stefanos82** [comment]
> If you want to make your code type safe, you could add an assertion to document your assumptions. The type of `typecode` will then be narrowed if the assert succeeds.
> 

Today I learned!

Thank you for teaching me something I honestly didn't know until now @erictraut 

Cheers :+1:
