### ISSUE TITLE
Missing default values in synthesized `__init__` signature of dataclasses

### ISSUE THREAD

**Issue by Viicos** [microsoft/pyright#8781]
Since pyright `1.1.372`, the default values of dataclasses is lost in the generated `__init__` signature:

Code sample in [pyright playground](https://pyright-play.net/?pyrightVersion=1.1.372&strict=true&code=GYJw9gtgBAJghgFzgYwDZwM4YKYagSwgAcwQFZEV0sAaKYfbVGAKBYAF4k1MMWesUAIIAuFlChwRBAHbkAvFABM4qACNp%2BOVEUMmMABQxswOAFdUCeUoCUbFkIM2gA)

```python
from dataclasses import dataclass, field

@dataclass
class A:
  a: int = 2
  b: int = field(default=2)


A()
```

![image](https://github.com/user-attachments/assets/bce5e36a-1874-458e-b221-a188358c7857)

In pyright `1.1.371`:

![image](https://github.com/user-attachments/assets/ccc1b607-12c3-4b67-8376-0fa66e1ab0de)

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.377.
