### ISSUE TITLE
Add output option for --createstub

### ISSUE THREAD

**Issue by LordAro** [microsoft/pyright#8782]
`--createstub` is an excellent replacement for mypy stubgen that, notably, doesn't have crashing issues with numpy 2.0.

However, it has no method of controlling the output other than `stubPath` in a config file.

For us, a workaround has been:
```
echo '{"stubPath": "./scripts"}' > pyrightconfig.json
PYTHONPATH=$PWD/src/script_common/scripts python -m pyright --createstub relative.path.to.my.module
rm pyrightconfig.json
```

which is horrible (especially as it's within a wildcard makefile rule so I've had to add `.NOTPARALLEL` so that it doesn't overwrite things).

It's able to work for us as our existing `pyproject.toml` config is simple enough that it doesn't matter that the settings disappear for the `--createstub` call, but others may not have that option. We can't put `stubPath` in the global `pyproject.toml` (which is at the top level of a monorepo with many different python projects contained in it) as the relative path is per project (and we can't have an absolute path for obvious reasons)

**Describe the solution you’d like**

A method of overriding stubPath on the commandline, or even an individual flag for the file. e.g.

```
pyright --createstub my.module --stub-output build/folder/here/
```

(a separate feature request is the ability to pass in a file instead of an import path, but I'll save that for another time)

**Comment by erictraut** [comment]
Thanks for the feature request. As far as I can remember, this is the first time someone has requested such a feature, so the need is probably not very prevalent. Most users want their generated stubs to be part of their project, and generating them in the stubPath directory works well in that case.

I'm going to reject the enhancement request for now, but I will reconsider the decision in the future if there is sufficient signal from other pyright users (in the form of upvotes or comments) that they also want such a feature. If this is a feature you'd like to see, please add a thumbs-up reaction.

In the meantime, it looks like you've identified a workaround that works reasonable well.
