### ISSUE TITLE
PEP 612 and 614 are not in Python 3.9

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#879]
Pyright's current implementation assumes that PEP 612 and 614 were going to make it into the Python 3.9 release, but it now looks like they'll slip out to Python 3.10. The functionality should therefore be conditionalized on 3.10.

**Comment by layday** [comment]
PEPs [612](https://mail.python.org/archives/list/typing-sig@python.org/message/LQGFOTCNJN7PGU5ZQ3ECGZ57LNIJWRFO/) and [604](https://mail.python.org/archives/list/typing-sig@python.org/message/ZYACLSHHSOEXGHMD4Q5RGSCBZCSPUWSK/) (which I think is the one you meant) have now been accepted for inclusion in 3.10.  I assume a backport of 612 will also make it into typing-extensions at some point.
