### ISSUE TITLE
"Cannot access member" Error for Union typed param even after checking isinstance with `PIL.Image.Image`

### ISSUE THREAD

**Issue by TotallyNotChase** [microsoft/pyright#884]
**Describe the bug**
I have a parameter in a function, declared like `bar: Union[str, Image.Image]` (`Image.Image` is from `PIL`). I want to perform different operations on this parameter depending on the type (and also some more conditionals). So what I do is check `isinstance` first and then perform the methods specific to that instance.

Basically I want to use `.replace` *if the param is an `str`* **and** if it meets another certain condition. And I want to use `.convert` *if the param is a `PIL.Image.Image`* **and** if it meets a certain condition.

But whenever I have multiple conditions on the first `if` check (which checks if the variable is an `str`), pyright errors out on the second `elif` block (which checks if the variable is an `Image.Image`) saying-

> error: Cannot access member "convert" for type "str"

Interestingly, if I don't have any other conditional other than `isinstance(bar, str)` on the `if` - it no longer errors out on the `elif`.

Even more interestingly, if I move the `isinstance(bar, Image.Image)` to the `if` and put `isinstance(bar, str)` on the `elif` - **even without any other conditionals**, it still errors out saying (this time on the `if` block of course)

> error: Cannot access member "convert" for type "str"

**To Reproduce**
OS: Windows 10 [Version 10.0.19041.388]
Python Version: 3.7.4 32 bit

* Use the code samples provided
* Do `pyright /path/to/script.py` in the command line
* Check for errors

**Expected behavior**
All code samples provided should pass perfectly fine and pyright should not raise any errors.

**Screenshots or Code**
* `str` check first + extra conditional on both - pyright throws error
  ```py
  from typing import Union
  
  from PIL import Image
  
  def foo(bar_img: Union[str, Image.Image], baz: bool):
      if isinstance(bar_img, str) and baz:
          bar_img = bar_img.replace(' ', ', ')
      elif isinstance(bar_img, Image.Image) and baz:
          bar_img = bar_img.convert('RGBA')
  ```
* `str` check first + extra conditional on `if` - pyright throws error
  ```py
  from typing import Union
  
  from PIL import Image

  def foo(bar_img: Union[str, Image.Image], baz: bool):
      if isinstance(bar_img, str) and baz:
          bar_img = bar_img.replace(' ', ', ')
      elif isinstance(bar_img, Image.Image):
          bar_img = bar_img.convert('RGBA')
  ```
* `str` check first + extra conditional on `elif` - pyright passes perfectly
  ```py
  from typing import Union
  
  from PIL import Image
  
  def foo(bar_img: Union[str, Image.Image], baz: bool):
      if isinstance(bar_img, str):
          bar_img = bar_img.replace(' ', ', ')
      elif isinstance(bar_img, Image.Image) and baz:
          bar_img = bar_img.convert('RGBA')
  ```
* `str` check first + no extra conditionals - pyright passes perfectly
  ```py
  from typing import Union
  
  from PIL import Image
  
  def foo(bar_img: Union[str, Image.Image], baz: bool):
      if isinstance(bar_img, str):
          bar_img = bar_img.replace(' ', ', ')
      elif isinstance(bar_img, Image.Image):
          bar_img = bar_img.convert('RGBA')
  ```

* Image check first + extra conditional on both - pyright throws error
  ```py
  from typing import Union
  
  from PIL import Image
  
  def foo(bar_img: Union[str, Image.Image], baz: bool):
      if isinstance(bar_img, Image.Image) and baz:
          bar_img = bar_img.convert('RGBA')
      elif isinstance(bar_img, str) and baz:
          bar_img = bar_img.replace(' ', ', ')
  ```
* Image check first + extra conditional on `if` - pyright throws error
  ```py
  from typing import Union
  
  from PIL import Image
  
  def foo(bar_img: Union[str, Image.Image], baz: bool):
      if isinstance(bar_img, Image.Image) and baz:
          bar_img = bar_img.convert('RGBA')
      elif isinstance(bar_img, str):
          bar_img = bar_img.replace(' ', ', ')
  ```
* Image check first + extra conditional on `elif` - pyright throws error
  ```py
  from typing import Union
  
  from PIL import Image
  
  def foo(bar_img: Union[str, Image.Image], baz: bool):
      if isinstance(bar_img, Image.Image):
          bar_img = bar_img.convert('RGBA')
      elif isinstance(bar_img, str) and baz:
          bar_img = bar_img.replace(' ', ', ')
  ```
* Image check first + no extra conditionals - pyright throws error
  ```py
  from typing import Union
  
  from PIL import Image
  
  def foo(bar_img: Union[str, Image.Image], baz: bool):
      if isinstance(bar_img, Image.Image):
          bar_img = bar_img.convert('RGBA')
      elif isinstance(bar_img, str):
          bar_img = bar_img.replace(' ', ', ')
  ```

**VS Code extension or command-line**
Pyright version: 1.1.55. Running from the commandline

**Additional context**

**Note**: I also should say that I've tested this with built in types like `List` and this problem is not reproducible with that. The errors seem very weird so I can't quite tell if this is more suited as a `typeshed` issue either. Like, why does it work when I do not use `and some_conditional`? Why does the conditional on the `if` statement seem to matter more in this case than the `elif` statement (when using `isinstance(bar, str)` in the `if`)?

**Comment by erictraut** [comment]
Your examples are working for me. I suspect the difference is that I'm using type stubs for PIL. If Pyright cannot find a type stub, it will by default assume that any import is an "unknown" type, so it cannot reason about it. It has to assume that it might be an instance of `str`, for example. 

I recommend uninstalling Pyright and installing Pylance in its place. The latter includes all the functionality of Pyright but also includes some additional bundled type stubs such as those for PIL.

If for some reason you really don't want to use Pylance, you can either find stubs for PIL or enable the `useLibraryCodeForTypes` setting which tells Pyright to attempt to extract type information directly from the library code rather than relying on stub files.

**Comment by TotallyNotChase** [comment]
@erictraut I do already use pylance as my vscode extension. But I'd like to have a way to type check my code through the commandline (even when I don't have vscode installed). I suppose I'll have to find the type stub for that option?

**Comment by erictraut** [comment]
We're working on making the bundled stubs the same between Pyright and Pylance (see https://github.com/microsoft/pyright/issues/861). There are a few technical issues we need to work through still. In the meantime, you could manually pull the stubs out of Pylance and use them with the CLI version of Pyright.
