### ISSUE TITLE
multiple venvs in "root" paths of project

### ISSUE THREAD

**Issue by hanamuura** [microsoft/pyright#8858]
in my project i store venv in multiple paths. for project structure of:
```
root/
   lib1/
      venv/
   lib2/
      venv/
```
my pyright config say me that import is not resolved. 
![изображение](https://github.com/user-attachments/assets/fcbae7e7-6323-473f-9180-ecf68f2f38fb)
my pyright config is 
```
{
    "include": ["lib1", "lib2"],
    "reportMissingImports": true,
    "venvPath": ".",
    "executionEnvironments": [
        {
            "root": "./lib1",
            "venv": "./lib1/venv"
        },
        {
            "root": "./lib2",
            "venv": "./lib2/venv"
        }
    ]
}

```
i dont know bug this or i wrong somewhere but i cant find any solves of problem. i see issue that looks like my problem but it didnt help me. pls help   :__

**Comment by erictraut** [comment]
Your configuration is incorrect here. The "executionEnvironments" feature in pyright does not support different python environments. Even if it did, the configuration mechanism involving `venvPath` and `venv` assumes that all of your venvs are in the same shared directory (pointed to by `venvPath`).

Your options are:
1. Treat each of your libraries as completely separate projects. Create a separate pyright config for each of them, within `lib1` and `lib2` respectively. If you're using the CLI version of pyright, run it twice — once for each project. If you're using pyright as a language server, establish separate workspaces within your client — one for each project.
2. Use a single venv for both projects and install all of the libraries that both of them require.

**Comment by hanamuura** [comment]
thank you for ur support. very sad about this because im really love pyright. sorry for wasting ur time.

**Comment by Eslsamu** [comment]
@erictraut 

It's fair to say that this is by design, but I think it would be super useful for monorepos to automate the switch between virtual environments within a single pyright run. Also it would be one of the most useful feature I can think of for VSCode/Pylance. (Specifying multiple environments belonging to different locations of the source.)
