### ISSUE TITLE
Tool that helps validate type stubs

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#887]
It would be useful to have a tool that compares a collection of type stubs against the corresponding library implementation. It should check for the following:
1. Are stub files missing?
2. Do stubs contain any syntax or semantic errors? Type consistency errors?
3. Are exported symbols present in the implementation that are missing from stubs or vice versa?
4. Do type annotations present in the implementation match those provided in the stub?
5. Do function and method signatures match?
6. Are all types provided in the stub complete (e.g. missing return types)?
7. (Possibly) Do types inferred from unannotated implementation code match the types in the stubs?
8. (Possibly) If docstrings are present in the type stub and the implementation, report any differences between the two?
9. (Possibly) If function docstrings are present and contain parameter names and types, report any differences between the type signature in the stub and the docstring description?

This would presumably be implemented as a new mode in the CLI version of Pyright.

This mode could be used as part of a CI toolchain for library authors. It could also be used for people who were developing hand-written type stubs to ensure that they were complete and high-quality.

**Comment by hauntsaninja** [comment]
In case it's useful to you, mypy's [stubtest](https://github.com/python/mypy/blob/master/mypy/stubtest.py) is capable of checking these things; it's what typeshed uses in its CI. It's capable of checking 1-5 in your list, and additional mypy flags can be used to check 6.

**Comment by erictraut** [comment]
@hauntsaninja, thanks for the suggestion. I agree that mypy's `stubtest` is a good starting point. 

I think pyright could add significant value beyond what stubtest provides. First, pyright tends to be more strict than mypy, so I think it will find problems that mypy misses. For type stubs, it's really important that they're complete and accurate, so strictness is valuable. Second, because pyright is also a language server, it would allow for edit-time diagnostic feedback, making it much easier to diagnose and fix any problems.

**Comment by erictraut** [comment]
I've now added some of the features listed above. The other features are either already better covered by a command-line or turned out to be too noisy (too many false positives) to implement.
