### ISSUE TITLE
Inference of Typevar inside `print` call is broken

### ISSUE THREAD

**Issue by kc0506** [microsoft/pyright#8878]
<h3> Environment data </h3>

-   Language Server version: 2024.7.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python

class A:
    a = 1

y = [A()]
list(sorted(y, key=lambda x: x.a))
print(list(sorted(y, key=lambda x: x.a)))

```

<h3> Expected behavior </h3>

The `x` should be inferred as `A` in both `sorted` calls.

<h3> Actual behavior </h3>

* The first `sorted` is working as expected
![image](https://github.com/user-attachments/assets/edbbe4a2-8910-4724-8a23-582e828546a3)

* In the second `sorted`, `x` is inferred as `Any`. The color of `.a` attribute is different, and autocomplete does not work. 
![image](https://github.com/user-attachments/assets/fd242c9e-bd9d-4e45-ba48-f387f1dfbb21)

**Comment by debonte** [comment]
I'm not able to repro this, even on 2024.7.1.

@kc0506, for what it's worth that version is almost 2 months old. We'll be releasing 2024.9.1 soon.

**Comment by kc0506** [comment]
I realized that I had overlooked a line `from rich import print` in the file. So the reason why it can't be reproduced is because the difference of signature:
```
builtins.print: (*values: object, ...) -> None
rich.print: (*values: Any, ...) -> None
```

However, after updating Pylance to the latest version, the problem no longer exists. I believe this resolves the issue, so I'll be closing it now. Thanks for your attention.
