### ISSUE TITLE
The `createstub` fails to create a `stub` correctly for `sqlalchemy`.

### ISSUE THREAD

**Issue by phi-friday** [microsoft/pyright#8922]
**Describe the bug**
It doesn't seem to recognize scripts written for the namespace.

**Code or Screenshots**
script:
```bash
❯ uvx --from=pyright --with=sqlalchemy pyright --createstub sqlalchemy.sql.expression
Installed 4 packages in 11ms
Type stub was created for 'sqlalchemy.sql.expression'
```
output:
```python
"""
This type stub file was generated by pyright.
"""

"""Defines the public namespace for SQL expression constructs.


"""
nullsfirst = ...
nullslast = ...

```
screenshots
![스크린샷 2024-09-07 오후 6 52 09](https://github.com/user-attachments/assets/445305ea-7d73-4bcd-a4fb-ece63cee82c6)
![스크린샷 2024-09-07 오후 6 52 16](https://github.com/user-attachments/assets/74324a7d-c0e5-47a4-bb5e-e0dd6a7f83c6)

It appears that this module creates one for each module it imports, and then doesn't use it.
![스크린샷 2024-09-07 오후 7 02 43](https://github.com/user-attachments/assets/3775eea6-bb00-4dc4-9f95-f402e5dba5c0)

**Comment by erictraut** [comment]
I'm not sure what problem you're reporting here. From your screen shots, it looks like the `createstub` feature is creating ".pyi" modules (stub files) for the corresponding ".py" files in this case.

Is your point that the `import` statements are not included in the corresponding stub?

The `createstub` feature is designed to help you create a "first draft" of type stubs. You will inevitably need to go back and clean up the resulting stubs before they are usable. 

Also, I'll note that sqlalchemy 2.0 includes inline type information, so creating stubs for this library shouldn't be needed unless you're using a really old version of the library.

**Comment by phi-friday** [comment]
I'm in an environment where I can't install `sqlalchemy` (due to dependency conflicts) and just want to use stubfiles. 
I knew that it creates them in draft level, but I asked because I didn't have any objects already imported (mypy stubgen worked).

This is an exceptional case.
I'll close the issue, as this seems to be what was intended.
Have a nice day.
