### ISSUE TITLE
The "organize imports" code action appears on every line.

### ISSUE THREAD

**Issue by rwols** [microsoft/pyright#893]
**Describe the bug**
The "organize imports" code action appears on every line.

**To Reproduce**
1. Use any editor that requests code actions for every selection change.
2. See a code action suggestion appear:
![Screenshot from 2020-07-30 20-52-40](https://user-images.githubusercontent.com/2431823/88962364-a140bd00-d2a6-11ea-8761-98f0e4bb9362.png)

**Expected behavior**
This server should ideally only suggest an organize imports code action when the user's selection is at an `import` line at the top of the file. And the server should also ideally check whether the imports are already organized before suggesting the action.

**VS Code extension or command-line**
N/A

**Additional context**
I'm working on an experimental Sublime Text client. This is a general-purpose client. It requests code actions for every selection change. This is e.g. how the eslint language server expects the client to behave, as well as the rust-analyzer language server.

The code that causes this behavior seems to be [here](https://github.com/microsoft/pyright/blob/e5733255544f1995ccef3b6fe82af01a2760ec9e/server/src/languageService/codeActionProvider.ts#L35-L37).

I'm not sure how open you are to changes in this area. I'm guessing the VSCode client code is doing something in such a way that it prevents this behavior?

**Comment by erictraut** [comment]
I agree this code action shouldn't be provided for every position. I don't think it should be returned conditionally within an import statement though. It makes more sense as a command, not a code action. I've removed the code action entirely.

**Comment by jakebailey** [comment]
Yes, I believe it should be the typical LSP organizeImports command.

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.59, which I just published.
