### ISSUE TITLE
Possible Overloads Regression in 1.1.378

### ISSUE THREAD

**Issue by max-muoto** [microsoft/pyright#8930]
The following code passed under Pyright 1.1.377:

```python
from typing import overload, Literal, Any
from collections.abc import Callable


class Page[T]:
    ...

class Container[T: Callable[..., Any]]:
    @overload
    def foo(
        self,
        path: str,
        klass: type[Any]| None = ...,
        manual: Literal[False] = False,
    ) -> Callable[[T], Page[Any]]: ...

    @overload
    def foo(
        self,
        path: str,
        klass: type[Any]
        | None = ...,
        manual: Literal[True] = ...,
    ) -> Callable[[T], T]: ...

    def foo(
        self,
        path: str,
        klass: type[Any]| None = None,
        manual: bool = False,
    ) -> Callable[[T], T | Page[Any]]: ...
```

However, with Pyright 1.1.378+, I get a warning that there's an overlapping overload - [Pyright Playground](https://pyright-play.net/?pyrightVersion=1.1.378&pythonVersion=3.14&strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMpgBuApiADZgCGAJgDRQAySMplZ9AginAFCiRQAxmDJligmEjAoAzgDpKAI0GZsufAGE2ZJWJ77BOmTKgAFSmmIBtACoBdAFw8oLqHPcGjJjdJiVUpLYOUFqiutbucpzcdo7OrgACRKQUNPEu1MTAUMBgYAAU6a4uMsRkwLRFxQiUMAAWwTIwIJXFxQDWXsHwCNZccHYAPlAActLEUAC8bu6tbS4QlCgArmzBTCwgbFYAYmyldlNQe2Slcy4AlFAAtAB8IdrhVrZ29OaWVv2xwZH6xUkkchUahFTLZXIFKquUrlc5tGr1RrNOEdLqwRB9GJQlzDMYoCbTSIo1yLFZrRjMVhkWwgZbEQ6E2ZFK53B5hRRiZ72ej2H4eUFZHJ5QrzEplCrYqAIhpQJotSWdSjGboYz4xXHjI544jEhZLVZkYKKPJkI4nM7Mm73UI6DnWF48qDDd6YgaOGZyIA). 

It seems clear to me that there's not an overlap here, with the overloads being distinct through `manual`.

**Comment by erictraut** [comment]
Pyright's new behavior here is correct. This was previously a bug. The problem is that the `manual` parameter has a default argument for both overloads. That means both of them would match if there were no `manual` keyword argument specified. You can fix this by removing the `= ...` in the second overload.

**Comment by max-muoto** [comment]
> Pyright's new behavior here is correct. This was previously a bug. The problem is that the `manual` parameter has a default argument for both overloads. That means both of them would match if there were no `manual` keyword argument specified. You can fix this by removing the `= ...` in the second overload.

Thanks for the clarification!
