### ISSUE TITLE
Type arguments are not allowed in TypedDict using functional syntax 

### ISSUE THREAD

**Issue by MtkN1** [microsoft/pyright#8942]
In TypedDict, type arguments are allowed in class-based syntax but not in functional syntax.

Below is the reproduced code:

Code sample in [pyright playground](https://pyright-play.net/?pythonVersion=3.12&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDiApikSEgMYA0UAKokQCYAilMN9CRAagIYg1eAZyFkYAfXhcAUNNpQAvHQZ8QACgBEtDQEpZ0igBthQqAFkwANyRE1nJqwowdALmlQPUFLwhEXUIRgQd084In5-VBh9IxMoACUiIRwUUQAhOABhYxE04SY7BhY2GmJScgoAbVoAXVcQj0DeGABXIUiUaM8oRmbef1p9ROSwVKIMgDEWlCckUd5DRWUuYqc1BqgNYZT0uCmZmDnvQw0qDYBvDe6NJtahDQ72K88NXpheB7oz7oBfM71ZIwiMBYEkJCAkjsiOIAEZwcSxESw-KMNQ6KAAWgAfFAAHKjPwbCEjMb%2BbajXbZEx5USMSoWaxEGpLc4eADEUAA8gBpZ4eG7vO6fABMAAZRd9ui83h9-OcNN5fJ8NGljECEtNyqdNmF%2BJ8AIwATgAHMK-hsfhsZUtiVDKq8%2BhoahsTGJJAw1DKaAybADpECQTAweJbRToXDxMBprN5oY0ZicfjSG5uqHSQlIWHJtHDrH6VYbMylKyoByAKLxeKc%2BJ8za3Noi8WSqWbGWfeWKojK1W8dXxTVkbUaXUgA0ms3NqCW7rWpRp0T2tvO7quvDurievregtEdGlqBEAAeXCcTH8PqINDQYBgA2kQA)

```python
from typing import Generic, TypedDict, TypeVar, assert_type

T = TypeVar("T")


class Movie(TypedDict):
    name: str
    year: int


class ResponseByClassBased(TypedDict, Generic[T]):
    status: int
    data: T


ResponseByFunctional = TypedDict(
    "ResponseByFunctional",
    {
        "status": int,
        "data": T,
    },
)


def test_response_by_class_based() -> None:
    response: ResponseByClassBased[Movie] = {  # OK
        "status": 200,
        "data": {"name": "Blade Runner", "year": 1982},
    }
    data = response["data"]
    assert_type(data, Movie)


def test_response_by_functional() -> None:
    response: ResponseByFunctional[Movie] = {  # ERROR
        "status": 200,
        "data": {"name": "Blade Runner", "year": 1982},
    }
    data = response["data"]
    assert_type(data, Movie)  # expected: Movie, got: T

```

```console
$ pyright tests/test_typeddict.py
tests/test_typeddict.py
  tests/test_typeddict.py:35:36 - error: Expected no type arguments for class "ResponseByFunctional" (reportInvalidTypeArguments)
  tests/test_typeddict.py:40:17 - error: "assert_type" mismatch: expected "Movie" but received "T@ResponseByFunctional" (reportAssertTypeFailure)
2 errors, 0 warnings, 0 informations 
```

> [!NOTE]
> Generics in TypedDict are allowed in python/cpython#89026.

The reproduced code passes in mypy. Could this be a bug in pyright?

```console
$ pyright --version
pyright 1.1.379
```

**Comment by erictraut** [comment]
Pyright is working in accordance with the Python typing spec, so I don't consider this a bug. TypeVars need to be scoped to a `class` statement, a `def` statement, or a type alias definition. In this case, there's no `class` statement to scope the TypeVar to.

If you want to define a generic TypedDict, you need to use the class syntax, not the functional syntax. 

I'll also note that you're using the legacy (pre-Python 3.12) mechanism for allocating TypeVars. Here's the modern (Python 3.12 and newer) way to define a generic class:

```python
class ResponseByClassBased[T](TypedDict):
    status: int
    data: T
```

**Comment by MtkN1** [comment]
@erictraut Thanks for the quick reply!

Got it. It seems each type checker implements this feature differently, so it's not a bug.

Alternatively, would it be feasible to consider supporting this as a feature enhancement? I noticed [a related comment](https://github.com/python/mypy/pull/13389#issuecomment-1214133700) in mypy.

**Comment by erictraut** [comment]
> would it be feasible to consider supporting this as a feature enhancement

Pyright is a standards-based type checker, and it [conforms](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html) to the [Python typing spec](https://typing.readthedocs.io/en/latest/spec/index.html). The spec doesn't allow for TypeVars to be scoped in this manner. I think it's unlikely that there would be interest in extending the spec to accommodate this because it goes against the direction of the new TypeVar syntax introduced in Python 3.12.

I recommend sticking with the class syntax when defining TypedDicts. There are rare circumstances where the functional form is needed (namely, when your key names are invalid identifiers), but in all other cases, the class syntax is preferable.

**Comment by MtkN1** [comment]
I didn't express it in the initial reproduction code, but my use case was for a rare scenario. I simply wanted to efficiently type annotate third-party JSON, which might contain invalid identifiers, using TypedDict and TypeVar.

```python
class Response[T](TypedDict):
    from: T  # invalid
```

Therefore, I preferred functional syntax, but it seems that using TypeVar is not a standard practice. Your explanation makes sense. I will consider avoiding the use of TypeVar!

```python
ResponseInt = TypedDict("ResponseInt", {"from": int})
ResponseStr = TypedDict("ResponseInt", {"from": str})
```

Thank you for your detailed explanation!
