### ISSUE TITLE
It's a bit unexpected that textDocument/documentHighlight highlights docstrings that are the same

### ISSUE THREAD

**Issue by rwols** [microsoft/pyright#896]
**Is your feature request related to a problem? Please describe.**

Given the following file
```python
def foo() -> None:
    """hello world"""
    pass


def bar() -> None:
    """hello world"""
```
and given that I put my caret on one of the two docstrings, the pyright server will return 2 ranges each of which spans one of the docstrings.

![Peek 2020-07-30 22-17](https://user-images.githubusercontent.com/2431823/88970289-70668500-d2b2-11ea-8960-d61e4741acda.gif)

**Describe the solution you'd like**
Respond to textDocument/documentHighlight with no ranges when the client's caret is on a docstring.

**Comment by jakebailey** [comment]
See also: microsoft/pylance-release#172

The crux is that "literals" are proper types in Python typing.

**Comment by erictraut** [comment]
Thanks for the report. As Jake mentioned, we're already tracking this issue in the pylance-release repo. We'll use the other issue to discuss the pros/cons of changing the current behavior. I'm going to close this one as a duplicate.
