### ISSUE TITLE
`TypeIs` doesn't narrow on union of generics

### ISSUE THREAD

**Issue by light-scattering-io** [microsoft/pyright#8966]
**Describe the bug**

When using `TypeIs` to narrow a variable annotated as an union of two generics with different types, the type is not narrowed in the successful branch.

**Code or Screenshots**
In the following example, the type revealed in the if branch is `Sequence[int] | Sequence[str]` (version 1.1.380 in pyright playground).

Instead, I would have expected `Sequence[int]`. 
And when I go back to version 1.1.373, this is indeed the correct `Sequence[int]` that is shown.

```python
from collections.abc import Sequence
from typing import TypeIs, reveal_type

def is_sequence_of_int(sequence: Sequence) -> TypeIs[Sequence[int]]:
    return all(isinstance(x , int) for x in sequence)

def foo(sequence: Sequence[int] | Sequence[str]):
    if is_sequence_of_int(sequence):
        reveal_type(sequence)
    else:
        reveal_type(sequence)
```

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.381.
