### ISSUE TITLE
createstub is generating a stub that is missing all of the code

### ISSUE THREAD

**Issue by daltairwalter** [microsoft/pyright#898]
I am using pyright 1.1.55 and trying to create a stub for a pyd file with:
pyright --createstub alt.hst.core.hstfitext

The messages seem to indicate that this was successful, but the type stub is basically empty.  It only contains:
"""
This type stub file was generated by pyright.
"""

Below is the output from running pyright:
Loading configuration file at C:\Altair\dwalter\HstFbCurie-02_tr-lap1038_dw\pyrightconfig.json
Assuming Python version 3.7
Assuming Python platform Windows
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding .git
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
Type stub was created for 'alt.hst.core.hstfitext'

**Comment by erictraut** [comment]
Pyright generates stub files based on Python source code. Pyd files are binary files, so there is no Python code present. So it's working as intended in this case.

**Comment by daltairwalter** [comment]
I am a bit confused and I am hoping you can help clarify.
1. What is the purpose of creating a stub for anything other than a pyd file?  From my perhaps simpleton perspective, the source already exists so why is a stub helpful in these cases.  Is this for protecting Intellectual Property or performance?
2. What is the difficulty in generating a stub from a pyd?  The pyd has a normal __dict__ that shows all of the classes and methods that should be stubbed.

**Comment by erictraut** [comment]
[This documentation](https://github.com/microsoft/pyright/blob/master/docs/type-stubs.md) might help clarify.

There is no type information within a pyd file other than symbol names.

**Comment by erictraut** [comment]
I guess it would be a good idea to emit an error if no type information can be found (i.e. only a pyd file).

**Comment by daltairwalter** [comment]
When you say that there is no type information within a pyd, I am a bit confused.  When I do a print(module. _ _ dict _ _ ) I see lots of additional information like what is a class is marked with <class>.  Similarly if I do print(module._ _dict_ _['myClass']._ _ dict _ _), I see all of the functions annotated with <instancemethod>.

**Comment by erictraut** [comment]
You are correct in that some type information is available in a pyd. It doesn't include parameter types, return types, instance variable types, etc.

In any case, Pyright does not extract any type information from binaries, and we currently have no plans to add this. There are other tools available that can generate initial type stubs based on the limited type information in a pyd, but you would need to do additional work to manually add the missing type information.
