### ISSUE TITLE
`[object Object]` in reportDeprecated error message

### ISSUE THREAD

**Issue by sunfkny** [microsoft/pyright#8995]
**Describe the bug**
The error message incorrectly displays `[object Object]` instead of the Python version.
```
This type is deprecated as of Python [object Object]; use "list" instead (reportDeprecated)
```

**Code or Screenshots**
https://pyright-play.net/?pyrightVersion=1.1.380&strict=true&locale=en&deprecateTypingAliases=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAySAzjEA

**VS Code extension or command-line**
Pyright command-line 1.1.380
Pylance VS Code extension v2024.9.100 (pre-release)

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.381.
