### ISSUE TITLE
'venvPath' and 'venv' not working on VS Code extension of version 1.1.376 and newer

### ISSUE THREAD

**Issue by FairySunny** [microsoft/pyright#9001]
**Describe the bug**
I have a micromamba environment named 'test' in `~/micromamba/envs/test`. On VS Code extension (VS Code OSS on Linux) of version 1.1.375, I set `python.venvPath` to `~/micromamba/envs` in configuration file `settings.json` and set `venv` to `test` in `pyrightconfig.json`, the extension correctly recognizes the packages (e.g. numpy) installed in the environment 'test'. However, on version 1.1.376 and newer, the extension says that the import cannot be resolved. I do not have pylance installed.

**VS Code extension or command-line**
VS Code extension (VS Code OSS on Linux) of version 1.1.376 and newer (I tried 1.1.376, 1.1.377 and 1.1.380).

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.381.
