### ISSUE TITLE
Potential bug with cancellation token handling

### ISSUE THREAD

**Issue by ethereon** [microsoft/pyright#9015]
This is an issue I'm encountering with `main` but not with the most recent release `1.1.380`. It manifests as the `vscode-pyright` language server abruptly ceasing all diagnostics.

## Possible Cause

I believe I've tracked it down to the following change: https://github.com/microsoft/pyright/pull/8969/files#diff-ac3a7b49798141e77c54e96bca892a082469cc83bb335322b35c01e020b060c8R481-R495

In particular, the issue seems to be that the cancellation source is now cached whereas it used to be recreated each time before (https://github.com/microsoft/pyright/pull/8969/files#diff-ac3a7b49798141e77c54e96bca892a082469cc83bb335322b35c01e020b060c8L1866-L1870).

From here on out, it seems like it can fail in two separate paths:

1. If background analysis is used, the token above is passed to `this._backgroundAnalysisProgram.startAnalysis`, which disposes it off here: https://github.com/microsoft/pyright/blob/e94fa867c53b4776324b3580a33975bfbe957538/packages/pyright-internal/src/backgroundAnalysisBase.ts#L295

2. Otherwise, it gets canceled during `_scheduleReanalysis`: https://github.com/microsoft/pyright/blob/e94fa867c53b4776324b3580a33975bfbe957538/packages/pyright-internal/src/analyzer/service.ts#L1864

## Reproducing

I encountered this issue in my own custom code. I've also managed to recreate it in vscode. However, it is a bit tricky since there are a few other interactions that can mask the issue. In particular:

- Debug mode needs to be disabled.
   The reason for this is that `throwIfCancellationRequested` is a no-op in debug mode :https://github.com/microsoft/pyright/blob/e94fa867c53b4776324b3580a33975bfbe957538/packages/pyright-internal/src/analyzer/analysis.ts#L55 and the cancelled/disposed token doesn't affect things here

- File based cancellation tokens mask the issue.
   This appears to be an interaction with path 1 above: the token gets disposed before cancelation and subsequent `cancel` calls have no effect: https://github.com/microsoft/pyright/blob/e94fa867c53b4776324b3580a33975bfbe957538/packages/pyright-internal/src/common/fileBasedCancellationUtils.ts#L50

With those two aside, observe that diagnostics no longer appear for newly created Python files.

**Comment by erictraut** [comment]
@rchiodo, @debonte, @heejaechang, it looks like this is related to a change that came in through pylance in the past week. Could someone take a look?

**Comment by rchiodo** [comment]
Thanks for the detailed description @ethereon, I would hazard a guess we need to recreate the token every time runAnalysis is called. That should maintain the old behavior.

**Comment by erictraut** [comment]
Thanks @ethereon for the bug report, and thanks @rchiodo for jumping on the issue quickly and getting a fix in place before this week's release of pyright.

**Comment by ethereon** [comment]
Thanks for the quick responses! I've verified that the latest `main` with #9016 resolves the issue for me.
