### ISSUE TITLE
type inference for objects of type list[Module] may not work

### ISSUE THREAD

**Issue by declaresub** [microsoft/pyright#9036]
Consider the following bit of code.

```python
import random, re
L1 = [random]
L2 = [random, re]
```

pyright 1.1.378 (running in VSCode) infers the type of L1 to be list[Module("random")], but reports that the type of L2 is list[Unknown].  

While this is easily resolved by annotating L2 to be types.ModuleType, I did not know whether this is a symptom of an issue in pyright, or is a consequence of some internal python trickery.

**Comment by erictraut** [comment]
Yeah, I agree these should be inferred as `list[ModuleType]`.

This will be addressed in the next release of pyright.

**Comment by Abderrahma77524** [comment]
You didn't add the name muddle (random.random()or random.randint()) to what
I think.
Because it is necessary to enter with the key and the name of the door

في الخميس، 19 شتنبر، 2024 17:38 Eric Traut ***@***.***> كتب:

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.382.
