### ISSUE TITLE
In stub files, mark imported but not re-exported values as unused

### ISSUE THREAD

**Issue by jakebailey** [microsoft/pyright#904]
If I'm in a stub file which contains just a line like:

```
from collections import namedtuple
```

The rules of how stub imports work (versus regular files) means that `namedtuple` is not re-exported, as that would have needed to be `from collections import namedtuple as namedtuple`. In "regular" code this code does have meaning, but in stub files it'd be nice for these to be grayed out so I know I can delete them or otherwise know that they aren't being properly reexported.

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.59, which I just published. It will also appear in the next release of Pylance.
