### ISSUE TITLE
Attributes with `attrs` converters show `__converterDescriptor_x` instead of type hint

### ISSUE THREAD

**Issue by my1e5** [microsoft/pyright#9041]
Related - https://github.com/microsoft/pyright/issues/8881

Using Pylance `v2024.9.101`, attributes using the `converter` feature of the `attrs` library no longer show the type hint when hovering over the symbol.

```python
import attrs

@attrs.define
class A:
    x: tuple[int, ...] = attrs.field(converter=tuple)

A([1,2,3]).x
```
![image](https://github.com/user-attachments/assets/8b2910f0-4e47-4546-aeea-96b7f5c90569)

This was first reported on the Pylance repo here - https://github.com/microsoft/pylance-release/issues/5391#issuecomment-2360757437
Relevant info from @debonte:

> it looks like this regressed in Pyright 1.1.379. Can you file a new issue on Pyright?

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.382.
