### ISSUE TITLE
Inconsistency between mypy and Pyright for overloaded method with union of callable types

### ISSUE THREAD

**Issue by hrpatil** [microsoft/pyright#9042]
There appears to be a discrepancy between mypy and Pyright in how they handle overloaded methods with a union of callable types. The following code passes mypy checks without any errors, but Pyright reports "Overloaded implementation is not consistent with signature of overload" errors.

```python
from typing import Any, Callable, Concatenate, TypeAlias, TypeVar, overload

Template: TypeAlias = dict[str, Any]
F1: TypeAlias = Callable[
    Concatenate[Template, str, None, str, ...], Template | list[Template] | None
]
F2: TypeAlias = Callable[
    Concatenate[list[Template], str, None, list[str], ...], list[Template] | None
]
F3: TypeAlias = Callable[
    Concatenate[Template, str, str, str, ...], Template | list[Template] | None
]
F4: TypeAlias = Callable[
    Concatenate[list[Template], str, str, list[str], ...], list[Template] | None
]
SlideCreationFunc: TypeAlias = F1 | F2 | F3 | F4
F = TypeVar("F", bound=SlideCreationFunc)

class Presentation:
    def __init__(self) -> None:
        self.slides: list[
            tuple[str, str, str | None, str | list[str], SlideCreationFunc]
        ] = []

    @overload
    def slide(
        self, section: str, slide_group: None, slide: str
    ) -> Callable[[F1], F1]: ...

    @overload
    def slide(
        self, section: str, slide_group: None, slide: list[str]
    ) -> Callable[[F2], F2]: ...

    @overload
    def slide(
        self, section: str, slide_group: str, slide: str
    ) -> Callable[[F3], F3]: ...

    @overload
    def slide(
        self, section: str, slide_group: str, slide: list[str]
    ) -> Callable[[F4], F4]: ...

    def slide(
        self, 
        section: str, 
        slide_group: str | None, 
        slide: str | list[str]
    ) -> Callable[[F], F]:
        def decorator(f: F) -> F:
            self.slides.append((f.__name__, section, slide_group, slide, f))
            return f
        return decorator
```

Code sample in [pyright playground](https://pyright-play.net/?pyrightVersion=1.1.353&pythonVersion=3.13&strict=true&enableExperimentalFeatures=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCKcANFAMICGANtZQEbUCmZ5YKAxpTEyty1AAqiJgWpJKAZzLCETAGqUQZMADcmIamEoATAFB7BTbHR4AuISLETJUALxQdSDjADakmMsLEAunoBiAIwWsqLiUvYUNHSMTK56UIkU7Fw8fDyuRib8ZB5eAHLsAnlkAHTlPjLGCKZMUAA%2BUOIemdW1Pg1QhShMen7%2BAEwhVuG2DlS0DMzxScmc-OlxzW5ZNfyVUCVdRWTL7p4b5aUbe6vtnd29-QDMw3LWEePRU3EJSWzzafyt2Ty5nv8vFsjhszvxOqc2usLkU%2BgEACx3MI2SITGLTN6JD6pXjfSG-JgbLZbPZ5Q4VXZIFpgngdRqXOEAZXEOiY5BATG4SHY-gArpwkQ8xlAgp1BmLrmL4QFIqFFCAABQAIn8SrI9DA-J0dmZSFZ7M5MG5KD5nAAlAYOHRJLYAAocyS8GBc9hmTGOJjAKAAfW9qCQMF9Csd1GAZqgAFoAHzbHpu2azEPAUqSFlMSQWPbuhNJGC8mpxYkAzaeGE9QEQqluMlkXX6jkuk38jh%2BHOJDoOVx%2Bd0AATUGi0undrK9qb1TAV2aSSdyTBcxosxLT3rQ4HzFkuuTTi887vD0aik1irlcQQ2Z4sRwMsz76k02n0sxHmzTk7bmyYodn89dJaBy9XTUEA3HYX3HTMq32EBWySfcYzRF4T0Gc8Bh8S9ymvJJbwHB9h09MDWTfNsZw-H8UB3f9xxXNdgL-LdwL-PdI3g55j1Pa5zw49DSkwxJsPvIcn3wsdCKnRISMdMiKPo1lqKA6SCKYCCWjJJiDwQtj-Hhc9tO43iPVHV8xI-L8oGMySjV-LZzIAmiKLLAQbIYvJKxUg41JYo9plPc80OM59WQ4XBuFwBVgAsfw4JFeN32nT9kxE9NSkoBA5BQHQFTC0pfT4CAmF9b9LJQGT8sA-MSrIMMLVipIOTzEAUCgYBjLq3kGo9IKQBCkAgA)

Code sample in [mypy play-net](https://mypy-play.net/?mypy=latest&python=3.12&gist=9649a5bf71a850744fe843882f4a9149)

pylance version : 2024.9.1 (9 September 2024) Release - No error
pyright version: 1.1.381 - 4 errors

**Comment by erictraut** [comment]
I'm not able to repro the problem with recent versions of pyright. The reason you're seeing errors in the pyright playground is that you have it set to pyright 1.1.353, which is quite old. If you switch to a more recent version of pyright, you should see the errors go away.

**Comment by hrpatil** [comment]
I've tested on the latest version of Pyright and can confirm there is no issue. The problem was indeed with an outdated version in my virtual environment. Updating Pyright resolved the errors. Thank you for your help in identifying this, and I appreciate your quick response to my report.
