### ISSUE TITLE
Union of Callable with different return types incorrectly treated as Callable with Union return type

### ISSUE THREAD

**Issue by kgaranger** [microsoft/pyright#9049]
I would expect the following code ([Pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDCAhgDYlEBGJApgFC0Am1wUwAFAB4BcUJSAzjADawEmCIwAulAA%2BvAcMEhJASi60omqAiL9%2B9Rsyho2cHsTKUaQoZIA0rMROlyL5KtRv2oS1eq2sbEJwbCoOISqqQA)) to be correct, but Pyright issues an error at the last line: `Argument of type "list[float | str]" cannot be assigned to parameter "x" of type "list[float] | list[str]" in function "f"`.
It seems to me that the argument passed to `f` should be `list[float] | list[str]` and not `list[float | str]`.

```python
from typing import Callable

def f(x: list[float] | list[str]):
    pass

def g(y: Callable[[], float] | Callable[[], str]):
    f([y(), y()])
```

**Comment by erictraut** [comment]
Pyright's behavior here is correct.

You can see why this is the case if you break down the expression into its subexpressions and think about how each is evaluated.

Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDCAhgDYlEBGJApgFC0Am1wUwAFAB4BcUJSAzjADawEmCIwAulAA%2BvAcMEhJASi60omqAiL9%2B9JizRs4PYmUo0hQyQBpWYidLnnyVatbtQlq9VqgAbgCMUAC8UHBsKhpaINQB1KQA%2BvAI1GzBKlAAxA7i%2BHJKMZoBAExhUELB9sGSxVBxCcmp6WVZuXyCIo4F3jDK9ext9bRAA)

```python
from typing import Callable

def f(x: list[float] | list[str]):
    pass

def g(y: Callable[[], float] | Callable[[], str]):
    v1 = y()
    reveal_type(v1) # float | str
    v2 = [v1, v1]
    reveal_type(v2) # list[float | str]
    f(v2)
```

Not surprisingly, mypy generates the same error in this case.
