### ISSUE TITLE
TypeForm and type(x)

### ISSUE THREAD

**Issue by adampauls** [microsoft/pyright#9055]
I'm aware the spec is not yet finalized and that the implementation is experimental. I'm also not clear on what the (current) spec says here. 

**Describe the bug**
```python
from typing import Any

from typing_extensions import TypeForm

s: str = "5"
t: type[str] = type(s)
tf: TypeForm[str] = type(s) #  error: Type "type[str]" is not assignable to declared type "TypeForm[str]"
    "type[type]" is not assignable to "type[TypeForm[str]]" (reportAssignmentType)

tf2: TypeForm[Any] = type(s) #  error: Type "type[str]" is not assignable to declared type "TypeForm[Any]"
    "type[type]" is not assignable to "type[TypeForm[Any]]" (reportAssignmentType)

tf3: TypeForm[Any] = str # ok
```

The [spec](https://peps.python.org/pep-0747/) says:

> When a type expression is evaluated at runtime, the resulting value is a type form object.

> TypeForm[T] describes the set of all type form objects that represent the type T or types that are [assignable to](https://typing.readthedocs.io/en/latest/spec/glossary.html#term-assignable) T.

`str` is unambiguously a type expression, whose resulting value is unambiguously a "type form object" as per the spec. `type(s)` evaluates to `str`, so I believe `type(s)` evaluates to a "type form object", but it's possible the spec is not being clear here. If it is true that `type(s)` evaluates to a type form object, then surely it must be assignable to `TypeForm`. 

It's possible the intent of the spec is that `TypeForm` represents things that are statically known to be the result of evaluating a type expression, and `type(s)` is itself unambiguously _not_ a type expression. If so, then I think the spec needs to be reworded.

** Version **
1.1.381 from the command line.

**Comment by erictraut** [comment]
This is working correctly. You're attempting to assign a value to a `TypeForm` type that does not come from a valid type expression. You'd see a similar error if you attempted to use the expression `type(s)` in a type annotation.

**Comment by adampauls** [comment]
I find it basically impossible to read the spec in the way that you are saying (though of course, you know the intent behind the spec much better than I am I'm sure). I agree that `type(s)` not a valid type expression, but nowhere in the spec does it say that `TypeForm` must be produced by a type expression. It says that it takes as an argument a type expression, but the TypeForm itself "describes the set of all type form objects that ...". Type form objects are the results of evaluating type expressions, but such objects can be produced in other ways too. 

Perhaps I should leave a comment on the spec? I'm not quite sure where to do that.

**Comment by erictraut** [comment]
If you find the spec to be ambiguous or confusing, I'd appreciate feedback on how to improve it. [Here](https://discuss.python.org/t/pep-747-typeexpr-type-hint-for-a-type-expression/55984/44) is the thread in the typing forums.
