### ISSUE TITLE
(windows) `exclude` parameter in config causes RAM bloat and infinite loop

### ISSUE THREAD

**Issue by Artalus** [microsoft/pyright#9057]
## **Describe the bug**
If `pyproject.toml` has `[tool.pyright] exclude = [ 'something/' ]`, launching `pyright` causes the `node.exe` process to go into some infinite loop, crunching at a few % of CPU and (seemingly endlessly) increasing the memory consumption. Even on the minimal repro project, the process did not finish after 2 minutes and grew up 2 gigs of RAM. When run on a real project, the RAM bloat happens faster, growing up to 1 GB in 10-20 seconds.

## **Code or Screenshots**
![изображение](https://github.com/user-attachments/assets/67b5a002-b9cd-4e49-9447-04c003f32395)
```toml
# pyproject.toml
[project]
name = 'myproject'
version = '0.1'

[tool.pyright]
exclude = [
    'ignore/',
]
strict = [ 'src/' ]

```
```python
# src\myproject\__init__.py
def foo(x):
    return x*2
```
```python
# ignore\folder\ignore.py
# can be empty
```
```powershell
PS E:\1> npm i pyright
PS E:\1> pyright
```

Replacing `exclude =` with `ignore =` solves the issue; the analysis is still not run over the ignored directory.

```
(1) PS E:\1> pyright
e:\1\src\myproject\__init__.py
  e:\1\src\myproject\__init__.py:1:5 - error: Return type is unknown (reportUnknownParameterType)
  e:\1\src\myproject\__init__.py:1:9 - error: Type of parameter "x" is unknown (reportUnknownParameterType)
  e:\1\src\myproject\__init__.py:1:9 - error: Type annotation is missing for parameter "x" (reportMissingParameterType)
  e:\1\src\myproject\__init__.py:2:12 - error: Return type is unknown (reportUnknownVariableType)
4 errors, 0 warnings, 0 informations
```

## **VS Code extension or command-line**
Command-line.
**OS**: Windows 10
**Python**: 3.11.3
**pyright**: 1.1.381
**node**: v20.0.0
**npm**: 9.6.4

**Comment by erictraut** [comment]
If you omit the `exclude`, pyright will auto-exclude certain directories within your project include `**/node_modules`, `**/__pycache__`, `**/.*` and directories that appear to be virtual environments. If you provide an explicit `exclude` setting, there are no auto-excludes and you are responsible for specifying which directories. I suspect what's happening is that you have a virtual environment in your project folder, so pyright is treating all of the files within this virtual environment as project source files and attempting to type check them.

**Comment by Artalus** [comment]
Thank you! Indeed I misread the docs, and thought these defaults remain even if I override the `exclude` values. Putting `.venv` into the list fixed the issue. Though the docs mention that _"Pylance also excludes any virtual environment directories regardless of the exclude paths specified"_ - is that a VS Pylance-specific behavior that PyRight CLI does not replicate?..

Shall I then copy the 3 default masks, and still put my project-specific ignores under `exclude`? Or better leave it alone, and use `ignore` instead? The docs are a bit ambiguous about this:

> \>`exclude` .... files that should not be considered part of the project .... may still be included in the analysis if they are referenced (imported) by source files that are not excluded
> \>`ignore` .... files whose diagnostic output (errors and warnings) should be suppressed even if they are an included file or within the transitive closure of an included file

Sounds as if the files under `exclude` will _likely_ get excluded from the analysis, but might _still_ get pulled in, if PyRight notices the dependencies. And the files under `ignore` would actually get _analyzed_, but the messages from them are silenced?..

**Comment by erictraut** [comment]
The `include` and `exclude` settings allow you to specify which files are part of your project. Errors are not reported for a file that is not part of your project unless you explicitly open such a file in your editor to view its contents.

If you want to suppress all of the errors in a file (regardless of whether it's in your project), you can add it to the `ignore` setting.

If you have a pyright config file, any settings in that config overrides any type-checker-related settings that you've specified in your VS Code `settings.json` file. This assumes that the config file is checked in to the repo, and it guarantees that everyone on the team will see the same type checking behaviors for the project regardless of their local settings.json files.

**Comment by lunaynx** [comment]
> If you provide an explicit `exclude` setting, there are no auto-excludes and you are responsible for specifying which directories.

I'm sorry, but how does anyone think this is good behavior? I recognize that there should be a way to start with a clean slate, but it should not be forced if you want to specify any additional exclusions at all.

I imagine it's too late to change this now without a major version bump, but perhaps an `extend_exclude` option or similar could be added?
