### ISSUE TITLE
python.languageServer": "Pylance" is not accepted 

### ISSUE THREAD

**Issue by bgulseren** [microsoft/pyright#906]
**Describe the bug**
Installed pylance using VS Code extensions and opened up settings.json. The entry `"python.languageServer": "Pylance"` is there however pylance is showing as not acceptable value.

**To Reproduce**
Install Pylance.

**Expected behavior**
Pylance to be recognized by vscode and language server getting to work.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/38707813/89087757-95123980-d352-11ea-9a40-04a8090b7766.png)

**VS Code extension or command-line**
Using Pylance v2020.7.4 form VS Code extension

**Comment by jakebailey** [comment]
See microsoft/pylance-release#16. This is expected, and Pylance should still start despite that warning.

If you run the insiders build of the Python extension, this is fixed (and will be fixed in the next Python extension release).

**Comment by jakebailey** [comment]
Didn't mean to close before getting your feedback, my mistake. Is Pylance starting despite the warning? Just to verify.

**Comment by erictraut** [comment]
As Jake mentioned, this is a duplicate. Please follow up on the linked thread if you have additional questions of feedback. Thanks!
