### ISSUE TITLE
Operator "+" not supported for types "List[str]" and "List[str | None]"

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#908]
```python
from typing import List, Optional


def append(l: List[str], lo: List[Optional[str]]) -> List[Optional[str]]:
    return l + lo
```

pyright 1.1.58:
```
error: Operator "+" not supported for types "List[str]" and "List[str | None]"
```

This works at runtime, so I wasn't expecting a type error.

**Comment by erictraut** [comment]
This is correct behavior as defined in PEP 484 for a List.

See issue #828 for a full explanation.

**Comment by tekumara** [comment]
Thanks for the pointer. The solution in #828 was to use a covariant collection like `Sequence` rather than `List`.

I tried using a `Sequence` but it didn't work, eg:

```python
from typing import Optional, Sequence


def append(l: Sequence[str], lo: Sequence[Optional[str]]) -> Sequence[Optional[str]]:
    return l + lo
```

also produces:
```
Operator "+" not supported for types "Sequence[str]" and "Sequence[str | None]"
```

The only way I've found around this is to append `# type: ignore`

**Comment by erictraut** [comment]
Sequences are immutable whereas lists are not. That's the very reason why you're not allowed to append a list with a type that violates the list's contents. 

If your intent is to mutate (append to) the input list `l` and return the resulting list, this is the correct way to do it:
```
def append(l: List[Optional[str]], lo: List[Optional[str]]) -> List[Optional[str]]:
    return l + lo
```

If your intent is to return a new list that contains the contents of the old list plus a new entry, this is the correct way to do it:
```
def append(l: List[str], lo: List[Optional[str]]) -> List[Optional[str]]:
    new_list: List[Optional[str]] = list(l)
    return new_list + lo
```
