### ISSUE TITLE
"__getitem__" method not defined on type "int"

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#909]
```python
kwargs = {
    "MinCount": 1,
    "NetworkInterfaces": [
        {
            "DeviceIndex": 0
        }
    ]
}
f = kwargs["NetworkInterfaces"][0]
```

pyright 1.1.58 with `"strictDictionaryInference": true`:
```
9:5 - error: "__getitem__" method not defined on type "int"
```

**Comment by tekumara** [comment]
Looks like I can fix this with the type hint `kwargs: Dict[str, Any]`

**Comment by erictraut** [comment]
That's correct. For more details about dictionary type inference, refer [to this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#dictionary-expressions).
