### ISSUE TITLE
[Request] Add automatic installation of dependencies to MyPright, just like `mypy --install-types`

### ISSUE THREAD

**Issue by oncealong** [microsoft/pyright#9098]
I have a large and complex code base, and I used mypy in the past. When I used mypy, I would configure it to automatically install the type library like this:
```
mypy --namespace-packages --explicit-package-bases . 
mypy --install-types 
```
But the combination of mypy and VSCode is not very good. In VSCode, I plan to use pylance because it supports features such as automatic import.
Now I am looking at the configuration of pyright, and I found that pyright has no way to automatically import type dependencies.

Pyright should provide a configuration like `pyright --install-types` to automatically install type libraries to help novices automatically install various dependencies

**Comment by erictraut** [comment]
Unlike mypy, pyright bundles all of the third-party typeshed stubs, so there's no need to install these packages into your python environment. 

Any other packages that your project depends upon should be installed in the selected Python environment prior to running pyright. Most popular Python packages now have inlined type information, so the need to install separate stub packages is becoming relatively rare.
