### ISSUE TITLE
Type isn't inferred when passing a generic function as an argument to a method of a generic class

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pyright#910]
I am using Pyright v1.1.58 as a VSCode extension.
I don't know whether it's a more general problem or if it's something specific to this example.

Setup code:
```py
from typing import *

A = TypeVar("A")
B = TypeVar("B")
C = TypeVar("C")

class Pair(Generic[A, B]):
    left: A
    right: B

    def __init__(self, left: A, right: B):
        self.left = left
        self.right = right

    def map_right(self, fn: Callable[[B], C]) -> "Pair[A, C]":
        return Pair(self.left, fn(self.right))
```

**Exampe A (works):**
```py
x = Pair[int, int](1, 2)
y = x.map_right(float)
```
In Example A, `y` is inferred to hold a value of type `Pair[int, float]`. If you define your own `int_to_float` function, it works as well.

**Example B (works):**
```py
def first(t: Tuple[A]) -> A:
    return t[0]
u = first((4,))
```
In Example B, `u` is correctly inferred as being `Literal[4]`.

**Example C (doesn't work):**
```py
p = Pair[int, Tuple[int]](1, (3,))
q = p.map_right(first)
```
In Example C, `q` is inferred as being `Pair[int, A]`, when it should have been inferred to be `Pair[int, int]`.

**Comment by erictraut** [comment]
You're using generic types in an incorrect manner here.

First, one small matter of terminology. There is no "type inference" happening in the evaluation of `q = p.map_right(first)`. All of the types here are declared, so no inference is needed.

The process by which the type of `q` is determined is referred to as TypeVar matching (sometimes also called TypeVar "solving"). This process is applied when evaluating call expressions where the target call signature contains generic types.

In your example, the expression `p.map_right` is a partially-specialized call with the type `Callable[[Callable[[Tuple[int]], C], Pair[int, C]`. The argument you're passing this call is `first` which has a type of `Callable[[Tuple[A]], A]`. It is the job of the TypeVar matching process to "solve" all of the type variables in the calling signature. In this case, we're going to "solve for C". Note that we are not "solving for A".

Solving TypeVars is a very involved and complicated process that uses both type narrowing and type widening, and it can sometimes require multiple passes across all of the arguments and parameters. It's not practical to solve for TypeVars in the argument types as in the parameter types, nor would that be consistent with how TypeVar matching is described in 483 and 484.

In the example above, the TypeVar matching process determines that "C" must be equal to "A", hence it determines that the resulting type of the call expression is `Pair[int, A]`
