### ISSUE TITLE
Non-compliance with PEP 747 (type forms)

### ISSUE THREAD

**Issue by luwqz1** [microsoft/pyright#9101]
- strict mode
- enableExperimentalFeatures = true

I used an example from the [PEP 747 #assignability](https://peps.python.org/pep-0747/#assignability) and decided to check it

```python
from typing import TypeForm

def get_type() -> type[int]: ...

t3: TypeForm[int | str] = get_type()  # In PEP OK, but pyright reports an error "reportAssignmentType"
t4: TypeForm[str] = get_type()  # Error
```

**Comment by erictraut** [comment]
Thanks for pointing that out. This section of the PEP was left over from an earlier draft and was unintentionally left in the latest draft. I've updated the PEP accordingly.

See [this discussion thread](https://discuss.python.org/t/pep-747-typeexpr-type-hint-for-a-type-expression/55984/47) for the reasoning for this. If you have thoughts on this, feel free to post to that thread.
