### ISSUE TITLE
Class instance attributes lose literal typing in methods

### ISSUE THREAD

**Issue by nathanrpage97** [microsoft/pyright#914]
**Describe the bug**

Instance attributes lose literal specificity after creation in constructor. They revert to a union of all types of the literal.

**To Reproduce**

Create any form of literal as instance attribute and use attribute in other methods.

**Expected behavior**

instance attributes should maintain typing across methods.

**Screenshots or Code**

```python
from typing import Literal

class Foo:
    def __init__(
        self,
        bar: Literal["left", "right", "center"],
        bar2: Literal[2, 3],
        bar3: Literal["left", 2],
    ) -> None:
        self.bar = bar     # typing as Literal["left", "right", "center"]
        self.bar2 = bar2   # typing as Literal[2, 3]
        self.bar3 = bar3   # typing as Literal["left",2]

    def test_bar(self) -> Literal["left", "right", "center"]:
        return self.bar # typing as string here

    def test_bar2(self) -> Literal[2, 3]:
        return self.bar2 # typing as int here

    def test_bar3(self) -> Literal["left", 2]:
        return self.bar3 # typing as str | int here
```

**VS Code extension or command-line**

1.47.3
Pylance 2020.7.4

**Additional context**

Explicitly setting the typing of instance attribute fixes the issue but adds unnecessary duplicate typing information.

```python
from typing import Literal

class Foo:
    def __init__(
        self,
        bar: Literal["left", "right", "center"],
        bar2: Literal[2, 3],
        bar3: Literal["left", 2],
    ) -> None:
        self.bar: Literal["left", "right", "center"] = bar
        self.bar2: Literal[2, 3] = bar2
        self.bar3: Literal["left", 2] = bar3

    def test_bar(self) -> Literal["left", "right", "center"]:
        return self.bar

    def test_bar2(self) -> Literal[2, 3]:
        return self.bar2

    def test_bar3(self) -> Literal["left", 2]:
        return self.bar3
```

**Comment by erictraut** [comment]
This behavior is intended. Please refer to the [documentation on type inference](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#literals) for an explanation.

If you want a variable to have a literal type, you should use a type declaration, not rely on type inference. The code in your second example is the correct approach.

**Comment by nathanrpage97** [comment]
I see. Thanks for the quick response.
