### ISSUE TITLE
Classes in Interpreter Paths defined in PyCharm are not found

### ISSUE THREAD

**Issue by sparky2708** [microsoft/pyright#9143]
In PyCharm if you go to File -> Settings -> Python Interpreter-> Your Python Interpreter -> Interpreter Paths and add a local path then it seems that pyright is not seeing the files in that directory. How can this be addressed?

**Comment by erictraut** [comment]
PyCharm doesn't have any association with pyright. They're different tools. I wouldn't expect pyright to understand PyCharm's settings or vice versa.

For information on how to configure pyright, refer to [this documentation](https://microsoft.github.io/pyright/#/configuration).

**Comment by sparky2708** [comment]
I'm OK with configuring pyright to understand there are local directories involved in this project. Is there a way to do that?
