### ISSUE TITLE
python.analysis.autoSearchPaths and python.analysis.extraPaths is supported?

### ISSUE THREAD

**Issue by seagle0128** [microsoft/pyright#916]
Is the "python.analysis.autoSearchPaths" and "python.analysis.extraPaths" setting in settings.json supported by the pyright extension? I can't seem to get it working and wanted to check it is actually used by pyright. Or is there another way to tell pyright about other paths to search for imports? Does pyright make use of the pyrightconfig.json file for example?

**Comment by erictraut** [comment]
Yes, Pyright supports both of those settings. The full list of supported settings is documented [here](https://github.com/microsoft/pyright/blob/master/docs/settings.md). 

Pyright (and Pylance) also support the pyrightconfig.json file. Some settings can be controlled in both locations. For a full list of options available in the config file, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md).

**Comment by seagle0128** [comment]
Let me double check.
