### ISSUE TITLE
False positive when annotating `self` as `Callable` in a callable class

### ISSUE THREAD

**Issue by luwqz1** [microsoft/pyright#9166]
Case 1:

![image1](https://github.com/user-attachments/assets/327cf4fc-ff73-4659-9e58-02d93d046cff)

Case 2:

![image2](https://github.com/user-attachments/assets/16b53f75-8dc8-466c-ab45-55fb674f1ef4)

But mypy works correctly [mypy playground](https://mypy-play.net/?mypy=latest&python=3.12&gist=f83d37e3ceaf35e011e526eb82313099)

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.384
