### ISSUE TITLE
New type parameter syntax in Python 3.12 raises `reportIndexIssue` for generic function

### ISSUE THREAD

**Issue by simensol** [microsoft/pyright#9216]
I'm upgrading my codebase from Python 3.11 to 3.12 and wanted to try the new, more compact, and explicit way to create generic classes and functions [introduced in PEP 695](https://docs.python.org/3/whatsnew/3.12.html#pep-695-type-parameter-syntax):

> ```python
> def max[T](args: Iterable[T]) -> T:
>     ...
> 
> class list[T]:
>     def __getitem__(self, index: int, /) -> T:
>         ...
> 
>     def append(self, element: T) -> None:
>         ...
> ```

However, my implementation below raises `reportIndexIssue` in both Pylance `v2024.10.1` and Pyright `v1.1.384`:

```python
def func[T](var: T) -> T:
    return var

func[str](var=1)
```

Pylance:
![Image](https://github.com/user-attachments/assets/67ad3dbb-14d3-42f0-8193-2cff898744bd)

Pyright:
```bash
poetry run pyright .
ixtures.py:143:1 - error: Object of type "(var: T@func) -> T@func" is not subscriptable (reportIndexIssue)
```

**Comment by erictraut** [comment]
Functions are not subscriptable, so `func[str]` will generate an exception at runtime. The type argument can be inferred from the arguments you pass to the function call, so there's no need to explicitly specialize the function.

```python
x = func(var=1)
reveal_type(x) # Revealed type is int
```

There is a [draft PEP 718](https://peps.python.org/pep-0718/) that proposes to make functions subscriptable, but it has not been formally submitted for consideration by the Python steering council.
