### ISSUE TITLE
`TypeGuard` unexpectedly widens generic type

### ISSUE THREAD

**Issue by brentyi** [microsoft/pyright#9224]
Here's a snippet that works:
```python
def foo[IntOrFloat: (int, float)](x: IntOrFloat) -> IntOrFloat:
    if isinstance(x, int):
        print(f"{x} is an int!")
    return x
```

When I replace `isinstance(x, int)` with my own TypeGuard, however, I get an error on the return statement:
```python
from typing import Any, TypeGuard

def is_int(x: Any) -> TypeGuard[int]:
    return isinstance(x, int)

def foo[IntOrFloat: (int, float)](x: IntOrFloat) -> IntOrFloat:
    if is_int(x):
        print(f"{x} is an int!")
    return x  # Type "int | IntOrFloat@func" is not assignable to return type "IntOrFloat@func"
```

([pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCKcANFACqICmA4gK4CGIAJgFCvNXCYDOA%2BqhgAKAB4AuQsQCUUALQA%2BCtXpNmAbUEBdMayh6oIKjDogUvVDxgMUAYyqiygqe07dgYMGoCSKGAHkQADEAGzAGGAkhQTJgUPCpTVEJH38guJgZBSgUgJCwiN19JG4kfkFRKR19aqgEEHLgACIAbxEAX14oa0xfAEJG52rDY1MoESA))

I found this surprising, is it intended? I tried both Pyright `1.1.384` and `1.1.300`.

Thanks!!

**Comment by erictraut** [comment]
Yes, this is working as intended. This is how `TypeGuard` is defined. If you want `isinstance` type narrowing semantics, use `TypeIs` instead. See [this documentation](https://typing.readthedocs.io/en/latest/spec/narrowing.html) for details.

**Comment by brentyi** [comment]
Hi @erictraut! It's possible I'm misunderstanding, but to clarify I'm not looking for any specific narrowing semantics. I was just expecting the return type to be unaffected by the TypeGuard call.

My understanding of `TypeIs` is that it primarily impacts the negative / "else" case of the narrowing. But I don't use use that in this example:
```python
def foo[IntOrFloat: (int, float)](x: IntOrFloat) -> IntOrFloat:
    if is_int(x):
        print(f"{x} is an int!")
    return x  # Type "int | IntOrFloat@func" is not assignable to return type "IntOrFloat@func"
```

Here's an alternative one with the same error:
```python
def foo[IntOrFloat: (int, float)](x: IntOrFloat) -> IntOrFloat:
    print("int" if is_int(x) else "may or may not be an int")
    return x  # Type "int | IntOrFloat@func" is not assignable to return type "IntOrFloat@func"
```

mypy passes for both.

**Comment by erictraut** [comment]
The difference in behavior that you're seeing between pyright and mypy isn't really related to `TypeGuard` narrowing. It's related to how the two type checkers handle [value-constrained type variables](https://microsoft.github.io/pyright/#/mypy-comparison?id=value-constrained-type-variables).

I recommend against using value-constrained type variables if you can help it because their behaviors are not well specified in the typing spec. They are not found in any other type system — and for good reason. There are many misunderstandings about value-constrained type variables, and I find that they are often misused. For example, your code sample defines a type variable with the value constrains `float` and `int`. These two types overlap completely; all values of type `int` are also values of type `float`, so it doesn't make sense to define a type variable with those value constraints. You might as well just define a regular type variable with an upper bound of `float`.

```python
def foo[T: float](x: T) -> T:
    if isinstance(x, int):
        print(f"{x} is an int!")
    reveal_type(x)
    return x
```

**Comment by brentyi** [comment]
Thanks for the quick reply + link! Yeah, I'm not actually using `(int, float)` in practice. The error I'm seeing in my actual code is from a call to `asyncio.iscoroutinefunction`, which I believe is handled as a TypeGuard, on a callable that's constrained to return `(None, Coroutine)` (in other words: it may or may not be async). As a fix I can replace the `TypeVar` with a union + overloads.

If the issue isn't related to `TypeGuard`, is the inconsistency between `TypeGuard` and `TypeIs` here expected?
```python
from typing import Any, TypeGuard
from typing_extensions import TypeIs

# Contrived example with `TypeGuard`.

def is_none_typeguard(x: Any) -> TypeGuard[None]:
    return x is None

def foo_with_typeguard[IntOrNone: (int, None)](x: IntOrNone) -> IntOrNone:
    if is_none_typeguard(x):
        print(f"{x} is an int!")
    return x  # pyright error! 


# Same as above, but with `TypeIs`.

def is_none_typeis(x: Any) -> TypeIs[None]:
    return x is None

def foo_with_typeis[IntOrNone: (int, None)](x: IntOrNone) -> IntOrNone:
    if is_none_typeis(x):
        print(f"{x} is an int!")
    return x  # ok
```

([pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCKcANFACqICmA4gK4CGIAJgFCuiSyKpoD6VAB4wqKAM5Iw4zNlz5KCKgEkx7AMRQAooIbYANlSgB3JDAAWUAAYLajFpYB07VsyrBMYviilU%2B8RWh2zAAUggBchMQAlFAAtAB8FNT0TMwA2gByPgC6YaxQBVAgVDB0IChQgh5QWShUzq7uwGBgfCbmftSBqWlKKDAA8iC1VBHBqDBkI1HZoRF9g8M%2BMQlQC0MjeYWY7kie3nWdAUGhUVvbhQggE8HAAEQA3oIAvtUMFRMAhHdR%2BYXFpXKlQKGgQcGuaDM%2BCoIHAIE%2BUGcGgAyrpDAwxFAGAAjMAANyoZGxdHw7Qs1moKkcDTcHi8PiOVD2c0icBWiRsKkyOXOBQBZQqVT2NR8NKaLTapjMjL2vX6Gx8YwmU2Ws3Ca3lSzq7I1i02fwKSF2%2BwZ-iZYlOvIuVxu9yer2F70w-W%2Bv22-KBVSgGjAAGsEcEMVAhIoAMYiZhRIA))
