### ISSUE TITLE
Pyright ignores configuration from pyproject.toml when run as `pyright .`

### ISSUE THREAD

**Issue by dbzix** [microsoft/pyright#9230]
When running pyright with a directory as an option, e.g. `pyright .`, it ignores configuration from `pyproject.toml`. E.g., I have the following configuration:
```
[tool.pyright]
include = ["mysrc", "tests"]
```
Running just `pyright` works fine, ignoring **other** directories containing python code.
Running `pyright .` ignores this configuration checking **everything** under the current directory.

Is this behavior intentional?
I cannot find a clear description of this behavior anywhere in the documentation.

**Comment by erictraut** [comment]
Yes, this is by design. If you want pyright to use the project's configuration, just run pyright from within the project's directory.

**Comment by dbzix** [comment]
> Yes, this is by design. If you want pyright to use the project's configuration, just run pyright from within the project's directory.

Would you please answer where in the documentation this behavior is described?
I'm expecting that running `pyright` **in the project directory** will behave **_the same way_** disregarding if it's running as `pyright .` or just `pyright`.

**Comment by dbzix** [comment]
@erictraut ?

**Comment by erictraut** [comment]
Please see my response above. This is by design.

**Comment by dbzix** [comment]
Mentioning this difference in the documentation would be really helpful.
@erictraut
