### ISSUE TITLE
Snippet support in completions

### ISSUE THREAD

**Issue by leungbk** [microsoft/pyright#924]
It would be nice if [snippets](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#snippet_syntax) were given in completions. For example, with the insertion point at `[-]` in

``` python3
def factorial(n: int) -> int:
    return 1 if n == 0 else n * fa[-]
```

one of the completions could be, using snippet syntax,

`factorial${1:(${2:n: int})}`

Type-inferencing could be useful here to let us automatically drop the outer pair of braces depending on context.

**Comment by erictraut** [comment]
Thanks for the suggestion. This is a feature that we probably wouldn't add to pyright, which is the core type checking engine, but we would consider adding it to pylance. I've copied your feature request to the pylance-release repo so it gets the appropriate attention there. Thanks again!

**Comment by hungrybirder** [comment]
> Thanks for the suggestion. This is a feature that we probably wouldn't add to pyright, which is the core type checking engine, but we would consider adding it to pylance. I've copied your feature request to the pylance-release repo so it gets the appropriate attention there. Thanks again!

I'm very sad for this reply from a neovim user's perspective.
Pyright is not only an excellent checking engine but also a very fast languager server.

If pyright supports `snippets`, I can speed up editing code definitely.

Could you reconsider this great feature?

Thank you.

**Comment by MagicRB** [comment]
Well this exchange made my morning. Lol (I use Emacs so it affects me too, but I don't use python.)
