### ISSUE TITLE
Analysis of function "..." is skipped because it is unannotated spam

### ISSUE THREAD

**Issue by tik-stbuehler** [microsoft/pyright#9240]
**Describe the bug**

I disabled `analyzeUnannotatedFunctions` because it is f...ing annoying, and now it complains with about the same number of messages "Analysis of function "..." is skipped because it is unannotated" - and I can't find any setting to disable this sh...

https://github.com/microsoft/pyright/blob/7f8764cce449d7098e1cf5c6619f7fd0f9b92403/packages/pyright-internal/src/analyzer/checker.ts#L402-L409 seems to be the origin of this crap.

**Comment by erictraut** [comment]
I understand that you are expressing frustration, but let's keep the discourse civil. Don't assume that because something doesn't work to your liking that it's unintended or "spam".

This informational diagnostic is emitted based on previous feedback from pyright users who use `analyzeUnannotatedFunctions`. Your use case may differ from their's. 

Let's better understand your use case to see if there's a good workaround. Are you using pyright as a language server, or are you using the CLI version? If you're using it as a language server, are you setting the `diagnosticMode` to `workspace`? What led you to disable analysis for unannotated functions? Is your code base primarily untyped?

**Comment by erictraut** [comment]
Closing issue because pyright is working as intended here and there was no response to my questions. If you'd like to provide more details about your use case, we can continue the discussion.

**Comment by taldcroft** [comment]
I'm having the same problem, so I'd like to re-open the conversation and get to the bottom of this. To start I'll say that I appreciate the help!

My use case and setup:
- Using the language server via VS code to develop Python code.
- Basically all of the code is not type annotated.
- The goal is to not see any warnings or errors related to type annotations or type checking.
- Python analysis Type Checking Mode is set to `off`.

With that, I'm seeing warnings like this:
![Image](https://github.com/user-attachments/assets/ffb35ba2-12d4-438d-8d7d-d4c94bbcbb85)

**Comment by erictraut** [comment]
What you're seeing here are not warnings. They're "informationals" (to use the terminology of the language server protocol). The purpose of these informationals is to indicate that the function is not analyzed, so no type checking or language server features will work within that function.

If you've disabled type checking (set `typeCheckingMode` to "off") and your use case involves code editing and language server features, then there should be no reason to set `analyzeUnannotatedFunctions` to false. The `analyzeUnannotatedFunctions` option was added for users who want to enable type checking but don't want pyright to analyze functions that have no annotations. If you've disabled type checking, there's no reason to use this feature.

**Comment by johnny1up** [comment]
For what it's worth, I was indeed able to filter out the Informational warning in the Problems. However, I still do see the squiggle underlines and the pop-up message. It would be nice to disable the squiggle somehow as well, as it does add noise.

**Comment by taldcroft** [comment]
It appears that explicitly setting `analyzeUnannotatedFunctions` to `False` was causing the informational messages. It is not intuitive, but beleting that setting from the VS code `settings.json` file seems to have resolved the issue.

FYI, I was working with @johnny1up to figure this out.

**Comment by datapointchris** [comment]
If `analyzeUnannotatedFunctions` is set to false in your `pyproject.toml`, it will override the VS Code settings, so check that file as well if changing the setting in the editor isn't doing anything.

**Comment by taldcroft** [comment]
> If `analyzeUnannotatedFunctions` is set to false in your `pyproject.toml`, it will override the VS Code settings, so check that file as well if changing the setting in the editor isn't doing anything.

Makes sense. In this project there is no `pyproject.toml` or `pyrightconfig.json` file.
