### ISSUE TITLE
Unix-style locale name string parsing issue

### ISSUE THREAD

**Issue by NCBM** [microsoft/pyright#9269]
**Describe the bug**

There is a difference between Windows NLS locale names (IETF standard locale names) and Unix locale names. In unix-like the separator of language and country/region is the underscore `_` instead of dash `-`, for example, `en_US.UTF-8` in linux instead of `en-us.UTF-8`. The former is not recognized by pyright and the latter is not recognized by linux locale support. I'm not sure if this behavior is as designed.

**Code or Screenshots**

(Any code that produces messages that can be localized.)

**VS Code extension or command-line**

Pyright command-line (any version that only handles IETF locale names.)

**Comment by erictraut** [comment]
Refer to [this documentation](https://microsoft.github.io/pyright/#/configuration?id=locale-configuration) for how to set the locale for pyright. You'll need to specify the locale using dashes if you want pyright to understand it.
