### ISSUE TITLE
Unreachable code highlighting after return or raise

### ISSUE THREAD

**Issue by erictraut** [Microsoft/pyright#93]
Code that is found after a return or raise statement is unreachable and should be shown in gray in VS Code.

**Comment by erictraut** [comment]
This is now fixed in 1.0.19

**Comment by andre-fu** [comment]
Bump just Found a similar same error! 

![image](https://user-images.githubusercontent.com/39042250/74979184-28d2f780-53fc-11ea-8859-0a18cd329b06.png)

**Comment by erictraut** [comment]
@andre-fu, I think your issue is different.

I'm guessing that Pyright's type analyzer is determining that cv2.findContours always raises an exception. If you hover over it, what is the return type? If it's "NoReturn", that would confirm my theory. If it's something else, then I can't explain what you're seeing, and I'd appreciate it if you'd open a new bug with more details. Thanks!
