### ISSUE TITLE
Type "None" cannot be assigned to type "str | None"

### ISSUE THREAD

**Issue by fabiencelier** [microsoft/pyright#932]
I have this unclear error message:

<pre>
Expression of type "List[None]" cannot be assigned to declared type "Table"
  TypeVar "_T" is invariant
    Type "None" cannot be assigned to type "str | None" 
</pre>

**To Reproduce**
```python
from typing import List, Union

Table = List[Union[str, None]]

row: Table = [None] * 10
```

I have also tried with `Table = List[Optional[str]]` but it gives the same error.

**Expected behavior**
I expect Pyright to not detect an error as it is the same thing as 
```python
row2: Table = [None, None, None, None, None, None, None, None, None, None]
```
which does not gives any error.

**VS Code extension or command-line**
Both extension and command line version 1.1.62

**Comment by erictraut** [comment]
This was discussed a length in https://github.com/microsoft/pyright/issues/736.

**Comment by fabiencelier** [comment]
This is confusing because some very similar operations have different results. For instance:

```python
a = [None]
b: List[Optional[str]] = [None]

list1: List[Optional[str]] = [None]    # OK
list2: List[Optional[str]] = a         # FAIL
list4: List[Optional[str]] = b         # OK
list3: List[Optional[str]] = [None] + [None]  # FAIL
```
I understand that the right side is sometimes evaluated as `List[None]` but shouldn't a `List[None]` considered a valid `List[Optional[str]]` ?

**Comment by erictraut** [comment]
I agree that it's non-intuitive, but it's the correct behavior as defined in PEP 483 and 484.

For more discussion and details, refer to these threads:
https://github.com/microsoft/pyright/issues/130
https://github.com/microsoft/pyright/issues/280
https://github.com/microsoft/pyright/issues/828

**Comment by fabiencelier** [comment]
Ok, I guess I'll use a Sequence or try to type correctly an intermediary value.
Thanks for the links !
