### ISSUE TITLE
Import error in editable mode package installation

### ISSUE THREAD

**Issue by zx80** [microsoft/pyright#9333]
**Describe the bug**

When a package is installed in _editable_ mode (eg `pip install -e ../alongside-package`) pyright errors on a missing import for this package.
If the very same package is installed directly (aka `pip install ../alongside-package`), pyright works fine.

I do not expect the type checker behavior to change depending on whether a package is installed with the `-e` option.

**Code or Screenshots**

```shell
pip install ../utils
# Processing /.../utils
#  Installing build dependencies ... done
#  Getting requirements to build wheel ... done
#  Preparing metadata (pyproject.toml) ... done
#  …  
# Building wheels for collected packages:  …
#  Building wheel for … (pyproject.toml) ... done
#   Created wheel for ...: filename=...-py3-none-any.whl size=8828 sha256=...
#   Stored in directory: /...
#  Successfully built ...
#  Installing collected packages: ...
#   Attempting uninstall: ...
#     Found existing installation: ...
#     Uninstalling ...
#       Successfully uninstalled ...
# Successfully installed ...
pyright *.py
...
0 errors, 8 warnings, 0 informations
```

But

```shell
pip install -e ../utils
# Obtaining file:///...
#   Installing build dependencies ... done
#   Checking if build backend supports build_editable ... done
#   Getting requirements to build editable ... done
#   Preparing editable metadata (pyproject.toml) ... done
#  ...
# Building wheels for collected packages: ...
#   Building editable for corrector (pyproject.toml) ... done
#   ...
# Successfully installed ...
pyright *.py
...
  /... - error: Import "..." could not be resolved (reportMissingImports)
```

**VS Code extension or command-line**

Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool?  NO
Which version? Pyright 1.1.386.

**Comment by erictraut** [comment]
Please refer to [this documentation](https://microsoft.github.io/pyright/#/import-resolution?id=editable-installs) for details about editable installs.

**Comment by zx80** [comment]
Thanks Eric for the useful pointer :smile:

I guess that one design decision that lead to this issue is that pyright seems to be written in _ts_ thus cannot (easily) execute python imports, although maybe it could try to handle common cases, and/or try to give a  hint in the error message?

**Comment by erictraut** [comment]
The language that pyright is written in is irrelevant. A static type checker should never execute the code that it's analyzing or cause arbitrary third-party code to be executed. Doing so would be a big security problem. Other type checkers like mypy (which is written in Python) also abide by this rule.

Static analysis tools require declarative mechanisms. Unfortunately, the many setup tools have switched to using runtime import hooks for editable installs.

The best solution is for the packaging community and the typing community to agree on a standard declarative mechanism. Unless and until that happens, we're stuck with inconvenient workarounds.

**Comment by zx80** [comment]
> The language that pyright is written in is irrelevant. A static type checker should never execute the code that it's analyzing or cause arbitrary third-party code to be executed. Doing so would be a big security problem. Other type checkers like mypy (which is written in Python) also abide by this rule.

Ok.

> Static analysis tools require declarative mechanisms. Unfortunately, the many setup tools have switched to using runtime import hooks for editable installs. 

Ok. 

> The best solution is for the packaging community and the typing community to agree on a standard declarative mechanism. Unless and until that happens, we're stuck with inconvenient workarounds.

Sure, that would be the best solution, although I would be pessimistic that this is resolved quickly in the Python ecosystem.

Now, there is a thing called _abstract interpretation_ which could mean that the relevant import code is executed _enough_ to resolve the issue whilst the security is still warranted. Alternatively, executing audited package loading code, possibly with some guards or sandboxing, or using code that you actually wrote for the purpose, may be considered safe and allow to handle most cases.  So for me such feature is still more of a choice, which is ok.

Nevertheless, ISTM that on import errors _static analysis_ could figure out that it is an editable install, say for `pip`there is an `__editable__<package...>_finder.py` in the python env, and report the issue more clearly? That may help save you ticket triaging time…

Anyway, thanks again for the detailed reply!
