### ISSUE TITLE
Type narrowing for `Optional` properties

### ISSUE THREAD

**Issue by Grutschus** [microsoft/pyright#9334]
**Describe the bug**
If I have an `Optional` attribute on a class and define a `property` that checks for the existence of the attribute, pyright does not correctly narrow the type.

**Code or Screenshots**
Broken code:
```python
from typing import Optional, reveal_type

class A:
    optional: Optional[int]

    @property
    def is_there(self) -> bool:
        return self.optional is not None


def test(x: A) -> None:
    if x.is_there:
        reveal_type(x.optional)  # Type of "x.optional" is "int | None"Pylance
```

Expected behavior:
```python
from typing import Optional, reveal_type


class A:
    optional: Optional[int]

    @property
    def is_there(self) -> bool:
        return self.optional is not None


def test(x: A) -> None:
    if x.is_there:
        reveal_type(x.optional)  # Type of "x.optional" is "int" Pylance
```

**VS Code extension or command-line**
Pylance language server 2024.10.1 (pyright version 1.1.382, commit e46efc6b)

**Comment by erictraut** [comment]
Pyright is working as intended here. Type narrowing operates only locally, not across function calls. If you want type narrowing to apply to the expression `x.optional`, you would need to write your code like this:

```python
def test(x: A) -> None:
    if x.optional is not None:
        reveal_type(x.optional)
```
