### ISSUE TITLE
False Liskov positive in generic subclass with different type variable

### ISSUE THREAD

**Issue by hauntsaninja** [microsoft/pyright#9347]
```
class Map[T]:
    def map(self, x: T) -> T:
        return x
    
class Sub[T](Map[T]):
    def map[U](self, x: U) -> U:
        return x
```

While perhaps unusual, I believe the above code is type safe. Currently pyright complains with:
```
Method "map" overrides class "Map" in an incompatible manner
  Return type mismatch: base method returns type "T@Sub", override returns type "U@map"
    Type "U@map" is not assignable to type "T@Sub"  (reportIncompatibleMethodOverride)
```
mypy accepts it (but has some issues in other cases)

(I would of course expect a type error if you added `super().map(x)` or `self.x = x` to the body of `Sub.map`)

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.387.

**Comment by LeeeeT** [comment]
If
```python
class Sub[T](Map[T]):
    def map[U](self, x: U) -> U:
        return x
```
is considered ok, why not
```python
class Sub(Map[str]):
    def map[U](self, x: U) -> U:  # "object*" is not assignable to "str"
        return x
```
too?

@erictraut is this intended behavior or a bug?

**Comment by erictraut** [comment]
@LeeeeT, I agree this looks like a bug. Please file a new issue so it doesn't get lost.
