### ISSUE TITLE
Regression (?) changes to imported entities not detected

### ISSUE THREAD

**Issue by colinRawlings** [microsoft/pyright#937]
**Describe the bug**

Pyright no longer spots that the definition of an imported symbol has changed.

**To Reproduce**

- Create a venv.
- Create a package `my_package` within the `${workspaceFolder}` which defines a function `foo` 
- editably install it to the venv: `venv/Scripts/pip install -e <path/to/my_package>`
- Set the project interpreter to be `venv/Scripts/python.exe`
- create a script `${workspaceFolder}/tmp.py` which imports and calls `foo` from `my_package`.

(So far everything behaves as expected)

- Modify `my_package` somehow:
e.g. change the name of foo, its call signature or its return type

pyright does not flag any errors in `tmp.py` despite its now incorrect usage of `my_package`.

- Restart the pyright language server: `Pyright: Restart Server`.

Now as expected the call to `foo` in `tmp.py` has the appropriate red squiggles (highlighting that the use of `foo` is no longer consistent with the definition).

**Expected behavior**
The red squiggles appear soon after the change is made to the package (i.e. without needing a restart of the language server).

**VS Code extension or command-line**

I am running on windows within VS Code.

**Additional context**

Please let me know what additional information would be helpful.  For now I am working around the problem by mapping `Pyright: Restart Server` to a keyboard shortcut.

**Comment by erictraut** [comment]
Thanks for the bug report. Pyright has code to track changes to installed libraries, but this code is conditionally enabled. It is enabled in Pylance builds, but it was unintentionally disabled for Pyright builds. I've re-enabled it, and the change will be in the next release of Pyright.

**Comment by erictraut** [comment]
This is now addressed in version 1.1.63 of Pyright, which I just published.
