### ISSUE TITLE
Don't require a network connection to run the pyright CLI

### ISSUE THREAD

**Issue by brt-adam-snaider** [microsoft/pyright#9373]
Running `pyright` starts by checking for new versions which requires an active network connection and will block if it can't do this. I would like there to be a flag like `--no-network` or `--no-version-check` that avoids this and enables running `pyright` without an internet connection.

**Comment by erictraut** [comment]
Pyright doesn't require a network connection. I assume that you're using the community-maintained [Python wrapper for pyright](https://github.com/RobertCraigie/pyright-python), which installs pyright and performs version checks. If you'd like to suggest enhancements to this tool, please file an enhancement request in that project.
