### ISSUE TITLE
`reportMissingImports` with secondary editable install

### ISSUE THREAD

**Issue by ringohoffman** [microsoft/pyright#9374]
**Is your feature request related to a problem? Please describe.**

I have 2 repos. `repo2` depends on `repo1`.

```
.
├── repo1
│   └─── ...
└── repo2
    └─── ...
```

When I am developing each repo, they are installed via editable install. When I am developing `repo2`, `repo1` is usually installed as a normal site-package. Sometimes though, when I want to develop a feature in `repo1` for use in `repo2`, I will `cd ../repo1` and perform an editable install of `repo1` in `repo2`'s environment. Or equivalently, I could do `pip install -e ../repo1`. Now I can develop them in tandem!

My problem is that `pyright` doesn't seem to realize that I have performed an editable install of `repo1` when I do this.

```console
$ pyright my_repo2_file.py
my_repo2_file.py:30:8 - error: Import "repo1" could not be resolved (reportMissingImports)
```

**Describe the solution you’d like**

To be clear, the code executes perfectly fine. `repo1` is resolvable by `python`, and I expect `pyright` to resolve it just the same.

When I check:

```python
>>> import importlib.metadata
>>> importlib.metadata.Distribution.from_name("repo1").read_text("direct_url.json")
'{"url":"file:///home/matthew/repo1","dir_info":{"editable":true}}'
```

I can tell that `repo1` is installed editably from a local path. Can `pyright` leverage this or something like it to better detect secondary editable installs?

**Comment by erictraut** [comment]
Refer to [this documentation](https://microsoft.github.io/pyright/#/import-resolution?id=editable-installs) for details about editable installs and static analysis tools.
