### ISSUE TITLE
Empty `__slots__` deactivates the error reporting

### ISSUE THREAD

**Issue by mosauter** [microsoft/pyright#9387]
**Describe the bug**
Setting `__slots__` to an empty `Iterable` deactivates any property assignments. If you assign a new property anyway `pyright` should report that as `reportGeneralTypeIssues` as it does if the slots are assigned to an empty string or assigned to a "filled" iterable.

**Code or Screenshots**
Code sample in [pyright playground](https://pyright-play.net/?strict=true&deprecateTypingAliases=true&enableExperimentalFeatures=true&reportCallInDefaultInitializer=true&reportImplicitStringConcatenation=true&reportImplicitOverride=true&reportMissingSuperCall=true&reportPropertyTypeMismatch=true&reportShadowedImports=true&reportUnnecessaryTypeIgnoreComment=true&reportUninitializedInstanceVariable=true&reportUnusedCallResult=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMrCoCGANgLABQlAAoSqZQMYlEDOrUAggFyVT9QA%2BoNYkwMVsKgBeKACI5fAQBMApsCGDUSGFIAUrVSWAAaKEW6YUMAJRQAtAD4oAOTApVvCgJ9RDxgDoiGXMoAGIoBDgQJDQAC3wQVRw8DiSUmABxVQ8QUgAVRFUASXYAV1VWSho6BgpmNg4AIS8fYVFxSUEQvTkAIzkTGyV%2BNQ1hbV1ugyNTc0tUWwdnNw9W335-YCCQ4IiomPjE5NwJKHTT7NyCotLWCqqqClpicnqWdigAYXX%2BdrEJFJZHpht4VOpNJN9FszBYrEsnK53J4Rr4tjtZHs-HEwGUSMpzCRWGBIuBlGVGKpzCgoKoQOAQGY%2BmV8MowJUUAByGConw1V5MD4cAAiv00HUB3VkAG0ALqosaQlA6aGzWELax2RGrFFgjbo4KY8LY3H4wnE0lgcmU6m0%2Bm4JksqBsjncoA)

```python
from typing import final

@final
class A:
    __slots__ = ""
    def __init__ (self, a: int) -> None:
        self.a = a # pyright reports reportGeneralTypeIssues

@final
class B:
    __slots__ = ("b",)
    def __init__ (self, a: int) -> None:
        self.a = a # pyright reports reportGeneralTypeIssues

@final
class C:
    __slots__ = ()
    def __init__ (self, a: int) -> None:
        self.a = a # should also produce an error, but doesn't
        
@final
class D:
    __slots__ = []
    def __init__ (self, a: int) -> None:
        self.a = a # should also produce an error, but doesn't
```

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.388.
