### ISSUE TITLE
Negative TypeGuard with Union applied to Union type does not narrow down the type

### ISSUE THREAD

**Issue by samvv** [microsoft/pyright#9388]
**Describe the bug**

When doing `TypeGuard[Foo | Bar]` and applying `Foo | Bar | Baz` to it in such a way that the `TypeGuard` must be negative, nothing happens, and the original type `Foo | Bar | Baz` remains present.

**Context**

I'm writing a compile pass for [Mage](https://github.com/samvv/mage) and I want to assert some types of a big union type have been filtered out by previous passes.

**Code or Screenshots**

```python
from dataclasses import dataclass
from typing import TypeGuard, assert_never

@dataclass
class Foo:
    pass

@dataclass
class Bar:
    pass

@dataclass
class Bax:
    pass

type Special = Foo | Bar

type Value = Foo | Bar | Bax

def is_foobar(value: Value) -> TypeGuard[Special]:
    return isinstance(value, Foo) or isinstance(value, Bar)

def test(value: Value):
    assert(not is_foobar(value))
    if isinstance(value, Bax):
        return
    assert_never(value)
```

**VS Code extension or command-line**

Pyright with Neovim

**Comment by erictraut** [comment]
Pyright is working correctly here. `TypeGuard` is specified not to narrow in the negative ("else") case. See [this part of the typing spec](https://typing.readthedocs.io/en/latest/spec/narrowing.html#typeguard) for details. The relevant part of the spec is "User-defined type guards apply narrowing only in the positive case (the if clause). The type is not narrowed in the negative case."

The newer [`TypeIs`](https://typing.readthedocs.io/en/latest/spec/narrowing.html#typeis) facility supports type narrowing in the negative case, but it is also more limited. It should work fine for your use case.
