### ISSUE TITLE
Class definition for D depends on itself - unable to figure out types

### ISSUE THREAD

**Issue by ljw1004** [microsoft/pyright#9391]
Pyright gets "Unknown" for the return-type of f, but Mypy and Pyre get "D.A".
```
from __future__ import annotations
from typing import Generic, Type, TypeVar
from abc import ABC

T = TypeVar("T")

class C(Generic[T], ABC):
    A: Type[T]

class D(C["D.A"]): # "class definition for D depends on itself" (pyright), no error (pyre, mypy)
    class A:
        pass

def f(_: Type[C[T]]) -> T: ...

x = f(D)
reveal_type(x)  # Unknown (pyright), D.A (pyre, mypy)
```
Playgrounds: [pyright](https://pyright-play.net/?code=GYJw9gtgBA%2BjwFcAuCQFM5QJYQA5hCSgEMA7UsJYpLMUgZwChRIokBPXLUgc2zwJEA4mlJoQWAMYAaKABVOaWQtxoAasRDNw0YgCNJ-fISgBBAEIBhRozlQAvPMUaQACgBEc9wEobkgDbE9PRQlq4iYhKSANpyALqyFpbeAFyMUBlmKU6qsXF%2BgcFQACKultHuxQB0pu5xqVAAxFDuAUEhACZowNxYNHRQwAQlUF2qpB0hA330aP7A7lCuuOwSPAAWSN6yFFDi4CBLK%2BiyEJzsvplQbUWmaVdXuO02XcCDrjDZKmjR5fH1UAAtAA%2BeTZKoQmwADwc72KvnQADc0MR-DAOKpXFDvBlmgBVUgAawoAHdSEdVlgNltZNVTBSTlAzitfEA), [mypy](https://mypy-play.net/?mypy=latest&python=3.12&gist=b3e7127f515337e60a7533ba997727d7), [pyre](https://pyre-check.org/play?input=from%20__future__%20import%20annotations%0Afrom%20typing%20import%20Generic%2C%20Type%2C%20TypeVar%0Afrom%20abc%20import%20ABC%0A%0AT%20%3D%20TypeVar(%22T%22)%0A%0Aclass%20C(Generic%5BT%5D%2C%20ABC)%3A%0A%20%20%20%20A%3A%20Type%5BT%5D%0A%0Aclass%20D(C%5B%22D.A%22%5D)%3A%20%23%20%22class%20definition%20for%20D%20depends%20on%20itself%22%20(pyright)%2C%20no%20error%20(pyre%2C%20mypy)%0A%20%20%20%20class%20A%3A%0A%20%20%20%20%20%20%20%20pass%0A%0Adef%20f(_%3A%20Type%5BC%5BT%5D%5D)%20-%3E%20T%3A%20...%0A%0Ax%20%3D%20f(D)%0Areveal_type(x)%20%20%23%20Unknown%20(pyright)%2C%20D.A%20(pyre%2C%20mypy)%0A)

I also see https://github.com/microsoft/pyright/issues/4518 "Class definition for "MyClass" depends on itself", but the repros there were non-deterministic and it seemed to be related to evaluation order. That issue was closed because of no clear repro.

I also see https://microsoft.github.io/pyright/#/mypy-comparison?id=circular-references "Because mypy is a multi-pass analyzer, it is able to deal with certain forms of circular references that pyright cannot handle." I don't know if this is an additional case of circularity that pyright can't handle?

My hope is that even if there's a type error in the declaration of `D`, I'd hope that the return type of `f` should still be solvable by pyright, so that hover and go-to-def on `x.foo()` will succeed. In other words some way to still retain useful information about `D` even in the presence of a type error, maybe even one that we suppress.

(The code in this bug is a minimal repro of an idiom that's widely used in generated code at my company).

**Comment by erictraut** [comment]
This is a form of circular reference that pyright doesn't (and is unlikely to ever) support. Sorry.

**Comment by ljw1004** [comment]
> I'll note that mypy has not yet implemented support for class decorators. It completely ignores them.

I think that might actually be the best choice *for the sake of codenav* (gotodef, hover). What I've observed: (1) there are few typesafe ways to annotate a decorator correctly which changes function signature, and I haven't seen any to add methods to a class. (2) Users usually get decorators wrong. (3) If we ignored decorators entirely, then Go-to-def and Hover would more often give the user what they wanted, i.e. reflecting the eventual runtime behavior of their program.

Here, I picked a random example of a decorator that you wrote https://github.com/microsoft/pyright/issues/774#issuecomment-755769085
```
#!/usr/bin/python3

from typing import Callable, TypeVar
from typing_extensions import ParamSpec

_P = ParamSpec("_P")
_R = TypeVar("_R")


def decorator(f: Callable[_P, _R]) -> Callable[_P, _R]:
    def wrapper(*args: _P.args, **kwargs: _P.kwargs):
        print("wrapper", *args, **kwargs)
        return f(*args, **kwargs)
    return wrapper
    
@decorator
def foo(x1:int, y1:str) -> str:
    return str(x1) + y1

@mistyped_decorator
def bar(x2:int, y2:str) -> str:
    return str(x2) + y2

print(foo(x1=1, y1=""))
print(bar(x2=1, y2=""))
```
If you cmd+click on the named arguments "x1" or "y1" then pyright doesn't find a definition; if you cmd+click on the named arguments "x2" or "y2" then it does.

So for cases where users get decorators right (like this one), and where they get them wrong, codenav would be better served by assuming the decorator doesn't exist.
