### ISSUE TITLE
False negative about union types being instantiable with python version < 3.10

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pyright#9407]
**Describe the bug**

Union types are treated as instantiable when `pythonVersion` is set below 3.10 in Pyright config.

**Code or Screenshots**

[Playground](https://pyright-play.net/?pythonVersion=3.9&strict=true&locale=en-us&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCqKSYKAUGQGIA2YAhvgLyHGkDawtDANJijAF0yADyjMa9GAAoADAEoyQA)

```python
from typing import Union

Float = Union[float, int]
x = Float(0)  # Obviously this line will cause crash in runtime.
```

**VS Code extension or command-line**

As far as I can tell, this issue seems to be introduced in v1.1.346 and remains till now (v1.1.388).

**Comment by erictraut** [comment]
The `UnionType` type was defined in typeshed only starting in 3.10. Pyright falls back on `Unknown` prior to that, so it doesn't know which operations are and are not allowed on a `UnionType` instance with older versions.

This could theoretically be addressed by adding a bunch of special-cased logic, but I don't think it's worth it here. This affects only older versions of python, results only in a false negative, and affects only those who are using `UnionType` as a runtime object, which is pretty atypical. I'm therefore closing this as "won't fix".
