### ISSUE TITLE
narrowing to [Base]ExceptionGroup should make use of typevar defaults

### ISSUE THREAD

**Issue by jakkdl** [microsoft/pyright#9408]
Currently these two cases are handled differently with the latter failing, but as far as I can tell they could be handled identically

```python
from typing_extensions import assert_type

try:
    ...
except ExceptionGroup as e:
    assert_type(e, ExceptionGroup[Exception])

try:
    ...
except Exception as e:
    if isinstance(e, ExceptionGroup):
        assert_type(e, ExceptionGroup[Exception]) # error: inferred as ExceptionGroup[unknown]
```

Running pyright gives the following:
```sh
$ pyright foo.py
/tmp/except_group_improvements/foo.py
  /tmp/except_group_improvements/foo.py:38:21 - error: "assert_type" mismatch: expected "ExceptionGroup[Exception]" but received "ExceptionGroup[Unknown]" (reportAssertTypeFailure)
1 error, 0 warnings, 0 informations 
```

version info: 1.1.388

I have not tried other constructs from typeshed (or by the user) that makes use of typevar defaults, but I suspect they might also fail?
The defaults for [Base]ExceptionGroup in typeshed was added in https://github.com/python/typeshed/pull/12258

**Comment by jakkdl** [comment]
maybe this is larger-scoped than just pyright and should be added to the typing spec. Mypy also does not handle it.

minimal repro not relying on typeshed:
```python
from typing import Generic, TypeVar
from typing_extensions import reveal_type

# adding `bound=Exception` makes no difference, but should maybe be required?
T = TypeVar("T", default=Exception)

class MyClass(Generic[T]):
    ...

def blah(mc: object):
    if isinstance(mc, MyClass):
        # type is MyClass[Unknown]
        reveal_type(mc)
```

**Comment by erictraut** [comment]
Pyright is working as intended here. A type checker cannot assume the TypeVar's default in this case. Doing so would be unsound. It's possible that the actual runtime value is not compatible with the default value.

**Comment by erictraut** [comment]
> it should be bound or any type constraints on the type.

That doesn't work either. Consider a class that has a single invariant type variable with an upper bound. (Note that all TypeVars have an upper bound of `object` if no explicit upper bound is provided.) If a type checker's `isinstance` narrowing logic were to assume the upper bound as the type argument, this would result in an incorrect narrowed type. `Unknown` is the only valid answer in this circumstance.

**Comment by jakkdl** [comment]
Ahh, I think this is simply a UX problem. AFAICT there's no typing error, but the guy that reported this to me interpreted `ExceptionGroup[Unknown]` as "we have no information" - but once I actually start trying to do anything with the type then everything* gets resolved correctly (in pyright, but not mypy, which was part of my confusion).

Perhaps it would be good if `reveal_type` told the user `ExceptionGroup[Exception]` when there is a bound (and some specific variance? idk that still confuses me), but maybe that would introduce confusion in the other direction? Maybe something like `ExceptionGroup[Unknown[Exception]]`???


*this should maybe say `Never`?
```python
from typing_extensions import reveal_type

try:
    ...
except Exception as e:
    if isinstance(e, ExceptionGroup):
        for subexc in e.exceptions:
            if isinstance(subexc, Exception):
                ...
            else:
                reveal_type(subexc) # type is unknown
```
