### ISSUE TITLE
pyrightconfig.json is ignored when files are provided on the command line

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#942]
Specifying files on the command line eg: `pyright app/*` will cause pyright to ignore *pyrightconfig.json*. I was expecting *pyrightconfig.json* would still be used.

pyright 1.1.62

**Comment by erictraut** [comment]
This is by design. If you want to check just a few files with default settings, you can specify them at the command line. If you want to check an entire project, you can create a pyrightconfig.json and specify which files to include/exclude.

**Comment by tekumara** [comment]
Perhaps this could be in the doco, if it isn't already? I had a quick look in [command-line.md](https://github.com/microsoft/pyright/blob/master/docs/command-line.md) couldn't find anything mentioning this.

**Comment by erictraut** [comment]
Yeah, that's a good point. It's not well documented currently. I'll update the docs accordingly. Thanks for the suggestion.

**Comment by tekumara** [comment]
It looks like this behaviour has been changed in [pyright 1.1.71](https://github.com/microsoft/pyright/releases/tag/1.1.71):

> Behavior Change: Changed the behavior of the command-line version of pyright when file specs are passed on the command line. Previously, file specs couldn't be used in conjunction with a config file. Now a config file is used, but the specified file specs override the "include" section of the config file.
