### ISSUE TITLE
Unable to find import from namespace package (logs shows it's found but not used??)

### ISSUE THREAD

**Issue by ashb** [microsoft/pyright#9439]
Pyright is unable to find some of the imports in apache/airflow since we've moved some of our code to a secondary namespace package.

**Describe the bug**

Pyright is unable to find 

**Code or Screenshots**

If you have uv, then `uv sync`, otherwise  `python -m venv .venv && . ./.venv/bin/activate && pip install -e . -e task_sdk`

Sorry, this isn't as minimal as I would like.

```
git clone git@github.com:apache/airflow.git airflow-pyright-test
cd airflow-pyright-test/
git reset --hard ff6038b8d1 # Just for predictability, to go a known sha that exhibits the issue
pyright --pythonpath $PWD/.venv/bin/python airflow/models/dag.py --verbose | grep -A45 "Could not import 'airflow.sdk'"
```

(There will be lots of other type warnings on those file, some related to this, others because the project doesn't use pyright yet.)

Of note here is likely the split namepsace package layout:

```
airflow/
  - __init__.py
task_sdk/
  - src/
    - airflow/
      - sdk/
        - __init__.py
        - py.typed
```

**VS Code extension or command-line**
command line, v 1.1.388

snippets of `--verbose` output:

```
Could not import 'airflow.sdk' in file '/Users/ash/code/tmp/airflow-pyright-test/airflow/utils/task_group.py'
  Looking in stubPath 'file:///Users/ash/code/tmp/airflow-pyright-test/typings'
  Attempting to resolve stub package using root path 'file:///Users/ash/code/tmp/airflow-pyright-test/typings'
  Attempting to resolve using root path 'file:///Users/ash/code/tmp/airflow-pyright-test/typings'
  Looking in root directory of execution environment 'file:///Users/ash/code/tmp/airflow-pyright-test'
  Attempting to resolve stub package using root path 'file:///Users/ash/code/tmp/airflow-pyright-test'
  Attempting to resolve using root path 'file:///Users/ash/code/tmp/airflow-pyright-test'
  Resolved import with file 'file:///Users/ash/code/tmp/airflow-pyright-test/airflow/__init__.py'
  Looking for typeshed stdlib path
  Looking for typeshed stdlib path
  Attempting to resolve using root path 'file:///Users/ash/code/tmp/airflow-pyright-test/node_modules/pyright/dist/typeshed-fallback/stdlib'
  Typeshed path not found
  Finding python search paths
  Executing interpreter: '/Users/ash/code/tmp/airflow-pyright-test/.venv/bin/python'
  Skipping '/Users/ash/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python312.zip' because it is not a valid directory
  Received 5 paths from interpreter
    file:///Users/ash/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12
    file:///Users/ash/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/lib-dynload
    file:///Users/ash/code/tmp/airflow-pyright-test/.venv/lib/python3.12/site-packages
    file:///Users/ash/code/tmp/airflow-pyright-test
    file:///Users/ash/code/tmp/airflow-pyright-test/task_sdk/src
  Looking in python search path 'file:///Users/ash/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12'
  Attempting to resolve stub package using root path 'file:///Users/ash/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12'
  Attempting to resolve using root path 'file:///Users/ash/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12'
  Looking in python search path 'file:///Users/ash/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/lib-dynload'
  Attempting to resolve stub package using root path 'file:///Users/ash/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/lib-dynload'
  Attempting to resolve using root path 'file:///Users/ash/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/lib-dynload'
  Looking in python search path 'file:///Users/ash/code/tmp/airflow-pyright-test/.venv/lib/python3.12/site-packages'
  Attempting to resolve stub package using root path 'file:///Users/ash/code/tmp/airflow-pyright-test/.venv/lib/python3.12/site-packages'
  Attempting to resolve using root path 'file:///Users/ash/code/tmp/airflow-pyright-test/.venv/lib/python3.12/site-packages'
  Looking in python search path 'file:///Users/ash/code/tmp/airflow-pyright-test'
  Attempting to resolve stub package using root path 'file:///Users/ash/code/tmp/airflow-pyright-test'
  Attempting to resolve using root path 'file:///Users/ash/code/tmp/airflow-pyright-test'
  Resolved import with file 'file:///Users/ash/code/tmp/airflow-pyright-test/airflow/__init__.py'
  Looking in python search path 'file:///Users/ash/code/tmp/airflow-pyright-test/task_sdk/src'
  Attempting to resolve stub package using root path 'file:///Users/ash/code/tmp/airflow-pyright-test/task_sdk/src'
  Attempting to resolve using root path 'file:///Users/ash/code/tmp/airflow-pyright-test/task_sdk/src'
  Resolved import with file 'file:///Users/ash/code/tmp/airflow-pyright-test/task_sdk/src/airflow/sdk/__init__.py'
  Looking for typeshed third-party path
  Looking for typeshed stubs path
  Typeshed path not found
```

Of particular note to me is the `Resolved import with file 'file:///Users/ash/code/tmp/airflow-pyright-test/task_sdk/src/airflow/sdk/__init__.py'
` line -- that file does exist, but it's not clear to me why Pyright is not using that import.

**Comment by erictraut** [comment]
There are two `airstream` packages here, but only one of them is a namespace package. The other has an `__init__.py` file, so it's not a namespace package, and it takes precedence when resolving imports. Pyright mirrors the behavior of the Python import loader, which always prefers traditional (non-namespace) packages over namespace packages. The logging that you see indicates that pyright is able to resolve to the namespace package, but it continues its search for a traditional package, and it finds one.

I'm able to make it work by adding a pyrightconfig.json file with the following contents:

```json
{
    "extraPaths": ["task_sdk/src"]
}
```

And by deleting the top-level `__init__.py` file (or alternatively adding an empty `task_sdk/src/airflow/sdk/__init__.py` file).

Pyright is working correctly here, so I'm going to close the issue.

**Comment by ashb** [comment]
https://github.com/apache/airflow/blob/ff6038b8d1/task_sdk/src/airflow/sdk/__init__.py already exists.

> the behavior of the Python import loader, which always prefers traditional (non-namespace) packages over namespace package

That is simply not true - Python quite happily loads the airflow.sdk package as evidenced by our tests.

**Comment by ashb** [comment]
`{ "extraPaths": ["task_sdk/src"] }` makes no difference, it's deleting of the `airflow/__init__.py` that is required.

So essentially the answer is "sucks to be you, you have to break compatibility with your users and remove this file if you want to use pyright". Which is no option at all.

**Comment by erictraut** [comment]
You're correct that this file already exists. I meant `task_sdk/src/airflow/__init__.py`.

**Comment by ashb** [comment]
Since removing the code isn't an option for me (not on any short term time-scale anyway! I would like to do it, but I care more about not breaking our users' workflows) would it be possible to have a config option to explicitly force something as a namespace package? Ruff has the [namespace-packages](https://docs.astral.sh/ruff/settings/#namespace-packages) config option for example.

**Comment by erictraut** [comment]
Are you able to add the file that I mentioned above? Does that address your use case?

It's unlikely that we'd add a config option to force something as a namespace package. I'd need to get significant signal from other pyright users that this would be useful before seriously considering it. No one has requested such a feature previously.

**Comment by ashb** [comment]
Oh `task_sdk/src/airflow/__init__.py` -- yeah we could add that (we already had to do it for pycharm)  - let me test it.

**Comment by ashb** [comment]
Yes that works. I don't love it, but it works and I understand not wanting to have an extra config option.

Curiously enough Pycharm is fine here, but it needed a `providers/src/airflow/providers/__init__.py` but was fine without `providers/src/airflow/` (I'm leave this note for anyone else stumbling across this in the future.)

**Comment by vnmabus** [comment]
> It's unlikely that we'd add a config option to force something as a namespace package. I'd need to get significant signal from other pyright users that this would be useful before seriously considering it. No one has requested such a feature previously.

@erictraut Please, consider this comment as an increase in the signal 😅. It would be a very useful option for the poor guys that have to deal with legacy code that uses explicit namespaces.

**Comment by vnmabus** [comment]
For these poor guys, I think I found some workaround: if you create the namespace folder inside the configuration's `stubPath` with just an empty `__init__.py` inside, it seems to work and it redirects correctly to all the subfolders of the namespace package, belonging to different "real" packages.

@erictraut I have no idea of why this works. It would be good to know (and please, if this is a bug *do not* change it). If this is legit, maybe it would be good to put a note in the docs somewhere, so that when you are asked again about legacy namespace packages support, you can point them to the workaround.

**Comment by wesleybl** [comment]
@erictraut I'm +1 for this:

https://github.com/microsoft/pyright/issues/9439#issuecomment-2468964618

See: https://github.com/microsoft/pylance-release/issues/7618
