### ISSUE TITLE
Ignore specific libraries when useLibraryCodeForTypes = true

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#945]
Enabling `"useLibraryCodeForTypes": true` will cause pyright to use/infer type information from `.py` files.

This can be helpful for third-party libraries that lack stubs. In general `"useLibraryCodeForTypes": true` is useful, and is the default for Pylance.

However, the precision and completeness of inferred types varies between third-party libraries that lack stubs. For example, pytoml uses context managers and exceptions to control flow, and so inferred signatures have the return type `NoReturn`. Ideally pytoml would have stubs with the correct return types. Given it doesn't, the options are to disable `useLibraryCodeForTypes` (and lose its benefits for other libraries) or add `# type: ignore` everywhere its functions are used.
 
There are other libraries that have similar problems. Given the lack of stubs, and the varying quality of inference across libraries, would it be possible instead to selectively ignore specific libraries? Then `useLibraryCodeForTypes` and its benefits could still be had for most libraries.

**Comment by erictraut** [comment]
My recommendation is that if you are using Pylance/Pyright for type checking, `useLibraryCodeForTypes` should be disabled. It was added primarily for users who are uninterested in type checking but are interested in completion suggestions and other language convenience features.

**Comment by erictraut** [comment]
I'm going to leave this request open for now but mark it "blocked". It relates to some discussions we're having about support for type annotations within library "py" files, and I need to wait for those discussions to conclude before recommending a solution to the problem you've described. 

We're unlikely to implement the feature that you have described here, but there are other ways we could address the problem.

**Comment by erictraut** [comment]
Please refer to #1003. I'm going to close this issue in favor of that one.

**Comment by turtlebasket** [comment]
> You can define a local stub file for the libraries whose types you don't want to be used. Create a "typings" or "stubs" folder within your project. For each package you want to exclude from "useLibraryCodeForTypes", create a subfolder with the name of the package, add a `__init__.pyi` file, and add the following line to that file:
> 
> ```
> def __getattr__(name) -> Any: ...
> ```
> 
> Pyright will then use the stub instead of the library code, and it will treat all symbols in that module as "Any" for the purpose of type checking.

This breaks coloring on imports from the `sqlalchemy` root module in VSCode.

Before (no custom `typings/sqlalchemy/__init__.py`):

<img width="538" alt="Screenshot 2023-11-08 at 6 23 52 PM" src="https://github.com/microsoft/pyright/assets/32886427/dea8152f-2d21-4b19-a55f-29480d76de26">

After (custom `typings/sqlalchemy/__init__.py`):

<img width="571" alt="Screenshot 2023-11-08 at 6 20 25 PM" src="https://github.com/microsoft/pyright/assets/32886427/a5b38c90-5b47-4d39-ac5e-7d36442fed51">

This fix does get rid of other (most?) error detection issues with pyright, but it is a pretty annoying tradeoff to have to make. Might just go with [sqlalchemy-stubs](https://github.com/dropbox/sqlalchemy-stubs) and make the jump to mypy for now :\
