### ISSUE TITLE
Type "str" cannot be assigned to type "str | None"

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#946]
```python
from typing import List, Optional

a = list(["a", "b", "c"])
aopt1: List[Optional[str]] = list(["a", "b", "c"])

aopt2: List[Optional[str]] = a
```

pyright 1.1.62 reports a type error on `aopt2`:
```
  6:30 - error: Expression of type "list[str]" cannot be assigned to declared type "List[str | None]"
  TypeVar "_T" is invariant
    Type "str" cannot be assigned to type "str | None" (reportGeneralTypeIssues)
```

I wasn't expecting this because `aopt1` is equivalent and doesn't have the type error

**Comment by erictraut** [comment]
This is the intended behavior. 

See [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#list-expressions) for details about list type inference. And see [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#generic-types) for an explanation for why `List[str]` is not assignable to `List[Optional[str]]`.

**Comment by tekumara** [comment]
Thanks for pointing me to the doco. I guess this is same reason this errors:
```
b: Optional[List[str]] = list(["a", "b", "c"])
bopt: List[Optional[str]] = list() if b is None else list(b)
```

but this doesn't error:

```
b: Optional[List[str]] = list(["a", "b", "c"])
if b is None:
    bopt: List[Optional[str]] = list()
else:
    bopt: List[Optional[str]] = list(b)
```
Although they are equivalent?

**Comment by erictraut** [comment]
The bidirectional type inference logic doesn't currently support ternary expressions (i.e. "x if y else z"), but it's trivial to add that support. This will be supported in the next version.
