### ISSUE TITLE
Support django special methods

### ISSUE THREAD

**Issue by last-partizan** [microsoft/pyright#947]
Django adds several special methods to models, like get_FOO_display for choice fields. But pyright doesn't seems to pick's it up.

django-stubs includes mypy_django_plugin: https://github.com/typeddjango/django-stubs/blob/665f4d8ea1723d0bcae59904a590ffb03a7c0355/mypy_django_plugin/transformers/models.py#L301 which adds these methods, and a few other.

What is the proper way to add this to pyright?

**Comment by erictraut** [comment]
Django has dynamic behaviors that cannot be described using standard Python static type annotations. We've talked about possibly adding support for plug-ins so knowledge of non-standard or dynamic behavior could be added. Creating a good plug-in interface is not easy, and it will limit the evolution of Pyright. We don't plan to add this until Pyright is a little more mature.
