### ISSUE TITLE
allow use of `+=` manipulation on `__all__` when `__all__` is a tuple

### ISSUE THREAD

**Issue by tungol** [microsoft/pyright#9479]
If you have a question about a behavior that you’re seeing in pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**
I was attempting to add `asyncio.__all__` to typeshed. There's a lot of differences depending on python version, but pyright complains for each instance of `__all__ += ("foo",)`. See: https://github.com/python/typeshed/pull/13038

**Describe the solution you’d like**
Pyright supports this if `__all__` is a list instead of a tuple. Is it possible to support this for tuple as well?

**Comment by erictraut** [comment]
Pyright [conforms to the typing specification](https://typing.readthedocs.io/en/latest/spec/distributing.html#library-interface-public-and-private-symbols) with regard to the `__all__` idioms that it accepts. If you think that the spec should be extended to support more idioms, you can make your argument in the [typing forum](https://discuss.python.org/c/typing/32), but I think it's unlikely that additional extensions will be made. Each additional idiom requires support from a wide breadth of tools in the Python ecosystem, so the bar is high for adding new ones. I recommend that you use one of the existing supported idioms.
