### ISSUE TITLE
Pyright doesn't full analyise flasks "abort()" when inside a function

### ISSUE THREAD

**Issue by TimmBmn** [microsoft/pyright#9483]
### The bug
I am currently writing a Flask application and when i encounter an error i use this snippet so i instantly escape any code from within any function:
```python
abort(make_response({"error": message}, 404))
```

 I've now i wanted to move them to a separate file in wrapper functions so that i can have custom messages and status codes.
Now i have encounter this bug where Flask doesn't realize that my wrapper function causes the code to stop executing which can result in it showing errors that are not there.

### Minimal Setup:
```python
from flask import Flask, abort

app = Flask(__name__)

def function_that_causes_404():
    abort(404)

@app.route("/pyrightbug")
def index():
    function_that_causes_404()
    return "Hello World" # it should say "Type analysis indicates code is unreachable" (see screenshot)

if __name__ == "__main__":
    app.run()
```

### Whats happening:
![Image](https://github.com/user-attachments/assets/d5f8f291-8216-48d1-bf02-1b1b5709f1dd)

### #What should happen:
![Image](https://github.com/user-attachments/assets/18bf2bf0-dc3e-4cc7-8405-f83769175e9c)

### How i stumbled upon this bug:
(because Pyright doesn't understand that errors.no_JSON_provided() calls abort() it keeps analyzing where it shouldn't
![Image](https://github.com/user-attachments/assets/5d0965a8-6a41-426c-a8e9-e7b2329268c5)

### Pyright version and environment
I am running Pyright version 1.1.389 inside of Neovim (my config can be found under https://github.com//TimmBmn/nvim-config)

**Comment by erictraut** [comment]
If you want `function_that_causes_404` to act like `abort`, you need to provide an explicit return type of `NoReturn`.

```python
def function_that_causes_404() -> NoReturn:
    abort(404)
```
