### ISSUE TITLE
Config file could not be parsed since version 1.1.389.

### ISSUE THREAD

**Issue by yclybouw** [microsoft/pyright#9486]
**Describe the bug**
Since version 1.1.389 (which introduces a new toml parser), I have:

```bash
% pyright
Loading pyproject.toml file at /Users/myuser/path/to/project/pyproject.toml
Pyproject file parse attempt 1 error: {}
Pyproject file parse attempt 2 error: {}
Pyproject file parse attempt 3 error: {}
Pyproject file parse attempt 4 error: {}
Pyproject file parse attempt 5 error: {}
Pyproject file parse attempt 6 error: {}
Config file "/Users/myuser/path/to/project/pyproject.toml" could not be parsed. Verify that format is correct.
```

When reducing my `pyproject.toml` file to only this:
```toml
[tool.pyright]
typeCheckingMode = "basic"
```
the issue remains.

Adding `--verbose` does not show extra relevant info. It starts with the error message above and proceeds as there was not config file.

Extra info:
- It works on 1.1.388
- I use the python wrapper (`pip install pyright`) on the same version as pyright
- I don't have a `pyrightconfig.json`
- The `pyproject.toml` is in the root of my project and I run `pyright` from there.
- The line endings of the toml file are unix style.

**Comment by yclybouw** [comment]
Let me know if I can provide any more information or if I can enable some debug.

**Comment by erictraut** [comment]
I'm not able to repro the problem from the steps above.

I wonder if there's an illegal (but invisible) character in your toml file? Could you try creating a new toml file from scratch and typing in the repro text above? When you say "unix style line endings", are you referring to "LF" (as opposed to CRLF commonly used on Windows)?

**Comment by yclybouw** [comment]
> I'm not able to repro the problem from the steps above.

My work colleagues cannot reproduce it, neither, so I'm really confused.

> I wonder if there's an illegal (but invisible) character in your toml file? Could you try creating a new toml file from scratch and typing in the repro text above?

I've deleted the toml file and created a new one and typed manually to avoid copy/pasting invalid chars. Still same issue.

> When you say "unix style line endings", are you referring to "LF" (as opposed to CRLF commonly used on Windows)?

Indeed.

Is there a way to know where in the parsing process this is failing?

**Comment by erictraut** [comment]
> Is there a way to know where in the parsing process this is failing?

Pyright uses a library to parse toml, and it doesn't provide diagnostics to specify where the parsing fails.

I'll need a set of repro steps to investigate further.

**Comment by michaelheiser-taxa** [comment]
I've had the same issue (1.386 is the last version that still works). Running this on WSL2:

```
mkdir /tmp/test
cd /tmp/test
uv init
uv add pyright
uv run pyright
```

Output:
```
❯ mkdir /tmp/test
cd /tmp/test
uv init
uv add pyright
uv run pyright
Initialized project `test`
Using CPython 3.12.7
Creating virtual environment at: .venv
Resolved 4 packages in 3ms
Installed 3 packages in 2ms
 + nodeenv==1.9.1
 + pyright==1.1.389
 + typing-extensions==4.12.2
Pyproject file parse attempt 1 error: {}
Pyproject file parse attempt 2 error: {}
Pyproject file parse attempt 3 error: {}
Pyproject file parse attempt 4 error: {}
Pyproject file parse attempt 5 error: {}
Pyproject file parse attempt 6 error: {}
Config file "/tmp/test/pyproject.toml" could not be parsed. Verify that format is correct.
0 errors, 0 warnings, 0 informations
```
comparison to 1.1.386
```
/tmp
❯ mkdir /tmp/test
cd /tmp/test
uv init
uv add "pyright<1.1.387"
uv run pyright
Initialized project `test`
Using CPython 3.12.7
Creating virtual environment at: .venv
Resolved 4 packages in 4ms
Installed 3 packages in 4ms
 + nodeenv==1.9.1
 + pyright==1.1.386
 + typing-extensions==4.12.2
WARNING: there is a new pyright version available (v1.1.386 -> v1.1.389).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`

0 errors, 0 warnings, 0 informations
```

**Comment by erictraut** [comment]
Here's a recent history that may help shed some light on what's going on:
* Pyright 1.1.386 switched to a newer version of the toml parsing library that was used in previous versions. This update was to address a bug in the older version.
* Pyright 1.1.387 switched to a different toml parsing library because the update to 1.1.386 contained a bug that affected other aspects of parsing.
* Pyright 1.1.389 switched to yet another toml parsing library because the previous one also contained a bug that affected other aspects of parsing.

I'll need a repro to investigate this further.

**Comment by yclybouw** [comment]
I found (by doing `ps` while running pyright) that the pip package of pyright used `~/.nvm/versions/node/v14.21.2/bin/node`. I deleted nvm and node and re-install pyright. It now uses its own node `~/.cache/pyright-python/nodeenv/bin/node`. Now it works.

**Comment by erictraut** [comment]
OK, thanks for the additional experimentation and resolution.

**Comment by michaelheiser-taxa** [comment]
Thanks @yclybouw ! Updating node did the trick here too.

Using nvm:
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
# after shell restart install latest version and set default
nvm install node 
nvm alias default node
```
