### ISSUE TITLE
"Partially unknown" message in for loop.

### ISSUE THREAD

**Issue by sindzicat** [microsoft/pyright#9496]
Hello!

When I type:

```python
arr1: list[int] = [1, 2, 3, 4, 5]
arr2: list[float] = [5/2, 3/2, 7/2]
el: int | float

for el in [*arr1, *arr2]:
    print(el)
```

I get an error message for `el` variable: 

```
Type of "el" is partially unknown
  Type of "el" is "Unknown | int | float"Pylance[reportUnknownVariableType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnknownVariableType)
(variable) el: Unknown | int | float
```

![Image](https://github.com/user-attachments/assets/76a7d50c-8203-41a6-ab41-ca227fbf62fc)

Then I changed my code slightly, replaced `[*arr1, *arr2]` with `arr1 + arr2`. The error message gone. Modified code, that works:

```python
arr1: list[int] = [1, 2, 3, 4, 5]
arr2: list[float] = [5/2, 3/2, 7/2]
el: int | float

for el in arr1 + arr2:
    print(el)
```

```
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.17763
```

```
Name: Pylance
Id: ms-python.vscode-pylance
Description: A performant, feature-rich language server for Python in VS Code
Version: 2024.11.101
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance
```

It seems to me, I found a bug.

**Comment by erictraut** [comment]
I'm not able to repro the problem. Here it is in [pyright playground](https://pyright-play.net/?code=MQAgDgngTglg5gCwC4C4QGcmwMZIFB4CGUUAjGgDYyYDaMAdkgLogC8INpANCAEw8BmHgBYeAViZESvStSQ0AZhQD2hZmw5iQAej6CdekAHYDvSQFMKaBkhAAfEEtX48C5VBCWQDDgCpiZDz%2B0kwoeCAR4LCMABSWAJR4QA).

Could you confirm that you're able to repro the problem with a new project and a new source file with only the contents of the code above?

**Comment by sindzicat** [comment]
@erictraut, I used pre-reliase version of Pylance. I switched back to production version of Pylance, but I steel see this error.

I see that pyright works correctly in playground.

How can I check, what pyright version is used in Pylance? Thanks!

**Comment by Azureblade3808** [comment]
The key seems to be `strictListInference=false`.

![Image](https://github.com/user-attachments/assets/8f75ed84-16b2-476d-8c65-062121641c0c)

**Comment by erictraut** [comment]
If you enable strict mode but disable `strictListInference`, you will see this error. This is expected, so it's not a bug. Refer to the [pyright documentation](https://microsoft.github.io/pyright/#/type-inference?id=list-expressions) for more details.
