### ISSUE TITLE
Pandas filter inferred as Series instead of DataFrame

### ISSUE THREAD

**Issue by oyarsa** [microsoft/pyright#950]
**Describe the bug**
Output of filtering a pandas DataFrame (like `df[df.col == x]`), when it is fact another DataFrame.

**To Reproduce**
```python
df1: pd.DataFrame = pd.DataFrame(
    [[1, 2], [3, 4]],
    columns=['a', 'b']
)
df1 = df1[df1.col == 1]
```
Error:
```Expression of type "Series[Dtype]" cannot be assigned to declared type "DataFrame"
  "Series[Dtype]" is incompatible with "DataFrame" Pylance (reportGeneralTypeIssues)
```

If I remove the `pd.DataFrame` type annotation, it works. But this is still significant because it applies to functions too:

```python
def f(df: pd.DataFrame) -> pd.DataFrame:
    return df1[df1.col == 1]
```

Gives the same error.

**Expected behavior**
Pyright should recognise the output as a DataFrame and not give any errors. 

**VS Code extension or command-line**
Pylance 2020.8.1, pyright 1.1.61

**Comment by erictraut** [comment]
Thanks for reporting.

This issue is related to the pandas type stubs that ship with Pylance, so I've transferred this issue to the pylance-release repo, and I'm closing this one.
