### ISSUE TITLE
Empty tuple type changes to Never inside if statement

### ISSUE THREAD

**Issue by vient** [microsoft/pyright#9523]
Code sample in [pyright playground](https://pyright-play.net/?pyrightVersion=1.1.389&pythonVersion=3.13&code=IYJxAIF5wCgSgFAIJYDNyhALgeP5UB7CAfXGQDsMwd87wAHYAZ2aTXABsBTCmTOOAB84AIy18RUuSqYseAMThuYYuGaUAxtzEA6UboDMAVgCcueniasEQA)

```python
arr = ()

if arr:
    for _ in arr:  # error
        pass

if len(arr) > 1:
    for _ in arr:  # error since 1.1.359
        pass
```
both `for _ in arr` lines get error `"Never" is not iterable` - type of `arr` inside if is changed from `tuple[()]` to `Never`. Error goes away if tuple is explicitly typed like `arr: tuple[int, ...] = ()` - pyright correctly deduces that code inside if blocks is not reachable. I would expect pyright to deduce it without explicit tuple typing as well.

**Comment by erictraut** [comment]
Pyright is working as intended here, so I don't consider this a bug.

The type narrowing logic was changed a while back to support empty tuples when performing a truthy or falsy test like in your example. The same is true for the `len(x) > L` type guard pattern. This supports cases where a type is a union of `tuple[()]` and other types. The `tuple[()]` is eliminated leaving any remaining types in the union. If all of the types in the union are eliminated, the result is `Never`.

Pyright doesn't perform reachability analysis for simple truthy or falsy tests unless the target expression is a simple variable whose type is declared. This is for performance reasons, as reachability analysis in the general case proved too expensive, especially in unannotated code. This explains the behavior you're seeing when you add the explicit type declaration for the `arr` variable.
