### ISSUE TITLE
Add support for generic `slice` type arguments in a slice expression

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#9533]
The typeshed definition for `slice` was recently updated to support generics. Pyright doesn't currently supply type arguments for the start, end, and step types when evaluating the type of a literal slice expression.

See [this mypy issue](https://github.com/python/mypy/issues/18225) for details.

**Comment by erictraut** [comment]
@Dr-Irv, this will be included in pyright 1.1.390, which should be released tomorrow.

**Comment by Dr-Irv** [comment]
> [@Dr-Irv](https://github.com/Dr-Irv), this will be included in pyright 1.1.390, which should be released tomorrow.

Thanks.  For our CI purposes, we may have to pin down to 1.1.389, unless you have ideas on how we can support mypy 1.13.0 and pyright 1.1.390 at the same time when doing `assert_type()`.  See my question here:  https://github.com/python/mypy/issues/18225#issuecomment-2512512135

**Comment by jorenham** [comment]
oh nevermind, judging by https://github.com/microsoft/pyright/commit/b0cd5f13b134e9700ccd3586d179897e8bcbcf8a this also required a change in pyright itself

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.390.
