### ISSUE TITLE
Symlinks are not taken into account with "find references"

### ISSUE THREAD

**Issue by agarfield-arine** [microsoft/pyright#9538]
**Describe the bug**
My org uses symlinks to reference shared code that can be imported by multiple python executables. When finding references to a symbol in the shared code I get different results depending on what file I request the reference lookup from.

**Code or Screenshots**
```sh
mkdir -p pyright_issue/shared_lib
cd pyright_issue
mkdir executables
mkdir executables/exe1
mkdir executables/exe2
ln -s $PWD/shared_lib $PWD/executables/exe1
ln -s $PWD/shared_lib $PWD/executables/exe2
echo 'foo = 123' > shared_lib/bar.py
echo 'from shared_lib.bar import foo' > executables/exe1/main.py
echo 'from shared_lib.bar import foo' > executables/exe2/main.py
```

```
$ cd pyright_issue
$ tree
.
├── executables
│   ├── exe1
│   │   ├── main.py
│   │   └── shared_lib -> /abs/path/pyright_issue/shared_lib
│   └── exe2
│       ├── main.py
│       └── shared_lib -> /abs/path/pyright_issue/shared_lib
└── shared_lib
    └── bar.py

7 directories, 3 files
```

When finding references for `foo` in `shared_lib/bar.py` I get:
```
shared_lib/bar.py|1 col 1-4| foo = 123
```

In `executables/exe1/main.py` I get:
```
executables/exe1/main.py|1 col 28-31| from shared_lib.bar import foo
shared_lib/bar.py|1 col 1-4| foo = 123
```

And in `executables/exe2/main.py` I get:
```
executables/exe2/main.py|1 col 28-31| from shared_lib.bar import foo
shared_lib/bar.py|1 col 1-4| foo = 123
```

**VS Code extension or command-line**
I'm using neovim and version 1.1.389 on Python 3.13.0

**Comment by erictraut** [comment]
Thanks for reporting the issue.

The "find references" language service is owned and maintained by the Microsoft Pylance team. 

Could someone from the pylance team please move this feature to the pylance-release project? Thanks!

**Comment by agarfield-arine** [comment]
My fault. I'll just copy it over there.
