### ISSUE TITLE
Variables set in an obviously-nonempty loop should not be considered unbound?

### ISSUE THREAD

**Issue by ANogin** [microsoft/pyright#9549]
**Describe the bug**
When a loop is e.g. over a statically known non-empty list, then the variables set in that loop should not be considered possibly unbound after the loop.

**Code or Screenshots**

```python
for x in [1, 2]:
    y = x+2
print(y)
```

Gets me a `"y" is possibly unbound`

**VS Code extension or command-line**
VSCode Pylance v2024.11.3

**Comment by erictraut** [comment]
Pyright is working as designed here, so this isn't a bug.

The type of expression `[1, 2]` is `list[int]`. Lists are mutable, and the length of a `list` type is not known by a static type analyzer. There have been some discussions on the typing forums about how to extend the type system to support knowledge of iterable lengths, but these haven't progressed very far. 

If you want to write code that type checks, I recommend avoiding the situation where variables are assigned only within a loop and then accessed outside of the loop. Most programming languages don't even allow this for good reason.
