### ISSUE TITLE
Add checks from pyflakes

### ISSUE THREAD

**Issue by tobiasdiez** [microsoft/pyright#955]
**Is your feature request related to a problem? Please describe.**
[Pyflakes](https://github.com/PyCQA/pyflakes) has some checks that are already covered by pyright (such as unused imports), but has a few others that would be a good addition to pyright (future imports, format strings). A list of errors of pyflakes can be found here: https://flake8.pycqa.org/en/latest/user/error-codes.html

**Describe the solution you'd like**
Include all checks from pyflakes.

**Comment by erictraut** [comment]
Can you be more specific? Which diagnostic checks do you think are missing from Pyright?

**Comment by tobiasdiez** [comment]
I think it would be nice if all pyflakes checks are included, since then pyright can serve as a drop-in-replacement for pyflakes. This is especially relevant since pyflakes has some problems to understand typing code (at least currently). 

I'm sorry, but I don't feel familiar enough with neither pyflakes nor pyright to decide which of the checks are already implemented or still missing.

**Comment by erictraut** [comment]
Yeah, I'm not familiar with pyflakes either. I hadn't heard of it before you mentioned it here. Scanning through the list of errors generated by pyflake, I think Pyright already covers most of them. The few exceptions I see are those that require internal (non-type-related) knowledge of specific calls like "format" and "print". Those are outside the scope of pyright. If there are specific features that you'd like to see, feel free to submit them individually. Thanks!
