### ISSUE TITLE
Crash in createSelfType

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pyright#9552]
This was logged in our crash telemetry for Pylance:

TypeError: Cannot read properties of undefined (reading 'node')</br>at node <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L15457'>pyright-internal/src/analyzer/typeEvaluator.ts:15457:28</a></br>at createSelfType <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L20597'>pyright-internal/src/analyzer/typeEvaluator.ts:20597:35</a></br>    at createSpecializedClassType <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L7532'>pyright-internal/src/analyzer/typeEvaluator.ts:7532:35</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeUtils.ts#L765'>pyright-internal/src/analyzer/typeUtils.ts:765:8</a></br>at expandedType <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L4096'>pyright-internal/src/analyzer/typeEvaluator.ts:4096:16</a></br>at expandSubtype <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L4153'>pyright-internal/src/analyzer/typeEvaluator.ts:4153:12</a></br>at mapSubtypesExpandTypeVars <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L7370'>pyright-internal/src/analyzer/typeEvaluator.ts:7370:21</a></br>    at getTypeOfIndexWithBaseType <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L6771'>pyright-internal/src/analyzer/typeEvaluator.ts:6771:32</a></br>at node <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L1124'>pyright-internal/src/analyzer/typeEvaluator.ts:1124:49</a></br>at getTypeOfExpression <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21106'>pyright-internal/src/analyzer/typeEvaluator.ts:21106:15</a></br>at getTypeOfExpressionExpectingType <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L1893'>pyright-internal/src/analyzer/typeEvaluator.ts:1893:31</a></br>at cb <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/common/cancellationUtils.ts#L32'>pyright-internal/src/common/cancellationUtils.ts:32:15</a></br>at invalidateTypeCacheIfCanceled <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L18311'>pyright-internal/src/analyzer/typeEvaluator.ts:18311:15</a></br>at getTypeOfFunctionPredecorated <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L18170'>pyright-internal/src/analyzer/typeEvaluator.ts:18170:27</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/common/timing.ts#L40'>pyright-internal/src/common/timing.ts:40:19</a></br>at getTypeOfFunction <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L411'>pyright-internal/src/analyzer/checker.ts:411:51</a></br>at visitFunction <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L451'>pyright-internal/src/analyzer/parseTreeWalker.ts:451:28</a></br>at visit <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L933'>pyright-internal/src/analyzer/parseTreeWalker.ts:933:20</a></br>at visitNode <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L915'>pyright-internal/src/analyzer/parseTreeWalker.ts:915:36</a></br>at walk <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L284'>pyright-internal/src/analyzer/checker.ts:284:18</a></br>at walk <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L2799'>pyright-internal/src/analyzer/checker.ts:2799:17</a></br>at _walkStatementsAndReportUnreachable <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L293'>pyright-internal/src/analyzer/checker.ts:293:13</a></br>at visitSuite <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L544'>pyright-internal/src/analyzer/parseTreeWalker.ts:544:28</a></br>at visit <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L933'>pyright-internal/src/analyzer/parseTreeWalker.ts:933:20</a></br>at visitNode <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L915'>pyright-internal/src/analyzer/parseTreeWalker.ts:915:36</a></br>at walk <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L284'>pyright-internal/src/analyzer/checker.ts:284:18</a></br>at walk <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L318'>pyright-internal/src/analyzer/checker.ts:318:13</a></br>at visitClass <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L388'>pyright-internal/src/analyzer/parseTreeWalker.ts:388:28</a></br>at visit <a href='https://github.com/microsoft/pyrx/blob/0d9b0607bca54462b0a43640315ee41e29dbe421/packages/pyright/packages/pyright-internal/src/analyzer/parseTreeWalker.ts#L933'>pyright-internal/src/analyzer/parseTreeWalker.ts:933:20</a></br>

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.391.
