### ISSUE TITLE
Configure reporting for top level awaits

### ISSUE THREAD

**Issue by kennyworkman** [microsoft/pyright#9561]
If you have a question about a behavior that you’re seeing in pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**

Would like a configuration option to allow top-level awaits (similar to https://docs.python.org/3/library/ast.html#ast.PyCF_ALLOW_TOP_LEVEL_AWAIT).

**Describe the solution you’d like**
A clear and concise description of the solution you would like to see.

Something like a `reportErrorOnTopLevelAwait` similar to options documented here - https://microsoft.github.io/pyright/#/configuration?id=diagnostic-rules.

**Comment by erictraut** [comment]
Top-level awaits are not allowed in Python (outside of a notebook). Why would you want to allow them?

It's unlikely that we'd add a configuration knob for something like this. There isn't precedent for enabling or disabling syntax rules by pyright configuration.

**Comment by kennyworkman** [comment]
Apologies, missed the notification here. 

We are building a notebook-like programming + visualization tool ([ex](https://wiki.latch.bio/plots/overview)). For similar reasons as traditional notebooks, the cell code is assumed to be within an implicit async function. Each notebook cell is transformed into a coroutine and executed on an event loop. 

We use the pyright lsp to aid code writing within the browser and it flags top level awaits. Will probably fork if this is too niche.

**Comment by erictraut** [comment]
Pyright is focused on type checking. It does have some basic LSP functionality, but that's not its focus. In particular, pyright doesn't have support for notebooks. Pylance (Microsoft's Python language server) adds support for notebooks on top of pyright, but pylance is closed source. The pylance team added a special set of flags internal to the pyright source code to modify its behavior when in "ipython" mode. This flag isn't exposed externally, and it's unlikely that we'd do this given the focus of pyright. Forking is an option.

When you say "we use the pyright lsp", who is "we"? Is this a personal project, or are you doing this for an employer?

**Comment by kennyworkman** [comment]
I am an engineer at a company building data analysis products for biotech teams and I am trying to use this for a scientific notebook product.

I didn't realize that the basic LSP functionality was not a main focus of the project and have found eg. autocompletion / diagnostic messages quite comparable in performance/quality to what I guess we would call "full fledged LSPs". Will look for some work arounds. Thank you for the quick responses.
