### ISSUE TITLE
Two diagnostics issued for invalid type in exception handler where one would suffice

### ISSUE THREAD

**Issue by AlexWaygood** [microsoft/pyright#9562]
**Describe the bug**
Pyright issues a pair of diagnostics on an invalid type in an exception handler. I can see where the first one comes from, but it seems somewhat confusing, and the second one is much better. I think it would be better just to emit the second one, not the first:

```py
try:
    pass
except 3:
    pass
```

Pyright says:

```
"Literal[3]" is not iterable
  "__iter__" method not defined  (reportGeneralTypeIssues)
"Literal[3]" is not a valid exception class  (reportGeneralTypeIssues)
```

I assume pyright is trying to iterate over `3` here because it's valid to catch a tuple of exception classes in an exception handler. However, arbitrary iterables are _not_ allowed in exception handlers (which pyright seems to recognise -- it complains if you try to catch `[ValueError]` in an exception handler), so even if you understand what pyright is talking about here, the specific complaint about an `__iter__` method missing seems perplexing.

https://pyright-play.net/?strict=true&code=C4JwngXAUABHMAcCGBnFUCmAPAxhhwMAzNPIqulKJLPMmprvoQNoBqSANgK4YCiIEAHsQAXVJ0KUIA

For comparison, mypy's complaint on this snippet is

```
main.py:3: error: Exception type must be derived from BaseException (or be a tuple of exception classes)  [misc]
```

And pyre's is

```
 3:7: Invalid except clause [66]: Exception handler type annotation `typing_extensions.Literal[3]` must extend BaseException.
```

(I discovered this issue as a result of comparing the error messages of other type checkers -- I'm working on implementing this check in red-knot!)

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.391.
