### ISSUE TITLE
Type narrowing for dictionary whose keys are Enum members

### ISSUE THREAD

**Issue by cdbrendel** [microsoft/pyright#9571]
Apologies in advance if this issue duplicates any of the current issues with type narrowing or Literal types--I'm not versed enough to know if this is redundant.

I noticed that Pyright doesn't seem to apply type narrowing logic to the elements of an explicitly-typehinted dictionary whose keys are a member of some Enum and whose values can be of more than one type. Minimal example:

```python
from enum import Enum

def function_wanting_str(_: str) -> None:
    pass

class Foo(Enum):
    A = 1
    B = 2
    C = 3

dict_using_foo: dict[Foo, str | None] = {
    Foo.A: "test1",
    Foo.B: None,
    Foo.C: "test2"
}

assert isinstance(dict_using_foo[Foo.A], str)

function_wanting_str(dict_using_foo[Foo.A])
```

Pyright produces the following error for the last line:

```
  /tmp/py/test.py:18:22 - error: Argument of type "str | None" cannot be assigned to parameter "_" of type "str" in function "function_wanting_str"
    Type "str | None" is not assignable to type "str"
      "None" is not assignable to "str" (reportArgumentType)
```

When I remove the explicit type annotation for `dict_using_foo`, the error disappears, but this seems to be due to pyright inferring that `dict_using_foo` is type  `dict[Foo, Unknown]`, 

Thanks in advance for your help and as always for your great work!

(pyright 1.1.389, hinting for python 3.13)

**Comment by erictraut** [comment]
Pyright is working as designed here, so this isn't a bug.

Type narrowing of index expressions is limited to cases where the subscript is a single integer or string literal. You are using a more complex subscript here (`Foo.A`), so type narrowing isn't applied in this case. For more details, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-narrowing).

For more complex subscripts, the recommended approach is to store the result of the index operation in a temporary variable and apply conditional checks or asserts on that variable. 

```python
temp = dict_using_foo[Foo.A]
assert isinstance(temp, str)

function_wanting_str(temp)
```

**Comment by cdbrendel** [comment]
Ah, thanks @erictraut, that makes sense. I noticed the temporary variable approach resolved the issue but was hoping to avoid that strategy. Thanks for the quick reply!
