### ISSUE TITLE
Improve Union Typing support

### ISSUE THREAD

**Issue by jamierpond** [microsoft/pyright#9575]
If you have a question about a behavior that you’re seeing in pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem.

**Describe the solution you’d like**
A clear and concise description of the solution you would like to see.

======================================================================================
It would be really fun to be able to make these types of assertions and for pyright to understand them :) 
```py
from typing import get_args

def fn_name[T]:
    assert T in get_args(str | int)
    foo: T = int(5)     ■■ Type "int" is not assignable to declared type "T@fn_name"    Type "int" is not assignable to type "T@fn_name...
    return foo
```

obviously this is a nonsense example, but you get the idea.

**Comment by erictraut** [comment]
This code doesn't make sense to me. I'm not sure what you're trying to do here. You appear to be using a union expression (`str | int`) outside of a type expression. Type expressions have well-defined meanings in the Python typing spec, but when you use similar-looking expressions outside of the context of a type expression, you are now outside the bounds of the typing spec.

If you would like to propose new features in the Python type system, the [Python typing forum](https://discuss.python.org/c/typing/32) is a good place to post your ideas.
