### ISSUE TITLE
<variable> is declared as Final error on relative import

### ISSUE THREAD

**Issue by bzoracler** [microsoft/pyright#9584]
**Describe the bug**

A relative import `from .abc import xyz` in a stub package's `__init__.pyi` triggers a pyright error if there is a module-level variable `abc` which is annotated as `abc: typing.Final[<type>]`.

This was discovered during a typeshed PR to add new stubs for a package.

**Code or Screenshots**

See https://github.com/python/typeshed/pull/13248/files:

```python
# __init__.pyi
...
from .watch import Watch  # "watch" is declared as Final and cannot be reassigned (reportGeneralTypeIssues)
...
watch: Final[Watch]
```

**Comment by erictraut** [comment]
Pyright's behavior here is intended here, and I don't consider this a bug.

Within an `__init__` module, a relative import will implicitly assign a value to the name of the module being imported — in this case `watch`. If you declare the type of this symbol to be `Final`, its value can be written only once in the module, as per the typing spec.

**Comment by bzoracler** [comment]
Ah, I wasn't aware of the behaviour `from .watch` assigning a variable named `watch`. Thanks!

The other type-checkers on typeshed (mypy, pytype) which I've run this on didn't seem to pick this `Final` assignment up.
