### ISSUE TITLE
Contradictory errors for ParamSpec defaults

### ISSUE THREAD

**Issue by diceroll123** [microsoft/pyright#9586]
I see contradicting errors for

```py
type AliasTuple[**P = (int, str)] = Callable[P, int]
```

The contradicting errors:
```
Tuple expression not allowed in type expression
Expected ellipsis, a tuple expression, or ParamSpec for default value of ParamSpec
```

Playground link: https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAKAhiERAMoICmAxgFCiRQ1gA2rtMSYKAzgHREARjUzZc%2BAMJF2wjnTrxqUAIKskRXgBUArgg4BtAFRGCUALxQAFKhgAaKLxggAlAF0LUabKGGCD2zc6AGJYAAsqKCoQcBBeKEZoYTAAN0iSSJYUZyIAEyQaGFw4fhDMfCEwGDCofN4ZVjAAd3iiFFyogA9qQtbYPQ4uhBAqXl5uFDKkfCbcAGtW-BAdbKwqAJQoNrhmTSp%2BcMiAIhYYziOoJqIdotqwcKR4x8vpmqIodRhomQ-H-GqwDo0GFSnQACJUYBEHSsGBmSzEUgUHpWI4QqEwuFHBy5SHQ2HmKxOEAbGAuFxQKChcYQJCsEhQIQ6fD5YDAaJUbKYMY6SIREYOHBjJC%2BOAAfjoQA

**Comment by erictraut** [comment]
Pyright is working as intended here. Both of these error messages apply, and they are not contradictory. One is a syntax error message, the other is a semantic error. If you fix the issue, both errors will go away.

**Comment by JelleZijlstra** [comment]
The second error message is incorrect, because it says a "tuple expression" is among the allowed options. In fact, pyright allows only a list expression here, so that's what that error message should say.

**Comment by billfelix** [comment]
收到，谢谢您的来信。我将及时回复您！ 
祝好！
