### ISSUE TITLE
Support for Final in typing_extensions

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#96]
The typing_extensions module defines a "Final" type that can be used to prevent subsequent assignments.

See [https://mypy.readthedocs.io/en/latest/final_attrs.html from typing_extensions](https://mypy.readthedocs.io/en/latest/final_attrs.html from typing_extensions).

**Comment by erictraut** [comment]
After looking at this more, I'm inclined not to support it at this time. I don't think it's very well conceived.

**Comment by Porges** [comment]
Hmm, `Final` appears in `typing.pyi` as supplied in the pyright extension, but it doesn't work. Perhaps it should be removed?

**Comment by erictraut** [comment]
Now that this is part of the python standard (as of 3.8), I think it makes sense to add support for it. Reopening.

**Comment by erictraut** [comment]
Boy, the specification of the "Final" annotation is full of inconsistencies. I wish I could go back in time and improve the proposal before it made its way into the Python spec. :(

That said, I added support for it in Pyright (with some semi-gross hacks and assumptions). This will be in the next release.

**Comment by erictraut** [comment]
This is now implemented in 1.1.20, which I just published.

**Comment by Porges** [comment]
Thanks!
