### ISSUE TITLE
Checks for method overrides in subclasses do not enforce exact type matches for parameters

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#960]
In #867, I decided to loosen the check for method overrides — both in terms of param types and the addition of parameters with default values. This has proven problematic because mypy and stubtest already enforce the stricter version of this test, so pyright is producing results that are not consistent with mypy.

I think we have several choices:
1. Undo the change in #867 and go back to a stricter test in all cases.
2. Limit the change for stubs only.
3. Provide a way for users to choose between a looser or stricter interpretation.

For now, I'm leaning toward option 1 for consistency and simplicity.

@russelldavis, since you filed issue #867, I'm interested in your input.

@jakebailey, interested in your thoughts as well.

**Comment by jakebailey** [comment]
Do you have some examples where our behavior is breaking things? I'm assuming you're finding this via submissions to typeshed. I'm curious as to whether or not this is configurable in mypy as well, as I think mypy has some sort of strictness check.

I'm still of the mind that the change made was correct and there are situations where things are still substitutable, so I would wonder if mypy has made a different decision for some other reason instead, or if it's just not been considered and could be changed there.

Is (3) any different than controlling the diagnostic itself? e.g., if we made it complain in strict mode only and allowed other forms in basic (via a diagnostic flag), is that enough? Or is this behavior a detail of another generic diagnostic?

**Comment by erictraut** [comment]
This is enforced for all stubs in typeshed. I've been submitting a bunch of changes to typeshed recently, and I keep getting bitten by this because Pyright isn't reporting an error, but mypy and stubtest reject the stub because it "violates this Liskov substitution principle".

Disabling the diagnostic in its entirety would suppress reporting of even egregious signature mismatches. Option (3) would allow users to keep the check enabled but use a "looser" form that allows for additional parameters (with default values) and narrower parameter types.

**Comment by russelldavis** [comment]
Can you post an example where mypy is stricter than pyright? I tried my example from #867 and mypy doesn't emit any errors: https://mypy-play.net/?mypy=latest&python=3.8&flags=strict&gist=02fa921b67483c651a2bf62d75da38d8

**Comment by jakebailey** [comment]
Ah, what I meant to ask was if this specific case (hey, this override violates Liskov) was its own diagnostic such that it could be toggled, but it sounds like it's being merged with others. I was just imagining a diagnostic that reports "this violates some stricter view of Liskov" such that it could be toggled distinctly from "this definitely violates Liskov, even in some looser view".

It could also be that there are some cases mypy accepts that we don't, and maybe the change overdid it? (e.g. the above) Or, mypy is inconsistent in how it's accepting or not accepting things and the fact that it's reporting things as violations is the bug.

**Comment by erictraut** [comment]
False alarm. There was actually a bug in the existing Pyright code where its logic for comparing parameter types was reversed. It was checking for a wider type when it should have been checking for a narrower type. This explains why mypy was generating different results.

Apologies for wasting your time.
