### ISSUE TITLE
Generic function for numpy array operation doesn't work

### ISSUE THREAD

**Issue by colinfang** [microsoft/pyright#9601]
Using python 3.12 and latest pylance 2024.12.1 from VSCode

```
import numpy as np
import numpy.typing as npt

def test1[T: npt.NDArray[np.float64]](x: T) -> T: # type error
    return x + x

# Type "NDArray[floating[Any]]" is not assignable to return type "T@test1"
# Type "NDArray[floating[Any]]" is not assignable to type "T@test1"Pylance[reportReturnType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportReturnType)


def test2(x: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: # works
    return x + x
```

**Comment by erictraut** [comment]
Pyright is working correctly here and in accordance with the typing spec, so this isn't a bug.

The `__add__` method for `NDArray` does not return the same type as its operands. It is defined to always return an `NDArray` object even if the operands are subclasses of `NDArray`. That means the results are not assignable to `T` in this case.
