### ISSUE TITLE
sorted() built-in does not check if tuple items are comparable

### ISSUE THREAD

**Issue by jcmacdon** [microsoft/pyright#9628]
**Describe the bug**
When using the built-in `sorted()`, pyright does not check if the iterable contains tuples with items that are not comparable.

**Code or Screenshots**
This example will typecheck correctly but will raise an error when run:
```python
items: list[tuple[int, object]] = [(1, object()), (1, object())]
sorted(items)
```
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'object' and 'object'
```

**VS Code extension or command-line**
pyright CLI version 1.1.391

**Comment by erictraut** [comment]
Pyright (and type checkers in general) don't have special-case knowledge about specific function calls. They base their analysis on provided type information. In this case, the type definition comes from the community-maintained typeshed project. The type definition for `sorted` can be found [here](https://github.com/python/typeshed/blob/e5c531811536a85c8838ef0862eeb19256ecaf90/stdlib/builtins.pyi#L1763).

Based on the type definition provided, pyright's behavior is correct, so this isn't a bug.

**Comment by jcmacdon** [comment]
Makes sense, I'll report this to typeshed instead, thanks!
