### ISSUE TITLE
`dict.get` can't be used as a key argument

### ISSUE THREAD

**Issue by Don-Cheadle** [microsoft/pyright#9634]
**Code or Screenshots**

```python
foo = list('abc')
indicies = {k: i for i, k in enumerate(foo)}
foo.sort(key=indicies.get)  # Gives error
```

**VS Code extension or command-line**
vscode: pylance 2024.12.1, python 3.13.1

**Comment by erictraut** [comment]
Pyright's behavior is correct here. The type definition for `dict.get` is not type compatible with the parameter type required for the `key` parameter. 

Not surprisingly, mypy generates the same error here. If you think that the type definitions for `dict.get` or `sort` are in error, please report the issue to the [typeshed project](https://github.com/python/typeshed), which provides type definitions for all stdlib functionality.
