### ISSUE TITLE
Auto import behavior clarification

### ISSUE THREAD

**Issue by f279801** [microsoft/pyright#967]
Hi,

I observed below behavior when using pyright with [lsp-pyright](https://github.com/emacs-lsp/lsp-pyright):
A module is on shown up in the completion list for a python if and only if it has been already import by at least one other file in the same workspace. That's being said:

- if I create an empty project
- and create a new file file for it
- Auto import for all modules in this file will not work.
- But if I make another file, auto import for some modules in this file will work here if they already been imported by previous file.

Would you mind to confirm above behavior or we actually have a bug here. Besides, if it is the actual behavior then what is the reason behind it? To reduce the completion list and improve the speed?

/f

**Comment by erictraut** [comment]
The current behavior is working as it was designed, but many other users have also expressed a desire for it to work differently, and it's currently be reworked in the context of Pylance.

The current behavior was copied from the TypeScript language server which limits its auto-imports to only those symbols and modules that have been imported somewhere else in the program.

The challenge in providing importable symbols and modules from all installed packages as auto-import suggestions is that it requires a massive amount of runtime processing if your Python environment has a large number of packages installed. Suggesting auto-imports for all installed packages can also result in an overwhelming number of suggestions, many of which are duplicates.

The solution we're pursuing involves a lightweight indexer to collect all of the module-level symbols for all installed packages. Depending on how many packages you have installed, this can take several seconds to minutes when VS Code starts. So even though it's "lightweight", it's still far from free.

We're still working on the problem of filtering suggestions so you aren't overwhelmed by a large number of auto-imports.

**Comment by f279801** [comment]
Thank @erictraut a lots for your clarification. It makes sense to me.
Then I guess we're waiting for that feature to be available.

In the meanwhile, do you know if we provide any kind of quickfix suggestion? e.g: 'Import <module>' via code action.

**Comment by erictraut** [comment]
A quickfix requires the same logic as the completion suggestions.

**Comment by f279801** [comment]
OK, I though that it would be a bit more lightweight since we are searching for an exact match.
Besides, the code action can be processed in the background and we have the alternative to only notify the client side about the suggestion whenever we finished the calculation.

**Comment by gsingh93** [comment]
> The solution we're pursuing involves a lightweight indexer to collect all of the module-level symbols for all installed packages.

Did this ever get implemented in pyright? Or was this only for pylance?
