### ISSUE TITLE
Question about bounded TypeVar.

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#975]
I'm not sure if the title correctly described what I need, feel free to change it :smile: 

In TypeScript, I can have some constraints like this:
```typescript
class BaseColumn {
  value: any
}

class StrColumn extends BaseColumn {
  value: string
}

function getValue<T extends BaseColumn>(column: T): T['value'] {
  return // ...
}

const v = getValue(new StrColumn()) // type of v is string
```
To be specific, I need to define a return type that inferred from a parameter's property type.

I tried to implement this constrains in python, here's what I tried:

```python
from typing import Any, TypeVar

class BaseColumn:
    value: Any
    value2 = Any

class StrColumn(BaseColumn):
    value: str
    value2 = str

_T = TypeVar('_T', bound=BaseColumn)

def getValue(column: _T) -> _T.value:
    ...

def getValue2(column: _T) -> _T.value2:
    ...

v = getValue(StrColumn()) # type of v is Any, what I need is str

v2 = getValue2(StrColumn()) # type of v2 is also Any
```
As you can see, Pyright only infers the property type according to the bounded base class, not the parameter's type.

My question is, Is this approach possible using the current version of Pyright? If not, can we change this into a feature request? 

Thank you very much!

**Comment by erictraut** [comment]
No, it doesn't work this way. The right way to do this is to make BaseColumn a generic class.

```
from typing import Any, Generic, Type, TypeVar

_T = TypeVar("_T")

class BaseColumn(Generic[_T]):
    value: _T

class StrColumn(BaseColumn[str]):
    pass

def getValue(column: BaseColumn[_T]) -> _T:
    ...

def getValue2(column: BaseColumn[_T]) -> Type[_T]:
    ...

v = getValue(StrColumn())
v2 = getValue2(StrColumn())
```

**Comment by giyyapan** [comment]
Ah, I see.

I'll give it a try. Thank you, Eric!

**Comment by erictraut** [comment]
Incidentally, I would recommend using the same pattern in TypeScript. I think it's easier to read, but maybe that's just me.

```
class BaseColumn<T> {
    value: T;
}

class StrColumn extends BaseColumn<string> {
}

function getValue<T>(column: BaseColumn<T>): T {
  return // ...
}

const v = getValue(new StrColumn()) // type of v is string
```

**Comment by giyyapan** [comment]
The reason I use the grammar above is because it's not always the BaseClass vs SubClass pattern, but I get your point, it's more clear in cases like this, indeed.
