### ISSUE TITLE
pyright could not find site-packages

### ISSUE THREAD

**Issue by OnePieceJoker** [Microsoft/pyright#98]
**Describe the bug**
I create a pyrightconfig.json file, but it still couldn't find site-packages

**To Reproduce**
Here is my pyrightconfig.json:
```
{
    "venvPath": "E:\\Envs",
    "venv": "\\venv"
}
```
Note: my virtual environment directory is in "E:\\Envs" and my virtual environment is "venv".

**To Reproduce**
window10
pyright 1.0.19
python 3.7.1

**Expected behavior**
can find the site-packages directory in the virtual environment.

**Screenshots or Code**
```
{
    "venvPath": "E:\\Envs",
    "venv": "\\venv"
}
```

> pyright output info:

![image](https://user-images.githubusercontent.com/25676220/56858575-bd242780-69ae-11e9-8927-8e54a75f61d6.png)

**VS Code extension or command-line**
VS code extension 1.0.19

**Additional context**
Possibly related to #54,

**Comment by erictraut** [comment]
What is the directory structure within your virtual environment directory? In other words, what directories are under `E:\Envs\venv`? Is there a `lib` or `Lib` directory in it? And is there a `site-packages` directory within that?

Also, what file system is the `E:` drive formatted with? Is it NTFS or a different file system that uses case-sensitive pathnames?

**Comment by OnePieceJoker** [comment]
This is my venv directory:
```
E:\Envs\venv> dir

<DIR> Include
<DIR> Lib
<DIR> Scripts
<DIR> tcl
LICENSE.txt
```
and site-packages exist in the lib directory：
```
E:\Envs\venv\Lib>dir
<DIR> site-packages
some python files...
```
`E:` drive is NTFS file system

The pyright output shows that only the Lib directory is queried and cannot be accessed into the site-packages directory.I don't know why?

**Comment by OnePieceJoker** [comment]
I have solved my problem. The cause of the problem seems to be the configuration of the setting.json of the vs code, but I corrected it back, and now pyright can resolve to the site-packages directory. 
Thank you for your answer.
