### ISSUE TITLE
TypedDicts should be accepted where dicts are accepted

### ISSUE THREAD

**Issue by AGiantSquid** [microsoft/pyright#997]
TypedDicts are dicts that have their keys pre-defined. Because they are still dicts, it would be nice if they could be feed to functions that expect dicts as the argument type.

Consider the following:
```python
from typing import TypedDict


class DemoType(TypedDict):
    float_field: float


def dict_func(arg: dict):
    # do work
    pass


def call_dict_func(arg: DemoType):
    return dict_func(arg)  # this errors
```

We see a function `dict_func` that can do some task with dictionaries. 

We also have `call_dict_func`, which explicitly requires a `DemoType` (which is a `TypedDict`). 

The function `call_dict_func` needs to call `dict_func`. 

It makes sense to type hint the argument to `dict_func` as a `dict`, as the function requires a dict and we want this requirement to be made explicit. It also makes sense to allow `call_dict_func` to specify the `TypedDict` it requires. 

We get an error when we try to call `dict_func` with a `DemoType` as it is not a `dict`.

I think this would make more sense if it did not error, as TypedDicts are just dicts with defined keys. I imagine many devs will need to modify their TypedDicts with dict helper functions, and will encounter this type error.

VSCode Snippet:

![image](https://user-images.githubusercontent.com/26531374/92071889-c375a100-ed64-11ea-9cb3-1c604033520e.png)

**Comment by erictraut** [comment]
Yeah, I'm sympathetic to your viewpoint, but unfortunately, that's not how TypedDicts were defined.

[PEP 589](https://www.python.org/dev/peps/pep-0589/#type-consistency) is very clear on this point:
>A TypedDict isn't consistent with any Dict[...] type, since dictionary types allow destructive operations, including clear(). They also allow arbitrary keys to be set, which would compromise type safety.

On the bright side, you can pass a TypedDict to a function that accepts a `Mapping`.
>... any TypedDict type is consistent with Mapping[str, object].

BTW, I love your GitHub account name. Well done!
