### ISSUE TITLE
Support zope.interface

### ISSUE THREAD

**Issue by mithrandi** [microsoft/pyright#999]
Something like https://github.com/Shoobx/mypy-zope

**Comment by davidatbu** [comment]
Have a look at #637 . In essence, if something is not expressable in a stub file or with inline annotations according to the currently accepted list of PEPs, (ie, something needs a plugin), Pyright will not be supporting it "in the near future", if at all.

**Comment by mithrandi** [comment]
zope.interface provides nominal typing rather than structural typing (despite some confused language in PEP 544 to the contrary) so a `z.i.Interface` is more like an ABC than a `Protocol`. Anyhow, thanks for the reply!
